### ISSUE TITLE
Customizer doesn't give a live preview?

### ISSUE THREAD

**Issue by atlanteavila** [reduxframework/redux-framework#1021]
Hi, so when I go to the customize section and see the live preview of the site, I change the color for the header div but it doesn't show the change on the page (I added styles to my header section with the variables from redux' framework as the background color). But if I refresh the page, the color that I chose is now visible in the header div. Am I doing something wrong? I thought by adding the styles in the header section, it would allow me to see the changes live in the customizer.

Please help and let me know if I'm missing a step. Here's the code in the header section.

```
<style type="text/css">
.hello{}
.navbar{background: <?php echo $saintly_opts['header-color']; ?>}

</style>
```

here's the redux defined field: 

```
array(
    'id'       => 'header-color',
        'type'     => 'color',
    'title'    => __('Header Color', 'redux-framework-demo'), 
    'subtitle' => __('Pick a background color for the theme header(default: #fff).', 'redux-framework-demo'),
    'default'  => '#FFFFFF',
    'validate' => 'color',
),
```

**Comment by uzzaldey** [comment]
thanks for your Redux tutorial ( use of global variable to publish the content ).

**Comment by dovy** [comment]
@uzzaldey You're welcome. Please don't piggyback tickets that were last updated in 2014. Make new ones or visit us on Slack. http://slack.redux.io
