### ISSUE TITLE
Custom Panel CSS doesn't append

### ISSUE THREAD

**Issue by Dvaeer** [reduxframework/redux-framework#1027]
I'm trying to append custom panel CSS as in the instructions here: http://docs.reduxframework.com/redux-framework/advanced/custom-panel-css/ 

But my custom CSS file doesn't get appended.

My code is:

``` php
function addPanelCSS() {
        wp_register_style('
            redux-custom-css',
            'http://mywebsite.com/option-panel.css',
            array('redux-css'),
            time(),
            'all'
            );
        wp_enqueue_style('redux-custom-css');
    }
    add_action( 'redux/page/redux_demo/enqueue', 'addPanelCSS' );
```

I noticed that in the source code the redux stylesheet id is _redux-css-css_ (see below):

``` html
<link rel='stylesheet' id='redux-css-css'  href='http://mywebsite.com/wp-content/themes/mytheme/options/ReduxCore/assets/css/redux.css' type='text/css' media='all' /
```

Not sure if this is relevant, but in my options-config file I tried changing this bit:

``` php
array('redux-css'),
```

into this:

``` php
array('redux-css-css'),
```

but that didn't help.

My opt_name is redux_demo, so that seems fine. What else could I try?

Thanks

**Comment by mrgurdeep** [comment]
@Daveer then how did it work for you ? Would you mind sharing it ?
