### ISSUE TITLE
Forbidden Error; You don't have permission to access /wp-admin/options.php

### ISSUE THREAD

**Issue by iwebsource** [reduxframework/redux-framework#1040]
Hi guys.
I just installed the latest Redux Framework 3.2.0 on a new wordpress installation.
Installed and activated the following theme; Showstrap 3.2.3.

In "Sample Options", anytime i 'Save Changes" I get the following error:

Forbidden
You don't have permission to access /wp-admin/options.php on this server.
Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request.

No other plugins are installed and I can't seem to figure this issue out.
Does anyone know what might be going on here, or has any idea what might be causing this problem?

Also, this is a cpanel server I run.

Thanks guys,

**Comment by MarketingIgniter** [comment]
I have encoutered the same issue on my WAMP server. How do you repair this issue using WAMP?Server
