### ISSUE TITLE
Redux + WPML?

### ISSUE THREAD

**Issue by ghost** [reduxframework/redux-framework#1064]
Hi,

I use Redux on a multilingual site to create a theme options page which includes several text fields. Is there a way to manage the translation of those strings with WPML?

Thanks,
pdme

**Comment by zindexsolutions** [comment]
HI ,
we follow all steps given in this link https://docs.reduxframework.com/core/advanced/wpml-integration/ but still we are not success.
Please check out wpml-config.xml file and config file of Redux in attached file
![screenshot 2015-12-28 18 59 50](https://cloud.githubusercontent.com/assets/16116433/12019372/7915b794-ad95-11e5-82ca-295761adf594.png)
![screenshot 2015-12-28 19 04 03](https://cloud.githubusercontent.com/assets/16116433/12019398/c94cb640-ad95-11e5-824b-d123f154faf9.png)

let us know what we missing.. 
Thanks 
Yuvraj Khavad

**Comment by jackbui2014** [comment]
I also have this issue.

**Comment by jackbui2014** [comment]
Please let me know if anyone have an answer for this problem.

**Comment by anikitas** [comment]
Hello,

You shouldn't write on closed tickets, probably a new issue would be better.

WPML needs the admin strings always in English. So when you use WPML you always need to write the strings in your Theme Options panel in English.

Then you can translate them via WPML from: WPML - String Translation
Select you domain under "Select strings within domain"  and translate as any other WPML string.
The text domain for admin strings always start with admin_texts_ + your opt_name in Redux.

If you need more info i would suggest to open a new topic.

I hope it helps!

**Comment by zindexsolutions** [comment]
Hi @anikitas 
Thanks for replay, Starting new topic is good idea.

**Comment by jackbui2014** [comment]
I created a new topic here: https://github.com/reduxframework/redux-framework/issues/2780
Please help me to solve it.
Thanks
