### ISSUE TITLE
Using Bedrock, Redux cannot find it's options URL

### ISSUE THREAD

**Issue by BrandonShutter** [reduxframework/redux-framework#1075]
Hey.  Using https://github.com/roots/bedrock your framework is dropping the ball.  

The exact error I'm getting is running a local wamp stack - and I believe I have figured out the error, but not the fix.

On line 4-6 of redux/options/defaults.php you have the following code:

`// Windows-proof constants: replace backward by forward slashes - thanks to: https://github.com/peterbouwmeester
    $fslashed_dir = trailingslashit(str_replace('\\','/', dirname(__FILE__)));
    $fslashed_abs = trailingslashit(str_replace('\\','/', ABSPATH));`

This is causing the a 403 error in console trying to find the files needed for admin styling and interaction. 

http://shutter.dev/wp/C:/www/shutter/web/app/themes/lens/wpgrade-core/vendor/redux2/options/fields/checkbox_hide_below/field_checkbox_hide_below.js

That path should be 

http://shutter.dev/web/app/themes/lens/wpgrade-core/vendor/redux2/options/fields/checkbox_hide_below/field_checkbox_hide_below.js

Note the missing /wp/C:/www/shutter - which shouldn't be needed or called at all.

My web directory lives in C:/www/shutter/web

**Comment by nhanledev** [comment]
I also encountered this problem in the latest release of Redux Framework: 3.6.11
