### ISSUE TITLE
NOT AN ISSUE: Help with Redux Menu Position

### ISSUE THREAD

**Issue by vmodha** [reduxframework/redux-framework#1118]
I cant seem to find which argument within the redux framework allows me to choose the position of the menu item?

I've looked through the documentation but didnt run into anything:
http://docs.reduxframework.com/redux-framework/arguments/getting-started-with-arguments/

I saw bug fix note in a previous release that confirmed you'd set the menu position to 0 to avoid conflicts, if you could let me know how I could change it that would be great.

I would like my menu underneath 'POSTS'.

Thank you

**Comment by rasel-js** [comment]
This is perfectly working. Thank you very much  ( kprovance )
