### ISSUE TITLE
Fatal error with apache_get_modules in nginx server

### ISSUE THREAD

**Issue by ghost** [reduxframework/redux-framework#1128]
Redux Version: 3.2.3.3
WordPress Version: WordPress 3.9
Developer Mode: No

I'm getting a fatal error on a fresh WordPress install with a fresh copy of Redux:

**Fatal error:** Call to undefined function apache_get_modules() in framework.php on line 394

I'm using nginx as my server for my WordPress site, so my first guess is that that's the problem. Not everyone use Apache for their servers. Maybe a simple `if ( function_exists( 'apache_get_modules' ) )` should do the trick

**Comment by chisumo2016** [comment]
Hi 

Quick question where should I press this code ?
if ( function_exists( 'apache_get_modules' ) )  as u said?
