### ISSUE TITLE
CodeStyling Localization Plugin wrong textdomain

### ISSUE THREAD

**Issue by anikitas** [reduxframework/redux-framework#1141]
Hello,
I have Redux Framework embeded in my Theme.
Redux Core Path: /includes/framework

When using CodeStyling Localization Plugin to search for my translation texts, it recognizes Redux Framework as textdomain instead of my Theme.

Have you seen such problem, do you know how to overcome this issue?
I use load_theme_textdomain in after_setup_theme action.

Thanks in advance!

**Comment by goranefbl** [comment]
How did you fix this issue ?

Having same.

**Comment by dovy** [comment]
Umm, that's not something we can control. You'd need to talk to their developers.

**Comment by dovy** [comment]
Plus CodeStyling Localization Plugin hasn't been updated in 2 years...

**Comment by goranefbl** [comment]
np, thanks for reply dovy.

**Comment by dovy** [comment]
:)  You're welcome. Best of luck!

**Comment by anikitas** [comment]
Sorry for the delay guys!
I translate the Theme via the Child Theme instead of the parent Theme with this plugin.
So problem solved, and also Child Theme is better if you update the Theme.

All translations stick to the Child Theme :)
