### ISSUE TITLE
Live preview is not working when 'Compiler' is used to add css dynamically to a flle.

### ISSUE THREAD

**Issue by sunny04** [reduxframework/redux-framework#1176]
Hello,

I've been trying to use the 'compiler' functionality of Redux for a field in the Theme Customizer, which works fine except that the changes don't show in the Live preview.
I've tested the same options by using the 'output' functionality for a field in Customizer, 
which works perfectly with changes showing up in the live preview. I've also tested the same field by using 'compiler' in the 'panel'.
So I believe the problem is only when the 'compiler' is pared with Customizer. Can you please confirm if this is an issue?

Really appreciate all the support you've provided, and for creating this framework.

Thanks and regards.

**Comment by QammarZaman** [comment]
hi there is anyone who can help me to integrate a compiler
my redux config file is placed in framework/redux-config.php
I'm placing the compiler function and filter in this file but I can't get the output
my style.css is placed in root of my theme
