### ISSUE TITLE
Custom font-weights for custom font

### ISSUE THREAD

**Issue by pnpetroff** [reduxframework/redux-framework#1227]
Hi, me again. Some trobule with typography field here, not sure if bug or something in my head is bugged. I'm using the latest 3.2.9.2 version  and inserting custom font.

This is the CSS code:

```
@font-face {
  font-family: "Apercu";
  src: url("fonts/Apercu_Regular.otf") format("opentype");
}

@font-face {
font-family: "Apercu";
  src: url("fonts/Apercu_Light.otf") format("opentype");
  font-weight: 300;
}
```

This is the typography field code:

```
array(
                    'id'          => 'header-font',
                    'type'        => 'typography',
                    'title'       => __('Headers Font', THEMENAME),
                    'google'      => true,
                    'fonts'       => array(
                            'Apercu, sans-serif' => 'Apercu'
                        ),
                    'font-size'   => false,
                    'font-style'  => false,
                    'font-weight' => true,
                    'line-height' => false,
                    'text-align'  => false,
                    'font-backup' => true,
                    'output'      => array('h1', 'h2', 'h3', 'h4', 'h5', 'h6', '.h1', '.h2', '.h3', '.h4', '.h5', '.h6', 'input', 'textarea', '.caption-title' ),
                    'units'       =>'px',
                    'default'     => array(
                        'color'       => '#000',
                        'font-weight'  => '300',
                        'font-family' => 'Roboto Slab',
                        'google'      => true
                        ),
                    )
```

However the field looks like this:

![image](https://cloud.githubusercontent.com/assets/1108563/3005963/8ef0dc8c-ddfe-11e3-902f-2db19d842af9.png)

This dropdown menu seems to me something like a default one. It has weight AND style (I've set 'font-style'  => false). How can I create a dropdown menu that will include custom options  (in my case - Regular (400) and 300)?

**Comment by yderindere** [comment]
Hi @pe6o, Could you find any solution about that?

**Comment by steve231293** [comment]
Hello @kprovance ,
Could you please add WP Hook to change default_font_weights var? Then I can add more weights for my custom fonts.
![Screenshot at Sep 12 14-53-50](https://user-images.githubusercontent.com/7134267/189602940-677b7166-beaf-4a4b-b77b-747e0a921b3f.png)

**Comment by kprovance** [comment]
@steve231293, shouldn't be too difficult. I opened a new ticket because this one is years old and closed. #3903
