### ISSUE TITLE
Use the homepage sorter with "required"

### ISSUE THREAD

**Issue by isarmstrong** [reduxframework/redux-framework#1268]
I hope I'm just asking after another undocumented feature this morning :)

I'd like to conditionally add section details based on whether that section is enabled or disabled in the homepage sorter. If I were using a switch to enable a section, I'd do this:

`
'required' => array('portfolio_switch','equals',true)
`

However, if I'm using the enabled/disabled flag on a sorter, I'm not sure how to capture that value using the array equals format.

Am I just making up crazy stuff again, or is there a built-in way to do this already?

**Comment by br113** [comment]
Is this still impossible? Thanks

**Comment by kprovance** [comment]
Not supported.  The code to write such a thing would be massive, and since no one is paying us to do so, chances are it will probably not happen.  Sorry.
