### ISSUE TITLE
DEVS! HELP US TEST ASAP.

### ISSUE THREAD

**Issue by dovy** [reduxframework/redux-framework#1337]
Hey WordPress devs. As if our last release wasn't enough, I just reduced load time of the panel by up to 300%! I need you to help me test ASAP.

*\* It's been merged into master **

Grab it. Tell us if you have problems. I don't think you will though. Did I mention, this work will dramatically help us get groups out too? Oh yea. That's forthcoming.

If you can, donate to the effort (https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=N5AD7TSH8YA5U). Some of us have bills to pay and we're spending way too much time making your dev life easier.

Some have asked what we did differently?

We made the JavaScript on-demand. Traditionally we initialized every field in the panel on load. This took a lot of time. Certain JS functions (like the WP color picker, editor, ace_editor, etc) took a LONG time to load. By doing it the way we are, only the fields visible at any time are initialized. As you traverse your panel fields that are newly visible get initialized. In this way you load the full panel without having to launch javascript for fields you never see or use. I think you're users will b every VERY happy.

Please test this hard. Every field. GO!

**Comment by maheshwaghmare** [comment]
@kprovance I'm still facing the issue `Uncaught ReferenceError: redux is not defined`

I'm working on localhost and used plugin `Redux Vendor Support` to enqueue the local assets.

As @tpaksu suggested ( https://github.com/ReduxFramework/redux-framework/issues/1337#issuecomment-45726818 ). I was made changes on locahost i.e.

```'dev_mode' => false,```

and

```//*****************************************************************
                // Redux JS
                //*****************************************************************
                wp_register_script(
                    'redux-js',
                    ReduxFramework::$_url . 'assets/js/redux' . $this->min . '.js',
                    $depArray,
                    $this->timestamp,
                    false
                );```

Set `false` in both changes. And it works.

My current redux version is - `3.5.8.1`

What was the wrong with my current setup. Or any other issue.

**Comment by maheshwaghmare** [comment]
Now, Update it with version `3.5.8.4`. Still facing same issue. I'm working on localhost by turning off internet. Its internet issue or any other?
