### ISSUE TITLE
WPML Problem on Backend

### ISSUE THREAD

**Issue by webbudesign** [reduxframework/redux-framework#1351]
Hi guys,

I am working on a multi language theme and have a problem with WPML. When I save settings of Redux Panel on backend everything is work fine. But If I change the language of backend and save with different values, it changes global options from db. I already checked #1064 and #999 . But can't find a solution for this problem.

I have some text fields and text areas (contain texts for translate) into the admin panel and these are needs to be translate and load different on backend + front end. 

Are you have a solution for this ?

Thanks for help.

**Comment by zindexsolutions** [comment]
Hi, if possible then give repay of my question at https://github.com/reduxframework/redux-framework/issues/1064
