### ISSUE TITLE
Large Amount of Temp Files Being Created

### ISSUE THREAD

**Issue by ajgagnon** [reduxframework/redux-framework#1383]
Really enjoying the plugin so far. Thanks for the great work.

I have a few issues with a large amount of temporary files being created for some users.  It seems every time a page loads, ~28 new .tmp files are created in the wp-content/uploads/tmp/ folder:

```
googlefonts10.tmp 
googlefonts16.tmp 
googlefonts21.tmp 
googlefonts27.tmp 
googlefonts32.tmp 
...etc
```

Eventually it crashes the server. This is using 3.3.2.3 (the latest on the master branch) and WordPress 3.9.1. Dev_mode is off.  This happens both with the plugin and when it's embedded in the theme. I've tried removing one or the other and it doesn't have any effect. I should mention the problem disappears with both the plugin and embedded framework removed.

It doesn't seem to happen on all installs, so it may be an issue with specific server settings. I just can't seem to pinpoint the part of the code that would create these temporary files. Any insight you can give is appreciated!

Thanks,

Andre

**Comment by wilsonf1** [comment]
I believe I'm using Version: 3.5.4.1 which came with my theme: Native Church.
We too get 1000's of info-htmlX.tmp files in our /tmp folder.

We have a wp-contents/uploads/Redux folder set to 777.

What is the next thing to check why this is happening?

**Comment by dovy** [comment]
Install Redux as a plugin from the admin plugin browser and delete that redux folder you created. ;)

**Comment by g48r137** [comment]
The problem can be reproduced if someone is using SSH SFTP Updater Support plugin as described here: https://codex.wordpress.org/Editing_wp-config.php#Enabling_SSH_Upgrade_Access
I think wp filesystem should be used only for update purposes not like in sample config.

**Comment by dovy** [comment]
So the new version works? Which sample config? One from the builder?

**Comment by g48r137** [comment]
I have not tested it, I'm currently working on specific page that by customer requirements uses 3rd party theme with built in plugin. The only problem I've found is sample-config.php
$sampleHTML = $wp_filesystem->get_contents( dirname( __FILE__ ) . '/info-html.html' );
Someone used this as base for their config. This file doesn't contain this line anymore in repository.
I have changed the code to first check if file_get_contents works. Anyway wp-filesystem initialization should contain some authentication prompt as far as I understand wp filesystem documentation properly.

Current version should work perfectly.

Best regards,
Gabriel.

**Comment by dovy** [comment]
:)  Great.  Thanks.

**Comment by g48r137** [comment]
Ahh... this can also be a problem:
https://github.com/reduxframework/redux-framework/blob/master/ReduxCore/inc/class.redux_functions.php
public static function initWpFilesystem()

Something like this seems to be proper way:
// now we have some credentials, try to get the wp_filesystem running
if ( ! WP_Filesystem($creds) ) {
	// our credentials were no good, ask the user for them again
	request_filesystem_credentials($url, $method, true, false, $form_fields);
	return true;
}

Like described here:
http://ottopress.com/2011/tutorial-using-the-wp_filesystem/

Cheers!

**Comment by dovy** [comment]
We've attempted to make our file system completely compliant but we don't have environments to mimic the issues. Can you dig into that class and try and help us solve this for good? We've done a ton of work in there...

**Comment by dovy** [comment]
Open source after all. ;)

**Comment by g48r137** [comment]
I think you can remove this function:
Redux_Functions::initWpFilesystem();
from:
https://github.com/reduxframework/redux-framework/blob/master/ReduxCore/inc/class.redux_functions.php
line 108-116

remove its reference from:
https://github.com/reduxframework/redux-framework/blob/master/sample/sample-config.php
lines 26 and 28

and replace:
$sampleHTML = $wp_filesystem->get_contents( dirname( __FILE__ ) . '/info-html.html' );
by:
$sampleHTML = file_get_contents( dirname( __FILE__ ) . '/info-html.html' );
at line 30.

The code in:
https://github.com/reduxframework/redux-framework/blob/master/ReduxCore/inc/class.redux_filesystem.php
seems to be OK, so all backend functions should work fine.

**Comment by dovy** [comment]
So here's the rub, we cannot use file_get_contents directly, ever. Won't pass theme check. Hence we init the WP file system and use the files directly.  ;)

**Comment by kprovance** [comment]
I'm also certain some of our extensions are still using the Redux_Functions::initWpFilesystem();

**Comment by g48r137** [comment]
So it looks like without refactor there is no perfect quick solution. Error in case of not direct FS_METHOD or warning in validator.

**Comment by dovy** [comment]
The point is that in most environments file_get_contents works perfect, but ThemeCheck says that's bad. So we attempt the filesystem directly, then a bypass of using the default WP functions for file_get_contents. That's the only way we could make this work. And so far, it hasn't given us any problems.

**Comment by g48r137** [comment]
https://wordpress.stackexchange.com/questions/157629/convenient-way-to-use-wp-filesystem/157641#157641

wp-filesystem should not be use outside admin. Recommended (best practice, but unfortunately not most popular - so far not among users of this great piece of software)  way of configuring wordpress is to use different user for for web server than for the file owner and not to keep credentials hardcoded in config.

**Comment by dovy** [comment]
Sorry my friend, but this is an impasse. SSH SFTP Updater Support plugin is not official and Redux writes files only while within the admin. So... I am pretty sure we comply.  ;)

**Comment by g48r137** [comment]
Maybe its not official, but officially recommended as first choice in:
https://codex.wordpress.org/Editing_wp-config.php#Enabling_SSH_Upgrade_Access.
Nevertheless forgot I've mention it.

If it writes only inside admin why not to use this:
https://github.com/reduxframework/redux-framework/blob/master/ReduxCore/inc/class.redux_filesystem.php
?

This can be used on frontend:
https://github.com/reduxframework/redux-framework/blob/master/ReduxCore/inc/class.redux_functions.php

If this is not true, then my theme is broken and please take my apologize, but as I've mentioned before I'm working on specific theme.
