### ISSUE TITLE
Global $redux_demo having to be defined on each theme file that referenced the array

### ISSUE THREAD

**Issue by fcryer** [reduxframework/redux-framework#1415]
Due to some issues with the multisite setup that were not able to be resolved yet (ticket submitted - https://github.com/ReduxFramework/redux-framework/issues/1323), I have to include the Redux Framework within my theme.

That being said, I am having to load the following text at the top of every php within my theme that ties in to / uses the options values:
<?php global $redux_demo; ?>

Is there another way to define / call this global variable in a single spot within the WordPress theme to where any PHP file within my theme can tap into the options?

If it's as easy as adding the following below, then I would like to know where this needs to be added as I've done this in my header.php file, functions.php file, and I have had no success either way.

// Due to a limitations of variables and functions, you must globally define
// variables inside functions.
global $redux_demo  // This is your opt_name.
print_r ($redux_demo);

Every article I've found on PHP and WordPress doesn't seem to solve this issue.

**Comment by wwwdonus** [comment]
I install redux frame work on my plugins, and i want to print 
global $redux_demo;
print_r ($redux_demo);
is not printing anything although i set the $opt_value;
but if i print 'anything' it is working.
what is the problem i made, I don't know, any suggestion will be highly appreciated.

**Comment by tillalsaeed** [comment]
@wwwdonus first you have to set global $redux_demo; than you have to get the value like
 echo  $redux_demo["give field id here"];
given field id here means the field you want to show on the specify place.
