### ISSUE TITLE
select image - default image not working

### ISSUE THREAD

**Issue by nicon-dev** [reduxframework/redux-framework#1441]
Hi!
I´m not shure if its me or a bug but I cant set the default image with an select image.
Doesn´t matter if I assign a path or number to the default value... it just doesn´t show up in the options page.

Here is the code I use:

```
$this->sections[] = array(
  'title'     => __('General', 'redux-framework-ptc'),
  'desc'      => __(''),
  'icon'      => 'el-icon-home',
  // 'submenu' => false, // Setting submenu to false on a given section will hide it from the WordPress sidebar menu!
   'fields'    => array(
     array(
    'id'        => 'opt-select-header',
    'type'      => 'select_image',
    'title'     => __('Select Header', 'redux-framework-ptc'),
    'subtitle'  => __('Select which header do you like to use.', 'redux-framework-ptc'),
   'options'   => array(
     '1' => array(
        'img' => get_stylesheet_directory_uri() .'/images/redux/nav_standard.png',
         'alt' => 'Standard Navigation'
       ),
       '2' => array(
           'img' => get_stylesheet_directory_uri() .'/images/redux/nav_standard.png',
           'alt' => 'Navigation Underscore'
         )
   ),
  'default' => '1',
 )
),
);
```

Any ideas why it is not working?

**Comment by jahir07** [comment]
Still not working this issue.. 

```
array(
                'id'       => 'header_style',
                'type'     => 'select_image',
                'title'    => __('Default Header', 'heal'), 
                'subtitle' => __('Select One of header layout.', 'heal'),
                'options'  => array(
                    '1'      => array(
                        'alt'   => '1 Column', 
                        'img'   => ReduxFramework::$_url.'assets/img/Screenshot.jpg'
                        ),
                    '2'      => array(
                        'alt'   => '2 Column Left', 
                        'img'   => ReduxFramework::$_url.'assets/img/Screenshot2.jpg'
                        )
                    ),
                'default'  => '1',
                ),
```
default should "1 column" show, but not showing.. :(
Showing placeholder text.. please help me..

**Comment by imranh654** [comment]
Same issue here
default does not select the default value.
`array(
                'id'      => 'header-variation',
                'type'    => 'select_image',
                'presets' => true,
                'title'   => __( 'Header Style', 'demo-theme' ),
                
                'options' => array(
                    '0' => array(
                        'alt' => 'Transparent Header',
                        'img' => ReduxFramework::$_url . '../sample/presets/preset1.png',
                    ),
                    '1' => array(
                        'alt' => 'Classic Header',
                        'img' => ReduxFramework::$_url . '../sample/presets/preset2.png',
                    ),
					'2' => array(
                        'alt' => 'Centered Header',
                        'img' => ReduxFramework::$_url . '../sample/presets/preset2.png',
                    ),
                ),
				'default' => 2,
            ),`
