### ISSUE TITLE
'link_color' with 'output' parameter doesn't work correctly

### ISSUE THREAD

**Issue by aonzzung** [reduxframework/redux-framework#1446]
Hi,

I found another issue with link_color field which I need only 'regular' and 'hover' states.

Redux version 3.3.3.5

Here is my array

<pre>
array(
                        'id'        => 'berry-menu-link-colors',
                        'type'      => 'link_color',
                        'title'     => __('Menu Link Colors', 'tymberry-theme-options'),
                        'subtitle'  => __('Pick colors for regular and hover states of menu links', 'tymberry-theme-options'),
                        //'regular'   => false, // Disable Regular Color
                        //'hover'     => false, // Disable Hover Color
                        'active'    => false, // Disable Active Color
                        'visited'   => false,  // Disable Visited Color
                        'default'   => array(
                            'regular'   => '',
                            'hover'     => '',
                        ),
                        'output'    => array( 'color' => '.navbar-nav li a')
                    ),
</pre>

My setting is
![screen shot 2557-07-11 at 1 22 56 pm](https://cloud.githubusercontent.com/assets/3109162/3549248/d80a0ae8-08c3-11e4-9cd0-851e67da04c6.png)

After browsing the fronted, I got an error.
![screen shot 2557-07-11 at 1 19 25 pm](https://cloud.githubusercontent.com/assets/3109162/3549229/5b2c7ec0-08c3-11e4-85eb-1522565b77c6.png)

Also, the actual output was
![screen shot 2557-07-11 at 1 20 10 pm](https://cloud.githubusercontent.com/assets/3109162/3549238/a88e283a-08c3-11e4-90b2-64dc3ff3fd52.png)

<pre>
.navbar-nav li a{color:#81d742;}:hover{color:#eeee22;}
</pre>

Expected output should be

<pre>
.navbar-nav li a{color:#81d742;}.navbar-nav li a:hover{color:#eeee22;}
</pre>

Thanks in advance for your contribution. ;)

Thanks for the best theme option I've ever used. 
Consider to donate after finishing my project as well ;)

**Comment by FabKos** [comment]
Had the same issue, had to google for it. I suggest to edit the description. BTW: Hope aonzzung really donated sth. All the best and thanks for the explanation.
