### ISSUE TITLE
admin.less and color scheme questions ?

### ISSUE THREAD

**Issue by aonzzung** [reduxframework/redux-framework#1466]
Hi Again ;)

I searched http://docs.reduxframework.com/ and couldn't find any documentation about this.

It seems there are available LESS mixins for developer to change accent color as well as some color schemes.

<pre>
/* Light fresh theme */
.admin-color-fresh {
    .adminThemeColorOverrides(#bbb, #0074a2, #222222, #1e8cbe);
}

/* Light admin theme */
.admin-color-light {
    .adminThemeColorOverrides(#e6e6e6, #04a4cc, #888888, #0384a4);
}

/* Blue admin theme */
.admin-color-blue {
    .adminThemeColorOverrides(#e2ecf1, #4796b3, #096484, #db9825);
}

/* Coffee admin theme */
.admin-color-coffee {
    .adminThemeColorOverrides(#cdcbc9, #c7a589, #46403c, #ba906d);
}
</pre>

I checked on the admin side and found that "admin-color-fresh" class is permanently added to body class.

<pre>
body class="wp-admin wp-core-ui js  jetpack-disconnected debug-bar-maximized  toplevel_page__options admin-bar branch-3-9 version-3-9-1 admin-color-fresh locale-en-us customize-support svg" screen_capture_injected="true"
</pre>

Is there any (redux config) argument to change the class name (i.e. change to admin-color-blue) ?
(This is because I plan to create a custom mixin for my own color scheme also.)

FYI: Now I do it from scratch by enqueuing my style with "admin_enqueue_scripts"

Thanks.

**Comment by screets** [comment]
Hello,

It changes the color according to user's default profile color. So you have to be careful when you use admin-color-fresh.. Because other users who use other admin color will see different color already.

-1 for davy's solution.

Best.
