### ISSUE TITLE
PHP Fatal Error: Class 'ReduxFramework_Extension__notes' not found

### ISSUE THREAD

**Issue by leesaenz** [reduxframework/redux-framework#1499]
Hi,

I have installed your theme on a wordpress site that is set up both in a local environment on OS X with the MAMP stack and also on an Apache remote server.

The theme works great on my remote, but locally, I am getting the following error and I'm not sure why:

PHP Fatal error:  Class 'ReduxFramework_Extension__notes' not found in /wp-content/themes/oneengine/plugins/admin-core/framework.php on line 2077

Any help or ideas?

The wordpress install works fine by itself, but once I active the theme, I get a white page with that error in the console log.  Am I missing something in my Apache build?

**Comment by jasonblackdog** [comment]
The solution @stevenriche gave solved my issue. Thank you!

**Comment by fyreflyt** [comment]
@stevenriche thanks a ton. I just got this error and was able to solve in under 30 minutes, saving me from a very late night at work.

**Comment by kprovance** [comment]
Wow.  I want to say we fixed that a while back.  Did it still occur on 3.5.9?

**Comment by martypaz** [comment]
Thanks som much @stevenriche - Design notes are a paing in my ass but this proves how much - Saved me lot of digging - Thanks

**Comment by jerrygarciuh** [comment]
@stevenriche  you are a hero!

**Comment by dovy** [comment]
@kprovance we should do a skip if the first string of the file we're loading is `.` or `_`.
