### ISSUE TITLE
Site Loads Too Slow When Using Redux Framework

### ISSUE THREAD

**Issue by simrandeep** [reduxframework/redux-framework#1522]
Hi

Recently one of my customers reported the issue of slow loading of site after activating my theme.

I got FTP access and tried to check the issue. I removed Redux Framework from my theme and site started loading amazingly fast. Then I further tried to check the issue. I removed different codes from config file and noticed that code related to typography is causing the issue of slow loading of site. Because when I removed just the code related to typography, the site started loading fine.

I tried uploading latest version of Redux that is 3.3.5.8 but that didn't help too. Customer is using latest version of WordPress that is 3.9.1

The theme is not in dev_mode and redux is embedded in the theme itself.

There are no errors in output console but I have users error log file.

Site is also giving Internal Server Error because of it.

What may be the issue? Please help fix it because earlier also few customers reported the same issue.

Thanks

**Comment by TukuTuru** [comment]
since this thread started with:
Site loads too slow....

I have a question:

My site is running good, even with Redux :dancer: 

but this one worries me a bit:

    SHOW FULL COLUMNS FROM `wp_options`

    require('wp-blog-header.php'), require_once('wp-load.php'), require_once('wp-config.php'),         require_once('wp-settings.php'), include('/themes/minimax3/functions.php'),     require_once('/themes/minimax3/theme-options/mx3-config.php'), Redux_Framework_mx3_config-    >__construct, Redux_Framework_mx3_config->initSettings, ReduxFramework->__construct,     do_action('redux/loaded'), call_user_func_array, Redux_Welcome->init, set_transient, update_option

==> !!!!!  (9.6ms)

it seems to happen only on pages, on posts its a bit lower, 8.5 ms, and on home (no page) its OK

Do you have any clue?
It seems somehow related to redux...
Sorry, now super hero in DB Stuff...
I just found that analyzing page speed...

**Comment by dovy** [comment]
@TukuTuru I really doubt it's Redux's doing. It more than likely in the other code.

Please also don't piggyback old issues. This is from 2014...

**Comment by born2net** [comment]
I am also seeing a major slow down when hitting 1000 items in the store, BUT only if the redux chrome extension is turned on, if I turn it off, no issues... :/ bummer :(

**Comment by kprovance** [comment]
"Please also don't piggyback old issues. This is from 2014."

Also, we offer no Chrome extension.  Not sure where you got that from.  It wasn't us.
