### ISSUE TITLE
Network Panel Doesn't work in Multisite mode

### ISSUE THREAD

**Issue by ghost** [reduxframework/redux-framework#1541]
Hi there,
I have set `database => network` and `network_sites => 1`, the options panel is showing up on admin section but when I tried to update options, it didn't work at all (all options didn't change).
Any idea about this issue? Thank you very much.
FYI: WP 3.9.2 Multisite + Redux latest version (3.5.5.10) + standalone theme + embedded in project. It works perfectly with single site mode + it still CAN get default option's value.

**Comment by robruiz** [comment]
What is the trick to getting this thing to work on a multi-site?

**Comment by kprovance** [comment]
Someone fixing it?

**Comment by nrkhatana** [comment]
badly need solution for this, when i save any setting on any of my site on network, it overwrites on all :|

**Comment by nrkhatana** [comment]
Got it, I have disabled in on Network. Enabled on each site and removed the following lines 
		'network_admin' 	   => true,
		'network_sites'		   => true,
		'database' 	           => 'network'
Its working now
