### ISSUE TITLE
not getting styles for redux admin panel

### ISSUE THREAD

**Issue by Aohor** [reduxframework/redux-framework#1574]
ok today I installed redux by this code: 
// load the reduX framework
if ( !class_exists( 'ReduxFramework' ) ) {
require_once( dirname(**FILE**) . '/ReduxCore/framework.php' );

}
// load the reduX options 
if ( !isset( $redux_imd ) ) {
require_once( dirname(**FILE**) . '/framework/admin-config.php' );
}

the problem is I'm not getting the styles for admin panel & it looks all messed up.
screenshot:
http://img4.uploadhouse.com/fileuploads/19746/1974653423193b567a08a7e953ed6c470b808a5c.jpg

I'm using:
latest v3.3.6.3 with 
WordPress latest Version 3.9.2
Dev mode is true.
& redux is embedded.

**Comment by k9t9** [comment]
Have exactly the same problem when embedding inside theme on localhost- and it is not a permission error - any fix for that ?
