### ISSUE TITLE
Image sizes data option for select fields

### ISSUE THREAD

**Issue by Gyroscopic** [reduxframework/redux-framework#1582]
Hi

I've added this feature to my options. It displays the list of image sizes registered in WP.

I dont use GIT so cant supply a pull request but I have added the following code to my local redux framework to allow me to choose image sizes in select fields.

```
} else if ( $type == "image_size" || $type == "image_sizes" ) {
            global $_wp_additional_image_sizes;
            foreach ($_wp_additional_image_sizes as $size_name => $size_attrs) {
                         $data[ $size_name ] = $size_name.' - '.$size_attrs['width'].' x '.$size_attrs['height'];
            }
           //if
```

I added this to the framework.php file around line 919 (after the menu_location option).

Any chance you can add it to the distro?

Many thanks.

**Comment by ghostpool** [comment]
Hey there,

The image_size option does not display the default WordPress image sizes (thumbnail, medium, large etc.) only your custom registered image sizes.

Is there any chance you could modify the code to include the default ones? I've added the following to framework.php to achieve this:

```
} else if ( $type == "image_size" || $type == "image_sizes" ) {
	global $_wp_additional_image_sizes;
	
	foreach ( get_intermediate_image_sizes() as $_size ) {
		if ( in_array( $_size, array( 'thumbnail', 'medium', 'medium_large', 'large' ) ) ) {
			$sizes[ $_size ]['width']  = get_option( "{$_size}_size_w" );
			$sizes[ $_size ]['height'] = get_option( "{$_size}_size_h" );
		} elseif ( isset( $_wp_additional_image_sizes[ $_size ] ) ) {
			$sizes[ $_size ] = array(
				'width'  => $_wp_additional_image_sizes[ $_size ]['width'],
				'height' => $_wp_additional_image_sizes[ $_size ]['height'],
			);
		}
		$name = $_size . ' - ' . $sizes[ $_size ]['width'] . ' x ' . $sizes[ $_size ]['height'];
		$data[ $name ] = $_size;
	}
```
