### ISSUE TITLE
is it possible to group options using the select field type?

### ISSUE THREAD

**Issue by con322** [reduxframework/redux-framework#1596]
is it possible to group options using the select field type?

How this type of issue/question is allowed & hasnt already been asked. Thanks/Sorry in advance.

For example 
 -Fade animations (just a label no value)
       -fade down
       -fade up 
       -fade right
       -fade left
-Bounce animations (just a label no value)
       -bounce down
       -bounce up
       -bounce right
       -bounce left

**Comment by prionkor** [comment]
Anyone who stumbled upon this ticket please check this #1803 for further information about grouped options. There isn't much info about optgroup in the select field documentation.
