### ISSUE TITLE
 3.3.6.7 Ace Editor Problem

### ISSUE THREAD

**Issue by vanmuoivp** [reduxframework/redux-framework#1600]
Hi ,

I am very proud to have got this ReduxFramework, and now.
I using redux version 3.3.6.7
I custom type ace_editor: http://screencast.com/t/Jiv9lV9la
But It not show form :(
http://screencast.com/t/JsuBs5l6vk
Please help me.
P/s: I view in file sample-config.php in reduxframework version 3.3.6.7 . You comment code it.
http://screencast.com/t/LP4cY5JNnQOH

Thank you very much.

**Comment by shohag121** [comment]
Use  use_cdn => true,
Or install "[Redux Vendor Support](https://github.com/reduxframework/redux-vendor-support)" plugin.
https://github.com/reduxframework/redux-vendor-support
