### ISSUE TITLE
Theme Customizer not displaying all Redux options

### ISSUE THREAD

**Issue by thrasherstudios77** [reduxframework/redux-framework#1626]
I have noticed on my Themes Customizer page Appearance->Customize, that only a handful of Redux theme options I have created are appearing. I have tried to figure out why certain options are available and others are not, but I can't seem to find a pattern, its very random which ones show up.

Is this the expected behavior, are certain Redux options not setup to be seen on the Customizer page? For an example out of 6 options on my Global Settings tab in Redux, only one is showing on the Customizer page.

Options that are skipped not showing:
1. image_select
2. slider
3. spacing
4. background
5. typography

Option that is showing:
1. color

Can anyone speak to this, am I missing somthing, it would be great to have all options available on the Customizer page.

thank you

**Comment by sinashamsizadeh** [comment]
Hi @dovy 
I hope your son is fine now.
Can you check this issue again and re-open this issue
