### ISSUE TITLE
Can't disable developer mode after setting dev_mode = False

### ISSUE THREAD

**Issue by badr0333** [reduxframework/redux-framework#1654]
I am not using redux as a plugin, i have embedded it into my theme.I can't disable dev mode even though i set dev_mode = false.I am using version 3.3.6.9.

**Comment by invot** [comment]
With a fresh install I am getting this notice. I'm unsure as to why. In my config file I have:
`'dev_mode'           => false,`

**Comment by kprovance** [comment]
#2238, @invot

**Comment by abeneo** [comment]
Hi,
i thank that because your have the define('WP_DEBUG', true) in wp-config.php (line 66),
just set it to 'false' and it will work.
@+

**Comment by asabanovic** [comment]
Yes I just want to confirm the @abeneo 's comment. If you have included Redux in your theme and then included the simple-config.php  and you have 'dev_mode' => false , then set your  WP_DEBUG to false in  wp-config.php. Thank you!

**Comment by abeneo** [comment]
Thanks for your feedback!

**Comment by foo123** [comment]
i'm not sure of the reason, but if dev_mode flag is set to false, dev_mode tips and messages should be ignored, right now (v.3.9.4) checks for dev_mode are of this type:

`if ( $this->args['dev_mode'] == true || Redux_Helpers::isLocalHost() == true )`

or even `if ( Redux_Helpers::isWpDebug() )`

which re-enables dev_mode (even if explicitly set to `false` ) if localhost environment is used. imo this should be removed. If a developer needs to test **without dev_mode on** even in localhost environment it should be doable

**Comment by kprovance** [comment]
This is the way we prefer it.  Those in local or debug mode who ask for help never seemed to have dev_mode on.  Plus, it circumvented our ad network, which is why Redux makes any type of money.
