### ISSUE TITLE
How to disable the print margin visibility

### ISSUE THREAD

**Issue by shivapoudel** [reduxframework/redux-framework#1663]
![image 10](https://cloud.githubusercontent.com/assets/3774827/4216191/81e9809c-38d6-11e4-9491-da4d9bfa6b5c.png)

Can we set `print margin` visibility in ace editor of Redux Framework. There's an option for this in [ace site](http://ace.c9.io/#nav=howto).

```
editor.setShowPrintMargin(false);
```

**Comment by ILNILEY** [comment]
I am confused about the usage of printMargin, in HTML it seems just a div have the class named 'ace_print-margin '. As for me , I don't want to show that so I just do editor.setShowPrintMargin(false) and it work. I just wanna know why print margin is show as default.

**Comment by kprovance** [comment]
See the reply from over three years ago.  That is how the ACE vendor does it.  It's not us.
