### ISSUE TITLE
Best way to add CSS for Admin Panel area of options?

### ISSUE THREAD

**Issue by ahmadawais** [reduxframework/redux-framework#1694]
I want to modify how Redux looks in the admin panel for a certain plugin. What would be the best way to  modify or add new CSS properties for Redux admin panel options so that updates of redux don't disturb the templating?

I read this http://docs.reduxframework.com/core/advanced/custom-panel-css/
Then I added this in base file of my plugin

```
function aa_wopt_addPanelCSS() {
    wp_register_style(
        'aa_wopt_redux_css',
         dirname(__FILE__).'/admin/css/aa_wopt_redux.css',
        array( 'redux-css' ), // Be sure to include redux-css so it's appended after the core css is applied
        time(),
        'all'
    );  
    wp_enqueue_style('aa_wopt_redux_css');
}
// This example assumes your opt_name is set to redux_demo, replace with your opt_name value
add_action( 'redux/page/aa+wopt/enqueue', 'aa_wopt_addPanelCSS' );
```

Still no CSS is being loaded
Looking forward.

**Comment by monecchi** [comment]
Yeap! The same here!

**Comment by kprovance** [comment]
FIrst, let's not piggy back year old tickets.  Begin a new one (and if you do so in the future, read ALL the text in the new ticket window, please.

Second this is an outdated way of doing this.  Most people - myself included - who have extra styling to apply to Redux just stick it in a CSS file and use admin_enqueue_scripts to add it into the project.  Works great.
