### ISSUE TITLE
Image Select with presets dont work

### ISSUE THREAD

**Issue by ghost** [reduxframework/redux-framework#1725]
I select one of predefined but options page isn't reloaded and no save is done.
In previous redux versions this option is ok. 

Redux Framework v3.3.8.5
Wordpress 4.0
Redux isnt in dev_mode

```
array(
 'id' => 'header_style_predefined',
'type' => 'image_select',
'title' => __('Header Predefined Styles', 'codeless-admin'),
 'presets'  => true,
'subtitle' => __('', 'codeless-admin'),
'options' => array(
    'header_1' => array(
     'alt' => 'Header 1', 
     'img' => 'http://localhost/test/wp-content/themes/s/images/patterns/header1.jpg',
     'presets' => array(
         'header_style' => 'header_1',
     ),
     'header_2' => array(
     'alt' => 'Header 2', 
     'img' => 'http://localhost/test/wp-content/themes/s/images/patterns/header2.jpg',
     'presets' => array(
         'header_style' => 'header_2',
     )
 ),

'default' => 'header_1'
),
```

Redux as theme options

Thank You

**Comment by zuper** [comment]
Let's agree to disagree kprovance. 

The code that @codeless shows is enough. I am having the same issue on redux version 3.5.

An example:

array(
                        'id'        => 'menu_preset',
                        'type'      => 'image_select',
                        'presets'   => true,
                        'title'     => __('Menu theme', 'redux-framework-demo'),
                        'subtitle'  => __('Select a menu theme appearance or create a custom one', 'redux-framework-demo'),
                        'desc'      => __('This allows you to set a json string or array to override multiple preferences in your theme.', 'redux-framework-demo'),
                        'options'   => array(
                            '0'  => array(
		                                        'alt' => 'Menu theme 1',
		                                        'img' =>  URI_SETTINGS_PATH . 'assets/images/menu_theme/menu_theme_1.png',
		                                        'presets' => array(
			                                        'menu_position'            => 'top-sticky'
		                                        )
                            ),
                            '1'  => array(
		                                        'alt' => 'Menu theme 2',
		                                        'img' => URI_SETTINGS_PATH . 'assets/images/menu_theme/menu_theme_2.png',
		                                        'presets' => array(
			                                        'menu_position'            => 'top'
		                                        )
                            )
                        ),

                        'default'   => 0,
                    )


As you see above if the 'default' is  0 the image_select does not work. If the 'default' is 1 the image_preset selects option '1', Both options are pointing to the field 'menu_position'

Can you please explain why when using 'default'  to '1' works ? but not on '0' if both point to the same field type ?
