### ISSUE TITLE
Change options via url?

### ISSUE THREAD

**Issue by maarcin** [reduxframework/redux-framework#1738]
Hi guys,

just quick question. Is there a way to change options on the front-end via address url? Lets say I have option like this one

<pre>
array(
    'title' => __('Logo align', 'mt-theme-options'), 
    'subtitle' => __('Choose logo align', 'mt-theme-options'),
    'id'=>'logo_align',
    'type' => 'button_set',
    'options' => array(
        'text-left' => __('Left', 'mt-theme-options'),
        'text-center' => __('Center', 'mt-theme-options'),
        'text-right' => __('Right', 'mt-theme-options'),
    ),
    'default' => 'text-center'
),
</pre>

I would like to change logo align on demo page with the url, because there is no other way to show multiple version when you try to show something on index.php. I saw something like that added to the url on other demo sites
<code>demosite.com/blog/?logo_align=text-left</code>
but it doesn't work. Is there a way to achieve this somehow?

Best
Marcin

**Comment by matyushen** [comment]
What could be a possible reason for this not to work? WP v.4.2.4. + Redux v.3.5.6.4 embed. Value is being grabbed from the URL but won't update the redux option.
