### ISSUE TITLE
Add settings for plugin to empty submenu

### ISSUE THREAD

**Issue by No3x** [ReduxFramework/redux-framework#1745]
Hello, I noticed strange behaviour with parent_page and 'menu_type' => 'submenu'. 

Redux-Framework Version: 3.3.6
Using Redux as: Plugin
Wordpress Version: 3.9
'dev_mode' => true,
Browser console errors: None

Builder TGM Settings: Embed only

In detail I was trying to add the settings as submenu to my plugin.
```
add_plugin_menu() {
        add_menu_page(
        __('Plugin Title', 'plugin'),
        __('Plugin Title', 'plugin'),
        'administrator',
        'my_plugin_dashboard', 
        array($this, 'Dashboard'),
        $pluginIcon
    );
}
add_action('admin_menu', array( $this, 'add_plugin_menu' ) );
```
My args look like this:
```
'page_slug' => 'my_plugin_settings',
'page_title' => 'Settings'
'menu_type' => 'submenu',
'page_parent' => 'my_plugin_dashboard',
```
I think this is the most simple setup to add the settings as submenu. But this is not working for me because the menu doesn't appear!
To get it working I need to **add at least one submenu** manually: 
So lets add it - 
```
add_submenu_page(
    'my_plugin_dashboard',
    null,
    'Im a silly dummy entry',
    'administrator',
    'dummy',
    '__return_null' 
);
```
After adding at least one submenu item that's the content of ```$submenu``` at the entry of add_submenu():
```
...
[my_plugin_dashboard] => Array
(
    [0] => Array
        (
            [0] => Plugin Title
            [1] => administrator
            [2] => my_plugin_dashboard
            [3] => Plugin Title
            [4] => menu-top toplevel_page_my_plugin_dashboard
            [5] => toplevel_page_my_plugin_dashboard
            [6] => dashicons-email-alt
        )

    [1] => Array
        (
            [0] => Im a silly dummy entry
            [1] => administrator
            [2] => dummy
            [3] => 
        )
)
```
As you can see now there is the key ```'my_plugin_dashboard' <=> $this->args['page_parent']``` and so obviously the custom menu case (see below) is true. 

If there is no submenu at all ```global $submenu``` doesn't contain information ( no key ```$this->args['page_parent']``` although there is a menu but with no submenus ) about the submenu and 
```
// framework.php -> add_submenu()
// custom menu
} elseif ( isset( $submenu[ $this->args['page_parent'] ] ) ) {
    $addMenu = true;
}
```
is never true.

I'm doing it wrong?
Please tell me if you need further details.
PS: ```global $menu``` contains the actually menu at any time but in fancy format (guess with priority as key):
```
...
[100] => Array
(
    [0] => Plugin Title
    [1] => administrator
    [2] => my_plugin_dashboard
    [3] => Plugin Title
    [4] => menu-top toplevel_page_my_plugin_dashboard
    [5] => toplevel_page_my_plugin_dashboard
    [6] => dashicons-email-alt
)
```

**Comment by menocreativity** [comment]
I'm afraid you're wrong. It's not a problem with our approach but with the submenu handling somewhere.

I have the exact same problem.
I want to add the Redux Options panel as settings 'sub-page' in my plugin.

Steps that work
1: add_menu_page (slug = 'my-overview-page')
2: add_submenu_page
3: trigger redux config with 'submenu' and 'page parent' setup as 'my-overview-page'
This works as expected: I have my custom plugin menu with a 'header item' that is repeated once as 'default' submenu item, my custom submenu item and then the redux options submenu item. Perfect.

Steps that don't work
1: add_menu_page (slug = 'my-overview-page')
2: trigger redux config with 'submenu' and 'page parent' setup as 'my-overview-page'
The redux config panel is not added as a submenu item. What I see is my custom menu item but no submenu items at all. Also: If I go to the redux options panel URL, it appears the URL doesn't exist. As if redux weren't available to me.

I referenced the above links and I'm aware of how they work. The key here is that if we add 1 submenu item ourselves, it works. Comment out that 1 submenu command and redux isn't added at all or not available.

I hope this information helps you figure out where things go wrong :)
Thanks! Good luck!

**Comment by No3x** [comment]
Please see http://stackoverflow.com/questions/26454814/redux-framework-add-submenu/26472241 for a minimal sample plugin to reproduce the issue.

**Comment by kprovance** [comment]
Okay, allow me to put this to bed once and for all.  What you want to do, create your own admin menu and append a Redux menu to it, via admin.php, yes, you will have to have one additional submenu.  That is the nature of the beast.  But this calls into question design strategy.  The point of an admin menu it to have...a menu.  A single item in the admin menu adds clutter to already valuable real estate.  That is, if you are stuffing another menu item that will do only one thing, to display options for a given plugin, then ideally it belongs under the Settings (or Tools, depending on functionality).  One should only really add a menu of their own design when an actual menu is involved.  Accept or ignore that advice as you will.  All that said, to do what you want will require at least one submenu item.  Period.  The end.  If this is unsatisfactory to you, no one - especially us - is stopping you from adding this functionality.  I believe you'll find it more difficult that it looks, as I gave it my best shot over a year ago, and gave up on it.  Why?  In the process of making it work, I broke too much backward compatibility with existing code...and for our project that is a HUGE no-no (and why all pull requests are tested thoroughly before we commit them.  Too many devs want to change our code to suit themselves without any thought of other users).  The alternative is to pay one of us to do it, as it would require Dovy or I to stop everything we are doing and focus on nothing else but...and that, my friend, would be very, very expensive in the end.  It's such a minute case instance, there is no way to justify the time on it, especially if it's just not workable without a complete rewrite of the Redux core, which isn't going to happen any time soon.

This leaves you with three choices:  You'll have to add a submenu page, regardless its functionality (make it a welcome page, or an about page, doesn't matter, use your imagination) and use the solution offered at the bottom of the stackoverflow link provided in the last post, or - if you are indeed only worried about a settings page - stick under Settings, where is should go anyway.  Or, lastly, add the functionality to Redux yourself.

Good luck, which ever way you go.

**Comment by No3x** [comment]
Thanks for the statement @kprovance. As mentioned my workaround is to create a simple "About this plugin" page. One can also add a landing page for updates. (As WordPress itself does or, to mention a plugin, easy digital downloads does).

**Comment by menocreativity** [comment]
So you consider this (screenshot) to be 'bad design strategy'? I personally prefer plugin stuff to be in the same place instead of being scattered around the wp-admin (while I have to look in multiple submenu's before finding the settings page for that plugin). 
![screenshot_ 2015-01-06 at 12 12 20](https://cloud.githubusercontent.com/assets/4326262/5627779/a6896aa6-959d-11e4-96ba-f45415564822.jpg)

**Comment by dovy** [comment]
Hehe, ok boys. Take a deep breath.

@menocreativity I fear Redux itself doesn't have this built in directly, but it's not hard to do at all.

First: set your redux config to have no menu:
http://docs.reduxframework.com/core/arguments/#menu_type
Set to hidden.

Then MANUALLY add your menu item with the pagenow being options.php and the page being your page_slug  http://docs.reduxframework.com/core/arguments/#page_slug

Should take all of 10 mins to do.  :)

**Comment by dovy** [comment]
Or whatever you have Redux to run under.  ;)

**Comment by No3x** [comment]
Hi @dovy. Could you explain what you mean with the manually step? I don't understand ```$pagenow being options.php```.

**Comment by dovy** [comment]
http://stackoverflow.com/questions/11613597/wordpress-add-submenus-to-custom-menu

**Comment by No3x** [comment]
I don't see any relation to $pagenow.

**Comment by dovy** [comment]
Haha, $pagenow is just the WordPress global variable...

Sorry, but I can't code this for you as it's basic WordPress coding. Just know the page still exists, you just have to hook it up.

Best of luck!

**Comment by No3x** [comment]
I know that. But I add menus via the API as told at the Stackexchange question and the codex. That's why I'm confused why you want to access it directly.

**Comment by dovy** [comment]
.... I'm saying to use the API, as Redux won't do it for you. I was just saying $pagenow because I'm used to the code. I was just saying to add it as a child to your custom menu. That's it.

**Comment by No3x** [comment]
Ah, got it. Thought you wanted to say I have to mess around with $pagenow directly.

**Comment by dovy** [comment]
Haha, my bad. I wasn't clear. Either way, post your solution if you would. I am sure others can benefit from it.

**Comment by No3x** [comment]
I'm really sorry. But imho this doesn't work either. :joy:
I receive a blank page. Redux doesn't appear.
If menu_type set to hidden add_submenu in redux is not called and also no action to _options_page_html. So I would say it can't appear.

**Comment by dovy** [comment]
Dig into the core and see if you can get it to work.  ;)

**Comment by menocreativity** [comment]
Hey Dovy,

I haven't tested your idea yet but it sounds pretty convincing. I'll check it out. What I did for now is just added a dummy-submenu and removed it with some CSS. Not perfect but it served the purpose until something better came along. (I thought I'd share this here for @No3x, in case he can't get this to work 'the correct' way ;) )

**Comment by No3x** [comment]
https://github.com/No3x/redux-framework/commit/06f6e97da69c5a9e36839e70630150326625b52c This should do the trick as described in the first post.  Maybe the cracks can see a backward incompatibility straight off.

**Comment by No3x** [comment]
Yepp. Just give it a try. It hardly relies on the case before that covers the  submenu in a non-empty parent so that the last case should only be covered for empty menus. The strpos should be changed to something more strict so that the slug must be identical instead of just containing the slug.

**Comment by kprovance** [comment]
Reopening

**Comment by kprovance** [comment]
I can confirm this fix is viable and does work.  Well done, @No3x!

For the stricter check, I changed your strpos check to:

```
if (strcasecmp($needle_menu_slug, $page_parent) == 0) {
   ...
}
```

Binary save, case insensitive check.  I also had to add `global $menu` as the foreach tanked without it.

I'll add your code and the changes on my end and push them, with proper credit given.  Again, awesome job!

**Comment by kprovance** [comment]
Okay, fix applied and pushed.  So far so good!

**Comment by menocreativity** [comment]
That's pretty cool! Thanks for the efforts, guys!

**Comment by No3x** [comment]
Sorry @kprovance, I added the global in a further commit in my fork. Hopefully this doesn't break something.
