### ISSUE TITLE
Issue when switching versions

### ISSUE THREAD

**Issue by robhadfield** [ReduxFramework/redux-framework#1756]
Hi all

We currently have a number (100+) sites that use the Redux Plugin (so thanks for that!) but we're having an issue updating I'm hoping you can help us with.

We're currently on 3.8.1 and are trying to upgrade to the latest WordPress repo version 3.3.8.4. (we had issues previously hence the being so far behind)

The issue seems to be around the slideshow repeating fields we have. When we update the Plugin and try and edit the options the options fail to save, first of all saying that some options were empty, and then after saving the whole slideshow section disappears. If you save again the slide area comes back but is empty. This seems to break the saved options array as the options are no longer recognised by the front end code. 

I can reliably recreate the issue so let me know if there is something I can do to better demonstrate and isolate the issue.

**WordPress : 4.0
Using a parent theme with the Redux as a plugin
Issue happens in prod or dev modes
No console errors
Section settings : http://pastebin.com/ZdaG0mre
Screenshots : http://imgur.com/5Q1oOTV,0fhITO4#1 and http://imgur.com/5Q1oOTV,0fhITO4#0**

Thanks
Rob

**Comment by FFIN** [comment]
I found a workaround.

The problem was the `$k` near `if ( $field['type'] == "slides" ) ` in  `/ReduxCore/framework.php`
Somehow in my environment, this `$k` was messing around.

I think this is a environment specific issue, so not sending any pull requests,
but for someone has similar situation like me maybe useful.


Edit
```
foreach ( $this->options[ $field['id'] ] as $k => $v ) {
    $data = wp_get_attachment_url( $v['attachment_id'] );
    if ( isset( $data ) && ! empty( $data ) ) {
        $this->options[ $field['id'] ][ $k ]['image'] = $data;
        $data                                         = wp_get_attachment_image_src( $v['attachment_id'], array(
            150,
            150
        ) );
        $this->options[ $field['id'] ][ $k ]['thumb'] = $data[0];
        $doUpdate                                     = true;
    }
}
```
something like to

```
foreach ( $this->options[ $field['id'] ] as $l => $v ) {
    $data = wp_get_attachment_url( $v['attachment_id'] );
    if ( isset( $data ) && ! empty( $data ) ) {
        $this->options[ $field['id'] ][ $l ]['image'] = $data;
        $data                                         = wp_get_attachment_image_src( $v['attachment_id'], array(
            150,
            150
        ) );
        $this->options[ $field['id'] ][ $l ]['thumb'] = $data[0];
        $doUpdate                                     = true;
    }
}
```

**Comment by kprovance** [comment]
Interesting @FFIN.  if `$k` was not returning the array index, what was it returning in it's stead?

**Comment by dovy** [comment]
Then we need to change one of those index variables. Can you discover which ones?

**Comment by FFIN** [comment]
Welcome back @dovy !
I just send a pull request. please review it.

Thanks in advance
FFIN

**Comment by robhadfield** [comment]
I will give this a try too @FFIN - thanks for your work on this.

...and Happy New Year @dovy - I hope the other family aren't still there!

**Comment by dovy** [comment]
Haha, thanks. Life is balancing out FINALLY.

Yes, @robhadfield please confirm if it works. I'd love to merge this in ASAP.

**Comment by kprovance** [comment]
Latest push should resolve this.  If not, please open a new ticket with the required information from our posting guidelines.  Thanks!
