### ISSUE TITLE
Translate String text of Slides of redux framework

### ISSUE THREAD

**Issue by carmelodiventi** [reduxframework/redux-framework#1760]
Hi, I would like to translate texts in the slide in various languages ​​on the site, but I can not find the strings of WPML , can anyone help

visit this URL: http://www.carmelodiventi.com/project/casadelpoeta/?lang=it

**Comment by progettowebfirenze** [comment]
There's a way

<?php echo __($opt_name['YOUR_DATA']); ?>

Then with string recognition on you'll be able to find your string in WPML string translation

**Comment by dovy** [comment]
That's a question for the WPML boys.  ;)
