### ISSUE TITLE
embeding redux framework with a plugin not working

### ISSUE THREAD

**Issue by arman1371** [ReduxFramework/redux-framework#1833]
hi

i developing a plugin for wordpress

when i embed redux framework in my theme it works well, but when i embed it with my plugin, the option name variable always return empty.

for example:

    global $redux_demo;
    print_r($redux_demo);die;

**Comment by kprovance** [comment]
Closing.  Can't get the requested information.  Please upgrade to the latest version.  If problem continue, submit a new ticket WITH THE REQUIRED INFORMATION.  Thanks.
