### ISSUE TITLE
404 issue on godaddy servers, even though mod rewrite is set to ON.

### ISSUE THREAD

**Issue by jaybabani** [reduxframework/redux-framework#1852]
Hello Dovy,
Redux is a great plugin and brilliant resource to get things done.

I am author of Ultra WordPress Admin Theme (http://codecanyon.net/item/ultra-wordpress-admin-theme/9220673) on CodeCanyon. Plugin uses redux framework. It is going great. Already crossed 80 sales in first 25 days.

Many customers from godaddy server are facing the issue of 404 page not found when saving options page.

I told them to ask their hosting service (godaddy) to enable mod rewrite option on their server.
Many customers say that godaddy guys have enabled the mod rewrite option on their server, but still they are facing the same issue.

Some say that godaddy guys tell them: we do not support such plugins using redux.

Can you please suggest what should be the possible solution to this thing.

Thanks

**Comment by jaybabani** [comment]
Hello Dovy,

Does this article by david walsh be of any help:

http://davidwalsh.name/mod_rewrite-htaccess-godaddy

Thank You.

**Comment by kprovance** [comment]
GoDaddy allows folks to edit their .htaccess?  Wow,If so, I can add these links to an article in our docs site for future cases.  Thanks for the heads up.  :)

**Comment by dovy** [comment]
So @jaybabani, just add `Options -Multiviews` to your .htaccess file and it should work. Can you verify?
