### ISSUE TITLE
Live Customizer fields hidden in WordPress 4.1

### ISSUE THREAD

**Issue by anikitas** [reduxframework/redux-framework#1917]
Hello,

Just tested with WordPress 4.1.
It seems that fields set by redux are hidden in Live Customizer ( also with v3.3.9.25 )
When pages loads are visible and after loading time all fields set by redux are display:none;

Thanasis

**Comment by ve3** [comment]
Are there any fix for redux 3.5.6.1 WP 4.2.3? Because it is still hidden and no where in document tell me this.

**Comment by dovy** [comment]
@ve3 please don't piggyback old OLD tickets.  ;)

Make a new one and submit a support URL please.
