### ISSUE TITLE
SCSS Compiler

### ISSUE THREAD

**Issue by Jim-E** [reduxframework/redux-framework#1919]
Developing a theme that uses the Leafo SASS/SCSS compiler. I don't see any reason to keep the one in our theme when we can use the one included in Redux which seems to work fine.

Opinions / comments?

Thanks

Redux embedded v3.3.9.26
WP v4.1

**Comment by kprovance** [comment]
@Jim-E , I had to go back to the old 0.0.12 install of scssphp, because too many people are still using that bloody PHP 5.2  :( :( :(

How difficult do you think it might be to fork their develop branch, ditch the namespace stuff and make it 5.2 usable?

**Comment by Jim-E** [comment]
Wow, http://php.net/archive/2010.php end of life was over 4 years ago, but it just won't die! 

I have an elderly parent going through chemo/radiation and soon surgery so at the moment time is an issue.
This [merge] (https://github.com/leafo/scssphp/pull/15/commits) made it look easy back in 2012.

I may be going back to LESS :( due to the way SASS handles !default), still researching and testing though.
