### ISSUE TITLE
Fatal error: Call to undefined function Leafo\ScssPhp\ctype_space()

### ISSUE THREAD

**Issue by alexmoss** [reduxframework/redux-framework#1926]
Hi guys,

Not sure if this problem is me, or you, or something else...

Redux: 3.3.9.29
WP: 4.1
PHP: 5.3.29

I get this error message when using Redux 3.3.9.29 within an AMPPS environment:

Fatal error: Call to undefined function Leafo\ScssPhp\ctype_space() in /Applications/AMPPS/www/test/wp-content/themes/theme-name/options/ReduxCore/inc/scssphp/src/Parser.php on line 803

I don't seem to have this issue when uploading to a server environment. Also to note, in AMPPS, version v3.3.8.8 of Redux works fine.

**Comment by faranarshad** [comment]
thanks guys, saved me big time.
