### ISSUE TITLE
Font style in typography field

### ISSUE THREAD

**Issue by azexo** [ReduxFramework/redux-framework#1928]
Is it possible to remove this code ?

                    if (empty($value) && in_array($key, array(
                                'font-weight',
                                'font-style'
                            ))) {
                        $value = "normal";
                    }

In general I think it is very flexible approach if redux will not define all CSS styles (for typography for example) - but such that only need to alter.

My theme have a lot of CSS styles for fonts - I want to give for user simple ability to change font by one field - not style not weight etc.

Thanks

**Comment by kprovance** [comment]
Yes, `'font-style' => false` would probably be your best bet.
