### ISSUE TITLE
custom taxonomy terms in the select field?

### ISSUE THREAD

**Issue by dariodev** [reduxframework/redux-framework#194]
I'm trying to get custom taxonomy terms in the select field. I need terms from pretty common taxonomy - "product_cat" (WooCommerce). If it is impossible to get with custom cofig, would be nice to see it in the core.

For now I have partial solution, I've tweaked the function get_wordpress_data()... which works but only in single installation. In multisite only first site will get the terms. 

```
function get_wordpress_data($type = false, $args = array()) {
...                   
} else if ($type == "product_cat" || $type == "product_cat") {
    // $terms = get_terms($args); // this will get nothing
    $terms = get_terms("product_cat"); 
    if (!empty($terms)) {       
        foreach ( $terms as $term ) {
            $data[$term->term_id] = $term->name;
        }//foreach
    } // If
```

I'm sure @dovy  have a one-liner :)

**Comment by anup04sust** [comment]
it will be helpful.
http://screencast.com/t/FMbuvbSGJB
http://screencast.com/t/Zg6rb6n8b

**Comment by ayyazzafar** [comment]
Thanks @anup04sust  Your reply was really helpful.
I spent several hours to get this solution. You saved my time.
Thanks a lot :)

**Comment by aligos** [comment]
hallo everyone, i use @dariodev code to get categories select from product_cat, yes it works, but i don't know for use on theme/html.
i want get url/link and product categoriest name can be show
i use this, but don't work
 <?php global $redux_demo;
                $featured_url_2 = $redux_demo['products-group-2']['url'];
                $featured_image_2 = $redux_demo['media-no-url-2']['url'];
                $featured_text_2 = $redux_demo['products-group-2']['title'];
            ?>      
                <a href="<?php echo $featured_url_2; ?>" class="thumbnail mythumb">
                            <img src="<?php echo $featured_image_2 ;?>" alt="...">
                            <div class="caption post-content">

                                <h3><?php echo $featured_text_2 ;?></h3>

                            </div>
                        </a>

**Comment by ArsooCh** [comment]
Hello, If someone is getting issue while hide_empty bringing are taxonomies. 
This works for me
`array(
	'id' => 'footer_area',
	'type' => 'select',
	'title' => __('Select Locations', 'text_domain'),
	'multi' => true,
	'data' => 'terms',
	'args' => array('taxonomy' => 'service-locations','hide_empty' => false,),
	),`
