### ISSUE TITLE
Date Picker is not Positioned correctly

### ISSUE THREAD

**Issue by towfiqi** [ReduxFramework/redux-framework#1941]
The Datepicker is shown few hundred pixels below the date field on the theme options page. This only happens with the latest version of redux. 

![Datepicker Issue](http://i.imgur.com/HFoCrlq.png)

Have tested this on 3 different redux installation. Here are the details:

Redux :             3.3.9.30
WordPress :      4.1
Browser:           Chrom ver- 39.0.2171.95 /Firefox ver- 34.0.5
OS:                    Windows 7

Thanks

**Comment by kprovance** [comment]
Fix in latest push to our git.

**Comment by hiskynet** [comment]
((I think I have issue related))

using Exploore template that depends on Redux framework

datepicker show wrongly after I updated to wordpress 4.8, installed eventon plugin, and then removed still the datepicker showing wrongly.

I tried few solutions to update jQuery libraries. but still same issue

hi-sky.net
