### ISSUE TITLE
Comments not showing on home page

### ISSUE THREAD

**Issue by annemartin** [ReduxFramework/redux-framework#1949]
I would like my comments to show on the main page and also show whole posts on the main page and remove the continue reading field. However, I cannot find any way of doing this. Any ideas? 

http://www.elizaquixote.com

**Comment by kprovance** [comment]
This is a support forum for Redux Framework.  General PHP/Wordpress questions should be directed to a forum more appropriate to them.

**Comment by annemartin** [comment]
Thanks.
