### ISSUE TITLE
Can`t use function.php`s function in my sample-config file. 

### ISSUE THREAD

**Issue by ishanshah1991** [ReduxFramework/redux-framework#1950]
Hello,
I Have install my redux framework in my local environment. what i am going to do is i am went to just include one file that belong to function.php and from that i am returing html to use in sample-config.php. but in included file i cant use function.php`s function on that file.
How should i have to use that functions in my file?

**Comment by kprovance** [comment]
I'm sorry, but I honestly have no idea what you are attempting to ask.  Please review out posting guidelines and open a new ticket with the correct information.  Thanks!
