### ISSUE TITLE
Select - List of Pages by Template

### ISSUE THREAD

**Issue by scrollmapper** [ReduxFramework/redux-framework#1952]
Hey Redux heros, quick question - 

                  'fields' => array(                                                
                        array(
                            'id'       => 'opt-homepage',
                            'type'     => 'select',
                            'data'     => 'page',
                            'args'     => array(
                                'post_type'  => 'page', 
                                array(
                                    'meta_key' => '_wp_page_template',
                                    'meta_value' => 'templates/page-home.php'
                                    )
                                ),
                            'title'    => __('Select Option', '_lp'),
                            'subtitle' => __('No validation can be done on this field type', '_lp'),
                            'desc'     => __('This is the description field, again good for additional info.', '_lp'),
                        ), 

As you can see here, I'm simply trying to make a select option of home page templates set by the user. Where am I going wrong?

**Comment by kprovance** [comment]
Looking at this as it stands, I do not know.  Unless it's a bug in out system, this'll fall under premium support.  Unless @Dovy could tell you at first glance.

**Comment by scrollmapper** [comment]
Actually this was my mistake - basic wordpress stuff - found answer here - 

http://wordpress.stackexchange.com/questions/29918/page-template-query-with-wp-query

**Comment by dovy** [comment]
Glad you found an answer.  ;)
