### ISSUE TITLE
Cannot redeclare class scssc

### ISSUE THREAD

**Issue by mattrace** [ReduxFramework/redux-framework#1953]
Receiving this error when accessing a page using the metaboxes extension(1.2.9) and the latest redux release. The error only started happening after upgrading redux. Please let me know if this is an issue that has been seen before. Currently I'm struggling to figure out what exactly is causing it. 

PHP Fatal error:  Cannot redeclare class scssc in /wp-content/themes/themename/core/options/inc/scssphp/scss.inc.php on line 45

**Comment by dovy** [comment]
Pull the latest update. I've put a fix in there.  ;)

**Comment by mattrace** [comment]
Pulled the latest, still seeing that error oddly enough.

**Comment by dovy** [comment]
Umm, that means another plugin is running it without error checking...

**Comment by mattrace** [comment]
hmm.. no plugins installed. Only redux, redux customizer, and redux extensions. I only get that error when it tries to load an admin page with the metaboxes extension on it.

**Comment by dovy** [comment]
Umm, did you pull from the repo and grab the latest release?

**Comment by dovy** [comment]
Skype? DovyDigital

**Comment by mattrace** [comment]
That new fix worked great, thanks Dovy!

**Comment by dovy** [comment]
Glad I could help.
