### ISSUE TITLE
Error found 

### ISSUE THREAD

**Issue by alisiddique** [ReduxFramework/redux-framework#1955]
NOTICE: E:\SERVER\XAMP\htdocs\WP\THEME-CHECK\wp-content\themes\twentyfifteen\libs\ReduxCore\inc\fields\color_rgba\field_color_rgba.php:251 - Undefined variable: rgba

**Comment by kprovance** [comment]
Please go back and review our posting guidelines, and include the required information.

**Comment by kprovance** [comment]
Fix in v3.3.9.34
