### ISSUE TITLE
function to return option value

### ISSUE THREAD

**Issue by krishna19** [ReduxFramework/redux-framework#1956]
is there any function to return option value ?
example : <code>redux_option( 'option_id', 'param' );</code>

**Comment by kprovance** [comment]
This?  http://docs.reduxframework.com/core/advanced/update-an-option-outside-the-options-panel/  Only instead of `set`, use `get`.  That's about as close to it as we have.

**Comment by krishna19** [comment]
i check a theme, the developer use a function like this. is it works or not ?
<pre>
	function redux_options($id, $fallback = false, $param = false ) {
		global $redux_options;
		if ( $fallback == false ) $fallback = '';
		$output = ( isset($redux_options[$id]) && $redux_options[$id] !== '' ) ? $redux_options[$id] : $fallback;
		if ( !empty($redux_options[$id]) && $param ) {
			$output = $redux_options[$id][$param];
		}
		return $output;
	}
</pre>

**Comment by kprovance** [comment]
I don't know.  If you want me to debug your code, you'll need to purchase premium support from us.
