### ISSUE TITLE
image_select issue

### ISSUE THREAD

**Issue by zutigrm** [ReduxFramework/redux-framework#1958]
I'm trying to add my own images to the image_select type option, but with no luck. 
I uploaded my images to the assets/img folder, and called them the same way given in the provided demo:
'options'  => array(
                                '1 => array(
                                'alt' => 'Image to the left',
'img' => ReduxFramework::$_url . 'assets/img/cta-right.png'
),
But all I get is a broken image picture.
![redux1](https://cloud.githubusercontent.com/assets/10414808/5627118/9530affc-9594-11e4-9911-2892d1266920.png)
 I tried to load them from my theme images directory, then resizing them to smaller (60x40px, originaly they are 120x80px), clearing the cache, even renaming one of them with the name of the existing image (3-col-portfolio.png), but still nothing. Except with the last case, after renaming the image, I would still get the default one, even if it does not exist in the folder any more.
![redux2](https://cloud.githubusercontent.com/assets/10414808/5627125/b3a10356-9594-11e4-9c79-576d972a9dcd.png)

Does anyone knows the solution for this?

Thanks in advance,
Aleksej

**Comment by zutigrm** [comment]
lol o.O, I pasted images to the old theme folder, instead of the current one. Sorry, my bad.

**Comment by dovy** [comment]
Haha. Glad you solved it.

If you're happy with Redux please do some or all of the following:
* Review us: http://wordpress.org/support/view/plugin-reviews/redux-framework
* Like us: http://facebook.com/ReduxFramework
* Follow us: http://twitter.com/ReduxFramework

Oh and check out our extensions to take Redux to a whole new level! http://reduxframework.com/extensions/
