### ISSUE TITLE
filemtime() in admin panel and  Invalid argument supplied for foreach() class.redux_functions.php on line 53

### ISSUE THREAD

**Issue by liquida** [ReduxFramework/redux-framework#1964]
Hello guys i just made the update to 3.3.9.34 to see if it solves the issue with the google fonts when you have two instance of redux

but i have many errors

admin panel -------------------------------------------------------------------------------------------------------------

Warning: filemtime(): stat failed for /home/themes/public_html/wp-content/plugins/lmm/ReduxCore/assets/js/vendor/select2/select2.css in /home/themes/public_html/wp-content/plugins/lmm/ReduxCore/framework.php on line 1652

Warning: filemtime(): stat failed for /home/themes/public_html/wp-content/plugins/lmm/ReduxCore/assets/js/vendor/select2/select2.min.js in /home/themes/public_html/wp-content/plugins/lmm/ReduxCore/framework.php on line 1671

Warning: filemtime(): stat failed for /home/themes/public_html/wp-content/plugins/lmm/ReduxCore/assets/css/vendor/elusive-icons/elusive-webfont.css in /home/themes/public_html/wp-content/plugins/lmm/ReduxCore/framework.php on line 1708

Warning: filemtime(): stat failed for /home/themes/public_html/wp-content/plugins/lmm/ReduxCore/assets/css/vendor/elusive-icons/elusive-webfont-ie7.css in /home/themes/public_html/wp-content/plugins/lmm/ReduxCore/framework.php on line 1716

Warning: filemtime(): stat failed for /home/themes/public_html/wp-content/plugins/lmm/ReduxCore/assets/css/vendor/qtip/jquery.qtip.css in /home/themes/public_html/wp-content/plugins/lmm/ReduxCore/framework.php on line 1724

Warning: filemtime(): stat failed for /home/themes/public_html/wp-content/plugins/lmm/ReduxCore/assets/css/vendor/jquery-ui-bootstrap/jquery-ui-1.10.0.custom.css in /home/themes/public_html/wp-content/plugins/lmm/ReduxCore/framework.php on line 1740

Warning: filemtime(): stat failed for /home/themes/public_html/wp-content/plugins/lmm/ReduxCore/inc/fields/slider/vendor/nouislider/redux.jquery.nouislider.css in /home/themes/public_html/wp-content/plugins/lmm/ReduxCore/inc/fields/slider/field_slider.php on line 22

frontend -------------------------------------------------------------------------------------------------------------

Warning: Invalid argument supplied for foreach() in /home/themes/public_html/wp-content/plugins/lmm/ReduxCore/inc/class.redux_functions.php on line 53

redux 3.3.9.34 in embeded mode

**Comment by kprovance** [comment]
Why are you embedding two instances?  Why are you not using the plugin, so both theme and plugin can share the same class?  To debug something like this will require one of us installing your theme and plugin and spending a fair amount of time going through it all, and that will fall under premium support.

**Comment by dovy** [comment]
Actually this is a server issue. Fix your permissions.

**Comment by liquida** [comment]
hello dovy, do you have any idea of what can cause this issue in the server?

**Comment by kprovance** [comment]
This what we're attempting to impart to you.  It's too broad a question.  It's like calling a mechanic and asking where to look at a car engine because it won't start.  It's something that has to be looked at, specifically, not something we can simply guess at.  This is why we are put in a position of asking our time be compensated, because it could potentially take quite a bit of it.

**Comment by liquida** [comment]
ok i understand, where can i hire the premium support ? 

i need help with this issues, the fonts issue, and a way to set the defaults values of a dynamic section before the panel be created

**Comment by dovy** [comment]
Only suggestion I can make is to install redux via the plugin installer (not ftp) and/or your theme as well. Sounds like your web server is running on a diff user than your ftp and php has no rights to that user account. 

This is the best I can do without extensive debugging. :-/

**Comment by dovy** [comment]
Premium support is on our extensions page.

**Comment by liquida** [comment]
ok i found it, do you think we can solve all this issues through the premium support ?

**Comment by dovy** [comment]
Probably. I'm 99% sure it's a server issue.

**Comment by liquida** [comment]
i mean this, and the other issues

2) google fonts not loading in theme redux instance https://github.com/ReduxFramework/redux-framework/issues/1927#issuecomment-68153574
3) set default values of dinamyc section trought the filters https://github.com/ReduxFramework/redux-framework/issues/1935

**Comment by dovy** [comment]
We'll do what we can. We'll dig in a little. If it's more complex and we think it will take longer than an hour we'll let you know.

**Comment by liquida** [comment]
hello dolly, i can hire the premium service, but im sure that arent issues on my development

1) the filetime issue according to my server support is a develpment issue

"Webserver is running under user 'nobody'

"This is more likely a coding error. This usually happens when the directory or file paths are not properly given in a program. Can you please check with your developer regarding this? Following links might be helpful."

this issue was not present on the previous versions of redux, i think filemtime in the scripts is unnecesary, and can cause this issue in users with my server config, 
anyway youre the developer

2) ive included redux in the plugin mode and the fonts aren't loading

3) the error on class.redux_functions.php on line 53 is a coding error

here is the solution

if (!is_array($cssArray) || count($cssArray) == 0) {
                return;
            }

**Comment by dovy** [comment]
Whenever you grab premium support and pass us ftp/wordpress/files we'll get to it.

But to answer your above statements:

1) filemtime works for thousands of users right now... No one has reported an issue but you. I bet there's something off on your end or your web host or you didn't follow the steps before.

Does 'nobody' and PHP have access to those file or not? Did you follow any steps I suggested? Have you tried chmod?

2) Probably a hook issue on your end

3) Agreed. But probably tied to a hook issue and will be resolved the moment the hooks fire properly.
