### ISSUE TITLE
multi_media extensions work in wp mu?

### ISSUE THREAD

**Issue by massimoxma** [ReduxFramework/redux-framework#1967]
I purchase the extension. Load it on theme generated with redux builder and work well.
When load in theme with wordpress Mu don't appear nothing.
Check the folder path and the extensions class: 

print_r ($folders); and echo $extension_class; all seems ok....

any suggestion?

**Comment by massimoxma** [comment]
close resolved, wrong configuration file

**Comment by massimoxma** [comment]
Close resolved wrong configuration

**Comment by kprovance** [comment]
Under what email address did you purchase this extension?  I see no record any one purchasing it, so I'm wondering where you got it from.

**Comment by massimoxma** [comment]
massimo1001110 gmail
