### ISSUE TITLE
Hints Icon Not Showing

### ISSUE THREAD

**Issue by Jim-E** [ReduxFramework/redux-framework#1968]
Redux v3.3.9.36 and the 3.3.9.4 plugin
WP v4.1
Redux Builder

For hints In options-init.php: ````'icon' => 'el-icon-question-sign'```` doesn't work

In firebug the html is showing ````<i class="el-el-icon-question-sign"></i>```` has one too many ````el-````

Change options-init.php to ````'icon' => 'icon-question-sign'```` and it works

Just thought I would put that out there.

framework.php 2366:287 change ````<i class="el-'```` to ````<i class="'````

**Comment by kprovance** [comment]
The problem is, if I change that HTML in the framework.php, it's going to break for everyone who is currently using the feature.  Did you use the builder to create that options-init?  If so, that can be fixed.  In the interim, remove the el- from your icon argument.

**Comment by Jim-E** [comment]
Yes I used the builder, and the docs say ````'icon'  => 'icon-question-sign'```` so you are correct, the builder needs a tweak.

**Comment by kprovance** [comment]
Okay, will tweak and update builder.  Thanks.  :)
