### ISSUE TITLE
Multiple fields in a single array

### ISSUE THREAD

**Issue by ehrig** [ReduxFramework/redux-framework#1971]
How can I save multiple fields in a single array, rather than creating eight unique fields?

**Comment by kprovance** [comment]
Through Redux, you cannot.

**Comment by dovy** [comment]
Actually... you can... Give me one min...

**Comment by dovy** [comment]
Something like this will work.

```
array(
                            'id'       => 'opt-text-data',
                            'name'       => 'OPT_NAME[testgroup][opt-text-data]',
                            'type'     => 'text',
                            'title'    => __( 'Text 1', 'redux-framework-demo' ),
                        ),
                        array(
                            'id'       => 'opt-text2-data',
                            'name'       => 'OPT_NAME[testgroup][opt-text2-data]',
                            'type'     => 'text',
                            'title'    => __( 'Text 2', 'redux-framework-demo' ),
                        ),
```

Just replace OPT_NAME with your actual opt_name or it won't work.

**Comment by ehrig** [comment]
I replaced OPT_NAME witht the opt_name of my theme options panel, but I just can't figure out how to output "testgroup" on the frontend.

**Comment by dovy** [comment]
Print_r() and use the test group as your key for the global variable. It's not in my job description to teach you php arrays. ;)

Best of luck!

**Comment by ehrig** [comment]
I tried <code>print_r( $OPT_NAME['testgroup'] );</code>, and I replaced OPT_NAME with my actual theme options opt_name, but all I receive is "Notice: Undefined index: testgroup". I also looked up for "testgroup" in my WP database, and 0 results came up. I am using Redux v3.3.9.6

**Comment by kprovance** [comment]
testgroup is an example given to you.  You need to declare your own.

**Comment by ehrig** [comment]
I am using @dovy code snippet and thought 'name' will add the [testgroup] array to my db, which it doesn't. Any other field in my db equals to its Redux 'id'. I am not sure where and how to declare my 'testgroup' array. Any help is very much appreciated.

**Comment by kprovance** [comment]
Unfortunately, since we are not PHP tutors, and since this is not a bug in our framework, request for this kind of help falls under premium support.

**Comment by ehrig** [comment]
Got it. Just thought its a simple one line answer or actually part of the official Redux documentation.

**Comment by dovy** [comment]
Sorry @ehrig, this is more an an advanced, undocumented feature. I gave you have we use for our "repeater" field that's in development. This functionality is not fully supported, but it does work. You're just going to have to dig around a bit or buy premium support to have us take the time for you specifically.  ;)

**Comment by ehrig** [comment]
Done. How can I get in touch with you guys?

**Comment by ehrig** [comment]
I have purchased premium support for $75 a day ago, on http://reduxframework.com/, how can I contact you @dovy ? Unfortunately the site doesn't make a good job explaining this.

**Comment by dovy** [comment]
@ehrig I take Sundays off for religious reasons. You can reach out to me on Skype today: DovyDigital or email: dovy@reduxframework.com.

**Comment by ehrig** [comment]
Will do, sorry I didn't realize it was a sunday ;-)

**Comment by dovy** [comment]
Solution shipped to you.  ;)

**Comment by souravh093** [comment]
Dovy, I am really happy with your work. Thank you very much.

**Comment by dovy** [comment]
Thanks @souravh093. You should check out Redux 4, it's release is so very very soon.  :) https://github.com/reduxframework/redux-framework-4
