### ISSUE TITLE
Using required argument to type info

### ISSUE THREAD

**Issue by nicolas92** [ReduxFramework/redux-framework#1972]
Hello, is it possible to use the argument "required" to a type info?
I tried the following code but it does not work:

<pre>array(
	'id'	=> 'multi-info',
	'type'	=> 'info',
	'title'	=> false,
	'desc'	=> __( 'Light/Dark Logo', 'Aktina' ),
	'required'	=> array( 'header_style', 'equals', 'transparent' ),
),</pre>

Thank you.

**Comment by kprovance** [comment]
Please supply the information required by our posting guidelines.

**Comment by nicolas92** [comment]
Sorry, I misunderstood, I would just bring up a title when an option is enabled, but require does not work on an info type.
