### ISSUE TITLE
Problem reset section

### ISSUE THREAD

**Issue by nicolas92** [ReduxFramework/redux-framework#1973]
Hi, I've updated to 3.3.10 redux version, when I click reset section I have the following error message:

Warning: Invalid argument supplied for foreach() in /public_html/aktina/wp-content/themes/Aktina/framework/redux/redux-core/framework.php on line 2551

Warning: Cannot modify header information - headers already sent by (output started at /public_html/aktina/wp-content/themes/Aktina/framework/redux/redux-core/framework.php:2551) in /public_html/aktina/wp-includes/pluggable.php on line 1178

Can you help me?
Thank you.

**Comment by kprovance** [comment]
Unable to reproduce.

**Comment by kprovance** [comment]
Unable to reproduce.

**Comment by nicolas92** [comment]
What? I have to do?
You want me you create an admin and ftp account so you can see the problem?

**Comment by kprovance** [comment]
Maybe Dovy will know.

**Comment by nicolas92** [comment]
Ok, how can I contact Dovy?
Thank you.

**Comment by kprovance** [comment]
He'll be along when he get's up.  Also, it would be considerably more helpful to see the section code, as was required by our posting guidelines.  Please review them and supply the required information.

**Comment by nicolas92** [comment]
Ah, ok, sorry I did not see the posting guidelines.
redux version: 3.3.10
wordpress Version: 4.1
dev_mode: false
I use redux directly into my theme
Here are error when I click reset section:

Notice: Undefined index: redux-section in /public_html/aktina/wp-content/themes/Aktina/framework/redux/redux-core/framework.php on line 2551

Notice: Undefined index: in /public_html/aktina/wp-content/themes/Aktina/framework/redux/redux-core/framework.php on line 2551

Warning: Invalid argument supplied for foreach() in /public_html/aktina/wp-content/themes/Aktina/framework/redux/redux-core/framework.php on line 2551

Warning: Cannot modify header information - headers already sent by (output started at /public_html/aktina/wp-content/themes/Aktina/framework/redux/redux-core/framework.php:2551) in /public_html/aktina/wp-includes/pluggable.php on line 1178

I can create an admin and ftp account, if you like?
Thank you.

**Comment by kprovance** [comment]
If Dovy wants to do the FTP thing, that's his prerogative.  I however, again, still would like to see the actual field code you are using.  If it's too long to post, using the Gist feature.

**Comment by nicolas92** [comment]
Yes, I'm stupid, that's better :)
I uploaded the file on mega:
https://mega.co.nz/#!VY5wzRBJ!hWDSleVqN2zRWui-kFlw7hjIgocO68IvXmMoz3VF5GY

**Comment by kprovance** [comment]
I can't just plug that in and try it since it is specific to your theme.  Too many errors.  I just need the SECTION code for the section you say is not working.  Is it only one section in particular, or all?  This is what I mean by detailed information.  If I can't reproduce it, I can't fix it or tell you what may be wrong.

Or, let's just wait for Dovy.  He made changes to that section of the code recently.  He'll probably know.

**Comment by nicolas92** [comment]
The error occurs in all sections.
If Dovy is available, I am willing to wait., if it does not work I would come back to the previous version, the time that everything is resolved.

**Comment by dovy** [comment]
Try going into framework.php and commenting out these lines: 
```
                if (isset($this->validation_ran)) {
                    return $plugin_options;
                }
                $this->validation_ran = 1;
```

If it works after that, then I know what to do.  ;)

**Comment by nicolas92** [comment]
Hi, I tried and I a error:
Using $this when not in object context

**Comment by dovy** [comment]
Just fixed it. It was my own error. Pull the new version. Sorry.

**Comment by nicolas92** [comment]
Hi, I confirm, it works perfectly, the best framework, thank you :)

**Comment by dovy** [comment]
Glad we got it. Thank you for being patient.

If you're happy with Redux please do some or all of the following:

Review us: http://wordpress.org/support/view/plugin-reviews/redux-framework
Like us: http://facebook.com/ReduxFramework
Follow us: http://twitter.com/ReduxFramework
Oh and check out our extensions to take Redux to a whole new level! http://reduxframework.com/extensions/

**Comment by nicolas92** [comment]
I come now to note 5 stars redux plugin, I already following you on twitter and I'm about to buy two extensions :)

**Comment by dovy** [comment]
Thanks! This year great things will happen with Redux.  ;)
