### ISSUE TITLE
Notice: Undefined index... on first activation

### ISSUE THREAD

**Issue by nova-ind** [ReduxFramework/redux-framework#1977]
Hi!

I am using WP 4.1 and Redux 3.3.10.1 in dev mode. Redux is embedded in the theme I'm developing.

So upon creating a new MU site and activating my theme on it, I get these 2 notices:

Notice: Undefined index: menu_type in THEME_PATH\ReduxCore\inc\class.redux_filesystem.php on line 78
Notice: Undefined index: page_slug in THEME_PATH\ReduxCore\inc\class.redux_filesystem.php on line 82

I didn't get any notices before updating today, and I checked my config, both options are defined.

**Comment by dovy** [comment]
Can you get me server access? I'd love to test it out quick.

**Comment by dovy** [comment]
Actually, can you just do this for me? Go to line 76 of class.redux_filesystem.php and type the following:
```
                if (!isset($this->parent->args['menu_type']) || empty($this->parent->args['menu_type'])) {
                    print_r($this->parent->args);
                    exit();
                }
```

Then paste me the blank page's values here please. This is all I need to debug. I'm pretty sure I know what to do, just don't have a multi-site instance sitting around.  :)

**Comment by nova-ind** [comment]
Hmm, it just returned an empty array ("Array ( )").
The server is local, so I can't give you access :)

**Comment by dovy** [comment]
That's what I needed. Do this then. Take that code I just gave you out, and put this at the top of this function:

```php
            public function execute( $action, $file = '', $params = '' ) {

                if ( empty( $this->parent->args ) ) {
                    return;
                }
```

Then tell me how that goes. Pretty sure that will resolve it.  ;)

**Comment by nova-ind** [comment]
Yep, that did the trick!
Thanks for the quick reply and keep up the ~~good~~ great work!

**Comment by dovy** [comment]
I'll push it to core then.  ;)
