### ISSUE TITLE
Theme customizer hidden sections?

### ISSUE THREAD

**Issue by alessandrotesoro** [ReduxFramework/redux-framework#1978]
Redux Framework 3.3.9.4
WordPress 4.1
Redux not in dev_mode
Redux is embedded

Hello,
I've searched for previous issues, the issue is the same as this one here #1917 however, the solution to comment out that section of the code mentioned into that issue, does not work. 

This is what happens:

--- Code not commented out (original redux code) ---
The redux customizer sections show up for a second and then they're set to "display:none" automatically.

--- Code commented out as per issue #1917 "solution" ---
The redux customizer sections do not load at all.

Any plans when the issue is planned to be fixed or alternative solutions?

Thank you.

**Comment by dovy** [comment]
Install the plugin from this repo. It's working, we're just making sure everything is working before we push to WP.org.
