### ISSUE TITLE
Google font loader

### ISSUE THREAD

**Issue by abukwaik** [ReduxFramework/redux-framework#1979]
Wordpress version: 4.1
ReduxFramework version: 3.3.10.1
dev mode: false
google api key: yes
using Redux:  embedded in a project.

Hello guys, Just upgraded to the latest version, and then the Google font loader stop working.

I'm working on local server using "wamp server" and google api key already activated.
Would you help please if i miss something?

Thank you

**Comment by kprovance** [comment]
#1975

**Comment by abukwaik** [comment]
@kprovance  Thank you.

**Comment by kprovance** [comment]
Resolved in v3.9.10.2 push

**Comment by abukwaik** [comment]
Thank you very much!
