### ISSUE TITLE
Sorter Issue - Undefined 

### ISSUE THREAD

**Issue by scrollmapper** [ReduxFramework/redux-framework#1980]
A small issue has popped up - the sorter is not saving "enabled" to the enabled part of the sorter's array. Checking the console, it appears there is an issue:

TypeError: selector is undefined
	
var scrollable = selector.find( ".redux-sorter" );

This seems to have popped up out of nowhere. Are there any obvious things that can cause this?

**Comment by kprovance** [comment]
#1975

**Comment by kprovance** [comment]
Fixed in v.3.3.10.3.

**Comment by scrollmapper** [comment]
Thank you.
