### ISSUE TITLE
TO ALL DEVS - PHP VERSION 5.3 FORCED?

### ISSUE THREAD

**Issue by dovy** [reduxframework/redux-framework#1981]
PHP 5.2 is DEAD and has been dead for years. We're thinking of recoding Redux to be 5.3 compliant only.

For many devs out there this may be a problem. The issue lies in the fact that we spend SO much time making everything 5.2 complaint when it could be an easy fix as most hosts support 5.2.

What we would do, is follow [Parallelus](http://themeforest.net/forums/thread/php-53-requirement-on-theme/122342) and others. We'd give the users an alert that they need to update to 5.3.

Thoughts?

**Comment by teamcrisis** [comment]
While I would absolutely love to support only new technology (yeah, I know, php 5.3 isn't "new" either), I don't think this is a good move at this time.

Does anyone know if this page is up-to-date and accurate? https://wordpress.org/about/stats/

If so, I'm sad to say, nearly 33% is not a number that can simply be ignored because us dev don't want to support it anymore. The simply fact is, the end user does not care their server is using php 5.2 or any other version for that matter. If they did, v5.2 would probably have died off several years ago.  

I don't think this situation is much different than frontend developers continuing to support IE8, solely because the usage stats were still over 10% (until the last year or two)

**Comment by dovy** [comment]
The only argument I have is that 99% of the hosts that "are 5.2" have an option to change versions in their .htaccess files. So... Really it's much less than 33%. That's just the default. 5.2 was killed off in 2011. This is more than old as far as the internet goes...

**Comment by teamcrisis** [comment]
I completely agree and know that to be true. However, this would greatly increase support request to theme developer, even though a settings change in cpanel is all that is needed to fix the problem. Even if Redux or the theme developer were to provide a basic how-to in the v5.3+ message, I don't see it helping much with support request.

Maybe some of the developers with large customer bases can weigh in on the support side of things?

**Comment by dovy** [comment]
The issue we have is we're having to cripple features and add more code to keep 5.2 support. Also major plugins are going to 5.3 exclusively. We want to make that jump as well.

**Comment by dovy** [comment]
And I KNOW that if 3 or 4 of the major plugins and/or WordPress itself forced 5.3 or (gasp) 5.4 90% of the hosts would suddenly change their default versions.

**Comment by teamcrisis** [comment]
Agreed. But until hosts get off their butts (and WP) I'm not sure theme devs want to (or have the ability to) handle the influx of support requests this may end up casing. I can't say the total impact this change may cause. I currently use redux only for custom client work, but I plan to release a theme to the evato community soon, and I fear this change may cause a support problem for everyone.

I could be wrong, so hopefully successful theme devs can weigh in, but my current stating is until WP takes the stance of 5.3+, a few plugin and theme developers aren't going to fix the issue. That has to happen via WP itself and hosting companies.

**Comment by dovy** [comment]
TF allows you to require PHP 5.3 as per the post noted above.

http://themeforest.net/forums/thread/php-53-requirement-on-theme/122342

;)

**Comment by teamcrisis** [comment]
So it seems evanto just wants you to clearly note it on the theme page (seems like an obvious things to do). I just wonder how many end users are going to actually pay attention to the notice and actually understand what it means before they buy the theme and put in a support request.

I think some devs would simply say "not my problem", but that kind of response doesn't work for me.  

I still need some decent stats about how large an issue this might cause with envato customers. Parallelus states about 1%, but is this an edge case or the rule for the envato community?

**Comment by farhanhu87** [comment]
can we reset a cookie save button is press in redux ???

**Comment by dovy** [comment]
@farhanhu87 First we can't understand what you're asking and second don't piggyback issues that have NO relevance to the question you're asking.

**Comment by corradomatt** [comment]
I say go for it, but then I'm biased and have no clients to support other than myself and I'm fortunately enough to know which version of PHP I'm on. ;)

**Comment by farhanhu87** [comment]
dear sir,
if we go to the admin panel and and there we have create a select option and when we select that option it will come but if we press the cross then it show nothing, i want that when we press the cross then show the default value, how to do this??
thanks

**Comment by kprovance** [comment]
1) Please do not piggy back on unrelated tickets.  2) What you posted makes NO sense at all.  Please refer to the posting guidelines when creating your own ticket and supply the required information.  Click NEW TICKET and click Guidelines for Contributing for the information required.

**Comment by farhanhu87** [comment]
sorry for that i was no idea before,
Thanks

**Comment by justnorris** [comment]
Although a move to 5.3 seems a bit scary ( all those support tickets...ugh...ogh... ) - Namespacing and anonymous functions would be a welcome addition to my every-day PHP development :)

And here is the deal - if more big open-source projects ( like Redux ) move to PHP 5.3 requirement, it's going to help push > 5.3 in mainstream. I just hope Wordpress takes that plunge someday too :)

It's a though choice, but I'm with you on this one @dovy

**Comment by dovy** [comment]
*sigh* We'll see. I think we'll stick with 5.2 for a bit longer. Redux 4 will be 5.3 though.

**Comment by kprovance** [comment]
Since we made the call, let's close this thing.  It's taking up space on my tracker.  :P
