### ISSUE TITLE
Demo account?

### ISSUE THREAD

**Issue by rclai** [ReduxFramework/redux-framework#1982]
http://demo.reduxframework.com/wp-admin/

**Comment by kprovance** [comment]
Yes, I see one.  And?

**Comment by rclai** [comment]
Nevermind, I just saw the button at the top right to create sandbox.

**Comment by kprovance** [comment]
Okay, well, for future reference, posting a link - and nothing else - isn't adhering to our posting guidelines.  It's also helpful to include a description of the issue you are having.  Thanks.
