### ISSUE TITLE
color_rgba option not working

### ISSUE THREAD

**Issue by ghostpool** [ReduxFramework/redux-framework#1983]
WordPress 4.1
Redux: 3.3.10.4
Integrated into theme

Hi there,

I'm using the following code to generate a semi transparent background colour:

	array(
		'id'        => 'main_header_scrolling_bg',
		'type'      => 'color_rgba',
		'title'     => __( 'Scrolling Background', 'gp_lang' ),
		'desc'  => __( 'The scrolling main header background.', 'gp_lang' ),
		'output' => array( 'background-color' => '.gp-scrolling #sub-header' ),
		'default'   => array(
			'color' => '#fff',
			'alpha' => '0.9',
		),
	),

However when I look at the output code it only returns this:

	.gp-scrolling #sub-header {
	background-color: ;
	}

The rgba value is not output.

**Comment by kprovance** [comment]
Fixed in v.3.3.10.5  :)
