### ISSUE TITLE
How to use both TGM and Embed css when images have changed ?

### ISSUE THREAD

**Issue by userseventeen** [ReduxFramework/redux-framework#1984]
i got redux set up suggest + embed style and made some changes like the images used in options and a little bit of css.

but when theme is installed, everything seems fine till Redux plugin install suggestion appears.

when user activates plugin (TGM) it overrides my images and css files.
before activation = "my theme/admin/assets/img/category.png" turns into sth like
wp-content/plugins/redux/assets/img/category.png 

How to solve that ?

**Comment by kprovance** [comment]
#1975

**Comment by userseventeen** [comment]
so do i need to buy premium support just for that ?

**Comment by FiGO-** [comment]
@userseventeen  He wasn't necessarily specifically suggesting that you need to buy premium support he's pointing the fact that you have not given any information regarding your redux version, wordpress version, etc  which is outlined in the <a href="https://github.com/ReduxFramework/redux-framework/blob/master/CONTRIBUTING.md">Contributing Guidelines</a> for posting issues.  thats all.

**Comment by kprovance** [comment]
Exactly, thank you @FiGO- .  It's became a real problem for us, folks dropping 'one liners' and expecting us to know exactly what is going on.  It doesn't work that way.

**Comment by userseventeen** [comment]
alright then thanks for your polite(!) answers , my bad.
wp : latest
redux : latest

i thought you wouldn't have had need these infos when replying the question

**Comment by kprovance** [comment]
Seriously?

<blockquote>
The version of Redux you are using. Please do not say 'the latest version' as what you perceive as the latest and what might be the latest could easily be two different things. At the bottom of the Redux options panel is a four digit version number. Please include it.
</blockquote>

**Comment by FiGO-** [comment]
@userseventeen  
Below is  a basic example based on instructions from <a href="https://github.com/ReduxFramework/redux-framework/blob/master/CONTRIBUTING.md">Contributing Guidelines</a> 

Redux Version:	3.3.10.6
WordPress Version:	4.1
dev_mode:	false
Redux Embedded:	Redux Embedded in my theme
Console Errors:	None

**Comment by userseventeen** [comment]
Redux Version: v3.3.9.4 
WordPress Version: 4.1
dev_mode: false
Redux Embedded: Redux Embedded in my theme
Console Errors: None

**Comment by dovy** [comment]
Lo and behold, Redux is up to 3.3.10.6. 

We don't modify anything TGM related. What do you mean by override? Please give some actual details and maybe even screenshots.

**Comment by userseventeen** [comment]
when i install my theme (before activating with tgm) the images and css files that i've modified are as i want.

after activating with tgm redux becomes the same (default) images and css files.(my options stills same)

say i made body{background:red} in my embedded redux , after  plugin activation it turns to default again.

**Comment by dovy** [comment]
Dude. You have to explain what fields your using. If you made the theme. Anything. You're not giving us much to go off of.

**Comment by userseventeen** [comment]
i do not have any single idea how to put it clearer.

but let me try this way.

i generated a redux for my theme in suggest + embed way. (Stage 1)

i downloaded and embedded it correctly , ignored the alert(you should install the plugin redux) (Stage 2)

and i've made some changes like main layout images (i changed your default image and uploaded it to mytheme/admin/redux/blabla/img) till now everything works perfect.

i also changed a little bit of css , no problem neither.

but when the user installs my theme a wordpress site , that alert box appears again and says install redux plugin.

user clicks and installs fresh redux.

at this point my changes are gone.the images i've prepared are gone.

before installing plugin (embed) : main layout option image is under (mytheme/admin/blabla/img/layout.png)

after installing plugin (tgm) : main layout option image is under (wp-content/plugins/redux/blabla/img/layout-different-file.png)

i hope you get the question

**Comment by dovy** [comment]
Here you go dude. I see you're modifying CORE redux files and your own CSS, and the plugin overrides those to the default Redux look.

Well, you have to properly enqueue your own CSS and NOT modify the ReduxCore. Here's an article on how to do that.

http://docs.reduxframework.com/core/advanced/custom-panel-css/

**Comment by userseventeen** [comment]
and what about the images dude ?

**Comment by dovy** [comment]
Your CSS must have the relative path to the images in it. As long as you're overriding Redux, all should be well.
