### ISSUE TITLE
Issue with color scheme extension

### ISSUE THREAD

**Issue by MrHunter** [ReduxFramework/redux-framework#1985]
Hey there,

Our company recently purchased the color scheme extension and it's awesome, it was a breeze to integrate into our theme and am looking forward to having it fully functional!

Problem is when I save the option from the color scheme extension it won't save the selector field that I have set in my config file.

Here are my details according to the guidlines:
<table>
<tr><td>Redux Version:</td><td> 3.3.10.6</td></tr>
<tr><td>WordPress Version: </td><td> 4.1</td></tr>
<tr><td>dev_mode: </td><td> false</td></tr>
<tr><td>Field Code: </td><td> http://pastebin.com/bEWk4qns</td></tr>
<tr><td>Using: </td><td> I have 2 option panels, 1 in a theme and 1 in a plugin, currently having troubles in the theme panel.</td></tr>
<tr><td>Redux Embedded: </td><td> Redux Embedded in my theme</td></tr>
<tr><td>Console Errors: </td><td> None</td></tr>
</table>

If you need some sort of purchase verification please let me know, I can get it for you.

Thanks.

**Comment by kprovance** [comment]
Hi.  All extension issue should be posted to their tracker:  https://github.com/ReduxFramework/redux-extensions/issues.  Also, please include the version of the ext used.  Thanks.

**Comment by MrHunter** [comment]
My bad.
