### ISSUE TITLE
Limit the characters lenght in a text field

### ISSUE THREAD

**Issue by Pablinus** [ReduxFramework/redux-framework#1986]
Hello It is possible to limit the characters in a text field or in a textarea field. 

Thanks

**Comment by dovy** [comment]
We've done it before, but it's a very specific JS problem.

I suggest you take a look at this article: http://docs.reduxframework.com/core/advanced/custom-panel-css/

And instead of CSS, enqueue a JS file. Then just use one of the many jQuery limit text field code snippets you can find on the web.

Best of luck!

**Comment by Pablinus** [comment]
Ok and what about to use a custom validation?  Validate by lenght of characters?

**Comment by dovy** [comment]
Then you just make your own validation class and run a add_filter before you load your config. Pretty strait forward.  ;)

**Comment by Pablinus** [comment]
Great!! but I have a problem. Do not understand how to generate a validate custom filter. I dont understand the documentation. Where I have to put:

  / * Custom validation callback function for the above referenced
  * /
if (function_exists ('your_custom_validate_callback_function')!):
 
     your_custom_validate_callback_function function ($ field, $ value, $ existing_value) {
         $ error = false;
         $ value = 'just testing';
         / *
           do your validation
 
           if (something) {
           $ value = $ value;
           } Elseif (something else) {
           $ error = true;
           $ value = $ existing_value;
           $ field ['msg'] = 'your custom error message';
           }
          * /
 
         $ return ['value'] = $ value;
         if ($ error == true) {
             $ return ['error'] = $ field;
         }
         return $ return;
     }
 
endif;

**Comment by dovy** [comment]
Look at the `validate_callback_function` function within the sample-config.  ;)

**Comment by Pablinus** [comment]
Ok thanks!!! When I have the solution I will post it

**Comment by Pablinus** [comment]
OK I can't do it :(

**Comment by Pablinus** [comment]
The documentation is really poor. I'm looking an example for this aplication but doesnt exist. :(

**Comment by kprovance** [comment]
<blockquote>
The documentation is really poor.
</blockquote>

If you believe you can write something better, we're completely open to suggestions.

**Comment by Pablinus** [comment]
I had no intention to offend. Redux is great and who worked on it did a great job. I simply can not find an example of what I'm looking for. I'm frustrated.

**Comment by Pablinus** [comment]
I apologize if it offended someone

**Comment by Pablinus** [comment]
Can anyone give me an example of using a custom field validation?

**Comment by Pablinus** [comment]
OK I got it

**Comment by Pablinus** [comment]
:)

**Comment by dovy** [comment]
Glad you got it. It just takes tinkering with. ;)

**Comment by Pablinus** [comment]
The solution:

array(
                        'id'                    => 'services_title',
                        'type'                  => 'text',
                        'title'                 => __('Section Title', 'fluid'),
                        'subtitle'              => __('Add the section title', 'fluid'),
                        'desc'                  => __('', 'fluid'),
                        'default'               => 'Services',
                        'validate_callback'     => 'redux_validate_callback_function'
                    ),

**Comment by Pablinus** [comment]
array(
                        'id'        => 'opt-text-post-type',
                        'type'      => 'text',
                        'title'     => __('Text Option with Data Attributes', 'redux-framework-demo'),
                        'subtitle'  => __('You can also pass an options array if you want.'),
                        'desc'      => __('', 'redux-framework-demo'),
                        'validate_callback'     => 'redux_validate_callback_function' ***ADD***
                    ),

**Comment by Pablinus** [comment]
if (!function_exists('redux_validate_callback_function')):
    function redux_validate_callback_function($field, $value, $existing_value) {
        $error = false;

        ***if($existing_value.length > 6) {
            $value = $existing_value;
            $error = true;
            $field['msg'] = '6 characters limit';
          } ***
        
        $return['value'] = $value;
        if ($error == true) {
            $return['error'] = $field;
        }
        return $return;
    }
endif;

**Comment by Pablinus** [comment]
Ok that solution not work.

**Comment by Pablinus** [comment]
This is what i'm doing and sometimes work and sometimes not. i'm lost here :(
 

if($existing_value.length < 6) {
           $value = $value;
        } 
        elseif($existing_value.length >= 6) {
            $value = $existing_value;
            $error = true;
            $field['msg'] = 'text length limit = 6';    
        }

**Comment by Pablinus** [comment]
the complete function.

if (!function_exists('redux_validate_callback_function')):
    function redux_validate_callback_function($field, $value, $existing_value) {
        $error = false;     
        
        if($value.length < 6) {
           $value = $value;
        } 
        elseif($value.length >= 6) {
            $value = $existing_value;
            $error = true;
            $field['msg'] = 'text length limit = 6';    
        }

        $return['value'] = $value;
        if ($error == true) {
            $return['error'] = $field;
        }
        return $return;
    }
endif;

**Comment by Pablinus** [comment]
Dovy? Any idea?

**Comment by dovy** [comment]
@Pablinus We're an open source project which is primarily a self-serve situation. I was trying to point you in the correct direction. I can't do your PHP coding for you. If you want us to code this up for you we can, but we'd need you to support us for our time and buy 1 order of premium support. The truth is your issue is not crucial to the core and it's hard for us to donate the time/money when we see very little impact on our users. Sorry, but we have families to feed. We have to be compensated for our time.

**Comment by Pablinus** [comment]
Ok It seems more than fair. Where I buy premium support? What is the cost?

**Comment by Pablinus** [comment]
Ok found it

**Comment by Pablinus** [comment]
Dovy I have some questions about premium support. You will code some custom field if I buy the premium support. I want to use font awsome. Could you adapt that for my theme?

**Comment by dovy** [comment]
For premium support you get 1 hour of support. We'll do whatever we can fit in that single hour. If you want more done, you pay for more. It's pretty strait forward. We're always for hire and we really appreciate the support.

**Comment by Pablinus** [comment]
So I have: 1 hour in 1 year of support? Ok I will make a plan so I know all the requirements for my theme.

**Comment by Pablinus** [comment]
I will buy one

**Comment by Pablinus** [comment]
SOLUTION:

if (!function_exists('redux_validate_callback_function')):
    function redux_validate_callback_function($field, $value, $existing_value) {
        $error = false;     
        $length = strlen($value);
        if($length < 10) {
           $value = $value;
        } 
        elseif($length >= 10) {
            $value = $existing_value;
            $error = true;
            $field['msg'] = 'text length limit = 10';    
        }

        $return['value'] = $value;
        if ($error == true) {
            $return['error'] = $field;
        }
        return $return;
    }
endif;
