### ISSUE TITLE
Spacing bug iPad

### ISSUE THREAD

**Issue by mathrafal** [ReduxFramework/redux-framework#1987]
With  the three column grid in portrait shows only 2, and when you turn the iPad to landscape orientation and back, the next page links at the bottom lose their top padding and touch the images.

**Comment by dovy** [comment]
Screenshot please?

**Comment by dovy** [comment]
Also care to tinker with the CSS and see if you can solve it? This is open source after all.  ;)

**Comment by mathrafal** [comment]
Sorry. Wrong repository

**Comment by dovy** [comment]
Haha, ok. Best of luck!
