### ISSUE TITLE
remove cookie

### ISSUE THREAD

**Issue by farhanhu87** [ReduxFramework/redux-framework#1988]
reset cookie on pressing save in Admin Panel,
this is the line that i have to embad on save button, $.removeCookie('khareedo_primary_navigation_status');
how to do this.. any idea sir

**Comment by dovy** [comment]
Add your own js file as I have said before and do an on click. Or use the save action to set or remove cookies the php way.

**Comment by farhanhu87** [comment]
Thanks @dovy
