### ISSUE TITLE
Does redux still suggest external plugin installation, or to include it directly in theme?

### ISSUE THREAD

**Issue by scrollmapper** [ReduxFramework/redux-framework#1991]
When I reviewed the original documentation of Redux, it was a sort of subject of debait - include redux in the theme/plugin itself, or use TGM (or similar) to prompt the user to install it.

I would like to know if this has changed at all - - I find it better to include it in the theme (creating a themeforest product) but I'd like to know what the current suggestion is.

**Comment by kprovance** [comment]
It's a 'to each his own' type situation.  There are pros and cons for each.  For example, embedding in your theme means no plug in dependency, requiring TGM or the like, however, when Redux is updated, users do not have the option to download the updated code via the plugin route.  It falls on your to update the Redux core with an update to your theme.  There's no right or wrong way.  It all about how you want to code up your work and the support that ultimately comes with it.  :)

**Comment by scrollmapper** [comment]
I've just embedded it and made it an optional include in TGM. I guess I'll stick with that.

**Comment by kprovance** [comment]
Just bear in mind, that the plugin install - when activated - will override the embed.  It's a nice fallback option for those users who don't/won't install the plugin, but again, the huge caveat would be code updates.  Good luck to you.  :)
