### ISSUE TITLE
add_filter('redux/options/'.$this->args['opt_name'].'/defaults not working on first load

### ISSUE THREAD

**Issue by liquida** [ReduxFramework/redux-framework#1992]
hello, im trying to use the filter

add_filter('redux/options/'.$this->args['opt_name'].'/defaults', array( $this,'change_defaults' ) );

        function change_defaults($defaults) {
            $defaults['str_replace'] = 'Testing filter hook!';

            return $defaults;
        }

i've downloaded the theme from the redux builder, with the development version

the filter only works when i press the "reset section" or "reset all" button

i dont know if this is the defaut behavior or its a bug, as i've looked in to the code and i couldt find any call to this filter in the functions involved to save the options
         
                    array(
                        'id'        => 'str_replace',
                        'type'      => 'text',
                        'title'     => __('Text Option - Str Replace Validated', 'redux-framework-demo'),
                        'subtitle'  => __('You decide.', 'redux-framework-demo'),
                        'desc'      => __('This field\'s default value was changed by a filter hook!', 'redux-framework-demo'),
                        'validate'  => 'str_replace',
                        'str'       => array(
                            'search'        => ' ', 
                            'replacement'   => 'thisisaspace'
                        ),
                        'default'   => 'This is the default.'
                    ),

has anyone had success using this filter?

regards

**Comment by kprovance** [comment]
<blockquote>
i've downloaded the theme from the redux builder, with the development version
</blockquote>
Yeah, because that's an actual version number that we require as part of our post guidelines.  You've been around long enough, dude.  You should know this by now.

**Comment by kprovance** [comment]
Closing.  Please feel free to file a new issue with the proper and required information
