### ISSUE TITLE
Select Limit 5 - Remove Select Limit

### ISSUE THREAD

**Issue by raul1989** [ReduxFramework/redux-framework#1993]
Hi,

Using Redux Version: 3.3.9.4

I am trying to connect Redux with a woocommerce plugin.

The plugin will make use of the table = 'posts', fields = 'post_type', value = 'product'

This all works, below is the working code:

array(
								'id'       => 'ecommerce-extra-product-1',
								'type'     => 'select',
								'data' => 'post',
                    			'args' => array('post_type' => array('product')),
							),

The select is populated with the desired data, but here comest the problem:

It only displays the 5 most recent products, while I wish to display ALL products. I tested this by adding a new product.
How do I remove/set the limit of the select option? So I can display all.

**Comment by kprovance** [comment]
#1506 - Asked and answered.
