### ISSUE TITLE
Using Timezone List with DateTime Picker

### ISSUE THREAD

**Issue by Buooy** [ReduxFramework/redux-framework#1994]
Hi,

I would like to have a timezone list of ALL the supported timezones. Where can I find one or is there a default setting to use.

It seems odd that we have to manually calculate the time offset and input them one by one. thats a lot!

**Comment by kprovance** [comment]
Hi!

In the future, all extensions issues should be directed to their own issue tracker.  The link is available on the extension page, or you could bookmark it here:  https://github.com/ReduxFramework/redux-extensions/issues

Second: Unfortunately, the manual offset of the date-time field falls upon the vendor, whose code we used in the extension.  Our documentation reflects theirs, which you may also view here:  http://trentrichardson.com/examples/timepicker/#timezone_examples
