### ISSUE TITLE
Adding a custom field

### ISSUE THREAD

**Issue by Pablinus** [ReduxFramework/redux-framework#1996]
Hello I can't add a custom field. I don't want a debbug of my code, only to know if this are the correct steps to do add a custom_field to redux.

1) Download Extension-boilerplate and loader-master.

2) I copy extensions-init.php and loader.php into the folder /admin/redux-extensions

3) After extract the extension-boilerplate-master.zip file I copy the folder custom_field. (The first folder that with another folder call custom_field and with extension-boilerplate-master.php).
I copy the first folder custom_field in /admin/redux-extensions/extensions

4) Modify files:
extensions-init.php
    <?php
$redux_opt_name = "myOpt_wp";
// Place any extra hooks/configs in here for extensions and 
// place the actual extension within the /extensions dir
// The loader will load all of the extensions automatically.
// Alternatively you can run the include/init statements below.
require_once(dirname(__FILE__).'/loader.php');
?> //****This should be removed (it's here only to close php between diferents files)****//

loader.php
<?php
// Replace {$redux_opt_name} with your opt_name.
// Also be sure to change this function name!
if(!function_exists('myOpt_custom_extension_loader')) :
    function myOpt_custom_extension_loader($ReduxFramework) {
        $path    = dirname( __FILE__ ) . '/extensions/';
            $folders = scandir( $path, 1 );
            foreach ( $folders as $folder ) {
                if ( $folder === '.' or $folder === '..' or ! is_dir( $path . $folder ) ) {
                    continue;
                }
                $extension_class = 'ReduxFramework_Extension_' . $folder;
                if ( ! class_exists( $extension_class ) ) {
                    // In case you wanted override your override, hah.
                    $class_file = $path . $folder . '/extension_' . $folder . '.php';
                    $class_file = apply_filters( 'redux/extension/' . $ReduxFramework->args['opt_name'] . '/' . $folder, $class_file );
                    if ( $class_file ) {
                        require_once( $class_file );
                    }
                }
                if ( ! isset( $ReduxFramework->extensions[ $folder ] ) ) {
                    $ReduxFramework->extensions[ $folder ] = new $extension_class( $ReduxFramework );
                }
            }
    }
    // Modify {$redux_opt_name} to match your opt_name
    add_action("redux/extensions/{$myOpt_wp}/before", 'myOpt_custom_extension_loader', 0);
endif;
?> //****This should be removed (it's here only to close php between diferents files)****//

5) Inside /admin/redux-extensions/extensions/custom_field/custom_field/     Here I have field_custom_field.php. There I add a simple print("hello word"); inside the render function.

6) I call the new added custom_field like this, but nothing happend. 
<?php
array(
    'id'                    => 'test_field',
    'type'                  => 'custom_field',
    'title'                 => __('TEST FIELD', 'myOpt'),
    'subtitle'              => __('TEST', 'myOpt'),
    'desc'                  => __('', 'myOpt'),
    'default'               => 'TEST',
),   
?> //****This should be removed (it's here only to close php between diferents files)****//   

******** What is wrong? Is it a missing step? Thanks. I will remove this post later to avoid problems. 

******** Thanks in advanced :) ********

**Comment by kprovance** [comment]
Custom fields and extensions are TWO different things:

http://docs.reduxframework.com/core/advanced/add-a-custom-field/

http://docs.reduxframework.com/core/advanced/loading-extensions/

**Comment by Pablinus** [comment]
Ok I feel stupid :(. So I'm doing all wrong

extract from documentation:
if you want to change the way a Redux field does something, you should ALWAYS use an extension instead of modifying the core.

**Comment by Pablinus** [comment]
I want to create an option inside the redux panel similar to slides but with only to text fields.

**Comment by kprovance** [comment]
It's up to you.  Overloading a field will change the behaviour of the field you overload.  It's the modification of an existing field without changing the core.  An extension is the creation of a completely new field.

**Comment by Pablinus** [comment]
Ok thanks kevin

**Comment by dovy** [comment]
You COULD grab the repeater field and then you could do exactly what you're aiming to do and support the project. Basically the repeater lets you make repeatable groups of any field type you specify.  ;)

Think slides on steroids.
