### ISSUE TITLE
AceEditor Improvements

### ISSUE THREAD

**Issue by corradomatt** [ReduxFramework/redux-framework#1998]
The aceeditor is great....but it has a few drawbacks and I'm hoping that we can solve a few of these within redux as I believe that the implementation in redux might be causing some of these.....

- when jumping around with selections using CMD-G on a long document, the window doesn't follow the selection
- no search or search/replace
- no fullscreen
- no css autocomplete (not sure we can solve this one)

I'm going to take a look at the field in redux and see if I can solve it on my own. If I come up with solutions to any of these issues, I'll submit some pull requests. Any feedback or advice is welcomed and appreciated. Thanks!

**Comment by corradomatt** [comment]
Now that I'm looking into this further, it appears that Ace has some updates that maybe we should include in redux, like.....

- [search box](https://github.com/ajaxorg/ace-builds/blob/master/src-min/ext-searchbox.js)
- [emmet](https://github.com/ajaxorg/ace-builds/blob/master/src-min/ext-emmet.js)

**Comment by corradomatt** [comment]
Also, since the ace editor uses require js, we should probably be using the no conflict version since it's namespaced and won't have issues with other require modules. Like masonry.js for example.

**Comment by kprovance** [comment]
Namespace would force us to drop PHP 5.2 support.  No?

**Comment by corradomatt** [comment]
No. Namespace is through JS in this particular case and would make requireJS a little less finicky. RequireJS has a tendancy to conflict with lots of other JS libraries. Using a namespace reduces that conflict to almost NIL. ```require``` becomes ```ace.require``` - [you can see it declared here](https://github.com/ajaxorg/ace-builds/blob/master/src-noconflict/ace.js#L39). We don't really have to do anything except update the field in redux to the new ACE code and make sure that we're initializing the plugin correctly.

I'm working on this now and should have a pull request by the end of this week or next week.

**Comment by kprovance** [comment]
Cool.  I'll be watching for it  :)

**Comment by corradomatt** [comment]
just submitted pull request https://github.com/ReduxFramework/redux-framework/pull/2012 but I'm also planning to build a full-screen keyboard shortcut feature as well that will make the editor go full screen if enabled. It could be triggered with ```cmd + enter``` or ```ctrl + enter``` on mac and PC respectively.

**Comment by dovy** [comment]
Also see if you can add a button somewhere to init the full-screen just for full user benefit.

Can't wait to see it.  :)

**Comment by corradomatt** [comment]
Sure @dovy - that shouldn't be a problem. I'm going to submit the full-screen feature as a separate PR.

**Comment by kprovance** [comment]
Added.  :)
