### ISSUE TITLE
Violet background

### ISSUE THREAD

**Issue by AndresitoK** [ReduxFramework/redux-framework#1999]
Hi,
first of all: sorry for my english. I have a problem when using the Redux Framework on certain templates.
When I try to initialize/include the framework by "
if ( ! class_exists('ReduxFramework') && file_exists( dirname( __FILE__ ) . '/admin/core/framework.php' ) ) {
    require_once(dirname( __FILE__ ) . '/admin/core/framework.php');
	}
if ( !isset( $strict_theme )  && file_exists( dirname( __FILE__ ) . '/admin/options.php' ) ) {
    require_once(dirname( __FILE__ ) . '/admin/options.php');
    }" I always get a violet background. Firstly I thought it is an error by the theme but I tried it with the new "Twenty Fifteen" too - and I have the same error... looking for it with firebug only tells me background: rgba(126,51,221,0.8); on some index(?) . I am using the latest Redux version, but I tried them all... the same problem. Thanks for your time...
![twentyfifteen](https://cloud.githubusercontent.com/assets/10654029/5856445/93047306-a243-11e4-869b-70ed767ca71d.png)

**Comment by kprovance** [comment]
#1975

**Comment by AndresitoK** [comment]
hi,
I hope you mean the guidelines - sorry for this. So once again:
Redux Version: 3.3.10.7 used in dev_mode and embedded
Wordpress Version: 4.1
Theme: Twenty Fifteen
initializing like I told in my first post, tried it too with the redux builder ( include('/admin/admin-init.php');)
but then - what a surprise - got an orange background...
thanks again!

**Comment by dovy** [comment]
Redux will do dynamic output of CSS using the output argument. There is a field in there that's changing the background color. You will find it in your panel. If you want to start out easier, it's suggested you start with the barebones example and go from there. That is located here: https://raw.githubusercontent.com/ReduxFramework/redux-framework/master/sample/barebones-config.php
