### ISSUE TITLE
Warning: Invalid argument supplied for foreach() in /wp-content/plugins/redux-framework/ReduxCore/framework.php on line 1401

### ISSUE THREAD

**Issue by sonlamtn200** [ReduxFramework/redux-framework#2000]
Check with me!
This is the link: http://vhotel.id/wordpress/
Thank very much

**Comment by kprovance** [comment]
Sorry, but this is a prime example of how NOT to report an issue.  Please review:  #1975

**Comment by kprovance** [comment]
Line 1401 is a comment in the current push, so, please upgrade your copy of Redux.
