### ISSUE TITLE
When redux framework updated in WP repository 

### ISSUE THREAD

**Issue by php-xpert** [ReduxFramework/redux-framework#2001]
Hi,

Currently redux framework is older and not updated since last couple of months at WP repository.

When we can expect WP repository updated with latest version..

**Comment by dovy** [comment]
Very good point. I should update it. I'll check with @kprovance and we'll see about making it happen.

**Comment by php-xpert** [comment]
Thank you.
Kindly update it as early as possible as we want to use latest updates as a WP plugin...
We highly appreciate your prompt support..

**Comment by kprovance** [comment]
Please?  @@

**Comment by dovy** [comment]
Pushing to .org now. Should be up in 20 mins at most.

**Comment by php-xpert** [comment]
Hi Dovy,

Thank you very much for updating the plugin, but it seems version is not updated in plugin file..

Previous version 3.3.9.4 & it shows current version 3.3.4 instead of 3.4.0..

**Comment by dovy** [comment]
Working on it. patience.  ;)

**Comment by dovy** [comment]
I don't know what the crap is up with WP.org. It's not working proper. Just download from the repo here.

**Comment by php-xpert** [comment]
Thank you dovy, 

One more help needed from you.. I read some where that you have begin working on group field as well..

Is it possible for you to share it with me..

Many thanks.

**Comment by dovy** [comment]
It's called the repeater extension. It's available today. 
http://reduxframework.com/extensions/repeater/
http://docs.reduxframework.com/extensions/repeater/

:)

**Comment by php-xpert** [comment]
Dovy,

If we purchase it one time, we can use it in unlimited themes ? can we use it in ThemeForest themes as well ?

**Comment by dovy** [comment]
It's the same as buying Visual Composer for a theme. One-Time purchase per theme. Pretty standard.  ;)

**Comment by dovy** [comment]
And wp.org is fixed now.
