### ISSUE TITLE
Sortable field label not displaying

### ISSUE THREAD

**Issue by wasimbhalli** [ReduxFramework/redux-framework#2002]
I've tried with the checkbox and it shows the label but for 'text' mode I'm unable to show it. Neither label nor the placeholder is displayed.

**Comment by teamcrisis** [comment]
https://github.com/ReduxFramework/redux-framework/issues/1975

**Comment by dovy** [comment]
A new version was just pushed to WP.org. Make sure you're using 3.4.0. Then follow the guidelines to provide the necessary information.

**Comment by kprovance** [comment]
I would just go ahead and update to the latest version.  If problem persist, then open a new issue, remembering to include all the required information from our posting guidelines.
