### ISSUE TITLE
Repeater field

### ISSUE THREAD

**Issue by xymurgist** [ReduxFramework/redux-framework#2003]
As of version 3.4.0, changelog says repeater field has been introduced. Question, how do we use this?

**Comment by dovy** [comment]
It's a premium extension. You can get that here: http://reduxframework.com/extensions/repeater/

:)

**Comment by kprovance** [comment]
It's a premium extension, found here:  http://reduxframework.com/extension/repeater/

**Comment by dovy** [comment]
Haha.  ;)

**Comment by xymurgist** [comment]
Oh, silly me. Thanks for the clarification.

**Comment by dovy** [comment]
Sorry @xymurgist, we have to keep the project alive somehow.  ;)
