### ISSUE TITLE
[urgent] I cannot access my Wordpress dashboard!!!! 

### ISSUE THREAD

**Issue by jayciro** [ReduxFramework/redux-framework#2008]
see screen shot.

I entered demo mode to show the creator of my theme (K-Theme http://goo.gl/k3LzzL) that I could not access the theme updates until I enter demo mode through the redux plug in. My laptop's battery died, so I never disabled demo mode - and now I cannot access my wordpress dashboard via .com/wp-admin. 

Also, I see a note at the top of my webpage 

"The class named Redux_Framework_sample_config has already been called. Developers, you need to prefix this class with your company name or you'll run into problems!"

![screen shot 2015-01-25 at 8 53 40 pm](https://cloud.githubusercontent.com/assets/7505994/5895460/3ac0c28c-a4d5-11e4-92a3-9ecf1d98ed6a.png)

**Comment by kprovance** [comment]
So, did you actually rename `Redux_Framework_sample_config` in your config file to something else, as suggested?  That would be the first thing to do.

**Comment by jayciro** [comment]
Hi I didnt do/change anything - I entered demo mode to grab screen shots.
And now I cannot access my wordpress login.

**Comment by kprovance** [comment]
I'm telling you, that's what you need to do, change the class name in your config file to something other than `Redux_Framework_sample_config`.  I really cannot put it any other way.

**Comment by jayciro** [comment]
Thank you, I understand that. But how can I access the Wp Confic file using
GoDaddy? I have searched all around with no results.

**Comment by kprovance** [comment]
You're supposed to edit it before uploading.  And I won't touch GoDaddy related issues unless premium support is involved.  They're a mess and usually end up taking a HUGE chunk of our day to deal with.

**Comment by dovy** [comment]
@jayciro, easy solution.

Rename your theme/plugin folder name to something else. Voila, it will be deactivated and you can access your backend again.

Then before activating again rename the Redux_Framework_sample_config to something more unique to your needs. ;)

**Comment by jayciro** [comment]
Hi, I had to remove the theme and your plugin from my site. Problem solved.
However I am not confident in using your product again.

thanks for the help

**Comment by dovy** [comment]
We didn't create the theme, we're an open source project and we created the framework your theme used.

Please don't judge Redux by the developers that use Redux. We have no control over them.  ;)

Best of luck.

**Comment by linkworldus** [comment]
Hi, I'm facing same problem. I clicked on demo version, after that,  My website is [https://www.linkworld.us](https://www.linkworld.us). I cannot access my wp-admin panel when I'm activating. After delete this plugins, my website is working fine. 

But this plugin required to get theme function. That means, My theme is now working not working properly. 

Please help me.
Thanks
