### ISSUE TITLE
Documentation and Theme Information not showing when ReduxFramework embedded in theme

### ISSUE THREAD

**Issue by adlibeo** [ReduxFramework/redux-framework#2009]
I've exported a theme using ReduxBuilder, using the Embed Only. The Documentation and Theme Information panel both show in the sidebar but the content is empty. When I activate the Redux plugin both these panels show data. 
No doubt a simple fix however not sure where to start.  

Redux Version: v3.3.6 
WordPress Version: 4.1
dev_mode: false
Redux Embedded: Redux Embedded in my theme
Console Errors: None

Exported a new theme using the builder and Development Version
Redux Version: v3.4.1 
WordPress Version: 4.1
dev_mode: true
Redux Embedded: Redux Embedded in my theme
Console Errors: None

**Comment by kprovance** [comment]
#1975

**Comment by adlibeo** [comment]
Apologies, I've updated the post with Redux and WordPress version numbers

**Comment by kprovance** [comment]
And your config code?  Also required.  Please don't edit the OP, just, make a new reply with it, please.

**Comment by adlibeo** [comment]
My config has 

                'output' => true,
                'output_tag' => true,
                'compiler' => true,
                'page_icon' => 'icon-themes',
                'page_permissions' => 'manage_options',
                'save_defaults' => true,
                'show_import_export' => true,
                'transient_time' => '3600',
                'network_sites' => true,

**Comment by kprovance** [comment]
It it perhaps a case of you not yet adding content to your config?  The builder does not do that for you, it gives you a framework.  You have to write your own sections and option arrays.  Otherwise, I really do not get what you're attempting to convey here.

**Comment by adlibeo** [comment]
I've added content. When I generate using the builder (as a theme embedd) it adds two panels, theme information (pulling info from styles.css and screenshot.png) and documentation (pulling information from readme.md). There doesn't seem to be an option within the buillder to turn these options on or off, and when used as a stand alone theme they don't pull in the required files (styles.css, screenshot.png and readme.md). However, when I install the plugin the informatino appears in the panels. 
![screen shot 2015-01-27 at 7 17 17 am](https://cloud.githubusercontent.com/assets/6202772/5910526/040b2508-a5f6-11e4-983b-0a6180bda0b6.png)
![screen shot 2015-01-27 at 7 18 35 am](https://cloud.githubusercontent.com/assets/6202772/5910527/04192bf8-a5f6-11e4-809f-8c151f7b3ffa.png)

**Comment by kprovance** [comment]
You 'turn them off' but not including the field arrays in your config file.
