### ISSUE TITLE
link_color field value not saved

### ISSUE THREAD

**Issue by creodev** [ReduxFramework/redux-framework#2011]
Hello,

I have and issue with the link_color field and the typography fields which cannot make to save the selected values that are chosen. 
I am using WordPress 4.1 and Redux framework version 3.4.1 which I embed into control panel of plugin. In options the configuration for those fields is set as (I have another fields from same type which also did not save):
```php
array(
    'id'       => 'customizer-nav-color',
    'type'     => 'link_color',
    'title'    => __( 'Links Color Option', 'edb' ),
    'subtitle' => __( 'Change default colors into navigation', 'ebd' ),
			
),
array(
    'id'       => 'customizer-nav-cat',
    'type'     => 'typography',
    'title'    => __( 'Category font', 'edb' ),
    'subtitle' => __( 'Specify the category font properties.', 'edb' ),
    'google'   => true,
    'color'    => false
),
```

The regular color field saves with not problem. I try with putting default values with <code>'default' => array()</code> and notice that they did not appear as default selected into those type of fields. So I suppose that something is missing in my configuration or include. 

I include framework using the following code:
```php
if ( !class_exists( 'ReduxFramework' ) && file_exists( dirname( __FILE__ ) . '/includes/options/framework.php' ) ) {
	require_once( dirname( __FILE__ ) . '/includes/options/framework.php' );
}
if ( !isset( $redux_demo ) && file_exists( dirname( __FILE__ ) . '/includes/config.php' ) ) {
	require_once( dirname( __FILE__ ) . '/includes/config.php' );
}
```

In configuration I try with both developer_mode true or false and save_defaults with true or false but still the same.

**Comment by kprovance** [comment]
I am unable to reproduce.  How many options does your ENTIRE panel have, and who is your host?

**Comment by creodev** [comment]
It is on local development machine. Options are a few (less the in the sample page) and mostly created using as modification of sample which is actually strange that they did not work in that configuration.

I can send the entire file which can be used to represent the problem but prefer this to be in private (via email for example).

**Comment by kprovance** [comment]
Good to know.  Thanks for reporting back.  :)
