### ISSUE TITLE
Global plugin settings on Multisite

### ISSUE THREAD

**Issue by jaybabani** [reduxframework/redux-framework#2013]
Hello,

Is it possible to install redux on a multisite network and control the settings from main dashboard only.

I mean if a plugin uses redux framework, then all the sites on the network have the ability to change the plugin settings individually.

But is there a way to change the option settings across all sites from one single location. Means a Global settings for plugin on the multisite network and NOT allowing each site on the network to change the settings individually.

Thank You

**Comment by dovy** [comment]
Yes, you can change! Use the http://docs.reduxframework.com/core/arguments/#network_admin argument.  :)

If you like Redux, or the support we render, please do one or all of the following:
* Donate to keep us going: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=MMFMHWUPKHKPW
* Review us: http://wordpress.org/support/view/plugin-reviews/redux-framework
* Like us: http://facebook.com/ReduxFramework
* Follow us: http://twitter.com/ReduxFramework
