### ISSUE TITLE
Banner or Javascript code by switch button

### ISSUE THREAD

**Issue by meno010** [ReduxFramework/redux-framework#2015]
Need to use switch button to choose between Banner or HTML/Javascript Ad
we used this code

    ###################
    <?php  if ( ! empty( redux_demo('header_banner_kind_2', true)) )
     {
     echo (redux_demo('header_banner_html_2'));
     }
     elseif 
     (empty( redux_demo('header_banner_kind2', FALSE)) ){  ?>
    <a href="<?php echo $redux_demo['header_banner_url_2']; ?>">
    <img src="<?php echo $redux_demo['header_banner_image_2']['url'];?>"></a>
    ###################`

But most times it's return only HTML/Javascript Ads !!!
also may be kind is HTML/Javascript but it's return Banners !!!

how we can return switch button if is true or false  because we used many codes without fix ??
1- if ( ! empty( redux_demo('header_banner_kind_2', true)) )
 2-if ( redux_demo('header_banner_kind_2') =="1") 
3- if ( redux_demo('header_banner_kind_2') == TRUE) 

WordPress 4.0.1
Redux version: 3.3.8.8
Our config
     ###################
     array(
     'id'=>'header_banner_kind_2',
     'type' => 'switch', 
     'title' => __('Banner Kind #2', 'redux-framework-demo'),
     'subtitle'=> __('Look, it\'s on!', 'redux-framework-demo'),
     'required' => array('header_banner_2', '=' , '1'),
     "default" 	=> 0,
     'on'       => 'HTML/Javascript',
     'off'      => 'Banner',
     ),
     ###################

**Comment by kprovance** [comment]
There is no possible way for me to test this code.  Your top snippet indicates a function of `redux_demo` that isn't included, and therefore untestable.  Truth is, for something like these, you'd be better off using the button_set field.
