### ISSUE TITLE
Question: How To Delete Embedded Framework Data When Theme Is Uninstalled?

### ISSUE THREAD

**Issue by edtheitguy** [ReduxFramework/redux-framework#2017]
Like the title says: 
I want all the database inserted data to be removed when the theme is uninstalled.

Is that possible? 
I didnt find any infomation about it - so the big question is:  
Is it something I am missing or is it a problem with the embedded version 

Info:
Used Builder to create a package (tried latest + dev version), added it to my theme, installed and tried it out, changed some Redux settings and uninstalled the theme.
Installed the same theme with some layout modifications and noticed during test that the settings from the first test were still there.

**Comment by kprovance** [comment]
Redux will not do this by design.  You'd have to roll your own solution for something like that.

**Comment by dovy** [comment]
Easiest thing is to do a add_action on `switch_theme` and run a `delete_option('OPT_NAME');`
