### ISSUE TITLE
Bug in switch field

### ISSUE THREAD

**Issue by mariomka** [ReduxFramework/redux-framework#2018]
Hello guys,

I found a bug in switch field.
If default value is set to *true*, *get* method of *ReduxFramework* always returns **true**.

When switch are disabled returns *"0"* (string) and this is false to check in PHP *empty* function, then returns default value (*true*).

```php
public function get( $opt_name, $default = null ) {
    return ( ! empty( $this->options[ $opt_name ] ) ) ? $this->options[ $opt_name ] : $this->_get_default( $opt_name, $default );
 }
```
In redux 3.4.1 embedded and wordpress 4.1

**Comment by kprovance** [comment]
Now, have you checked this alteration with EVERY field Redux offers?  I don;t like changing core code for one field unless I know it isn;t going to break for others.

**Comment by mariomka** [comment]
This isn't a alteration, is a original code for a fast read.
Alteration maybe can be like:

```php
public function get( $opt_name, $default = null ) {
    return ( ! empty( $this->options[ $opt_name ] ) && $this->options[ $opt_name ] !== "0" ) ? $this->options[ $opt_name ] : $this->_get_default( $opt_name, $default );
 }
```
 I didn't send pull request because I don't know if it going to break other fields.

**Comment by kprovance** [comment]
Not all fields are boolean based, so yeah, it might break something.  I don't have the time to test every, single, field.  You might just check against tru in your code, like

```php
if ($redux_demo['opt_switch']) {
...
}
```
or
```php
if (!$redux_demo['opt_switch']) {
...
}
```
