### ISSUE TITLE
Hide th row

### ISSUE THREAD

**Issue by goranefbl** [ReduxFramework/redux-framework#2020]
I am developing extension and searching for a way to hide left part - title and subtitle one. Is this possible? I saw full_width property but it does not work. Also css would work but cant target id that is starting with number.

**Comment by kprovance** [comment]
There is no proper way, since Redux uses the options API within WP.  However, it can be done in a hacky sort of way by manipulating the HTML.  See the info field, or the section field for an example of how to do so.

**Comment by goranefbl** [comment]
Thanks, that worked, and thanks for great framework.
