### ISSUE TITLE
Latin + latin-ext subsets question

### ISSUE THREAD

**Issue by fireform** [ReduxFramework/redux-framework#2021]
Hi guys,
Hope you're well.

I'm trying to get proper links to Google Fonts. So my issue is:
Now how the link looks http://fonts.googleapis.com/css?family=Roboto+Condensed:300,400,700,300italic,400italic,700italic%7CLato:100,300,400,700,900,100italic,300italic,400italic,700italic,900italic%7CLibre+Baskerville:400,700,400italic&amp;subset=latin-ext
But this link must include latin and latin extended both, because Polish language for example includes latin and latin extended sets. So it should be http://fonts.googleapis.com/css?family=Roboto+Condensed:300,400,700,300italic,400italic,700italic%7CLato:100,300,400,700,900,100italic,300italic,400italic,700italic,900italic%7CLibre+Baskerville:400,700,400italic&amp;subset=latin,latin-ext

Maybe I missed something while setting up typography field?

Thanks in advance!

**Comment by kprovance** [comment]
#1975

**Comment by fireform** [comment]
Hi Kevin,
Additional info here:

1. Redux v. 3.4.2
2. WordPress 4.1
3. Redux not in dev mode
4. The code
<pre>
array(
	'id'          => 'ef_heading_font',
	'type'        => 'typography',
	'title'       => __( 'Heading font', EF_TDM ),
	'google'      => true,
	'font-backup' => false,
	'text-align'    => false,
	'font-size'     => false,
	'font-style'    => true,
	'line-height'   => false,
	'letter-spacing'=> true,
	'color'         => false,
	'all_styles'  => true,
	'compiler'    => true,
	'units'       => 'em',
	'subtitle'    => __( 'Specify heading font properties.', EF_TDM ),
	'default'     => array(
		'font-weight'  => '700',
		'font-style'  => 'normal',
		'font-family' => 'Cabin',
		'google'      => true,
		'letter-spacing' => '0'
	),
),
</pre>
5. Standalone theme
6. Redux as plugin
7. No javascript errors

**Comment by kprovance** [comment]
Honestly, I'm not sure what needs to be done to do what you want.  Redux pulls the Google font data from Google, then parses the subset data.  It appends the selection from the subset into the google font string.  Other than hard coding it in there (which is frowned upon), I'm not sure how that would be accomplished.  Latin Extended needs to be a choice offered by the Google fonts data.

**Comment by fireform** [comment]
Understand. Will try to add "hardcoded" fix to my projects.
Thanks :)
