### ISSUE TITLE
Demo for repeater extension

### ISSUE THREAD

**Issue by paulthecoder** [ReduxFramework/redux-framework#2022]
Hi,

I'm very interested in grabbing the repeater extension, however there is no demo or even screenshots of how it looks/works. I'd like to take it for a test ride before I purchase it. Can you put up a demo of some sort on the redux demo site?

Thanks,
Paul

**Comment by Webcreations907** [comment]
Hey there @paulthecoder ,

I picked up one of those, it's great and easy to use. I'm mainly just using it for social links/icons in a header(above menu) and is working out really well.

If you have the [MetaBoxes Extension](http://reduxframework.com/extension/metaboxes/), then it works in there too. 

Figured I'd give my input on it, and attach screen image of mine. Course I'm only using __2__ fields in it, but will work with most other fields. 

![repeater-screen-shot](https://cloud.githubusercontent.com/assets/8421576/6011541/6db9b698-aae9-11e4-999b-37fb8eb200ae.jpg)


:smile:

**Comment by kprovance** [comment]
Hey @Webcreations907, would you be willing to post or share with me that field code for your repeater?  So many requests for a demo, and my time is limited.  It's be easier to share yours on my site so folks can take a look see.  Thanks.  :-)

**Comment by Webcreations907** [comment]
@kprovance Sure thing.

I changed it a bit just because I'm using font awesome for the social field, so switched it to the elusive-icons

```
array(
    'id'           => 'opts-topbar-right',
    'type'         => 'repeater',
    'title'        => __('Right Topbar Social', 'redux-framework-demo'),
    'subtitle'     => __('Select a social icon to append a link to.', 'redux-framework-demo'),
    'group_values' => true,
    'item_name' => 'Social Icons',
    'fields'    => array(
        array(
            'id' => 'social-icon',
            'type' => 'select',
            'data' => 'elusive-icons',
            'title' => __( 'Icon', 'redux-framework-demo' ),
            'subtitle' => __( 'Select a icon to appear before.', 'redux-framework-demo' ),
        ),
        array(
            'id'        => 'social-url',
            'type'      => 'text',
            'title'     => __('Link URL', 'redux-framework-demo'),
            'subtitle'  => __('This must be a valid URL i.e http://www.twitter.com/username', 'redux-framework-demo'),
            'desc'      => __('This will make the icon linked.', 'redux-framework-demo'),
            'validate'  => 'url',
            'default'   => '',
        )
    )
)
```


And Example to output/use those on the front end

```
// $redux_demo ReduxFramework option name
// global $redux_demo
for ( $i=0; $i < count( $redux_demo['opts-topbar-right'] ); $i++ ) {

	$redux_social_icon = ( isset( $redux_demo['opts-topbar-right']['social-icon'][$i] ) && !empty( $redux_demo['opts-topbar-right']['social-icon'][$i] ) ) ? $redux_demo['opts-topbar-right']['social-icon'][$i] : '';
	$redux_social_url  = ( isset( $redux_demo['opts-topbar-right']['social-url'][$i] ) && !empty( $redux_demo['opts-topbar-right']['social-url'][$i] ) ) ? $redux_demo['opts-topbar-right']['social-url'][$i] : '';

	echo 'Icon: '. $redux_social_icon;
	echo '<br/>';
	echo 'Url: '. $redux_social_url;
	echo '<br/><br/>';

}
```
:smile:

**Comment by kprovance** [comment]
Awesome, @Webcreations907, thank you!  :)

For those looking for a repeater demo, I set up an ad hoc version, until we can get a proper extensions demo running on the main site.  For now, go here:  http://redux.kevinprovance.com/wp-admin/  login: demo; pw: demo

**Comment by paulthecoder** [comment]
Awesome guys! Thanks @Webcreations907 and @kprovance, I appreciate the help.

**Comment by prionkor** [comment]
Repeater field is not working. I am trying to get help by opening ticket in extension repo but it seems support is dead too.
