### ISSUE TITLE
JS:Custom submenu not working

### ISSUE THREAD

**Issue by abeel** [ReduxFramework/redux-framework#2023]
Hi,
when i added my custom submenu to my redux parent menu, the link of submenu it is not clickable because of this line in redux.js : 

            $( '#toplevel_page_' + redux.args.slug + ' .wp-submenu a, #wp-admin-bar-' + redux.args.slug  + '        a.ab-item' ).click(
                      function( e ) {
                                 if ( $( '#toplevel_page_' + redux.args.slug ).hasClass( 'wp-menu-open' ) || $( this ).hasClass( 'ab-item' ) ) {
                                e.preventDefault();

                             var url = $( this ).attr( 'href' ).split( '&tab=' );
                        $( '#' + url[1] + '_section_group_li_a' ).click();
                    return false;
                }
            }
        );

can you please correct this ? add else if isnot redux submenu 

Thank you,

**Comment by kprovance** [comment]
You want us to modify our core code based on a very general description of wht you are doing?  Sorry, but we don;t operate that way.  You need to provide information via #1975 so that we can try your code and see if it's reproducible on our end first.  If it is, we can look into it.  If not, and it's something on your end, then  the fix comes from there.

**Comment by dovy** [comment]
Remember, there are a ton of developers using code as is. We do our best to NEVER break backwards compatibility.

Sorry, we just have more than a few developers to think about. We have thousands.  ;)

**Comment by dovy** [comment]
If you find a solution, then please send it our way. Right now we're knee deep in coding our own theme. Our bandwidth for extra projects is a little small.  ;)

**Comment by dovy** [comment]
This issue has been resolved in d74f81728376ac373a460b3267f1b464af41f4fa.
