### ISSUE TITLE
Customizer Support for Plugins

### ISSUE THREAD

**Issue by TinyGiantStudios** [ReduxFramework/redux-framework#2024]
Using Redux 3.3.9.4 in plugin, but for some reason it just doesn't pick up the fields in WP Customizer. Got pretty basic fields as well: Background, Border, Font, Dimensions, Padding / Margin.

I've had a look at the documentation, but there's barely anything on it at the moment... Any ideas?

**Comment by TinyGiantStudios** [comment]
Hmmm - Did some more digging - seems like all the fields I'm using aren't supported customizer. Might be a good idea to update the documentation to say which fields are available in the customizer. The fields I'm using include:
-- Background
-- Border
-- Spacing
-- Typography
-- Dimensions

**Comment by kprovance** [comment]
I'll put it on my to-do list.  Thanks.

**Comment by dovy** [comment]
@TinyGiantStudios Wordpress doesn't have any such fields. Background, border, spacing, typogrpahy, dimensions. 

Yes they may be "simple" fields, but WordPress doesn't have them. At this time our customizer is only what WordPress supports. In a little while we'll be bringing all of our extensions into the customizer, but it will be a paid extension.

Sorry for the delay. We've had some code for that for ages, but life has got in our way. We're doing the best we can.

If you would like to sponsor the effort, it would sure put it towards the top of our list. It's just hard doing lots of work for very little financial gain.  ;)

**Comment by TinyGiantStudios** [comment]
Hey @dovy,

Totally bummed if my posting across as criticism - not intended that way. You guys are doing awesome work, and at least two of my plugins would never have seen the light of day if it wasn't for you...

As soon as your customizer plugin hits te shelf, I'll be sure to grab a copy. It's a must in my books :)

**Comment by dovy** [comment]
Same for me. I want to get it done. Just have to find the time for it.  ;)
