### ISSUE TITLE
Select sortable field not working properly

### ISSUE THREAD

**Issue by mekshq** [ReduxFramework/redux-framework#2025]
Setup: Redux version is 3.4.1 but problem existed in previous versions as well. And this only happens on WordPress version 4.1 (I can confirm that 4.0 is working fine).

Bug: When you try to sort items in select field they always switch back to previous order after saving the options. I guess that problem is somewhere in js files but haven't find the way to make it fix myself...

Thanks

**Comment by kprovance** [comment]
Per #1975, if you don't provide some code, I can't try it, and can't do anything about it.

**Comment by mekshq** [comment]
Found a fix, the error is in file redux.select2sortable.js

<pre>
if($(this).data('select2Data') != undefined){
var id = $(this).data('select2Data').id;
return $select.find('option[value="' + id + '"]')[0];
 }
</pre>

I'm not a javascript expert but it needs an "if" statement to avoid javascript error.

What code I need to provide? It breaks in every case on wp 4.1 with select sortable field

**Comment by mekshq** [comment]
Here's an example case of my field definition if it may help:

<pre>
array(
                        'id'        => 'home_fa_posts_manual',
                        'type'      => 'select',
                        'data'      => 'post',
                        'multi'     => true,
                        'sortable'     => true,
                        'title'     => __('Choose posts', THEME_SLUG),
                        'subtitle'  => __('Pick your featured area posts manually', THEME_SLUG),
                        'desc'      => __('Note: Please keep in mind that number of picked posts must match your layout limit (i.e. if you are using 3+4 layout, choose 7 posts)', THEME_SLUG),
                        'args' => array('posts_per_page' => 100, 'post_type' => array('post','page')) 
                    ),
</pre>

**Comment by kprovance** [comment]
The author of that library has not updated it in almost two years, which suggests abandonment.  I don;t have the time right now to dig into that code and debug it.  You're welcome to give it a shot, but it's going to be a few weeks for me to even think about it.

**Comment by mekshq** [comment]
I have just sent you a solution: 

Just adding an if statement here:

<pre>
if($(this).data('select2Data') != undefined){
var id = $(this).data('select2Data').id;
return $select.find('option[value="' + id + '"]')[0];
 }
</pre>

Can't you just apply it and update the minified version of the script and push the update? It is not a minor issue, it means that everyone that has latest wordpress version will have a bug if select sortable field is used in redux.

**Comment by kprovance** [comment]
Fine.  Pushed v.3.4.2.1.  And since I dropped everything just to tend to this matter, I hope perhaps a donation to our project will be forthcoming.  :)

**Comment by mekshq** [comment]
Thanks :) Will do, but I have just tried to help both you, me, and all other redux users with this fix ;)

**Comment by kprovance** [comment]
Perhaps, but

<blockquote>
Can't you just apply it and update the minified version of the script and push the update?
</blockquote>

Still amounts to me dropping what I'm doing - work I actually get paid for.

**Comment by dovy** [comment]
We're working hard on a theme right now. We appreciate the support, but it does take us time to submit these things unless there's a pull request.

In the future if you submit a fix, send a pull request. That will make it literally seconds for us to implement than to stop what we're doing.

Thanks!

**Comment by mekshq** [comment]
Of course, I understand and really appreciate your efforts! Good luck with the theme and if you need any thoughts or second opinions feel free to ask, we would be glad to help :)

However, I bet that you wouldn't want that bug in your fresh new theme either, for all your WP 4.1 users ;)

**Comment by dovy** [comment]
Hehe, we don't use sortable, but I am sure others will love it.  :)
