### ISSUE TITLE
Output option variables on front end

### ISSUE THREAD

**Issue by cpfeifer** [ReduxFramework/redux-framework#2026]
Hi, I'm just getting started with the framework (totally awesome by the way), and the answer to this is probably very simple and right in front of me, but I haven't found what I'm looking for quite yet.

I have a color chooser and some other options working fine in the backend, I'm trying to apply a color value to the front end without a compiler. What call would I use from the object array to output a value to store in a variable or output directly? For example I saw this syntax in a demo theme: **$my_options['basecolor1']** - but it's not working for me, basecolor1 is the id of the color chooser in question. Any help is appreciated.

**Comment by kprovance** [comment]
The question is too general.  Please review out docs site:  http://docs.reduxframework.com.  Also, a working knowledge of PHP is required to use Redux.

**Comment by cpfeifer** [comment]
I know PHP, and I have reviewed the documentation. Can you point me to a specific article in your documentation that explains how to output the options for use on the front. That's all I need to know. Thank you.

**Comment by cpfeifer** [comment]
Never mind, I found it. I wasn't using the output argument, that's missing piece I was looking for. Thanks.

**Comment by dovy** [comment]
No worries! If you have ideas for how we can improve our documentation we're all ears.  :)

**Comment by cpfeifer** [comment]
First of all, thanks for making and supporting this great framework, I'll be using it a lot now that I found it. My only comment on the docs is that there isn't much in terms of how to use the option settings on the front end, all the setup and backend stuff is great. I'd be happy to contribute once I fully wrap my head around everything. Thanks again.

**Comment by dovy** [comment]
Point taken. It's just hard for us since we use this all the time. If you want to write an article I KNOW the community would appreciate it. I just don't know how to explain things like that since it seems so second nature to me now.

Thank you for being patient and I hope you love Redux.  :)

**Comment by cpfeifer** [comment]
I totally understand the time constraint, I work on a number of open source projects and contribute docs all the time so I know the drill :) The project I'm using this on is pretty complex, so I'll definitely have a full understanding once I get through it.
