### ISSUE TITLE
Activate theme = Notice: Undefined index: opt-slides

### ISSUE THREAD

**Issue by AlexAlexandru** [ReduxFramework/redux-framework#2027]
WordPress: v4.1
Redux v3.4.2.3 Embed Only(from the build generator )
PHP v5.6.3
'dev_mode' => true,
'WP_DEBUG', true

I generate a theme from the build website and activate the theme and this is what I get
```php
Notice: Undefined index: opt-slides in C:\xampp\htdocs\wp-content\themes\betty-theme\admin\redux-framework\ReduxCore\framework.php on line 2165
```

**Comment by kprovance** [comment]
And you did what to get this error?  Load the page, reset?  Some more details, please.

**Comment by AlexAlexandru** [comment]
As I said I got the theme.I upload the theme.Then I go to Appearence > themes and I just click Activate button on my generated theme.

**Comment by kprovance** [comment]
Can't reproduce, so I'm guessing at the fix.  v.3.4.2.4 pushed.
