### ISSUE TITLE
Which action gets triggered when i save settings ?

### ISSUE THREAD

**Issue by bravokeyl502** [ReduxFramework/redux-framework#2028]
I want to write to a file using the options defined by user but i need to write/update this file every time user updates settings.How can i do this ? Is there any action that gets fired every time user updates settings ?

i know added_option()

Thanks

**Comment by kprovance** [comment]
Replace `<opt name>` with whatever your opt_name argument is.

```
add_action ("redux/options/<opt name>/saved", "saved_function", 10, 2)

function saved_function ($options, $changed_values ) {
    ...
}
```

**Comment by bravokeyl502** [comment]
Thanks
