### ISSUE TITLE
Different options array for different users

### ISSUE THREAD

**Issue by bravokeyl502** [ReduxFramework/redux-framework#2030]
Is it possible to store different options arrays for different users ? Let's say user1 sets some option values , then store them in redux_options_user1 array and user2 options in redux_options_user2

I think we can do this by setting opt_names different for different users like this

 `"opt_name" => 'redux-option'.get_current_user_id()`

Or do we have to change global variable for this.

In this case how can i use 
`
$action = "redux/options/halloi_options".get_current_user_id()."/saved";
add_action ($action, "options_saved", 10, 2);
function options_saved($a,$b){}
`
Did redux has this kind of functionality ?

**Comment by dovy** [comment]
That should work fine. It's nothing special. You're just updating the opt_name by user id. If no user is signed in value 0 will be returned.  ;)
