### ISSUE TITLE
Compiler question

### ISSUE THREAD

**Issue by AlexAlexandru** [ReduxFramework/redux-framework#2033]
Here is a quick video https://www.youtube.com/watch?v=nDQMc6CwdjU&feature=youtu.be Is it posible to keep my .f-dropdown styles and only to update the .site-title using the compiler?

**Comment by kprovance** [comment]
Possibly?  I'm not sure.  These kinds of questions fall under premium support.

**Comment by dovy** [comment]
This is purely in your own code. What I would do is the following...

I'd append some commented string to that file where your Dynamic CSS goes. Then on save, I'd grab the file contents until that parsed line. Then you can append the newly compiled data and have all your asking.

But, as @kprovance points out, we can't code that for you unless you provide us with premium support. It's not part of our framework, but a feature you want and use in your code.  ;)

Good luck!
