### ISSUE TITLE
Group Field

### ISSUE THREAD

**Issue by DJMIMi** [ReduxFramework/redux-framework#2036]
When I try to implement group field for example with this code:

array( 'id' => "group", 'type' => 'group',//doesn't need to be called for callback fields 'repeatable'=> true, 'title' => __('Group - BETA', 'redux-framework-demo'), 'subtitle' => __('Group any items together. Experimental. Use at your own risk.', 'redux-framework-demo'), 'groupname' => __('Group', 'redux-framework-demo'), // Group name 'fields' => array( array( 'id' => '2', 'type' => 'text', 'title' => __('Test Field', 'redux-framework-demo'), 'subtitle'=> __('', 'redux-framework-demo'), 'desc' => __('', 'redux-framework-demo'), ), ) ),

I get following error:
Fatal error: Call to private method ReduxFramework::get_default_output_string() from context 'ReduxFramework_group' in C:\wamp\www\blogus\wp-content\plugins\redux-framework\ReduxCore\inc\fields\group\field_group.php on line <i>104</i>

**Comment by kprovance** [comment]
The group field is no longer supported, or available.  We now have the repeater field:  http://reduxframework.com/extension/repeater/
