### ISSUE TITLE
How can i get category posts from my specific selected category?

### ISSUE THREAD

**Issue by easin55474** [ReduxFramework/redux-framework#2037]
I want to get category posts from my specific selected category using redux? how can i do that. anyone help please.  I am newly using redux and always love to use redux.

**Comment by kprovance** [comment]
Using what field, in what scenario?  This is too general question.  Please check out our docs site:   http://docs.reduxframework.com/

**Comment by easin55474** [comment]
Hello,
Thanks for give me the answer.. I was using select field to get the category posts. please take look on my code. how can i get my selected category post. I was trying more and more.. please help me to get my selected category post. please

array(
            'id' => 'opm_services',
            'type' => 'select',
            'data' => 'posts',
            'title' => __('Select category post', 'opm'),
            'args' => array('post_type'=>'post', 'cat' => 'categories'),
            'multi'=> true,
            'sortable'=>true
        ),

**Comment by easin55474** [comment]
I want to get my category post from my selected category. Please see my screenshot for batter understanding.   http://prntscr.com/62qos0

Please help me.

**Comment by kprovance** [comment]
You need to use arguments as outlined on this page from the WP codex:  http://codex.wordpress.org/Template_Tags/get_posts.

The issue tracker is designed for issues with the framework, bugs and the link.  Asking us to fix your code would require premium support, since it's more of a PHP issue.
