### ISSUE TITLE
Customizer Issues! 

### ISSUE THREAD

**Issue by sgssandhu** [ReduxFramework/redux-framework#2038]
This is a GREAT Framework and I love it. 
But customizer extension really needs improvements.

1. If we have menu and submenus in redux admin panel, The fields that are directly under the menu are not shown in the customizer ! Please see screenshot.
![customizer_issue](https://cloud.githubusercontent.com/assets/1094719/6098703/0f57bfa4-b00d-11e4-8cf2-e3c25f2b4c79.jpg)
2. Only text boxes, select boxes and check boxes are defined in customizer. Please also add support for other field types.  I have converted the switches at the admin panel to check boxes at the customizer area. Please tell me if I need to share the code.

Redux-Framework Version: 3.4.2.6
Using Redux as: Theme
Wordpress Version: 4.1
'dev_mode' => true,
Browser console errors: None

**Comment by kprovance** [comment]
Addressed in issue #2024

**Comment by sgssandhu** [comment]
@kprovance : Hi, Only 2. point is similar to issue #2024 but 1. is different issue and surely is a bug. The issue is not about the some type of fields not showing but the issue is the whole section is missing even if we have only text boxes as the fields.
Let me explain the issue again !

Let's say we have following menu TREE and we have only text boxes as the fields(elements)

- Color Settings
- General Settings
  - Header Settings
  - Page Settings
  - Footer Settings
- Background Settings
- General Settings

Now issue is elements in all the sections are there at customizer except the **General Settings**. 
The sections which have sub-sections are completely missing in the customizer. Please test it once and ask if you need further explanation !

Thanks

**Comment by kprovance** [comment]
That larger point - which I guess you missed - was this:

<blockquote>
Yes they may be "simple" fields, but WordPress doesn't have them. At this time our customizer integration is only what WordPress supports. In a little while we'll be bringing all of our extensions into the customizer, but it will be a paid extension.
</blockquote>

That said, Dovy is away on a family thing.  He'll be back late tomorrow, at which time I am sure he'll also comment.  :)

**Comment by sgssandhu** [comment]
Hi, I was able to fix the above mentioned serious bug. Issue is in the IF condition at line no 242 in 

I was able to fix it by replacing
```
if ( method_exists( $wp_customize, 'add_panel' ) && ( ! isset( $section['subsection'] ) || ( isset( $section['subsection'] ) && $section['subsection'] != true ) ) && isset( $this->parent->sections[ ( $key + 1 ) ]['subsection'] ) && $this->parent->sections[ ( $key + 1 ) ]['subsection'] ) {

                        $wp_customize->add_panel( $section['id'], array(
                            'priority'       => $section['priority'],
                            'capability'     => 'customize',
                            'theme_supports' => '',
                            'title'          => $section['title'],
                            'description'    => $section['desc'],
                        ) );
                        $panel = $section['id'];

                    } else {
                        if ( ! isset( $section['subsection'] ) || ( isset( $section['subsection'] ) && $section['subsection'] != true ) ) {
                            $panel = "";
                        }
                        $wp_customize->add_section( $section['id'], array(
                            'title'       => $section['title'],
                            'priority'    => $section['priority'],
                            'description' => $section['desc'],
                            'panel'       => $panel
                        ) );
                    }
```

with

```
if ( method_exists( $wp_customize, 'add_panel' ) && ( ! isset( $section['subsection'] ) || ( isset( $section['subsection'] ) && $section['subsection'] != true ) ) && isset( $this->parent->sections[ ( $key + 1 ) ]['subsection'] ) && $this->parent->sections[ ( $key + 1 ) ]['subsection'] ) {

                        $wp_customize->add_panel( $section['id'], array(
                            'priority'       => $section['priority'],
                            'capability'     => 'customize',
                            'theme_supports' => '',
                            'title'          => $section['title'],
                            'description'    => $section['desc'],
                        ) );
                        $panel = $section['id'];

                        $wp_customize->add_section( $section['id'], array(
                            'title'       => $section['title'],
                            'priority'    => $section['priority'],
                            'description' => $section['desc'],
                            'panel'       => $panel
                        ) );


                    } else {
                        if ( ! isset( $section['subsection'] ) || ( isset( $section['subsection'] ) && $section['subsection'] != true ) ) {
                            $panel = "";
                        }
                        $wp_customize->add_section( $section['id'], array(
                            'title'       => $section['title'],
                            'priority'    => $section['priority'],
                            'description' => $section['desc'],
                            'panel'       => $panel
                        ) );
                    }
```

**Comment by dovy** [comment]
Yay, you fixed the customizer! Thank you. Pushed.
