### ISSUE TITLE
Composer fork

### ISSUE THREAD

**Issue by alexVauch** [reduxframework/redux-framework#2039]
Hi there!

Composer [version](https://github.com/redux-framework/redux-framework/tree/master) of plugin is outdated. Please update [package](https://packagist.org/packages/redux-framework/redux-framework)  to the latest version.

Thank you.

**Comment by dovy** [comment]
Hey there. We've updated the ReduxFramework organization so that the main repo can now take the composer package. It's been updated. Do an update and all should work.
