### ISSUE TITLE
Redux Framework embedded in two plugins activated on same site

### ISSUE THREAD

**Issue by phillipw1994** [ReduxFramework/redux-framework#2042]
Hi i am trying to use the Redux Framework on multiple plugins however when they are both activated there is only one options panel instead of two. I think one is being overridden because of the position so how would i fix this from happening.

**Comment by dovy** [comment]
99% sure you're using the same class name for each and one is running before the other. Make your class names unique to you. ;)

**Comment by phillipw1994** [comment]
How would i go about changing these

**Comment by phillipw1994** [comment]
Thanks for the help i have it sorted now
