### ISSUE TITLE
Problem in Image Select Type

### ISSUE THREAD

**Issue by krishna19** [reduxframework/redux-framework#2043]
i use image select field type for background pattern selection. The spaces between the rows are not working.
<pre>
    array(
        'id'       => 'opt-patterns',
        'type'     => 'image_select',
        'tiles'    => true,
        'title'    => __( 'Images Option (with pattern=>true)', 'redux-framework-demo' ),
        'subtitle' => __( 'Select a background pattern.', 'redux-framework-demo' ),
        'default'  => '',
        'options'  => $sample_patterns,
    ),
</pre>
Redux Version : 3.4.2.6
![screen shot 2015-02-11 at 10 18 22 am](https://cloud.githubusercontent.com/assets/4782674/6142216/df387800-b1d7-11e4-8e28-eb0ae49a063b.png)

Thanks

**Comment by dovy** [comment]
Care to configure a fix after you test it in different browsers?

**Comment by krishna19** [comment]
Already i check in two browsers Firefox 35.0.1 & Chrome 40.0.2214.111.

**Comment by kprovance** [comment]
Updated in latest push.  3.4.3.4
