### ISSUE TITLE
I want to sample display Gallery <img>.

### ISSUE THREAD

**Issue by wasantec** [ReduxFramework/redux-framework#2046]
I want to sample display Gallery <img>.

http://docs.reduxframework.com/core/fields/gallery/

thank

**Comment by kprovance** [comment]
What exactly is the question?

**Comment by wasantec** [comment]
I want to show Gallery all

<?php global $test_option;  echo $test_option['gallery']; ?>

<img src=" your code "/>

**Comment by wasantec** [comment]
in < img src=" your code " />

**Comment by kprovance** [comment]
From the docs:
<blockquote>
The gallery field returns a comma separated value of the attachment IDs of the selected images.
</blockquote>

So you have to explode those values and use them in a for loop with http://codex.wordpress.org/Function_Reference/wp_get_attachment_image_src

**Comment by wasantec** [comment]
use ? 

<?php global $test_option; echo $test_option['gallery']; ?>
$test = $test_option['gallery'];
and  echo $test ; 
 theme option test output =  30,25,26,27,28,29,30

<?php 
$attachment_id = 8; // attachment ID

$image_attributes = wp_get_attachment_image_src( $attachment_id ); // returns an array
if( $image_attributes ) {
?> 
<img src="<?php echo $image_attributes[0]; ?>" width="<?php echo $image_attributes[1]; ?>" height="<?php echo $image_attributes[2]; ?>">
<?php } ?>

**Comment by dovy** [comment]
We can't help you code basic WordPress stuff. It's beyond our job description.   ;)    Look at the myriad of articles online to learn how.

Best of luck!

**Comment by Mahbubur-Rashid** [comment]
how to show redux option gallery to the font page
