### ISSUE TITLE
color_rgba - transparent: value should be transparent

### ISSUE THREAD

**Issue by Ninos** [reduxframework/redux-framework#2047]
If you select transparent on the color_rgba field (color picker), the returned value should be transparent, not empty. Also if you select a color and set the alpha value to 0, you'll get the color and an alpha value 1.

**Comment by aman704** [comment]
Same issue for me too.

**Comment by kprovance** [comment]
SO, make the change and submit a pull request.  :)

**Comment by yerooleopard** [comment]
I have same issue with $option['alpha'] when equals 0, is there any progress?

**Comment by kprovance** [comment]
Since it's up to me to have to fix this the proper way, all I can say is 'eventually'.  I'm hip deep in work that pays.  I'll get to this as soon as I can.

**Comment by kprovance** [comment]
Updated in latest push 3.4.3.4

**Comment by Ninos** [comment]
I don't want to say something, thx for your fix but the bug still exists. A value "0" in the validation part is still not possible. So what you done is a simple workaround. ```rgba(*,*,*,0)``` is still not working. I would really implement my pull request. This will also not break something, if you have looked into the code and just affects the validation functions.. :-)

**Comment by kprovance** [comment]
Validation for fields should not be done in the core, has always been my point.  It needs to be done at the field level, or via a validation class (yes, I know the one for colorrgba in the validation folder doesn't work, it never has).  Again, you're free to tinker with that, but changing the core for one field for one use case is not something we like to do, because of those alternatives.

**Comment by Ninos** [comment]
This bug does not just affect the colorrgba field. This affect all the core. A value "0" is not possible on every field type with a using validation. This is because you check the field values with the ```empty()``` function and ```empty("0")``` also returns true.
Because of your workaround for me the merging of my pr is not important anymore. For me it's just not a nice way to fix something outside of the problem, if the bug exists in core, with the reason that you don't want to touch the core :)
If you're still interested in my pr, just let me know, so I'll fix the merge conflicts, otherwise close it please.

**Comment by dovy** [comment]
I merged this in after I tested it. Great work Ninos. Gave you credit.

**Comment by Ninos** [comment]
Nicee, thx :)
