### ISSUE TITLE
[translation bug] Some words missing

### ISSUE THREAD

**Issue by kwayyinfotech** [reduxframework/redux-framework#2049]
Hello,

Recently I checked the "typography" element and found that the word "Font Family" word is not found in the pt_PT.mo file. I checked the pt_PT.mo file and found that the word is as "Font family" so it cannnot translate.  

I also checked that the other words also not translated so I think it should be re-scan and re-generate so it will work with all other words too.

Thanks,
Bob

**Comment by dovy** [comment]
Sorry, but it should be. If you look here:
https://github.com/reduxframework/redux-framework/blob/master/ReduxCore/inc/fields/typography/field_typography.php#L227-L228

You can clearly see the strings are there. Also in our pot file: https://github.com/reduxframework/redux-framework/blob/master/ReduxCore/languages/redux-framework.pot#L398-L404

It is clearly listed.

Are you sure you didn't previously translation it to be something else? Also have you checked out language translation project? https://www.transifex.com/organization/wp-translations/dashboard/redux-framework

It would be best to translate there so everyone could benefit.  :)

**Comment by kwayyinfotech** [comment]
Hello,

I think I haven't describe you with details. Let me explain.

I am creating a custom theme with Redux Framework. I like to make it translation ready. So I am using Redux's translation files.

Currently I am testing the translation and checking if everything is translated or not. I translated my WordPress to "Portuguese" language. So it loads the **pt_PT.mo** file for translation. All other words are translated from my custom language files but the custom text like "Font Family" and "Font family" are written in the Redux files so it should translated in the Redux's **pt_PT.mo** file. But it's not there. The pt_PT.mo file contain the "Font family" BUT does not contain translated word for "Font Family". 

I know that pt_PT.mo is encoded file but I managed to open it by this command (on linux):
`msgunfmt /var/www/html/howes/wp-content/themes/customtheme/inc/ReduxCore/languages/pt_PT.mo`

The command output:
`
msgid ""
msgstr ""
"Project-Id-Version: Redux Framework\n"
"Report-Msgid-Bugs-To: https://github.com/ReduxFramework/ReduxFramework/"
"issues\n"
"POT-Creation-Date: 2014-09-24 17:38:11+00:00\n"
"PO-Revision-Date: 2015-01-16 13:42+0000\n"
"Last-Translator: Ricardo H. <rickrsh@gmail.com>\n"
"Language-Team: Portuguese (Portugal) (http://www.transifex.com/projects/p/"
"redux-framework/language/pt_PT/)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Language: pt_PT\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"
"X-Generator: grunt-wp-i18n 0.4.8\n"
"X-Poedit-Basepath: ../\n"
"X-Poedit-Bookmarks: \n"
"X-Poedit-Country: United States\n"
"X-Poedit-KeywordsList: __;_e;_x:1,2c;_ex:1,2c;_n:1,2;_nx:1,2,4c;_n_noop:1,2;"
"_nx_noop:1,2,3c;esc_attr__;esc_html__;esc_attr_e;esc_html_e;esc_attr_x:1,2c;"
"esc_html_x:1,2c;\n"
"X-Poedit-SearchPath-0: .\n"
"X-Poedit-SourceCharset: UTF-8\n"
"X-Textdomain-Support: yes\n"

msgid "Activate Demo Mode"
msgstr "Ativar modo demo"

msgid "Active"
msgstr "Ativo"

msgid "Add More"
msgstr "Adicionar mais"

msgid "Add/Edit Gallery"
msgstr "Adicionar/Editar Galeria"

msgid "All"
msgstr "Todos"

msgid "Background Attachment"
msgstr "Anexo do fundo"

msgid "Background Position"
msgstr "Posição do fundo"

msgid "Background Repeat"
msgstr "Repetir fundo"

msgid "Bottom"
msgstr "Fundo"

msgid "Changelog"
msgstr "Registo de alterações"

msgid "Close"
msgstr "Fechar"

msgid "Copy"
msgstr "Copiar"

msgid "Copy Link"
msgstr "Copiar ligação"

msgid "Credits"
msgstr "Créditos"

msgid "Deactivate Demo Mode"
msgstr "Desativar modo demo"

msgid "Default"
msgstr "Por defeito"

msgid "Delete"
msgstr "Eliminar"

msgid "Description"
msgstr "Descrição"

msgid "Disable"
msgstr "Desactivar"

msgid "Dismiss"
msgstr "Ignorar"

msgid "Documentation"
msgstr "Documentação"

msgid "Download"
msgstr "Baixar"

msgid "Enable"
msgstr "Ativar"

msgid "Expand"
msgstr "Expandir"

msgid "Export Options"
msgstr "Exportar opções"

msgid "Font color"
msgstr "Cor da fonte"

msgid "Font family"
msgstr "Fonte"

msgid "Font style"
msgstr "Estilo da fonte"

msgid "From "
msgstr "De"

msgid "Height"
msgstr "Altura"

msgid "Import"
msgstr "Importar"

msgid "Import / Export"
msgstr "Importar / Exportar"

msgid "Import / Export Options"
msgstr "Importar / Exportar opções"

msgid "Import Options"
msgstr "Importar opções"

msgid "Import from URL"
msgstr "Importar de URL"

msgid "Import from file"
msgstr "Importar de ficheiro"

msgid "Left"
msgstr "Esquerda"

msgid "Letter Spacing"
msgstr "Espaçamento entre letras"

msgid "Off"
msgstr "Desligado"

msgid "On"
msgstr "Ligado"

msgid "Options"
msgstr "Opções"

msgid "Password"
msgstr "Palavra-passe"

msgid "Remove"
msgstr "Remover"

msgid "Reset All"
msgstr "Restabelecer todos"

msgid "Reset Section"
msgstr "Restabelecer secção"

msgid "Right"
msgstr "Direita"

msgid "Save Changes"
msgstr "Guardar Alterações"

msgid "Select an item"
msgstr "Selecionar um item"

msgid "Size"
msgstr "Tamanho"

msgid "Style"
msgstr "Estilo"

msgid "System Info"
msgstr "Informações do sistema"

msgid "Title"
msgstr "Título"

msgid "To "
msgstr "Para"

msgid "Top"
msgstr "Topo"

msgid "Transparent"
msgstr "Transparente"

msgid "URL"
msgstr "URL"

msgid "Upload"
msgstr "Carregar"

msgid "Username"
msgstr "Utilizador"

msgid "Version %s"
msgstr "Versão %s"

msgid "Width"
msgstr "Largura"

msgid "Word Spacing"
msgstr "Espaçamento entre palavras"

msgid "Working..."
msgstr "A trabalhar..."

msgid "You do not have sufficient permissions to access this page."
msgstr "Não tem permissões suficientes para aceder a esta página."
`

As you can see the **Font family** word is there but the **Font Family** word is not found.

Also I am using latest version of Redux framework.

**Comment by kwayyinfotech** [comment]
I found that the word is not translated because it's not translated on the https://www.transifex.com/ site. Sorry to bother you.

**Comment by kprovance** [comment]
You understand that the Transifex repo is open community.  That is, you can create an account and add changes as needed.  We set our project up this way so folks wouldn't have to wait for us to drop everything we're doing and do it for them.
