### ISSUE TITLE
Footer_text not work properly

### ISSUE THREAD

**Issue by abukwaik** [ReduxFramework/redux-framework#2050]
WordPress version: 4.1
ReduxFramework version: 3.4.2.9
dev mode: false
using Redux: embedded in a project.

Hello guys, After upgraded to the 3.4.2.9 version, "Footer_text" now is not shown.

Thank you

**Comment by dovy** [comment]
Sorry about that. I'll fix it up early next week. Working on Ajax saving.  ;)

**Comment by abukwaik** [comment]
No problem @dovy i wish good luck ^_^ 

Thank you.

**Comment by dovy** [comment]
Actually just pushed a fix. Forgot `echo`.  ;)

**Comment by dovy** [comment]
You can tinker with Ajax save by setting `'ajax_save' => true`. Let me know what you think.  ;)

**Comment by abukwaik** [comment]
Great :+1: Again Thank you.
OK, Sounds very nice.

**Comment by abukwaik** [comment]
@dovy Actually it works nice and looks cool but when i hit save it just keep loading till i refresh the page manually. Test it in Firefox  and Chrome.
