### ISSUE TITLE
Problem with Google Fonts not using https

### ISSUE THREAD

**Issue by garcialinares** [reduxframework/redux-framework#2051]
Hello,

One question. I have SSL on my site. So, when I select some font family in typography I want to use https instead of http. Is it possible to change it to use Google Fonts with https? What should I modify to use always https when I select one Google Font?

Thank you.

**Comment by kprovance** [comment]
Without the required information from #1975 , it's difficult to say.  The google-font stylesheet link Redux generated automatically detects the https protocol, so, other than that, I'm not sure what you're referring to.

**Comment by dovy** [comment]
Yea, we automatically account for this.  ;)
