### ISSUE TITLE
Got WARNING: file_get_contents, when i tried to upload theme in wordpress

### ISSUE THREAD

**Issue by Shahedalam** [ReduxFramework/redux-framework#2052]
from sample-config.php
file_get_contents was found in the file theme_admin.php File operations should use the WP_Filesystem methods instead of direct PHP filesystem calls.

What should i use instead of file_get_contents ? , i tried WP_Filesystem , but got error , my be i don't know proper way . I want to use readme.md in Documentation.

Can you help me with some example , please.

**Comment by dovy** [comment]
Just made this for you and anyone else who may want it.

http://docs.reduxframework.com/uncategorized/wp_filesystem-proxy/

;)

**Comment by Shahedalam** [comment]
thank you :+1:
