### ISSUE TITLE
CALLING ALL DEVS - TEST AJAX SAVE!!!

### ISSUE THREAD

**Issue by dovy** [reduxframework/redux-framework#2053]
Hey there developers, we need you to test Ajax save for us. Especially in fields like checkboxes, sorter, multi-check, etc.

To enable ajax_save, you need only add `'ajax_save'=>true` to your arguments array and away you go.

Please report ANY issues here.

**Comment by matyushen** [comment]
Great! No issues fo far

**Comment by dovy** [comment]
Please be very thorough. I'd love to turn it on by default.

Check reset sections, compiler hooks, etc.

**Comment by dingo-d** [comment]
What differences are there with this enabled? I tried it with checkbox option on my personal site, and I still had to save with the save options button.

**Comment by kprovance** [comment]
Options don;t save when changing them individually.  The Save button still needs to be clicked.  The difference is they save without the page reload.

**Comment by Ninos** [comment]
I've tested all my fields (image, select, background, color, colorrgba, css,js, url, text, switch, presets, slider), also requirements & presets through different tabs and all's working fine.

PS: With ajax the theme options are very fast, nice work :)

**Comment by kprovance** [comment]
@Dovy will be *thrilled* to hear this.  :smile:

**Comment by Ninos** [comment]
haha that's not what I wanted to achieve with it :D

**Comment by dovy** [comment]
We're going to just push it soon. Ha.

**Comment by dingo-d** [comment]
Oh, that's the functionality! Cool, great job :)

**Comment by simrandeep** [comment]
It is working really fast now :)

**Comment by simrandeep** [comment]
Found a bug. Editor type field is not getting saved here with ajax_save enabled

**Comment by kprovance** [comment]
Dovy says he fixed it in the latest release.  Since you didn't specify which you have, all I can suggest is updating.  Sorry.

**Comment by simrandeep** [comment]
I'm using v3.4.3.2 that's the latest version. I am facing one more issue. Reset section button when pressed disables all three buttons - Save, Reset Section and Reset all

**Comment by kprovance** [comment]
Okay, so, start a new ticket, including information from #1975 and it'll get looked at.  Please don;t picky back old tickets with one liners, it wastes our collective time, and since I've seen you around before, you should know these guidelines by now.  Thanks.

**Comment by simrandeep** [comment]
I didn't open a new ticket because this thread was dedicated to Ajax Save issues. I am opening a new ticket now. Thanks
