### ISSUE TITLE
Save Options inside Callback Function?

### ISSUE THREAD

**Issue by jaschaio** [reduxframework/redux-framework#2055]
Hi, great work with the Framework, its really extremely helpful.

I copied the callback function from the sample-config.php to create my own custom field.

    if ( ! function_exists( 'mailchimp_lists' ) ):
     function mailchimp_lists() {
            global $MailChimp;
            $lists = $MailChimp->call('lists/list');
            echo '<select name="mailchimp[lists]['. $list['id'] . ']">';
            foreach ($lists['data'] as $list) {
            ?>
            <option value="<?php echo $list['id']; ?>"><?php echo $list['name']; ?></option>
            <?php
            }
            echo '</select>';
        }
    endif;

It works fine and shows the custom field pulling my lists from mailchimp. **But how do I save the selected option?**

**Comment by dovy** [comment]
Your select name must be: your_opt_name[field_id], then it will save properly. 

Happy coding!

**Comment by jaschaio** [comment]
Thanks a lot, sometimes the solution is so easy that you don't see it. Keep up the excellent work

**Comment by dovy** [comment]
Will do!

If you like Redux and the service we render, please do any or all of the following.

Like us: http://facebook.com/ReduxFramework
Follow up: http://twitter.com/ReduxFramework
Donate to keep us going: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=MMFMHWUPKHKPW

**Comment by dovy** [comment]
Oh and try setting ajax_save to true in your config with the newest version in the repo here.  ;)
