### ISSUE TITLE
Output a field for each term in taxonomy

### ISSUE THREAD

**Issue by Lawless55** [reduxframework/redux-framework#2056]
Is it possible to output a field for each term for a specific taxonomy. I'm trying to output a a field for each term in 'product_cat' (WooCommerce) taxonomy.

Here is my code:
```
if ( class_exists( 'WooCommerce' ) ) {
	$prod_cat_args = array(
		'taxonomy'     => 'product_cat'
	);
					
	$all_prod_categories = get_categories( $prod_cat_args );
	foreach ($all_prod_categories as $cat) {
		$prod_cat_field = array(
			'id'       =>    'text' . $cat->name,
			'type'   =>    'textarea',
			'title'    =>    __( 'Title', 'demo' )
		);
		$prod_cat_fileds[] = $prod_cat_field;	
	}
	$this->sections[] = array(
	        'title'  => __( 'Product Categories', 'demo' ),
	        'fields' => $prod_cat_fileds
	);
}
```
I'm not sure if this is a hook 'firing order' issue. But when I var_dump($all_prod_categories), it returns a WP_Error 'invalid_taxonomy'.

Any help or direction would be greatly appreciated.

**Comment by dovy** [comment]
It's because Redux is running before WooCommerce loads. Try delaying when your config file runs and it should work.

If not, then you're going to have to do some custom stuff... hah. But i've done this before. Shouldn't be too hard.

**Comment by Lawless55** [comment]
Hi @dovy the delay loading was my first 'go to', but after hours of Google'ing i wasn't able to find anything. Regarding the '...some custom stuff...' - are you referring to a custom field type?
