### ISSUE TITLE
Translate custom text in field

### ISSUE THREAD

**Issue by protasisimone** [reduxframework/redux-framework#2063]
Hi all, I've a question: Can I translate a custom text inserted into text field? Example: I've created a textarea with Redux Framework; an user insert your custom text in this textarea and after he can translate this text? 

It's possible?

Sorry for my bad english.

Thanks a lot

**Comment by dingo-d** [comment]
WPML comes to my mind. If you put that field in .xml file provided then it could be done.

**Comment by protasisimone** [comment]
And i wanna change a custom text into field?
Example: I wrote "Say hello" in field...can I translate? After, if I write "Say goodmorning" can i translate again? It's correct?

**Comment by kprovance** [comment]
WPML is your best bet.  This is not something Redux can or will do inherently.
