### ISSUE TITLE
Export menus

### ISSUE THREAD

**Issue by zealmurapa** [reduxframework/redux-framework#2067]
I am trying to export my menus with locations,
help with:

Primary (menu)		Primary Menu (menu location)

anyone?

**Comment by kprovance** [comment]
Is this a redux issue, or a theme issue?  If it's a theme issue, you need to contact whomever authored your theme.  The only thing Redux can and will export are option settings, not Wordpress settings.

**Comment by zealmurapa** [comment]
I am refering to this: 

https://github.com/Webcreations907/WBC-Importer-extension

**Comment by kprovance** [comment]
Then you need to post your question in his issue tracker, not ours.

**Comment by zealmurapa** [comment]
kprovance take it easy

**Comment by kprovance** [comment]
Okay?  But you're the one posting corrections to the incorrect issue tracker.  So, smarten up?

**Comment by zealmurapa** [comment]
Maybe you haven't noticed, but issues with Redux extensions are forwarded here. Just so you know

**Comment by dovy** [comment]
@zealmurapa, WBC_Importer is a project by one of our users. It supports Redux. We in NO way have anything to do with menu locations, unless you're using our extension widget areas. So then, again, it falls under their issue tracker not ours.

Best of luck!
