### ISSUE TITLE
Update an Option Outside the Options Panel

### ISSUE THREAD

**Issue by invisiblevision** [reduxframework/redux-framework#2068]
How can i pass an array to a set function , Like i have to change the 'background-color' of field 
'page-title' so it will be like this array('page-title'=>array('background-color')) but as set function only accepts string in first argument so i am unable to do so ,OR  Is there any alternative , Using JSON or js ?? 
i don't wanna use Iimage presets , as i am selecting color dynamically from color field and updating to all necessary fields
Thanks ! 

http://docs.reduxframework.com/core/advanced/update-an-option-outside-the-options-panel/

**Comment by kprovance** [comment]
Because the first argument is the string of your opt_name.  I suppose you could pass an array for the second parameter, but I;ve never tried it.  Anything you pass get's saved to the database as is.

**Comment by invisiblevision** [comment]
Awsome ! :+1:  You made my day , Thanks a lot ,

**Comment by dovy** [comment]
If you like Redux, please do some or all of the following.

Review us: http://wordpress.org/support/view/plugin-reviews/redux-framework
Like us: http://facebook.com/ReduxFramework
Follow us: http://twitter.com/ReduxFramework
Donate to keep us going: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=MMFMHWUPKHKPW
