### ISSUE TITLE
Including a custom config

### ISSUE THREAD

**Issue by jasperf** [reduxframework/redux-framework#2069]
Just started using your builder to make an options page / Redux Panel. Downloaded the admin folder and settings, added it to my Roots Sage theme and got it loaded. I also activated the plugin as I chose embedding + plugin usage (suggest + embed).

Then I copied the samle config ```admin/redux-framework/sample/sample-config.php```  to ```admin/config.php``` and added ```require_once (dirname(__FILE__) . '/admin/config.php');``` to my functions.php and made a small change in text and I changed the class name in the config file.

The required file is loaded and no errors there. But my changed text is not showing in the panel. I just changed the descripton at the top of the theme panel under home settings. Here the description as in the sample config panel:

```desc'      => __('Redux Framework was created with the developer in mind. It allows for any theme developer to have an advanced theme panel with most of the features a developer would need. For more information check out the Github repo at: <a href="https://github.com/ReduxFramework/Redux-Framework">https://github.com/ReduxFramework/Redux-Framework</a>', 'redux-framework-demo'),```

Other issue is that the panel now seems to be loaded twice

**Comment by jasperf** [comment]
Hmm, Seems ```options-init.php``` is a sample file I need to change too? I did and the data changed. Should I make a copy and rename and load it or just edit it?

**Comment by kprovance** [comment]
First, make sure the Redux demo is disabled, from the plugin menu.  Second, sample-config is just that, a sample, a guide.  Any change you make should be to whatever config file you are  loading via include.

**Comment by jasperf** [comment]
Decided to work with the Redux Framework plugin now. Downloaded it from Github.  And I added
```
function init_my_custom_redux() {
    require_once(dirname(__FILE__).'lib/redux-config.php');
}
add_action('plugins_loaded', 'init_my_custom_redux', 30);
```
to load only my redux config. Now panel is loaded only once. I also changed the class to one with an original name "Redux_Framework_img_config
I changed the title "Home Settings" to something else and reloaded. No joy. No changes were shown. I turned off dev mode in my config using
```
'dev_mode'             => false,
````
It did NOT turn off. 
Seems to be the same issue as here http://stackoverflow.com/questions/23937556/how-to-initiate-custom-redux-framework-config-file .

**Comment by jasperf** [comment]
Well once I removed the plugin's config sample file, my data in the new config was loaded. But I guess when I update the plugin I will have that file back again?
Loading the file like this now:
```
$sage_includes = [
  'lib/utils.php',                 // Utility functions
  'lib/init.php',                  // Initial theme setup and constants
  'lib/wrapper.php',               // Theme wrapper class
  'lib/conditional-tag-check.php', // ConditionalTagCheck class
  'lib/config.php',                // Configuration
  'lib/assets.php',                // Scripts and stylesheets
  'lib/titles.php',                // Page titles
  'lib/nav.php',                   // Custom nav modifications
  'lib/gallery.php',               // Custom [gallery] modifications
  'lib/extras.php',                // Custom functions
  'lib/redux-config.php',                // Redux Framework Config
];
```
