### ISSUE TITLE
Including custom sample config

### ISSUE THREAD

**Issue by essentialweb** [reduxframework/redux-framework#2071]
Hi, I have a difficult to use Redux following the installation instructions.

I have copied the sample-config.php into the theme root, changed the class name and added this line: require_once (dirname(__FILE__) . '/sample-config.php');, but it still uses the original file within the plugin.

Is there something wrong?

**Comment by kprovance** [comment]
Ensure the Redux demo is NOT enabled, and remove any include references in your code that may be pointing to that file.

**Comment by essentialweb** [comment]
I have installed it like a plugin. Is possible that it is the cause?
How do I disable the demo mode?

**Comment by kprovance** [comment]
From the plugin menu, where Redux Framework is listed.

**Comment by essentialweb** [comment]
Got it! 

Last thing: I don't understand why is requested to change the class name. I tried but it gives me error...

**Comment by kprovance** [comment]
To avoid conflict with any other plugin that might be using Redux.  If everyone used the same class name, nothing work work properly.

**Comment by essentialweb** [comment]
Is "Redux_Framework_sample_config" the class that need to be changed?

**Comment by kprovance** [comment]
Yes, and any other place in that config where that appears.  You do understand that a more than passing knowledge in PHP is required here.  If you don't have that, you will struggle with this.
