### ISSUE TITLE
Save Issue with Ajax Save Enabled in Editor Type Field

### ISSUE THREAD

**Issue by simrandeep** [reduxframework/redux-framework#2072]
Hi

I am facing a issue with editor type field with ajax save enabled. The editor field is not saving the data. It is showing that field is saved but when options panel is refreshed, I get the default values.

One more issue is there. If I press the reset section button then all three buttons - Save, Reset Section and Reset All buttons are disabled and becomes non-clickable.

Redux version is v3.4.3.2
WordPres: 4.1.1
No in dev_mode
Redux is embedded in theme

Thanks

**Comment by Ninos** [comment]
For me it's working fine. Which mode and validation function you're using? May you could post your config of the field?

Redux version: v3.4.3.2
Wordpress: 4.1.1
No dev_mode
Redux as plugin

**Comment by simrandeep** [comment]
I even tried with default sample config file supplied with Redux Framework and still the same issue.

Try doing this:

- Open options panel
- Change some text in "editor" type field
- Now save the options panel. You will see the notification that settings are saved.
- Now refresh the options panel. You will see that text in editor field is restored to default and it was not saved.

Here is the code:

<pre>

                    array(
                        'id'=>'bpxl_copyright_text',
                        'type' => 'editor',
                        'title' => __('Copyright Text', 'bloompixel'), 
                        'subtitle' => __('Enter copyright text to be shown on footer or you can keep it blank to show nothing.', 'bloompixel'),
                        'default' => '&copy; Copyright 2015. Theme by BloomPixel</a>.',
                        'editor_options'   => array(
                                'media_buttons'    => false,
                                'textarea_rows'    => 5
                            )
                        ),
</pre>

**Comment by dovy** [comment]
Boys, I have a fix, but I haven't pushed yet because I was working on another issue and it would break things in the panel. I'll have it pushed here really shortly. Give me a few.

**Comment by simrandeep** [comment]
Sure, I just reported the issue. We are not in hurry :)

Please check reset section issue too. It is making these buttons non-clickable.

**Comment by dovy** [comment]
This has just been pushed.  :)

**Comment by simrandeep** [comment]
Thanks :)

**Comment by messycodegirl** [comment]
Seems this issue has returned in Version 3.5.8.1 I have tried in Dev mode on/off. I am running Redux as a plugin. Any suggestions on a fix? Thanks!
