### ISSUE TITLE
Redux framework slowing my site homepage

### ISSUE THREAD

**Issue by shilpavashisht** [reduxframework/redux-framework#2073]
Redux framework is slowing (a no. of times kills homepage with loading time error) my site. I was getting a message to upgrade to newer version, which I was unable to. Now the site home page either doesnt load or loads too late. Not getting any upgrade version message. Current version is  3.4.1 .
Site -> exp.dentavacation.com

I also tried to disable dev_mode but nothing happened after putting dev_mode => false in config.php and adding some lines of code to functions.php.

**Comment by dovy** [comment]
First, are you a developer or a user? If you are a user, it's probably not Redux, but whomever coded your product. Redux is a framework that developers use.

If dev_mode is not disabling, there is another config file running somewhere. Try downloading this plugin: https://wordpress.org/plugins/redux-developer-mode-disabler/ It will disable all dev_mode arguments no matter what.

;)

**Comment by shilpavashisht** [comment]
I already used this dev_mode disabler but its not working.

Warm Regards,
Shilpa Vashisht

**Comment by dovy** [comment]
Then something else is wrong in your configuration. It works perfectly for everyone as it's a global override.

Are you sure you don't have a wayward plugin elsewhere?

**Comment by shilpavashisht** [comment]
I re-installed the theme and it is only my website's home page that's not
loading. After I deactivated redux, it loads fine, which means that redux
is the reason for site home page speed.

Can you please suggest me if turning off dev_mode would help? My current
wordpress theme is 4.1.1 and the dev_mode plugin is tested till 4.1.0 only,
so not really working on my website.

www.dentavacation.com

Warm Regards,
Shilpa Vashisht

**Comment by kprovance** [comment]
Really, it does not mean that at all.  Another plugin could be playing havoc, your php configuration could be off.  If you are using a crappy service like GoDaddy, that could also be a reason.  Honestly, if the problem were widespread, there would be at least one other person (if not thousands) flooding this tracker with the same complaint.  As you can see, there are not.  Sorry, but I too am not convinced Redux is the issue.

As for turning off dev_mode, that enables minified JS scripts and minified CSS, basically.  It also disabled various features devs use.

**Comment by shilpavashisht** [comment]
Can you tell me how to turn dev_mode off?

Warm Regards,
Shilpa Vashisht
