### ISSUE TITLE
Can not get Metaboxes installed correctly

### ISSUE THREAD

**Issue by ericwallen** [reduxframework/redux-framework#2074]
Hi, I just purchased metaboxes but can not for the life of me get them to work. I have added the extension and loader but nothing extra on any post or page appears. I do have a menu in my wp dashboard that says metaboxes. It pretty much looks like a custom post type or something. It appears to have no functionality.

I wish your docs would explain it like this..
First: Place files here
Second: call them like this
Third: do something else

It seems convoluted. What does this mean? "Because of WordPress hooks you need to include this before you create your ReduxFramework instance. It has to do with hooks. Just load this loader and your config settings prior to creating that object."

So this is what I put in to functions.php

require_once (dirname(__FILE__) . '/redux-ext/loader.php');

require_once (dirname(__FILE__) . '/redux-ext/config.php');

require_once (dirname(__FILE__) . '/redux-ext/extensions/metaboxes/extension_metaboxes.php');

require_once (dirname(__FILE__) . '/assets/redux-config.php');

I put the ext in a folder called "redux-ext"

Am I missing a step or what am I doing wrong?

Thanks, Eric

**Comment by dovy** [comment]
Ok, so the problem is the loader is what requires the files. So nix your inclusion of the extension_metaboxes.php file.

Also why not try the Redux builder? Using it gives you a customized fully working example. I suggest just exporting the admin folder to see how you do it.  ;)    http://build.reduxframework.com

**Comment by ericwallen** [comment]
Ok, so I just completely gave up a few months ago. I would like to get this working but the link you sent http://build.reduxframework.com will not let me log in. Pretty weird considering I am already logged in to the site and it let me download my items. 

Whats the deal with the builder? The same problem I faced a few months ago.

Also, why are we marking everything closed before you even get a response?

I know your not going to answer this but why is there not some simple explanation of how to install metabox?

Anyway, I guess every documentation page points to this generator that I can not get logged in to.

**Comment by ericwallen** [comment]
Yeah, I just created a whole new account and still can't get in to your builder. It simply wont accept any credentials. Can I send you my site and FTP so that  you can just install it for me? After I have a working code example I will have no problem moving forward from there. 

Thanks, please let me know how we can fix this.
