### ISSUE TITLE
RTL Theme options Issue

### ISSUE THREAD

**Issue by mahfoozroy** [reduxframework/redux-framework#2076]
Hi Team Redux

Redux version we are using 3.4.3
wordpress version: 4.1.1
Yes in dev mode
embedded in our Theme, I am a dev team member.
The issue is in your code for Right to Left languages.
rtl.css file.
in Theme Options Page, the main .redux-main "class" is there, But for RTL it is coded to be given a margin of 201px from right. 
there are 2,3 class like i mentioned below.
But actually in ReduxCore/assets/css/rtl.css it is coded like this.

#redux-container #expand_options,
#redux-sidebar,
.cb-enable,
.cb-disable,
.cb-enable span,
.cb-disable span,
#redux-footer #redux-share {
  float: right; 
}

#redux-main {
  border-left: 0px;
  margin-left: 0px;
  border-right: 1px solid #d8d8d8;
  margin-right: 201px;
 }
 the fixes are:
#redux-main should be .redux-main
#redux-container should be .redux-container
#redux-siderbar should be .redux-sidebar

please look for more changes like this in ReduxCore/assets/css/rtl.css
the way it is now it is a big problem for RTLs, because theme options page does not show up.
please fix this issue.

Thanks
Roy Mahfooz
Realty Theme Development Team

**Comment by dovy** [comment]
Awesome suggestion. I'm surprised no one has mentioned this before. We changed those keys like 6 months ago! I've made the changes and will be pushing a new version to this repo later today. I'm knee deep in some other fixes.

Thank you!

**Comment by mahfoozroy** [comment]
Hi Dovy

Thank you so much.
Glad to contribute :)

Thanks

**Comment by dovy** [comment]
Fix just pushed. Thanks again.

**Comment by mahfoozroy** [comment]
Thank you :)
