### ISSUE TITLE
Can you create 1:1 relationships? (Like you can with Posts 2 Posts plugin)

### ISSUE THREAD

**Issue by ReessKennedy** [reduxframework/redux-framework#2077]
I know Redux allows us easily create a select box option that allows us to query posts or custom posts and include them in a select or multi-select but anyone ever tried to create a 1:1 relationship like a true database using this? 

Example: I have two custom post types I want to connect. One is news. The other is team. I want to create a new news story and then using the multi select option to select all the team members this news story applies to. That part I get. And then I could output the team members. 

But then when I go back to a team members profile page I guess I also want to be able to output all news stories that have been associated with them. 

I guess if I wrote some code that looped through all news stories and only selected the ones that have this person associated with them that would work but it would be an inefficient database call, likely. I'm hoping someone knows exactly what I mean and has solved this already. Thanks.

**Comment by dovy** [comment]
So honestly we can't do miracles, just simple magic. heh. If the call you make is intensive, you'll need to use it in your panel sadly.

So the short answer is there's no easy answer.

**Comment by ReessKennedy** [comment]
Thanks @dovy

**Comment by dovy** [comment]
Wish I had better news for you, that's just the case.

You can, however, do a filter on the data argument I believe if you wanted to create a custom "data" hook.

If you like Redux, please do some or all of the following:
Review us: https://wordpress.org/support/view/plugin-reviews/redux-framework
Like us: http://facebook.com/ReduxFramework
Follow us: http://twitter.com/ReduxFramework
Donate to keep us going: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=MMFMHWUPKHKPW
