### ISSUE TITLE
Confirm Navigation on 

### ISSUE THREAD

**Issue by ReessKennedy** [reduxframework/redux-framework#2078]
Using the metabox extension and following the documentation, including just the basic metabox sample config code you include here http://docs.reduxframework.com/extensions/metaboxes/?_ga=1.130858123.549903214.1423688383 

BUT I when I try to update the page after changing the option I am getting the "Confirm Navigation" pop up. Any ideas? I search the Github issues and couldn't find anyone using this language or having this issue. 

![screen shot 2015-02-21 at 1 55 06 pm](https://cloud.githubusercontent.com/assets/3970267/6339580/329531f8-bb85-11e4-95df-cd96b0511849.png)

**Comment by dovy** [comment]
What version of metaboxes are you using?

**Comment by kprovance** [comment]
Could you confirm your purchase, with the email address you used when purchasing?  I have no record of ReessKennedy or any variation of it in our records.  Thanks.

**Comment by kprovance** [comment]
Closing.  Once you are able to confirm your purchase, please open a ticket in the proper issue tracker https://github.com/ReduxFramework/redux-extensions/issues.  Also - and I make no accusations - but if you've come across our metabox code through some means other than our site, please, pay for it.  A lot of work went into it.
