### ISSUE TITLE
Impossible set font-weight: false in typography field

### ISSUE THREAD

**Issue by antoniomangiacapra** [reduxframework/redux-framework#2079]
Wordpress version: 4.1
ReduxFramework version: 3.4.2.6
dev mode: true
google api key: no
using Redux: embedded in a project.

Hi guys, I am trying to make fields wich allow only modify font-size of headings, but font-weight is  always present, while font-weight is set to false.

I have miss something?
Thanks.

**Comment by dingo-d** [comment]
http://www.w3schools.com/cssref/pr_font_weight.asp

Of course you can't since that's not a valid value for font-weight property.

**Comment by antoniomangiacapra** [comment]
Maybe I am badly explained: I don't want show font-wieght select in option
panel

2015-02-24 12:16 GMT+01:00 dingo-d <notifications@github.com>:

**Comment by kprovance** [comment]
#1975  Show your code.

**Comment by antoniomangiacapra** [comment]
I am sorry.

My code is this:


array(
                            'id'          => 'typography-h1-size',
                            'type'        => 'typography', 
                            'title'       => __('h1, .h1', 'startertheme'),
                            'google'      => false, 
                            'font-backup' => false,
                            'output'      => array('h1,.h1'),
                            'units'       =>'px',
                            'text-align'  => false,
                            'text-transform' => false,
                            'subsets'     => false,
                            'line-height' => false,
                            'color'       => false,
                            'letter-spacing' => false,
                            'font-family' => false,
                            'font-weight' => false,
                            'font-size'   => true 
                        ),

And in panel there are font-size select and font-weight select.
Thanks and sorry again.

**Comment by kprovance** [comment]
Add 'font-style' => false,` to your field array.
