### ISSUE TITLE
Dimensions field units and final css output issues!

### ISSUE THREAD

**Issue by HELWATANY** [reduxframework/redux-framework#2080]
## Development Environment Info:
1. **The version of Redux you are using:** Redux Framework 3.4.3.2
2. **The version of WordPress you are running:** WordPress 4.1.1
3. **Redux dev_mode:** Enabled
4. **Integration mode:** Embedded
5. **ReduxCore location:** < theme-folder >/inc/core/redux/ReduxCore
6. **Options files location:** < theme-folder >/lib/options.php

## Field Code:
``` php
		array(
			'id'		=> 'unique_id',
			'type'		=> 'dimensions',
			'title'		=> __('FIELD_TITEL', 'txt_domain'),
			'desc'		=> __('FIELD_DESC', 'txt_domain'),
			'units'		=> array('rem'),
			'width'		=> true,
			'height'	=> false,
			'compiler'  => array('.test_class'),
			'default'   => array(
				'width'     => '64.25',
				'units'     => 'rem'
			)
		)
```

## Issue #1
The dimensions field doesn't support "rem" unit and when rendering the output of the options using the ```'output'``` or ```'compiler'``` arguments the final css always come without the unit even if the ```'units_extended'``` is set to true.

## Issue #2
The dimensions field doesn't support *float* values **EX:** *72.225* and the final css output using the ```'output'``` or ```'compiler'``` arguments always come with an integer value so if the entered value in the option panel is *72.225* the final css output will be *72225*!

## Solution for Issue #1:
**In "ReduxCore/inc/fields/dimensions/field_dimensions.php":** ((*Near line 69*)) Adding the 'rem' unit to the units array near line 69 should solve the problem.

## Solution for Issue #2
**In "ReduxCore/inc/fields/dimensions/field_dimensions.php":** ((*Near line 276*)) Changing the filter from ```FILTER_SANITIZE_NUMBER_INT``` to ```FILTER_SANITIZE_NUMBER_FLOAT, FILTER_FLAG_ALLOW_FRACTION``` in the process of storing the clean values in ```$cleanValue``` array will allow floats values in the final css output.

**Comment by kprovance** [comment]
First, kudos on the excellent reporting.  I wish everyone would do that!  :)

Second, care to submit these changes via a pull request?

**Comment by dovy** [comment]
That way you get the credit. I really hope you'll stick around and find more bugs! Also try ajax_save in your redux arguments.  ;)

**Comment by HELWATANY** [comment]
Thanks guys I really appreciate that :smile: 
@kprovance sure I will but I'm new to GitHub that's why I didn't want to miss things up :wink: 
@dovy I plan to! :+1:

**Comment by dovy** [comment]
Ping me on skype if you need help. DovyDigital. Or gchat: info@simplerain.com.

**Comment by kprovance** [comment]
Fixes pushed, credit given.  Thanks again!  ;)
