### ISSUE TITLE
Section field indent end

### ISSUE THREAD

**Issue by Webcreations907** [reduxframework/redux-framework#2081]
Hello hope all is well. :)

Seem to have a issue with section end field when indenting, something like the below will hide any fields after the indent=>false.

```
array(
    'id' => 'test-section-start',
    'type' => 'section',
    'title' => __('Test Section', 'framework'),
    'indent' => true
),
array(
    'id'        => 'test-text-field',
    'type'      => 'text',
    'title'     => __('Some Field', 'framework'),
    'subtitle'  => __('A Text Field', 'framework'),
),
array(
    'id'        => 'test-text-field-another',
    'type'      => 'text',
    'title'     => __('Some Field', 'framework'),
    'subtitle'  => __('A Text Field', 'framework'),
),
array(
    'id'     => 'test-section-end',
    'type'   => 'section',
    'indent' => false,
),
array( //This One Is Hidden
    'id'        => 'test-text-field-one-more',
    'type'      => 'text',
    'title'     => __('This isn\'t seen', 'framework'),
    'subtitle'  => __('A Text Field', 'framework'),
),
```
I see in ```field_section.php``` that the CSS class of ```hide``` is getting applied to the fields after, if I comment that hide class out the missing fields get shown correctly

WP v4.1.1
Redux 3.4.3.2 - 3.4.3.4
Embedded in theme

Thanks :)

**Comment by kprovance** [comment]
I guess I added that in there to fix someone elses issue.  Taking it out will surely break whatever that was.  I'll try and get to that soon.

**Comment by Webcreations907** [comment]
Great thanks, I just put/changed the below in ```field_section.php line 72``` there for now till you get a chance.

```
if ( isset( $this->field['indent'] ) &&  true === $this->field['indent'] ) {
    $add_class = ' form-table-section-indented';
} elseif( !isset( $this->field['indent'] ) || ( isset( $this->field['indent'] ) && false !== $this->field['indent'] ) ) {
   $add_class = " hide";
}
```

**Comment by kprovance** [comment]
Cool, I'll patch that in and push it. Honestly, I can;t remember what the original issue was, or any issue on the tracker about it...so if it comes back up, I'll deal with it then.  :)

**Comment by kprovance** [comment]
Okay, done.  Thanks again!

**Comment by Webcreations907** [comment]
Awesome, thanks :money_with_wings: __donated__ :wink:

**Comment by dovy** [comment]
Awesome. Thanks @Webcreations907
