### ISSUE TITLE
Reset Not Working Without Ajax Save

### ISSUE THREAD

**Issue by andrastudio** [reduxframework/redux-framework#2084]
My specs are:

1. Redux v3.4.3.4
2. WordPress 4.1.1
3. dev_mode = false
4. -
5. Standalone theme
6. Embedded in theme
7. No JS error

Tested on PHP 5.3.1 and 5.3.28

When Ajax save isn't activated using 'ajax_save' => true, the "Reset Section" and "Reset All" button doesn't seem to reset all of the options to the default values. But when I added 'ajax_save' => true to the arguments the reset buttons are working just fine.

However the reset buttons still worked even without activating ajax save when I tested on another environment running PHP 5.5.15.

**Comment by dovy** [comment]
Sorry, but I can't replicate. Update the newest Redux. I just tested on php 5.3.28...
