### ISSUE TITLE
Theme not shown in Customizer

### ISSUE THREAD

**Issue by ghostpool** [reduxframework/redux-framework#2085]
WordPress 4.1.1
Redux Framework 3.4.3.4 (integrated)

Hi guys,

The theme is not loaded at all in the preview window on the Customizer page. I removed the Redux framework and the theme then shows up suggesting this is related to the framework itself. Can you replicate this issue?

**Comment by dovy** [comment]
Umm... that's vague. I can't reproduce. Care to provide a theme for us to test? support@reduxframework.com.

**Comment by ghostpool** [comment]
I think it has to do with the number of options I have. If I remove nearly all the options or set 'customizer' to false then the site loads in on the Customizer page.

I've emailed you a copy of the theme the issue occurs on.

**Comment by dovy** [comment]
Update to the newest version of Redux found in this repo. This has been resolved.
