### ISSUE TITLE
Color Rgba Metabox

### ISSUE THREAD

**Issue by Bluxart** [reduxframework/redux-framework#2086]
Hi I tested the last version of Redux Framework. But the color_rgba don't save the value if use the Redux Metabox.

The color change but the alpha value remains the same.

```php
array(
    'id'            =>  $prefix .'title_header_mask_background',
    'type'          =>  'color_rgba',  
    'title'         =>  __( 'Color Mask', 'redux-framework-demo' ), 
    'subtitle'      =>  __( 'Optional. Select your custom hex color with opacity.', 'redux-framework-demo' ),
    'default'       =>  array( 'color' => '#000000', 'alpha' => '0.55' ),
    'validate'      =>  'colorrgba',
    'transparent'   =>  false,
    'required'  => array(
        array( $prefix . 'title_header_mask_mode', '!=', 'none' ),
        array( $prefix . 'title_header_mask_mode', '!=', 'mask_pattern' ),
    ),
),
```

```php
$mask_rgba_value = Redux_Helpers::hex2rgba(''.$title_header_mask_color['color'].'', ''.$title_header_mask_color['alpha'].'');
```

**Comment by kprovance** [comment]
#1975

**Comment by kprovance** [comment]
Or, why not just use `$title_header_mask_color['rgba'].`?

**Comment by kprovance** [comment]
I tried your code as indicated.  `Redux_Helpers::hex2rgba(''.$title_header_mask_color['color'].'', ''.$title_header_mask_color['alpha'].'')` returns `rgba(0,0,0,0.55)`.  That is to see, the result is as expected and I am unable to reproduce this issue.  Since no version information was included, either Redux or Metaboxes, please ensure you have the latest releases of both (as of this writing, Redux: 3.4.3.6 and Metaboxes: 1.3.0)

**Comment by Bluxart** [comment]
Hi, I written the last version of both, otherwise I use this version available.

Redux Framework: 3.4.3.6
Redux Metabox: 1.3.0

In my metabox I use the color_rgba field:
```php
array(
    'id'            => 'title_header_mask_background',
    'type'          =>  'color_rgba',  
    'title'         =>  __( 'Color Mask', 'redux-framework-demo' ), 
    'subtitle'      =>  __( 'Optional. Select your custom hex color with opacity.', 'redux-framework-demo' ),
    'default'       =>  array( 'color' => '#000000', 'alpha' => '0.55' ),
    'validate'      =>  'colorrgba',
    'transparent'   =>  false,
),
```
Now I need call the post_meta
```php
$options_az = redux_post_meta( 'alice' , $postid );
$title_header_mask_color = $options_az['title_header_mask_background'];
```
The output with the default value of metabox is:
```php
<?php echo $title_header_mask_color['color']; ?>  /* #000000 */
<?php echo $title_header_mask_color['alpha']; ?> /* 0.55 */
<?php echo $title_header_mask_color['rgba']; ?>  /* Error: Undefined index: rgba
```
If change the value with the color-picker ( color-4f55cd and alpha-0.21 ) and save the new output is:
```php
<?php echo $title_header_mask_color['color']; ?>  /* #4f55cd */
<?php echo $title_header_mask_color['alpha']; ?> /* 0.55 */
<?php echo $title_header_mask_color['rgba']; ?>  /* Error: Undefined index: rgba
```
The metabox don't save the new alpha channel, remains always the 0.55 default value.

**Comment by matyushen** [comment]
Is this still an issue? I'm getting the same "Undefined index: rbga" under Redux 3.4.4.8 and WP 4.2-beta3-31934. Maybe it's worpress beta who's messing here? Have to check. Redux_Helpers::hex2rgba woks as expected.

**Comment by kprovance** [comment]
I think I finally nailed with with the Redux 3.5.0 release.
