### ISSUE TITLE
How to remove menu added in Tools?

### ISSUE THREAD

**Issue by ahmadawais** [reduxframework/redux-framework#2089]
How to remove menu added in tools menu?
```
/wp-admin/tools.php?page=redux-about
```
I am using embeded redux in theme and version of redux is 3.4.3.5
There should be an action to remove this feature.

**Comment by dovy** [comment]
Really, you're upset about an unobtrusive link in the tools menu that's hardly used?

Well let me explain why. We have, from time to time, received issues from users of our developers asking for support. We assume they're developers only to find out later they're users who didn't know where to go for support. So we intend to route them to a page, within their panel, outlining the plugins and/or theme they have installed, inform them it's using Redux and to contact them directly.

I fail to see why this would be upsetting.

**Comment by ahmadawais** [comment]
It is forced use of our clientele, you should ask the developer to opt in to this program.
This is exactly why I didn't opt for Unyson Framework, they completely hijack the WordPress user and it seems like the user didn't buy our theme but their framework instead. 
I hope redux doesn't make the same mistake. I have manually disabled the feature. 

I think, you should not use this welcome page for embedded form of Redux. Or you should give developers the choice for opting in to showing your welcome page and allowing you to track their users through tracking file. It's just only the true spirit of Open Source. 

I do appreciate everything you guys are doing, and I know you want to build a business out of it, hell even, me myself am building a redux extension to be sold at your site. But things like these, enforcing something in without the consent of a developer is not going to be something anyone will appreciate. At-least I won't.

**Comment by kprovance** [comment]
I think entities like WooCommerce, or Visual Composer would disagree.  Theme authors should also - in my opinion, since we're giving them freely - a more reliable and easy way for their clients to contact them for support, instead of coming to us, and wasting our time.  And we don;t get paid anything, you get that, yeah?

**Comment by dovy** [comment]
Plus we won't be like woo. If we did do the welcome page redirect it would only be for major releases. But that redirect would be optional. Keeping an accessible menu though, that's not death is it?

**Comment by ahmadawais** [comment]
WooCommerce? I wonder if you even read what I suggested? I quote "I think, you should not use this welcome page for embedded form of Redux." 
And people build addons for WooCommerce, while we are not building themes for Redux, we are just using Redux in our themes. 
I never used visual composer, not a fan of bloat, so, can't comment on that.

I think if you redirect it or add the menu forcefully, it will be wrong, and I will be the one of many developers who'll shift towards something like Titan Framework.

**Comment by kprovance** [comment]
I see.  Do it your way or threaten us with an inferior product.   You are familiar with an old adage about flies, honey and vinegar?  You claimed to have 'disabled' it, so what;s the problem?

**Comment by dovy** [comment]
@ahmadawais I'm really sorry, but if you feel maybe you should move to Titan. I love Benjamin and he does good work over there. It's a light product with a limited feature set. Go for it.

Second, we're not trying to make a business, but rather have the community support us. We have learned the hard way that donations are not a sustainable model, so we're trying other things. We can't continue to further develop Redux when our users, such as yourself, are making tons of money. A one time purchase of an extension does not equal the time we put in for you.

Also, threatening that you're going to leave only makes us never ever want to help you again. If you're decision to stay with Redux is that volatile, then maybe it's time for you to go elsewhere. We love the community, but you do not own us. Even if you bought an extension we don't owe you anything really, as you get a lot more with Redux than you've ever paid for. We've made a great product that as of just recently surpassed all other frameworks by way of downloads on WordPress.org. We're growing like crazy, and we can't please everyone nor can we try.

That being said, you're a smart cookie. You removed the menu item. So who cares? Go forward and use our hard work and make money off us. Just don't forget we helped you to get where you are.  ;)
