### ISSUE TITLE
Typography color dosn't change ! 

### ISSUE THREAD

**Issue by PoshtibanHa** [reduxframework/redux-framework#2090]
Hi 
i have a problem with typography
i used it and when i change text color in admin panel, it dos not change and always shows default value 
thanks

**Comment by kprovance** [comment]
#1975, please

**Comment by PoshtibanHa** [comment]
i'm sorry,
1. Redux Version 3.4.3.3
2. Wordpress Version 4.1.1
3. Field: 

                        array(
                            'id'          => 'opt-typography',
                            'type'        => 'typography', 
                            'title'       => __('Typography', 'redux-framework-demo'),
                            'google'      => true, 
                            'font-backup' => true,
                            'color'       => true,
                            'text-align'  => true,
                            'output'      => array('.main_nav ul.main_menu>li>a'),
                            'units'       =>'px',
                            'subtitle'    => __('Typography option with each property can be called individually.', 'redux-framework-demo'),
                            'default'     => array(
                                // 'color'       => '#333', 
                                'font-style'  => '700', 
                                'text-align'  => 'left', 
                                'font-family' => 'Abel', 
                                'google'      => true,
                                'font-size'   => '33px', 
                                'line-height' => '40'
                            ),
                        )                    

5. I use it on a theme
6. I embedded redux in my theme
--  Redux is in this place on my project: htdocs/cornita/wp-content/themes/Cornita/includes/ReduxFramework
-- My config file is here: htdocs/cornita/wp-content/themes/Cornita/includes/ReduxFramework/cornita/panel-config.php
-- And the codes to initialize in functions.php file:
if ( !class_exists( 'ReduxFramework' ) && file_exists( dirname( __FILE__ ) . '/includes/ReduxFramework/ReduxCore/framework.php' ) ) {
    require_once( dirname( __FILE__ ) . '/includes/ReduxFramework/ReduxCore/framework.php' );
}
if ( !isset( $redux_demo ) && file_exists( dirname( __FILE__ ) . '/includes/ReduxFramework/cornita/panel-config.php' ) ) {
    require_once( dirname( __FILE__ ) . '/includes/ReduxFramework/cornita/panel-config.php' );
}

7. I have this error in my browser console but i don't know it pertaining to redux or not 

when i save settings this fields doesn't save:
Backup Font Family
Text Align
Font Color

Thank you

**Comment by kprovance** [comment]
I tried your code as given and am unable to reproduce.  Everything saves as expected.  I've seen fields not save because option panels were too large, or the PHP input variable in the php.ini was set too low.  Or there is some other configuration setting that is off.  However, I don't believe it's the typography code within Redux.

**Comment by PoshtibanHa** [comment]
thank you, 
is it possible to conflict with visual composer plugin? 
http://vc.wpbakery.com/

**Comment by kprovance** [comment]
Could be.  VC is a mess from which I stay far away.

**Comment by dovy** [comment]
Haha. We try to comply and work well with others. They auto add a Google that you can disable from their panel. That's most likely the issue.

**Comment by dovy** [comment]
Google font I meant. ;)

**Comment by PoshtibanHa** [comment]
Ok! Thanks guys 
Good luck
