### ISSUE TITLE
problems installing visual composer

### ISSUE THREAD

**Issue by moskinho** [reduxframework/redux-framework#2091]
I have problems installing visual composer. After several times trying to install this plugin essential to work with FOLIO FOX Theme and paying surprise after surprise fee I still getting this error: Destination folder already exists. /home/content/p3pnexwpnas03_data03/11/2432811/html/wp-content/plugins/js_composer/.

Anybody can help me with this?

**Comment by kprovance** [comment]
This is Redux Framework, not Visual Composer.  You have the wrong company, and the wrong issue tracker.  Please contact them directly.  Thanks.

**Comment by dovy** [comment]
Sorry, as @kprovance said, you'll need to contact your developer directly. Best of luck!
