### ISSUE TITLE
OFF TOPIC: Some clarifications

### ISSUE THREAD

**Issue by ahmadawais** [reduxframework/redux-framework#2092]
Answers to this issue https://github.com/reduxframework/redux-framework/issues/2089#issuecomment-76406137
@dovy & @kprovance 
This is not an issue, but since you commented and then blocked me out, I thought I should make some points clear. 

I am building a Redux extension, I am also half way through with Video tutorials which will in fact lower down the gap for an average WordPress developer to get onboard with Redux and start creating awesome set of options. 

Reason of mentioning this is to show my support for the work you people put in this framework. 

I don't know why you both are being so offensive, if you don't want to support it's fine. Just close up the issues panel and make an announcement. If you don't want feedback, tell everyone you don't want it. Since all I did was provided you guys with feedback. Instead you started talking about how much regretful you are for giving this framework for free and not earning through it like authors who build themes are earning. 

This is negative attitude, I won't appreciate it. You have built an awesome framework, why are you shooting yourself in the feet by telling everyone again and again about how you are not earning and everyone else is. 

Truth be told, if Redux wasn't open source not many theme authors would have opted for it, coz you know how theme/plugin authors are, or how human beings are, they generally don't pay for anything if they could get it done for free. E.g. if one could get free coffee a block away from a shop which charges mere $3 for a cup, he'll always go for the free option. 

I think, you guys are doing an amazing job, and you are not getting to earn by spending so much time building such a good framework. Now either you people could develop a new paid framework, or choose to add the Welcome page and sell plugins/themes of your own through it. 

Here is where I was suggesting you people not to do it. The feedback which made you both angry and lead to strange comments. I am going to quote myself again 
I said
"I think, you should not use this welcome page for embedded form of Redux."

I stand by my words! You should not add it in the embedded form of redux, or if you want to add it, give theme authors an option to disable it.

Addition of this app/extension store from Redux is inevitable for the existence of your business, I get that, add it through plugin. Anyone with Redux framework installed as a plugin will get this app store of yours. That is 201,346 people as of now. No theme author will ever think bad about it, as in it is your framework's plugin and you own it, you can modify it the way you desire to. But when Redux is being used in embedded form, you should either not include this welcome thingy or give authors a choice to disable it. Since, you don't own their themes/plugins, they have the write to every bit of it, being GPL, and you should respect that. If you will bruteforce this thing in for embedded form of redux, I think people will move away to other solutions available, E.g. Titan Framework or back to SMOF and stuff. Which concerns me? Why? Coz, I am building an extension based upon Redux, if people are going to move away, then I'll be wasting my time building it. So, is the case with the video series I have had been working on for two months now. 

I hope so you get the point now. I don't want to step over my line here. Neither do I want you both to get offended in any way. You people have done a pretty amazing job, and I am grateful for that. I have only used Redux in a single product as of now, which has only been sold for 17 times. So, yes! I am making a tons of money by using Redux, as per your assumption. Which offended me, and I had to clarify things. 

I think you people should take feedback like these serious, instead of being offensive. I can't think of a reason why simple feedback makes you feel threatened or upset you to smash it like that. 

Thankful to your efforts, as always. Even when you people stopped helping me. I come in peace and mean no harm whatsoever.

Take a look at Unyson framework and how powerful it is, and then research a little why it is not successful as of Redux. I hope the next redux version doesn't convert it to something like that, which makes a theme/plugin author feels like he is giving up control of his clientele.

**Comment by dovy** [comment]
Can we please take this off public forum. This is a personal discussion. Skype me: DovyDigital. Thank you.

**Comment by dovy** [comment]
This has been resolved and was a HUGE misunderstanding. We mis-read each other. Deleting!  :P
