### ISSUE TITLE
Error when using Typography with "required" option

### ISSUE THREAD

**Issue by sascha95** [reduxframework/redux-framework#2095]
Hi,

I get this error message when i click "Reset All":
Notice: Undefined index: data in ...\redux-core\framework.php on line 3735

The field type is typography and i'm using the "required" option ( 'required' => array( font-type', '=', '1' ) )
When I remove the line the error disappears.

**Comment by dovy** [comment]
Well, font-type isn't a valid key. Have you tried font-family? And maybe setting it to be a real value, not 1 which is not possible?

**Comment by sascha95** [comment]
Here is an examples of what I mean. There I get the error message.

array(
                            'id'       => 'switch-parent',
                            'type'     => 'switch',
                            'title'    => __( 'Switch - Nested Children, Enable to show', 'redux-framework-demo' ),
                            'subtitle' => __( 'Look, it\'s on! Also hidden child elements!', 'redux-framework-demo' ),
                            'default'  => 0,
                            'on'       => 'Enabled',
                            'off'      => 'Disabled',
                        ),

                        array(
                            'id'          => 'opt-typography',
                            'type'        => 'typography',
                            'required' => array( 'switch-parent', '=', '1' ),
                            'title'       => __( 'Typography', 'redux-framework-demo' ),
                            'google'      => true,
                            'font-backup' => true,
                            'all_styles'  => true,
                            'output'      => array( 'h2.site-description, .entry-title' ),
                            'compiler'    => array( 'h2.site-description-compiler' ),
                            'units'       => 'px',
                            'subtitle'    => __( 'Typography option with each property can be called individually.', 'redux-framework-demo' ),
                            'default'     => array(
                                'color'       => '#333',
                                'font-style'  => '700',
                                'font-family' => 'Abel',
                                'google'      => true,
                                'font-size'   => '33px',
                                'line-height' => '40px'
                            ),
                        ),

**Comment by sascha95** [comment]
Fixed the issue. Sorry I thought the error is in the framework.

**Comment by dovy** [comment]
Glad you solved it!  :)

If you like Redux, or the support we render, please do one or all of the following:
* Donate to keep us going: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=MMFMHWUPKHKPW
* Review us: http://wordpress.org/support/view/plugin-reviews/redux-framework
* Like us: http://facebook.com/ReduxFramework
* Follow us: http://twitter.com/ReduxFramework
