### ISSUE TITLE
Ajax save adds a backslash to apostrophe

### ISSUE THREAD

**Issue by britner** [reduxframework/redux-framework#2097]
Hey,
1. Redux Version 3.4.3.8
2. Wordpress Version 4.1.1
3. not in dev mode
4. effects all fields as best as I can tell.
5. using as embedded in a theme

First saw this while trying to save a standard font: Trebuchet MS. Once you save the apostrophes around the font name have backslashes added to them. (be sure to refresh the theme options page to see in the theme options and not only in the output)
This also happens in any text box. 

Only happens if ajax save is enabled.

Ben

**Comment by yerooleopard** [comment]
Hello,
same issue here, it break my tracking code in 'ace_editor' field, converting ' to \'. I tested it with 'textarea' field also, same result.

**Comment by dovy** [comment]
Please try the following: Inside functions.php, line 2651:
https://github.com/reduxframework/redux-framework/blob/master/ReduxCore/framework.php#L2651-L2653

Then follow this process:
* Comment out the if statement.
*Reset section to defaults
* Reload Page
*Try a new save

Let me know if it fixes the issue.   :)

**Comment by britner** [comment]
Yes, that works for me, is that a good long term fix?

Ben

**Comment by dovy** [comment]
Indeed. I thought it was only affecting my environment. I'll push a fix then. ;)

Resolved!  ;)
