### ISSUE TITLE
How To Validate Phone Numbers & Using Icons

### ISSUE THREAD

**Issue by renegademarketer** [reduxframework/redux-framework#2098]
I'm new to Redux as well as theme coding.  This is not a bug but per the instructions on the WP.org plugin page, I'm posting my issue here. 

I'm trying to validate a phone number field but the available options other than text won't work since people may use dashes and parentheses to enter their number. For such a common contact field, I assume there is a way to achieve this so I'm hoping someone can assist me.

Also, it seems that the available icons only display in the section header or info message field but not next to other field labels. I'm using the exact same code for the info field as other fields but no icon is showing.

However, I noticed on the Peadig theme demo (screenshot: http://goo.gl/FOclLK) the developer has icons next to each field label. Any advice on how to accomplish this?

**Comment by kprovance** [comment]
For the first question, use the `preg_replace`validation type.  You'll have to author your own regex code, naturally.

I cannot answer the second question because information required from #1975 (or the link at the top of the new issues page) was not given.

**Comment by thehung2224** [comment]
Hi @kprovance 

I've tried below code but the message doesn't appear, please check my issue:

```
array(
    'id'       => 'sz-header-contact-phone',
    'type'     => 'text',
    'title'    => __( 'Phone number', 'redux-framework-demo' ),
    'subtitle' => __( 'Enter your phone number here.', 'redux-framework-demo' ),
    'validate' => 'preg_replace',
    'preg' => array(
        'pattern' => '/[^a-zA-Z_ -]/s',
        'replacement' => 'no numbers'
    ),
    'msg'      => 'Please enter correct email address',
    'placeholder' => 'Enter your phone number here.'
),
```

**Comment by kprovance** [comment]
@thehung2224 - First, please do not piggy back other tickets.  Please open your own with the information from #1975.  Also, your code array doesn't make sense.  Your regex ALLOWS letters, not forbads them.  And your msg is wrong, since email addresses are not involved.
