### ISSUE TITLE
RGBA and Header border problems.

### ISSUE THREAD

**Issue by thehung2224** [reduxframework/redux-framework#2099]
First of all, thanks for awesome options framework.

I'm learning the usage of it. I have 2 problems hope everyone can help me out. Thanks in advance.

WP version: 4.1.1
Redux: 3.4.1
Integrated

1. I already set header border like this:

```php
array(
    'id'       => 'opt-header-border',
    'type'     => 'border',
    'title'    => __( 'Header Border Option', 'redux-framework-demo' ),
    'subtitle' => __( 'Only color validation can be done on this field type', 'redux-framework-demo' ),
    'output'   => array( '.site-header' ),
    // An array of CSS selectors to apply this font style to
    'desc'     => __( 'This is the description field, again good for additional info.', 'redux-framework-demo' ),
    'default'  => array(
        'border-width'  => '2px',
        'border-color'  => '#999999',
        'border-style'  => 'solid',
        'border-bottom' => '2px'
    )
),
```
On the homepage, my header still having 4 sides border. How do I fix it?

2 After integrated, the body background color automatically change to color that set in RGBA option. Now I want to change background color, I also have to change RGBA color to make it work because it overrides body background color option. How do I fix it?

Regards.

**Comment by dovy** [comment]
Are you sure you don't have CSS somewhere else? Or another field conflicting. Sorry, but I'm not sure how else to help but to say keep looking. You could look up the dynamic CSS and see if it's outputting improperly, but I doubt it.

**Comment by thehung2224** [comment]
Hi,

Thank you for replying. My background color was changed because of RGBA after integrated, would you mind to help me out with this case. I think it related to your plug-in.

**Comment by dovy** [comment]
Are you a user or a developer? Have you activated the sample config? (Go to the plugins page, find redux, and see if it says deactivate demo mode or not).

**Comment by thehung2224** [comment]
Hi

I'm newbie developer. I didn't active demo mode, I'm configuring myself.

**Comment by kprovance** [comment]
Also, you have `border-width` set, which is why all the sides of the border come out to 2px.  Setting that argument defaults ALL sides, and is only necessary to use when the `all` argument is set.   Also for the color issue, the border color picker doesn't support RGBA.  I'm not quite sure how you're able to set RGBA color with it.

**Comment by thehung2224** [comment]
Thank @kprovance 

It's totally solved first issue. For the color issue, I mean that background color affected by RGBA after integrated.
