### ISSUE TITLE
Accidental Fatal error: Class 'Redux_Helpers' not found

### ISSUE THREAD

**Issue by badjohnny** [reduxframework/redux-framework#2100]
One of my theme user told me an error when he login WP admin  "Fatal error: Class 'Redux_Helpers' not found", the theme is always working fine with this framework until now, he did nothing for the codes.

And, the theme framework is also working fine on the most websites, but only this user. So, Is it a server configuration problem?

I directly embed redux framework 3.3.6.8 to my theme.

Thanks

**Comment by dovy** [comment]
Chances are the users has a really old version of Redux running as a plugin. Have them install the same version of Redux you embedded as a plugin.
