### ISSUE TITLE
Adding \ into fields.

### ISSUE THREAD

**Issue by coleh33** [reduxframework/redux-framework#2101]
After updating to the latest release of Redux, I am having an issue that wasn't happening before.

In my text field I would have a \' to be able to use the ' character's and it was working fine but now it won't let me delete the \ and will add extra \\\ each time I try to delete one and hit save settings.

It's also happening in my javascript fields anywhere there is a ' it is adding a bunch of \\\\ in front of those characters.

Can someone point me in the right direction for fixing this issue?  It started with the latest update.

Thank You.

**Comment by coleh33** [comment]
Didn't see the latest release.  It fixed the issue.

**Comment by dovy** [comment]
Good, good.  :)

**Comment by dingo-d** [comment]
Hi! I updated redux to the latest release, but this issue still exists. my options get \'0'\, well the text output is.
