### ISSUE TITLE
Can't go to http://reduxframework.com/ 

### ISSUE THREAD

**Issue by kidesigner** [reduxframework/redux-framework#2102]
Can't go to http://reduxframework.com/ . Unable to connect. Someone like me?

**Comment by kprovance** [comment]
Mandatory maintenance on the server.  Check back soon!

**Comment by kidesigner** [comment]
How long till the completion of maintenance?

**Comment by dovy** [comment]
It was only supposed to be for 2 hours. Use Google and look at the cached pages.

**Comment by kidesigner** [comment]
Thank you, but i want to use Build.reduxframework.com

**Comment by dovy** [comment]
It's back up.  :)
