### ISSUE TITLE
Theme-Check issue warnings for File Methods

### ISSUE THREAD

**Issue by jaschaio** [reduxframework/redux-framework#2103]
I used the [theme-check plugin](https://wordpress.org/plugins/theme-check/) to check my wordpress theme for some errors or warnings and noticed that it says some warnings about the php filesystem calls

    WARNING: file_get_contents was found in the file mailchimp/MailChimp.php File operations should use the WP_Filesystem methods instead of direct PHP filesystem calls.
    Line 8: * Uses curl if available, falls back to file_get_contents and HTTP stream.

    WARNING: file_get_contents was found in the file admin/redux-framework/sample/sample-config.php File operations should use the WP_Filesystem methods instead of direct PHP filesystem calls.
    Line 1279: 'content'   => file_get_contents(dirname(__FILE__) . '/../README.md')
    Line 1499: 'content'   => nl2br(file_get_contents(trailingslashit(dirname(__FILE__)) . 'README.html'))

    WARNING: file_get_contents was found in the file admin/redux-framework/ReduxCore/inc/welcome.php File operations should use the WP_Filesystem methods instead of direct PHP filesystem calls.
    Line 438: $readme = file_get_contents ( $file );

    WARNING: file_get_contents was found in the file admin/redux-framework/ReduxCore/inc/class.redux_filesystem.php File operations should use the WP_Filesystem methods instead of direct PHP filesystem calls.
    Line 126: $res = file_get_contents( $file );

    Line 1019: 'content'   => file_get_contents(dirname(__FILE__) . '/../README.md')
    Line 1033: 'content'   => nl2br(file_get_contents(trailingslashit(dirname(__FILE__)) . 'README.html'))

    WARNING: curl_init was found in the file admin/redux-framework/ReduxCore/inc/p.php File operations should use the WP_Filesystem methods instead of direct PHP filesystem calls.
    Line 185: $ch = curl_init( $url );

    WARNING: curl_exec was found in the file admin/redux-framework/ReduxCore/inc/p.php File operations should use the WP_Filesystem methods instead of direct PHP filesystem calls.
    Line 211: list( $header, $contents ) = preg_split( '/([\r\n][\r\n])\\1/', curl_exec( $ch ), 2 );

And additionally some issues were marked as required:

    REQUIRED: admin/redux-framework/ReduxCore/inc/import_export.php. Themes should use add_theme_page() for adding admin pages.
    Line 147: add_submenu_page(
 
    REQUIRED: admin/redux-framework/ReduxCore/inc/debug.php. Themes should use add_theme_page() for adding admin pages.
    Line 74: add_submenu_page(

    REQUIRED: admin/redux-framework/ReduxCore/framework.php. Themes should use add_theme_page() for adding admin pages.
    Line 1136: // wrappers and need to be appened to using add_submenu_page.
    Line 1172: $this->page = add_submenu_page(
    Line 1229: add_submenu_page(
    Line 1253: add_submenu_page(

Just wanted to be sure that you are aware of this, not sure if there is something we can do about it.

**Comment by dovy** [comment]
There's a doc all about this on our docs site, but out host is down right now. ;)

**Comment by kprovance** [comment]
http://docs.reduxframework.com/core/theme-check/
