### ISSUE TITLE
validate_callback not run with empty values

### ISSUE THREAD

**Issue by rnlmedia** [reduxframework/redux-framework#2104]
Maybe related - https://github.com/ReduxFramework/redux-framework/issues/678

I'm noticing an issue with redux's validate_callback feature. It doesn't appear to be running when the value is empty.

Redux Framework Version 3.4.3.9.

```php
array(
  'id'        => 'test-string',
  'type'      => 'text',
  'title'     => __('Key', 'my-text-domain'),
  'subtitle'  => __('password key', 'my-text-domain'),
  'validate_callback' => 'my_key_callback',
),
```

```php
function my_key_callback($field, $value, $existing_value) {
        $error = false;
       //increment to test
        update_option('validation_run', 'test1');
        $return['value'] = $value;
        if ($error == true) {
            $return['error'] = $field;
        }
        return $return;
    }
```

The my_key_callback function is only being run when the test-string field is not an empty string, evidenced by the fact that it doesn't update the validation_run option when it's empty, yet works fine when it's not, or even a single space. Yet the value still changes in the options array.

Is this expected behaviour - surely not, else how would empty string validation occur?

**Comment by dovy** [comment]
I suggest you make a validation class instead of a callback. It's just how the core runs and it would be difficult to bypass. An example can be found here: https://github.com/reduxframework/redux-framework/blob/master/ReduxCore/inc/validation/not_empty/validation_not_empty.php

Just change the class name to be unique to you, include it before you setup Redux, and use the validate argument vs the validate_callback argument. This should help you resolve your issue.

**Comment by thehung2224** [comment]
@dovy I have the same problem. Could you show me how to do this "Just change the class name to be unique to you, include it before you setup Redux, and use the validate argument vs the validate_callback argument.". Thank you so much.

**Comment by kprovance** [comment]
Find all instances of `Redux_Framework_sample_config` and change it to something else.

**Comment by thehung2224** [comment]
With the custom callback function, we can pass the class name and method as following:

`'validate_callback' => array( $this, 'validate_callback_function' )`

But I found `validate_callback_function` has `$existing_value` but I don't know how it works?
