### ISSUE TITLE
Textarea/Ace Editor - Single Quotes

### ISSUE THREAD

**Issue by Bluxart** [reduxframework/redux-framework#2105]
Hello, I have a question/curiosity to solve.

Redux Framework Version: v3.4.3.8

Code of Textarea and Ace Editor:
```php
// Textarea
array(
  'id'        =>  'js_textarea_code',
  'type'      =>  'textarea',
  'title'     =>  __('js Code', 'redux-framework-demo'), 
  'subtitle'  =>  __('Simple Js Code', 'redux-framework-demo'),
  'desc'      =>  ''
),

// Ace Editor
array(
  'id'        =>  'js_ace_code',
  'type'      =>  'ace_editor',
  'mode'      =>  'javascript',
  'theme'     =>  'chrome',
  'title'     =>  __('js Code', 'redux-framework-demo'), 
  'subtitle'  =>  __('Simple Js Code', 'redux-framework-demo'),
  'desc'      =>  ''
),
```

If I insert a simple alert inside the textareas like this:
```php
alert('ok');
```

I have this output:
```php
<?php echo $options['js_textarea_code']; ?>
<?php echo $options['js_ace_code']; ?>
// Result: alert(\'ok\');
```

Instead if I use this syntax into the textareas:
```php
alert("ok");
```

I have the correct output and the js alert work:
```php
<?php echo $options['js_textarea_code']; ?>
<?php echo $options['js_ace_code']; ?>
// Result: alert("ok");
```

The question is simple because if I use the single quote instead the double-quotes the textarea and the ace_editor change the output syntax?

When I used the old version of redux framework (3.3.8.1) I did not have this problem, but with the last version I have the problem with the single quote.

**Comment by kprovance** [comment]
v3.4.3.9 is the latest repo build, please update to that version.

**Comment by donkoink** [comment]
I am using the latest version (v3.4.4.4) and have another issue related to single quotes:

If in a Textarea or AceEditor field, I type:

alert('ok');

and I press Save, it saves successfully. However, as soon as I reload/refresh the same page in the browser, the textarea shows:

alert(\'ok\');

and if I save again without modifying anuthing, and refresh the page again, it shows:

alert(\\'ok\\');

another save, refresh, 2 more slashes are added. That's the pattern.

Am I missing something or is this a bug?
