### ISSUE TITLE
Add Tabbs 

### ISSUE THREAD

**Issue by abeel** [reduxframework/redux-framework#2106]
Hi,
first thanks for this great freamwork.it is possible to add tabs fields ?

|---------|---------|
| Tab1  | Tab2  |
|---------|---------|
|           |           |
|           |           |
|           |           |
|           |           |

**Comment by kprovance** [comment]
At this time, no.  Sorry.  :)

**Comment by dovy** [comment]
You could easily build it into the section field. We were thinking about doing tabs for sections at one time. The code is in the templates, but just commented out.

Contribute! That's what open source is about.  ;)
