### ISSUE TITLE
How to pass partial sass files to scssphp compiler on save?

### ISSUE THREAD

**Issue by limestreet** [reduxframework/redux-framework#2107]
Is there any way (using Redux functionality) to @import sass files, merge them with variables (taken from option fields) and compile as a css file?

Thanks in advance

**Comment by kprovance** [comment]
You'll need to include the following file:  `ReduxCore/inc/scssphp/scss.inc.php`

Instructions on using the SCSS compiler may be found here:  http://leafo.net/scssphp/
