### ISSUE TITLE
please can you update this version to wordpress repository

### ISSUE THREAD

**Issue by smpdesignmedia** [reduxframework/redux-framework#2109]
- can you upload this to wordpress repository, it too long time, you have not uploaded it in wordpress.

**Comment by dovy** [comment]
We want to make sure Ajax is working perfectly before we do. We don't feel like breaking things for thousands of users.  ;)

**Comment by dovy** [comment]
If you want it out faster, please help us verify Ajax saving is perfect.

**Comment by smpdesignmedia** [comment]
i will try to help you,
