### ISSUE TITLE
Call to undefined method Redux_Helpers::isTheme()

### ISSUE THREAD

**Issue by pe6o** [reduxframework/redux-framework#2110]
I never get this error but some of my clients are complaining that a blank page appears after theme installation. I enabled WP_DEBUG and found the following error:
```
Call to undefined method Redux_Helpers::isTheme()* in includes/theme-options/theme-options.php (this is the sample-config.php file but with custom options)
```
Redux is installed as a plugin using TGM Activation. There is no notification for a new version.
The version at the bottom of the admin panel is v3.4.1

In the functions.php I have:

require_once( THEME_INCLUDES . '/admin/admin-init.php' );

I see that in `class.redux_helpers.php` there is indeed `public static function isTheme( $file ) {}`

The `admin-init.php` contains:

```php
<?php

// Load the TGM init if it exists
if (file_exists(dirname(__FILE__).'/tgm/tgm-init.php')) {
    require_once( dirname(__FILE__).'/tgm/tgm-init.php' );
}
// Load Redux extensions - MUST be loaded before your options are set
if (file_exists(dirname(__FILE__).'/redux-extensions/extensions-init.php')) {
    require_once( dirname(__FILE__).'/redux-extensions/extensions-init.php' );
}
// Load the embedded Redux Framework
if (file_exists(dirname(__FILE__).'/redux-framework/ReduxCore/framework.php')) {
    require_once( dirname(__FILE__).'/redux-framework/ReduxCore/framework.php' );
}
// Load the theme/plugin options
if (file_exists(dirname(__FILE__).'/options-init.php')) {
    require_once( dirname(__FILE__).'/options-init.php' );
}
```

Why is that error?

**Comment by kprovance** [comment]
It's in your config someplace.  You said you're using Redux as a plugin, but your code is force loading an embedded version (which you shouldn't be doing, you should check for the class first.  WHy?  If someone else is using Redux as a plugin AND your project, they will be forced to use your embedded version which cannot be updated like a plugin).  Also, you are getting the error in `theme-options.php`, but I see no loading of that file in the code above??  So, again, it's in your config someplace.

**Comment by pe6o** [comment]
I changedthe code to use it as a plugin.

In my functions.php:
```php
require_once( THEME_INCLUDES . '/admin/admin-init.php' );
```

in admin/admin-init.php
```php
<?php

// Load the TGM init if it exists
if (file_exists(dirname(__FILE__).'/tgm/tgm-init.php')) {
    require_once( dirname(__FILE__).'/tgm/tgm-init.php' );
}
// Load the theme/plugin options
if (file_exists(dirname(__FILE__).'/options-init.php')) {
    require_once( dirname(__FILE__).'/options-init.php' );
}
```
*(My options are in options-init.php)*

And the tgm-init.php is:
```php
<?php

/**
 * TGM Init Class
 */
include_once ('class-tgm-plugin-activation.php');

function starter_plugin_register_required_plugins() {

	$plugins = array(
		array(
			'name' 		=> 'Redux Framework',
			'slug' 		=> 'redux-framework',
			'required' 	=> true,
		),
	);

	$config = array(
		'domain'       		=> 'redux-framework',         	// Text domain - likely want to be the same as your theme.
		'default_path' 		=> '',                         	// Default absolute path to pre-packaged plugins
		'parent_menu_slug' 	=> 'plugins.php', 				// Default parent menu slug
		'parent_url_slug' 	=> 'plugins.php', 				// Default parent URL slug
		'menu'         		=> 'install-required-plugins', 	// Menu slug
		'has_notices'      	=> true,                       	// Show admin notices or not
		'is_automatic'    	=> true,					   	// Automatically activate plugins after installation or not
	);

	tgmpa( $plugins, $config );

}
add_action( 'tgmpa_register', 'starter_plugin_register_required_plugins' );
```

And on activation it still gives:
**Call to undefined method Redux_Helpers::isTheme() in /home/notabe01/2loud.org/www/wp-content/plugins/redux-framework/sample/sample-config.php on line 23**
