### ISSUE TITLE
Redux Warning: filemtime()

### ISSUE THREAD

**Issue by hamdan-mahran** [reduxframework/redux-framework#2111]
Hello Mr Dovy,
I using your awesome framework, but i have little issue, i got this warning message : 

<pre>Warning: filemtime(): stat failed for /home2/creative/public_html/mysitename/wordpress/wp-content/themes/Arwen/theme-admin/options/ReduxFramework/ReduxCore/assets/css/vendor/elusive-icons/elusive-webfont.css in /home2/creative/public_html/mysitename/wordpress/wp-content/themes/Arwen/theme-admin/options/ReduxFramework/ReduxCore/framework.php on line 1683

Warning: filemtime(): stat failed for /home2/creative/public_html/mysitename/wordpress/wp-content/themes/Arwen/theme-admin/options/ReduxFramework/ReduxCore/assets/css/vendor/elusive-icons/elusive-webfont-ie7.css in /home2/creative/public_html/mysitename/wordpress/wp-content/themes/Arwen/theme-admin/options/ReduxFramework/ReduxCore/framework.php on line 1691

Warning: filemtime(): stat failed for /home2/creative/public_html/mysitename/wordpress/wp-content/themes/Arwen/theme-admin/options/ReduxFramework/ReduxCore/assets/css/vendor/jquery-ui-bootstrap/jquery-ui-1.10.0.custom.css in /home2/creative/public_html/mysitename/wordpress/wp-content/themes/Arwen/theme-admin/options/ReduxFramework/ReduxCore/framework.php on line 1715

Warning: filemtime(): stat failed for /home2/creative/public_html/mysitename/wordpress/wp-content/themes/Arwen/theme-admin/options/ReduxFramework/ReduxCore/inc/fields/slider/vendor/nouislider/redux.jquery.nouislider.css in /home2/creative/public_html/mysitename/wordpress/wp-content/themes/Arwen/theme-admin/options/ReduxFramework/ReduxCore/inc/fields/slider/field_slider.php on line 224
</pre>

My Wordpress Version is : 4.1.1 
Redux Version is : 3.3.9

Thanks!

**Comment by kprovance** [comment]
Your version of Redux is outdated.  Please update to the latest version.  Thanks.

**Comment by hamdan-mahran** [comment]
I update to the last version, i see the issue is fixed, and the warning message is gone 
Thanks very much @kprovance

**Comment by dovy** [comment]
If you like Redux, or the support we render, please do one or all of the following:
* Donate to keep us going: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=MMFMHWUPKHKPW
* Review us: http://wordpress.org/support/view/plugin-reviews/redux-framework
* Like us: http://facebook.com/ReduxFramework
* Follow us: http://twitter.com/ReduxFramework
