### ISSUE TITLE
Field dependency on other fields' values

### ISSUE THREAD

**Issue by dmitrijs** [reduxframework/redux-framework#2112]
Is it possible to use one field's values as options for another field?

Foe example, I have Multi Text field named "opt-letters" with values: "A", "B", "C".
And I want to have a Multi Select field named "opt-letters-banned", where I want to choose between values of field "opt-letters".

I see that 'options' field only accept a static array. And $redux_demo global is not available while setting up the fields' definition.

Is it possible to do this without defining custom fields?

**Comment by kprovance** [comment]
Unless Dovy knows of some undoc'ed code that I'm not aware of, linked lists are not supported.  That is, one field reacting to the selection of another.  The only way I imagine it's possible is via jQuery, using an overloaded field (http://docs.reduxframework.com/core/advanced/add-a-custom-field/) and adding the javascript necessary to support linked lists.  It's fairly advanced, so a more than intermediate knowledge of javascript and jQuery would be necessary.
