### ISSUE TITLE
Customizer Issue: Fatal Error when save_defaults set to false.

### ISSUE THREAD

**Issue by towfiqi** [reduxframework/redux-framework#2113]
@dovy When You set save_defaults to false and the options are not saved in db yet, You click on Appearance> Customizer and You get this:

Fatal error: Maximum function nesting level of '100' reached, aborting! in C:\xampp2\htdocs\wordpress\wp-includes\option.php on line 25

    Call Stack:
    0.0010     193784   1. {main}() C:\xampp2\htdocs\twentyten\wp-admin\customize.php:0
    0.0020     236544   2. require_once('C:\xampp2\htdocs\twentyten\wp-admin\admin.php') C:\xampp2\htdocs\twentyten\wp-admin\customize.php:13
    0.0030     248000   3. require_once('C:\xampp2\htdocs\twentyten\wp-load.php') C:\xampp2\htdocs\twentyten\wp-admin\admin.php:31
    0.0030     255024   4. require_once('C:\xampp2\htdocs\twentyten\wp-config.php') C:\xampp2\htdocs\twentyten\wp-load.php:29
    0.0040     316688   5. require_once('C:\xampp2\htdocs\twentyten\wp-settings.php') C:\xampp2\htdocs\twentyten\wp-config.php:80
    0.1490   11526656   6. include('C:\xampp2\htdocs\twentyten\wp-content\themes\twentyten\functions.php') C:\xampp2\htdocs\twentyten\wp-settings.php:329
    0.1720   12787688   7. require_once('C:\xampp2\htdocs\twentyten\wp-content\themes\twentyten\theme-options.php') 
    
    

    C:\xampp2\htdocs\twentyten\wp-content\themes\twentyten\functions.php:43
    0.1720   12788112   8. twentyten_theme_options-&gt;__construct() C:\xampp2\htdocs\twentyten\wp-content\themes\twentyten\theme-options.php:2376
    0.1720   12788248   9. twentyten_theme_options-&gt;initSettings() C:\xampp2\htdocs\twentyten\wp-content\themes\twentyten\theme-options.php:30
    0.2010   13336424  10. ReduxFramework-&gt;__construct() C:\xampp2\htdocs\twentyten\wp-content\themes\twentyten\theme-options.php:70
    0.2060   13423480  11. ReduxFramework-&gt;get_options() C:\xampp2\htdocs\twentyten\wp-content\themes\twentyten\lib\redux\framework.php:320
    0.2060   13423680  12. apply_filters() C:\xampp2\htdocs\twentyten\wp-content\themes\twentyten\lib\redux\framework.php:850
    0.2060   13424472  13. call_user_func_array() C:\xampp2\htdocs\twentyten\wp-includes\plugin.php:213
    0.2060   13424640  14. ReduxFramework_extension_customizer-&gt;_override_values() C:\xampp2\htdocs\twentyten\wp-includes\plugin.php:213
    0.2060   13424640  15. ReduxFramework-&gt;get_options() 
    
    
    C:\xampp2\htdocs\twentyten\wp-content\themes\twentyten\lib\redux\extensions\customizer\extension_customizer.php:130
    0.2060   13424824  16. apply_filters() C:\xampp2\htdocs\twentyten\wp-content\themes\twentyten\lib\redux\framework.php:850
    0.2060   13425504  17. call_user_func_array() C:\xampp2\htdocs\twentyten\wp-includes\plugin.php:213
    0.2060   13425520  18. ReduxFramework_extension_customizer-&gt;_override_values() C:\xampp2\htdocs\twentyten\wp-includes\plugin.php:213
    0.2060   13425520  19. ReduxFramework-&gt;get_options() 

Looks like the error source is `_override_values` function inside the extension_customizer.php file in line 130, my guess is the customizer is trying to load the default settings when there are none, because the options are not saved in db yet. Any solution?

Redux version: 3.3.9.29
WordPress version: 4.1.1
Redux is embedded in theme.
No js error

**Comment by kprovance** [comment]
Have you tried updating to the latest version of Redux yet?  That should ALWAYS be the first thing to do before filing an issue, as per our guidelines.

**Comment by towfiqi** [comment]
I havent, but I updated the customizer extension to latest version.
I will update redux now and see if the error is still there and report here.

Thanks

**Comment by towfiqi** [comment]
Yep! Just tried with v3.4.3.9 same issue.

**Comment by kprovance** [comment]
Dovy'll have to handle it when he gets back next week.  The Customizer isn't my specialty.

**Comment by dovy** [comment]
Please update to the newest version and tell me if the problem persists.

**Comment by dovy** [comment]
Fixed! Give it a try.
