### ISSUE TITLE
Google fonts won't load in admin pulldown typography section

### ISSUE THREAD

**Issue by TheRegge** [reduxframework/redux-framework#2114]
Redux Framework version: __3.4.3.5__
Wordpress Version: __4.1.1__
dev_mode: __false__
Standalone theme with __embedded__ Redux Framework
No js errors, no php errors (well, I get a js error if I choose 'none' in the pulldown menu `Uncaught TypeError: Cannot read property 'length' of undefined` in (view screen grab because it does not let me copy this part:) 
![screen_shot_2015-03-09_at_11_26_05_am](https://cloud.githubusercontent.com/assets/494409/6557950/6224a802-c64f-11e4-82e9-a7f957c27dc3.png)

This is what the problem looks like, if my description is unclear: no google fonts!
![screen shot 2015-03-09 at 10 54 35 am](https://cloud.githubusercontent.com/assets/494409/6557731/a6da4288-c64d-11e4-8355-dd4ce8358ba5.png)

I am developing on a virtualbox ubuntu server set up to be very similar to my prod server. On my dev, the typography module loads google fonts without any issues. The same exact same setup does not load google fonts in the admin pulldown menu.
* I am using a google api key with dns set to 'any'. Using the same key both on dev and prod servers. I also tried to use two different keys for dev and prod, same results.
* All the files in my theme belong to the web user, so they are all readable and writable.
* I have checked if I had any strange .htaccess that would block something, commented out anything that was not pure WordPress .htaccess... no effect.
* I could not find documentation on the 'async_typography' config.. I am not sure what it does. I turned in on and off, no noticeable effects.
I am pasting below the config section where I define the typography modules (I use it 2 times, one for body text, one for headers)

    ````php
     public function setSections() {
                // ACTUAL DECLARATION OF SECTIONS
                $this->sections[] = array(
                    'title'  => __( 'Typography', 'redux-framework-demo' ),
                    'desc'   => __( 'Typography Options for the blog.', 'redux-framework-demo' ),
                    'icon'   => 'el-icon-font',
                    // 'submenu' => false, // Setting submenu to false on a given section will hide it from the WordPress sidebar menu!
                    'fields' => array(
                        array(
                            'id'          => 'opt-typography-body',
                            'type'        => 'typography',
                            'title'       => __( 'Body font', 'redux-framework-demo' ),
                            'google'      => true,
                            // Disable google fonts. Won't work if you haven't defined your google api key
                            'font-backup' => TRUE,
                            'font-style'  => TRUE, // Includes font-style and weight. Can use font-style or font-weight to declare
                            'font-size'   => FALSE,
                            'text-align'  => FALSE,
                            'line-height' => FALSE,
                            'color'       => TRUE,
                            'all_styles'  => TRUE,
                            'output'      => array( '.main p' ),
                            'units'       => 'px',
                            'subtitle'    => __( 'Font style for the body text', 'redux-framework-demo' ),
                            'default'     => array(
                                'color'       => '#333',
                                'font-family' => 'Open Sans',
                                'google'      => true
                            ),
                        ),
                        array(
                            'id'          => 'opt-typography-headers',
                            'type'        => 'typography',
                            'title'       => __( 'Headers font', 'redux-framework-demo' ),
                            'google'      => true,
                            // Disable google fonts. Won't work if you haven't defined your google api key
                            'font-backup' => TRUE,
                            'font-style'  => TRUE, // Includes font-style and weight. Can use font-style or font-weight to declare
                            'font-size'   => TRUE,
                            'text-align'  => FALSE,
                            'line-height' => TRUE,
                            'color'       => TRUE,
                            'all_styles'  => TRUE,
                            'output'      => array( 'h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'h1 a', 'h2 a','h3 a','h4 a','h5 a','h6 a'),
                            'units'       => 'em',
                            'subtitle'    => __( 'Font style for the text headers', 'redux-framework-demo' ),
                            'default'     => array(
                                'color'       => '#333',
                                'font-weight' => '600',
                                'font-family' => 'Open Sans',
                                'google'      => true,
                                'font-size'   => '1.1em',
                                'line-height' => '1.2em'
                            ),
                        ),
            array(
                            'id'      => 'opt-typography-links',
                            'type'    => 'link_color',
                            'title'   => __( 'Links', 'redux-framework-demo' ),
                            'output'  => array( 'a'),
                            //'visited' => TRUE,
                            'subtitle'    => __( 'Links color', 'redux-framework-demo' ),
                            'default'     => array(
                                'regular' => '#428bca',
                                'hover'   => '#3282c9',
                                'active'  => '#3282c9',
                            ),
                        ),
                    )
                );
            }
````
Can anyone help? Thanks!

**Comment by kprovance** [comment]
I am unable to reproduce.  However, you are not uisng the latest version of Redux from this repo.  We ask you apply the latest version first, before filing an issue, as there is no point in debugging older versions.

**Comment by dovy** [comment]
It's a permissions issue. Make sure your /uploads folder is writeable to the owner of the user that owns the redux framework files.

**Comment by TheRegge** [comment]
@dovy: thanks. Checked permission, they are all good.
@kprovance: thanks, I updated to 3.4.3.9 and no resolution.
any thoughts?

**Comment by dovy** [comment]
@TheRegge I promise the issue is permissions. If you don't see a redux folder under your uploads folder, it's because WordPress can't make it. And this, Google fonts fail.  ;)

**Comment by TheRegge** [comment]
@dovy: ok, thanks... I'll check again.

**Comment by TheRegge** [comment]
@dovy: unfortunately, I checked the permissions again. I even chmod uploads to 777, no change. I even added a redux folder inside my upload folder, with fully open permissions (777), still no change. Something is failing before that... but thank you anyway.

**Comment by dovy** [comment]
Chown it maybe? Or maybe you're running Redux too late?

**Comment by TheRegge** [comment]
it is all under www-data ownership. Also, the same setup runs on my dev server (ubuntu on a virtualbox). I have a simple ReduxFramework in the root of my theme folder, another folder with my theme's Redux config... I link to the Redux Framework in the functions.php... all pretty standard. And it works well on my dev server. :(

**Comment by TheRegge** [comment]
I see that someone closed this issue, even though it was not resolved... interesting. Anyhow, if anyone is interested, I found my problem. Redux Framework is broken by the plugin "JW Player".

**Comment by dovy** [comment]
What version of he player?

It was closed because this was a common issue, or so it seemed. It appears I was wrong.

**Comment by TheRegge** [comment]
@dovy - no worries - sorry if I sounded short! I am using JWPlayer v6.11 on WordPress v4.1.1

**Comment by dovy** [comment]
I can't find a plugin with that version. URL?

**Comment by kprovance** [comment]
@TheRegge - we really need a URL to the plugin in question, or we'll have to close this issue unresolved.  Please reply ASAP.

**Comment by TheRegge** [comment]
@dovy @kprovance Sorry guys I was confused about the versions... The WordPress plugin is
**JW Player 6 Plugin for Wordpress**
**Version 2.1.10**
This plugin uses the **version 6.11** of the JWPlayer, a web video product that is not limited to WordPress ([jwplayer.com](http://www.jwplayer.com/)).

But **I found out what breaks Redux typography module in the JW Player 6 WordPress plugins:**
In the plugin file `jwp6/jwp6-class.media.php` the plugin loads the `jquery.select2` javascript library and its related css. When I prevent the plugin from loading those libraries, the Redux typography modules **loads google fonts correctly**.  Preventing to load this library does not seem to break anything in the JWPlayer plugin... 
So, as far as I am concerned, the issue can be closed. I am very grateful for your guys' help. The ball is in JWPlayer's developers side. I did not find a ticket/issue system on their site, so I sent them a Twitter message with as much info as I could. They seemed to be responsive.
Cheers!

**Comment by dovy** [comment]
Awesome. Thanks!

**Comment by DigitalMediaPro** [comment]
Really interesting because i'm having same issue of Google Fonts not loading & i fixed all the "permissions issue" & still can't load them. I don't have the JW player & using another theme (Mobius) Any help?

**Comment by dovy** [comment]
Don't piggyback tickets that are resolved. You have a different experience. Open your own ticket and provide the requested information.
