### ISSUE TITLE
Using Sass file with Netbeans 8.0.2 on Mac

### ISSUE THREAD

**Issue by ewtstudio** [reduxframework/redux-framework#2115]
Dear All,
firstly thank you very much for the great Redux Framework. I created a theme using BuildReduxFramework. I want to use the Sass files. I'm using the Netbeans IDE 8.0.2 on my mac.  Also, I installed the Sass on my computer.
It's working on a different project. but it does not working on my wordpress project.

How can solve this issue?
I will be grateful for any help you can provide. 
Thank you very much for your help.

**Comment by dovy** [comment]
We use grunt to do that. grunt compileCSS. So instead load grunt via Netbeans and you'll be good to go. :)

**Comment by ewtstudio** [comment]
Thank you very much for the quick response :) Great.. 
I will try it and I'll let you know the result.

**Comment by ewtstudio** [comment]
I'm so sorry Dovy,
Could you provide more information or link or tutorials of the grunt compileCSS? How do I install it?
Thank you very much for your help & Kind Regards...

**Comment by dovy** [comment]
Sorry, that's beyond our scope. There's a grunt integration for netbeans. Or just look how to install grunt normally using NPM.

Hint, when you have it working you can just run `grunt watch` and it will auto-compile for you with each scss change.  ;)

**Comment by ewtstudio** [comment]
Hi Dovy,
I want to ask your something. I'm using Coda2 for the Less files. What can I use for  Sass files instead of Netbeans IDE?
I need to install necessarily grunt?

And finally. How do I get support from you about this? Do I need to pay for it?

Thank you very much for your interest & Kind Regards,

**Comment by kprovance** [comment]
We don't really support development environments.  This type of question would be better asked on the Netbeans community forums.  it really has nothing to do with Redux.

**Comment by ewtstudio** [comment]
I understand. Ok. Sorry. Thank you very much for your interest.

**Comment by dovy** [comment]
We can help you get setup, but it goes far beyond the scope of our project and you'd be paying us for information about another project. Thus, the reason I suggested you look elsewhere.

Getting grunt setup is trivial, but I don't think you should have to pay us to set it up. There are endless tutorials out there.

That being said, we'll gladly accept payment if you want to support the project.  :P

**Comment by dovy** [comment]
1. Install node: https://docs.npmjs.com/getting-started/installing-node
2. Install grunt: http://gruntjs.com/getting-started
3. From the Redux directory (ReduxCore) run:
npm install

Then just grunt. DONE.

**Comment by ewtstudio** [comment]
Thank you very much Dovy,
I understand. 
Finally, Can I ask you one more thing, please?
I'm building a theme with Redux and Underscores. 
If I make any changes inside the theme-name/style.css file, does that then causes a problem?

Therefore, I want to make changes to the files in the Sass folder.
Is this a proper approach?

Finally, yes. I will try to support your project ;)

Thank you very much
Yours sincerely,

**Comment by kprovance** [comment]
It's one or the other, really. You can make changes to the CSS file, and they will apply.  If you don;t make the same changes to the SASS files, it will overwrite the CSS on compile.  The idea is to make changes to the SCSS files, then compile, negating the need to edit the CSS.

**Comment by ewtstudio** [comment]
Thank you very much Kevin, your comment was very helpful.
Kind Regards,

**Comment by dovy** [comment]
If you like Redux, or the support we render, please do one or all of the following:
* Donate to keep us going: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=MMFMHWUPKHKPW
* Review us: http://wordpress.org/support/view/plugin-reviews/redux-framework
* Like us: http://facebook.com/ReduxFramework
* Follow us: http://twitter.com/ReduxFramework
