### ISSUE TITLE
Only allow one user at a time to edit the Redux Panel

### ISSUE THREAD

**Issue by paulthecoder** [reduxframework/redux-framework#2116]
I've had issues with the redux panel when it comes to multiple users editing the options. 

Let's say <b>user A</b> has the option panel loaded up with the a color set to black. And then <b>user B</b> logs on and changes the color to orange. All is well until <b>user A</b> with the color still being black in his instance presses save (perhaps changing a different option without knowing <b>user B</b> changed the color). Resulting in <b>user B</b> confused on why the color changed back to black.

I think they're should be the exact same functionality as WordPress does with it's posts. Lock the theme options to one user at a time to avoid confusion.

**Comment by kprovance** [comment]
Tagging it at #348  Good idea, but it looks like a goodly amount of work to implement.  If you like, you're always free to implement it and submit a pull request.  :)
