### ISSUE TITLE
Filed Typography Error (js)

### ISSUE THREAD

**Issue by ManiakMill** [reduxframework/redux-framework#2118]
https://github.com/reduxframework/redux-framework/blob/master/ReduxCore/inc/fields/typography/field_typography.min.js

TypeError: r.replace is not a function
..."+");if(h===!0){var A=z;""!==r&&(A+=":"+r.replace(/\-/g," ")),""!==s&&(A+="&subs...

Hi Guys, i found this error message on change "Font Weight & Style" options.

**Comment by dovy** [comment]
Version? Browser?

**Comment by kprovance** [comment]
Also, we are not able to debug minified javascript files.  Please enable dev_mode and re-report the issue with un-minifed code, along with Dovy's request.  Thanks!

**Comment by ManiakMill** [comment]
Uncaught TypeError: undefined is not a function - line 522.
ver. 3.4.4
Browser Chrome ver. 40.0.2214.115 

 if ( style !== "" ) {
 link += ':' + style.replace( /\-/g, " " );
}

**Comment by kprovance** [comment]
Pushed an update  v.3.4.4.1.  Turns out some experimental code was accidentally added to the master.  Sorry about this.  Fixed.  :)
