### ISSUE TITLE
Slides field returning undefined index

### ISSUE THREAD

**Issue by PulsarMedia** [reduxframework/redux-framework#2119]
Hi,

For some reason i am getting an undefined index notice on my slides field.

Here is the code i am using to call the field:

global $energy_options;
$slides = $energy_options['opt-pulse-slider-slides'];

It seems the $slides variable isn't returning any data when there are no slides inserted resulting in the undefined index notice.

Here is my current configuration:

WordPress 4.1.1
Redux Framework v3.4.3.9
dev_mode is off

Here is the code for my slides field:

<pre>
$fields = array(
					'id'          => 'opt-pulse-slider-slides',
					'type'        => 'slides',
					'title'       => __('Slides', 'energytheme'),
					'subtitle'    => __('Unlimited slides with drag and drop sortings.', 'energytheme'),
					'desc'        => __('This field will store all slides values into a multidimensional array to use into a foreach loop.', 'energytheme'),
					'placeholder' => array(
						'title'           => __('Slide Title', 'energytheme'),
						'description'     => __('Slide Message', 'energytheme'),
						'url'             => __('Button text and URL (ex. View More - http://www.yourdomain.com/more)', 'energytheme'),
					),
				),
</pre>

Any help with this would be greatly appreciated and if you need any further info please let me know asap.

Thanks.

**Comment by PulsarMedia** [comment]
Hi,

I also wanted to mention that this only happens when i initialize my theme. If i insert a slide and then delete it the $slides variable returns an empty array and the undefined index notice is gone.

So it seems the slides field is not returning a default empty array upon initialization resulting in the undefined index notice.

Regards.

**Comment by kprovance** [comment]
Any chance on you doing a fix and submitted a pull request?  Dovy and I hip deep in another project right now.  Waiting for us could take a few days.

**Comment by PulsarMedia** [comment]
Sorry im pretty busy myself with other projects as well. I don't mind waiting a few days for a proper update and i will be sure to make a donation once the fix is released.

Thanks.

**Comment by kprovance** [comment]
After looking at the code, I tend to this this was by design, because there wasn't any point is saving a blank slide to the database.  The answer, in the interim, is to use isset to check that field before attempting to pull values from it.  I'll have to ask @Dovy if this was by design or not.

**Comment by kprovance** [comment]
Okay, I just confirmed it.  We do not save blank slides to the database, ever.  Use this in your code (please change `$redux_demo` to whatever your opt_name is):

```php
global $redux_demo

if (isset($redux_demo['opt-pulse-slider-slides']) && !empty($redux_demo['opt-pulse-slider-slides']) {
    $data = $redux_demo['opt-pulse-slider-slides'];
    // or whatever you need to do here.
}
```
I'll add this information to the docs.

**Comment by PulsarMedia** [comment]
ok thanks for info...the isset/empty methods eliminates the Notice.

Thanks for your help.
