### ISSUE TITLE
Theme Preview Image overlaps Theme Description Text in Theme Information Section

### ISSUE THREAD

**Issue by rupokify** [reduxframework/redux-framework#2120]

**Comment by dovy** [comment]
Screenshot, version, anything. How are we supposed to duplicate this?

**Comment by rupokify** [comment]
Wow. That was really fast. You merged it before I uploaded details. Thanks a lot mate. Cheers!

**Comment by dovy** [comment]
;)

If you like Redux, or the support we render, please do one or all of the following:
* Donate to keep us going: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=MMFMHWUPKHKPW
* Review us: http://wordpress.org/support/view/plugin-reviews/redux-framework
* Like us: http://facebook.com/ReduxFramework
* Follow us: http://twitter.com/ReduxFramework
