### ISSUE TITLE
Hi Guys.

### ISSUE THREAD

**Issue by ManiakMill** [reduxframework/redux-framework#2122]
Hi Guys.
I found another bug:

https://github.com/reduxframework/redux-framework/blob/master/ReduxCore/templates/panel/footer.tpl.php

string: line 32
<img src="<?php $link['img'] ?>"/>

missing echo...

**Comment by ManiakMill** [comment]
<?php $link['img'] ?> missing echo.

**Comment by dovy** [comment]
Thanks! Pushed.

If you like Redux, or the support we render, please do one or all of the following:
* Donate to keep us going: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=MMFMHWUPKHKPW
* Review us: http://wordpress.org/support/view/plugin-reviews/redux-framework
* Like us: http://facebook.com/ReduxFramework
* Follow us: http://twitter.com/ReduxFramework
