### ISSUE TITLE
Appending CSS file

### ISSUE THREAD

**Issue by sodbileg** [reduxframework/redux-framework#2123]
Hi.
First, I used this code and it wasn't appending.
```
function addPanelCSS() {
    wp_register_style(
        'redux-custom-css',
        'http://urltomyfile',
        array( 'redux-css' ), // Be sure to include redux-css so it's appended after the core css is applied
        time(),
        'all'
    );  
    wp_enqueue_style('redux-custom-css');
}
```

Later, I changed `array('redux-css')` to `array()` and it worked. Is it what it should be? Redux version is `3.4.3.9`.

**Comment by kprovance** [comment]
It should be `array( 'redux-admin-css' )`.  I need to update the docs.  :)
