### ISSUE TITLE
Is there a way to achieve this?

### ISSUE THREAD

**Issue by genethic** [reduxframework/redux-framework#2124]
I want the users of my theme to enter a list with more than one data. I will put my example to explain:

I want they to enter a domain extension(.com, .org, .net) and the associated price. I can lets users enter as many domain extension as they want  with the multi-text field or the sortable field, but how can I do to associate a price to it?

I have trying to think in a way to achieve this, but I don't know, maybe is not possible.  If you guys could give me an idea it will be great.

Thanks in advance!

**Comment by dovy** [comment]
http://docs.reduxframework.com/extensions/repeater/   ;)
