### ISSUE TITLE
Redux Typography Field Problem

### ISSUE THREAD

**Issue by webbudesign** [reduxframework/redux-framework#2125]
Hi,

I am using WP : 4.1.1
And Redux v.3.4.4.1

My problem is with Typography Field. I am changing the font size and saving settings. But css compiler not work until I refresh the page or exist the page. You can find my configuration for output below code:

'opt_name'             => 'xxy',
				'global_variable' 	   => 'xxx',
                'display_name'         => 'xxx',
                'menu_type'            => 'submenu',
                'page_parent'          => 'xxx',
                'menu_title'           => esc_html__('Options Panel'),
                'page_title'           => 'xxx',
                'admin_bar'            => false,
                'allow_sub_menu'       => false,
                'admin_bar_priority'   => 50,
                'global_variable'      => '',
                'dev_mode'             => false,
                'update_notice'        => false,
                'menu_icon'            => 'dashicons-admin-tools',
                'page_slug'            => 'xxxx',
                'save_defaults'        => true,
                'default_show'         => false,
                'default_mark'         => '',
                'transient_time'       => 60 * MINUTE_IN_SECONDS,
                'output'               => true,
                'output_tag'           => false,
                'database'             => '',
                'system_info'          => false,
                'domain'               => 'redux-framework',
                'hide_reset'           => true,
                'update_notice'        => false,
                'google_api_key' 	   => "xxx",
                'google_update_weekly' => true,
                'async_typography' 	   => true,
                'compiler' 			   => true,

**Comment by kprovance** [comment]
Your arguments array tells us nothing.  We need the field code, and an example of how your compiler is setup.

**Comment by webbudesign** [comment]
I discover another thing. On the typography field it not make any change after first font change. But If I made another font change it apply first one. But not apply last one. This happen all fields in to the typography field. I am writing my compiler and field code below;

FIELD CODE: (my typography field)

<code>

array(
								'id' => 'setup22_searchresults_title_typo',
								'type' => 'typography',
								'title' => esc_html__('Title Area', 'xx') ,
								'google' => true,
								'font-backup' => true,
								'compiler' => array(
									'.pflist-itemdetails .pflist-itemtitle a'
								) ,
								'units' => 'px',
								'color' => false,
								'default' => array(
									'font-weight' => '400',
									'font-family' => 'Ubuntu Condensed',
									'google' => true,
									'font-size' => '18px',
									'line-height' => '21px',
									'text-align' => 'left'
								)
							) ,
</code>



compiler code:


<code>
public function initSettings(){
				$this->setArguments();
				$this->setSections();
				if (!isset($this->args['opt_name'])) {return;}

				// Custom CSS
				add_action('redux/plugin/hooks', array($this,'remove_demo'));
				add_filter('redux/options/' . $this->args['opt_name'] . '/sections', array($this,'dynamic_section'));
				add_filter('redux/options/' . $this->args['opt_name'] . '/compiler', array($this,'compiler_action') , 10, 2);
				
				$this->ReduxFramework = new ReduxFramework($this->sections, $this->args);
			}

function compiler_action($options, $css){
				
				$uploads = wp_upload_dir();
				$upload_dir = trailingslashit($uploads['basedir']);
				$upload_dir = $upload_dir . '/pfstyles';
				if (! is_dir($upload_dir)) {mkdir( $upload_dir, 0755 );}
				$filename = trailingslashit($uploads['basedir']) . '/pfstyles/pf-style-main' . '.css';
				global $wp_filesystem;
				if (empty($wp_filesystem)) {
					require_once (ABSPATH . '/wp-admin/includes/file.php');
					WP_Filesystem();
				}
				if ($wp_filesystem) {$wp_filesystem->put_contents($filename, $css, FS_CHMOD_FILE);}
			}
</code>

**Comment by webbudesign** [comment]
Thanks for fast reply.

**Comment by kprovance** [comment]
Yup, you found a bug!  Ding, ding, ding!  We'll have it fixed before end of day.  Thanks!

**Comment by webbudesign** [comment]
Thank you very much. waiting fix.

**Comment by webbudesign** [comment]
Hi,

Any new about solution. Because look like there is more than typography  field. A lot of option not work.

**Comment by dovy** [comment]
@webbudesign It's taking more work. Doing the best I can to fit it in.  :)

**Comment by kprovance** [comment]
v.3.4.4.2, now available should address this.  Thanks.  :)
