### ISSUE TITLE
WPML String Translation Plugin Conflict

### ISSUE THREAD

**Issue by mahfoozroy** [reduxframework/redux-framework#2126]
Hi Team Redux Framework

When WPML plugin is installed and activated there is no issue, but if we install WPML string translation plugin then the check boxes in theme options does not work properly, once a checkbox is checked, we save and it works fine, but then if we uncheck it and save settings, if the WPML string translation is active it does not save the new settings for checkbox, the checkbox gets checked all the time.
I have tried different ways but it is issue.
Please have a look.

Thanks
Realty Theme Development Team.

**Comment by dovy** [comment]
@mahfoozroy I am not sure if WPML should translate anything except strings. I am working on a resolution for string translation, but WPML stores things quite differently than Redux does. We can't have that type of backwards compatibility unless we modify WPML directly.

I suggest you only work with strings.

**Comment by mahfoozroy** [comment]
Hi Dovy

Thank you for getting back to me, We do not have any issues with WPML,
strings are being translated fine, the issue is WPML String translation
plugin has conflict with Redux Framework, translation is not a problem,
settings for redux framework are not being saved when string translation
plugin is active.
We have contacted and have done some research on this which concludes that
v2.0.4 of String translation plugin works fine but releases after that do
not work fine. please suggest here

Thanks

**Comment by kprovance** [comment]
Well, if their plugin broke something, why is it on us to fix it?

**Comment by mahfoozroy** [comment]
Hi Kevin

I am sorry if you have any inconvenience
I just wanted to raise the issue before you people.
Obviously it is not on you but if you people can do something about it,
many people can get advantage from it. We have contacted them also for this
issue, I hope they will help us too.

Thank you so much for your time.

Regards
Roy
