### ISSUE TITLE
How to: full-width option?

### ISSUE THREAD

**Issue by paulthecoder** [reduxframework/redux-framework#2128]
Hi,

No issues here, just couldn't find anything of this sort in the doc besides the raw field. How can I make the ace editor field full width so that the editor is below the title and subtitle, instead of to the right of it? 

If this is not possible, let me know. I can probably take some time into coding this feature!

Thanks guys!

**Comment by kprovance** [comment]
You can't, not without hacking the field code.  That's the way the Wordpress options API works.

**Comment by dovy** [comment]
So look at our section field. We did this bt breaking out of tables and using js magic.  ;)

**Comment by kprovance** [comment]
FTR, that `full_width` argument I wrote for the raw field, specifically.  No other fields use it.

**Comment by dovy** [comment]
`full_width` is now an argument for the core and ANY field can be made full width.  ;)

Donations welcome!  :)  
https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=MMFMHWUPKHKPW

**Comment by paulthecoder** [comment]
Awesome, thanks again! I'll be sure to donate when I get the chance.
