### ISSUE TITLE
Problem welcome page

### ISSUE THREAD

**Issue by nicolas92** [reduxframework/redux-framework#2129]
Hello, I have updated redux to the latest version and I just noticed a submenu "Redux Framework" in "Tools", but there is nothing written, only titles, is it possible to remove this page?
Thank you.

**Comment by kprovance** [comment]
It is not.  That page will be finished soon and will be part of the Redux core.

**Comment by nicolas92** [comment]
Ok, but why there is just nothing written except the titles, it is I who must fill the page or is this normal?
Thank you.

**Comment by kprovance** [comment]
The page isn't finished yet.  When we push it to wp.org, it will be.

**Comment by nicolas92** [comment]
Meanwhile, the page is useless, why it is visible?
It will end up in a long time this page?
After I stop bothering you :)
