### ISSUE TITLE
WPEngine Conflict, segmentation fault

### ISSUE THREAD

**Issue by Ryu-k** [reduxframework/redux-framework#2131]
Hi, I have an hosting account on wpengine and it seems that Wpengine block the access to the theme option panel page ( 502 error ) because the reduxframework seems to create a segmentation fault.

I tried with the default wordpress theme and still got the error.

Did anyone know anything about this?

Thanks in advance

**Comment by kprovance** [comment]
#1975,, please.

**Comment by kprovance** [comment]
I think Dovy meant to post this here.  It ended up in the wrong thread:



Are you checking the error logs? Have you checked permissions?

We used to use WPEngine, so I know it's not something that regularly occurs. Cardinal (http://cardinal.swiftideas.com) and others are on WPEngine. It's something with your setup specifically.

**Comment by Ryu-k** [comment]
It's seems that I had an issue with one of the extension, using the newest version 3.4.4.2 fixed the problem.

Thanks
