### ISSUE TITLE
Typography field outputs font-weight and font-style

### ISSUE THREAD

**Issue by jaschaio** [reduxframework/redux-framework#2132]
Hey Guys,
I have the same problem as #1591, the typography field outputs font-weight and font-style, althought they are disabled:

    array(
        'id'        => 'typography-body',
        'type'      => 'typography',
        'title'     => __('Body Font', 'redux-framework-test'),
        'subtitle'  => __('Specify the font for the body text.<br /><em>Default: Lato</em>', 'redux-framework-growtheme'),
        'google'    => true,
        'font-style'=> false,
        'font-weight'=> false,
        'font-size' => false,
        'line-height'=> false,
        'text-align'=> false,
        'subsets'   => false,
        'color'     => false,
        'default'   => array(
            'font-family'   => 'Lato',
        ),
        'output'    => array (
            'font-family'   => 'body',
        )
    ),

Output:

    body{font-family:Lato;font-weight:normal;font-style:normal;}

**Comment by kprovance** [comment]
#1975, please.

**Comment by jaschaio** [comment]
Sorry Kevin, I had indeed used an outdated version (v3.3.6) althought I was sure that I had the latest one. Thanks anyway, won't happen again!

**Comment by dovy** [comment]
@jaschaio No worries. Just look around. There are few questions that haven't been answered by the community.  :)

If you like Redux, or the support we render, please do one or all of the following:
* Donate to keep us going: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=MMFMHWUPKHKPW
* Review us: http://wordpress.org/support/view/plugin-reviews/redux-framework
* Like us: http://facebook.com/ReduxFramework
* Follow us: http://twitter.com/ReduxFramework
