### ISSUE TITLE
Backslashes being added to textareas

### ISSUE THREAD

**Issue by ghostpool** [reduxframework/redux-framework#2133]
Redux: 3.4.4.2
WordPress 4.1.1
Integrated

Hey guys,

Many of my users are reporting that backslashes are being added to their JavaScript content added to textareas. They did not have this issue in v3.4.3.2 it's only occurring since upgrading to v3.4.4.2 (although may have been since v3.4.4 as I updated the theme from v3.4.3.2 to v3.4.4.2). Here's an example of the code used:

	array( 
		'id' => 'footer_ad',
		'title' => __( 'Advertisement', 'gp_lang' ),
		'desc' => __( 'Add your advertisement code to display just above the footer.', 'gp_lang' ),
		'type' => 'textarea',
	),

**Comment by kprovance** [comment]
I am unable to replicate.  Can you provide the actual text used in the textarea, the one that is having slashes added to it?

**Comment by dingo-d** [comment]
It could be the ajax save thing, it added slashes to me to, even with the newest version.

**Comment by ghostpool** [comment]
Here's the code they are using:

	<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
	
	<ins class="adsbygoogle"
	 style="display:block"
	 data-ad-client="ca-pub-4686116187392891"
	 data-ad-slot="1747455360"
	 data-ad-format="auto"></ins>
	<script>
	(adsbygoogle = window.adsbygoogle || []).push({});
	</script>

**Comment by kprovance** [comment]
I tried this sample and still cannot reproduce.  I assume it's happening for you as well?  Have you tried resetting the section, and then saving it again?

**Comment by kprovance** [comment]
Also,  do we know what version of PHP this happens with, specifically, is it 5.2?

**Comment by britner** [comment]
I've been doing some testing, this only happens with php 5.2 for me. Happens with apostrophes and quotes

Ben

**Comment by dovy** [comment]
Found an issue with PHP 5.2 doesn't do a proper array_map with stripslashes_deep. I'm about to push the fix. I think we're finally done with this!
