### ISSUE TITLE
Media upload issue 

### ISSUE THREAD

**Issue by hamdysalah** [reduxframework/redux-framework#2136]
after i integrated redux with a theme i can't upload or view images in media it's appear white box and keep loading 
look at the pic 
http://awesomescreenshot.com/0244ntbg3b

i testing uploading in normal theme it's working fine 

anyone have a solution ?

//sorry for my english :/

**Comment by kprovance** [comment]
#1975, please.

**Comment by dovy** [comment]
And please disable all other plugins before testing. There may be a conflict somewhere.

Also are you a developer or a user?

**Comment by dovy** [comment]
Oh wait, just looked at your screen. I am 100% sure that this is not a Redux issue.

Use chrome, open up the Inspect Element option, and check your network traffic. There is a PHP bug somewhere in your code. The media browser works via Ajax, so the error or warning is stopping the ajax event from happening.

Best of luck!
