### ISSUE TITLE
Font-weight without font-style

### ISSUE THREAD

**Issue by paulthecoder** [reduxframework/redux-framework#2137]
I'm using:
Redux Version 3.4.1
WordPress 4.1.1

When I choose Roboto as my font-family, all the font-weights and font-styles show up, even though I have font-style set to false. It would be cool if only the font-weights would show up, and if you want to achieve perfection, perhaps changing the field title to "Font Weight" instead of "Font Weight & Style"? Let me know if I did something wrong here. Thanks!

Here is my field code:
```
array(
	'id'             => 'font',
	'type'           => 'typography',
	'title'          => __('title', 'theme'),
	'google'         => true,
	'color'          => false,
	'font-size'      => false,
	'font-style'     => false,
	'font-weight'    => true,
	'letter-spacing' => true,
	'line-height'    => false,
	'text-align'     => false,
	'subsets'        => false,
	'units'          => 'px',
	'subtitle'       => __('subtitle.', 'theme'),
	'default'        => array(
		'font-family'    => 'Roboto',
		'google'         => true,
		'font-weight'    => 700,
		'letter-spacing' => '0px',
	),
	'preview' => array(
		'font-size' => '18px'
	),
	'select2' => array(
		'minimumResultsForSearch' => 10,
		'allowClear' => false,
	),
),
```

**Comment by kprovance** [comment]
Update Redux, please.

**Comment by paulthecoder** [comment]
I've updated to v3.4.4.4, and still the same issue.

**Comment by kprovance** [comment]
I'll be sure to look at it when I get the chance.  ;-)
