### ISSUE TITLE
Presets option for Select Field

### ISSUE THREAD

**Issue by paulthecoder** [reduxframework/redux-framework#2138]
Is there any way of using the presets option in the <a href = "http://docs.reduxframework.com/core/fields/select/" target = "_blank">select field</a> just like the <a href = "http://docs.reduxframework.com/core/fields/image-select/" target = "_blank">image select field</a>?

**Comment by kprovance** [comment]
Inherently.  No.  With the compiler hook, anything is possible tho.  You'd have to write your own code, tho.

**Comment by paulthecoder** [comment]
Ok, thanks @kprovance
