### ISSUE TITLE
Redux Framework 

### ISSUE THREAD

**Issue by blwl** [reduxframework/redux-framework#2139]
Hi, 

I am currently using the wordpress theme, Akast, which uses the redux-framework for its theme option,  for the past 2 days, the theme option is not functioning well. On and off, the loading of the actual site would take 20+ sec and theme option would not load at all (blank white page).

As of now, everything is working fine. I was wondering if this could be the result of the redux framework maintenance.

Cheers,
Billy

**Comment by dovy** [comment]
Billy:
Even if Redux went down it would have no effect on your site. Unless your developer shipped with Developer Mode enabled, there is nothing that we have in there that could temporarily slow your site down. It must have been something else.

Best of luck.

**Comment by blwl** [comment]
Thanks Dovy for the clarification.

**Comment by dovy** [comment]
You're welcome. :)
