### ISSUE TITLE
Textarea/Ace Editor - Single Quotes - New Slashes Per Save

### ISSUE THREAD

**Issue by donkoink** [reduxframework/redux-framework#2140]
I am using the latest version (v3.4.4.4) and have another issue related to single quotes:

If in a Textarea or AceEditor field, I type:

```
alert('ok');
```

and I press Save, it saves successfully. However, as soon as I reload/refresh the same page in the browser, the textarea shows:

```
alert(\'ok\');
```

and if I save again without modifying anything, and refresh the page again, it shows:

```
alert(\\'ok\\');
```

another save, refresh, 2 more slashes are added. That's the pattern.

Am I missing something or is this a bug?

**Comment by kprovance** [comment]
It might be time to move away from PHP 5.2?  We'll have to look into it, again.

**Comment by donkoink** [comment]
Yep can confirm: using PHP 5.5 fixes the problem. 

Sadly, my client's host is still running an old version of PHP.

Thanks for the quick feedback though! Cheers!

**Comment by dovy** [comment]
Resolved in 3.4.4.5. Had to do a stripslashes and stripslashes_deep to get it to work. Darn archaic php 5.2!

;)

If you like Redux, or the support we render, please do one or all of the following:
* Donate to keep us going: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=MMFMHWUPKHKPW
* Review us: http://wordpress.org/support/view/plugin-reviews/redux-framework
* Like us: http://facebook.com/ReduxFramework
* Follow us: http://twitter.com/ReduxFramework
