### ISSUE TITLE
best way to enable have options per user (for admin)

### ISSUE THREAD

**Issue by mc007** [reduxframework/redux-framework#2141]
Hi,
there are quite some topics around: 'multiple instances' and 'use subsections',....Nothing really fits of that.

Here is the use-case: 

1. Admin creates/edit from within a redux-panel a new set of options(not subsection) per user or user group, using a default/global set of options as input.

2. After this new and named option-set is 'registered' or in the database, admin can attach/set this to a user or user group (I am aware about some complications, but please ignore the logic/model for now).

3.  Admin later on can delete and remove this dynamic set of options.

I hope this makes sense to you. Do you have some little guidance doing this? Best is to think about a creating and managing 'permission/setting templates' for a file-manager a administrator might set per user/group. 

Thank you!

**Comment by kprovance** [comment]
The closest we have to such a thing would be Permissions:  http://docs.reduxframework.com/core/fields/using-permissions/

**Comment by mc007** [comment]
hi, thanks, but no, the 'permission' were just an example. We need a full set of options; its like dynamic and manageable Redux instances per user.

**Comment by mc007** [comment]
Could you please confirm that this is at least doable with Redux at all? I mean without large efforts.
thank you.

**Comment by kprovance** [comment]
Sections can be added dynamically, yes.  See the sample-config.php for an example.  Combining that with permissions, that will be code you will have to write.

**Comment by mc007** [comment]
ok, i saw another thread where a user actually said that sections are quit inflexible in such case and i agree, but i will try again. thanks for the heads up!

wishlist: enable dynamic & multiple instances

**Comment by kprovance** [comment]
tagged in #348.  Financial backing helps make wishlist items a reality.  :)

**Comment by mc007** [comment]
better guidance or instructions as well :-)

**Comment by kprovance** [comment]
Hey, anytime you think you can write better docs, you're welcome to have at it.  You get what you pay for, right?

**Comment by dovy** [comment]
Boys boys. But yes, mc007 it's not our job to do more than we've done. Sorry.
