### ISSUE TITLE
Using Shortcode in ace editor

### ISSUE THREAD

**Issue by ericwallen** [reduxframework/redux-framework#2142]
Good morning, hope you guys are well.

I have been trying to figure out how I can use a shortcode in redux ace editor. I have tried several modes including php so I could echo shortcode..html and a few others.

Ideally I would like to edit just once piece of the short code:

[stat_counter icon_type="selector" icon="Defaults-twitter" img_width="48" icon_size="60" icon_color="#40b6e5" icon_style="none" icon_color_bg="#1e73be" icon_color_border="#333333" icon_border_size="1" icon_border_radius="500" icon_border_spacing="50" icon_animation="swing" icon_position="top" counter_title="Twitter" counter_value="90" counter_sep="," counter_decimal="." speed="6" font_size_title="18" font_size_counter="28" counter_color_txt="#ffffff"]

Is there a way to create an option that can update the 90 value of this shortcode?

or

can I put the whole shortcode in the option and pull it back in to my theme in some fashion that will work?

Thanks!

**Comment by dovy** [comment]
Do_shortcode is the Wordpress function you're looking for.

**Comment by ericwallen** [comment]
I have tried variations of using this <?php echo do_shortcode( $content ) ?> inside my theme with redux.

Could you please provide me an example of how to use redux to update a value of the shortcode.

Note: I have not problem using <?php echo do_shortcode( $content ) ?> without redux. I need redux to update the counter value of previously stated shortcode.

**Comment by ericwallen** [comment]
here is my option:

array(
    'id'        => 'episodes-counter',
    'type'     => 'text',
    'title'    => __('Episodes Count', 'redux-framework-demo'),
    'subtitle' => __('Paste your CSS code here.', 'redux-framework-demo'),
    'mode'     => 'php',
    'desc'     => '',
    'default'   => '50',
),


<?php echo do_shortcode('
[stat_counter icon_type="selector" icon="Defaults-image" img_width="48" icon_size="60" icon_color="#d8c12d" icon_style="none" icon_color_bg="#1e73be" icon_color_border="#333333" icon_border_size="1" icon_border_radius="500" icon_border_spacing="50" icon_animation="swing" icon_position="top" counter_title="Episodes" counter_value="365" counter_sep="," counter_decimal="." speed="8" font_size_title="18" font_size_counter="28" counter_color_txt="#ffffff"]
');?>


How can I get the redux value to create/update shortcode vale: counter_value="365" ?

**Comment by ericwallen** [comment]
pls ignore mode. I accidently left that when I was experimenting with the ace editor instead of text

**Comment by dovy** [comment]
It should work find provided you're usint the key of your field name with your global variable...

Do_shortcode($global_variable['ace_field_variable'])

**Comment by ericwallen** [comment]
I set it up like this:
					array(
    'id'        => 'episodes-counter',
    'type'     => 'ace_editor',
    'title'    => __('Episodes Count', 'redux-framework-demo'),
    'subtitle' => __('Paste your CSS code here.', 'redux-framework-demo'),
    'mode'     => 'html',
    'desc'     => '',
    'default'   => '[stat_counter icon_type="selector" icon="Defaults-image" img_width="48" icon_size="60" icon_color="#d8c12d" icon_style="none" icon_color_bg="#1e73be" icon_color_border="#333333" icon_border_size="1" icon_border_radius="500" icon_border_spacing="50" icon_animation="swing" icon_position="top" counter_title="Episodes" counter_value="365" counter_sep="," counter_decimal="." speed="8" font_size_title="18" font_size_counter="28" counter_color_txt="#ffffff"]',
),
				
Then in my php.
<?php echo do_shortcode($redux_demo['episodes-counter'])');?>


But it didn't work. Is this what you were suggesting or do I have it messed up?

**Comment by ericwallen** [comment]
Dovy, look. I am obviously not as smart as you. I am just looking for a working code example. I am surely not the first to try this with redux? 

It seems I followed your instructions to the T.

**Comment by kprovance** [comment]
Dovy might be unavailable for the next day or so.  First, I must know what version of Redux you are using (please, don't say 'latest').  Second, I need to know what is set under the opt_name argument, third, have you done a print_r on the episodes-counter variable, to see if anything if even in that variable?

**Comment by ericwallen** [comment]
Hi kprovance, thanks for the reply. You know I am so embarrassed that I don't know php hardly at all. Honestly, I use plugins such as redux because of this. I don't know how to print_r but did make it to my local barnes and noble to pick up my first php book. I couldn't dive in to it because I am juggling two jobs. Seems like redux could do this...i mean its robust enough. Thanks for you help. Do I need to figure out how to do the print_r before figuring this out? My current version is 3.4.1. Again, thanks.
