### ISSUE TITLE
Option to hide fields from customizer

### ISSUE THREAD

**Issue by nova-ind** [reduxframework/redux-framework#2145]
Hi folks,

I was wondering if there is a way to hide some fields from showing up in the customizer. I am aware of the customizer_only argument, I'm interested in doing the opposite, because with the fields not supported by the WP customizer hidden the other fields just show up without separators and section titles and are very confusing. I'd also like to know if there's a way to add support for fields myself, without modifying core files.

I apologize if this has been answered before, I did my homework but couldn't find anything.

Cheers!

**Comment by dovy** [comment]
Set the field arg of `customizer` to false. 

Also you can set customizer to false in the panel args to completely disable the customizer for all your fields.

If you like Redux, or the support we render, please do one or all of the following:
* Donate to keep us going: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=MMFMHWUPKHKPW
* Review us: http://wordpress.org/support/view/plugin-reviews/redux-framework
* Like us: http://facebook.com/ReduxFramework
* Follow us: http://twitter.com/ReduxFramework
