### ISSUE TITLE
Redux Builder Issue

### ISSUE THREAD

**Issue by AliJahandideh** [reduxframework/redux-framework#2146]
Hi there,
in redux builder -> admin folder  when i click on "Generate Admin Folder" button, IDM start downloading the file, but its just 1Byte. whenever I try to extract with WinRAR it just gives me the "damaged file" error.

**Comment by AliJahandideh** [comment]
it totally worked on mac firefox

**Comment by kprovance** [comment]
I have check the builder, and cannot reproduce.  If you are using any type of download accelerator, please disable it.  See #1677
