### ISSUE TITLE
using REDUX FRAMEWORK i can't upload theme to wordpress theme directory.

### ISSUE THREAD

**Issue by imVinayPandya** [reduxframework/redux-framework#2147]
Hello friends i have made my first wordpress theme [check my theme here] (https://github.com/imVinayPandya/Local).

i am using redux framework for theme options. but when i was trying to upload theme to wordpress theme directory and its giving me lot of error and warning from redux framework files.

i have already removed extra folder and files, from redux framework directory and also used theme check plugin its giving me positive response. but i dont know why wordpress theme directory giving me errors.

thank you in advance.

**Comment by kprovance** [comment]
http://docs.reduxframework.com/core/theme-check/

**Comment by dovy** [comment]
The actual page you need for WP.org submissions: http://docs.reduxframework.com/core/wordpress-org-submissions/

**Comment by imVinayPandya** [comment]
thank you sir; but i am getting some warning and info like use
file_get_content() and more like this

**Comment by dovy** [comment]
That's backup for if the wp file system fails. We have many themes on wp.org.

**Comment by imVinayPandya** [comment]
i have deleted that tracking.php after disabling tracking from
framework.php but still getting some errors.

here is my theme

https://github.com/imVinayPandya/Local

**Comment by imVinayPandya** [comment]
yup i can understand but i am newbie from wordpress theme development and
this is my first theme. please help me

**Comment by dovy** [comment]
We are a framework, not teachers in theme development. Let's just say if you follow the docs and refer to docs during submission all should be fine. :)

**Comment by imVinayPandya** [comment]
ok leave it, i have tried all of that. and i am not asking for theme
support i am asking for frameworks bcz all the warning and info locate your
framework file that is why i asked for support.

thank you for time.

**Comment by dovy** [comment]
Haha. Like I said. It will pass. Just follow the docs.
