### ISSUE TITLE
Redux Builder download function doesn't work

### ISSUE THREAD

**Issue by wolfinjo** [reduxframework/redux-framework#2148]
Hi,

I have the same problem as this: https://github.com/ReduxFramework/redux-framework/issues/1326

When I go to download the files from the Redux builder, I am directed to a page that is blank except for a single zero (0) in the top left.

I tried with Mozilla, IE8, Chrome and Opera... and every time is the same....

What can I do now ?

Thank you

**Comment by kprovance** [comment]
I have check the builder, and cannot reproduce.  If you are using any type of download accelerator, please disable it.  See #1677

**Comment by wolfinjo** [comment]
What is download accelerator ?
