### ISSUE TITLE
call the templates in the theme

### ISSUE THREAD

**Issue by nicolas92** [reduxframework/redux-framework#2149]
Hello, I would like to modify the templates of the panel, can you give me the code to insert into my redux file to call the templates, I tried several things but it does not work, I have found nothing in the documentation.
Thank you very much.

**Comment by kprovance** [comment]
You'll need to set the `template_path` argument to the location where you are storing your template files.  Redux will look in that directory for the templates to apply and override the ones included in the core.

**Comment by nicolas92** [comment]
Forgive my ignorance, but what do you mean by "template_path" I have to create a function like the custom css of the panel, can you give me an example, I would understand much better.
Thank you very much.

**Comment by kprovance** [comment]
First, a more than passing working knowledge of PHP is required to use Redux, especially its more advanced features.  I really can't write your code for you, as I have NO idea about your project or how it's setup.  That's what premium support is for.

Redux uses arguments, as set in the config file under the `setArguments` function.  That is where you would assign the path to the directory for your template files, to the `template_path` argument.  There is no possible way for me to know what that path is.  It's wherever you are putting you template files.

**Comment by dovy** [comment]
Also this is a new and undocumented feature. Hence the lack of docs. ;)

**Comment by nicolas92** [comment]
I want an example only to understand, I created a custom css for the panel, I entered the following code:

<pre>function redux_custom_css() {
	wp_register_style( 'redux-custom-css', get_template_directory() .'redux/redux-custom.css', array(), time(), 'all' );
	wp_enqueue_style( 'redux-custom-css' );
}
add_action('redux-enqueue-my_options', 'redux_custom_css' );</pre>

it works, it's very simple, I want a code with a fake path only to understand how to do, I tried several things but nothing works.
Can you help me?
Thank you very much.

**Comment by nicolas92** [comment]
All right, I found how to do.

**Comment by mrgurdeep** [comment]
@nicolas92 Can you share how did you change it ?

**Comment by mrgurdeep** [comment]
Never Mind, I Got it thanks by setting variable
templates_path=> get_template_directory().'/admin/templates, 
adding to config files
where admin/templates is folder where all custom templates are copied.

**Comment by nicolas92** [comment]
Hello @mrgurdeep, you found :)
