### ISSUE TITLE
Theme check failed

### ISSUE THREAD

**Issue by abukwaik** [reduxframework/redux-framework#2150]
WordPress version: 4.1.1
ReduxFramework version: 3.4.4.2
dev mode: false
google api key: yes
using Redux: embedded in a project.

Hello guy, 

I know this has been discussed before, but yet, i couldn't find any solutions.

OK, long story short. My theme was approved 6 weeks but unfortunately, they reopened the ticket and asked me to not include "zip" file inside the theme folder (i was using Redux as a plugin) and so, I re-embedding Redux using the "Redux Generator" but the theme just failed in the check. 

Note: I tried Generated version 3.3.6 and Developer version 3.4.4.2.

Ticket reference: 
https://themes.trac.wordpress.org/ticket/23148#comment:13
Check screenshots:
v3.3.6 : http://i.imgur.com/l45gF80.png
v3.4.4.2 : http://i.imgur.com/EESXD6x.png

Thank you,

**Comment by dovy** [comment]
And there's a doc for wp.org submissions. Please read it.
