### ISSUE TITLE
Not Working with plugin

### ISSUE THREAD

**Issue by shehryarabs** [reduxframework/redux-framework#2152]
I am using Redux in my plugin. Redux option panel is coming but When I echo something it does not show anything.

I created my main plugin file and then function.php file (include Redux in this file) then include function.php file in Main Plugin file.

Can you please tell me why this is not showing anything.

Thanks,
Shehryar

**Comment by kprovance** [comment]
#1975, please

**Comment by shehryarabs** [comment]
So If take premium then you will help me? I have used your plugin in my theme before. At that time I followed your document to integrate your plugin but this time it's not working. I just want to know if there is anything else I have to do to integrate it in my plugin or the same document will work.

Thanks,

**Comment by dovy** [comment]
We haven't changed compatibility. If it worked before for you, it should again. You probably have something miscofigured.

**Comment by dovy** [comment]
Just remembered the global variable is the same as your opt_name

**Comment by shehryarabs** [comment]
Thanks for your reply Dovy

**Comment by dovy** [comment]
Did it work?

**Comment by shehryarabs** [comment]
Actually no, I have already check this it's same but not working.

Thanks

**Comment by dovy** [comment]
Sorry, but I you need to provide a bunch more details. 

Are you changing the class name? Perhaps you're using the same class and things are being overridden?

**Comment by shehryarabs** [comment]
Yes I change the class name

**Comment by dovy** [comment]
Sorry dude, you have to give me something to go off of. "Not working" isn't enough to go off of. I can't code for you unless you want to have us provide you with premium support.

**Comment by shehryarabs** [comment]
I would take premium support but this my first try to create and sell plugin. I have to do everything myself. If I get success and get any problem in future will ask you guys with premium support.

Thank for your reply

**Comment by dovy** [comment]
Best of luck my friend. Until you can get me some more details I can't help. Later!

**Comment by shehryarabs** [comment]
I am making a plugin. First I created a main plugin file then a functions.php file include your framework and sample-config file in that and set global variable in main plugin file.

Now option panel is coming. I also create a widget with my plugin and want to display data from option panel to my widget that's not coming.

**Comment by dovy** [comment]
@shehryarabs I am sorry, but I really need you to read #1975. Open a new ticket when you have the actual information requested. Know that this is not a fault on our end, but in your code. We won't help you further unless you can show us how this is OUR bug. Otherwise we need premium support to dig into your code. I'm sorry, but this is open source which is pretty much self-serve. We'll fix bugs, but we can't and won't instruct on basic PHP.
