### ISSUE TITLE
Cant get demo to show

### ISSUE THREAD

**Issue by amelk0516** [reduxframework/redux-framework#2154]
Hi, 

I edited all the information through intima settings but the landing page is the default blog. How do I get the landing page to be the Main page that looks like the demo which i have all of my information on.

**Comment by dovy** [comment]
@amelk0516 We did not make your theme. We're the framework developers use to build option panels. Contact your theme developer.

**Comment by amelk0516** [comment]
Thanks

**Comment by dovy** [comment]
You're welcome. Best of luck!
