### ISSUE TITLE
Import not working

### ISSUE THREAD

**Issue by paulthecoder** [reduxframework/redux-framework#2155]
WordPress 4.1.1
Redux 3.4.4.5

I've tried to import, but no success. I've tried multiple methods to see if I was at fault, but none of them worked. Any ideas?

I am using the show_import_export option in the arguments. I also tried adding the import/export field, but still no cigar.

Update: I've searched through framework.php 'function ajax_save' and redux.js ajax save and found nowhere does it handle import code? Are you guys still implementing it for the ajax save? Let me know, I could help finish coding the import faster! Thanks.

**Comment by dovy** [comment]
Fixed in 3.4.4.8. Thanks as always @paulthecoder
