### ISSUE TITLE
Sortabel FIield: Can't hide the values before text areas when mode is not checkbox.

### ISSUE THREAD

**Issue by codespacing** [reduxframework/redux-framework#2156]
I'm trying to hide the the values before the text areas in the Sortable field using the argument "value" as described in the documentation but this doesn't seems to work. I think there's a bug in this level. Thank you for fixing this small issue and thank you for the fabulous Framework.

Redux version: 3.4.4.4 / dev_mod = yes / embedded in my project
Wordpress version: 4.1.1
Javascript errors: 0 error

**Comment by dovy** [comment]
Care to do some of your own footwook and see if you can find where the problem may be? We're knee deep in other things right now.  :-/

**Comment by kprovance** [comment]
Having your field code would also be helpful, and as it stands, required #1975, please.

**Comment by kprovance** [comment]
The docs are incorrect.  `value` should be 'label'.  I'll update all this shortly.

**Comment by codespacing** [comment]
Thank you for the prompt answer :)

**Comment by kprovance** [comment]
Fixed in latest GIT push v.3.4.4.6.  Remember `label`, not `value`.  I'll update the docs as well.  :)
