### ISSUE TITLE
Spacing field not using padding default values

### ISSUE THREAD

**Issue by thehung2224** [reduxframework/redux-framework#2158]
Padding default values for the spacing field won't set.

Default values:

```php
array(
    'id'             => 'sz-content-spacing',
    'type'           => 'spacing',
    'output'         => array( '#article-list' ),
    // 'mode'           => 'padding',
    'units'          => array( 'px', 'em' ),
    'units_extended' => 'false',
    'title'          => __('Padding Content', 'redux-framework-demo'),
    'subtitle'       => __('Change distance from top and bottom of content.', 'redux-framework-demo'),
    'left'           => false,
    'right'          => false,
    'default'             => array(
        'padding-top'     => '100px',
        'padding-bottom'  => '100px',
        'units'           => 'px',
    ),
),
```
Output:

![Content](http://hulk.upanh.biz/2015/03/25/Untitled7cb1c.png)

So it seems, even with my corrections I still can't get spacing to output default values. I've tried appending margin to those default values and it works. 

Thanks for any help.
Regards,

**Comment by kprovance** [comment]
I ran your code with no issue, but - as without everyone who posts here - there was a post that said PLEASE READ BEFORE POSTING (#1975), that tell you what information is required for support.  So, make sure you are using the latest version of Redux from this git repo, and also, try resetting the section for that field.

**Comment by thehung2224** [comment]
My issue was fixed. Because I've set default value before changing global variable so I need to re-set this value. Thank you.

Regards,
Hung The.

**Comment by dovy** [comment]
:)
