### ISSUE TITLE
Sub menu items still visible when not permitted

### ISSUE THREAD

**Issue by wgstjf** [reduxframework/redux-framework#2159]
Hi there,

Just getting started but love the framework, thanks!  

Got a small issue though.  When I set the permissions for a section to such that they should not display for certain roles they are still visible as sub-menu items in the admin menu.  Is there a way to get them to follow the permissions setup as is correctly done within the framework page itself?

Cheers,

Will

**Comment by kprovance** [comment]
#1975, please.  The PLEASE READ BEFORE POSTING applies to everyone.  Thanks.

**Comment by wgstjf** [comment]
I do apologise.

WP Version: Version 4.1.1
Redux Version: v3.4.4.6
Dev_mode: no
Embedded rather than plugin.

Thanks in advance :-)

**Comment by kprovance** [comment]
The guidelines also asked you supply the code you claim does not work.  I can't attempt to reproduce this without it.

**Comment by kprovance** [comment]
Last chance:  I need to see your field code, or I'll have to close this issue as unresolved.  Thanks!  :)

**Comment by wgstjf** [comment]
Hi,

Sorry for the delay...crazy busy here.  Appreciate you taking a look at this for me.

I have the sample config file, which I am just starting to play around with.  The permissions functionality is something that attracted me to redux in the first place.

The issue is that the admin sub-menu contains items that should not be visible to a user (based on their role's capabilities).  The example below is supposed to be hiding the 'Responsive Settings' from all but the Administrator as it requires 'manage_options' capability.  What actually happens is that the 'Responsive Settings' item is hidden in the Redux submenu but not in the WP Admin menu (see attached image).

The relevant bit of code is as follows:

```
/* Responsive Settings */

    $this->sections[] = array(
		'icon' => ' el-resize-small',
		'icon_class' => 'el',
        'title' => __('Responsive Settings', INDIGO_THEME_NAME),
      //  'desc' => __('Enter in your social media locations here and then activate which ones you would like to display in your footer options & header options tabs. <br/><br/> <strong>Remember to include the "http://" in all URLs!</strong>', INDIGO_THEME_NAME),
        'permissions' => 'manage_options',
        'fields' => array(

            array(
                'id' => 'responsive-menu-custom',
                'type' => 'switch',
                'title' => __('Custom Menu for small devices', INDIGO_THEME_NAME),
                'sub_desc' => __('Do you want to have a custom menu for smaller devices', INDIGO_THEME_NAME),
                'desc' => __('', INDIGO_THEME_NAME),
                'switch' => true,
                'std' => '0'
            ),
```
The following is a screenshot when logged in as an editor

![image](https://cloud.githubusercontent.com/assets/3740694/7140677/8a59d176-e2c4-11e4-9895-73ec4cf82ac1.png)

Cheers in advance.  If you need any more info do let me know :-)

Will

**Comment by kprovance** [comment]
You'll need to review this, then open a NEW issue.  This one is now closed.  Thanks.
