### ISSUE TITLE
Get image in defined sizes

### ISSUE THREAD

**Issue by Emetrop** [reduxframework/redux-framework#2162]
I don't know if I do something wrong but I cannot find out how to get an image uploaded via media type field in some other sizes then the origin size through the url attribute or thumbnail size through the thumbnail attribute from the returned redux array. I would like to have access to all of the predefined image sizes by WP like - medium, small, etc. + my custom sizes defined by add_image_size WP function. Or do I do just something wrong?

**Comment by dovy** [comment]
You have to use the WordPress functions to get the size you want using the returned `id` value. ;)
