### ISSUE TITLE
Bug in section tabs when show_import_export = false

### ISSUE THREAD

**Issue by Enchiridion** [reduxframework/redux-framework#2163]
I'm getting the exact same error as in issue #1358.
I've narrowed it down to the `show_import_export` arg. When it's true, everything works fine, but when it's false I get the javascript error:

```
TypeError: redux.field_objects is undefined                        redux.js...7319129 (line 478)
if ( redux.field_objects[type] ) {
```
I'm using the Redux Framework plugin v3.4.1, Wordpress v4.1.1.
There error happens with dev_mode set to true and false.

**Comment by dovy** [comment]
Please pull the version of Redux found from this repo. And please let me know the line issue if the problem persists.

**Comment by Enchiridion** [comment]
I pulled the latest and overwrote the ReduxCore folder in the plugin folder, but it didn't fix the issue.
I tested with v3.4.4.6.
The line number the error occurred on changed to 617.

**Comment by kprovance** [comment]
Unable to reproduce as described.  Dovy?

**Comment by dovy** [comment]
I've tested and re-tested this. I couldn't get it to break.

However, I did add some extra checking JUST IN CASE that will resolve that error. I just don't know how you got it!

Either way, it's fixed. Even though I can't duplicate.  :P

**Comment by Enchiridion** [comment]
Thanks, that fixed it!

**Comment by dovy** [comment]
Great.  :)
