### ISSUE TITLE
Upgrade framework request

### ISSUE THREAD

**Issue by NikkiMay** [reduxframework/redux-framework#2164]
I'm trying to install the plugin Ultimate Member to my site however it won't activate. the UM support writes : "A theme or plugin is using a very old version of Redux, causing this problem. Please ask them to upgrade Redux framework" - any chance you can help? Thx

**Comment by dovy** [comment]
Sorry, we didn't make Ultimate Member. What I'd suggest is install Redux Framework as a plugin, and then it should work.

Good luck.

**Comment by NikkiMay** [comment]
Thank you for your time and your response.
I will give it a go.

On Thu, Mar 26, 2015 at 11:51 PM, Dovy Paukstys <notifications@github.com>
wrote:

> Closed #2164
> <https://github.com/reduxframework/redux-framework/issues/2164>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/reduxframework/redux-framework/issues/2164#event-265810207>
> .
>



-- 
Aust: (+61) 407 066 105
Myanmar (+95) 4320 9584
nicolemay.design@gmail.com

**Comment by dovy** [comment]
You are so welcome. Best of luck!
