### ISSUE TITLE
Insert select list with CF7 names

### ISSUE THREAD

**Issue by cocodedesigns** [reduxframework/redux-framework#2166]
I think it might be related to https://github.com/reduxframework/redux-framework/issues/631, but I will ask it as a separate issue:

I'm trying to get RF to display a list of Contact Form 7 forms that I have.  I know CF7 saves the forms as CPTs, but my code doesn't seem to work all that well.  I've got:

                    array(
                        'id'        => 'wca-contact-form',
                        'type'      => 'select',
                        'data'      => 'post_types',
                        'args'      => array( 'post_type' => 'wpcf7_contact_form', ),
                        'title'     => __('Forms', 'wca-wp'),
                    ),

as my code for the select field, but I'm getting a response back saying "No items of this type were found.", yet I can see I have two forms in CF7. Have I missed something?  In a meta box I have in one of my other pages, 'wpcf7_contact_form' is the post type I use and it displays all of the forms I have there without issue.  I've tried 'post_type' and 'post_types' in both data and args.

**Comment by dovy** [comment]
Just change data to `posts` and you're good to go.

`post_types` is for listing post_types.

Here's your completed config:
```
array(
                    'id'        => 'wca-contact-form',
                    'type'      => 'select',
                    'data'      => 'posts',
                    'args'      => array( 'post_type' => 'wpcf7_contact_form', ),
                    'title'     => __('Forms', 'wca-wp'),
                ),
```

Good luck!
