### ISSUE TITLE
it's too long time you've not updated redux to wordpress repository

### ISSUE THREAD

**Issue by smpdesignmedia** [reduxframework/redux-framework#2167]
it's too long time gone, you've not updated redux to wordpress repository, where you will give update in wordpress repository ?

**Comment by kprovance** [comment]
When we are confident we have all the bugs worked out in our new features.  No sense is posting buggy code, unless you're offering to handle all our support requests?  :)

It'll be ready when it's ready.

**Comment by dovy** [comment]
@smpdesignmedia It's coming soon. Really it is. We're just finishing off a few last items. I'm hoping next week.

**Comment by dovy** [comment]
And since Redux is used by hundreds of thousands of users world-wide, we'd prefer not to break anything.  ;)
