### ISSUE TITLE
How To Validate Phone Numbers

### ISSUE THREAD

**Issue by thehung2224** [reduxframework/redux-framework#2169]
I'm trying to validate a phone number field but the available options other than text won't work since people may use dashes and parentheses to enter their number. 

I've tried preg_replace but I'm still not seeing error messages when entering incompatible data, e.g. an 'x' characters entered into a text field which should only accept an number value. 

Besides a pop-up appears say that: "There was a problem with your action. Please try again or reload the page."

```php
array(
    'id'       => 'sz-header-contact-phone',
    'type'     => 'text',
    'title'    => __( 'Phone number', 'redux-framework-demo' ),
    'subtitle' => __( 'Enter your phone number here.', 'redux-framework-demo' ),
    'validate' => 'preg_replace',
    'preg' => array(
        'pattern' => '^\(\d{3}\) \d{3}-\d{4}$',
        'replacement' => 'no numbers'
    ),
    'msg'      => 'Please enter correct phone number',
    'placeholder' => 'Enter your phone number here.'
)
```

Thanks for any help. 

Regards,
Hung The.

**Comment by kprovance** [comment]
You're regex is malformed.  Unfortunately, if you want me to write this for you, I'll ask you purchase premium support.
