### ISSUE TITLE
Could not create directory. redux-framework/.tx

### ISSUE THREAD

**Issue by GuerrillaCoder** [reduxframework/redux-framework#2170]
plugin installed fine but I had some errors with theme that it shipped with so I re-installed all plugins.  This time it keeps failing due to folder already being there.  I delete the folder but now every time I get this error and it fails:

"Could not create directory. redux-framework/.tx"

Any idea why? 

(Hosted on iis 7.5)

**Comment by dovy** [comment]
Your host does not let you see files that start with a . So delete the parent folder and then remake it and all should work.

**Comment by GuerrillaCoder** [comment]
I've done that several times but doesn't work.  Weird thing is it installed fine the first time.

I have access to the server.  I tried adding full permissions to the folder but same issue.  Anything you would suggest changing on the server?

I am new to wordpress and php in general but I'll try to see if I can get an actual code error to work from.

**Comment by dovy** [comment]
Just delete the offending folder before you upload.

**Comment by GuerrillaCoder** [comment]
"I've done that several times but doesn't work"

**Comment by dovy** [comment]
No idea bud. It's a host issue. :(
