### ISSUE TITLE
required - not_contain does not work with checkbox

### ISSUE THREAD

**Issue by vekexasia** [reduxframework/redux-framework#2171]
Hello There,

i was trying to clone and set up a dev environment to patch this issue but i'm unable to build redux on my machine and I didn't find any wiki or page explaining the steps and necessary tasks to achieve in order to start developing the redux-core.

BTW the not_contain "required" key does not work if the parentValue is a multi-checkbox.

**Comment by dovy** [comment]
It's on our docs site. There's no building required per say. Just load this repo as a WordPress plugin and you're good. ;)

**Comment by vekexasia** [comment]
ok perfect. I saw you closed this issue but actually not_contain does not work :)

**Comment by kprovance** [comment]
#1975 is required information, including the code you are using.
