### ISSUE TITLE
image_select not saving

### ISSUE THREAD

**Issue by hellofantastic** [reduxframework/redux-framework#2172]
Hey there
Using latest Redux
If I select the second option it saves but on reloading the page the default is highlighted and still the saved option.

Insight much appreciated

Image select array
```php
array(
							'id'       => 'listing-detail-layout',
							'type'     => 'image_select',
							'title'    => __('Listing Detail Page Layout', 'option-framework'), 
							'subtitle' => __('Select the listing detail page layout. Choose between 1, 2 column layout.', 'option-framework'),
							'options'  => array(
								'detail-2-column-left.php'      => array(
									'alt'   => '2 Column', 
									'img'   => ReduxFramework::$_url.'assets/img/detail-2-column-left.jpg'
								),
								'detail-1-column.php'      => array(
									'alt'   => '1 Column', 
									'img'   => ReduxFramework::$_url.'assets/img/detail-1-column.jpg'
								)
							),
							'default' => 'detail-2-column-left.php'	
						),	
```

**Comment by kprovance** [comment]
Please review #1975.  "Latest version" is not accepted.

**Comment by hellofantastic** [comment]
Ah okay 

Redux version: 3.4.4.6
Wordpress version 4.1.1
dev_mode false

```php
$this->sections[] = array(
				'title' => __('Layout Options', 'option-framework'),
				'desc' => __('Make layout choices for Homepage, Content page and Listing detail page', 'option-framework'),
				'icon' => 'el-icon-layout',
			    // 'submenu' => false,
				'fields' => array(	
					array(
                         'id'=>'section-media-start',
                         'type' => 'section', 
                         'title' => '',
                         'subtitle'=> '',                            
                         'indent' => false 
                         ), 								
				
					array(
							'id'       => 'listing-detail-layout',
							'type'     => 'image_select',
							'title'    => __('Listing Detail Page Layout', 'option-framework'), 
							'subtitle' => __('Select the listing detail page layout. Choose between 1, 2 column layout.', 'option-framework'),
							'options'  => array(
								'detail-2-column-left.php'      => array(
									'alt'   => '2 Column', 
									'img'   => ReduxFramework::$_url.'assets/img/detail-2-column-left.jpg'
								),
								'detail-1-column.php'      => array(
									'alt'   => '1 Column', 
									'img'   => ReduxFramework::$_url.'assets/img/detail-1-column.jpg'
								)
							),
							'default' => ''	
						),	
				
					),
				);

```

On first load of options page with this config for image_select the first choice is highlighted, select the second choice and hit save and it says Settings saved. Leave and come back to page and setting is back on first choice, first choice is also in the global variable for the options

**Comment by kprovance** [comment]
I've not be able to duplicate this.  I followed your instructions, but on page reload, the second option is always selected.  I'm not sure what the issue could be, except that it may be server side?  Something is not allowing the save?

**Comment by hellofantastic** [comment]
hmm okay , I'll clear th db and do I fresh config and see. thanks

**Comment by hellofantastic** [comment]
What I have deduced so far is that when i select a different image choice and save the option isn't in the data that gets passed thru ajax to the php redux set options. but if I load the page leave the default hit save, the value is in the data that gets passed

**Comment by kprovance** [comment]
Well, again, I cannot duplicate, so I'm not quite sure what to tell you.  I can't fix what I can't break.  :)

**Comment by hellofantastic** [comment]
true... and I'm avoiding a fresh test  but that's what ill do, thanks for your time.

**Comment by hellofantastic** [comment]
tried a fresh install of redux and updated to 3.4..4.8 using the sample config and still no go , and its just on the image_select, every other field works fine... nothing like a wrench in the works

**Comment by kprovance** [comment]
a fresh install of Redux doesn't nuke the DB data.  Have you tried that?

**Comment by hellofantastic** [comment]
ah hahaha!...
Found it... had a custom admin js file for custom post that was being loaded and unchecking radio inputs!
(Queue in the Aquarius song... Let the Sunshine In!)

**Comment by dovy** [comment]
Whew. Glad you found it.
