### ISSUE TITLE
Error when using admin-ajax.php

### ISSUE THREAD

**Issue by qacheck** [reduxframework/redux-framework#2173]
When it happens the ajax call is never ending. The little happens cause \redux-framework\ReduxCore\framework.php line 831 (action 'redux/options/{opt_name}/options'). Deeper causes are unclear.

**Comment by kprovance** [comment]
C'mon people.  #1975 IS REQUIRED, please.  We cannot work with one lines that all but say 'it don't work."

**Comment by qacheck** [comment]
Normally in wordpress a request domain/wp-admin/admin-ajax.php returns 0. But when used Redux plugin framework, it can not return anything. You help me, pleases!

**Comment by kprovance** [comment]
Sorry, but you completely ignore my request for more information.  I cannot even begin to think about helping until it is supplied.

**Comment by kprovance** [comment]
Closing due to lack of reply requiring required information.  In the future, please open a new issue with the necessary information,.  Thanks.
