### ISSUE TITLE
Fields Background is not save "Default Options"

### ISSUE THREAD

**Issue by bibiangel1989** [reduxframework/redux-framework#2174]
Hi,

I install ReduxFramework for my theme, but when i install fields background, and install "Default Options". This is example:

```
array(
			'id'       => 'as_option_background_footer_1',
			'type'     => 'background',
			'output'   => array( '#as-footer-1' ),
			'title'    => __( 'Footer Background', 'as' ),
			'subtitle' => __( 'Footer background with image, color, etc.', 'as' ),
			'defaults' => array(
                                'background-color'      => '#22313f',
                        ),
	),
```

The default value : 'background-color'      => '#22313f', are not save with Redux. 

Any opinion for this issue ???

Thank you !

**Comment by kprovance** [comment]
#1975, please

**Comment by kprovance** [comment]
http://docs.reduxframework.com/core/fields/background/

Use the argument `default`, NOT `defaults`.  There is no plural.

**Comment by bibiangel1989** [comment]
Oh sh*t ... sorry, this is my fault, thank you for support ! Great framework ! :+1:
