### ISSUE TITLE
Maximum function nesting level of 'xxx' reached, aborting! when live previewing

### ISSUE THREAD

**Issue by nova-ind** [reduxframework/redux-framework#2176]
Redux 3.4.4.8, WP 4.1.1

I am getting this error when trying to live preview my theme on a fresh site. I've increased the xdebug maximum_nesting value until 400, same error. Going above that returned a "server connection reset" error. This only happens when the options are not saved to db, activating the theme works. I'm concerned that it might cause the reviewers to reject my theme. I found 2 similar issues here, one still open but decided not to piggyback.

Here is part of the error:

```
 Fatal error: Maximum function nesting level of '400' reached, aborting! in E:\Dropbox\DEV\WP\wp-includes\cache.php on line 497
Call Stack
#	Time	Memory	Function	Location
1	0.0070	330152	{main}( )	..\customize.php:0
2	0.0100	397736	require_once( 'E:\Dropbox\DEV\WP\wp-admin\admin.php' )	..\customize.php:13
3	0.0110	415872	require_once( 'E:\Dropbox\DEV\WP\wp-load.php' )	..\admin.php:31
4	0.0120	432536	require_once( 'E:\Dropbox\DEV\WP\wp-config.php' )	..\wp-load.php:29
5	0.0250	530904	require_once( 'E:\Dropbox\DEV\WP\wp-settings.php' )	..\wp-config.php:99
6	0.3720	20439296	do_action( )	..\wp-settings.php:353
7	0.4030	20584512	call_user_func_array:{E:\Dropbox\DEV\WP\wp-includes\plugin.php:496} ( )	..\plugin.php:496
8	0.4030	20584800	TGM_Plugin_Activation->init( )	..\plugin.php:496
9	0.4030	20584880	do_action( )	..\class-tgm-plugin-activation.php:208
10	0.4030	20586312	call_user_func_array:{E:\Dropbox\DEV\WP\wp-includes\plugin.php:496} ( )	..\plugin.php:496
11	0.4030	20586512	mixt_register_plugins( )	..\plugin.php:496
12	0.4030	20586768	mixt_plugins( )	..\init.php:174
13	0.4410	22436928	require_once( 'E:\Dropbox\DEV\WP\wp-content\themes\mixt\framework\redux-config.php' )	..\init.php:92
14	0.4410	22437712	Redux_MIXT_config->__construct( )	..\redux-config.php:2308
15	0.4410	22437904	Redux_MIXT_config->initSettings( )	..\redux-config.php:31
16	0.4670	22816176	ReduxFramework->__construct( )	..\redux-config.php:69
17	0.5000	23153688	ReduxFramework->get_options( )	..\framework.php:320
18	0.5010	23153976	apply_filters( )	..\framework.php:826
19	0.5010	23155360	call_user_func_array:{E:\Dropbox\DEV\WP\wp-includes\plugin.php:213} ( )	..\plugin.php:213
20	0.5010	23155696	ReduxFramework_extension_customizer->_override_values( )	..\plugin.php:213
21	0.5010	23155696	ReduxFramework->get_options( )	..\extension_customizer.php:130
22	0.5010	23155968	apply_filters( )	..\framework.php:826
23	0.5010	23157192	call_user_func_array:{E:\Dropbox\DEV\WP\wp-includes\plugin.php:213} ( )	..\plugin.php:213
24	0.5010	23157224	ReduxFramework_extension_customizer->_override_values( )	..\plugin.php:213
25	0.5010	23157224	ReduxFramework->get_options( )	..\extension_customizer.php:130
```

The last 4 lines keep repeating until reaching the limit. I've tried turning the customizer off for all sections and then globally from the args, but no change.

**Comment by dovy** [comment]
Do this for me, update to the newest version of Redux found in this repo. Then go to the ~/wp-admin/tools.php?page=redux-support URL within your site. Click on Generate a Support Hash, then click I am a developer and give me the support URL please.

**Comment by dovy** [comment]
Do this for me, update to the newest version of Redux found in this repo. Then go to the ~/wp-admin/tools.php?page=redux-support URL within your site. Click on Generate a Support Hash, then click I am a developer and give me the support URL please.

**Comment by dovy** [comment]
Actually, just read about it here: http://docs.reduxframework.com/core/generating-a-support-hash/

**Comment by nova-ind** [comment]
Hmm, it says "There was an error. Please try again later". I deactivated my firewall and antivirus without result.

**Comment by dovy** [comment]
Shouldn't be. Could you please use chrome, click on the network tab, and tell me the error that's returned?

**Comment by dovy** [comment]
Ie, use a network inspector.

**Comment by dovy** [comment]
Skype? DovyDigital.

**Comment by nova-ind** [comment]
Sorry for the delay, I've added you on Skype

**Comment by dovy** [comment]
http://support.redux.io/?id=f2mM93eMUukn2z1CTEh5Q6ldGAhKFnGaf155jnR%2B87u80vSxhR09xUas%2Bc3dgRSIWICrUl8Dkzsk%2BH868SG8EQ%3D%3D

FYI @nova-ind, just tried Redux on the new WP beta. It's not in the core. It seems like something you're doing. I'll do my best to debug it soon after the 3.5 release.

**Comment by dovy** [comment]
Just tested you exact config without any problems. It's unfortunately somewhere in your theme. We can't dig into your code without Premium Support. Best of luck!

**Comment by nova-ind** [comment]
Normally, I would assume my theme is the cause as well, but this time it's definitely not the theme or even the config.
I've setup a new WP install, modified the TwentyFifteen theme to include Redux with the sample config and i get the same error when live previewing it. Again, once the theme is activated, switching to another theme and live previewing the one with Redux again, it works fine. It's something to do with the default options not being saved that causes this issue.
Please try this for yourself, just add the following to one of WP's themes functions.php
```
if ( ! class_exists( 'ReduxFramework' ) ) {
	require_once( get_template_directory() . '/plugins/redux/ReduxCore/framework.php' );
}
require_once( get_template_directory() . '/plugins/sample-config.php' );
```
and live preview it on a site where it's never been activated, I'm sure the error will rear its ugly head.

Please reopen the issue and i'll gladly do what i can on my end to help diagnose the cause, because every theme with Redux will get this error when previewing.

**Comment by dovy** [comment]
Ohhhhh. Live preview! Ok, on it!

**Comment by nova-ind** [comment]
Great, let me know if you need me to test anything on my environment!

**Comment by dovy** [comment]
Fixed and pushed.  :)
