### ISSUE TITLE
Multi Select Output

### ISSUE THREAD

**Issue by coleh33** [reduxframework/redux-framework#2177]
I'm not sure if this is something I am doing wrong or not but I am having an issue with outputting the multi-select options.  I am trying to use this to select categories to output in the main index loop.  

However, when just checking the echo output all that gets output is "Array" with nothing else after it.

    $fields = array(
      'id'       => 'trending-categories',
      'type'     => 'select',
      'multi'    => true,
      'title'    => __('Trending Categories', 'redux-framework-demo'), 
      'subtitle' => __('Select the categories to appear on the homepage.', 'redux-framework-demo'),
      'data' => 'categories',
    );

    <?php global $alpha_options; echo $alpha_options['trending-categories']; ?>

I can't seem to figure out why when multiple categories or even one are selected the output of the echo is just Array with nothing after it.  I am hoping to use this to alter the main query with select categories but can't work on the query until I can see the output of the data.  The server is running on PHP 5.5.

Thanks again for Redux!  It has been amazing to learn and implement.

**Comment by kprovance** [comment]
First, no redux version info was stated, per #1975.  Second, echo, on an array?  That should be giving you an error.

http://docs.reduxframework.com/core/fields/select/

I ran your code, bu instead did `print_r($alpha_options['trending-categories']);` and the result was (after choosing two categories at random): `Array ( [0] => 1 [1] => 5 )`.

**Comment by coleh33** [comment]
Thanks for the clarification. Sorry about that.  Will in future post version as well.
