### ISSUE TITLE
Deactivated-Reactivated Plugin, site won't load.

### ISSUE THREAD

**Issue by jpatrickm** [reduxframework/redux-framework#2178]
The plugin was installed by a previous developer and in the course of troubleshooting some other compatibility issues we deactivated redux-framework temporarily. We reactivated it and the site won't load - admin or live facing site. We renamed the plugin folder to get the site functioning again but would like to get this back operational. 

I'm not familiar with the plugin enough to fix so I'm hoping someone here can shed some light on this. I'm guessing maybe a config file got copies to the wrong place?  The formatting of individual blog posts are different now so I'm hoping these were being managed by the redux-framework plugin.

We are using Wordpress version 4.1.1. Redux-framework plugin version 3.4.1. It is an installed plugin - not embedded in other development code. 

I would greatly appreciate any input. 

~ Thanks

**Comment by kprovance** [comment]
#1975 states you need to have the latest version installed before we will offer support.  Please download the version from this repo and follow these instructions:  http://docs.reduxframework.com/core/generating-a-support-hash/

**Comment by jpatrickm** [comment]
I thought the version I had installed was the latest through the Plugins panel. I downloaded the most recent version from git and installed. Still unable to access the site once activated. I am unable to generate a support hash because once the plugin is active, the site goes down. No URL's function.

**Comment by dovy** [comment]
Very odd. This is not a typical occurrence. Can you contact the previous developer? Something is quite off here.

**Comment by dovy** [comment]
Very odd. This is not a typical occurrence. Can you contact the previous developer? Something is quite off here.

**Comment by dovy** [comment]
Very odd. This is not a typical occurrence. Can you contact the previous developer? Something is quite off here.

**Comment by jpatrickm** [comment]
Previous developer is no longer available.

**Comment by jpatrickm** [comment]
I tried restoring files from a previous backup but site still breaks. Are there settings stored in the database that could be corrupt?

**Comment by dovy** [comment]
It's really REALLY hard to say. Can you look at your error logs at all?

**Comment by jpatrickm** [comment]
The server error logs? I'm not sure I'd know where to begin as they are huge. We get a ton of traffic daily and logs are quite long. Unless there are other logs someplace else you are referring to.

**Comment by dovy** [comment]
I'd really love to help, but I have no idea what your previous developer did. It could be a permissions error, or a mistake in code that corrupted something as you say. The only way I'd know is to dig in and have WordPress and server access.

If you could find the error logs, we could help debug a bit more, without them we'd have to get access to your site and have you buy an hour or two of premium support. 

I really wish there was a quick answer here, but I have no idea what's going on. Activating/Deactivating our plugin shouldn't cause a concern. It's how the framework was used.

Best of luck!

**Comment by jpatrickm** [comment]
Ok thanks for your input. Deactivating and activating the plugin was literally all we did. Site has been functioning fine for several months. It was fully functioning one minute, down the next. Renaming that plugin folder brought the site back up again.

**Comment by dovy** [comment]
It's so odd. We produce the tools, but developers harness them. Heh. No idea what they may have done. Good luck!

**Comment by jpatrickm** [comment]
Ok so how do we remove this garbage from our database?

**Comment by dovy** [comment]
How flippant of you...

Ask your former developer? They set a global option name and I have no idea what that may be...

I can't just take my time to support what your former dev did. I don't actually work for you.

That being said, we'll be happy to help, you just have to support us for taking the time.  :)

**Comment by jpatrickm** [comment]
Flippant of me?! Just saying "Good luck" isn't good support. Completely removing your plugin, then installing a fresh version and activating it takes our site down. How is that the previous developers fault? Paying for support isn't the problem. Actually wanting to pay or believing in your product or that I'll actually get good support beyond that is another thing entirely.

**Comment by kprovance** [comment]
If you would acquiesce and actually peruse your php error log, chances are the clues to the issue are there.  But you don't want to.  How is that our fault?  That's where the support process would have begun.  You declines.  We're done, unless you're paying for premium support, in which case we'll download youor product and review it.  That's how it works.  Supply and demand.

**Comment by dovy** [comment]
We're an open source project, not a commercial product you've purchased.

Please understand.

**Comment by jpatrickm** [comment]
I understand open source and paid support. What I don't understand your attitude. I see why another reviewer stated "They want to sell premium support, but they're attitude is condescending and immature." Why would I pay for this type of relationship?

Oh well, moving on... as you would say "Good luck!"

**Comment by dovy** [comment]
Thank you!

**Comment by kprovance** [comment]
Maybe it's just me, but I have just a bit of trouble taking something someone said with the handle of 'stickypod' seriously.  ;-)
