### ISSUE TITLE
Adding your link to the Tools menu freaked out multiple customers

### ISSUE THREAD

**Issue by zackkatz** [reduxframework/redux-framework#2179]
In Version 1.4, Redux Framework links were added to Tools menu. I'm not pleased that:

1. The link was added without it being explicitly enabled in settings
2. That there was no filter to allow easily turning off the link

My customers don't care what settings framework I use. Redux should get out of the way, not insert itself into sites in a sneaky (yes, sneaky) way.

I'm switching to using my own custom-rolled settings page because of this. I'm only posting this so that you all understand that it was not cool.

**Comment by dovy** [comment]
@zackkatz, first Redux is at 3.4.4.9+... not 1.4. I think you have your versions wrong.

Second, it's nothing forced or sneaky. If dev_mode is enabled, or if the plugin is installed, users will be redirected on major releases to see what's new. If not, it just sits there. Why are you so concerned that your users would know you base your products off of Redux Framework?

Also we're trying to reduce the support requests we get from developer's users. Please check out the support and status page so see that. That's useful information you can request from your users to find out about their environment for debugging.

I'm sorry if you find us trying to improve the user experience "sneaky".  I wish you the best of luck and let us know what you come up with. We'd love to see it. I always love new ideas.

**Comment by zackkatz** [comment]
I find adding a menu item (outside of the footer credits on the settings page) to be beyond what is required for Redux to function. 

Not providing a setting, like you do for the footer text, leads me to believe this was forced on people, unlike other Redux branding. That's why I called it sneaky. It fails the smell test.

I question your judgement of user experience, and that is why I felt the need to post about the issue.

**Comment by dovy** [comment]
You're entitled to your opinion. My opinion is you don't want your users to know that you're using Redux. ;)

And I'm not sure if you've used many WordPress plugins/frameworks out there. I could have just forced a top level link rather than use the least used menu in WordPress like I did. 

I have learned one thing with Redux, I can't please everyone. :(

Best of luck on your own version.
