### ISSUE TITLE
stripslashes in ace_editor

### ISSUE THREAD

**Issue by ghostpool** [reduxframework/redux-framework#2181]
Redux v3.4.4.9.1
WordPress 4.1.1
Integrated

Hey guys,

Great to see that the backslashes are now being stripped from text boxes however this causes a small issue when using the ace_editor for CSS code. CSS uses backslashes for unicode characters and it's removing these from the CSS. Any way around this?

**Comment by dovy** [comment]
Example please.

**Comment by ghostpool** [comment]
Here you go:

	.follow-item:after {
	content: '\f067';
	font-family: 'FontAwesome';
	margin-left: 5px;
	}

**Comment by dovy** [comment]
I literally had to do a version compare for anything less than PHP 5.4 because they changed how strip_slashes worked. Sheesh. Resolved in 3.4.4.9.4.

**Comment by ghostpool** [comment]
I'm not sure if you understood what I meant Dovy. Backslashes are needed in ace_editor in CSS mode. I've upgraded to 3.5.0 and the backslashes are still removed from "content: '\f067';"

**Comment by dovy** [comment]
What version of php? I tested it extensively in my environment.

**Comment by ghostpool** [comment]
I'm using PHP version 5.3.2.

**Comment by dovy** [comment]
Local or live? Magic_quotes or no?

**Comment by dovy** [comment]
I'll help, I just need you to help me help you.  :P

**Comment by kprovance** [comment]
I did some quickie research on magic quotes, and it *could* be the issue.  It was depreciated with 5.3 and done away with completely 5.4 and on (which I use, so I can't test).  Here are instructions for disabling.  Take a look at them and check for us, to ensure that feature is off.  http://php.net/manual/en/security.magicquotes.disabling.php

**Comment by ghostpool** [comment]
This is a live environment and magic_quote_gpc is off.

**Comment by dovy** [comment]
That's what I need. I'm on it.

**Comment by dovy** [comment]
Actually, ghostpool, can you go to the support tab in Tools -> ReduxFramework, generate a support URL and provide it here?

**Comment by dovy** [comment]
Scratch that. Pull from the repo and verify. I'm pretty sure I just resolved the issue for good.

**Comment by dovy** [comment]
And please check box the textarea issues as well as the ace_editor issues that you previously reported. It's working fine for me in all cases, but I want to verify on your end.

**Comment by ghostpool** [comment]
Backslashes are no longer removed from the ace_editor which is great. Thanks Dovy.

Backslashes are also not removed from textareas - was this intended? It's fine for me because backslashes are not added to textareas automatically (was only a problem for my PHP 5.2 users), it just doesn't remove the one's I manually add.

**Comment by dovy** [comment]
So php 5.2 has an issue now? Textareas should work the same as the ace editor. If you leave a slash it should remain unless you are using a validation. Can you confirm that is how it works or not?

**Comment by ghostpool** [comment]
No it doesn't - not that I'm aware. I was just saying that I'm not able to see if backslashes are working correctly in textarea and ace_editor fields on PHP 5.2 as I am using PHP 5.3. Both the textareas and ace_editor fields working correctly for me on 5.3. Thanks Dovy.

**Comment by kprovance** [comment]
If you like Redux, or the support we render, please do one or all of the following:
* Donate to keep us going: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=MMFMHWUPKHKPW
* Review us: http://wordpress.org/support/view/plugin-reviews/redux-framework
* Like us: http://facebook.com/ReduxFramework
* Follow us: http://twitter.com/ReduxFramework
