### ISSUE TITLE
Bottom argument in border field!!

### ISSUE THREAD

**Issue by ZoOmArts** [reduxframework/redux-framework#2183]
Hey There,

I have found issue in border field, in this case the bottom border width will appear on theme-options!!
I want only to show the color, but it doesn't work!!

array(
'id' => 'my-border',
'type' => 'border',
'title' => __('My Border', MY_THEME_NAME),
'all' => false,
'style' => false,
'left' => false,
'right' => false,
'top' => false,
'botttom' => false,
'output' => array('.my-elem'),
),
![](https://cloud.githubusercontent.com/assets/11763471/6955934/d002a826-d8e5-11e4-912b-70bc90a23b2d.png)

Thanks!

**Comment by kprovance** [comment]
While it might be an issue (I can;t look into it today), using the border field to set a border color is *overkill*.  The same thing is more easily accomplished using the color field and outputting the CSS is the exact same way you have here.

http://docs.reduxframework.com/core/fields/color/

For your `output` argument, set it as `'output' => array ('border-bottom' => '.my-elem')` (this cool trick only works on the color fields)  http://docs.reduxframework.com/core/the-basics/output-2/

**Comment by ZoOmArts** [comment]
Great!!
Thanks Mr.Kevin

**Comment by kprovance** [comment]
Actually, I see the issue should you still want to do it your way.  The word 'botttom' is misspelled.   ;-)

**Comment by ZoOmArts** [comment]
I'm really sorry for that :smile: it's my fault and thanks again.

**Comment by kprovance** [comment]
Not to worry, it happens quite frequently.  To err is human.  ;-)
