### ISSUE TITLE
Redux Builder not working

### ISSUE THREAD

**Issue by cmwwebfx** [reduxframework/redux-framework#2185]
Hi,

When I log into my Redux account and go visit redux builder I am finding it does not reset at all.

There is a notice in the builder that the Redux is outdated, however it has the latest version selected in the dropdown.

http://build.reduxframework.com/

![redux builder not resetting](https://cloud.githubusercontent.com/assets/1312880/6961393/1ed30a7c-d972-11e4-932c-87dbb63534d4.jpg)

![redux using latest dev branch and displaying old version](https://cloud.githubusercontent.com/assets/1312880/6961394/2136dd48-d972-11e4-9284-c59cbfde44f2.jpg)

**Comment by dovy** [comment]
Fixed. 

I thought you had moved on. ;)

**Comment by cmwwebfx** [comment]
I have a product that I built on the framework, so needed updating.
Also notice the changelog in github does not reflect the latest version

**Comment by cmwwebfx** [comment]
Scratch that, changelog reflects fine. Read the ver. numbers wrong.

**Comment by dovy** [comment]
;)
