### ISSUE TITLE
Function $redux_demo to get the options value is not working perfectly

### ISSUE THREAD

**Issue by dewaadiperdana** [reduxframework/redux-framework#2187]
When i try to get the option value in my theme and i put the option value on the .sidebar area, everything in the .sidebar area are gone and i got the message were it says "Fatal error: Function name must be a string in C:\xampp\htdocs\redux\wp-content\themes\twenty fifteen\header.php on line 33" maybe anyone can help me to figure this out...?

**Comment by kprovance** [comment]
This is not a Redux issue.  That error means you've probably put a $ in front of a function name.

**Comment by dewaadiperdana** [comment]
So, what should i put in front of a function name...?, please help me out!

**Comment by dovy** [comment]
@dewaadiperdana I really am sorry. I want to help, but we can't help you learn PHP. A better source for that is http://php.net.

Just know the opt_name is usually what your global variable is called. You need to declare it global or use: $GLOBALS['OPT_NAME'] replacing your opt_name.

If you need more help than that, I fear you need to study up elsewhere. Best of luck though. We all start somewhere!
