### ISSUE TITLE
Use of undefined constant AUTH_KEY & SECURE_AUTH_KEY

### ISSUE THREAD

**Issue by craiglondon** [reduxframework/redux-framework#2188]
Enviroment: Windows 8.1
XAMPP
Wordpress v4.11
Redux v3.50

```
Notice: Use of undefined constant AUTH_KEY - assumed 'AUTH_KEY' in C:\xampp\htdocs\wordpress\wp-content\plugins\redux-framework\ReduxCore\inc\class.redux_instances.php on line 67

Notice: Use of undefined constant SECURE_AUTH_KEY - assumed 'SECURE_AUTH_KEY' in C:\xampp\htdocs\wordpress\wp-content\plugins\redux-framework\ReduxCore\inc\class.redux_instances.php on line 67
```

**Comment by dovy** [comment]
Very odd. Did you not create the wp salt and do a normal wp install? That should be in everyone's config file. Part of wp security.

**Comment by dovy** [comment]
From the default wp config:
`php
/**#@+
 * Authentication Unique Keys and Salts.
 *
 * Change these to different unique phrases!
 * You can generate these using the {@link https://api.wordpress.org/secret-key/1.1/salt/ WordPress.org secret-key service}
 * You can change these at any point in time to invalidate all existing cookies. This will force all users to have to log in again.
 *
 * @since 2.6.0
 */
`
I really think this needs to be in your config. I doubt any LIVE instance wouldn't have that.

**Comment by craiglondon** [comment]
Thank you!  I was following this post for local development and I had my salts in the condition for production server, I moved it outside the statement for dev/prod and I don't get that error.  I appreciate you taking the time to respond!

http://efeqdev.com/website-development/this-is-how-we-version-control-and-deploy-our-wordpress-websites-with-git/

```
if ($_SERVER['REMOTE_ADDR']=='127.0.0.1') {
    define('WP_ENV', 'dev');
} else {
    define('WP_ENV', 'prod');
}

if (WP_ENV == 'dev') {
    define('WP_SITEURL', 'http://' . $_SERVER['SERVER_NAME'] . ':' . $_SERVER['SERVER_PORT'] . '/wordpress');
    define('WP_HOME',    'http://' . $_SERVER['SERVER_NAME'] . ':' . $_SERVER['SERVER_PORT']);
    define('WP_CONTENT_DIR', $_SERVER['DOCUMENT_ROOT'] . '/wp-content');
    define('WP_CONTENT_URL', 'http://' . $_SERVER['SERVER_NAME'] . ':' . $_SERVER['SERVER_PORT'] . '/wp-content');

    define('DB_NAME', 'efeqdev-dev');
    define('DB_USER', 'root');
    define('DB_PASSWORD', 'root');
    define('DB_HOST', 'localhost');
} else {
    define('WP_SITEURL', 'http://' . $_SERVER['SERVER_NAME'] . '/wordpress');
    define('WP_HOME',    'http://' . $_SERVER['SERVER_NAME']);
    define('WP_CONTENT_DIR', $_SERVER['DOCUMENT_ROOT'] . '/wp-content');
    define('WP_CONTENT_URL', 'http://' . $_SERVER['SERVER_NAME'] . '/wp-content');

    define('DB_NAME', 'efeqdev-prod');
    define('DB_USER', 'username');
    define('DB_PASSWORD', 'password');
    define('DB_HOST', 'mysql.efeqdev.com');
} 
```

**Comment by dovy** [comment]
Whew. Glad you got that sorted! That could have been a problem, hah.

Best of luck to you!

If you like Redux, or the support we render, please do one or all of the following:
Donate to keep us going: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=MMFMHWUPKHKPW
Review us: http://wordpress.org/support/view/plugin-reviews/redux-framework
Like us: http://facebook.com/ReduxFramework
Follow us: http://twitter.com/ReduxFramework

**Comment by jb510** [comment]
Same issue...  same situation (local dev).  

I added salts to my local config and it went away, but would it not be better inside Redux to check defined('AUTH_KEY') ?  avoid this ever happening?

**Comment by Krasheninin** [comment]
Have the same problem with Redux....

**Comment by dovy** [comment]
I should add a check, but usually this is defined by the default WP install. Whatever local env you're using is disregarding the standard process set by WordPress. *sigh*

**Comment by Krasheninin** [comment]
I generate new security keys and put their in wp-config.sys But problem not fixed...

**Comment by dovy** [comment]
Ohhhh. These are PHP 7.X warnings, not actual errors... Got it.

**Comment by dovy** [comment]
Use the master branch from this repo to install Redux. If it works, I'll push out to the rest of the world.  ;)

**Comment by dovy** [comment]
IE, I think I fixed it.  ;)

**Comment by Krasheninin** [comment]
n fact, these bugs in no way affect the operation of my site. I'll try to reinstall Redux again through the Wordpress plugin panel. If it doesn't help - I'll closed my eyes for those mistakes.

**Comment by dovy** [comment]
@Krasheninin Please just try the new version of the plugin I just did. I worked to solve it.

Use this instead of the WP.org version: https://github.com/reduxframework/redux-framework/archive/master.zip

**Comment by Krasheninin** [comment]
Thanks! I did as you said - downloaded zip and installed again. After i will look in logs, if there will be any errors.

**Comment by Krasheninin** [comment]
Problem solved! logs are clean. Thank you again!

**Comment by dovy** [comment]
Just pushed to WP.org. Thanks for testing!
