### ISSUE TITLE
Slider with suggested step

### ISSUE THREAD

**Issue by No3x** [reduxframework/redux-framework#2189]
Hi there, 
this is no bug but an feature request
```
Redux-Framework Version: 3.5.0
Using Redux as: Plugin
Wordpress Version: 4.1
'dev_mode' => true,
Browser console errors: None
```
I would like to use a slider like this:
Type in 4 instead using a specific value from the slider
![bildschirmfoto 2015-04-02 um 15 59 58](https://cloud.githubusercontent.com/assets/2690708/6965389/6185dfaa-d951-11e4-809f-03777143e006.png)
But when leaving the field it snaps to a 7 step again:
![bildschirmfoto 2015-04-02 um 16 00 10](https://cloud.githubusercontent.com/assets/2690708/6965388/61811f74-d951-11e4-87ae-8f03bd8dc0d9.png)
So the stepper should use the steps as assistance for selection (if defined by a setting of the slider) and use the typed in value 4 instead.
```
array(
'id'            => 'log-rotation-delete-time-days',
'type'          => 'slider',
'required'  	=> array('log-rotation-delete-time', '=', '1'),
'title'         => __('Time', 'wpml' ),
'subtitle'      => __('When should mails are deleted?', 'wpml'),
'desc'      	=> __('Delete mails older than days...', 'wpml'),
'default'       => 30,
'min'           => 1,
'step'          => 7,
'max'           => 400,
'display_value' => 'text'
),
```
Do you know a workaround for this?
I also can't get 7-14-21-.. steps working used for periods.
![bildschirmfoto 2015-04-02 um 16 15 03](https://cloud.githubusercontent.com/assets/2690708/6965633/771c1c6a-d953-11e4-9fa5-23e9f9fb4c01.png)

**Comment by dovy** [comment]
So what you're saying is you want steps by 7, but you don't want the min value to count as part of those. IE, 1, 7, 14 instead of 1, 8, 15. Correct?

Or are you asking for something else?

**Comment by No3x** [comment]
> So what you're saying is you want steps by 7, but you don't want the min value to count as part of those. IE, 1, 7, 14 instead of 1, 8, 15. Correct?

Yes, thats the essence from

> I also can't get 7-14-21-.. steps working used for periods.

The stuff above (the more important) is about that you can't use the input field apart from the 'step' value. If the step value is 7 you can't type in 4.
The use case is: 
1. Some users want to set periods of 1, 7, 14 (they use the stepper) 
2. others use the stepper first and decide after a while.. it would be good to decrease/increase the value by one - so they would type this into the input next to the stepper - click save - but the value cant be used since it snaps to the next 7-step.

**Comment by dovy** [comment]
Ahhhh, so the non-forced step would be an easy fix. I could add that in seconds.

The other one is more... painful. Does it really make sense? I'm trying to find a way to do it along with the other way.

Can you suggest how we could do both?

**Comment by No3x** [comment]
In my case it is not important that the user leaves the defined 'step' values, since it adjust the days after mails are deleted. 

There are other use cases the step value must be ensured. - At the moment the slider is made for this one.

There must be an option to switch between one of them.
Is it possible to get the input value and the stepper value via an hook? I was not able to do so with 3.3.x .. But the correction of the input value and the step is done via JS before.. Can't we just disable this JS correction when the slider has an option x set?

**Comment by kprovance** [comment]
I played with this for a bit.  What you want to accomplish isn't possible through Redux.  The 'disabling of the correction' would have to happen in the vendor code.  IOW, there is no quick and dirty way to accomplish this.  Sorry.
