### ISSUE TITLE
Redux Framework Question - Updating Field ID's

### ISSUE THREAD

**Issue by Es0teric** [reduxframework/redux-framework#2192]
Redux-Framework Version: 3.3.5.1
Using Redux as: Plugin
Wordpress Version: 4.1
dev_mode => true,
Browser console errors: None

Hi, my question is how do I dynamically update a field? For instance I am connecting to an API and I want to dynamically save items to field id's that already exist based off the values that are returned from the API. This would be happening in a functions.php file that resides in a child theme

**Comment by dovy** [comment]
You grab your options via get_option("opt_name") and change the key within then update_option("opt_name"). ;)

**Comment by Es0teric** [comment]
ah i see now, thanks!

**Comment by dovy** [comment]
:+1: 

If you like Redux, or the support we render, please do one or all of the following:
* Donate to keep us going: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=MMFMHWUPKHKPW
* Review us: http://wordpress.org/support/view/plugin-reviews/redux-framework
* Like us: http://facebook.com/ReduxFramework
* Follow us: http://twitter.com/ReduxFramework
