### ISSUE TITLE
Detecting development version

### ISSUE THREAD

**Issue by szepeviktor** [reduxframework/redux-framework#2194]
Please consider looking at `WP_DEBUG` in `isLocalHost()`.
I think it is not obvious to have `127.0.0.1`. For example I develop on a remote development server.

**Comment by dovy** [comment]
This shouldn't affect you at all... What is the problem? Do you not have WP_DEBUG set?

**Comment by szepeviktor** [comment]
I suggest to detect it ina WordPress way.

**Comment by szepeviktor** [comment]
If I don't develop on localhost that function will fail.

**Comment by kprovance** [comment]
Fail how?  Return false?  An actual error?  This isn;t about WP_DEBUG, it's about those blasts appearing for those devs who think setting dev_mode to false will shut them off, while ensuring their clients do not see them.  Checking for WP_DEBUG negates that, especially if they aren't using it.

**Comment by szepeviktor** [comment]
Excuse me. I didn't know about those divers users of yours.

**Comment by szepeviktor** [comment]
As I see it - modifying your code because those users lowers code quality.
But I know you have to solve your users' problems.

**Comment by dovy** [comment]
Indeed we do. It's regrettable. Best of luck!
