### ISSUE TITLE
I have some errors by themecheck plugin

### ISSUE THREAD

**Issue by ZoOmArts** [reduxframework/redux-framework#2195]
Hi there,

When i check my theme with "ThemeCheck" plugin i have found some warnings, Is this normal or there something I've missed?

![screenshot-zoomarts works 2015-04-04 05-29-21](https://cloud.githubusercontent.com/assets/11763471/6991306/8016e41e-da8c-11e4-9151-18402a38fe27.png)

Thanks!

**Comment by kprovance** [comment]
That makepot stuff isn't ours.  Can't help you with those.  The parsedown.php is a false flag.  It's mistaking a regex statement for a shorttag.  The scss is a vendor file that has nothing to do with WP or your theme code.  It should be excused.
