### ISSUE TITLE
Ajax unable to save when field type 'editor' is present

### ISSUE THREAD

**Issue by JayCarr91** [reduxframework/redux-framework#2196]
Tested barebone & sample configuration files and both fail to save unless I comment out 'editor' type field.

**Comment by kprovance** [comment]
Please go to the support tab in Tools -> ReduxFramework, generate a support URL and provide it here.

**Comment by JayCarr91** [comment]
Turns out this only occurs when running on localhost. I uploaded the updated file to a live server and it worked flawlessly.

Weird
localhost: Redux Framework -> System Status *passes on everything*
live server: Redux Framework -> System Status *passes on everything*
