### ISSUE TITLE
Import Options doesen't work

### ISSUE THREAD

**Issue by easymoneysniper** [reduxframework/redux-framework#2198]
Hello guys. I am working on a theme and I am having a trouble with import options. I have two exactly the same installations of wordpress and redux but everytime i try to import theme options from one site to another i get nothing.. It is like options doesen't even save in database but notifications says it does. Help me guys!

Wordpress Version - 4.1.1
Redux Version - 3.4.3.4
No javascript errors in a console.
Host - BlueHost.

PS. Opt_name is the same on both installations. It is a same theme and everything.

**Comment by dovy** [comment]
Please update to 3.5.0 and try again.

**Comment by paulthecoder** [comment]
Updating to 3.5.0 does the trick.

**Comment by easymoneysniper** [comment]
Just so you know.. IT WORKS NOW!! Thank you very much guys, you are my superheroes !

**Comment by kprovance** [comment]
:+1:

If you like Redux, or the support we render, please do one or all of the following:

    Donate to keep us going: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=MMFMHWUPKHKPW
    Review us: http://wordpress.org/support/view/plugin-reviews/redux-framework
    Like us: http://facebook.com/ReduxFramework
    Follow us: http://twitter.com/ReduxFramework
