### ISSUE TITLE
One stupid q

### ISSUE THREAD

**Issue by mkdizajn** [reduxframework/redux-framework#2199]
Hi guys, 

I'm having one not redux related issue but php related one .. here, take a look. everytime I write some plugin I keep ending with this coding practice ..

```php
<?
if ( ! class_exists( 'classname' ) ) {
    class classname {
        public function __construct() {
            require_once dirname( __FILE__ ) . '/admin/admin-init.php' ;
            add_action( 'hook1' , array( $this, 'method1') );
            add_action( 'hook2' , array( $this, 'method2') );
        }
        public function method1(){
		    global $redux_opt_name;
		    // other logic
		}
        public function method2(){
		    global $redux_opt_name; 
		    // other logic
		}
	}
}

```

Hope that you can see this repetative little thing that drives me nuts and it's defining again and again global $redux_opt_name for each function in my class..  

I'm clueless, don't know how to define it in _constructor or else so that I can remove that first lines from my plugin.. would save like 50 of them for sure :)

thanks,, :)

**Comment by kprovance** [comment]
Whether you set a public variable in construct or use the global statement, that's just how PHP works.  Unfortunately, we don;t have the time or resource to be PHP tutors for everyone.  You're best bet is to dig into http://php.net/ or google php tutorials.

**Comment by dovy** [comment]
Or use $GLOBALS["opt_name"] instead as your variable. No need to declare global then. ;)

**Comment by mkdizajn** [comment]
Yes @dovy that works great, thanks! In the meantime I found great post from citizens on SO here and applied it here: 

http://stackoverflow.com/questions/4489134/php-class-global-variable-as-property-in-class

and this code now works also for me,, I altered it to something like this.. 

```php
<?
if ( ! class_exists( 'classname' ) ) {
    class classname {
        protected $my;
        public function __construct() {
            require_once dirname( __FILE__ ) . '/admin/admin-init.php' ;
            add_action( 'hook1' , array( $this, 'method1') );
            add_action( 'hook2' , array( $this, 'method2') );
            global $redux_opt_name;
            $this->my = &$redux_opt_name;
        }
        public function method1(){
            echo $this->my;
            // other logic
        }
        public function method2(){
            global $redux_opt_name; 
            echo $redux_opt_name;
            // other logic
        }
    }
}
```

method1 & method2 now returns same value, but first one is one line smaller :) cheers

hope to help someone if
