### ISSUE TITLE
Redux Guidelines?

### ISSUE THREAD

**Issue by dodzki** [reduxframework/redux-framework#22]
The framework is nice. Been checking the functionality in the admin side and it looks great same as HNP Framework that I'm using. The problem with this, there's no guide on how to use in front-end. Guidelines on how to use it in front-end should be implemented. Like, how to use the radio option, multi-check, upload, fonts and especially with if else state.

What's nice if there's an if else statement guide; is to display the field entry if there is an entry, and if it's empy, it should not display or else, display another content as default.

Not all front-end developer is good in PHP like me. Hope this will be implemented like what Advanced Custom Fields doing. Lots of sample guidelines for front-end development. Thanks for the framework. Good job.

**Comment by TusarNill** [comment]
Please help, Before of Redux Framework 
'opt_name' => 'demo' from here get the text into footer.php  <?php global $demo; echo $demo['id'] ?>
But in update of Redux Framework
 'opt_name' => $opt_name   <---- how can i get the output text into my footer.php

**Comment by dovy** [comment]
@TusarNill Don't piggyback OLD tickets, make new ones.

Find where $opt_name is defined in the sample-config and update it.  ;)
