### ISSUE TITLE
Issue with translation

### ISSUE THREAD

**Issue by allazim** [reduxframework/redux-framework#2200]
First i want to say thank you very very much for the awesome and great plugin you create.
I am working on a commercial plugin and i integrated redux in it and use it as my option panel, i am almost done with the plugin, i started to translate the plugin but the translation doesnot work, i do all things correctly in my plugins function.php and still not want to work
i add this to my plugin functions 
load_plugin_textdomain('my_plugin_name', false, basename( dirname( __FILE__ ) ) . '/languages' );
and make all strings translatable but it does not work

**Comment by dovy** [comment]
Run that command before you load Redux and all should work. ;)

**Comment by allazim** [comment]
I try this already but it does not work, only work as i remove the whole redux

**Comment by dovy** [comment]
You're probably putting a hook on the loading of your load_text_domain. Remove the hook and it will work.

**Comment by allazim** [comment]
This is what i add before calling redux 

load_plugin_textdomain('pxd-opt-sab', false, basename( dirname( __FILE__ ) ) . '/languages' );

**Comment by dovy** [comment]
Are you trying to bypass Redux translations (ie the UI), or field translations (IE your field titles/subtitles)? I don't know what to tell you, but it works for hundreds of thousands of developers out there. It's something somewhere in your configuration.  :(

**Comment by allazim** [comment]
yes. I m trying to translate fields of redux and also translate the whole plugin. and even if I regenerate a new po files it does not work

**Comment by dovy** [comment]
Fields you can do easily. Translating the full plugin will require a lot more. Why not instead help the translation of Redux found here so others can befit: https://www.transifex.com/projects/p/redux-framework/
