### ISSUE TITLE
Getting error message when trying to save options

### ISSUE THREAD

**Issue by PulsarMedia** [reduxframework/redux-framework#2202]
Hi,

I am experiencing a strange issue. For some reason when i try to save my options on my development server i get the following error message:

"There was a problem with your action. Please try again or reload the page"

I tried reloading the page several times, as the message suggested, but i keep getting the same error. It also seems that some of my settings do get saved and some do not.

Here are my server specs:

1. Master build v3.5.0.2
2. WordPress version 4.1.1
3. Redux is not in dev_mode
4. Plugin is embedded
5. No javascript errors in console

Any help is appreciated, thanks.

**Comment by kprovance** [comment]
There should be text in the console on this error.  That's how it was coded.  We'd need to see that.

Alternatively:  http://docs.reduxframework.com/core/generating-a-support-hash/

**Comment by PulsarMedia** [comment]
I tried generating a support hash URL through the WordPress admin (Tools -> Redux Framework -> Support Tab) but i get the following error when i click on Generate a Support URL:

"There was an error. Please try again later."

Anyways, i looked in my FireBug console and now i see that is an error occuring:

<b>Warning</b>:  parse_str(): Input variables exceeded 1000. To increase the limit change max_input_vars in php.ini. in <b>/home/pulsarme/wp/energytest/wp-content/themes/energy-theme/ReduxFramework/ReduxCore/framework.php</b> on line <b>2698</b>

I will increase the limit and see if it fixes the issue...i will keep you posted.

**Comment by PulsarMedia** [comment]
I increased the variable on my server and it looks like the error is gone and my options are now saving.

You might want to look into the "Generate a Support URL" error though...im still getting that.

Regards.

**Comment by dovy** [comment]
It means your panel is quite large or you have multiple panels running. Provide the support URL and I will duplicate the setup and see if I can recreate and find a solution.  ;)

**Comment by PulsarMedia** [comment]
I cant do it from the Wordpress admin so try this: http://wp.pulsarmedia.ca/energytest/wp-admin/tools.php?page=redux-support

Thanks.

**Comment by kprovance** [comment]
login credentials required.

**Comment by dovy** [comment]
email: support@reduxframework.com

**Comment by PulsarMedia** [comment]
Just sent you an email, thanks.

**Comment by kprovance** [comment]
Issue resolved via email

If you like Redux, or the support we render, please do one or all of the following:
* Donate to keep us going: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=MMFMHWUPKHKPW
* Review us: http://wordpress.org/support/view/plugin-reviews/redux-framework
* Like us: http://facebook.com/ReduxFramework
* Follow us: http://twitter.com/ReduxFramework

**Comment by marcodedo** [comment]
I have the exact same error. How can I fix?

**Comment by dovy** [comment]
@marcodedo please open a new ticket and do this: http://docs.reduxframework.com/core/generating-a-support-hash/

**Comment by KevinBatdorf** [comment]
Great that you solved the problem via email, but putting the resolution here would save the rest of us time and resources.

**Comment by dovy** [comment]
It's usually because you're outputting some data and the string gets returned improperly. Please post a new issue though. But I'd suggest you check the response on the ajax_save post to see if perhaps you're adding some extra stuff there that's causing the issue.

**Comment by kaeons** [comment]
Try this solution:

/wp-content/plugins/redux-framework/ReduxCore/framework.php

there you find such option
$args = array_merge( array( $current_user ), func_get_args() );

change it to
$name_arr=func_get_args();
$args = array_merge( array( $current_user ),$name_arr );

That's php version. ;)

**Comment by thiru-ikomet** [comment]
Hi,
I use Avada theme, I need to add extra options in theme options. Any possibility in there?

Thanks,
Thiru

**Comment by dovy** [comment]
@thiru-ikomet please don't highjack threads. Start your own.
