### ISSUE TITLE
Is there a way to opt out of AJAX Save?

### ISSUE THREAD

**Issue by ahmadawais** [reduxframework/redux-framework#2203]
Hey Dovy,
I am reviewing the code of Redux 3.5.0 and while new AJAX save is cool, I have some functionality in my themes which needs a page load. I looked through the sample-config.php file and there is no option where I could just put false to the AJAX save and use the older page-loading save version.

I did find this in framework.php

```
 'ajax_save'                 => true,
```
Setting it to false doesn't work. 
Can you add this setting to option-init.php so that we can disable the AJAX save and still use the latest version of Redux?

Or am I missing something?

**Comment by ahmadawais** [comment]
Actually inside framework.php when I changed 
```
'ajax_save'                 => true,
```

to 

```
'ajax_save'                 => false,
```

It does deactivate the AJAX saving. But I am wondering if it could be possible to add it inside option-init.php config file so that the plugin should not override it.

**Comment by ahmadawais** [comment]
As a matter of fact I went ahead and added 

```
'ajax_save'                 => false, // disabled the AJAX save
```
to the options-init.php and it did work.

Thanks. Closing it down.

**Comment by dovy** [comment]
You got it!

Any reason for the disabling of ajax_save?

**Comment by ahmadawais** [comment]
I am using some actions/filter on save button which only seem to work when complete page is loaded. I need to figure out how to manage them with AJAX save. Until then I have disabled it. Nothing relevant to Redux :)
