### ISSUE TITLE
Override option value depending on URL parameter

### ISSUE THREAD

**Issue by sodbileg** [reduxframework/redux-framework#2204]
Hi, I am just wondering that if it is possible to override option value depending on URL parameter.

For example,
`$admin_options['main_layout']`'s default value is `standard`. And then if URL is `http://...URL.../?layout=grid`, `$admin_options['main_layout']`'s value is `grid` even the value stored in DB is `standard`. Is it possible?

**Comment by dovy** [comment]
Everything is possible.  ;)

You can modify the global variable this way:
`$GLOBALS[ $this->args['global_variable'] ] = apply_filters( "redux/options/{$this->args['opt_name']}/global_variable", $this->options );`

That's in the core. So you can modify via the URL by hooking into that filter. Make sense?

**Comment by sodbileg** [comment]
Hi @dovy, I'm not sure that I got it. Do I have to modify it in my config file?

**Comment by sodbileg** [comment]
W00t? I didn't know it was possible. It solved my problem. https://github.com/reduxframework/redux-framework/wiki/Update-an-option-outside-the-options-panel
