### ISSUE TITLE
Sortable checkbox fields showing key names, not value

### ISSUE THREAD

**Issue by xconsau** [reduxframework/redux-framework#2205]
As of version 3.5 of plugin, the sortable checkbox fields are not displaying label names. They show key names. For example, the following code:

<pre>'id'       => 'id-name',
'type'     => 'sortable',
'mode'     => 'checkbox',
'options'  => array(
    '1' => 'Item 1',
    '2' => 'Item 2',
    '3' => 'Item 3',
    '4' => 'Item 4',
)</pre>
outputs 1, 2, 3 and 4 inside Option Panel and not the label names. The 'mode' => 'text' is working correctly.

Ref: https://wordpress.org/support/topic/sortable-checkbox-fields-showing-key-names-not-value

**Comment by kprovance** [comment]
Please update to the version of Redux from this repo.  it has been resolved, per the changelog.md

**Comment by xconsau** [comment]
Thank you. It works great. Appreciate your time.

**Comment by dovy** [comment]
If you like Redux, or the support we render, please do one or all of the following:
* Donate to keep us going: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=MMFMHWUPKHKPW
* Review us: http://wordpress.org/support/view/plugin-reviews/redux-framework
* Like us: http://facebook.com/ReduxFramework
* Follow us: http://twitter.com/ReduxFramework
