### ISSUE TITLE
Don't save changes!!!

### ISSUE THREAD

**Issue by pooyaa** [reduxframework/redux-framework#2206]
Hi there
I want create for demo site.
Is it possible that the user can not save the changes? Just visible.

I am using the latest version. Thanks.

**Comment by kprovance** [comment]
http://docs.reduxframework.com/core/generating-a-support-hash/

**Comment by pooyaa** [comment]
hi, when i click on the button : 
error. 
there was an error please try again later!!

**Comment by dovy** [comment]
Ok, please download the version of Redux from this repo and install it as a plugin.

**Comment by pooyaa** [comment]
I've downloaded the latest version from github. WordPress version should I download? Plugin?

**Comment by dovy** [comment]
Use the GitHub version, not the WordPress version and try to create another support URL please.

**Comment by pooyaa** [comment]
hi again
i try on other url
i must put my support url in here?
http://support.redux.io/?id=1GaGGH%2Fl7KBQ3RmXd5Wc%2FXWwRfhjfzD1nXNWQZ9VQqM8Iegcq9E7zTT2R2gV3xNxclrNlvdSMbbpxnOEXD2ZTw%3D%3D

**Comment by pooyaa** [comment]
when i open this url don'n see anything in screen an no any thing open on my browser. can you help me here plllz? my request very important and i need to help you

**Comment by dovy** [comment]
Perfect, thank you. That helped a lot.

So while providing you with a sample I found a small bug. It's resolved in the version of the code that's in this repo right now.

Here's the code you need to run before you load your instance of Redux.  ;)

```
add_action( "wp_ajax_helpbase_options_ajax_save", 'read_only_ajax', 0 );
    function read_only_ajax() {
        if ( ! is_admin() ) {
            echo json_encode( array(
                'status' => __( 'This panel is set to be Read-Only. Saving is disabled.', 'redux-framework' ),
                'action' => 'error'
            ) );
            die();
        }
    }
```

You can easily change the is_admin() check to check for specific users or whatever you want.

Best of luck!

**Comment by dovy** [comment]
OH, FORGOT! Replace helpbase_options with your opt_name.

**Comment by pooyaa** [comment]
thanks a lot for help me,
but. i test this code with my custom opt_name. but dont any change in admin panel. when user click the save easy save setting.
i set persmission for any user to can see the admin panel.

i save this code before and after redux settings. but  no any changes!!!
Thanks a lot

**Comment by pooyaa** [comment]
WOW!!!
Work fine!
thanks a lot :)

**Comment by dovy** [comment]
If you like Redux, or the support we render, please do one or all of the following:
* Donate to keep us going: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=MMFMHWUPKHKPW
* Review us: http://wordpress.org/support/view/plugin-reviews/redux-framework
* Like us: http://facebook.com/ReduxFramework
* Follow us: http://twitter.com/ReduxFramework
