### ISSUE TITLE
Notice: Array to string conversion in C:\wamp\www\theme\wp-content\plugins\redux-framework\ReduxCore\framework.php on line 1828

### ISSUE THREAD

**Issue by arabscimitar** [reduxframework/redux-framework#2207]
i think it's color theme extension bug

**Comment by kprovance** [comment]
With the plethora of details you've provided, who knows.  Please review:  http://docs.reduxframework.com/core/generating-a-support-hash/

**Comment by dovy** [comment]
Yes, please submit your support URL then we can further assist. Thanks!

**Comment by arabscimitar** [comment]
ok

**Comment by dovy** [comment]
Also are you a user or a developer?

**Comment by dovy** [comment]
Could you please provide your support URL here?

**Comment by arabscimitar** [comment]
i am a developer

**Comment by dovy** [comment]
Please post the support URL here. If it isn't working, download the newest version of Redux from this repo, run it as a plugin, and retry.

**Comment by arabscimitar** [comment]
Non-static method PDO::getAttribute() cannot be called statically in <b>/home/thematy
/public_html/thecrescent/wp-content/plugins/redux-framework/ReduxCore/inc/class.redux_helpers.php
error while generating the support url

**Comment by kprovance** [comment]
That code was fixed in the latest version from our repo.  Please upgrade to that version and try again.

**Comment by arabscimitar** [comment]
ok

**Comment by arabscimitar** [comment]
yes when upgrade all fixed thanks and sorry

**Comment by kprovance** [comment]
Could you please still provide his support url, so we can see the systems that were affected by this error?  Thanks!

**Comment by arabscimitar** [comment]
the error apear after i saved theoptions and i can't generate the support url

**Comment by dovy** [comment]
That means we need to find out why even more! We want to resolve issues like this. Did you update redux? What's the new error?

**Comment by arabscimitar** [comment]
http://support.redux.io/?id=l0ao9SQ5RTz1BuqUCOPpyT66efg%2BfocB%2Fdb34T56kQHZyQnRUYNbco3HGLqpJSjxuIoT3Q%2FzSDbwFOaUScx83Q%3D%3D

**Comment by arabscimitar** [comment]
finally i disable wp_debug to generate the url

**Comment by dovy** [comment]
If you enablw wp_debug, what was the error returned?

**Comment by arabscimitar** [comment]
<b>Notice</b>:  Array to string conversion in <b>/home/thematy/public_html/thecrescent/wp-content/plugins
/redux-framework/ReduxCore/framework.php</b> on line <b>1827</b><br />
<br />
<b>Notice</b>:  Undefined property: ReduxFramework::$fontControl in <b>/home/thematy/public_html/thecrescent
/wp-content/themes/thecrescent/admin/redux-extensions/extensions/custom_fonts/extension_custom_fonts
.php</b> on line <b>793</b><br />

**Comment by arabscimitar** [comment]
this in the generate url

**Comment by dovy** [comment]
So this is my custom fonts extension that's giving the problem.

Could you please send me your code as is so I can further debug this?

dovy@reduxframework.com

I assure you, we will not steal your code.  :)

**Comment by arabscimitar** [comment]
sure what code ?? you mean in the options-init.php ??

**Comment by dovy** [comment]
The whole theme if you would so we can truly duplicate.

**Comment by arabscimitar** [comment]
ok

**Comment by arabscimitar** [comment]
check your mail :)

**Comment by dovy** [comment]
@arabscimitar Ok, so I've resolved most of your issues in 3.5.2. You can grab it from WP.org.

The other issues pertain to the age of the extensions. However, if you go into ~/custom_fonts/extensions_custom_fonts.php, find the add_section() function (bottom) and modify it to be this, the error will go away.

```
function add_section() {

                if ( ! isset( $this->parent->fontControl ) ) {
                    $this->parent->sections[] = array(
                        'title'  => __( 'Font Control', 'redux-framework-demo' ),
                        'desc'   => __( '<p class="description"></p>', 'redux-framework-demo' ),
                        'icon'   => 'el-icon-font',
                        'id'     => 'redux_dynamic_font_control',
                        // Leave this as a blank section, no options just some intro text set above.
                        'fields' => array()
                    );

                    for ( $i = count( $this->parent->sections ); $i >= 1; $i -- ) {
                        if ( isset( $this->parent->sections[ $i ] ) && isset( $this->parent->sections[ $i ]['title'] ) && $this->parent->sections[ $i ]['title'] == __( 'Font Control', 'redux-framework-demo' ) ) {
                            $this->parent->fontControl = $i;
                            $this->parent->sections[ $this->parent->fontControl ]['fields'][] = array(
                                'id'   => 'redux_font_control',
                                'type' => 'custom_fonts'
                            );
                            break;
                        }
                    }
                }
            }
```

I will be releasing an update to custom fonts here very soon. Thank you for your help to solve this issue.

**Comment by arabscimitar** [comment]
i downloaded the last versions of all my extensions and custom font i downloaded it and its give me version 1.0.1 but  i clicked to downloaded 1.0.4 may be wrong download link in my account

**Comment by arabscimitar** [comment]
and i cant find add_section() function in the custom font extention
