### ISSUE TITLE
Theme Mentor errors

### ISSUE THREAD

**Issue by thehung2224** [reduxframework/redux-framework#2208]
Hello,
I am using Redux Framework v3.4.4.6 on wordpress 4.1.1. Theme Mentor plugin gives me the following error:

![screen shot 2015-04-08 at 09 46 04](https://cloud.githubusercontent.com/assets/5288362/7037909/5f22311e-ddd4-11e4-9f76-a0777adf873b.png)

Do you know how can this be addressed ?

Kind regards,

Hung The.

**Comment by kprovance** [comment]
Many of those are comments.  They'll never show in the finished product.

**Comment by thehung2224** [comment]
So that mean I can ignore these warnings. @kprovance

**Comment by kprovance** [comment]
Yeah, comments shouldn't count.  That plugin you're using should take those into account.  It's kind of sloppy, IMHO.

**Comment by thehung2224** [comment]
Thank you. I get your point :D
