### ISSUE TITLE
Redux v 1.0.0 declares available upgrade in WP 4.1.1, fails with no error

### ISSUE THREAD

**Issue by tylerregas** [reduxframework/redux-framework#2210]
I'm using Redux on a site to support a plugin and an update to v 3.5.1 appeared just a little while ago. When I update it, it says it's complete, but there is no change. The plugin still shows v 1.0.0 and that there is an update available. I tried completely removing the files and reinstalling v 3.5.1 from the WP repository, but it still does the same thing. There are no errors of any kind displayed at any time.

**Comment by dovy** [comment]
Basically the developer of the plugin didn't follow our suggestions and embedded Redux inside.  :P

The issue is one of the plugins that is running has a name higher in the alphabet than Redux and is running BEFORE `plugins_loaded`. If you can find which plugin it is, and just change the init of that plugin until the plugins_loaded hook, you're gravy.

**Comment by tylerregas** [comment]
Ah. Wish I was a developer :) I'm pretty smart though. Where is the init? Once I've got that, I'm pretty sure I can mod the code to make it work. I might have more questions, though :D I'll then complain to the developer of the offending plugin that they're breaking stuff. Thanks! -TC

**Comment by dovy** [comment]
Here you go. Take all the code from the main plugin file in question, and put it within this function and you're done.  :)

```
function bypass_bad_redux_plugin_load() {
	
}
add_action( 'plugins_loaded', 'bypass_bad_redux_plugin_load', 10 );
```

**Comment by tylerregas** [comment]
Awesome! That's a huge help :D

**Comment by dovy** [comment]
No worries. Best of luck.

If you like Redux, or the support we render, please do one or all of the following:
* Donate to keep us going: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=MMFMHWUPKHKPW
* Review us: http://wordpress.org/support/view/plugin-reviews/redux-framework
* Like us: http://facebook.com/ReduxFramework
* Follow us: http://twitter.com/ReduxFramework

**Comment by tylerregas** [comment]
Unfortunately, I couldn't get the mod to work, but I did figure out how to fix it. I disabled Post Per Cat from Urosevic, updated Redux, and then reactivated it. Now the update sticks. I'll send a note to the developer of that plugin to let them know about the issue. Thanks for the help! I'm liking you on Facebook and following you on Twitter :) All very appreciated :D -TC

**Comment by dovy** [comment]
It's not the developer's fault, it was ours. We've resolved it. Thanks!

**Comment by tylerregas** [comment]
Oh, that's okay :) I posted to the forum and the WP page about how I worked around it and what the issue was. I didn't suggest anything unpleasant :) Thanks again!
