### ISSUE TITLE
Redux Admin Notice Editor notification wont go away

### ISSUE THREAD

**Issue by KushClean** [reduxframework/redux-framework#2211]
Redux Admin Notice Editor notification wont go away
it says i have version 1.0 and there is a version 3.51

i deleted the plugin
downloaded the latest 3.51 from wordpress.org
and i still have this issue

**Comment by dovy** [comment]
Redux Admin Notice Editor? What is that? Can you send me a screenshot?

**Comment by dovy** [comment]
If you mean the update notice, are you sure you've updated the running instance of Redux? If you're making a plugin have you delayed your plugin from loading until after plugins_loaded?

**Comment by dovy** [comment]
Whoops. I see the issue. Sorry, my bad. I'll get on it first thing tomorrow!  :)

**Comment by xotlr43** [comment]
I got same problem too.

even I reinstall Redux Admin Notice Editor, I still got 'There is a new version of Redux Admin Notice Editor available. View version 3.5.1 details or update now.' 
I deactivated Redux Admin Notice Editor, and deleted it.

**Comment by dovy** [comment]
Sorry about that. One of our devs was working on a new extension and must have accidentally added it to the wrong place. I'm pushing the fix to wp.org now. This won't show up anymore.

**Comment by dovy** [comment]
Just delete the version of Redux you have, and re-install from wp.org. Thanks!

**Comment by xotlr43** [comment]
Solved! Thanks you dovy
