### ISSUE TITLE
Please help with image_select field

### ISSUE THREAD

**Issue by KAJOJEK** [reduxframework/redux-framework#2212]
Hello, I would like to thank you for create this awesome panel. I'm neewbie and would like to use image_select field to change layout on my blog.

That is my field:

array(
                        'id'        => 'blog-layout',
                        'type'      => 'image_select',
                        'compiler'  => true,
                        'title'     => __('Blog Layout', 'Theme'),
                        'subtitle'  => __('Select blog content and sidebar alignment. Choose between 1 or 2 column layout.', 'Theme'),
                        'options'   => array(
                            'blog-full.php' => array('alt' => '1 Column',       'img' => ReduxFramework::$_url . 'assets/img/1col.png'),
                            '2' => array('alt' => '2 Column Left',  'img' => ReduxFramework::$_url . 'assets/img/2cl.png'),
                            '3' => array('alt' => '2 Column Right', 'img' => ReduxFramework::$_url . 'assets/img/2cr.png')
                            
                        ),
                        'default'   => 'blog-full.php'
                    ),

and I don't know how to use this in my home.php I have tried something like this:

<?php require ('<?php echo $my_option ['blog-layout']; ?>'); ?>

but this dosen't work.

Please help!

**Comment by KAJOJEK** [comment]
ok:) resolved

<?php require ($my_option ['blog-layout']); ?>

works:)

sorry for a problem.

**Comment by dovy** [comment]
Haha. Glad you found a solution!

If you like Redux, or the support we render, please do one or all of the following:
* Donate to keep us going: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=MMFMHWUPKHKPW
* Review us: http://wordpress.org/support/view/plugin-reviews/redux-framework
* Like us: http://facebook.com/ReduxFramework
* Follow us: http://twitter.com/ReduxFramework
