### ISSUE TITLE
jquery onchange not firing on switch field

### ISSUE THREAD

**Issue by kmob2** [reduxframework/redux-framework#2213]
Hello,

I am using the raw output field together with jQuery to show a live preview of the changes to the menu bar. So far everything works as expected.

However when I use switch field, I can't seem to get the jQuery to fire. I noticed the switch fields use hidden fields.

All I am trying to do is to get a jQuery script to fire, once it detects a change in an On/Off switch.

This here does not work, most likely because it's a hidden input field.
```
jQuery('#nav_primary_dropshadow').change(function() {
	alert("I changed");
	//bgstyle={ "box-shadow:": "0 3px 4px #8B8B8B"};	
	//jQuery(".nav-primary-preview").css(bgstyle);
});
```

How else would I be able to detect a change in the switch fields?

**Comment by kmob2** [comment]
By the way, this is the html created by redux for the switch fields.

```

<fieldset id="epurus_theme-nav_primary_dropshadow" class="redux-field-container redux-field redux-field-init redux-container-switch " data-id="nav_primary_dropshadow"  data-type="switch">
	<div class="switch-options">
		<label class="cb-enable selected" data-id="nav_primary_dropshadow">
			<span>On</span>
		</label>
		<label class="cb-disable" data-id="nav_primary_dropshadow">
			<span>Off</span>
		</label>
		<input type="hidden" class="checkbox checkbox-input" id="nav_primary_dropshadow" name="epurus_theme[nav_primary_dropshadow]" value="1" />
	</div>
</fieldset>
```

**Comment by kprovance** [comment]
Something like this would fall under our premium support offering, as it's not a Redux bug or issue.  Here is a hint, look inside the field_switch.js to see how we did it.  :)
