### ISSUE TITLE
issue when we reset section

### ISSUE THREAD

**Issue by smpdesignmedia** [reduxframework/redux-framework#2216]
- click on the reset section button, after this the the "Save Changes" button going disabled, both the buttons.

- after clicking on reset button we can not save the data, i was going to fill the data in slide, but it can not save, because the save button was disabled.

- so, after reset section button we want to "shift + refresh" our browser screen.

- see the attachment for this error.

![error after clicking on reset section button](https://cloud.githubusercontent.com/assets/5764334/7089047/949543ca-dfb6-11e4-9497-1d10226088e2.png)

**Comment by dovy** [comment]
Can you look at your Javascript console and tell me the error you see there? Also please go to ~/wp-admin/tools.php?page=redux-support in your instance and submit a support URL and then post that here.

**Comment by dovy** [comment]
Here's a doc with details: http://docs.reduxframework.com/core/generating-a-support-hash/

**Comment by smpdesignmedia** [comment]
There is no error i found in the "Javascript console", if you want to see this, just take one blank section, click on the "reset section" button, you can see that, i can give you the video recording for this, issue to help you in this, tell me if you want.!!

**Comment by kprovance** [comment]
Thank you for posting on the Redux Issue tracker. In order for us to begin debugging your issue, we need you to first generate a support URL. You can learn about how you generate that here: http://docs.reduxframework.com/core/generating-a-support-hash/

Please update this ticket with the support URL when you have it. Thank you.

**Comment by kprovance** [comment]
48 hours has passed since our request for more information.  Since we have no heard back from you, we are closing this issue.  Please feel free to open a new with the requested information, in the future, should the issue persists.  Thanks!.

**Comment by anikitas** [comment]
Hello,

Have the same issue Redux Framework v3.5.4 embedded in Theme.
Trying the new Redux in a new Theme i'm developing.

ajax_save => true is included in the options tested only in localhost at the moment.

There is no javascript error in the console. I can make a few tests/debug if you want.

You can close this ticket if you want to handle this in a different way :)
Thanasis

**Comment by anikitas** [comment]
I think in this case of reset, buttons are disabled and the action is reload.
There is no remove disable there as the rest of the cases.

Under: \assets\js\redux.js Line approx: 113
<pre>
if ( response.action && response.action == "reload" ) {
	jQuery( '.redux-action_bar input' ).removeAttr( 'disabled' );
	location.reload();
}
</pre>

I just added a line to remove the attribute also in this case and seems to work.
Doesn't make sense as it supposed to reload though, maybe an ajax thing.

**Comment by abukwaik** [comment]
Same issue too, i believe it's related to Firefox. I fixed it by adding `true` to `location.reload();`
`location.reload(true);` No need to remove the attribute.

**Comment by dovy** [comment]
Good to know! Adding it to the core with the true attribute. Great fix @abukwaik!

**Comment by anikitas** [comment]
Good news. I gave a quick and dirty solution :)
Yes that's true, boolean forces reload without caching.

**Comment by smpdesignmedia** [comment]
it's true !
