### ISSUE TITLE
Save changes not completing

### ISSUE THREAD

**Issue by Piscine** [reduxframework/redux-framework#2217]
Dan, the developer of the Petsitter theme said in my support ticket there:
"As I see in your admin dashboard there is some javascript error (screenshot attached). I just tried to install the latest version of Redux Framework from Github and it works.
I'm not sure this is Redux fault or not, but you can replace your current version of Redux with the latest from Github. Or you can wait until next release (I'm pretty sure it will be soon)." (screenshot attached)

Version 3.5.2 just downloaded and installed from Git. Save changes still not completing cycle.

http://support.redux.io/?id=%2FeRvagnDERRNZtE0c9lVMI4OKerAkrIvZu1VAIo4dZptvLT6%2FwUDFuBWDJvnalZ6y4nDRbINOTMHx7%2BSVSAmVw%3D%3D

Appreciate any help.

![6128356110](https://cloud.githubusercontent.com/assets/1532376/7093661/0e102e94-dfb3-11e4-99aa-40118ad9aafb.png)

**Comment by dovy** [comment]
Could you please disable all of your plugins and try again? Then if it works enable them one by one until you find which plugin is the offending item?

I've tested your config and setup and I can't duplicate locally. It must be something that a plugin is doing...

**Comment by Piscine** [comment]
All plugins have been disabled and error remains...

**Comment by dovy** [comment]
Can you give me admin login information? That really doesn't seem right. dovy@reduxframework.com

**Comment by Piscine** [comment]
Hi Dovy,


simonchapman

eight001

Thanks!

Sign up today at www.quotefish.com

**Comment by dovy** [comment]
That didn't work... You'll also want to send it to me directly so your login isn't public knowledge.

**Comment by Piscine** [comment]
I realised just after I hit send...
Will send you another email.

**Comment by kprovance** [comment]
Since this has gone private, I am closing the ticket.  Thanks.
