### ISSUE TITLE
Notice: Undefined index: icon in framework.php on line 1883

### ISSUE THREAD

**Issue by promokit** [reduxframework/redux-framework#2218]
Wordpress 4.1.1, Redux 3.5.2
Notice: Undefined index: icon in /wp-content/plugins/redux-framework/ReduxCore/framework.php on line 1883
http://cl.ly/image/3I3d3b0T1y1W

**Comment by dovy** [comment]
Thank you for posting on the Redux Issue tracker. In order for us to begin debugging your issue, we need you to post to this ticket a support URL. You can learn about how you generate that here: http://docs.reduxframework.com/core/generating-a-support-hash/

Please update this ticket when you have a support URL. Thank you.

**Comment by dovy** [comment]
Did you solve it?

**Comment by promokit** [comment]
Sorry, I forgot to describe that.
The issue was with my options in the file options-init.php
I just removed following bit of code:
array(
                        'id'        => 'opt-web-fonts',
                        'type'      => 'media',
                        'title'     => __('Web Fonts', 'redux-framework-demo'),
                        'compiler'  => 'true',
                        'mode'      => false, // Can be set to false to allow any media type, or can also be set to any mime type.
                        'desc'      => __('Basic media uploader with disabled URL input field.', 'redux-framework-demo'),
                        'subtitle'  => __('Upload any media using the WordPress native uploader', 'redux-framework-demo'),
                        'hint'      => array(
                            //'title'     => '',
                            'content'   => 'This is a <b>hint</b> tool-tip for the webFonts field.<br/><br/>Add any HTML based text you like here.',
                        )
                    ),

**Comment by dovy** [comment]
Ahhh. So very odd. Glad it works.

**Comment by promokit** [comment]
Thank you for your reply!
