### ISSUE TITLE
Redux framework making website slow

### ISSUE THREAD

**Issue by chandreshd** [reduxframework/redux-framework#2219]
hello team,

i have setup redux plugin in wordpress website

http://www.mypcc.tv/

but its slowing down the admin and website both

so please its really urgent for us and guide us

thanks

**Comment by kprovance** [comment]
Thank you for posting on the Redux Issue tracker. In order for us to begin debugging your issue, we need you to first generate a support URL. You can learn about how you generate that here: http://docs.reduxframework.com/core/generating-a-support-hash/

Please update this ticket with the support URL when you have it. Thank you.

**Comment by aman704** [comment]
+1 for this issue, Redux adds 3-4 seconds straight to the page load on both frontend and backend.
Also, redux version 3.4.4.2 does not slow down the website, its something with the latest versions only.

http://support.redux.io/?id=yUzIQBxFaayN7azIPgXyzsU7KXt2eFbZXdgMEolKLm520kqF7Ys9fKqeH5yjkqOklEg8B3%2BDmjzmfl2hum9jMw%3D%3D

Thanks!

**Comment by kprovance** [comment]
@aman704 - In the future, please open your own issue.  I now have the pleasure of working two tickets from one window, which will ultimately get confusing.

Anyways, I ran your config.  Vantage menu: 51 queries in 1.531 seconds.  Supermenu: 51 queries in 1.624 seconds.  Sorry, but I see no speed degradation here.  I AM seeing a bunch of net::err_name_not_resolved errors in the console window for all those hard coded links to image files, which seemed to slow things down a bit.  Make sure that's not an issue on your side.

**Comment by chandreshd** [comment]
Hello all,

can you tell me exact solution to do , both front and back end of wordpress
website is slow after installing redux plugin

thanks

**Comment by kprovance** [comment]
Please see my original reply, @chandreshd.  If you are unwilling to supply that information, we cannot help you.

**Comment by aman704** [comment]
@kprovance I can confirm that this issue is not related to Redux, some recent changes in our theme caused the issue which we're looking into. Appreciate both your sarcasm and willingness to help though!

**Comment by dovy** [comment]
Glad you figured it out!
