### ISSUE TITLE
Missing default option for typography, 'subsets'

### ISSUE THREAD

**Issue by erayalakese** [reduxframework/redux-framework#2220]
There is no *subsets* for default values, but I want to choose *Latin Extended* as default subset like this : 

               'default'     => array(
                    'subset'      => 'Latin Extended',
                    'font-style'  => '700',
                    'font-family' => 'Open Sans',
                    'google'      => true,
                    'font-size'   => '40px',
                    'font-backup' => 'Arial, Helvetica, sans-serif',
                ),

It will be great if you add this feature.

**Comment by kprovance** [comment]
`'subset'      => 'Latin Extended'` should be `'subsets'      => 'latin-ext,`

**Comment by erayalakese** [comment]
@kprovance  Thank you but actually you misunderstood me.

I thought it's not possible to set a default value for subset because it's not listed on [documentation](http://docs.reduxframework.com/core/fields/typography/) (look at Default Options section) . So now my question is evolved to this :

Can you update documentation and add **subset** to list which under **Default Options** title.

**Comment by kprovance** [comment]
SUBSETS!  I'll try and get it to it soon.
