### ISSUE TITLE
Upload Button Not Working in Background Field

### ISSUE THREAD

**Issue by erayalakese** [reduxframework/redux-framework#2221]
**WordPress version** : 4.1.1 (yes, tried with fresh installation)
**Redux version** : 3.5.2 (Downloaded master.zip from GitHub repo)
**Activated Plugins** : Just my test plugin.
**Activated Theme** : Twenty Fifteen
**Config File** : http://paste.ubuntu.com/10812644
**Support Hash** : http://support.redux.io/?id=jVbmX4ozY0Ry6DiHNDlk%2BFKEjz9qI%2Bi5W4BpYBqrWQYOCC1auFr7u6OmzaPh7ccePqr4StRyhYaM4pCi8QoSGg%3D%3D

I'm trying to use [Background](http://docs.reduxframework.com/core/fields/background/) Field but there is a problem with **field_background.js** file line 226.

     frame = wp.media(

This line causing 

> Uncaught TypeError: undefined is not a function

error. There is no 404 error on Chrome Developer Tools. So all js files included to page.
# UPDATE 1 :
I've tried inspecting **wp** object so typed `console.log(wp);`  after `use strict;` line in *fields_background.js* file . This is the result :

     Object {
          svgPainter: Object, 
          heartbeat: Object
         __proto__: Object
     }

And tried this if() control to find if media() function is exists or not ([source](http://stackoverflow.com/questions/20027715/jquery-check-function-exist))

     if (typeof wp.media !== 'undefined' && $.isFunction(wp.media)) {
         alert("exist");
     }else{
         alert("not exist");
     }

Result : **not exist**

# UPDATE 2 [Pull Request](https://github.com/reduxframework/redux-framework/pull/2222)
Found a solution !
After a Google research, I found [this](https://wordpress.org/support/topic/wpmedia-is-undefined) . And called `wp_enqueue_media()`  function inside `admin_enqueue_scripts` hook in my plugin. Now **Upload** button is working. **I think that** problem because of Redux isn't calling `wp_enqueue_media()` function.

**Comment by kprovance** [comment]
Thank you for posting on the Redux Issue tracker. In order for us to begin debugging your issue, we need you to first generate a support URL. You can learn about how you generate that here: http://docs.reduxframework.com/core/generating-a-support-hash/

Please update this ticket with the support URL when you have it. Thank you.

**Comment by erayalakese** [comment]
@kprovance http://support.redux.io/?id=jVbmX4ozY0Ry6DiHNDlk%2BFKEjz9qI%2Bi5W4BpYBqrWQYOCC1auFr7u6OmzaPh7ccePqr4StRyhYaM4pCi8QoSGg%3D%3D

But I'm developing locally , so if you need I can provide a [ngrok](https://ngrok.com/) HTTP tunnel for you to access.

**Comment by erayalakese** [comment]
@kprovance  And please check **Update 1**, it will help you to resolve issue.

**Comment by erayalakese** [comment]
Just solved problem and send a [PR](https://github.com/reduxframework/redux-framework/pull/2222)

**Comment by kprovance** [comment]
I've got a different solution that I used in other media based fields.  Thanks.
