### ISSUE TITLE
How condition setup in redux ?

### ISSUE THREAD

**Issue by raselkhancse** [reduxframework/redux-framework#2223]
I want display value from redux option panel,  display is ok but my condition is not working , see below

if(isset($global_demo['url'])){
echo ''OK";
} else{
echo "Sorry";
}

but, I've not setup or value $global_demo['url'] I want to disply "Sorry", but still showing me is "OK" output, How can i fix this?

**Comment by AlexAlexandru** [comment]
Hello try this code 
global_demo must be your opt name
global $global_demo;
if if (!empty($global_demo['url'])){
	echo 'ok';
}
else {
	echo 'sorry';
}

**Comment by raselkhancse** [comment]
I've OK !
