### ISSUE TITLE
install issue with wp 4.1.1?

### ISSUE THREAD

**Issue by youngpixel** [reduxframework/redux-framework#2225]
Hi,

I'm trying to install redux on wp 4.1.1, which is recommended with Simple Mag Theme, but am getting this error at plugin install:

Downloading install package from https://downloads.wordpress.org/plugin/redux-framework.3.5.2.zip…
Unpacking the package…
Installing the plugin…
Could not create directory. /home/bullboat/public_html/getdevice.com/blog/wp-content/plugins/redux-framework/ReduxCore/assets/img/social
Plugin install failed.

Is it a server issue? Although its installing partially. Please help.

**Comment by AlexAlexandru** [comment]
maybe this will to it http://www.hongkiat.com/blog/update-wordpress-without-ftp/

**Comment by youngpixel** [comment]
I tried FS_METHOD and it didn't worked. Also added ftp details to wp-config
and nothing changed.
Now I got this:

Downloading install package from
https://downloads.wordpress.org/plugin/redux-framework.3.5.2.zip…
Unpacking the package…
Installing the plugin…
Could not copy file. /home/bullboat/public_html/
getdevice.com/blog/wp-content/plugins/redux-framework/ReduxCore/assets/css/vendor/elusive-icons/scss/_icons.scss
Plugin install failed.

Thank You.


Vlad Jantuan


*Shopify expert & e-commerce enthusiast@youngpixel*

http://www.youngpixel.com <http://www.jantuanchik.com>

<http://www.youngpixel.com>

**Comment by AlexAlexandru** [comment]
hi try this http://www.hongkiat.com/blog/update-wordpress-without-ftp/

**Comment by AlexAlexandru** [comment]
download the zip from https://downloads.wordpress.org/plugin/redux-framework.3.5.2.zip download unzip get the folder upload to  your server using a ftp client (filezila, winscp) in wp-content/plugins (here you upload the folder) then go to your plugins in wp dashboard and activate

**Comment by youngpixel** [comment]
Yep, that worked. Thanks Alex
