### ISSUE TITLE
Redux Framework not working on JAZ theme on local host

### ISSUE THREAD

**Issue by MattLuka** [reduxframework/redux-framework#2226]
Massive apologies for coming to you for support but I am working on a web re-build and I am getting no response from the theme developer. If this is something you cant help with then fair enough but I am an impass. 

Basically I am running a full dump of my wordpress sight on a XAMMP local host and trying to build the new theme on and get everything sorted. This issue is that the 'JAZ Options' don't appear in the appearance menu and it seems its a problem with redux. I appreciate it is not your fault though, and its obviously something to do with the theme but I was just wondering if you can help at all? 

If you need the original redux plugin bundled with the theme I can pop you the .zip.

As I say if you cant help or don't have time fair enough, thought is worth an ask!

Many Thanks 

PS I am running wordpress 4.1.1

**Comment by kprovance** [comment]
Take a read here:  http://docs.reduxframework.com/core/support-defined/
