### ISSUE TITLE
CSS code in ace editor not compiled

### ISSUE THREAD

**Issue by sadmansh** [reduxframework/redux-framework#2229]
Hi, I have the ace editor set for a custom CSS field:

```
Redux::setSection( $opt_name, array(
        'title' => __('Add Custom CSS', 'icarus'),
        'desc'      => __('You can add your custom CSS here', 'icarus'),
        'id'    => 'custom-css',
        'subsection'    => true,
        'fields'=> array(
            array(
                'title'     => __('Custom CSS', 'icarus'),
                'id'        => 'custom-css-editor',
                'type'      => 'ace_editor',
                'mode'      => 'css',
                'compiler'  => true,
            ),
        )
    ) );
```

If I type any css code in the editor from the front-end, the code does not show up in the custom.css file I have set for the compiler.

For other fields, however, it works. For example, in the background-type field, if a background color is selected from the front-end, the custom.css file gets updated with that specific code. My background-type field is:

```
array(
          'title'     => __('Post box background','icarus'),
          'id'        => 'post-bg',
          'type'      => 'background',
          'compiler'  => array('.posts-index .post .post-details'),
),
```

I have this line uncommented: 

```
add_filter('redux/options/' . $opt_name . '/compiler', 'compiler_action', 10, 3);
```

My compiler function is (copied directly from the redux docs):
```
function compiler_action( $options, $css, $changed_values ) {
        // echo '<h1>The compiler hook has run!</h1>';
        // echo "<pre>";
        // print_r( $changed_values ); // Values that have changed since the last save
        // echo "</pre>";
        // print_r($options); //Option values
        // print_r($css); // Compiler selector CSS values  compiler => array( CSS SELECTORS )

        global $wp_filesystem;
 
        $filename = get_template_directory() . '/custom.css';
     
        if( empty( $wp_filesystem ) ) {
            require_once( ABSPATH .'/wp-admin/includes/file.php' );
            WP_Filesystem();
        }
     
        if( $wp_filesystem ) {
            $wp_filesystem->put_contents(
                $filename,
                $css,
                FS_CHMOD_FILE // predefined mode settings for WP files
            );
        }
}
```

I'm not sure if I am doing anything wrong, but if I am, can someone please help me set it up? It would be very much appreciated.

**Comment by kprovance** [comment]
Thank you for posting on the Redux Issue tracker. In order for us to begin debugging your issue, we need you to first generate a support URL. You can learn about how you generate that here: http://docs.reduxframework.com/core/generating-a-support-hash/

Please update this ticket with the support URL when you have it. Thank you.

**Comment by kprovance** [comment]
It just occurs to me; ACE_Editor does not support output or compile in terms of output.  Setting compiler to true will trigger the compiler, but it's contents will not output via the $css parameter.  Pull the changed value from the $changed_value parameter instead.  It's an array, so you'll have to code accordingly.

**Comment by sadmansh** [comment]
I have updated the op with the support url. Could you please tell me how to pull the changed value from the $changed_value parameter? I basically want to have the user input some custom CSS code of their own in the Ace editor that will be output to a css file which I can enqueue after all other stylesheets via the enqueue_style function in my theme's function.php.

**Comment by kprovance** [comment]
Not without reviewing your project.  That falls under premium support.

**Comment by dovy** [comment]
Yea, I fear you're asking for custom work. We've given you a bit of a hint. You should try to make it work. If you can't, we need to be compensated for writing custom code for you.

Best of luck!

**Comment by sadmansh** [comment]
Yep I understand. Thank you for the hint, I will try to make it work. And another thing, is there a way I can remove the 'Redux Framework' menu from 'Tools'?

**Comment by dovy** [comment]
Standard WordPress menu functions will do that for you. Though we did put it in the least used menu item of all of WordPress in hopes that you'd leave it.  ;)

**Comment by EMIN-NIME** [comment]
function ono_customize_css() {
	global $theme_option;
	if(isset($theme_option['custom-css'])) {
		echo '<style type="text/css">'.$theme_option['custom-css'].'</style>';
	}
}
add_action( 'wp_head', 'ono_customize_css');


solution of the problem
