### ISSUE TITLE
Redux setting Shoud not dispplay on customize.php

### ISSUE THREAD

**Issue by dipskakadiya** [reduxframework/redux-framework#2230]
I register setting and some of setting will display on customize.php 
Here is my code to add setting using redux 
https://github.com/rtCamp/rtbiz/blob/master/app/settings/class-rt-biz-setting.php#L182

![selection_005](https://cloud.githubusercontent.com/assets/2979084/7157805/c5ce5584-e390-11e4-81a4-d477f3b9dc4d.png)
![selection_006](https://cloud.githubusercontent.com/assets/2979084/7157806/c66906f6-e390-11e4-846a-97759055dfca.png)

**Comment by AlexAlexandru** [comment]
https://github.com/rtCamp/rtbiz/blob/master/app/settings/class-rt-biz-setting.php#L292 change it to false

**Comment by dipskakadiya** [comment]
Thanks :)

**Comment by dovy** [comment]
Good call @AlexAlexandru. Thanks for being part of the community.
