### ISSUE TITLE
Google Fonts not showing up in Drop Down List

### ISSUE THREAD

**Issue by hellofantastic** [reduxframework/redux-framework#2231]
Redux version: 3.4.4.8
Wordpress version 4.1.1
dev_mode false
embedded in theme
no javascript errors

I Setup typography field as such

Tried with an API key in config but then read in Change log that need for key was dropped
```php
 array(
						'id'          => 'Heading Font',
						'type'        => 'typography', 
						'title'       => __('Heading Font Choice', 'option-framework'),
						'google'      => true, 
						'font-backup' => true,
						'units'       =>'rem',
						'subtitle'    => __('Choose the Font you\'d like for Page Headings.', 'option-framework'),
							'default'     => array(
								'color'       => '#333', 
								'font-style'  => '700', 
								'font-family' => 'PT Sans', 
								'google'      => true
								
							),
						),

```

I have gone as far as echoing variables from field_typography.php in function getGoogleArray()
and $fonts has all the Google fonts in there and at the end if that function the $this->parent->font_groups array has the google fonts in there.

**Comment by dovy** [comment]
Please update to Redux 3.5+ and that should fix the issue. If the problem persists after the update, read and do the following: http://docs.reduxframework.com/core/generating-a-support-hash/

:)

**Comment by hellofantastic** [comment]
Wow, amazing update but the issue is still persisting. 
And even though I have dev_mode false, I know see a Developer mode enabled  little button white text on orange.
 
http://support.redux.io/?id=4VTXQF0QPAwMq5Sy3UWbhunzj4p3jY3OrFEjir1zGQYDLR8glV3l%2B9pWlNHBh2GCW59sVIsZuN9mfAE2v%2BB6%2BaYW3wGsqyLox4JXb1GOxEnwepkKCfbOkr9K06dXkSp6

**Comment by dovy** [comment]
Dev_mode is now always on when developing locally and when WP_DEBUG is set to true. 

So go to tools-> Redux Framework and the status page. Do you see anything red?

**Comment by hellofantastic** [comment]
no there is no red

**Comment by kprovance** [comment]
Your ID arg has a space in it.  Can't do that.  Use a hyphen or underscore instead.

**Comment by kprovance** [comment]
Also, please change your page_slug argument to something other than the default '_options'.  If everyone uses the default, then we're going to have users with collision problems.

**Comment by hellofantastic** [comment]
And there it is, okay and change default... it won;t cause issues?

**Comment by dovy** [comment]
It's the slug that you specify, so no it won't cause problems.  :)
