### ISSUE TITLE
Not filtering a field

### ISSUE THREAD

**Issue by sodbileg** [reduxframework/redux-framework#2232]
Hi, I can't filter a field. Here's what I did.

1. Field ID which I tried to filter = `main_layout`
2. `opt_name` = `my_admin_options`
3. Loaded a framework and config file in a parent theme
4. Added code below in a child theme

```
function override_global( $data ) {

	$data = 'left_sidebar';
	return $data;
}
add_filter( "redux/options/my_admin_options/field/main_layout", 'override_global' );
````

And the result is no change on front-end, but getting errors below on back-end.

````
Warning: Illegal string offset 'id' in /URL/wp-content/themes/mytheme/redux/ReduxCore/framework.php on line 2179

Warning: Illegal string offset 'id' in /URL/wp-content/themes/mytheme/redux/ReduxCore/framework.php on line 2183

Warning: Illegal string offset 'type' in /URL/wp-content/themes/mytheme/redux/ReduxCore/framework.php on line 2207
````

I also tried loading a framework and a config file in a child theme after these code with no luck. Is there anything I'm doing wrong? Redux version is 3.4.3.9.

**Comment by dovy** [comment]
That returns the FULL field object, not the value of the field.

To change the value, you need another filter for the options, or the global variable.

`"redux/options/{$this->args['opt_name']}/global_variable"`

Then just modify the single key. This won't modify the DB at all, even on save.  :)

**Comment by sodbileg** [comment]
Holy ... That works. Thank you so much for your kind answers. Here's what I did in case of someone with the same issue need it.

```
function override_global( $data ) {

	$data['main_layout'] = 'left_sidebar';
	return $data;
}
add_filter( "redux/options/my_admin_options/global_variable", 'override_global' );
```

**Comment by dovy** [comment]
Heh, Redux can do almost anything you can think of.  :)


If you like Redux, or the support we render, please do one or all of the following:
* Donate to keep us going: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=MMFMHWUPKHKPW
* Review us: http://wordpress.org/support/view/plugin-reviews/redux-framework
* Like us: http://facebook.com/ReduxFramework
* Follow us: http://twitter.com/ReduxFramework

**Comment by sodbileg** [comment]
Reviewed, liked and have already followed. Hasn't donated yet, but definitely will :) :+1:

**Comment by dovy** [comment]
:)
