### ISSUE TITLE
Site broken with last update

### ISSUE THREAD

**Issue by allandavidbush** [reduxframework/redux-framework#2233]
url:http://exclusiveretail.net/wp/

The error:
Warning: include(/home/exclus66/public_html/wp/wp-content/plugins/redux-framework/config.php): failed to open stream: No such file or directory in /home/exclus66/public_html/wp/wp-content/plugins/redux-framework/redux-notice-admin.php on line 35

Warning: include(): Failed opening '/home/exclus66/public_html/wp/wp-content/plugins/redux-framework/config.php' for inclusion (include_path='.:/usr/local/php55/pear') in /home/exclus66/public_html/wp/wp-content/plugins/redux-framework/redux-notice-admin.php on line 35

I've made no modifications to permissions since last install of this.

Since this is integral to my site's theme, i'm screwed until i can get a fix. Can some one give me a fix for this?

**Comment by dovy** [comment]
Sorry about that. Delete the version you have installed and reinstall. I've pushed a fix to WP.org.

**Comment by dovy** [comment]
A quick fix is to also remove /home/exclus66/public_html/wp/wp-content/plugins/redux-framework/redux-notice-admin.php

;)

**Comment by dovy** [comment]
Just pushed 3.5.3.1 to fix this issue. So sorry about that. Long story short, SVN didn't delete a file we had deleted last release.  ;)
