### ISSUE TITLE
Redux Admin Notice Editor

### ISSUE THREAD

**Issue by KellBellCA** [reduxframework/redux-framework#2234]
Hi! I just updated to Redux Framework 3.5.3.1. (via Wordpress.org) and my plugins panel is showing a new plugin in addition to RF called Redux Admin Notice Editor ver. 1.0.0 with a nagging update notice (wants to update to ver. 3.5.3.1.). I have it deactivated and it doesn't seem to be messing with my site, but seems to me it shouldn't be there.

**Comment by KellBellCA** [comment]
Never-mind. I found the issue. I had a lingering file from ver. 3.5.3 that didn't get deleted for some reason when I updated to 3.5.3.1. I fully deleted RF via FTP and re-uploaded, and the Admin Notice Editor is now gone.

**Comment by dovy** [comment]
Ya, svn kept a file we had deleted in 3.5.3. Hence the update. ;)
