### ISSUE TITLE
Dev Mode

### ISSUE THREAD

**Issue by Bluxart** [reduxframework/redux-framework#2235]
Hi I updated today to last version of Redux Framework.

Wordpress: 4.1
Redux Framework: 3.5.3.1

In my sample-config.php I set the dev_mode -> false 
but inside the wordpress area in the option panel below the title of the theme I have the label with the "Developer Mode Enabled". I used the sample-config-legacy.php as a reference.

I missed something?

**Comment by AlexAlexandru** [comment]
If you have wp_debug set to true dev mode will be set to true ,
if you are developing in a localhost environment  dev mode will be set to true

**Comment by Bluxart** [comment]
Ah ok thanks for the info. :)

**Comment by braginteractive** [comment]
This should be mentioned in the docs!

**Comment by dovy** [comment]
It's brand new! hah.

**Comment by braginteractive** [comment]
Good to know. Glad I found this ticket, I was trying all kinds of stuff.
