### ISSUE TITLE
Required parameter or

### ISSUE THREAD

**Issue by ahmetertem** [reduxframework/redux-framework#2236]
Hi,
Is there a way to make "or" in requrements ? For example:

Field_A:
1: ....
2: ...
3: .....

Field_B:
1: ....
2: ...
3: .....

Field_C:
1: ....
2: ...
3: .....

Field_D:
1: ....
2: ...
3: .....

Field_D's required =
(Field_A == 2 and Field_B == 1) or (Field_C == 3 and Field_B == 2) 

Is there a way to doin' this ?

Sorry for my English

Regards

**Comment by kprovance** [comment]
See http://docs.reduxframework.com/core/the-basics/required/ specifically the using multiple parents example.

**Comment by ahmetertem** [comment]
@kprovance , thanks for reply. I already read that page before (many times) but there is no information about " or " case.

**Comment by kprovance** [comment]
No, there is no 'or' evaluator.  That would be quite a bit of work to add.  We'd need financial backing to do so.

**Comment by dovy** [comment]
You have to simulate it yourself. ;)

**Comment by ahmetertem** [comment]
:+1:  thanks for replies. I'll go with alternative way :)

Regards
