### ISSUE TITLE
SSL certificate

### ISSUE THREAD

**Issue by newgraphicses** [reduxframework/redux-framework#2237]
Hi, 

I am using in my theme is redux framework for temeoption is the extension of the Metabox.
Installing the SSL certificate data entered in the theme redux no longer be seen and therefore the issue is no longer displayed correctly, why?

Can you help me?

Thank you

**Comment by kprovance** [comment]
To be honest, I have *no* idea what you are attempting to convey.  What does an SSL cert have to do with an options panel, or a metabox?  You'll need to be much more specific.

**Comment by newgraphicses** [comment]
Hi, 

excuse I try to explain better.
I bought http://reduxframework.com/extension/metaboxes/ where I have set the option to choose the page layout (full width, left sidebar, rigth sidebar). Plus I set the Metabox to decide the predominant color of the page (useful for the preview of custom post and other settings.
Once you add the ssl certificate settings Metabox are no longer interpreted by  the theme.

I await your information.

Thank you

**Comment by kprovance** [comment]
Thank you for posting on the Redux Issue tracker. In order for us to begin debugging your issue, we need you to first generate a support URL. You can learn about how you generate that here: http://docs.reduxframework.com/core/generating-a-support-hash/

Please update this ticket with the support URL when you have it. Thank you.

**Comment by kprovance** [comment]
Okay, it's been two days now.  We cannot help you without that support URL.  I am closing this issue.  If you need to refile, please open a NEW issue with the requested support URL.  Thanks!
