### ISSUE TITLE
Developer Mode can't be disabled

### ISSUE THREAD

**Issue by xymurgist** [reduxframework/redux-framework#2238]
Setting up the `'dev_mode'  => false` argument still shows the developer mode enabled tag below the header. I'm using the 3.5.3.1 WP.org release.

**Comment by kprovance** [comment]
Yes.  Redux will now default to dev_mode = true when WP_DEBUG is enabled and if the dev environment is localhost.  Too many people have been disabling it and then requesting support in cases when it needed to be on, so we're saving ourselves some trouble.  Good news is, it will still be set to false when shipped, so your clients will never see it.

**Comment by dovy** [comment]
By design, if developing locally or when wp_debug is on, dev_mode will show. ;)

This is as per request of developers. ;)

**Comment by xymurgist** [comment]
Ah, I wasn't aware of that. Thanks for the update!

**Comment by TukuTuru** [comment]
I am just wondering what publicity has to do with debugging.

But never mind :)

**Comment by kprovance** [comment]
Purchase of our extensions is what keeps Redux alive.  If no one buys, Redux will cease to be.  We have families to feed, after all.  And with literally NO one donating - especially considering the amount of time Redux saves you as a developer - we have to do everything we possibly can to keep the project alive.

**Comment by TukuTuru** [comment]
ye, I Unterstand this fully.

It's just,,, Debugging hasn't much to do with advertising.

I'll send you a donation of 500 bucks tomorrow :)
I appreciate your work.

Consider put some DOC online (or perhaps to donators only?) on how to have a non-adevrtizing code running :)

**Comment by TukuTuru** [comment]
please pass me a donate link!
I won't buy anything, I want to pass money just for sponsoring porpoises

**Comment by dovy** [comment]
https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=MMFMHWUPKHKPW   :)

**Comment by dovy** [comment]
OR: https://reduxframework.com/donate/

**Comment by TukuTuru** [comment]
ok, 500USD in your inbox.
Now tell me how to get rid of that annoying publicity when Debug is ON, can you?
;)
Confirmation number: 57M18893022342438

**Comment by TukuTuru** [comment]
you can private me on my email
you should have receive my email with my payment :dancers:

**Comment by TukuTuru** [comment]
http://reduxframework.com/donation-thankyou gives a 404
just so you know !

**Comment by TukuTuru** [comment]
soryyyyy :)

the other topic's already closed :)

:) You are awesome and it's a great product congrats.

I am now sure all works with the hints, just this:

    'tip_style'     => array(
                        'color'   => 'red',

makes not difference in the "hint" "field" (you call that "Tooltip"?) 

wether i set light, dark, red or green, it stays  cream(default)

Perhaps I use a wrong combination of Style + Color?

**Comment by kprovance** [comment]
It's because you have cluetip set in style.  I checked with the vendor whose library we use (qTip), and if you are using a certain style, the default color will not apply.  Colors only apply to their default tip (when no style is specified).  It's a vendor limitation.  If you want colored tips, omit the cluetip style.  :)

You are also free to continue commenting on closed issues.  :)
