### ISSUE TITLE
Notice: Array to string conversion in plugins\redux-framework\ReduxCore\framework.php on line 1850

### ISSUE THREAD

**Issue by arabscimitar** [reduxframework/redux-framework#2239]
couple of days ago i posted this error and i told you that it is a color theme extension problem 
now i am sure 
the problem about the get_default_output_string() in this function it's get the default string witch is an array in this extension so it's throw that error 
i have made a hot fix to redux core in redux-framework\ReduxCore\framework.php on line 1850
to be 
```
    if( ! is_array($defaultv) ){  
          $default_output .= $defaultv . ', ';
    }
```
and the error gone

**Comment by kprovance** [comment]
I can't (or rather, won't) make modification based on an issue I have yet to reproduce.  Please provide a support URL: http://docs.reduxframework.com/core/generating-a-support-hash/ (this is required for all support requests now).  I need to be able to recreate the issue on my end first.  I can do that with the support URL.  Thanks.

**Comment by arabscimitar** [comment]
ok

**Comment by arabscimitar** [comment]
the support url
http://support.redux.io/?id=WbpbMipG5okG1KBUfQv7HpbFiovwXdJE3BN0F5aJ7oAZqEj6EGEkusQsliSN3CwQcP3WbOahWwDPQQj0EIHZbg%3D%3D

**Comment by arabscimitar** [comment]
sorry i mean color scheme extension :)

**Comment by kprovance** [comment]
Turns out several extensions didn't support default values.  Filtered them out.  Redux v3.5.3.2 should handle this now.

**Comment by arabscimitar** [comment]
thanks you are the best
