### ISSUE TITLE
Developer mode issue

### ISSUE THREAD

**Issue by pubuduranjan** [reduxframework/redux-framework#2241]
Hello there,

I am using your great redux framework plugin for my theme. I have given the users to install the redux framework plugin from WP repository after activating the theme. Although I have disabled dev_mode ( 'dev_mode' => false ) it still indicates that developer mode is on in the options panel.

I never experienced this issue with earlier versions of plugin. But now I see this problem with Version 3.5.3.1. Could you please tell me why this happens? I attach screenshots with this.

![dev mode false](https://cloud.githubusercontent.com/assets/12006942/7215387/f50707a6-e5f2-11e4-8ca5-d19ae15e0559.PNG)
![developer mode enabled](https://cloud.githubusercontent.com/assets/12006942/7215388/f50a1aea-e5f2-11e4-8dac-e7f743e20520.PNG)

Thanks.
Pubudu.

**Comment by teamcrisis** [comment]
https://github.com/reduxframework/redux-framework/issues/2238

**Comment by pubuduranjan** [comment]
teamcrisis, Problem solved. Great...! Thank You very much..
