### ISSUE TITLE
How can i use the output of multi_text field!!

### ISSUE THREAD

**Issue by ZoOmArts** [reduxframework/redux-framework#2242]
Hey,

I'm using redux framework in my theme and i have a problem with the new version 3.5.3.3
I'm using multi_text option type to generate a custom sidebars in my theme. In the usual i get my output by using foreach() and it was working in the old version, but it doesn't work in the latest version.

```
foreach( $zoomarts_options['manage_sidebars'] as $sidebar ) {
   register_sidebar( array(
      'name'            => $sidebar,
      'id'                  => za_generateSlug($sidebar, 45),
      'before_widget'  => '<div id="%1$s" class="widget %2$s">',
      'after_widget'     => '</div>',
      'before_title'       => '<h3 class="widget-title">',
      'after_title'          => '</h3>',
   ) );
}
```
Warnning Message:
```
Invalid argument supplied for foreach() in /home/zo................
```

Can you help me?

Thanks.

**Comment by kprovance** [comment]
That field did not change between major versions.  That error message means the `$zoomarts_options['manage_sidebars']` variable is empty.  You'll need to write code to compensate for that.

**Comment by ArhaamAcademy** [comment]
Hey,

I am using the Redux framework for the first time with the current version (5.6) of wp. Everything is working fine but multi_text and slides are not working. I have followed its documentation properly but the result is not OK. 
Can you help me, please? 

Thanks,
