### ISSUE TITLE
Problem ads header

### ISSUE THREAD

**Issue by nicolas92** [reduxframework/redux-framework#2243]
Hello, I've updated to 3.5.3.3 redux version, but there are ads in the header, I modified the template of redux, I put the save buttons in the header and ads are displayed over the buttons, so I would remove the banners, can you help me?
Thank you a lot.

**Comment by kprovance** [comment]
Sorry, but we won't post methods to remove the banners. It's through our advertising of extensions that Redux exists.  Rest assured, as long as dev_mode is set to false, you end users will not see them.

**Comment by nicolas92** [comment]
Yes, I fully understand why you put ads but they are on the buttons, I modified the template header of redux.
The "dev_mode" is on false, but there is always the information related to dev, this is normal?
Thank you.

**Comment by kprovance** [comment]
#2238

**Comment by nicolas92** [comment]
Ah okay, no problem then :)
Good continuation :)
