### ISSUE TITLE
How can I add default slides to the slider field ?

### ISSUE THREAD

**Issue by ckissi** [reduxframework/redux-framework#2245]
Hi,

I want to add default slides to the slides field, so they will be visible to the user right after installing the theme unfortunately I cannot see "default" property  in docs like for other fields.
Ho can I do that ?

**Comment by kprovance** [comment]
AFAIK, the slides field does not support any type of default setting.  Due to the complexity of some of the code, it's not as simple as specifying an image and some data.  Sorry.
