### ISSUE TITLE
Error in saving theme options

### ISSUE THREAD

**Issue by Joseph-a** [reduxframework/redux-framework#2248]
Hi,
I developed a theme based on your framework ( Thanks for your great job ) and it works like a charm in my localhost and demo website, but I submitted it in ThemeForest to be approved. The reviewer faced with a strange error that I have no idea how and in which situation he faced with this error, actually after the error he couldn't save the options. Here is the screenshot the reviewer sent me : http://envato.d.pr/IiAM/1WaexRSM

I asked the reviewer for extra information but he just sent me the same screenshot.

Thanks,

**Comment by kprovance** [comment]
That file is minimized.  No way to debug it.

**Comment by Joseph-a** [comment]
So you don't have any idea that how he faced with this error?

FYI, I removed the welcome folder from the core.

**Comment by kprovance** [comment]
That could be why.  It was never intended to be removed.  If you go hacking into our core like that, we can't support any errors that come of it.  Sorry.
