### ISSUE TITLE
Customize doesn't work, it tends to refresh to simple option listing instead of the theme's

### ISSUE THREAD

**Issue by jengraph** [reduxframework/redux-framework#2250]
I'm experiencing an issue with Customize, with two different website/clients. At first I thought it was theme related but it did it again with a totally new hosting/theme. So I'm thinking it is do with WordPress latest version OR Redux framework? How can we fix this? What happens for me is that I click on Customize, then I see all the list of options to use but it quickly refreshes to the basic option all on its own. It happens to two different theme/hosting installation. Very strange. Any fix for this?

I've already switch themes, the Twenty Fifteen theme does not have a full Customize options like other themes do, so hard to test and compare in that theme. Both different themes though uses Redux framework, not sure if that is related or the WP Core version, I've rolled back a version with WP and it does the same issue.

Any ideas? Workaround now is to click on Customize. Quickly in the Browser URL I click on the X to prevent this from refreshing again once I'm on that screen (otherwise this will refresh automatically to the 2nd shorter list of options which is not what I want, I need to be able to adjust the theme options (the long list).

**Comment by dovy** [comment]
What version of Redux are you running? Please do the following: http://docs.reduxframework.com/core/generating-a-support-hash/

**Comment by jengraph** [comment]
I sent you an email... I can't view that page either with permissions, I've tried changing permissions on that page but still can't view this.

**Comment by dovy** [comment]
That means you have a really old version of Redux installed. Please install the Redux Framework plugin from within the WordPress admin. Then try again.  :)

**Comment by jengraph** [comment]
That did the trick! OMG these theme developers need to know this, I was going crazy for the last 24 hours. :D

**Comment by dovy** [comment]
haha. I am so sorry. It's not our fault what our developer's do!

Glad we were able to solve it though! Best of luck to you.

**Comment by jengraph** [comment]
Spoke too soon! That just delayed the screen refreshing in Customize. This is crazy. What else can it be?

**Comment by dovy** [comment]
Hhaha, ok. Well, do the support URL.

**Comment by dovy** [comment]
Then I can help further and test.

**Comment by jengraph** [comment]
http://support.redux.io/?id=na6ePYYqT2AKS0qQBr2KclHGxnfBGCkzdZL%2FWdP77ukiR68N3rH3bci4jGQL5wZ8xLD4bV9mkGGOzJZpoCLLpA%3D%3D

**Comment by jengraph** [comment]
This is the other site having same issue, I've added the plugin to both. http://support.redux.io/?id=mpByKXsvUfneRKwS4LAyInVPb%2F%2F7MtWkrLRzWLMDP%2FUkxIWA3Jdl%2FLZZjdUPYqeY4e0Jj4VXOFBuwpXguPqK1wuGALSrZyt1S25E69vRsiKNY7q3NVtgA%2BfhUpMB01YJ

**Comment by dovy** [comment]
I was able to reproduce. Very odd indeed. It's working on our demo site... I'm on it.

**Comment by kprovance** [comment]
Seems this is an issue for larger option panels.  Not much we can do about that.

**Comment by dovy** [comment]
Actually, I'm working on it.  :)
