### ISSUE TITLE
How to add quick tags (H1,H2,...) to editor ?

### ISSUE THREAD

**Issue by ckissi** [reduxframework/redux-framework#2251]
I tried this code but it doesn't work :

<pre>
array(
  'id'               => 'intro-text',
  'type'             => 'editor',
  'title'            => __('Intro Text', 'redux-framework-demo'),
  'subtitle'         => __('Subtitle text would go here.', 'redux-framework-demo'),
  'default'          => 'Lorem Ipsum is simply',
   'args'   => array( 
      'textarea_rows'    => 15,
      'wpautop' => true,
      'media_buttons' => false,
      'quicktags' => array(
          array('eg_paragraph','p','<p>','</p>','p','Paragraph tag',1),
       ),
    )
),
</pre>

**Comment by dovy** [comment]
I'm going to be honest, I don't know the WP Editor JS code at all. Everything in Args is passed strait to the WP JS. So I doubt we can be of much assistance since we don't know that API.  :(

**Comment by ckissi** [comment]
It must be possible as I see it in your demo: http://www.webpagescreenshot.info/img/55352a43c02a25-23310423
There is button "toggle toolbar" but I don't know how to make it visible in "args" and clicked by default

**Comment by dovy** [comment]
Well then, follow the sample config.  :)   https://github.com/reduxframework/redux-framework/blob/master/sample/sample-config.php#L543-L558

Good luck!
