### ISSUE TITLE
Use a different compiler for various fields

### ISSUE THREAD

**Issue by jaschaio** [reduxframework/redux-framework#2252]
Hey Guys,
is it possible to use a different compiler for various fields?

So for example that I have two different compiler functions and one fields uses the first one and another field uses the second one.

**Comment by kprovance** [comment]
As cool as that would be, not at this time.  In our (forthcoming) theme, we did a condition check in the compiler function, checking the for the field key in the $changed parameter to handle different fields.  :)

**Comment by jaschaio** [comment]
Thanks for your response kevin, I implemented it similar now. Maybe something worth to consider for future versions, if it is not something just very few people need. Thanks anway :)
