### ISSUE TITLE
Metaboxes: Spinners manual entry not working

### ISSUE THREAD

**Issue by gustavoarielms** [reduxframework/redux-framework#2253]
Hi there, I'm using a spinner field and when I try using manual entry or the up and down keys I got the error NaN. I have set the max and min and the default value as well.
How can be this solved?
Thanks!

**Comment by kprovance** [comment]
Please post issues with extensions to their issue tracker.  This is one for the framework only.  Thanks.

https://github.com/reduxframework/redux-extensions/issues
