### ISSUE TITLE
Escaping add_query_arg

### ISSUE THREAD

**Issue by Stephen-Cronin** [reduxframework/redux-framework#2254]
Hi,

I'm sure you're aware of the [XSS vulnerability affecting multiple plugins](https://blog.sucuri.net/2015/04/security-advisory-xss-vulnerability-affecting-multiple-wordpress-plugins.html) today. 

We (Envato) are writing to ThemeForest and CodeCanyon authors to advise them what to do. We noticed that Redux uses these functions and while most are properly escaped, there are a couple of instances in the EDD code that *may* need to be escaped (very low risk indeed!).

In EDD_License_Handler.php there are 2 cases of add_query_arg. I think these should be fine because they are passing a URL (issue can only occur when no URL is passed) - but I notice that Pippen now  uses esc_url_raw in his sample plugin. [Screenshot of Redux](http://envato.d.pr/5r0s/4mebyXW4) | [Screenshot of EDD sample plugn](http://envato.d.pr/1kugc/4Yh5iT44)

The one that I'm not sure about is in extension_edd.php, line 156 in Redux 3.5.3.1. A URL is being passed, but is coming from posted data, so probably should be escaped anyway? [Screenshot](http://envato.d.pr/13MLn/4IrRkQko)

I think the risk is very low, but any chance of getting this investigate and potentially patched? Thanks.

**Comment by kprovance** [comment]
extension_edd.php was removed from our core a long, long time ago...but lo, it appears to be within the wp.org download?  Hmmm.  I think we can remove this leftover junk file and make it a non-issue.  Thanks for the heads up!
