### ISSUE TITLE
Forced Dev Mode? How to disable it?

### ISSUE THREAD

**Issue by ahmadawais** [reduxframework/redux-framework#2256]
I just updated the local copy of my theme with 
```
REDUX VERSION 3.5.4
```
In ref to TF's article about XSS vulnerability.

Now, it is not deactivating the dev mode. First it said the dev mode is activated coz of debug true in wp-config.php, I turned it false and now it says that the dev mode is on coz you are working in locahost.

I have already defined 
```
dev_mode'                  => false, 
```
in options-init.php file of configuration. What should I do to turn dev_mode off?

**Comment by ahmadawais** [comment]
I read inside the builder

```
This argument tells Redux to use the compressed JS files or not. If developing locally, or if you have WP_DEBUG set, dev_mode is automatically enabled. It is strongly advised that you ensure dev_mode is set FALSE prior to the release of your product release.

```

I would like to disable the dev_mode locally, can you suggest what to do?

**Comment by AlexAlexandru** [comment]
you could delete the if statement starting at  https://github.com/reduxframework/redux-framework/blob/1d9b0319ecdb7b2b25dbdd5bdb575caf8fad9c36/ReduxCore/framework.php#L245 with and finishing at 247

**Comment by ahmadawais** [comment]
@alexalexandru that I can do. But won't be a good way. I'd like to do it through options-init.php file so that I could keep updating redux easily.

**Comment by ahmadawais** [comment]
I changed the line Line 245 and 408 it worked. But that's not a good way. I think there should be an argument which I could turn off though options file.

**Comment by AlexAlexandru** [comment]
ar far as I know there is not such argument maybe in feature I don't know I'm not the dev of redux

**Comment by ahmadawais** [comment]
I know Alex, I am looking forward to answer from @dovy

**Comment by kprovance** [comment]
You can't.  When WP_DEBUG is set and/or you're in a local host environment, it's forced to true.

**Comment by kprovance** [comment]
@AlexAlexandru - Discussing on how to circumvent code we deliberately put in place is frowned upon.  Please, refrain from doing so in the future.  If you wish to fork Redux and make your own mods, that's fine, but discussion of it will be removed in the future.  Thanks for the understanding.

**Comment by ahmadawais** [comment]
I'd like @dovy to add this feature, since I show my theme from my local server to clients before deploying them. There should be an argument we developers could switch off instead of going into code and disabling it.

**Comment by kprovance** [comment]
Well, then, that would defeat the purpose of what we've added.  Continuing to keep dev_mode set to false will ensure your users do not have dev_mode enabled, but since you are a developer, it shouldn;t be that big of a deal.  I mean, seriously, what's the problem?

**Comment by ahmadawais** [comment]
The problem is user experience testing. You can't know what kind of problems your end user will face if you won't try and test your product in the similar environment. And I did mention another reason in my last comment. I guess you missed it.

**Comment by kprovance** [comment]
I didn't, but I'm not swayed.  We're talking about unminimized JS files here, basically.  How is that a debug hindrance, or are you just unhappy that the ads don't go away?

**Comment by dovy** [comment]
@ahmadawais This feature came at the request of our developers. A number of them informed us they forget to turn on dev_mode and as such, lose the benefits. If you're developing locally you are a developer. 

Beyond this request we saw a need for it because unless compress JS is disabled, we will never get proper javascript errors back from out users.

```
The error is on line one of file.js...
```

When a JS file is compressed, line 1 is the entire file, heh. This helps with support.

We have no intention of making the change you suggest as it defeats the purpose of this feature. You're welcome to change the framework.php, since you are a developer and @AlexAlexandru was so kind enough to supply you instructions. 

Also the majority of product demos occur on a server, not locally. Your particular use case is unique.

One last thing, @kprovance may have mentioned the ads, but that was not one of our deciding factors. However, if that is the concern then you are welcome to fork what you need.

Have a great day!

**Comment by ahmadawais** [comment]
I keep the dev_mode true whenever I am developing but I need to see the end user side of things. Which this feature has forced me not to, unless until I am not on localhost. 

I don't care about ads or stuff like that, actually it helps me find stuff which I was not aware of.

It's really upto you, but forcing the dev_mode is not good when I need to see how user will find these options. 

Else is up to you. My job is to share my experience and feedback, you can either consider it constructive or not :)

**Comment by dovy** [comment]
@ahmadawais I'm sad to say you're the first person who we explained this to who didn't say "wow, great idea!"  Hehe.

I doubt we're going to make an extra argument for developers to forget. Just disable it manually yourself for your unique issue. Just remember to turn it back on before release.  ;)

**Comment by ahmadawais** [comment]
I have it turned on in the Development Server. Believe me. I know you are trying to build a solution out of it. I am here to back you up. It's jus that anything forced is not something I wish for, just like Customizer is now being forced at WP.org.

**Comment by dovy** [comment]
Yea, the customizer terms are as follows (just found out today)

```
Redux Requirements

In 6 months time, all options MUST be customizer based for themes submitted to WP.org. Redux may be used, but only under these conditions.

* TGM to recommend Redux installed as a plugin OR follow the instructions to embed Redux in a way that is approved by WP.org.
* Redux panel must be disabled, and only the customizer used.
* Use only Customizer field types may be used. Any field that isn't supported by the customizer must be coded by the developer or not used.
```

So Redux can offer... 10 field types to the customizer as is. Oy.

**Comment by ahmadawais** [comment]
@dovy Off topic, I wish you could start a sister company Redux-Customizer. It will have much better impact, you'll get to do the business over again, you'll get paid for what you gave for free in Redux and you won't have to care about getting banned at W.org. I think it would be a good business decision. You should vet this.

**Comment by dovy** [comment]
Ping me on Skype. DovyDigital

**Comment by kowsar89** [comment]
@dovy I respect the reason behind forced enabling dev mode, but also as a developer i like to have total control on things I'm using even if small things. The way i see it, i can't disable the dev mode in localhost from config file unless i touch core files.
Maybe its not important, maybe it's a small thing to consider, but things like these are big deal for me when i see i can't control things the way i want no matter what how small things they are.
Hope you understand. Now I'm looking at core files to hide it and i hate to do such unnecessary things which could be avoided!

**Comment by kowsar89** [comment]
@dovy I respect the reason behind forced enabling dev mode, but also as a developer i like to have total control on things I'm using even if small things. The way i see it, i can't disable the dev mode in localhost from config file unless i touch core files.
Maybe its not important, maybe it's a small thing to consider, but things like these are big deal for me when i see i can't control things the way i want no matter what how small things they are.
If some developers think that its a good thing to force them into dev mode when they're in localhost, it's their philosophy. My philosophy could be different. Why i have to be forced to adopt others philosophy instead of applying mine? With due respect, I don't like it.
Hope you understand. Now I'm looking at core files to hide it and i hate to do such unnecessary things which could be avoided!

**Comment by dovy** [comment]
Just put this anywhere in your code before Redux is run.  ;)

```
$_SERVER['REMOTE_ADDR'] = "local";
```

That should solve it.  ;)   Just put it in a debug plugin, don't ship with your product.  ;)

**Comment by kowsar89** [comment]
Thanks for quick ans.
I'm going to ship it so i changed in framework.php file line 1255 like this:
`$this->args['dev_mode'] = false;`

**Comment by kprovance** [comment]
Changing the core code is a bad idea.  Any changes will be undone on update, or if your users have Redux running as a plugin.

**Comment by kowsar89** [comment]
yeah you are right, it's not a good idea. I just hope my changes will exists as long as users don't update redux from other sources. That's the compromise I'm doing now because of this issue. Anyway thanks

**Comment by dovy** [comment]
You realize your users won't experience this, right?  ;)

**Comment by kowsar89** [comment]
Yeah i realize that. But still i like to keep things in my way.

**Comment by fyeboahus** [comment]
forced dev mode off enabled has been set to true in redux framework.how do i set it to false in my wordpress backend

**Comment by kprovance** [comment]
That feature was removed.  It was hurting our extensions sales.  Sorry,

**Comment by fyeboahus** [comment]
ok but i have it in my plugin.
can you help me change it to false

**Comment by kprovance** [comment]
I just said there is no more "forced dev mode off".  There is nothing to set.  As long as dev_mode is set to false, your clients will not see the ads.
