### ISSUE TITLE
multi-text Undefined index if no value in array

### ISSUE THREAD

**Issue by HandyWP** [reduxframework/redux-framework#2257]
Hello,

I have created this field:

                    array(
                        'id'=>'custom-sidebars',
                        'type' => 'multi_text',
                        'title' => __('Custom Sidebars', 'redux-framework-demo'),
                        'validate' => 'no_special_chars',
                        'show_empty' => false,
                        'subtitle' => __('Add unlimited custom sidebars to use in your website', 'redux-framework-demo'),
                        'desc' => __('Click on Add More to add the widget. If you want to remove sidebars, click remove next to the text field.', 'redux-framework-demo')
                    )

for making custom sidebars and this is the code in a file called widgets.php located in a folder called framework:

	global $handy_wp;
	$sidebars = $handy_wp['custom-sidebars'];
	if($sidebars){
		foreach ($sidebars as $sidebar){
			register_sidebar( array(
				'name' => $sidebar,
				'id' => sanitize_title($sidebar),
				'before_widget' => $sidebar,
				'after_widget' => $after_widget,
				'before_title' => $before_title,
				'after_title' => $after_title,
			) );
		}
	}

It appears in options without any problem but there is an error message appear on the top of the admin panel:

Notice: Undefined index: custom-sidebars in C:\MAMP\htdocs\76\wp-content\themes\hwp\framework\widgets.php on line 54

Line number 54 is:
$sidebars = $handy_wp['custom-sidebars'];

But when I add values the error message disappear and when I delete all values the error message return.

Is there a way to disable this error message if there is no value entered in the multi-text field?

Notice that:
Debug mode is On
Developer mode is On
Redux Version: 3.5.1

**Comment by kprovance** [comment]
You'll want to do an isset on `$handy_wp['custom-sidebars']` before assigning it to a variable.
