### ISSUE TITLE
Welcome Error

### ISSUE THREAD

**Issue by MrHunter** [reduxframework/redux-framework#2258]
Here are my details according to the guidelines:
<table>
<tr><td>Redux Version:</td><td> 3.5.4</td></tr>
<tr><td>WordPress Version: </td><td> 4.1.2</td></tr>
<tr><td>dev_mode: </td><td> true</td></tr>
<tr><td>Using: </td><td> I have 2 option panels, 1 in a theme and 1 in a plugin.</td></tr>
<tr><td>Redux Embedded: </td><td> Redux Embedded in my theme</td></tr>
<tr><td>Console Errors: </td><td> None</td></tr>
</table>

I am currently getting this error on updating the Redux framework: Warning: Invalid argument supplied for foreach() in /Applications/XAMPP/xamppfiles/htdocs/automotive/wp-content/plugins/automotive/ReduxFramework/ReduxCore/inc/welcome/welcome.php on line 72.

Thanks.

**Comment by kprovance** [comment]
Please do the following: http://docs.reduxframework.com/core/generating-a-support-hash/

**Comment by MrHunter** [comment]
Here we go: http://support.redux.io/?id=CzpXpO1x6XzD4rJ0RB8Qm%2FZfe%2BRa2BnVGAuBwoj%2FcnfRcbldIFMXcgl7Ng6i6N0KDwMwDeiBoOQEhgtVGq4uWQ%3D%3D

Cool feature BTW.

**Comment by kprovance** [comment]
Thanks.  Credit @dovy, it was mostly his doing.  ;-)

Can't quite reproduce this yet.  It has to do with Redux instances not enuming in the welcome page, but yet for the support URL, they enum just fine.  It's weird.  Gotta ponder this some more.

**Comment by MrHunter** [comment]
No worries, for now I just wrapped the foreach in an if(!empty()) for a temporary fix

**Comment by kprovance** [comment]
I can't recreate using an embed install.  I'm beginning to think the plugin might be the culprit, specifically some kind of load order.  Any change I can get you to send that to me, your plugin?  It;s the only thing I haven't tried yet.  kevin@reduxframework.com.  Danke schoen.  ;-)

**Comment by kprovance** [comment]
Upgrading to v.3.5.4.3 should resolve this.

**Comment by MrHunter** [comment]
Unfortunately I am still receiving the warning message =/

**Comment by kprovance** [comment]
Try loading the framework.php inside a `plugins_loaded` action, and see if that makes a difference.
