### ISSUE TITLE
WordPress.org Theme Requirements - READ

### ISSUE THREAD

**Issue by dovy** [reduxframework/redux-framework#2259]
To all devs who develop **themes** on WordPress.org. There is a new requirement that will go into effect within the next 6 months. You can read all the details here: https://make.wordpress.org/themes/2015/04/21/this-weeks-meeting-important-information-regarding-theme-options/ 

Essentially, the WordPress.org themes submission teams is mandating that theme developers ONLY use the Customizer for options.

What does this mean for Redux users? Here are the terms:

```
In 6 months time, all options MUST be customizer based for themes submitted to WP.org. Redux may be used, but only under these conditions.

* TGM to recommend Redux installed as a plugin OR follow the (instructions to embed Redux in a way that is approved by WP.org)[http://docs.reduxframework.com/core/wordpress-org-submissions/].
* Redux panel must be disabled, and only the `customizer_only` argument used.
* Only Customizer field types may be used. Any field that isn't supported by the customizer must be coded by the developer or not used.
```

These are the following field types that can be used in the customizer, but most cannot have advanced options.
* text
* checkbox
* radio
* select
* textarea
* color
* media

Unfortunately this is beyond our control. You are welcome to voice your opinion if you feel motivated to do so here: https://make.wordpress.org/themes/2015/04/21/this-weeks-meeting-important-information-regarding-theme-options/

Unfortunately it seems that any framework, aside from http://kirki.org, should not be used in WordPress.org themes. Please voice your opinion if you have one to the WP.org team.

**Comment by abukwaik** [comment]
I did but who cares :disappointed_relieved:

**Comment by dovy** [comment]
Haha, yea. Well, it can affect everything. Either way, speaking up does something vs doing nothing.  ;)

**Comment by abukwaik** [comment]
Indeed. And you did great defending your point :confused:

**Comment by dingo-d** [comment]
Let's see how long it takes for Themeforest to start enforcing the same... :\

**Comment by dovy** [comment]
I'm not that worried about ThemeForest. Remember the "new requirements" that are still on hold?  ;)

Thought I may have to make Redux run as a customizer only option.  :P

**Comment by aman704** [comment]
Our theme was pretty much ready, using Redux. But after this announcement, to make the theme future-proof I'm going to switch Redux to Customizer. Been on it for an hour and now I'm worried more about the backend limitations then the actual functionality of the theme. Also makes you realise the importance of Redux. Thankfully, we are still and will keep using it in our plugin. 

You guys should make a new framework for customizer controls, even if its premium I'll buy it ;)

**Comment by dovy** [comment]
We're working on it now.  :P    And the announcement will come very soon.

**Comment by aman704** [comment]
@dovy that's actually a good news, I tried Kirki and it showed some error so dropped it. Do you have any ETA as to when the announcement/basic version might come out? Might save me alot of hours figuring out customizer.

**Comment by dovy** [comment]
@aman704 Skype me.

**Comment by aman704** [comment]
Added

**Comment by wpthemes786** [comment]
Hello Dovy. First of All bundle of thanks for this amazing framework. Secondly i have send you a skype request kindly accept me if layman's are allowed in your contact list.

Dovy i have integrate redux with underscore theme. and also enable kirki framework for customizer options. i just want to know that how to disable the customizer options that comes with redux framework and wordpress default customizer options. Conclusion is i just want to show kirki settings.

Lastly when will your amazing framework launch customizer api.

Thanks in advance.

Regards:

Bilal Ahmed

**Comment by dovy** [comment]
@wpthemes786 Just set customizer=> false in your global args.

We have a demo going. We're just looking for support from the community to finish it off. https://ideas.reduxframework.com/campaigns/complete-customizer-integration/

**Comment by wrrr** [comment]
All that said how do I react to my theme dev saying: "Redux evolved a lot since (theme) was initially released. We have it in stable version that provides all necessary functionality for us...."

Yet in a query monitor I get:

Broken Dependencies	redux_options_panel
https://domain.com/wp-content/themes/theme/theme-framework/admin/js/redux-options-panel.js

jquery redux-opts-js (missing)

What do you suggest in this scenario, is this going to be a bigger problem later? Or is there a fix that can be implemented ourself without digging through the theme?

thx
Stu

**Comment by dovy** [comment]
@wrrr please open a new ticket. Have you tried installing Redux as a plugin?
