### ISSUE TITLE
Undefined constant AUTH_KEY and Undefined index REMOTE_ADDR

### ISSUE THREAD

**Issue by erayalakese** [reduxframework/redux-framework#2260]
I get some errors while unit testing with `phpunit`. My test suite was working before integrating Redux to my plugin. 

    Installing...
    Running as single site... To run multisite, use -c tests/phpunit/multisite.xml
    PHP Notice:  Use of undefined constant AUTH_KEY - assumed 'AUTH_KEY' in /PLUGINDIR/libs/redux-framework-3.5.2/ReduxCore/inc/class.redux_instances.php on line 67

    Notice: Use of undefined constant AUTH_KEY - assumed 'AUTH_KEY' in /PLUGINDIR/libs/redux-framework-3.5.2/ReduxCore/inc/class.redux_instances.php on line 67
    PHP Notice:  Use of undefined constant SECURE_AUTH_KEY - assumed 'SECURE_AUTH_KEY' in /PLUGINDIR/libs/redux-framework-3.5.2/ReduxCore/inc/class.redux_instances.php on line 67

    Notice: Use of undefined constant SECURE_AUTH_KEY - assumed 'SECURE_AUTH_KEY' in /PLUGINDIR/libs/redux-framework-3.5.2/ReduxCore/inc/class.redux_instances.php on line 67
    PHP Notice:  Undefined index: REMOTE_ADDR in /PLUGINDIR/libs/redux-framework-3.5.2/ReduxCore/inc/tracking.php on line 65

    Notice: Undefined index: REMOTE_ADDR in /PLUGINDIR/libs/redux-framework-3.5.2/ReduxCore/inc/tracking.php on line 65
    PHP Notice:  Use of undefined constant AUTH_KEY - assumed 'AUTH_KEY' in /PLUGINDIR/libs/redux-framework-3.5.2/ReduxCore/inc/tracking.php on line 91

    Notice: Use of undefined constant AUTH_KEY - assumed 'AUTH_KEY' in /PLUGINDIR/libs/redux-framework-3.5.2/ReduxCore/inc/tracking.php on line 91
    PHP Notice:  Use of undefined constant SECURE_AUTH_KEY - assumed 'SECURE_AUTH_KEY' in /PLUGINDIR/libs/redux-framework-3.5.2/ReduxCore/inc/tracking.php on line 91

    Notice: Use of undefined constant SECURE_AUTH_KEY - assumed 'SECURE_AUTH_KEY' in /PLUGINDIR/libs/redux-framework-3.5.2/ReduxCore/inc/tracking.php on line 91
    PHP Notice:  Undefined index: REMOTE_ADDR in /PLUGINDIR/libs/redux-framework-3.5.2/ReduxCore/inc/class.redux_helpers.php on line 69
    PHP Notice:  Undefined index: REMOTE_ADDR in /PLUGINDIR/libs/redux-framework-3.5.2/ReduxCore/inc/class.redux_helpers.php on line 69
    PHP Warning:  Cannot modify header information - headers already sent by (output started at /PLUGINDIR/wordpress-develop/tests/phpunit/includes/bootstrap.php:53) in /PLUGINDIR/wordpress-develop/src/wp-includes/pluggable.php on line 1196

    Notice: Undefined index: REMOTE_ADDR in /PLUGINDIR/libs/redux-framework-3.5.2/ReduxCore/inc/class.redux_helpers.php on line 69

    Notice: Undefined index: REMOTE_ADDR in /PLUGINDIR/libs/redux-framework-3.5.2/ReduxCore/inc/class.redux_helpers.php on line 69

    Warning: Cannot modify header information - headers already sent by (output started at /PLUGINDIR/wordpress-develop/tests/phpunit/includes/bootstrap.php:53) in /PLUGINDIR/wordpress-develop/src/wp-includes/pluggable.php on line 1196

All constants (like `AUTH_KEY`, `AUTH_KEY_SECURE`) are defined in **wp-config.php** .

When I remove these lines from my plugin file, it's working again.     

    require_once ('libs/redux-framework-3.5.2/ReduxCore/framework.php');
    require_once ('libs/redux-config.php');

I know these error usually because of mising constant definitions in **wp-config** , but as I said before, I've define them.

**Comment by erayalakese** [comment]
I found this temporary (or maybe permanent?) solution.

Add this lines to your **phpunit.xml**

     <php>
        <const name="WP_IS_IT_TEST" value="true" />
    </php>

And in your plugin file :

    if(!WP_IS_IT_TEST) :
    require_once ('libs/redux-framework-3.5.2/ReduxCore/framework.php');
    require_once ('libs/redux-config.php');
    endif;

So, during your unit tests , Redux won't included.

**Comment by dovy** [comment]
Those are all WordPress specific items.... Are you loading WordPress first?

**Comment by erayalakese** [comment]
Yes I'm loading Redux in my plugin  file.  So Redux loading in
plugin_loaded action.
23 Nis 2015 18:09 tarihinde "Dovy Paukstys" <notifications@github.com>
yazdı:

**Comment by daithi-coombes** [comment]
I'm having the same issues. My test cases are created using the plugin scaffolding from [wp-cli](http://wp-cli.org), my quick fix around it was to set `convertNoticesToExceptions="false"` in my `phpunit.xml` config.

**Comment by kprovance** [comment]
Should be fixed in the v3.5.4.4 push.
