### ISSUE TITLE
Redux Video Course

### ISSUE THREAD

**Issue by nomansbeauty** [reduxframework/redux-framework#2261]
Latest version is super, very nice work. Are there any video tutorials available Paid / Free?
I am asking because you may know if someone has produced such training stuff? Please let me know.

Thanks.

**Comment by dovy** [comment]
I'm actually working on some courses now. Do you have anything specific you'd like to see?

**Comment by kprovance** [comment]
Right now, any available videos would be on our docs site:  http://docs.reduxframework.com.  We are considering putting together a tutorial site, but due to the work involved, they would not be free.  Time will tell.  :)

**Comment by dovy** [comment]
Here are some of our OLD video tutorials:
http://reduxframework.com/video-tutorials/

Do you have anything specific you'd like?

**Comment by nomansbeauty** [comment]
Hi guys,

Thanks for prompt response. I did checked these random videos. Here are my suggestion or which type of video training I am taking about @dovy  

1. A complete training for all the major features that will speed up learning process of using Redux for any new WP developer.
2. Best practices - DOs & DONTs
3. Like we have WordPress codex but Lynda.com published comprehensive training for WP (rather than reading through whole lots of API docs)
4. How Redux framework can be used with other WP features (such as metaboxes)
5. Any other important / useful thing regarding redux and may be explanation of its most complex components.

@kprovance We will be glad to buy the video training if it exists :) We are already using Redux in our Premium Themes and we owe you for this powerful tool.

These are just my ideas, I was really sad to find that there is NO such training available anywhere.
Thank you
