### ISSUE TITLE
last tag (3.5.5.10) of the repo seems wrong

### ISSUE THREAD

**Issue by franceimage** [reduxframework/redux-framework#2262]
I think you meant 3.3.5.10

I noticed that while I was trying my [plugin](https://github.com/franceimage/wp-alt-repositories) against your repository. It allows to install any version of your plugin and be notified of updates as well as updating with any commit of your liking.

So when you download the last tag of redux (named 3.5.5.10)  you get this strange situation
your plugin says
![redux 1](https://cloud.githubusercontent.com/assets/3442039/7294192/2382c97e-e9ab-11e4-9bc3-355c48f636af.png)

my plugin says
![redux 2](https://cloud.githubusercontent.com/assets/3442039/7294200/31f8a6b8-e9ab-11e4-9905-b9ead3f4e707.png)

I also think version 3.5.4 should come from a Github tag (not from a source file).
When I get the message 'new version: 3.5.4' I expect to find a tag with that name. From your perspective, 3.5.4 does not mean a lot for support because you don't know what commit it is referring to.

**Comment by dovy** [comment]
That tag was from 2014 and was a mistake. It has been deleted from the repo.

**Comment by vburlak** [comment]
@dovy please, also remove git tag [3.5.5.10](https://github.com/reduxframework/redux-framework/releases/tag/3.5.5.10)

There one more issue, when installing redux framework via composer - it's downloading `3.5.5.10`

my composer.json:
```
"require": {
    "redux-framework/redux-framework": "~3",
},
```

and it's output:
```
Loading composer repositories with package information
Updating dependencies (including require-dev)           
- Installing redux-framework/redux-framework (3.5.5.10)
    Downloading: 100%         
```


you can easy debug that issue via `composer show redux-framework/redux-framework`

```
name     : redux-framework/redux-framework                                   
descrip. : Redux is a simple, truly extensible options framework for WordPress themes and plugins.
keywords : Settings, customizer, framework, options, plugin, redux, wordpress
versions : dev-master, * 3.5.5.10, 3.5.4.3, 3.5.3, 3.5.1, 3.5.0, 3.4.3.6, 3.4.0, 3.3.9.4, 3.3.8, 3.3.6.8, 3.3.6, 3.3.4, 3.3.3, 3.3.1.1, 3.3.0, 3.2.9.13, 3.2.9, 3.2.8, 3.2.6, 3.2.5, 3.2.4, 3.2.3, 3.2.2, 3.2.1, 3.1.9, 3.1.8, 3.1.6, dev-sass-dev
type     : wordpress-plugin
license  : GNU General Public License v3.0 or later (GPL-3.0+) (OSI approved) http://spdx.org/licenses/GPL-3.0+#licenseText
source   : [git] https://github.com/reduxframework/redux-framework.git e447b1c0f3edfa06cdc66e83b74c278f139f272f
dist     : [zip] https://api.github.com/repos/reduxframework/redux-framework/zipball/e447b1c0f3edfa06cdc66e83b74c278f139f272f e447b1c0f3edfa06cdc66e83b74c278f139f272f
names    : redux-framework/redux-framework

requires
composer/installers ~1.0
php >=5.2.0
```

Cheers
