### ISSUE TITLE
Developer Mode Remains Enabled Always in v3.5.4

### ISSUE THREAD

**Issue by simrandeep** [reduxframework/redux-framework#2263]
Hi

I just updated one of my themes to use latest version of Redux that is Redux Framework v3.5.4 and after updating it to latest version Developer Mode is always enabled no matter dev_mode is set to false or true. Please look into it.

Here are my details:

- WordPress version: 4.1.2
- Redux is embedded in theme
- Redux framework version is 3.5.4

Thanks

**Comment by teamcrisis** [comment]
Please review closed issues: https://github.com/reduxframework/redux-framework/issues/2238

**Comment by simrandeep** [comment]
Thanks
