### ISSUE TITLE
Description for section not showing?

### ISSUE THREAD

**Issue by paulthecoder** [reduxframework/redux-framework#2264]
Redux: 3.5.4
WordPress: 4.2
Server: localhost

I am setting my options the legacy way, still have yet to update to the new Redux API. The description for the section is not showing up.

```
$this->sections['single_post'] = array(
	'title'     => __('Posts', 'theme'),
	'desc'      => __('Description.', 'theme'),
	'fields'    => array()
);
```

**Comment by dovy** [comment]
Subtitle.  ;)

**Comment by kprovance** [comment]
Ah, I hate to disagree with you, Captain, but subtitle is for individual fields.  He's talking about the section itself, which does use `desc`.

That said, I loaded the legacy config file, and it's outputting the `desc` argument.  :|

**Comment by kprovance** [comment]
Paul, if you want a quick conversion to the API way, post a support URL.  I can bang it right back to you.

**Comment by paulthecoder** [comment]
I must of had some illegal character or something, I refreshed and it just started working! Sorry about that, just something random on my end. Thanks @kprovance, I don't got too many fields at the moment plus I have started converting to the API already so no need.

**Comment by kprovance** [comment]
Excellent!  Glad it worked out.  Cheers.
