### ISSUE TITLE
cant run with `phpunit`:  PHP Warning:  `headers already sent by (output started at bootstrap.php:53) pluggable.php on line 1196`

### ISSUE THREAD

**Issue by daithi-coombes** [reduxframework/redux-framework#2265]
The error is only being thrown when `redux framework` is included in my tests. I've disabled `php notices` in my unit tests to solve this issue: #2260 but not willing to do so for `php warnings`. Happy to test my plugin in isolation, as is normal to me. The warning however might be a blocker for anybody that is unable to test in isolation. 

I've scaffold my plugin using [wp-cli](http://wp-cli.org) so the issue may lie there. Removing my autoloading of the framework that I got from here [embedding redux into your theme or plugin](http://docs.reduxframework.com/core/advanced/embed/), removes the `php warning` and my plugins tests pass. Autoload the `redux-framework` and they fail.

Stack Trace:
```
PHP Warning:  Cannot modify header information - headers already sent by (output started at /opt/wordpress/tests/wordpress-tests-lib/includes/bo
otstrap.php:53) in /opt/wordpress/tests/wordpress/wp-includes/pluggable.php on line 1196
PHP Stack trace:
PHP   1. {main}() /home/daithi/.composer/vendor/phpunit/phpunit/phpunit:0
PHP   2. PHPUnit_TextUI_Command::main() /home/daithi/.composer/vendor/phpunit/phpunit/phpunit:36
PHP   3. PHPUnit_TextUI_Command->run() /home/daithi/.composer/vendor/phpunit/phpunit/src/TextUI/Command.php:104
PHP   4. PHPUnit_TextUI_Command->handleArguments() /home/daithi/.composer/vendor/phpunit/phpunit/src/TextUI/Command.php:114
PHP   5. PHPUnit_TextUI_Command->handleBootstrap() /home/daithi/.composer/vendor/phpunit/phpunit/src/TextUI/Command.php:622
PHP   6. PHPUnit_Util_Fileloader::checkAndLoad() /home/daithi/.composer/vendor/phpunit/phpunit/src/TextUI/Command.php:792
PHP   7. PHPUnit_Util_Fileloader::load() /home/daithi/.composer/vendor/phpunit/phpunit/src/Util/Fileloader.php:42
PHP   8. include_once() /home/daithi/.composer/vendor/phpunit/phpunit/src/Util/Fileloader.php:58
PHP   9. require() /var/www/my-site/wp-content/plugins/my-plugin/tests/bootstrap.php:18
PHP  10. require_once() /opt/wordpress/tests/wordpress-tests-lib/includes/bootstrap.php:85
PHP  11. do_action() /opt/wordpress/tests/wordpress/wp-settings.php:337
PHP  12. call_user_func_array:{/opt/wordpress/tests/wordpress/wp-includes/plugin.php:496}() /opt/wordpress/tests/wordpress/wp-includes/plugin.ph
p:496
PHP  13. Redux::createRedux() /opt/wordpress/tests/wordpress/wp-includes/plugin.php:496
PHP  14. Redux::loadRedux() /var/www/my-site/wp-content/plugins/my-plugin/vendor/ReduxFramework/ReduxCore/inc/class.redux_api.php:127
PHP  15. ReduxFramework->__construct() /var/www/my-site/wp-content/plugins/my-plugin/vendor/ReduxFramework/ReduxCore/inc/class.redux_api.php:115
PHP  16. do_action() /var/www/my-site/wp-content/plugins/my-plugin/vendor/ReduxFramework/ReduxCore/framework.php:430
PHP  17. call_user_func_array:{/opt/wordpress/tests/wordpress/wp-includes/plugin.php:496}() /opt/wordpress/tests/wordpress/wp-includes/plugin.ph
p:496
PHP  18. Redux_Welcome->init() /opt/wordpress/tests/wordpress/wp-includes/plugin.php:496
PHP  19. Redux_Welcome->check_version() /var/www/my-site/wp-content/plugins/my-plugin/vendor/ReduxFramework/ReduxCore/inc/welcom
e/welcome.php:47
PHP  20. wp_safe_redirect() /var/www/my-site/wp-content/plugins/my-plugin/vendor/ReduxFramework/ReduxCore/inc/welcome/welcome.ph
p:88
PHP  21. wp_redirect() /opt/wordpress/tests/wordpress/wp-includes/pluggable.php:1270
PHP  22. header() /opt/wordpress/tests/wordpress/wp-includes/pluggable.php:1196
```

**Comment by daithi-coombes** [comment]
have confirmed the same issue is arising with the framework being provided by the `redux  wordpress plugin`.

**Comment by daithi-coombes** [comment]
i've `forked` and created a `pr` around this issue: https://github.com/daithi-coombes/redux-framework/pull/1 Think that the issue #2260 may also be resolved here?

**Comment by kprovance** [comment]
Honestly, that phpunit.xml has been sitting there for so long, I can't even begin to guess at how valid it is.  Sadly, I know very little about how it's supposed to work.  If any of you find a working solution, PLEASE, feel free to submit a pull request for it.  ;-)

**Comment by daithi-coombes** [comment]
gladly ;)
https://github.com/daithi-coombes/redux-framework/pull/1

@kprovance I was wondering - is there still a dependency on including [TIVWP](https://github.com/TIVWP/tivwp-dm-development-manager) in the [current tests](https://github.com/reduxframework/redux-framework/blob/master/tests/bootstrap.php#L18)?

**Comment by kprovance** [comment]
Um...@Dovy?  I don't know, to be honest.  I was never involved with any of that.  ;-)

**Comment by kprovance** [comment]
I think the final answer here is yes.  All of those tests are using in our TRAVIS compiler.

**Comment by daithi-coombes** [comment]
cool - I've created a `pr` for this issue: https://github.com/daithi-coombes/redux-framework/pull/1

atm its not merging with master so I'll fix those conflicts when I get home tonight and let you know when its ready

**Comment by kprovance** [comment]
Okay, all is pushed.  Hopefully this solves it.  ;-)
