### ISSUE TITLE
Outdated documentation for "Update an Option Outside the Options Panel"

### ISSUE THREAD

**Issue by erayalakese** [reduxframework/redux-framework#2268]
I'm trying to update a Redux option outside of Redux Option panel. I'm following [your official guide](http://docs.reduxframework.com/core/advanced/update-an-option-outside-the-options-panel/), but it's **outdated**.

In newest version of Redux, there is no new `Redux_Framework_sample_config();` line in config file. There is a static Redux class and this class don't have any `set()` method.

So, how can I update an option outside of Redux option panel? And can you update the documentation?

> Redux Version : 3.5.2.1
WordPress 4.1
dev_mode is enabled

**Comment by dovy** [comment]
Probably the EASIEST way is simply this:

```
$data = get_option( 'opt_name' );
$data['key_i_want_to_change'] = 1;
update_option( 'opt_name', $data );
```

But yes, I'll get to work on updating the documentation.  ;)

**Comment by erayalakese** [comment]
@dovy ,

I tried same code snippet but `update_option()` causing this fatal error:

> Call to a member function get() on a non-object in /Users/erayalakese/www/wp-page-generator/wp-includes/cache.php on line 113

When I use random string like this `update_option('blabla', 'new value')`  it's working, but when I use  Redux opt_name as first arguments, it's giving error.

**Comment by thimfy** [comment]
it is work fine, but how to use two or more options with it: like
$data = get_option( 'opt_name' );
$data['key_i_want_to_change'] = 1;
$data['key_i_want_to_change'] = 0;
update_option( 'opt_name', $data );

Like this it is not working
