### ISSUE TITLE
Hints settings are not respected if edited - me being dumb or BUG ? 

### ISSUE THREAD

**Issue by TukuTuru** [reduxframework/redux-framework#2270]
my HASH:
http://support.redux.io/?id=tnNrJZZhDka3m2%2BvIrsCO9CC5nPT3PZ6bl5gQN6RGJ6czVM9UrExvub%2B4pyarrCe8f3gXPd%2FWC2o13%2FqSR39zg%3D%3D

I have this Field in the following section:

    array( 
                        'title'     => __( 'Featured Button', 'minimax3' ),
                        'subtitle'  => __( 'Enable/Disable featured button.', 'minimax3' ),
                        'id'        => 'featured_btn',
                        'default'   => true,
                        'on'        => __( 'Enable', 'minimax3' ),
                        'off'       => __( 'Disable', 'minimax3' ),
                        'type'      => 'switch',
                        'hint'          => array(
                            'title' => 'something',
                            'content' => 'Hint text. Yay!',
                        ),

                        
                    ),

This are the Hint Configurations:

    // HINTS
                $field['hints'] = array(
    'icon'              => 'icon-question-sign',
    'icon_position'     => 'right',
    'icon_color'        => 'lightgray',
    'icon_size'         => 'normal',
 
    'tip_style'         => array(
        'color'     => 'light',
        'shadow'    => true,
        'rounded'   => false,
        'style'     => '',
    ),
    'tip_position'      => array(
        'my' => 'top left',
        'at' => 'bottom left',
    ),
    'tip_effect' => array(
        'show' => array(
            'effect'    => 'slide',
            'duration'  => '500',
            'event'     => 'mouseover',
        ),
        'hide' => array(
            'effect'    => 'slide',
            'duration'  => '500',
            'event'     => 'click mouseleave',
        ),
    ),
    );
Now If I change any value in this configurations, nothing happens.
(lets say, change color to something else or whatever)

- No errors, dev mode on, no console errors, config file (embedded) is in theme root > theme options > redux-config.php, correctly called from functions.php, Redux 3.5.4.1, so I assume it's "fresh" :)

All is working like a charm, but those confutations can't be changed...

I am confused about this DOC:
http://docs.reduxframework.com/core/the-basics/using-hints-in-fields/

There you mention, hints should be included in fields as follows:

    $field['hint'] = array(
        array(
        'title'   => 'Hint Title',
        'content' => 'This is the content of the tool-tip'
      )
      );

but that won't work!

only this works:

    'hint'          => array(
                            'title' => 'something',
                            'content' => 'Hint text. Yay!',
                         ),

Let me know what I'm doing wrong, OK?

Also donation has been sent a few minutes ago :) !!

thank you

**Comment by kprovance** [comment]
Well, there is a mistake in the docs, which I'll have to correct.

The args declaration for hints is incorrect, it should look like this in your main args array (in the setArguments function):

```php
$this->args = array(
   // ...list of your args
   'hints'                => array(
       'icon'          => 'el el-question-sign',
       'icon_position' => 'right',
       'icon_color'    => 'lightgray',
       'icon_size'     => 'normal',
       'tip_style'     => array(
           'color'   => 'light',
           'shadow'  => true,
           'rounded' => false,
           'style'   => '',
       ),
       'tip_position'  => array(
           'my' => 'top left',
           'at' => 'bottom right',
       ),
       'tip_effect'    => array(
           'show' => array(
               'effect'   => 'slide',
               'duration' => '500',
               'event'    => 'mouseover',
           ),
           'hide' => array(
               'effect'   => 'slide',
               'duration' => '500',
               'event'    => 'click mouseleave',
           ),
       ),
   )
);
```

The way you are using hints in your field code is correct.

**Comment by kprovance** [comment]
Docs updated.  Yeah, they were WAY off.  Thanks for pointing that out.  :)

**Comment by TukuTuru** [comment]
:)

"Glad" the doc was wrong, but above "solution" I did already figure out myself yesterday and also tried it.
I tried in again :) and it does not bring the desired effect, sadly.

what I have now:

    $this->args = array(
    // ...list of your args
    'hints'                => array(
       'icon'          => 'el el-question-sign',
       'icon_position' => 'right',
       'icon_color'    => 'lightgray',
       'icon_size'     => 'large',
       'tip_style'     => array(
           'color'   => 'red',
           'shadow'  => true,
           'rounded' => false,
           'style'   => '',
       ),
       'tip_position'  => array(
           'my' => 'top left',
           'at' => 'bottom right',
       ),
       'tip_effect'    => array(
           'show' => array(
               'effect'   => 'slide',
               'duration' => '500',
               'event'    => 'mouseover',
           ),
           'hide' => array(
               'effect'   => 'slide',
               'duration' => '500',
               'event'    => 'click mouseleave',
           ),
       ),
     )
    );

and in the field:

    array( 
                        'title'     => __( 'Featured Button', 'minimax3' ),
                        'subtitle'  => __( 'Enable/Disable featured button.', 'minimax3' ),
                        'id'        => 'featured_btn',
                        'default'   => true,
                        'on'        => __( 'Enable', 'minimax3' ),
                        'off'       => __( 'Disable', 'minimax3' ),
                        'type'      => 'switch',
                        'hint'          => array(
                            'title' => 'something',
                            'content' => 'Hint text. Yay!',
                        ),

Have you tried it?

It does not bring any changes!

**Comment by kprovance** [comment]
I have tried it, any changes I make are reflected in the panel.  Chances are you're putting the code in the wrong place.  Use the Gist feature and past in your entire config file, the post back the URL.  I'm certain the issue lies in there.

**Comment by TukuTuru** [comment]
and this confounds me still:
(from DOC http://docs.reduxframework.com/core/the-basics/using-hints-in-fields/)

    $field['hint'] = array(
    array(
        'title'   => 'Hint Title',
        'content' => 'This is the content of the tool-tip'
    )
   );

Why 2 arrays? 

Shouldn't that example be:

     "Add this to the array of your field where you want the hint to appear"

     'hint'          => array(
                            'title' => 'Hint Title',//Optional
                            'content' => 'This is the content of the tool-tip',
                        ),

I mean, If I have a existing field, I don't need to add 2 arrays? right?

**Comment by kprovance** [comment]
No, you don't, but without seeing your config, I can;t begin to speculate.  Looking at the config via your support hash, you have TWO arrays in your args for hints, one that is incorrect and one that is not.  It looks like you are attempting to use the incorrect one to makes changes, hence the failure.  Gist me your config, and I'll fix it.

**Comment by TukuTuru** [comment]
Sorry!!
You where just to fast :D

here we go:
https://gist.github.com/TukuTuru/f22108819cbd88d6d63c

**Comment by kprovance** [comment]
Corrected version:  https://gist.github.com/kprovance/638be52cbb2d34e9e437

The problem was you added the entire args array I suggested within your actual args array.  All you needed to do was add the hint array.

**Comment by TukuTuru** [comment]
I'm a dumbs sorry
I just figured it out same time you wrote your answer
Great work.

I'll send another 500 bucks your way.

Can you help me there?
https://github.com/reduxframework/redux-framework/issues/2238#issuecomment-96778811
(remove all publicity also with Debug true)

**Comment by kprovance** [comment]
We're working on that code for you as we speak, and testing it (so we don't break anything in the process).  We will have it for you very shortly.  Dovy will email it to you when he's finished.  :)
