### ISSUE TITLE
Latest Update Disabling Website 

### ISSUE THREAD

**Issue by tiffanydawn** [reduxframework/redux-framework#2271]
The latest update is causing my website to go down and be inaccessible from both from and back ends. The error reads "too many redirects." I've disabled every single plugin on my site and narrowed it down to redux framework for certain. My site www.recyclingideas.com is currently up and running, but this necessary plug in for my theme is missing and the site is not showing up properly. Thank you for your help.

**Comment by dovy** [comment]
Can you get me login and FTP access and email support@reduxframework.com? We'll gladly resolve this. However, if it isn't the fault of Redux would you donate some time for the effort we spent on your issue?

Either way, we'll help. Get us the info please.

**Comment by tiffanydawn** [comment]
Hi, Yes, I don't mind to donate time either way.

My hosting is through GoDaddy

Login: Tiffany Duke
PW: OneTime1040

The website is www.globalrecyclingideas.com (www.recyclingideas.com is
redirected to this site)

Please let me know if you have any issues and what kind of time you would
like me to give you in exchange.

THANK YOU

**Comment by dovy** [comment]
Please email next time. This is a public forum and I don't want your logins getting out there!  :)

**Comment by dovy** [comment]
Bah, deleted it so quick I didn't copy! Could you please email me the info? I need WordPress login as well as FTP details.

support@reduxframework.com

**Comment by dovy** [comment]
Just found the issue. wp_safe_redirect doesn't work in all cases and on GoDaddy. Changed to wp_redirect and everything works as it should. Pushing to core.

**Comment by kprovance** [comment]
v.3.4.5.2 now pushed and available.

**Comment by tiffanydawn** [comment]
This is amazing. Thank you for your help.
