### ISSUE TITLE
Options with validate argument are not included in customizer

### ISSUE THREAD

**Issue by anikitas** [reduxframework/redux-framework#2272]
Hello,

ReduxFramework  v3.5.4.3 embedded in Theme.

Just want to make clear if this is intended. I lost all my options that used validate in the customizer.
Is this a bug or i should remove all instances of validate when used also in the customizer?
File: \inc\extensions\customizer\extension_customizer.php
<pre>
  if ( isset( $option['validate'] ) && $option['validate'] != false ) {
    continue;
  }
</pre>

I understand that validation will not work in the customizer, but if you need them in both places you loose validation. Just want to make sure if i need to remove all validations when options are used in the customizer.

Thanks in advance!

Thanasis

**Comment by anikitas** [comment]
A common example is using the color picker with validate color:
<pre>
	array(
		'id'          => 'bg_color',
		'type'        => 'color',
		'title'       => 'Background color',
		'subtitle'    => 'Pick a background color.',
		'default'     => '#ff6863',
		'transparent' => false,
		'validate'    => 'color',
	),
</pre>

If validate is used then this option is not available in the customizer.

**Comment by Ryu-k** [comment]
If you want to use color you can modify the line to 
<pre>if ( isset( $option['validate'] ) && $option['validate'] != false && $option['validate'] !== 'color' ) {</pre>

**Comment by anikitas** [comment]
Yes i know :)
But i don't want to modify Redux Framework Core files.
I just removed the validations for these specific option fields in my config file.

I'm fine with that for the moment.

**Comment by dovy** [comment]
I need to finish fixing the customizer implementation!  ;)

**Comment by anikitas** [comment]
No problem Dovy,
I was updated from an older release. I can live with that.

Also subsections in the customizer would be nice :)
