### ISSUE TITLE
JS error with Metaboxes Extension and WP SEO

### ISSUE THREAD

**Issue by corradomatt** [reduxframework/redux-framework#2273]
WP SEO recently updated qTip and the metaboxes extension removed the qTip enqueued scripts because there was an issue with compatibility between the qTip version 1 and version 2. WP SEO updated their version of qTip to version 2 earlier this year (or maybe last year) and the extension no longer needs to dequeue these scripts.

1. In ```metaboxes/extension_metaboxes.php``` on lines 93 through 95 we can remove the actions
2. In the same file the callback function can also be removed between lines 365 and 369.

I experienced admin JS errors in post edit screens when WP SEO was installed and activated with the metaboxes extension.

**Comment by kprovance** [comment]
Please post all extension issues in the area designated for them.  Thanks!

**Comment by corradomatt** [comment]
https://github.com/reduxframework/redux-extensions/issues/181

**Comment by dovy** [comment]
Answer in 181
