### ISSUE TITLE
Many Warnings if Theme Check by "Developer" Plugin by Autmattic

### ISSUE THREAD

**Issue by TukuTuru** [reduxframework/redux-framework#2275]
Hey, I loved my Theme Check results made with this plugin:
https://wordpress.org/plugins/developer/
when I coded my theme Options from scratch manually 
(result, 0 errors)

Now, with Redux, I have some Warnings.

I will now go ahead and try to fix them, submit fix here, and ask you to implement in next release.

I know many of those warnings are because redux is both, a theme and a plugin option builder, but perhaps we should therefore have 2 versions?

Dunnotnow :)

Anyway, I will paste here the link to Gist, the (many) warnings, so you can take a look
https://gist.github.com/TukuTuru/1db01e81477f4b83f5e3

My environment is the same a yesterday :D

NOTE:
theme-options/options-core is where the redux core files are in my theme :dancer:

**Comment by dovy** [comment]
@TukuTuru 
http://docs.reduxframework.com/core/theme-check/

Also most of those warnings are if you USE those options. If you're intending to submit to WP.org then be more wary.

If not, then most of those things are extra classes and non-issues really.  :)

**Comment by TukuTuru** [comment]
said uao, bookmarked, looking for less ....whatever... tester plugin :D
(weird, that plugin is from automattic!!)
==> Nice to know that I can clean out that folder as well by deleting bunch of stuff I don't knew whats it for :)

:+1: 

Any more "skinning" possible ?

My theme name says it all:
MINIMAX (minimal stuff for maximal results :D)

tnx!

**Comment by dovy** [comment]
Skinning of Redux? Sure. There are templates, custom CSS, and slimming Redux down using the builder: http://build.reduxframework.com.  ;)

**Comment by TukuTuru** [comment]
erhm, my english, sorry, with skinning i meant probably slimming :D 
(cut out parts I don't need, keep slim, thin, light, :D)

Will have a look at that thanks
