### ISSUE TITLE
Options Object menu gives me Basic Fields Page

### ISSUE THREAD

**Issue by lidya1859** [reduxframework/redux-framework#2276]
Whenever I click Options Object menu in sidebar it goes to Basic Fields Page..
Is it only me or anyone here have same problem with me?
![tangkapan layar 2015-04-29 16 27 54](https://cloud.githubusercontent.com/assets/9672394/7387154/871999e0-ee8d-11e4-824b-4e23082f2920.png)

**Comment by kprovance** [comment]
Should be fixed in the v3.5.4.4 push.
