### ISSUE TITLE
Redux admin folder 3.5.4.3 downloaded 29.04.2015 gives fatal error

### ISSUE THREAD

**Issue by AleksandarPredic** [reduxframework/redux-framework#2277]
I downloaded from Redux builder 3.5.4.3 version (not development) and new fatal error appers: Warning: require_once(...\admin\redux-framework\ReduxCore/inc/lib.redux_instances.php): failed to open stream: No such file or directory in...\admin\redux-framework\ReduxCore\framework.php on line 36

I also downloaded startup framework and I am getting the same error.

I tried version 3.5.1 from the Redux builder and all is working fine

**Comment by ILLID** [comment]
Yes, I got same issue. Looks like someone forget to add all needed files.
I hope this will be fixed soon

**Comment by kprovance** [comment]
Use the development branch for now.  It's the exact same code base.

**Comment by kprovance** [comment]
We'll be pushing a new stable tag shortly to resolve the one up that that seems...incomplete.
