### ISSUE TITLE
W3 Total Cache & Redux Framework

### ISSUE THREAD

**Issue by Bluxart** [reduxframework/redux-framework#2278]
Redux Framework: 3.5.4.3 ( embed )
Wordpress: 4.2.1

Hi, today I update the last version of Redux Framework and I found an error.

If I have activate the W3 Total Cache - Object Cache ( Enabled ) 
When I go to the Theme Options Panel and change some variables and save, Redux report an alert box and in the changelog report me this error:

*Non-static method W3_ObjectCache::instance() should not be called statically, assuming $this from incompatible context in redux/redux-core/framework.php on line 2694*

If deactivate only the object cache the theme option panel works perfectly.

**Comment by kprovance** [comment]
Should be fixed in the v3.5.4.4 push.
