### ISSUE TITLE
Backup font select field returns value in select2 instead of label

### ISSUE THREAD

**Issue by corradomatt** [reduxframework/redux-framework#2279]
Or maybe I'm backwards and the issue is with the standard field, but I noticed that when I create an array of default (non-google) fonts for my panel and I wanted to use a SCSS variable as the value of the option things work fine in the standard field but in the backup font field, they are reversed.

For example, here's my fonts array....
```php
$fonts = array(
    'Font group 1' => '$font-group-1',
    'Font group 2' => '$font-group-2',
    ...
);
```

I pass that array to the field so that it loads my fonts in the select2 field in the panel. Everything works great. I have google fonts enabled. Then the user chooses a google font from the select field and the backup fonts field is displayed. In the backups fonts field we see ```$font-group-1``` as an option instead of ```Font group 1```. But, again, the option appeared correctly in the default **Font Family** field.

I altered the font field in redux (*field_typography.php*) on [the following block here](https://github.com/reduxframework/redux-framework/blob/master/ReduxCore/inc/fields/typography/field_typography.php#L262-L264) by swapping the foreach loop as below and it worked as expected.
```php
foreach ( $this->field['fonts'] as $family => $i ) {
    echo '<option data-google="true" value="' . $i . '"' . selected( $this->value['font-backup'], $i, false ) . '>' . $family . '</option>';
}
```
*The only change I made is to swap **$family** with **$i** in the foreach loop.

**Comment by corradomatt** [comment]
Also, during this whole process, I just realized that the font-backup field doesn't clear out when a user clears the main font field of any selection. (not that this should happen that often really...but thought I'd bring it up anyway)

**Comment by kprovance** [comment]
But, the return value from backup font SHOULD be what is in the dropdown.  if we change it to be the label, it's going to break it for everyone else, thus killing backward compatibility.

**Comment by corradomatt** [comment]
Actually, I think I had it backwards in that the main field is pulling from the value instead of the label. But that still doesn't address the backwards compatibility issue which is another matter entirely.

I'm fine if you want to close the issue.....it's probably not a problem since other devs haven't brought it up.
