### ISSUE TITLE
Color editing in WordPress live customize no longer possible?

### ISSUE THREAD

**Issue by Ryu-k** [reduxframework/redux-framework#2280]
Redux Framework embed v3.5.4.2
wordpress 4.2.1
not in dev mode

The option color are not showing anymore in the wordpress live customizer ( Appearance > Customize )

http://www.awesomescreenshot.com/image/163366/01d3da1cf985355eb2f72824d151b0ae

Before updating redux and wordpress could change the color 

http://www.awesomescreenshot.com/image/163374/c13caa67e54cdea555b7f191f6b01b88

Is there any way to have the color option back in the appearance live customize ?

**Comment by Ryu-k** [comment]
For anyone who still want to use color in customizer go edit your extension_customizer file line 285
to
<pre> if ( isset( $option['validate'] ) && $option['validate'] != false && $option['validate'] !== 'color' ) {
                            continue;
                        }
</pre>

**Comment by kprovance** [comment]
See here:  https://ideas.reduxframework.com/campaigns/complete-customizer-integration/  :)
