### ISSUE TITLE
Bootstrap Glyphicons

### ISSUE THREAD

**Issue by TukuTuru** [reduxframework/redux-framework#2281]
hello guys.

I saw, you use this to enqueue FontAwesome into Admin Panel Menus:

    function newIconFont() {
    // Uncomment this to remove elusive icon from the panel completely
    //wp_deregister_style( 'redux-elusive-icon' );
    //wp_deregister_style( 'redux-elusive-icon-ie7' );

    wp_register_style(
        'redux-font-awesome',
        '/css/font-awesome.min.css',//Adapted because I don't need to retrieve from WWW, I have it in my theme folders
        array(),
        time(),
        'all'
     );  
    wp_enqueue_style( 'font-awesome', get_template_directory_uri() . '/css/font-awesome.min.css',   array(), '4.2.0', 'all' );//Adapted because I don't need to retrieve from WWW, I have it in my theme folders

    }
    // My Opt.Name is mx3_options.  Therefore:
    add_action( 'redux/page/mx3_options/enqueue', 'newIconFont' );

That's Nice!

I though I am cool and use Bootstrap Glyphicons!

so I did:

    function newIconFont() {
    // Uncomment this to remove elusive icon from the panel completely
    //wp_deregister_style( 'redux-elusive-icon' );
    //wp_deregister_style( 'redux-elusive-icon-ie7' );

    wp_register_style(
        'redux-bootstrap-styles',
        '/css/bootstrap.min.css',//Adapted because I don't need to retrieve from WWW, I have it in my theme folders
        array(),
        time(),
        'all'
    );
    wp_enqueue_style( 'bootstrap-styles', get_template_directory_uri() . '/css/bootstrap.min.css', array(), '3.3.0', 'all');//Adapted because I don't need to retrieve from WWW, I have it in my theme folders

    }
    // My Opt.Name is mx3_options.  Therefore:
    add_action( 'redux/page/mx3_options/enqueue', 'newIconFont' );

But now, the Info Bar (WP Default "Help" tab at pages top) is not "reacting anymore" (if click on the tooltip, nothing happens

the problematic part is this:
    wp_enqueue_style( 'bootstrap-styles', get_template_directory_uri() . '/css/bootstrap.min.css', array(), '3.3.0', 'all');

Do you know if there are conflicts?

How would you enqueue Bootstrap Glyphicons?

Again, your software is just what I call... cool :)
I read some bad comments in WP about you guys not giving support on custom code issues for free.
well, let me say, I understand you. :D
This product is worth more then the 1000 hours ahead _s underscores theme, and it's completely free.

keep on going!

**Comment by kprovance** [comment]
Look in the debug console (CTRL+SHFT+I) see if there are enqueue error in regard to the loading of the CSS.

**Comment by TukuTuru** [comment]
there is something about DOM - new calculation, says 0.46 sec, and has a link to a script ,which is:
load-scripts.php

No warnings in JS, and I have the exact same DOM stuff + load-scripts.php if I do it with font-awesome

this seems somehow a JS Issue, since the "contextual-help-link" does react once, but does not open, instead it just turns the arrow upwards, and that's it

Hmm.. I see. thats not easy to troubleshoot over a couple 1000 Miles away :dancer: 

dang!

**Comment by TukuTuru** [comment]
how would you enqueue it?

Same way, I assume, right?

**Comment by kprovance** [comment]
Honestly, I have NO idea why shoestrap fonts would be interfering with WP fonts in the info bar.

**Comment by TukuTuru** [comment]
I will try around and possibly post a solution here

I also found out, Glyphicons dont properly apply when used as tab icons in REDUX Theme Admin Panel:
Only the first 8 Glyohicons from this list are rendering, the other return a empty square :
http://getbootstrap.com/components/

This is strange. I suspect a issue with that "free" version of glyph icons (usually glyph icons and halflings are a paid service, bootstrap though states they got it as generosity from them...)

**Comment by TukuTuru** [comment]
btw. why you mention shoestrap fonts?
not entirely sure whats the relation to glyph icons ?

**Comment by dovy** [comment]
We use http://elusiveicons.com in our panel.  ;)   They originated from Shoestrap. That's why they were mentioned.

**Comment by kprovance** [comment]
Was there ever a resolution to this issue?

**Comment by kprovance** [comment]
Closing issue.
