### ISSUE TITLE
Best way to enqueue js script that only loads on redux admin panel?

### ISSUE THREAD

**Issue by kmob2** [reduxframework/redux-framework#2282]
Hello,

I need to load a javascript file for the raw HTML field that I am using, so was I wondering, is there a special way to include a javascript file inside the admin panel for redux?

So far I have just included the js file via my themes function.php file by using

```
function enqueue_jquery_sticky( $hook ) {
	/*if ( 'admin.php' != $hook ) {
		return;
	}*/
	wp_enqueue_script( 'my_custom_script', get_stylesheet_directory_uri() . '/js/sticky-menu-admin.js' );
}

add_action('admin_enqueue_scripts', 'enqueue_jquery_sticky');
```
The ```if```` part is commented out on purpose, because it doesn't seem to work. If this is the best way to include a javascript file, how would I make it so it only loads on the redux admin panel pages?

**Comment by kprovance** [comment]
As this is not a direct issue with Redux, or a bug in Redux, we ask those who seek help with basic PHP support to purchase premium support.  http://reduxframework.com/extension/premium-support/  Thanks.  :)

**Comment by dovy** [comment]
You can also see our docs for information like this:
http://docs.reduxframework.com/core/advanced/custom-panel-css/
