### ISSUE TITLE
ReduxFramework folder - 30MB ?

### ISSUE THREAD

**Issue by drosa88** [reduxframework/redux-framework#2283]
Hi guys,

thanks for this awesome framework! I love your work!

Little question: I´m using your framework for plugin development and i include it directly in my files. The problem: Your "ReduxFramework" folder has 30MB Filesize..this is very large for a plugin upload. How do you handle this? Do i need all of them?

Thanks for support!

-Edit-  Okay, i found your builder! :D Amazing!

**Comment by kprovance** [comment]
I'm not sure where you are getting a 30MB download.  The version here in our repo, unzipped is 5.80 MB.
