### ISSUE TITLE
How to Change Redux Panel Template?

### ISSUE THREAD

**Issue by PoshtibanHa** [reduxframework/redux-framework#2284]
Hi, 
I tried to change redux panel template by adding this code into my config file: 
'templates_path'            => ReduxFramework::$_url . 'cornita/templates/panel/',
and i place new template files in: 
wp-content/themes/Cornita/includes/ReduxFramework/ReduxCore/cornita/templates/panel

1. Redux Version 3.5.4.6
2. Wordpress Version 4.2.1
3. Redux is included in my theme:
-- Redux is in this place on my project: 
htdocs/cornita/wp-content/themes/Cornita/includes/ReduxFramework
-- My config file is here: 
htdocs/cornita/wp-content/themes/Cornita/includes/ReduxFramework/cornita/panel-config.php
-- And the codes to initialize in functions.php file:
if ( !class_exists( 'ReduxFramework' ) && file_exists( dirname( FILE ) . '/includes/ReduxFramework/ReduxCore/framework.php' ) ) {
require_once( dirname( FILE ) . '/includes/ReduxFramework/ReduxCore/framework.php' );
}
if ( !isset( $redux_demo ) && file_exists( dirname( FILE ) . '/includes/ReduxFramework/cornita/panel-config.php' ) ) {
require_once( dirname( FILE ) . '/includes/ReduxFramework/cornita/panel-config.php' );
}

4. Panel Configuration: 

                $this->args = array(
                    // TYPICAL -> Change these values as you need/desire
                    'opt_name'             => 'Cornita_Config',
                    // This is where your data is stored in the database and also becomes your global variable name.
                    'display_name'         => $theme->get( 'Name' ),
                    // Name that appears at the top of your panel
                    'display_version'      => $theme->get( 'Version' ),
                    // Version that appears at the top of your panel
                    'menu_type'            => 'menu',
                    //Specify if the admin menu should appear or not. Options: menu or submenu (Under appearance only)
                    'allow_sub_menu'       => true,
                    // Show the sections below the admin menu item or not
                    'menu_title'           => __( 'Cornita Options', 'redux-framework-demo' ),
                    'page_title'           => __( 'Cornita Options', 'redux-framework-demo' ),
                    // You will need to generate a Google API key to use this feature.
                    // Please visit: https://developers.google.com/fonts/docs/developer_api#Auth
                    'google_api_key'       => '',
                    // Set it you want google fonts to update weekly. A google_api_key value is required.
                    'google_update_weekly' => false,
                    // Must be defined to add google fonts to the typography module
                    'async_typography'     => true,
                    // Use a asynchronous font on the front end or font string
                    //'disable_google_fonts_link' => true,                    // Disable this in case you want to create your own google fonts loader
                    'admin_bar'            => true,
                    // Show the panel pages on the admin bar
                    'admin_bar_icon'     => 'dashicons-portfolio',
                    // Choose an icon for the admin bar menu
                    'admin_bar_priority' => 50,
                    // Choose an priority for the admin bar menu
                    'global_variable'      => '',
                    // Set a different name for your global variable other than the opt_name
                    'dev_mode'             => true,
                    // Show the time the page took to load, etc
                    'update_notice'        => true,
                    // If dev_mode is enabled, will notify developer of updated versions available in the GitHub Repo
                    'customizer'           => true,
                    // Enable basic customizer support
                    //'open_expanded'     => true,                    // Allow you to start the panel in an expanded way initially.
                    //'disable_save_warn' => true,                    // Disable the save warning when a user changes a field

                    // OPTIONAL -> Give you extra features
                    'page_priority'        => null,

                    'templates_path'            => ReduxFramework::$_url . 'cornita/templates/panel/',

                    // Order where the menu appears in the admin area. If there is any conflict, something will not show. Warning.
                    'page_parent'          => 'themes.php',
                    // For a full list of options, visit: http://codex.wordpress.org/Function_Reference/add_submenu_page#Parameters
                    'page_permissions'     => 'manage_options',
                    // Permissions needed to access the options panel.
                    'menu_icon'            => '',
                    // Specify a custom URL to an icon
                    'last_tab'             => '',
                    // Force your panel to always open to a specific tab (by id)
                    'page_icon'            => 'icon-themes',
                    // Icon displayed in the admin panel next to your menu_title
                    'page_slug'            => '_options',
                    // Page slug used to denote the panel
                    'save_defaults'        => true,
                    // On load save the defaults to DB before user clicks save or not
                    'default_show'         => false,
                    // If true, shows the default value next to each field that is not the default value.
                    'default_mark'         => '',
                    // What to print by the field's title if the value shown is default. Suggested: *
                    'show_import_export'   => true,
                    // Shows the Import/Export panel when not used as a field.

                    // CAREFUL -> These options are for advanced use only
                    'transient_time'       => 60 * MINUTE_IN_SECONDS,
                    'output'               => true,
                    // Global shut-off for dynamic CSS output by the framework. Will also disable google fonts output
                    'output_tag'           => true,
                    // Allows dynamic CSS to be generated for customizer and google fonts, but stops the dynamic CSS from going to the head
                    // 'footer_credit'     => '',                   // Disable the footer credit of Redux. Please leave if you can help it.

                    // FUTURE -> Not in use yet, but reserved or partially implemented. Use at your own risk.
                    'database'             => '',
                    // possible: options, theme_mods, theme_mods_expanded, transient. Not fully functional, warning!
                    'system_info'          => false,
                    // REMOVE

                    // HINTS
                    'hints'                => array(
                        'icon'          => 'icon-question-sign',
                        'icon_position' => 'right',
                        'icon_color'    => 'lightgray',
                        'icon_size'     => 'normal',
                        'tip_style'     => array(
                            'color'   => 'light',
                            'shadow'  => true,
                            'rounded' => false,
                            'style'   => '',
                        ),
                        'tip_position'  => array(
                            'my' => 'top left',
                            'at' => 'bottom right',
                        ),
                        'tip_effect'    => array(
                            'show' => array(
                                'effect'   => 'slide',
                                'duration' => '500',
                                'event'    => 'mouseover',
                            ),
                            'hide' => array(
                                'effect'   => 'slide',
                                'duration' => '500',
                                'event'    => 'click mouseleave',
                            ),
                        ),
                    )
                );

5.I have this errors in my browser console: 
![selection_001](https://cloud.githubusercontent.com/assets/5385410/7440542/5bfc75f2-f0d1-11e4-865d-c7f2fff489c9.png)

thank you

**Comment by kprovance** [comment]
The only problem I see is here:  `'templates_path' => ReduxFramework::$_url . 'cornita/templates/panel/'`

The path needs a directory path, not a URL.  So:

`'templates_path' => ReduxFramework::$_dir . 'cornita/templates/panel/'`

**Comment by alexanderlperez** [comment]
This was a problem I ran into.  To summarize how this helped, templates_path is expecting an absolute directory path from the system root, not simply a relative path from the *theme or wordpress* directory.  Repeat: using the absolute path given by `ReduxFramework::$_dir` along with a path relative to it was what worked, ex:

```
// use something like this
 'templates_path'            => ReduxFramework::$_dir . '../templates/panel/',

// not something like this
 'templates_path'            =>  '../templates/panel/',
```

**Comment by dovy** [comment]
That is correct as Redux can be in a theme or plugin. You must provide the absolute path.

Do NOT store your files using anything ReduxFramework based, or the plugin will override them.

Use `dirname(__FILE__).'/templates/panel'` instead.

**Comment by jilani53** [comment]
How to change redux framework layout from front-end? but not show  save button. It's only for demo site for client. So, Client check all layout from theme demo.
