### ISSUE TITLE
Detecting a value is changed or not

### ISSUE THREAD

**Issue by sodbileg** [reduxframework/redux-framework#2285]
Is it possible to detect a value is changed or not? For example, a field with an id `username` has `userA` value. And after changing its value to `userB` and saving, is it possible to execute a function?

**Comment by kprovance** [comment]
Yes.  Use a compiler hook:  http://docs.reduxframework.com/core/advanced/integrating-a-compiler/.  The `$changed_values` parameter will be an array of changed values.
