### ISSUE TITLE
Premium Extensions for Commercial Use

### ISSUE THREAD

**Issue by rflfn** [reduxframework/redux-framework#2286]
Sorry, but I don't understand very well about license terms. If I buy one license, example for this (http://reduxframework.com/extension/metaboxes/) I can use on only one theme right? but I can sold this theme unlimited times on ThemeForest? The time that have on page of extension (1 year) is only for my support? or is time that I can use this extension?

Other question, all extensions is updated together ReduxFramework? or if I buy one extension, I need wait for author make extension compatible with ReduxFramework update?

And, all extensions is validated on plugin ThemeCheck?

Have one 'Extended License' for use for unlimited themes? or have one 'Extented Time License' for support for unlimited time (more than 1 year)?

Thanks.

**Comment by kprovance** [comment]
You may include this extension in one premium (not free) WordPress theme or plugin.

Pricing includes 1 year of support and updates. You may cancel at any time and retain the code you have for one product. If you wish for updates, support, or to support the project, please keep your subscription active.

Typically, extensions do not need updating when the Redux core is updated.  However, in the rare instance that should happen, updated are usually put out at the same time.  All extensions are in compliance with ThemeForest/Envato guidelines.

At this time, we do not offer Extended licenses (that I am aware of.  @Dovy could better answer that).  The revenue from our extensions is what we use to keep the Redux project alive and on it's feet.
