### ISSUE TITLE
Getting error after uncommenting compiler filter

### ISSUE THREAD

**Issue by sodbileg** [reduxframework/redux-framework#2287]
Hi,

1. I uncommented this code `add_filter('redux/options/'.$this->args['opt_name'].'/compiler', array( $this, 'compiler_action' ), 10, 3);`
2. I added `'compiler' => true` to a field

After these steps, I tried to save options and got the following error.
![screenshot 2015-05-03 17 25 41](https://cloud.githubusercontent.com/assets/1418797/7444530/7befd190-f1b9-11e4-9e75-aabcce243d25.png)

Redux version: 3.5.4.1
WP version: 4.2.1

**Comment by kprovance** [comment]
Because, using echo or print_r while ajax saved is turned out produces this.  if you look at the javascript debug console, you will see the values of echo or print_r.  Commenting out any echo or print_r statement will resolve this.
