### ISSUE TITLE
Redux Metabox values reset to default when clicking save from Visual composer in editor

### ISSUE THREAD

**Issue by algebres** [reduxframework/redux-framework#2288]
Hello 
Guys

I have one issue with redux metabox.  im using visual composer editor and redux metabox.
 
when i save the values from font end of visual composer i noticed that all the value of metabox i have previewslly entered are reseting  to default values of metabox 

In other words , from front end of visual composer , when clikcing of save , all the entered values for metabox i previewslly enter in the page are reset to default value of metabox

Will be great if you guys can help 

Thank in aedvance

**Comment by dovy** [comment]
?

**Comment by algebres** [comment]
I still expecting an answer 

Thanks you

**Comment by kprovance** [comment]
This issue was closed because 1) it's on the wrong issue tracker and 2) You posted it to the correct issue tracker already.  Any forthcoming answer will be there, and not here.  Thanks.

**Comment by pzstar** [comment]
Is this issues fixed? I am also experiencing the same problem.

**Comment by dovy** [comment]
Front end eigh? @kprovance we should look into this. I wonder if they're resetting the meta fields or if we are. If they are, we need to hook in somehow and restore.

**Comment by pzstar** [comment]
@dovy yes, its when edit is made from the frontend. From admin end there is no problem at all.

On editing with visual composer from the frontend and then updating all the redux metabox value is reset.

**Comment by kprovance** [comment]
Fixed it a long time ago for my theme.  No one gives up version info or support urld, so who kkow.  Old version I am guessing.

**Comment by kprovance** [comment]
Also, this belongs on the extensions issue tracker and why this was closed.

**Comment by pzstar** [comment]
@kprovance i am using the latest version of the Redux Framework v3.6.4

**Comment by kprovance** [comment]
Ugh.  @Dovy, you got paid for this extension, so it's your support show.  All I know is I fixed the VC front end thing last year.  Load up Seele and see for yourself.

First three lines under meta_box_save

```php
                if ( isset($_POST['vc_inline']) && $_POST['vc_inline']){
                    return $post_id;
                }                
```
