### ISSUE TITLE
Compiler action and output

### ISSUE THREAD

**Issue by hellofantastic** [reduxframework/redux-framework#2290]
http://support.redux.io/?id=4VTXQF0QPAwMq5Sy3UWbhunzj4p3jY3OrFEjir1zGQa6Y1Cb%2BDNkE%2BP0HwKWVW7IRGsrLUdwKp7y82TXMA800IVNhy6MyDzRZ%2BJh%2Fye6CfO2f8guFXl44O%2BrdO7z9z5Z

Hi there

Wondering if I can use the output argument and compiler action to modify css and still have it output in the head? I combed the issue tracker and the docs to see if anything would clue me in.
I tried taking the compiler $css and modifying it and returning it but that doesn;t seem to be it if its possible?

**Comment by dovy** [comment]
We don't have a return function for our output. However, you can use the compiler argument just like output to supply you with a variable containing out dynamic output. Then you can write that to a file and run with is.

So really, the compiler is for you to write your own file-saving function and enqueue that CSS file.

But anything is possible.  ;)

**Comment by hellofantastic** [comment]
ah okay thanks, I should have mentioned I have it working by writing a file but I was like ahhh I don;t want another file.Haha I have enough files... alright one more file.

**Comment by dovy** [comment]
Yea, stinks. We're probably going to make our output write to a file ourselves soon enough. hah. More optimized that way.
