### ISSUE TITLE
Welcome Screen and Admin Notifications

### ISSUE THREAD

**Issue by adrianlbs** [reduxframework/redux-framework#2292]
Hello there,

We're using the Redux Framework in our themes and I am so happy to see it's improving a lot. That's great stuff!

In the latest version (3.5+), I see a welcome screen and a few new admin notification. I am wondering if we can turn those off? They're clearly useful for us as developers, but there's nothing for an end user and as far as the user is concerned, there's just another thing calling for action.

Thank you and keep up the good work!
Adrian.

![](http://content.screencast.com/users/adrianlbs/folders/Jing/media/b155265b-4cf1-48be-b127-0019b46e4721/2015-05-04_1602.png)

![](http://content.screencast.com/users/adrianlbs/folders/Jing/media/f21ef443-aa33-40af-9d62-09f9cc89a230/2015-05-04_1601.png)

**Comment by kprovance** [comment]
Those only appear when dev_mode is set to true.  As long as this variable is set to false, user sill not see them. (Note: Dev mode will be automaatically set to true when WP_DEBUG is enabled and/or running on localHost.)

**Comment by adrianlbs** [comment]
Thanks a bunch!
