### ISSUE TITLE
Options not loaded on after_theme_setup hook

### ISSUE THREAD

**Issue by mekshq** [reduxframework/redux-framework#2293]
Hi,

I have a problem. Noticed that in the version 3.5 + options are not available in after_theme_setup hook so I cannot get any option from global variable as it is empty. Can you please explain?

**Comment by dovy** [comment]
By default Redux loads the instances at the init hook. You can easily load it anytime you desire by using the following command:
```
Redux::init('OPT_NAME');
```

;)

**Comment by mekshq** [comment]
Ok, thanks for explanation but since I'm not sure if this is the optimized way I have found a workaround. 

I just need options from database so in case global variable is empty I call get_option('global_variable_string'). 

Is that ok?

**Comment by dovy** [comment]
That's fine. Init will load the object and populate the global variable for you. But either way. It's just an extra DB call.  ;)

**Comment by mekshq** [comment]
Tnx Dovy,

Keep up the great work ;)
