### ISSUE TITLE
Default Install. First text or textarea fields missing in UI

### ISSUE THREAD

**Issue by pxforti** [reduxframework/redux-framework#2294]
I have installed redux as plugin and also have downloaded it and added to template. In both cases, I am using the barebones config and the first text field does not appear in the admin ul. Only the title and description. 

I have tried this on several wordpress local installs and several wordpress template including one I created with your redux builder. In all cases, the first text or textarea field do not appear on the options page: only the option title and description appear. 

Also, it doesn't matter what text field I move to the first option, the field does not appear on the option page.

Config: latest version mamp; latest version of a vanilla wordpress install.

Below is the option code I am using:

 // -> START Basic Fields
    Redux::setSection( $opt_name, array(
        'title'     => __( 'Basic Field', 'redux-framework-demo' ),
        'id'        => 'basic',
        'desc'      => __( 'Basic field with no subsections.', 'redux-framework-demo' ),
        'icon'      => 'el el-home',
        'fields'    => array(
            'id'       => 'opt-text',
            'type'     => 'text',
            'title'    => __( 'Example Text', 'redux-framework-demo' ),
            'desc'     => __( 'Example description.', 'redux-framework-demo' ),
            'subtitle' => __( 'Example subtitle.', 'redux-framework-demo' ),
            'hint'     => array(
               'content' => 'This is a <b>hint</b> tool-tip for the text field.<br/><br/>Add any HTML based text you like here.',
           )            
        )
    ) );    

    Redux::setSection( $opt_name, array(
        'title' => __( 'Basic Fields', 'redux-framework-demo' ),
        'id'    => 'basic',
        'desc'  => __( 'Basic fields as subsections.', 'redux-framework-demo' ),
        'icon'  => 'el el-home'
    ) );    
    
    Redux::setSection( $opt_name, array(
        'title'      => __( 'Text', 'redux-framework-demo' ),
        'desc'       => __( 'For full documentation on this field, visit: ', 'redux-framework-demo' ) . '<a href="http://docs.reduxframework.com/core/fields/text/" target="_blank">http://docs.reduxframework.com/core/fields/text/</a>',
        'id'         => 'opt-text-subsection',
        'subsection' => true,
        'fields'     => array(
            array(
                'id'       => 'text-example',
                'type'     => 'text',
                'title'    => __( 'Text Field', 'redux-framework-demo' ),
                'subtitle' => __( 'Subtitle', 'redux-framework-demo' ),
                'desc'     => __( 'Field Description', 'redux-framework-demo' ),
                'default'  => 'Default Text',
            ),
        )
    ) );
    
    Redux::setSection( $opt_name, array(
        'title'      => __( 'Text Area', 'redux-framework-demo' ),
        'desc'       => __( 'For full documentation on this field, visit: ', 'redux-framework-demo' ) . '<a href="http://docs.reduxframework.com/core/fields/textarea/" target="_blank">http://docs.reduxframework.com/core/fields/textarea/</a>',
        'id'         => 'opt-textarea-subsection',
        'subsection' => true,
        'fields'     => array(
            array(
                'id'       => 'text-example',
                'type'     => 'textarea',
                'title'    => __( 'Text Area Field', 'redux-framework-demo' ),
                'subtitle' => __( 'Subtitle', 'redux-framework-demo' ),
                'desc'     => __( 'Field Description', 'redux-framework-demo' ),
                'default'  => 'Default Text',
            ),
        )
    ) );

**Comment by pxforti** [comment]
I think I figured out the problem. In your example code, you use the same id (text-example) for two text fields. Once I changed the name of the second occurance, it fixed the problem. Please update the code so it works when copied. Thanks

**Comment by dovy** [comment]
Updated. Good eye!
