### ISSUE TITLE
'Plugins' link redirected to the 'Redux welcome' page

### ISSUE THREAD

**Issue by Dannci** [reduxframework/redux-framework#2295]
Hi guys,

I'm getting this error on my demo site:
When I click on 'Plugins' link http://prntscr.com/71s36w (..wp-admin/plugins.php) page is redirected to the 'Redux welcome page' (..wp-admin/tools.php?page=redux-about). 
Redux is installed as plugin and when I disable/delete plugin, following message is visible: "You do not have sufficient permissions to access this page."

Notes:
- I've reinstalled wp core, disabled all plugins - nothing works.
- I cannot replicate issue on on other demo sites.
- link alternative: ...wp-admin/plugins.php?plugin_status=all  works fine
- no message in server's error_log

http://support.redux.io/?id=rpJ2%2FlC7JCHOSSlaIVoNmRPGdFNqrrvseOt3tggN8N9GLzByJvllX2O6blXI5eEmknf6M74qiK7q%2B9OSouzGFw%3D%3D

Thank you
Dannci

**Comment by dovy** [comment]
We can't reproduce. Can you please provide us WP login info and FTP login info at support@reduxframework.com and we'll try to log in and debug.  :)

**Comment by dovy** [comment]
Sorry for the delay in response. We just couldn't duplicate.

Also please update to the version of Redux in this repo. That may solve the issue.  :)

**Comment by Dannci** [comment]
Hello and thanks for getting back.

I'm running new theme on that installation and I've big traffic there. So I can live with it now and I'll get back (with login and FTP credentials) when traffic will be lower. 

Thank you

**Comment by mhennessie** [comment]
@dovy I am having this same issue. When ever I click Plugins->Installed it redirects me to the Redux About page at Tools->Redux Framework.
