### ISSUE TITLE
Options work

### ISSUE THREAD

**Issue by AminulBD** [reduxframework/redux-framework#2297]
Hi,

I've downloaded redux latest version and embeded in my TwentyFifteen theme, Then, I'm getting this result: http://s21.postimg.org/xaq38csnr/screenshot_15.png

Can you tell me why i'm getting blank option??

**Comment by sickmindNO** [comment]
Its because their CDN is not working.

**Comment by kprovance** [comment]
No, it's because some experimental code got recommitted, and needs to be fixed or removed.  It's being worked on.  It has nothing to do with any CDN.

**Comment by sickmindNO** [comment]
My mistake then. Well, it was to obvious to be that causing the error then.

**Comment by kprovance** [comment]
Render issue fixed with v.3.5.4.8
