### ISSUE TITLE
Assets CDN not working

### ISSUE THREAD

**Issue by sickmindNO** [reduxframework/redux-framework#2298]
Your CDN is not working, and it should be a fallback to local if CDN is down. I cant find the plugin to locally host assets either.

**Comment by kprovance** [comment]
Yeah, the entire point of a CDN is to get rid of the bloat people are complaining about.  Which CDN is not working?  You did not say.  it is because you are working locally without an internet connection?  If this is over the panels not rendering, that's a completely different issue being worked on.

**Comment by sickmindNO** [comment]
Every CDN requests is unavailable for assets. Added screenshot of errors.

![screenshot 2015-05-06 16 08 46](https://cloud.githubusercontent.com/assets/5708994/7494817/48597090-f40a-11e4-851d-871fbe139135.png)

**Comment by kprovance** [comment]
It would be HUGELY helpful if you would answer ALL my questions.  This way I do not have to ask twice, like now.

<blockquote>
 it is because you are working locally without an internet connection? 
</blockquote>

**Comment by sickmindNO** [comment]
Sorry, Both local, staging and production servers have the same error.

**Comment by kprovance** [comment]
Well, I cannot reproduce at this time.  My local and demo do not have these warnings.  They are designed to show when no internet connection can be established.

**Comment by sickmindNO** [comment]
Strange, I´ll look into it later then. Thanks.

**Comment by kprovance** [comment]
Fallback URL for support plugin added in v.3.5.4.8
