### ISSUE TITLE
SMOF to Redux conversion

### ISSUE THREAD

**Issue by tonyhogben** [reduxframework/redux-framework#2299]
I have a theme with SMOF embedded and want/need to convert to using Redux.

I have installed the Redux Converter 1.1.3.1 and Redux Framework 3.5.4.3 plugins and created the config file using the converter plugin.

I have copied the config file to my theme and included it in the themes functions.php file but it does not seem to be affecting anything as when I remove SMOF from functions.php I loose the SMOF 2 Redux menu item.

What am I doing wrong? #FeelingStupid

**Comment by kprovance** [comment]
Please do the following: http://docs.reduxframework.com/core/generating-a-support-hash/

**Comment by dovy** [comment]
You're not stupid at all, so don't go saying that.  ;)

Are you running Redux itself?

**Comment by tonyhogben** [comment]
Thanks Dovy.

I have installed the Redux Framework plugin and have the SMOF 2 Redux menu item (generated by the Redux Converter plugin I assume) but have not done anything else with the plugins (other than the afore mentioned attempt to generate the config php and include it in the theme).

So, when you ask "Are you running Redux itself?", I'm afraid I'm not 100% sure what you mean.

**Comment by dovy** [comment]
You have the plugin installed. That's great. Have you included your config file in your functions.php page?

**Comment by tonyhogben** [comment]
I have included the ReduxFramework.config.php generated by the Convert to Redux! area in the SMOF 2 Reux menu item - is this the correct config file?

In functions.php I have (at the top of the file)...

    require_once('admin/index.php'); //SMOF admin panel
    require_once('ReduxFramework.config.php');

**Comment by dovy** [comment]
Can you http://gist.github.com that config file?

**Comment by tonyhogben** [comment]
Sure... https://gist.github.com/tonyhogben/36f411cf5e4b8b1dde9d

**Comment by tonyhogben** [comment]
Did that help Dovy?

**Comment by dovy** [comment]
Sorry, I've been preping for our webinar today. I forgot to get back to you! I'll look at this tomorrow. My bad.

**Comment by kprovance** [comment]
Has this issue been resolved?

**Comment by tonyhogben** [comment]
Hi Kevin,

Thanks for following up. Unfortunately, the deadline meant I had to abandon
the theme I was attempting to repair in favor of another.



Tony Hogben.
mtstudios - websites, apps, digital

*Please use our new ticketing system to contact us*:
Raise a new support ticket here <http://mtstudios.net/support>
Request an alteration to your website here <http://mtstudios.net/feature>

mtstudios ltd
Second Floor
49-51 High Street
Deal
CT14 6EL

**Comment by kprovance** [comment]
Okay, thanks.  Closing issue.

**Comment by gangesh** [comment]
Issue still exists.
Here is code generated by converter.

https://gist.github.com/gangesh/19271a6e9218bc96e2290373c9a6f8d3

And here is what I am adding in functions.php

` require_once (dirname(__FILE__) . '/sample/ReduxFramework.config.php'); `

If I use sample config file everything work fine.

Any clue why it isn't working?

Thanks in advance.
