### ISSUE TITLE
I have issue in my html theme in themeforest

### ISSUE THREAD

**Issue by hamdan-mahran** [reduxframework/redux-framework#2301]
Hello,
( Sorry for my bed English language )
I'm author in themeforest, and i have issue on my html on the iPhone and iPad,
And i don't have IPad or iPhone. 
If i register in your premium support. can you fix it for me ? :)

Thanks!

**Comment by dovy** [comment]
It really depends on the issue. Can you first do this?
http://docs.reduxframework.com/core/generating-a-support-hash/

**Comment by hamdan-mahran** [comment]
Hello @dovy 
Its not in Redux, its in jquery :)

**Comment by hamdan-mahran** [comment]
This is my theme in themeforest,
http://themeforest.net/item/enar-responsive-multipurpose-html5-template/11107340

**Comment by dovy** [comment]
Awesome. Best of luck! I've added your theme to the showcase.

If you like Redux, or the support we render, please do some or all of the following:
* Donate to keep us going: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=MMFMHWUPKHKPW
* Review us: http://wordpress.org/support/view/plugin-reviews/redux-framework
* Like us: http://facebook.com/ReduxFramework
* Follow us: http://twitter.com/ReduxFramework
