### ISSUE TITLE
Form values not updated when saved when validated

### ISSUE THREAD

**Issue by Enchiridion** [reduxframework/redux-framework#2302]
I have a panel with a field that I'm using a regexp validator on it.  Currently I'm using your example code:

```
'validate' => 'preg_replace',
'preg' => array(
    'pattern' => '/[^a-zA-Z_ -]/s', 
    'replacement' => 'no numbers'
)
```

The validator works as excepted, however the value on the form isn't updated upon saving when ```ajax_save``` is true.

For example if I type 'Foo Bar 1' into the field then click Save Changes, the form will still say 'Foo Bar 1'.  However if I look in the database, it was saved as 'Foo Bar no numbers' as it should be.  If I refresh the page then the field will then show the correct value.
If I turn ```ajax_save``` off, then click Save Changes, the form reloads with the correct value.

**Comment by kprovance** [comment]
Please provide a support URL.

**Comment by kprovance** [comment]
So, I've just been told preg_replace will not do any real time replacement with ajax save enabled.  I imagine there must be a way to make it work - and if you'd like to contribute code to make that happen, that'd be awesome.  otherwise, we'd probably need some financial backing to dig into such an endevour.

**Comment by dovy** [comment]
Validation will show if there is an error, and there will be a warning if the value if different (I believe).

But there's no way, with the complexities of Redux, to dynamically update the input fields too without substantial effort.  :(
