### ISSUE TITLE
Option menu does not appear sometimes

### ISSUE THREAD

**Issue by drosa88** [reduxframework/redux-framework#2303]
Hi guys,

sometimes users write me that the option menu for my plugin does not appear. (Alltough the ReduxFramework Plugin is installed and activated). I require your framework after activating my plugin with this class helper: http://tgmpluginactivation.com/

My file head:
```
// Security
if ( ! defined( 'ABSPATH' ) ) exit; // Exit if accessed directly

/**
 * Options requirements
 */

if ( file_exists( dirname( __FILE__ ) . '/admin/class-tgm-plugin-activation.php' ) ) {
  require_once( dirname( __FILE__ ) . '/admin/class-tgm-plugin-activation.php' );
}
if ( !isset( $dd_options ) && file_exists( dirname( __FILE__ ) . '/admin/options.php' ) ) {
  require_once( dirname( __FILE__ ) . '/admin/options.php' );
}
```
Any idea? Thanks in advance!

**Comment by kprovance** [comment]
Are you able to reproduce?

**Comment by drosa88** [comment]
unfortunately no :(

**Comment by kprovance** [comment]
I don't know.  You're going to have to do some legwork with your client and their setup to make that determination.  We do not have the resources to do support for your clients, that is, reproduce it on your end and report back to us those specific circumstances.

**Comment by dovy** [comment]
Here's a suggestion. Get the offending client to provide you with a support URL. ;)

**Comment by dovy** [comment]
That will at least tell you their PHP version...

**Comment by drosa88** [comment]
I´m in contact with this guy, so i can ask him directly :) He uses the php version 5.3 ... do you have other questions?

Thank you again!

**Comment by dovy** [comment]
@drosa88 I'm saying that you should do the support URL. We cannot provide support for something that's probably a server issue without premium support. Should you keep trying and not be able to get the info, unless you provide the support URL we can't help further.

So I was just suggesting for good measure that you provide the support URL.  ;)

**Comment by drosa88** [comment]
Oh, i missunderstood you because of my average english, i´,m sorry :-) Unfortunately I get no data. But it´s no problem..i don´t wanted support for users of my plugin..i tought that the fault maybe is located on my own code, maybe because of including your framework not correctly.

If you says me that everything is fine with including, is not has to be my problem when the framework does not work because of old php versions or other not given conditions.

Greetings!

**Comment by kprovance** [comment]
Closing the ticket, then.
