### ISSUE TITLE
Accordion wont work - why ?

### ISSUE THREAD

**Issue by ivovk9** [reduxframework/redux-framework#2304]
Hello,

I am now testing the Accordion - http://docs.reduxframework.com/extensions/accordion/

And it wont show icons: plus and minus...

What I need to do to get icons for plus and minus ?

this below is just test code and it is not working, I mean there is no icon... 

array(
    'id'        => 'opt-accordion-begin-1',
    'type'      => 'accordion',
    'title'     => 'Accordion Section One',
    'subtitle'  => 'Section one with subtitle',
	'open-icon'=> 'el-plus',
    'position'  => 'start', 
),
    array(
        'id'       => 'opt-blank-text-1',
        'type'     => 'text',
        'title'    => 'Textbox for some noble purpose.',
        'subtitle' => 'Frailty, thy name is woman!'
    ),
    array(
        'id'       => 'opt-blank-text-2',
        'type'     => 'switch',
        'title'    => 'Switch, for some other important task!',
        'subtitle' => 'Physician, heal thyself!'
    ),             
array(
    'id'        => 'opt-accordion-end-1',
    'type'      => 'accordion',
    'position'  => 'end'
),

Thank you

**Comment by kprovance** [comment]
Accordion is a premium extension.  You need to purchase it first.  http://reduxframework.com/extension/accordion/

**Comment by ivovk9** [comment]
ok. I did not know that. 

Thank you
