### ISSUE TITLE
syntax error while activating theme - class-tgm-plugin-activation.php on line 523

### ISSUE THREAD

**Issue by ecuras** [reduxframework/redux-framework#2305]
Hello,

I created a custom theme using ReuxBuilder, uploaded it on a clean Wordpress install, downloaded the redux plugin.  Then when I was activating it I received the following error:

"
( ! ) Parse error: syntax error, unexpected '<<' (T_SL) in F:\Wamp\www\sb1\wp-content\themes\LastThemeVer2\admin\tgm\class-tgm-plugin-activation.php on line 523
Call Stack
#	Time	Memory	Function	Location
1	0.0020	233072	{main}( )	..\themes.php:0
2	0.0040	276552	require_once( 'F:\Wamp\www\sb1\wp-admin\admin.php' )	..\themes.php:10
3	0.0040	287976	require_once( 'F:\Wamp\www\sb1\wp-load.php' )	..\admin.php:31
4	0.0050	295584	require_once( 'F:\Wamp\www\sb1\wp-config.php' )	..\wp-load.php:37
5	0.0060	357264	require_once( 'F:\Wamp\www\sb1\wp-settings.php' )	..\wp-config.php:82
6	0.6330	25389840	include( 'F:\Wamp\www\sb1\wp-content\themes\LastThemeVer2\functions.php' )	..\wp-settings.php:329
7	0.6350	25394688	require( 'F:\Wamp\www\sb1\wp-content\themes\LastThemeVer2\admin\admin-init.php' )	..\functions.php:12
8	0.6380	25397648	require_once( 'F:\Wamp\www\sb1\wp-content\themes\LastThemeVer2\admin\tgm\tgm-init.php' )	..\admin-init.php:5
"

I tried these steps twice on both local and remote installs.  

I am not knowledgeable in coding so appreciate your help with this matter a lot.

Thank you,
-Ben

**Comment by kprovance** [comment]
TGM changed repos, apparently.  Until we can update our builder to compensate, you'll have to replace the TGM files in your project with the ones from here:  https://github.com/TGMPA/TGM-Plugin-Activation

**Comment by ecuras** [comment]
Thank you so much.  That solved the issue!

**Comment by dovy** [comment]
Glad it's working!  :)

If you like Redux, or the support we render, please do one or all of the following:
* Donate to keep us going: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=MMFMHWUPKHKPW
* Review us: http://wordpress.org/support/view/plugin-reviews/redux-framework
* Like us: http://facebook.com/ReduxFramework
* Follow us: http://twitter.com/ReduxFramework
