### ISSUE TITLE
Using options in functions.php (Result: NULL)

### ISSUE THREAD

**Issue by drosa88** [reduxframework/redux-framework#2306]
Hi guys,

i´m working on another project with your framework and everything goes well! Now unfortunately i got the first problem: I want to use one option in my functions.php. But the array always gives me NULL.

My code:

```
global $dd_options;
echo var_dump($dd_options);
echo var_dump($dd_options['option-startseite-page']);
```
The answer for both is NULL. When i include this lines in another file, for example header.php, i receive the array correctly. So with the global variable everything is fine.. it´s not possible to get the option array in the functions.php file?

Above i call your plugin:
```
if ( !isset( $dd_options ) && file_exists( dirname( __FILE__ ) . '/admin/options.php' ) ) {
  require_once( dirname( __FILE__ ) . '/admin/options.php' );
}
```
Maybe by setting the $dd_options as global variable for the server exist and so the options-file will not loaded?

Thanks in advance and sorry for too many questions!

**Comment by kprovance** [comment]
Thank you for posting on the Redux Issue tracker. In order for us to begin debugging your issue, we need you to first generate a support URL. You can learn about how you generate that here: http://docs.reduxframework.com/core/generating-a-support-hash/

Please update this ticket with the support URL when you have it. Thank you.

**Comment by dovy** [comment]
Actually, I know this issue without that.

It's because Redux doesn't load by default until after init. functions.php runs before init.

So, you can force the loading of Redux this way:
```
Redux::init( 'OPT_NAME' );
```

Just be sure you've set all your sections and such before that.  ;)

**Comment by drosa88** [comment]
Works, thanks! You get another donation! :+1:

**Comment by dovy** [comment]
Ty. ;)

**Comment by udarts** [comment]
Sorry to ask this, but where do I put: Redux::init( 'OPT_NAME' );

I have put it at the bottom of my options-init.php, which is where the admin options are constructed.

**Comment by dovy** [comment]
After you've declared your options and before you try using them.

**Comment by udarts** [comment]
Ok, thanks, in my functions.php, I call the redux framework (embedded in my theme), like the following:

    function sportentrainer_setup() {

	/*
	 * Add Redux Framework
	 */
	require get_template_directory() . '/admin/admin-init.php';

    }
    add_action( 'after_setup_theme', 'sportentrainer_setup' );

    Redux::init('some_fw');

    global $some_fw;

    print_r($some_fw);

I get an error: Fatal error: Uncaught Error: Class 'Redux' not found in ...... 
In the admin-init.php, I load the following:

    if ( file_exists( dirname( __FILE__ ).'/ReduxCore/framework.php' ) ) {
         require_once dirname(__FILE__).'/ReduxCore/framework.php';
    }
    if ( file_exists( dirname( __FILE__ ) . '/options-init.php' ) ) {
        require_once dirname( __FILE__ ) . '/options-init.php';
    }
    if ( file_exists( dirname( __FILE__ ) . '/page-options-init.php' ) ) {
        require_once dirname( __FILE__ ) . '/page-options-init.php';
    }
    if ( file_exists( dirname( __FILE__ ) . '/loader.php' ) ) {
        require_once dirname( __FILE__ ) . '/loader.php';
    }

**Comment by kprovance** [comment]
Because the call to Redux::init is running before the code in the action hook.  The code in the action hook runs after, since it's in a hook.

**Comment by udarts** [comment]
Ah, yes, your are correct, I moved the admin-init.php part outside the function and now it works.

Thanks.

**Comment by prionkor** [comment]
As a sidenote you should require the `options.php` file at the top of the `functions.php` file to avoid further issue.

**Comment by maheraldous** [comment]
In my functions.php I write this code to make the $aldous_vera_park work but it's still not work and I am not sure how to use Redux::init('aldous_vera_park'); @dovy 
`global $aldous_vera_park;

Redux::init('aldous_vera_park');

function my_styles_method() {
  	wp_register_style('style', get_template_directory_uri() . '/style.css', false, null);
	wp_enqueue_style('style');
        $color = $aldous_vera_park['hover-color'];
        $custom_css = "
                .filter-item-content a {
					font-size: 13px;
					color: $color;
				}
				";
        wp_add_inline_style( 'style', $custom_css );
}
add_action( 'wp_enqueue_scripts', 'my_styles_method' );`

**Comment by TakiDDine** [comment]
> Redux::init('aldous_vera_park');

thank you so much ! this helped me show the options in functions.php
