### ISSUE TITLE
"Options Object" in Options Menu

### ISSUE THREAD

**Issue by jaschaio** [reduxframework/redux-framework#2307]
After updating to v3.5.4.8 I got a new Item in my Admin Panel called "Options Object":

![image](https://cloud.githubusercontent.com/assets/11058666/7533303/8ff7caac-f570-11e4-9edc-973666bc45c7.png)
![image](https://cloud.githubusercontent.com/assets/11058666/7533315/aed7fe2e-f570-11e4-880d-ac5a8aa40c14.png)

No idea where it came from and how to delete this section.

**Comment by kprovance** [comment]
It's part of dev_mode being set to true.  Your end users will not see it.
