### ISSUE TITLE
redux_notice.json failed to open stream

### ISSUE THREAD

**Issue by azexo** [reduxframework/redux-framework#2309]
My site output this message:

Warning: file_get_contents(http://www.reduxframework.com/wp-content/uploads/redux/redux_notice.json): failed to open stream: Connection timed out in

Can I fix it somehow or this is bug?

**Comment by AlexAlexandru** [comment]
This is because reduxframwork.com is down. The redux framework (plugin) is making a connection to reduxframework.com to display some informations but the website is down.Thats why you see that error.So you will have to wait until the reduxframework.com website is back online not a big deal.

**Comment by kprovance** [comment]
Site was rebooting.  It's back up.  Regardless, I'll code in some trapping for such a condition so no error displays in the future.  :)

**Comment by Blavish** [comment]
Hi, is the site rebooting again because i'm getting this error 

Warning: file_get_contents(http://www.reduxframework.com/wp-content/uploads/redux/redux_notice.json) [function.file-get-contents]: failed to open stream: Connection refused in www/blog/wp-content/themes/blackmag/components/redux-framework/ReduxCore/inc/class.redux_filesystem.php on line 186

**Comment by f-lungov** [comment]
Same here.

**Comment by dovy** [comment]
I'm getting sick of this, haha. Moving to a new host today. I'll try to get things up ASAP.

**Comment by kprovance** [comment]
Half you folks need to pont up support urls/hashes, coz maybe your using old versions of Redux?  I just went through the code, and I can find no references to the filesystem.

**Comment by Blavish** [comment]
Thanks, its all good now :)

**Comment by viniciusbig** [comment]
So, years later..

redux framework is dead, right? in favor of version 4?
Is that correct?

So this URL is definitely down now, right?
