### ISSUE TITLE
Translating custom options

### ISSUE THREAD

**Issue by Ryu-k** [reduxframework/redux-framework#2311]
Redux Framework embed v3.5.4.2
wordpress 4.2.1
not in dev mode

I am trying to translate the custom options I added to my redux panel option but it seems that the translation doesn't take effect.

I searched in the documentation but didn't find if I needed to add something in the theme functions.php in order to make the translation take effect.

My theme only use load_theme_textdomain, do I need anything else?

Anyone help would be appreciated!

**Comment by kprovance** [comment]
This issue has been asked and answered numerous times:  https://github.com/reduxframework/redux-framework/search?q=load_theme_textdomain&type=Issues&utf8=%E2%9C%93
