### ISSUE TITLE
 failed to open stream: HTTP request failed! in /xxxxxx/wp-content/plugins/redux-framework/ReduxCore/inc/class.redux_filesystem.php on line 186

### ISSUE THREAD

**Issue by JohanRoosien** [reduxframework/redux-framework#2312]
Hello,

We have an issue when opening the page. The following error is displayed at the top of the page:

Warning: file_get_contents(http://www.reduxframework.com/wp-content/uploads/redux/redux_notice.json) [function.file-get-contents]: failed to open stream: HTTP request failed! in xxxx/public_html/wp-content/plugins/redux-framework/ReduxCore/inc/class.redux_filesystem.php on line 186

We have Wordpress 4.2.2 and Redux Framework version 3.5.4.8. Is there a solutions for this problem? 

Kind regards,
Johan Roosien

**Comment by kprovance** [comment]
The site might have been down.  It appears to be up now.  This will be addressed in the next release.

**Comment by JohanRoosien** [comment]
Hello,

One our later and we still have the error message. Do we need to do something?

**Comment by kprovance** [comment]
Just pushed v3.5.4.9 with error suppression.  See if that helps.

**Comment by JohanRoosien** [comment]
Thanks! it worked!

**Comment by dovy** [comment]
If you like Redux, or the support we render, please do one or all of the following:
* Donate to keep us going: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=MMFMHWUPKHKPW
* Review us: http://wordpress.org/support/view/plugin-reviews/redux-framework
* Like us: http://facebook.com/ReduxFramework
* Follow us: http://twitter.com/ReduxFramework
