### ISSUE TITLE
Error sometimes when displaying the typography option

### ISSUE THREAD

**Issue by peterigz** [reduxframework/redux-framework#2313]
I have a panel with an option to choose a font and it wasn't displaying properly and displaying a *'can't read property length of undefined'*. This was originating from line 396 of field_typography.js where the $.each function was trying to use details.variants which didn't exists.

Looking back through the code I could see that *family* was not being set because for some reason although the selector was finding the (in this case) '#opt-menu-font #opt-menu-font-family' element, val() was returning an empty value rather then the font it should have been. It was only happening on this panel which only has the one font selector. I have other panels with font selectors and they work ok.

I've fixed the issue by making it get the font from the placeholder attribute if there's no value and that seems to work fine, but I don't know enough about the code to know if this is a good solution or not. This is what I changed from line 320:

        var family = $( '#' + mainID + ' #' + mainID + '-family' ).val();

        if ( !family ) {
            family = $( '#' + mainID + ' #' + mainID + '-family' ).attr('placeholder');
            if(!family) {
                family=null;
            }
        }

**Comment by kprovance** [comment]
It would be helpful if I could recreate the issue first.  Please post back a support URL:  Please do the following: http://docs.reduxframework.com/core/generating-a-support-hash/

**Comment by peterigz** [comment]
Typical, I find exactly why moments after I post. It's because I had defined the same option id in 2 different panels, so not a bug in redux at all, just my brain! Sorry :)

**Comment by kprovance** [comment]
Yeah, that would do it.  Glad you figured it out.  :)
