### ISSUE TITLE
http://reduxframework.com/docs is down

### ISSUE THREAD

**Issue by pxforti** [reduxframework/redux-framework#2315]
Are you aware that the site has been down on and off since yesterday.

**Comment by kprovance** [comment]
Yes, it's being worked on.  Please be patient with us.  Thanks.  :)

**Comment by pxforti** [comment]
Thanks!

> On May 11, 2015, at 4:28 PM, Kevin Provance <notifications@github.com> wrote:
> 
> Yes, it's being worked on. Please be patient with us. Thanks. :)
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/reduxframework/redux-framework/issues/2315#issuecomment-101066307>.
> 

------
Pat Fortino
writenowdesign.com <http://writenowdesign.com/>

====================
- Website Design
- WordPress Website Design
- Joomla Website Design
- Ecommerce Websites
