### ISSUE TITLE
Button_set not working with folding

### ISSUE THREAD

**Issue by meno010** [reduxframework/redux-framework#2316]
Hello,
 We are using
Redux 3.5.4.8.
Redux in dev_mode.
WordPress 4.0.5.
Mozilla Firefox 37.0.2.

When try 3 button_set for 3 info fields, if disable one it's disable all fields !!

				 array(
                            'id'       => 'info-p',
                            'type'     => 'button_set',
                            'title'    => __( 'Active Banners', 'redux-framework-demo' ),
                            'subtitle' => __( 'No validation can be done on this field type', 'redux-framework-demo' ),
                            'desc'     => __( 'This is the description field, again good for additional info.', 'redux-framework-demo' ),
                            'multi'    => true,
                            //Must provide key => value pairs for radio options
                            'options'  => array(
                                '1' => 'Banner #1',
                                '2' => 'Banner #2',
                                '3' => 'Banner #3'
                            ),
                            'default'  => array( '1','2','3')
                        ),
						
							  array(
                            'id'     => 'opt-notice-info1',
                            'type'   => 'info',
                            'style'  => 'info',
                            'title'  => __( '<font color="red">info #1</font>', 'redux-framework-demo' ),
								'required' => array('info-p', '=' , '1')
                        ),
						
							  array(
                            'id'     => 'opt-notice-info2',
                            'type'   => 'info',
                            'style'  => 'info',
                            'title'  => __( '<font color="red">info #2</font>', 'redux-framework-demo' ),
								'required' => array('info-p', '=' , '2')
                        ),
						
							  array(
                            'id'     => 'opt-notice-info3',
                            'type'   => 'info',
                            'style'  => 'info',
                            'title'  => __( '<font color="red">info #3</font>', 'redux-framework-demo' ),
								'required' => array('info-p', '=' , '3')
                        ),

Why this happen?

**Comment by kprovance** [comment]
It would be helpful if I could recreate the issue first. Please post back a support URL: Please do the following: http://docs.reduxframework.com/core/generating-a-support-hash/

**Comment by meno010** [comment]
Your site has an Error

Oh no!
If you are able to read this message, you are normal and we are not.

We will be back soon!

**Comment by kprovance** [comment]
You don't have to go to that page.  You only need paste back the URL, please.

**Comment by meno010** [comment]
I'm too sorry. I can't understand what did you mean ?
What's the URL and where we must paste back the URL ?

**Comment by dovy** [comment]
Our doc site is back. Please go look here: http://docs.reduxframework.com/core/generating-a-support-hash/

**Comment by meno010** [comment]
Here you are
http://support.redux.io/?id=wIrbM6iYIJBW%2FnX4lUPmFLKBC2PQBCazgM45APUbqpZ1uQ%2Bq7%2B%2FrhLtf%2Fm9QAajF%2B9uovpfGEnDc2IGS3cLElw%3D%3D

**Comment by dovy** [comment]
ooohhhh, multi button set. Yea. This is a bug. Kevin care to give it a try?

**Comment by kprovance** [comment]
Use the `contains` evaluator, instead of `=`.

**Comment by meno010** [comment]
@kprovance  Thank you too much.
if we add redux to theme can we remove copyrights ?

**Comment by dovy** [comment]
You can change the footer text all you want. Just remember us when you're making money and give back, especially for things like this: https://ideas.reduxframework.com/campaigns/complete-customizer-integration/

If you like Redux, or the support we render, please do one or all of the following:
* Donate to keep us going: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=MMFMHWUPKHKPW
* Review us: http://wordpress.org/support/view/plugin-reviews/redux-framework
* Like us: http://facebook.com/ReduxFramework
* Follow us: http://twitter.com/ReduxFramework

**Comment by meno010** [comment]
If we did we can't forget you and your pro work.
I respect @kprovance and @dovy too much.

but need ask you @dovy .
i work to create jquery code to repeat fields by add more and remove 
but faced some  problem can you help ? 
because we can't buy repeater addon now.
even you can't . Thank you

**Comment by dovy** [comment]
Sorry, but that was a LOT of work. So I can't just give you the code away. You'd have to buy the extension.  But hey, in doing so you support the project!  :)

**Comment by meno010** [comment]
This extension 1 time  fee for any theme or to one theme only ?

**Comment by dovy** [comment]
Every extension is per theme. :)

That way as you make new themes and make more money, you help to keep the project alive.

**Comment by meno010** [comment]
If css, js or any files on CDN servers,How we can change it to local server ?

**Comment by dovy** [comment]
We have a plugin coming out soon, but that's the dev build. You're welcome to use the last tagged release version of Redux to get the local version of the css/js files.

**Comment by meno010** [comment]
How we will get last tagged release version of Redux to get the local version of the css/js files ?

**Comment by dovy** [comment]
I have other things to do, but there's a releases tab up above or you can grab it from WordPress.org.  ;)
