### ISSUE TITLE
Force Disable Developer Mode on Localhost?

### ISSUE THREAD

**Issue by blacklistedgod** [reduxframework/redux-framework#2317]
I noticed that developer mode still active in localhost even if its already set to false, 

is there a way to forcefully disable it? 

if I enable Query Monitor with developer mode enabled, the values would display below the option panel in an array format which is kind of annoying. 

http://i.imgur.com/35PzDHA.png

**Comment by kprovance** [comment]
This is by design now, and cannot be disabled.  Sorry.

**Comment by dovy** [comment]
You could manually go in and comment out our code.

The reason we did this was at request of developers forgetting to enable dev_mode again.  Haha.

Now we're getting the opposite reaction.
