### ISSUE TITLE
Cool Options

### ISSUE THREAD

**Issue by emc390** [reduxframework/redux-framework#2318]
Where can I set up the editor to Add New Post?
What you could edit Kohl OPTIONS. As illustrated in the DEMO: http://demo.redux.io/wp-admin/post-new.php
Thanks

**Comment by dovy** [comment]
That's one of our extensions called Metaboxes. You can grab it here: http://reduxframework.com/extensions/metaboxes/

Best of luck!

**Comment by emc390** [comment]
cool options
