### ISSUE TITLE
PHP Warning

### ISSUE THREAD

**Issue by getbowtied** [reduxframework/redux-framework#2320]
From one of our clients:

Hi,

Since the latest SK update my server error logs are filled up with warnings about the redux framework, see examples below.

Can you please help?

Thanks 
Kevin

We are using redux v3.5.4.6.

5/10/2015 3:40:02 PM - PHP Warning: file_get_contents(http://www.reduxframework.com/wp-content/uploads/redux/redux_notice.json): failed to open stream: no suitable wrapper could be found in /var/www/vintageheirloom.com/wp-content/themes/shopkeeper/settings/redux/ReduxCore/inc/class.redux_filesystem.php on line 186

5/10/2015 3:40:02 PM - PHP Warning: file_get_contents(): http:// wrapper is disabled in the server configuration by allow_url_fopen=0 in /var/www/vintageheirloom.com/wp-content/themes/shopkeeper/settings/redux/ReduxCore/inc/class.redux_filesystem.php on line 186

**Comment by dovy** [comment]
Please get a support URL and post it here. Also try to get WordPress and FTP info.

**Comment by kprovance** [comment]
Closing issue due to lack of reply.  Please feel free to open a new issue with the required information should you want us to explore this further.
