### ISSUE TITLE
Select with Custom Post and Category

### ISSUE THREAD

**Issue by AKlossner** [reduxframework/redux-framework#2321]
I want to populate a select field with both custom post and custom taxonomy(category) into a single select field.  I can only get one to work at a time... I want to combine the two

array(
	'id'        => 'slide1-btn-url',
	'type'      => 'select',
	'data'      => 'posts',
	'args' => array('post_type' => array('sleepography', 'page'), 'posts_per_page' => -1),
	'title'     => __('Button Link', 'redux-framework-demo'),
	'subtitle'  => __('Which page the visitor is sent to when clicking this button', 'redux-framework-demo'),
),
array(
	'id'        => 'slide1-btn-url2',
	'type'      => 'select',
	'data'      => 'category',
	'args' => array('taxonomy' => array('collections'), 'posts_per_page' => -1),
	'title'     => __('Button Link', 'redux-framework-demo'),
	'subtitle'  => __('Which page the visitor is sent to when clicking this button', 'redux-framework-demo'),	

I tried..
array(
	'id'        => 'slide1-btn-url',
	'type'      => 'select',
	'data'      => array('posts','category'),
	'args' => array(array('post_type' => array('sleepography', 'page'), 'posts_per_page' => -1),array('taxonomy' => array('collections'), 'posts_per_page' => -1)),
	'title'     => __('Button Link', 'redux-framework-demo'),
	'subtitle'  => __('Which page the visitor is sent to when clicking this button', 'redux-framework-demo'),

But it didn't work...

**Comment by dovy** [comment]
So, to do something like that you'e going to have to do your own custom data argument.

```
array(
'id' => 'slide1-btn-url',
'type' => 'select',
'data' => 'CALL_THIS_ANYTHING',  // This is your custom arg for your data argument
'args' => array(array('post_type' => array('sleepography', 'page'), 'posts_per_page' => -1),array('taxonomy' => array('collections'), 'posts_per_page' => -1)),
'title' => __('Button Link', 'redux-framework-demo'),
'subtitle' => __('Which page the visitor is sent to when clicking this button', 'redux-framework-demo'),
```

Then you need to hook into that:
```
add_filter("redux/options/OPT_NAME/wordpress_data/CALL_THIS_ANYTHING/", 'custom_select_data');
function custom_select_data() {
   // Do my custom query to get whatever I want, and shove into a variable. Then return it
   return $data;
}
```

Just be sure to replace the OPT_NAME, and come up with your own custom data key.  ;)
