### ISSUE TITLE
WPML not working for the front-end 4.2?

### ISSUE THREAD

**Issue by mfreeman3769** [reduxframework/redux-framework#2322]
Hi,

Great product!

I'm trying to debug a Theme (not mine) and I added WPML translation for Redux as per documentation. I have tried a lot of things but I'm not familiar with Redux or WPML.

The strings appear correctly in the WPML string translation.

However the translations do not show on the site, nothing but the original ones...The header code that calls the translations is for a slider: $slides

Below, the Header PHP code (original)
'
<?php if($enablePulseSlider === 'yes') { ?>
                <?php
                    global $vienna_options;
                    $slides = '';
                    if( isset($vienna_options['opt-pulse-slides']) && !empty($vienna_options['opt-pulse-slides']) ){
                        $slides = $vienna_options['opt-pulse-slides']; 
                    }
                ?>

if(is_array($slides)) :
                        $sliderCounter = 0;
                        if(count($slides) > 0){
                            echo '<div class="pm-pulse-container" id="pm-pulse-container">';
                                echo '<div id="pm-pulse-loader"><img src="'.get_template_directory_uri().'/js/pulse/img/ajax-loader.gif" alt="slider loading" /></div>';
                                echo '<div id="pm-slider" class="pm-slider">';
                                    echo '<div id="pm-slider-progress-bar"></div>';
                                    echo '<ul class="pm-slides-container" id="pm_slides_container">';
                                        foreach($slides as $s) {
                                            $btnText = '';
                                            $btnUrl = '';
                                            if(!empty($s['url'])){
                                                $pieces = explode(" - ", $s['url']);
                                                $btnText = $pieces[0];
                                                $btnUrl = $pieces[1];
                                            }
                                            echo '<li data-thumb="'.$s['image'].'" class="pmslide_'.$sliderCounter.'"><img src="'.$s['image'].'" alt="img01" />';
                                                echo '<div class="pm-holder">';
                                                    echo '<div class="pm-caption">';
                                                          if( !empty($s['title']) ){
                                                              echo '<h1><span>'.__($s['title'], 'viennatheme').'</span></h1>';
                                                          }
                                                          if( !empty($s['description']) ){
                                                              echo '<span class="pm-caption-decription">';
                                                                echo __($s['description'], 'viennatheme');
                                                              echo '</span>';
                                                          }
 
                                                          if($btnText !== ''){
                                                             echo '<a href="'.$btnUrl.'" class="pm-slide-btn animated">'.__($btnText, 'viennatheme').' <i class="fa fa-chevron-right"></i></a>';
                                                          }
                                                    echo '</div>';
                                                echo '</div>';
 
                                            echo '</li>';
 
                                            $sliderCounter++;
                                        }
                                    echo '</ul>';
                                echo '</div>';
                            echo '</div>';
                        }//end of if
                    endif;
'

I tried using:
$slides = get_option( 'opt-pulse-slides', ' ' );
I get an empty $slides, nothing...

As I know 4.2 broke a few things with WPML - I wonder if it is not the cause of this bug. 

Also found this:
"You also want to load your text_domain BEFORE your Redux Options are run, and not within any hook or the strings won't be translated before they're used." 

Not sure what it means...

**Comment by dovy** [comment]
You'd need to do:
$data = get_option('vienna_options');
$slides = $data['opt-pulse-slides'] and it should work...

If not, it's a WPML thing which they need to resolve.  :)

**Comment by mfreeman3769** [comment]
Hi,  Thanks !!!!

Now $slides are not empty, but still only appear in one language, English...
Any other ideas? Weird, that the strings are properly displayed in WPML String Translation

**Comment by dovy** [comment]
No idea my friend. Did you declare those values properly as the sample wpml.xml in the repo?

Sorry, but these are questions for WPML, not us.

**Comment by mfreeman3769** [comment]
What does this imply: "You also want to load your text_domain BEFORE your Redux Options are run, and not within any hook or the strings won't be translated before they're used." ?

**Comment by dovy** [comment]
That's for custom translation files. It doesn't apply to WPML.

**Comment by mfreeman3769** [comment]
I saw it in context of WPML, but was not sure. You actually mentioned it on ticket #1064
https://github.com/reduxframework/redux-framework/issues/1064

Thanks again !  (Yeah did everything according to docs.)

**Comment by dovy** [comment]
Sorry. WPML is quite the beast when it's not working. heh.
