### ISSUE TITLE
Spacing not working in editor field

### ISSUE THREAD

**Issue by Aohor** [reduxframework/redux-framework#2323]
I'm using redux latest version with tgm plugin activator. My Wordpress is also the latest version.

My problem is spacing is not working for editor field. my setup:
array(
'id'       => 'about-desc',
 'type'      => 'editor',
 'title'     => __('About Area Description.', 'imd'),
'validate'     => 'html'
),

if I want to make some space, then I have to switch back to text mode & put <br/> tag manually. visual editor is not working properly when creating spacing between the paragraph or line. what is the solution?

**Comment by dovy** [comment]
Umm. I don't know enough about the editor personally. Since we're open source, do you care to take a stab at fixing it?

Just turn dev_mode => true, and modify the JS and PHP inside ~/ReduxCore/inc/fields/editor/

Your contribution will literally help hundreds of thousands of users!  :)

**Comment by kprovance** [comment]
Closing issue since no reply has come in over the last two days.
