### ISSUE TITLE
Single Checkbox Desc

### ISSUE THREAD

**Issue by davidcasey** [reduxframework/redux-framework#2324]
The description (desc) is not lining up with the single checkbox as specified in the API. Rather, it is placing it below. (This is in a metabox.) I'd be happy to use a Multi Checkbox, which works correctly. However, I need to require it as checked, and apparently that is not supported: https://github.com/reduxframework/redux-framework/issues/1629
```
array(
    'id'       => 'opt_checkbox',
    'type'     => 'checkbox',
    'title'    => __('Checkbox Option', 'redux-framework-demo'),
    'subtitle' => __('No validation can be done on this field type', 'redux-framework-demo'),
    'desc'     => __('This is the description field, again good for additional info.', 'redux-framework-demo'),
    'default'  => '1'// 1 = on | 0 = off
)
```
![screen shot 2015-05-14 at 11 25 54 am](https://cloud.githubusercontent.com/assets/744677/7637633/891affa4-fa2c-11e4-9ddb-d98bd308d13a.png)

**Comment by kprovance** [comment]
Metabox is a premium extension. Please post extension issues to it's issue tracker.  Thanks.
