### ISSUE TITLE
Consider: List of actions and filters.

### ISSUE THREAD

**Issue by paulthecoder** [reduxframework/redux-framework#2325]
Having an updated list of actions and filters with short descriptions would definitely beef up the doc for developers. It eliminates the process of searching through the Redux codebase and keeps developers away from hooks they're not supposed to using.

Thanks,
Paul

**Comment by dovy** [comment]
Really good call. Care to contribute?  :-)

**Comment by kprovance** [comment]
Lest we forgot, I made a list of them for the docs site.  They're saved as drafts, unformatted.  It's the writing a description for each that makes me not want to do it.  :P

**Comment by dovy** [comment]
Haha, @paulthecoder if we provide the list, would you be willing to help with the descriptions?

**Comment by paulthecoder** [comment]
Yea, I'd be glad to. I can start after this weekend. If you guys can send me the list to paulthecoder@gmail.com that'd be great.

**Comment by kprovance** [comment]
List sent.  Closing issue since we're working on this off the tracker.  :)
