### ISSUE TITLE
Subsections titles not displaying on smaller screens

### ISSUE THREAD

**Issue by joethomas** [reduxframework/redux-framework#2326]
Hey, guys. When the Rudux Options Panel menu minimizes (max-width: 1124px), the subsections aren't really accessible (meaning, the menu bar is too small to display the subsection title). Here's a screenshot of the demo.redux.io options panel for reference:

![demo redux io - options panel subsections inaccessible](https://cloud.githubusercontent.com/assets/5191326/7645964/67f55e36-fa82-11e4-82d9-e20d0e02814d.png)

The only solution I can think of (besides not using subsections) is to have each section's subsections expand into the same panel when browser width is below the breakpoint.

**Comment by kprovance** [comment]
They become flyout menus.  Not enough room to stuff text in there.

**Comment by joethomas** [comment]
Yes, they become flyout menus, but there's no indication that there's anything there. To get the flyout menu, you have to hover over a blank area of dark gray, which isn't intuitive for a user.

![image](https://cloud.githubusercontent.com/assets/5191326/7658632/65fde1f0-fb01-11e4-90f2-0126753677a5.png)

It would be intuitive, though, to collapse `.redux-sidebar ul .subsection` and have each subsection link in a flyout menu when hovering over the section icon?

**Comment by dovy** [comment]
Hint, use ICONS.  ;)   Then the icon appears.  ;)

**Comment by joethomas** [comment]
Thanks, Dovy. At least that adds a visual cue for users.

**Comment by dovy** [comment]
Yea. It's really hard. I guess we could replace with another icon... Do you have any other ideas?

**Comment by dovy** [comment]
Or are the icons sufficient for you?

**Comment by joethomas** [comment]
Not sure if I'll use it or not. My issue with it is that the visual cue of an icon generally doesn't convey what it represents very well for many things. E.g., what icon is a good representation of "Header" or "Footer"? (That's a rhetorical question, btw.) I'm not saying the use of icons there is a bad idea...quite the opposite! But, like all things in UX, I think there's room for improvement.

With the recent gauntlet coming down re: the Customizer, my options panels will necessarily be simplified, so I may be able to get away with using no subsections, anyway.

**Comment by dovy** [comment]
Well, subsections work in the customizer. And you can set them to display in the customizer only.

Check https://ideas.reduxframework.com/campaigns/complete-customizer-integration/ for a demo and details.

And if you missed the webinar: https://www.youtube.com/watch?v=LFmLIgC3e50

**Comment by dovy** [comment]
Oh, and if you want to chat real time: http://slack.redux.io   ;)

**Comment by joethomas** [comment]
Thanks, Dovy. Enjoyed the webinar.

**Comment by dovy** [comment]
Ahh, that's you Joe. Wasn't sure. Usernames are SO different.
