### ISSUE TITLE
Redux Builder not working

### ISSUE THREAD

**Issue by costinu** [reduxframework/redux-framework#2327]
Hello, 

I'm trying to generate a new theme using the Redux Builder but when I download the theme I find only the admin generated files.

**Comment by MargieinAZ** [comment]
I'm having the same problem. Is there anywhere we can download a generic zip file directly, without going through the builder?

**Comment by dovy** [comment]
I need to fix the builder. Apparently in the move something got messed up.

Give me a little bit to look at it.

**Comment by MargieinAZ** [comment]
Okay. No problem. Thanks Dovy!!!

**Comment by costinu** [comment]
Ok, Thanks! I'll wait for your confirmation.

**Comment by ezbizmobile** [comment]
Just ran across the same problem today. Found this thread. Thanks for looking at this, Dovy!

**Comment by sitefloat** [comment]
Same here, I just get a file called zip with no extension.. Thanks Dovy!

**Comment by dovy** [comment]
It's actually working, just put a https:// for your URL instead of http. Working on a permanent redirect.  ;)

**Comment by sitefloat** [comment]
Thanks!! :smiley:

**Comment by dovy** [comment]
Thanks for the patience all. The new builder has been released. It's fast, updated, and much more solid than ever before. Go give it a try. You'll be pleased.  ;)
