### ISSUE TITLE
Load Google Fonts In Dashboard

### ISSUE THREAD

**Issue by mstoic** [reduxframework/redux-framework#2329]
When using Google fonts via Typograhy field, Redux automatically loads the Google Fonts CSS on the front-end. I want the same thing in WP Dashboard. Is it possible?

**Comment by kprovance** [comment]
In your global arguments array, and (or modify if it exists) the `output_location` argument to this:

```php
'output_location'           => array( 'frontend', 'admin' )
```

**Comment by mstoic** [comment]
Added the argument in options-init file, but still not working.

**Comment by kprovance** [comment]
That code was user contributed by @JonasDoebertin.  Jonas, could you look into this please?

**Comment by mstoic** [comment]
It worked great. Now the issue I am facing is, the fonts don't work in the post editor. They just work out of the post editor area. I want to mimic the look of the front-end in the post editor. Any help is much appreciated. Thanks

**Comment by dovy** [comment]
The post editor is an frame, that's why.

**Comment by dovy** [comment]
The post editor is an frame, that's why.

**Comment by mstoic** [comment]
Then any idea on how can we can accomplish it.

**Comment by dovy** [comment]
Nope. If you find a solution the community would love it. ;)

**Comment by JonasDoebertin** [comment]
You should probably have a look at [add_editor_style](https://codex.wordpress.org/Function_Reference/add_editor_style). This allows loading styles for the TinyMCE Editor.

Unfortunately, I don't have the time to fiddle something out that works with Redux, right now.
