### ISSUE TITLE
Speeding up Redux Admin: Deregister 17(!) Separate CSS Files in Admin

### ISSUE THREAD

**Issue by geromefreeman** [reduxframework/redux-framework#2330]
Love Redux but holy cow: 17 separate HTTP calls to different style sheets while in admin? (see below for all of them)

I like everything about my sites to be fast and this is something that can be fixed. But, for some reason, deregistering the styles sheets isn't working. I am using code like below and calling it AFTER calling redux in my functions.php but the style sheet remains in admin. 

I think what I plan on doing is just minifying all 17 CSS files into one small redux CSS and then just call this myself in the admin. I couldn't find another thread like this here. Excuse me if someone already brought this up. 

function dequeue_redux_styles(){
    wp_dequeue_style( 'redux-css-css' );
 
}
add_action( 'wp_enqueue_scripts', 'dequeue_redux_styles', 20 );

-------------------------------------------------

<link rel='stylesheet' id='select2-css-css'  href='http://localhost.com/wp-content/themes/mytheme/redux/redux-core/assets/js/vendor/select2/select2.css?ver=1431920885' type='text/css' media='all' />
<link rel='stylesheet' id='jquery-ui-css-css'  href='http://localhost.com/wp-content/themes/mytheme/redux/redux-core/assets/css/vendor/jquery-ui-bootstrap/jquery-ui-1.10.0.custom.css?ver=1431920886' type='text/css' media='all' />
<link rel='stylesheet' id='qtip-css-css'  href='http://localhost.com/wp-content/themes/mytheme/redux/redux-core/assets/css/vendor/qtip/jquery.qtip.css?ver=1431920886' type='text/css' media='all' />
<link rel='stylesheet' id='redux-elusive-icon-css'  href='http://localhost.com/wp-content/themes/mytheme/redux/redux-core/assets/css/vendor/elusive-icons/elusive-webfont.css?ver=1431920885' type='text/css' media='all' />

<link rel='stylesheet' id='mediaelement-css'  href='http://localhost.com/wp-includes/js/mediaelement/mediaelementplayer.min.css?ver=2.16.2' type='text/css' media='all' />
<link rel='stylesheet' id='wp-mediaelement-css'  href='http://localhost.com/wp-includes/js/mediaelement/wp-mediaelement.css?ver=4.2.2' type='text/css' media='all' />
<link rel='stylesheet' id='imgareaselect-css'  href='http://localhost.com/wp-includes/js/imgareaselect/imgareaselect.css?ver=0.9.8' type='text/css' media='all' />
<link rel='stylesheet' id='thickbox-css'  href='http://localhost.com/wp-includes/js/thickbox/thickbox.css?ver=4.2.2' type='text/css' media='all' />
<link rel='stylesheet' id='redux-css-css'  href='http://localhost.com/wp-content/themes/mytheme/redux/redux-core/assets/css/redux.css?ver=1431920886' type='text/css' media='all' />
<link rel='stylesheet' id='redux-field-section-css-css'  href='http://localhost.com/wp-content/themes/mytheme/redux/redux-core/inc/fields/section/field_section.css?ver=1' type='text/css' media='all' />
<link rel='stylesheet' id='redux-field-text-css-css'  href='http://localhost.com/wp-content/themes/mytheme/redux/redux-core/inc/fields/text/field_text.css?ver=1' type='text/css' media='all' />
<link rel='stylesheet' id='redux-field-switch-css-css'  href='http://localhost.com/wp-content/themes/mytheme/redux/redux-core/inc/fields/switch/field_switch.css?ver=1' type='text/css' media='all' />
<link rel='stylesheet' id='redux-field-media-css-css'  href='http://localhost.com/wp-content/themes/mytheme/redux/redux-core/inc/fields/media/field_media.css?ver=1' type='text/css' media='all' />
<link rel='stylesheet' id='redux-field-info-css-css'  href='http://localhost.com/wp-content/themes/mytheme/redux/redux-core/inc/fields/info/field_info.css?ver=1' type='text/css' media='all' />
<link rel='stylesheet' id='redux-field-ace-editor-css-css'  href='http://localhost.com/wp-content/themes/mytheme/redux/redux-core/inc/fields/ace_editor/field_ace_editor.css?ver=1' type='text/css' media='all' />
<link rel='stylesheet' id='redux-field-spinner-css-css'  href='http://localhost.com/wp-content/themes/mytheme/redux/redux-core/inc/fields/spinner/field_spinner.css?ver=1' type='text/css' media='all' />
<link rel='stylesheet' id='redux-field-editor-css-css'  href='http://localhost.com/wp-content/themes/mytheme/redux/redux-core/inc/fields/editor/field_editor.css?ver=1' type='text/css' media='all' />
<link rel='stylesheet' id='redux-field-select-css-css'  href='http://localhost.com/wp-content/themes/mytheme/redux/redux-core/inc/fields/select/field_select.css?ver=1' type='text/css' media='all' />
<link rel='stylesheet' id='redux-field-image-select-css-css'  href='http://localhost.com/wp-content/themes/mytheme/redux/redux-core/inc/fields/image_select/field_image_select.css?ver=1' type='text/css' media='all' />
<link rel='stylesheet' id='redux-field-typography-css-css'  href='http://localhost.com/wp-content/themes/mytheme/redux/redux-core/inc/fields/typography/field_typography.css?ver=1' type='text/css' media='all' />
<link rel='stylesheet' id='redux-field-multi-text-css-css'  href='http://localhost.com/wp-content/themes/mytheme/redux/redux-core/inc/fields/multi_text/field_multi_text.css?ver=1' type='text/css' media='all' />

**Comment by kprovance** [comment]
Redux already does this for you.  When shopped, and not in dev_mode, the field CSS is combined into one file.

**Comment by dovy** [comment]
Yea, it's really because you're in dev_mode and this way when bugs arise you can tell us the actual offending JS file, instead of line 1 of the compressed one.  :P
