### ISSUE TITLE
Sortable field loses sort when using "validate"

### ISSUE THREAD

**Issue by paulthecoder** [reduxframework/redux-framework#2331]
Redux: v.3.5.4.9
WordPress: 4.2.2

The sortable field reverts back to the original sort order of options. I've nailed it down to "validate" being the culprit. When I get rid of it, the sortable fields works fine.

Field code:
```
array(
	'id'         => 'social_networks',
	'type'       => 'sortable',
	'title'      => '',
	'label'      => true,
	'options'    => array(
		'facebook'  => '',
		'instagram' => '',
	),
	'validate'   => 'no_html', // odd man out
	'full_width' => true,
),
```

**Comment by kprovance** [comment]
Many of the validation checks no longer work with ajax_save.  This is one of them.  There is no way to know if or when this can ever be addressed.  The amount of work required to make real time validation work properly is considerable.
