### ISSUE TITLE
Sections visible only in developer mode 

### ISSUE THREAD

**Issue by azexo** [reduxframework/redux-framework#2332]
Is it possible to do this ?
When one theme can provide different HTML and CSS skins. 
I think it is more easy for developer support one theme source (with adjustment options) than many.
Thanks

**Comment by azexo** [comment]
sorry. I forgot. I can just not add these sections in live mode.

**Comment by kprovance** [comment]
Why not place your section code in an if/else that checks for dev_mode equaling true/false?  And sorry, but I don't know what 'live mode' is or means.
