### ISSUE TITLE
Redux as a Plugin

### ISSUE THREAD

**Issue by wrrr** [reduxframework/redux-framework#2333]
New topic from - https://github.com/reduxframework/redux-framework/issues/new

@dovy asked if I tried installing as a plugin....

--

Do you mean install https://wordpress.org/plugins/redux-framework/ ?

The script notice I'm getting:

Broken Dependencies	redux_options_panel
/wp-content/themes/theme/theme-framework/admin/js/redux-options-panel.js

jquery redux-opts-js (missing)

I am not building a theme, merely using one with redux elements - so if I install Redux Framework as a plugin what are the steps to correct this issue?

Many thanks for your attentiveness Dovy !

stu

**Comment by kprovance** [comment]
Yes, that's the plugin he mentioned, but I think there is a larger issue going on here.  The file `redux-options-panel.js` was never part of the Redux core, not even as far back as version 2.  I did a google search for that file and discovered a theme that uses it, along with v.2 of Redux.  It seems that someone, at some point decided to modify the core of that version of Redux to suit their own purposes, which is fine, that's their right.  However, it probably won't be compatible with the current version of Redux, and there isn't much we can do about that.  You'll have to get with the theme developer to work that out.  If his theme is still dependent upon that old hacked version of Redux 2, it's probably best to stay with whatever version he ships with, unless he wants to do the work to bring Redux up to date, but again, that's his choice.

**Comment by wrrr** [comment]
I appreciate your time on that response @kprovance - understood.

**Comment by dovy** [comment]
We really we wish you the best of luck. Take care.
