### ISSUE TITLE
Purchased extensions repo acces

### ISSUE THREAD

**Issue by Enchiridion** [reduxframework/redux-framework#2334]
Hi,
Is it possible to get access to the git repos for the extensions I've purchased?  I'm working on a patch for one of them and like to make sure I'm up to date.
Thanks.

**Comment by Enchiridion** [comment]
Whoops, wrong area.

**Comment by kprovance** [comment]
Depends on the extention.  Im not keen on folks changing my code around.  If you have feature requests, you could post them.

**Comment by dovy** [comment]
And we're more than fine with fixes. We just don't have a private repo we give out yet. But we'll take patches of they work without flaw. ;)

**Comment by Enchiridion** [comment]
It's for the metaboxes extension.  I'm working on a good sized upgrade to it, repo access would make it easier to patch it.  I can add my changes to a feature branch, then you can merge if you like the changes.

**Comment by dovy** [comment]
@Enchiridion I'm not opposed to setting up a private repo just for us. Do you use Skype/Slack?
Skype: dovydigital
Slack: http://slack.redux.io   @dovy
