### ISSUE TITLE
Redux Demo Site down?

### ISSUE THREAD

**Issue by hellofantastic** [reduxframework/redux-framework#2335]
Looking to demo some premium extensions as its time in current project to add the extra oompf but this site is a blank screen
http://demo.redux.io/wp-admin/

**Comment by dovy** [comment]
Ya, I seem to have broken it. Hah. It will be up by tomorrow. Sorry about that.

**Comment by hellofantastic** [comment]
okay.. and is this issue tracker the place to ask questions that are not issues per se, like say i'm looking for the ability to do something after combing closed issues and the docs?

**Comment by kprovance** [comment]
http://demo.redux.io/wp-login.php seems to work, for now.

**Comment by hellofantastic** [comment]
demo demo sems to be accepted then the next page 
http://demo.redux.io/wp-admin/admin.php?page=_options&tab=0 <http://demo.redux.io/wp-admin/admin.php?page=_options&tab=0>

is blank.


On May 20, 2015, at 6:01 PM, Kevin Provance <notifications@github.com> wrote:

http://demo.redux.io/wp-login.php <http://demo.redux.io/wp-login.php> seems to work, for now.

—
Reply to this email directly or view it on GitHub <https://github.com/reduxframework/redux-framework/issues/2335#issuecomment-104084286>.


Dallas Larsen
Principal at hellofantastic
dallas@hellofantastic.com
250.509.0036
www.hellofantastic.com

**Comment by dovy** [comment]
Fixed for real now.  ;)

**Comment by geo4orce** [comment]
is it down?
http://www.downforeveryoneorjustme.com/http://demo.redux.io/

**Comment by dovy** [comment]
Oy. I need to just deploy it to somewhere else. Bah.

**Comment by ACODA-LTD** [comment]
I wanted to checkout a couple more extensions - however, http://demo.redux.io/ is down. 

Does Color Schemes work with the WP Customizer? Thanks.

**Comment by kprovance** [comment]
It is.  We'll look into that.  Also, no Color scheme's will not work in the customizer at present.
