### ISSUE TITLE
Updated List of Actions and Filters

### ISSUE THREAD

**Issue by paulthecoder** [reduxframework/redux-framework#2336]
Hey guys,

I just did a comprehensive list of the available action and filter hooks in Redux. Feel free to correct any mistakes or add onto the descriptions so @dovy and @kprovance can put the final version in the doc.

# Filters
Tag | Value | Extra Args | Description
----|-------|------------|------------
redux/textdomain/{opt_name} | string The locale of the blog or from the 'locale' hook. | string 'redux-framework' text domain. | Locale for text domain.
redux/font-icons | array $font_icons Array of elusive icon classes. |  | 
redux/page/{opt_name}/enqueue/jquery-ui-css | string The url to enqueue jQuery UI CSS. |  | 
redux/{opt_name}/field/class/{field.type} | string Field class file path. | array $field Field config data. | Change the path of a specific field.
redux/{opt_name}/localize/save_pending | string Save pending text. |  | 
redux/{opt_name}/localize/reset | string Reset all string. |  | 
redux/{opt_name}/localize/reset_section | string Reset section string. |  | 
redux/{opt_name}/localize/preset | string Preset confirm string. |  | 
redux/{opt_name}/panel/templates_path | string The panel templates path. |  | 
redux/{opt_name}/panel/template/{file_name} | string Path to the template file. |  | 
redux/{opt_name}/field/font/icons | array $font_icons Array of elusive icon classes |  | 
redux/{opt_name}/field/class/{field.type} | string Field class file. | array $field Field config data. | Field class file.
redux/{opt_name}/field/class/{field.type} | string Field class file path. | array $field Field data. | 
redux-imported-text-{opt_name} | string Translated "settings imported" text. |  | 
redux-defaults-text-{opt_name} | string Translated all "defaults restored" text. |  | 
redux-defaults-section-text-{opt_name} | string Translated section "defaults restored" text. |  | 
redux-saved-text-{opt_name} | string Translated "settings saved" text. |  | 
redux-changed-text-{opt_name} | string Translated "settings have changed" text. |  | 
redux/args/{opt_name} | array $args ReduxFramework configuration. |  | 
redux/options/{opt_name}/args | array $args ReduxFramework configuration. |  | 
redux/options/{opt_name}/sections | array $sections Field option sections. |  | 
redux/options/{opt_name}/global_variable | array $value Option value to set global_variable with. |  | 
redux/options/{opt_name}/data/{type} | string $data WordPress specific data. |  | 
redux/options/{opt_name}/defaults | array $defaults Option default values. |  | 
redux/options/{opt_name}/section/{section.id} | array $section Section configuration. |  | 
redux/options/{opt_name}/field/{field.id}/register | array $field Field config data. |  | 
redux/options/{opt_name}/field/{field.id} | array $field Field config data. |  | 
redux/field/{opt_name}/output_css | array $field Field config data. |  | 
redux/field/{opt_name}/{field.type}/render/after | string Rendered field markup. | array $field Field data. | 
redux/field/{opt_name}/render/after | string Rendered field markup. | array $field Field data. | 
redux/field/{opt_name}/_can_output_css | array $field Field data. |  | Check if a field meets its requirements before outputting to CSS.
redux/extension/{opt_name}/{folder} | string Extension class file path. | string $extension_class Extension class name. | 
redux/validate/{opt_name}/defaults | array $defaults Option default values. |  | When all options have been reset to defaults.
redux/validate/{opt_name}/defaults_section | array $plugin_options Option default values. |  | When a section's options have been reset to defaults.
redux/validate/{opt_name}/before_validation | array $plugin_options The options array before validation. | array $redux_options | 
redux/validate/{opt_name}/class/{field.validate} | string Validation class file path. | string $class_file Validation class file path. | 

# Actions
Tag | Args | Description
----|------|------------
redux/init |  | On Redux init.
redux/plugin/hooks | object $this ReduxFrameworkPlugin | After the plugin is activated and loaded.
redux/ajax/heartbeat | object $this ReduxFramework | Disregard WP AJAX 'heartbeat' call. Why waste resources?
redux/construct | object $this ReduxFramework | Construct hook.
redux/loaded | object $this ReduxFramework | Redux has loaded.
ReduxFrameworkPlugin_admin_notice |  | Before displaying the admin notice.
redux/{opt_name}/panel/before |  | Before the panel template is echoed.
redux/{opt_name}/panel/after |  | After the panel template is echoed.
redux/page/{opt_name}/enqueue |  | After Redux has enqueued its stylesheets and scripts.
redux/page/{opt_name}/load | object $screen WP_Screen | Redux options page has loaded.
redux/page/{opt_name}/header | object $this ReduxFramework | Redux admin_head() hook for options page.
redux/page/{opt_name}/sections/after | object $this ReduxFramework | Right after all the sections in the options panel, just before the footer.
redux/page/{opt_name}/menu/after | object $this ReduxFramework | After the sections menu in the options panel.
redux/page/{opt_name}/form/before | object $this ReduxFramework | Before the panel's form is echoed.
redux/page/{opt_name}/form/after | object $this ReduxFramework | After the panel's form is echoed.
redux/options/{opt_name}/import | object $this ReduxFramework | When the last save mode is an import.
redux/options/{opt_name}/import | &array [&$plugin_options, redux_options] | Hook when options are being validated.
redux/options/{opt_name}/reset | object $this ReduxFramework | When the last save mode is a global reset.
redux/options/{opt_name}/section/reset | object $this ReduxFramework | When the last save mode is a section reset.
redux/options/{opt_name}/saved | mixed $value Set/saved option value | When the last save mode is the normal save options.
redux/options/{opt_name}/settings/change | mixed $value Set/saved option value | When the user has changed an option.
redux/options/{opt_name}/errors | array $this->errors Error information | Error notification.
redux/options/{opt_name}/warnings | array $this->warnings Warning information | Warning notification.
redux/options/{opt_name}/field/{field.type}/register | array $field The field settings. | Before the field is registered with add_settings_field().
redux/options/{opt_name}/register | array $this->sections Option sections | When registering the options.
redux/options/{opt_name}/compiler | array $this->options <br><br>string $this->compilerCSS CSS that gets sent to the compiler hook. | Compiler hook.
redux/options/{opt_name}/compiler/advanced | object $this ReduxFramework | Advanced compiler hook.
redux/options/{opt_name}/validate | &array [&$plugin_options, redux_options] | Hook on option validation.
redux/field/{opt_name}/{field.type}/callback/before | &array [&$field, &$value] Field data + field id. | Before the callback of a specific field type.
redux/field/{opt_name}/callback/before | &array [&$field, &$value] Field data + field id. | Before the callback of each field.
redux/field/{opt_name}/{field.type}/callback/after | &array [&$field, &$value] Field data + field id. | After the callback of a specific field type.
redux/field/{opt_name}/callback/after | &array [&$field, &$value] Field data + field id. | After the callback of each field.
redux/field/{opt_name}/{field.type}/render/before | &array [&$field, &$value] Field data + field id. | Before the output of a specific field type.
redux/field/{opt_name}/render/before | &array [&$field, &$value] Field data + field id. | Before the output of each field.
redux/field/{opt_name}/{field.type}/fieldset/before/{opt_name} | &array [&$field, &$value] Field data + field id. | Before the fieldset of a specific field type.
redux/field/{opt_name}/fieldset/before/{opt_name} | &array [&$field, &$value] Field data + field id. | Before the fieldset of each field.
redux/field/{opt_name}/{field.type}/fieldset/after/{opt_name} | &array [&$field, &$value] Field data + field id. | After the fieldset of a specific field type.
redux/field/{opt_name}/fieldset/after/{opt_name} | &array [&$field, &$value] Field data + field id. | After the fieldset of each field.
redux/extensions/before | object $this ReduxFramework | Before Redux extensions are registered (not specific to your opt_name).
redux/extensions/{opt_name}/before | object $this ReduxFramework | Before Redux extensions are registered (specific to your opt_name).
redux/extensions/{opt_name} | object $this ReduxFramework | Register Redux extensions.
redux/customizer/live_preview |  | Runs on wp_head() when the Customizer live preview initializes.

**Comment by kprovance** [comment]
Oh shit!  Well done, sir!  I'll make it a point to transfer this to the docs site tomorrow (well, today, depending on the time zone).  ;-)

**Comment by paulthecoder** [comment]
Haha it's today for me :P I've sent you an email with the list in php arrays.

**Comment by kprovance** [comment]
Articles now live on the docs site.  Thanks again for the effort.  ;-)
