### ISSUE TITLE
Quick Question

### ISSUE THREAD

**Issue by MrHunter** [reduxframework/redux-framework#2337]
Just a quick question here. 

Currently I have Redux on XAMPP on my localhost and have created a link between a folder using Redux and the WordPress installation on localhost. It all works fine until Redux tries linking to the scripts it uses a link like this (which returns 404):

http://localhost/automotive/wp-content//Users/dan/Git/plugins/automotive/ReduxFramework/ReduxCore/assets/js/vendor.min.js

and the correct URL is:
/Users/dan/Git/plugins/automotive/ReduxFramework/ReduxCore/assets/js/vendor.min.js

Just wondering if there is a quick and easy way to remove that starting part of the URL so I can still use Redux this way?

Thanks.

**Comment by dovy** [comment]
There's a filter if you want to run using a symbolic link. The issue is PHP won't allow you to detect the actual target folder. Look on the issue tracker, it's a pretty simple filter and you'll just have to manually define via like a mu-plugin declaration.  ;)
