### ISSUE TITLE
Google font collision with multiple Redux instances

### ISSUE THREAD

**Issue by liquida** [reduxframework/redux-framework#2338]
Hello, the latest version 3.5.0 includes an old issue that had been solved in the past

Im using Redux in the plugin mod

This is the issue in the changelog

v3.3.10.4

Fixed: Google font enqueues with opt_name to avoid collision with multiple Redux instances.

Regards

**Comment by liquida** [comment]
sorry, i have the output argument set to false

 'output' => true, // Global shut-off for dynamic CSS output by the framework. Will also disable google fonts output

regards

**Comment by dovy** [comment]
?   Confused.

Please include a support URL and tell us exactly what's going "wrong."

**Comment by kprovance** [comment]
If the global output argument is set to false, google fonts won't enqueue.
