### ISSUE TITLE
Pinterest Icon Missing from Elusive Icons CSS File

### ISSUE THREAD

**Issue by knilob** [reduxframework/redux-framework#2339]
I'm not really sure how this even happened, but the Pinterest icon is missing from the Elusive Icons CSS file you all have packaged with Redux. I see the most recent icon y'all added (Plurk) in the file, but it skips from .el-picture:before to .el-plane:before.

**Comment by kprovance** [comment]
Moving issue to Elusive Icons issue tracker.

**Comment by dovy** [comment]
I think I have this resolved. Just need to test.
