### ISSUE TITLE
Redux Repeater : Is it possible dynamically show fields depending on a 'select' field?

### ISSUE THREAD

**Issue by aonzzung** [reduxframework/redux-framework#2341]
Hi,

I bought Repeater plugin and I have a quick question.
I already asked on redux-extensions but haven't get an answer yet. 
Here : https://github.com/reduxframework/redux-extensions/issues/176

Do you have any idea about this?

Thanks for your time

**Comment by kprovance** [comment]
Please post extensions issues in the extension issue tracker.  This one is for the Redux core.  Thanks.

**Comment by aonzzung** [comment]
@kprovance Sorry for posting here. If you're able to take a look for #176(link above), I would appreciate. So, i can find any alternative if it cannot support this.

Thanks

**Comment by kprovance** [comment]
You'll have to wait for Dovy to get to it.  He knows that code WAY better than I.
