### ISSUE TITLE
Problem CDN unavailable

### ISSUE THREAD

**Issue by nicolas92** [reduxframework/redux-framework#2342]
Hello, I have three messages when I'm in my panel, look at the screenshot, I made redux to the latest version, WordPress is version 4.2.2, I disabled all plugins but nothing changes, I do not understand why there's error messages.
http://postimg.org/image/e57a01v5n/
Can you help me?
Thank you a lot.

**Comment by kprovance** [comment]
Knowing the version of Redux would also have been helpful, or even the support URL.  Chances are you are working on a localhost with no internet access, in which case, install this plugin: https://reduxframework.com/wp-content/uploads/2015/05/redux-vendor-support.zip to restore the local vendor libraries.  You will NOT need to distribute that plugin.

**Comment by nicolas92** [comment]
Thank you, it works very well.
