### ISSUE TITLE
Transferring Website - Googlefonts.html and Googlefonts.json error

### ISSUE THREAD

**Issue by infernalrage** [reduxframework/redux-framework#2344]
Our website was recently transferred over to another host and it seems like we have some issues. I never worked on the site and have never really worked in WordPress so I am not quite sure what the issue is.

I see that there is an error when I inspect the element in Chrome and hide the background saying:
"Warning : copy(.../wp-content/uploads/redux/google-fonts/googlefonts.html): failed to open stream: No such file or directory in .../wp-admin/includes/class-wp-filesystem-direct.php"

The message is hidden in the background and it creates this huge white space so a user has to scroll down before they actually see anything on the site.

I then installed the Redux plugin since that is what appears to be causing the issue through WordPress and the white space goes away, but I can't scroll down all the way. Then it shows this error message in a smaller white space saying

"Warning: mkdir(): Permission denied in ...html/wp-content/plugins/redux-framework/ReduxCore/inc/class.redux_filesystem.php"

I got the FTP access and I changed the permissions on the file it was saying to 755, but I keep getting the same error about:

<b>Warning</b>
: mkdir(): Permission denied in
<b> .../wp-content/plugins/redux-framework/ReduxCore/inc/class.redux_filesystem.php</b>
on line
<b>131</b>
I am not sure if this is even the correct solution, but any help would be greatly appreciated. If the plugin is not the error, any help would be greatly appreciated.

**Comment by kprovance** [comment]
It's all a permissions issue.  You need to install Wordpress as a user, not through FTP, otherwise permissions get all wonky and nothing works properly.

**Comment by dovy** [comment]
Yup, yup.

Or rather, your web server needs to have access to those files.  ;)

**Comment by infernalrage** [comment]
It was installed as a user I believe. All the other plugins were reinstalled and work fine, but I am just having an issue with this one. Is there any other solution to fix that error or anything else I can try?

**Comment by kprovance** [comment]
Well, if you are not the author of the theme, you would need to contact the theme author, as they are using a very outdated version of Redux.  if the theme author needs support from us, then we can offer it to them.

**Comment by kprovance** [comment]
Here is a more detailed breakdown:  https://docs.reduxframework.com/core/support-defined/
