### ISSUE TITLE
library_filter for media field

### ISSUE THREAD

**Issue by Neejoh** [reduxframework/redux-framework#2345]
According to the [docs of the media field](https://docs.reduxframework.com/core/fields/media/) the `library_filter` allows an array:
> Array of file type values (NOT mime) the media library should only display.

```php
array(
	'id' => 'general-favicon',
	'type' => 'media',
	'title' => __('Image', COMC),
	'desc' => __('Accepts <code>.ico</code> or <code>.png</code>', COMC),
	'library_filter' => array('ico','png'),
),
```
When I add `var_dump($jsonArr, $libFilter);` after line 110 in `inc/fields/media/field_media.php` it correctly creates an array with the two file types, but the media manager shows no results (the images are there though).

My guess is that where `$libFilter` is used, it's not in line with the urlencode/json_encode that is generated.

**Comment by kprovance** [comment]
Thank you for posting on the Redux Issue tracker. In order for us to begin debugging your issue, we need you to first generate a support URL. You can learn about how you generate that here: http://docs.reduxframework.com/core/generating-a-support-hash/

Please update this ticket with the support URL when you have it. Thank you.

**Comment by kprovance** [comment]
Two days have passed since I asked for additional information.  I am closing this ticket for now.  If the issue persists, please open A NEW ticket with the required support URL.  Thanks.
