### ISSUE TITLE
Validate multiple fields in one callback function?

### ISSUE THREAD

**Issue by dw-hyphen** [reduxframework/redux-framework#2346]
Hi, I was just wondering if it is possible to validate multiple fields at once in a single callback function. For example, I have 3 slider fields with ranges between 0-12. I would like to make sure that the sum of these three sliders does not exceed 12. Is this possible? I am using Redux Framework v3.5.4.8.

Thanks very much.

**Comment by kprovance** [comment]
You might try custom validation:  https://docs.reduxframework.com/core/the-basics/validation/  An example is also available in the sample-config.php file.

**Comment by dw-hyphen** [comment]
I am sorry I wasn't clear. I have tried to do this using a custom validation function, the problem is I can only seem to validate the fields one at a time. I haven't been able to compare the new values for 3 separate fields together at once. I can only compare the values after they have all been set instead of before. 

Can I compare the values of 3 separate fields, before they are set?
