### ISSUE TITLE
Undefined index after theme activation

### ISSUE THREAD

**Issue by ZoOmArts** [reduxframework/redux-framework#2347]
Hi there,

I have some errors with redux after activate my theme.
Here is a screenshot for better understanding http://take.ms/Rji1t
But after clicking save changes in my theme options all errors disappear also when set 'dev_mode' = false!

WordPress: Last version
Redux: 3.5.4.13
dev_mode: false,
WP_DEBUG: true

**Comment by dovy** [comment]
Please provide a support URL. Are you using the new Redux API or the legacy class method?

**Comment by ZoOmArts** [comment]
I'm using Redux API

**Comment by dovy** [comment]
Now just this: https://docs.reduxframework.com/core/generating-a-support-hash/

**Comment by ZoOmArts** [comment]
http://support.redux.io/?id=D%2FHhw%2FdQoUpFW4zukzlBLwEC73LUkjmctQ4vsEaf1Qb6rUS5sGq5xuUyGdlAab1RLV%2BcmYCFGHKcKcyoUHD4RA%3D%3D

**Comment by ZoOmArts** [comment]
Let me know if there is anything missing

**Comment by kprovance** [comment]
I guess the ball got dropped here?  Send your theme to info@reduxframework.com

**Comment by ZoOmArts** [comment]
But i will upload my theme on themeforest!

**Comment by kprovance** [comment]
You're not posting it for anyone to download, just Dovy and I.  if you do not want to that is fine, but we won't be able to debug your issue any further until we have the environment it fails in.

**Comment by ZoOmArts** [comment]
Nop, I will send it right now.

**Comment by kprovance** [comment]
Reopening, as it's a bug in our code.  A fix will for coming in the next day or so.

**Comment by ZoOmArts** [comment]
Is the issue is resolved in the new version?
I did not see any change. The bug still exist.

**Comment by kprovance** [comment]
It does.  I told you I would post back when it was fixed.  As I have not posted back, it is not yet fixed.

**Comment by dovy** [comment]
This has been resolved.  ;)
