### ISSUE TITLE
[bug] and [feature]: typogaphy multi select for weight and and subset not working

### ISSUE THREAD

**Issue by kwayyinfotech** [reduxframework/redux-framework#2350]
Hello,

I am creating a typography element. I like to add General font option in Theme Options. But as you know, body has all font weight varients like Bold, Italic, BoldItalic. So I added multi option so user can select multiple weights so all the Google Font variants will load. So I added this code:

```
array(
			'id'          => 'generalfont',
			'type'        => 'typography', 
			'title'       => __('General Font', 'innovation'),
			'text-align'  => false,
			//'compiler'  => true, // Use if you want to hook in your own CSS compiler
			'google'      => true, // Disable google fonts. Won't work if you haven't defined your google api key
			'font-backup' => true, // Select a backup non-google font in addition to a google font
			//'font-style'=> false, // Includes font-style and weight. Can use font-style or font-weight to declare
			'subsets'     => true, // Only appears if google is true and subsets not set to false
			//'font-size' => false,
			'line-height' => true,
			'font-weight' => true,
			'text-transform' => true,
			//'word-spacing' => true, // Defaults to false
			//'letter-spacing' => true, // Defaults to false
			'color'       => true,
			//'preview'   => false, // Disable the previewer
			'output'      => array('ul.nav-menu li a, div.nav-menu > ul li a, #navbar #site-navigation .mega-menu-wrap .mega-menu.mega-menu-horizontal > li.mega-menu-item > a'), // An array of CSS selectors to apply this font style to dynamically
			'units'       => 'px', // Defaults to px
			'subtitle'    => __('Select font, color and size for main menu.', 'innovation'),
			 'multi'      => array(
                    'subset' => true,
                    'weight' => true,
                ),
			'default'     => array(
				"font-family" => "Roboto Slab",
				"google"      => "1",
				"font-backup" => "'Trebuchet MS', Helvetica, sans-serif",
				"font-size"   => "12px",
				"line-height" => "12px",
				"color"       => "#333333",
				
			),
		),

```

**BUG:**
Now the bug is the multi option is not working properly. I can select first variant but I cannot select next variant. Example, I can select NORMAL text but when I try to select another BOLD variant than it will remove the first NORMAL variant too and also I cannot select any variant. This same happens to Subset too.

**FEATURE REQUEST:**
I also like to add a new feature. Currently, I can select multiple font weights so all the Google Fonts variants will load and the variant will work perfectly. But currently I cannot select default applied font variant. So I like to add feature to select default font weight too. Example, I like to add Bod, Italic and all variants but I like to make the Italic as default font.

Thanks,
Bob

**Comment by kprovance** [comment]
mutli select was removed (for the time being) as it was buggy and not working properly.  It wasn't ready for prime time.  Feel free to submit the idea at ideas.reduxframework.com.  If we can get decent financial backing, we could add it in the future.
