### ISSUE TITLE
Fatal error: Cannot use object of type WP_Error as array in ReduxCore/core/newsflash.php on line 63

### ISSUE THREAD

**Issue by monnoval** [reduxframework/redux-framework#2351]
I'm working in local and I'm always having this error. I also did embed redux via [embed](https://docs.reduxframework.com/core/advanced/embed/) in a wordpress plugin.

The fix that I do for now is to comment line 63 for the mean time. Then go to Wordpress Admin and uncomment it again. Similar below

``` php
62                $data = wp_remote_get($this->server_file, array('sslverify'=>false));
63                // $data = $data['body'];
64                // if some data exists
65               if ($data != '' || !empty($data)) {
```

After this everything is working again. 

Sorry I really do not have any idea how to fully fix this part for now. I only found a workaround so that I could continue working on my stuff.

**Comment by kprovance** [comment]
Fixed in the latest push to this repo, v3.5.4.14

**Comment by monnoval** [comment]
Thank you so much!

**Comment by dovy** [comment]
If you like Redux, or the support we render, please do one or all of the following:
* Donate to keep us going: http://ideas.reduxframework.com
* Review us: http://wordpress.org/support/view/plugin-reviews/redux-framework
* Like us: http://facebook.com/ReduxFramework
* Follow us: http://twitter.com/ReduxFramework
