### ISSUE TITLE
How can I Disable Redux's 'About' Page On Theme Activation

### ISSUE THREAD

**Issue by mstoic** [reduxframework/redux-framework#2353]
The users are being redirected to the Redux's about page whenever the theme is activated. Any possible way to disable that?

Also, is there a way to redirect them to the theme's options page instead.

**Comment by dovy** [comment]
Are they using the plugin or is it embedded? Do you have dev_mode off?

**Comment by mstoic** [comment]
Thanks. **dev_mode** solved the issue.

**Comment by mstoic** [comment]
And what about the **improve our panel notice**? Can we turn that off?

**Comment by dovy** [comment]
We'd ask you to leave that on. It only comes up once per instance, and really helps us to know things we need to support. You can figure out how to turn it remove it yourself, but we're not going to offer code for that since it's very unobtrusive.  :)

**Comment by mstoic** [comment]
Figured it out.

Commenting the below line did the trick.

    *add_action( 'admin_print_footer_scripts', array( $this, 'tracking_request' ) );*

**Comment by thesagor** [comment]
Redux option not working/saved without theme activate.How to bypass theme activation?

**Comment by dovy** [comment]
@thesagor Tell your theme author they integrated Redux wrong and to load it before they use a hook. ;)
