### ISSUE TITLE
PHP Warning

### ISSUE THREAD

**Issue by kpmcgee73** [reduxframework/redux-framework#2359]
Hi,

My theme developer Getbowtied.com posted a query about my php errors but looking at the thread I'm uncertain if he followed this up with you.

My site is vintageheirloom.com, host is http://websynthesis.com/, using redux v3.5.4.6.

My server error logs are filled up with warnings about the redux framework, examples:

6/1/2015 12:32:29 PM - PHP Warning: file_get_contents(http://www.reduxframework.com/wp-content/uploads/redux/redux_notice.json): failed to open stream: no suitable wrapper could be found in /var/www/vintageheirloom.com/wp-content/themes/shopkeeper/settings/redux/ReduxCore/inc/class.redux_filesystem.php on line 186

6/1/2015 12:32:29 PM - PHP Warning: file_get_contents(): http:// wrapper is disabled in the server configuration by allow_url_fopen=0 in /var/www/vintageheirloom.com/wp-content/themes/shopkeeper/settings/redux/ReduxCore/inc/class.redux_filesystem.php on line 186

My host Synthesis reports this:

I have been digging and I believe I found an issue with your theme, as it relies extensively on this file as well. The theme seems to also not be fully compatible with Synthesis, as it uses a PHP function that we have disabled for security reasons: 
- Warning: file_get_contents(): http:// wrapper is disabled in the server configuration by allow_url_fopen=0 in /var/www/vintageheirloom.com/wp-content/themes/shopkeeper/settings/redux/ReduxCore/inc/class.redux_filesystem.php on line 186 

I'm happy to supply FTP WP log in details if there is a secure method, please advise.

Can you please help?

Thanks 
Kevin

**Comment by kprovance** [comment]
Please upgrade to the latest version of Redux from this repo.  v3.5.4.15.  This issue has been resolved.

**Comment by kpmcgee73** [comment]
Hi Kevin

Many thanks for confirming this fixes the issue. I've contacted my theme developer and they 'plan' to update.

Cheers
Kevin

**Comment by dovy** [comment]
In the meantime, you can easily load this repo as a plugin, and all should work properly for you.

**Comment by kpmcgee73** [comment]
Hi Dovy,

Thanks !

I'm not a developer, so I've no idea how the theme developers implemented your Redux framework. I don't want to break anything, is there any possible conflict by updating?

I can't see Redux in the WP plugin list, so if it goes wrong how do I first backup the current Redux install and roll back if necessary?

Thanks
Kevin

**Comment by kprovance** [comment]
Probably not.  But as we did not write the theme, it would be impossible to say.  This is a question best posed to the theme developer.

**Comment by kpmcgee73** [comment]
Thanks
