### ISSUE TITLE
Custom css in external file

### ISSUE THREAD

**Issue by alvisir** [reduxframework/redux-framework#236]
Hi,
I understand how to include custom css in front-end with `<style>` tag. My question is: is it possible include the same css code in an external file (custom.php)?
`<link rel='stylesheet' id='custom-css'  href='mypath/custom.php' type='text/css' media='all' />`
I tried to do it but my file is empty... I remember that in SMOF you could do it.

**Comment by LoyalBen** [comment]
Is there no easy way to get an external css file with php like "style.css.php" with redux variables work? That would be the ultimate boost for the Redux Framework!

**Comment by zebulondev** [comment]
Hello !
The post is old but i found how to use $globals Redux on css.php file :-)

On start your php css wrote this line :
define('WP_USE_THEMES', false);
require('../../../../wp-load.php'); //change path in your level :-)

header("Content-type: text/css; charset: UTF-8");
$variableFooterColor = $GLOBALS['redux_demo']['opt-color-footer'];

/* write css and use php variables */

Enjoy
