### ISSUE TITLE
Using redux with a parent theme symlink

### ISSUE THREAD

**Issue by polsola** [reduxframework/redux-framework#2360]
Hello!

Just wanted to know if I'm doing something wrong or this just can't be done

I'm using the same theme (which has redux included) for local development in some different WordPress installs, to avoid duplicating files I've symlinked the theme folders, the theme shows and looks fine but the Redux Framework Panel is missing, I've followed the steps in this thread

https://wordpress.org/support/topic/redux-framework-and-symbolic-link

But can't get it to work either, I'm using the last version of Redux Framework

Is there something I can do?

Thanks!

**Comment by kprovance** [comment]
What you might perceive as the latest version and what is could be two different things.  Please provide a support URL.

**Comment by polsola** [comment]
Hello again and thanks for answering!

Currently I'm working on my computer so I don't have an URL, I've checked the version of the redux framework included in the theme and it's the 3.5.4.3

Do I need to provide more info? 

Thanks again!

**Comment by kprovance** [comment]
We need the support URL, as explained here: https://docs.reduxframework.com/core/generating-a-support-hash/  If this is not possible, then I'm not sure what to tell you.   This is how we do support now, versus back and forth piece-meal.

**Comment by kprovance** [comment]
Closing issue due to lack of response.  If further support is needed, please open a NEW ticket with the requested support URL.  Thanks!

**Comment by hannwong** [comment]
I am seeing this problem too.
