### ISSUE TITLE
dev_mode is always true, if WP_DEBUG is on

### ISSUE THREAD

**Issue by Ninos** [reduxframework/redux-framework#2361]
In my config I set `dev_mode = false` but it does not work anymore, just because the WP_DEBUG is set to true. I want to disable it by default, also if the debug mode is enabled.

Also it should be possible to disable the ads & tracking by default, regardless of the dev_mode.

Wordpress: 4.2.2
Redux Framework: 3.5.4.3

**Comment by kprovance** [comment]
<blockquote>
In my config I set dev_mode = false but it does not work anymore, just because the WP_DEBUG is set to true. I want to disable it by default, also if the debug mode is enabled.
</blockquote>
By design now.  Please do not submit pull requests in an attempt to alter this.

<blockquote>
Also it should be possible to disable the ads & tracking by default, regardless of the dev_mode.
</blockquote>
Tracking is opt in.  As for the ads, that'll never happen.  Again, please do not submit pull requests in an attempt to circumvent this.

**Comment by dovy** [comment]
If dev_mode is on, the ads show. If it's not, they won't show. ;)

**Comment by Ninos** [comment]
@dovy The dev_mode is set to false, but turns automatically on, if debug mode is set to true. I think then the dev_mode should be definitely turned off.

**Comment by dovy** [comment]
@Ninos Only on if you're developing locally bud. It's not automatically on otherwise.  ;)

**Comment by dovy** [comment]
AND if WP_DEBUG is true too.  ;)

**Comment by Ninos** [comment]
If dev_mode is set, it should have a higher rating than the global wp debug mode. So I think it should not be activated.

PS: Before some versions the setting worked fine..

**Comment by dovy** [comment]
Ninos, if you're so frustrated with it, we welcome you to make your own mods. This was at request of fellow developers like you who forgot to turn dev_mode on. They wanted it automatic.

It won't be changing from our end. Honestly, the result is most people are happy with the change.

**Comment by Ninos** [comment]
Ok for me it's just confusing. I'll create a PR in near future :) Due the track and ads, an argument to activate/deactivate them globally is not welcome, right?

**Comment by dovy** [comment]
@Ninos It's not confusing, you just don't want to see them. And no, a pull re-lease won't be accepted as your users never see it.  :p

**Comment by Ninos** [comment]
For me it is. I searched in the redux code today, why the argument is not working anymore. Ok I still don't understand what customers could do with that extentions, because they need to be implemented and most of them cannot code, but I respect your decision :) So I'll just create a PR for the dev_mode thing..

**Comment by kprovance** [comment]
Pull requests that tamper with the way we have dev_mode setup will NOT be accepted.  I asked you once not to do so.  Any request will be closed.  This thread is now closed and locked.
