### ISSUE TITLE
global var is always and everywhere empty

### ISSUE THREAD

**Issue by w3b-beweb** [reduxframework/redux-framework#2362]
Debug info:

  -  Redux version: 3.5.4.15
  -  Wordpress 4.2.2
  -  Redux in dev_mode (because of active WP_DEBUG)
  -  Redux embedded as a plugin

here's my plugin code:

```php
defined( 'ABSPATH' ) or die( 'Plugin file cannot be accessed directly.' );
require_once plugin_dir_path( __FILE__ ) . "admin/admin-init.php";
```

and this is my options init code:
```php
if ( ! class_exists( 'Redux' ) ) {
        return;
    }

    // This is your option name where all the Redux data is stored.
    $opt_name = "adv_opts";

   $args = array(
        'opt_name' => $opt_name,
        'display_name' => 'Pannello Opzioni',
        'display_version' => FALSE,
        'page_slug' => 'escort_site_opts',
        'page_title' => 'Opzioni Avanzate Sito',
        'update_notice' => TRUE,
    		'disable_save_warn' => false,
        'intro_text' => '<p>In questa sezioni trovi le opzioni avanzate del sito. Se ti trovi in difficoltà prova a consultare la sezione <strong>Aiuto</strong> in alto a destra in questa pagina.</p>',
        'footer_text' => '<p>Le impostazioni marcate con «".$this->args[\'default_mark\']."» sono impostate al <strong>valore consigliato</strong>.</p>',
        'admin_bar' => TRUE,
    		'admin_bar_icon' => 'dashicons-admin-settings',
        'menu_type' => 'menu',
        'menu_title' => 'Opzioni Avanzate',
        'allow_sub_menu' => TRUE,
        //'page_parent_post_type' => 'your_post_type',
        'default_show' => TRUE,
        'default_mark' => '*',
        'class' => 'redux-escort',
        'hints' => array(
            'icon' => 'el el-info-circle',
            'icon_position' => 'right',
            'icon_size' => 'normal',
            'tip_style' => array(
                'color' => 'light',
                'shadow' => '1',
                'style' => 'jtools',
            ),
            'tip_position' => array(
                'my' => 'bottom center',
                'at' => 'top center',
            ),
            'tip_effect' => array(
                'show' => array(
                    'effect' => 'fade',
                    'duration' => '500',
                    'event' => 'mouseover',
                ),
                'hide' => array(
                    'effect' => 'fade',
                    'duration' => '500',
                    'event' => 'mouseleave unfocus',
                ),
            ),
        ),
        'output' => TRUE,
        'output_tag' => TRUE,
        'compiler' => TRUE,
        'global_variable' => $opt_name,
    		'menu_icon' => 'dashicons-admin-settings',
        'page_permissions' => 'manage_categories',
        'save_defaults' => TRUE,
        'show_import_export' => TRUE,
        'transient_time' => '3600',
        //'network_sites' => TRUE,
    );

    
    Redux::setArgs( $opt_name, $args );
```
The option panel shows in the back-end but the global var $adv_opts is always empty. For example, doing:

```php
global $adv_opts;
print_r($adv_opts);
```
in any template file or functions.php, it always returns an empty variable.
I think I'm missing something obvious, but I can't find it. That's my first Redux 3.5 attempt but I'm using Redux 3.4.x, embedded in my theme, on several other sites and accessing options via global var works perfectly.

**Comment by dovy** [comment]
Are you using the new API?

**Comment by jobkit** [comment]
I have the same problem. But I don't want to use the global variable anyway, so how do I get the options?
I can use get_option($opt_name), but that's hardly intuitive...

**Comment by jezzdk** [comment]
I have the same problem. But I don't want to use the global variable anyway, so how do I get the options?
I can use get_option($opt_name), but that's hardly intuitive...

**Comment by jezzdk** [comment]
Is this the correct way of getting the value of an option?

$value = Redux::getField($opt_name, 'field-id');

**Comment by w3b-beweb** [comment]
@dovy Yes, I'm using the new API as I've generate the option-init skeleton with your builder (btw, I found some problem with the builder code, in admin/admin-init.php where extension was included BEFORE framework, producing an error with non existing Redux class; including extensions after framework, seems to fix the problem). Then I've customized the panel with my sections and fields and it works great: saves and loads values with no problems at all, no errors and no warnings. 

After I've opened the issue here, I was using a workaround to set and use a global variable adding the following code in my option-panel plugin:

```php
global $adv_opts;
$adv_opts = get_option('adv_opts');
```

But now, I think I've found the problem! There's no `Redux::init($opt_name);` call in builder generated skeleton. Adding this call to my option-init.php file, fixes it all. Now the global var is alive.

**Comment by w3b-beweb** [comment]
UPDATE: no problem on frontend, but when I try to switch to backend, I always get a 
> PHP Fatal error:  Call to undefined function wp_create_nonce() in /srv/www/e2.w3b.it/site/wp-includes/functions.php on line 1341,
if I remove the call to Redux::init I can use the back-end again

**Comment by stcfive** [comment]
Hello,

Thanks for the frameworks.

I have the same problem and also noticed that the builder's theme is broken.

Redux version 3.5.4.8.

Sorry I couldn't add anything constructive to the discussion, but probably this is an issue with these releases. On that note, how can I get old version of Redux that is actually works?

Thanks W3b-beweb, will try to fix based on your suggestion.

**Comment by aman704** [comment]
@w3b-beweb were you able to fix this?

**Comment by w3b-beweb** [comment]
@aman704 I'm using the code in my last comment, i.e. calling Redux::init only on front-end. This way back end gives no errors and I can use the global var on frontend.

**Comment by aman704** [comment]
Thanks @w3b-beweb

**Comment by dovy** [comment]
Sorry all, been out for a few days. I'll get on this tomorrow.  :)

**Comment by w3b-beweb** [comment]
Don't worry Dovy. You guys are doing a fantastic job with redux, and your free support here is faster than many other premium supports I came across.

**Comment by w3b-beweb** [comment]
(@kprovance, plz don't hate me for this! :smile: )
Any news on this issue?

**Comment by kprovance** [comment]
You'll have to ask @Dovy.  He's the one tasked with fixing it.

**Comment by kprovance** [comment]
Try the most recent push of v.3.5.4.29.  We added an extra hook on the ReduxAPI.  See if it helps.

**Comment by kprovance** [comment]
Okay, it's been a few days without a reply.  Closing ticket.  Please open a new issue with a support URL if things continue.

**Comment by w3b-beweb** [comment]
sorry, I was out for a few days of vacation. I'll try it asap. Thanks

**Comment by w3b-beweb** [comment]
Well, updated to 3.5.4.34 and disabled my workarounds above: all seems to work just fine!

**Comment by dovy** [comment]
Yay! Glad to hear it.  :)

**Comment by PlayerThemes** [comment]
I have similar issue.
global $my_var_name is empty when accessed in functions.php file or any other file included, but works well in template files like header.php etc.

Here is my code in functions.php

/**
  * Load Redux Framework
 */
 if ( !class_exists( 'ReduxFramework' ) && file_exists( dirname( __FILE__ ) . '/inc/admin/framework.php' ) ) {
    require_once( dirname( __FILE__ ) . '/inc/admin/framework.php' );
}

// custom settings for redux framwork
if ( !isset( $redux_demo ) && file_exists( dirname( __FILE__ ) . '/inc/redux-options.php' ) ) {
    require_once( dirname( __FILE__ ) . '/inc/redux-options.php' );
}

global $my_var_name;
print_r($my_var_name);

---------

Note: I have embedded redux 3.5.4.34 into theme

**Comment by dovy** [comment]
That's an easy fix. If you want to use it in functions.php, just run Redux::init('opt_name');

That will force the redux object to be created and any code after that will have a populated object. ;)

**Comment by PlayerThemes** [comment]
Dovy, thanks its working. Although the logic behind it is not clear to me.  Why static method for functions.php and global variable for template file?

And big thanks for fixing the theme check issue. Wow!!! 0 warnings. No need to explain any thing anymore to any theme reviewer again. Dovy, I am sure you must be felling very happy after getting that monkey off the back.

**Comment by dovy** [comment]
@PlayerThemes Let me explain.

The Redux API is set to run at `after_setup_theme` or `init`, whichever happens first. Since functions.php runs BEFORE after_setup_theme, Redux never has a chance to load.

So by doing the static init, you force the loading of Redux at that instance, the other hooks are ignored, and you can use the global variable as you would expect.

Not too complicated.  ;)

**Comment by PlayerThemes** [comment]
@dovy, Yup, that makes sense. Thanks. :)

**Comment by udarts** [comment]
I am trying to get option values working in functions.php, using the Redux::init('opt_name'); inside my options-init.php which is inside my admin-init.php:

`if ( file_exists( dirname( __FILE__ ).'/ReduxCore/framework.php' ) ) {
        require_once dirname(__FILE__).'/ReduxCore/framework.php';
    }

    // Load the theme/plugin options
    if ( file_exists( dirname( __FILE__ ) . '/options-init.php' ) ) {
        require_once dirname( __FILE__ ) . '/options-init.php';
    }

    // Load the page options
    if ( file_exists( dirname( __FILE__ ) . '/page-options-init.php' ) ) {
        require_once dirname( __FILE__ ) . '/page-options-init.php';
    }

    // Load the loader if it exists
    if ( file_exists( dirname( __FILE__ ) . '/loader.php' ) ) {
        require_once dirname( __FILE__ ) . '/loader.php';
    }`

The Redux::init($opt_name); is at the end of the options-init.php file after all the setsections, but I still don't get any option values.

What am I missing?
