### ISSUE TITLE
Values output as NULL in some files

### ISSUE THREAD

**Issue by aman704** [reduxframework/redux-framework#2363]
Redux Version:  v3.5.4.15
Wordpress Version: 4.2.2
Dev_mode: enabled
Redux Integration: Embedded in the plugin

So redux embedded in the plugin as require_once( 'admin/admin-init.php');
After that, I require another file require_once( 'inc/test.php');

test.php needs redux values, so I add

`<?php
global $supermenu;
var_dump($supermenu);`

This outputs NULL, however, it works perfectly in some files. 
I saw another similar issue ( https://github.com/reduxframework/redux-framework/issues/2306 ) where you mentioned using Redux::init( 'OPT_NAME' ); 
It works after adding this but wp-admin shows this error:
Fatal error: Call to undefined function wp_create_nonce() in /Applications/MAMP/htdocs/wordpress/wp-includes/functions.php on line 1341

Ideas?

**Comment by dovy** [comment]
Did you figure it out?
