### ISSUE TITLE
Getting value with global_variable = false

### ISSUE THREAD

**Issue by jezzdk** [reduxframework/redux-framework#2364]
Example of problem: How do I retrieve the html value of an editor field, when I don't have the global variable present?

**Comment by kprovance** [comment]
You use the opt_name you set in your args as the variable:
```
global $redux_demo

$redux_demo['my_option'];
```
This is covered here, in step 3: https://docs.reduxframework.com/core/getting-started/

**Comment by jezzdk** [comment]
You didn't answer my question. I've disabled the global variable.
