### ISSUE TITLE
Editor field returns value in plaintext (No html)

### ISSUE THREAD

**Issue by jezzdk** [reduxframework/redux-framework#2365]
Even though wpautop is set to true, the value is returned without `<p>` and `<br>` tags.

**Comment by kprovance** [comment]
That's just how it works.  It's not a Redux issue.  Sorry.

**Comment by jezzdk** [comment]
Then what is the point of the 'wpautop' setting in the WP Editor Options?
https://docs.reduxframework.com/core/fields/editor/
