### ISSUE TITLE
html_custom validation is not working for me

### ISSUE THREAD

**Issue by dipskakadiya** [reduxframework/redux-framework#2366]
Hey 
I have text filed with "html_custom" validation but it's allow other tag also. like <hr/>, <b>

```
array(
 'id'           => 'rthd_auto_response_message',
 'type'         => 'textarea',
 'title'        => __( 'Auto response message' ),
 'desc'         => 'blah blah',
 'validate'     => 'html_custom',
'required'     => array( 'rthd_enable_auto_response', '=', 1 ),
'allowed_html' => array(
       'a'      => array(
		'href'  => array(),
		'title' => array(),
	),
	'br'     => array(),
	'em'     => array(),
	'strong' => array(),
),
),
```

**Comment by kprovance** [comment]
This is one of the validation schemes that will not work as originally designed with ajax_save set to true.  At some point in the near future this will be addressed.  For the time being, the only solution is to disable ajax_save.

**Comment by dipskakadiya** [comment]
Hey kprovance  
Event i set 
``` 'ajax_save'         => false,``` validation doesn't work for me

**Comment by kprovance** [comment]
Please provide a support URL then.  Also, are you using the Redux API to create your panel, or the 'legacy' way?
