### ISSUE TITLE
Issues with last Redux Update

### ISSUE THREAD

**Issue by wpinsite** [reduxframework/redux-framework#2368]
Hi Guys,

Since the last update, which was yesterday my Redux Control Panel Columns have gone out of alignment.

E.G If the field has a long description explaining it, then the actual field is pushed right over to the right of the screen. The columns between the description and the actual field is distorted.
It is like "word-wrap: no-wrap" has been added to the descriptions.

Is this something that has changed?

Also, when using the compiler to output the CSS styles. How often is the dynamic file updated as a lot of time I save the changes in the Redux Control Panel but the changes don't always show. If using the "output" tag it is instant.

Thanks
Broady

![issues](https://cloud.githubusercontent.com/assets/6923718/7973769/9a5c8c1c-0a9c-11e5-94e0-6a48c7aa0915.jpg)

**Comment by kprovance** [comment]
Please provide a support URL: https://docs.reduxframework.com/core/generating-a-support-hash/

**Comment by wpinsite** [comment]
Hi Kevin, 
Sorry about that. Here is the support hash:

http://support.redux.io/?id=40xwIWzGSfLupdta1%2BFAszvr98%2BqDF51b%2F3rRJwuqwdv2%2FdtWbFfmoy96zRq92R9f7dkyDbjU551a71V4iUP6w%3D%3D

**Comment by kprovance** [comment]
Fixed in v.3.5.4.17

**Comment by wpinsite** [comment]
Thanks Kevin. Appreciate the prompt reply and fix.
