### ISSUE TITLE
validate_callback not working on type => "color"

### ISSUE THREAD

**Issue by liquida** [reduxframework/redux-framework#2369]
Hello guys

i need a to create custom validation function that allow me to validate a color and not emtpy

i created these fields

array(
                    'title' => __('Navbar Text', 'liquidatheme'),
                    'subtitle' => __('Pick a color for the navbar text.', 'liquidatheme'),
                    'id' => 'scheme_' . $key . '_navbar_text',
                    'type' => 'color',          
                    'validate_callback' => 'lmm_validate',
                    'compiler' => true,
                    'default' => '#ffffff'
                ),

 array(
                    'id' => 'scheme_' . $key . '_navbar_background_color',
                    'title' => __('Navbar Color', 'liquidatheme'),
                    'subtitle' => __('Pick a background color for the navbar.', 'liquidatheme'),
                    'type' => 'color_rgba',       
                    'validate_callback' => 'lmm_validate',
                     'compiler' => true,
                    'default' => ''
                ),

and a function that allways return error, to test

function lmm_validate($field, $value, $existing_value) {

    $error = false;

    $field['msg'] = __('This field cannot be empty. Please provide a value.', 'liquidathemes');

    $return['value'] = 'just testing';

    $return['error'] = $field;

    return $return;
}

but the message is only displayed on the rgba fields

regards

**Comment by kprovance** [comment]
How long have you been posting here, dude?  Seriously?  No version info, on anything?  Please post back a support URL.  That is REQUIRED from here on in.

**Comment by kprovance** [comment]
In fact, I need you to do a little more work on this, otherwise I'm going to ask for premium support on this, as I don;t believe it's a redux bug...yet.  have you checked value and existing_value for all the fields you are attempting to use?  Are they different, empty, etc?  See if you can find what is or is not working before I spend the hours probably required on this.  Thanks.

**Comment by kprovance** [comment]
Fixed in v.3.5.4.17

**Comment by liquida** [comment]
I think it would be nice to have the possibility to combine validations, for example "validate"=> array(''not_empty", "color")

in my case I need not_empty and color, thats wy inussing validation_callback

anyway, you're making an amazing job with redux

regards

**Comment by kprovance** [comment]
<blockquote>
I think it would be nice to have the possibility to combine validations, for example "validate"=> array(''not_empty", "color")
</blockquote>
That would take a considerable rewrite within the core.  Feel free to submit the idea to https://ideas.reduxframework.com.  If we can get enough financial backing to do it, we will.

<blockquote>
when v.3.5.4.17 will be available in wordpress?
</blockquote>
When it's ready, and it'll be 3.5.5 when it is.

**Comment by liquida** [comment]
thanks kevin

regards!
