### ISSUE TITLE
Latin extended Google fonts not displaying correctly

### ISSUE THREAD

**Issue by eugeneowp** [reduxframework/redux-framework#2372]
Redux Plugin v3.5.4.3.
WordPress 4.2.2.
Dev Mode disabled.

I have used Redux in a theme I am selling through ThemeForest. A user contacted me highlighting an issue where Latin extended characters of Google fonts do not display correctly on any browser other than Chrome.

I did some digging and found that the problem is caused by the font URL generated by Redux. Specifically <code>$amp;</code> is used where an actual "&" is required.

In ReduxCore/inc/fields/typography/field_typography.php the two instances of this line:

<pre><code>$link .= "&#38;amp;subset=" . implode( ',', $subsets );</code></pre>

should be:

<pre>$link .= "&subset=" . implode( ',', $subsets );</pre>

**Comment by kprovance** [comment]
Problem with doing that is: 1) It will crash anyone who uses validation which leads to 2) breaking backward compatibility.

**Comment by eugeneowp** [comment]
Well as it stands now it doesn't work.

**Comment by kprovance** [comment]
I don't know.  You haven't given me a lot to work with.  No case example no version information, no support URL.  Nada.

**Comment by kprovance** [comment]
https://docs.reduxframework.com/core/generating-a-support-hash/

**Comment by kprovance** [comment]
Cjosing issue due to lack of reply.  If you still require support, please open a new ticket with the request support URL.  Thanks!
