### ISSUE TITLE
Help Please how to disable Redux, someone disabled admin bar links

### ISSUE THREAD

**Issue by BabiB** [reduxframework/redux-framework#2374]
Hello all,
please i have a real frustrating problem,
i've a theme with redux framework dev mode but someone is logged on my admin panel and disabled (hidden) links of admin bar (general setting, tools, plugin ect.)

how i can show again these? i can disable redux from database? Please give me some solutions please :'-((((

**Comment by kprovance** [comment]
You need to contact the author of the theme and ask them.  We do not support theme that use our framework, that is the responsibility of the theme author.  Sorry.

**Comment by dovy** [comment]
This might work if your developer shipped with "dev_mode" on.

https://wordpress.org/plugins/redux-developer-mode-disabler/

**Comment by BabiB** [comment]
Hi Dovy thanks for your support,
but i can not see "plugin" link in admin bar as "general setting" etc... they were hidden :-(

**Comment by kprovance** [comment]
This is why you need to complain to the THEME AUTHOR!!!    https://docs.reduxframework.com/core/support-defined/

**Comment by BabiB** [comment]
I'm not complaining, i don't why you are angry Kevin. before I wrote to theme author too but no one reply so I thought to post here.. it's wrong? Ok close post! I would not a miracle!!!

**Comment by kprovance** [comment]
Not angry, just annoyed.  An influx of theme users believing we offer support for theme has been taking up my time as of late.  I point them on their way, but they don;t want to take no for an answer.

**Comment by dovy** [comment]
Haha, come now everyone.   ;)

Sorry @BabiB, but it's not in our job description, since what's affecting you we did not code. That being said, we DO offer customization services at $150/hr. I could probably find the code for you in a max of 2 hours. If you'd like to do that, please contact me: dovy@redux.io.

Thank you and good luck.
