### ISSUE TITLE
Typography options slows down the options panel.

### ISSUE THREAD

**Issue by guzun** [reduxframework/redux-framework#2375]
Hi there.

I'm trying to add like 20 typography settings and this slows down the options page significantly.
I'm wondering if there is any solution to improve that. 

Thank you,
Alex

**Comment by kprovance** [comment]
Inherently, no.  I might reconsider the design if 20 typo fields are necessary.

**Comment by dovy** [comment]
And with Redux, if you're not loading that section (tab) the Javascript won't be loaded.

Yea, as @kprovance suggested I would lighten up on the use of Typography fields. Honestly, the issues are not in our code, but in the WP Color Picker and Select2, which slow that field down dramatically.

:)
