### ISSUE TITLE
mysql_gets_server_info() warning

### ISSUE THREAD

**Issue by coleh33** [reduxframework/redux-framework#2377]
Is this related to my server being PHP 5.5 and no longer supported according to PHP documentation?  Is this something to be concerned about or will everything still run fine regardless?  Just wanted to make sure.

PHP Warning: mysql_get_server_info(): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (13) in /nas/wp/www/cluster-40124/alphamedia/wp-content/themes/alphamedia/ReduxFramework/ReduxCore/inc/tracking.php on line 365

PHP Warning: mysql_get_server_info(): A link to the server could not be established in /nas/wp/www/cluster-40124/alphamedia/wp-content/themes/alphamedia/ReduxFramework/ReduxCore/inc/tracking.php on line 365

Thanks.

**Comment by kprovance** [comment]
Please provide a support URL:  https://docs.reduxframework.com/core/generating-a-support-hash/

**Comment by coleh33** [comment]
Thanks for the heads up on that step.

Now i'm getting "You do not have sufficient permissions to access this page."  So i'll have to go first find out why i'm getting that message when my account is the super admin of the multi-site.

**Comment by coleh33** [comment]
I was finally able to get the access for a support hash.  I can also report those same Warnings are still happening.

http://support.redux.io/?id=whB0V7uGRgrHcNlBEkkzEEqsHV01O0nSlnlBhwhybmgUvuZzI1XeogKPNQVqxwUjfVgqYHQkiZdGvR4DQps4zw%3D%3D

**Comment by kprovance** [comment]
Fixed in v.3.5.4.19 - Changed that call to a $wpdb call, so it shouldn't be an issue anymore.  :)
