### ISSUE TITLE
Metaboxes cfg

### ISSUE THREAD

**Issue by Ronanzzzzzzzzzz** [reduxframework/redux-framework#2378]
Hi, i'm using a theme that use redux framework and i'm willing to add a post association with a post_type of my own.
So i've done it with page like that :
'fields' => array(
	array(
		'id'      => 'post_association',
		'type'    => 'select',
		'multi' => true,
		'title'   => __( 'Post Association', 'gp_lang' ),
		'desc' => __( 'blabla bla.', 'gp_lang' ),
		'data' => 'page',
		'default' => ''
	),

but when i replace 'page' to 'my_custom_posttype' i doesnt work, how should i do ?

**Comment by kprovance** [comment]
Please post all Redux extension issues to the extensions issue tracker.  This issue tracker is for the Redux core only.  Thanks.  https://github.com/reduxframework/redux-extensions/issues

**Comment by kprovance** [comment]
Also, if you are NOT the theme author, but rather a user of the theme, you need to contact the theme author for support.  We do not support themes that use Redux, that is the theme author's responsibility.

**Comment by Ronanzzzzzzzzzz** [comment]
So... i'm a developpeur, i'm working on a theme a friend use. I cant have infos on the framework ?
Well nice, i dont think i'll use it again. Maybe remove it from the wp of my friend will be easier for me since i dont get infos.

**Comment by kprovance** [comment]
Okay, not a problem.  All I'm asking is you post your issue in the appropriate forum.  I supplied you with the link.  Thanks!

**Comment by Ronanzzzzzzzzzz** [comment]
its done...
