### ISSUE TITLE
Uploads Folder

### ISSUE THREAD

**Issue by winwinwebdesign** [reduxframework/redux-framework#2379]
Before I begin, I want to thank Dovy and Kprovance 100 times for making Redux Framework, you're changing the world for the better and you don't even know it. I HATE how themeforest artists rarely give back to the backbone of their earnings, but I promise to change that one day soon.

Anyways, for my client's project I need to completely barebone everything except for Theme Options so I've removed Newsflash, Notification, and Tools. 

I was curious if it's possible to remove the creation of "uploads/redux" folder since I don't seem to be using it for anything anymore.

**Comment by kprovance** [comment]
It is not.  Redux uses that folder internally to test for various read/write routines.  It is also used for data store with certain extensions, and will be necessary when the customizer extension is ready.  :)
