### ISSUE TITLE
sliders with 2 handles: initializing error (cannot use scalar value as array) 

### ISSUE THREAD

**Issue by w3b-beweb** [reduxframework/redux-framework#2380]
Debug info:

  -  Redux version: 3.5.4.17
  -  Wordpress 4.2.2
  -  Redux in dev_mode (because of active WP_DEBUG)
  -  Redux embedded as a plugin

I'm trying to use a slider field with 2 handles to let user select a range, with this code (as per documentation):

```php
	    array(
	    		'id'        => 'opts_ageslider_2',
	    		'type'      => 'slider',
	    		'title'     => __('Age Slider', 'redux-framework-demo'),
	    		'subtitle'  => __('Select an age range', 'redux-framework-demo'),
	    		"default"   => array (
	    				1	=>	18,
	    				2 	=>	50,
	    		),
	    		"min"       => 18,
	    		"step"      => 1,
	    		"max"       => 50,
	    		'handles'		=> 2,
	    		'display_value' => 'label'
	    ),

```
When I load the panel page, I have the php error reported in the issue title above, on several lines of redux-framework/inc/fields/slider/field_slider.php; the first one is on line 186.
After some debug, I've found that $this->value seems to take "min" value instead of "default" ones.

Let me know if you need further details.
Thanks

**Comment by kprovance** [comment]
I tried your code and cannot reproduce.  Please submit a support URL.  Thanks.

**Comment by w3b-beweb** [comment]
Hi Kevin, don't know why but I cannot reproduce the error me too. The error was showing only at the first panel load, when no values was previuosly saved in the db (and with other two one-handle sliders in the same section, one above and one below).  Today I've undone my changes to redux core and just tryed to add another new 2 handles sliders to the section: no errors.

This is the full section code, if you wanna do another try on your testing enviroment

```php
Redux::setSection( $opt_name, array(
		    'title'     	=> __( 'Age ranges', 'redux-framework-demo' ),
		    'id'        	=> 'search_filters_agesliders_opts',
		    'desc'      	=> __( 'Set the 3 age ranges', 'redux-framework-demo' ),
		    'icon'      	=> 'el el-resize-horizontal',
		    'subsection'	=> true,
		    'fields'    	=> array(
					    array(
					    		'id'        => 'opts_ageslider_1',
					    		'type'      => 'slider',
					    		'title'     => __('First range', 'redux-framework-demo'),
					    		"default"   => 18,
					    		"min"       => 18,
					    		"step"      => 1,
					    		"max"       => 50,
					    		'display_value' => 'select'
					    ),
					    array(
					    		'id'        => 'opts_ageslider_2',
					    		'type'      => 'slider',
					    		'title'     => __('Second range', 'redux-framework-demo'),
					    		"default"   => array (
					    				1	=>	18,
					    				2 =>	50,
					    		),
					    		"min"       => 18,
					    		"step"      => 1,
					    		"max"       => 50,
					    		'handles'		=> 2,
					    		'display_value' => 'label'
					    ),
					    array(
					    		'id'        => 'opts_ageslider_3',
					    		'type'      => 'slider',
					    		'title'     => __('Third range', 'redux-framework-demo'),
					    		"default"   => 18,
					    		"min"       => 18,
					    		"step"      => 1,
					    		"max"       => 50,
					    		'display_value' => 'select'
					    ),
					)
    ) );
```

Feel free to close this issue and thanks for the support.

**Comment by kprovance** [comment]
Well, to be thorough, I gave the new code you provided a try.  Still no luck.  The Redux API has a glitch on first run that not setting certain settings to the DB, which I think is being worked on.  Possible cause, perhaps?  Still not sure.  I'll close.  If it pops up again, let us know!
