### ISSUE TITLE
Do not let user to remove an option completely from a select field

### ISSUE THREAD

**Issue by fakeartist** [reduxframework/redux-framework#2381]
Is this possible? Right now, the user can remove an option complete, so the "select an item" text appears. It would be great to force the user to select an option (or if he removes it, to return to the default). I know I can use the radio option, but I like better the select field presenation.

**Comment by dovy** [comment]
There's an argument for that. Look at the docs. But yes, it's completely possible.

**Comment by fakeartist** [comment]
Thanks for the quick response. Where exactly can I find the argument? And how it is possible? Any guidelines? Thanks in advance

**Comment by dovy** [comment]
Http://docs.reduxframework.com and look at the select field. Where all our solid documentation is stored. :p

**Comment by fakeartist** [comment]
I already saw the doc page before posting the issue (https://docs.reduxframework.com/core/fields/select/), but I could not (and still cannot) find the argument that you are referring. Could you tell me which one is?

**Comment by dovy** [comment]
Haha, I thought I had coded that in. My bad. I'll make the change today.

**Comment by kprovance** [comment]
You're talking about the X in the select box?  If so, the documentation is there (https://docs.reduxframework.com/core/fields/select/)  Ot's the select2 argument.  It accepts an array of options.  I think the one you want is allowClear => false.  You have to check with the select2 docs.  A link is provided on the docs page under that argument.

**Comment by dovy** [comment]
Ha, you're right!

So it's:
`'select2' =>array('allowClear' => false) `

**Comment by fakeartist** [comment]
Works like a charm! Thank you!

**Comment by marium0505** [comment]
Your documentation still doesn't mention this.... 
![image](https://user-images.githubusercontent.com/1466933/49154157-06951b80-f318-11e8-94a3-9bbc6769869c.png)

So your documentation isn't as "solid" as you claim it to be. ;)
