### ISSUE TITLE
Fatal error: Class 'Redux' not found

### ISSUE THREAD

**Issue by kidesigner** [reduxframework/redux-framework#2382]
I use redux builder and get notice and stop when active theme: 

Fatal error: Class 'Redux' not found in /wp-content/themes/equity/admin/redux-extensions/extensions-init.php on line 4

Please help me. Thank so much!

**Comment by toddsantoro** [comment]
I have the same issue. I'm in my local MAMP stack using WP2015 theme just for kicks on a new install of everything and using the embed method in the theme.

**Comment by dovy** [comment]
Yea, I made a mistake with the builder. Include reduxcore/framework.php first. I'll push a fix shortly.

**Comment by kidesigner** [comment]
Please notify me when you complete. Thank you

**Comment by toddsantoro** [comment]
Do you want me to fix it then push the fix and add a pull request?

**Comment by kidesigner** [comment]
Can you send me "admin" folder?

**Comment by toddsantoro** [comment]
Just including the framework.php file does not do the trick. Would you say its better to not use the builder and just clone the github repository or will that not make a difference?

**Comment by toddsantoro** [comment]
Is this still unsolved???

**Comment by kprovance** [comment]
Okay fella, some patience, please.  Both Dovy and I have paid work that takes priority over a FREE service.  I just updated the builder to fix this issue.  That said, if any of you feel like the project or the effort is worth donation toward, please...do.  :)

**Comment by toddsantoro** [comment]
@kprovance I completely understand. I will make a donation. I tried to offer my assistance but got no response. Cheers!!!
