### ISSUE TITLE
Multiple select font-weight and subsets in typography field

### ISSUE THREAD

**Issue by sodbileg** [reduxframework/redux-framework#2383]
Hi, is it possible to select multiple font-weight or subsets in typography field?

**Comment by kprovance** [comment]
Not at this time.  We played with it, but it needs considerable work.  If we can get ample financial backing from the community, it could happen sooner rather than later.  Please feel free to submit the idea at ideas.reduxframework.com.  Thanks!

**Comment by dovy** [comment]
You can use the all_styles (i believe) arg to get everything for a given font if needs be.  ;)

**Comment by sodbileg** [comment]
Hey guys, thanks for your replies.
