### ISSUE TITLE
Pledging $100, question about Dynamic CSS output

### ISSUE THREAD

**Issue by kmob2** [reduxframework/redux-framework#2386]
Hello Dovy,

I am about to pledge a $100 so I could get the customizer extension today. I read that all redux fields have been ported already.
I don't need the "validation" feature and I can live without the "required" feature for now. However I read that the "Dynamic (AJAX) CSS output" is not working yet. I assume this is the feature where it dynamically outputs the CSS using the compiler, correct? https://docs.reduxframework.com/core/advanced/updating-a-css-file-dynamically/

If so, I also don't need that, all I am currently in need for is that all redux fields work in the customizer (hopefully raw field as well) and that I can fiddle around with jQuery to add live previews based on the redux fields.

**Comment by dovy** [comment]
Hey @kmob2. Standard dynamic CSS output DOES work, but it causes a customizer re-load. It isn't a "live" reload.

The compiler arg doesn't work yet, but CSS/Typography output works JUST fine.

You will need to use the version of Redux in this repo, and I'm making some extra changes here this afternoon that will make it even better.   :)

**Comment by dovy** [comment]
And yes, with the extension, all fields work in the customizer EXCEPT for the ones outlined (WP Editior included).

**Comment by kmob2** [comment]
Thanks Dovy, I just made a $100 pledge. Could you send the early access to the email I used to pledge? (Sorry don't feel like making my email address public here)

**Comment by dovy** [comment]
Email me directly: dovy@redux.io   ;)

Or Skype (DovyDigital) or Slack (http://slack.redux.io) me.
