### ISSUE TITLE
CDN Error

### ISSUE THREAD

**Issue by krishna19** [reduxframework/redux-framework#2387]
when i open theme options page, I'm getting three errors. And my internet connection also works fine and i'm not work locally, but i get this error.

Redux Version : 3.5.4.13
WP Version : 4.2.2
![redux](https://cloud.githubusercontent.com/assets/4782674/8088723/27b9e6c6-0fc1-11e5-8ea3-a0c4c2ba402b.jpg)

Thanks

**Comment by dovy** [comment]
Here's a plugin you can load when running locally and without the internet: https://github.com/reduxframework/redux-vendor-support

**Comment by dovy** [comment]
That means the CDN is down... I am not getting that myself. Probably a connectivity issue.
