### ISSUE TITLE
Refresh a page after saving specific field

### ISSUE THREAD

**Issue by sodbileg** [reduxframework/redux-framework#2389]
Hi, this is what I did in `compiler_action()` function with no luck. Is it possible to refresh a current page after saving specific field?

```php
if ( array_key_exists( 'the_field', $changed_values ) ) {
    header( 'Refresh: 0;' );
}
```

**Comment by kprovance** [comment]
The header method won't work.  I've tried.  ;-)

You can turn ajax_save off by setting it to false.  That's about it.

**Comment by sodbileg** [comment]
Hi @kprovance, thanks for your quick reply.
Do you mean turn off ajax_save globally?

**Comment by kprovance** [comment]
Yeah, that's the only way to do it.  Set it in your config where you set your global args.

**Comment by sodbileg** [comment]
Okay, thank you.

**Comment by dovy** [comment]
So you can do it via JS. `redux.args.ajax_save=false;`

**Comment by dovy** [comment]
You could also do this via the compiler action, and do a die();

```
                    echo json_encode( array(
                        'status' => '',
                        'action' => 'reload'
                    ) );
```

**Comment by sodbileg** [comment]
Hi dovy,

I did that, but it's not refreshing. Am I doing something wrong?

```php
if ( array_key_exists( 'the_field', $changed_values ) ) {
    echo json_encode( array(
        'status' => '',
        'action' => 'reload'
     ) );

    die();
}
```

**Comment by dovy** [comment]
Check the network response and see if it runs or not...

**Comment by sodbileg** [comment]
No, it's not running.

**Comment by dovy** [comment]
So your compiler hook isn't running at all? Can you test that?

**Comment by dovy** [comment]
What about a save hook instead?

**Comment by sodbileg** [comment]
Oh, silly me. I forgot to enable `compiler` option on my field.

But now it shows me this alert.
![screenshot 2015-06-12 13 03 28](https://cloud.githubusercontent.com/assets/1418797/8123859/7fda3d2c-1103-11e5-93b3-f0ed5e727f03.png)

**Comment by dovy** [comment]
Look at the network response...  ;)

**Comment by sodbileg** [comment]
Response is appeded with `{"status":"","action":"reload"}`

**Comment by dovy** [comment]
Maybe add something in status, heh.

**Comment by kprovance** [comment]
Okay, I know it's a little late, but I added an argument `reload_on_change` which you can add to the field array of a specific field.  When set to true, the options page will reload when that field's value has changed.  When the value changes, the page will save, then reload.  You'll need to update to v.3.5.4.20 to use it.  Cheers.

**Comment by sodbileg** [comment]
Hi @kprovance,

I added `reload_on_change => true` in my field like below.

```php
array(
    'id'               => 'the_field',
    'type'             => 'text',
    'title'            => __('Title', 'domain'),
    'reload_on_change' => true,
),
```

But it's not reloading after I change a value of this field and save.

v3.5.4.27

**Comment by kprovance** [comment]
I'll try and look into it later this week.  I'm slammed with work that pays at the moment.

**Comment by sodbileg** [comment]
Okay thanks. Good luck with your paid work ;)

**Comment by sodbileg** [comment]
Hi @kprovance,
Just wondering if you looked into it.

**Comment by vikasbaru** [comment]
I know its a bit late, but anyone who is looking for a solution use this argument:
```javascript
'ajax_save' => false
```
