### ISSUE TITLE
using redux in another plugin

### ISSUE THREAD

**Issue by egydes** [reduxframework/redux-framework#2394]
Hello

thanks for great framework Redux
i am making some custom post types as external plugin  and i want to make the client name the titles of that custom post type via our redux dashboard , when i call the option value in plugin .. nothing happen why that ?

my suffix :abtheme_

want to get the content of : $abtheme_['shro7at_name'] as string value in external plugin file?

thanks

**Comment by kprovance** [comment]
I don't understand what you are asking.  Are you attempting to get the Redux options of one plugin in another?  That's not really possible.

**Comment by dovy** [comment]
You'd have to use native WP functions to get the other plugin's info...

You COULD use a custom data argument with a hook to construct them on your own I suppose.

**Comment by kprovance** [comment]
Closing issue due to lack of reply
