### ISSUE TITLE
Theme options save not works

### ISSUE THREAD

**Issue by krishna19** [reduxframework/redux-framework#2395]
Hi,
Theme options save function not works in Chrome & Safari, but works in firefox.
When i try to save the options the loading icon loads continuously. Please help

Redux Version : 3.5.4.13
Wordpress Version : 4.2.2
Chrome Version : 43.0.2357.124
Safari Version : 8.0.6

Thanks

**Comment by kprovance** [comment]
Well, I've been working with Redux all day, and it's saving fine under Chrome.  Let's start with you providing us with a support URL, and we can go from there.

**Comment by kprovance** [comment]
Closing issue due to lack of reply.  If the problem persists, please open a new issue with the requested support URL.
