### ISSUE TITLE
Enable Redux Framework for QTranslate X

### ISSUE THREAD

**Issue by dejudicibus** [reduxframework/redux-framework#2396]
I have written a JSON file to enable TA Pluton theme for QTranslate X. However there are still part of the admin panel that are not translated in the various languages. Snooping in code I realized that the problem is related to Redux framework. So I need to enable Redux frameworks too, in order to have all working. But how?

**Comment by kprovance** [comment]
Honestly, I have no idea.  What you contacted the developer of the product in question?  If there product is not working with ours, you might ask them why, as it's not really our responsibility to make Redux work with them.

**Comment by dovy** [comment]
It's difficult because they have custom options there. Perhaps we could make an extension eventually, but we'd need to be supported in the effort.  ;)

**Comment by dejudicibus** [comment]
Which support do you need?

2015-06-15 18:59 GMT+02:00 Dovy Paukstys <notifications@github.com>:

> It's difficult because they have custom options there. Perhaps we could
> make an extension eventually, but we'd need to be supported in the effort.
> ;)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/reduxframework/redux-framework/issues/2396#issuecomment-112137856>
> .
>



-- 
Dario de Judicibus, Rome, Italy (EU)
Site: http://www.dejudicibus.it
Blog: http://www.lindipendente.eu
Book: http://www.lalamanera.it

**Comment by dovy** [comment]
Meaning someone needs to provide the funding to help make it happen. hah.  ;)
