### ISSUE TITLE
Title Wrapper Background

### ISSUE THREAD

**Issue by Levko** [reduxframework/redux-framework#2397]
The style fails to generate when the site is restored fresh from backup.

The 'Title Wrapper Background' totally fails to generate.

`<style type="text/css" title="dynamic-css" class="options-output">.logo{margin-top:20px;}#iv-layout-title-wrapper{background-repeat:no-repeat;background-size:cover;background-attachment:fixed;background-position:center center;background-image:url('http://example.com/image.jpg');}</style>`

How do I fix this as dozens of pages are missing the main images for the pages and I am forced to do a database search and then list the images and then have to figure out the pages they belong to?

Why is the CSS failing to generate on rebuild?

USING PHPMYADMIN TO DO A DATABASE DUMP

THE FILES ARE SYNCHRONIZED AS IDENTICAL COPIES

**Comment by kprovance** [comment]
It would be literally impossible for me to speculate on any of this, considering I have NO idea how you backed up or restored your site.  It's like calling me and telling me your car won;t start after you replaced the engine.  Unless I was there, how could I know?  Now, that said, Redux has an import/export option.  Did you try that, assuming you made an export of your options?

As for the CSS generation issue, I have no idea what a 'title wrapper background' is.  Are you the theme developer or a user of the theme?

**Comment by Levko** [comment]
All sites should be portable and its irrelevant of backup method. I am an admin that has developed sites using themes. Developers have built the site and in your redux framework master php file the outputCSS is failing to generate. I assume you know your code. The settings are in the database but it seems as if a cookie is set for the style. If a theme or framework is not portable it is rejected as failing to meet minimum standards as it cannot be backed up and restored without interference from a third party.

**Comment by Levko** [comment]
https://docs.reduxframework.com/core/advanced/updating-a-css-file-dynamically/

This is your work no?

**Comment by Levko** [comment]
Do you understand your own work?

**Comment by kprovance** [comment]
I do, but I don't care for the attitude and you blaming us for your database woes.  I'm sure @Dovy will be along to pick this up at some later time.  Cheers.

**Comment by dovy** [comment]
*sigh*

@Levko You'll have to add your own activation hook to load your own compiling function. We can't be to blame when it's your code my friend. There are plenty of examples out there of theme activation/update hooks. Just go online.  :)
