### ISSUE TITLE
Having issues with patterns saving. All cool on Local.

### ISSUE THREAD

**Issue by guuthemes** [reduxframework/redux-framework#2399]
Hey,

Just seems to be with the patterns field? All cool on Local. Pushed to live server, not so good.

Getting - "There was a problem with your action. Please try again or reload the page"

Every other option in my panel saves great. Just the patterns. When you highlight one, and save, it throws the error.

Seeing this in the console - "There was an error saving. Here is the result of your action:" redux.min.js:1
"Forbidden"

Cheers folks

Support hash below -

http://support.redux.io/?id=vO8QqY6lD3nzI0lV863yvy4TfY2AFJbheSLyVCxbEFYUrlcNflT%2BthDBvI%2FN%2BHQ7TscoY7HVUkzcG56PAExU%2Fg%3D%3D

**Comment by kprovance** [comment]
I can't reproduce, but I see you are using URLs instead of local files.  Have you tried not using URLs to see if it makes a difference?

**Comment by guuthemes** [comment]
URLs in where, sorry?

**Comment by kprovance** [comment]
The image_select field?  I assume that's what you mean by 'pattern' field, since we don't actually have a pattern field.  :)

**Comment by guuthemes** [comment]
I am using the image_select :) What should I be using here Kevin?

**Comment by kprovance** [comment]
```
alt => "whitediamond",
img => "http://konvers.guuthemes.com/wp-content/plugins/redux-framework/ReduxCore/../sample/patterns/whitediamond.png"
```
This is what I'm talking about.  Now, since I cannot reproduce this, I am making guesses.  You're using a url here.  Sometimes that doesn't work, which is why I asked if you've tried using a local file and building the path to that.  Again, guessing.

**Comment by guuthemes** [comment]
You mean linking to patterns in my theme build? As Redux is currently embedded.

**Comment by kprovance** [comment]
It doesn't matter.  Something like

```
img => ReduxFramework::$_url . "sample/patterns/whitediamond.png" // (or whatever the proper path is in your case)
```

**Comment by dovy** [comment]
I wouldn't use $_URL.
Instead something like `get_bloginfo('template_directory')`. If someone installs Redux framework at all via plugin, the $_url will break.  ;)

**Comment by guuthemes** [comment]
Just stumped why all cool on Local, but not live? Links are not changing?

**Comment by kprovance** [comment]
Again, if I could reproduce, I could tell you.  I cannot.  The only clue is that 'forbidden' error, which is usually indicative of some kind of file permission thing.

**Comment by kprovance** [comment]
You might also turn dev_mode on, so we can get a proper line number in redux.js, because line 1 means it's minimized, and impossible to debug.

**Comment by guuthemes** [comment]
Just switched on dev_mode. Cheers.

**Comment by guuthemes** [comment]
Tried - get_bloginfo('template_directory'). Nothing.

**Comment by kprovance** [comment]
<blockquote>
Just switched on dev_mode. Cheers.
</blockquote>

And?  Do you have a proper line number being returned in the console now?

**Comment by guuthemes** [comment]
Nope

**Comment by guuthemes** [comment]
Tried in my hosting .ini file -

`max_input_vars=2000`

So it's not an issue there

**Comment by guuthemes** [comment]
Ok. So spoke to my hosting company (Clook). They logged in to my admin and came back with -

> It looks like some of the requests it was making were being blocked by the security rules on the server, > as they were interpreted as an attack attempt. The rule that was causing the problem has been disabled

**Comment by kprovance** [comment]
That damned mod-security.  Tell them to stop mimicking GoDaddy.  :P 

Glad you got is resolved.  This should come in handy if the issue crops back up.  :)

**Comment by guuthemes** [comment]
I thought they were a decent host (Clook). Is that a GoDaddy thing as you mentioned though Kevin?

**Comment by kprovance** [comment]
Honestly, I'm not at all familiar with Clook (could they be a GoDaddy reseller?  They are hundreds of them out there.)  I say this from pure experience, but as far as WP hosting goes?  GoDaddy sucks more than anything in the history of sucking.  They have more rules than the IRS, and more security than there is around Obama's college transcripts.  Put another way, we've seen issues related around mod security on GD servers more than once.  You can search the issue tracker for them, they're out there.  Some are just plain crazy.

**Comment by guuthemes** [comment]
No. They're definitely not a GoDaddy reseller. That much I know. But only realised how strict they can now be. Time for a new host maybe?

> They have more rules than the IRS, and more security than there is around Obama's college transcripts

:):)
