### ISSUE TITLE
Issue in Slider section

### ISSUE THREAD

**Issue by janith** [reduxframework/redux-framework#2400]
Hi,

I am using a theme which is using Redux framework as the backend of theme options. It was working fine, but from few days before I face strange issue which Theme options not loading.(not showing anything)

When I debug the issue I found that it is related to slider section and error as given below, (exactly when it's loading previous selected posts for slider.)

 Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 32 bytes) in /var/www/web0/html/blog/wp-includes/wp-db.php on line 2204 

Redux version : Redux Framework v3.3.9.2
Wordpress version : 4.1.5

I know that there is newer versions available, but for now I need to stick with this version as I am not the author of the theme. 

Please note that I am using the same theme on few other test location without any issues, only in my production version giving this issue. So I guess it may be related to the data load. 

Edited : 

I went deeper and found the issue is related to field_select.php file line 62.

$this->parent->get_wordpress_data( $this->field['data'], $this->field['args'] )

The inputs for this line is,
data : "posts"
args : array( "posts_per_page"=> -1 } 

finally I found the issue is coming from the framework.php it self line 951

$posts = get_posts( $args );

Thanks

**Comment by kprovance** [comment]
Unfortunately, you'll need to take this up with the theme developer.  We do not, and cannot support older version of Redux.
