### ISSUE TITLE
Modify/add options to existing field in Child Theme

### ISSUE THREAD

**Issue by MichaelKaeser** [reduxframework/redux-framework#2401]
Hello everyone

I have a child theme in which I'm trying to modify or add options to an existing field (defined in the parent theme).

I already tried [this](http://stackoverflow.com/questions/27799026/wordpress-adding-to-redux-theme-options-using-child-theme), but unfortunately this only adds a new section. I want to edit an existing one, also tried out something like this: 
```
function add_another_field_value_sk($field){
    $field[] = array(
                            'id'       => 'th_select_stylesheet',
                            'type'     => 'select',
                            'title'    => __( 'Theme Stylesheet', 'redux-framework-demo' ),
                            'subtitle' => __( 'Select your themes alternative color scheme.', 'redux-framework-demo' ),
                            'options'  => array( 'default.css' => 'default.css', 'blue.css'  => 'blue.css', 'brown.css'  => 'brown.css', 'green.css'  => 'green.css', 'orange.css'  => 'orange.css', 'purple.css'  => 'purple.css', 'red.css'  => 'red.css', ),
                            'default.css'  => 'default.css',
    );

    return $field;
}
// In this example: opt_name = theme_data.
add_filter("redux/options/theme_data/field/th_select_stylesheet/register", 'add_another_field_value_sk');
```
I'm referring to the [filter-hooks-documentation](https://docs.reduxframework.com/core/advanced/filter-hooks/) - Tag = redux/options/{opt_name}/field/{field.id}/register

Has anyone an idea how I could accomplish this?

**Comment by MichaelKaeser** [comment]
Just found out how to do it on my own:
```
function add_another_field_value_sk($field){

    $field['title'] = __( 'Theme Stylesheet Custom', 'redux-framework-demo' );
    $field['options']['newcolor.css'] = 'newcolor.css';

    return $field;
}
// In this example OPT_NAME is the returned opt_name.
add_filter('redux/options/theme_data/field/th_select_stylesheet/register', 'add_another_field_value_sk');
```
But what's the difference between those two filters hooks?
redux/options/{opt_name}/field/{field.id}/register
redux/options/{opt_name}/field/{field.id}

It works with ../register but not with the second one?

**Comment by dovy** [comment]
/register = before the data gets running

/ = after the data has been created, so you can get the value, and completed declaration.   ;)

Glad you got it!

**Comment by anupalhub** [comment]
Please help.
How to include the above inside any existing section?
