### ISSUE TITLE
Redux Screen is active on first Theme activation

### ISSUE THREAD

**Issue by TukuTuru** [reduxframework/redux-framework#2407]
I am not sure wether it is my bad, or expected, or whatever.

The current situation is that when I activate my theme the FIRST time on a fresh install, the Redux welcome screen opens (the one that usually is under the tools tab

I have removed that tab programmatically, so it is not present, but still, on FIRST theme activation the screen that usually shows there, is displayed. Once navigated away, you can't re-access it because the tab isn't there of course (which is what I want)

So, How can I "get rid" of this screen also on first time activation?
I mean, nice would be to show the theme admin on first activation, or whatever, but I would like to not show this Redux Screen

Thanks for any hint, and sorry if this has already been asked a thousand times :)

BTW, debug is off, and the rest is working just great :)

**Comment by kprovance** [comment]
You can't.  It's that way by design.  I've also removed the code that shows how to circumvent our support tab, since we really do NOT want folks removing it.
