### ISSUE TITLE
Unexpected token u

### ISSUE THREAD

**Issue by mquestionable** [reduxframework/redux-framework#2408]
Hello, after adding *'class' => 'test'* to field with type *color_rgba*, that field and all underneath doesn't work correctly (if I add class to any other field type it works perfectly) and I get error in console saying:
```
Uncaught SyntaxError: Unexpected token u
admin.php:1
```

Am I doing something wrong or is it problem with framework?
Thanks

**Comment by kprovance** [comment]
Please provide a support URL:  https://docs.reduxframework.com/core/generating-a-support-hash/

**Comment by mquestionable** [comment]
Here you go: http://support.redux.io/?id=kht72H7Jh5TGz0bSH7XyQM4YRkC%2BoIXIewUp%2BMrxAHPGB4mPd5Lqm5ucTrpPX60fNLaUwLg5O%2FPI%2BD0CR2FDOA%3D%3D

Thanks

**Comment by kprovance** [comment]
Well, I ran your config and added class names to all the class arguments of your color_rgba fields.  I don;t see any improper rendering.  That message you report sometimes has to do with the ad server acting wonky, but I've never seen it affect render.  Could you provide a screen cap of this bad render?  Also, FWIW, the colorrgba doesn't work.  It was geared toward the previous library we used for the color_rgba field.  I'd remove them.  Spectrum pretty much validates itself.

**Comment by mquestionable** [comment]
Here is screenshot: http://prntscr.com/7jpg9i
Sorry but I couldn't really understand you that last sentences, I shouldn't use color_rgba?

**Comment by kprovance** [comment]
No, I said using the colorrgba in the validate argument isn't needed.  Cut and paste back the entire field with the added class.  I need to try EXACTLY what you are trying.

Also, please try updating to the lastest version of Redux  v3.5.4.20

**Comment by mquestionable** [comment]
Oh, okay. I copy/pasted what is in sample-config for color_rgba, there is also validate argument.

I update it and now It works. Sorry, I needed to update it first and then ask question if there is still problem, that was so rookie mistake.

Sorry again and thank you very much!

**Comment by kprovance** [comment]
Not a problem.  Glad it worked out.  :)
