### ISSUE TITLE
Icons Not Working With Info Field

### ISSUE THREAD

**Issue by renegademarketer** [reduxframework/redux-framework#2410]
When using Elusive Icons with the Info Field, it shows a square instead of the selected icon. However, the exact same Elusive Icons work properly with the Sections field. See a screenshot here: https://drive.google.com/file/d/0B4R3Y3od0fzuVXhiY1o1YVpVNGs/view?usp=sharing

Here is the code I'm using:

      array(
			'icon' => 'el-icon-envelope',
			'id'   => 'contact_notice',
			'type' => 'info',
			'style' => 'success',
			'desc' => __('<strong>Contact Details</strong><br /> Enter your business contact information below. It will be used on your review pages.', 'customersvoice')
	        ),

My Redux version is: 3.5.4.3
WP version 4.2.2
I'm getting same results both in or not in dev_mode

**Comment by dovy** [comment]
Try el el-icon-envelope. ;)

**Comment by renegademarketer** [comment]
@dovy, thanks that worked.

**Comment by dovy** [comment]
;)
