### ISSUE TITLE
WordPress Theme check failed 

### ISSUE THREAD

**Issue by luckyali55** [reduxframework/redux-framework#2411]
Hi, 
I am using redux for a wordpress theme. While testing i got warning and errors which causes them test failed. 

Am using latest version of redux 4.2.2

Got the following result.

Results of Automated Theme Scanning: Fail

WARNING: Found PHP short tags in file parsedown.php.
Line 838: if (preg_match('/^\[(.+?)\]:[ ]*<?(\S+?)>?(?:[ ]+['\'(](.+)['\')])?[ ]*$/', $Line['text'], $matches))
WARNING: fwrite was found in the file scss.inc.php File operations should use the WP_Filesystem methods instead of direct PHP filesystem calls.
Line 830: fwrite(STDERR, 'Line $line DEBUG: $value\n');
WARNING: fread was found in the file panel.php File operations should use the WP_Filesystem methods instead of direct PHP filesystem calls.
Line 272: $file_data = fread( $fp, 8192 );
WARNING: fread was found in the file class.redux_helpers.php File operations should use the WP_Filesystem methods instead of direct PHP filesystem calls.
Line 642: $file_data = fread( $fp, 8192 );
WARNING: fread was found in the file class.redux_api.php File operations should use the WP_Filesystem methods instead of direct PHP filesystem calls.
Line 466: $file_data = fread( $fp, $size );
WARNING: fopen was found in the file panel.php File operations should use the WP_Filesystem methods instead of direct PHP filesystem calls.
Line 269: $fp = fopen( $file, 'r' );
WARNING: fopen was found in the file class.redux_helpers.php File operations should use the WP_Filesystem methods instead of direct PHP filesystem calls.
Line 376: $sysinfo['redux_data_writeable'] = self::makeBoolStr( @fopen( ReduxFramework::$_upload_dir . 'test-log.log', 'a' ) );
Line 639: $fp = fopen( $file, 'r' );
WARNING: fopen was found in the file class.redux_api.php File operations should use the WP_Filesystem methods instead of direct PHP filesystem calls.
Line 463: $fp = fopen( $file, 'r' );
WARNING: file_put_contents was found in the file scss.inc.php File operations should use the WP_Filesystem methods instead of direct PHP filesystem calls.
Line 4475: file_put_contents($out, $css);
Line 4476: file_put_contents($this->importsCacheName($out),
WARNING: file_put_contents was found in the file class.redux_sass.php File operations should use the WP_Filesystem methods instead of direct PHP filesystem calls.
Line 59: $ret = @file_put_contents(self::$matrix_file, $ids);
Line 166: $ret = @file_put_contents($css_file, $new_css);
Line 206: $ret = @file_put_contents($scss_path . '/' .  $filename . '.css', $new_css);
WARNING: file_put_contents was found in the file class.redux_filesystem.php File operations should use the WP_Filesystem methods instead of direct PHP filesystem calls.
Line 161: $res = file_put_contents( $file, $content, $chmod );
WARNING: file_get_contents was found in the file scss.inc.php File operations should use the WP_Filesystem methods instead of direct PHP filesystem calls.
Line 1652: $code = file_get_contents($path);
Line 4430: $imports = unserialize(file_get_contents($icache));
Line 4468: $css = $this->scss->compile(file_get_contents($in), $in);
Line 4529: echo file_get_contents($output);
WARNING: file_get_contents was found in the file class.redux_sass.php File operations should use the WP_Filesystem methods instead of direct PHP filesystem calls.
Line 52: $ids = file_get_contents(self::$matrix_file);
WARNING: file_get_contents was found in the file class.redux_filesystem.php File operations should use the WP_Filesystem methods instead of direct PHP filesystem calls.
Line 187: $res = @file_get_contents( $file );
WARNING: fclose was found in the file panel.php File operations should use the WP_Filesystem methods instead of direct PHP filesystem calls.
Line 275: fclose( $fp );
WARNING: fclose was found in the file class.redux_helpers.php File operations should use the WP_Filesystem methods instead of direct PHP filesystem calls.
Line 645: fclose( $fp );
WARNING: fclose was found in the file class.redux_api.php File operations should use the WP_Filesystem methods instead of direct PHP filesystem calls.
Line 469: fclose( $fp );
WARNING: .name .ds_store Hidden Files or Folders found.
REQUIRED: welcome.php. Themes should use add_theme_page() for adding admin pages.
Line 196: add_management_page(
Line 204: add_management_page(
Line 212: add_management_page(
Line 220: add_management_page(
Line 229: add_management_page(
Line 237: add_management_page(
REQUIRED: framework.php. Themes should use add_theme_page() for adding admin pages.
Line 1307: // wrappers and need to be appened to using add_submenu_page.
Line 1357: $this->page = add_submenu_page(
Line 1416: add_submenu_page(
RECOMMENDED: No reference to add_theme_support( "title-tag" ) was found in the theme. It is recommended that the theme implement this functionality for WordPress 4.1 and above.
RECOMMENDED: No reference to add_theme_support( "custom-header", $args ) was found in the theme. It is recommended that the theme implement this functionality if using an image for the header.
RECOMMENDED: No reference to add_theme_support( "custom-background", $args ) was found in the theme. If the theme uses background images or solid colors for the background, then it is recommended that the theme implement this functionality.
RECOMMENDED: Theme URI: is missing from your style.css header.
INFO: Non-printable characters were found in the welcome.php file. You may want to check this file for errors.
Line 102: echo 'If you like <strong>Redux</strong> please leave us a <a href='https://wordpress.org/support/view/plugin-reviews/redux-framework?filter=5#postform' target='_blank' class='redux-rating-link' data-rated='Thanks :)'>���������������</a> rating. A huge thank you from Redux in advance!';
INFO: welcome.php The theme appears to use include or require. If these are being used to include separate sections of a template from independent files, then get_template_part() should be used instead.
Line 375: include_once( 'views/about.php' );
Line 390: include_once( 'views/changelog.php' );
Line 405: include_once( 'views/extensions.php' );
Line 421: include_once( 'views/support.php' );
Line 436: include_once( 'views/credits.php' );
Line 451: include_once( 'views/status_report.php' );
INFO: tracking.php The theme appears to use include or require. If these are being used to include separate sections of a template from independent files, then get_template_part() should be used instead.
Line 280: require_once( ABSPATH . 'wp-admin/includes/admin.php' );
INFO: panel.php The theme appears to use include or require. If these are being used to include separate sections of a template from independent files, then get_template_part() should be used instead.
Line 254: include( $path );
INFO: framework.php The theme appears to use include or require. If these are being used to include separate sections of a template from independent files, then get_template_part() should be used instead.
Line 35: require_once( dirname( __FILE__ ) . '/inc/class.redux_instances.php' );
Line 36: require_once( dirname( __FILE__ ) . '/inc/lib.redux_instances.php' );
Line 47: require_once( dirname( __FILE__ ) . '/inc/class.redux_cdn.php' );
Line 50: require_once( dirname( __FILE__ ) . '/inc/class.redux_api.php' );
Line 53: require_once( dirname( __FILE__ ) . '/inc/class.redux_helpers.php' );
Line 56: require_once( dirname( __FILE__ ) . '/inc/class.redux_functions.php' );
Line 57: require_once( dirname( __FILE__ ) . '/inc/class.p.php' );
Line 59: require_once( dirname( __FILE__ ) . '/inc/class.redux_filesystem.php' );
Line 62: require_once( dirname( __FILE__ ) . '/inc/class.redux_themecheck.php' );
Line 65: require_once( dirname( __FILE__ ) . '/inc/welcome/welcome.php' );
Line 67: //require_once( dirname( __FILE__ ) . '/inc/class.redux_sass.php' );
Line 648: require_once( dirname( __FILE__ ) . '/inc/tracking.php' );
Line 1588: require_once( $class_file );
Line 1663: include_once( 'core/enqueue.php' );
Line 1977: include( ABSPATH . 'wp-includes/pluggable.php' );
Line 2430: require_once( $class_file );
Line 2807: include_once( 'core/enqueue.php' );
Line 2811: include_once( 'core/panel.php' );
Line 2961: require_once( $class_file );
Line 3186: include_once( 'core/panel.php' );
Line 3326: require_once( $class_file );
INFO: field_select.php The theme appears to use include or require. If these are being used to include separate sections of a template from independent files, then get_template_part() should be used instead.
Line 57: require_once( $icons_file );
INFO: field_raw.php The theme appears to use include or require. If these are being used to include separate sections of a template from independent files, then get_template_part() should be used instead.
Line 32: require_once( $this->field['include'] );
INFO: extension_customizer.php The theme appears to use include or require. If these are being used to include separate sections of a template from independent files, then get_template_part() should be used instead.
Line 629: require_once( $class_file );
INFO: enqueue.php The theme appears to use include or require. If these are being used to include separate sections of a template from independent files, then get_template_part() should be used instead.
Line 318: require_once( $class_file );
INFO: class.redux_sass.php The theme appears to use include or require. If these are being used to include separate sections of a template from independent files, then get_template_part() should be used instead.
Line 140: require( 'scssphp/scss.inc.php' );
Line 191: require( 'scssphp/scss.inc.php' );
INFO: class.redux_helpers.php The theme appears to use include or require. If these are being used to include separate sections of a template from independent files, then get_template_part() should be used instead.
Line 99: require_once( ABSPATH . 'wp-admin/includes/admin.php' );
INFO: class.redux_functions.php The theme appears to use include or require. If these are being used to include separate sections of a template from independent files, then get_template_part() should be used instead.
Line 112: require_once( ABSPATH . '/wp-admin/includes/file.php' );
INFO: class.redux_filesystem.php The theme appears to use include or require. If these are being used to include separate sections of a template from independent files, then get_template_part() should be used instead.
Line 79: require_once( ABSPATH . '/wp-admin/includes/template.php' );
Line 80: require_once( ABSPATH . '/wp-admin/includes/file.php' );
INFO: class.redux_api.php The theme appears to use include or require. If these are being used to include separate sections of a template from independent files, then get_template_part() should be used instead.
Line 65: require_once( $extension['path'] );

**Comment by dovy** [comment]
Read our theme check docs. ;)

**Comment by luckyali55** [comment]
@dovy i read that, i removed that directories mentioned in documentation, but still theme check is failed. Documentation doesn't help me pass the theme check test.
