### ISSUE TITLE
Redux Framework and QTranslateX, Post title not translate

### ISSUE THREAD

**Issue by Shinnobi23** [reduxframework/redux-framework#2412]
First of all, Many thanks for creating an AWESOME PLUGIN.

I use [Qtranslate X plugin](https://wordpress.org/plugins/qtranslate-x) to make my site support multi-language and Redux Framework to create Theme Options, it doesn't return the single title for chosen language. I expected it to return "Title" NOT "[:en]English Title[:][:fr]French Title[:]".

![theme options wordpress - google chrome](https://cloud.githubusercontent.com/assets/2570579/8272457/5c9a1780-186d-11e5-880b-c51c6c64d7bd.jpg)

I use this code to render select and sort-able "Tour" (custom post type) field.

```php
array(
    'id'         => 'option_id',
    'type'     => 'select',
    'data'     => 'post',
    'args'     => array(
         'post_type'   => array('tour'),
         'posts_per_page' => -1
    ),
    'multi'      => true,
    'sortable' => true,
     'title'       => __( 'Option Title', TEXT_DOMAIN ),
),
```

Please help. Many Thanks.

**Comment by kprovance** [comment]
See #2396
