### ISSUE TITLE
Hints Not Working Anymore

### ISSUE THREAD

**Issue by renegademarketer** [reduxframework/redux-framework#2413]
I'm developing a project and had Hints working. After a month or so break, I recently updated my Redux install and now the Hints are no longer rendering. Below is a sample of the code I'm using:

      array(
                            'id'    => 'coupon_bad_expiration',
                            'type'  => 'date',
                            'title' => __('Coupon Expiration Date', 'customersvoice'), 
                            'subtitle' => __('Enter the expiration date of your offer. Skip this option to have no expiration date.', 'customersvoice'),
                            'desc' =>__('Select a date from the popup calendar.', 'customersvoice'),                           
                            'placeholder' => 'Click to enter a date',
                            'required' => array('coupon_bad_results_yes_no','equals','1'),                             
                             'hint'  => array(
                               'content' => __('We suggest including an expiration date within 30 to 60 days.','customersvoice'),
                             ),
                            ),    

My Redux version is: 3.5.4.3
WP version 4.2.2
I'm getting same results both in or not in dev_mode

**Comment by kprovance** [comment]
Please update to the latest version of Redux from our repo first.  Post back if the problem persists.  If it does, please provide a support url  https://docs.reduxframework.com/core/generating-a-support-hash/

**Comment by renegademarketer** [comment]
Updated to the latest version as instructed and problem still exists. My support url is: http://support.redux.io/?id=W1gWvbLzMlMFNz%2Bo1kCq0LiaXkAj42XPNAQ1TQeHLbCmWiBm7b7SSUzjvcauz2v6mDZB5ZZrQPSTD0ycK1TwwA%3D%3D

Additionally, I'm using the Sorter fields and had labels under each sorter option that have now disappeared.

**Comment by kprovance** [comment]
Oh, I see the problem.  In your args, specifically the hints array, change `icon-question-sign` to `el el-question-sign`.  Elusive icons got updated, which broke some older code.  Sorry about that.

As for sortable (I assume you meant sortable, I did not see a sorter field), make sure the `'label'    => true` is set.

**Comment by renegademarketer** [comment]
@kprovance thanks, your advice worked for both issues. Was going crazy trying to identify the problem. Truly appreciate your assistance.

**Comment by kprovance** [comment]
My pleasure.  :)   I'm guessing you have a fairly old version of Redux, before updating.  Those issues were older ones.  Cheers.  :)
