### ISSUE TITLE
Theme Options Behavior Error and Error Message

### ISSUE THREAD

**Issue by Lors** [reduxframework/redux-framework#2414]
http://support.redux.io/?id=XTiPF5bdL9u%2B35wfdj%2FlJe1U%2B%2BctVRdzE%2BWo7N91goj0slOBxmjt6niKX22lbtyaqomgKf5DcAQZhGftZoPLeA%3D%3D

Hi guys,

I'm having a problem with the github version of redux. When I open the options panel, WITHOUT making any change or modification in any of the fields values, it shows me the following message:

**Settings have changed, you should save them!**

This would be true if I actually enter or change new settings values ( obviously I'm not changing anything as I'm just opening the panel )

And then, when I click the **"Save Changes"** button, an error message is displayed saying:

**There was a problem with your action. Please try again or reload the page.**

I think it isn't an error in my code, because when I switch to the Redux plugin. the theme works just fine, and it compiles perfectly, Im using scssphp compiler and works like heaven with the plugin.

Im wondering about this, maybe you guys can check whats happening in the Github version, I know that the plugin is the stable version, just checking if you know what could be happening within the main code.

Thanks :)

**Comment by kprovance** [comment]
Please open the javascript console log and click the save button, if there are outputted error messages on the page, they will interfere with the saving process, and will show up in that console.

**Comment by Lors** [comment]
Hi Kevin, 
it seems to be when I added a rgba field. The Js Console throw me this message:

```The specified value '!' does not conform to the required format.  The format is '#rrggbb' where rr, gg, bb are two-digit hexadecimal numbers.```

And this warning:

```Warning:  Invalid argument supplied for foreach() in ..../framework/redux-framework/ReduxCore/framework.php on line 2828```

Hopefully it helps.

**Comment by kprovance** [comment]
The ajax save issue is solved with v3.5.4.21.  Not sure what the console warning is about.  I don't have it in mine, and I have enough rgba fields in play to last two lifetimes.  :)

**Comment by Lors** [comment]
Thanks Kevin :) you da man!
