### ISSUE TITLE
Redux Error with WP Engine

### ISSUE THREAD

**Issue by tinadimichele** [reduxframework/redux-framework#2420]
I'm in the process of migrating my site from godaddy to WP Engine.  The migration process is complete but the site is not displaying correctly - I'm chatting with WP Engine support right now and they said it seems to be related to the redux-framework plugin.  

Ex. - preview on WP Engine --  http://resawntimber.wpengine.com/
current site http://resawntimberco.com/

Error messages:

[Tue Jun 23 00:56:31.153006 2015] [:error] [pid 18393] [client 73.194.145.158:46325] PHP Fatal error: Class 'ReduxFramework_Extension__notes' not found in /nas/wp/www/cluster-40876/re…mework/ReduxCore/framework.php on line 2403, referer: http://resawntimber.wpengine.com/rstco-furniture/

[Tue Jun 23 00:45:42.628364 2015] [:error] [pid 16362] [client 66.162.212.19:44317] PHP Fatal error: Class 'ReduxFramework_Extension__notes' not found in /nas/wp/www/cluster-40876/re…mework/ReduxCore/framework.php on line 2403, referer: http://resawntimber.wpengine.com/

It also seems that the woocommerce portion of the site is not working correctly.

Any ideas?

**Comment by kprovance** [comment]
In your extensions folder, delete any folder that begins with '__notes'.  As for Woocommerce issues, you'll need to contact them.  We do not handle support for Woo.  :)

**Comment by tinadimichele** [comment]
wowie that was fast - thanks!  working on it now

**Comment by tinadimichele** [comment]
unfortunately it did not work

**Comment by kprovance** [comment]
You're going to have to go through ALL the folders in the extension folder and delete them all.

**Comment by tinadimichele** [comment]
kprovance you are nothing short of AMAZING -- thanks for all your help -- this worked!
