### ISSUE TITLE
Yes-Template: Couldn't add Event Section

### ISSUE THREAD

**Issue by svolvaer** [reduxframework/redux-framework#2422]
Hi there, 
I have buyed the yes-template. And i will change my initial-page.

If i want to add the "Event Section" with visual Composer i receive this error-code:

Warning: Invalid argument supplied for foreach() in //wp-content/plugins/js_composer/include/classes/editors/class-vc-edit-form-fields.php on line 199

i don't know how i could fix it.

The wordpress is completely new installed, the template and the cild-template is new installed.

Could anybody help?

Thanks a lot.
svolvaer

**Comment by dovy** [comment]
We didn't build that theme or visual composer where the issue apparently is. Best to contact your theme developer. Good luck!
