### ISSUE TITLE
extensions_init.php does not work for v3.5.4.3

### ISSUE THREAD

**Issue by sarpdoruk** [reduxframework/redux-framework#2425]
In `extensions-init.php` the first 2 lines is like this;

    // All extensions placed within the extensions directory will be auto-loaded for your Redux instance.
    Redux::setExtensions( 'my_theme', dirname( __FILE__ ) . '/extensions/' );

and here is the related method from Redux Core;

    public static function setExtensions( $opt_name, $path ) {
                if ( is_dir( $path ) ) {
                    $path   = trailingslashit( $path );
                    $folder = str_replace( '.php', '', basename( $path ) );
                    if ( file_exists( $path . 'extension_' . $folder . '.php' ) ) {
                        self::checkExtensionClassFile( $opt_name, $folder, $path . 'extension_' . $folder . '.php' );
                    }
    ...

If you look at the first 4 lines of the method you can easily see that `file_exists( $path . 'extension_' . $folder . '.php' )` outputs `/path/to/the/wordpress/theme/admin/redux-extensions/extensions/extension_extensions.php`

`Redux::setExtensions( 'my_theme', dirname( __FILE__ ) . '/extensions/' );` line in `extensions-init.php`  should auto-load all the extensions in the `extensions` folder but instead it tries to load `/path/to/the/wordpress/theme/admin/redux-extensions/extensions/extension_extensions.php` which does not make any sense.

I found the solution;
If I change the 2nd line in `extensions-init.php` to `Redux::setExtensions( 'my_theme', dirname( __FILE__ ) . '/extensions/my_extension_folder' );` it works fine.

Now here is my question; Am I supposed to edit this file and write `Redux::setExtensions( 'my_theme', dirname( __FILE__ ) . '/extensions/my_extension_folder' );` there or is it just a bug you need to fix ?

In earlier versions I was using extension-loader and it worked just fine because content of the `extensions-init.php` was different.

**Comment by kprovance** [comment]
Try upgrading to the latest version of Redux from this repo before rewriting things.  The wp.org version is mildly outdated.

**Comment by sarpdoruk** [comment]
Actually, I am using Redux Builder.  I just created & downloaded an admin-folder.zip for myself.  v3.5.4.3 is the only stable version option there.

**Comment by dovy** [comment]
Yes, please use the development branch so we can see if we fixed it previously.

**Comment by sarpdoruk** [comment]
Yep, It works with the latest version. :+1: 

Btw, you should update the version at Redux Builder too.

Thank you.

**Comment by kprovance** [comment]
<blockquote>
Btw, you should update the version at Redux Builder too.
</blockquote>

I'm looking at the version select now, the development branch IS listed,  :)
