### ISSUE TITLE
section indent css issue field_section.css

### ISSUE THREAD

**Issue by dimitrilongo** [reduxframework/redux-framework#2426]
I was trying to get session indent work. I' had a css issue with

```<table id="section-table-section-start" data-id="section-start" class="form-table form-table-section no-border form-table-section-indented">```

css file ``` field_section.css``` is loaded but rule from class name ```form-table-section-indented``` not applied.
I thought it was my config so i install a fresh version from redux builder same issue, so i look the css from http://demo.redux.io/ and indent works, but small difference in  ```field_section.css```
 css from builder or my install :
```.redux-section-field .form-table-section-indented{width:95%;margin-left:5%}```
css from demo.redux.io :
```.redux-main .form-table-section-indented{width:95%;margin-left:5%}```
So it works with ```.redux-main .form-table-section-indented{width:95%;margin-left:5%}```

Regards
Dimitri

redux : v3.5.4.21
wp 4.2.2
mamp pro
dev mode

**Comment by kprovance** [comment]
We had a user 'contribute' to the CSS at some point, and it's been all downhill ever since.  I'll see if I can figure this one out too.

**Comment by kprovance** [comment]
Fixed in v3.5.4.24.  Thanks.  :)
