### ISSUE TITLE
Not work the 'required' argument based on checkbox or checkbox sortable

### ISSUE THREAD

**Issue by kisonic** [reduxframework/redux-framework#2429]
I install Redux Framework like a plugin in wordpress, copy redux-framework/sample/sample-config.php to my theme and change it. And I have problem with this part:

```php
Redux::setSection( $opt_name, array(
    'id' => 'sec_test',
    'title' => __('test', 'redux-framework-demo'),
    'fields' => array(
        array(
            'id' => 'test_checkbox',
            'type' => 'checkbox',
            'title' => __('test', 'redux-framework-demo'),
            'options' => array(
                'test_1' => 'test 1',
                'test_2' => 'test 2',
            ),
            'default' => array(
                'test_1' => 1,
                'test_2' => 0,
            ),
        ),

        array(
            'id' => 'test_opt',
            'type' => 'text',
            'title' => __('test text', 'redux-framework-demo'),
            'required' => array('test_checkbox', '=', 'test_1'),
        ),
    )
) );
```
'required' in option 'test_opt' not work. I try this variations:
```php
'required' => array('test_checkbox', '=', 'test_1'),
'required' => array('test_checkbox', '=', array('test_1')),
'required' => array('test_checkbox', '=', array('test_1' => 1)),
'required' => array('test_checkbox', 'contains', 'test_1'),
'required' => array('test_checkbox', 'contains', array('test_1')),
'required' => array('test_checkbox', 'contains', array('test_1' => 1)),
```
Nothing works.
Sometimes 'test_opt' is visible, but when I click on some checkbox (no matter 'test_1' or 'test_2') option 'test_opt' is hide and no show again.

Wordpress: 4.2.2

Redux Framework: 3.5.4.3

Developer Mode Enabled

P.S. Sorry for my english if something incorrect.

**Comment by dovy** [comment]
Please provide us this as well: https://docs.reduxframework.com/core/generating-a-support-hash/

**Comment by kisonic** [comment]
http://support.redux.io/?id=%2B5UpkW9Nz8TTGFkuBOvYv0AlwJ88Sv%2FlVITUQcp5yH3TugkjvbmfFB8tIgJwp%2FkwVvO%2B9FCHkEzP891FcUfH%2BQ%3D%3D

**Comment by kprovance** [comment]
Fixed in v.3.5.4.25.

You will need to do this:
```php
'required' => array('test_checkbox', 'contains', array('test_1' => 1)),
```

**Comment by kisonic** [comment]
Cool! When new version will be available on wordpress.org/plugins/?
