### ISSUE TITLE
Theme check issues

### ISSUE THREAD

**Issue by arunschandran** [reduxframework/redux-framework#2430]
Hi Redux team,

Thanks for this wonderful framework. This framework is awesome.
But when I checked the theme using theme check, i found following Errors

WARNING: Found PHP short tags in file parsedown.php.
Line 838: if (preg_match('/^\[(.+?)\]:[ ]*<?(\S+?)>?(?:[ ]+['\'(](.+)['\')])?[ ]*$/', $Line['text'], $matches))
WARNING: fwrite was found in the file scss.inc.php File operations should use the WP_Filesystem methods instead of direct PHP filesystem calls.
Line 830: fwrite(STDERR, 'Line $line DEBUG: $value\n');
WARNING: fread was found in the file panel.php File operations should use the WP_Filesystem methods instead of direct PHP filesystem calls.
Line 270: $file_data = fread( $fp, 8192 );
WARNING: fread was found in the file class.redux_helpers.php File operations should use the WP_Filesystem methods instead of direct PHP filesystem calls.
Line 637: $file_data = fread( $fp, 8192 );
WARNING: fread was found in the file class.redux_api.php File operations should use the WP_Filesystem methods instead of direct PHP filesystem calls.
Line 372: $file_data = fread( $fp, $size );
WARNING: fopen was found in the file panel.php File operations should use the WP_Filesystem methods instead of direct PHP filesystem calls.
Line 267: $fp = fopen( $file, 'r' );
WARNING: fopen was found in the file class.redux_helpers.php File operations should use the WP_Filesystem methods instead of direct PHP filesystem calls.
Line 376: $sysinfo['redux_data_writeable'] = self::makeBoolStr( @fopen( ReduxFramework::$_upload_dir . 'test-log.log', 'a' ) );
Line 634: $fp = fopen( $file, 'r' );
WARNING: fopen was found in the file class.redux_api.php File operations should use the WP_Filesystem methods instead of direct PHP filesystem calls.
Line 369: $fp = fopen( $file, 'r' );
WARNING: file_put_contents was found in the file scss.inc.php File operations should use the WP_Filesystem methods instead of direct PHP filesystem calls.
Line 4475: file_put_contents($out, $css);
Line 4476: file_put_contents($this->importsCacheName($out),
WARNING: file_put_contents was found in the file class.redux_sass.php File operations should use the WP_Filesystem methods instead of direct PHP filesystem calls.
Line 59: $ret = @file_put_contents(self::$matrix_file, $ids);
Line 166: $ret = @file_put_contents($css_file, $new_css);
Line 206: $ret = @file_put_contents($scss_path . '/' .  $filename . '.css', $new_css);
WARNING: file_put_contents was found in the file class.redux_filesystem.php File operations should use the WP_Filesystem methods instead of direct PHP filesystem calls.
Line 160: $res = file_put_contents( $file, $content, $chmod );
WARNING: file_get_contents was found in the file scss.inc.php File operations should use the WP_Filesystem methods instead of direct PHP filesystem calls.
Line 1652: $code = file_get_contents($path);
Line 4430: $imports = unserialize(file_get_contents($icache));
Line 4468: $css = $this->scss->compile(file_get_contents($in), $in);
Line 4529: echo file_get_contents($output);
WARNING: file_get_contents was found in the file class.redux_sass.php File operations should use the WP_Filesystem methods instead of direct PHP filesystem calls.
Line 52: $ids = file_get_contents(self::$matrix_file);
WARNING: file_get_contents was found in the file class.redux_filesystem.php File operations should use the WP_Filesystem methods instead of direct PHP filesystem calls.
Line 186: $res = file_get_contents( $file );
WARNING: fclose was found in the file panel.php File operations should use the WP_Filesystem methods instead of direct PHP filesystem calls.
Line 273: fclose( $fp );
WARNING: fclose was found in the file class.redux_helpers.php File operations should use the WP_Filesystem methods instead of direct PHP filesystem calls.
Line 640: fclose( $fp );
WARNING: fclose was found in the file class.redux_api.php File operations should use the WP_Filesystem methods instead of direct PHP filesystem calls.
Line 375: fclose( $fp );
REQUIRED: No content width has been defined. Example:
if ( ! isset( $content_width ) ) $content_width = 900;
REQUIRED: welcome.php. Themes should use add_theme_page() for adding admin pages.
Line 193: add_management_page(
Line 201: add_management_page(
Line 209: add_management_page(
Line 217: add_management_page(
Line 226: add_management_page(
Line 234: add_management_page(
REQUIRED: framework.php. Themes should use add_theme_page() for adding admin pages.
Line 1283: // wrappers and need to be appened to using add_submenu_page.
Line 1333: $this->page = add_submenu_page(
Line 1392: add_submenu_page(
Line 1408: add_submenu_page(
REQUIRED: debug.php. Themes should use add_theme_page() for adding admin pages.
Line 74: add_submenu_page(
RECOMMENDED: No reference to the_post_thumbnail() was found in the theme. It is recommended that the theme implement this functionality instead of using custom fields for thumbnails.
RECOMMENDED: No reference to add_editor_style() was found in the theme. It is recommended that the theme implement editor styling, so as to make the editor content match the resulting post output in the theme, for a better user experience.
RECOMMENDED: Tags: is either empty or missing in style.css header.

Can you guys please help me?

**Comment by kprovance** [comment]
https://docs.reduxframework.com/core/theme-check/

**Comment by arunschandran** [comment]
Thanks for the reply.

I already red that. But how can i solve issues like

WARNING: fwrite was found in the file scss.inc.php File operations should use the WP_Filesystem methods instead of direct PHP filesystem calls.
Line 830: fwrite(STDERR, 'Line $line DEBUG: $value\n');
WARNING: fread was found in the file panel.php File operations should use the WP_Filesystem methods instead of direct PHP filesystem calls.
Line 270: $file_data = fread( $fp, 8192 );
WARNING: fread was found in the file class.redux_helpers.php File operations should use the WP_Filesystem methods instead of direct PHP filesystem calls.
Line 637: $file_data = fread( $fp, 8192 );
WARNING: fread was found in the file class.redux_api.php File operations should use the WP_Filesystem methods instead of direct PHP filesystem calls.
Line 372: $file_data = fread( $fp, $size );
WARNING: fopen was found in the file panel.php File operations should use the WP_Filesystem methods instead of direct PHP filesystem calls.
Line 267: $fp = fopen( $file, 'r' );
WARNING: fopen was found in the file class.redux_helpers.php File operations should use the WP_Filesystem methods instead of direct PHP filesystem calls.
Line 376: $sysinfo['redux_data_writeable'] = self::makeBoolStr( @fopen( ReduxFramework::$_upload_dir . 'test-log.log', 'a' ) );
Line 634: $fp = fopen( $file, 'r' );
WARNING: fopen was found in the file class.redux_api.php File operations should use the WP_Filesystem methods instead of direct PHP filesystem calls.
Line 369: $fp = fopen( $file, 'r' );

**Comment by kprovance** [comment]
There are some things that wp_filesystem cannot be used for.  Who is this for?  wp.org?  They no longer accept themes with the Redux panels.  If it's for ThemeForest, I don't believe they really care.

**Comment by arunschandran** [comment]
Ok thanks kprovance. this is for ThemeForest :)

**Comment by dovy** [comment]
We're going to do our best to fix this going forward. In the meantime, just use TGM to install Redux as a plugin and all will be good again.  ;)
