### ISSUE TITLE
error when saving theme options

### ISSUE THREAD

**Issue by oyarhaag** [reduxframework/redux-framework#2431]
**"There was a problem with your action. Please try again or reload the page."**

---

**General**
Remote Address:178.32.95.220:80
Request URL:http://sunshineholidays.oyarhaag.com/wp-admin/admin-ajax.php
Request Method:POST
Status Code:413 Request Entity Too Large

**Response Headers**
Connection:keep-alive
Content-Encoding:gzip
Content-Length:304
Content-Type:text/html; charset=iso-8859-1
Date:Fri, 26 Jun 2015 10:34:44 GMT
Server:nginx
Vary:Accept-Encoding

---

client_max_body_size is 128 mb

What settings do I need to have? I'm running nginx and modsecurity.
You can get access to wordpress installation also.

Thank you in advance!

**Comment by AlexAlexandru** [comment]
Hello I'm not an official developer but I guest they would like you do to this https://docs.reduxframework.com/core/generating-a-support-hash/

**Comment by dovy** [comment]
That means there are too many options in that panel. It won't save because PHP won't allow that many field variables to pass.  :(

We can't fix it. You need to slim down the panel. The only way around it is to modify your PHP.ini file. Sorry.

**Comment by oyarhaag** [comment]
I got it now... For you as advice - When running nginx with or without
modsecurity you need to increase the "SecRequestBodyNoFilesLimit" in your
settings. In my case the POST content length was over 200,000. The limit
should be above this value.

Mit besten Grüßen / with best regards

Benjamin Haag

[image: logo] <http://www.oyarhaag.de>Rügener Weg 33, 68309 Mannheim

Benjamin Haag

Telefon: +49 (621) 95 35 40 65
Mobil: +49 (178) 54 22 444
E-Mail: haag@oyarhaag.de
Web: www.oyarhaag.de <http://http//www.oyarhaag.de/>


[image: Profilbild]
[image: Facebook] <http://www.facebook.com/oyarhaag> [image: LinkedIn]
<http://www.linkedin.com/in/benjaminhaag> [image: Xing]
<http://www.xing.com/profile/Benjamin_Haag5>

[image: Please consider the environment before printing this email Join the
campaign at http://thinkBeforePrinting.org] <http://thinkbeforeprinting.org>


DE: Der Inhalt dieser E-Mail und aller Anlagen ist vertraulich und enthaelt
rechtlich geschuetzte Informationen. Er ist ausschliesslich fuer den
bezeichneten Adressaten bestimmt. Wenn Sie nicht der richtige Adressat oder
dessen Vertreter sind, setzen Sie sich bitte mit dem Absender der E-Mail in
Verbindung und loeschen Sie diese E-Mail von Ihrem Computer. Jede Form der
Nutzung, Veroeffentlichung, Vervielfaeltigung oder Weitergabe des Inhalts
fehlgeleiteter E-Mails ist unzulaessig.

EN: This e-mail message and all attachments transmitted with it are
intended solely for the use of the address and may contain legally
privileged and confidential information. If the reader of this message is
not the intended recipient, or an employee or agent responsible for
delivering this message to the intended recipient, you are hereby notified
that any dissemination, distribution, copying, or other use of this message
or its attachments is strictly prohibited. If you have received this
message in error, please notify the sender immediately by replying to this
message and please delete it from your computer.

2015-06-26 14:23 GMT+02:00 Dovy Paukstys <notifications@github.com>:
