### ISSUE TITLE
Faulty barebones-sample.php

### ISSUE THREAD

**Issue by ltarasiewicz** [reduxframework/redux-framework#2432]
Hello,

I've just started using Redux so I am not bery familiar with it. However, I followed one tutorial, copied the sample/ folder to my theme root directory, activated `barebones-sample.php` in function.php.

This is the error that I receive in the development mode:

> Undefined index: id in /srv/www/sabre.local/current/web/app/plugins/redux-framework/ReduxCore/inc/class.redux_api.php on line 273

> Cannot modify header information - headers already sent by (output started at /srv/www/sabre.local/current/web/app/plugins/redux-framework/ReduxCore/inc/class.redux_api.php:273) in /srv/www/sabre.local/current/web/wp/wp-includes/option.phpon line772

> Cannot modify header information - headers already sent by (output started at /srv/www/sabre.local/current/web/app/plugins/redux-framework/ReduxCore/inc/class.redux_api.php:273) in /srv/www/sabre.local/current/web/wp/wp-includes/option.php on line 773

Am I missing something here? or is this a bug/faulty config?

I will also add that this happens only with barebones-config.php

**Comment by dovy** [comment]
Update to the version of Redux in this repo. We've made quite a few changes. We'll be pushing to .org soon.
