### ISSUE TITLE
Documentation updates

### ISSUE THREAD

**Issue by Enchiridion** [reduxframework/redux-framework#2433]
Hi,
I was going through the field documentation and I found some things that should be fixed:

https://docs.reduxframework.com/core/fields/background/
In the Example Declaration
Line 1, extra --, =-->

https://docs.reduxframework.com/core/fields/color-gradient/
In the Example Declaration
Line 2, extra semi-colon =>;

https://docs.reduxframework.com/core/fields/link-color/
In the Example Declaration
Line 10, end of the line is missing a comma

https://docs.reduxframework.com/core/fields/select-image/
In the Example Declaration
Line 9, missing a comma at the end of the line
Line 13, missing a comma at the end of the line
Line 18, extra ), this line should be removed

https://docs.reduxframework.com/core/fields/sortable/
In the Example Declaration
Line 12, missing a comma at the end of the line
Line 21, ‘default' should be ‘options’

I found the example code a little confusing at first as to what was needed for using it in ‘text’ mode.  It might be better to provide a separate example for each mode:

```
$fields = array(
    'id'       => 'text-sortable',
    'type'     => 'sortable',
    'title'    => __('Sortable Text Option', 'redux-framework-demo'),
    'subtitle' => __('Define and reorder these however you want.', 'redux-framework-demo'),
    'desc'     => __('This is the description field, again good for additional info.', 'redux-framework-demo'),
    'mode'     => 'text',
    'options' => array(
         '1' => 'Item number one',
         '2' => 'Number two here',
         '3' => 'Three strikes, yer out!',
    ),
);

$fields = array(
    'id'       => 'checkbox-sortable',
    'type'     => 'sortable',
    'title'    => __('Sortable Checkbox Option', 'redux-framework-demo'),
    'subtitle' => __('Define and reorder these however you want.', 'redux-framework-demo'),
    'desc'     => __('This is the description field, again good for additional info.', 'redux-framework-demo'),
    'mode'     => 'checkbox',
    'options'  => array(
        '1' => 'Item 1',
        '2' => 'Item 2',
        '3' => 'Item 3',
    ),
    'default' => array(
        '1' => false,
        '2' => true,
        '3' => false,
    ),
);
```

**Comment by kprovance** [comment]
Awesome.  It's all you dude.  Close ticket when you're done.  :)

**Comment by kprovance** [comment]
Never mind, I went ahead and did them myself.  Thanks.
