### ISSUE TITLE
Is it possible to import files/settings to a new Redux Cloud? 

### ISSUE THREAD

**Issue by emorling** [reduxframework/redux-framework#2434]
Is it possible to import files/settings to a new Redux Cloud?

**Comment by kprovance** [comment]
Can't say I'm familiar with a "Redux Cloud".  Redux has an import/export settings feature.  Is that not adequate?

**Comment by emorling** [comment]
@kprovance Sorry I mean in "build.reduxframework.com"

**Comment by kprovance** [comment]
At this time, no.  The builder doesn't deal in actual settings, it generates a customized version of Redux based on the fields you want.  We hope to offer a panel builder in the future - you know - after Redux makes actual revenue.  ;-)
