### ISSUE TITLE
Transferring Theme Options to a menu such as woocommerce

### ISSUE THREAD

**Issue by m0hamm4dElmi** [reduxframework/redux-framework#2435]
Hi There,
I was wondering about transferring Theme Options to a menu such as woocommerce. How can I do that? It looks this feature is available in Redux ( framework.php, line: 1308)

Best Regards

**Comment by kprovance** [comment]
Line 1308 in the latest version is a comment, so I don't know what you're referring to.

**Comment by m0hamm4dElmi** [comment]
Hi There,
You are right; I needed to be more specific. Sorry about that. I’m using latest version of Redux which is 3.5.4.25 and also latest version of WordPress which is 4.2.2
In framework.php in line 1281 add_submenu private function is defined and its general behavior is related on existing if (1301) and else (1306)
If is working fine, it means if we want to transfer theme options to one of Dashboard submenus all we need is using below settings:

'menu_type' => 'submenu',
'page_parent' => 'index.php',

But else in this function which is related to menus such as woocommerce does not act properly. (Although it’s my problem that I can’t apply my config otherwise Redux is fine). So it’s better to ask my question this way:
How can I transfer Theme Options to woocommerce submenu?

Best Regards

**Comment by kprovance** [comment]
For a full list of options, visit: http://codex.wordpress.org/Function_Reference/add_submenu_page#Parameters  You'd want the one concerning edit.php and post_type.
