### ISSUE TITLE
Validation does not operate on empty fields

### ISSUE THREAD

**Issue by rnlmedia** [reduxframework/redux-framework#2436]
As per Dovy's recommendation in https://github.com/reduxframework/redux-framework/issues/2104, I have created my own validation function for doing a key check in addition to checking for empty strings. Everything works great except when validating empty  strings (again)

I have narrowed down the issue to the following code in ReduxCore/framework.php

```php
// Default 'not_empty 'flag to false.
$isNotEmpty = false;
// Make sure 'validate' field is set.
if ( isset ( $field['validate'] ) ) {
    // Make sure 'validate field' is set to 'not_empty' or 'email_not_empty'
    if ( $field['validate'] == 'not_empty' || $field['validate'] == 'email_not_empty' || $field['validate'] == 'numeric_not_empty' ) {
      // Set the flag.
      $isNotEmpty = true;
    }
 }
 // Check for empty id value
if ( ! isset ( $field['id'] ) || ! isset ( $plugin_options[ $field['id'] ] ) || ( isset ( $plugin_options[ $field['id'] ] ) && $plugin_options[ $field['id'] ] == '' ) ) {
    // If we are looking for an empty value, in the case of 'not_empty'
    // then we need to keep processing.
   if ( ! $isNotEmpty ) {
       // Empty id and not checking for 'not_empty.  Bail out...
      continue;
    }
}
```

Because my function is not called not_empty, email_not_empty or numberic_not_empty, $isNotEmptyFlag never gets set an it passes validation (not sure why $field['id']  is not being set).

At the moment I need to add my function name to this ensures the $isNotEmpty flag gets set and for validation checks on empty strings to be run. 

Is this a bug or is there something I am missing?

**Comment by kprovance** [comment]
Probably because those validations are part of our core, and your - if custom - is not.  I'm not sure what tyhe answer is, short of modifying our core for custom code, which we do not like to do.  @Dovy?

**Comment by dovy** [comment]
Hmmmmmmm... Let me think on this.

**Comment by kprovance** [comment]
Have you considered using the validation_callback option?   https://docs.reduxframework.com/core/the-basics/validation/

**Comment by rnlmedia** [comment]
@kprovance Yes, that was originally what I tried to use, see https://github.com/reduxframework/redux-framework/issues/2104. @dovy Recommended trying this method, which has seem to have come to a dead end, suggesting a deeper issue.

The issue is it seems you can't call validation that runs a custom validation function that includes checking for empty values, because empty values checks are only working if the validation function name is one of the certain pre-defined ones (not_empty, email_not_empty or numberic_not_empty).

My thoughts are that an additional key such as 'check_for_empty' on the $field variable is needed and then this can be set when the _validate_values validation function must check a field is not empty?

**Comment by kprovance** [comment]
So, 'check_for_empty' would be a new validation type?  problem is, as it stands, each field can only use one validation type, not several, hence the reason for multiple not empty types.  We don;t want to add everyone custom validation to our core, because if we do it for one person, we have to do it for everyone and then our core could get polluted pretty quickly.

I'm thinking about doing a kind of wildcard check to replace the predetermined ones, so if one wants to write their own validation check, and suffixes it with '_not_empty', the core will recognize it.

**Comment by kprovance** [comment]
Okay, our core now checks the `validate` argument for any validation type ending with `not_empty` and will treat it like it does any other not_empty validation.  So, if you are writing a type to check for something not empty, suffix it with 'not_empty', like 'buggy_buddy_baby_bumper_not_empty' will be treated for a not empty check in the core.  Version 3.5.4.34 or higher.
