### ISSUE TITLE
If not set line-height it set to underfined

### ISSUE THREAD

**Issue by kisonic** [reduxframework/redux-framework#2437]
In field "typography" if not set line-height it set to underfined.
This is part of my config:
```php
array(
	'id' => 'test_font',
	'type' => 'typography',
	'title' => __('Test typography', 'redux-framework-demo'),
	'google' => true,
	'font-backup' => true,
	'subsets' => false,
	'font-size' => false,
	'line-height' => true,
	'text-align' => false,
	'all_styles' => true,
),
```
then I print options:
```
<pre><?print_r($redux_demo["test_font"])?></pre>
```
and what I see:
```
Array
(
    [font-family] => 
    [font-options] => 
    [google] => 1
    [font-backup] => 
    [font-weight] => 
    [font-style] => 
    [line-height] => undefinedpx
    [color] => 
)
```

Wordpress: 4.2.2

Redux Framework: 3.5.4.3

Developer Mode Enabled

**Comment by kprovance** [comment]
Please provide a support URL.

**Comment by kprovance** [comment]
It might also help to set some default values.  If something saves a panel with empty values, well, text with no lone height won't look proper.

**Comment by kprovance** [comment]
Fixed in v.3.5.4.26.  You may need to reset any section affected by this.
