### ISSUE TITLE
Plugin Warning After Latest Update

### ISSUE THREAD

**Issue by wpinsite** [reduxframework/redux-framework#2438]
Just installed the latest update and am now receiving this message in the WordPress Admin:

Redux Framework Warning
The Redux Vendor Support plugin is either not installed or not activated and thus, some controls may not render properly. Please ensure the Redux Vendor Plugin is installed and activated.

Framework is integrated into theme and not installed as a plugin.

**Comment by kprovance** [comment]
Whoops, default value for use_cdn was set incorrectly.  Fixed in v.3.5.4.27

**Comment by wpinsite** [comment]
Thanks Kevin
