### ISSUE TITLE
Select2 CSS CDN 

### ISSUE THREAD

**Issue by abouolia** [reduxframework/redux-framework#2440]
Hello, i have this message "`select2-css CDN unavailable. Some controls may not render properly.`" i don't know where's the problem? can anyone help me. version v3.5.4.27

**Comment by kprovance** [comment]
Are you on a local install, and does it have internet access?  If so, you'll need the vendor support package plugin:  https://reduxframework.com/wp-content/uploads/2015/06/redux-vendor-support.zip
