### ISSUE TITLE
Single Checkbox Style 

### ISSUE THREAD

**Issue by abouolia** [reduxframework/redux-framework#2441]
why is not lining up with the single checkbox it's placing below, is there something wrong in my code or what ? 

![0_lvgnlnjqrslav0nm1tw2szxtbnwzqjx5hu59jlcas](https://cloud.githubusercontent.com/assets/2197422/8446835/c538ec4e-1fa7-11e5-8056-ba63e7a1a319.jpg)

```
array(
                    'id'       => 'page-comments',
                    'type'     => 'checkbox', 
                    'title'    => __('Page - Comments (Default)', 'Redux'),
                    'desc'     => __('Show comments for pages.', 'Redux'),
                    'default'  => false,
                ),
```

**Comment by kprovance** [comment]
Please provide a support URL

**Comment by abouolia** [comment]
oh sorry, now the image works.

**Comment by kprovance** [comment]
Okay?  Cool.  :)

**Comment by abouolia** [comment]
i didn't understand you, i'm asking here why the label of checkbox looks like in the picture?

**Comment by kprovance** [comment]
And I asked you to provide a support URL.  We cannot help without it.  https://docs.reduxframework.com/core/generating-a-support-hash/  I have NO idea why something like that would be happening.  It isn;t happening on my local dev.  Showing me a photo doesn;t really help, and I'd rather not go back and forth for days trying to extract information from you over it.  So please, provide the hash.

**Comment by kprovance** [comment]
Closing.  We cannot offer assistance without the support hash.
