### ISSUE TITLE
In which the file is determined by the value of 'redux-framework-demo'?

### ISSUE THREAD

**Issue by emc390** [reduxframework/redux-framework#2443]
In which the file is determined by the value of 'redux-framework-demo'?
I want to change the value on their own. But I can not find it. Help me please.

**Comment by dovy** [comment]
I'm sorry, but I'm not sure what you're asking here...

**Comment by emc390** [comment]
'title' => __('Additional Fields', 'redux-framework-demo'),

**Comment by dovy** [comment]
The sample-config file is inside ~/sample/sample-config.php.  :)
