### ISSUE TITLE
Is there a way to define a label in the sortable field?

### ISSUE THREAD

**Issue by abhishek1234321** [reduxframework/redux-framework#2444]
Update: I figured it out. Just had to set the **label** option as true (My bad!), you can go ahead and close this issue.

I have this code for the sortable field option (using the latest stable Redux v3.5.4.3 with dev mode turned on)

```php
Redux::setSection( $opt_name, array(
  'title' => __( 'Copyright', 'avc-redux-framework' ),
  'id'    => 'footer-copyright-subsection',
  'icon'  => 'el el-home',
  'subsection' => true,
  'fields'     => array(
    array(
      'id'          => 'footer-social-icons',
      'type'        => 'sortable',
      'url'         => true,
      'title'       => __( 'Social Icons', 'avc-redux-framework' ),
      'options'     => array(
          '1'     => 'Angel List',
          '2'     => 'Twitter',
          '3'     => 'Facebook',
      ),
    ),
  )
) );
```

This is what the redux options look like

![sortable](https://cloud.githubusercontent.com/assets/529159/8461130/07c697be-2048-11e5-919b-8e36d28a8466.png)

Is there a way to label each of the sortable item as shown in this image (Facebook, Twitter etc)

![68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f313630363635352f3131363137372f63633565623365342d366265632d313165322d393538392d3539613039666534333362362e706e67](https://cloud.githubusercontent.com/assets/529159/8461178/57573266-2048-11e5-987a-cc3b99dee187.png)
I got the image from this page https://github.com/ghost1227/historical-redux2/issues/70#issuecomment-12966794 (which was a Redux issue before)

It would be great if somebody can help me on this.

Thanks!

**Comment by kprovance** [comment]
Cool, glad you figured it out.  :)
