### ISSUE TITLE
Typography field dosen't save when select standard font after google font 

### ISSUE THREAD

**Issue by lionhurt** [reduxframework/redux-framework#2446]
Hi, 

Thank you for great work.

Typography field has a simple issue when you select font from google and save options then decide change this font to one form the standard fonts like arial or arial black the field never save any standard font value unless you reset this section 

PS: if you change the font with one from Google fonts it works normally 

Thanks.

**Comment by kprovance** [comment]
Well, based on this very minimal information, I am unable to reproduce.  Perhaps you could provide us with a support URL?

**Comment by kprovance** [comment]
I think I fixed it in v.3.5.4.29
