### ISSUE TITLE
Custom field extension and included validator?

### ISSUE THREAD

**Issue by IzaacJ** [reduxframework/redux-framework#2448]
Working on a really specific extension, and I would need a validator that always happens on this extension. The validators function will be to reorganize the content in a nice array, and I've found that a validator is the best way. I have however, not been able to find out how to include a validator in a custom field extension.

```php
array(
   array( 'uid' => 'userid', 'key' => 'apikey', 'otherfield' => true, 'someselect' => 'val1,val2,val5'),
   array( 'uid' => 'userid2', 'key' => 'apikey2', 'otherfield' => false, 'someselect' => 'val2,val4,val5')
)
// or
array(
   array( 'userid', apikey', true, 'val1,val2,val5'),
   array( 'userid2', 'apikey2', false, 'val2,val4,val5')
)
```

**Comment by kprovance** [comment]
You're venturing into premium support here.  These kinds of questions require one of us to sit down and examine your code, which we get paid a pretty penny to do by contract.

**Comment by IzaacJ** [comment]
Actually, this would be solved by some example of how to use redux/validate/{opt_name}/class/{field.validate} I think.

**Comment by kprovance** [comment]
Search the wordpress codex on how to use action hooks and filters.  Again, beyond the scope of basic support.

**Comment by IzaacJ** [comment]
I do know very well how to use actions and filter hooks, the thing I do not know is what the {field.validate} refers to. Field name does not seem to be the answer.
