### ISSUE TITLE
Redux Admin notice not dismissing (3.5.4.30)

### ISSUE THREAD

**Issue by Neejoh** [reduxframework/redux-framework#2449]
I've just updated to Redux Framework v3.5.4.30 but keep getting the notification `Redux Framework: Complete Customizer Integration` on every page refresh. When I dismiss the notification it does animate out, but when I reload it comes back.

Like it says in the [changelog](https://github.com/reduxframework/redux-framework/blob/master/CHANGELOG.md#35430) it's "pretty", but far from functional 😜

**Comment by dovy** [comment]
Sorry. I have a fix, just haven't pushed it yet. I will within the next 2 hours.

**Comment by dovy** [comment]
Pushed!  :)

**Comment by Neejoh** [comment]
Didn't fix it for me, after dismissing I keep getting the notification on every screen in Wordpress and not just on the Theme Options page(s). 
![notice](https://cloud.githubusercontent.com/assets/7911547/8517994/4d5cbf70-23c6-11e5-8b91-e46f856e99fd.png)
