### ISSUE TITLE
Undefined index: 'id' when loading barebones-config.php

### ISSUE THREAD

**Issue by ltarasiewicz** [reduxframework/redux-framework#2450]
Hi,

Even after bringing my codebase up to date with the master branch of this repo, I get the following error message when using `barebones-config.php`.

>Undefined index: id in /srv/www/example.com/current/web/app/plugins/redux-
framework/ReduxCore/inc/class.redux_api.phpon line 343

There is no error for `barebones-config-legacy.php`

**Comment by dovy** [comment]
It was mis-coded. Forgot a nested array. Fixed the error AND fixed the config.
