### ISSUE TITLE
CALLING ALL DEVS - Test Theme-Check Now! YEA BABY!

### ISSUE THREAD

**Issue by dovy** [reduxframework/redux-framework#2451]
So I went through the past two days and made Redux 100% Theme-Check complaint with the ThemeForest version, and regular Theme-Check.

In every instance we use a native WP function, instead of direct file writing. We do push the envelope a bit, but we're using all native WP functions.

PLEASE we need help testing.

You'll also note, we added some suggestions for WP.org theme devs inside Theme-Check as well as some basic checks.

Any help you can give to test would be great. I want to do a big release for Redux next week so I can start bringing down the new Customizer class.  ;)

** Update **
The Redux Builder output now reflects the changes to avoid theme-check errors.  ;)

**Comment by dovy** [comment]
@joshmedeski & other Envato Reviewers, we're doing all we can to make Redux comply with ThemeForest requirements. Could you give us any insight on this newest build for things that we would need to change to make it pass the ThemeForest reviews without question? Sometimes people get docked because of Redux, and we want to do away with that. Any suggestions?

**Comment by Stephen-Cronin** [comment]
Hey @dovy, It would be great to make things smoother, so we'll definitely take a look. However, we've got a lot going on right now! We'll have to schedule it in (it'll definitely be at least a couple of weeks)... Sorry about that and thanks for asking!

**Comment by dovy** [comment]
We released it. I guess we'll fix any problems that occur.  :P

**Comment by Stephen-Cronin** [comment]
Oh yeah, wasn't suggesting you wait! 

Anyway, it's in our backlog now to come back and have a closer look at it. *If* there's anything that may be an issue, we'll come back and discuss with you and see if we can work it out together... Hope that makes sense.

**Comment by dovy** [comment]
For sure. Let us know any problems you may find.

**Comment by sodbileg** [comment]
Hi @dovy,
It gave me the error below on 3.5.5. I think this file is important. Should I remove it?

REQUIRED It appears that you have embedded the full Redux package inside your theme. You need only embed the ReduxCore folder. Embedding anything else will get your rejected from theme submission. Suspected Redux package file(s):
Redux Plugin File: /PATH/redux/class.redux-plugin.php

**Comment by dovy** [comment]
That means you included ALL of the Redux plugin in your theme. You need only embed the ReduxCore folder. Many marketplaces will reject you if you embed it all.  ;)
