### ISSUE TITLE
sections via ajax ?

### ISSUE THREAD

**Issue by liquida** [reduxframework/redux-framework#2452]
Hello guys, Im wonder if its possible to add sections to the panel via ajax?

for example

add_action( 'wp_ajax_my_action', 'my_action_callback' );

function my_action_callback() {
	global $redux;

//get the new section in some way

		wp_die();
}

add_action( 'admin_footer', 'my_action_javascript' ); // Write our JS below here

function my_action_javascript() { ?>
	<script type="text/javascript" >
	jQuery(document).ready(function($) {

		var data = {
			'action': 'my_action',
		};

		$.post(ajaxurl, data, function(response) {
			//append new section to redux
		});
	});
	</script> <?php
}

any ideas?

thanks

**Comment by kprovance** [comment]
I guess anything is possible.  However, if you're looking for us to do it for you, that would fall under premium support or a generous donation.

**Comment by dovy** [comment]
Yea. That would take a bit of doing. Best to use required for now. ;)

**Comment by liquida** [comment]
Hello guys

Could you tell me how much it would cost to do the following in premium support?

I have a functions that hooks in to wp_nav_menu

Every menu has its own theme_location, every theme_location has its own section on redux

The hook for wp_nav_menu creates a global var to store the locations used in the current page

I want to load the redux section based on this global var

So, if in the current page preview i have the theme location "Header" the section loaded in the customizer is "Header Settings"

Regards
