### ISSUE TITLE
Using core filters in custom field extension

### ISSUE THREAD

**Issue by IzaacJ** [reduxframework/redux-framework#2453]
Building a custom field extension, and it's almost done, but one of the WordPress core filters does NOT fire when saving.

Adding it in the constructor, but nothing is happening at all.
The filter is pre_update_option_{option_name} and is done like this:
```php
class ReduxFramework_custom_field extends ReduxFramework {
function __construct($field = array(), $value = '', $parent) {
global $opt_name;

// default code in boilerplate

add_filter('pre_update_option_'.$opt_name, array($this, 'prepare_for_save'), 10, 2);
}

public function render() {
//rendering the field
}

public function prepare_for_save($new, $old) {
// my code
return $new;
}
}
```

The code is based on the boilerplate, and I've not been able to find out how to use this core filter inside a Redux Custom Field Extension.
Any ideas?

**Comment by kprovance** [comment]
I hate to sound like a broken record, but these kind of thing falls under premium support, since it has nothing to do with Redux. `pre_update_option_`  is a WORDPRESS function.  it has nothing to do with the Redux core or the boilerplate code.

https://docs.reduxframework.com/core/support-defined/

**Comment by IzaacJ** [comment]
It works outside of the redux framework, but as soon as I put it in my extension, it won't fire.

**Comment by dovy** [comment]
WordPress Core Filters is a rather vague description. Haha. After all, we bypass the core validation for our own...

You will need to elaborate. Though Kevin is right. You're doing very custom work, and we can't provide support for free for things outside of the scope of what we've done. We can point you in the right direction, but this is very much open source.  ;)

**Comment by kprovance** [comment]
I've written handfuls of extensions.  Wordpress action hooks and filters do work.  I've used dozens of them.  But again, this is a premium support issue.  I have to be getting paid to look at code unrelated to Redux itself, because if I do it for one person, I have to do it for everyone, and I don;t have tht kind of time to give away.  Surely you understand that.

**Comment by kprovance** [comment]
Don't put the filter in the field file.  Put in it the extension file.  I recall having that issue once.

**Comment by IzaacJ** [comment]
I'll try that and get back to you.
