### ISSUE TITLE
3.5.5 UPDATE- Update broke my site, getting syntax error

### ISSUE THREAD

**Issue by ksmcmath** [reduxframework/redux-framework#2455]
When I updated your plugin a few hours ago, my site went white screen.  Logged into FTP to shut down plug-ins and discovered yours was the issue.  Deleted and reinstalled your plugin.  After I tried to activate it, I got the following:

Plugin could not be activated because it triggered a fatal error.
Parse error: syntax error, unexpected T_PAAMAYIM_NEKUDOTAYIM in /home/ksmcmath/public_html/wp-content/plugins/redux-framework/ReduxCore/inc/themecheck/class.redux_themecheck.php on line 193

Your plugin is required for my theme to work.  Please resolve so that my site looks as it should.

Thx!

**Comment by bourloud** [comment]
Go to class.redux_themecheck.php file and modify this 2 lines:

193: $redux->$_url instead of $redux::$_url
209: $redux->$_url instead of $redux::$_url

After that, it will be work !?

**Comment by shopi** [comment]
Please advice.

Got fatal error after update the lines... 

Parse error: syntax error, unexpected T_IF in /home/rwayf92/public_html/wp-content/plugins/redux-framework/class.redux-plugin.php on line 327

Please urgent help... my site is broken because of this update of redux.

My website is running on simplemag theme.

**Comment by dovy** [comment]
@shopi The fix is about to be pushed. Basically there are two references to $redux::$_url in that file as @bourloud pointed out. 

I just pushed Redux 3.5.5.1 which resolves all those issues. Manually install it, and you'll be good to go. I just tested locally with PHP 5.2.  :)

Sorry about that!
