### ISSUE TITLE
syntax error

### ISSUE THREAD

**Issue by mmmolst** [reduxframework/redux-framework#2456]
Hi,

My site, www.saveonskincares.com shows a syntax error message while i try to log in to the admin dashboard which i believe is somehow related to your plugin.
 It says "Parse error: syntax error, unexpected T_PAAMAYIM_NEKUDOTAYIM in /home2/mmmolst/public_html/saveonskincares.com/wp-content/plugins/redux-framework/ReduxCore/inc/themecheck/class.redux_themecheck.php on line 193"

Even when I got redux-framework plug in to deactivated, it continues to reactivate...
Would you mind helping me figuring this out?

Thanks so much!

-mon

**Comment by bourloud** [comment]
Go to class.redux_themecheck.php file and modify this 2 lines:

193: $redux->$_url instead of $redux::$_url
209: $redux->$_url instead of $redux::$_url

After that, it will be work !?

**Comment by shopi** [comment]
After i do this i receive another one... please urgent help.
my website wayfarerstyle.com.

I am running a theme called simplemag.

Parse error: syntax error, unexpected T_IF in /home/rwayf92/public_html/wp-content/plugins/redux-framework/class.redux-plugin.php on line 327

**Comment by dovy** [comment]
Just pushed a new version of Redux. 3.5.5.1. This will resolve those PHP 5.2 issues. Just install that version of Redux. Sorry for the issues!
