### ISSUE TITLE
rgba field error - settings have changed message

### ISSUE THREAD

**Issue by Lors** [reduxframework/redux-framework#2457]
http://support.redux.io/?id=XTiPF5bdL9u%2B35wfdj%2FlJe1U%2B%2BctVRdzE%2BWo7N91goj0slOBxmjt6niKX22lbtyaqomgKf5DcAQZhGftZoPLeA%3D%3D

Hi guys,

I'm having a problem ( again ) with the **github and now the plugin version of redux.** When I open the options panel, WITHOUT making any change or modification in any of the fields values, it shows me the following message:

**Settings have changed, you should save them!**

This would be true if I actually enter or change new settings values ( obviously I'm not changing anything as I'm just opening the panel )

And then, when I click the "Save Changes" button, it seems to return to the normal state, but seconds later it shows the message of: Settings have changed...

This wasn't happening with the plugin **until the recent update.**

The javascript console shows the next warning:

```load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,utils,plupload&ver=4.2.2:3 The specified value '!' does not conform to the required format.  The format is '#rrggbb' where rr, gg, bb are two-digit hexadecimal numbers.```

I'm kind of frustrated by this, if you guys know how to solve this, would be awesome.

Thanks :)

**Comment by dovy** [comment]
@Lors There was a mistake, that I just pushed. It's fixed.  ;)

Go ahead and pull from master and all will be good, I think.

**Comment by Lors** [comment]
@dovy Thanks for your help :)

I updated redux:

http://support.redux.io/?id=XTiPF5bdL9u%2B35wfdj%2FlJe1U%2B%2BctVRdzE%2BWo7N91goj0slOBxmjt6niKX22lbtyaqomgKf5DcAQZhGftZoPLeA%3D%3D

And now the js console don't display the message, but it keeps showing the alert:

![Image of Error]
(http://oi60.tinypic.com/zxk60g.jpg)
