### ISSUE TITLE
New Customizer Integration!

### ISSUE THREAD

**Issue by dovy** [reduxframework/redux-framework#2458]
In the master branch you can now test our new customizer integration!

In this version, we have support for the following fields:
* checkbox
* color_rgba
* color
* raw
* media
* spinner
* palette
* button_set
* image_select
* radio
* select
* gallery
* slider
* sortable
* switch
* text
* textarea

We also support fields and all compiler save hooks. What this integration is lacking is the following:
* Validation - Custom validation callbacks
* Required - Custom field value linking
* Live Updates - We do updates on refresh, not live.
* Compiler Hook - Firing on each save no matter what. Gotta fix that!

Other than that, we consider this to be stable for release to WP.org or any space. Give it a try, and let us know what you find!  :)

**Comment by AlexAlexandru** [comment]
Great testing right now

**Comment by renztoygwapo** [comment]
awesome
