### ISSUE TITLE
scss.inc.php error in line 1653

### ISSUE THREAD

**Issue by Lors** [reduxframework/redux-framework#2459]
http://support.redux.io/?id=XTiPF5bdL9u%2B35wfdj%2FlJe1U%2B%2BctVRdzE%2BWo7N91goj0slOBxmjt6niKX22lbtyaqomgKf5DcAQZhGftZoPLeA%3D%3D

Hi,

I'm having problems with the compiler since I recently updated the redux github and plugin.

It throws an error about line **1653** in the **scss.inc.php** file

I have notice that line **1654** is commented:

```php
$code = self::$parent->filesystem->execute( 'get_contents', $path );
//$code = file_get_contents($path);
```

When I uncomment line 1654 and comment line 1653 everything works fine again, like this:

```php
//$code = self::$parent->filesystem->execute( 'get_contents', $path );
$code = file_get_contents($path);
```

I don't know why it throws that error, is there something that we have to change using the redux API?

thanks for your help in advance

**Comment by kprovance** [comment]
That will break theme-check compatibility,  it would be INCREDIBLY helpful if you would tell us the error.

**Comment by Lors** [comment]
The error is this one:

Notice: Trying to get property of non-object in /framework/redux-framework/ReduxCore/inc/scssphp/scss.inc.php on line 1653

Fatal error: Call to a member function execute() on null in /framework/redux-framework/ReduxCore/inc/scssphp/scss.inc.php on line 1653

**Comment by kprovance** [comment]
Okay, I spoke to Dovy.  We're dumping that sass compiler soon since we have no plans to use it in v3.  Best to download and embed your own copy.

**Comment by Lors** [comment]
@dovy @kprovance So in that case, for the new customizer integration features, is there going to be and ajax live preview in case of using redux with sass files?

**Comment by dovy** [comment]
Yes. There will be a preview compiler hook. ;)

**Comment by Lors** [comment]
Awesome :) thanks
