### ISSUE TITLE
Related with Theme Options doesn't show #1432

### ISSUE THREAD

**Issue by henrysw15** [reduxframework/redux-framework#2460]
The problem was that Theme Options doesn`t show, and following solution indicated I modified Config file (ronneby > redux_framework > ReduxCore > Extensions > Config.php) removing the IF statement and just leaving $this->initSettings()
Probably I implemented the solution wrongly and at this moment I can´t open the WP panel neither the public site.
I wrote back same initial theme code in Config file, but still the problem.
Can anybody tell me exactly the code to overwrite this?:

if (  true == Redux_Helpers::isTheme(__FILE__) ) {
            $this->initSettings();
        } else {
            add_action('plugins_loaded', array($this, 'initSettings'), 10);
        }

And any idea about restore the web site?
Thanks in advanced.

**Comment by dovy** [comment]
Umm, we no longer use that method. Try using the new Redux API and this problem won't occur.  ;)

**Comment by henrysw15** [comment]
Thanks dovy, any other indication? How can I get it and how can I implement it? thanks in advanced!

**Comment by dovy** [comment]
Yup!  https://github.com/reduxframework/redux-framework/blob/master/sample/barebones-config.php

**Comment by henrysw15** [comment]
Where should I put that file? I`ve put into redux_framework > ReduxCore > extension (jioned to sample-config.php and config.php) but doesn´t work. Theme Options in Ronneby 1.0.0 still doesn`t show up.

**Comment by henrysw15** [comment]
Thanks for your help dovy!!! It's already working!! Much simple, installing your pluging!!! glups... sorry for your time... :-)

**Comment by dovy** [comment]
No worries!

If you like Redux, or the support we render, please do one or all of the following:
Donate to implement new ideas: http://ideas.reduxframework.com
Review us: http://wordpress.org/support/view/plugin-reviews/redux-framework
Like us: http://facebook.com/ReduxFramework
Follow us: http://twitter.com/ReduxFramework
