### ISSUE TITLE
If Airplane Mode is active, automatically set use_cdn to false

### ISSUE THREAD

**Issue by chriscct7** [reduxframework/redux-framework#2463]
If the plugin Airplane Mode is installed and active, disregard the settings for `use_cdn` and assume false (probably would be a good idea to put a filter around that). 

Airplane mode is a plugin by Norcross that disables calls to external sites, speeding up local development. Aside from being a popular plugin among developers, it also is now in the popular Desktop Server application

github.com/norcross/airplane-mode

**Comment by dovy** [comment]
Care to dive in and see what we need to check for to enable this feature?

**Comment by dovy** [comment]
BTW, you can embed the CDN extension if you choose.

**Comment by kprovance** [comment]
Or just install the vendor plugin?  That's why we (I) made it.

**Comment by chriscct7** [comment]
If I'm distributing it to people, installing the vendor plugin doesn't work.

You just need to do:
```
    $cdn = //whatever value it is;
	// Check if the Airplane Mode plugin is installed
	if ( class_exists( 'Airplane_Mode_Core' ) ) {
		$airplane = Airplane_Mode_Core::getInstance();
		if ( method_exists( $airplane, 'enabled' ) ) {
			if ( $airplane->enabled() ) {
				$cdn = true;
			}
		} else {
			if ( $airplane->check_status() == 'on' ) {
				$cdn = true;
			}
		}
	}
```

You could do that inline or in a Airplane Mode function

**Comment by chriscct7** [comment]
Also, I'd rather use CDN when I can. Its more of fixing an annoyance when developing. The select fields totally break when use_cdn is true and airplane mode is on.

**Comment by dovy** [comment]
I'll implement in my next push and credit you.

**Comment by dovy** [comment]
Integrated with the following code. Basically if enabled, turned off CDN which makes the embedded plugin fire instead of Remote.

```
// Check if the Airplane Mode plugin is installed
                if ( class_exists( 'Airplane_Mode_Core' ) ) {
                    $airplane = Airplane_Mode_Core::getInstance();
                    if ( method_exists( $airplane, 'enabled' ) ) {
                        if ( $airplane->enabled() ) {
                            $this->args['use_cdn'] = false;
                        }
                    } else {
                        if ( $airplane->check_status() == 'on' ) {
                            $this->args['use_cdn'] = false;
                        }
                    }
                }
```
