### ISSUE TITLE
how to embed redux in a plugin?

### ISSUE THREAD

**Issue by AlexAlexandru** [reduxframework/redux-framework#2465]
Just a test case here this goes into index.php 
```php 
<?php
/**
* Plugin Name: Testing arround
* Plugin URI: 
* Description: 
* Version: 1.0.0
* Author: 
* Author URI:
* License: 
*/

if ( ! defined( 'ABSPATH' ) ) exit;//exit if accessed directly

//include all the files that are needed
if ( !class_exists( 'ReduxFramework' ) && file_exists( dirname( __FILE__ ) . '/ReduxFramework/ReduxCore/framework.php' ) ) {
    require_once( dirname( __FILE__ ) . '/ReduxFramework/ReduxCore/framework.php' );
}


if ( !isset( $redux_demo ) && file_exists( dirname( __FILE__ ) . '/ReduxFramework/sample/sample-config.php' ) ) {
    require_once( dirname( __FILE__ ) . '/ReduxFramework/sample/sample-config.php' );
}

global $redux_demo;
print_r($redux_demo);
```

And I have a folder called ReduxFramework with the framework inside.I activate the plugin.I can see the sample options everything works but the print_r($redux_demo) gives null.
If i use print_r($redux_demo); into my theme file is working but not in my plugin.Any ideas?

**Comment by dovy** [comment]
Embed Redux, but don't include or run ANYTHING. Hook everything to run after `plugins_loaded`. Then Include Redux, run your config, and then initialize your config with `Redux::init('OPT_NAME');` and you'll be gravy.  ;)

**Comment by AlexAlexandru** [comment]
Works great plugin :+1:

**Comment by dovy** [comment]
;)
