### ISSUE TITLE
Typography field opens "Settings have changed, you should save them!" notification.

### ISSUE THREAD

**Issue by getbowtied** [reduxframework/redux-framework#2466]
Bug: Just placing a typography type field will open the yellow notice that says: "Settings have changed, you should save them!".

**Comment by getbowtied** [comment]
http://screencast.com/t/AzZOE8GTe7

**Comment by dovy** [comment]
That's because you didn't define the defaults for the different field types and the JS is fixing it for you.

**Comment by getbowtied** [comment]
The defaults are set. Even after saving changes, when you come back on the tab that contains a typography field, the notice will fire.

**Comment by dovy** [comment]
OOoo. Good bug file. @kprovance care to investigate?

**Comment by dovy** [comment]
Fixed and pushed.  ;)

**Comment by getbowtied** [comment]
Thank you!

**Comment by dovy** [comment]
You're welcome!

Donate to the customizer project if you are able: https://ideas.reduxframework.com/campaigns/complete-customizer-integration/
