### ISSUE TITLE
Can't compile the custom theme from Redux Builder

### ISSUE THREAD

**Issue by andryesh** [reduxframework/redux-framework#2467]
Can't compile/download the custom theme from build.reduxframework.com, I have tried around 5-6 times, it freezes and loading continuosly but not download a zip file? I'm doing something wrong? Thank you in advance.

**Comment by dovy** [comment]
Hmm, what's your WP.org username?

**Comment by dovy** [comment]
Redux, I meant Redux. hah.

**Comment by andryesh** [comment]
Hi dovy! Thank you for fast reply, my username is andryesh, the same as on github. Thank you)

**Comment by andryesh** [comment]
http://puu.sh/iUqv7/b4e9cac646.png

**Comment by dovy** [comment]
Can you screenshot your javascript console too?

**Comment by andryesh** [comment]
http://puu.sh/iUqWt/18dab6a0f5.png

**Comment by dovy** [comment]
safebuilting, a chrome extension, is causing the issue.  :)

**Comment by andryesh** [comment]
dovy, I tried the same in firefox, the same result with no action.

**Comment by andryesh** [comment]
http://puu.sh/iUrcD/9992c474d7.png

I only have 1 extension in chrome )

**Comment by dovy** [comment]
Hmm. I'll look again then. I cannot see that. hmm.

**Comment by andryesh** [comment]
Look now, it's not showing the safebulting:

http://puu.sh/iUryN/9fa094011b.png

**Comment by andryesh** [comment]
again appears: http://puu.sh/iUs3s/d984c68a17.png

**Comment by andryesh** [comment]
I do not know what to do in this case, any suggestions how to help me? Thank you in advance.

**Comment by dovy** [comment]
I've duplicated on your account. I'll look into it.

**Comment by andryesh** [comment]
Thank you, waiting for a reply. Maybe I was doing something wrong)
