### ISSUE TITLE
Is the builder working properly?

### ISSUE THREAD

**Issue by ameenC** [reduxframework/redux-framework#2470]
Hello,
I've been trying to use the builder since yesterday but whenever I click "generate admin files", It goes into saving/loading mode but never actually generates the files no matter how long I wait. Anyone experiencing this or just me?
Thanks a lot!

**Comment by dovy** [comment]
We're working on it. Sorry for that.

**Comment by ameenC** [comment]
No problem, thanks for the answer, good luck to you.

**Comment by andryesh** [comment]
I have that issue,too. Dovy already knows about this.

**Comment by tnchuntic** [comment]
I have that issue also, I was thinking it is a browser issue. I have tried all the browser but I couldn't download the start-up theme/the admin folder files for redux.

**Comment by dovy** [comment]
We're on it all. Please be patient.  ;)

**Comment by kprovance** [comment]
We know folks, all the 'me toos' won't make the process go any faster.  We'll post back when the fix is complete.  Tag in with a +1 if need be.  Thanks!  :)

**Comment by abhishek1234321** [comment]
Is this the reason why the builder doesn't display the version no when Stable Release is chosen as the option under Redux version?

**Comment by andryesh** [comment]
Any news regarding the builder?

**Comment by dovy** [comment]
Working on it.

**Comment by dovy** [comment]
The builder is now fixed. Sorry about that.  All is good again.
