### ISSUE TITLE
Add fields to Slides type

### ISSUE THREAD

**Issue by contempoinc** [reduxframework/redux-framework#2472]
How would I go about adding fields to the slides type, without hacking core?

I'd like to add a field for Price and Video Embed

**Comment by kprovance** [comment]
Overload the field with your own:  https://docs.reduxframework.com/core/advanced/add-a-custom-field/

**Comment by dovy** [comment]
Or grab the repeater extension. :)

**Comment by contempoinc** [comment]
Are there demos of each of the extensions? Didn't see it in http://demo.redux.io/wp-admin/admin.php?page=_options&tab=0

**Comment by kprovance** [comment]
It says "Extension Demos" in the admin panel.

**Comment by contempoinc** [comment]
Awesome, thanks!
