### ISSUE TITLE
Fatal error: Allowed memory size of 209715200 bytes exhausted

### ISSUE THREAD

**Issue by contempoinc** [reduxframework/redux-framework#2474]
I'm getting this error on my live server, works fine locally.

Fatal error: Allowed memory size of 209715200 bytes exhausted (tried to allocate 261900 bytes) in /nfs/c01/h16/mnt/1320/domains/wp.contempographicdesign.com/html/wp-real-estate-7/multi-demo/wp-content/themes/realestate-7/admin/ReduxFramework/ReduxCore/inc/class.redux_filesystem.php on line 122

I've increased limits in php.ini to:

memory_limit = 200M
max_execution_time = 600
upload_max_filesize = 20M
post_max_size = 24M

With no luck, any ideas what could be causing this? I would submit a support URL but I can't get into the admin.

**Comment by dovy** [comment]
Ahh yes, my bad. Pushed.

**Comment by contempoinc** [comment]
Just did a pull and uploaded to my server, getting the same error.

http://wp.contempographicdesign.com/wp-real-estate-7/multi-demo/wp-admin

Fatal error: Allowed memory size of 209715200 bytes exhausted (tried to allocate 261900 bytes) in /nfs/c01/h16/mnt/1320/domains/wp.contempographicdesign.com/html/wp-real-estate-7/multi-demo/wp-content/themes/realestate-7/admin/ReduxFramework/ReduxCore/inc/class.redux_filesystem.php on line 123

**Comment by dovy** [comment]
*sigh* Could I get WP and FTP info to your server?

Email: support@redux.io.

**Comment by contempoinc** [comment]
Sent, thanks!



Cheers,

Chris Robinson
www.contempoinc.com
twitter.com/contempoinc

**Comment by dovy** [comment]
Also need WP login to test.  ;)

**Comment by contempoinc** [comment]
Sent two emails one with FTP the other with WP



Cheers,

Chris Robinson
www.contempoinc.com
twitter.com/contempoinc

**Comment by dovy** [comment]
Fixed.
