### ISSUE TITLE
ThemeCheck breaks with v3.5.5.5

### ISSUE THREAD

**Issue by winwinwebdesign** [reduxframework/redux-framework#2475]
I receive this error on the ThemeCheck page after updating to DevBuild v3.5.5.5

*Undefined variable: _url in class.redux_themecheck.php on line 197*

*Fatal error: Cannot access empty property in class.redux_themecheck.php on line 197*

<hr>

I was able to fix by replacing <b>$redux->$_url</b> with <b>$redux::$_url</b>

**Comment by dovy** [comment]
Good call, thanks for that. Pushed.
