### ISSUE TITLE
Color transparent is not refreshing the preview

### ISSUE THREAD

**Issue by AlexAlexandru** [reduxframework/redux-framework#2476]
Going to Color Section(In customizer) -> Color -> Check Transparent is only changing the color to transparent but is not refreshing the live preview at first click after that if you uncheck it it's refreshing the live preview.
Btw
https://github.com/reduxframework/redux-framework/blob/master/ReduxCore/inc/themecheck/class.redux_themecheck.php#L213
redux::$_url ?

**Comment by dovy** [comment]
Good call, fixed the URL. I'll check the color bug.

**Comment by dovy** [comment]
Give that a try. Didn't up the version number (yet). If that works, I'll have to make a few more updates.  ;)

**Comment by AlexAlexandru** [comment]
Working nice job  :+1:

**Comment by dovy** [comment]
K, i'll update the other fields with that as well.  ;)

**Comment by dovy** [comment]
All updated. Good find. Keep testing!  :)
