### ISSUE TITLE
submenu issue in class.redux_filesystem.php file

### ISSUE THREAD

**Issue by m0hamm4dElmi** [reduxframework/redux-framework#2477]
Hi There,
I’m using latest version of Redux which is 3.5.5.6 and also latest version of WordPress which is 4.2.2
Dear friend, I like to use Redux submenu feature as submenu, well I could do it easily but I encounter a small issue. I’m going to explain it as an example:
1. Assume that I want to have a menu named “Redux” in admin panel
add_menu_page( 'Redux', 'Redux', 'manage_options', 'redux' );

2. To show theme options as submenu in Redux menu I did following settings in config file:
'menu_type' => 'submenu',
'page_parent' => 'redux',
'page_slug' => 'themeoptions',

3. Regarding to the code inside of "private function add_submenu" in framework.php below section runs:
elseif ( isset ( $submenu[ $this->args['page_parent'] ] ) ) {
$addMenu = true;
}

And with being true of $addMenu following code runs: 
if ( true == $addMenu ) {
$this->page = add_submenu_page(
$page_parent, $page_title, $menu_title, $page_permissions, $page_slug, array(
&$this,
'generate_panel'
)
);
}

In framework.php everything is fine and runs perfectly but in class.redux_filesystem.php below code shows wrong output:
$base= $page_parent . '?page=' . $this->parent->args['page_slug'];
// out: redux?page=themeoptions
It happens because unlike framework.php, different states for submenu are not considered. Redux is great and can be greater.

**Comment by dovy** [comment]
Interesting find. Care to try and solve the issue?  ;)

**Comment by m0hamm4dElmi** [comment]
Yes, of course. Just need some to time to get home ;)

**Comment by m0hamm4dElmi** [comment]
Yes, of course. Just need some time to get home ;)

**Comment by m0hamm4dElmi** [comment]
Dear Dovy,
There are 3 items that I like share them with you:
1. When I set “var_dump(‘expression’);” in “public function execute” which is located in “class.redux_filesystem.php” it prints twice.
2. Right now I’m involved in an important project and time matters for me; regarding to the issues that I encounter in ‘class.redux_filesystem.php” unfortunately I could not fix it ;)
3. In ReduxCore/inc/welcome/css/redux-welcome.scss line: 438 there some classes that can be deleted. With some search you’ll note my point ;)

**Comment by m0hamm4dElmi** [comment]
Dear dovy,
No news from you for a while. Would you please come back to me as soon as possible?

**Comment by dovy** [comment]
1. That's used for read and write. So not shocked there.
2. Pull from this Repo, we made fixes.
3. Suggest them to us, and we'll make the change.  ;)

Sorry, we're not always compensated for time with Redux. So we don't always respond as quickly as you may need. We respond quicker for those who pay for premium support, but other than that we're "Open Source."   ;)

**Comment by m0hamm4dElmi** [comment]
Sorry for late response. OK, I’ll try to fix it in a proper time and sent it to you ;)

**Comment by kprovance** [comment]
Closing this issue due to age.  if you have a pull request, please submit it for review when it's ready.
