### ISSUE TITLE
it's posible to put !important to the outputed css?

### ISSUE THREAD

**Issue by AlexAlexandru** [reduxframework/redux-framework#2479]
it's posible to put !important to the outputed css?

**Comment by AlexAlexandru** [comment]
I try to use redux/field/{opt_name}/_can_output_css and redux/field/{opt_name}/output_css but I can't see the css value from the user

**Comment by AlexAlexandru** [comment]
I tryied some stuff didn't work

**Comment by AlexAlexandru** [comment]
Finaly I found on workaround but feels hacky... any thoughts on adding this one to redux?

**Comment by kprovance** [comment]
It would take a bit of work, anew argument to each filed that supports it and a rewrite of each output function...and even then it would append output to every selector to that field.  To do individual selectors would be a serious rework, again, of each field that supports it.  You could submit it to ideas.reduxframework.com.  If I could get 500 dollars or more in backing, I'd do it.  :)
