### ISSUE TITLE
T_PAAMAYIM_NEKUDOTAYIM

### ISSUE THREAD

**Issue by brimtick** [reduxframework/redux-framework#2481]
I'm getting the following error. Can anyone help?

Parse error: syntax error, unexpected T_PAAMAYIM_NEKUDOTAYIM in /home/freodoc/public_html/wp-content/plugins/redux-framework/ReduxCore/inc/themecheck/class.redux_themecheck.php on line 193.

Everything was working fine so I'm not sure what has caused this or how to fix it!

**Comment by dovy** [comment]
Pull from this repo. We fixed that.

**Comment by brimtick** [comment]
Sorry but what does that mean? Download and install the latest version?
