### ISSUE TITLE
Required field as checkbox value

### ISSUE THREAD

**Issue by PatelUtkarsh** [reduxframework/redux-framework#2482]
### My switch is required to have checkbox 1 to be checked. But there is no way i can check required checkbox is checked or not. 

```
array(
				'id'       => 'my_checkbox',
				'title'    => __( 'Checkboxs' ),
				'type'     => 'checkbox',
				'options' => array(
					'checkboxa'   => __( 'checkbox 1' ),
					'checkboxb' => __( 'checkbox 2' ), ),
),
array(
				'id'       => 'my_awesome_switch',
				'title'    => __( 'my awesome switch' ),
				'type'     => 'switch',
				'default'  => false,
				'on'       => __( 'On' ),
				'off'       => __( 'Off' ),
				'required' => array('my_checkbox','=','1'); // how do i check if checkbox 1 (checkboxa) is checked or not ?
			)
``` 

Using latest redux.

**Comment by kprovance** [comment]
"Latest redux" means nothing.  Please supply a support URL.  https://docs.reduxframework.com/core/generating-a-support-hash/

**Comment by kprovance** [comment]
Regardless, I believe you have to use the 'contains' evaluator for fields that contains multiple options.  Plus, you have to compare again the actual key.  There is no '1' in your checkbox options field.

```php
'required' => array('my_checkbox','contains','checkboxa');
```

**Comment by PatelUtkarsh** [comment]
Here is [support url](http://support.redux.io/?id=QcDE%2BOVSTGZhMtKsfYTBIIu%2BsCstb4kBCxqDlrBDp5G37kVwIWsOCoOVUgUS%2FvWSqDKYZ00ns1JVB%2FzBv7FUPg%3D%3D)

The solution you provided is not working for checkbox.
