### ISSUE TITLE
Getting an error when trying to access the theme check plugin

### ISSUE THREAD

**Issue by contempoinc** [reduxframework/redux-framework#2484]
Getting this error, running local or live, when trying to use the Theme Check plugin:

Fatal error: Cannot access empty property in C:\wamp\www\wordpress\wp-content\themes\realestate-7\admin\ReduxFramework\ReduxCore\inc\themecheck\class.redux_themecheck.php on line 197

**Comment by dovy** [comment]
Version? Did you update from the repo here?

**Comment by contempoinc** [comment]
Its whatever the latest version is



Cheers,

Chris Robinson
www.contempoinc.com
twitter.com/contempoinc

**Comment by dovy** [comment]
Odd, can't reproduce. Care to ship me your theme to test with? dovy@redux.io.

**Comment by kprovance** [comment]
Or, could you supply an actual version number.  "Latest version" means nothing.  Thanks.

**Comment by contempoinc** [comment]
Dovy sent you an email



Cheers,

Chris Robinson
www.contempoinc.com
twitter.com/contempoinc

**Comment by dovy** [comment]
You need to check the closed issues before you ask about things like this. We fixed this this morning. ;)
