### ISSUE TITLE
Broken Info Link

### ISSUE THREAD

**Issue by winwinwebdesign** [reduxframework/redux-framework#2485]
Under ThemeCheck the link is broken:
<blockquote>RECOMMENDED: If you are submitting to WordPress.org Theme Repository, it is strongly suggested that you read <u>this</u> document, or your theme will be rejected because of Redux.</blockquote>

On line 15 of embedded.php I changed  
`<a href="%1" target="_blank">this document</a>`

to  
`<a href="https://docs.reduxframework.com/core/wordpress-org-submissions/" target="_blank">this document</a>`

There might be a better way to fix, just letting you know. :)

**Comment by dovy** [comment]
Just pushed a fix. Please pull from the repo. Thanks!
