### ISSUE TITLE
2 redux :: plugin overrides theme 

### ISSUE THREAD

**Issue by kiarashi** [reduxframework/redux-framework#2487]
I'm not sure if this is the right place but I'm getting redirected here for support.

I've build a theme options panel with Redux and heavily styled the backend (css)

I'm in the middle of adding theme support for a plugin that also uses Redux.
The problem I'm facing now is that the plugin's redux framework is loaded first
and therefore my css styling and images inside my option panel are all gone (not being loaded).
I found out that it grabs the plugins redux folder by looking at the source code.
If I disable the plugin then everything works just fine.

We both use different opt_name, page_slug, 'page_parent' and if statements.
https://github.com/ReduxFramework/redux-framework/issues/1693

This is on top of my functions.php file

	if ( !class_exists( 'ReduxFramework' ) && file_exists( dirname( __FILE__ ) . '/framework/theme-options/framework.php' ) ) {
		require_once( dirname( __FILE__ ) . '/framework/theme-options/framework.php' );
	}
	if ( !isset( $kiwi_theme_option ) && file_exists( dirname( __FILE__ ) . '/framework/theme-options/kiwi-config.php' ) ) {
		require_once( dirname( __FILE__ ) . '/framework/theme-options/kiwi-config.php' );
	}

My config file (short version)

http://pastie.org/private/theufhyf2qzvpko5f5sq

The plugin uses this

	public function load_settings() {
		if ( !class_exists( 'ReduxFramework' ) && file_exists( dirname( __FILE__ ) . '/classes/redux/ReduxCore/framework.php' ) ) {
			require_once( dirname( __FILE__ ) . '/classes/redux/ReduxCore/framework.php' );
		}
		require_once( dirname( __FILE__ ) . '/classes/admin/class-settings.php' );
	}

Plugin config file (short version)	
	
http://pastie.org/private/mezmvg8qmw0nu4r5nw	
	
	
		
Any idea on how to solve this?

**Comment by dovy** [comment]
It's because you modified files within the ReduxCore folder. Never EVER do this. We have enough hooks and filters to make it possible for you not to.

To add custom CSS to just YOUR instance of Redux, follow our docs here: https://docs.reduxframework.com/core/advanced/custom-panel-css/

Best of luck!

**Comment by kiarashi** [comment]
I'm not modifying the core files. What makes you think I did? ^^

I can't believe I missed the Custom Panel CSS tutorial. ^^;;

Thanks to you I was also able to solve the the url path with images inside redux. 
Before I used: (short version)

	array(	
		'type'      => 'image_select',
		//Must provide key => value(array:title|img) pairs for radio options
		'options'   => array(
			'1' => array('alt' => 'Sidebar right',  'img' => ReduxFramework::$_url . 'images/sidebarone.png'),		
		),
	),


Now I changed ReduxFramework::$_url with get_template_directory_uri().

As always, thank you!!

**Comment by dovy** [comment]
You are so welcome. If you haven't already, please contribute to the customizer project: https://ideas.reduxframework.com/campaigns/complete-customizer-integration/
