### ISSUE TITLE
Border-style: Double is missing from the dropdown menu

### ISSUE THREAD

**Issue by kiarashi** [reduxframework/redux-framework#2488]
Please consider to add the border-style 'double' inside the dropdown menu.

inc -> fields -> border -> field_border.php

on line 167

if ( $this->field['style'] != false ) {
                $options = array(
                    'solid'  => 'Solid',
                    'dashed' => 'Dashed',
                    'dotted' => 'Dotted',
		    'double' => 'Double',  // add this one here
                    'none'   => 'None'
                );

**Comment by kprovance** [comment]
You could perhaps specify the field in question?

**Comment by kprovance** [comment]
Oh, nevermind.  I'll add it to the next release.

**Comment by kiarashi** [comment]
Thanks :)
