### ISSUE TITLE
Legacy Sample Config

### ISSUE THREAD

**Issue by braginteractive** [reduxframework/redux-framework#2490]
Does the sample-config-legacy.php file not work anymore? 

The link to the file goes to a 404 page now: https://docs.reduxframework.com/core/redux-api/

**Comment by kprovance** [comment]
It's been removed.  I'll update the docs.

**Comment by braginteractive** [comment]
@kprovance will the legacy file still work moving forward though?

**Comment by dovy** [comment]
@braginteractive of course! We're just not supporting it any longer since it's more complicated than most devs prefer.  ;)

**Comment by braginteractive** [comment]
@dovy thank you

**Comment by dovy** [comment]
You're welcome. If you are able, donate to the customizer project! https://ideas.reduxframework.com/campaigns/complete-customizer-integration/
