### ISSUE TITLE
Some bugs, please fix asap

### ISSUE THREAD

**Issue by digital-nomad** [reduxframework/redux-framework#2491]
Hi I have 2 screenshots regarding bugs on the site.

1. I cannot get the visual editor to show certain settings: http://screencast.com/t/PUUeYjQ8lH

2. http://screencast.com/t/x5EeICkGg  the social media settings are not saving. please look into this.

**Comment by dovy** [comment]
Umm, we did not develop your theme. You may wan to contact the developer. Seems they have some problems in their code.
