### ISSUE TITLE
Standard Select Field Is Not Pulling the Default Value

### ISSUE THREAD

**Issue by knilob** [reduxframework/redux-framework#2492]
I'm trying to add a basic select menu to my options panel, but none of the default values I set are being pulled through. I'm on Redux Framework v3.5.5.7 and WordPress v4.2.2. I'm pasting my field panel code below:

```php
Redux::setSection( $opt_name, array(
    'title'      => __( 'Social Media Share Buttons', 'my_brand' ),
    'id'         => 'my-social-sharing',
    'subsection' => true,
    'desc'       => __( 'Turn Social Media Share buttons on or off.', 'my_brand' ),
    'fields'     => array(
        array(
            'title'     => __( 'Display Social Media Share Buttons', 'my_brand' ),
            'desc'      => 'Choose whether you want the icons to display below the main content section or in the sidebar.',
            'id'        => 'social-share',
            'type'      => 'select',
            'options'   => array (
                'none' => 'No, Don\'t Display Sharing Buttons',
                'main' => 'Bottom of the Main Column',
                'right' => 'Top of the Right Column'
              ),
            'default'   => 'none',
        )
    )
));
```

I'm expecting the default option of "No, Don't Display Sharing Buttons" to be selected when I view this panel. Instead, I only see the grayed out "Select an item" placeholder as seen in this screenshot:

![image](https://cloud.githubusercontent.com/assets/218796/8706019/f3f80488-2af2-11e5-8898-515e08df3764.png)

I've tested the default value for a multi-select field, and it seems to work as intended.

**Comment by dovy** [comment]
Make sure you reset the section. If something is in the DB (even empty) it will override.  ;)

**Comment by knilob** [comment]
Yep, that worked. My bad for not thinking about doing that.

**Comment by dovy** [comment]
No worries. Glad it's working.

If you are able, please donate to the customizer project. https://ideas.reduxframework.com/campaigns/complete-customizer-integration/
