### ISSUE TITLE
Save Default Values after Theme Activation

### ISSUE THREAD

**Issue by sascha95** [reduxframework/redux-framework#2497]
Is there a way to save the defaults right after Theme activation in the database?

**Comment by AlexAlexandru** [comment]
https://docs.reduxframework.com/core/arguments/#save_defaults

**Comment by sascha95** [comment]
Thanks, but I already know this method.
There, the default values only be saved when you call the Theme Options.
But I want to save the values after Activation of the Theme.

**Comment by dovy** [comment]
Support URL please. ;)

**Comment by s3w47m88** [comment]
I'm also finding that documentation to be fundamentally unhelpful for this purpose.

If @sascha95 is trying to achieve the same thing I am the issue lacking from that documentation is that YES it says how to write the code that sets the value. But it doesn't explain what Filter should be specified to trigger that code to execute and, thus, set the value.

In this case I think we're both trying to ensure that the default values of the Theme are set upon activation.

In my case I'm writing Child Theme of Shoestrap 3 Theme.

As for "Support URL" - forgive me but I'm not clear what you mean by that. Clicking on the Support URL on the website brings me here (to Github).

Thank you for your time!

**Comment by kprovance** [comment]
<blockquote>
But I want to save the values after Activation of the Theme.
</blockquote>
If you're using the Redux API to formulate your options, then it does in fact do this.

<blockquote>
I'm also finding that documentation to be fundamentally unhelpful for this purpose.
<blockquote>
Please, feel free to submit something you feel is superior.  I mean, you get what you pay for, right?

**Comment by kprovance** [comment]
<blockquote>
As for "Support URL" - forgive me but I'm not clear what you mean by that. Clicking on the Support URL on the website brings me here (to Github).
</blockquote>

From our fundamentally unhelpful docs:  https://docs.reduxframework.com/core/generating-a-support-hash/

**Comment by s3w47m88** [comment]
Hi @kpodemski - I think you misunderstood my tone. I was not trying to insult you guys so I'm really sorry if it came off like that.

I was simply trying to articulate that the provided URL doesn't answer the question at hand (from what me or @sascha95 - apparently - could tell).

I understand this is a free product that you guys aren't entitled to provide support for and I greatly appreciate and value this resource. I'm just trying to understand how to use it.

**Comment by Santukon2** [comment]
Hello Team,
   I have a question regarding this argument, and it is the following: Im trying to update a typography field. I imagined I can do it like the following, but I just can update 1 or 2 fields and rest are getting empty: 
Redux::setOption('option_name', 'field_id', 
array(
   'font-family' => $family,
   'font-options' => '', 
   'google' => '1', 
   'font-backup' => $backup, 
   'font-weight' => $weight, 
   'font-style' => $style, 
   'subsets' => $subsets, 
   'text-align' => $align, 
   'text-transform' => $transform, 
   'font-size' => $size, 
   'line-height' => $height, 
   'color' => $color 
)
);
Can someone give me any tip of how to achieve this?

**Comment by kprovance** [comment]
First, please do not piggy back old issues.  Best to create a new one and supply us with the info the New Issues window specifies.

Second, please review:  https://docs.reduxframework.com/core/fields/typography/  You need to set your default array, which will solve your issue.
