### ISSUE TITLE
What WP Action do I use when wrapping my functions in Functions.php so they're executed at the appropriate time (Theme Activation)?

### ISSUE THREAD

**Issue by s3w47m88** [reduxframework/redux-framework#2499]
I'm not sure if I'm doing this right but [according to this post](https://github.com/reduxframework/redux-framework/issues/2497) and the instructions on the Support tab I'm suppose to supply you guys with this support hash to get support for my question(s):

http://support.redux.io/?id=wTkunIH9vx6za%2FIjBjHXxuJsv50j4DqUTiZLWwbbzyC2ahtyiVNE1HTiAmAxz3eap3cLL%2BUPlMWRMl%2FC0KaaKQemPZAPAoqBdWV85FTVWr4Ks%2F%2FRy2wG50ixGHTGoGBs

## Context
I have created a Child Theme of Shoestrap 3, and I'm customizing it and writing necessary code to match a custom design.

In the past, I just use the native Shoestrap Redux Options UI and customize it to my needs and then write any remaining LESS and PHP/HTML to fill in the gaps.

## Obstacle
Now, what I am trying to accomplish, is to programmatically set the values for the EXISTING values that Shoestrap specifies out of the box. And then also add new ones.

I have spent like four hours reading through the docs and I feel like I understand everything - specifically the code required to set the values. *But...* what I have yet to see anywhere in the documentation, and have been unable to find in any of my Google searches, is what that code should be wrapped in so it's executed upon Theme Activation (or whenever the proper time is).

## Examples
Here is an example of what I see in the docs but (obviously) doesn't work when I paste it (and modify it to my needs) in my functions.php as is.
```
global $sampleReduxFramework

$sampleReduxFramework->ReduxFramework->set('my_option', 'its_value');
```

And here is an example of what I *think* I am in need of but doesn't work either (I tried admin_head for the action as well):
```
function custom_values_for_my_theme() {
    global $sampleReduxFramework;
    $sampleReduxFramework->ReduxFramework->set('gradients_toggle', 1);
}
add_action('dont-know-what-goes-here', 'custom_values_for_my_theme');
```

This whole topic may be showing my own ignorance so if it does please be patient with me. Despite having been a programmer for 10 years I don't have a formal education so I've just learned as of gone.

# Thank You
I understand you guys are providing this application and support for free. And I greatly respect and value your time. So if I sound ignorant, stupid or rude please know that's not my intention. I'm just trying to understand an application that seems fantastic and well respected so I can teach my staff how to use it and spread the good word!

Thank you for your time.

## Support Hash
If it's helpful to you guys; I am an experienced programmer but relatively new to Redux and I had *no idea* that I was suppose to generate the support hash until someone told me. If that is a requirement for getting support I imagine it would reduce confusion and your own support overhead if, when a user clicks on Support, they get the same message that appears in Tools > Redux > Support. I hope that information is helpful to you guys.

**Comment by dovy** [comment]
Thank you for your insight. The hook you want to wrap you code in is switch_theme.
https://codex.wordpress.org/Plugin_API/Action_Reference/switch_theme   :)

I appreciate the support URL input. We do have a doc about it: docs.reduxframework.com/core/generating-a-support-hash/    It's just hard to get that word out.

Have a great day.

**Comment by s3w47m88** [comment]
Thank you!

Does this tell Redux that this is the new default as well? Meaning if they click Reset that it will use my specified values?

**Comment by s3w47m88** [comment]
To clarify, by *this* I meant does this code `$sampleReduxFramework->ReduxFramework->set('my_option', 'its_value');` - I know the WP Action does not have anything to do with Redux.

**Comment by dovy** [comment]
It's a hook you can fire to run conversions when themes load. What I would do for Switch Theme is to bypass Redux directly, and access my opt_name via get_option, change the data, then do update_option and I'd be sure at theme switch that my code was working.  ;)

**Comment by dovy** [comment]
Here's an example. Just did it for another dev today.

```
// OLD DATA MIGRATION
    add_action( 'switch_theme', 'evolve_migrate_options' );
    function evolve_migrate_options() {
        $newData = get_option( 'evl_options', array() );
        if ( empty( $newData ) ) {
            $config = get_option( 'evolve' );
            if ( isset( $config['id'] ) ) {
                $oldData = get_option( $config['id'], array() );
                if ( ! empty( $oldData ) ) {
                    foreach ( $oldData as $key => $value ) {
                        $fontKeys  = array(
                            'evl_bootstrap_slide_subtitle_font',
                            'evl_bootstrap_slide_title_font',
                            'evl_carousel_slide_subtitle_font',
                            'evl_carousel_slide_title_font',
                            'evl_content_font',
                            'evl_content_h1_font',
                            'evl_content_h2_font',
                            'evl_content_h3_font',
                            'evl_content_h4_font',
                            'evl_content_h5_font',
                            'evl_content_h6_font',
                            'evl_menu_font',
                            'evl_parallax_slide_subtitle_font',
                            'evl_parallax_slide_title_font',
                            'evl_post_font',
                            'evl_tagline_font',
                            'evl_title_font',
                            'evl_widget_content_font',
                            'evl_widget_title_font',
                        );
                        $mediaKeys = array(
                            'evl_bootstrap_slide1_img',
                            'evl_bootstrap_slide2_img',
                            'evl_bootstrap_slide3_img',
                            'evl_bootstrap_slide4_img',
                            'evl_content_background_image',
                            'evl_favicon',
                            'evl_footer_background_image',
                            'evl_header_logo',
                            'evl_scheme_background',
                            'evl_slide1_img',
                            'evl_slide2_img',
                            'evl_slide3_img',
                            'evl_slide4_img',
                            'evl_slide5_img',
                        );
                        // Typography SHIM
                        if ( in_array( $key, $fontKeys ) ) {
                            if ( isset( $value['size'] ) ) {
                                $value['font-size'] = $value['size'];
                                unset( $value['size'] );
                            }
                            if ( isset( $value['face'] ) ) {
                                $value['font-family'] = $value['face'];
                                unset( $value['face'] );
                            }
                            if ( isset( $value['style'] ) ) {
                                $value['font-style'] = $value['style'];
                                unset( $value['style'] );
                            }
                            $oldData[ $key ] = $value;
                        } else if ( in_array( $key, $mediaKeys ) ) {
                            $oldData[ $key ] = array( 'url' => isset( $value ) ? $value : '' );
                        }
                    }

                    update_option( 'evl_options', $oldData );
                }
            }
        }
    }
```

**Comment by s3w47m88** [comment]
Thank you so much Dovy this appears to be exactly what I was after.

So this line `$newData = get_option( 'evl_options', array() );` and the one beneath it is use to check if any values have been set for Redux - correct?

If so, I'm not clear as to where you're getting that option name from. Are you just checking any option? Because, theoretically, at the time of activation no values would be have been set?

Thanks again!

**Comment by dovy** [comment]
@s3w47m88 I can't sit here giving you a WordPress tutorial my friend, unless you want to donate to a project and grab some premium support:  http://ideas.reduxframework.com   :)

This was a sample where we were migrating a theme from another framework to Redux. I'm checking if there is new data, if not, then I pull the old. Then I'm massaging the old data to match what I need in the new. Then I'm updating the data to ensure I don't get conflicts or any lost information.

That's it.   ;)

**Comment by s3w47m88** [comment]
Sorry @dovy , I understand and I appreciate your time.

I just feel like the docs really don't give a starting place for this and it's really the first step IMO to using Redux. I represent 4 other developers on my staff that have the same questions.

But, again, I completely understand and respect your time and appreciate what you've given. Forgive my ignorance but than you again.

**Comment by s3w47m88** [comment]
Thank you for the link for donations. I went ahead and made a $20 donation.

Of course, I didn't pay that to purchase your time here (I know $20 wouldn't cover that), rather to support the overall development as I'm confident that Redux is a worthy platform.

However, I do hope you'll reconsider adding something on your website that provides a tutorial on first time usage of how to set a value because myself and my staff see a big disconnect and really have no where to turn except to you and your staff from our perspective.

Again, thank you for your free support and application.

**Comment by kprovance** [comment]
<blockquote>
However, I do hope you'll reconsider adding something on your website that provides a tutorial on first time usage of how to set a value because myself and my staff see a big disconnect and really have no where to turn except to you and your staff from our perspective.
</blockquote>
Heh.  Wow.  Okay, Redux is a tool that assume the user is familiar with basic PHP.  We are not PHP tutors or Wordpress tutors.  There are VAST other resources for that.  Personally, I think our docs site is far superior to others out there.  Sorry you find it inadequate.  You are certainly free to write up any tutorial you like and submit it for review.  it is a community project after all (except when it comes to financial support, everything for free and all that).

Cheers.

**Comment by s3w47m88** [comment]
@kprovance I'm not sure why I keep offending you but please know that is not my intention whatsoever.

While I don't have a formal education in programming, and definitely have gaps in my knowledge, over the past ten years I *have*, personally, written close to 100 Themes and been the lead architect on about 12 Plugins.

So if my questions are leaving you with the impression I need a PHP 101 course then my ability to communicate the issue I'm experiencing is inadequate. Of course, I may still be under-educated or just plain ignorant - in which I have to beg for grace.

My notes about the documentation aren't intended to insult you or anyone else. Your docs are beautifully organized and well articulated.

However, until Dovy's reply, neither myself, your other customer in the other thread, nor the four other developers on my staff could locate *any* documentation showing how to trigger the execution of that code.

Sadly, while Dovy's reply does allow me to set the values it's not set as the default value. So that is an incomplete solution with regards to my question at this time.

So I'm not demanding, nor do I expect, you guys do anything. But myself, and others, are collectively stuck on this and cannot locate a solution. It seems you guys hold the key.

If you guys aren't able, or willing, to help me any further I completely understand and just appreciate what you've given so far. But I hope you'll reconsider for the reasons above.

Thank YOU for your time @kprovance - really.
