### ISSUE TITLE
$.cookie not enqueued, console error 

### ISSUE THREAD

**Issue by SanchoPoncho** [reduxframework/redux-framework#2506]
On latest version 3.5.5.1 it looks like jquery.cookie is not enqueued, causing this error and non-functioning Theme Options page.
http://prntscr.com/7vir1m
http://prntscr.com/7vir7e

**Comment by winwinwebdesign** [comment]
Not having this issue in 3.5.5.9

**Comment by kprovance** [comment]
You have dev_mode turned off.  We cannot offer support unless that is activated and a support URL is provided.  You should however, update to the latest version from this repo.
