### ISSUE TITLE
Having sample/patterns in theme folder. Correct path?

### ISSUE THREAD

**Issue by guuthemes** [reduxframework/redux-framework#2507]
Hi guys,

Wanting to place the sample/patterns folder in my theme folder (as I've added a my own selection of different patterns), and so they don't get overwritten when a user decides to update the plugin. I have the folder in the my theme folder currently, but I sure as heck cannot get the path working?!

My config file is in my theme folder - /config/redux/framework.config.php, and my patterns folder is in /config/redux/ alongside my framework-config.php file

I have tried setting constants in functions.php -

`define( 'THEME_DIR', get_template_directory() . '/' );`
`define( 'THEME_URI', get_template_directory_uri() . '/' );`

and then in framework-config.php -

`$sample_patterns_path = 'THEME_DIR' . '../sample/patterns/';`
`$sample_patterns_url = 'THEME_URI' . '../sample/patterns/';`

But no dice. The patterns are nowhere to be seen in the options panel?

thanks

**Comment by kprovance** [comment]
You're using defines incorrectly   http://php.net/manual/en/function.define.php

**Comment by guuthemes** [comment]
Hi Kevin,

Puzzled here my friend? Have defined them in the past like above. And all was good. Unsure how I am using them incorrectly to be honest?

thanks
