### ISSUE TITLE
Undefined index: icon in redux-framework/framework.php on line 3087

### ISSUE THREAD

**Issue by vburlak** [reduxframework/redux-framework#2508]
Hi there

After update to `3.5.5.9` have same php warning: 
`Undefined index: icon in /path-to-my-redux/redux-framework/framework.php on line 3087`

Warning shown for each section's `'icon'`.
Example of my section config code:
```php
Redux::setSection( $opt_name, array(
    'title' => __( 'General', 'orbital_station' ),
    'id'    => 'general',
    'icon'  => 'el el-cogs',
    'fields'=> array(
        array(
            'id'       => 'general_css',
            'type'     => 'ace_editor',
            'title'    => __('CSS Code', 'orbital_station'),
            'mode'     => 'css',
            'theme'    => 'chrome'
        ),
    )
) );
```
Before update to `3.5.5.9` i'm used `3.5.4.3`, and I did not have that warning(with same section config code).

* Redux Version: `3.5.5.9`
* WordPress: `4.2.3-beta1`
* Redux dev_mode: `disabled` (via `'dev_mode' => false` and `'forced_dev_mode_off' => true`)
* Redux `embedded` in Theme
* Browser console: `no errors`
* [My enviroument](http://support.redux.io/?id=x2KbCuGP%2Fj3x9nvyP3M8FSpfjBkaE%2BwJjZsH3bsMy1rhL9z2myPzkCYnXw0tySL%2FlBMp3S2Rbx1tBxYsywQNhg%3D%3D), working on `localhost` via MAMP

Regards

**Comment by kprovance** [comment]
Sorry, but we do not support those using forced dev mode.

**Comment by dovy** [comment]
Turn off forced dev mode and submit a support URL and if the bug persists. ;)

**Comment by vburlak** [comment]
@dovy @kpodemski thx for fast reply.

disabled `forced_dev_mode_off` and enabled `'dev_mode' => TRUE,`

Here is my support URL
http://support.redux.io/?id=x2KbCuGP%2Fj3x9nvyP3M8FSpfjBkaE%2BwJjZsH3bsMy1rhL9z2myPzkCYnXw0tySL%2FlBMp3S2Rbx1tBxYsywQNhg%3D%3D

**Comment by vburlak** [comment]
@dovy @kprovance 
ok, 96e7649616c8edc81f70edd06039a246a8a10a02 helped.
and thx for `3.5.6` dev release. Changelog is awesome.
