### ISSUE TITLE
Wordpress Editor field not accepting text input when placed in accordion extension. 

### ISSUE THREAD

**Issue by mrgurdeep** [reduxframework/redux-framework#2510]
I have applied wordpress editor inside an accordion in the options panel but there seems to be some issue with the editor.While the editor shows up properly, it does not accept ant unput text and is essentially of no use.

I am not sure if I have done something wrong in using the field and hence i am pasting the  code i used below.Any help will be highly appreciated.
```
            array(
                'id'      => 'theme_ftr_desc',
                'type'    => 'editor',
                'title'   => __( 'First Feature Description', 'redux-framework-demo' ),
                'desc' => 'Enter a short description for the First Feature Heading.',
                'compiler' => true,
                'args'    => array(
                    'wpautop'       => false,
                    'media_buttons' => false,
                    'textarea_rows' => 5,
                    'teeny'         => false,
                    'quicktags'     => false,
                )
            ),
```

**Comment by kprovance** [comment]
Extensions issues belong in the extension issue tracker.  This one is for Redux.  Regardless, this is a known issue.  Has to do with javascript.  Truth be told, based on lousy sales and my distinct lack of time, I have no idea when I'll get around to doing anything about it.  If you come up with a fix, let me know, Ill patch it in and give you credit.  :)
