### ISSUE TITLE
small problem redux v3.5.6

### ISSUE THREAD

**Issue by nicolas92** [reduxframework/redux-framework#2512]
Hi, I have updated redux to the 3.5.6 release and I found a little problem with sub sections, there is an error message:

Notice: Undefined index: icon in /redux-core/framework.php on line 3087

Can you fix it?
thank you a lot.

**Comment by knilob** [comment]
This was fixed if you're using the GitHub repo. See commit https://github.com/reduxframework/redux-framework/commit/96e7649616c8edc81f70edd06039a246a8a10a02.

**Comment by nicolas92** [comment]
Hi, thank you very much but I always the error.

**Comment by kprovance** [comment]
Please provide a support URL

**Comment by nicolas92** [comment]
Have you an email because I have to create an admin account.
Thank You.

**Comment by kprovance** [comment]
What?  I mean this:  https://docs.reduxframework.com/core/generating-a-support-hash/

**Comment by nicolas92** [comment]
ah, sorry: http://support.redux.io/?id=vto%2BKT2Ix6vrXFnh1%2B266Fwgw8UntuhJD00uSeI%2FkxwKEzUdVtUd2v308ICIl8fgiEL4uKvqSJwWMvvMXaxmSw%3D%3D

**Comment by kprovance** [comment]
Sorry, but I cannot recreate using the version of Redux from the repo, v.3.5.6.1.  Please make sure that's the EXACT version you are using.

**Comment by nicolas92** [comment]
Yes, I just installed the latest version and I always the error.

**Comment by kprovance** [comment]
Generate a NEW support URL.. Do NOT cut and paste the last one.

**Comment by nicolas92** [comment]
here :)
http://support.redux.io/?id=vto%2BKT2Ix6vrXFnh1%2B266Fwgw8UntuhJD00uSeI%2FkxwKEzUdVtUd2v308ICIl8fgiEL4uKvqSJwWMvvMXaxmSw%3D%3D

**Comment by kprovance** [comment]
It shows you are still running version 3.5.6, and thus the error.

**Comment by nicolas92** [comment]
I download the latest version on github and I installed it.

**Comment by kprovance** [comment]
Then it's not installed properly, or you have the plugin running the older version.  I don't know.  That's up to you to figure out.  Your support URL shows 3.5.6 running, and that is why the error.

**Comment by nicolas92** [comment]
I'll reinstall redux.

**Comment by nicolas92** [comment]
problem solved :)
I do not know why he had trouble install the first time.
Thank You.
