### ISSUE TITLE
why am I getting this?

### ISSUE THREAD

**Issue by dlswings** [reduxframework/redux-framework#2513]
Warning: require_once(D:\Hosting\13861106\html\wp-content\plugins\redux-framework\ReduxCore/inc/welcome/welcome.php) [function.require-once]: failed to open stream: No such file or directory in D:\Hosting\13861106\html\wp-content\plugins\redux-framework\ReduxCore\framework.php on line 67

**Comment by kprovance** [comment]
Someone removed that file and did a bad job of it?  Reinstall Redux toi replace that file, preferaably the version from this repo.
