### ISSUE TITLE
v3.5.6.1 for WordPress Plugin Repo

### ISSUE THREAD

**Issue by webbudesign** [reduxframework/redux-framework#2514]
Hi,

My latest theme using Redux and my customers begin to report #2512 . Are you thinking to release this fix to the WordPress Plugin Repo?

**Comment by kprovance** [comment]
It's up to  @Dovy, but I'm assuinmg yes.  When, couldn't say.

**Comment by kprovance** [comment]
It's been done shortly.  :)
