### ISSUE TITLE
Not saving full settings if have more than 1000 options

### ISSUE THREAD

**Issue by aneesv** [reduxframework/redux-framework#2515]
Our settings page have more than 1000 settings (have many sliders and other widget options) and redux is not saving settings after 1000 as  parse_str used has a limit of 1000 by default 

` PHP Warning:  parse_str(): Input variables exceeded 1000. To increase the limit change max_input_vars in php.ini. in ReduxCore/framework.php on line 2788`

**Comment by monstertheme** [comment]
That's a lot of settings, overdoing it much? :laughing: 

I'm not sure that can be fixed without adding `max_input_vars = 2000` to your php.ini

**Comment by aneesv** [comment]
@monstertheme The problem is most clients has shared hosting and they cant edit ini 

I have managed to solve this by separating fields into multiple panel (Using Different opt_name)

**Comment by kprovance** [comment]
You may have to reconsider the design then.  At present Redux is bound by the max_var_input limit, and over 1000 options will break that.  We've discussed serializing the output to avoid this issue, but it happens so rarely and the work involved would be substantial.  Unless we have serious financial backing from our community, it's probably not going to happen anytime soon.  Sorry to say that, but it's the reality of the situation.  Redux doesn't pull in enough donations.
