### ISSUE TITLE
Override field works only in admin panel problem in customizer

### ISSUE THREAD

**Issue by AlexAlexandru** [reduxframework/redux-framework#2517]
I have override the color field with an extension in wordpress dashboard on my theme page is working great my color field only fires on my selected opt-name but in customizer is overriding all the color fields not just my selected opt-name but also the redux-demo opt name(from the sample config).

**Comment by dovy** [comment]
Well, depends on the argument you used. You should probably make an extension and use a new field name. If it's the same as a core field, of course every option will be overridden.  ;)
