### ISSUE TITLE
Extension customizer _extension_dir

### ISSUE THREAD

**Issue by ninox92** [reduxframework/redux-framework#2519]
Im using the redux wordpress plugin, on a Windows pc. Also i use Roots.io.
When I navigate to the Theme Customizer page an incorrect url is being created for the javascript to enqueue.

The failty url is being created in extension_customizer.php at the if-statement on row 83.

Example of incorrect url : 
http://localhost/WebSpace/web/wp/C:/Users/Username/Documents/GitHub/WebSpace/web/app/plugins/redux-framework/ReduxCore/inc/extensions/customizer/extension_customizer.css?ver=1438018588

My temporary solution:
<addr>
$this->_extension_dir = trailingslashit( str_replace( '\\\', '/', dirname( __FILE__ ) ) );
                    $dir = "/plugins/";
                    $before = strpos($this->_extension_dir, $dir);
                    $end = $before + strlen($dir); 
                    $end = substr($this->_extension_dir, 0, $end);
                    $this->_extension_dir = str_replace( $end, '', $this->_extension_dir );
                    $this->_extension_url = trailingslashit( str_replace( '\\\', '/', plugins_url() ) ) . $this->_extension_dir;
</addr>

**Comment by kprovance** [comment]
Symbolic links are a mess, as there is no way to detect them. There is no one solution that fits all. As you noted there are filters in place to set the Redux core url and dir:

"redux/_url"
"redux/_dir"

Use add_filter in your theme's function.php to set those.  They should be the FIRST lines. Theoretically, that should set the paths to your config.

**Comment by ninox92** [comment]
I'm using the Redux-framework plugin. If im correct then the filters would not apply because the action "redux/init" is called before wordpress "after_theme_setup".
Correct me if im wrong

**Comment by dovy** [comment]
Every instance recalls the framework. Just first declare the filters, then load your config and it will work. ;)

**Comment by ninox92** [comment]
This should work, but the filters are not applied.


    add_filter( "redux/_url", 'bw_redux_url' );
    add_filter( "redux/_dir", 'bw_redux_dir' );
    function bw_redux_url(){
        return plugins_url( "redux-framework/" );
    }
    function bw_redux_dir(){
        return plugins_url( "redux-framework/ReduxCore" );
    }
    require_once(dirname(__FILE__).'/redux/config.php');

**Comment by kprovance** [comment]
plugins_url in your dir function is not returning a dir path, for one, and the url path doesn't include ReduxCore.  So yeah, they're incorrect.
