### ISSUE TITLE
Redux Framework not working on Wordpress 4.2.3

### ISSUE THREAD

**Issue by haiderdev** [reduxframework/redux-framework#2520]
Hi ,

Actually i am using wordpress 4.2.3 and currently i am running the redux framework plugin version 3.5.6.1 but whenever i activate it crashes my wordpress backend. I tried talking to my hosting customer service which is siteground but they have tried quite a bit and it doesnt work. I really need this fixed as soon as possible.

Thanks 

Salman

**Comment by kprovance** [comment]
I need you to be a little more specific than "crashes my wordpress backend".  What is the error?  Are there errors in the PHP log?  We need detailed data, please.

**Comment by kprovance** [comment]
We also need the PHP version you are using, and the Redux version.

**Comment by haiderdev** [comment]
The php version is 5.3.29 and the redux version is 3.5.6.1 . When i activate the plugin it doesnt allow me to log in to my worpdress backend , it doesnt even load the page. Maybe it's not compatible or something but i also talked with my hosting service which is siteground and they said for this you need to contact the plugin developer so i thought to ask you about it.

Thanks

**Comment by kprovance** [comment]
Well, Redux has been thoroughly tested with the latest version of Wordpress, and there are no issues.  We'd have long heard about it by now.  These leaves either a conflict with another plugin, or a server misconfiguration.  Most 'white screen of death' cases usually are.  Have you tried disabling ALL your plugins, and then just try activating Redux.  We need to be 100% certain it's Redux.  it could also be a bad download of Redux (it happened to me once).  So first, delete the version you have and reinstall, preferably from this repo.  Then deactivate all other plugins and activate Redux.

**Comment by haiderdev** [comment]
ok ill try that right now , but siteground said that its redux that is causing the problem

**Comment by kprovance** [comment]
How would they know?  Did they review your error logs to make this determination?  That is information we could use, those logs.  If you could get that information, it would save us a LOT of time.

**Comment by haiderdev** [comment]
they just told me , but let me try and delete all the plugins and re-install them

**Comment by haiderdev** [comment]
if it doesn't work ill ask them for the logs

**Comment by kprovance** [comment]
Well, I could tell you the sky was made of cheese, but that doesn't make it so.  If that support person made that determination, they would have a reason for it, and I'd like to know what that evidence is.  Otherwise, if they pulled some excuse out of the air, in turn making it my problem, then I'm not cool with that.  So, if he has a reason for that claim, I'd like to know what it is.

**Comment by haiderdev** [comment]
ok it's not working so im gonna ask them for the error logs

**Comment by haiderdev** [comment]
I have asked them and the way they can determine that it is that plugin that is casuing the problem is when they deactivate the plugin the backend seems to work properly and when they activate it it doesn't let me log in. I don't know what to do

**Comment by kprovance** [comment]
Still need to see those logs.  Otherwise, WE have to go into your server and start debugging, and that falls under premium support.

**Comment by haiderdev** [comment]
Hi ,

Just wanted to say one thing that i on my own have fixed this problem right now which to me is amazing. Because first of all i am 16 and i do web development as a job in my company called haider development aslo i am not a wordpress expert but it seems that i know quite a bit. Anyways thanks for the help!

Salman Haider / twitter.com/@146salman

**Comment by haiderdev** [comment]
I mean this problem couldn't be solved by one of the best hosting companies for a week and i solved it in one day

**Comment by dovy** [comment]
Tells you how good the hosting companies really are, heh.

What was the issue so others could benefit?
