### ISSUE TITLE
Customizer sections and all everything in redux's config are hidden on preview page loaded.

### ISSUE THREAD

**Issue by ve3** [reduxframework/redux-framework#2521]
http://support.redux.io/?id=uk0W7LvQ%2BwR19KSMM%2BFxpj%2BFDPahZGaGUcmBC0sg2p4CSXFopk4AT5CBt6irGV3TmabEfI18SlonG%2B14%2BFL4eQ%3D%3D

If I activate demo mode on plugins page -> it works.
But if I use my config that copy from sample-config.php and deactivate demo mode -> it's not working.
Everything show up and disappear after theme preview page loaded.

**Comment by kprovance** [comment]
You do understand that not all Redux fields are included in the case customizer offered in the core, correct?  We only included basic fields.  The more advanced ones will be part of the advanced customizer extension.

**Comment by ve3** [comment]
Yep, I do understand. It's my fault. I use is_admin to include redux config.php file because at first I don't know about customizer only for theme.
Remove is_admin condition before include and it's working now.

**Comment by dovy** [comment]
;)   Glad you got it.
