### ISSUE TITLE
Cannot clear removed sections, fields on saved.

### ISSUE THREAD

**Issue by ve3** [reduxframework/redux-framework#2522]
I used to use demo config and saved.
Now, I use only my options and saved.
All previous options on demo are still exists. I don't found this arguments in the document, sorry. 
How to clear those not exists options?

Thank you.

**Comment by dovy** [comment]
Typical WP functions my friend. `delete_option('YOUR_OPT_NAME');`, run once then remove.

**Comment by dovy** [comment]
Or just run Reset All.  ;)

**Comment by ve3** [comment]
Reset button cannot work in customizer.

**Comment by dovy** [comment]
That is true.  ;)

Then the delete_option is your solution!  :)
