### ISSUE TITLE
Fatal at extensions init (when embed only?)

### ISSUE THREAD

**Issue by tivnet** [reduxframework/redux-framework#2524]
Fatal error: Class 'Redux' not found in `...\themes\wpg-qa\admin\redux-extensions\extensions-init.php on line 4`

Builder: admin folder, no TGM, only embedded.

In theme's `functions.php`: `include 'admin/admin-init.php';`, as per builder's instructions.

**Comment by tivnet** [comment]
Also

`Uncaught ReferenceError: redux is not defined
.../themes/wpg-qa/admin/redux-framework/inc/extensions/options_object/options_object/field_options_object.js?ver=4.0 line 6`

**Comment by kprovance** [comment]
Reset the admin-init so extensions are loaded before options (as it should have been).  This should resolve the issue.  :)

**Comment by tivnet** [comment]
@kprovance 

Very likely :)

... but, when admin-init.php comes from the Builder, extensions are **after** the options there.

**Comment by kprovance** [comment]
I'm looking at the live admin-init template on the builder site now.

```php
    // Load the TGM init if it exists
    if ( file_exists( dirname( __FILE__ ) . '/tgm/tgm-init.php' ) ) {
        require_once dirname( __FILE__ ) . '/tgm/tgm-init.php';
    }

    // Load Redux extensions
    if ( file_exists( dirname( __FILE__ ) . '/redux-extensions/extensions-init.php' ) ) {
        require_once dirname( __FILE__ ) . '/redux-extensions/extensions-init.php';
    }

    // Load the theme/plugin options
    if ( file_exists( dirname( __FILE__ ) . '/options-init.php' ) ) {
        require_once dirname( __FILE__ ) . '/options-init.php';
    }
```
If you're getting something else, then, clear cache?  I just purged cache on the builder site, it may take a few minutes.

**Comment by tivnet** [comment]
OK then. The ticket is 8 days' old. You could just write "Fixed" :)

**Comment by kprovance** [comment]
duly noted.
