### ISSUE TITLE
Callback validation error due to recent update? 

### ISSUE THREAD

**Issue by ksmcmath** [reduxframework/redux-framework#2525]
My Admin & site pages are showing the following message:

/** Custom function for the callback validation referenced above * */ if (!function_exists('redux_validate_callback_function')): function redux_validate_callback_function($field, $value, $existing_value) { $error = false; $value = 'just testing'; /* do your validation if(something) { $value = $value; } elseif(something else) { $error = true; $value = $existing_value; $field['msg'] = 'your custom error message'; } */ $return['value'] = $value; if ($error == true) { $return['error'] = $field; } return $return; } endif;

I'm not sure how to resolve this, as I haven't added any custom functions for validation.  Please advise.

**Comment by dovy** [comment]
https://github.com/reduxframework/redux-framework/blob/master/sample/sample-config.php#L2281-L2312

It means, you closed your PHP tag, and didn't open a new one.  :)

Good luck.
