### ISSUE TITLE
Documentation, Build Site Down

### ISSUE THREAD

**Issue by EdwardBeckett** [reduxframework/redux-framework#2527]
The [documentation site](https://docs.reduxframework.com/), is down. you might consider mirroring the site here for good measure

**Comment by dovy** [comment]
Back again.  ;)   Takes about 60 seconds to reboot sometimes.

**Comment by EdwardBeckett** [comment]
Good Man... quick job... `ssh root@ruduxframework.com && shutdown -r now` :+1:

**Comment by dovy** [comment]
We use HHVM and it crashes sometimes.  ;)

**Comment by EdwardBeckett** [comment]
In ten years I've yet to find a VM server that doesn't ;)
