### ISSUE TITLE
Tag request for release 3.5.6.2

### ISSUE THREAD

**Issue by EdwardBeckett** [reduxframework/redux-framework#2528]
All in the title... please tag 3.5.6.2 for checkout. Thanks :)

**Comment by kprovance** [comment]
We're up to 3.5.6.3

**Comment by EdwardBeckett** [comment]
Okay... but there isn't a tag for either... (?)

**Comment by kprovance** [comment]
We don't build releases, only major/minor

**Comment by EdwardBeckett** [comment]
Not a problem... just thought I'd ask...

**Comment by dovy** [comment]
Mainly because we'd be making SO many releases if we do. We tend to release as we're releasing to WP.org, to ensure it's really stable. Until then, trunk is pretty dang stable. If not, we'll fix it.  :P
