### ISSUE TITLE
Field > input text > autocomplete="off" please.

### ISSUE THREAD

**Issue by ve3** [reduxframework/redux-framework#2529]
I don't see any autocomplete off in the document. 
https://docs.reduxframework.com/core/fields/text/

I assume that there is no autocomplete arguments.
Please add autocomplete to turn on or off.
This is a little security improve for users and admin.

Thank you.

**Comment by kprovance** [comment]
I don't have any auto-complete in my text boxes.  Are you sure this isn't a browser feature?  Please provide a support URL, so we can see your browser setup.

**Comment by dovy** [comment]
@kprovance He wants to add a autocomplete="no" to the html of the input box.  ;)

**Comment by ve3** [comment]
Yes, you don't have but in HTML5 input there is autocomplete attribute.
autocomplete="off" to turn off autocomplete.

Please add this into your plugin. :+1:

**Comment by dovy** [comment]
@ve3 Submit a pull release, with this option defined.  :P

**Comment by kprovance** [comment]
No problem, I'll get right on it.  Also, please donate.  Thanks!  :)

**Comment by kprovance** [comment]
Added in v3.5.6.3.  Again, please donate so we know our time was worth the effort.  :)

https://ideas.reduxframework.com/campaigns/donate-to-keep-redux-alive/

**Comment by ve3** [comment]
donated. :)
