### ISSUE TITLE
Exclude system fonts

### ISSUE THREAD

**Issue by promokit** [reduxframework/redux-framework#2530]
Hi Redux.
There are system fonts in request to google font.
http://media.promokit.eu/screenshots/screencloud/screenshot20150803_193422.jpg
Could you please exclude system fonts from that request?

**Comment by kprovance** [comment]
I can't do anything with this limited information.  First, please provide a support URL.  Second, you'll need to provide a list of steps you took within Redux to end up with this particular string in your HTML.  *I* Need to be able to recreate *your* issue here before anything can be 'excluded'.

**Comment by dovy** [comment]
@kprovance They want to remove the standard fonts and only have google fonts.  ;)

**Comment by kprovance** [comment]
Oh.  Okay.  `fonts => array()`

https://docs.reduxframework.com/core/fields/typography/
