### ISSUE TITLE
Cannot redeclare shuffle_assoc() - use function_exists to check if already exists

### ISSUE THREAD

**Issue by Ninos** [reduxframework/redux-framework#2531]
Some plugins (e.g. Awesome Support) are also using a function called shuffle_assoc(). To avoid fatal errors I would use the function `function_exists()`.

https://github.com/reduxframework/redux-framework/blob/master/ReduxCore/inc/welcome/views/extensions.php#L102

**Comment by kprovance** [comment]
function renamed

**Comment by dovy** [comment]
Thanks for that. We always aim to not clash.  :P

**Comment by Ninos** [comment]
Np and thx :D

**Comment by dovy** [comment]
Thank @kprovance not me.  :P

**Comment by Ninos** [comment]
"np" was for you, "thx" for @kprovance XDD
