### ISSUE TITLE
Making Redux work as a theme embed with a Vagrant/VM environment

### ISSUE THREAD

**Issue by willenglishiv** [reduxframework/redux-framework#2533]
this might be a / an RTFQ but I'm having trouble figuring this stuff out.

I am trying to develop a theme using Redux.  I'm using VVV with an auto site install, I have my structure as follows

root
  /src/theme/my-theme - my theme
  /htdocs/ - wordpress install.

Problem is that Redux won't load assets with this config.  The theme is symbolically linked both on the VM and my host machine

I did see this - https://github.com/reduxframework/redux-framework/issues/1566 and this - https://github.com/reduxframework/redux-framework/issues/1709 and I tried to set the wp_content_dir global but it did not fix my problem.

I have fixed this in another install by moving my theme from src/themes/ to the correct htdocs/wp-content/themes directory but I would prefer to not do that.

If I were to use apply_filters, what is the syntax and what would I put in the variable to fix it?

**Comment by kprovance** [comment]
Symbolic links are a mess, as there is no way to detect them.  There is no one solution that fits all.  As you noted there are filters in place to set the Redux core url and dir:

"redux/_url"
"redux/_dir"

Use add_filter in your theme's function.php to set those.  Theoretically, that should set the paths to your config.

**Comment by willenglishiv** [comment]
cool.  I had to make the filter one of the first lines in my functions.php for this to work.  Found Dovy's post somewhere on wordpress.org.  Moving on!
