### ISSUE TITLE
 Customizer Beta Missing Options

### ISSUE THREAD

**Issue by paulasimpson** [reduxframework/redux-framework#2536]
I am about to buy customize license. But I have questions. While going through Customizer Beta I saw few options missing. Like major one is in Media Uploads > SLIDES missing. Which is most required. Also Typography missing. Are you still working on these modules or its removed? Waiting for answer.

**Comment by kprovance** [comment]
The customizer in the core is a 'basic' version.  The advanced version - which is an extension - contains the more advanced fields.  https://ideas.reduxframework.com/campaigns/complete-customizer-integration/
