### ISSUE TITLE
Fatal error: Class 'Redux' not found on new install

### ISSUE THREAD

**Issue by ukscotth** [reduxframework/redux-framework#2537]
Hi,

I've generated a new redux build using the redux builder with the underscores theme option but when I activate the theme it gives the following error. Im using it on a fresh install of Wordpress locally. 

Fatal error: Class 'Redux' not found in C:\wamp\www\luxi\wp-content\themes\luxi\admin\redux-extensions\extensions-init.php on line 4

Any ideas ?

Many thanks,

Scott.

**Comment by kprovance** [comment]
Apparently, someone sent me on a wild goose chase to fix something in our builder that was never broke, which broke it in the process.  I think I fixed it for real this time.  Before redownloading, please be sure you have deleted all previous theme or admin folders, so no old code exists.

**Comment by ukscotth** [comment]
Ok thankyou :)
