### ISSUE TITLE
Setting a Multi Text field with user given information

### ISSUE THREAD

**Issue by wichertandre** [reduxframework/redux-framework#2540]
Hello,

I'm trying to set a new value to a Multi Text field. The user sets an input value and this value should be stored.
I've tried a little bit around with the Redux API as described here: https://docs.reduxframework.com/core/redux-api/ but couldn't even receive the stored value. The API is called but nothing more happens.

This should return a value, but only returns *false*:
```
Redux::getField($opt_name, $id);
```
If I call the global variable, there are several entries for my multi text field set.

Thank you for your support.

Support Hash:
http://support.redux.io/?id=2lgKz0vpGgp9WT1XYBy9KU%2FjRFS0JO3C2TwOQgVj3ypUMH%2FPQ7iOf1Hq2RS6xc3zVh3xRDFUfy0r2JmEGPFeZA%3D%3D

**Comment by kprovance** [comment]
You can;t set an option using get/setField.  Currently, there is no API to do so (although we're going to add it, eventually).  In the interim, you'll have to use get_option or Update option with your opt_name as they key.
