### ISSUE TITLE
Redux FrameWork Very Slow in Theme Glammy - eCommerce WordPress - ThemeForest

### ISSUE THREAD

**Issue by atorresbr** [reduxframework/redux-framework#2541]
Hello, I would like to know, because I'm getting CDN error, and then activate the plugin, WP admin is very slow and can hardly leave the place, I'm using an old aversion plugin to work around the problem.

The image with the error can be viewed at the link below.

https://www.terabyte-rs.com.br/wp-content/uploads/2015/08/REDUX.png

**Comment by kprovance** [comment]
You'll need to contact the theme author.  We do not support themes or plugin that use Redux.  That is the author's responsibility.

**Comment by atorresbr** [comment]
it was proved that the fault was redux, not wordpress tehem

**Comment by kprovance** [comment]
Shipping with an old version, with dev_mode enabled.  Kinda not our fault.

**Comment by atorresbr** [comment]
Gentlemen, the problem disappeared after your software has been updated, solely after your upgrade. As you do not know my wordpress theme could not blame him, because it remained perfect with redux old version, and soon after came a broken redux version, shat all, is fortunately now fixed. :) Thank u

**Comment by kprovance** [comment]
One again, we don't deal with theme users.  We deal directly with the developer.  In the future, you should go to him, and then him to us.  it avoids confusion.  Thanks.
