### ISSUE TITLE
Unable to find slide option

### ISSUE THREAD

**Issue by vjsahu99** [reduxframework/redux-framework#2542]
I have checked and we are unable to find slide option underneath media in customize beta.

http://demo.redux.io/wp-admin/customize.php
 
![slide](https://cloud.githubusercontent.com/assets/13786769/9258772/fe11e2ce-421a-11e5-9348-c53c3a75ac31.png)

**Comment by kprovance** [comment]
Slides is part of the advanced customizer plugin, and is not available in the Redux core.  We couldn't give everything away for free.  :)

**Comment by vjsahu99** [comment]
I am happy to Pledge $200 but after that will I get slide option with customizer and Early Access, & Unlimited License for Use.

**Comment by dovy** [comment]
Yup!  ;)
