### ISSUE TITLE
Security Issue

### ISSUE THREAD

**Issue by BoiteAWeb** [reduxframework/redux-framework#2543]
Hello i'm Julio Potier, a french Web Security Consultant.

I found a kind of "glitch" where a user can update the settings even if he doesn't have the correct rights/role/capa to do it.

This is, of course,a security flaw.

Please, contact me quickly, i don't want to talk in public about this.

See you soon!

_julio @ boiteaweb.fr_

**Comment by dovy** [comment]
Are you sure this flaw is in redux, or the theme/plugin you're using?

You're welcome to contact us at support@reduxframework.com

**Comment by kprovance** [comment]
Recieved your email, sir.  Re-opening the issue for further (but private) discussion.

**Comment by kprovance** [comment]
At least until @Dovy has a chance to go over it with you, since he's the architect behind ajax save.  :)

**Comment by BoiteAWeb** [comment]
Hello @kprovance, thank you! Private of course, until we agree or not on my research.

**Comment by BoiteAWeb** [comment]
_If you just could reply to tell me "received" so i wont open a new thread in your support in guess._

**Comment by kprovance** [comment]
Reply sent.  Still waiting to hear from Dovy.  He'll chime in whenever he returns.  :)

**Comment by kprovance** [comment]
Read your mail @BoiteAWeb, you should have a few by now.  Oui?  ;-)

**Comment by MarceloRecife** [comment]
Hello, love redux!

**Comment by kprovance** [comment]
Suggestions implemented.

**Comment by BoiteAWeb** [comment]
Fix confirmed, thank you Dove and Kevin!
