### ISSUE TITLE
There was a problem with your action. Please try again or reload the page.

### ISSUE THREAD

**Issue by ilyapavlov** [reduxframework/redux-framework#2544]
Getting error message when trying to save options

http://support.zoner.io/?id=%2B%2FiDYCw8IQ%2BmMZLxEDTh%2BXAjTl5dbtyixvpyx9swN%2Bb7JKwuQHoHI%2FU3pkx6o7hvUcgS1ktzZ%2Fze6sHWMDvtzw%3D%3D

**Comment by AlexAlexandru** [comment]
I was developing a plugin and I got this problem to.Check if you have any php outputing like var_dump echo print_r in the wp-admin dashboard and no errors.

**Comment by kprovance** [comment]
What Alex said, basically.  Check the browser output console (CTRL+SHIFT+I).  At the top of the string in the console will be whatever output is causing that message.  You'll then need to comment out whatever echo, print_r, etc is causing it.

**Comment by ilyapavlov** [comment]
@kprovance Problem is not solved. In console I see 

"Failed to load resources: the server responded with a status of http://www.yourwebsite.com/wp-admin/admin-ajax.php 404 (Not found)"

**Comment by kprovance** [comment]
That's not a Redux issue, that's a Wordpress issue.

**Comment by ilyapavlov** [comment]
@kprovance Problem appeared on some servers when our theme with Redux Framework is active. With default themes everything is okay. Can you check log which was generated? Our customers faced with problems and we did not know how to help.

**Comment by kprovance** [comment]
Again, this is not a Redux issue.  We do not do Wordpress support.  If the resource admin-ajax.php cannot be loaded, then guess what?  That's a Wordpress file and a Wordpress issue.  My guess if the file isn't found, it needs to be reinstalled?  Take it up with Wordpress support.
