### ISSUE TITLE
"ace_editor" Type Bug

### ISSUE THREAD

**Issue by ZoOmArts** [reduxframework/redux-framework#2545]
Hello Brothers,

I have an issue with the ace_editor type.
I need to use this code in my custom css editor (ace_editor)
<pre>h1, h2, h3, h4 {
 font-family: 'Trade Gothic Pro Bold', 'Open Sans', Arial, Sans-serif!important;
}</pre>
But when saving the change i get this problem <a href="http://take.ms/UACJ8">Screenshot</a>
Here is my option code
<pre>array(
    'id'            => 'custom-css',
    'type'          => 'ace_editor',
    'mode'          => 'css',
    'theme'         => 'monokai',
    'title'         => __('Custom CSS', ZA_THEME_NAME),
    'validate'      => 'css',
),</pre>

Regards!

**Comment by ZoOmArts** [comment]
http://support.redux.io/?id=D%2FHhw%2FdQoUpFW4zukzlBLwEC73LUkjmctQ4vsEaf1Qb6rUS5sGq5xuUyGdlAab1RLV%2BcmYCFGHKcKcyoUHD4RA%3D%3D

**Comment by dovy** [comment]
Please inspect your Network console and provide the details of that here. It should be in the console.

**Comment by ZoOmArts** [comment]
Which console? Did you mean the Theme Options of my theme?

**Comment by dovy** [comment]
Browser console.  ;)

**Comment by ZoOmArts** [comment]
It happened with me and with my client also!
I think it's from this symbols ( ' and " ) because when i remove 'Trade Gothic Pro Bold', 'Open Sans' it works without any problem.
Here is my console details: Google Chrome: Version 44.0.2403.130 m (64-bit)

**Comment by kprovance** [comment]
Browser console output, please.

**Comment by ZoOmArts** [comment]
Please take a look to this <a href="http://take.ms/UACJ8">Screenshot</a>.

**Comment by kprovance** [comment]
The screenshot doesn't help.  I need to see the console output, as I cannot replicate using the various WP installed themes.  I don't know if it's in Redux, or the config, or some erroneous output.  Better yet, send us your theme, privately of course to support@reduxframework.com.  If I can replicate the issue, I can find the cause.

**Comment by kprovance** [comment]
Ah, I couldn't reproduce because you're using the css validation.  It's outputting an error in our css validator (it should be a message on the page, but it's configured incorrectly).  Looks like the validator is adding escape slashes to the quotes around the font name(s), thus causing an unsafe message.

I can fix both in the next few minutes.

**Comment by kprovance** [comment]
v3.5.6.5 fixes the CSS validation issue.  Please note, if for some reason that data you indicated - the one with the font names - somehow got saved with the escape slashes, you'll need to delete the data in the ACE field and replace it with the proper data.  It will save without the escape slashes now.

**Comment by ZoOmArts** [comment]
Many thanks for you..

**Comment by ZoOmArts** [comment]
Also i have one more question. Where is the custom fonts extension?
https://reduxframework.com/extensions/

**Comment by kprovance** [comment]
Broken, unfortunately.  it got pulled until it could be fixed.  When that will be, well, probably not anytime soon.  The work required is considerable, and sales were lousy, reducing the incentive.  It was a pretty nifty extension, I agree.  I too wish it were working and available.  :)
