### ISSUE TITLE
Cannot translation the plugin admin page using Redux

### ISSUE THREAD

**Issue by ve3** [reduxframework/redux-framework#2549]
http://support.redux.io/?id=uk0W7LvQ%2BwR19KSMM%2BFxpj%2BFDPahZGaGUcmBC0sg2p4CSXFopk4AT5CBt6irGV3TmabEfI18SlonG%2B14%2BFL4eQ%3D%3D

```
$okvyte = new \OKVYTe\Libraries\OKVYTe();
$okvyte->addActionsFilters();
$okvyte->addSettingsPage();
```

```
namespace OKVYTe\Libraries;
class OKVYTe
{
    public function addActionsFilters()
    {
        add_action('init', [&$this, 'pluginInit']);
    }

    public function addSettingsPage()
    {
            require dirname(__DIR__).'/vendor/redux/config.php';
    }

    public function pluginInit() 
    {
       // load language.
       $result = load_plugin_textdomain('okv-yte', false, dirname(plugin_basename(OKV_YTE_FILE)) . '/languages/');
        // $result is Boolean true.
    }
}
```

Translated text works fine in all other part of plugin except setting page using Redux.

How to make setting page using Redux can use other languages?
Please don't just mark resolved without resolve anything.

**Comment by kprovance** [comment]
Redux has it's own languages files.  Unless you want to go through Redux and replace every text domain (which isn't recommended since updates will undo it all).  Not sure what else to tell you.

**Comment by ve3** [comment]
I cannot translate my settings page.

```
Redux::setSection($opt_name, array(
    'icon' => 'el el-youtube',
    'id' => 'okvyte-youtube',
    'title' => __('YouTube API settings', 'okv-yte'),
    'fields' => $fields1
));
```

**Comment by kprovance** [comment]
It's all in the order of when things are loaded.  Did you search our issues tracker?  It's been asked and answered a handful of times.  I think options have to load first before any textdomain calls, I think.

**Comment by ve3** [comment]
Yes, I seach all of that and found nothing really fixed.
Load text domain first or **last** or **after** options did not help anything.

**Comment by kprovance** [comment]
Well, then I don't know.  @Dovy will.  I'll ask him to review this this week.
