### ISSUE TITLE
Using Extensions in embedded version

### ISSUE THREAD

**Issue by thrasherstudios77** [reduxframework/redux-framework#2550]
Wordpress version: 4.2.2
Redux version: 3.5.5
dev mode: true
Type: Embedded in theme NOT the plugin
Environment: localhost

Support URL
http://support.redux.io/?id=YjyEGnI%2BA2QSEat31D7%2FRAT5W%2FeLH8xHzDgVkFczE%2BUhE%2B%2Fbtl%2BYMPHQI8n7rmxJcqdliXip89ygsFes9a2h4A%3D%3D

I used the builder to export the latest stable build v.3.5.5  and included the files into my theme. All my options are showing up and working correctly in the backend and frontend.
https://build.reduxframework.com/wp-admin/admin.php?page=_options

Now am looking how to add these extensions (customizer, import_export, options_object), which do not come with the exported builder zip file, but can be found in the latest GIT download zip file, which is version 3.5.6
 
I took the folders for the extensions, which I grabbed from the GIT download zip directory, version 3.5.6, and copied the folders over to my '/redux-extensions/extensions/' folder. They are now showing up under the 'Status Tab->Redux Instance->Extensions'

However when I navigate to the 'Appearance->Customizer' screen none of my theme options are showing up, only the the 'Site Title & Tagline, 'Navigation', Widgets' and 'Static Front Page' sections. 

I remember when running Wordpress 3.8 and Redux 3.2.9 that on the Customizer screen, certain Redux theme options would show up, those type of options that were recognized by that Wordpress version.

The main reason I upgraded to the newest build is that Dovy mentioned to me before that Wordpress 4.0 and up with the newest build of Redux will allow for all Redux theme options to show up on the Customizer Page. 

Maybe I misunderstood, but my hope was that the users of my theme could make their changes on the fly using Ajax on the frontend Customizer. If this is true what am I missing or not including in my Redux framework. Is this now a paid extension?

thanks for your time.

**Comment by kprovance** [comment]
I'm not sure what you're talking about, really.  I just tested the builder, creating an install with the dev branch.  The core extensions are in there:  `\admin-folder\admin\redux-framework\inc\extensions`.  When you begin moving stuff around and replacing/renaming things, stuff breaks.

**Comment by thrasherstudios77** [comment]
You were right, those extensions do come with the download, I got confused seeing the 'redux-extensions' folder on the root, thought they should be added there. I removed the extension folders that I added.

I still have the issue with the Customizer not showing my theme options, should it be showing them?

**Comment by kprovance** [comment]
Depends on the options.  The basic customizer in the Redux core does not support all fields, just basic ones.  That's what the advanced customizer extension is for:  https://ideas.reduxframework.com/campaigns/complete-customizer-integration/

**Comment by kprovance** [comment]
Closing, since original issue was resolved.

**Comment by thrasherstudios77** [comment]
Will this plugin be able to be used on Premium themes on Themeforest, is there a developer license?

**Comment by dovy** [comment]
Redux is free to use anywhere, GPL. If you make money, please support the effort so we can keep doing awesome things.  :)

**Comment by thrasherstudios77** [comment]
Thanks Dovy I really appreciate your guys hard work, but please stop asking for money every time I post here. we do plan on supporting you guys once our theme is released :)

My question wasn't about the Redux Framework I was asking about the upcoming 'Advanced Custimoizer Extension'. Will Premium theme authors on Themeforest be able to get a 'Developer License'  so we can include the extension with our Themes?

**Comment by dovy** [comment]
Every extension will be available for premium themes to use. Yes, it is coming shortly.  :)

**Comment by thrasherstudios77** [comment]
So it should cost $99 for 1 year license to use the 'Advanced Customizer Extension' on our themes? If we pay $200 is this a lifetime license?

**Comment by dovy** [comment]
The $200 was a lifetime subscription. Use it anywhere. With that window closed now, it may be different. Still debating about it.

**Comment by thrasherstudios77** [comment]
OK thanks for the info, will the $99 per 1 year license always be in effect?

**Comment by dovy** [comment]
yup

**Comment by kprovance** [comment]
<blockquote>
but please stop asking for money every time I post here. we do plan on supporting you guys once our theme is released :)
</blockquote>
If we had a dollar for everything we heard that, we wouldn't need to ask for donations.  ;-)

**Comment by thrasherstudios77** [comment]
I get that, what you guys have accomplished is so helpful to the community and is very much appreciated. I can only speak for our company, that we plan on supporting you once this theme is released, not only with a license but for further development on future projects.

thanks again Kevin for answering all my questions the last few days.
