### ISSUE TITLE
Set defaults for Sortable Field in 'text' mode

### ISSUE THREAD

**Issue by thrasherstudios77** [reduxframework/redux-framework#2551]
Wordpress version: 4.2.2
Redux version: 3.5.5
dev mode: true
Type: Embedded in theme NOT the plugin
Environment: localhost

Support URL
http://support.redux.io/?id=YjyEGnI%2BA2QSEat31D7%2FRAT5W%2FeLH8xHzDgVkFczE%2BUhE%2B%2Fbtl%2BYMPHQI8n7rmxJcqdliXip89ygsFes9a2h4A%3D%3D

Is there a way to give the Sortable Field in 'text' mode default values, like you can when using the 'checkbox' mode.

I can see that the fields have the defaults as recommendations faded out in grey, but they need to be initially filled in, then have the ability to leave them blank so as to remove the sorting option from the frontend. 

I could add information to the 'subtitle' and 'desc' to make it more clear that these have to have values for my widget on the frontend to work correctly, but I can see this being confusion and error prone to my users. I would rather the fields be initially filled in if possible.

thanks

**Comment by kprovance** [comment]
Allow me to introduce you to our docs site:  https://docs.reduxframework.com/core/fields/sortable/  WYSIWG.  :)
