### ISSUE TITLE
Palette Color Option

### ISSUE THREAD

**Issue by regan008** [reduxframework/redux-framework#2554]
Hello,

I'm currently building an options panel using redux and I came across the "Palette Color" option in your demo but I do not see any documentation for it. Is this still an active option and if so could you point me to the documentation? [This is the link](http://docs.reduxframework.com/core/fields/palette-color/) provided in `sample/sample-config.php` but it returns a 404 error. 

If you could point me in the right direction that would be greatly appreciated. Thanks!

**Comment by dovy** [comment]
@kprovance we never made a doc page! Doh. 

We'll get on it.

**Comment by regan008** [comment]
@dovy Awesome thanks so much!

**Comment by dovy** [comment]
In the meantime our sample config has an example. ;)

**Comment by kprovance** [comment]
Done.

**Comment by niklasp** [comment]
is it really useful for anything. Like the output does not work with it right?

**Comment by kprovance** [comment]
It acts as a selector whose name you would reference in css to display
those colours.
