### ISSUE TITLE
Media uploader not working

### ISSUE THREAD

**Issue by webipgroup** [reduxframework/redux-framework#2555]
Hi all, 
I got a problem trying to set a tab with a media uploader in my Theme Options. If I insert the proper code in barebons-config.php file, in my Theme Options nothing is shown but the link to Redux Framework documentation. Here's the code

    Redux::setSection( $opt_name, array(
        'title'      => __( 'Home Page Images', 'redux-framework-demo' ),
        'desc'       => __( 'For full documentation on this field, visit: ', 'redux-framework-demo' ) .     '//docs.reduxframework.com/core/fields/text/',
        'id'         => 'opt-media-subsection',
        'subsection' => true,
        'fields' => array(
    'id'       => 'opt-imgs',
    'type'     => 'media',
    'url'      => true,
    'title'    => __('Media w/ URL', 'redux-framework-demo'),
    'desc'     => __('Basic media uploader with disabled URL input field.', 'redux-framework-demo'),
    'subtitle' => __('Upload any media using the WordPress native uploader', 'redux-framework-demo'),
    'width'    => '250',
    'height'   => '600',
    'mode'     => false,
    'default'  => array(
        'url'=>'http://s.wordpress.org/style/images/codeispoetry.png'
            ),
        )
    ) );

What I get is a blank tab: 

![Image of blanktab]
(https://lh5.googleusercontent.com/TufMfBwZYgTKRVo_u9dhaHT-oIp34XfF2qkIDO_30pyUoPtHigbQu7pKlUN8Q3er_SRuPG38wMmCqGU=w1256-h546-rw)

How can I fix it? Thanks!

**Comment by kprovance** [comment]
It's not proper code.  Your fields argument is incorrect.  The fields argument takes an array of arrays.  Put your media field inside an array.

**Comment by webipgroup** [comment]
Sorry, I didn't understand: where am I supposed to put the field?

**Comment by kprovance** [comment]
Look at the examples in the sample-config to see how it's done.  We're talking basic PHP arrays here.  Usage of Redux assumes a basic knowledge of PHP.  We're not PHP tutors.

**Comment by webipgroup** [comment]
Chill man! To ask is legit, to answer is courtesy. I made a simple question, I didn't ask you to explain me the whole PHP.
