### ISSUE TITLE
Add second tier to customizer but not theme options panel

### ISSUE THREAD

**Issue by ThinkUpThemes** [reduxframework/redux-framework#2556]
Hi guys,

Is it possible to use the Redux::setSection feature so add a section to the customizer but not the theme options panel?

I'm wanting to have the options organized in Cutomizer within an overarching Theme Options tab. However, within the theme options panel I'd want the individual sections to show as tabs in their own right.

Hope that makes sense! I assume I'll need to do some template overriding. :-)

**Comment by dovy** [comment]
Set the customizer_only arg to the section or per field. ;)

**Comment by ThinkUpThemes** [comment]
Thanks for the info. So if I wanted to include the same option in both the customizer and theme options panel, would I need to have the sections code twice? One for customizer only, and structure the hierarchy as I want. Then another for the theme options panel?

**Comment by dovy** [comment]
Nope, just once.

So, for Anything you want to enable the customizer for, you set the global arg of `'customizer' => true`. If you have the global arg of above set, then you can limit individual fields/sections this way:
`'customizer' => false` means it won't show in the customizer. `'customizer_only' => true` means it only shows in the customizer.

Declare it only once.  ;)

**Comment by ThinkUpThemes** [comment]
ok, I think maybe the question in the heading is not quite accurate in that case. I want the option to show in both the theme options panel and customizer as mentioned above. The only difference is that I don't want the section to show as a sub-section in the theme options panel. However I do want the section to show as a sub-section in customizer.

Is there any way to achieve this? I'm not referring to showing / hiding individual settings. It's more about sub-sections. Hope that helps clarify what I mean. :-)

**Comment by dovy** [comment]
In the customizer it will appear as a panel, and a section within the panel. If you DON'T want that, then you'll have to (in your config file) check the global $pagenow variable, and check for customizer.php.  ;)

**Comment by dovy** [comment]
And change your subsection argument to be false.  ;)

**Comment by ThinkUpThemes** [comment]
Thanks so much, that sounds like what I'm after. I'll give this a go and see how I get on. Thanks!
