### ISSUE TITLE
Enqeue custom scripts using extension

### ISSUE THREAD

**Issue by ThinkUpThemes** [reduxframework/redux-framework#2557]
Hello,

Is there a tutorial or an example which shows how to go about using creating an extension that's used to enqeue scripts for the customizer or theme options page? I'm wanting to move the css customizations out of my theme stylesheet into an extension folder for redux.

Thanks again!

**Comment by dovy** [comment]
Use the extensions boilerplate, available in this organization on GitHub. It's all there. ;)

**Comment by dovy** [comment]
https://github.com/reduxframework/extension-boilerplate   ;)
