### ISSUE TITLE
Missing subtitle sections even with code present?

### ISSUE THREAD

**Issue by celestja** [reduxframework/redux-framework#2559]
Where is the subtitle field section?
It appears in the code but when I check the redux documentation, even the diagram example used under 'slides' (https://docs.reduxframework.com/core/fields/slides/) 
doesn't have it showing. 
![nosubtitlefield](https://cloud.githubusercontent.com/assets/13933709/9429989/da5b272a-49e3-11e5-8c75-e37f7c3d1ad5.png)

**Comment by kprovance** [comment]
Not sure what you mean.  This is from the sample config:
```php
    Redux::setSection( $opt_name, array(
        'title'      => __( 'Slides', 'redux-framework-demo' ),
        'id'         => 'additional-slides',
        'desc'       => __( 'For full documentation on this field, visit: ', 'redux-framework-demo' ) . '<a href="//docs.reduxframework.com/core/fields/slides/" target="_blank">docs.reduxframework.com/core/fields/slides/</a>',
        'subsection' => true,
        'fields'     => array(
            array(
                'id'          => 'opt-slides',
                'type'        => 'slides',
                'title'       => __( 'Slides Options', 'redux-framework-demo' ),
                'subtitle'    => __( 'Unlimited slides with drag and drop sortings.', 'redux-framework-demo' ),
                'desc'        => __( 'This field will store all slides values into a multidimensional array to use into a foreach loop.', 'redux-framework-demo' ),
                'placeholder' => array(
                    'title'       => __( 'This is a title', 'redux-framework-demo' ),
                    'description' => __( 'Description Here', 'redux-framework-demo' ),
                    'url'         => __( 'Give us a link!', 'redux-framework-demo' ),
                ),
            ),
        )
    ) );
```
Which produces this:
![slides](https://cloud.githubusercontent.com/assets/3412363/9430030/83850720-49b3-11e5-99d7-079aef9bb5e4.png)

The subtitle is directly under the title, where it should be.

Now, unfortunately, I noticed you made some custom modifications to the field itself.  Once you start making mods like that, you're kinda on your own.  We don't support such things.

**Comment by celestja** [comment]
Yes, in the sample configuration it has a subtitle field but if you see the example you posted, it's just got the title and description and link section- but no subtitle field 

"'subtitle'    => __( 'Unlimited slides with drag and drop sortings.', 'redux-framework-demo' )," 
this part. My question is, where is it?

**Comment by kprovance** [comment]
![image2](https://cloud.githubusercontent.com/assets/3412363/9430046/51c512ba-49b4-11e5-8939-d543beb54042.png)

**Comment by celestja** [comment]
Ah! so there is no way to add a subtitle to the field options using the redux framework without manually customising the code?

**Comment by kprovance** [comment]
As I said, you've modified the core.  I have NO idea what you've done, and thus, it's either a premium support issue, or nothing.  Sorry, that's always been our policy.

**Comment by celestja** [comment]
Well, is redux framework  designed to add field options to the redux framework through the plugin offered by default- or if it's something that has to be coded in manually. Without considering the modified version, I just want to know what the default demo is capable of (whether im just not looking carefully enough or if its indeed something that can't be done without modifying the core)
