### ISSUE TITLE
Can one field hold many values?

### ISSUE THREAD

**Issue by safiro** [reduxframework/redux-framework#2560]
1- Can one field hold many values?
I've a select field  with id 'style_picker'  it contains style one,  style two,  style three and I want them to get their information from one field say color field with id 'choose_color'  , so I choose style one and assign a green, style two assigned to red,  style three assigned to pink. many selections using one color field, and when I switched to style two the color field shows  red, when I switched to style three the color field shows  pink, etc.... 

2- Is it possible to create fields from options panel?
Based on number one, is it possible to make a text field with id 'style_name' and color field with id 'style_color_value' , and in text field I write style four and in color field I choose blue, and these style added to styles in the select field to be style one,  style two,  style three, style four

**Comment by kprovance** [comment]
These things cannot be inherently, no.  We do have a premium extension library, specifically the repeater field:  https://reduxframework.com/extensions/
