### ISSUE TITLE
Show entire section in customizer

### ISSUE THREAD

**Issue by ThinkUpThemes** [reduxframework/redux-framework#2561]
Hello,

I've set the overall setting to disable settings from showing in the customizer by settings the following in the "SET ARGUMENTS" section:

<pre>'customizer' => false</pre>

However, I want to enable only certain sections from showing. I've added the following to Redux::setSection:

<pre>'customizer' => true,</pre>

This doesn't work. The only way to make it work is to add the above to each individual option. Is there any way to show whole sections in the customizer without adding the above to each option in that section?

Thanks!

**Comment by AlexAlexandru** [comment]
Hello try customizer_only => true/false

**Comment by kprovance** [comment]
Isn't it `customizer_only` for sections?

**Comment by dovy** [comment]
Implemented in 3.5.7.  :)

**Comment by ThinkUpThemes** [comment]
Awesome! Thanks Dovy. I'll be upgrading to 3.5.7 now. :-)
