### ISSUE TITLE
theme colors

### ISSUE THREAD

**Issue by visualrefinery** [reduxframework/redux-framework#2563]
Hi,

We just bought "the shop" theme from themeforest, installed it and are in the process of trying to get it dialed in.  Can you please tell me why the theme colors in the admin don't update all of the colors?

I was of the understanding that changing the colors would be very easy, am I missing an update or something?

Please let me know.  Thanks!

- Ryan

theShop - Retina Responsive WordPress Shop Theme 1.0.0

**Comment by kprovance** [comment]
We are not the theme's author.  You need to contact them directly for support.
