### ISSUE TITLE
Cannot Save New Page & Save Changes On Existing Page

### ISSUE THREAD

**Issue by toopai** [reduxframework/redux-framework#2564]
I currently face problem to save new page and to save to make changes on existing page.

When I click on Update button, the page does not saved and the Update icon keep moving.

Theme used: Hermes Press

Please help.

**Comment by kprovance** [comment]
Please contact the author of your theme.  We do not support themes that use our product.  That is the responsibility of the theme author.

**Comment by toopai** [comment]
okay thank you for your advice.
