### ISSUE TITLE
Customizer in WordPress 4.3 showing Redux Sections

### ISSUE THREAD

**Issue by PulsarMedia** [reduxframework/redux-framework#2565]
Hey Guys,

After upgrading to WordPress 4.3 the theme customizer now displays all the sections in my Redux framework even though i have the customizer value set to false in my config file. Furthermore the sections are appearing blank in the theme customizer.

Is there a way i can permanently disable Redux sections from appearning in the theme customizer as of WordPress 4.3? If not then how do i get the options to appear instead of blank sections?

Here is my info in case you need it:

WordPress version: 4.3
Redux version: v3.5.6.8
Windows 8.1 machine
Localhost environment running on XAMPP
FireFox 40.0.2 browser

A quick answer would be appreciated as i have customers complaining about this.

Thanks.

**Comment by kprovance** [comment]
Quick may be an issue.  Due to lack of support from our community, Dovy had to take a full time job, and I'm busy with mine. Could be a week or two.  Sorry.

**Comment by PulsarMedia** [comment]
Im willing to make a considerable donation if you can get on this issue within the next few days.

Let me know, thanks.

**Comment by kprovance** [comment]
It's up to @Dovy.  I don;t know thing one about the customizer.  I despise it.  :)

**Comment by PulsarMedia** [comment]
Ok, i really need this fixed asap so whoever is fixing it let me know what you want for your time and i will forward a payment.

Thanks, appreciate it.

**Comment by kprovance** [comment]
Can you post a support URL?

**Comment by PulsarMedia** [comment]
A support URL for my WordPress theme?

You can see my theme here: http://wp.pulsarmedia.ca/aayat/

But the issue is in the customizer area so you will have to login to see the issue. Should i email you the credentials? if so please provide me with the email address.

Thanks.

**Comment by kprovance** [comment]
No.  This:  https://docs.reduxframework.com/core/generating-a-support-hash/

**Comment by PulsarMedia** [comment]
oh right, i forgot about that.

Here is the Support URL:

http://support.redux.io/?id=xLGBy7%2BXIzSyHrlw5T9YhbPxpjvUIZt%2FsQ4k5%2FzJPezxAjvmNPBPto4%2FaG%2Fi%2Fl4bv6QtZT0xgryJ2pP%2BlLefBA%3D%3D

Do you require anything else?

**Comment by kprovance** [comment]
I was hoping to replicate based on the support data.  I cannot.  All fields are hidden.  You're going to have to send me your theme privately.  I have to be able to recreate this first.  info@reduxframework.com

**Comment by PulsarMedia** [comment]
Hi Kevin,

I just emailed you a set of credentials for my theme along with an explanation on how to recreate the issue.

If you need anything else please let me know.

Thanks.

**Comment by dovy** [comment]
Resolved in 3.5.7 just released.

**Comment by PulsarMedia** [comment]
Awesome guys, thanks for fixing the issue so quickly.

Whats your donation link again? I will forward through a donation asap as a token of my appreciation.

Cheers!

**Comment by dovy** [comment]
https://ideas.reduxframework.com/campaigns/donate-to-keep-redux-alive/ if you want to have it public. Paypal: billing@reduxframework.com if you want it private.

Thanks!  :)

**Comment by PulsarMedia** [comment]
Thanks Dovy, i just put through a donation.

And thanks again for the quick turn around time.

Cheers!

**Comment by dovy** [comment]
When you support us, we can support you. After all, we all have day jobs.  :P

**Comment by PulsarMedia** [comment]
Yea absolutely...you cant expect everything for free in life.

Thanks again for the update :]

Cheers!
