### ISSUE TITLE
How to enable Redux in admin area???

### ISSUE THREAD

**Issue by safiro** [reduxframework/redux-framework#2566]
global $redux;
$redux_opt = $redux['options_pick'];
echo $redux_opt ;

The previous code is working in theme files.
How to make it works in admin pages too?
I'm using another framework to do some stuff on admin style and I want to do this:

if ($redux_opt){
do the code
}

**Comment by dovy** [comment]
Ahh. Use the redux API init() function as outlined in the docs.

**Comment by safiro** [comment]
Can you please explain how to use it?
Thanks.

**Comment by dovy** [comment]
https://github.com/reduxframework/redux-framework/issues/2362#issuecomment-119600184

**Comment by safiro** [comment]
I completely lost,
Can you please explain how to do it step by step?
what code should I add in files?
Thanks.

**Comment by dovy** [comment]
Bottom of your config file my friend. The issue is Redux doesn't load until after your theme is loaded. If you need to use the global variable earlier then:
1. Do your own `get_option('OPT_NAME')`
OR
2. Use: `Redux::init('OPT_NAME');` to tell redux to load immediately.

**Comment by safiro** [comment]
Thanks it is working. but I'm getting this error when clicking any save changes button.
"There was a problem with your action. Please try again or reload the page."
when I disable Redux::init('OPT_NAME'); the error is gone !!!

**Comment by kprovance** [comment]
You did remember to remplace OPT_NAME with your projects opt_name, correct?  Because if you didn't, that's why.

**Comment by safiro** [comment]
Of course I replaced it.

**Comment by safiro** [comment]
I reactivated the theme and reset the section. and it is working fine now.
Thanks for your Help.
