### ISSUE TITLE
Sorter Creating Another Disabled Column

### ISSUE THREAD

**Issue by coleh33** [reduxframework/redux-framework#2569]
I am having an issue with using the sorter field.  It appears that if I add another item to the options-config file to the sorter disabled section and go to the options page, a 3rd column appears marked "Disabled" to the right of the "enabled" and "disabled" columns.  

This makes me have to reset the entire section for it to disappear. Not sure why that is happening, but I believe it shouldn't be doing that when adding another sorter option to disabled in the config file.

http://support.redux.io/?id=tnNrJZZhDka3m2%2BvIrsCO9CC5nPT3PZ6bl5gQN6RGJ6czVM9UrExvub%2B4pyarrCe8f3gXPd%2FWC2o13%2FqSR39zg%3D%3D

**Comment by kprovance** [comment]
Cannot replicate.  This is what I get.
![sorter](https://cloud.githubusercontent.com/assets/3412363/9559469/fe7967b6-4dc1-11e5-995d-2766a7f626db.png)
I moved the blocks around, saved, reloaded.  Nothing.  Try a section reset.

**Comment by coleh33** [comment]
But if you add another option to the config file under disabled it will create a third column called "Disabled" that would make it have to be reset every time a new item is added over time.

**Comment by kprovance** [comment]
I worked on the data provided in the support url.  If you are working with something different, that information should be been provided.

**Comment by coleh33** [comment]
That is the same data I was working with.  When I go to the options-config.php file and add another sorter option under disabled this is what happens.
![screen shot 2015-08-29 at 10 54 04 am](https://cloud.githubusercontent.com/assets/11298821/9563564/8d176174-4e3c-11e5-827c-1bd1c3e4a6be.png)

**Comment by kprovance** [comment]
I guess I'm not making myself clear.  YOU have to give me the data you are trying.  Telling me 'you added something' isn't sufficient.  I don't have time to sit here and guess at what you did.  So, please, either provide the data you are using, or close the ticket.  Thanks.

**Comment by coleh33** [comment]
I'm simply adding another option under disabled.  Over time as we want to add more options to the sorter, right now if we put the new option under disabled in the config.php file it creates a 3rd column (screenshot above) that is causing the entire section to always have to be reset to fix it.

Here is a new Support hash with the 3rd column appearing: http://support.redux.io/?id=tnNrJZZhDka3m2%2BvIrsCO9CC5nPT3PZ6bl5gQN6RGJ6czVM9UrExvub%2B4pyarrCe8f3gXPd%2FWC2o13%2FqSR39zg%3D%3D

    array(
      'id'       => 'homepage-modules-order',
      'type'     => 'sorter',
      'title'    => __( 'Homepage Modules Order', 'redux-framework-demo' ),
      'desc'     => __( 'Choose the modules and the order you would like them to appear on the   homepage.', 'redux-framework-demo' ),
      'options'  => array(
      'enabled' => array(
       ),
     'disabled' => array(
         'news-syndicated' => 'News - Syndicate',
         'news'  => 'News - Primary',
         'news-secondary' => 'News - Secondary',
         'shows' => 'Shows',
         'videos' => 'Videos',
         'events' => 'Events',
         'social' => 'Social',
         'new-one' => 'New One', //Will add a new Disabled column to the theme options panel that needs to be reset to make the extra column disappear.
          ),
       ),

Thank You for looking into this.

**Comment by kprovance** [comment]
Resolved.  Please upgrade to v.3.5.7.2.
