### ISSUE TITLE
Small CSS Issue

### ISSUE THREAD

**Issue by pootato** [reduxframework/redux-framework#2570]
The following **.deletion** CSS rule found in __redux-fields.css__ alters core Wordpress CSS.

`.deletion, .redux-container .redux-multi-text-remove, .redux-container a.redux-multi-text-remove {
    color: red;
    padding: 2px 4px;
    margin-left: 5px;
    background: orange;
}`

This makes the background orange for the "Move to Trash" link.

`.deletion:hover, .redux-container .redux-multi-text-remove:hover, .redux-container a.redux-multi-text-remove:hover {
    background: red;
    color: #fff;
    text-decoration: none;
}`

Hovering makes the background red for the "Move to Trash" link.

<hr>

I suggest adding the following fix:

`.redux-container .deletion, .redux-container .redux-multi-text-remove, .redux-container a.redux-multi-text-remove {
    color: red;
    padding: 2px 4px;
    margin-left: 5px;
    background: orange;
}`

`.redux-container .deletion:hover, .redux-container .redux-multi-text-remove:hover, .redux-container a.redux-multi-text-remove:hover {
    background: red;
    color: #fff;
    text-decoration: none;
}`

**Comment by kprovance** [comment]
Fixed in v.3.5.7.1.  Thanks.  :)

**Comment by kprovance** [comment]
Make that 3.5.7.2, the fields css for dev_mode off didn't update.  Fixed now.
