### ISSUE TITLE
Is it possible to hide menus and submenus based on a select?

### ISSUE THREAD

**Issue by safiro** [reduxframework/redux-framework#2571]
I've over 10 menus with too much fields and it takes too much time to load.
So, I created  array in global options menu:

                 'title'=>'Choose your theme',
		'id'=>'picklayout',
		'type'=>'select',
		
		'options'=>array(
		'layoutone'=>'Layout One',
		'layouttwo'=>'Layout Two',
                'layoutthree'=>'Layout Three',
		'layoutfour'=>'Layout Four',
		'layoutfive'=>'Layout Five',
                'layoutsix'=>'Layout Six',
		),
		'default'=>'layoutthree',
		),

Now, I'd like when theme activated, all menus not displayed but only layout three menu, if I select Layout Two and refresh , only layout two options menu displayed. and so on ......

Thanks.

**Comment by kprovance** [comment]
Unfortunately, this issue tracker is for bug reports.  This kind of thing would fall under premium support, since it's not a bug or an issue with Redux.  Here is a hint however: Use the compiler hook.  https://docs.reduxframework.com/core/advanced/integrating-a-compiler/  Sample included in the sample-config.php

**Comment by safiro** [comment]
I think it can be done but I want to know how to get the array output inside sample-config.php 
for WP files we use 
global $opt_name;
$layout = $opt_name['picklayout'];

How to do this in sample-config.php before Redux::setSection($opt_name,array(    ???
I think I can do it by using if statement but I need to get the array output.

**Comment by kprovance** [comment]
Redux::getOption (opt_name, opt_id)

It's newly added, not in the docs yet.

**Comment by safiro** [comment]
How to use it?
In sample-config.php What's the code for:
if (picklayout value == 'two'){
run the code.
}
