### ISSUE TITLE
Slides field doesn't work in customizer

### ISSUE THREAD

**Issue by ThinkUpThemes** [reduxframework/redux-framework#2573]
The slides field doesn't work when using the advanced customizer. Also, custom extensions buildtusing the slides field as a base also don't work. I've also edited the customizer_fields.php file to extend it to use the Redux core slides field. This again doesn't work.

A jQuery error is thrown up reading:

<pre>Uncaught TypeError: Cannot read property 'setting' of undefined</pre> on line 354 of extension_customizer.js when dev_mode is enabled.

Checked this in the latest version of Redux here on GitHub and the issue is still present. Please can this be resolved asap. It was made clear that the advanced customizer allowed for all core Redux fields to be used in Customizer. That was a big sell for the larger donations. This was the main reason I supported the development of Redux through donations.

Look forward to hearing a solution shortly.

**Comment by ThinkUpThemes** [comment]
I've reviewed the code in entension_customizer.js and from what I can tell there isn't even an attempt at making the customizer compatible with slides. If this really is the case, you've completely misled users with the benefits of the larger donations.

The function redux.customizer.save trips up all the time with the slides field. Please can you be transparent. Have you misled users? Donations of $200 and above were for the extension that apparently allowed for ALL Redux fields to work in the Customizer, not just some of them.

Eagerly awaiting your reply.

**Comment by dovy** [comment]
Working on it.  ;)

**Comment by kprovance** [comment]
I heard this was settled privately...so I'm closing.
