### ISSUE TITLE
Is it possible to set rgba(transparent) value for border color?

### ISSUE THREAD

**Issue by thirumani02** [reduxframework/redux-framework#2574]
Hello,
I am just trying to set the semi-transparent value( for ex. rgba(0,0,0,0.4) ) to the border color via "border" field but i failed. Is there any possible way to do this?

**Comment by kprovance** [comment]
In what context?  Using Redux?  I can't answer this properly without knowing what exactly you tried.

**Comment by thirumani02** [comment]
Yes, at redux option panel framework 3.5.4 and i am referring <strong>border</strong> field https://docs.reduxframework.com/core/fields/border/ 

this is a sample code array for customising border.
<pre>$fields = array( 
    'id'       => 'header-border',
    'type'     => 'border',
    'title'    => __('Header Border Option', 'redux-framework-demo'),
    'subtitle' => __('Only color validation can be done on this field type', 'redux-framework-demo'),
    'output'   => array('.site-header'),
    'desc'     => __('This is the description field, again good for additional info.', 'redux-framework-demo'),
    'default'  => array(
        'border-color'  => '#1e73be', 
        'border-style'  => 'solid', 
        'border-top'    => '3px', 
        'border-right'  => '3px', 
        'border-bottom' => '3px', 
        'border-left'   => '3px'
    )
);</pre>
I would like to add the alpha value(transparency) for border color as they done here https://docs.reduxframework.com/core/fields/color-rgba/ Is it possible?

**Comment by kprovance** [comment]
Not without a rewrite of the border field.  Sorry.  Optionally, you can take the existing field and overload it with your own, or use it to create an extension.  https://docs.reduxframework.com/core/advanced/add-a-custom-field/

Bear in mind, however, you need to have a firm understanding of PHP and Javascript, and any changes made are unsupported by us.

**Comment by dovy** [comment]
That being said. If you want to extend the field and submit a pull request I am sure the community would appreciate it. ;)
