### ISSUE TITLE
Color RGBA field doesn't save value in customizer

### ISSUE THREAD

**Issue by kmob2** [reduxframework/redux-framework#2576]
Hello,

I tried it on several fresh installation, it seems that when using the Color RGBA field to save a color inside the customizer, no value is being saved. Field works correct outside of customizer.

**Comment by kprovance** [comment]
Provide a support URL please, as you've included no pertinent information.

**Comment by dovy** [comment]
Hmm, are you using the advanced customizer BTW? Yes, please provide a support URL.

**Comment by kmob2** [comment]
I just updated from redux 3.5.6.1 to 3.5.7.2 and it's all working now. 
I did have a look at the changelog before regarding the rgba field and since I didn't see anything, I didn't update straight away. Lesson learned - always update, regardless of the changelog :)

Sorry about opening an issue!

**Comment by dovy** [comment]
No worries. Glad it works. ;)
