### ISSUE TITLE
Removing notices

### ISSUE THREAD

**Issue by sodbileg** [reduxframework/redux-framework#2578]
I received a soft rejection with the message to remove those panels. I set `dev_mode` to `false`. Is there any easy way to remove those panels even WordPress debug mode is enabled? Redux version is 3.5.7. WordPress version is 4.3.

![screen shot on 2015-09-01 at 10-27-31](https://cloud.githubusercontent.com/assets/1418797/9598419/f69efd90-50bd-11e5-88d9-94b0d589677f.png)
![screen shot on 2015-09-01 at 10-26-41](https://cloud.githubusercontent.com/assets/1418797/9598421/f7af8876-50bd-11e5-92e5-aa1058adbc04.png)
![screen shot on 2015-09-01 at 10-26-15](https://cloud.githubusercontent.com/assets/1418797/9598423/f9a049c2-50bd-11e5-86d6-1fc9b9ee747c.png)

**Comment by sodbileg** [comment]
Okay, I removed the widget. But how can I remove the notice? I tried the code below with no luck.
`remove_action( 'admin_notices', array( ReduxFrameworkPlugin::instance(), 'admin_notices' ) );`

Also how can I remove `Redux Theme-Check` box?

**Comment by kprovance** [comment]
These things cannot be removed.  Make a note to the reviewer that you have set dev_mode to false, and that users will not see these things, unless WP_DEBUG is set to true.  In which case, they're probably developers, who would need those resources.  Also, you might point out that numerous plugin do the same things, Yoast, WooCommerce, BuddyPress, etc. and yet they are not required to remove those features.
