### ISSUE TITLE
Builder not working? Can't create/download admin folder nor theme

### ISSUE THREAD

**Issue by nonamebaby** [reduxframework/redux-framework#2580]
Just wanted to generate a new admin folder but apart from the spinner nothing is happening.

**Comment by asmikhalil** [comment]
Same here, I can't download admin folder.

**Comment by kprovance** [comment]
We recently updated the Redux ajax_save security to include the opt_name in the nonce check.  That's what caused the builder to bark.  I updated the builder.  Tis fixed now.

Sorry about that.

Cheers.
