### ISSUE TITLE
Trying to get property of non-object

### ISSUE THREAD

**Issue by saqibsarwar** [reduxframework/redux-framework#2582]
I am getting following php notice

"Trying to get property of non-object [my-server-path]/wp-content/plugins/redux-framework/ReduxCore/framework.php on line 940"

Any pointers on resolving this ?

Thanks in advance.

**Comment by saqibsarwar** [comment]
I got it fixed. It was due to an option about a taxonomy that is not yet available as related plugin was deactivate.

I still thinks this should not happen as the checks in redux code are failing to avoid this and those checks needs to be improved.

Regards

**Comment by dovy** [comment]
@kprovance can you add a check for this?

**Comment by kprovance** [comment]
I could have SWORN we fixed this already, it was an issue forever.  ::Sigh::

**Comment by kprovance** [comment]
Yeah, we can fix this again, BUT...if a dev is loading options based on a separate plugin, it's good practice to do a check for the existence of that plugin before loading that option, possibly via a class_exists check.

**Comment by kprovance** [comment]
Fix pushed.

**Comment by saqibsarwar** [comment]
Sorry for not checking back on this on time as I remained busy with a product launch.

@kprovance You are right and I added a class_exists check to fix this issue in my code.

Thanks for fixing it so quickly in redux framework.
