### ISSUE TITLE
Hope this is the right place

### ISSUE THREAD

**Issue by Keystone101** [reduxframework/redux-framework#2583]
Using Webhosty Theme - not in Dev mode
Options panel created using Redux Framework v3.5.4.24	
Cannot work out how to either add something to this area or to remover the words placeholder from the screen http://awesomescreenshot.com/03b57exsd6 

Can you offer me any help or advise please?
Many thansk,

Gordon J

**Comment by kprovance** [comment]
Sorry, but it's not.  You need to contact the author of the theme for support, as we did not author it.
