### ISSUE TITLE
Global argument 'use_cdn' => 'false' does not work

### ISSUE THREAD

**Issue by dasmaeh** [reduxframework/redux-framework#2584]
I've tried using the global argument `'use_cdn' => 'false'` to force Redux loading scripts from the local server upon user request. However this does not have any effect. JS and CSS are still being loaded from cdn.jsdelivery.net
Did I misunderstand the argument or is simply not working in the way intended?

**Comment by kprovance** [comment]
Please provide us with a support URL.

**Comment by kprovance** [comment]
Closing due to lack of reply.  If further assistance is required, please open a new ticket with the required support URL.
