### ISSUE TITLE
Something missing in structure of generated admin folder

### ISSUE THREAD

**Issue by nonamebaby** [reduxframework/redux-framework#2585]
Using the generated folder, I got this message:

>Warning: require_once(...\admin\redux-framework/inc/welcome/welcome.php): failed to open stream: No such file or directory in ..\admin\redux-framework\framework.php on line 67
>
>Fatal error: require_once(): Failed opening required '...\admin\redux-framework/inc/welcome/welcome.php' (include_path='.;...\xampp\php\PEAR') in ...admin\redux-framework\framework.php on line 67*

**Comment by kprovance** [comment]
I just checked the builder and downloaded and admin folder.  The file `\admin-folder\admin\redux-framework\inc\welcome\welcome.php` exists.  Try another download?

**Comment by kprovance** [comment]
Use the dev branch, please.  It's stable.

**Comment by nonamebaby** [comment]
Well tried the download several times. As Admin Folder only and also as theme. In both are missing welcome directory and also templates directory!
I have now downloaded dev branch an copied it over - that works.

Thank you for your time.
