### ISSUE TITLE
Can I exclude few sidebars from the Select field??

### ISSUE THREAD

**Issue by asmikhalil** [reduxframework/redux-framework#2586]
I have an option in my theme that allows the user to create Unlimited sidebars & assign them to different pages ( Homepage, Single Post, Single Page, Archives...etc )

I am using the Select field and passing 'data' => 'sidebars', as argument to get the list of all registered sidebars. Now I want to exclude few sidebars by their ids ( header-area, below-title-area, first-footer-widget-area ...etc) because I want only the default sidebar ( sidebar-1 ) and the custom sidebars created by the user to be listed in this dropdown. Is this possible by using the args argument or any other way other than editing the Select field directly.

Thanks in advance & keep up the good work!

**Comment by kprovance** [comment]
Unfortunately, all Redux does when passing sidebars in the data argument is this:

```php
                            global $wp_registered_sidebars;

                            foreach ( $wp_registered_sidebars as $key => $value ) {
                                $data[ $key ] = $value['name'];
                            }
```
There is no `args` to filter out specific items.  When I've seen others do is write their own function (using the above code as a start) to return a key/pair array of the sidebars they want, and pass that array into the select's `options` argument.  It accomplishes the same thing.

**Comment by dovy** [comment]
You can also register a custom data type and apply it via filter to get the desired effect.

**Comment by asmikhalil** [comment]
Thank you guys! i will try to create custom data type
