### ISSUE TITLE
Change redirect after theme activation

### ISSUE THREAD

**Issue by antoniomangiacapra** [reduxframework/redux-framework#2587]
Hello,

I noticed that after a theme with redux framework embed is activated, user is redirected to welcome page of redux, is it possible change redirect page or disable it?

Thanks.

**Comment by kprovance** [comment]
This only happens on first run and when we do major updates (not minor ones, like freakin' WooCommerce).  But no, this cannot be removed.

**Comment by ebencarljo** [comment]
Very annoying behavior...

**Comment by kprovance** [comment]
And how much have you donated to, or give back to the project?  Specifically?

**Comment by ebencarljo** [comment]
So it's a way to punish thoses who did'nt donate ?

**Comment by kprovance** [comment]
No, but people who didn't, don't, or refuse to don't really have a right to complain, or criticize.  If you don't like Redux, you're free to write your own options panels.  :)

**Comment by ebencarljo** [comment]
what a awesome support... thanks

**Comment by kprovance** [comment]
LOL, whatever pal.  You didn't buy anything, or contribute anything, so I (we) owe you exactly, nothing.  Locking conversation, since this is unproductive.
