### ISSUE TITLE
Overriding settings (theme-options.php) in a child theme?

### ISSUE THREAD

**Issue by sporkman** [reduxframework/redux-framework#2588]
Can't find anything about this in the documentation, but fairly simple question.  If one wants to override something like "$this->args['intro_text'] " inside the "setArguments()" function, how is that accomplished?

I've seen some information on adding additional sections and such in a child theme, but not the actual redux options.  Any tips, and if so, could that be added to the official docs.

**Comment by kprovance** [comment]
You're still using legacy code?  Not easily then.  With the Redux API (https://docs.reduxframework.com/core/redux-api/), changing argument, sections and fields is a one line call, setArg.  Again, you'll have to change your options config to use the API.

**Comment by dovy** [comment]
But don't worry, migration is so VERY easy.   :)
