### ISSUE TITLE
Redux website is down... 

### ISSUE THREAD

**Issue by ruturaaj** [reduxframework/redux-framework#2589]
Hi,

Not sure if it's just with me, but I'm not able to access the Redux documentation and website. It says "Database connection error". Please update on this issue...

Thanks,

Ruturaj.

**Comment by Mubbi-CO8** [comment]
Yups, cant access too

**Comment by dovy** [comment]
Good thing I setup a cluster for our DB. For some reason the master is 20x too big, but it's fix now. Think I'll offload our demo onto Heroku or something as not to bring our main site down again. I think someone was being naughty.  ;)

**Comment by ruturaaj** [comment]
It will be great if we can build a downloadable PDF of documentation.

**Comment by dovy** [comment]
Man, that would be tough since there are so many pieces to Redux... Oy.
