### ISSUE TITLE
WordPress Plugin Repo rejected my plugin for redux

### ISSUE THREAD

**Issue by Mina88** [reduxframework/redux-framework#2591]
Hello, After submitted it on WordPress they sent me following message. Pls help me how can i overcame this. 

"There are issues with your plugin code. Please read this ENTIRE email, address all listed issues, and reply to this email with your corrected code attached. It is required for you to read and reply to these emails, and failure to do so will result in your plugin being rejected.

## Including another plugin

You have redux core included in your plugin

We cannot accept a plugin that includes an entire other plugin, wholesale, inside it.

While we understand the use of framework (or boilerplate) plugins, and encourage the use of common libraries, full blown plugins should never be included inside another, as it causes multiple potential issues, such as function/attribute conflicts, and also opens your code up for issues should the included plugin be closed for a security hole.

The proper way to include another plugin would be to require it in your own. You can use the hook is_plugin_active() to check to see if the plugin is, indeed, installed and active.

https://codex.wordpress.org/Function_Reference/is_plugin_active

The other alternative would be to actually fork the code, and not have a 100% copy in yours. Sadly, WordPress plugins don't have the ability to do sub-modules, so you'll have to actually customize the code for interaction."

**Comment by kprovance** [comment]
Asked and answered in #2289  :)

**Comment by Mina88** [comment]
Thanks sir i am trying it. If i face any problem, can i tell you again.

**Comment by kprovance** [comment]
You can, but all I can do it tell you the same thing.  Those are WP.org's rules, not ours.  There isn't anything we can do about it.

**Comment by dovy** [comment]
The main thing is, don't include anything but the ReduxCore folder or you'll be instantly rejected. "Plugins can't contain other plugins."

**Comment by Mina88** [comment]
I have added only reduxcore folder in my plugin. In reduxcore folder i inlcluded sample-config.php file also. It's rejected. can i use TGM to my plugin or has another way?

**Comment by dovy** [comment]
It shouldn't be rejected for using a framework.  Try to talk some sense into them.

If not, TGM will work.  :)
