### ISSUE TITLE
Can't use Select2 plugin with Custom Select field

### ISSUE THREAD

**Issue by Themient** [reduxframework/redux-framework#2592]
Hello everyone!
I have created a custom Select field called select_custom. it is the same as select field except I exclude few built in sidebars from the data array. Everything is working like a charm but my only problem is the custom select field appears like a normal html select while the Core select field get rendered by select2 jquery plugin.

I am not a geek but I think this problem is easy to solve because when I use both types of select fields (select & select_custom) on the same tab/section both field get recognized & rendered by select2 but when I don't use select alongside select_custom, the latter gets displayed as a normal HTML select.

I think there is a JS file that is required by select2 and only get loaded when the select field is used. But I have spent a long time digging into this but found that the same files are loaded each time.

I am using JS to add "redux-container-select" class to the select fieldset.

Please guys would any of you help me to solve this?!

**Comment by kprovance** [comment]
Something like this would fall under premium support.  We don't have the time to debug other people's code for free anymore.  Sorry.

**Comment by dovy** [comment]
My suggestion is to add a select2 field to your panel, hide it via required or the hide class, and then select2 will be enqueued for you.  ;)   Cheap and easy.

**Comment by Themient** [comment]
Hi dovy!
I've tried that but only the HTML structure is rendered. the select2 Div is not linked to the select field.
Please tell me how to do it.
Or is it possible to edit the 'select' field without changing the 'op_name' and without touching the Core code??

**Comment by kprovance** [comment]
Premium support, bud.  If you're not willing to pay for our time, we can't dig into your code.  You might try overloading:  https://docs.reduxframework.com/core/advanced/add-a-custom-field/

**Comment by Themient** [comment]
Ok! thanks anyway for creating this great plugin ;)
