### ISSUE TITLE
Outdated copies of Redux Framework template files

### ISSUE THREAD

**Issue by jaschaio** [reduxframework/redux-framework#2593]
Getting this error notice:
`Your panel has bundled outdated copies of Redux Framework template files – if you encounter functionality issues this could be the reason. Ensure you update or remove them.`

Not sure what it means, I have downloaded and included the latest version from github. Do I need to update my config file?

**Comment by jaschaio** [comment]
I had an old argument in my config:
`'templates_path' => plugin_dir_path( __FILE__ ) . 'panel/'`

Removed it and the notice is gone. Thanks anyway

**Comment by dovy** [comment]
;)  There you go.

Mainly because you had old templates.  :)
