### ISSUE TITLE
Migrate one option to another

### ISSUE THREAD

**Issue by alexmoss** [reduxframework/redux-framework#2596]
I have some options I want to merge into other options within Redux. For example, I have several normal text fields asking for social media usernames that I want to merge into one bigger Sortable Text Option. How can I move several of those options into the one sortable text option?

**Comment by dovy** [comment]
So you'd have to do this yourself. An easy way to do so is via the switch_theme hook. This will fire when the theme is activated. Just do a check for the "expanded" field names, and if they're present manually combine them, then delete the expanded versions and do an update_options.  ;)
