### ISSUE TITLE
Problem with subsection classes

### ISSUE THREAD

**Issue by alexmoss** [reduxframework/redux-framework#2597]
I have found an issue with a class of the submenu not appearing until it is hovered over or made active. v3.5.7.5 and WP v4.3

![image](https://cloud.githubusercontent.com/assets/1687659/9738051/00874c5e-564a-11e5-8271-5d85ddd77d40.png)

**Comment by dovy** [comment]
Care to find the CSS fix for this?  ;)  We'll add it in and give you credit.

**Comment by kprovance** [comment]
I am unable to replicate.

**Comment by kprovance** [comment]
Um...your image shows two panels with the same name?  Possible conflict there?

**Comment by alexmoss** [comment]
Let's close this as I, of course, didn't see it since. If I do I'll let you know.

**Comment by alexmoss** [comment]
I seemed to identified the issue, FYI.

I had my theme running and active, and saw that I also had Redux installed as a plugin. The plugin wasn't active but deleting it solved the issue.
