### ISSUE TITLE
Select - non numeric keys supported?

### ISSUE THREAD

**Issue by No3x** [reduxframework/redux-framework#2598]
Hi guys, I would like to use a simple array('html', 'raw', 'json') as options for a select field with default.
Am I right in thinking that only associative arrays are supported where the key is 'pseudo numeric' (because of the string)?
I tried it this way without success and kinda wondering it is not supported:
```
array(
	'id'        => 'preferred-mail-format',
	'type'      => 'select',
	'options' 	=> array('html', 'raw', 'json'), // or as associative array with key = value (e.g. 'html' => 'html')
	'default' 	=> '0', // or 'html'
	'title'     => __('Default Format for Message', 'wpml'),
	'subtitle'  => __('Select your preferred format.', 'wpml'),
),
```
or as associative array with key == value (e.g. 'html' => 'html')
```
array(
	'id'        => 'preferred-mail-format',
	'type'      => 'select',
	'options' 	=> array('html' = 'HTML', 'raw' => 'Raw', 'json' => 'JSON'),
	'default' 	=> 'html'
	'title'     => __('Default Format for Message', 'wpml'),
	'subtitle'  => __('Select your preferred format.', 'wpml'),
),
```
So there are actually 2 Questions:
Are non numeric keys for the options supported? And if yes:
How to select it as default?

Redux version: 3.5.5.10

**Comment by kprovance** [comment]
1) You need to seriously update your version of Redux.
2) The select fields use the select2 rendering library.  I imagine you will need to consult their docs for the answer, since it's beyond our control:  http://select2.github.io/select2/

**Comment by monecchi** [comment]
Mr. @kprovance seems not to take into account that not everyone is an expert developer and they're might be arriving late to Redux Framework's party! I totally get the point that some issues posted here are far too old and out of the scope of the plugin.

However, despite of having a great documentation, Redux Framework docs doesn't cover everything. Thus the repository issues might come in handy when they're not completely discarded by the peeps that think they're above the level to deal with such silly questions. 

Simply shutting down such a valid question/issue is a bad thing to do!

The select fields being rendered by the select2 library should not have any implications on how to get non numerical keys from the select options array.
