### ISSUE TITLE
Updating an option outside the options panel via Redux API 

### ISSUE THREAD

**Issue by jaschaio** [reduxframework/redux-framework#2600]
I have just updated my config file to use the [Redux API](https://docs.reduxframework.com/core/redux-api/). 

I have noticed that the [old way](https://docs.reduxframework.com/core/advanced/update-an-option-outside-the-options-panel/) to update an option outside the options panel won't work anymore once using the Redux API to setup Redux.

I saw that @kprovance added the two functions `getOption` and `setOption` just a couple of days ago (1de356f0e63c8e6cd114b5188dae50aeffb0086d). So obviously the docs still won't explain them. Anyway I was wondering if I am doing it right:

Setting $opt_name global:
`global $opt_name;`

Call the function from anywhere like any other API function:
`Redux::setOption( $opt_name, 'checkbox', 0);`

What is the `getOption` function for? Shall I stop using the global variable + key (e.G. `$redux_demo['key']`) and instead use the API function `Redux::getOption( $opt_name, 'key')`?

Do you guys need help updating the docs?

**Comment by kprovance** [comment]
Well, I made the foolish assumption that get/setOption were pretty self explanatory.  get, as in to retrieve and option.  Set, as to save option.  If I really need to say all that on the docs site, then we have larger issues with our user base.

If my docs are inadequate, then I guess I can take the time to repeat myself here, although it'll be there same:  setOption (to save an option with a new or different value).  Param one is the string value opt_name (not the opt_name array itself, big difference.  I did specify string, hopefully that's not an issue.)  Second param, the ID of the option to change.  Only you know the IDs of your options, you'll have to determine that for yourself.  Third param, the new option to save.

getOption does exactly what it says, it retrieves a previously saved option.

What you do with your code is up to you.  That said, if you are using the Redux API in your code, your option panel needs to be API, NO legacy code.  Either the the API completely, or use none of it ata all.  Using it partially may not work.

**Comment by jaschaio** [comment]
Thanks for your reply.

It is pretty self explanatory, but not referenced in the docs therefore I was asking.

Anyway I have one issue: If I try to update an option with `Redux::setOption( $opt_name, 'key')` from within a `validate_callback` function it won't work. Everywhere else it is working.

**Comment by kprovance** [comment]
Well, that's unfortunate, but I don;t have the time to go into it this week.  I will when I can.  Sorry.

**Comment by dovy** [comment]
@jaschaio probably because with a validate_callback, you return the value to be saved I believe. Right after all the validations the options are saved. If you didn't return a value, then yes it would not update.

**Comment by jaschaio** [comment]
@dovy thanks for your response. I am returning the value but anyway it won't work with the validate_callback. As well if I use the hook you mentioned in #2601.

There is actually another strange behaviour:

If I use `Redux::setOption( $opt_name, 'key')` inside both a compiler or saved hook it reloads the page with the old options set. If I than reload the page again it loads it with the new, updated options.

**Sample code:**

Fields:


            array(
                'id'        => 'field-id',
                'type'      => 'text',
                'title'     => __('Sample Text Title', 'textdomain'),
                'compiler'  => true,
            ),
            array(
                'id'        => 'switch-id',
                'type'      => 'switch',
                'title'     => __('Sample Switch Title', 'textdomain'),
                'default'   => 0,
            ),

Compiler Hook:


        add_filter('redux/options/' . $opt_name . '/compiler', 'field_compiler', 10, 3);

Function:

        if (!function_exists('field_compiler')) {
                function field_compiler ( $options, $css, $changed_values ) {

                global $redux_demo;
                global $opt_name;
                $opt_name = 'redux_demo';

                if ( array_key_exists('field-id', $changed_values) ) {

                if ($redux_demo['field-id'] == 'one') {
                    Redux::setOption( $opt_name, 'switch-id', 1);
                } else {
                    Redux::setOption( $opt_name, 'switch-id', 0);
                }
            }
        }

So if I enter one into the text field it saves and on reload the switch keeps disabled (0). If I then reload it again the switch changes to enabled (1). The same is true if I change the text field back to something else then one: After saving the switch keeps enabled, only after an additional reload it takes the new option-value (disabled).

So to see the new set option value from Redux::setOption the user has to do an additional reload. As well if I want to use the new value inside a callback field, I have to do an additional reload to be able to use it.

**Comment by fbester** [comment]
Hey there @dovy, @kprovance, thanks for the great job on redux! 

Hi @jaschaio.

I can confirm this problem too. I have a bunch of options that I update using Redux::setOption()
 and when Saving Changes, old option values still persist until you do another page refresh.

Have tried alleviating it with 'ajax_save' => false.
I'm using the redux/options/ps_options/settings/change hook and have tried different priorities.
I'm no expert, but it might have something to do with the transients.

Support Hash: http://support.redux.io/?id=69nqks2ibzwd4tXbO%2Fk8AzSWbanEClRd82zxWAq1%2BIXSz0PSLi3E8oOFrdQvp5MX8XUJaArIC5PCVso3CFI0YQ%3D%3D

Regards,

Fritz.

**Comment by kprovance** [comment]
This is the nature of the best.  If you change an option via setOption, it will NOT update on the options panel until the page is refreshed, which needs to be done before saving.  Unfortunately, with the current workload Dovy and I have, it's not something we can get into any time soon.  That said, this is open source.  If you'd like to fix it and submit a pull request, that's what open source is all about.  :)
