### ISSUE TITLE
Custom Validate Callback error returns undefined

### ISSUE THREAD

**Issue by jaschaio** [reduxframework/redux-framework#2601]
[Check the demo to replicate](http://demo.redux.io/wp-admin/admin.php?page=_options&tab=49). If you enter "1" it shows "undefined" instead of the error message. If you enter "2" it shows the warning message as intended.

Field Code (from sample-config.php)

    array(
        'id'                => 'opt-text-custom_validate',
        'type'              => 'text',
        'title'             => __( 'Text Option - Custom Callback Validated', 'redux-framework-demo' ),
        'subtitle'          => __( 'You decide.', 'redux-framework-demo' ),
        'desc'              => __( 'Enter <code>1</code> and click <strong>Save Changes</strong> for an error message, or enter <code>2</code> and click <strong>Save Changes</strong> for a warning message.', 'redux-framework-demo' ),
        'validate_callback' => 'redux_validate_callback_function',
        'default'           => '0'
    ),

Custom Validate Callback Function (from sample-config.php)

    /**
     * Custom function for the callback validation referenced above
     * */
    if ( ! function_exists( 'redux_validate_callback_function' ) ) {
        function redux_validate_callback_function( $field, $value, $existing_value ) {
            $error   = false;
            $warning = false;

            //do your validation
            if ( $value == 1 ) {
                $error = true;
                $value = $existing_value;
            } elseif ( $value == 2 ) {
                $warning = true;
                $value   = $existing_value;
            }

            $return['value'] = $value;

            if ( $error == true ) {
                $return['error'] = $field;
                $field['msg']    = 'your custom error message';
            }

            if ( $warning == true ) {
                $return['warning'] = $field;
                $field['msg']      = 'your custom warning message';
            }

            return $return;
        }
    }

**Comment by kprovance** [comment]
Have you perhaps considered attempting to find a fix and submit a pull request?  It is open source.  Waiting for me to fix it means you could be waiting a while, since our days jobs take priority over projects that the dev community refuses  to support.  :)

**Comment by pootato** [comment]
You have plenty of support, just not in the development aspect you're hoping for. I've tried to help and have added a few minor dev fixes, but most of the code is beyond me.

The problem is most of the devs that use Redux Framework are only Designers, if they had the amazing skills you possess they would probably just make their own framework.

Have you considered creating your own Themes @kprovance @dovy ? Would take you only a few weeks per theme and could lead you to the financial freedom you are hoping for.

**Comment by kprovance** [comment]
I've been working on one for moths, with the last few eating rejections from TF over stupid crap.  So, yeah, not quite that simple.

**Comment by pootato** [comment]
Yeah, I imagine the first theme is the hardest to get past their annoying submission team. 

Keep at it though, then you can re-use the first successful theme as a framework.

**Comment by dovy** [comment]
That's the plan @pootato. Poor @kprovance has had quite the runaround on a powerful theme. *sigh* It's a pain.

Sorry for the latent frustration wading through all of that.  ;)

To get the custom callback to work, are you using the hook to run the function? You can't just have the function...

```php
<?php
 add_action("redux/validate/OPT_NAME/class/VALIDATION_STRING", 'redux_validate_callback_function');
```

Replace opt_name with your opt_name and VALIDATION_STRING with what you call the validation in the hook. Run this before you run your Redux config.  ;)
