### ISSUE TITLE
An error occured while updating the theme

### ISSUE THREAD

**Issue by memash** [reduxframework/redux-framework#2602]
I am using Easy Digital Downloads. I am not able to update the theme. I get the following error when trying to update the theme. What do I do?

Update Theme
Downloading update from http://supernovathemes.com/?edd_action=package_download&license=05989f42974c3f0a28d08b36f6763fdd&id=1439&key=3bf4bfe6527e4a6804b0c8cfac7edcba&expires=MTQ0MTg0MDY0NA%3D%3D…

Unpacking the update…

Could not create directory. powen-pro/pro/admin/redux-framework/assets/css/vendor/elusive-icons/fonts

Return to Themes page

**Comment by kprovance** [comment]
You need to contact the author of theme to receive support from them regarding server issues.  We do not support themes that use our product, that is the theme author's responsibility.  Sorry.
