### ISSUE TITLE
CDN unavailable errors

### ISSUE THREAD

**Issue by joshricha** [reduxframework/redux-framework#2603]
I haven't changed anything on my theme recently but have started receiving the following CDN errors:

Redux Framework Warning
select2-css CDN unavailable. Some controls may not render properly. Please wait a few minutes, then try refreshing the page..

Redux Framework Warning
redux-spectrum-css CDN unavailable. Some controls may not render properly. Please wait a few minutes, then try refreshing the page..

Redux Framework Warning
qtip-css CDN unavailable. Some controls may not render properly. Please wait a few minutes, then try refreshing the page..

Redux Framework Warning
select2-js CDN unavailable. Some controls may not render properly. Please wait a few minutes, then try refreshing the page..

Redux Framework Warning
qtip-js CDN unavailable. Some controls may not render properly. Please wait a few minutes, then try refreshing the page..

Redux Framework Warning
redux-spectrum-js CDN unavailable. Some controls may not render properly. Please wait a few minutes, then try refreshing the page..

Redux Framework Warning
ace-editor-js CDN unavailable. Some controls may not render properly. Please wait a few minutes, then try refreshing the page..

Redux Framework Warning
select2-css CDN unavailable. Some controls may not render properly. Please wait a few minutes, then try refreshing the page..

Redux Framework Warning
redux-spectrum-css CDN unavailable. Some controls may not render properly. Please wait a few minutes, then try refreshing the page..

Redux Framework Warning
qtip-css CDN unavailable. Some controls may not render properly. Please wait a few minutes, then try refreshing the page..

Redux Framework Warning
select2-js CDN unavailable. Some controls may not render properly. Please wait a few minutes, then try refreshing the page..

Redux Framework Warning
qtip-js CDN unavailable. Some controls may not render properly. Please wait a few minutes, then try refreshing the page..

Redux Framework Warning
redux-spectrum-js CDN unavailable. Some controls may not render properly. Please wait a few minutes, then try refreshing the page..

Any ideas how to fix it?

**Comment by kprovance** [comment]
You have an OLD version of Redux.  Most of those were removed, and the logic improved.  Please update ASAP!

**Comment by joshricha** [comment]
Great, thanks! Redux came with a theme I bought, will it have any effect on everything else?

Junior question but do I just update the files via ftp?

**Comment by kprovance** [comment]
You need to contact the author of your theme in regard to this.  It's their responsibility to keep Redux current in their work, and as such need to be offering you support for this issue.

**Comment by joshricha** [comment]
Thanks for your help!

**Comment by dovy** [comment]
You can install the Redux plugin from the WordPress.org repo and it will override the embedded version. That should help in the interim.  ;)

**Comment by joshricha** [comment]
Great, thanks! Sorted.
