### ISSUE TITLE
How to get option values inside the admin area

### ISSUE THREAD

**Issue by mstoic** [reduxframework/redux-framework#2604]
Hi, I wanted to display a meta box only if user has enabled it in the redux settings. Is it possible? Because I am not getting redux values in the WP dashboard.

**Comment by dovy** [comment]
Run:  Redux::init('opt_name') to get Redux to run before the init hook, and work within the functions.php file.  ;)

**Comment by distincthq** [comment]
sorry to comment on this closed topic, 
dovy you mentioned to add Redux::init('opt_name') so we can use values in functions.php
where should this be added?

**Comment by dovy** [comment]
Before you try to use the global variable. ;)

Basically Redux is delayed loading until the init hook to ensure all things load. If you need the data sooner you can a) do your own get_option for previously set options b) force Redux to load. Make sure all your configuration has loaded first.
