### ISSUE TITLE
How to add Metabox option in custom post type?

### ISSUE THREAD

**Issue by Mina88** [reduxframework/redux-framework#2605]
Hello, I have read following link but i have not understood where i need to paste this code. I have pasted it in my function.php file but it have not seen in custom post type(Post/Page).

https://docs.reduxframework.com/extensions/metaboxes/

could you tell me where i need to paste? i also pasted in my sample-config.php file

**Comment by dovy** [comment]
Before your options config file.  ;)

**Comment by Mina88** [comment]
Hello, Thanks for reply. I have added but not showing anything in page/post. See my code from below file 

http://themeratio.com/theme-config.txt

**Comment by kprovance** [comment]
```
add_action("redux/metaboxes/$cjr_social/boxes", "redux_add_metaboxes");
```
You're adding the opt_name variable, when it needs to be the actual string value of the opt_name.

**Comment by Mina88** [comment]
Hello sir i am not expert in php. Now what i need to do. could you give me modified code from my file so that i can add it without hesitate. I really want this because redux other function is simple for me. Only i am facing problem with this. I have tried many times but i have failed and i am 100% sure you have solution for me.

**Comment by kprovance** [comment]
Well, Using Redux and it's extensions require a working knowledge of PHP.  What you want from me at this point falls under premium support.  In that code you posted, you have an $opt_name variable, but it's not set to anything, so I can't even tell you what your opt name is to put in the metaboxes filter.

We aren't PHP tutors here.  If you want one of us to write your code for you, it's going to fall under premium support services.

**Comment by dovy** [comment]
Here's a hint. In the string, replace $cjr_social with your actual opt_name. Or in other words... `cjr_social`

**Comment by kprovance** [comment]
Assuming that's the actual opt_name, since one is never set.  Until that's done in the global args, it's never work.

**Comment by Mina88** [comment]
Thanks have you seen i have added my global option name. cjr_social is my option name

<pre>
    // This is your option name where all the Redux data is stored.
    $opt_name = "cjr_social";
</pre>

so i have added it to below option 

<pre>add_action("redux/metaboxes/$cjr_social/boxes", "redux_add_metaboxes");</pre>

**Comment by dovy** [comment]
You didn't give us any code to go off of my friend. It's really hard to know that when you don't provide the source...

Do you use the Redux API or the old way of adding options? Have you run the Redux::setExtensions() function?

**Comment by kprovance** [comment]
<blockquote>
add_action("redux/metaboxes/$cjr_social/boxes", "redux_add_metaboxes");
</blockquote>

And I said, previously:
<blockquote>
You're adding the opt_name variable, when it needs to be the actual string value of the opt_name.
</blockquote>

**Comment by dovy** [comment]
Actual @kprovance, that will work. Double quotes allow for the use of variables automatically.

**Comment by Mina88** [comment]
Ok @dovy you are really good see my below image you can understand. I have download latest redux framework and included only Reduxcore folder in my hosting then i have added theme-config.php file in Reduxcore folder. see below image you can understand 

![redux](https://cloud.githubusercontent.com/assets/9547134/9821056/966084f2-58d9-11e5-8254-596a49067289.jpg)

**Comment by cuongpx** [comment]
@kprovance  you can upload file demo.

**Comment by brody182** [comment]
if I paste this in options-init.php nothing show up in posts of page..

```
// BE SURE TO RENAME THE FUNCTION NAMES TO YOUR OWN NAME OR PREFIX
	if ( !function_exists( "redux_add_metaboxes" ) ):
			function redux_add_metaboxes($metaboxes) {
					// Declare your sections
					$boxSections = array();
					$boxSections[] = array(
							//'title'         => __('General Settings', 'redux-framework-demo'),
							//'icon'          => 'el-icon-home', // Only used with metabox position normal or advanced
							'fields'        => array(
									array(
											'id' => 'sidebar',
											//'title' => __( 'Sidebar', 'redux-framework-demo' ),
											'desc' => 'Please select the sidebar you would like to display on this page. Note: You must first create the sidebar under Appearance > Widgets.',
											'type' => 'select',
											'data' => 'sidebars',
									),
							),
					);

					// Declare your metaboxes
					$metaboxes = array();
					$metaboxes[] = array(
							'id'            => 'sidebar',
							'title'         => __( 'Sidebar', 'fusion-framework' ),
							'post_types'    => array( 'page', 'post' ),
							//'page_template' => array('page-test.php'), // Visibility of box based on page template selector
							//'post_format' => array('image'), // Visibility of box based on post format
							'position'      => 'side', // normal, advanced, side
							'priority'      => 'high', // high, core, default, low - Priorities of placement
							'sections'      => $boxSections,
					);

					return $metaboxes;
			}
			// Change {$redux_opt_name} to your opt_name
			add_action("redux/metaboxes/theme_mars/boxes", "redux_add_metaboxes");
	endif;
```

**Comment by kprovance** [comment]
HI.

1) Please do not piggy back old issue.
2) Please post all extension issues here:  https://github.com/reduxframework/redux-extensions
3) Please include your purchase number so we may verify a current subscription.

Thanks.
