### ISSUE TITLE
Typography and Font Option Not Showing in WP Theme Customizer

### ISSUE THREAD

**Issue by suresha5** [reduxframework/redux-framework#2606]
Typography not showing in wp theme customizer i am using latest version of Redux Framework v3.5.7.5

**Comment by AlexAlexandru** [comment]
Redux Framework supports a limited number of fields in customizer and typography is not support.However there is a paid extension https://ideas.reduxframework.com/campaigns/complete-customizer-integration/ .

**Comment by kprovance** [comment]
What @AlexAlexandru said.  :)
