### ISSUE TITLE
Problem submission WordPress repository

### ISSUE THREAD

**Issue by nicolas92** [reduxframework/redux-framework#2608]
Hello, I have a little problem, I try to add a theme in wordpress directory and when I submit, I have several information messages, it does not matter but I have three messages "REQUIRED" the files "welcome.php" and "framework.php" I read the documentation when you say that the theme will not be rejected because of his mistakes but when I upload the theme, I have a message "Your theme has failed the theme check. Please correct the problems with it and upload it again.", it means that his mistakes should be corrected so that the theme is submitted, is that it?
Or theme will be examined manually?
Thank you a lot.

**Comment by kprovance** [comment]
Hard to say, since the reference to these messages are vague.  Any chance on posting them exactly as they appeared?

**Comment by nicolas92** [comment]
Hi, there are several message "INFO", but I think it is not important, here are 3 three messages "REQUIRED":

<pre>REQUIRED: welcome.php. Themes should use add_theme_page() for adding admin pages.
Line 195: $page = 'add_management_page';</pre>

<pre>REQUIRED: framework.php. Themes should use add_theme_page() for adding admin pages.
Line 1408: $this->page = call_user_func( 'add_menu_page', $this->args['page_title'], $this->args['menu_title'], $this</pre>

<pre>REQUIRED: framework.php. Themes should use add_theme_page() for adding admin pages.
Line 1331: // wrappers and need to be appened to using add_submenu_page.
Line 1382: $this->page = call_user_func( 'add_submenu_page', $page_parent, $page_title, $menu_title, $page_permission
Line 1440: call_user_func( 'add_submenu_page', $this->args['page_slug'], $section['title'], $section['t</pre>

**Comment by kprovance** [comment]
@Dovy, them check got wise.  What say ye?

Honestly, I do not know the answer.  Redux also functions for plugin, so add_theme_page would not work.  The TRT are being draconian, as usual.

**Comment by nicolas92** [comment]
Yes, unfortunately, I can not submit the theme before having solved its three messages.
But there is something strange, I think some use wordpress themes come redux framework, how did he manage to submit their theme.

**Comment by kprovance** [comment]
I don't know.  Grandfathered in, perhaps?  wp.org doesn't even allow options panels anymore.  So unless your theme is customizer only, they'll reject it.

**Comment by nicolas92** [comment]
Yes, I know, I use redux only in the customizer.

**Comment by nicolas92** [comment]
Problem solved :)
I had integrated redux directly into the theme, now is via TGM.
Thanks, have a good day :)

**Comment by kprovance** [comment]
Okay, cool  :)

**Comment by dovy** [comment]
Proper solution is to comment out that line. We'll need to update the builder.
