### ISSUE TITLE
ATTENTION DEVS: PLEASE READ - This is regarding data escaping and santizing in the Redux Core.

### ISSUE THREAD

**Issue by kprovance** [reduxframework/redux-framework#2610]
Devs - male and female alike.

I have begun the long and arduous process of going through the Redux core in an effort to begin the proper data escaping and sanitizing that entities like ThemeForest demand.  It's long over due, anyway.  This will be happening in sections.  Today I pushed into the core a lot of base files, such as templates, core extensions, and a few fields (ace, textarea, info, and section.

Please, if you find issues pertaining to misprinted text on your Redux options panel, it's probably due to my goofing something up.  Please file all reports that pertain to this issue here, so I may investigate.  I'd like to make Redux fully compliant with TF data rules, so those who embed don't have to experience rejection and rejection (some get away with it, some don't.  It's odd).

Also, if you're like me and like to comb over code, I welcome suggestions, and bugs to squash...so don't be shy!

The fun begins with v3.5.7.8

- Kevin, for Team Redux.

**Comment by MonsterTheme** [comment]
This sounds amazing, great work!

**Comment by fireform** [comment]
No sure I understand why most TF authors include framework into the theme (it's easy to create your own extension or override existing one). Never had any problems approving themes using Redux as plugin + config that comes with the theme.

**Comment by MonsterTheme** [comment]
To have more control over updates and to be more user-friendly. 

If the user decides to not install the plugin (ex. no internet), they get a broken theme.

**Comment by fireform** [comment]
1. More control? That means old framework version anytime you forgot/has no motivation to update theme.
2. Broken theme? <a href="https://codex.wordpress.org/Function_Reference/current_theme_supports">current_theme_supports</a>. Sorry, sounds unprofessional.

**Comment by MonsterTheme** [comment]
1. Better to have the old framework version. If you do heavy editing to the framework, a later version could break something.
2. It's more professional to have everything built-in and ready to go, than to have a user install a dozen things to get a theme to work.

**Comment by fireform** [comment]
1. Oh, heavy editing.. then I understand buyers giving 3 stars rating.
2. Say hello to new Envato quality standards, but anyway I believe that it's best practice to keep additional functionality in plugins. The theme must work as a plain blog without it.

**Comment by dovy** [comment]
Obviously we prefer it as a plugin for updatability and easy of pain, but we want to support embedding.

Honestly though, there's no real benefit to embedding Redux other than the ability to hide the references of Redux.  ;)

**Comment by fireform** [comment]
Ha-ha, yes Dovy. There are too many sly developers who want to mark as his own product.

**Comment by MonsterTheme** [comment]
I agree that irresponsible authors who never update should go with the Plugin method.

It's one thing to hide references (bad form), it's another to make a theme look nice with no effort in making the panel look equally amazing. That's like having a ferrari with the interior of a honda. 

Own up to your brand and your customers will appreciate the added effort. :P

**Comment by dovy** [comment]
Indeed.

Side note, you can modify Redux completely by CSS or even panel HTML using proper hooks and filters. heh. Nuff said.

**Comment by MonsterTheme** [comment]
Yes I tried this, but kept getting the error "Your panel has bundled outdated copies of Redux Framework template files". Plus forced_dev_mode in local is causing the ads to cover up buttons.

**Comment by dovy** [comment]
FYI, the error only occurs when we change the template files for some reason. May want to look at that.  ;)

**Comment by MonsterTheme** [comment]
Yea I keep updating it, it's mainly a problem with forced_dev_mode.

**Comment by kprovance** [comment]
<blockquote>
Never had any problems approving themes using Redux as plugin + config that comes with the theme.
</blockquote>
@fireform, you do theme checking for TF?

**Comment by anikitas** [comment]
Hello guys,

I though this will come up eventually.

Had to resubmit 2 times for a new Theme in TF regarding escaping. I almost changed all the files.
I managed to pass the review at last with embedded Redux 3.5.6.6.

What will you use for displaying the configuration title/desc?

Some people use <br> inside translations or to break configuration descriptions in separate lines.
Using esc_html__() or esc_html() will actually print the line break as tag.

**Comment by kprovance** [comment]
I may have to go wp_kses_post to preserve HTML.  Did it break already?

**Comment by anikitas** [comment]
I removed all br tags in the last Theme before submission just in case.
I have to retest my older Themes with the latest version of Redux.

But usually TF is very strict to new Themes submissions not updates of old ones.

**Comment by kprovance** [comment]
If it's your code your worried about, push the translation into a variable and run it through wp_kses_post (that's what I did).

And yeah, TF.  Ugh.  I wish I could express how so very disappointed I am with them at present.

**Comment by anikitas** [comment]
I was actually worried of the Redux Fields regarding labels and descriptions.
Configuration is done from the config file owned by the Theme Authors, but the actual display is Redux Core.

So escaping can be done either from the title/subtitle/desc of field configuration( config file), or at the end just before displaying ( Redux ).

I think a general rule TF is searching is "echo $"

If they find many of them, it's automatic rejection. I don't think they even bother looking at the code. Reviewers have a quick way to identify possible issues. Don't know if they have a specific tool.

They always redirect me to these 3 articles:

- http://codex.wordpress.org/Data_Validation
- http://developer.wordpress.com/themes/escaping/
- https://vip.wordpress.com/2014/06/20/the-importance-of-escaping-all-the-things/

I also tried the automation scanner: https://github.com/Automattic/vip-scanner
Only managed in console mode though.

I hope it helps.

Going to sleep...

**Comment by anikitas** [comment]
Hello Kevin,

I found an issue while testing escaping with Theme Check with embedded Redux.
Tested various Redux releases also: 3.5.7.10
It seems that one Redux translation gets a weird php notice on Theme Check.

Notice: Undefined offset: 2 in ...\wp-content\plugins\theme-check\checks\textdomain.php on line 82

I narrowed it down to welcome.php function: change_wp_footer()

The https URL confuses the translation or/and Theme Check
It confuses "https://" as a  text domain

I think it's the concatenation of the URL
<pre>
href="' . 'https://' . 'wordpress.org/support/view/plugin-reviews/redux-framework?filter=5#postform"
</pre>

I hope it helps!

**Comment by kprovance** [comment]
I believe Dovy broke up those URLs to avoid all those "no hard coded URL' warning messages.  Granted, no hard coded URLs should be used in actual theme code, but sometimes there is cause, for times such as this, and theme check doesn't respect that.

I've reported this error to the guys who do the code in the past.  Whether they fix it or not remains to be seen.  :)

**Comment by anikitas** [comment]
That was my assumption too :)

The problem came up after the addition of translation function __()
There was no problem before.

I think the Theme Check gets confused.

You could use a sprintf for the URL, i think i've seen it used in similar code in the same file.
Something like:
<pre>
echo sprintf( __('If you like <strong>Redux</strong> please leave us a <a href="%s" target="_blank" class="redux-rating-link" data-rated="Thanks :)">&#9733;&#9733;&#9733;&#9733;&#9733;</a> rating. A huge thank you from Redux in advance!','redux-framework'), 'https://wordpress.org/support/view/plugin-reviews/redux-framework?filter=5#postform' );
</pre>

**Comment by kprovance** [comment]
Hmmm.  Worth a try.  I think the difference is - in my own theme - I don't embed Redux and have not seen this before.  If it works, I'll push the change.  Thanks.  :)

**Comment by anikitas** [comment]
No problem,

Just drop the ReduxCore folder into a Theme.
I think ThemeCheck just scans the files of the Theme not need to actually embed.

**Comment by anikitas** [comment]
Hello Kevin i see that the problem with the translation is still in the latest release 3.8.1.

I will submit a new Theme soon.

Are you thinking of modifying it? I think i will change it in my submission because it's found on Theme Check.

I didn't want to open a new issue about this. Sorry i reply on the closed one. All information is on the latest comments of this issue though.
