### ISSUE TITLE
Missing :hover with link_color when there are multiple selectors

### ISSUE THREAD

**Issue by Slobork** [reduxframework/redux-framework#2612]
Hi,

I have encountered a problem with the <code>link_color</code>.
When there's multiple selectors, pseudo hover is added only to the last selector.

For example, instead of outputting:
<code>selector1 a, selector2 a { color: #ccc; }</code>
<code>selector1 a:hover, selector2 a:hover  { color: #ddd; }</code>
it will output:
<code>selector1 a, selector2 a { color: #ccc; }</code>
<code>selector1 a, selector2 a:hover { color: #ddd; }</code>

Notice that it is missing the <code>:hover</code> on selector1 a.

I'm on localhost using the latest version of the Redux. Hopefully you can reproduce this.

Thanks for everything including the taking the time to look into this issue!

**Comment by kprovance** [comment]
Required info now:  https://docs.reduxframework.com/core/generating-a-support-hash/

**Comment by Slobork** [comment]
Hi Kevin, here's a link:

http://support.redux.io/?id=2nTfPP7JUoDEslxMQ%2BQWi0K66nn1%2B%2F1k6iPYqAssiJ1G9vzlgUINaqQTK1DZGCuEN4z%2FnCF2WnOtKtBkCypThQ%3D%3D

**Comment by kprovance** [comment]
Fixed in git push v.3.5.7.9.
