### ISSUE TITLE
tmp directory

### ISSUE THREAD

**Issue by jpilcher** [reduxframework/redux-framework#2613]
I'm having issues with a theme that uses the ReduxCore as a dependency running on Pantheon. Does Redux write to the /tmp directory?

Looking at the source it looks like a '/redux/' folder is created and a 'tmp' folder is used inside of that. Is that correct?

It looks like the theme is using version 3.3.3.2 of Redux. Any insight into the issue is greatly appreciated. Not looking for a fix just some information about Redux.

**Comment by kprovance** [comment]
YOu need to contact the theme author and ask them to update Redux.

**Comment by jpilcher** [comment]
I'm not asking for help with the theme. I'm just asking if Redux tries to write to the /tmp directory.

**Comment by dovy** [comment]
The OLD version of Redux DOES write, but not to the tmp directory. It makes it's own directory inside wp-content/redux. You can try installing the Redux plugin, but your version of Redux is so old that I hope it doesn't affect anything. Should be good though, we're pretty rabid about not breaking things.  ;)

**Comment by jpilcher** [comment]
Thanks dovy!

**Comment by dovy** [comment]
Np.  ;)
