### ISSUE TITLE
Themeforest reviewer: fwrite, fopen, fread, file_put_contents, file_get_contents is not safe, use WP_Filesystem instead

### ISSUE THREAD

**Issue by vianhtu** [reduxframework/redux-framework#2614]
Hello

Themeforest reviewer: fwrite, fopen, fread, file_put_contents, file_get_contents is not safe, use WP_Filesystem instead.

Thanks!

**Comment by dovy** [comment]
We do, it's just a fallback. Send them to our theme-check page on the docs.
