### ISSUE TITLE
Download an older version of redux

### ISSUE THREAD

**Issue by kmob2** [reduxframework/redux-framework#2616]
I am not very familiar with github. I am looking to download older versions of redux framework. All I could find is this page here; https://github.com/reduxframework/redux-framework/tags but that doesn't include most versions. I am looking for redux 3.5.6.9 (or no older than 3.5.6.3).

**Comment by kprovance** [comment]
Here, I think:  https://github.com/reduxframework/redux-framework/archive/3.5.5.zip.  Understand the issues we've fixed since then you'll have to apply manually.
