### ISSUE TITLE
Visual Composer/Ronneby Theme : not able to save any modifications !

### ISSUE THREAD

**Issue by TimotheeNalet** [reduxframework/redux-framework#2617]
Hi there,
I'm using Theme Forest - Ronneby (last version downloaded from Envato 2 days ago) and Visual Composer came included in it (version 4.7.1).
Everything is working fine, except I can't save any modification performed through the Visual Composer popup window.
The button "Save" seems like inactive, same for the Settings icon in the popup window.
I've tried many options : deactivating extensions, re-installing wordpress, updating everything, etc. etc.

Have you ever heard of any similar problem ?
Below is the result in my console, if this helps..

Really looking forward to receiving some help from you, as I'm stuck in the construction of my website, and it has to be lie within a few days :/ ...

Best,
Timothée

![capture](https://cloud.githubusercontent.com/assets/14345510/9956990/1be8399e-5dfd-11e5-83c2-517dee5a7206.JPG)

**Comment by TimotheeNalet** [comment]
Probem solved !
Thanks

**Comment by kprovance** [comment]
That's good, because we're Redux Framework.  NOT VC, and not your theme's author.  In the future, please seek support for your theme's author.
