### ISSUE TITLE
Unable to save settings

### ISSUE THREAD

**Issue by AlexAlexandru** [reduxframework/redux-framework#2618]
One of my users can't save it's settings.For my it's working on localhost also on a live website.
Here is a ss of the error 
http://imgur.com/KUPKWuP
and here is the support hash
http://support.redux.io/?id=dxNQ2qIQ3UwiaJ5BZJ5D%2FDm5Xgamt%2BTJK7Ek6kHbz8C1qiubvrIZULwypbbExIHG1TOghnq0UdoLRKlbMB%2Bycg%3D%3D
This is my config file
https://github.com/VortexThemes/rating-system/blob/master/admin/vortexlikedislike.php

**Comment by kprovance** [comment]
Is the support URL the users, or your yours?  It needs to be the users.  Yours won't have the necessary info.

**Comment by kprovance** [comment]
The support URL provided indicated the use of the 2015 theme with no instances of Redux loaded.  Can't use it.

**Comment by AlexAlexandru** [comment]
http://support.redux.io/?id=dxNQ2qIQ3UwiaJ5BZJ5D%2FDm5Xgamt%2BTJK7Ek6kHbz8C1qiubvrIZULwypbbExIHG1TOghnq0UdoLRKlbMB%2Bycg%3D%3D

It's from the user

**Comment by kprovance** [comment]
Well, that doesn't help either.  She's running the 2015 theme, that somehow uses Redux (but inherently does not), but has NO Redux config?

None of this makes any sense.

**Comment by AlexAlexandru** [comment]
It was from my way of hooking the config file into redux my bad.
