### ISSUE TITLE
Radio buttons return array when empty

### ISSUE THREAD

**Issue by ThinkUpThemes** [reduxframework/redux-framework#2620]
Hello,

By default when the theme is initially activated, without any options being saved. For the radio field an array is returned for the variable, rather than the variable being empty. This means that the following check doesn't work:

<pre>if( empty( $variable ) )...</pre>

Is there any way to make sure an empty value is returned when the user hasn't chosen an option for whenever a radio field is used?

Thanks as always!

**Comment by dovy** [comment]
Set your default to be ''.  ;)

**Comment by ThinkUpThemes** [comment]
That was too easy! Thanks!!!
