### ISSUE TITLE
Translation problem via a plugin

### ISSUE THREAD

**Issue by nicolas92** [reduxframework/redux-framework#2621]
Hello, I have created a plugin where I joined redux, but I can not translate the panel, all translations work except the panel, here is my code:

<pre>add_action( 'plugins_loaded', 'uw_core' );
function uw_core() {
	load_plugin_textdomain( 'kho', false, dirname( plugin_basename( __FILE__ ) ) . '/languages' );
}</pre>

Can you help me, thank you very much :)

**Comment by kprovance** [comment]
This has been asked and answered *multiple* times.  https://github.com/reduxframework/redux-framework/search?q=plugin+translation+&type=Issues&utf8=%E2%9C%93

**Comment by nicolas92** [comment]
Hello, I looked at various topics and the problem is not resolved, I can not translate options panel that I created.
I saw a solution to a theme but not for a plugin.

**Comment by AlexAlexandru** [comment]
What does this "panel" means?
``php
Redux::setSection( $opt_name, array(
        'title'  => __( 'Settings for comments', $domain ),
        'id'     => 'comments',
        'desc'   => __( 'Here you can customize the settings only for comments.For posts and pages go to Settings for Posts and Pages.', $domain ),
		));
``
You mean the title?Settings for comments you can't translate that?

**Comment by AlexAlexandru** [comment]
What does this "panel" means?
```php
Redux::setSection( $opt_name, array(
        'title'  => __( 'Settings for comments', $domain ),
        'id'     => 'comments',
        'desc'   => __( 'Here you can customize the settings only for comments.For posts and pages go to Settings for Posts and Pages.', $domain ),
		));
```
You mean the title?Settings for comments you can't translate that?
By the way use this code
```php
load_plugin_textdomain( 'kho', FALSE, basename(plugin_dir_path( __FILE__ )). '/languages' );
```

**Comment by nicolas92** [comment]
Hello @AlexAlexandru, yes, that's what I'd like to translate, with the code you gave me the translation is still not working.

**Comment by AlexAlexandru** [comment]
Strange for me it's working.I also use redux framework with a plugin.Is your plugin open source or on github to take a look at it?

**Comment by nicolas92** [comment]
Hi, there is a free version of the plugin: https://wordpress.org/plugins/ultimate-widgets-light/

**Comment by AlexAlexandru** [comment]
Does the translation work for anything else?

**Comment by nicolas92** [comment]
Translation works for all except the panel.

**Comment by AlexAlexandru** [comment]
For me is everything is in english

**Comment by nicolas92** [comment]
Yes but if you want to translate the plugin, for example in French, the translation of sentences of the panel does not.

**Comment by AlexAlexandru** [comment]
I found the issue

**Comment by nicolas92** [comment]
What's the problem?

**Comment by AlexAlexandru** [comment]
Refresh

**Comment by nicolas92** [comment]
Ah ok, I'll try :)

**Comment by nicolas92** [comment]
it works :)
Thank you very much, I would never have found it, thank you :)

**Comment by AlexAlexandru** [comment]
You welcome.

**Comment by aktarujjman** [comment]
@mma Thanks a lot
