### ISSUE TITLE
Is there a way to start an action only if section is saved and not every time anything is saved

### ISSUE THREAD

**Issue by nonamebaby** [reduxframework/redux-framework#2622]
Hello,
I'm using my options panel to automatically create / update a page filled with collected data.
Using the action hook `redux/options/{opt_name}/saved` the created page is updated everytime any option is saved.
Is there a hook like `redux/options/{opt_name}/{section_id}/saved` ? 
Or do you have another idea how to only update the generated page if the section with the page data is altered?

**Comment by kprovance** [comment]
Any available filters hooks/actions hook are listed here:

https://docs.reduxframework.com/core/advanced/filter-hooks/
https://docs.reduxframework.com/core/advanced/actions-hooks/

If something similar isn't listed, then we don't have it.
