### ISSUE TITLE
Size of Slider on tablet an smartphone

### ISSUE THREAD

**Issue by ruedelbert** [reduxframework/redux-framework#2623]
Hi,
my slider does not reduce the resolution in regard to the display width of the mobile device. I just see a part of the slider.

Is it my problem or is it a setting that i change change?

thanks

ruediger

**Comment by kprovance** [comment]
Could we start with a support URL please?  Absolutely no pertinent information was provided.

**Comment by ruedelbert** [comment]
http://filu2.blauequelle.de/bq-login
User: developer
passwort: fgbG56gFr!!we

**Comment by kprovance** [comment]
No, this: https://docs.reduxframework.com/core/generating-a-support-hash/

Going onto your server would fall under fee based support.  It's not a free service anymore.

**Comment by kprovance** [comment]
Closing due to lack of reply.
