### ISSUE TITLE
WSOD when activating framework plugin

### ISSUE THREAD

**Issue by stephangriesel** [reduxframework/redux-framework#2627]
See my previous issue closed. Here is the log I found when trying to activate the plugin:
Warning: file_get_contents(http://www.reduxframework.com/wp-content/uploads/redux/redux_notice.jason):failed to open stream: Connection timed out in /opt/lampp/htdocs/www/wordpress/wp-content/themes/domik/ReduxCore/inc/class.redux_filesystem.php on line 186

I am running WordPress Version 4.3.1

**Comment by kprovance** [comment]
LIne 186 is an isset statement.  I check your pat post, and no where did you mention what version of Redux you are using.  Chances are, it's outdated.  Please update (preferably from this repo).  Also, generally, timeout errors are a server config thing.  Change the timeout settings in your php.ini (if you don;t know what that means, contact whomever provides your web ghosting, since we do not support server configurations).

**Comment by stephangriesel** [comment]
From what I can see I was using 3.5.7. From what I can see the master also 3.5.7?

**Comment by kprovance** [comment]
mast is 3.5.7.9  (soon to be .10).  It's in the changelog.

**Comment by stephangriesel** [comment]
installed the latest version, updated php versions, set time outs and still getting wsod screen. contacted host now.

**Comment by kprovance** [comment]
Dovy believes it's because cURL is not installed.  Ask them about that.

**Comment by stephangriesel** [comment]
Yep cURL installed. See error message below when trying to activate plugin:

Fatal error: Cannot redeclare compiler_action() (previously declared in /home/skepstud/public_html/new/wp-content/plugins/redux-framework-master/sample/sample-config.php:2271) in /home/skepstud/public_html/new/wp-content/themes/domik/functions/admin-config.php on line 3026

**Comment by dovy** [comment]
Aha. So you need to change that function name in your code. Problem solved. You have the sample config running and you are running a copy of it. Easy fix.

**Comment by stephangriesel** [comment]
Ok? So what do I need to do? Delete old one?

**Comment by dovy** [comment]
...

Prefix all function names with a unique identifier so you don't clash with other authors. Standard programming mojo.  ;)

**Comment by stephangriesel** [comment]
Ok I have no idea how to do that, can you maybe give me steps?

**Comment by dovy** [comment]
@stephangriesel  I can't be your PHP tutor my friend... This is the last time i'll comment on this.

Change: `function compiler_action(` to `stephengriesel_compiler_action(`

**Comment by stephangriesel** [comment]
I don't expect you to be, I just want support on this plugin that is not working with the theme I bought

**Comment by dovy** [comment]
OOOHHH, if you had told us you were a user... Contact your theme author. They did something funky.

But the quick fix is to disable Redux Demo Mode from the plugin screen before you run the theme.

Then tell your author they need to change that function name.  ;)

**Comment by kprovance** [comment]
Ugh!

You bought a theme that used Redux, and came to US for support?  Sorry, no.  You need to go to the author of the theme, the guy you paid.  It's his responsibility to get you up and running.  Not ours.
