### ISSUE TITLE
Redux Warnings

### ISSUE THREAD

**Issue by PulsarMedia** [reduxframework/redux-framework#2628]
Hey Guys,

I am getting the following 2 warnings in WordPress:

Redux Framework Warning
select2-css CDN unavailable. Some controls may not render properly. Please wait a few minutes, then try refreshing the page. Unable to load some remotely hosted scripts..

Redux Framework Warning
select2-js CDN unavailable. Some controls may not render properly. Please wait a few minutes, then try refreshing the page. Unable to load some remotely hosted scripts.

Also, I am unable to edit any of my font settings and i am guessing its due to these errors.

Will the CDN be back up and running soon? or do i need to install the extension to get my fonts working again?

Thanks.

**Comment by kprovance** [comment]
It's not our CDN, don't know.  I can only assume you're using the latest version of Redux from this repo.  You didn't say.

**Comment by PulsarMedia** [comment]
Sorry, here are the version details:

WordPress version 4.3.1
Redux version 3.5.7

Is the 3.5.7 the latest version?

Thx.

**Comment by kprovance** [comment]
3.5.7.9 - but nothing regarding the CDN has changed.  If wp_remote_get  fails, that message appears.  Again, it's not our CDN.  I've been working all day on a Redux related project, and I've not seen that message.  If you're working local, you might check the connection, or if worse comes to worst, install the https://github.com/reduxframework/redux-vendor-support on your local.

**Comment by PulsarMedia** [comment]
ok this is strange...I am getting the errors on my live domains but not on my localhost environments.

Any ideas?

**Comment by kprovance** [comment]
Without going onto the server and debugging?  Nope.  None.  That's a premium support service now.  As I said, if wp_remote_get fails, that's the message.  So why would wp_remote_get fail on that server?  Look at your php error logs and see if it's a php config issue (if any),  Find out what the return value of wp_remote_get is (class.redux_cdn.php, line 61).  The answer is probably in the wp_error array.

**Comment by PulsarMedia** [comment]
ok, ill see what i can dig up.

Thanks.

**Comment by PulsarMedia** [comment]
Well not sure what happened but the errors are gone today...i guess it was just an isolated issue with my server.

Sorry to bother you guys about this.

**Comment by kprovance** [comment]
Okay?  Closing.  :)

**Comment by DavidRe9** [comment]
Can add this line on wp-config:

/**
*  The constant WP_ACCESSIBLE_HOSTS will allow additional hosts to go through for requests
*/
define('WP_ACCESSIBLE_HOSTS', 'cdn.jsdelivr.net,look.redux.io,');

**Comment by anggavaro** [comment]
nice
