### ISSUE TITLE
Compiler CSS properties

### ISSUE THREAD

**Issue by eugeneowp** [reduxframework/redux-framework#2630]
I have a theme currently using the Redux output function to apply custom styling. The problem I have is that there are a lot of colour related options which means a massive block of code is being added to the page head.

I am looking at using the compiler to add the dynamic styles to an external file instead but have run into a problem where it doesn't seem possible to use a single option value for multiple CSS properties across multiple CSS selectors in the way that is possible with the output argument.

For example, using output you can do the following to use one value for both the background and text colour of a combination of several selectors:

<pre>array(
	"id"           => "accent-color",
	"title"        => __( "Accent Colour" ),
	"type"       => "color",
	"default"	=> "#FF0000",
	"output"	=> array(
		"background-color"	=> ".element1, .element2",
		"color"			=> ".element3"
	)
)</pre>

However with the compiler you can only use the value for one CSS property across multiple selectors:
<pre>array(
	"id"            => "accent-color",
	"title"         => __( "Accent Colour" ),
	"type"        => "color",
	"default"	 => "#FF0000",
	"compiler" => array( ".element1", ".element2" ),
	"mode"      => "background-color"
	)
)</pre>

Am I right that the compiler doesn't have the same level of flexibility the output argument has or have I missed something?

**Comment by kprovance** [comment]
For the color field, output and compile share the same function as far as outputting goes.  However, you've provided no version information or sample compiler code, so, there isn't much else I can suggest.

**Comment by eugeneowp** [comment]
WordPress: 4.3.1
Redux:  3.5.7

I'm using the exact code from the compiler dynamic CSS documentation page (https://docs.reduxframework.com/core/advanced/updating-a-css-file-dynamically/)

<pre>add_filter( 'redux/options/' . $opt_name . '/compiler', 'compiler_action', 10, 3 );	
function compiler_action( $options, $css, $changed_values ) {

	global $wp_filesystem;
 
	$filename =  trailingslashit( get_template_directory() ) .'style-dynamic.css';
 
	if( empty( $wp_filesystem ) ) {
		require_once( ABSPATH .'/wp-admin/includes/file.php' );
		WP_Filesystem();
	}
 
	if( $wp_filesystem ) {
		$wp_filesystem->put_contents(
			$filename,
			$css,
			FS_CHMOD_FILE // predefined mode settings for WP files
		);
	}
		
}</pre>

Just to be clear I'm not reporting a bug. I'm asking about the functionality of the "compiler" and "mode" arguments and if it is possible to get it to behave the same way as the output argument.

When using the output argument the CSS property and selectors are in the same array so you can use the option value for more than one CSS property and multiple selectors:
<pre>"output" => array(
        "background-color"  => ".element1, .element2",
        "color"             => ".element3",
        border-color"       => ".element3, element4"
)</pre>

But this isn't the case when using the compiler as the selectors are added as an array in the compiler argument and the CSS property is added to the mode argument meaning it's not possible to mix and match in the same way.
<pre>"compiler" => array( ".element1", ".element2" ),
"mode"     => "background-color"</pre>

**Comment by kprovance** [comment]
First, to be clear, that sample code with the wp_filesystem was from our legacy config.  It's been known to fail on MANY a server, which is why we discontinued it (and yeah, I should take that down).  It's not meant for production and ther are other better ways to do the same thing.

Second, I understand what you are saying, but unless you tell me what the actual return value is in the compiler, or show me some code I can try, I'm not sure what exactly it is you want from me.  I don't have the time to create a new project from scratch just to test this.  I did look at the field_color.php and the routine for output and compiler are exact.  So then, what exactly is the compiler returning?

**Comment by eugeneowp** [comment]
Thanks for your time Kevin.

**Comment by jaschaio** [comment]
@eugeneowp Have you found a solution to this? I was wondering about the exact same thing.

@kprovance In your answer you mention that the sample code with the wp_filesystem was from your legacy config and that it's been known to fail on MANY servers. You mention that there are better ways to accomplish the same thing, but unfortunately you don't point us in the right direction. Whats the best way to accomplish this?
