### ISSUE TITLE
Specific IP address of the Server

### ISSUE THREAD

**Issue by ryangreg55** [reduxframework/redux-framework#2632]
Hi 

I am having major issues getting Redux Framework for Concept (CodePark Wordpress Theme) to install and activate on my site. 

My hosting provder has asked:

Please contact the plugin developer and ask them about the specific IP address of the plugin's server to which the connections should be allowed so that we could activate the plugin.

Can you specify this please :) 

Kind regards,
Ryan

**Comment by kprovance** [comment]
You'll need to contact the author of your theme for support.  We do not provide support for individual themes that use Redux.  That is up to the author, the guy you actually paid.  :)
