### ISSUE TITLE
Customizer extension  fails on some server (in core)

### ISSUE THREAD

**Issue by ThinkUpThemes** [reduxframework/redux-framework#2633]
The following line in the extension customizer results in a 404 error on some sites:

<pre>$this->_extension_url = site_url( str_replace( trailingslashit( str_replace( '\\', '/', ABSPATH ) ), '', $this->_extension_dir ) );</pre>

Would it be a problem to change this to:

<pre>$this->_extension_url = site_url( str_replace( trailingslashit( str_replace( '\\', '/', ABSPATH ) ), '/', $this->_extension_dir ) );</pre>

This seems to fix the 404 issue. Thanks in advance!

**Comment by kprovance** [comment]
I guess we'll find out.  Addressed in v.3.5.7.11
