### ISSUE TITLE
How to link entire google font family in the site?

### ISSUE THREAD

**Issue by cristianstan** [reduxframework/redux-framework#2634]
Hi,

How can I import a particular google font on my wordpress site using the Google Fonts Dropdown?
**Basically, in my site should echo the font in this manner: **

> link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600,600italic,700,700italic,800,800italic' rel='stylesheet' type='text/css'

**But currently it shows this way:**

> link rel='stylesheet'  href='http://fonts.googleapis.com/css?family=Roboto' type='text/css' media='all'

I achieve this using the **typography** type and display it on html using the **output**.

At this moment I can use only regular font when styling elements. But I want to have all the family available from 300(lighter), 400 to 800 (bold)

Anyone how to achieve this using redux?

Thanks

**Comment by kprovance** [comment]
Currently, our typography field does not support multiple font weights per field.
