### ISSUE TITLE
Metaboxes extension assumes non SSL urls.

### ISSUE THREAD

**Issue by anttiviljami** [reduxframework/redux-framework#2636]
Didn't know where to submit this patch, but found this in a commercial theme that has the metaboxes extension included.

From `extensions/metaboxes/extension_metaboxes.php`:
```
 117                 $this->base_url = 'http://' . $_SERVER["HTTP_HOST"] . $_SERVER["REQUEST_URI"];
 118                 $this->post_id  = $this->url_to_postid( 'http://' . $_SERVER["HTTP_HOST"] . $_SERVER["REQUEST_URI"] );
```

Patched by checking the scheme via the `is_ssl()` helper function:
```
117                 $this->base_url = ( is_ssl() ? 'https://' : 'http://' ) . $_SERVER["HTTP_HOST"] . $_SERVER["REQUEST_URI"];
118                 $this->post_id  = $this->url_to_postid( $this->base_url );
```

Cheers!

**Comment by ottok** [comment]
What was the name/url of this buggy theme?

**Comment by anttiviljami** [comment]
http://imagelesstheme.com/

**Comment by kprovance** [comment]
Okay, first, this issue has since been fixed.  Second, you need to take this up with the theme author (that is, encourage them to update).  Posting about it here won't accomplish much of anything.

**Comment by anttiviljami** [comment]
Thanks!

I had no way of knowing if this had been fixed or not. I'll let the theme author know about the update.

**Comment by taksu** [comment]
Hi, Thanks anttiviljami, theme is now updated with the fixed extension.
