### ISSUE TITLE
Color Picker Clear

### ISSUE THREAD

**Issue by inspiraaz** [reduxframework/redux-framework#2637]
Color picker clear button causes this error:

TypeError: ui is undefined  ... field_color.js line 59

field_color.js line 58
```javascript
clear: function( e, ui ) {
    $( this ).val( ui.color.toString() );
    redux_change( $( this ).parent().find( '.redux-color-init' ) );
}
```

wpColorPicker clear callback doesn't return any object and should be written like this

```javascript
clear: function() {
    $( this ).val( '' );
    redux_change( $( this ).parent().find( '.redux-color-init' ) );
}
```

**Comment by kprovance** [comment]
Submit a pull request.

**Comment by kprovance** [comment]
Or, I can just do it myself!  Addressed in v.3.5.7.11
