### ISSUE TITLE
Invalid security credential. Please reload the page and try again.

### ISSUE THREAD

**Issue by benoiit6** [reduxframework/redux-framework#2639]
Hi guys,

When i try to do something on the developer window, i have this message, every time ! 

"Invalid security credential. Please reload the page and try again."

Can you help me?
<img width="1080" alt="capture d ecran 2015-10-04 a 18 58 31" src="https://cloud.githubusercontent.com/assets/14965986/10269008/f23953f6-6ac9-11e5-8858-982d99d5095c.png">

**Comment by kprovance** [comment]
Without seeing a support URL, or knowing version information...my solitary guess is that you are using template files.  You need to update them.  Probably the header_stickybar.tpl.php, where the opt_name was added to the nonce for ajax save.

**Comment by m00s** [comment]
@benoiit6 I'm using the same theme and I have the same issue. Did you solve?

**Comment by kprovance** [comment]
Okay guys, this is obvious an issue with the theme's developer.  I thought you were a developer, not a theme user.  We do not support themes.  it is the theme author's responsibility, even if they are using Redux, to offer support to their users, not us.  You paid them, after all.  :)

Please contact the theme author for a fix.

**Comment by kmarshy** [comment]
Most probably, you have your redux framework on dev mode. Go to to the plugins page and disable it. That should solve it.

**Comment by kostasx** [comment]
What I did, was, clear the browser's cache and the message disappeared.

**Comment by vaibhav011286** [comment]
> Most probably, you have your redux framework on dev mode. Go to to the plugins page and disable it. That should solve it.

Thanks!!

**Comment by iamfortune** [comment]
> Most probably, you have your redux framework on dev mode. Go to to the plugins page and disable it. That should solve it.

did this work?????
i have the same issue with my wordpress website

**Comment by mcilva** [comment]
This happens if there is a conflict with page slug (More than 1 plugin or theme with the same page slug)

edit this worked for me

**'page_slug' => 'your-page-custom-slug'**

**Comment by dovy** [comment]
Nice find @mcilva   :)

P.S. Be sure to start using Redux 4 since Redux 3 has hit EOL. I'll merge the repos here shortly.

https://github.com/reduxframework/redux-framework-4
