### ISSUE TITLE
Issue on line 119 extensions.php

### ISSUE THREAD

**Issue by KaISBC** [reduxframework/redux-framework#2640]
I don't know why, I have this error:
Warning: Invalid argument supplied for foreach() in .../wp-content/plugins/redux-framework/ReduxCore/inc/welcome/views/extensions.php on line 119

Could someone give me an advice to try to fix please.

Best regards,

**Comment by kprovance** [comment]
Our website is down, and that's why the issue.  I'll have it corrected to exit when the site goes down, next push.
