### ISSUE TITLE
Issue with multi button_set

### ISSUE THREAD

**Issue by harunbasic** [reduxframework/redux-framework#2641]
The problem with the multi button_set field is that it saves duplicated values. 

For example the saved value with ajax save should be

<pre>
array(
  '0' => 'val1',
  '1' => 'val2'
)
</pre>

but instead the values are duplicated

<pre>
array(
  '0' => 'val1',
  '1' => 'val2',
  '2' => 'val1',
  '3' => 'val2'
)
</pre>

The reason is the input type checkbox. Maybe you should use javascript to add values to hidden input field just like for other checkboxes.

Because now the serialized string looks like this.

<pre>
redux_demo%5Bopt-button-set-multi%5D%5B%5D=1&redux_demo%5Bopt-button-set-multi%5D%5B%5D=3&redux_demo[opt-button-set-multi][]=1&redux_demo[opt-button-set-multi][]=0&redux_demo[opt-button-set-multi][]=3
</pre>

It has the serialized values for multi button_set but at the end there is also an array of those values and that is the reason why there are duplicated values.

**Comment by kprovance** [comment]
If you want to take a stab at it, go for it.  Again, it's time thing for me, in that I don't have much to spare at this point.

**Comment by harunbasic** [comment]
Ok. I will fix it in the next few days.

**Comment by maheshwaghmare** [comment]
I have same issue with `button_set`. Hope It'll fix in next release.

**Comment by kprovance** [comment]
Again, it's a time/cost thing for me right now.  You're free to take a stab at it and submit a pull request.  It is a community project after all.  :)

**Comment by kprovance** [comment]
Fixed in v.3.6.3.1.  Also, because of the way this fix was addressed, it is recommended you check any option using this field with empty() or is_array() for any foreach() call.  Now, only selected options will be saved to the database, which necessitaes the use of foreach() to access the data.  Accessing it via array indexes is no longer a reliable way to retrieve the data.
