### ISSUE TITLE
Using settings API based option!

### ISSUE THREAD

**Issue by hamdan-mahran** [reduxframework/redux-framework#2642]
Hi
Do this article https://ideas.reduxframework.com/campaigns/complete-customizer-integration/ means that i can't use Redux options API with my themeforest themes any more? 
i understand that from the article :( maybe because my English is so weak?

Thanks!

**Comment by kprovance** [comment]
No.  It means that themes submitted to wp.org may no longer use the options panel.  TF is fine.

**Comment by hamdan-mahran** [comment]
Thank you very much @kprovance
