### ISSUE TITLE
Translations?

### ISSUE THREAD

**Issue by PulsarMedia** [reduxframework/redux-framework#2643]
Hey Guys,

How do i go about adding translations for Redux fields? I need to translate a few slide fields and i am using WPML but it seems WPML does detect the strings that need to be translated.

If there is online documentation for this please point me in the right direction.

Thanks.

**Comment by kprovance** [comment]
Our docs site has a search feature.  https://docs.reduxframework.com/?s=wpml

**Comment by PulsarMedia** [comment]
Thanks Kevin, i got it working.

Cheers.
