### ISSUE TITLE
CSS Compiler don't write on file, but php log doesn't display errors

### ISSUE THREAD

**Issue by antoniomangiacapra** [reduxframework/redux-framework#2644]
Hello,
I developed a Wordpress theme embending Redux Framework, I used a it for a log time without problems, now I noticed that all css modification are not writed in css file, but php log doesn't report permissions erros. 'Output' instead work well.
I am using Wordpress 4.3.1 and Redux 3.5.7.2.

Please may you advice me what I could check about this issue? Thank you a lot.

**Comment by kprovance** [comment]
That probably has something to do with how Wordpress was installed, and permissions issues.  Unfortunately, it is beyond the scope of the support we offer for Redux, since it's not a Redux feature.  If you search our issue tracker, I believe it's been discussed and semi-answered.

**Comment by antoniomangiacapra** [comment]
Thank you kprovance, I found solution. I write so that it could help someone else:

After a themeforest review I replaced all dirname(__FILE__) with get_template_directory_uri() and for a mistake I replaced this also in compiler_action(). So it was a path issue.

I am sorry if I asked here before check enough and thank you for this awesome framework. I'll pay you  with a donation as soon as I'll gain enough with my theme :)

**Comment by itsabhik** [comment]
@antoniomangiacapra can you please share your code which you are using to generate dynamic css?
I am having almost the same issue except I can't figure out the compiler filter that runs in latest versions.

TIA

**Comment by antoniomangiacapra** [comment]
Hi @itsabhik, this is my code ;)

<pre>
function compiler_action( $options, $css, $changed_values ) {

                $filename = dirname(__FILE__) . '/../../css/theme-options' . '.css';

                global $wp_filesystem;
                
                if( empty( $wp_filesystem ) ) {
                    require_once( ABSPATH .'/wp-admin/includes/file.php' );
                    WP_Filesystem();
                }

                if( $wp_filesystem ) {
                    $wp_filesystem->put_contents(
                        $filename,
                        $css,
                        FS_CHMOD_FILE // predefined mode settings for WP files
                    );
                }
             
            }
</pre>

**Comment by itsabhik** [comment]
Thanks mate!! That really helps.
