### ISSUE TITLE
Prevent option to be saved (or be able to reset it right after save)

### ISSUE THREAD

**Issue by ckissi** [reduxframework/redux-framework#2645]
I'm using checkbox field for resetting data in one of my DB tables.
I'm using this hook:

    add_action('redux/options/'.$args['opt_name'].'/saved','redux_save_action', 10, 3);

It works ok. So after "Save" I make required DB changes inside the "redux_save_action" function.

And now the issue comes in. I need to reset this checkbox field right after the Save (make it unchecked). 

I was able to do it with this function:  

    Redux::setOption($opt_name,'db-reset',false) 

inside the  redux_save_action function I mentioned earlier.

Unfortunately to make this change visible I have to reload the page first. The issue here is that the Save function uses AJAX to save data and I'm unable to view the checkbox unchecked until I reload the page.

Any idea how to solve this ?

**Comment by kprovance** [comment]
The only thing you can do, really, is to add the 'ajax_save' => false argument to the checkbox field.  This will force a page reload when that checkbox is changed and the page saved.
