### ISSUE TITLE
last_tab argument doesn't work

### ISSUE THREAD

**Issue by ckissi** [reduxframework/redux-framework#2646]
I want to open options panel on tab 1 every time so I set last_tab argument to 1, unfortunately every time I open settings it shows me the last opened tab. 

I checked cookies and there is a "redux_current_tab" cookie set to the last opened tab. I always uses that cookie to set tab and ignores the "last_tab" argument completely.

**Comment by kprovance** [comment]
That cookie setting is correct.  It has nothing to do with the feature in question.  However, you;ve not included any penitent information, which is required.  We'll need one of these to continue:  https://docs.reduxframework.com/core/generating-a-support-hash/

**Comment by ckissi** [comment]
ok, here is the hash url: http://support.redux.io/?id=b0wATTLsreBkIReloah1Oq0ewlEgDS5afD7g8fK4MAPmPXfoLGIn0eIiVF5%2BWIJ4IydwMurMjWU48gw7AaDxVQ%3D%3D

**Comment by kprovance** [comment]
You're last_tab argument is set to blank in the config provided.  Before I spend half my day tearing into this, could you please set it to something other than blank and try again?

**Comment by ckissi** [comment]
Thats strange. My config of arguments at the time of hash generation looked like this:

    $args = array(
    'opt_name' => 'wp_optin_bar',
    'use_cdn' => TRUE,
    'display_name' => 'WP Opt-in Bar',
    'display_version' => FALSE,
    'disable_tracking' => true,
    'dev_mode' => FALSE,
    'forced_dev_mode_off' => FALSE,
    'page_title' => 'WP Opt-in Bar Options',
    'update_notice' => TRUE,
    'intro_text' => '',
    'footer_text' => '',
    'admin_bar' => TRUE,
    'menu_type' => 'submenu',
    'menu_title' => 'Settings',
    'allow_sub_menu' => TRUE,
    'page_parent' => 'wp-optin-bar-main',
    'page_parent_post_type' => 'your_post_type',
    'page_slug' => 'wp_optin_bar',
    'customizer' => TRUE,
    'default_mark' => '*',
    'hints' => array(
        'icon_position' => 'right',
        'icon_color' => 'lightgray',
        'icon_size' => 'normal',
        'tip_style' => array(
            'color' => 'light',
        ),
        'tip_position' => array(
            'my' => 'top left',
            'at' => 'bottom right',
        ),
        'tip_effect' => array(
            'show' => array(
                'duration' => '500',
                'event' => 'mouseover',
            ),
            'hide' => array(
                'duration' => '500',
                'event' => 'mouseleave unfocus',
            ),
        ),
    ),
    'output' => TRUE,
    'output_tag' => TRUE,
    'settings_api' => TRUE,
    'cdn_check_time' => '1440',
    'compiler' => TRUE,
    'page_permissions' => 'manage_options',
    'save_defaults' => TRUE,
    'show_import_export' => TRUE,
    'database' => 'options',
    'transient_time' => '3600',
    'last_tab' => 7,
    'network_sites' => TRUE,
    ); 

I didn't change that section for several hours now.

**Comment by kprovance** [comment]
Fixed with v.3.5.7.12.
