### ISSUE TITLE
Compiler hook for new config file?

### ISSUE THREAD

**Issue by itsabhik** [reduxframework/redux-framework#2647]
Hi,
Redux Version: 3.5.7
WordPress Version: 4.3.1
Dev Mode: True
Redux is embedded, as well as required using TGM

In previous versions, I used this compiler hook to dynamically generate CSS file,

```php
add_filter('redux/options/'.$this->args['opt_name'].'/compiler', array( $this, 'generate_css' ), 10, 3);
```
However, since the new versions out with newly formatted config file, this no more works. I tried to find the proper hook in docs with no luck. I tried hardcode the option name in hook, but that failed.

```php
add_filter('redux/options/mytheme_options/compiler', 'generate_css', 10, 3);
```
Nothing.. What could be the reason?

Here is the complete code I am using for the new config file:

```php
array(
				'id'       => 'nav-color-hover-bg',
				'type'     => 'color',
				'desc'	   => __( 'Menu Link Background Color (Hover/Active)', 'protons' ),
				'default'  => '#8224e3',
				'validate' => 'color',
				'compiler'    => array( 
								'color' => '.navbar-fixed-top #menu-primary li > a',
								'background-color' => '#menu-primary li.active > a, #menu-primary li.open > a, #menu-primary li > a:hover',
								),
				'transparent'	=> false,
			),


function generate_compiler_css( $options, $css, $changed_values ) {
	$url = 'themes.php?page=mytheme-options';
	if (false === ($creds = request_filesystem_credentials($url, '', false, false, null) ) ) {
		return; // stop processing here
	}
	if ( ! WP_Filesystem($creds) ) {
	request_filesystem_credentials($url, '', true, false, null);
	return;
	}
	global $wp_filesystem;
	
	$file = get_template_directory() . '/lib/css/dynamic.css';
	
	$wp_filesystem->put_contents(
		$file,
		$css,
		FS_CHMOD_FILE
	);
	
//print_r ($options);
// print_r ($css);
//print_r ($changed_values);
}
add_filter('redux/options/mytheme-options/compiler', 'generate_compiler_css', 10, 3);
```

**Comment by kprovance** [comment]
It work, I use it in my own theme.  However, I do not put the action hook in the config file.  It has it's own separate PHP file.  I don;t know if that makes a difference.  It should not.

```php
add_filter('redux/options/my_opt_name/compiler', 'redux_compiler', 10, 3);

function redux_compiler() {
    ....
}
```

If this is about the file writing routine, we no longer support that, and why it was removed from the sample config.  If the issue is there, it's a premium support issue.

**Comment by itsabhik** [comment]
Hello @kprovance 
Can you please share some more code? I mean, I can see that you are not passing any accepted arguments, then how you are getting the option values? Sorry, I am bit confused here, I know my code *should* work, but somehow not writing to the file. And, no PHP errors or warnings whatsoever. Can't even debug whether the filter is triggering or not.

**Comment by kprovance** [comment]
There's not much more code I can give.  That's the compiler setup.  If it's not working, there must be something in your code or load order that is off.  That's a premium service, for me to look at it.  It;s no longer a free service.

**Comment by itsabhik** [comment]
Gotcha!!
