### ISSUE TITLE
Get image gallery caption

### ISSUE THREAD

**Issue by rafamem** [reduxframework/redux-framework#2648]
Hi! I need to get the caption of all images that I upload in the gallery: https://docs.reduxframework.com/core/fields/gallery/

But, this code returns me [caption] => (empty)

```php

<?php 
$attachmentIds = explode(',', $redux_demo['opt-gallery']);
    foreach($attachmentIds as $attachmentId): 
        $metaAttachment = wp_get_attachment_metadata( $attachmentId );
        echo '<pre>';
        print_r( $metaAttachment );
        echo '</pre>';
?>

```

![image_meta](https://cloud.githubusercontent.com/assets/4790387/10412172/778a9d8e-6f53-11e5-8f50-d1b9177fb854.png)

**Comment by kprovance** [comment]
Unfortunately, this is not a Redux issue and would fall under premium support, should you want us to determine why a WordPress API is not working for you.  Sorry, but we don;t have time to devote to every single PHP or WP issue that comes our way.
