### ISSUE TITLE
redux_notice.json failed

### ISSUE THREAD

**Issue by sodbileg** [reduxframework/redux-framework#2649]
I am getting the error below. Using Redux v3.5.7 as a plugin.

Warning: file_get_contents(http://www.reduxframework.com/wp-content/uploads/redux/redux_notice.json): failed to open stream: HTTP request failed! HTTP/1.0 500 Internal Server Error

**Comment by kprovance** [comment]
Internal server error typically means something is wrong with the server, incorrect settings, etc.  We don't debug those kinds of things for free anymore.

**Comment by sodbileg** [comment]
The point is that this json file is actually on **https:**//reduxframework.com/wp-content/uploads/redux/redux_notice.json not **http:**//www.reduxframework.com/wp-content/uploads/redux/redux_notice.json

**Comment by kprovance** [comment]
Both URL's work for me.  Not sure what to tell you.
