### ISSUE TITLE
Not all the options are saved on some servers

### ISSUE THREAD

**Issue by guzun** [reduxframework/redux-framework#2651]
Hi there.

I've just encountered a very strange issue for the second time.
A theme that uses the Redux Framework and has many options, on some servers it is not able to save all the options.
It saves for example the first 40 options and then the 41st and the other which follow are not saved any more. 
And that happened only on 2 servers.
I'm curious if this is a known problem, and if there is a way to fix that. Or if it may be related to the server settings, what is necessary to be changed in order to solve the issue.

Also the options which are not saved via the options panel can be saved via the customizer if it is enabled for the customizer as well.

Any hints on how this may be fixed is appreciated.

Thank you,
Alex

**Comment by kprovance** [comment]
Are you a theme's author, or a user of the theme?

**Comment by guzun** [comment]
I have to support it now.
But it wasn't me who developed it.

**Comment by kprovance** [comment]
Such a thing happens if the max_input_vars exceeds 1000.  You could change it on your server, but it would still affect your users.  We're semi-working on something to fix that, but it's still a ways off.  The only other thing you could do is redesign the options panel to not use so many input variables.

**Comment by guzun** [comment]
Thank you for the quick tip.
Will try to increase the max_input_vars on the client side.
Though on several test servers max_input_vars is set to 1000 (same value as on the user's site which has the issue) and it works fine, but on the user'r site it does not. 

Any way, I appreciate your help.

Cheers,
Alex

**Comment by kprovance** [comment]
Yeah, I just said that in so many words.  It's a design consideration at this point.  Like I said, we're working on a fix, but it requires some rewriting of core code, and with the community decidedly not supporting the project, it's one of those 'we'll get to it when time permits' things.

**Comment by guzun** [comment]
Thanks Kevin.

You can close this issue.

Have a nice day!
