### ISSUE TITLE
Notice error on after 3.5.8 update

### ISSUE THREAD

**Issue by dinolatoga** [reduxframework/redux-framework#2652]
`Notice: load_plugin_textdomain was called with an argument that is deprecated since version 2.7 with no alternative available. in ../wp-includes/functions.php on line 3572`

**Comment by kprovance** [comment]
I'm not seeing this.  Could you explain what you did to produce the message?  Also, please provide a support URL.

**Comment by dinolatoga** [comment]
The plugin was working normally before I upgraded it. This only appeared after i updated the plugin via WP update.

I'll try to do a clean test, without the other plugins and just using the default theme to see if I can reproduce it.

**Comment by dinolatoga** [comment]
Update: It's there alright. I've installed a fresh copy of Redux Framework on a fresh WP install. The Notice Error started appearing after I activated the Demo Mode. So it must have something to do with the demo theme config.

More Info: I'm using VVV for my local development server.

**Comment by kprovance** [comment]
Oh, I see.  I had to load the plugin to make it bark.  An empty param is missing from that API.  <sigh>  I'm on it.

**Comment by kprovance** [comment]
Fixed in v.3.5.8.1.  I'll see if we can get that pushed to wp.org this evening.  It's a fairly serious issue.  Thanks!

**Comment by dinolatoga** [comment]
That was fast. Thanks!

**Comment by dovy** [comment]
Pushed to WP.org. My bad.
