### ISSUE TITLE
Builder doesn't work

### ISSUE THREAD

**Issue by ckissi** [reduxframework/redux-framework#2653]
When I tried to build redux files with embedded redux it doesn't generate the archive with included redux core files. redux-framework directory contrains only directories "inc" and "templates"

**Comment by ckissi** [comment]
Now I'm completely unable to generate files. Seems something is broken.

**Comment by kprovance** [comment]
I'll get to it when I can.  Projects that generate income come first.

**Comment by ckissi** [comment]
Makes sense

**Comment by kprovance** [comment]
Builder has been fixed.
