### ISSUE TITLE
Redux System Status Report

### ISSUE THREAD

**Issue by Basilakis** [reduxframework/redux-framework#2654]
Hello,

Could someone help out, how we can generate the following:
https://docs.reduxframework.com/core/support/understanding-the-redux-framework-system-status-report/

I can nod find a related string or something.

Thank u

**Comment by kprovance** [comment]
Tools > Redux Framework > Status Tab.

**Comment by Basilakis** [comment]
Thanks a lot :-)

How can I activate those backs, maybe through function, if theme author has disabled them? 

Thank u once again :)

**Comment by kprovance** [comment]
You'll have to get with the theme author on that one.  He/she should not have been disabling it in the first place.
