### ISSUE TITLE
can not save change

### ISSUE THREAD

**Issue by ngocson2306** [reduxframework/redux-framework#2656]
I can not save change. when i add this content for content field:

<script type="text/javascript" src="https://cdn-fluct.sh.adingo.jp/f.js?G=1000034104"></script>

<script type="text/javascript">
//<![CDATA[
if(typeof(adingoFluct)!="undefined") adingoFluct.showAd('1000052937');
//]]>
</script>
it' popup: 
There was a problem with your action. Please try again or reload the page.

**Comment by kprovance** [comment]
What content?  What versions, of anything?  What field code?  Please provide a support URL.  ALso, are you a developer or the user of a theme that uses redux?

**Comment by kprovance** [comment]
No reply after two days.  Closing.
