### ISSUE TITLE
Dashicons Missing With Repeater Extension

### ISSUE THREAD

**Issue by coleh33** [reduxframework/redux-framework#2657]
Can anyone else confirm that when they have the repeater extension enabled that the Wordpress dashicons disappear only on the Redux Options page?

I noticed that on all other admin pages Wordpress makes a call in the head section to a bunch of standard css files and usually includes dashicons right at the beginning but when loading my custom theme options page the dashicons is missing from the Wordpress core call.

When removing the repeater extension API call, they come back and work.

If someone else can confirm if they are seeing this issue or not, that would be awesome!

Thank You for the plugin and extension!

**Comment by kprovance** [comment]
Please file all issues pertaining to extensions on the extensions issue tracker.  Thanks!  This one is specifically for Redux.
