### ISSUE TITLE
Stuck on Loading Page

### ISSUE THREAD

**Issue by SquincyWeb** [reduxframework/redux-framework#2658]
Hi, 

When I navigate to my domain, it is stuck on the 'Loading' page and it doesn't navigate to the
home page. 

I suspect this is after we update to Redux framework version 3.5.8.1

Redux framework Version 3.5.8.1
Redux Developer Mode Disabler Version 1.0.1 
Contact Form 7 Version 4.3 
WordPress 4.2.5

Thanks

**Comment by kprovance** [comment]
<blockquote>
Redux Developer Mode Disabler Version 1.0.1 
</blockquote>

Yeah, not sure what that is, but it sounds like your deliberately shutting off our ad network.  We do not support people who do that.  Even so, you've not given any real reason why you think Redux is the issue.

**Comment by SquincyWeb** [comment]
Hi, 

Sorry, we didn't know it would shut off your ad network as the plugin says 'This plugin globally disables developer mode for all Redux instances.' - We assumed disabling developer mode to prevent any unexpected changes from user. 

We have no disabled the plugin however it still stuck on the 'Loading' page. 

Do you have any clue? Your support is kindly appreciated as we still have 5 months support remaining with your template. 

Thanks

**Comment by SquincyWeb** [comment]
Hi,
We have solved it. 

We upgraded to WordPress 4.3.1, and it looks like the theme with Redux framework Version 3.5.8.1 works better with  WordPress 4.3.1 compare to WordPress 4.2.5.

Thanks.

**Comment by kprovance** [comment]
You are a user of the theme?  You need to contact the theme author.  They provide you support, not us, as it's them you are paying, and not us.  Sorry.

**Comment by SquincyWeb** [comment]
I am apologize, but the support link on the theme linked us to here. 
We assumed you and the theme owner are the same group. 

Apologize for any inconvenienced caused.

**Comment by kprovance** [comment]
What theme?  I need to have a chat with the author about that.
