### ISSUE TITLE
Teacher Page and Footer setup

### ISSUE THREAD

**Issue by shardalal** [reduxframework/redux-framework#2662]
Hi There,

I was wondering, I installed the theme but i didn't get any teacher posts/pages available.

also, I was wondering how I can add Facebook/Twitter etc... boxes in the footer? where is the place to put the code? or the widgets?

Thanks, and sorry for the silly question,

Sharbel

**Comment by kprovance** [comment]
You need to direct this question to the actual author of the theme.  We did not author the theme, we did not receive any compensation for the sale of that theme, therefore we offer no theme support.  Redux is a tool the theme author used to create their work.
