### ISSUE TITLE
Fatal error during the activation

### ISSUE THREAD

**Issue by rodrigoleaobr** [reduxframework/redux-framework#2663]
Hi

I'm using the MedicalPress theme, and when I'll activate the Redux Frameword, I receive this message:

Warning: require_once(C:\Inetpub\vhosts\orallumen.com.br\httpdocs\wp-content\plugins\redux-framework\ReduxCore/inc/lib.redux_instances.php) [function.require-once]: failed to open stream: No such file or directory in C:\Inetpub\vhosts\orallumen.com.br\httpdocs\wp-content\plugins\redux-framework\ReduxCore\framework.php on line 36

Fatal error: require_once() [function.require]: Failed opening required 'C:\Inetpub\vhosts\orallumen.com.br\httpdocs\wp-content\plugins\redux-framework\ReduxCore/inc/lib.redux_instances.php' (include_path='.;./includes;./pear') in C:\Inetpub\vhosts\orallumen.com.br\httpdocs\wp-content\plugins\redux-framework\ReduxCore\framework.php on line 36

Can you help me to fix it?

**Comment by kprovance** [comment]
Please contact the author of MedicalPress for support with their theme.  We do not support theme's that use our framework.  That is the responsibility of the theme author, as you paid them, and not us.  They may have an incomplete copy of Redux and need to update.
