### ISSUE TITLE
The Text Color Button hidden in the Editor

### ISSUE THREAD

**Issue by safiro** [reduxframework/redux-framework#2664]
My code:

 array(
                'id'      => 'my-editor',
                'type'    => 'editor',
                'title'   => __( 'Editor', 'mytheme' ),
                'args'    => array(
                    'wpautop'       => false,
                    'media_buttons' => false,
                    'textarea_rows' => 5,
                    'teeny'         => false,
                    'quicktags'     => false,
                )
            ),

**Comment by kprovance** [comment]
This isn't enough to work with.  Please provide a support URL.

**Comment by kprovance** [comment]
I ran your code, and the button appears:

![editor](https://github-cloud.s3.amazonaws.com/assets/3412363/10565635/926e4320-75a3-11e5-9ebd-42e553e32041.png)

Make sure you have the "Toggle Toolbar' button selected (first highlight).

**Comment by safiro** [comment]
This is my editor Screenshot : 
I updated my browsers "Firefox , Opera, Chrome" to latest version but I still can't find the text color button.
![editor-screenshot](https://github-cloud.s3.amazonaws.com/assets/13925876/10565684/33c77bdc-75d7-11e5-8fb3-b44d004e6791.png)

**Comment by kprovance** [comment]
It's working on my end, so I'm not sure what to tell you.  No support information was given.
