### ISSUE TITLE
Stray dir in 'extensions' causes fatal error

### ISSUE THREAD

**Issue by dougcassidy** [reduxframework/redux-framework#2665]
Hi, guys.

in ReduxCore/framework.php: line 2845...
`                    if ( $class_file ) {
                        if ( file_exists( $class_file ) ) {
                            require_once( $class_file );
                        }
                        $this->extensions[ $folder ] = new $extension_class( $this );
                    }
`
if there is an empty dir (or one that doesnt contain 'extension_{$folder}.php' ) in the /extensions dir, there will be a fatal error.  I think, probably that you could simply move the instantiation into the   if ( file_exists( $class_file ) )  block.

**Comment by kprovance** [comment]
Why are there empty or other dirs in that folder, one must wonder.

**Comment by kprovance** [comment]
Fixed in v.3.5.8.2
