### ISSUE TITLE
No head picture in posts

### ISSUE THREAD

**Issue by bartmelis** [reduxframework/redux-framework#2669]
Hello, I bought the journey theme and it's great.

I do have a small problem. There is no big picture visible when reading the post (picture above the title). Does anyone know how to resolve this problem. In the beginning it dit work correct.

www.vetexbart.be

![image](https://cloud.githubusercontent.com/assets/15210901/10603272/67c7146e-771d-11e5-81c5-7507cfd5ff8f.png)

**Comment by kprovance** [comment]
For the millionth time, WE DO NOT SUPPORT THEMES!  You need to contact the theme author and ask THEM for support, since it is THEM you paid.  Redux is a tool your theme author used, and not some kind of support service!!

**Comment by bartmelis** [comment]
OK, CHANGE THE DAMN 'SUPPORT' BUTTON.

[image: Inline afbeelding 1]

2015-10-20 13:44 GMT+02:00 Kevin Provance <notifications@github.com>:

> Closed #2669
> <https://github.com/reduxframework/redux-framework/issues/2669>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/reduxframework/redux-framework/issues/2669#event-440227822>
> .
>



-- 
Regards,
Bart Melis





*Weversberg 15  2450 Meerhout, Belgium mobile: (+32) 470/43.82.53*



*skype: bart-melisfacebook: /bmelis*P   * please consider the environment
before printing this*

**Comment by kprovance** [comment]
Okay, I can't see your image, and 2, if your theme author isn't bright enough to change the default settings to his own, then he has no business writing theme..  Cheers.

**Comment by dovy** [comment]
Boys, boys. Sheesh, hah.

@bartmelis we're sorry that you are frustrated by us. We provide a sample config so people understand how the use our framework and for some reason they leave our "sample" information when they release a theme. Hence why you were directed to us.

Please do know that we're sorry you're having issues, but this happens all too often. It's frustrating and @kprovance was voicing that a bit too much.

All the best and I hope you're able to solve your issue with your theme author. Good luck!
