### ISSUE TITLE
Custom WPML solution, thoughts?

### ISSUE THREAD

**Issue by MrHunter** [reduxframework/redux-framework#2670]
No issue here but I just had a question with Redux and WPML and was wondering if you guys foresee any sort of issues with this idea.

So instead of using the wpml-config.xml would it be safe to have the opt_name change depending on the language they are using? Then the user would be able to change the admin language and set the new settings for each language rather then using WPML's string translation to translate a few of the texts (and even allow the user to have completely different options for each language).

Do you see any sort of issues that may arise from the options using this method?

**Comment by dovy** [comment]
Not really per say. A lot of theme authors do that. You'll just have to make sure you pre-populate empty ones with that data. Only concern is if they changed their panel, and now you've switched languages, it may throw off all your design options.

Another solution is to do a hook on language, and only save for that filter the value of the fields that use languages you want to translate, and use the master "opt_name" for the rest of the data. You'll just have to do your own pull and use the Redux data hooks to update the data properly.  :)

**Comment by MrHunter** [comment]
Hey Dovy,

I went ahead and got the language based options working for the most part, only thing is when the option name seems to change the output from my custom extensions ceases to show, I even tried commenting out the existing code in the render method and replaced it with static text...

Any reason off the top of your head as why this would be happening?
