### ISSUE TITLE
Google fonts not listing

### ISSUE THREAD

**Issue by Mediavuk** [reduxframework/redux-framework#2671]
Redux version: 3.5.8
Wordpress version 4.3.1
dev_mode false
embedded in theme
no javascript errors

So, this code does not give me drop-down list of google fonts, just empty space bellow 'Font Family'
 Redux::setSection( $opt_name, array(
        'title'      => __( 'Font settings', 'redux-framework-demo'),
        'subsection' => true,
        'fields'     => array(
          array(
            'id' => 'bla',
            'type' => 'typography',
            'title' => __('Title Area', 'mediathumper-settings') ,
            'google' => true,
            'font-backup' => true,
            'font-family' => true,
            'compiler' => array(
                'body'
            ) ,
            'units' => 'px',
            'color' => false,
            'default' => array(
                'font-weight' => '400',
                'font-family' => 'Ubuntu Condensed',
                'google' => true,
                'font-size' => '18px',
                'line-height' => '21px',
                'text-align' => 'left'
            ),
            'preview' => array(
                'text' => '1234567890ABCDEFGHIJKLMNOPQRZTUVWXYZabcdefghigklmnopqrstuvwxyz',
                'font-size' => '24px',
                'always_display' => true
                )
        ) ,
          
        )
    ) );

API key is added, what`s interesting is that only way to make fonts work is to add this line :
Redux::setSection( 'blahblahblah', array(
) );
So anything but $opt_name in ^^ line will make google fonts work. 
What am i missing ?

**Comment by dovy** [comment]
You don't need to add an API key and yes, the first string is the opt_name and it is required.

**Comment by Mediavuk** [comment]
I don`t understand why this topic is closed when no useful help is provided. I know that opt_name is required, and it is provided in the function, but still, only way to make google fonts appear is to add new section with wrong opt_name. I`m developing a theme so solution like that is not an option.

**Comment by kprovance** [comment]
I tried your code, substituting the $opt_name variable with the one I use in my theme, and it works.  This means there is a problem someplace in your config, and not necessarily with Redux itself.  Since that information was not provided to us, there isn't much else we can do, except to suggest you continue to debug your config on your own.  Start by ensuring that $opt_name is what it should be (echo or print_r is helpful) and that it matches your config.  Also, ensure your opt_name is unique.
