### ISSUE TITLE
issue with WP_CLI wp_redirect() inc/welcome/welcome.php

### ISSUE THREAD

**Issue by dimitrilongo** [reduxframework/redux-framework#2673]
hi

I use wp_cli in shell script for dev environment. WP_CLI send a warning msg when trying to activate a theme with REDUX embed and activate a plugin just after
Warning: Some code is trying to do a URL redirect. Backtrace: etc....

I have modified that function in welcome.php, and now all my wp_cli scripts are fine

    public function do_redirect() {

	        if ( !defined('WP_CLI') && WP_CLI ) {
				wp_redirect( admin_url( 'tools.php?page=redux-about' ) );
				exit();
			}
            
        }

Just take a look, if you want to 

Regards
Dimitri

**Comment by kprovance** [comment]
Added to latest push.  Kudos!
