### ISSUE TITLE
Edit existing options panel based on Redux

### ISSUE THREAD

**Issue by WallyJ** [reduxframework/redux-framework#2674]
Can someone point me in the right direction on how to edit an existing options panel on an already existing theme? Thanks.

**Comment by kprovance** [comment]
You need to contact the theme author.

**Comment by WallyJ** [comment]
Why, if it was built using Redux? I already have their permission to edit the theme however I want. I just need the technical steps now for Redux.

**Comment by kprovance** [comment]
I am assuming you skipped over our contributing guidelines.  Please review them:  https://github.com/reduxframework/redux-framework/blob/master/CONTRIBUTING.md.

**Comment by WallyJ** [comment]
I'm assuming you missed the reduxframework.com homepage that said "If you've discovered a bug, have a feature request, or generally just want to say 'Hi', feel free to post an issue or contact us! We won't bite, we promise!".

This probably fits into "just say hi"-ish. I think an answer that would have been easy for you to write, and would be helpful might sound like;
"Hey, you need to be in developer mode to make any changes to the redux functionality. You'll want to check out reduxframework.com/linktosomedocumentationsectionhere." That should get you started. This board is mainly for advanced questions, bug reports, etc. Thanks"....

I didn't say "The theme I bought is broken... please fix it." I understand that's not what this forum is for. However, I figured there would be experts here who could give me a simple nudge in the right direction, rather than a roadblock.

**Comment by kprovance** [comment]
We have an extensive docs site, with examples:  https://docs.reduxframework.com.  The Redux package comes with extensive sample code, duplicated on the demo page:  http://demo.redux.io/.  If you understand PHP, these things should be ample to get you started.  You are not reporting a bug, or an actual issue.  I'm sorry if you feel slighted, but if you want actual custom code, you'll have to pay for our time.  As much as I would like to give my time away for everyone who wants it, it doesn;t feed my family or pay my bills.  Supply and demand.

**Comment by WallyJ** [comment]
Simple answer needed. Objective, sour response given. Be helpful, or go join reddit to be the post nazi police.

**Comment by kprovance** [comment]
Okay, uncalled for and not very civilized.  I am locking this thread.
