### ISSUE TITLE
How to create a sortable element?

### ISSUE THREAD

**Issue by cawa-93** [reduxframework/redux-framework#2676]
How to create a sortable element (such as slides), but in the inside were 2 text fields and 1 checkbox?

**Comment by kprovance** [comment]
You'd have to author your own, either by overloading the field, or  by writing your own extension.  

More info here:  https://docs.reduxframework.com/core/advanced/add-a-custom-field/

Please be aware, we provide the tools, but you have to write your own code, which means a solid understanding of PHP and Javascript.
