### ISSUE TITLE
Redux ReferenceError: tinymce is not defined

### ISSUE THREAD

**Issue by seventhqueen** [reduxframework/redux-framework#2677]
Hi, this error occurs when the user has the wp editor disabled from its profile. This will prevent saving theme options

Cheers

Using Redux version 3.5.8.1

**Comment by kprovance** [comment]
Please review out posting guidelines:  https://github.com/reduxframework/redux-framework/blob/master/CONTRIBUTING.md

**Comment by seventhqueen** [comment]
Redux is used inside a theme developed by us and the Javascript error generated is 
Redux ReferenceError: tinymce is not defined
We are developing locally, sorry if I missed something

**Comment by kprovance** [comment]
I'm not sure how to proceed, since non of the information I asked for was given.
