### ISSUE TITLE
Console issue - Duplicate of - #1337

### ISSUE THREAD

**Issue by maheshwaghmare** [reduxframework/redux-framework#2679]
This is same issue on page `#1337`. 

`Uncaught ReferenceError: redux is not defined`

Not found any valid solution for that I created it again.

@kprovance I'm still facing the issue `Uncaught ReferenceError: redux is not defined`

I'm working on localhost and used plugin `Redux Vendor Support` to enqueue the local assets.

As @tpaksu suggested ( https://github.com/ReduxFramework/redux-framework/issues/1337#issuecomment-45726818 ). I was made changes on locahost i.e.

```'dev_mode' => false,```

and

File: `\framework\core\enqueue.php` - `Line - 278`
```//*****************************************************************
// Redux JS
//*****************************************************************
wp_register_script(
                    'redux-js',
                    ReduxFramework::$_url . 'assets/js/redux' . $this->min . '.js',
                    $depArray,
                    $this->timestamp,
                    false
);
```

Set `false` in both changes. And it works.

My current redux version is - `3.5.8.1`

What was the wrong with my current setup. Or any other issue.

**Comment by maheshwaghmare** [comment]
Now, Update it with version `3.5.8.4`. Still facing same issue. I'm working on localhost by turning off internet. Its internet issue or any other?

**Comment by kprovance** [comment]
We have new support guidelines.  Please follow them, as this is not enough information.

https://github.com/reduxframework/redux-framework/blob/master/CONTRIBUTING.md

**Comment by kprovance** [comment]
Also, it's Sunday, and we don;t work on Sundays.  This will have to be addressed sometime later this week, or next, especially if I don;t have enough data to recreate this on my own.  Sorry.

**Comment by maheshwaghmare** [comment]
Okay. No issue. I'll tried to solve this myself. Thanks for quick response.

**Comment by kprovance** [comment]
Closing then.
