### ISSUE TITLE
Issue with live customizer field values

### ISSUE THREAD

**Issue by nova-ind** [reduxframework/redux-framework#2680]
I'm having a very strange issue with the live customizer. Basically, the field values are either empty or are returning the value last saved in customizer mode. So, if I save a field and refresh the customizer, the value is correct. However, if I save the field in the Redux panel, and go back to the customizer and use wp.customize('option').get(), it returns the value saved last time in the customizer and not the current one saved in the panel. The fields themselves are rendered with the current value, but the API is retreiving the old one, default or empty if the field was never saved in the customizer.

Also, when clicking the "Save & Publish" button, the spinner appears and disappears, but the button does not change to the saved state, and I still get the warning that leaving the page will result in unsaved changes. No errors in the console.

I should mention, I set the customizer flag to false for the sections in my config and cloned the fields I wanted in the customizer with customizer_only set to true, if that makes any difference.
When I worked on the customizer integration, it was all working well. I think I was using 3.5.7.12. I didn't change anything relevant in the theme that I can recall.

[Support URL](http://support.redux.io/?id=uvFYw2V5QL90gxDo4TGeFK4OhoLawTvlAezztWwGusbo%2BX65LEhyLA6%2Fk2CttTJkkTnPCtKdDaG6r7HqrP0cfQ%3D%3D)

EDIT: The button issue is no longer relevant, it was somehow caused by using empty() or isset() in the callback function for 'customize_save_after'. What the hell.

**Comment by kprovance** [comment]
https://github.com/reduxframework/customizer-integration/issues.  Please post customizer issue there.  Thanks.
