### ISSUE TITLE
How remove ads in redux frame work wordpres admin ?

### ISSUE THREAD

**Issue by ronak11** [reduxframework/redux-framework#2681]
i am using redux frame work  in my wordpress theme for theme option but it show ads in wordpress  admin  panel so how to solve this problem. thanks in advanced

**Comment by kprovance** [comment]
As a developer, you cannot.  If you're a user of a theme that uses Redux, you need to contact the theme author and ask them to set dev_mode to false.

**Comment by davidsantanacosta** [comment]
-1

**Comment by kprovance** [comment]
I see.  And how much have you contributed to our project, sir?
