### ISSUE TITLE
Redux fields call in front end error

### ISSUE THREAD

**Issue by adamski24** [reduxframework/redux-framework#2682]
hello i am new to redux and am trying to use on a theme i made 

in option-init.php files my opt_name is 

   // This is your option name where all the Redux data is stored.
    $opt_name = "mazya_opt";

    $args = array(
        'opt_name' => 'mazya_opt',

and whne i call an option like logo url i use

<?php  $mazya_opt['logo']['url']; ?>

where i have a logo field with media type

array(
                'id'       => 'logo',
                'type'     => 'media', 
                'url'      => true,
                'title'    => __('Logo', 'redux-framework-demo'),
                'desc'     => __('Please Upload your logo here', 'redux-framework-demo'),
                'subtitle' => __('Website Logo Image', 'redux-framework-demo'),
                'default'  => array(
                    'url'=>'http://s.wordpress.org/style/images/codeispoetry.png'
                            ),

here is the full code of the options-init.php file

http://pastebin.com/shCkVkiN

my problem is the link/option does not work/show at front end

**Comment by kprovance** [comment]
Without seeing your frontend code, I cannot say.  The options array works fine on my end.  Make sure your global your opt_name before calling it

```php
<?php global $mazya_opt; ?>
<?php $mazya_opt['logo']['url']; ?>
```

**Comment by adamski24** [comment]
Thank you for the reply 
i tried what u made but did not work with me so here is the link 
https://drive.google.com/file/d/0B51s0LlXiZ1cVDU0NWFtWW9EOE0/view?usp=sharing

its an underscore starter theme was downloaded by redux builder

**Comment by kprovance** [comment]
I'm sorry, but for us to download and debug your code, that's a premium service.

**Comment by adamski24** [comment]
Oh, ty any way
