### ISSUE TITLE
Problem with save options

### ISSUE THREAD

**Issue by KAJOJEK** [reduxframework/redux-framework#2683]
Hi I have a problem with save options in panel.
I've copied this from console: 

There was an error saving. Here is the result of your action: redux.js:106:21
<div class="rvolt-header">{"status":"success","options":{"last_tab":"1","theme-css-select":"1","page-width":"2","boxed-on":"","body-background-image":{"background-repeat":"","background-size":"cover","background-attachment":"fixed","background-position":"","background-image":"","media":{"id":"","height":"","width":"","thumbnail":""}},"boxed-background":{"background-color":"#F5F8F8"},"dts-favicon":{"url":"","id":"","height":"","width":"","thumbnail":""},"back-on":"1","java_editor":"","custom-css":"                                    ","page-background":{"background-color":"#F5F8F8"},"accent-color":"#00BCFF","info-color":"#A8AAAA","box-bg-color":"#FFFFFF","lines-color":"#E6E6E6","link-color":"#454545","input-color":"#454545","body-typography":{"font-family":"","font-options":"","google":"1","font-backup":"","font-weight":"","font-style":"","subsets":"","text-align":"","text-transform":"","font-size":"","line-height":"","word-spacing":"","letter-spacing":"","color":""},"widget-h3-typography":{"font-family":"","font-options":"","google":"1","font-weight":"","font-style":"","subsets":"","text-transform":"","font-size":"","line-height":"","letter-spacing":"","color":""},"custom-header-typography":{"font-family":"","font-options":"","google":"1","font-weight":"","font-style":"","subsets":"","text-transform":"","font-size":"","line-height":"","letter-spacing":"","color":""},"h1-typography":{"font-family":"","font-options":"","google":"1","font-weight":"","font-style":"","subsets":"","text-transform":"","font-size":"","line-height":"","letter-spacing":"","color":""},"h2-typography":{"font-family":"","font-options":"","google":"1","font-weight":"","font-style":"","subsets":"","text-transform":"","font-size":"","line-height":"","letter-spacing":"","color":""},"h3-typography":{"font-family":"","font-options":"","google":"1","font-weight":"","font-style":"","subsets":"","text-transform":"","font-size":"","line-height":"","letter-spacing":"","color":""},"h4-typography":{"font-family":"","font-options":"","google":"1","font-weight":"","font-style":"","subsets":"","text-transform":"","font-size":"","line-height":"","letter-spacing":"","color":""},"h5-typography":{"font-family":"","font-options":"","google":"1","font-weight":"","font-style":"","subsets":"","text-transform":"","font-size":"","line-height":"","letter-spacing":"","color":""},"h6-typography":{"font-family":"","font-options":"","google":"1","font-weight":"","font-style":"","subsets":"","text-transform":"","font-size":"","line-height":"","letter-spacing":"","color":""},"blockquote-typography":{"font-family":"","font-options":"","google":"1","font-weight":"","font-style":"","subsets":"","text-transform":"","font-size":"","line-height":"","letter-spacing":"","color":""},"italic-typography":{"font-family":"","font-options":"","google":"1","font-weight":"","font-style":"","subsets":"","text-transform":"","font-size":"","letter-spacing":"","color":""},"header-layout":"header1.php","logo-width":"150","header-fluid":"","header-fixed":"1","header-resize":"1","header-search":"1","cart-on":"1","dts-logo":{"url":"","id":"","height":"","width":"","thumbnail":""},"dts-second-logo":{"url":"","id":"","height":"","width":"","thumbnail":""},"retina-on":"","dts-retina-logo":{"url":"","id":"","height":"","width":"","thumbnail":""},"dts-retina-second-logo":{"url":"","id":"","height":"","width":"","thumbnail":""},"menu-typography":{"font-family":"","font-options":"","google":"1","font-weight":"","font-style":"","subsets":"","text-transform":"","font-size":"","letter-spacing":"","color":"#454545"},"drop-typography":{"font-family":"","font-options":"","google":"1","font-weight":"","font-style":"","subsets":"","text-transform":"","font-size":"","letter-spacing":"","color":"!important"},"col-menu-typography":{"font-family":"","font-options":"","google":"1","font-weight":"","font-style":"","subsets":"","text-transform":"","font-size":"","letter-spacing":"","color":""},"on-shadow":"0","background-header":{"color":"#FFF","alpha":"0.9","rgba":"rgba(255,255,255,0.9)"},"submenu-color-menu":{"color":"#FFF","alpha":"0.9","rgba":"rgba(255,255,255,0.9)"},"first-footer":"1","footer-logo":{"url":"","id":"","height":"","width":"","thumbnail":""},"footer-menu-typography":{"font-family":"","font-options":"","google":"1","font-weight":"","font-style":"","subsets":"","text-transform":"","font-size":"","line-height":"","letter-spacing":"","color":"#FFF"},"footer-one-background":{"color":"#454545","alpha":"1","rgba":"rgba(69,69,69,1)"},"widget-footer":"1","footer-widget-typography":{"font-family":"","font-options":"","google":"1","font-weight":"","font-style":"","subsets":"","text-transform":"","font-size":"","line-height":"","letter-spacing":"","color":"#AAADAE"},"footer-column":"footer-4col.php","widget-footer-h3-typography":{"font-family":"","font-options":"","google":"1","font-weight":"","font-style":"","subsets":"","text-transform":"","font-size":"","line-height":"","letter-spacing":"","color":"#AAADAE"},"footer-widget-background":{"color":"#F5F8F8","alpha":"1","rgba":"rgba(245,248,248,1)"},"social-footer":"1","footer-social-typography":{"font-family":"","font-options":"","google":"1","font-weight":"","font-style":"","subsets":"","text-transform":"","font-size":"","line-height":"","letter-spacing":"","color":"#AAADAE"},"footer-social-icon":{"color":"#AAADAE","alpha":"1","rgba":"rgba(170,173,174,1)"},"footer-social-background":{"color":"#FFF","alpha":"1","rgba":"rgba(255,255,255,1)"},"footer-facebook-url":"http:\/\/facebook.com","footer-twitter-url":"http:\/\/twitter.com","footer-instagram-url":"http:\/\/instagram.com","footer-google-plus-url":"http:\/\/plus.google.com","footer-behance-url":"http:\/\/behance.net","footer-linkedin-url":"","footer-tumblr-url":"","footer-deviantart-url":"","footer-github-url":"","footer-pinterest-url":"","footer-vimeo-url":"","footer-youtube-url":"","footer-soundcloud-url":"","footer-copy-typography":{"font-family":"","font-options":"","google":"1","font-weight":"","font-style":"","subsets":"","text-align":"","text-transform":"","font-size":"","line-height":"","letter-spacing":"","color":"#AAADAE"},"footer-text":"Copyright (C) 2015 by D-Themes. All rights reserved. Theme created by D-Themes. Powered by Wordpress.","blog-layout":"blog-right.php","masonry-columns":"1","blog-fluid":"","blog-paggination":"1","blog-infinity":"","post-excerpt-on":"1","post-excerpt":"20","single-layout":"single-right.php","post-custom-header":"","single-breadcrumbs":"1","single-next-post":"1","post-date":"1","post-like":"1","social-media-buttons":"1","blog-author":"1","post-tags":"1","shop-layout":"3","product-layout":"1","shop-columns":"2","related-on":"1","portfolio-layout":"portfolio-standard.php","pf-social-on":"1","pf-like-on":"1","pf-date-on":"1","pf-tags-on":"1","pf-author-on":"1","pf-related-on":"1","protfolio-select":"1","loader-on":"1","loader-icon":{"url":"http:\/\/localhost:8888\/TEST\/wp-content\/themes\/rvolt-theme\/images\/loader.png","id":"","height":"","width":"","thumbnail":""},"loader-animation":"spinner_dtsanim","page-loader-color":"#FFFFFF","button-size":"2","shop-button-size":"2","button-style":"1","button-rounded-corners":"5","button-color":"#454545","button-font-color":"#FFFFFF","button-hover-font-color":"#FFFFFF","rvolt-404-image":{"url":"","id":"","height":"","width":"","thumbnail":""},"h1-404":"404","h1-size":"200","h1-color":"#6F6F6F","h2-404":"NOT FOUND","h2-size":"60","h2-color":"#6F6F6F","button-404":"1","button-404-text":"BACK TO HOMEPAGE","contact-typography":{"font-family":"","font-options":"","google":"1","font-weight":"","font-style":"","subsets":"","text-transform":"","font-size":"","letter-spacing":"","color":"#454545"},"contact-background":"#FFFFFF"},"errors":null,"warnings":null,"notification_bar":"<div class=\"saved_notice admin-notice notice-green\"><strong>Settings Saved!<\/strong><\/div><div class=\"redux-save-warn notice-yellow\"><strong>Settings have changed, you should save them!<\/strong><\/div><div class=\"redux-field-errors notice-red\"><strong><span><\/span> error(s) were found!<\/strong><\/div><div class=\"redux-field-warnings notice-yellow\"><strong><span><\/span> warning(s) were found!<\/strong><\/div>"} redux.js:107:21

can you help me to resolve this problem ?
Thank You.

**Comment by kprovance** [comment]
Please be mindful of our new support guidelines.  You've not included the required information.

https://github.com/reduxframework/redux-framework/commit/a6dab4b87262017c5fba6d363fb3b5e071a7ce45

**Comment by KAJOJEK** [comment]
Ok, sorry. Problem is solved. That was problem with some functions in function.php
Thank you
