### ISSUE TITLE
Sorter Field Custom Taxonomy Terms

### ISSUE THREAD

**Issue by sudarshann** [reduxframework/redux-framework#2684]
I have a Taxonomy called "group"

Below is my settings in the options-init.php

```
array(
                'id'       => 'opt-categories-layout',
                'type'     => 'sorter',
                'title'    => 'Category Manager',
                'subtitle' => 'You can add multiple drop areas or columns.',
                'compiler' => 'true',
                'args' =>  array(
                        'enabled' => array(
                            'taxonomies' => array('group')
                        ),
                ),
                'data'      =>  array(
                            'enabled' => 'terms', 
                ),
                'options'  => array(
                    'enabled'  => array(),
                    'disabled' => array(),
                ),
            ),
```
I dont get anything in the sorter

in the below file
https://github.com/reduxframework/redux-framework/blob/master/ReduxCore/framework.php#L1165

I tried altering it to as below  (removed  $this->)
if ( ! isset (field['args'][ $key ] ) ) {

it list me the terms in the taxonomy.

but I tried to save the settings but it doesnt save that setting. 

Please let me know how this can be fixed

**Comment by kprovance** [comment]
Please be mindful of our new support guidelines. You've not included the required information.

https://github.com/reduxframework/redux-framework/blob/master/CONTRIBUTING.md

**Comment by sudarshann** [comment]
@kprovance I did notice you require a support url to be generated which is as below
http://support.redux.io/?id=vGJc7OsIs1Lsra%2BGyjVmhxIZmVCk65hZavqR%2Bqkbr1d5JyG1lysgopfIV3EpCCakIFdUpvm2WCPGTzEn%2Bx4k7w%3D%3D

**Comment by kprovance** [comment]
```
                'args' =>  array(
                        'enabled' => array(
                            'taxonomies' => array('group')
                        ),
                ),
```
That's not how that works.  Take out the enabled array.

**Comment by sudarshann** [comment]
@kprovance   Could you please explain me more in details about this 

do you mean

```
'args' =>  array(
                            'taxonomies' => array('group')
                ),
```

because I tried above but it doesnt work

**Comment by kprovance** [comment]
I don't have time right now to reproduce this entire thing on my local.  I'll try and get to it later this week, or next.

**Comment by sudarshann** [comment]
Thank you very much
