### ISSUE TITLE
Redux causes notices in Theme Check plugin

### ISSUE THREAD

**Issue by IgorCode** [reduxframework/redux-framework#2685]
I'm getting these two notices when I run Theme Check:
`Notice: Undefined offset: 2 in /wp-content/plugins/theme-check/checks/textdomain.php on line 82`
`Notice: Undefined offset: 3 in /wp-content/plugins/theme-check/checks/textdomain.php on line 82`

I have identified this to be due to a string concatenating inside ReduxFramework, [welcome.php file](https://github.com/reduxframework/redux-framework/blob/master/ReduxCore/inc/welcome/welcome.php#L104):
`...s a <a href="' . 'https://' . 'wordpress.org/s...`
 Is there any reason why this string is not in one piece?

**Comment by kprovance** [comment]
Because it will still fail theme check.  The issue is with theme check itself.  It's not parsing strings properly.  Contact them about it.

**Comment by dovy** [comment]
Actually, we may be able to fix this by escaping the URL...

**Comment by Otto42** [comment]
String concatenation like this is invalid in translation functions. The code scanners that read the code to find the strings to be translated don't run the code, they just parse it. Strings to be translated need to be plain strings only, not combined pieces of strings.

**Comment by dovy** [comment]
@otto - users asked us about the info notices. If we escape it will the info go away? We prefer not to have support requests over things like this. ;)

**Comment by kprovance** [comment]
<blockquote>
Edit: Also, a URL like that does not "fail" theme check, it just throws an INFO notice for reviewers. If the URL is fine, then there's nothing wrong with an INFO notice. There's no reason for this to not just be one string, without the concatenation.
</blockquote>
I don't disagree, but people still complain to us, as if we've somehow offended their heightened sense of accomplishment.   ;-)

**Comment by kprovance** [comment]
Rejoined the http strings.  You will get INFO notices in theme check, but Otto says it's okay, so, we'll go with that.

**Comment by Otto42** [comment]
An INFO notice is never a fail. Ever. It's informational. Thus the name. ;)
