### ISSUE TITLE
Error : Your panel has no fields. Nothing to save.

### ISSUE THREAD

**Issue by kmtuhin** [reduxframework/redux-framework#2686]
I have just started with Redux Framework Version 3.5.8.1.
When I am trying to save my options,  this error is showing:

"Your panel has no fields. Nothing to save".

This error is not only showing for my Custom Config file but also by using sample-config.php file.

Is there any solution for this error?

**Comment by kprovance** [comment]
Please be mindful of our new support guidelines. You've not included the required information.

https://github.com/reduxframework/redux-framework/blob/master/CONTRIBUTING.md

**Comment by kprovance** [comment]
Closing due to lack of reply.  If assistance is required in the future, please open a new issue with the required information.  Thanks.
