### ISSUE TITLE
Using "Required"with multicheck

### ISSUE THREAD

**Issue by ThinkUpThemes** [reduxframework/redux-framework#2687]
Is it possible to to use the "required" conditions, where the condition is bases on whether the user had selected a particular checkbox in a multicheck field?

Thanks in advance as always!

**Comment by kprovance** [comment]
Have you read the required documentation on ours docs site?  You could try it for yourself and find our, or do you really want me to do that for you?  If so, it'll be days or weeks before I have that kind of time to waste.  :)

https://docs.reduxframework.com/core/the-basics/required/

**Comment by ThinkUpThemes** [comment]
REALLY??? You think that's a way to respond to someone asking for help given that I paid for support when you begged people to 'donate' to Customizer.

Given that your donation guarantee was support for all issues I expect a reply. Or are you telling me that your support promise was a lie? In that case I'm so glad that I donated via PayPal. ;-)

If you like I'll be happy to send you some support articles on how to test people with respect. If reading is a challenge for you I'll be happy to find a YouTube video for you.
