### ISSUE TITLE
fields out put translation

### ISSUE THREAD

**Issue by adamski24** [reduxframework/redux-framework#2688]
Hello,
i have done making a theme back end panel and every thing is done but i wanted to get the fields value as text and text area translated as well so how it works or how i can get the translation of it by wpml

**Comment by kprovance** [comment]
https://docs.reduxframework.com/core/advanced/wpml-integration/

**Comment by adamski24** [comment]
Thank you, i have done the file in xml and wonder where i should paste it in theme root or admin folder as i use the redux files within the theme as built-in option or should i refer to it
