### ISSUE TITLE
Cusomizer slides can't be removed

### ISSUE THREAD

**Issue by ThinkUpThemes** [reduxframework/redux-framework#2689]
When using the "slides" field in customizer if you add a few slides, then save the customizer. If you then try and delete all the slides, it won't allow this. A single slide always remains in the preview. Sometimes the slides do delete, but it only shows when the customizer is saved and the page reloaded.

**Comment by kprovance** [comment]
I'm sorry, are you on staff here?  You don;t have any kind of right to speak to me in this way.  I own you, NOTHING.  If you have something you want to say to me, EMAIL IT!

**Comment by ThinkUpThemes** [comment]
Sure, what's your email address? Please add me to Skype and we can have a chat. Skype name is the same as my username.

Look forward to speaking with you shortly. :-)

**Comment by ThinkUpThemes** [comment]
Hi buddy,

I can't find your email address. I took a look at your website but couldn't find it on there. I'm not too familiar with GitHub, so not sure if I can email you on here directly or not. If so, let me know. I know it's not your job to provide GitHub support, but you've been so helpful already I'm sure you won't mind. :-)

Thanks again for offering to provide 1:1 support via email. I really can't wait to chat via Skype.

**Comment by ThinkUpThemes** [comment]
Hello kprovance,

Notice you deleted your cool message from earlier. Now my messages don't make sense in isolation, so I've gone ahead and removed them also.

Anyway, was really looking forward to speaking. I guess you don't want to talk anymore. No worries, no doubt you're very busy. Anyway, if you can look into the above issue when you get a chance that'll be much appreciated.

Thanks again mate!

**Comment by kprovance** [comment]
Our issue tracker is not the place for you to air grievances.  I am going to delete these as well.  If you continue, I will ban you, at which time you can work it all our with Dovy.  Understand?
