### ISSUE TITLE
How do i supply a dropdown beside a text box ???

### ISSUE THREAD

**Issue by cmsni** [reduxframework/redux-framework#2690]
I am wantng to acheive merge code list beside textboxes and text areas I have seen this done many times via options frameworks I am using redux to complete my options panel So I am giving the user a section for emails.

This is a bit of code to show what i meen by a short code its anything between {}
`<?php

//lets get the redem voucher email that will go to both the user and the admin.

$replacements = array(
'({player_id})' => $playerId,
'({player_fname})'=> $player->display( 'player_first_name' ),
'({player_lname})'=> $player->display( 'player_last_name' ),
'({message_body})' => nl2br( stripslashes( $ggs['player-redeem'] ) )
);
$message = preg_replace( array_keys( $replacements ), array_values( $replacements ), $ggs['player-redeem']);
Below is a screen shot I want to acheive.
http://snag.gy/PkkJS.jpg

**Comment by kprovance** [comment]
This is not something Redux does, inherently.  You'd have to author your own extension or field overload:  https://docs.reduxframework.com/core/advanced/add-a-custom-field/

A more than intermediate knowledge of PHP and JavaScript would be necessary.
