### ISSUE TITLE
WP_USER > id with redux-framework

### ISSUE THREAD

**Issue by tuannguyen2086** [reduxframework/redux-framework#2691]
Hi, 

I installed the redux framework plugin with git. and hit Active. 

there appeare this error:
 WP_User->id was called with an argument that is deprecated since version 2.1! Use WP_User->ID instead. in /web/wp/wp-includes/functions.php on line 3570

**Comment by kprovance** [comment]
Here's the problem:  Redux doesn't use the WP_User query.  The error is being generated someplace else.

**Comment by ruthvik39** [comment]
PHP Warning:  is_readable(): open_basedir restriction in effect. File(D:\inetpub\vhosts\r3katelier.com\httpdocs/wp-content/plugins/D:/inetpub/vhosts/r3katelier.com/httpdocs/wp-content/plugins/redux-framework/ReduxCore/languages/en_US.mo/redux-framework-en_US.mo) is not within the allowed path(s): (D:/inetpub/vhosts//r3katelier.com\;C:\Windows\Temp\) in D:\inetpub\vhosts\r3katelier.com\httpdocs\wp-includes\l10n.php on line 481

Hello,

When i update my redux framework, this is the message i receive. Kindly help me out

Thanks

**Comment by kprovance** [comment]
This is a configuration issue with your server.  You will need to adjust it yourself, or have support for your server handle it.
