### ISSUE TITLE
Updated and now no content

### ISSUE THREAD

**Issue by alisoncastillo** [reduxframework/redux-framework#2692]
Today I updated my theme and all necessary plug ins. Now my site is loading with blank content, although I can see all of my content within Wordpress and in live preview mode.

I saw this error but can not recreate it: select2-css CDN unavailable

sincerely-we.org

**Comment by kprovance** [comment]
Unfortunately, we do not support the actual themes that use our framework.  That is the responsibility of the theme's author.  Please contact them for support.  Thanks!
