### ISSUE TITLE
Redux Framework PHP Warning

### ISSUE THREAD

**Issue by ruthvik39** [reduxframework/redux-framework#2693]
PHP Warning:  is_readable(): open_basedir restriction in effect. File(D:\inetpub\vhosts\r3katelier.com\httpdocs/wp-content/plugins/D:/inetpub/vhosts/r3katelier.com/httpdocs/wp-content/plugins/redux-framework/ReduxCore/languages/en_US.mo/redux-framework-en_US.mo) is not within the allowed path(s): (D:/inetpub/vhosts//r3katelier.com\;C:\Windows\Temp\) in D:\inetpub\vhosts\r3katelier.com\httpdocs\wp-includes\l10n.php on line 481

When i update the redux framework, this is the message i receive. I am working my website from a server and not a local computer. Please help me.
Thanks

**Comment by kprovance** [comment]
This is a configuration issue with your server.  You will need to adjust it yourself, or have support for your server handle it.
