### ISSUE TITLE
There was a problem with your action. Please try again or reload the page.

### ISSUE THREAD

**Issue by safiro** [reduxframework/redux-framework#2695]
I updated to latest version and I still getting this message when trying to click "Save Changes".

I think I did create so many options.
is there any way to create many sample options files to divide options to be.
Home Options.
Category Options
Single Post  Options
and so on .....

**Comment by kprovance** [comment]
Please be mindful of your new posting guidelines. There is not enough information here for us to assist.

https://github.com/reduxframework/redux-framework/blob/master/CONTRIBUTING.md

**Comment by waazes** [comment]
I updated the plugin to version 3.5.8.1 and now im getting these errors:

http://prnt.sc/8xpj1d

Notice: Undefined index: id in public_html/vorumaa/wp-content/themes/voru/includes/redux/extensions/metaboxes/extension_metaboxes.php on line 1142

Notice: Undefined index: id in public_html/vorumaa/wp-content/themes/voru/includes/redux/extensions/metaboxes/extension_metaboxes.php on line 1171
Notice: Undefined index: id in public_html/vorumaa/wp-content/themes/voru/includes/redux/extensions/metaboxes/extension_metaboxes.php on line 1172
Notice: Undefined index: id in public_html/vorumaa/wp-content/themes/voru/includes/redux/extensions/metaboxes/extension_metaboxes.php on line 1179
Notice: Undefined index: id in public_html/vorumaa/wp-content/plugins/redux-framework/ReduxCore/framework.php on line 3367
Notice: Undefined index: id in /public_html/vorumaa/wp-content/plugins/redux-framework/ReduxCore/framework.php on line 3450
Notice: Undefined index: id in public_html/vorumaa/wp-content/plugins/redux-framework/ReduxCore/framework.php on line 3494
Notice: Undefined index: id in public_html/vorumaa/wp-content/plugins/redux-framework/ReduxCore/framework.php on line 3494
Notice: Undefined index: id in public_html/vorumaa/wp-content/themes/voru/includes/redux/extensions/datetime/datetime/field_datetime.php on line 153

What's causing this?

**Comment by kprovance** [comment]
FIrst @waazes , do NOT piggy back other tickets with your own issue.  Second, you need to review the support guidelines https://github.com/reduxframework/redux-framework/blob/master/CONTRIBUTING.md, then open your own ticket with the appropriate information.

**Comment by safiro** [comment]
for my issue.
I installed my theme on a free hosting and it is working fast & fine !!!!!!!
while I'm getting "There was a problem with your action. Please try again or reload the page." on Hostgator, So I had to remove some sections and it's working.. 
it might be hosting issue.

**Comment by kprovance** [comment]
We needed the information from the guidelines I suggested you read.  If you cannot provide them, there isn;t much more we can do for you.  Closing ticket.  If you need assistance in the future, please mind our guidelines and submit the required information.  Thanks!
