### ISSUE TITLE
Fatal error: Allowed memory size 

### ISSUE THREAD

**Issue by riccardosirchia** [reduxframework/redux-framework#2698]
Can someone assist me to fix this problem? i have put a php.ini file in the root folder but no luck.
Theme, Ronneby

**Comment by kprovance** [comment]
Please review:  https://github.com/reduxframework/redux-framework/blob/master/CONTRIBUTING.md

**Comment by kprovance** [comment]
Closing issue due to lack of reply.  If you continue to experience issues, please open a new ticket with the required information.  Thanks!
