### ISSUE TITLE
Redx Tab Link

### ISSUE THREAD

**Issue by Basilakis** [reduxframework/redux-framework#2699]
Hello,

I am trying to create a Tab Menu, which will include sub tabs also, but can not find to the documentation, what extra option I should give, to be inherit on one.

Can u please assist on that?

Thanks a lot

**Comment by kprovance** [comment]
If you're talking about the help tabs and help tab sidebar, here:  https://docs.reduxframework.com/core/arguments/

If you're talking about an actual tabbed menu on the page, Redux doesn't do that.  :)

**Comment by Basilakis** [comment]
Hey,

I am speaking for the following part:
http://awesomescreenshot.com/04f5ds1323

which is actually a subtab - submenu.

Thanks ;-)

**Comment by ARCITEX** [comment]
hi, just use sample.ini.php as cheatsheet.

Based on your ss:
to creating a section/menu
```
    Redux::setSection( $opt_name, array(
        'title'            => '',
        'id'               => '',
        'desc'             => '',
        'fields'           => array()));
```

and for a subsection/submenu just create another section (code is same as above) below the current one and add this line of code
```
'subsection'       => true,
```

entire code for subsection/submenu
```
    Redux::setSection( $opt_name, array(
        'title'            => '',
        'id'               => '',
        'subsection'       => true,
        'desc'             => '',
        'fields'           => array()));
```

**Comment by Basilakis** [comment]
Thank you!

It is to bad, when theme authors edit the core files of redux.
Took me ages to do an update.

Thanks again!

**Comment by ARCITEX** [comment]
Your welcome.
