### ISSUE TITLE
How to remove Options Object tab?

### ISSUE THREAD

**Issue by safiro** [reduxframework/redux-framework#2700]
How to remove "Options Object" tab which exists above "Import/Export" tab?

**Comment by dovy** [comment]
Turn off dev_mode.

**Comment by jilani53** [comment]
it's not removed

**Comment by ReessKennedy** [comment]
@jilani53: Even with dev mode off, I think it still only remains there if you're still on localhost.

**Comment by kprovance** [comment]
Add `'show_options_object'   => false` to your global arguments.

**Comment by 6buddav** [comment]
@kprovance  thanks it works fine

**Comment by rajusulayman7** [comment]
Thanks a lot kprovance

**Comment by kprovance** [comment]
Cheers!
