### ISSUE TITLE
Redux for Plugins

### ISSUE THREAD

**Issue by naumanahmed19** [reduxframework/redux-framework#2701]
Hi,

I am using redux for some of my plugins and themes. I know it can be used if I have unique option name for each plugin.

My question is.. I want to create only one panel of all Plugins. Is there any hook method to show all options in one place if respective plugin is activated (sure I will add redux core in each plugin and check if its already activated or not)

**Comment by kprovance** [comment]
I've never tried anything like that.  However, using multiple opt_names would prevent it outright.  You could TRY using the same opt_name for each project, even tho it's discouraged.  If there is a caveat to it, I can't think of any at present.
