### ISSUE TITLE
Cannot get all registerd post type

### ISSUE THREAD

**Issue by NlGhT** [reduxframework/redux-framework#2703]
I am creating an option panel using redux api. My intention is to create a "select" field with all the registered post type... It must not be obtained manually because this functionality is intended to be used by a plugin.
Problem is that when redux loads its panel, only 5 post types appear (there are 13) and if I hook the option panels a bit later (when the 13 registered post types appear) then, the option panel wont display.

When is the latest I can hook redux to?... Is there a way to hack into the core to have the redux panel display after admin_init ?---- Thanks in advanced

**Comment by kprovance** [comment]
Well, if you hack the core, you're on your own.  People have done that, and their users come to us for fixes, which we cannot support.

I'm not sure how the loading of Redux affects the loading of post types?  That suggest Redux is preventing them from doing so, which isn't possible, really.  Have you made that specific determination through debugging?

You could try loading post types without the init hook.  I know WP says to do it that way, but it causes more problems than not, and I personally do not use init for CPT.

**Comment by kprovance** [comment]
But, to answer your question - if you are using the Redux API to create your panel, you could load your panel using whatever action hook you like.

**Comment by NlGhT** [comment]
Thanks for you quick answer

Hacking into the core would be the last resort... Redux optons panel loads like a charm!, Only thing is that my first attempt was loading redux function at my_cred_ini hook (a hook for another plugin when it loads its module, according to their doc that hook fires at admin_init, thus allowing the options panel to display under their settings menu... Problem is that at that time, the option panel has only 5 post_types (mega checked) and if I just display the panel a bit later, then I can echo the 13 post types but panel won't load... 

Which is the latest I can hook the options panel to, so that the 13 post types registered appear without going to far from the hook that can be use to display the  options panel?

This CPT where registered using the native wordpress register post type action.

Many thanks if you know the answer this and decide to repply

**Comment by kprovance** [comment]
As I said, you can set a hook to any WordPress action to load the panel whenever you like.  I have mind set to load in an after_setup_theme hook.  The very last line of my options-config is `Redux::init ($opt_name);`  ($opt_name being the string variable of my theme's actual opt_name).  That line allows you to init the options panel, on demand.

**Comment by NlGhT** [comment]
Just tested and it does display one more CPT... now I got 6 on the list... 7 more to go

**Comment by kprovance** [comment]
Closing.
