### ISSUE TITLE
Issue with WP Plugin (Causes 500 error upon activation)

### ISSUE THREAD

**Issue by EvilVillain** [reduxframework/redux-framework#2704]
Title kinda says it all. It happens right on activation:
/wp-admin/update.php?action=install-plugin&plugin=redux-framework&_wpnonce=XXXXXXXX
(WP error log & server logs dont mention anything noteworthy)

The front-end is still functioning, /wp-admin and further is giving me 500-errors. Tried disabling plugins, flushing caches, replacing .htaccess for new ones etc., nothing seems to work. Any clues?

**Comment by kprovance** [comment]
500 errors are server based errors.  Those are not something we are able to debug for you without a premium support subscription.  You may need to adjust your php.ini error logging to E_ALL to see all the errors generated.  The answer will probably be in there, someplace.

**Comment by pilyf** [comment]
Hello! I've been having the same problem.  
My web server is iis, could that be it, or is it strictly php related?

**Comment by kprovance** [comment]
Again, 500 errors are server config related.  There's no way for me to know anything about your server or how it's configured, therefore I am unable to answer your question.  Review your error logs for clues.  That's about all I can suggest.

Also, in the future, please don;t piggy back older tickets.  Open a new one with the required information:  https://github.com/reduxframework/redux-framework/blob/master/CONTRIBUTING.md
