### ISSUE TITLE
Typography not outputing on live server

### ISSUE THREAD

**Issue by petarcar** [reduxframework/redux-framework#2705]
Small issue I believe. 
On local server everything is working just fine, but on live server, when i set google fonts for specific 'output' array, google fonts just wont work. When I inspect element i can see that font is loaded properly, but not rendering it on front end. I am trying to troubleshoot issue for couple of days now, and it just wont work.
Hope you can help. Thanks.

**Comment by kprovance** [comment]
Please review our support guidelines.  You've included NO pertinent information.

**Comment by petarcar** [comment]
Ok, I'll try to be more specific about the problem I have. 

I've been developing standalone theme in local environment, and everything worked just fine, when I tested fields. When I moved website on live server, typography field does not work.

It is loading google fonts in select menu in theme options panel, also it is outputting settings correctly in css, but it wont change font for specific output array. In other words, I can't see change on front end of the website.

Basically nothing changed except the environment, it was on local server, now it is on live server and it is not working.

Here is the sample,

array(
                            'id'          => 'slide1-typography',
                            'type'        => 'typography', 
                            'title'       => __('Slide 1 typography', 'wapp_stars'),
                            'google'      => true, 
                            'font-backup' => true,
                            'output'      => array('.slide1-caption'),
                            'units'       =>'px',
                            'subtitle'    => __('Set general properties of slide 1 typography', 'wapp_stars'),
                            'default'     => array(
                                'color'       => '#333', 
                                'font-style'  => '700', 
                                'font-family' => 'Verdana', 
                                'google'      => true,
                                'font-size'   => '14px', 
                                'line-height' => '16'
                                ),
                            'required'  => array('enable_disable_sliderfull','equals','1')
                        ),
                        array(
                            'id'          => 'slide1-title-typography',
                            'type'        => 'typography', 
                            'title'       => __('Slide 1 title typography', 'wapp_stars'),
                            'font-family' => false, 
                            'text-align'  => false, 
                            'font-backup' => false,
                            'output'      => array('.slide1-caption h2'),
                            'units'       =>'px',
                            'subtitle'    => __('Set general properties of slide 1 title typography', 'wapp_stars'),
                            'default'     => array(
                                'color'       => '#333', 
                                'font-style'  => '700', 
                                'font-family' => 'Verdana', 
                                'google'      => true,
                                'font-size'   => '14px', 
                                'line-height' => '16'
                                ),
                            'required'  => array('enable_disable_sliderfull','equals','1')
                        ),

So .slide1-caption has font-family enabled and h2 should inherit that from .slide1-caption. I tried to be more specific and enable font-family for h2 also, but I get same result. 

Thanks.

**Comment by kprovance** [comment]
I meant this:  https://github.com/reduxframework/redux-framework/blob/master/CONTRIBUTING.md

So far, I cannot reproduce.  Make sure you check all your php error logs as well.  If it ends up being a server issue, that is beyond the scope of our free support, so you need to be certain that is not it.

**Comment by petarcar** [comment]
Found the solution. it appears to be browser issue. 
This little piece of code fixed it. 
Just load this and typography field will work just fine.

( function( $ ) {
  "use strict";
  $( window ).on( 'load', function() { 
    
    $( 'body' )
      .hide()
      .show();
      
  });
}( jQuery ) );

I really hope this will help somebody out there. Cheers, and thank you very much for help.

**Comment by dovy** [comment]
What browser? Sheesh.

**Comment by petarcar** [comment]
Chrome and FF. It appears to be the problem with latest updates.
https://codestag.com/fix-google-chrome-web-fonts-issue/

**Comment by dovy** [comment]
Lol. Google needs to fix their problem then. ;)

**Comment by petarcar** [comment]
:D Exactly.

**Comment by dovy** [comment]
If I were you I'd use the CSS solution on that page. Less resources to the user. But that's me. 

I'll consider this situation resolved. Best of luck!
