### ISSUE TITLE
No way to dismiss the developer notification

### ISSUE THREAD

**Issue by Neejoh** [reduxframework/redux-framework#2707]
I get it that you guys want to collect as much money as possible to fund the Redux Customiser Integration but this message is getting on my nerve. It returns _every_ page load on _every_ page in WP Admin...

![screen shot 2015-11-10 at 12 16 48](https://cloud.githubusercontent.com/assets/7911547/11061156/3adf7c96-87a5-11e5-9fc5-3abb2bac67fe.png)

There is no way to dismiss it, besides setting `WP_DEBUG` to `false` while I'm developing. Please let me dismiss the notification all together instead of hiding it for a second and show it again once the page is reloaded.

**Comment by kprovance** [comment]
Click the little X at the top left.

**Comment by Neejoh** [comment]
What little X at the top left?
If you mean the top right, I tried that but as I mentioned it is briefly hidden but comes back right after you refresh (or navigate to another page within wordpress).
