### ISSUE TITLE
There was a problem with your action. Please try again or reload the page.

### ISSUE THREAD

**Issue by safiro** [reduxframework/redux-framework#2708]
I'm getting this error when clicking "Save Changes" button.
Redux Version: The latest
Sections: 27 Section
Wordpress Version: The latest
Web Hosting: Hostgator "Reseller".
Browsers: FF The Latest - Opera 33.0.1990.43 - Chrome 46.0.2490.80 m

This error happens on Hostgator.
I tried setting up the theme on free hosting and it is working fine.

So, How to fix this issue?

**Comment by kprovance** [comment]
Sorry, but 'the latest' is unacceptable.  Please review our support guidelines. https://github.com/reduxframework/redux-framework/blob/master/CONTRIBUTING.md.  You'll take special note of the javascript console.  AFter that message, there will be information in the debug console.  We need to see that info.

**Comment by safiro** [comment]
Wordpress Version 4.3.1 
Options panel created using Redux Framework v3.5.8.7

Console:

There was an error saving. Here is the result of your action:
redux.min.js?ver=3.5.8.7:1 <br />
<b>Warning</b>:  parse_str(): Input variables exceeded 1000. To increase the limit change max_input_vars in php.ini. in <b>/home/mytheme/public_html/wp-content/themes/videotheme/inc/cp/ReduxCore/framework.php</b> on line <b>2819</b><br />

**Comment by kprovance** [comment]
Well, there is the issue then.  Redux ajax save fails when there are on screen warnings such as this.  You have to eliminate the error (which is a whole different issue).  Your options panel is just too large.  We're sorta kinda working on a way to move past the max_input_var limit, but it's still preliminary.  That setting may be changed via php.ini, but that'll only solve your side of it.  Every client would need to do so as well, and 1000 is the default limit.

**Comment by safiro** [comment]
I hope that fixed ASAP.
But is there any temporary fix till the final one.
Thanks.

**Comment by kprovance** [comment]
Rethink your options panel design to not use so many options?  Otherwise, no.  Sorry.
