### ISSUE TITLE
Multi_text Undefined index error

### ISSUE THREAD

**Issue by PauloNatal** [reduxframework/redux-framework#2709]
Hi, 
I am a developer using your Redux Framewok to build an options panel for a theme I am developing.

have already updated to the last version.

Getting the following error with a multi_text field:

Undefined index: (multi_text id)

Also getting the following alert:
There was a problem with your action. Please try again or reload the page.

The console shows Uncaught SyntaxError: Unexpected token
There was an error saving. Here is the result of your action: 

After this an array with all the options I have so far.

Support URL:
http://support.redux.io/?id=1vZ8WrqK%2FPXDuLMuYrZ85%2FCX2MpwOk5OfVO5p86ytjzt93iuaHH3YRLKRpVPKuIfTpIuug8v%2FATZelSHsSTJfA%3D%3D

Thank you

**Comment by kprovance** [comment]
Undefined index: (multi_text id): NO line number?  IMPORTANT!

**Comment by PauloNatal** [comment]
Sorry
Notice: Undefined index: custom_sidebars in C:\xampp\htdocs\empyrus\wp-content\themes\empyrus\functions.php on line 231

**Comment by kprovance** [comment]
That error has nothing to do with Redux.  It's probably in your functions file when dealing with sidebar creation.  We only support Redux issues.

**Comment by PauloNatal** [comment]
This is what is in that line:

global $my_theme_option;
$custom_sidebars = $my_theme_option[ 'custom_sidebars' ];

custom_sidebars is a field on my theme_options.php file:
  array(
            'id'         => 'custom_sidebars',
 )

**Comment by PauloNatal** [comment]
Any ideas of what it might be? It's just strange that a text field is fine and a multi_text gives the error..

**Comment by PauloNatal** [comment]
Well, it has to be  a redux framework issue, but I can already see I wont get any help from you so Ill use something else. Take care

**Comment by kprovance** [comment]
Today is an American holiday, and I don't work on holidays (or work for free on holidays, which is what this is).  I owe you nothing.  You didn't pay for Redux, or my time.  If you couldn't wait a day, that's on you.

Goo luck to you, sir.
