### ISSUE TITLE
Disable slides drag & drop feature in Customizer

### ISSUE THREAD

**Issue by ThinkUpThemes** [reduxframework/redux-framework#2710]
Hello,

The drag and drop feature to rearrange slides doesn't work within customizer, or well at least it doesn't work with the live preview updating. Is there a way to disable the drag and drop feature?

Thanks!

**Comment by kprovance** [comment]
I'd like to move all customer issues here:  https://github.com/reduxframework/customizer-integration/issues

As they might take a while before anyone is able to address them, I'd rather not have them clogging up this particular issue tracker.  Thanks!
