### ISSUE TITLE
Redux Installation Issues

### ISSUE THREAD

**Issue by Absolutebc** [reduxframework/redux-framework#2711]
I get this error when I install Redux Framework: Parse error: syntax error, unexpected $end, expecting T_FUNCTION in /home/c0nt17en/public_html/wp-content/themes/enhenyero/admin/theme-options/extensions/ow_repeater/extension_ow_repeater.php on line 11

Could anyone please advise how i can fix this problem?

**Comment by kprovance** [comment]
You need to contact whomever wrote 'ow_repeater'.  That didn't come from us.

**Comment by Absolutebc** [comment]
Hi Kevin

That does not help me at all.  Where does ow_repeater come from?  On this
Wordpress Installation, I have literally, installed the Enhenyero Theme and
the IgniteUp plugin.  The other plugins came with your theme.

I would like a refund,  I have already lost 5 days on development using
this theme, and I am now loosing money.




Best Regards,

Janine Doubell
Member

C: 083 675 1998
T: 087 63 000 59
E: janine@absolutebc.co.za

**Comment by dovy** [comment]
Sorry, but we didn't develop they theme at all. You need to contact your actual developer.  We build a framework that author used.  :)

Dovy Paukstys
