### ISSUE TITLE
Redux Framework Produces Server Error 500

### ISSUE THREAD

**Issue by arvobowen** [reduxframework/redux-framework#2712]
I get the following error...
`[13-Nov-2015 17:29:31 UTC] PHP Fatal error: Class 'Evolve_Redux_Customizer_Section' not found in /home2/myuserpath/public_html/wp-content/plugins/redux-framework/ReduxCore/inc/e‌​xtensions/customizer/extension_customizer.php on line 588.`

Tried reinstalling the plugin but that did not change anything.  It used to work maybe an update changed something?

**Comment by kprovance** [comment]
You'll need to contact whomever authored the 'evolve' theme.  They made some kind of change that we are unable to support  (also, theme users should always contact the theme author, before us.  We did not author the theme, and it's the theme author's responsibil;ity to investigate errors in their work.  Not us.)

Thanks.
