### ISSUE TITLE
Issue with share_icons notice showing all the time

### ISSUE THREAD

**Issue by njeffers** [reduxframework/redux-framework#2713]
I was getting the following notice, and couldn't figure out why. Made sure there were no references, updated redux, and even migrated my options over to the new sample options code. 

At the top of Redux, you'll get the following:
Redux Framework Notice: There are references to the Redux Framework support site in your config's share_icons argument. This is sample data. Please change or remove this data before shipping your product.

The error appears to be in Line 3974 of framework.php.

if (strpos(strtolower($y), 'redux') >= 0) {

should probably be:

if (strpos(strtolower($y), 'redux') > 0) {

**Comment by kprovance** [comment]
Or, change your arguments so they do not include Redux, which prevents your users from coming to us for support for your products.  :)

**Comment by njeffers** [comment]
@kprovance - Yes, I know. They haven't had redux links for over a year now, but the error remains. For me, it doesn't work properly until I change that line of code. Do you not get the error? Maybe it's just something tripping out on my side, though it does it on all of our sites. If so, I'm baffled at what could be causing it.

**Comment by ousjah** [comment]
Dear Sir, I also keep having the same error each time on this Version 3.5.8.7 see below: Any help!
Redux Framework Notice: There are references to the Redux Framework support site in your config's share_icons argument. This is sample data. Please change or remove this data before shipping your product.

**Comment by kprovance** [comment]
It's not an error.  It's a notice.  It means go into your config and change or remove the share icons and/or admin_bar_links data from Redux to your own.  I added this because theme and plugin end users are coming to US for theme support...and I'm getting tired of dealing with it because folks won't change those config lines.  :)

**Comment by dovy** [comment]
Fixed and pushed.

**Comment by ousjah** [comment]
Thanks a lot @dovy much appreciated.

**Comment by dovy** [comment]
You're welcome. Donate if you feel so inclined. ;)
