### ISSUE TITLE
Tracking code comping up 

### ISSUE THREAD

**Issue by mumfidential** [reduxframework/redux-framework#2714]
I'm having a weird problem with my wordpress site and am wondering if you could help??
It's in this article
http://www.mumfidential.com/mumfidential-handpicked-christmas-gift-guide-2015/
:If you go down to Tractor Ted... the two links keep going through to a webgain. 
The links that are in the site are NOT webgain... they are pointing to Tractor Ted and they are correct... i've checked them countless times. If I hold down SHIFT while clicking on them, they go to the right place. 

I've spoken to my developer about this who says he linked it back to Redux Framework

they  found these two files that suggested that the plugin redux-framework was causing the issue:

Code:
[100][socket+base64]/home/mumfiden/public_html/plugins/redux-framework/ReduxCore/inc/fields/ace_editor/vendor/mode-php.js
[100][doc.write+ifrm+http]/home/mumfiden/public_html/plugins/redux-framework/ReduxCore/inc/fields/ace_editor/vendor/worker-javascript.js

Please could you look into this for me... I need these links to point to the right place. 

Thanks, Anna

**Comment by kprovance** [comment]
ace_Editor is not our code, and Redux wouldn't do anything like this.  You'd have to contact https://ace.c9.io/ about the specifics of what their code does.

**Comment by mumfidential** [comment]
how has their code got in here??

**Comment by kprovance** [comment]
First, we took it out of Redux a while back, which means you probably need to upgrade.  Second, it's a vendor library, which means we did not write the code.

**Comment by mumfidential** [comment]
HI, I have upgraded Redux and the same issue is still happening. It is just with this one link, not to any others. What would you suggest I do about it?

**Comment by kprovance** [comment]
I just told you, ACE is not our code.  If you want me to debug your site, it's 100 dollars an hour.  We don;t do that kind of thing for free.

**Comment by mumfidential** [comment]
I would never suggest you did anything for free. I don't see why you're being so aggressive! As an amateur with no experience of code I'm just trying to piece together what is going on here and how I should resolve it.
