### ISSUE TITLE
site being hacked 

### ISSUE THREAD

**Issue by mumfidential** [reduxframework/redux-framework#2715]
hi there, three new users have subscribed to my site just now... I haven't added them... please help!!

**Comment by kprovance** [comment]
I'm sorry, but we aren't Wordpress support.  I can;t help you with these things.  Sorry.

**Comment by kprovance** [comment]
I can tell you this; if you believe you have been hacked, you need to contact whomever hosts your site, NOW.  Only they can help you with that.
