### ISSUE TITLE
Yoast SEO Update and Metaboxes Issue

### ISSUE THREAD

**Issue by mediagin** [reduxframework/redux-framework#2717]
Is anyone else seeing an issue with Metaboxes layout breaking with the new Yoast SEO update?  The metaboxes appear fine and function on post types still but the layout is broken with everything left justified rather than spaced nicely, buttons appear as radios, etc.  I see no errors in Chrome Dev Console.  I can disable that particular custom post type in Yoast settings and everything appears normal, but I'd rather not do that.  Is there a workaround?  Thanks.

**Comment by Enchiridion** [comment]
I just updated to the new Yoast and haven't seen any metabox issues, at least not in Firefox.

**Comment by kprovance** [comment]
Please review:  https://github.com/reduxframework/redux-framework/blob/master/CONTRIBUTING.md

This is the wrong section, and no pertinent info has been included.
