### ISSUE TITLE
Redux Extensions - No Responses

### ISSUE THREAD

**Issue by coleh33** [reduxframework/redux-framework#2718]
I'm a little baffled as to why I get told to report extension issues in the extension support page when no one will respond but yet you guys are always very responsive in this section?

I was under the assumption that buying your extensions would offer me even more support for the product but I am curious as to why that support thread appears to get little coverage?

I have posted 2 issues in their and not received one acknowledgement or reply.

I think your product is great, which is why I invested in the repeater extension and in turn I would appreciate someone taking a look at the support requests within Extensions.

Thank You.

**Comment by dovy** [comment]
Sorry, I've been quite behind.

@kprovance care to step into these boards and help out?

**Comment by kprovance** [comment]
Responding to those I can.
