### ISSUE TITLE
Color Sheme  extension not appearing in my option panel

### ISSUE THREAD

**Issue by ObviousMarketing** [reduxframework/redux-framework#2719]
Hi, I purshased color scheme, and followed the instructions to load the extension but nothing is happening, is the a way I can get help?

Thank you,
Anne

**Comment by kprovance** [comment]
I gave you instructions in a different thread.  If I need to go onto your server to set the entire thing up for you, that is a premium service.  Setup and coding are not included in the price of the extension.

**Comment by kprovance** [comment]
THis issues goes in the extensions issue tracker.  This tracker is got Redix issues.

**Comment by ObviousMarketing** [comment]
Hi I purchased the Premium support,can you help me setting it up properly?
Thank you,
Anne

**Comment by kprovance** [comment]
EMail me kevin@reduxframework.com  (that is, do not reply to this forum with the info I need)

I will need two things:

1) admin login to the wordpress site.
2) ftp login to get into the server.

Again, send that to my email, don't post that info here!  :)
