### ISSUE TITLE
Issue with [ WARNING: wp-includes/class-http.php:2136 - gzinflate(): data error ... ]

### ISSUE THREAD

**Issue by bibiangel1989** [reduxframework/redux-framework#2721]
Hi Redux Team,
I was create a theme and use Redux Framework. But recently I discovered a hard bug fix : http://prntscr.com/952vqc . I'm wondering if this is the error comes from Redux Framework ?? Any idea for this issue ?
Thanks !
*p/s: I'm using the latest version of Redux Framework.

**Comment by kprovance** [comment]
It's a glitch in the WordPress core.  It's been well documented.  Google it.  :)

**Comment by bibiangel1989** [comment]
Ok, thank for reply :+1:
