### ISSUE TITLE
I get this error when i install redux as a plugin or including on the theme

### ISSUE THREAD

**Issue by AminulBD** [reduxframework/redux-framework#2722]
Hi,

Today I downloaded redux from master branch and try to embed with my theme. I'm using the latest WordPress version with few development plugins. I think you should check this error with redux.

Hrere is error screencast: http://www.screencast.com/t/88b9hKfu

Thanks.

**Comment by kprovance** [comment]
Please update to version 3.5.8.8

Also, in the future, please do not use videos.  They are difficult to read and it was jumping all over the place.  Screencaps are better.  In fact, these are the preferred guidelines: https://github.com/reduxframework/redux-framework/blob/master/CONTRIBUTING.md
