### ISSUE TITLE
HTML Being stripped out of RAW field

### ISSUE THREAD

**Issue by yojance** [reduxframework/redux-framework#2723]
Hi guys,

Thank you for creating this wondering Framwrok. I'm working with the latest version of WordPress and the Redux Framework "3.5.8" is being embeded in my plugin. I can no longer create a "Submit" input field with the RAW field because it's being ran through wp_kses_post() and removing everything from my field.

Redux Frameowk 3.5.7 didn't have wp_kses_posts() so it was working fine.

Here is the code I'm using:

```
array(
            'id'       => 'export_members_button',
            'type'     => 'raw',
            'title'    => __('Export Members', 'redux-framework-demo'),
            'subtitle' => __('', 'redux-framework-demo'),
            'desc'     => __('', 'redux-framework-demo'),
            'content'  => '<p><input type="submit" name="export_submit_button" id="export_submit_button" class="button button-primary" value="Export Members" /></p>',
        );
```

I don't see any way of bypassing this. If this is going to be the default behaviour going forward, then the RAW field shouldn't really be called RAW, right?

**Comment by kprovance** [comment]
Upgrade to the version I posted yesterday

**Comment by yojance** [comment]
I've upgraded to 3.5.8.8 and Im still expirencing the same result, my submit button is missing.

**Comment by kprovance** [comment]
I removed wp_kses_posts from the raw field.  I did not update the version.  Pull from the master via this repo.
