### ISSUE TITLE
Template file has been moved in WordPress 4.4

### ISSUE THREAD

**Issue by chriscct7** [reduxframework/redux-framework#2726]
Redux requires a file, wp-admin/includes/template.php which has been moved in 4.4 to wp-admin/template.php as part of https://core.trac.wordpress.org/ticket/33413#comment:126. Redux needs to get an update for this that does an if file exists load 4.4 file else load pre 4.4 file location before WordPress 4.4 is released else a ton of sites will fatal error when 4.4 is released.

The changeset is https://core.trac.wordpress.org/changeset/35718 done in 
https://core.trac.wordpress.org/ticket/33413#comment:117
and the note about the breakage that affects Redux is https://core.trac.wordpress.org/ticket/33413#comment:125

Also it appears redux requires other files that moved as part of that change.

**Comment by chriscct7** [comment]
You basically just need to find all the places you require wp-admin/includes/template.php and replace with
if ( file_exists( wp-admin/template.php ) {
  // WP >= 4.4 
  require_once wp-admin/template.php;
} else {
  // WP <= 4.4 
  require_once wp-admin/includes/template.php;
}

**Comment by kprovance** [comment]
Great.  Leave it to the core devs guys to not give a !%#$ about anyone else.  I only see one usage of it in our core.  I can update to compensate.  Thanks for the heads up.  :)

**Comment by kprovance** [comment]
fixed in v.3.5.8.9.

**Comment by chriscct7** [comment]
Just a heads up 13 files got moved. I only looked for 1, but you might want
to double check you guys don't directly call the other 12

**Comment by kprovance** [comment]
I admit, I didn't read the entire trac.  Did they list the files they moved?

**Comment by chriscct7** [comment]
Actually, this needs to be reopened, I've misread the commit. The issue is in 4.4, the classes and functions were split. Let's say for example you extended the category walker, in 4.4, you now need to load require_once ABSPATH . 'wp-admin/includes/template.php'; and require_once(ABSPATH . 'wp-admin/includes/class-walker-category-checklist.php'); Before nacin's commit, doing require_once ABSPATH . 'wp-admin/includes/template.php'; would also require_once(ABSPATH . 'wp-admin/includes/class-walker-category-checklist.php'); and wp-admin/includes/class-wp-internal-pointers.php as a method of backwards compatibility for those who previously require_once ABSPATH . 'wp-admin/includes/template.php'; as in pre 4.4, the walkers and pointers were in template.php. In nacin's commit, that backwards compatibility was removed, thus causing the fatal error described on Trac.

You'll want to revert what I suggested above as it's incorrect (my apologies for a misread on nacin's comment).

What you're going to need to do look at https://core.trac.wordpress.org/changeset/35718#file17 and then examine each of the files where you require_once wp-admin/includes/* and see if any of those new files have the function you previously required, and add a require for it.

Example:
If before you extended the category checklist walker, you'll need to swap
require_once ABSPATH . 'wp-admin/includes/template.php';

for 
require_once ABSPATH . 'wp-admin/includes/template.php'; 
require_once(ABSPATH . 'wp-admin/includes/class-walker-category-checklist.php');

**Comment by chriscct7** [comment]
Basically for any file you used to require in wp-admin/includes/* you'll need to ensure what you used to get from those files is still there and hasn't moved.

**Comment by chriscct7** [comment]
Also it looks like when you added that check, its backwards. You'll definately want to revert that asap

**Comment by kprovance** [comment]
Reversed it all.  Redux doesn't use any 'wallker', so I'm not even sure what that's all about.

I really don't have the time to download and install a new setup for WP 4.4.  I'll deal with it when they release it.

**Comment by chriscct7** [comment]
Fair enough. Looking at the original commit in https://github.com/reduxframework/redux-framework/commit/f655e59bf4dd63e67fb9bfc939372bf0ceac919c I'm not sure why Dovy added it

**Comment by kprovance** [comment]
file.php and template.php were added to make that weak wp_filesystem creds thing work properly (if I am remembering this correctly).  After all, we're not allowed to use PHP IO functions, not when the oh-so-perfect wp_filesystem is available (note the sarcasm).  The truth is, it sucks, and Otto won't acknowledge it.  But, to stay compliant with theme check, we had to put together that plate of spaghetti to keep the WP purists happy.  On paper, it should work great, but people install WP in the most odd ways, which destroy file permissions in some setups, which makes writing to the server a nightmare, and thus our  ::ehem:: solution.  It works, it's just not the way I would have done it, were we given the option to use PHP IO functions.

**Comment by dovy** [comment]
Reopening. I'll get this sorted over the next few days.  ;)   Want to be ready for 4.4.

**Comment by dovy** [comment]
Just resolved and pushed.

**Comment by chriscct7** [comment]
+1
