### ISSUE TITLE
Can I get access to redux options without using the global?

### ISSUE THREAD

**Issue by Madeirense** [reduxframework/redux-framework#2727]
Just wondering if using the redux global everywhere I need to manipulate an option is the only/best way to work with redux.

I have heard people saying that We should avoid using globals for the following reasons amongst other:

Your entire codebase is dependent on a) the variable name $global_name and b) the existence of that variable. If you want to rename the variable (for whatever reason), you have to do so everywhere throughout your codebase. 

Even though I am only starting to play with it I have to say I really like it. I am just not sure if the above observations are valid..

Thank you

**Comment by dovy** [comment]
We use a global variable because it's the most complete solution. You can, however, disable the global option if you feel so inclined. You can also rename it to be different than your opt_name. 

;)
