### ISSUE TITLE
Admin Notices in Dev Mode, Envato not allowing them anymore.

### ISSUE THREAD

**Issue by contempoinc** [reduxframework/redux-framework#2729]
@dovy For some reason Envato reviewers all of sudden decided they won't allow the admin notices in dev mode anymore so they've rejected my theme update (themes already been approved). I think its completely ridiculous but how can I go about removing them?

The three they're referring to:

- http://envato.d.pr/1bIy3/2tmFqzfs
- http://envato.d.pr/y2Pf/3813FkZs
- http://envato.d.pr/1d3q8/3AM3K8Cl

**Comment by dovy** [comment]
Working on an extension now.  ;)

**Comment by kprovance** [comment]
Turn dev mode off.

**Comment by contempoinc** [comment]
@dovy Awesome, thank ya sir! I kinda chewed out the reviewer http://cl.ly/image/1A1a361H460r waiting to see what they come back with, lol. They do this kinda stuff all the time it seems, just out of nowhere coming up with new requirements.

**Comment by dovy** [comment]
Yea, it's crazy. Can't stand it. They also don't want the theme-check helps embedded. LOL.

**Comment by contempoinc** [comment]
@kprovance Right, but they're stating that they're not allowing these notices when dev mod is on.

**Comment by dovy** [comment]
Yea, for local stuff @kprovance. So the whole point of keeping dev_mode to true at all even locally or when WP_DEBUG is on.

**Comment by dovy** [comment]
(Annoying)

**Comment by kprovance** [comment]
I guess explaining to those drones at Envato that your end users don't see that stuff would be pointless.

**Comment by contempoinc** [comment]
@dovy He approved my update but then pointed me to this https://github.com/reduxframework/redux-developer-mode-disabler/blob/master/redux-disable-devmode.php is that the solution?

**Comment by kprovance** [comment]
If you have dev_mode set to false, it's not needed.  The Envato drone probably has WP_DEBUG set to true, which turns on all those things, hence my last reply, in which to explain to them your users won;t see all that stuff.  It's for developers who have WP_DEBUG set to true and/or on localhost.

**Comment by contempoinc** [comment]
@kprovance Exactly, but that's what they're saying they don't allow anymore. They won't allow the notices when WP_DEBUG is true under any circumstance.

**Comment by dovy** [comment]
Just so very annoying.

**Comment by contempoinc** [comment]
@dovy Agreed, so I'm guessing that function doesn't work anymore and the extension you're working on is the way to go?

**Comment by dovy** [comment]
Indeed.  ;)   I'll get it done shortly.

**Comment by contempoinc** [comment]
@dovy Ok, cool thanks man!

**Comment by saqibsarwar** [comment]
Hello Guys,

I was checking the code with same concern and I came across following block of code http://jmp.sh/yeBWYSk 

So, I think using `'forced_dev_mode_off'  => true,` should resolve this issue.

Let me know if I am wrong.

Regards

**Comment by kprovance** [comment]
I just released a new extension to deal with this:  https://reduxframework.com/extension/ad-remover/

Cheers.

**Comment by contempoinc** [comment]
Nice I'll give it a test!



Cheers,

Chris Robinson
www.contempoinc.com
twitter.com/contempoinc
