### ISSUE TITLE
Serialised data and wp_query in Reduxframework

### ISSUE THREAD

**Issue by mrtieutien90** [reduxframework/redux-framework#2730]
Hi all.
How to I can using select posts of post_type by  meta_query ?
I try code :
      <pre><code>  
               array(
                        'id'        => 'opt_theme_support_rel_functions',
                        'type'      => 'select',
                        'title'     => esc_html__( 'Choose Function Support', 'template-builder' ),                        
                        'multi'     => true,
                        'data' => 'posts',                        
                        'args' => array(
                            'post_type' => 'function',
                            'meta_query' => array(
                        			array(
                                        'key' => 'tmp_builder_function_support_theme`',
                            			'value' => 'yes',
                                        'compare' => 'LIKE',
                                    )
                            )                            
                        )                   
                    ),    
      </pre></code>

but It don't working. Please help me.
Thanks  all.

**Comment by kprovance** [comment]
I don't know if this can be done the way you are trying.  See https://codex.wordpress.org/Template_Tags/get_posts on available args.  Even so, this would fall under code debugging, which requires a premium support purchase.

**Comment by mrtieutien90** [comment]
I think this is a bug of Redux Framework. However, thank you. I solved problem without your help.

**Comment by dovy** [comment]
Glad you solved it, but I highly doubt this is a problem in Redux. All this 'data' argument does is a passthrough.

https://github.com/reduxframework/redux-framework/blob/master/ReduxCore/framework.php#L961-L969

Best of luck to you though.

**Comment by mrtieutien90** [comment]
This is is the problem I encountered when I using meta_query in 'args'.
Notice: Array to string conversion in E:\xampp\htdocs\template-builder\wp-content\plugins\template-builder\libs\admin\reduxframework\ReduxCore\framework.php on line 884

**Comment by dovy** [comment]
Umm, what version of Redux are you using?
https://github.com/reduxframework/redux-framework/blob/master/ReduxCore/framework.php#L884

Doesn't make sense.

**Comment by mrtieutien90** [comment]
hi, dovy.
I have updated version Redux: 3.5.8.10 and problems occur in line 893.
<code>Notice: Array to string conversion in ...\reduxframework\ReduxCore\framework.php on line 893</code>
https://github.com/reduxframework/redux-framework/blob/master/ReduxCore/framework.php#L893
