### ISSUE TITLE
Call fields within extension

### ISSUE THREAD

**Issue by seurolandolero** [reduxframework/redux-framework#2732]
Hi, sorry if here is not right place for this question.

I'm trying load a field within my custom extension. I thought load the class and call the render method would be enough, but it seems that this is not correct. Like this:

    include_once(ReduxFramework::$_dir . 'inc/fields/select/field_select.php');
                    $ic = new ReduxFramework_select(
                        array(
                            'id'    => 'ic_option',
                            'type'  => 'select',
                            'title' => 'Lorem ipsum',
                            'subtitle' => 'aa',
                            'desc'     => 'sdsdf',
                            'data'  => 'elusive-icons',
                                'class' => 'redux-select-item font-icons chosen redux-font-icons-file',
                                'name'    => 'opt-texto-titulo-icone2',
                                'name_suffix' => $this->field['name_suffix'],

                        ), NULL, $this->parent);
               echo $ic->render();

What am I forgetting?

**Comment by kprovance** [comment]
I'm not altogether positive it can be done in this manner.  When I did selects in my extensions, I rendered them using HTML, and not by calling existing fields.

**Comment by seurolandolero** [comment]
Thanks for the answer!
When I need simple fields, as select field, I think the best way is actually render by HTML. However, in this case I need a specific functionality that has been developed ('elusive-icons', 'select-image' or another), it would be nice if I could reuse it without implementing it again...

**Comment by kprovance** [comment]
I understand.  That's custom coding, which is not a free service we offer.  You''d be looking at several hours at the minimum of premium service.  See here for more information:  https://github.com/reduxframework/redux-framework/blob/master/CONTRIBUTING.md
