### ISSUE TITLE
Post editor broken - Uncaught TypeError: jQuery(...).qtip is not a function (conflict with Yoast SEO?)

### ISSUE THREAD

**Issue by primitivenet** [reduxframework/redux-framework#2734]
I am getting a Javascript error on the new and post edit screens (post-new.php and post.php) in WP-ADMIN.

The JS error is causing various button not to work, including stopping the icons (bold, align,etc) buttons showing up, and making it impossible to switch between text and visual editor - clicking the tab does nothing. The Yoast SEO metabox is also blank.

The error I get is "Uncaught TypeError: jQuery(...).qtip is not a function"  at wp-seo-metabox-302.min.js:1 

The error seems to be a conflict between Yoast SEO and the Redux Framework - as if I disable either then the error goes away.

I'm using Wordpress 4.3.1, Yoast SEO 3.04, and Redux Framework 3.5.8.10 - the latest of all three.

**Comment by kprovance** [comment]
Well, if the error is in Yoast's code, why contact us?  He's the first person you should be asking about this, being it's his code in question.

**Comment by primitivenet** [comment]
Bah, the theme (Townpress) was including an old version of Redux extension metaboxes that included the following lines

    // Fix for wp-seo embedding an old version (RC3) of qtip. Bah.

    add_action( 'wp_print_scripts', array( $this, 'FIX_wp_seo' ), 100 );

    add_action( 'admin_enqueue_scripts', array( $this, 'FIX_wp_seo' ), 100 ); 

I removed them and the issue was fixed.

Sorry - closed.

**Comment by kprovance** [comment]
Oh, metaboxes, yeah...that fix was fixed.  Gotta get that theme author to update.
