### ISSUE TITLE
Save Changes on Options Page not working; spinning wheel never completes

### ISSUE THREAD

**Issue by TBAtj** [reduxframework/redux-framework#2735]
On one of my staging sites, when I click the save changes (on the options page) the wheel just spins and spins, but never completes. I have turned off all plugins, same issue. Deactivated, deleted, uploaded latest version, same issue.

**Comment by kprovance** [comment]
https://github.com/reduxframework/redux-framework/blob/master/CONTRIBUTING.md

**Comment by kprovance** [comment]
No reply or follow up.  Closing.
