### ISSUE TITLE
New 'add_text' argument for 'Add Slide' button text

### ISSUE THREAD

**Issue by PareshRadadiya** [reduxframework/redux-framework#2737]
Unlike **Multi Text** field's `add_text`argument, we don't have any hook or argument to change `Add Slide` button text. So new argument for the `Add Slide` button text would be great addition.

**Comment by kprovance** [comment]
I have NO idea what you are talking about, or even what this is in reference to.

**Comment by PareshRadadiya** [comment]
Hello @kprovance 

Thanks for your prompt response.

Lemme me explain this to you, I'm using [Slides](https://docs.reduxframework.com/core/fields/slides/) field ( `type => slides` ) and I want to change `Add Slide` button text, [Multi Text](https://docs.reduxframework.com/core/fields/multi_text/) field has a argument `add_more` to change text display on the ‘Add’ button though.

![slide-fields](https://cloud.githubusercontent.com/assets/6149344/11552706/7f15f7b8-99ad-11e5-89b4-2fb8cdaad188.png)

**Comment by kprovance** [comment]
This has been asked, discussed and answered numerous times:  https://github.com/reduxframework/redux-framework/search?utf8=%E2%9C%93&q=overload+slides&type=Issues
