### ISSUE TITLE
How to fix 'redux-framework-tracking' slow sql

### ISSUE THREAD

**Issue by teuber** [reduxframework/redux-framework#2738]
Hi Support Team,
My website : nginx + php + mariadb
And error : 
SlowTimer [1410ms] at runtime/ext_mysql: slow query: UPDATE `wp_options` SET `option_value` = 'a:3:{s:8:\\"dev_mode\\";b:0;s:4:\\"hash\\";s:32:\\"720951df56366d70e22e4a9133df5e27\\";s:14:\\"allow_tracking\\";s:2:\\"yes\\";}' WHERE `option_name` = 'redux-framework-tracking'

How to fix? Thanks you!

**Comment by kprovance** [comment]
Did this ever get resolved?

**Comment by kprovance** [comment]
Closing.
