### ISSUE TITLE
issue with rendering table in custom extension -> class "redux_remove_th"

### ISSUE THREAD

**Issue by dimitrilongo** [reduxframework/redux-framework#2739]
hello,

Found something, when you make a custom extension. Hope you can reproduce:

So in the render function, make a table with thead (so you have your table nested in the redux table container, it's html valid), it works, but if add the ```full_width``` arguments in your field args, you will see each th in your thead disappear when you click on any section button  this is because you add a class ```redux_remove_th``` ```ReduxCore/framework.php  line 3504``` and a js script. 

I know it s a particular case, because of nested table, i'v made a hack in jquery for my personal use, so it's not a problem for me. If you have time just take a look maybe you can fix it in the framework.

Regards

**Comment by kprovance** [comment]
That's by design.  We aren't going to change it.  if your hack works for your purposes, then cool.  :)
