### ISSUE TITLE
Cannot download required plugins for Estate Pro Post Types & Shortcodes and Revolution Slider

### ISSUE THREAD

**Issue by C21wp** [reduxframework/redux-framework#2740]
We get this message when installing plugins:

Downloading install package from /home/content/p3pnexwpnas04_data02/58/2951458/html/wp-content/themes/estatepro-child/plugins/estatepro-post-type-shortcodes.zip…

Download failed. A valid URL was not provided.

**Comment by kprovance** [comment]
You need to contact the theme/plugin author for support.  We did not write the theme/plugin and therefore do not support it.
