### ISSUE TITLE
Redux Framework & Customizer API

### ISSUE THREAD

**Issue by AndreaBazerla** [reduxframework/redux-framework#2741]
Hi, I'm confused: can I use Redux Framework with Customizer API?

For example, I want to include in a section created with Redux a my custom button to execute a my script in JavaScript...but I don't want to pay any Redux's premium extensions, because code is free!

So I need to get the section's slug to include my custom button, it is possible?

(I've just see your campagne [here](https://ideas.reduxframework.com/campaigns/complete-customizer-integration/), is it in work in progress?)

Thanks

**Comment by kprovance** [comment]
<blockquote>
but I don't want to pay any Redux's premium extensions, because code is free!
</blockquote>
Thanks for the support.  Always appreciated.

However, premium support is NOT free, and that's what this falls under.

Sorry.
