### ISSUE TITLE
WordPress Visual Editor Problems.

### ISSUE THREAD

**Issue by frank6tg** [reduxframework/redux-framework#2742]
When in Visual Editor while Redux Framework Plugin is enabled, I'm unable to switch between Visual and Text mode, Unable to Add Media, Insert Links etc.

**Comment by kprovance** [comment]
https://github.com/reduxframework/redux-framework/blob/master/CONTRIBUTING.md

**Comment by kprovance** [comment]
No reply given.  Closing.
