### ISSUE TITLE
Does "Redux::hideSection" work? How?

### ISSUE THREAD

**Issue by edtheitguy** [reduxframework/redux-framework#2743]
WP 4.3.1
Framework: actual from git

I am trying to get the Redux::hideSection to work but it doesnt seem to work so I think maybe I am doing something wrong.
In Doc says use:

Redux::hideSection($opt_name, $id, $hide);

so i tried

Redux::hideSection($opt_name, 'layout', $hide);
and
$hide = true;
$id = 'layout';
Redux::hideSection($opt_name, $id, $hide);

my section code:

Redux::setSection( $opt_name, array(
'icon'      => 'el el-magic',
'id'		=>'layout',
'title'     => __('Layout', 'pf_settings'),
'desc'      => __('In the Section you set the Layout.'),
'fields'    => array(

array( 
'id'        => 'layout-type-activate',
'type'      => 'button_set',
'title'     => __('Select Layout Type', 'pf_settings'),
'subtitle'  => __('Choose what type of Layout you want to setup: Single, with 1 or 2 Cols', 'pf_settings'),
'desc'  => __('Simply click on a Button to pick a layout.', 'ucf_settings'),
'options' => array(
'1' => 'Single', 
'2' => '1 Col', 
'3' => '2 Col'
), 
'default' => '2'
),
array(
'id'        => 'layout-type1',
'type'      => 'section',
'title'     => __('Layout Type', 'pf_settings'),
'subtitle'  => __('Choose what type of Layout you want to setup: Single, with 1 or 2 Cols', 'pf_settings'),
 ),	
)
)
);

I also tried it on the type => section field with

Redux::hideSection($opt_name, 'layout-type1', $hide);

but it also didnt work.
Am I doing it wrong or is it a bug?
Thanks

**Comment by kprovance** [comment]
I was never able to get it to work.  Fields take a boolean 'hidden' argument, and that's what I've been using.

**Comment by edtheitguy** [comment]
@kprovance -> maybe helpful ;)
I played around with "::hideSection" and "::hideField"  both didnt work, so I digged into the code.
During my "bug hunt" I couldnt figure out why they shouldnt/didnt work until I rearranged my sample code.
It turned out that both "::hideSection" and "::hideField" MUST be inserted after the end of ALL sections then it worked, direct after the "to hide things" it was a 50:50 chance to work properly -> please test and add notice in docs.

Changing the status from "hidden" to "visible" via "button_set" or "switch" was easy, the only probem I had was that the hidden section/field would only appear after a page refresh. This was solved by adding " 'ajax_save' => false " to the "switching field".

Because the refresh takes a bit I added a critical notice field for the impatience users: "Changing this Option will reload the administration panel, it can take a few seconds to reload."

Another thing I found out is that a field " 'type' => 'section' " only works with "::hideField" and it will NOT hide the entire "section fields", the only way I could get that working is be adding a "foreach" -> maybe someone could dive into that and make it work out of the box ;)

My Sample Testing Code:
- tested on WP 4.1 / Redux: 3.5.7.10
- used on WP 4.3.1 / Redux 3.5.8.9

Redux::setSection( $opt_name, array(
	'icon' => 'el el-magic',
	'id' =>'hide-section',
	'title' => __('Hide Section', 'pf_settings'),
	'desc' => __('Hide A Section.'),
	'fields' => array(
			array(
				'id'        => 'info-des',
				'type'      => 'info',
				'style'		=> 'critical',
				'icon'		=> 'el el-warning-sign',
				'notice'    => true,
				'desc'      => __('Changing this Option will reload the administration panel, it can take a few seconds to reload.', 'pf_settings')
				),	
		array(
			'id' => 'hide-a-section',
			'type' => 'button_set',
			'ajax_save' => false,			
			'title' => __('Select Section To Hide', 'pf_settings'),
			'subtitle' => __('Choose which section you want to hide', 'pf_settings'),
			'desc' => __('1: Hide Sec1 + Sec2 Field 2, 2: Hide Sec2 + Sec3 Field1, 3: Hide Sec3 + Sec1 Field1, 4: Hide Sec3 SubSec and its fields.', 'pf_settings'),
			'options' => array(
				'1' => '1',
				'2' => '2',
				'3' => '3',
				'4' => '4'
				),
				'default' => ''
			),
		)
	)
);
Redux::setSection( $opt_name, array(
	'icon' => 'el el-magic',
	'id' =>'section-1',
	'title' => __('Section 1', 'pf_settings'),
	'desc' => __('Section 1'),
	'fields' => array(
		array(
			'id' => 'sec1-field-1',
			'type'      => 'textarea',
			'title' => __('Field 1', 'pf_settings'),
			'subtitle' => __('Sample Text Area', 'pf_settings'),
			'default'	=> 'Sample Text Area for Hide Section Field Test',
			),
		)
	)
);
Redux::setSection( $opt_name, array(
	'icon' => 'el el-magic',
	'id' =>'section-2',
	'title' => __('Section 2', 'pf_settings'),
	'desc' => __('Section 2'),
	'fields' => array(
		array(
			'id' => 'sec2-field-1',
			'type'      => 'textarea',
			'title' => __('Field 1', 'pf_settings'),
			'subtitle' => __('Sample Text Area', 'pf_settings'),
			'default'	=> 'Sample Text Area for Hide Section Field Test',
			),
		array(
			'id' => 'sec2-field-2',
			'type'      => 'textarea',
			'title' => __('Field 2', 'pf_settings'),
			'subtitle' => __('Sample Text Area', 'pf_settings'),
			'default'	=> 'Sample Text Area for Hide Section Field Test',
			),			
		)
	)
);
Redux::setSection( $opt_name, array(
	'icon' => 'el el-magic',
	'id' =>'section-3',
	'title' => __('Section 3', 'pf_settings'),
	'desc' => __('Section 3'),
	'fields' => array(
		array(
			'id' => 'sec3-field-1',
			'type'      => 'textarea',
			'title' => __('Field 1', 'pf_settings'),
			'subtitle' => __('Sample Text Area', 'pf_settings'),
			'default'	=> 'Sample Text Area for Hide Section Field Test',
			),
		array(
			'id' => 'sub-section-1',
			'type' => 'section',
			'subsection' => true,
			'indent' => true,
			'title' => __('SubSection 1', 'pf_settings'),
			'subtitle' => __('This is a SubSection for Hide Section Field Test', 'pf_settings'),
			), 			
			array(
				'id' => 'sec3-field-2',
				'type'      => 'textarea',
				'title' => __('Field 2', 'pf_settings'),
				'subtitle' => __('Sample Text Area', 'pf_settings'),
				'default'	=> 'Sample Text Area for Hide Section Field Test',
				),
			array(
				'id' => 'sec3-field-3',
				'type'      => 'textarea',
				'title' => __('Field 2', 'pf_settings'),
				'subtitle' => __('Sample Text Area', 'pf_settings'),
				'default'	=> 'Sample Text Area for Hide Section Field Test',
				),
		)
	)
);

$pf_settings = get_option('pf_vars');		
	if($pf_settings['hide-a-section'] == "1"){
		$hide_section = true;
		$id_section = 'section-1';
		$hide_field  = true;
		$id_field = 'sec2-field-2';
		}
	if($pf_settings['hide-a-section'] == "2"){
		$hide_section = true;
		$id_section = 'section-2';
		$hide_field  = true;
		$id_field = 'sec3-field-1';		
		}
	if($pf_settings['hide-a-section'] == "3"){
		$hide_section = true;
		$id_section = 'section-3';
		$hide_field  = true;
		$id_field = 'sec1-field-1';	

		}
	if($pf_settings['hide-a-section'] == "4"){
		$hide_field  = true;
		$id_all_sub_fields = array('sub-section-1','sec3-field-2','sec3-field-3');
		foreach($id_all_sub_fields as $id_fields){
				Redux::hideField($opt_name, $id_fields, $hide_field);
			}
		}		
Redux::hideSection($opt_name, $id_section, $hide_section);
Redux::hideField($opt_name, $id_field, $hide_field);
