### ISSUE TITLE
Append link after field by jQuery

### ISSUE THREAD

**Issue by meno010** [reduxframework/redux-framework#2745]
Hello, 
 Our Blog has this info
WordPress 4.3.2-alpha
Your version: 3.5.4.8
PHP 5.5.1

we only need to append link after field by jQuery

```
$('table#section-table-section-start1').after('<a href="link">click here</a>');
```
we added it to redux.js file but not work
Is there any way to do that?

**Comment by kprovance** [comment]
Modification of our core files is unsupported.  You should consider adding a JS file and enqueueing it separately.  However, that would fall under our premium support model.
