### ISSUE TITLE
Translate theme options of redux

### ISSUE THREAD

**Issue by Joseph-a** [reduxframework/redux-framework#2748]
Hi,
I checked the below ticket and do the same.

https://github.com/ReduxFramework/redux-framework/issues/1546

I added "load_theme_textdomain" before the redux without any hook, but in Russian language we will have this error! What do you think? It happened just for Russian and the other languages work like a charm.
Fatal error: Maximum execution time of 30 second exceeded in MY_PATH\inc\class.redux_api.php line 272

We increased the limitation of php execution time but nothing happened.

**Comment by kprovance** [comment]
https://github.com/reduxframework/redux-framework/blob/master/CONTRIBUTING.md

**Comment by kprovance** [comment]
Closing from lack of reply.
