### ISSUE TITLE
use redux framework to create option panel for each search form

### ISSUE THREAD

**Issue by widesoft** [reduxframework/redux-framework#2750]
I'm developing a search plugin , in this plugin user can create multiple search form , each search form has Its own settings . how it possible by redux framework ?

in the other words , how to crate specific option panel for each users search form ?

**Comment by kprovance** [comment]
Using the standard options panel?  Not in any easy way I can explain in one post.  Per user settings would require (if I understand you correctly) say, a select field that lists available users.  You'd have to write up some *serious* javascript to get each option field to save and recall each users settings, which would be a bit of an undertaking (and not something we could do for free).  Even then, it's not the best route to go.

However, if you are using a custom post type for individual search forms, our metaboxes extension might be helpful with that.  https://reduxframework.com/extension/metaboxes/

**Comment by widesoft** [comment]
tank for response
but , I want the user to have the ability to create multiple search form  and each form  has Its own specific settings 
in the other words , i want deference option panel based on search forms not users?

**Comment by kprovance** [comment]
I don't think you'll be able to use Redux in it's core form for such a thing.  If you are going the CPT route for your search forms, then metaboxes is probably the way to go.  I don't know anything about your design, and to advise on any matter outside of the Redux, we begin to get into premium territory.

**Comment by widesoft** [comment]
tanks - i read description  on  https://reduxframework.com/extension/metaboxes/ and I'm shore its my answer but Unfortunately i haven't Money to pay the price. most to find another way.

redux framework is good (and i think best )platform and i love it , thank you for leading this project.
