### ISSUE TITLE
PHP7 constructors

### ISSUE THREAD

**Issue by sybrew** [reduxframework/redux-framework#2752]
PHP 7 has deprecated PHP4 constructors. PHP5+ is required for WordPress, which allows for the function `__construct()` as the constructor.

/ReduxCore/inc/browser.php

`Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; Browser has a deprecated constructor in /../redux/ReduxCore/inc/browser.php on line 119`

**Comment by kprovance** [comment]
I'll see if there is an updated version of this code.  Someone else wrote it, and for such a small thing, I really don;t want to rewrite and test it at this point.  If you;d like to and submit a pull request, that would also be acceptable.  :)
