### ISSUE TITLE
QUESTION: Is there a way to list custom page templates in a select field?

### ISSUE THREAD

**Issue by edtheitguy** [reduxframework/redux-framework#2753]
WP: 4.4
Redux: actual from git

I am looking for a way to list all of my custom page templates in a select field ( or any other field )
My custom page templates are in a sub (template) folder.
I can list the "template name => file name" in an array and even provide a comma seperated "file name" list.
The problem is, I have no idea how to get that information into a select field.

Any Idea how this could work?

**Comment by edtheitguy** [comment]
I couldnt find anything that could do this, so I ended up with a workaround, here my sample code from testing, maybe usefull for others:
- tested on WP 4.1 / Redux: 3.5.7.10
- used on WP 4.4 / Redux 3.5.8.10
```
array(
	'id'        => 'custom-templates',
	'type'      => 'select',
	'title'     => __('Templates', 'pf_settings'),
	'subtitle'  => __('Installed Templates.', 'pf_settings'),
	'desc'  => __('Simply click here to choose one.', 'pf_settings'),
	'options' => List_Custom_Templates(),
	'default' => ''
	)
```
and this is the sample function to get my templates, remove the unwanted + path:
```
	function List_Custom_Templates() {
			$all_templates = array_flip(wp_get_theme()->get_page_templates());
				unset($all_templates['Redirect']);
					$my_templates = str_replace('page-templates/', '',$all_templates);
				$templates = array_flip($my_templates);
			return $templates;
		}

```
the function gives a list like below and it works perfectly for the fields 'options':
 ```
array(
    template-1.php => Template 1
    template-2.php => Template 2
    template-3.php => Template 3
)
 ```
use in code like everything else:  $your_option['custom-templates']

NOTE: This is sample code, for sure there is a "smarter way" I didnt look for during testing ;)

**Comment by kprovance** [comment]
My answer would have been to write PHP code to enumerate your templates and pass them  into the select options arg.  But, you figured it ouy.  :)
