### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by dvolsysop** [reduxframework/redux-framework#2755]
How do I reduce the surrounding margins between main menu and body content as well as between body content and footer in black. Not seeing where this is in css? Is there a line of code I can use in advance settings to reduce this space from 230 to 75px?  See http://philadelphiadance.org/main/

**Comment by kprovance** [comment]
This sounds like an issue you need to take up with the theme author.  We do not support themes that use our framework.  That is the responsibility of the theme author.  :)
