### ISSUE TITLE
how to solve this required: use add_theme_page instead add_submenu_page

### ISSUE THREAD

**Issue by uxdesignit** [reduxframework/redux-framework#2756]
hi, i'm trying to submit new wordpress theme to themesforest.net, but reviewer till say me fix this:

REQUIRED: framework.php. Themes should use add_theme_page() for adding admin pages.
Line 1426: $this->page = call_user_func( 'add_menu_page', $this->args['page_title'], $this->args['menu_title'], $this
REQUIRED: framework.php. Themes should use add_theme_page() for adding admin pages.
Line 1349: // wrappers and need to be appened to using add_submenu_page.
Line 1400: $this->page = call_user_func( 'add_submenu_page', $page_parent, $page_title, $menu_title, $page_permission
Line 1458: call_user_func( 'add_submenu_page', $this->args['page_slug'], $section['title'], $section['t

Can you give me some advice to solve this?
Thanks in Advances

**Comment by kprovance** [comment]
https://github.com/reduxframework/redux-framework/blob/master/CONTRIBUTING.md

**Comment by kprovance** [comment]
No reply.  Closing.
