### ISSUE TITLE
Request: When Custom Fonts extension will be available after overhaul?

### ISSUE THREAD

**Issue by vburlak** [reduxframework/redux-framework#2758]
Hi Redux team.

I'm interested when Custom Fonts extension will be available in Redux's Extensions store? I didn't purchased previous version, when it was available.
I saw #2568 . 
Just want to know any approximate release date.
Cheers!

**Comment by kprovance** [comment]
Sometime in the new year/  It still needs work.  it will also necessitate the need to obtain your own mashape key for font conversion and hosting that conversion process on your own server.  We will no longer be hosting that service.  We are adding the option to not include font conversion for those who do not wish to run their own conversion service.  We'll announce availability on our site when it's available.
