### ISSUE TITLE
Custom field not showing in customizer

### ISSUE THREAD

**Issue by developerzinan** [reduxframework/redux-framework#2760]
Hi, i made a simple custom text field and its working nicely in theme option. Its saving data and output is also fine but i didn't see it in customizer. Is there any reason ?

Importantly does sorter and multi-text field support customizer ?

**Comment by dovy** [comment]
That's why we built the advanced customizer extension, but it's not been released yet. We're deciding how to release it to those who didn't support the initial development. Email me directly if you're interested in it.  ;)   dovy@reduxframework.com
