### ISSUE TITLE
Sticky posts don't work with Select

### ISSUE THREAD

**Issue by freetruman** [reduxframework/redux-framework#2762]
I'm using the Select feature to allow for the selection of arbitrary lists of posts, and it works just great for this. Except for one thing: for scalability purposes, I don't want the post query to select *all* posts, so I set it to just fetch the most recent, say, 200. But in case I or another admin wants to select a post that is more than 200 back in the archive, it won't be available in that list.

The simplest workaround is to use stick posts to set specific posts jump up into this list. However, Redux appears to be ignoring stickies, even when I manually set the ignore_sticky_posts query argument to false (or 0). Can anyone advise?

My field settings:

	'fields' => [
		[
			'id' => 'my-article-list',
			'type' => 'select',
			'title' => 'My Artice List',
			'data' => 'posts',
			'args' => [
				'posts_per_page' => 200,
				'ignore_sticky_posts' => false,
			],
		   ],
	    ],

**Comment by kprovance** [comment]
Redux uses get_posts to retrieve this data.  Any specified arguments are passed directly to that call.  After looking at get_posts on the WordPress codex, it appears ignore_sticky_posts is not included, or supported.  I suspect that is used exclusively with wp_query.  The alternative might be to retrive your data using said query and feed it into the select field options arg.

**Comment by freetruman** [comment]
Okay, I came up with a workaround for this. The problem is a combination of get_posts not properly accepting ignore_sticky_posts -- I think this may be due to Redux code or something else on my setup rather than WP itself -- and also that even when the argument is properly set, get_posts ignores it unless the query is executing on the home page, and ->is_home is true.

So here's the hacky workaround. WARNING: I'm not sure what else is_home does, so this might have unforeseen circumstances. First, add the custom parameter 'force_stickies' into your Redux query args:

```
'fields' => [
[
    'id' => 'my-article-list',
    'type' => 'select',
    'title' => 'My Article List',
    'data' => 'posts',
    'args' => [
        'force_stickies' => true,
    ],
   ],
],
```

Then add this filter, which will force sticky behavior on queries with the 'force_stickies' parameter set to true:

```
function force_stickies( $query ) {
     	if ($query->get('force_stickies')) {
     		$query->set('ignore_sticky_posts', false);
     		$query->is_home = true;
     	}
}
add_action( 'pre_get_posts', 'force_stickies' );
```

Note that this approach should also work for invocations of get_posts elsewhere in WP.

**Comment by kprovance** [comment]
LOL.  I just said:
<blockquote>
Redux uses get_posts to retrieve this data. Any specified arguments are passed directly to that call.
</blockquote>

Translation:  It's not a Redux issue.  It's a WordPress get-Posts doesn't support the ignore_sticky_posts argument issue.

**Comment by freetruman** [comment]
Mr. Provance, when one of your users writes code to work around a limitation in your framework -- yes, your framework, because it's your framework that chooses to use get_posts, whatever the virtues of doing so, and doesn't offer a workaround for this issue -- and then goes out of his way to post a sanitized version for the benefit of your other users, it's rather poor form to mock him.
