### ISSUE TITLE
Section title and languages issue.

### ISSUE THREAD

**Issue by Joseph-a** [reduxframework/redux-framework#2763]
Hi,
I checked the codes and find out that you use "sanitize_html_class" in class.redux_api.php > line 259 that it returns empty when we use the redux in other languages and some text that doesn't have "A-Z,a-z,0-9,_,-" characters in it. For example translation of "Main Setting" is "Основным параметром" in Russian, as you can see it doesn't have any of the character that "sanitize_html_class" support, so it returns empty and the other fields in this section is not generated.
Please check and let me know how we can fix this issue.

**Comment by kprovance** [comment]
sanitize_html_class is a WordPress function.  We have no control over it.

**Comment by Joseph-a** [comment]
:) I know that it's a WordPress function, as you can see this function can causes some bugs in other languages, and the question is why you don't use other functions for fixing this issue. By the way I fixed my issue on my website, but it was a report for a bug.

**Comment by kprovance** [comment]
Such as?  If you have a solution that work, submit a pull request and we'll review it.  The truth is, I don;t have time or to research an alternative.

**Comment by Joseph-a** [comment]
I have no idea that it was OK or not but it works for me. I just replace the "sanitize_html_class" function to "sanitize_title" in line 259 of "inc/class.redux_api.php"

**Comment by kprovance** [comment]
Very good.  It'll be done next release.  :)
