### ISSUE TITLE
About function

### ISSUE THREAD

**Issue by mofizul21** [reduxframework/redux-framework#2764]
Hi,

I'm using Redux from 6 months ago. In new version showing a problem-

Redux::setSection($opt_name, array( // Applied in frontpage.php
  'title'     =>  __('Social Options', 'zboom'),
  'icon'      =>  'fa fa-twitter',
  'fields'    =>  array(
      array(
          'title'     =>  __('Social Icons', 'zboom'),
          'subtitle'  =>  __('Enter your social media link', 'zboom'),
  			 'type'      =>  'text',
          'id'        =>  'add_social',
          'options'	=>	array(
          	'1'	=>	'Facebook',
          	'2'	=>	'Twitter',
          	'3'	=>	'LinkedIn',
          	'4'	=>	'Google+',
          	'5'	=>	'YouTube',
          ),
      )
  )
));

Options value Facebook, Twitter, LinkedIn ... adding as input box value in admin area. As a result it's a creating value 1 and showing in front page.
Please see the photo- https://www.facebook.com/photo.php?fbid=552693354884309&set=o.243141545850368&type=3

I want that when people paste social URL from admin area, then only it will show in front page.

Can you remove the value from input box?

**Comment by kprovance** [comment]
You need to set blank defaults for your options.
