### ISSUE TITLE
Redux Repeater Out of Order

### ISSUE THREAD

**Issue by vincentjr** [reduxframework/redux-framework#2766]
In the admin section of our site we're starting to notice that entries are returning in the correct order after they are sorted, but some fields don't match

For example, this is part of the fields structure:
```
                array(
                    'id'          => 'name',
                    'type'        => 'text',
                    'title'       => 'Name',
                    'validate'    => 'not_empty'
                ),
                array(
                    'id'          => 'release-date',
                    'type'        => 'date',
                    'title'       => 'Date',
                    'validate'    => 'not_empty'
                ),
                array(
                    'id'          => 'misc-info',
                    'type'        => 'textarea',
                    'title'       => 'Misc. Info'
                ),
```

If we 3 add entries in the repeater as:
Name: Test1
Date: 1/1/95
Title: Test1

Name: Test2
Date: 1/1/96
Title: Test2

Name: Test3
Date: 1/1/97
Title: Test3

and then we sort the items as:
Name: Test2
Date: 1/1/96
Title: Test2

Name: Test1
Date: 1/1/95
Title: Test1

Name: Test3
Date: 1/1/97
Title: Test3 

Then we close the site, re-open admin, add another repeater item, and sort, we'll see:
Name: Test4
Date: 1/1/99
Title: Test4

Name: Test2
Date: 1/1/96
Title: Test3

Name: Test1
Date: 1/1/95
Title: Test2

Name: Test3
Date: 1/1/97
Title: Test1

Notice the title's no longer match the names. It's as if only the 'bind_title' is being sorted and displayed correctly. I recently updated to Wordpress 4.4.

**Comment by kprovance** [comment]
Extension issues go here, please:  https://github.com/reduxframework/redux-extensions/issues
