### ISSUE TITLE
select_image Field is not displaying saved values

### ISSUE THREAD

**Issue by brandexponents** [reduxframework/redux-framework#2767]
Hi, 

Thank you for this great tool. It has been awesome to build our entire Options Panel using your framework. I have not had any major issues with this in the past, however I am running into one now and am unable to fix it. 
I am using the most recent version of Redux Framework - 3.5.8.10. Since i updated the version, the <b>Select Image</b> field in my options panel is not retrieving any Saved Values. Is there something that is changed in the way values are saved? 

This is my code - 

<pre>
$sample_patterns_path   = get_template_directory().'/img/headers/'; //ReduxFramework::$_dir . '../img/headers/';
$sample_patterns_url    = get_template_directory_uri().'/img/headers/'; //ReduxFramework::$_url . '../sample/patterns/';
$header_patterns        = array();

if ($sample_patterns_dir = opendir($sample_patterns_path)) :
    $header_patterns = array();

    while (( $sample_patterns_file = readdir($sample_patterns_dir) ) !== false) {

        if (stristr($sample_patterns_file, '.png') !== false || stristr($sample_patterns_file, '.jpg') !== false) {
            $name = explode('.', $sample_patterns_file);
            $name = str_replace('.' . end($name), '', $sample_patterns_file);
            $header_patterns[]  = array('alt' => $name, 'img' => $sample_patterns_url . $sample_patterns_file);
        }
    }
endif;

// Field Declaration
$this->sections[] = array(
'title'     => __('Settings', 'be-themes'),
'desc'      => __('', 'be-themes'),
'icon'      => 'el-icon-cog',
'subsection' => true,
'submenu' => false, 
'fields'    => array(
        array(
            'id'        => 'opt-header-style',
            'type'      => 'select_image',
            'tiles'     => true,
            'title'     => __('Top Header Style', 'be-themes'),
            'subtitle'  => __('', 'be-themes'),
            'options'   => $header_patterns  ,
            'default' => 'style3',
        ), 
    )
);
</pre>

Thanks,
Swami

**Comment by dovy** [comment]
I don't think so. If you updated your config at all, you may have to "refersh/reset" the section to update the arrays properly. Give it a try and let us know.  :)

**Comment by kprovance** [comment]
No reply after 48 hours.  Closing.
