### ISSUE TITLE
set values to less variables using compiler

### ISSUE THREAD

**Issue by rob-ot-dot-be** [reduxframework/redux-framework#2769]
I'm able to use the compiler to write css to a file. But i'm looking for a way to write less variables instead.
any idea or direction where to start?

tnx

**Comment by dovy** [comment]
Run the compiler hook to launch an action. Grab your values, and pass them into your LESS compiler.  :)

**Comment by rob-ot-dot-be** [comment]
and then I had my 'ahaa' moment ...

for those who struggle also with the 'compiler'. the key for me was to understand that the compiler is not only a css compiler (thus the naming made it confusing). but can be used to write  almost anything to any kind of language you like (for ex JS)

The compiler get launched whenever a field has ` 'compile' => true `
setting an array with css classes will wrap the values into them, but this is not needed.

What i have done :
I say to use a 'lessCompile' action
`add_filter('redux/options/'.$this->args['opt_name'].'/compiler', array($this ,'lessCompiler' ), 10, 2);`

in this method, I grab the values of some fields and just write my own 'less' variables:

```
public static function lessCompiler($options, $css ) {
            $filename = dirname(__FILE__) . '/colors/generated-colors.less';

            $out = "@color-one:".$options['color-one'].";\n";
            $out .= "@color-two:".$options['color-two'].";\n";
            $out .= "@color-three:".$options['color-three'].";\n";
            $out .= "@color-four:".$options['color-four'].";\n";
            $out .= "@color-five:".$options['color-five'].";\n";
            $out .= "@color-six:".$options['color-five'].";\n";

            $r = ReduxFrameworkInstances::get_instance('in_d');
            $r->filesystem->execute(
                    'put_contents',
                    $filename,
                    array(
                            'content' => $out
                    )
            );
        }
```

I do use the redux filesystem class, I had this idea the WP on did not work properly 

Hope this is of use to someone.

Tnx for the help.
great framework
