### ISSUE TITLE
Redux panels not loading...

### ISSUE THREAD

**Issue by PulsarMedia** [reduxframework/redux-framework#2770]
Hi Guys,

I have a customer of mine who is running into an issue loading the Redux framework. The framework itself loads up fine but when i try to access any of the panels they all appear blank.

Here is a video to better illustrate what i am experiencing:
http://screencast.com/t/bombWM8LpL1j

If the video doesn't load for whatever reason here is an image for visual reference:
http://www.pulsarmedia.ca/images/quantum-issue.jpg

The framework works fine on my server so i am guessing my client's server may not be configured correctly to support Redux?

Here is the Support URL i generated from my clients installation:
http://support.redux.io/?id=r9fwJDdzNvOKsimFQby49JxyYkDyPfBhGGFNj2JArDyYh8VicJVKxgjPSWpgqOyFt1wgHnVPzqVGP6%2F78hMTRg%3D%3D

And some additional info:

WordPress 4.4
Redux version v3.5.8.10

Any help is appreciated, thanks.

**Comment by dovy** [comment]
Javascript error. Right click, inspect content and see what's wrong. 99% sure another plugin is messing things up.  ;)

**Comment by PulsarMedia** [comment]
I deactivated all plugins and there are no javascript errors being reported in the console...and its still not loading correctly :[

**Comment by PulsarMedia** [comment]
Actually there is one plugin that i can not decativate:

1&1 Product Subdomain

Its installed in the /wp-content/mu-plugins directory and its being executed automatically.

I will see if i can get my client to deactivate it.

**Comment by dovy** [comment]
Next step is to look at your network activity as the page loads and the HTML. There might be a PHP error output somewhere.

Also try adding WP_DEBUG => 1 in the wp-config.php file.

**Comment by PulsarMedia** [comment]
ok, i was actually just about to do that and when i did i saw the following error in the source:

<b>Fatal error</b>:  Uncaught Error: Function name must be a string in /homepages/11/d606375446/htdocs/clickandbuilds/DigitalCloudInnovations/wp-content/themes/quantum-theme/ReduxFramework/ReduxCore/inc/fields/raw/parsedown.php:797
Stack trace:
#0 /homepages/11/d606375446/htdocs/clickandbuilds/DigitalCloudInnovations/wp-content/themes/quantum-theme/ReduxFramework/ReduxCore/inc/fields/raw/parsedown.php(827): Parsedown-&gt;element(Array)
#1 /homepages/11/d606375446/htdocs/clickandbuilds/DigitalCloudInnovations/wp-content/themes/quantum-theme/ReduxFramework/ReduxCore/inc/fields/raw/parsedown.php(234): Parsedown-&gt;elements(Array)
#2 /homepages/11/d606375446/htdocs/clickandbuilds/DigitalCloudInnovations/wp-content/themes/quantum-theme/ReduxFramework/ReduxCore/inc/fields/raw/parsedown.php(49): Parsedown-&gt;lines(Array)
#3 /homepages/11/d606375446/htdocs/clickandbuilds/DigitalCloudInnovations/wp-content/themes/quantum-theme/ReduxFramework/ReduxCore/inc/fields/raw/field_raw.php(43): Parsedown-&gt;text('## Redux Option...')
#4 /homepages/11/d60637 in <b>/homepages/11/d606375446/htdocs/clickandbuilds/DigitalCloudInnovations/wp-content/themes/quantum-theme/ReduxFramework/ReduxCore/inc/fields/raw/parsedown.php</b> on line <b>797</b><br />

**Comment by PulsarMedia** [comment]
Hey Dovy,

Any idea what is causing that fatal error?

**Comment by dovy** [comment]
Are you using Markdown in any of your fields? It would seem like your raw field is causing issues.

**Comment by kprovance** [comment]
He has two raw fields.  One for his theme, and one (Odin knows why) for Redux Framework changelog.  The latter uses markdown.

I would suggest removing the raw field that discusses the redux framework change log.  It's not really needed for your clients, and may only serve to confuse them when it comes to support.  We get WAY too many theme users looking to us for support because of things like this.  Just take it out.  :)

**Comment by PulsarMedia** [comment]
Hi Kevin,

How exactly do i remove the change log field? I don't want to mess anything up further so please provide some details on the procedure.

Thanks.

**Comment by kprovance** [comment]
You need to get with whomever wrote your options panel and have them remove the "Documentation" section.

**Comment by kprovance** [comment]
Oh.  The issue itself is obvious to me now.  Your client is running PHP 7.0.  The markup code (which we did not write, it's vendor code) is only supported up to PHP v5.6.  They do not yet have an update.  Removing the Documentation panel will resolve this.

**Comment by PulsarMedia** [comment]
Thanks Kevin, that worked.

Appreciate the help :]

Cheers.
