### ISSUE TITLE
Invalid Arg foreach() when using Sorter field type

### ISSUE THREAD

**Issue by contempoinc** [reduxframework/redux-framework#2772]
Getting these two errors when using the Sorter field type in Version 3.5.8.10 was getting the same in v3.5.7 as well.

Screenshot: http://cl.ly/1N2y2Z3G073t

Warning: Invalid argument supplied for foreach() in /Applications/MAMP/htdocs/wordpress/wp-content/themes/realestate-7/admin/ReduxFramework/ReduxCore/inc/fields/sortable/field_sortable.php on line 44

Warning: Invalid argument supplied for foreach() in /Applications/MAMP/htdocs/wordpress/wp-content/themes/realestate-7/admin/ReduxFramework/ReduxCore/inc/fields/sortable/field_sortable.php on line 95

**Comment by kprovance** [comment]
Please review our posting guidelines:  https://github.com/reduxframework/redux-framework/blob/master/CONTRIBUTING.md

**Comment by dovy** [comment]
IE, we need a support URL.  ;)

**Comment by kprovance** [comment]
No reply after 48 hours.  Closing.
