### ISSUE TITLE
Border with 0px strange issue

### ISSUE THREAD

**Issue by fakeartist** [reduxframework/redux-framework#2774]
Hi. I have WordPress 4.4 and Redux 3.5.8.1 and I have the following issue. I have this field

    array(
    'id' => 'header_border',
    'type' => 'border',
    'title' => __('Header border', 'redux-framework-demo'),
    'all' => false,
    'default' => array(
        'border-color' => '#000000',
        'border-style' => 'solid',
        'border-top' => '0px',
        'border-right' => '0px',
        'border-bottom' => '0px',
        'border-left' => '0px'),
    'output' => array('.site-header'),
    ),

When I press Reset section or Reset all it works great. 

But if I change one of the values (let's say, set border-left to 1) and then press save, all the other fields become blank.

Is this a bug?

**Comment by kprovance** [comment]
Please review our posting guidelines:  https://github.com/reduxframework/redux-framework/blob/master/CONTRIBUTING.md

**Comment by kprovance** [comment]
I found the issue.  Resolved in 3.5.8.11

**Comment by fakeartist** [comment]
Thank you! Works like a charm.

**Comment by kprovance** [comment]
Donations to the project are always appreciated.  :)

**Comment by fakeartist** [comment]
Fair! Really appreciate your time and effort in this. Great work.
