### ISSUE TITLE
QUESTION: Call/Trigger Reset Section and/or Reset All from within a function?

### ISSUE THREAD

**Issue by edtheitguy** [reduxframework/redux-framework#2777]
I have a MultiSite Installation with an Admin Panel to control all installations and their own Option Panels, that perfectly works if I manually go to each site and hit the needed section reset button.
What I would like to do is trigger each sites section reset when saving the section on the main admin panel so that the new values are loaded into database without having to visit each page.
So, all I need to know is how I can "call / trigger" the reset, is there any "direct access" via url or function?
Thanks

**Comment by kprovance** [comment]
There is no way to do this via any function.  It's all handled via JavaScript and trigger via a button.  The only thing you could do via a function is to nuke the database key that holds the option data.  That key would be the opt_name arg in your config.
