### ISSUE TITLE
Theme check Warning with latest version of Redux

### ISSUE THREAD

**Issue by PulsarMedia** [reduxframework/redux-framework#2778]
Hey Guys,

You might want to fix the following Warning i am getting with the Theme check plugin:

Found a translation function that has an incorrect number of arguments. Function __, with the arguments 'If you like Redux please leave us a ★★★★★ rating. A huge thank you from Redux in advance!'

Themeforest reviewers are being really anal about theme check errors these days.

Thanks.

**Comment by kprovance** [comment]
Another case of URL splitting that needs to be undone.  I can either put it on the list of things that'll probably not get fixed anytime soon, or you can do a pull request.  Line 104 of welcome.php.  Remove the string concatenation.

**Comment by najafnaseem** [comment]
Hello,
i am getting these warnings but unable to resolve, please help
Warning: More than one text-domain is being used in this theme. This means the theme will not be compatible with WordPress.org language packs.
The domains found are tgmpa, lawyeria-lite, lawyeria, zerif-lite

**Comment by kprovance** [comment]
@najafnaseem - This is not a Redux issue.  It's a theme code issue.  Sorry.  Good luck.
