### ISSUE TITLE
I can't translate my theme option 

### ISSUE THREAD

**Issue by jackbui2014** [reduxframework/redux-framework#2780]
Dear,
I follow all steps given in this link https://docs.reduxframework.com/core/advanced/wpml-integration/ but still we are not success.
I can find my option string in WPML dashboard
![save](https://cloud.githubusercontent.com/assets/8417884/12049719/908b9202-af1d-11e5-88e3-a7c2e5609428.JPG)
However, my original option has been changed after I refresh page.
![slsl](https://cloud.githubusercontent.com/assets/8417884/12049726/ab300714-af1d-11e5-8d8b-820e357e95ad.JPG)
Please help me to solve this problem.
Thanks
Jack

**Comment by zindexsolutions** [comment]
Also i have same problem.

We follow all steps given in this link https://docs.reduxframework.com/core/advanced/wpml-integration/ but still we are not success.
Please check out wpml-config.xml file and config file of Redux in attached file
![1](https://cloud.githubusercontent.com/assets/16116433/12049758/b498c0f4-af11-11e5-8792-2f8c771b5bd6.png)
![2](https://cloud.githubusercontent.com/assets/16116433/12049760/bf20709e-af11-11e5-8ae7-bba5f079c44f.png)
let us know what we missing..
Thanks
Yuvraj Khavad

**Comment by anikitas** [comment]
Ok no problem,

Keep in mind that if you are in development phase and you add addiotinal strings in wpml-config.xml you might need to rescan the Theme from translations under WPML - Theme and plugins localization.

But i need clear examples from both of you:
opt_name
field id;s used in Redux
wpml-config.xml

I also don't know which WPML version you have.

Let's take as an example jackbui2014 case.

From the screenshot your opt_name seems to be jb_theme_options.

So you need to have as key name in your wpml-config.xml : jb_theme_options

Rescan Theme for translations: WPML - Theme and plugins localization
Select your admin textdomain : WPML - String Translation

When you translate a string you need ofcourse to select: Translation is complete and Save

**Comment by anikitas** [comment]
In Redux Settings you can specify a different name for your global variable than opt_name.
If you have already set a different value then you need to use your global variable for WPML.
By default is the same.

'global_variable' => '', // Set a different name for your global variable other than the opt_name

**Comment by zindexsolutions** [comment]
Hi @anikitas,
Thanks for message.
Please check out the zip file it's contain redux config file and wpml-config file at root.
[zi.zip](https://github.com/reduxframework/redux-framework/files/74793/zi.zip)

**Comment by zindexsolutions** [comment]
If you need online assess then i will provides you ftp details and wp-admin user name and password.

**Comment by anikitas** [comment]
I think you have an error in your wpml-config.xml. You have an additional closing key tag in the middle of the file. Also you can remove key with name Footer, as it is a section and not a field.

**Comment by anikitas** [comment]
[wpml-config.zip](https://github.com/reduxframework/redux-framework/files/74797/wpml-config.zip)

**Comment by zindexsolutions** [comment]
Yes , by mistake i sent you another file. Still have problem, after the adding you file.

**Comment by anikitas** [comment]
Can you find your admin text domain under: WPML - String Translation?

**Comment by zindexsolutions** [comment]
Yes,  
It shows like this http://awesomescreenshot.com/0d75io5822

**Comment by anikitas** [comment]
I think you have a more general problem. You still have some default sample code in your Redux config file. If you load only your config file you don't need this line. You have to disable the Demo config file and load only yours.

 // This line is only for altering the demo. Can be easily removed.
    $opt_name = apply_filters( 'redux_demo/opt_name', $opt_name );

You can try to remove it.

**Comment by zindexsolutions** [comment]
Ok
 
Let me check

**Comment by zindexsolutions** [comment]
Once I translate at string-translation menu in wpml it works. Text filed values changed 

But when i switch language at Theme Option at top menu at back-end values reaming same as English , it this possible to change values at  THEME Options.

For more details please check attached image .
![theme options vision research wordpress 2015-12-30 17-17-34](https://cloud.githubusercontent.com/assets/16116433/12050329/ccbee7b4-af19-11e5-9eb7-6b9644578a3f.png)

**Comment by anikitas** [comment]
The Flag will not affect anything in your Theme Options.
All admin text translations must be done via WPML interface.

The strings in your Theme Options must always be in English.

**Comment by zindexsolutions** [comment]
Ok, Then my problem is fix.
Text filed values is translate from WPML interface.

Thanks for Support 
Keep it Good Work Like this.

Thanks
Yuvraj Khavad

**Comment by anikitas** [comment]
@jackbui2014 Have you resolved your issues or you still have issues?

**Comment by jackbui2014** [comment]
Hi anikitas,
I haven't been  resolved my issues yet.
These are my Redux's config file and wpml-config.xml file

![problem](https://cloud.githubusercontent.com/assets/8417884/12060315/6a1d934a-af9f-11e5-9524-a54ff9fcef3f.JPG)


I already translate options on wmpl interface. However, my original option has been changed after I refresh page like the photos I post above.
Please help me to check it.
Thank you so much!
Jack

**Comment by anikitas** [comment]
From the field names and screenshots i'm not sure if you are trying to translate pages or redux options.
I don't see how you define your sections and how you use them in your Theme.

As i explained before the flag is not affecting any changes in Redux Theme Options screen.
Your initial translations strings regarding Theme Options must be in English.

Then you translate them only via the WPML interface: WPML - String Translation

I hope it helps!

**Comment by kprovance** [comment]
What @anikitas said.  You might also try contacting WPML support.
