### ISSUE TITLE
Getting custom taxonomy terms for select

### ISSUE THREAD

**Issue by Johnnychaos** [reduxframework/redux-framework#2781]
I'm trying to create "select" with terms from custom taxonomy "property_type" from my custom post type "property" but I can't get it work.
I try a solution I've found on some old posts here (https://github.com/reduxframework/redux-framework/issues/194) but it's not working for me.
```
array(
			'id'      => 'some_id',
			'type'   => 'select',
			'title'    => __( 'title', 'redux' ),
			'data'  => 'terms',
			'args'  => array('taxonomy' => 'property_type'),
		),
```
Any help will be appreciated :)

**Comment by kprovance** [comment]
Please review our posting guidelines:  https://github.com/reduxframework/redux-framework/blob/master/CONTRIBUTING.md

**Comment by kprovance** [comment]
I don't think that is a proper argument for terms.  See a list here:  https://codex.wordpress.org/Function_Reference/get_terms

**Comment by kprovance** [comment]
Oh, it should be this:  `array('taxonomies' => 'property_type')`
