### ISSUE TITLE
UTF-8 Character Problem

### ISSUE THREAD

**Issue by samiuygur** [reduxframework/redux-framework#2782]
Hi,
I have some text fields on Redux panel, When i save it with latin-extended character set, like Turkish lang characters, it saving ascii code of that characters, Wordpress saving properly, but Redux panel not, How can i fix it? 

Thank you so much, Redux is wonderful.

**Comment by kprovance** [comment]
This came up recently, and it looked to be a database setup issue.  Redux uses the WordPress settings API to do saving/retrieving exclusively, which means WordPress is saving settings.  The last individual who reported this I was never able to replicate.  All UTF/Unicode saved to the database as expected.  After looking up some issues reported at wp.org, it was determined that the users database wasn't supporting said characters, and unfortunately, that does not fall under the scope of our support.
