### ISSUE TITLE
[1] wp_remote_get() failed. [2] Fatal error:

### ISSUE THREAD

**Issue by WPExpert** [reduxframework/redux-framework#2783]
I just installed a new WordPress theme "Broker" and it uses Redux which is a first for me. 

Now I am seeing two errors which I believe have the same source. The homepage is only partially showing and the whole site cannot be seen unless you are logged in.

[1] wp_remote_get() failed. This is needed to get information from remote servers. Contact your hosting provider. Error: Failed to connect to reduxframework.com port 80: Network is unreachable

[2] Fatal error: Uncaught Error: Function name must be a string in /srv/users/serverpilot/apps/binaryopportunity/public/wp-content/plugins/redux-framework/ReduxCore/inc/fields/raw/parsedown.php:797 Stack trace: #0 /srv/users/serverpilot/apps/binaryopportunity/public/wp-content/plugins/redux-framework/ReduxCore/inc/fields/raw/parsedown.php(827): Parsedown->element(Array) #1 /srv/users/serverpilot/apps/binaryopportunity/public/wp-content/plugins/redux-framework/ReduxCore/inc/fields/raw/parsedown.php(234): Parsedown->elements(Array) #2 /srv/users/serverpilot/apps/binaryopportunity/public/wp-content/plugins/redux-framework/ReduxCore/inc/fields/raw/parsedown.php(49): Parsedown->lines(Array) #3 /srv/users/serverpilot/apps/binaryopportunity/public/wp-content/plugins/redux-framework/ReduxCore/inc/welcome/welcome.php(463): Parsedown->text('## 3.5.8.1\n* Fi...') #4 /srv/users/serverpilot/apps/binaryopportunity/public/wp-content/plugins/redux-framework/ReduxCore/inc/welcome/views/changelog.php(19): Redux_Welcome->parse_readme() #5 /srv/ in /srv/users/serverpilot/apps/binaryopportunity/public/wp-content/plugins/redux-framework/ReduxCore/inc/fields/raw/parsedown.php on line 797

**Comment by kprovance** [comment]
You need to contact the theme developer and report it to them as we do not support actual themes that use Redux.  If the theme author needs support, then he'll come to us.  They need to determine first if it's a code issue or a server issue.

**Comment by kprovance** [comment]
When you contract them, mention it's a PHP 7.0 issue, and he should update Redux to version 3.5.8.12, which addresses this.

**Comment by WPExpert** [comment]
On 1 January 2016 at 22:43, Kevin Provance <notifications@github.com> wrote:

> When you contract them, mention it's a PHP 7.0 issue, and he should update
> Redux to version 3.5.8.12, which addresses this.


​Thank you so much Kevin.​

​Terence.​

**Comment by commercegurus** [comment]
Hey @kprovance - we're the theme devs for the Broker theme.
A couple of quick points for clarity from our prior diagnosis that we did for @WPExpert that are relevant and should be repeated here as I suspect this isn't a Redux error - but an environment issue. But I'm open to be told otherwise after the data below is reviewed.

The Error strack trace from Redux and it refers to this Redux method

parse_readme()

I checked that method's source code and noticed this line

                return $Parsedown->text( trim( str_replace( '# Redux Framework Changelog', '', wp_remote_retrieve_body( wp_remote_get( ReduxFramework::$_url . '../CHANGELOG.md' ) ) ) ) );

You can see it does a wp_remote_get.

I then re-checked @WPExpert 's Redux status screenshot and noticed this

http://i.imgur.com/ro8poA4.jpg

So the issue is Redux isn't calling home to a dead server - it's trying to call home to a live server to grab it's changelog and parse it into the Redux welcome screen and it's being blocked.

So my assessment is that @WPExpert should open up wp_remote_get() and I reckon it should be fine.

Or this is a known issue specifically with PHP7?

Colm

**Comment by commercegurus** [comment]
I should also mention that Redux is not embedded - it's installed via TGMPA directly from the .org repo - the latest version there looks to still be 3.5.8.1

**Comment by WPExpert** [comment]
I spoke to the Serverpilot devs about this and this was their response ~

"By default we don't block any outbound ports in the firewall, so that could only occur if you customized the firewall. [OP: which I haven't]

When we've seen a similar error ("wp_remote_get() failed") it was because the remote site was down, and not a problem with the server itself. I tested reduxframework.com and it does appear to be down at the moment. I'd recommend contacting them if it doesn't return soon.

I tested on two different sites (see screenshots) so I'm confident their server is not responding properly.

It's possible that a new version of the Redux handles this better, but the root cause seems to be the server being down.

Attachment(s)
Screen Shot 2016-01-01 at 6.02.39 PM.png [https://serverpilot.zendesk.com/attachments/token/B9ezWRwfnN7aNasMVPWFymP9u/?name=Screen+Shot+2016-01-01+at+6.02.39+PM.png]
Screen Shot 2016-01-01 at 6.02.42 PM.png [https://serverpilot.zendesk.com/attachments/token/RaRf5WkW1ARgROkGfkN0oJuEn/?name=Screen+Shot+2016-01-01+at+6.02.42+PM.png]"

**Comment by WPExpert** [comment]
And http://reduxframework.com still appears to be down ~ http://screencast.com/t/11tWGWAZ7vB8

**Comment by WPExpert** [comment]
I switched the site from PHP 7 to 5.6 and I can now confirm it was a PHP 7 issue. However, the server access error [code]wp_remote_get() failed. This is needed to get information from remote servers. Contact your hosting provider. Error: Operation timed out after 5000 milliseconds with 0 bytes received
[/code] is still being reported.

I think. When it walks like a duck, and it quacks like a duck, you probably got yourself a duck.

**Comment by commercegurus** [comment]
Thanks @WPExpert for that info.

@kprovance - are you aware reduxframework.com has been down for most of the past 24 hours?

also, is there an ETA for these updates to be pushed over to the .org repo? That latest version over there is 3.5.8.1 and your changelog seems to go up to 3.5.8.12 at this point - sounds like a lot of users who install the plugin from .org will be running code that doesn't work on PHP7 

Thanks

**Comment by kprovance** [comment]
I'm aware of it, but it's out of my hands.  The host is experiencing some issues that I can do nothing about.

For now, install the version from our git repo.

**Comment by WPExpert** [comment]
The host must be back up and running now, because my wp_remote_get issue is gone, Redux has stopped clashing with the plugins sidebar menu, and since I swapped the site back to PHP 5.6 everything's sweetness and light.

**Comment by dovy** [comment]
I'll put a more permanent fix in place.  :)

**Comment by dovy** [comment]
Pushed a bunch of fixes for this that should suppress the issues from here on. Thanks for the feedback.
