### ISSUE TITLE
NewsFlash dependency on reduxframework.com

### ISSUE THREAD

**Issue by ahardin** [reduxframework/redux-framework#2784]
The following code (around line 418) of ReduxCore/framework.php represents a dependency on the reduxframework.com website being alive and well. Today there seemed to be an issue with reduxframework.com which basically introduced a 60 second delay to **every** page load (admin and non-admin) while the "news flash" request timed out.

```php
    if ( $this->args['dev_mode'] == true || Redux_Helpers::isLocalHost() == true ) {
        include_once 'core/dashboard.php';
        if ( ! isset ( $GLOBALS['redux_notice_check'] ) ) {
            include_once 'core/newsflash.php';
            $params = array(
                'dir_name'    => 'notice',
                'server_file' => 'http://www.reduxframework.com/' . 'wp-content/uploads/redux/redux_notice.json',
                'interval'    => 3,
                'cookie_id'   => 'redux_blast',
                );
                  
               new reduxNewsflash( $this, $params );
               $GLOBALS['redux_notice_check'] = 1;
        }
    }

I would dig into this a little further and submit a pull request for this, but I just don't have time. Sorry. 

Note: I see this code is wrapped in a check for `$this->args['dev_mode'] == true`. I don't have a ton of experience with Redux, so it's possible the theme I'm using (TheFox) simply doesn't give me the option to disable "dev_mode" so that this news flash isn't loaded all the time. But I would still think this code shouldn't be called as often as it is.

**Comment by kprovance** [comment]
You'll need to take this up with the author of the theme, the issue of dev_mode being enabled.  They need to disable dev_mode before shipping.  Otherwise, yes, the people who host our site are down.  I'll see about adding a catch to the newsflash code.

**Comment by driskell** [comment]
I had this same issue, due to isLocalHost returning true as I'm behind a proxy (Varnish). So any site using Redux Framework that is behind a proxy will inherently have Dev Mode enabled even though it shouldn't be, and as a result have a dependency on www.reduxframework.com. I will raise a new issue if it's felt better that re-opening this.
