### ISSUE TITLE
Call function on plugin activation

### ISSUE THREAD

**Issue by kmob2** [reduxframework/redux-framework#2785]
Hello,

Before I switched to redux, I simply called the function `flush_rewrite_rules()` inside the pugin activation_hook like so:

```
register_activation_hook( __FILE__, 'myplugin_activate' );

function myplugin_activate() {
    flush_rewrite_rules();
}
```

 
But now since redux is taking over the activation hook, how can I add `flush_rewrite_rules()` to that hook, without modifying redux core code?

**Comment by dovy** [comment]
Redux is not run on activation, so I suggest the following if you're using Redux as the "hook" for your app.

```
<?php
register_activation_hook( __FILE__, 'myplugin_activate' );
function myplugin_activate() {
    Redux::init('YOUR_OPT_NAME');
}
```

Good luck!
