### ISSUE TITLE
Bionick theme

### ISSUE THREAD

**Issue by gimbha** [reduxframework/redux-framework#2786]
Hey there,

Setting up the theme with my content, and a strange thing happened... the section titles on the home page pages have disappeared from one day to the next.

The information is entered into the specific page, and upon the site's loading it shows up the section subtitle correctly. It is similarly entered onto other pages that are NOT part of the home page... and they show up fine on those pages. It originally showed up perfectly on the front page/home page, too. Not sure what to try...

The site (in progress) is www.catchingfire.ca

Thanks!

**Comment by kprovance** [comment]
You need to contac the author of your theme.  We are not the author.  Apparently, the author left links to our support site in their theme.  They should have been removed.
