### ISSUE TITLE
Update Google Fonts only one time

### ISSUE THREAD

**Issue by br0k3n** [reduxframework/redux-framework#2787]
Hi,

I'm coding a new theme to sell on Themeforest marketplace. I there a way to update the fonts of google just once and then load the theme with the whole list? Is necessary that our API Key will be leave into the theme sold on Themeforest or can we remove it after the fonts update?

Thanks :)

**Comment by kprovance** [comment]
Yes.  See here:  https://github.com/reduxframework/redux-framework/issues/2776

**Comment by br0k3n** [comment]
Thanks, but after the update, can I remove my API Key keeping the fonts added?

Thanks

**Comment by kprovance** [comment]
See my previous reply, in which I answered, 'yes'.  :)

**Comment by br0k3n** [comment]
Thanks so much. I added the lines reported into my configuration file, but checking the Google developer console it reports 7 generic 4xx errors.

Please, could you help me?

Thanks so much

**Comment by kprovance** [comment]
Help with what, specifically?  I don;t know what 'google developer console' is.  If it's something outside of Redux, we don;t support it.
