### ISSUE TITLE
Warning: parse_str(): Input variables exceeded 1000.

### ISSUE THREAD

**Issue by M-olwan** [reduxframework/redux-framework#2789]
How to solve this error ??
Warning: parse_str(): Input variables exceeded 1000. To increase the limit change max_input_vars in php.ini. in /home/pulsarme/wp/energytest/wp-content/themes/energy-theme/ReduxFramework/ReduxCore/framework.php on line 2698

**Comment by kprovance** [comment]
At this point, you're going to have to make some more conservative design choices in your options panel, to keep the input variables under 1000.  We're working on a solution for this, but it's not complete.  I am unable to give you an ETA when.  Noteworthy donations to our project have been known to help speed things like this up.  :)
