### ISSUE TITLE
Remove notices

### ISSUE THREAD

**Issue by PulsarMedia** [reduxframework/redux-framework#2790]
Hey Guys,

How do i go about removing or disabling the following:

http://envato.d.pr/1gyWe/2U7cUdiT
http://envato.d.pr/1e7Iv/4a6YWsan
http://envato.d.pr/1aixb/4ze5N3P5

Another classic example of Themeforest reviewers being super anal about everything these days.

Thanks.

**Comment by kprovance** [comment]
See here:  https://github.com/reduxframework/redux-framework/issues/2729

Dovy was working on something about this.  Not sure the status.  TF goes after these kind of things when embedding Redux.  If you were to TGM it as a plugin, they shouldn't care.  That was the last I heard about it.

**Comment by kprovance** [comment]
I just released a new extension to deal with this:  https://reduxframework.com/extension/ad-remover/

Cheers.
