### ISSUE TITLE
Redux Framework has an embedded demo. Click here to activate the sample config file

### ISSUE THREAD

**Issue by dbaf** [reduxframework/redux-framework#2791]
I developed the theme. Redux Framework configuration file located in the theme directory. Himself ReduX Framework I installed from the repository Wordpress using the TGM. But when I install a theme, then this message appears

**Redux Framework has an embedded demo. Click here to activate the sample config file.**
and I need to click on the link for load my options!

How can I make so that my settings are automatically loaded?

functions.php in my theme
```php
/**
* Redux
*/
if ( class_exists( 'ReduxFramework' ) ) {
    require_once( dirname( __FILE__ ) . '/inc/options-init.php' );
}
```

**Comment by kprovance** [comment]
See the remove_demo function in the sample-config.php file of the Redux package.  Use that to remove the demo message, and then apply your own with whatever link/info you want to display.  To make that function run, you will need to uncomment out the following line:

//add_action( 'redux/loaded', 'remove_demo' );

**Comment by dbaf** [comment]
kprovance, many thanks for the answer!
