### ISSUE TITLE
Redux is not updating through the plugin

### ISSUE THREAD

**Issue by malguy** [reduxframework/redux-framework#2792]
A new build of Redux is now available!

Your version: 3.5.8.1
New version: 3.5.8.13

If you are not a developer, your theme/plugin author shipped with dev_mode on. Contact them to fix it, but in the meantime you can use our dev_mode disabler.

I have installed Redux Developer Mode Disabler and updated several times, but am still getting version 3.5.8.1

Please help.

**Comment by kprovance** [comment]
That is a developer notice for updates available via our git.  The dev_mode disabled is for theme users when the theme author does not disable dev mode.  If that notice bothers you, you can turn it off via global arguments.  https://docs.reduxframework.com/core/arguments/#update_notice
