### ISSUE TITLE
Undefined Index Error

### ISSUE THREAD

**Issue by krishna19** [reduxframework/redux-framework#2794]
Hi,
when i open theme options page, I'm getting this errors.
<pre>Notice: Undefined index: sortable in ../framework/admin/redux-framework/inc/fields/select/field_select.php on line 157</pre>

And Theme-Check plugin gives me the following error. Just now I updated to 3.5.8.13 and I get these error, before that I'm using 3.5.8.3 and I don't get these errors
<pre>
WARNING: Found PHP short tags in file framework/admin/redux-framework/inc/fields/raw/parsedown.php.

Line 765: if (preg_match('/^\[(.+?)\]:[ ]*<?(\S+?)>?(?:[ ]+['\'(](.+)['\')])?[ ]*$/', $Line['text'], $matches))

INFO: Possible hard-coded links were found in the file framework/admin/redux-framework/inc/welcome/welcome.php.

Line 478: &lt;a href=&#39;http://docs.reduxframework.com/&#39; class=&#39;docs button button-primary&#39;&gt;Docs&lt;/a

Line 481: &lt;a href=&#39;https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&amp;hosted_button_id=MMFMHW
</pre>

Redux: 3.5.8.13
Wordpress: 4.4

**Comment by kprovance** [comment]
I'll check on the undefined index.

That other stuff cannot be helped.  Otto himself, the author of theme check says INFO notices are ok (https://github.com/reduxframework/redux-framework/issues/2685).  The shorttag issue is not a real shorttag, as it's part of a regex statement.  This is a false notice

**Comment by kprovance** [comment]
Fixed in 3.5.8.14 - the index error.
