### ISSUE TITLE
Can't disable dev_mode in redux.

### ISSUE THREAD

**Issue by kajdzo** [reduxframework/redux-framework#2795]
Hi, 
First of all I want to thank you guys for creating this awesome framework.
I came across an issue with disabling dev_mode.
Here is my config.php file 
 $args = array(
        'opt_name' => 'theme',
        'dev_mode' => false,
        'use_cdn' => TRUE,
        'display_name' => 'ThemeOptions',
        'display_version' => '1.0.0',
        .
        .
        . rest of the arguments...
)
I'm using the latest version but I don't use redux as plugin, I embedded it to my theme. Any suggestions? Thanks.

**Comment by kprovance** [comment]
By design, if developing locally or when wp_debug is on, dev_mode will show.

**Comment by kajdzo** [comment]
Thanks very much! :)
