### ISSUE TITLE
show or hide custom option by button

### ISSUE THREAD

**Issue by adamski24** [reduxframework/redux-framework#2797]
Hello,
i have made some Options in redux for Ads and i would like to select from Button set which option i need to activate/show in the option panel.
exmaple

Google Ads or Normal Ads

when i select the Google Ads i need to see the Google Ads Options and hide the normal ads and same for Normal Ads

is there any way to make that by redux as i have made if option

             if($arrowcolors['ads-opt'] == 1) {
                 
                array(
                    'id'       => 'link',
                    'type'     => 'text',
                    'title'    => __( 'some text', 'arrowcolors-theme' ),
                );
                 
             }  else {
                 
                array(
                    'id'       => 'text2',
                    'type'     => 'text',
                    'title'    => __( 'some text', 'arrowcolors-theme' ),
                );
             }
                    endif; 

but i get error at the 1st line

**Comment by kprovance** [comment]
Use the required argument in the field you want to show or hide based on the button selection.

https://docs.reduxframework.com/core/the-basics/required/
