### ISSUE TITLE
remove notice in redux

### ISSUE THREAD

**Issue by ronak11** [reduxframework/redux-framework#2798]
Hi ,
i am useing  redux framework in my theme .it show notice in admin area . we disable dev mode but it show ad or notice .i want to submit my theme on Theme Forest plateform but they reject this theme due to  show redux advertise or notice .so please help me .
Thanks in advnced

**Comment by kprovance** [comment]
I just released a new extension to deal with this: https://reduxframework.com/extension/ad-remover/

Cheers.
