### ISSUE TITLE
Add custom fonts

### ISSUE THREAD

**Issue by kanha007** [reduxframework/redux-framework#2799]
I'm new to about Redux, plz share how to add custom fonts in existing drop down menu in Typography.

Thanks

**Comment by kprovance** [comment]
See the 'fonts' argument:  https://docs.reduxframework.com/core/fields/typography/

**Comment by kanha007** [comment]
i visited the url  but i couldn't find any solution. is there a need to add upload fields for uploading custom fonts?

**Comment by kprovance** [comment]
Redux does not offer that functionality.  In the future, we will offer a plugin that will.  No ETA when.
