### ISSUE TITLE
Theme and plugin both use Redux !

### ISSUE THREAD

**Issue by templatation** [reduxframework/redux-framework#2802]
Hi,

I had a customer today, with a problem that as soon as he activates certain plugin the Themeoptions disappear.

I investigated the issue, and figured that plugin author too is using Redux as their Options panel, and my theme too.

What I am doing is, placing the redux in a Framework plugin of mine ( the call is inside ! class exists Redux), and then I am adding options using a filter from my theme.
So the above call because false and my themeoptions doesnt not show up at all, if that plugin is active.

Customer insists that he wants to keep the plugin, what is suggested cure of this issue ?

Thanks in advance.

**Comment by kprovance** [comment]
This may take some more research on your part.  What happens if you disable this other plugin?  Do your theme options load then?  If so, that plugin developer should probably upgrade, as it might be using an outdated version.

**Comment by templatation** [comment]
Hi Kevin,

Thanks for quick reply, and yes, once the plugin is deactivated my themeoptions loads and works fine. Ok, I will inform the plugin developer about your suggestion to update.

**Comment by kprovance** [comment]
Closing.  Please reopen if additional information is available.
