### ISSUE TITLE
Editor issue 

### ISSUE THREAD

**Issue by pra98935** [reduxframework/redux-framework#2803]
We are using type editor for editor. but problem is that if we use editor under accordion section and user select visual part so i'm unable to write any text. but if we use editor without accordion then editor in visual mode properly working means we can type

**Comment by kprovance** [comment]
If you are a registered user of the Accordion field, then these issues need to go under our extensions issue tracker, for future reference.

There are issues with the editor field type inside an accordion (we have the same issue with the repeater field).  It has to do with the jQuery UI CSS, we think.  I or Dovy have not had the time to dive into it to determine why.  We had another used try to figure it out, and they could not.  It may stay on the know issue list for the foreseeable future.  Sorry.  :)

**Comment by pra98935** [comment]
We have solved out this issue thanks for your reply
