### ISSUE TITLE
Custom Field Type

### ISSUE THREAD

**Issue by kajdzo** [reduxframework/redux-framework#2804]
Hi, 
I'm trying to add custom field type in redux framework and I managed to do that using boilerplate you guys provided, thanks for that by the way, but I'm having issue enabling color picker on the custom field, whatever I do I always get input[type="text"]. I think my issue is here: 

 public function enqueue() {

            $extension = ReduxFramework_extension_scroll_color::getInstance();

        	wp_enqueue_style('wp-color-picker');
           
            wp_enqueue_script(
                'redux-field-scroll-color-js',
              	$this->extension_url . 'field_scroll_color.js',
                array( 'jquery', 'wp-color-picker', 'redux-js' ),
                time(),
                true
            );
            if($this->parent->args['dev_mode']){

            	wp_enqueue_style('redux-color-picker-css' );

				wp_enqueue_style(
				    'redux-field-scroll-color-css', 
				    $this->extension_url . 'field_scroll_color.css',
				    time(),
				    true
				);
       		}
        }

Any suggestion would be helpful. Thanks.

**Comment by kprovance** [comment]
Assistance with extensions fall under premium support.  It isn't covered under issue tracking for the Redux core.  Sorry.  :)

**Comment by dovy** [comment]
And you should use the extensions boilerplate to make new fields for yourself. It's rather strait forward.  :)

https://github.com/reduxframework/extension-boilerplate

**Comment by kajdzo** [comment]
Thanks for quick response guys. I really appreciate it. I'm glad that I can notify you that I figured it out. I had bug in my JS code and I fixed it. Thanks again for great support... :)
