### ISSUE TITLE
reduxfreamwork slider

### ISSUE THREAD

**Issue by develperwp** [reduxframework/redux-framework#2806]
hi  
Instead of the slide and what to let slides? 
 
 foreach($slider as $sliders)     
 
tnx

**Comment by kprovance** [comment]
I don't understand the question, or what it's in relation to.

**Comment by develperwp** [comment]
Tuts creat slider for redux.

**Comment by kprovance** [comment]
https://github.com/reduxframework/redux-framework/blob/master/CONTRIBUTING.md

**Comment by develperwp** [comment]
Video tuts ?

**Comment by kprovance** [comment]
If this is about tuts article, you might want to leave your comment on the article itself, in case we were not the author.  Posting it here without any type of reference doesn't really accomplish much.  :)
