### ISSUE TITLE
Featured Post/Blog Post

### ISSUE THREAD

**Issue by hprendergast** [reduxframework/redux-framework#2808]
Hello,

I am using the theme Glimmer and for some reason when I set a blog post as a featured post it removes it from my main blog roll. I would like to be able to post somethings as featured, but still have them remain in the main blog roll. Can you assist?

Thank you!
Holly

**Comment by kprovance** [comment]
We are not the author of your theme.  You need to contact them directly (and also ask they remove any and all references to Redux from their support menu).  Thanks.
