### ISSUE TITLE
Theme Check Error

### ISSUE THREAD

**Issue by geniuspro** [reduxframework/redux-framework#2809]
Hello. Thanks for theme awesome plugin.
I've integrated your plugin on our theme. But theme check shows me on some error. 

WARNING: Found a translation function that has an incorrect number of arguments. Function __, with the arguments 'If you like Redux please leave us a ★★★★★ rating. A huge thank you from Redux in advance!'
WARNING: Found a translation function that has an incorrect number of arguments. Function __, with the arguments 'If you like Redux please leave us a ★★★★★ rating. A huge thank you from Redux in advance!', 'redux-framework'
WARNING: fopen was found in the file parsers.php File operations should use the WP_Filesystem methods instead of direct PHP filesystem calls.
Line 415: $fp = $this->fopen( $file, 'r' );
Line 641: function fopen( $filename, $mode = 'r' ) {
Line 644: return fopen( $filename, $mode );

How can i fix it. I've read theme check docs and but can't found solution. 

Please help me guys. Thanks again.

**Comment by kprovance** [comment]
Please review:  https://github.com/reduxframework/redux-framework/blob/master/CONTRIBUTING.md

**Comment by kprovance** [comment]
Also, I don't believe we have a file called parsers.php in the Redux core.  Can't advise you on that one.

**Comment by kprovance** [comment]
Closing due to lack of reply.  Please feel free to repoen if/when you have the required information for us.  Thanks.
