### ISSUE TITLE
Spacing Field in Absolute Mode

### ISSUE THREAD

**Issue by ItalianWebStyle** [reduxframework/redux-framework#2810]
Trying to compile the CSS dynamically if I use the mode => 'absolute' nothing happens.

My version is 3.5.8

    array(
                'id'             => 'header-height-test',
                'type'           => 'spacing',
                // An array of CSS selectors to apply this font style to
                // absolute, padding, margin, defaults to padding
                'mode' => 'absolute',
                'all'            => false,
                // Have one field that applies to all
                //'top'           => false,     // Disable the top
                'right'         => false,     // Disable the right
                'bottom'        => false,     // Disable the bottom
                'left'          => false,     // Disable the left
                'units'          => array( 'px' ),      // You can specify a unit value. Possible: px, em, %
                'units_extended' => 'false',    // Allow users to select any type of unit
                'compiler' => array( '.menu-test' ),
                'output' => array( '.menu-test' ),
                //'display_units' => 'false',   // Set to false to hide the units if the units are specified
                'title'          => __( 'Padding/Margin Option', 'redux-framework-demo' ),
                'subtitle'       => __( 'Allow your users to choose the spacing or margin they want.', 'redux-framework-demo' ),
                'desc'           => __( 'You can enable or disable any piece of this field. Top, Right, Bottom, Left, or Units.', 'redux-framework-demo' ),
                'default'        => array(
                    'top'    => '150',
                    'units' => 'px'
                )
            )

**Comment by kprovance** [comment]
Please review:  https://github.com/reduxframework/redux-framework/blob/master/CONTRIBUTING.md

**Comment by kprovance** [comment]
Closing issue due to lack of reply.
