### ISSUE TITLE
color rgba issue

### ISSUE THREAD

**Issue by pra98935** [reduxframework/redux-framework#2811]
We are using type = "color_rgba" for color selection. if we use single time in section then it's working properly but if we use multiple time within same section then it's alert a message "There was a problem with your action. Please try again or reload the page." please resolved this issue.

**Comment by kprovance** [comment]
Please review and provide us with the required information:  https://github.com/reduxframework/redux-framework/blob/master/CONTRIBUTING.md

**Comment by kprovance** [comment]
Closing issue due to lack of reply.
