### ISSUE TITLE
Pages will show only to logged in users

### ISSUE THREAD

**Issue by Shadayy** [reduxframework/redux-framework#2813]
Hi,
After installing the redux framework all pages in my website will only show for logged in users, I'm new using the framework I don't know if there's an option for this or if I have done something wrong.

I'm using wordpress 4.4.1, PHP 5.4.33, Redux 3.5.9

**Comment by kprovance** [comment]
Please review:  https://github.com/reduxframework/redux-framework/blob/master/CONTRIBUTING.md

**Comment by kprovance** [comment]
Closing issue due to lack of reply.
