### ISSUE TITLE
no way to change anythink

### ISSUE THREAD

**Issue by Offensichtlich** [reduxframework/redux-framework#2814]
Hi,

I use the Bionick template new. My problem is I install the template and the necessary plugins but I can't activate there. General I can change styles and things but after saving is all away?!
Wordpress: 4.4.1
PHP: 5.6
Redux: 3.5.7.5

A another template and plugins works fine?!

**Comment by kprovance** [comment]
If Redux came with your template/theme, and there is an issue, you need to contact the template/theme author.  They need to be the ones to do the debugging.  Also, that version of Redux they are using is WAY outdated.  They need to upgrade.

**Comment by Offensichtlich** [comment]
Hi kprovance,
yes it comes from "webRedox" - okay - I write him.
Thanks a lot
