### ISSUE TITLE
How to add gallery field inside slide field

### ISSUE THREAD

**Issue by sanjay17kol** [reduxframework/redux-framework#2817]
How to add gallery field inside slide field

**Comment by kprovance** [comment]
I just told you by showing you the other post.  You have to write the code to do it yourself, with a field overload or an extension.  Please click that link above and review the answers.

**Comment by sanjay17kol** [comment]
Is this feature available in premium support

**Comment by kprovance** [comment]
For me to write you an extension that puts the gallery field inside the slide field will run you - at the minimum $300.00 for three hours worth of work.  Letting you know that up front.

**Comment by kprovance** [comment]
Closing.  If you need premium support in this matter, please let me know.
