### ISSUE TITLE
Output background image without using BACKGROUND field

### ISSUE THREAD

**Issue by ismaelyws** [reduxframework/redux-framework#2820]
Hi,

Since Customizer doesn't support the Redux Background field, how would I go about setting a background image for a section/dev? Use Media field?

I've been playing around with it but can't seem to figure it out.

If anybody have an example (code) of what they did that could help.

Thanks.

My code
========================
array(
                'id'       => 'hero-bg',
                'type'     => 'media',
                'title'    => __( 'Background', 'integral' ),
                'subtitle' => __( 'Change the background image. This will fill up the background of the welcome section. Click the "Upload" button to upload your background image.', 'integral' ),
                'compiler' => array('.hero'),
                'mode' => 'background-image',
	            'default'  => array(
                            'url' => get_template_directory_uri().'/images/bg-home.jpg',
                        )

                

            ),
=======================

**Comment by dovy** [comment]
We have the advanced customizer extension coming soon that allows these fields.  ;)

**Comment by kprovance** [comment]
Even so, I thought the media field has a thumbnail arg that would display the selected photo.

**Comment by ismaelyws** [comment]
@dovy I will be submitting the theme to the WP.org directory so it needs to use Redux without any additional extensions.

@kprovance It does display the thumbnail in Customizer but I need it to output the image as a background image in a div.

**Comment by ismaelyws** [comment]
Since the customizer doesn't support the background field, I need an alternative.

**Comment by kprovance** [comment]
<blockquote>
but I need it to output the image as a background image in a div.
</blockquote>

Where?  In the customizer itself?  I'm not sure that's entirely possible (Dovy is the resident customizer guru.  He would know better).

**Comment by dovy** [comment]
@ismaelyws there is a "way" to do it without the "Redux Advanced Customizer". hah. But it's a bit custom. Did it before...

**Comment by ismaelyws** [comment]
No on the front-end. The background field adds "background-image: URL TO IMAGE; to the .hero div.

I need it to do the same.

**Comment by ismaelyws** [comment]
@dovy how did you do it?

**Comment by dovy** [comment]
@ismaelyws email me:   dovy@reduxframework.com

**Comment by kprovance** [comment]
You want front-end code?  I don't mean to be a buzz kill, but that's PHP, and we charge premium services for that.  

You can use the media field outputs (as detailed here: https://docs.reduxframework.com/core/fields/media/).  Probably with inline CSS.

**Comment by ismaelyws** [comment]
@kprovance I don't think you understood my question. I was asking how do I use the media field to output a background image using inline css. Simillar to how the background field does it, since the Customizer doesn't support the background field.

**Comment by kprovance** [comment]
I understand that.  But that would involve me having to look at your project and give basic PHP advice, which I get paid to do otherwise.  It's a premium service.  I'm sorry if our customizer in its current form does not meet your needs, but it doesn't mean I'm giving away what little free time I have to teach PHP.

Please, read our posting guidelines.  It should have made *all* of this clear up front:  https://github.com/reduxframework/redux-framework/blob/master/CONTRIBUTING.md

**Comment by ismaelyws** [comment]
@kpodemski I really don't mind paying for a premium service. I wasn't aware this fell into that category.

**Comment by ismaelyws** [comment]
@kpodemski @dovy I figured it out gentleman!

I output the URL of the media (image) uploaded with inline css. Which is what the background field does anyway. Thanks for your help anyways and sorry for wasting your time.
