### ISSUE TITLE
JS Conflict - Video Embeds/Permalink

### ISSUE THREAD

**Issue by joeponzio** [reduxframework/redux-framework#2823]
When Redux is active (built into theme) on WP 4.4.1 running PHP 7, I paste a YouTube link in the WYSIWYG editor and it doesn't convert into a video (in the editor - appears fine on the front end). On a new post, when you blur off the title and the permalink is created, this appears before the permalink:

http://localhost/wp-content/themes/mytheme/includes/redux/ReduxCore/inc/extensions/customizer

**Comment by kprovance** [comment]
You understand Redux has no control over the WYSIWYG editor, right?  That's TinyMCE, which is part of Wordpress.

**Comment by joeponzio** [comment]
Yes, but it doesn't happen with v3.5.8.1. This is a brand new issue in v3.5.9 on a fresh install - no plugins. The problem isn't with the WYSIWYG...perhaps an ajax issue.

**Comment by kprovance** [comment]
I'm doubting it.  I don't have PHP 7, so there's not way for me to know.  Either way, if we could please do this the correct way:  https://github.com/reduxframework/redux-framework/blob/master/CONTRIBUTING.md

**Comment by joeponzio** [comment]
Had to revert back to 3.5.8.1 to generate the support URL for the same issue - a javascript error due to the output of that same url which caused the URL generation to fail. I'll close this issue here but feel free to contact me if you need me to test anything in my environment.
