### ISSUE TITLE
Twitter Icon 

### ISSUE THREAD

**Issue by logonom** [reduxframework/redux-framework#2824]
Hey, this is very urgent so I would appreciate a reply as soon as you can.

The social media icon displayed in the top right does not redirect to the URL, it just lands on the same page where it is http://www.cranberrymanagement.com/

What could be the issue here?

Thanks,

Jay

**Comment by kprovance** [comment]
Please contact the theme author for support, since we did not author the theme.  They left support links for Redux in his theme and forgot to take them out, which mistakenly led you here.  When you contact him, please ask him to remove those Redux support links from his theme.
