### ISSUE TITLE
Demo date

### ISSUE THREAD

**Issue by anujoshi10** [reduxframework/redux-framework#2825]
Hi,
I have purchased your theme from themeforest.net. Trying to install dummy data. .
According to your theme documentation I have checked "Appearance > Benz Demos" and try to find "theme demo" but unable to find it :(

Can you please help me to how do I do that?
OR
Can you please send me dummy data XML file for the same?

Check attached files for more details.

![dummydatadoc](https://cloud.githubusercontent.com/assets/353837/12550790/f7beeece-c38b-11e5-80b1-65fba206190c.PNG)
![dummydata](https://cloud.githubusercontent.com/assets/353837/12550803/10dd0c06-c38c-11e5-8038-48237da1df52.png)

**Comment by kprovance** [comment]
We are not theme authors.  You didn't buy this theme from us.  The theme author forgot to remove support links to us as he is using our framework in his theme..  Please contact him for support, and suggest he remove links to Redux in his theme.
