### ISSUE TITLE
There was a problem with your action. Please try again or reload the page

### ISSUE THREAD

**Issue by davidfsd** [reduxframework/redux-framework#2827]
I used Redux Builder to start my project.

What I have now is:

Wordpress: 4.4.1
Redux Framework version: 3.5.8

Everything working fine, including Wordpress->Customize.

I receive the warning about the new version:

Redux Framework: 3.5.9.1

I downloaded all files from Github and I updated the following folders and files:

assets - core - inc - languages - templates - framework.php (entire ReduxCore folder)

When I tried save some stuff, I received the following message:

"There was a problem with your action. Please try again or reload the page."

My console:

`Uncaught SyntaxError: Unexpected end of input
There was an error saving. Here is the result of your action:
http://rebecca.dev/wp-content/themes/duck2go/admin/redux-framework/inc/extensions/customizer/{"status":"success","options":{"last_tab":"","opt-text":"","text-example":"","textarea-example":""},"errors":null,"warnings":null,"notification_bar":"<div class=\"saved_notice admin-notice notice-green\"><strong>Settings Saved!<\/strong><\/div><div class=\"redux-save-warn notice-yellow\"><strong>Settings have changed, you should save them!<\/strong><\/div><div class=\"redux-field-errors notice-red\"><strong><span><\/span> error(s) were found!<\/strong><\/div><div class=\"redux-field-warnings notice-yellow\"><strong><span><\/span> warning(s) were found!<\/strong><\/div>"}`

When I tried to use Wordpress->Customize it's showing on top of the page.

http://rebecca.dev/wp-content/themes/duck2go/admin/redux-framework/inc/extensions/customizer/

![screenshot from 2016-01-25 18 36 01](https://cloud.githubusercontent.com/assets/16630637/12563692/ab006656-c392-11e5-9595-c15f7acb7410.png)
![screenshot from 2016-01-25 18 37 00](https://cloud.githubusercontent.com/assets/16630637/12563693/ab06abf6-c392-11e5-9579-a0b7b1ba521e.png)

**Comment by kprovance** [comment]
Addressed in v3.5.9.2.  Please upgrade from this repo asap.  Thanks.
