### ISSUE TITLE
Can't access theme options page with full admin permissions

### ISSUE THREAD

**Issue by bruno-thisfunctional** [reduxframework/redux-framework#2829]
I got a project to make a few modifications, however when I try to access the theme options page I get an error: "You don't have permissions to access this page".

I've used plugins to change roles and capabilities, changed it in the db myself, and looked around the files to check for anything unusual.

The website uses the redux framework with a theme I believe it's called shopkeeper, can't be sure because who developed the website changed the plugins and themes names :(

I don't have contact with who developed it

Plus the first admin created was deleted from the database.
My guess is that who developed the website created a custom role to access the theme options and when he/she deleted the user and role the access got "damaged"... Is there anyway to check this?^

Or if you have any other idea please share.

**Comment by kprovance** [comment]
I'm not sure how this is a Redux issue.  Please observe our posting guidelines:  https://github.com/reduxframework/redux-framework/blob/master/CONTRIBUTING.md

**Comment by bruno-thisfunctional** [comment]
I've posted it in the wordpress support and they suggested to come here, since this uses Redux and probably I've to change Redux files in order to "reset" the permissions needed I thought it's an acceptable Redux support issue.

**Comment by kprovance** [comment]
Redux is set by the theme author.  You should probably consult with them first, especially if it's a permissions thing.  Now, since you won't supply a support URL or other relevant information, there's nothing more I can do now.  Contact the theme author.

**Comment by dovy** [comment]
If you submit a support URL we can tell you what you may need to change in your config so you could access the page.  :)
