### ISSUE TITLE
How use Extension in redux?

### ISSUE THREAD

**Issue by ronak11** [reduxframework/redux-framework#2830]
Hi,
i am use redux in my theme for theme options.Use sample-config file in theme for theme option .i want to use more fields like accordian,icon select but i ca'n understand how use loader.php for load extension so help me with example so i can use in my theme and make more feature.
Thanks in advanced

**Comment by kprovance** [comment]
Those are premium extensions that require purchase before they can be used.

https://reduxframework.com/extensions/
