### ISSUE TITLE
Options page strings don't translate

### ISSUE THREAD

**Issue by KEYwebdesign** [reduxframework/redux-framework#2831]
I'm using Redux Framework (3.5.9) as a plugin to use in my custom theme but I can't seem to get the English strings to display in the language that I set. It keeps showing the "Save Changes" button instead of the Dutch translation.

I set the language in my Wordpress install (4.4.1) and to be sure I but the WPLANG rule in my wp-config file. Nothing worked.
Then, I downloaded the .po file from Transifex to try and include that but no luck.

What can be the problem?

**Comment by kprovance** [comment]
Please review out posting guidelines and submit the required information.  Thanks!

https://github.com/reduxframework/redux-framework/blob/master/CONTRIBUTING.md

**Comment by KEYwebdesign** [comment]
Support URL: http://support.redux.io/?id=txxYb1M0g%2BJW4PcsnUE4wFYCqU8Gxpg9GXDTxEmAEXSGBL%2BRQrEd9QErWznIHT311Q34QezEOj3TkyU5DoWpjQ%3D%3D

Wordpress version 4.4.1, Redux Framework (plugin) version 3.5.9, which is the latest version of the plugin!
And furthermore I am a developer wishing to use the framework (as a WP plugin) in my own custom WP theme.

**Comment by kprovance** [comment]
Fixed with v3.5.9.3.  Please update from this repo.
