### ISSUE TITLE
Style conflict

### ISSUE THREAD

**Issue by dejann** [reduxframework/redux-framework#2832]
When I activate Revolution slider plugin Redux menu list font becomes bolder.
Revolution slider is probably loading Open Sans font-weight: 700; in admin dashboard.

The following CSS classes should have font-weight: 600; instead of font-weight: bold;

 `.redux-sidebar .redux-group-menu li a` and `.redux_field_th`

Here is the comparison:
http://imgur.com/a/zphaZ
Top image is with Revolution slider on

**Comment by kprovance** [comment]
Fixed with v3.5.9.3.  Please update from this repo.

Seriously tho, those Rev Slider guys need to not load all their CSS on every admin page.  Sloppy, IMO.  That was part of the problem.  The other half was our outdated CSS.
