### ISSUE TITLE
Getting error message when trying to save options

### ISSUE THREAD

**Issue by viraleditorial** [reduxframework/redux-framework#2833]
I am using a theme powered with redux framework . Everytime i try to save options it gives me an error

> There was a problem with your action . Please try again or reload the page.

I read some discussions and tried to create support HASH but that failed too

> There was an error please try again . 

I am using latest version of Redux Downloaded from github

**Comment by kprovance** [comment]
Chances are you have some echo or print_r (or php error) outputting that is interfering with the process.  Open the console log and past back everything.

**Comment by viraleditorial** [comment]
where to find console log ??

**Comment by kprovance** [comment]
You really need to review this first:  https://github.com/reduxframework/redux-framework/blob/master/CONTRIBUTING.md

**Comment by kprovance** [comment]
Closing due to lack of reply or necessary information.
