### ISSUE TITLE
 image select issue with  'tiles'    => true,

### ISSUE THREAD

**Issue by uxdesignit** [reduxframework/redux-framework#2835]
Hi, i found this issue: image select seem does not work properly with  'tiles'    => true
after render, i see html code for this, it returns wrong value. Eg:

<input type="radio" value="http://localhost:86/wpunyson/wp-content/plugins/redux-framework/ReduxCore/../sample/patterns/tree_bark.png" name="redux_demo[opt-patterns]" id="opt-patterns_1" class=" noUpdate " checked="checked">

Incase value  should be numeric e.g: value  = "1" . 

Notes it work well if  'tiles'    => true is not set

just for more detail, this bug raised with clean redux plugin install with  'tiles'    => true

**Comment by kprovance** [comment]
https://github.com/reduxframework/redux-framework/blob/master/CONTRIBUTING.md

**Comment by uxdesignit** [comment]
just for more detail, this bug raised with clean redux plugin install with  'tiles'    => true

**Comment by kprovance** [comment]
That is not more detail.  I asked you to review the link I provided and supply the required information.  If this is not possible for you to do, then please close the ticket.
