### ISSUE TITLE
Server Requirements List?

### ISSUE THREAD

**Issue by contempoinc** [reduxframework/redux-framework#2837]
Searched the docs couldn't find anything, is there a server requirements list I've had a few buyers recently run into issue with the framework not working, panels not loading, etc…no errors in the console and no errors being thrown with debug. One of them moved from GoDaddy to Bluehost and that solved the issue so that tells me its gotta be something not installed or enabled on the server. So in that case do you guys have a server requirements list that you can supply that I could pass on to their host?

**Comment by contempoinc** [comment]
This only started happening in version 3.5.9.1, I've grabbed the latest version 3.5.9.3 and am releasing an update to my theme with that today. But something must have changed in that update that requires a certain module to be installed on the server that some might not have.

**Comment by kprovance** [comment]
The requirements are no different that those of WordPress.  But as with all things, I can;t make any guesses with so little information.  GoDaddy is a bleedin' nightmare for WordPress.  It's always some config issue (and a premium support issue for us to go in and debug it, *especially* because it's GoDaddy).  I would also make sure those clients are using something newer than PHP 5.2.  At least 5.3 or higher, if possible.

The only thing you can do is dig deeper.  I would go into the PHP logs (and good luck with that on a GoDaddy server) and begin combing it for errors relating to Redux.  If you find some, post them back.

We did add some experimental code for saving without the max_input_var limit, but that shouldn't prevent load issues.  Again, if you can go through those logs and look for notices and errors, that would be incredibly helpful.

**Comment by contempoinc** [comment]
Yeah I totally understand, GoDaddy is garbage hosting — every time I would go back and forth with my buyer she would contact GoDaddy and they'd blame the theme, ridiculous run around they wouldn't check raw logs. The only thing I did see is that when any kind of XML file was uploaded via FTP for the Redux Demo Importer extension it would deny the file and refuse the connection but that doesn't have anything to do with the panel itself only the importer files. Absolutely no errors in the console or with debug enabled either impossible to debug.

**Comment by contempoinc** [comment]
Is there anything that changed in v3.5.9.1 vs 3.5.9 that would require extra server reqs? All of these buyers that have reported the issue its come when I released the update with v3.5.9.1 release.

**Comment by kprovance** [comment]
Here...saves me trouble of typing it all out:  https://github.com/reduxframework/redux-framework/blob/master/CHANGELOG.md

No new args.  Just the max_input_var saving, and a dir path check for the extension loader.

If you want to check (upgrade to 3.5.9.3 first, so our line numbers match), you can go into framework.php, comment out line 2821 ($values = $this->redux_parse_str( $_POST['data'] );) and uncomment out line 2818 (//parse_str( $_POST['data'], $values );).  Doing that will undo the new ajax_save method.

Also, you could go into ReduxCore/inc/extensions/customizer and in extension_customizer.php comment out lines 89 - 91, which will undo the change there.

Those two things were the only major changes.

**Comment by kprovance** [comment]
Also, I;ve seen these things happen because of memory issues. I can only assume GoDaddy will not let you adjust the php.ini settings as well?

**Comment by contempoinc** [comment]
Ok, thanks! If it were a memory issue wouldn't the normal error "bytes exhausted…" show up?

**Comment by kprovance** [comment]
Oh yeah, that should be plenty.  Usually - if asked - I would say:

The following PHP.INI settings need to be adjusted accordingly:
max_execution_time = 600
memory_limit = 256M
post_max_size = 64M

Also, add or adjust the WordPress wp-config.php settings:
define( 'WP_MEMORY_LIMIT', '256M' );
define( 'WP_MAX_MEMORY_LIMIT', '512M' );

They got to let you into those logs.  That's the only way we're going to know for sure.  But  in the interim, rollback those things and see if it helps any.

**Comment by kprovance** [comment]
or adjust the php.in so it displays ~W_ALL errors.  With WP_DEBUG set, everything should output on screen (assuming GoDaddy doesn't have some custom thing in place to mess with that too.)

**Comment by contempoinc** [comment]
Yeah, rolled back to even further than 3.5.9, also added those two lines to wp-config.php still the same issue has to be a server setting, he's contacting his host to get the logs.

**Comment by contempoinc** [comment]
Got the logs not sure what to look for though?

https://gist.github.com/contempoinc/42667c69dce679211851

**Comment by contempoinc** [comment]
Looks like he got it working just needed to add this to his .htaccess

AddType application/x-httpd-php53 .php

**Comment by kprovance** [comment]
Those are access logs.  We need the error logs.

**Comment by kprovance** [comment]
PHP 5.2.  UGH I KNEW IT!!!!  FREAKIN GO DADDY!!!

Awesome.  That would have been my next suggestion.  :)

**Comment by kprovance** [comment]
I'll close then.  Cheers.
