### ISSUE TITLE
selecting terms from post_terms

### ISSUE THREAD

**Issue by slamorte** [reduxframework/redux-framework#2839]
Redux is awesome! Thanks so far it's a key part of our build.

I'm trying to select a handful of terms from post_terms to put into $site_options. 

        array(
          'title'	=> 'Trending Menu',
          'subtitle'	=> 'Select Tag Terms to feature in the Trending Menu. Maximum 8 terms.',
          'id'          => 'trending-news',
          'type'      => 'select',
          'data'      => 'tags',
          'args'     => array(
            'taxonomies'=>'post_tag',
            'args'    => array(
              'hide_empty'  => 1,
              'number'      => 10,
              'orderby'     => 'count',
              'order'       => 'DESC',
            ),
          ),
          'multi'     => true,
          'sortable'  => true,
        ),
I've read the docs and several user-posted examples and my code seems correct, but I have two problems:

1. the second args seem to be unprocessed — I get all terms unsorted.
1. it takes forever to generate the select list because the lookup starts as soon as the field is clicked. A one second delay to allow a few characters to be typed would provide much better performance. The delay causes Unresponsive Script errors.
1. when attempting to save changes, page generates an error "There was a problem with your action. Please try again or reload the page." Upon reload the selected terms appear to be saved though. 

I did find issue #194 which suggested an error in functions.php and I modified line 943 to read `$terms = get_terms( $taxonomies, $args['args'] ); // this will get nothing` but it still does not pass the args to get_terms. 

Thanks, Scott

Support URL: http://support.redux.io/?id=dzrj6GF%2FqLEnln5DUpYH5mbGqbBf8KfgrRDoKTg0XV%2BNupLVpJakmZyLnVoQL%2BstyPTaAL52u6OgpFqyHAirmg%3D%3D

**Comment by slamorte** [comment]
I think I've solved it. 

Issue #613 provided the answer. Leave the `['args']` out of frameworks.php, but construct the section field without the nested args. As 613 says:

> And just make sure that all term args are added into the top level of the $args array (along with the 'taxonomies' arg string) all is well as the taxonomies element of the array is unset."

So my array is: 
```
         array(
          'title'  => 'Trending Menu',
          'subtitle' => 'Select Tag Terms to feature in the Trending Menu. Maximum 8 terms.',
          'id' => 'trending-news',
          'type' => 'select',
          'data' => 'tag',
          'args' => array(
            'taxonomies' => 'post_tag',
            'hide_empty' => 1,
            'number' => 2000,
            'orderby' => 'count',
            'order' => 'DESC',
          ),
          'multi' => true,
          'sortable' => true,
        ),
      )
    );
```

Searches are speedy, Save works correctly, items are property sorted. But one issue I am having is some terms are not being found — term 'election 2106' has 4 posts but is not found when typing 'election' or '2016.'

**Comment by slamorte** [comment]
Note that because this non-nested args arrangement is counter to the Codex provided examples for get_terms, and because I see a half-dozen people hitting this same wall in your issues, I'd like to suggest putting a term select code example on the [Core / Fields / Select documentation page](https://docs.reduxframework.com/core/fields/select/). Feel free to use my example!

**Comment by kprovance** [comment]
I'll add it to the list of things that need to eventually get done.  :)

Closing, if solved.

**Comment by slamorte** [comment]
Turn on site comments and I’ll add the user-suggested code myself. =)

**Comment by kprovance** [comment]
Yeah, that was a spammy mess, and why they got shut off.  Submit them to support@reduxframework.com.  :)

**Comment by slamorte** [comment]
Or give me the keys to the site and I’ll edit the page for you. =)

**Comment by kprovance** [comment]
Let's start with submitting.  I tend not to give people I don;t know keys to my house.  :P
