### ISSUE TITLE
Warning: call_user_func_array() expects parameter 1 to be a valid callback, 

### ISSUE THREAD

**Issue by swapnil2430** [reduxframework/redux-framework#2840]
Hi There,

we are using this plugin in more then 3-4 themes and they are working very well but we recently buy a new theme and that supports this plugin as it recommend to install and we had contact with the theme developer and they are not able to help us so we are really disappoint with them. They are telling that there theme is supported this plugin but we don't know why it is not working on your website. 
In the backend and on the front end of the header it display this Warning message as below.
  
Warning: call_user_func_array() expects parameter 1 to be a valid callback, function 'redux_register_custom_extension_loader' not found or invalid function name in /home/../public_html/../wp-includes/plugin.php on line 525

I have find some of the article on google to and try to solve it but not success so our last hope is you guys. Please help us.

Thanks

**Comment by kprovance** [comment]
Well, the hard reality is you paid them for your theme, which includes support.  We aren't getting paid at all, by you or them.  The theme author pushing it on is is completely inappropriate.  If there is a problem with Redux, THEY need to come to us, not their end users (you) as burden you with their responsibility is wrong, and unprofessional.  Problem is, I can't begin to examine this issue without access to your server and install, which is a premium service for us to do on behalf of theme authors.

What theme, specifically?  And the author?  I'll take this up with them.

**Comment by kprovance** [comment]
See, 'redux_register_custom_extension_loader' isn't even part of our core.  It's part of the extension loader, which suggests the theme author is either using one of our extensions improperly, or they wrote their own, which again, falls under their responsibility.  They need to debug this, not you, or us.  Again, get me a contact point, and I'll find out what's wrong.

**Comment by swapnil2430** [comment]
Well i just try to reinstall and delete this function and that work but i really need help from theme developer i have put a complain into envato market so may be they can help me out i have change the theme and now the plugin works properly. Thanks for your help you can close this ticket if you want as i had gave up on the current theme

**Comment by Miguel99990** [comment]
Como Puedo Solucionar Este Error.

Warning: call_user_func_array() expects parameter 1 to be a valid callback, class 'ReduxFramework' does not have a method '_options_page' in /home4/wilmer/public_html/wp-includes/plugin.php on line 525
