### ISSUE TITLE
Problem after installing Redux Framework 3.5.9

### ISSUE THREAD

**Issue by GingerSigns** [reduxframework/redux-framework#2841]
I have a clean install of WP no plugins.
i installed theme Boxy Pro part of install was to install Redux Framework 3.5.9 as soon as i activate i.e. all i get is a b;and screen and cannot get back to dash board her anything. only way out is to remove wp and start again. any ideas please. Cheers

**Comment by kprovance** [comment]
Pro, meaning premium theme?  If so, you need to obtain support from the theme author.  They are the ones who need to debug your server for the issue, s you paid them.  :)

If they discover an issue, then need to work with us on it.  Typically, we do not deal with end users of themes.
