### ISSUE TITLE
reduxframework plugin showing error 

### ISSUE THREAD

**Issue by wp-subrata** [reduxframework/redux-framework#2842]
Hi! 

I am new to reduxframe work...I have installed the plugin in localhost (xampp) and when i activated the plugin, it is showing the below error message;

Call to undefined function wp_generate_password() in /var/www/html/ReduxWP/wp-admin/includes/file.php on line 169

I have searched for the possible issue but couldnot figure out. Pls help and suggest what to do now?

Thanks

**Comment by wp-subrata** [comment]
I have figured out the issue..it is with the file permission in plugins and sub-folders...its showing in admin panel now. 

As i am a newbie...can anyone suggest me how to start with...i have checked the admin panel with the redux dashboard but not found anything like how to integrate the suggested features in my theme.

Pls suggest.

**Comment by kprovance** [comment]
We aren't actually able to write your options panel for you.  You can either visit our docs site (https://docs.reduxframework.com) or view the sample-config.php included with the Redux project.  Both can get you started.  ;)

**Comment by wp-subrata** [comment]
Thanks...will check those...

**Comment by SubratBarik** [comment]
At last got a little drop of Redux Framework in my grab ;) Its just beginning but enjoyed a lot. You guys have done a miracle. 

Please keep updating documentation of Redux as it will help lots of newbies like me :)

Best Wishes...
