### ISSUE TITLE
[Request] Custom multi fields

### ISSUE THREAD

**Issue by mrmoonlb** [reduxframework/redux-framework#2844]
Is there any option to create custom multiple fields (with add more), example: One field: TItle, Image, Radio button, Select.

**Comment by kprovance** [comment]
Inherently, no.  You have two options.  If you are versed in PHP and Javascript, you can write your own extension (https://docs.reduxframework.com/extensions/using-extensions/), or purchase our repeater extension (https://reduxframework.com/extension/repeater/).  :)
