### ISSUE TITLE
[Request] Use WP Editor in Slides

### ISSUE THREAD

**Issue by FabKos** [reduxframework/redux-framework#2846]
Slides are a mighty tool for me, but it's not extendable as it seems. Could you please change from a plain textbox to wp-editor? So the customer could really style the slides content. Just like the Question asked here: http://stackoverflow.com/questions/35247538/redux-framwork-use-wp-editor-in-slides 

informations requested:
1. I'm coding a theme using redux as a plugin in combination with TGM
2. Using the Version: 3.5.9, no newer version found in the wp-store / repo
3. Ticket Reason: "something is not working as it should" (I really see this as an usability thing)
4. Turned back on DEV Mode. Still the same issue.

All the best

**Comment by kprovance** [comment]
That would break backward compatibility with existing users.  It's something we go out of our way not to do.  You are free to create a comparable field with either overloading or by writing your own extension (you will need a more than passing knowledge with PHP and JavaScript to do so):  https://docs.reduxframework.com/core/advanced/add-a-custom-field/

**Comment by FabKos** [comment]
Thank you, I'll take a look at it - if I can handle it, I'll publish the code so other people can afford from it to. Thanks for the link, AND: I totally understand the decision. It's good to know, you keep an eye on backwards compatibility.
