### ISSUE TITLE
Field Validation in Redux Fram work

### ISSUE THREAD

**Issue by swapnilshetes** [reduxframework/redux-framework#2847]
Hi,

First Please check folder structure : theme name is 'mytheme'
1) mytheme\inc\admin
2)  mytheme\inc\admin\redux-extensions
3) mytheme\inc\admin\redux-framework
4)  mytheme\inc\admin\options-init.php
5) mytheme\inc\admin\page-template-metabox.php

In 'page-template-metabox.php' we have provided all meta fields for pages and posts 
for example  : 
//
$boxSections[] = array(
            'title' =>
__('Carousel Images', 'test'),
            'icon' => 'el el-briefcase',
            'fields' => array(
array(
                        'id' => CR_POST_EDUC_QUALIF,
					    'type' => 'textarea',
                        'title' => __('Educational Qualifications', 'test'),
                        'width' => '100%',
					    'placeholder' => __('Please enter educational qualifications', 'test'),
						'validate' => 'not_empty'
                    ),
                array(
                    'id' => HOME_PAGE_IMAGES_LIST,
                    'type' => 'repeater',
                    'title' => __('Add/Edit Carousel Items', 'test'),
                    'item_name' => __('carousel', 'test'),
                    'group_values' => true,
                    'width' => '100%',
                    'bind_title' => 'opt-carousel-title',
                    'fields' => array(
                        array(
                            'id' => HP_CL_IMAGE_URL,
                            'type' => 'media',
                            'preview' => true,
                            'width' => '100%',
                            'class' => 'test-social-icons-wrapper',
                            'url' => false,
                            'subtitle' => __('Upload only PNG images with (TBD) pixel dimentions', 'test')
                        ),
						 )
                )
                
            )
        );
        
        
        
        // Declare community metaboxes
        if (!isset($metaboxes) && !is_array($metaboxes)) {
            $metaboxes = array();
        }
        $metaboxes[] = array(
            'id' => 'carousel_category',
            'title' => __('Home Page Carousel', 'test'),
            'post_types' => array(
                'page'
            ),
            'page_template' => array(
                'front-page.php'
            ), // Visibility of box based on page template selector
            //'post_format' => array('image'), // Visibility of box based on post format
            'position' => 'normal', // normal, advanced, side
            'priority' => 'high', // high, core, default, low - Priorities of placement
            'sections' => $boxSections
        );
        
        return $metaboxes;
    }
    add_action("redux/metaboxes/{$redux_opt_name}/boxes", "test_add_home_page_carousel_metaboxes");

If we tried to add 'validate' => 'not_empty' in field array which having type is textarea. This is not getting validated at time of publish the page in admin side. Please can you assist us how to validate the admin pages in redux framework.

Thanks.

**Comment by kprovance** [comment]
Please post all extension issue to the extension issue tracker.  This one is specifically for Redux itself:  https://github.com/reduxframework/redux-extensions/issues

**Comment by swapnilshetes** [comment]
Thanks :)
