### ISSUE TITLE
Compiler hooks doesn't affect style.css file

### ISSUE THREAD

**Issue by sullysheperd** [reduxframework/redux-framework#2849]
I did try the code in sample-config file which is for demo, and the hook seems to work(I saw it on console) but when I try it on my theme's config-file it doesn't work. This is the code I have in my config file:

```
$opt_name = "easyread";
add_filter('redux/options/' . $opt_name . '/compiler', 'compiler_action', 10, 3);
function compiler_action($options, $css, $changed_values) {
global $wp_filesystem;

$filename = dirname(__FILE__) . '/style.css';

if( empty( $wp_filesystem ) ) {
    require_once( ABSPATH .'/wp-admin/includes/file.php' );
    WP_Filesystem();
}

if( $wp_filesystem ) {
    $wp_filesystem->put_contents(
        $filename,
        $css,
        FS_CHMOD_FILE // predefined mode settings for WP files
    );
}
}
```

And this is an example of a field that is supposed to change after changing:

```
array(
                'id'       => 'opt-color-header',
                'type'     => 'color',
                'mode' => 'background-color',
                'compiler' => array('body', '.header', '.site-footer'),
                'title'    => __( 'Header Background', 'redux-framework-demo' ),
                'default'  => '#333',
                'validate' => 'color',
            ),
```

            
As you can see, it's suppose to change the background for body and .header, but no luck! there is no error either. Help me with this please, this is the first theme I'm publishing, I would try the premium support as soon as I earn some money to buy it, but right now I have no other choice. Thanks

**Comment by dovy** [comment]
So `output` is what you want to use to generate custom CSS. Compiler, set to true, only fires the hook so YOU can write the CSS to your file.  :)

**Comment by dovy** [comment]
So change compiler to output and it will work.

**Comment by sullysheperd** [comment]
Thanks for responding man, I'm not sure if I'm following! I tried these two and no luck:

```
array(
                'id'       => 'opt-color-header',
                'type'     => 'color',
                'mode' => 'background-color',
                'compiler' => true,
                'output' => array('body', '.header', '.site-footer'),
                'title'    => __( 'Header Background', 'redux-framework-demo' ),
                'default'  => '#333',
                'validate' => 'color',
            ),
```
And:

```
array(
                'id'       => 'opt-color-header',
                'type'     => 'color',
                'mode' => 'background-color',
                'output' => array('body', '.header', '.site-footer'),
                'title'    => __( 'Header Background', 'redux-framework-demo' ),
                'default'  => '#333',
                'validate' => 'color',
            ),
```

**Comment by kprovance** [comment]
You have to specify your selector array in the compiler arg.

**Comment by dovy** [comment]
Just get on Slack and we can talk about it.  http://slack.redux.io

**Comment by sullysheperd** [comment]
I haven't received any email in my inbox for slack, I tried registering with another email but no that one hasn't received anything yet either. 

Just could you please edit this code in a way that you mean? Because I think I have those selectors, for example I want to change the background of body, and this is the code but it doesn't change it:

```
array(
                'id'       => 'opt-color-header',
                'type'     => 'color',
                'mode' => 'background-color',
                'compiler' => array('body'),
                'title'    => __( 'Header Background', 'redux-framework-demo' ),
                'default'  => '#333',
                'validate' => 'color',
            ),
```

**Comment by Karpatsky** [comment]
First - **be sure that id is unique**  in config file.

here working array for compiler


`        array(
            'id'       => 'topbar-color-background',
            'type'     => 'color',
            'compiler' => array('.topbar'),
            'title'    => __('Top Bar Background Color', 'redux-framework-demo' ),
            'subtitle' => __('Pick a background color for top bar (default: #fff).', 'redux-framework-demo' ),
            'default'  => '#FFFFFF',
            'mode' => 'background-color',
            'validate' => 'color',
        ),`
