### ISSUE TITLE
Advanced Embedded Link 404

### ISSUE THREAD

**Issue by arelidev** [reduxframework/redux-framework#2850]
http://docs.reduxframework.com/redux-framework/advanced/embedding-redux-into-your-theme-or-plugin/ does not go anywhere

**Comment by kprovance** [comment]
Odd.  The page is there, but WP doesn't like the slug.  Anyways, I changed it.  Here it is:  https://docs.reduxframework.com/core/advanced/embedding-redux-into-your-theme-or-plugin/

Thanks for letting us know!
