### ISSUE TITLE
Upgrade select 2 to version 4.0.1

### ISSUE THREAD

**Issue by SMR21** [reduxframework/redux-framework#2851]
These are the changes that I personally made:

-File Enqueue.php:

Replace the following:
`
Redux_CDN::register_style(
         'select2-css',
         '//cdn.jsdelivr.net/select2/3.5.2/select2.css',
         array(),
         '3.5.2',//$this->timestamp,
         'all'
);
`
`
Redux_CDN::register_script(
         'select2-js',
         '//cdn.jsdelivr.net/select2/3.5.2/select2' . $this->min . '.js',
         array( 'jquery', 'redux-select2-sortable-js' ),
         '3.5.2',
         true
);
`

by:

`
 Redux_CDN::register_style(
          'select2-css',
          '//cdn.jsdelivr.net/select2/4.0.1/select2.css',
          array(),
          '4.0.1',//$this->timestamp,
          'all'
 );
`
`
Redux_CDN::register_script(
         'select2-js',
         '//cdn.jsdelivr.net/select2/4.0.1/select2.full' . $this->min . '.js',
         array( 'jquery', 'redux-select2-sortable-js' ),
         '4.0.1',
         true
);
`

-File Redux.select2.sortable.js:

Replace by the following:

`
(function ($) {
    
    "use strict";
    
    $.fn.extend({
        select2SortableOrder: function () {
            
            var $this, $select, $select2, sorted, optArr, groupName, optVal, id;
            
            $this = this.filter('[multiple]');

            $this.each(function () {
                
                $select = $(this);

                // skip elements not select2-ed
                if (typeof ($select.data('select2')) !== 'object') {
                    return false;
                }

                $select2 = $select.siblings('.select2-container');

                // Opt group names
                optArr = [];
                
                $select.find('optgroup').each(function (idx, val) {
                    optArr.push(val);
                });
                
                $select.find('option').each(function (idx, val) {
                    groupName = $(this).parent('optgroup').prop('label');
                    optVal = this;
                    
                    if (groupName === undefined) {
                        if (this.value !== '' && !this.selected) {
                            optArr.push(optVal);
                        }
                    }
                });
                
                sorted = $($select2.find('.select2-selection__rendered li[class!="select2-search--inline"]').map(function () {
                    if (!this) {
                        return undefined;
                    }
                    
                    /*
                    if ($(this).data('select2Data') !== undefined) {
                        id = $(this).data('select2Data').id;
                        return $select.find('option[value="' + id + '"]')[0];
                    }*/
                    if ($(this).data('data') !== undefined) {
                        id = $(this).data('data').id;
                        return $select.find('option[value="' + id + '"]')[0];
                    }

                    
                    //var id = $(this).data('select2Data').id;

                    //return $select.find('option[value="' + id + '"]')[0];
                }));
 
                sorted.push.apply(sorted, optArr);
                
                $select.children().remove();
                $select.append(sorted);
            });

            return $this;
        },
        
        select2Sortable: function () {
            
            var args, $this, validMethods, defaultOptions, options, $select, $select2choices;
            
            args = Array.prototype.slice.call(arguments, 0);
            $this = this.filter('[multiple]');
            validMethods = ['destroy'];

            if (args.length === 0 || typeof (args[0]) === 'object') {
                defaultOptions = {
                    bindOrder: 'formSubmit', // or sortableStop
                    sortableOptions: {
                        placeholder: 'ui-state-highlight',
                        items: 'li:not(.select2-search--inline)',
                        tolerance: 'pointer'
                    }
                };
                
                options = $.extend(defaultOptions, args[0]);

                // Init select2 only if not already initialized to prevent select2 configuration loss
                if (typeof ($this.data('select2')) !== 'object') {
                    $this.select2();
                }

                $this.each(function () {
                    $select = $(this);
                    $select2choices = $select.siblings('.select2-container').find('.select2-selection__rendered');

                    // Init jQuery UI Sortable
                    $select2choices.sortable(options.sortableOptions);

                    switch (options.bindOrder) {
                    case 'sortableStop':
                        // apply options ordering in sortstop event
                        $select2choices.on("sortstop.select2sortable", function (event, ui) {
                            $select.select2SortableOrder();
                        });

                        $select.on('change', function (e) {
                            $(this).select2SortableOrder();
                        });
                        break;

                    default:
                        // apply options ordering in form submit
                        $select.closest('form').unbind('submit.select2sortable').on('submit.select2sortable', function () {
                            $select.select2SortableOrder();
                        });
                        break;
                    }
                });
            } else if (typeof (args[0] === 'string')) {
                if ($.inArray(args[0], validMethods) === -1) {
                    throw "Unknown method: " + args[0];
                }
                
                if (args[0] === 'destroy') {
                    $this.select2SortableDestroy();
                }
            }
            
            return $this;
        },
        
        select2SortableDestroy: function () {
            
            var $this, $select, $select2choices;
            
            $this = this.filter('[multiple]');
            $this.each(function () {
                $select = $(this);
                $select2choices = $select.parent().find('.select2-selection__rendered');

                // unbind form submit event
                $select.closest('form').unbind('submit.select2sortable');

                // unbind sortstop event
                $select2choices.unbind("sortstop.select2sortable");

                // destroy select2Sortable
                $select2choices.sortable('destroy');
            });
            
            return $this;
        }
    });
}(jQuery));
`

**Comment by kprovance** [comment]
There are other considerations that make this not possible right now.  Typography would need work, and I don't have the time to dig into it all to fix it.

**Comment by dovy** [comment]
You're welcome to make the changes locally, and then try to get typography properly working.

If you can do that, send a pull request. We'd love it!

**Comment by SMR21** [comment]
I'm working on it, sent it when finished.

**Comment by dovy** [comment]
Awesome. Please be thorough before you send a pull release. This affects a LOT of people if something breaks. Millions of sites.
