### ISSUE TITLE
Next button only goes to Page 2, no matter what page you're on (myblogger theme)

### ISSUE THREAD

**Issue by naptownpint** [reduxframework/redux-framework#2853]
http://naptownpint.com/

I haven't changed anything in the code. It's a quirk that's always been there, I just keep forgetting to ask about it. Thanks.

**Comment by dovy** [comment]
See previous response.   :P

**Comment by naptownpint** [comment]
I'm confused - how are the links that go from page to page a plugin issue? Isn't that coded into the theme itself?

**Comment by kprovance** [comment]
We're not the author of the plugin.  The author probably used Redux as part of his package and forgot to remove the support links that led you here.  Please contact whomever the author is for support for their work.  Thanks.  :)
