### ISSUE TITLE
Instagram Slider Widget no longer populating (myblogger theme)

### ISSUE THREAD

**Issue by naptownpint** [reduxframework/redux-framework#2854]
Again for http://naptownpint.com

Confirmed this issue on multiple browsers and on mobile, but the Instagram section is now blank. My Instagram credentials haven't changed, the plugin is up to date and I'm not getting any errors. It just randomly today stopped showing any photos.
![instagram broken](https://cloud.githubusercontent.com/assets/17206024/13018675/f35441fc-d198-11e5-96fa-1197e131af43.PNG)

**Comment by dovy** [comment]
We didn't develop this plugin. Please contact the actual author. Good luck!

**Comment by naptownpint** [comment]
Thanks!

On Friday, February 12, 2016, Dovy Paukstys <notifications@github.com>
wrote:

> We didn't develop this plugin. Please contact the actual author. Good luck!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/reduxframework/redux-framework/issues/2854#issuecomment-183468955>
> .
>


-- 
*L I Z  M U R P H Y*
Craft beer writer for the Capital Gazette
Maryland beerlanthropist
Tomfoolery enthusiast

Phone: 410.980.6341 | Web: NaptownPint.com <http://naptownpint.com/> |
Twitter @naptownpint <http://www.twitter.com/NaptownPint> | FB: NaptownPint
<http://www.facebook.com/NaptownPint>
