### ISSUE TITLE
Calling "All Categories" in Select Filed 

### ISSUE THREAD

**Issue by sojibrahmanbd** [reduxframework/redux-framework#2856]
I can't find any field called like "All categories" in **Select field**. I want to make an option for choosing any specific category or selecting "All Categories" for displaying all categories post in a query. 

How can i do that?

Thanks

**Comment by dovy** [comment]
It's called the data argument. There's a whole page in the docs on it. Best of luck.

**Comment by Letreiros** [comment]
@dovy

**Comment by Letreiros** [comment]
`[](url)`

**Comment by dovy** [comment]
Docs.reduxframework.com
