### ISSUE TITLE
How to use global variable in theme development??

### ISSUE THREAD

**Issue by ronak11** [reduxframework/redux-framework#2859]
Hi,
i am using redux as theme option in theme development. we use global var as include in file at top of file .But theme foret team refuse to use this kind of way .So let me know how use global variable of redux.if not include in file than it  show undefined variable.below are commets  by themforet team.
"**global variable should be used restrictively and only if theme really needs to.

Here’s an example how this would be acceptable: http://envato.d.pr/1aT9P/3ageodpz

It's highly recommended not to use them at all just to keep things out of the global namespace.**
"
Thanks in advanced

**Comment by kprovance** [comment]
Wrap your option retrieval inside a function, where you can use the global.

**Comment by ronak11** [comment]
thanks for rply @kprovance 
but can you give example about this. i talking about use option in theme file where we use option like site logo,banner ,some text etc.

**Comment by kprovance** [comment]
It's basic PHP, my friend, and anything I wrote probably won't work in your code.  You write a function, you pass the option you want to retrieve, pull it from the global variable and return it.
