### ISSUE TITLE
Post to page association getting reordered alphabetically

### ISSUE THREAD

**Issue by damian5000** [reduxframework/redux-framework#2860]
Post to page association getting reordered alphabetically instead of keeping the order which we place association, this is causing incorrect page headers to show for our posts when post associations get alphabetically reordered by the framework.

**Comment by kprovance** [comment]
I need you to review this please:  https://github.com/reduxframework/redux-framework/blob/master/CONTRIBUTING.md.  We need to know what this has to do with Redux, exactly.

**Comment by damian5000** [comment]
Hello, thanks for your reply, here is more detailed info:

I'm using a multi select field that you can select pages from - and this orders the pages alphabetically when the page is saved.

```
array(
    'id'      => 'post_association',
    'type'    => 'select',
    'multi' => true,
    'title'   => esc_html__( 'Post Association', 'gauge' ),
    'desc' => esc_html__( 'Choose what hub pages to associate with this post.', 'gauge' ),
    'data' => 'page',
    'args' => array( 'post_status' => array( 'publish', 'future' ) ),
    'default' => '',
)
```

The problem is that if choosing more than one page to be associated with, the fields are reordered alphabetically, and I need the first entered page to remain first so that the page header ends up as the one I need it to be.

Example, if I have a Honda CBR post, but I want it associated with the Honda page and the Honda CBR page, but I want the Honda CBR header, not the Honda page header, but this will get reordered and end up as the Honda header.

Hope this makes sense.

**Comment by kprovance** [comment]
Build your arg structure based on these criteria:  https://codex.wordpress.org/Function_Reference/get_pages
