### ISSUE TITLE
Submenu placement

### ISSUE THREAD

**Issue by tjankov** [reduxframework/redux-framework#2862]
First of all, kudos for a really useful framework.

Im trying to use redux to make a WooCommerce plugin.
So how do I add submenu in a specific place under WooCommerce admin menu?
I managed to place it under WooCommerce by using
`'page_parent'          => 'woocommerce',`
but setting the order escapes me.

How would I do it?

And if I want to place the settings page as a **tab** in  Woocommerce settings?

**Comment by kprovance** [comment]
That's not how page parent works.   For WooCommerce, which is technically a custom post type, you have to specificy edit/php and the post type.  In WooCommerce's case, I believe its: `edit.php?post_type=shop_order` you need to put in page_parent.

As for using Redux to add to WooCommerce's options page, sorry, but it cannot be done.

**Comment by tjankov** [comment]
no, @kprovance, Im afraid that just removed everything from WooCommerce menu.

using 'woocommerce' as page_parent **DID** create submenu item, I just couldnt change its order.
It puts it 3rd place and cant move it from there.

**Comment by kprovance** [comment]
Redux cannot do that inherently, as add_submenu_page does not support any type of positioning.  They are in the order they are originally added.  The only way to resort them is to use the `custom_menu_order` filter and change the order manually.
