### ISSUE TITLE
customize issue

### ISSUE THREAD

**Issue by pra98935** [reduxframework/redux-framework#2863]
we are using 'slides' type. we have created 6 n 7 no. slide by using click on 'add slide' but we are unable to see these slide in 'customize' section. i'm attaching both image please check.
![redux1](https://cloud.githubusercontent.com/assets/11588055/13220721/a68a3b12-d99d-11e5-9f31-5c12bac1271d.png)
![redux](https://cloud.githubusercontent.com/assets/11588055/13220722/a68e8064-d99d-11e5-8196-0f132c3d5c94.png)
![customize](https://cloud.githubusercontent.com/assets/11588055/13220811/391a58d6-d99e-11e5-9091-242641c97705.png)

**Comment by kprovance** [comment]
@Dovy, was this an outstanding issue?  Something was, and I don't recall if this was it.

**Comment by kprovance** [comment]
Wait, I'm confused, our slides field type doesn't have 'button' and 'enabled'.  Is this some kind of custom job?  If you've made modifications to the code, then it's no longer ours and unsupported.  Please clarify.

**Comment by pra98935** [comment]
Please don't focus on enable slides 5 (on/off button). in 2nd image we have created 6 n 7 no. slides by using this code (https://docs.reduxframework.com/core/fields/slides/). after that we have checked in customize (image 1) section where 6 n 7 no. slides  not displaying. 

so my query is that how we can display slides in customize section.

**Comment by dovy** [comment]
With the advanced customizer field shortly coming.  :)

**Comment by kprovance** [comment]
Well, it's all part and parcel...if you make modifications to our core, you can't expect us to support it when it doesn't function correctly.  I double checked our slider field on our demo site, and it seemed to function properly in the customizer.  If you made changes, then support becomes premium terroritory, as it's beyond the scope of our core software.  I'm sorry if that's not what you want to hear, but you did make changes, and we are not responsible for them.
