### ISSUE TITLE
Custom Fonts

### ISSUE THREAD

**Issue by schrovena** [reduxframework/redux-framework#2864]
I would like to obtain the custom fonts extension. Were can I find it?

**Comment by kprovance** [comment]
It is no longer available.  We may repackage it in the future.  Difficult to sat at present.  :)

**Comment by schrovena** [comment]
Do you still have an copy? Don't matter if it's working or not. I'm really stuck :(. 

Kind regards, 



Andy SCHROVEN 

----- Oorspronkelijk bericht -----

Van: "Kevin Provance" <notifications@github.com> 
Aan: "reduxframework/redux-framework" <redux-framework@noreply.github.com> 
Cc: "schrovena" <andy.schroven@telenet.be> 
Verzonden: Dinsdag 23 februari 2016 17:18:05 
Onderwerp: Re: [redux-framework] Custom Fonts (#2864) 



It is no longer available. We may repackage it in the future. Difficult to sat at present. :)

**Comment by kprovance** [comment]
Sorry, it's just not available right now.  There are too many outstanding issues.

**Comment by schrovena** [comment]
I'm a developer myself and I want to take a shot at it, but I need something to work with :(

**Comment by dovy** [comment]
@schrovena get on Slack and chat with me if you wish.  ;)

**Comment by dovy** [comment]
http://slack.redux.io
