### ISSUE TITLE
Group fields (like a section) and have field names nest appropriately?

### ISSUE THREAD

**Issue by foo123** [reduxframework/redux-framework#2866]
Hello, 

since the thread on this (2-year old) issue https://github.com/reduxframework/redux-framework/issues/600#issuecomment-188556474 is both **closed and locked**

i would like to ask a question (with 2 parts)

1. can multiple fields be grouped inside a section?
2. regardless of the of the above question, can the field names be customised, for example even if i find a way to group fileds inside a section the most important part is to make the field names in that part nest under the name of the section, for example:  section name `profiles` (nested) fields under this section `profiles[columns]`  `profiles[texts]` `profiles[texts][text1]` and so on..

Regards

**Comment by kprovance** [comment]
The answer to both is yes.  See the documentation: https://docs.reduxframework.com/extensions/repeater/ and the demo:  http://demo.redux.io/wp-admin

**Comment by foo123** [comment]
ok but i did not ask this, was asking without using the repeater extension? 

is it doable? 
is the secon option doable? (please note that i explicitly mentioned at least 2-leves nested field names) the demo has only one level nested fields

PS Do provide a little time to answer an issue instead of closing it immediately, 
except if you really dont want to answer any issues for the open spurce project you have
