### ISSUE TITLE
Question on color field/alpha

### ISSUE THREAD

**Issue by Webcreations907** [reduxframework/redux-framework#2867]
Hello,

Just curious if you have plans on adding rgba support to the standard color picker, I know that it's not currently possible, but I noticed the start of code for it in the files. 

I was going to override the color field to add it, but just wanted to check before hand to see if it was in the works.

Thanks :smile:

**Comment by kprovance** [comment]
We have the color_rgba field, which is way more powerful than anyting we could add to the Iris colour picker.  :)

**Comment by Webcreations907** [comment]
Thanks for the quick reply and your time. :smile:

**Comment by kprovance** [comment]
No problem.  :)
