### ISSUE TITLE
Wordfence plugin: 'mode-php.js' may contains malicious executable code

### ISSUE THREAD

**Issue by champsupertramp** [reduxframework/redux-framework#2868]
Wordfence plugin found this in the last scan:
This file may contain malicious executable code: /home/axel/uni-vr/wp-content/plugins/ultimate-member/admin/core/lib/ReduxFramework/ReduxCore/inc/fields/ace_editor/vendor/mode-php.js

**Comment by dovy** [comment]
There is no malicious code. We've seen this warning before and it's false. :)
