### ISSUE TITLE
Using select field with data and args to request "all taxonomies of a custom post_type" [paid support]

### ISSUE THREAD

**Issue by zagarskas** [reduxframework/redux-framework#2869]
**Support Hash:**
http://support.redux.io/?id=YP24Nb07d%2F2vE9IQTlRq405GTGv1AUo6ToNl8O%2Buo%2FRCMqzgn6Ng5fmFyWB8xT5SKvDzNOEYZ2K15ShyD9PEI9fEeXvMk6pl3psFy3NkyfVjC8UPzP%2FTsjJXMRLcM0Qq

Version: public static $_version = '3.5.9.4'; //most recent
PHP 5.3.29 | MySQL 10.0.23 | WordPress 4.4.2

**Premium Support purchase** (recently purchased)
Payment: 4882, PayPal, 
Purchase Key eeed6e7926859ead111c9b4061723acb

**Problem**
Using the select field with data and args values set to request "all taxonomies of a custom post_type" does not work as expected.

**Expected result**
WordPress get_object_taxonomies() type function where as NAME and LABEL would be returned as the values of data and args.

**Detailed description of Issue with Code and Video:**
*VIDEO: *http://www.screencast.com/t/ecU5zaod9W

I have examined the following with limited success:
https://github.com/reduxframework/redux-framework/issues/194
https://github.com/reduxframework/redux-framework/issues/2321
https://github.com/reduxframework/redux-framework/issues/2567
https://github.com/reduxframework/redux-framework/issues/329

Elaboration:
As expected the following code shows a list of all taxonomies
`'data' => 'taxonomies'`
however, I need only a list of taxonomies for the custom post_type called "product"
_note: I do not need the "child values" of each product taxonomy, just the taxonomy itself..._

Non working example:
```
array(	
'title'    => __( 'Filter types to show', 'zaga_theme' ),
'id'       => 'filter_product_types',
'type'     => 'select',
     'data' => 'taxonomies',
     'args' => array('post_type' => array('product')),
'multi'    => true,
'sortable' => true,
),
/* this would be awesome if it returned the following to the SELECT field
$_tax->name => $_tax->labels->name
'options'  => array("product-category"=>"Product sets"
"age-group"=>"Age Groups"
"subject"=>"Class and Subjects")
*/

```

Partially working example:

```
array(		
'title'    => __( 'Filter types to show', 'zaga_theme' ),
'id'       => 'filter_product_types',
'type'     => 'select',
'data' => 'taxonomies',
'multi'    => true,
'sortable' => true,
),
/* this however returns the taxonomies of all post_types, but does not get their names...
it shows all taxonomies and does not show the [taxonomy->label]
```

**Comment by kprovance** [comment]
I'll have to get with Dovy on this.  We can't simply go into the section of code that deals with returning taxonomies and changing the return value.  it could potentially breaks thousands of other users.

One of the things you have to keep in mind with the `args` argument is that we feed it directly into the API call, in this case `get_taxonomies`.  There are no alterations done by us, so if an arg isn;t working, it's because WP doesn't support it.  Looking at https://codex.wordpress.org/Function_Reference/get_taxonomies, there doesn't seem to be a `post_type` argument supported.  get_taxonomies also doesn't return an object, it returns an array, so taxonomy->label would never work.

**Comment by kprovance** [comment]
Bah, I spoke too soon, I see what you mean to do, with the array return value.  Never mind on that last point.  :)

**Comment by zagarskas** [comment]
Thank you for your consideration in this matter.

I considered hacking this into the Redux core, but really don't like to do that sort of thing...
but I thought it might be useful to consider.
```
array(  
'title'    => __( 'Filter types to show', 'zaga_theme' ),
'id'       => 'filter_product_types',
'type'     => 'select',
     'data' => 'get_object_taxonomies', // make a new data method?
     'args' => array('post_type' => array('product')),
'multi'    => true,
'sortable' => true,
),
```

and somewhere within  the core the "get_object_taxonomies" could be used when recognizing the data value?
https://codex.wordpress.org/Function_Reference/get_object_taxonomies

```
$taxonomies=get_object_taxonomies($data, 'objects');
$pt_arr = array();
foreach($taxonomies as $_tax) {
	$pt_arr[$_tax->name] = $_tax->lables->name;
}
// then return $pt_arr
```

**Comment by kprovance** [comment]
I chatted with Dovy about it.  We don;t need to hack or modify the core.  Apparently there is a filter that will accomplish the same thing.  I do however need to look into it, because I don;t know what it is off the top of my head.

**Comment by dovy** [comment]
Give me 20 and I'll post the solution for you. ;)

**Comment by zagarskas** [comment]
any luck here? (no rush, I understand these things take time, just checking in)

**Comment by kprovance** [comment]
I'm guessing that 20 came and went?  I thought Dovy has this handled?

**Comment by kprovance** [comment]
Okay, I guess I'm doing this:

Let's start here:

```
        array(      
            'title'    => __( 'Filter types to show', 'zaga_theme' ),
            'id'       => 'filter_product_types',
            'type'     => 'select',
            'data' => 'taxonomies',
            'args' => array('object_type' => array('product')),
            'multi'    => true,
            'sortable' => true,
        ), 
```

This will get you a list of the tax for the products post type...but you want the actual name.  We'd have to pass 'objetcs' instead of 'names' in get_taxonomies, which means an entire rewrite of that function.   The filter solution won't work either, as there is nothing to filter.

Ugh.

Let me see what Dovy wants to do.  Maybe we need to add get_taxomony object after all.

**Comment by zagarskas** [comment]
Ideally the goal is this:
`'type'     => 'select',
     'data' => 'taxonomies',
     'args' => array('post_type' => array('product')),`
where as the select field will return only all taxonomies of the custom post type called product

This can be done using the following code in the theme:
`$taxonomies=get_object_taxonomies($data, 'objects');
$pt_arr = array();
foreach($taxonomies as $_tax) {
    $pt_arr[$_tax->name] = $_tax->labels->name;
}`

**Comment by zagarskas** [comment]
Your example works. 
http://www.screencast.com/t/N1qrXKD2
However, it returns the slug as both the "value" and the "name" (which is fine by me but would be nice to have the name returned as well) 

Apparently I was not using the arguments properly, I hope this post helps other users.
I see no reason not to close this thread.

thank you for your assistance with this issue.

**Comment by dovy** [comment]
Reason for the lack of the name vs the slugs, is names can change and slugs change less. You're welcome to dig in and help make it work as you suggest.  ;)

**Comment by kprovance** [comment]
There are two ways to go with that.  1) Add yet another arg to specify the object, go get_taxomonies will return an object and pull the name that way, but it means lots of extra code in the function, and then we have to support it for ALL the data types, which is a LOT of work.  or 2) add get_taxomonies_object to the data types and pull that way.  Less work.

**Comment by zagarskas** [comment]
makes sense to me. I think that as a framework since Redux can pull the slug that its up to me as a developer to grab the name, id, ect... as long as I have something to go on to hook into a query I am good! 
Thanks for your help and making a great product, hands down, Redux is the best thing Ive seen happen to wordPress in a about a decade.
