### ISSUE TITLE
Custom svg media preview

### ISSUE THREAD

**Issue by kiwiadv** [reduxframework/redux-framework#2870]
Hi, I able WordPress to upload svg file and redux work. I have also added one function for show the swg thumb in media library and it's work but in redux the preview don't show any svg thumb. May be it's possible add some function in redux core for solve? In this case, how to? Thank you in advance :-)

**Comment by kprovance** [comment]
If you've come up with a way that works, submit a pull request.  We'll be glad to review it and add it if it works without breaking anything.  :)
