### ISSUE TITLE
Foreign Characters saved in option text.

### ISSUE THREAD

**Issue by akentigernfox** [reduxframework/redux-framework#2871]
framework.php 
line : 762

Strip Slashes causes loss of foreign text, from the log you'll see the thai characters are turned into the unicodes without the escape sequence removed.  Not too sure on the importance of strip slashes yet.
 
 ```
 // Strip those slashes!
    error_log('Before Strip Slashes :  '. var_export($value,true));
    $value = json_decode( stripslashes( json_encode( $value ) ), true );
    error_log('After Strip Slashes : '. var_export($value,true));
       
```       

 Before Strip Slashes :  array (
  'last_tab' => '0',
  'wpml:th:wpml_button_text' => 'แก้ปัญหานี้คณิตศาสตร์ที่เรียบง่าย',
  'wpml:fr:wpml_button_text' => 'Commencez démonstration',
  'wpml:en:wpml_button_text' => 'Start Demonstration',

)
 After Strip Slashes : array (
  'last_tab' => '0',
  'wpml:th:wpml_button_text' => 'u0e41u0e01u0e49u0e1bu0e31u0e0du0e2bu0e32u0e19u0e35u0e49u0e04u0e13u0e34u0e15u0e28u0e32u0e2au0e15u0e23u0e4cu0e17u0e35u0e48u0e40u0e23u0e35u0e22u0e1au0e07u0e48u0e32u0e22',
  'wpml:fr:wpml_button_text' => 'Commencez du00e9monstration',
  'wpml:en:wpml_button_text' => 'Start Demonstration',
  )

**Comment by dovy** [comment]
Strip_slashes works for ace editor.

You may have to just disable ajax_save to get this to work. Unless you can find a better solution.  :(

**Comment by akentigernfox** [comment]
I've worked a little way towards a solution. I know there is another place in the cod that uses strip_slashes in the same way, that i will have a look into also.  What i've tried so far and appears to be approximately ok for a first test.  (I've left the error_log in there for testing purposes).

So it just runs the strip_slashes on ace_editor field values.

framework.php
line  761

```
} else if ( $this->args['database'] === 'network' ) {
                        // Strip those slashes!
                        error_log('Current Options ' . var_export($this->sections ,true));
                        error_log('Before Strip Slashes :  '. var_export($value,true));
                        foreach ($this->sections as $section) {
                        	foreach ($section['fields'] as $field) {
                        		error_log('checking: ' . var_export($field,true));
                        		if ($field['type'] === 'ace_editor') {
                        			if (isset($value[$field['id']])) {
                        				error_log('Running Strip stripslashes ' .$value[$field['id']]);
                        				$value[$field['id']] =json_decode( stripslashes( json_encode($value[$field['id']] ) ), true );
                        				error_log('AFTER Strip stripslashes ' .$value[$field['id']]);
                        				
                        			}
                        		}
                        	}
                        }
                       // $value = json_decode( stripslashes( json_encode( $value ) ), true );
                        error_log('After Strip Slashes : '. var_export($value,true));
                        update_site_option( $this->args['opt_name'], $value );
                    } else {
```

**Comment by kprovance** [comment]
YOu may want to check the wp_editor as well.  I believe there were issues with that also.

**Comment by kprovance** [comment]
We've not heard back from you about this.  If this successfully works with BOTH the ace field and editor field, submit a pull request and we'll give it a test.

**Comment by akentigernfox** [comment]
Kevin,

I have to work on some other project work, I will keep on working things out slowly,  I really love the Redux Framework, and am happy to contribute to make things better.    I have only so far taken code from a git project to my mac onto Eclipse,  and have never tried to push my changes back to somebody else project.  If you have a pointer document on how to do this, it would be great,  if not i will work it out slowly myself.

Andrew
