### ISSUE TITLE
Editor stripping my <p> and <br> tags + TinyMCE Advanced features not shown

### ISSUE THREAD

**Issue by icommstudios** [reduxframework/redux-framework#2872]
http://support.redux.io/?id=JJmA8qAUuAz3XWogW8cknRyx6EPk6JzzA7l2w%2BYDMDcUWGmLdqiyX7MPlXSQC6LHS2se8vRGxbauGpzun1%2F1fw%3D%3D

How can I keep Redux TinyMCE from stripping my `<p>` and `<br>` tags?  Also I have TinyMCE Advanced plugin installed but none of those options display within the Redux editor either.  Any help is greatly appreciated.  Thanks!

**Comment by kprovance** [comment]
I'm not sure.  Have you set wpautop to false?  As for the other plugin, if there are compatibility issues, I'm not too sure how to go about dealing with that.  Redux uses the wp_editor API to instantiate the TinyMCE editor.  What displays on the toolbars, plus all tinyMCE options can be set via field arguments: https://docs.reduxframework.com/core/fields/editor/

**Comment by icommstudios** [comment]
Thanks Kevin, I'll give these suggestions a try. 

Be Happy,

Travis Hedrick
(sent from my mobile office)
