### ISSUE TITLE
Skip some options when exporting. 

### ISSUE THREAD

**Issue by FrankM1** [reduxframework/redux-framework#2873]
Hi,

I love the framework and I've been using it extensively. 

Is it possible to skip exporting some field's saved data using the "Import/Export" tool?

**Comment by kprovance** [comment]
It is not.  Sorry.

**Comment by dovy** [comment]
You can use a filter and hook into the "import" method to filter out the items you don't want.  ;)

**Comment by FrankM1** [comment]
Thanks Dovy, I'll try this method. For some reason I had forgotten there are filters available to do this. 

I'm currently trying to improve the importer in https://github.com/FrankM1/radium-one-click-demo-install but need to keep some things such as api keys private.

**Comment by dovy** [comment]
No worries. That should work fine.  ;)
