### ISSUE TITLE
Select image - Default not working

### ISSUE THREAD

**Issue by Mediavuk** [reduxframework/redux-framework#2874]
Redux 3.5.8
Wordpress 4.4.2
Dev_mode - on 

`    Redux::setSection( $opt_name, array(
        'title'      => __( 'Slide arrows', 'redux-framework-demo'),
        'subsection' => true,
        'desc'  => __( 'Chosse arrows lefts and right for your slides.', 'redux-framework-demo' ),
        'fields'     => array(
            array( 
                'id'       => 'arrows-select',
                'type'     => 'select_image',
                'title'    => __('Select Arrows', 'redux-framework-demo'),
                'desc'     => __('Selected arrows will appear on each sections made of slides.', 'redux-framework-demo'),
                'options'  => Array(
                    '1' => Array (
                         'alt'  => 'Arrows - branches',
                         'img'  => get_template_directory_uri() . '/img/slides/next.png',
                    ),
                    '2' => Array (
                         'alt'  => 'Arrows - circle',
                         'img'  => get_template_directory_uri() . '/img/slides/circle_arrow_right.png',
                    )
                ),
                'default'  => '1',
            ),     
        )
    ) );`
When i "Reset Section" , my Redux option points to blank default field, and my Redux option doesn`t work until option is selected.

**Comment by dovy** [comment]
PHP arrays work from index 0 on up. If you're not going to use an actual string for the name, I wager PHP is trying to reset the array to a true array.

So instead this should work, and lose the quote around non-string keys:
```php
Redux::setSection( $opt_name, array(
    'title' => __( 'Slide arrows', 'redux-framework-demo' ),
    'subsection' => true,
    'desc' => __( 'Chosse arrows lefts and right for your slides.', 'redux-framework-demo' ),
    'fields' => array(
        array(
            'id' => 'arrows-select',
            'type' => 'select_image',
            'title' => __( 'Select Arrows', 'redux-framework-demo' ),
            'desc' => __( 'Selected arrows will appear on each sections made of slides.', 'redux-framework-demo' ),
            'options' => Array(
                0 => Array(
                    'alt' => 'Arrows - branches',
                    'img' => get_template_directory_uri() . '/img/slides/next.png',
                ),
                1 => Array(
                    'alt' => 'Arrows - circle',
                    'img' => get_template_directory_uri() . '/img/slides/circle_arrow_right.png',
                )
            ),
            'default' => 0,
        ),
    )
) );
```
