### ISSUE TITLE
Redux Instalation

### ISSUE THREAD

**Issue by kajdzo** [reduxframework/redux-framework#2876]
Hello, 
I'm developing WP theme (WP version 4.4.2) and I want to use redux framework to create Theme Options. I'm trying to embed redux in my theme but I keep getting following error:

**Parse error: syntax error, unexpected 'if' (T_IF) in C:\xampp\htdocs\my-theme\wp-content\themes\my-theme\redux-framework-master\ReduxCore\inc\class.redux_helpers.php on line 711**

I've included config.php and framework.php file into functions.php and I've set opt_name.
Any suggestions? 

Thanks.

**Comment by kprovance** [comment]
Fixed in v3.5.9.6.  Sorry about that.

**Comment by kajdzo** [comment]
Now works fine. Thanks for great work.
