### ISSUE TITLE
Compiler action not working in 3.5.9

### ISSUE THREAD

**Issue by justnorris** [reduxframework/redux-framework#2877]
I've been trying to figure out the compiler today, and I'm stuck with what seems like the hook is just not triggered on save. 

I've added that `die()` there to check if the action is even triggered. It's not. I edited `framework.php` directly on `line 2387`
```
                    /**
                     * action 'redux/options/{opt_name}a'
                     *
                     * @param array  options
                     * @param string CSS that get sent to the compiler hook
                     */
	                die("Hello There, How are you ?");
                    do_action( "redux/options/{$this->args['opt_name']}/compiler", $this->options, $this->compilerCSS, $this->transients['changed_values'] );
```

From my options.php:
```
array(
			'id'          => 'body_background_color',
			'type'        => 'color',
			'mode' => 'background-color',
			'default'     => '#FFFFFF',
			'validate'    => 'color',
			'transparent' => false,
			'output' => array('body'),
		),
```

Am I doing something wrong?

**Edit** 
Testing different redux versions:

3.5.9: Broken
3.4.1: Working
3.5.5: Working
3.5.8: Working
3.5.9 Fresh from WP.org: Working

Thank you all very much for participating. Turns out I screwed up somewhere...

**Comment by justnorris** [comment]
`Hello There, How are you` shows up when I reset section, but not when I save changes.

**Comment by dovy** [comment]
Figured it out I see?  ;)
