### ISSUE TITLE
How to use Compiler ?

### ISSUE THREAD

**Issue by justnorris** [reduxframework/redux-framework#2878]
I've been at this all day. Any help appreciated.

I have this in my options.php
```
array(
			'id'       => 'site_fadein_duration',
			'title'    => 'Site Fade In: Duration',
			'subtitle' => 'In ms ( 1000ms equals 1 second )',
			'type'     => 'slider',
			'min'      => '0',
			'max'      => '1200',
			'step'     => '25',
			'default'  => '600',

			// Generate CSS
			'compiler' => array('.js body'),

		),
```

It's a Redux Slider field. And in this case, it represents milliseconds. Now, of course, Redux doesn't support all possible values and combinations out of the box. But surely there is a way for me to tap into the compiler and tell it that I want:
```
					array(
						'-moz-transition-duration'    => '%%value%%ms;',
						'-ms-transition-duration'     => '%%value%%ms;',
						'-webkit-transition-duration' => '%%value%%ms;',
						'transition-duration'         => '%%value%%ms;',
					)
```

The only thing I can think of at the moment is the following:
`add_action( 'redux/options/' . $my_key . '/compiler/advanced', 'compile_css_function', 10 );`

And then in `compile_css_function` use `$this->sections` to loop over all values, until I find `$this->changed_values`, pick them out, check their *type*, and if their *type* matches some array ( of my specified types ) then parse that and add to `$css`. That process seems very, very cumbersome, for a pretty common thing. **Is there a better way?**

**Comment by kprovance** [comment]
The select field does not support a compiler CSS output in the way in which you are attempting to do.  Those are more for fields who have defined selectors (typography, background, color, etc).

The way you suggest is really the only way, and part of the reason for having the compiler, so folks can manipulate the data however they wish.  :)

**Comment by justnorris** [comment]
Ok, thanks for the info.
If I can come up with a more easily extendable way to do this - would you accept a PR ?

**Comment by kprovance** [comment]
We are always happy to consider user contributions (although we vet them more carefully now to avoid backward compatibility issues, which have cropped up).  Here are some things to consider.

1) Most important, backward compatibility.  Can't break existing functionality.  There isn't much in terms of changes that could be made to the actual compiler without doing so (that I can think of off the top of my head).

2) There isn't much point to adding compiler css output to the select field, since select was never designed to return css selectors with it's chosen value.  Most it's used for sting items, not integer or float values.

3) Ideally, what you want to do involves the border field, but you want radius...which isn't supported.  Years back I wrote an extension to support radius for margin/padding/border, but no one seems interested in it.  Perhaps it's something to consider now, adding that to the border field.  Something to think about.  :)

**Comment by justnorris** [comment]
@kprovance just a sketch I came up with. I haven't tested it, but this is the general idea that could work right now, without breaking any existing functionality:

 ```php
if ( ! empty ( $this->options[ $field['id'] ] ) && class_exists( $field_class ) ) {
    /**
    * Render CSS From Field Class
    */
    if ( method_exists( $field_class, 'output' ) && $this->_can_output_css( $field ) ) {
        $field = apply_filters( "redux/field/{$this->args['opt_name']}/output_css", $field );

        if ( ! empty ( $field['output'] ) && ! is_array( $field['output'] ) ) {
            $field['output'] = array( $field['output'] );
        }

        $value   = isset ( $this->options[ $field['id'] ] ) ? $this->options[ $field['id'] ] : '';
        $enqueue = new $field_class ( $field, $value, $this );

        if ( ( ( isset ( $field['output'] ) && ! empty ( $field['output'] ) ) || ( isset ( $field['compiler'] ) && ! empty ( $field['compiler'] ) ) || $field['type'] == "typography" || $field['type'] == "icon_select" ) ) {
            $enqueue->output();
        }
    }
    /**
    * Optionally render CSS From other fields
    */
    else if( $output = apply_filters( "redux/field/{$this->args['opt_name']}/field/{$field['type']}/css", false, $field ) ) {

        if( is_array( $output ) && ! empty($output['css']) && ! empty($output['type']) && is_string( $output['css'] ) ) {
            if( 'compiler' === $output['type'] ) {
                $this->compilerCSS = $output['css'];
            }
            if( 'output' === $output['type']){
                $this->outputCSS = $output['css'];
            }
        }
        
    }
}
```

This would allow hooking into any field that isn't rendering content and return results. 

There are some issues with this approach too:
1. No way to offer the same filter for fields that do render CSS on their own, because they're locked in tight with `$this->parent->outputCSS`. I think that the API should be changed for that. Instead of modifying a string in the parent class, the fields should return the string they want to add to the parent class. - Then that value could be also filterable, and the code above could be cleaned up a ton. 

2. It just looks a little ugly. This code basically does the same thing twice. Once with loading a class, and then once again but with a filter, but in a more clumsy way. I'll probably clean the clumsy way, and make it look at least decent before submitting a pull.

Have you thought about cleaning up framework.php, splitting it into a more `solid` approach? ( single-responsibility kind of thing ). I could try to help a little. Currently framework.php does anything and everything. Took me quite a while to dig through it. And a lot of code repeats itself making it difficult to read.

**Comment by kprovance** [comment]
Yeah.  Christine was slightly amused at the fact I used her name in my tests.  ;-)

Let's get @Dovy to chime in.  He wrote the compiler function.  He would know better the feasibility.

**Comment by justnorris** [comment]
Haha :smiley: - you probably lost her in there because the file is just huge, so splitting it into smaller chunks wouldn't be a bad idea.

@dovy - is there something else that part of the compiler is supposed to do, except render CSS?

**Comment by kprovance** [comment]
We've had several discussion about doing so, splitting up that file.  It's a cost versus work thing.  No one is really supporting us, so it seems like a terrible waste of time, at present.

**Comment by justnorris** [comment]
So if every once in a while I would find a bit of code that I could split out from framework.php into a separate class and submit a PR - you'd merge that? Or is it something that you guys want to pursue on your own sometime in an unknown future.

**Comment by thimfy** [comment]
slider type not working compiler or outpur option?
array(
        'id'            => 'menu_height',
         'type'          => 'slider',
         'title'         => __( 'Menu Height', 'thimfy' ),
            'subtitle'      => __( 'Set height of menu', 'thimfy' ),
	'output'		=> array( '.navigation > ul > li > a' ),
	'compiler'		=> array( '.navigation > ul > li > a' ),
            'default'       => 60,
            'min'           => 40,
            'step'          => 5,
            'max'           => 90,
            'display_value' => 'label'
        ),

**Comment by kprovance** [comment]
The slider field does not support output or compiler.  Sorry.
