### ISSUE TITLE
Very weird stuff, maybe you know what could went wrong

### ISSUE THREAD

**Issue by VladNov** [reduxframework/redux-framework#2879]
Redux is integrated into a theme using the usual way:

`require_once( dirname(__FILE__) . '/admin/theme-options.php' );`

but one site http://www.mrtripper.com/ acts really weired.

Everytime we visit this site in Safari on iPad it reloads several times then just crashes. As soon as i comment require_once line, the site loads normally. It looks like something on this site's server is not accepting something in Redux core or maybe in fields array. Tried lots of possible solutions, nothing helps. Maybe you guys had something similar or have a clue what can be a reason for this strange behavior?

**Comment by dovy** [comment]
99% sure it's a permissions thing. Have the user install redux via the plugins interface, not ftp. It redux is the problem, that will resolve it. 

Also make sure they can upload images via the media uploaded. If not, they need to fix their Wordpress installation.

**Comment by VladNov** [comment]
Hi Dovy,

Thank you for your help. Tried to reinstall the theme and the plugin using the WP installers, but unfortunately nothing helps, Safari on iPad still crashes. The thing is that it's only Safari on iPad. Safari on other devices or other browsers on other devices work perfect. Never seen something like that.

**Comment by VladNov** [comment]
Hi Dovy,

Seems that the issue is resolved, it was the permissions thing. Thank you very much for your help!

**Comment by dovy** [comment]
Glad it worked out. ;)

In case you feel generous. https://www.paypal.me/dovyp

;)

**Comment by VladNov** [comment]
Hi Dovy,

Unfortenutely, and as it seems, paypal.me is not availbale in our country. Is there any other way we can feel generous? :)
