### ISSUE TITLE
options are not being saved and giving fatal error.

### ISSUE THREAD

**Issue by booleandream** [reduxframework/redux-framework#2880]
Today i've downloaded and pasted the redux folder in my theme's directory. Then included the redux files in my theme's main functions.php file as following:
`require_once 'redux/ReduxCore/framework.php';
require_once 'redux/sample/sample-config.php';`

Now if i try to go to Appearance>Customize in my dashboard, then a fatal error shows:

> Fatal error: Using $this when not in object context in C:\wamp\www\wordpress\wp-content\themes\zboom\redux\ReduxCore\inc\class.redux_helpers.php on line 710

If i comment out the 710th line of file class.redux_helpers.php, then the error vanishes.

Please resolve the issue...

**Comment by booleandream** [comment]
The original 710 line of ReduxCore\inc\class.redux_helpers.php is

`$ext_dir = str_replace( wp_normalize_path( WP_CONTENT_DIR ), WP_CONTENT_URL, $this->_extension_dir );`

After I edit the line as showed below, the issue resolves...

`$ext_dir = str_replace( wp_normalize_path( WP_CONTENT_DIR ), WP_CONTENT_URL, Redux_Helpers::get_extension_dir( $dir ) );`

**Comment by kprovance** [comment]
Yeah, I found this out today the hard way.  I'm on it.  That function is completely hosed.

**Comment by dovy** [comment]
I have a fix i will post tomorrow. Sorry all.  ;)

**Comment by kajdzo** [comment]
Hello, 
I'm getting the same error when I try to add new menu item in Appearance > Menus... Just wanted to let you know. :) anyway thanks for all the great work you guys do with redux...

**Comment by kprovance** [comment]
v3.5.9.7 pushed.  That should take care of it.
