### ISSUE TITLE
Build versions

### ISSUE THREAD

**Issue by TuxReports** [reduxframework/redux-framework#2883]
I appreciate the build.reduxframework.com website so the framework is easy to embed in a plugin. However, the versions are behind. The stable is sitting 3.5.8.1 but the releases are already in 3.5.9.x.

**Comment by kprovance** [comment]
Yeah, I see that too!

@Dovy,  :kick:  I can;t run that on my local.  Don't know why those repos won't update.

Anyways, the the interim, I manually updated them.  :)
