### ISSUE TITLE
library_filter and ogg file

### ISSUE THREAD

**Issue by chernandezenigmind** [reduxframework/redux-framework#2884]
Hi!! I need add a file field with .ogg support and I don't have idea how I can do it. library_filter doesn't help me. (sorry for my english, I hope you can understand me.)

**Comment by kprovance** [comment]
Going to need way more information, I'm afraid:  https://github.com/reduxframework/redux-framework/blob/master/CONTRIBUTING.md

**Comment by chernandezenigmind** [comment]
Ok, sorry. I would do my best. 

I want to add a video to my website, but I need the same video en three differents formats (.mp4, .webm and .ogg) with the mp4 I have not problems thanks to an [older ticket](https://github.com/reduxframework/redux-framework/issues/1877) so I tried to do the same thing with the .ogg and .webm but didn't work.

Basically what I'm doing is:
`array(
            'id'        => 'home-header-video-ogg',
            'type'      => 'media',
            'preview'   => false,
            'library_filter' => array('ogg'),
            'title'     => __('Video en formato ogg', 'enigmind'),
            'subtitle'  => __('','enigmind')
        ),`

I don't know what I'm doing wrong. Sorry if this not the place to ask but I don't know where else I can do it.

**Comment by dovy** [comment]
Unless you also allow WordPress to upload those filetypes, everything will fail.

http://www.wpbeginner.com/wp-tutorials/how-to-add-additional-file-types-to-be-uploaded-in-wordpress/    :)

Best of luck!

**Comment by chernandezenigmind** [comment]
I can upload the files, but when I select them nothing happens. So I tried to add the library_filter but didn't work, so the only thing that I could do was  `library_filter put => false` whith library_filter in false I have no filter (bad thing) but I can choose the file that I need. Thaks for your help and your great product.

**Comment by kprovance** [comment]
What Dovy is saying is that it's not a Redux issue.  It;s a WordPress issue.  Setting the library filter won;t make a difference if WP itself doesn't support the file.  We don't support actual WP issues, as it's outside the scope of Redux.  Sorry.

**Comment by dovy** [comment]
Here's a little hint for you. Run this code:
```
$mimeTypes = get_allowed_mime_types();
print_r(mimeTypes);

```

Inside there should be your OGG file if you properly added it to WordPress. Make sure you have the right key and add it into library_filter.  ;)

It may take the mimeType instead, I don't remember.
