### ISSUE TITLE
Composer not working

### ISSUE THREAD

**Issue by LiviaAmedeo** [reduxframework/redux-framework#2885]
Hello, I’ve just bought and installed the theme on this page http://amedeo.locandadelpicchio.com
I’ve activated all the plugin and imported demo content, but I see that the visual composer is not active on the pages.

**Comment by kprovance** [comment]
Please contact the author of the theme (we didn't write it).  They are the ones who need to support you in this matter.

**Comment by LiviaAmedeo** [comment]
Hi thanks for replying back. I can't find the contact of the author, may you help please?

**Comment by kprovance** [comment]
It would run you about 100 dollars an hour.  Expect at least two.

**Comment by LiviaAmedeo** [comment]
No, perheps I wasn't clear: I asked if you are able to give me the contact of the theme author as I can't find it. I'm asking you help to find the contact . The composer is included in the theme and it must work. Thanks again
