### ISSUE TITLE
Getting a Cannot read property 'action' error on save in redux.min.js

### ISSUE THREAD

**Issue by contempoinc** [reduxframework/redux-framework#2887]
Getting a Cannot read property 'action' error on save in redux.min.js screenshot from the console, http://cl.ly/0h062f2i2f02 this is only happening on my demo server so I'm guessing something I need isn't enabled? Do you know what is required for the ajax save any particular server modules or settings?

**Comment by kprovance** [comment]
Please review and submit the necessary information:  https://github.com/reduxframework/redux-framework/blob/master/CONTRIBUTING.md

**Comment by contempoinc** [comment]
Whenever I try to generate a support URL it throws an error, this has never worked since I started using Redux like 6+ months ago.

**Comment by kprovance** [comment]
"throws an error", which...is?

**Comment by contempoinc** [comment]
This is all I get http://cl.ly/1w10373X181Q

**Comment by contempoinc** [comment]
Also from the console http://cl.ly/3F3X1m3U3v3N

**Comment by contempoinc** [comment]
Running the latest version as well.

**Comment by contempoinc** [comment]
Also what table do the options get saved in?

**Comment by contempoinc** [comment]
With debug on I get a depercated notice http://cl.ly/3C0L0c3L382p:

> There was an error saving. Here is the result of your action:
redux.js?ver=3.5.9.7.1457551482:109 <br />
<b>Deprecated</b>:  mysql_connect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead in <b>/home/contempothemes/public_html/wp-real-estate-7/multi-demo/wp-includes/wp-db.php</b> on line <b>1518</b><br />

**Comment by kprovance** [comment]
wp-db.php isn;t our.  I can;t speculate about that.

Please tell me you're not on a GoDaddy server.  Seems something is set off if you are getting all these issues.  Please understand for us to go onto your server to resolve server issues is a premium service.

**Comment by kprovance** [comment]
I can tell you if there is error info, or debug info, or echo/print_r info on screen when you attempt to save, that error will occur.  Ajax saving doesn't like that data on the page.  Is has to be clear of it.

**Comment by kprovance** [comment]
Read this:  It's a PHP 5.5 thing.  WordPress needs to catch up:  http://stackoverflow.com/questions/13944956/the-mysql-extension-is-deprecated-and-will-be-removed-in-the-future-use-mysqli

**Comment by contempoinc** [comment]
LOL, no this is on a DV with Mediatemple

I'm rebuilding right now with PHP 5.6.19 to see if that resolves the issue.

**Comment by kprovance** [comment]
And this:  https://wordpress.org/support/topic/2-deprecated-errors-in-371

**Comment by kprovance** [comment]
Anything after 5.5 with WP_DEBUG enabled will kick back that depreciated error.  The WP core team needs to deal with that.

**Comment by contempoinc** [comment]
Gotcha, that's what I figured.

**Comment by kprovance** [comment]
Use mysqli instead?  http://wordpress.stackexchange.com/questions/199641/deprecated-mysql-connect-error-when-installing-roots-bedrock

**Comment by contempoinc** [comment]
Upgrading to 5.6.19 fixed the issue.

**Comment by kprovance** [comment]
Moving on, looking at the error regarding the support hash.  It says Fatal error: Call to private Browser::__construct() from invalid context

I had to look that one up:  http://stackoverflow.com/questions/1997721/fatal-error-call-to-private-myobject-construct-from-invalid-context

It's curious.  The browser.php we use in Redux is not set to private, by class or construct__.  That error should not be happening, unless there is another plugin that uses it, and it's already loaded and the construct set to private.  Or some other code has loaded a class called Browser which is something different (and why devs should prefix their classes).  That's my guess.  I suppose you could disable plugins (except Redux) and see if the issue persists.  If not, then chances are someone else has a modified copy of the Browser class.

**Comment by kprovance** [comment]
Oh, okay then.  Never mind.  :P

**Comment by kprovance** [comment]
I'm guessing all is well, then?  Closing.  :)
