### ISSUE TITLE
Illegal string offset for every field on activation of the theme

### ISSUE THREAD

**Issue by antoniomangiacapra** [reduxframework/redux-framework#2888]
Hello,

I am using:
- Redux Framework 3.5.9.5
- Wordpress 4.4.2

I ambeded Redux in a Themeforest theme, I used it for a while without problems, now I sended my theme again for an update and they experience this on activation:

`Warning: Illegal string offset 'fb-opengraph' in /Applications/MAMP/htdocs/tf/wp-content/themes/tructor/admin/core/ReduxCore/framework.php on line 2198`

This happens for every field that I created and at the nd also for:

`Warning: Illegal string offset 'REDUX_last_saved' in /Applications/MAMP/htdocs/tf/wp-content/themes/tructor/admin/core/ReduxCore/framework.php on line 737

Warning: Illegal string offset 'REDUX_LAST_SAVE' in /Applications/MAMP/htdocs/tf/wp-content/themes/tructor/admin/core/ReduxCore/framework.php on line 739`

I can't reprodue this but I noticed that they are using a MAMP server, maybe this is the cause.

Also, I noticed that your sample file for field is changed, I created my fields using an a starter file old around 6 month, so I still do something like this:

`public function setSections() {
                $this->sections[] = array(
                        ...
                 )
)
`

Instead of

`Redux::setSection( $opt_name, array(
   ...
));
`

This could be the cause? As I told I can't reproduce it so I have no idea how to solve.

Thank you so much in advantage :)

**Comment by kprovance** [comment]
There isn't enough provided for me to test.  I need to see your options config file, that is, all of it.  Use Gist to send it if necessary.

**Comment by kprovance** [comment]
And yes, that way of setting up the options panel is legacy.  You might consider going to the API way.  :)

**Comment by antoniomangiacapra** [comment]
I tryed to explain the situation, I hope they will understand :(

Anyway Thank you so much for your help :)
