### ISSUE TITLE
Loading styles and scripts

### ISSUE THREAD

**Issue by Webcreations907** [reduxframework/redux-framework#2890]
Hello,

I noticed that the ```wp_enqueue_script()``` & ```wp_enqueue_style``` use ```time()``` for the version in the fields and framework for Redux, which seems to cause each css/js file to reload on every page load and not use the cached one.

I've changed them to ```ReduxFramework::$_version``` instead of ```time()``` which seems to increase the loading time a bit.

Example from one of the fields below, from [Here](https://github.com/reduxframework/redux-framework/blob/master/ReduxCore/inc/fields/dimensions/field_dimensions.php#L224-L240) so you know what I'm referring to.

```php
wp_enqueue_script(
    'redux-field-dimensions-js',
    ReduxFramework::$_url . 'inc/fields/dimensions/field_dimensions' . Redux_Functions::isMin() . '.js',
    array( 'jquery', 'select2-js', 'redux-js' ),
    time(),
    true
);
if ( $this->parent->args['dev_mode'] ) {
    wp_enqueue_style(
        'redux-field-dimensions-css',
        ReduxFramework::$_url . 'inc/fields/dimensions/field_dimensions.css',
        array(),
        time(),
        'all'
    );
}
```

Was just curious if there is any plans to update those in the future?

Thanks for your time :smile:

**Comment by kprovance** [comment]
Maybe, eventually.  dev_mode should have time, at the minimum.  If you feel like editing every instance of this (there are many, one for each field and those in framework), you're free to submit a pull request.  But we'd prefer to have to time() for dev_mode on, at the minimum.  :)

**Comment by Webcreations907** [comment]
Great, will do that then.

Thanks for your blazing fast reply :)
