### ISSUE TITLE
Getting started

### ISSUE THREAD

**Issue by geoclaps** [reduxframework/redux-framework#2894]
Hi! I am a front end developer and currently I'm trying to make the plugin work for me. I installed the most recent (stable) version. At the moment I am trying to make a copy of the sample file so I can setup my own settings here. I have tried this via https://docs.reduxframework.com/core/getting-started/ (Part 2) but the description is a little fague regarding the configuration of setting up a new settings file. I now have copied the file with a new name: sample-config.php > **my-settings.php** to the following directory: **wp-content/themes/my-theme/redux/my-settings.php**.

Now begins the tricky part. The documentation states "_Don’t forget to update the path so it matches the path to your copy!_" so the first question comes to mind is "where should I change this path?". I found it in plugins/redux-framework/class.redux-plugin.php @ rule 157 but I can't really confince myself it's safe to change the path directly since it's the function to activate the demo settings. It also isn't safe because of update issues in the future? With these 2 questions in mind I tried to find another way, sure I am not the only one who had these questions right? And I found the next article: http://stackoverflow.com/questions/23937556/how-to-initiate-custom-redux-framework-config-file

This article states that you should active the new config-sample file via the functions.php of the theme via:
```
function init_my_custom_redux() {
    require_once(dirname(__FILE__).'/path/to/config.php');
}
add_action('plugins_loaded', 'init_my_custom_redux', 30);
```
I tried that but still no luck. As soon as I turn off demo content via plugins, I get to see no options page at all.

Can you point me in the right direction?

**Comment by kprovance** [comment]
I don't know what the path setup on your server is like, so it's impossible for me to give a clear answer.  The instruction isn't really vague, as using Redux requires a more than passing knowledge of PHP.  For us to go onto your server and set it up for you would require a purchase of premium support.

The generic version is this, if this were in the main function file of the plugin:

```
add_action('plugins_loaded', 'load_redux_config');

function load_redux_config() {
    include_once 'config.php';
}
```
This assumes the config file is in the same folder (or root) of the main function file.  If you have your config file in a subdir called 'admin', the the line would be `include 'admin/config.php'`

http://php.net is a great place to read up on PHP directives, should you not be familiar with them.  :)
