### ISSUE TITLE
Not able to access option set in options panel in another option in same option panel

### ISSUE THREAD

**Issue by mrgurdeep** [reduxframework/redux-framework#2895]
I tried setting a variable in options and tried accessing that variable to set value of other option. 

Say I have set maximum number of posts in one options (option1)
Then I have to set maximum number of posts for each page like archive and search but they should be less than option1.

I tried using the global variable and tried using get_option was not getting the value.

Appreciate your help and time.

**Comment by kprovance** [comment]
Probably because the option isn't yet available in the global variable.  You'll have to use get_option with your opt_name as the key.  If it's already been saved, it'll be available.

**Comment by mrgurdeep** [comment]
I tried using get_option('redux_demo[font-size]') but it is still not giving out value which is already been saved and I can see it in database

**Comment by mrgurdeep** [comment]
@kprovance Thanks for taking time and writing back. 

It worked, 

This is what I did and how it worked
$redux_demo_get = get_option('redux_demo');
$font_size=$redux_demo_get['font-size'];

Thanks & Love the framework.
