### ISSUE TITLE
ajaxComplete issue

### ISSUE THREAD

**Issue by alexgff** [reduxframework/redux-framework#2896]
I have issue with 'ajaxComplete' event which you unbind 
@see 
https://github.com/reduxframework/redux-framework/blob/master/ReduxCore/assets/js/redux.js#L1481 so all next ajaxComplete events are stopped.
You need to use another way to stop your own event without affecting the following calls.

**Comment by kprovance** [comment]
Feel free to see if you can find one, and submit a pull request.  :)
