### ISSUE TITLE
How to add a field from a child theme

### ISSUE THREAD

**Issue by reliable-mantra** [reduxframework/redux-framework#2897]
Hi,

I am trying to add a field into an existing section from my child theme, I have found ways to add a section and many filters: to change existing fields... but I can't find a way to create/append one.

I have found this in your documentation:

```php
Redux::setField($opt_name, $field)
```

setField requires two parameters. First, the $opt_name string value, the second, an array of field data.  Be sure to add the key/pair 'section_id' => "id of section" (replace “id of section” with the actual section ID) to your field array. This is necessary so the field is set to the correct section.

The problem is also that sections and subsections are declared without IDs... Is there a way to do this?

I tried finding the id with developer inspector and doing something like this:

```php
function add_latest_articles($sections) {

	$sections[45] = array(
			'fields' => array(

				array(
	                'id' => 'single_posts',
	                'type' => 'switch',
	                'title' => esc_html__( 'Display Latest Articles posts box', 'herald' ),
	                'subtitle' => esc_html__( 'Choose if you want to display Latest Articles on single posts.', 'herald' ),
	                'default' => true,
	                'section_id' => 45,
				)
			)
		);

	/*
	$opt_name = 'herald_settings';
	$field = array(
                'id' => 'single_posts',
                'type' => 'switch',
                'title' => esc_html__( 'Display Latest Articles posts box', 'herald' ),
                'subtitle' => esc_html__( 'Choose if you want to display Latest Articles on single posts.', 'herald' ),
                'default' => true,
                'section_id' => 45,
            );
	Redux::setField($opt_name, $field);
	*/

	return $sections;

}
add_action('redux/options/herald_settings/register', 'add_latest_articles');
```

Regards,
Ivan

**Comment by reliable-mantra** [comment]
I added a new section for my child theme and put the field there:

```php
function add_latest_articles($sections){
    $sections[] = array(
    	// Redux ships with the glyphicons free icon pack, included in the options folder.
        // Feel free to use them, add your own icons, or leave this blank for the default.
    	'icon' => 'el-icon-wrench',
        'title' => esc_html__( 'Child Theme Settings', 'herald' ),
        'desc' => esc_html__( 'These are settings for child-theme', 'herald' ),
        'fields' => array(

        	array(
                'id' => 'section_latest_articles',
                'type' => 'section',
                'title' => esc_html__( 'Latest Articles', 'herald' ),
                'indent' => false
            ),

			array(
	            'id' => 'single_posts',
	            'type' => 'switch',
	            'title' => esc_html__( 'Display Latest Articles posts box', 'herald' ),
	            'subtitle' => esc_html__( 'Choose if you want to display Latest Articles on single posts.', 'herald' ),
	            'default' => true,
			)

    	)
    );

    return $sections;
}
// In this example OPT_NAME is the returned opt_name.
//add_filter("redux/options/OPT_NAME/sections", 'add_another_section_bl');
add_filter("redux/options/herald_settings/sections", 'add_latest_articles');
```

Still, I would like to know is it possible and how to add a field to an existing section from a child theme?

**Comment by kprovance** [comment]
You're still using the 'legacy' way to write your fields.  If there was a way using the legacy method, I don;t know.  We've moved on to the API way (https://docs.reduxframework.com/core/redux-api/).

With the API, it's as simple as using setSection, and specifying a priority number in the section argument as to where inthe panel you want the section to appear.

The same can be done with fields, provided the section ID is passed.  Please read the link to the API docs provided for more information.

If you have to stay with the legacy method, we'd ask you purchase premium support since 1) It's depreciated and 2) I'd have to stop what I'm doing to figure out if it's even possible.

**Comment by reliable-mantra** [comment]
Hi, thank you for Your answer!

I used 'legacy' way because I found this example online and it worked.. The theme I am trying to affect trough a child-theme uses:

```php
/* Branding */
Redux::setSection( $opt_name , array(
        'icon'      => ' el-icon-smiley',
        'title'     => esc_html__( 'Branding', 'herald' ),
        'desc'     => esc_html__( 'Personalize theme by adding your own images', 'herald' ),
        'fields'    => array(

            array(
                'id'        => 'logo',
                'type'      => 'media',
                'url'       => true,
                'title'     => esc_html__( 'Logo', 'herald' ),
                'subtitle'      => esc_html__( 'Upload your logo image here, or leave empty to show the website title instead.', 'herald' ),
                'default'   => array( 'url' => esc_url( get_template_directory_uri().'/assets/img/herald_logo.png' ) ),
            ),
```

and the pattern is the same, sections don't have id declared while fields do.

Can You give me an example how would I go about adding a field to this Branding section if it had an 'id' => 'branding'? And which filter or action to use in child themes functions.php?

**Comment by kprovance** [comment]
First, Redux is outdated.  You should have read this first, https://github.com/reduxframework/redux-framework/blob/master/CONTRIBUTING.md.  The link was at the tp of the New Issues page.

Second, all I can really do is tell you to go back and read the API documentation page.  setField is what you want.  You pass the opt_name and the field array.  In your field array you add the `section_id` argument and pass the id of the section to add to.  

In your example code, you have to add the `id` argument to your setSection.  If no ID is set, it cannot be referenced in your field array.  Again, all explained here:  https://docs.reduxframework.com/core/redux-api/

For me to to give you actual working code, I'd have to delve into your project, which is a premium service.

**Comment by svincoll4** [comment]
For someone else needs the answer, put this in your functions.php file

```

add_action('after_setup_theme', 'child_load_redux_settings');
function child_load_redux_settings(){
    if ( class_exists( 'Redux' ) ) {
        $opt_name = "redux";
        Redux::setField($opt_name, array(
            'section_id' => 'header-nav-general',
            'id' => 'secondary_logo',
            'type' => 'media',
            'title' => __('Secondary Logo Upload', 'ss'),
            'subtitle' => __('Upload your secondary logo here.', 'ss'),
            'desc' => ''
        ));
    }
}

```

**Comment by kprovance** [comment]
Nice!  Thanks for the share!  :)

**Comment by javed-codified** [comment]
> 
> 
> For someone else needs the answer, put this in your functions.php file
> 
> ```
> 
> add_action('after_setup_theme', 'child_load_redux_settings');
> function child_load_redux_settings(){
>     if ( class_exists( 'Redux' ) ) {
>         $opt_name = "redux";
>         Redux::setField($opt_name, array(
>             'section_id' => 'header-nav-general',
>             'id' => 'secondary_logo',
>             'type' => 'media',
>             'title' => __('Secondary Logo Upload', 'ss'),
>             'subtitle' => __('Upload your secondary logo here.', 'ss'),
>             'desc' => ''
>         ));
>     }
> }
> ```

I tried you code but didn't work for me . Can you please help me
