### ISSUE TITLE
Getting a error gzinflate()?

### ISSUE THREAD

**Issue by contempoinc** [reduxframework/redux-framework#2898]
Got this back from a reviewer on Themeforest seems there's an error being thrown for gzinflate()?

http://envato.d.pr/nU2A/14gbE1kx

I'm running the latest version of the framework, no other mods or anything just straight "out of the box".

**Comment by kprovance** [comment]
Unfortunately, that gzinflate issue is a well kown WordPress core issue.  There isn;t much we can do about it.

**Comment by contempoinc** [comment]
Ok, cool I'll bring it to the reviewers attention.
