### ISSUE TITLE
Override dev_mode to false on live site with 'localhost' as a server name

### ISSUE THREAD

**Issue by champsupertramp** [reduxframework/redux-framework#2899]
Hi,

I hosted my site on cloudways.com 
Redux Framework detects the server name 'localhost' and automatically enables the dev mode on a live site.

How do i override this? is this an issue with the framework? I already set the dev_mode to false in my config file.

Regards,

**Comment by kprovance** [comment]
This is by design.  dev_mode needs to be enabled during development, so that when folks come to us with issues, we can get the proper information.  When they turned it off, it made our jobs much more difficult.  So in localhost and WP_DEBUG modes, Redux dev_mode stays on.

**Comment by champsupertramp** [comment]
Hi,

I have another WP site in production mode which has the following code in wp-config.php

```PHP
define('WP_DEBUG', false);

define('WP_DEBUG_LOG', false);
```

and site's host name is localhost.

I still keep getting the Redux Framework debug mode even when it is set to false:
```PHP
'dev_mode'          => false,
			
```

Let me know if you need more details.

**Comment by kprovance** [comment]
Expected behaviour.  Redux goes into dev mode when WP_DEBUG is active or in a localhost environment.  Too many devs would turn it off in the dev environment, and then ask for support without it turned on, which is why we decided to do this.  Your live site will not show dev_mode as enabled as long as it's set to false.  If you mouse over the dev mode enabled badge, the tooltip will tell you why it's enabled.

**Comment by oakwoodgates** [comment]
@kpodemski A lot of webhosts use localhost by default when set up. It would still be nice to turn dev mode off.

**Comment by kprovance** [comment]
And then we lose our ad network and other valuable information when people come looking for support.

**Comment by dovy** [comment]
@oakwoodgates it's a fine line. If you have any idea how to support the majority of our developers while on certain hosts that use localhost, that would be good to know. But I've been doing hosting for years and we don't typically set a domain to be localhost. It's usually the domain.  :)

**Comment by dovy** [comment]
@oakwoodgates It appears you are a bit frustrated, so I'll post this here.

Our ads are a basis of how we sustain further development with Redux. If you would like to support the project and rid yourself of ads, you can purchase our inexpensive ad blocking extension https://reduxframework.com/extension/ad-remover/. However, if you're just going to continue slandering, I fear we're not really motivated to assist.

Truly I hope you figure out your problems and the project you are working on is a great success.

**Comment by dovy** [comment]
Found a solution I believe. Modify `/etc/hostname` on your server to have a name and reboot.  :)
