### ISSUE TITLE
Get data on one page from different pages and posts 

### ISSUE THREAD

**Issue by swapnilshetes** [reduxframework/redux-framework#2900]
Hi, 

In WP admin I have created pages with page meta data like below  : 
Home page : Slider with upload images 
About page : Different types of information and some images (using repeated uploader)
Out Thoughts  Post type : having posts

I have concerns that I have to show all information on landing page (front end not admin side) for example on landing page I want show slider with info then About page data and Out thoughts on one page so how can I achieve this in redux framework . because I have tied to show this is on one page I got the empty data. but when I called individual page then that data/information appeared correctly. 

 I tried with **global $redux_demo **  but this has show me only page or post wise data. Any method that should overrider to display all pages and post data 

So can you please help me out hoe can I achieve this different page and post data on one landing page.

Thanks.

**Comment by kprovance** [comment]
Please review:  https://github.com/reduxframework/redux-framework/blob/master/CONTRIBUTING.md

**Comment by kprovance** [comment]
Closing due to lack of reply.
