### ISSUE TITLE
What to change black alpha over slider

### ISSUE THREAD

**Issue by ViviLo** [reduxframework/redux-framework#2901]
![issue1](https://cloud.githubusercontent.com/assets/1589033/13858733/e53a38cc-ec4d-11e5-8b6d-6883663251a8.jpg)

What to change the alpha color over the image slider, but I can't find the css for delete it.

Please help me!

**Comment by kprovance** [comment]
We, Redux, are not the author of this theme.  You need to contact the theme author for support.
