### ISSUE TITLE
Malware detected in files

### ISSUE THREAD

**Issue by ghostpool** [reduxframework/redux-framework#2903]
Hi there,

I've had a number of users suddenly email me telling me the following files have malware (field_border.js and field_border.min.js). I downloaded a brand new copy of the framework from Github ran the files through VirusTotal.com and get the same malware notice. You can view it here:
https://www.virustotal.com/en/file/edcb98b5fc26d20c953ae621c3d19d4da3fddfb16cddaa8d33e0c6083cb2f057/analysis/1458381110/

I have no idea if this is a false positive but wanted to let you know.

**Comment by kprovance** [comment]
Avast, huh? Hmm.  Anyways, I downloaded Redux and examined the border field js and min.js.  No malware.   It would have been extremely helpful had that site/report actually identified what it believed to be an issue, versus being as vague as 'it don't work, fix it'..  I did not see that information, but yeah, total false positive here.  Maybe it didn't like the word 'keypress' or 'keydown', which appear in the js file?  Who knows!  :)

**Comment by phpbits** [comment]
Same here on border_field.js but removing this code fixed it. 

`$( document ).ready(
        function() {

        }
    );`

There is no use for this code right? Maybe it's better just to remove it. Thanks!

Cheers,
phpbits

**Comment by kprovance** [comment]
Fixed, pushed v.3.5.9.8.  Thanks again.  Cheers!

**Comment by ghostpool** [comment]
It seems like a recent antivirus update is triggering this warning, prior to today nobody reported this and then all of a sudden I've had a lot of customers get this warning. The point is, false positive or not people's antivirus software is preventing them from downloading Redux or any theme including the framework. You may want to make the changes to these files that phpbits suggested otherwise I suspect you'll be getting a lot more tickets about this over the coming days.

**Comment by kprovance** [comment]
For anyone reading, what has happened is that the Avast check didn't like the empty document.ready in the border field JS.  Not sure why that's such a threat.  It was leftover code when we moved our field javascripts to lazy load.  Our fields don;t use document.ready anymore.  Guess one of us forgot to remove it.  Anyways, it's been removed.  I'll get with @Dovy about pushing this to wp.org next week.

**Comment by ghostpool** [comment]
Thanks for the quick fix.
