### ISSUE TITLE
Can't edit Custom CSS/JS panel

### ISSUE THREAD

**Issue by jeffceriello** [reduxframework/redux-framework#2904]
Hi there,

I need to make some amends to a live site and to do that I have copied it locally. On the live version I am able to amend the Custom CSS/JS panels but it doesn't let me on localhost.

Why is that? Here is a screenshot.

![screen shot 2016-03-20 at 11 30 25](https://cloud.githubusercontent.com/assets/5859601/13903932/350d2466-ee8f-11e5-9a12-2cfc4bdce286.png)

Thank you
Jeff

**Comment by kprovance** [comment]
Please review:  https://github.com/reduxframework/redux-framework/blob/master/CONTRIBUTING.md

**Comment by kprovance** [comment]
No reply.  Closing.
