### ISSUE TITLE
Why are paragraphs removed in editor fields?

### ISSUE THREAD

**Issue by stephanemartinw** [reduxframework/redux-framework#2906]
Hi 

I use the last version of Redux to build 'editor' fields.
Even if documentation indicates the wpautop is true by default, <p> are not inserted and also removed from my texts in the admin panel, when manually added.

When googling, I can find other people that have encountered this problem, but no solution.

Is it a redux issue or a WP settings to override (a snippet in functions.php ?) ?

Thank you for your help, 

Stephane

**Comment by kprovance** [comment]
Again, the mysteries of why the editor act the way it does confounds us all.  First, we do not set wpautop true by default.  If it's set to true by default, then it's something WordPress does.  That said, I checked my theme to see what was going on.  I have wpautop set to true.

![image1](https://cloud.githubusercontent.com/assets/3412363/13966893/ebf633f4-f04a-11e5-9f7e-bfddc4b901c5.png)

Working.  Understand that ALL Redux does is initiate the wp_editor API, feeding it the args supplied in the field array.  We made no internal alterations to that information.  If the editor is not acting as expected, the fault is not with Redux.  There are SO many plugins and ways to alter the editor field, I couldn't begin to offer a suggestion.  Sorry.  If you should find out what's going on, post back.  :)

**Comment by stephanemartinw** [comment]
Hi, 

You're right! wp's editor works like this in wpautop=true mode (default), ie no paragraphs are used in the editor but a filter adds them when displaying!.
Thanks for your answer that makes me understand where I was wrong.

I could not display in the editor the <p> tags because for this you need to set wpautop to FALSE! in Redux:
 array(
                        'id'        => 'about-description',
                        'type'      => 'editor',
                        'title'     => __('About Description', 'redux-framework-demo'),
                        'subtitle'  => __('Type some description', 'redux-framework-demo'),                        
                        'default'   => 'Sample Text',
                        'args' => array (
                            **'wpautop' => false**
                        )
                    ), 


Another solution is to keep the default wpautop mode to true, but to add a wpautop() call when displaying the text entered in my theme settings (with redux) in my page template : 

<?php echo wpautop($var['the-description']); ?>
instead of just :
<?php echo $var['the-description']; ?>

because wp's default filters only apply to post's body and excerpt.

Thanks!
