### ISSUE TITLE
Allowed memory size of 134217728 bytes exhausted (tried to allocate 130968 bytes) in /home/eleme915/public_html/wp-content/themes/ronneby/inc/lessc.inc.php on line 1384

### ISSUE THREAD

**Issue by bob519** [reduxframework/redux-framework#2908]
Allowed memory size of 134217728 bytes exhausted (tried to allocate 130968 bytes) in /home/eleme915/public_html/wp-content/themes/ronneby/inc/lessc.inc.php on line 1384
Is this my hosting company or soething I have to fix seems like a host papa issue

**Comment by kprovance** [comment]
Again, folks, Redux Framework is not the author of your theme.  We do not support themes.  You MUST contact the author of your theme for ANY type of support.  That's what you paid THEM for. Thanks.
