### ISSUE TITLE
Events Page/Widget Not Working

### ISSUE THREAD

**Issue by briananddiana317** [reduxframework/redux-framework#2910]
I have tried a bunch of different ways to get the events page & widget to work and no matter what I try, it's not showing the events on the page/widget. Am I missing something?

![events1](https://cloud.githubusercontent.com/assets/18071313/14045938/4c49ea36-f274-11e5-9683-da299fdbe358.JPG)
![events2](https://cloud.githubusercontent.com/assets/18071313/14045942/51d5f468-f274-11e5-8291-095f68af839b.JPG)
![events3](https://cloud.githubusercontent.com/assets/18071313/14045945/5537d2b6-f274-11e5-92cb-24b59273c47c.JPG)
![events4](https://cloud.githubusercontent.com/assets/18071313/14045948/59483710-f274-11e5-9b65-1c324da4dec2.JPG)

**Comment by kprovance** [comment]
Once again, Redux is NOT the author of your theme, or ANY theme.  We do not support themes that use our framework.  That is the responsibility of the theme author.  Please contact them for support.
