### ISSUE TITLE
Theme Check ERROR: Those are Okay with ThemeForest or WordPress.org?

### ISSUE THREAD

**Issue by sojibrahmanbd** [reduxframework/redux-framework#2911]
Hi, 
I got Some error in my new developed theme. Here is those; 

**WARNING**: Found PHP short tags in file parsedown.php.
Line 765: if (preg_match('/^\[(.+?)\]:[ ]*<?(\S+?)>?(?:[ ]+['\'(](.+)['\')])?[ ]*$/', $Line['text'], $matches))

**REQUIRED: welcome.php. **Themes should use add_theme_page() for adding admin pages.
Line 197: $page = 'add_management_page';

**REQUIRED: framework.php. **Themes should use add_theme_page() for adding admin pages.
Line 1421: $this->page = call_user_func( 'add_menu_page', $this->args['page_title'], $this->args['menu_title'], $this

**REQUIRED: framework.php.** Themes should use add_theme_page() for adding admin pages.

**Line 1344**: // wrappers and need to be appened to using add_submenu_page.

**Line 1395: **$this->page = call_user_func( 'add_submenu_page', $page_parent, $page_title, $menu_title, $page_permission

**Line 1453:** call_user_func( 'add_submenu_page', $this->args['page_slug'], $section['title'], $section['t

Did i skip those error or i need to fix them?

Thanks

**Comment by kprovance** [comment]
Asked and answered:  https://github.com/reduxframework/redux-framework/issues/2430
