### ISSUE TITLE
Loading Redux fails when it is included in a theme and there is a symlink in the path

### ISSUE THREAD

**Issue by bazza** [reduxframework/redux-framework#2912]
Somewhat related to #1432:

In `sample-config-legacy.php`  there is this code:
```
// This is needed. Bah WordPress bugs.  ;)
if ( true == Redux_Helpers::isTheme( __FILE__ ) ) {
    $this->initSettings();
} else {
    add_action( 'plugins_loaded', array( $this, 'initSettings' ), 10 );
}
```
As the issue title suggests, if Redux is installed as part of a theme, and you have a symlink anywhere in the path, this check fails.  This is because PHP's `__FILE__` will resolve the symlink, but later on in `Redux_Helpers::isChildTheme` and `Redux_Helpers::isParentTheme` the results are compared to `get_stylesheet_directory()` which will **not** resolve the symlink.   If we are going to compare, we should compare apples to apples.  Probably the easiest way to do this would be to replace calls to      `self::cleanFilePath( get_stylesheet_directory() )`  with `self::cleanFilePath( realpath( get_stylesheet_directory() ) )`  

Can you let me know if this change is something you would accept and if you would like a PR for it?

**Comment by kprovance** [comment]
I would suggest using the Redux API to build your options.  The legacy method is no longer supported.  Also, SYmlinks don't work well either.
