### ISSUE TITLE
Draggable Slides Parallax

### ISSUE THREAD

**Issue by gordo019** [reduxframework/redux-framework#2913]
I am trying to incorporate a Parallax slider into my Redux Theme Options and Homepage Layout Manager, so the Parallax module can be configured with selected images and inputted text.
See:
http://freshvoodoo.com/blog/
It seems like the Redux Media Upload Slides would allow selecting any amount of desired images and the inputting of text to create a Parallax module, when enabled by the Homepage Layout Manager.
Can you direct me to the necessary Redux config code to setup a slides in my Homepage Layout Manager?
And secondly, what PHP loop would display those slides images and text? Maybe just point me towards an eventual solution to creating this desired homepage module. I want my client to be able to build the Parallax without coding, just using the homepage theme options.

**Comment by kprovance** [comment]
PHP falls under premium support.  We don't have the time or resources to do that kind of thing for free anymore.

We have a premium extension that allows for the selecting of multiple images from the WP media library.  https://reduxframework.com/extension/multi-media/.  But Redux out of the box?  Yeah, the slider field would probably be your closet alternative.
