### ISSUE TITLE
Customiser Support

### ISSUE THREAD

**Issue by Kieran-Calvert** [reduxframework/redux-framework#2916]
Hi Guys

Love Redux and would love to lend support

I was trying to get my hands on the new full customiser support version but cannot seem to find a purchase link or any updated information on it. The page at https://ideas.reduxframework.com/campaigns/complete-customizer-integration/?_ga=1.23016059.1796581023.1445937785# seems months out of date.  Is it still in the works?

Thanks

Kieran

**Comment by kprovance** [comment]
It's still in the works.  We are aiming to have it ready as part of the 'extension club' bundle by June, or so.  :)

**Comment by Kieran-Calvert** [comment]
Great Kevin

Really looking forward to it!

Thanks

Kieran
