### ISSUE TITLE
Customizer files missing forward slash

### ISSUE THREAD

**Issue by ghostpool** [reduxframework/redux-framework#2917]
Hi there,

Version: 3.5.9.8

When using the Customizer extension_customizer.css and extension_customizer.js return 404 errors because they're missing a forward slash in the URL e.g. .../ReduxCore/inc/extensions/customizerextension_customizer.css?ver=1460104308

I fixed this by adding forward slashes to lines 145 and 149 in  ReduxCore/inc/extensions/customizer/extension_customizer.php.

**Comment by kprovance** [comment]
People keep changing the way those paths are formed with pull requests and whatnot.  I'm not surprised if it's busted.

**Comment by ghostpool** [comment]
What people are changing the way those paths are formed? Are you referring to WordPress?

**Comment by dovy** [comment]
Fixed.
