### ISSUE TITLE
Fetching value from Redux api function Redux::getField or Redux::getSection

### ISSUE THREAD

**Issue by Asktofreelancer** [reduxframework/redux-framework#2918]
I am new to Redux framework. Have gone through all the doc. but didn't find how to call or get the value from the new Api function.

When i used getField or getSection method then it returns an array but no field value there. here is my code
$var = Redux::getField('harish','footer1-text');    
    echo "<pre>";
    print_r($var);
Array
(
    [id] => footer1-text
    [type] => text
    [title] => copyright info
    [section_id] => footer1
    [placeholder] => Enter copyright info. here
    [priority] => 5
)

Could you please guide me or share any sample site having example code.

Thanks,
Harish

**Comment by kprovance** [comment]
Because getField and getSection does exactly that, gets the array data for the section and field.  `getOption ($opt_name, $key)` is probably what you want.

**Comment by Asktofreelancer** [comment]
getField and getSection returns an array, but  how will i get any field value, suppose I enter the value in theme option->footer section-> footer text field  and saved the value "copywright info@ 2016" from backend, I want to fetch the value and display it in my footer section.

**Comment by kprovance** [comment]
That's not how you're supposed to fetch setting using Redux.  Please see Step 3 on this page on how to properly retrieve saved settings:  https://docs.reduxframework.com/core/getting-started/
