### ISSUE TITLE
_transient__redux_activation_redirect slow queries and hang

### ISSUE THREAD

**Issue by iPublicis** [reduxframework/redux-framework#2920]
Hi,

Having this issue that is rising a lot of complaints from the customer. This is a webstore so you can imagine the kind of complaints we are getting.

The site hangs a lot and has some slowiness. I installed Query Monitor and I got a lot of slow queries related to this:

```
UPDATE `huberthwp_options`
SET `option_value` = '1'
WHERE `option_name` = '_transient__redux_activation_redirect'
```

How can I solve this?

**Comment by kprovance** [comment]
Please review:  https://github.com/reduxframework/redux-framework/blob/master/CONTRIBUTING.md

**Comment by iPublicis** [comment]
You must be joking.

**Comment by kprovance** [comment]
No, actually.  We need to know the Redux config and the support URL of the affected system.  It is *impossible* for us to even begin to hazard a guess based on a single message from 'query monitor'.

**Comment by kprovance** [comment]
Closing due to lack of reply.

**Comment by davidfavor** [comment]
Redux Framework fails on high traffic servers.

The original information posted is sufficient to understand the problem.

If you have a high traffic Web site, ways to fix include.

1) Best - avoid any theme using this code.

2) In file redux-framework/ReduxCore/inc/welcome/welcome.php comment out...

update_option( 'redux_version_upgraded_from', ReduxFramework::$_version );
set_transient( '_redux_activation_redirect', true, 30 );

This instantly stop server thrashing mysql + returns site performance.

To the developers, please rethink the function of this code, to stop mysql thrash.

**Comment by dovy** [comment]
#1 Please don't piggyback old threads.
#2 This code is from WooCommerce
#3 Seems like your server blocked transients. Sure you're not using a third party plugin that did that?  ;)
