### ISSUE TITLE
Flexwrite - How do I change the background image/photo in the default settings of the Theme

### ISSUE THREAD

**Issue by nicdan63** [reduxframework/redux-framework#2921]
The settings offer to upload a photo image but I would like to have a white/transparent background. The image consistently shows the wheat photo from the default on the theme.

Now uploaded a photo and still it does not replace the default theme image of the wheat field.

**Comment by nicdan63** [comment]
[www.marniesstreet.com](url)

**Comment by kprovance** [comment]
We are not the author of this theme.  You need to contact them for support.
