### ISSUE TITLE
'page_parent' => '_dev_theme_welcome',

### ISSUE THREAD

**Issue by samushi** [reduxframework/redux-framework#2922]
`'page_parent'   => '_dev_theme_welcome', `

This option not working for me can help me someone?

**Comment by kprovance** [comment]
I'm sorry, but you're going to have to be a bit more specific.  Please review:  https://github.com/reduxframework/redux-framework/blob/master/CONTRIBUTING.md

**Comment by kprovance** [comment]
Closing due to lack of reply.
