### ISSUE TITLE
Cant save editor field with "Database: Network" settings

### ISSUE THREAD

**Issue by db-dzine** [reduxframework/redux-framework#2923]
Hello,

seems like there is an error  when trying to save the editor field with 'database': 'network' settings.

Strange: It only appears when I try to set text align to center ...

The Error: 
![bildschirmfoto 2016-04-14 um 10 37 23](https://cloud.githubusercontent.com/assets/3169388/14522093/34374af6-022d-11e6-9566-f8b10ef0e5b2.png)

The Text
![bildschirmfoto 2016-04-14 um 10 37 39](https://cloud.githubusercontent.com/assets/3169388/14522103/392d27c4-022d-11e6-8f9b-5c9f35bc871d.png)

**Comment by kprovance** [comment]
Please review:  https://github.com/reduxframework/redux-framework/blob/master/CONTRIBUTING.md

**Comment by kprovance** [comment]
Closing due to lack of reply.
