### ISSUE TITLE
Script Error

### ISSUE THREAD

**Issue by bcdrendel** [reduxframework/redux-framework#2924]
This is causing my slider on the home page to disappear. It was working before the most recent wordpress update. 

The script in question that causes the javascript error when the plugin above is enabled is:

<script>(function ($, window, document, undefined) {
	'use strict';
		$(function() {
				$('a[href*=#]:not([href=#])').click(function() {
				if (location.pathname.replace(/^\//,'') == this.pathname.replace(/^\//,'') && location.hostname == this.hostname) {
					var target = $(this.hash);
					target = target.length ? target : $('[name=' + this.hash.slice(1) +']');
					if (target.length) {
					$('html,body').animate({
						scrollTop: target.offset().top
					}, 1000);
					return false;
					}
				}
				});
			});
})(jQuery, window, document);</script>	

Here is the error I get in Mozilla firefox when the plugin is enabled (which means the above script is present):

Error: Syntax error, unrecognized expression: a[href*=#]:not([href=#])

**Comment by kprovance** [comment]
Please review:  https://github.com/reduxframework/redux-framework/blob/master/CONTRIBUTING.md

**Comment by kprovance** [comment]
I am seeing no script errors with the Redux slider field with our latest version from this repo.  If you are the theme author, please upgrade.  If you are a theme user, please contact the theme author for support.
