### ISSUE TITLE
Any ETA on when the customizer will support all features?

### ISSUE THREAD

**Issue by kmob2** [reduxframework/redux-framework#2925]
Hello,

I donated exactly 1 year ago to make redux compatible with the customizer and to get early access.
Most of the features have been working ever since I got early access, except for 1 major one, the "required" field. Now a year later it's still and outstanding issue.

Is there any ETA on when that feature will be implemented?

**Comment by kprovance** [comment]
Hi.  Please post customizer issues here:  https://github.com/reduxframework/customizer-integration/issues
