### ISSUE TITLE
Redux framework constantly redirecting to the about page

### ISSUE THREAD

**Issue by FrankM1** [reduxframework/redux-framework#2926]
Hi guys,

An obscure behaviour bug has been reported by the Themeforest review team regarding the plugin. When you click on posts it redirects to the about redux page. I am not quite sure what is triggering it. 

See the screencast below for the behaviour.
http://envato.d.pr/1dxKo/5jmsZo7V

Anyway, I've been able to fix it by adding the code below to the theme. 

<pre>add_action( 'redux/construct', 'radium_remove_as_plugin_flag' );
/**
 * Remove plugin flag from redux. Get rid of redirect
 *
 * @since 1.0.0
 */
function radium_remove_as_plugin_flag() {
    ReduxFramework::$_as_plugin = false;
}</pre>

Any idea why this redirect is happening?

**Comment by kprovance** [comment]
I hate to keep asking this, folks, but please, READ OUR SUPPORT GUIDELINES FIRST, BEFORE POSTING!  I have an issue tracker full of posts and no information.  Support URLS ARE A MUST.  Please.

https://github.com/reduxframework/redux-framework/blob/master/CONTRIBUTING.md

**Comment by kprovance** [comment]
Try removing your hook and see what happens.

**Comment by FrankM1** [comment]
I have resolved the issue using the code I've included. I posted this because I wanted to gain an understanding of why it happened in the first place. I figured this is the best place to ask. Anyway ...never mind. 

Hopefully this will help someone who comes across a similar problem in future.

**Comment by kprovance** [comment]
Please note, whomever does this, if Redux is not installed as a plugin, there might be unpredictable behavior.  That flag is set the way it is for a reason.  If so, you're on your own.  :).
