### ISSUE TITLE
Customizer update sections and field in new url

### ISSUE THREAD

**Issue by PayteR** [reduxframework/redux-framework#2927]
Hi, i'm currious, if there is some way how can i update customizer sections "from inside of iframe". 

For example, when i'm in customizer, and have some field, for example "Homepage sidebar visible" checkbox, i want to have this field just on homepage in customizer and when i click to some post in iframe, i want this field disapear, and vice versa... can i somehow achieve this? thx

**Comment by kprovance** [comment]
Hi.  Please post customizer issues here:  https://github.com/reduxframework/customizer-integration/issues

**Comment by PayteR** [comment]
hi, i have replied many times, even from my gmail email, but still no answer, whats the problem?
