### ISSUE TITLE
Wrong default options in type "border"

### ISSUE THREAD

**Issue by kisonic** [reduxframework/redux-framework#2928]
This my option:

	array(
		'id' => 'header-border',
		'type' => 'border',
		'title' => esc_html__('Header border', 'trendy'),
		'subtitle' => esc_html__('Select a custom border to be applied in the header.', 'trendy'),
		'all' => false,
		'left' => false,
		'right' => false,
		'color' => false,
	),
And this default settings:

	["header-border"]=> {
		["border-top"]=>
		string(2) "px"
		["border-right"]=>
		string(2) "px"
		["border-bottom"]=>
		string(2) "px"
		["border-left"]=>
		string(2) "px"
		["border-style"]=>
		string(5) "solid"
		["border-color"]=>
		string(5) "solid"    // bug
	}
But must be like this:

	["header-border"]=> {
		["border-top"]=>
		string(0) ""
		["border-right"]=>
		string(0) ""
		["border-bottom"]=>
		string(0) ""
		["border-left"]=>
		string(0) ""
		["border-style"]=>
		string(0) "solid"
		["border-color"]=>
		string(0) ""
	}
Or better like this:

	["header-border"]=> {
		["border-top"]=>
		string(0) ""
		["border-bottom"]=>
		string(0) ""
		["border-style"]=>
		string(0) "solid"
	}

Can you fix it?

Wordpress: 4.5

Redux Framework: 3.5.9

Developer Mode Enabled

**Comment by kprovance** [comment]
I believe that has been fixed in the version available on this repo.

**Comment by kisonic** [comment]
When it will be available in wordpress plugins?
