### ISSUE TITLE
Wordpress 4.5 update - page not loading

### ISSUE THREAD

**Issue by srivatsan73** [reduxframework/redux-framework#2929]
After the wordpress 4.5 update, the Redux Framework plugin causes the page to not load. If I disable the plugin the page loads ok.

Is there an update that works with the Wordpress 4.5 update?

**Comment by kprovance** [comment]
Redux is WordPress 4.5 ready.  We're going to need much more info from you.  Please review:  https://github.com/reduxframework/redux-framework/blob/master/CONTRIBUTING.md

**Comment by kprovance** [comment]
Assuming you are using the latest version of Redux from this repo.

**Comment by srivatsan73** [comment]
We are on version 3.5.9 of the Word Press Plugin.

Problem is resolved now - Had to fix the issue manually. Problem was with the dropout js /wp-content/themes/dropout/javascript/theme.js. Am guessing the Redux Framework uses this. Wordpress 4.5 upgraded query to 1.12.. and it doesnt like the following syntax: line 155

	$('a[href*=#]:not([href=#]):not([data-toggle])').click(function() {

had to be changed to

	$('a[href*="#"]:not([href="#"]):not([data-toggle])').click(function() {

Thanks

**Comment by kprovance** [comment]
Ya.  That would be a theme issue, not a Redux issue.  Theme and plugins are pretty much required to use the version of jQuery included with Wordpress, so we abide by that guidelines.  Cheers!
