### ISSUE TITLE
Using PHP with the Raw field

### ISSUE THREAD

**Issue by cocodedesigns** [reduxframework/redux-framework#2931]
Hi,

I'm bringing in a PHP file through the Raw field and I want to use the built in Wordpress functions (or any PHP function) within the code, like when I have an image, I want to be able to use the `get_template_directory_uri` function to look in my theme directory.  However, it inserts the PHP code as part of the image, thus making my image source `<?php echo get_template_directory_uri(); ?>/images/my-image.php` instead of `http://www.mysite.com/wp-content/themes/my-theme/images/my-image.php`.  Is there a way of getting this supported so that I don't need to worry about the installation that I use?

**Comment by kprovance** [comment]
PHP code cannot be used in the raw field.

**Comment by dovy** [comment]
The faw field CAN include a PHP file though. You'd just have to specify it as test to show it.

**Comment by cocodedesigns** [comment]
I know that the raw field can run PHP code, or at least the PHP code that I am looking to run, which is just a couple of Wordpress functions that get information from the site options.  If I place the PHP code inside the `content` variable, it will run perfectly.  The problem comes when I put PHP code inside of an external file, which is then declared as the data in either the `content` or `content_path` variable. It is the PHP code inside of this file that is not running. I can declare the file and any HTML is being inserted as required, so it is finding the file and inserting it, but the PHP code inside there doesn't seem to be executing.  So far, I have used the following:

`dirname( __FILE__ ) . '/theme-info.php'`
`file_get_contents( dirname( __FILE__ ) . '/theme-info.php' )`
`include( dirname( __FILE__ ) . '/theme-info.php' )`
`include_once( dirname( __FILE__ ) . '/theme-info.php' )`
`require( dirname( __FILE__ ) . '/theme-info.php' )`
`require_once( dirname( __FILE__ ) . '/theme-info.php' )`

`include` and `require` do execute the PHP code, but not inside of the content area.  The others just include the PHP code as though it was plain text.

@dovy You said I would need to specify it as test to show it.  What do you mean by this?
