### ISSUE TITLE
Options Panel not visible after update to RF 3.5

### ISSUE THREAD

**Issue by Dannci** [reduxframework/redux-framework#2932]
Hello,

options panel is not visible after update to 3.6 version. Checked in FF and Chrome: http://prnt.sc/at8lbu
And when I expand options panel (hide sidebar menu), font selector is not visible: http://prnt.sc/at8mcb

Also here is error which is visible in console: http://prnt.sc/at8pjm

Support URL: http://support.redux.io/?id=gHDSOSPhZn8YgdIrkb9ET7Gr8F%2BituqU4W512dlkqJWfT1Pfil8TtWSUd2V6UmURQpJsM6oy4gTTWSzMRgTWhA%3D%3D

Thank you

**Comment by dovy** [comment]
Thanks to your config just found the issue. Re-pushed a fix just now.  :)
