### ISSUE TITLE
Cannot access posts after update to version 3.6.0

### ISSUE THREAD

**Issue by EllenGr** [reduxframework/redux-framework#2933]
After updating Redux Framework to Version 3.6.0 I cannot access the "posts" section (.../wp-admin/post.php) of my WP page. Each request is redirected to .../wp-admin/tools.php?page=redux-about

How can I fix this issue?

**Comment by kprovance** [comment]
I am not able to replicate this issue based on the provided information.  Please review our support guidelines (https://github.com/reduxframework/redux-framework/blob/master/CONTRIBUTING.md) and provide us with the necessary information to continue.  Thanks.

**Comment by ZERGE** [comment]
Try to logout and then login again.

**Comment by EllenGr** [comment]
@ZERGE: I cannot access login page after logout. Also login page is redirected to /wp-admin/tools.php?page=redux-about
@kprovanve I am not a developer. I am using the Redux Framework plugin for my WP site. Nevertheless, I would still appreciate your assistance, because the error is evident.

**Comment by kprovance** [comment]
I understand your situtation.  Now try and understand mine; either the theme or some plugin is using Redux, otherwise, why would it be on your WP setup?  Lots of times devs mess with our core and these things happen.  We *must* have that support URL, the one asked for in the support guidelines.

**Comment by EllenGr** [comment]
@kprovance Sorry I cannot generate the requested support hash. I cannot access the admin panel  and using the URL produces a 404 error...
Theme and Redux Framework plugin 3.5.9 were running stable. Error occurred immediately after updating the plugin to version 3.6.0. No other updates were made at the same time

**Comment by EllenGr** [comment]
Wait a second... I downgraded to version 3.5.9 and now I can access the admin panel again

**Comment by kprovance** [comment]
Dovy said he'd go onto your server to see what's up.  Please email WP Login info (with admin rights) and FTP Login information to support@reduxframework.com

**Comment by dovy** [comment]
@ellengr - we'd like to solve your problem. Could you send ftp and WP-admin login access and we'll get right on it. :)

**Comment by dovy** [comment]
Send the info to support@reduxframework.com

**Comment by EllenGr** [comment]
@dovy abd @kprovance sorry guys, but this sounds to me as if you'd asked me to send you my e-banking details... Is there any other way to find out what is wrong with FR 3.6.0?

**Comment by kprovance** [comment]
Well, it's like this.  We cannot reproduce it.  We need to be on a server where it actually happens to see why.  We do this all the time, that is, go onto servers of our users to fix their issues.  If you're unable or unwilling to allow this, then unfortunately, no, I have no other solution at this time.  We'll simply have to guess at it or wait for someone who experiences the same issue to allow us to debug on their server.  To fix it, I have to see it break.  It's as simple as that.  :)

**Comment by dovy** [comment]
To echo Kevin, we cannot fix what we cannot experience. 

Try installing the redux plugin again. I did a push late last night that may solve the issue. If it doesn't, we need access. Rest assured we work on many peoples sites and we have millions of installs world-wide. We have no interest of hurting of keeping your login credentials.

**Comment by EllenGr** [comment]
Thank you for your assistance, @dovy and @kprovance! You may be trustworthy, but as it seems that I solved the problem by downgrading to RF 3.5.9, my actual need for support is somewhat diluted. 
@dovy Maybe I will try to install the redux 3.6.0 plugin in the upcoming days. For now I am happy that everything is working well again.

**Comment by dovy** [comment]
Alas, tis your choice. Now we wait for someone else to experience the same but who's willing to provide the details we need.

Best of luck!
