### ISSUE TITLE
problem with section 

### ISSUE THREAD

**Issue by netcentersolution** [reduxframework/redux-framework#2935]
We bought your WordPress’s  theme „lotek”.
We have a problem when deleting section "pricing". When we doing it, the whole theme is breaking and not working correctly. There is an another problem too. 
When we trying to edit with Visual Composer, site is just looping in loading the page. Can u help us?

**Comment by kprovance** [comment]
We are not the author of that theme, or any theme.  Please direct all support request to the theme's author, as we do not support themes.  Thanks.

**Comment by dovy** [comment]
We're just the framework that they used.  :)
