### ISSUE TITLE
Still wrong default options in type "border"

### ISSUE THREAD

**Issue by kisonic** [reduxframework/redux-framework#2936]
This my option:

	array(
		'id' => 'header-border',
		'type' => 'border',
		'title' => 'Header border',
		'subtitle' => 'Select a custom border to be applied in the header.',
		'all' => false,
		'left' => false,
		'right' => false,
		'color' => false,
	),
And this default settings:

	["header-border"]=> {
		["border-top"]=>
		string(2) "px"       // must be without px
		["border-right"]=>
		string(2) "px"       // must be without px
		["border-bottom"]=>
		string(2) "px"       // must be without px
		["border-left"]=>
		string(2) "px"       // must be without px
		["border-style"]=>
		string(5) "solid"
		["border-color"]=>
		string(5) ""
	}
But must be like this:

	["header-border"]=> {
		["border-top"]=>
		string(0) ""
		["border-right"]=>
		string(0) ""
		["border-bottom"]=>
		string(0) ""
		["border-left"]=>
		string(0) ""
		["border-style"]=>
		string(0) "solid"
		["border-color"]=>
		string(0) ""
	}
Or better like this:

	["header-border"]=> {
		["border-top"]=>
		string(0) ""
		["border-bottom"]=>
		string(0) ""
		["border-style"]=>
		string(0) "solid"
	}

Only when I setup border-top = 1 and border-bottom = 1 and save changes, and then delete 1 from border-top input and from border-bottom input and save changes. Then options looks:

	["header-border"]=> {
		["border-top"]=>
		string(0) ""
		["border-right"]=>
		string(0) "px"       // still wrong
		["border-bottom"]=>
		string(0) ""
		["border-left"]=>
		string(0) "px"       // still wrong
		["border-style"]=>
		string(0) "solid"
		["border-color"]=>
		string(0) ""
	}

Can you fix it?

Wordpress: 4.5

Redux Framework: 3.6.0

Developer Mode Enabled

**Comment by kprovance** [comment]
Sorry, I can't get to it this week.  Maybe next?  This is a community project, feel free to take a look.  If you find a fix,, you can submit a pull request.

**Comment by kisonic** [comment]
Ok, take your time. And I'll try to fix it too.

**Comment by kprovance** [comment]
Fixed in 3.6.0.1 from this repo.
