### ISSUE TITLE
Is there a single number input field?

### ISSUE THREAD

**Issue by NoahjChampion** [reduxframework/redux-framework#2937]
Is there a single number input field?

**Comment by dovy** [comment]
Pretty much.  ;)

You can use the text field: https://docs.reduxframework.com/core/fields/text/

with a validate argument of `numeric`: https://docs.reduxframework.com/core/the-basics/validation/

**Comment by NoahjChampion** [comment]
Ok. 

Do you think it would be too much to ask for such a field like in the screenshot below? 

Just a single numeric field with the up and down buttons. 

I'm new, looking at Redux, but I have options to migrate to Redux and I've grouped my own design builders for custom things, using the single fields with custom css to group them how I want, but without the number field it makes it a little less savvy. I just assumed out of all the fields offered :) this was in there, but it is not. 

Again, would it be too much to request such a field to be added?

![custom theme custom theme - baby wordpress-18-04-2016-ooa3r](https://cloud.githubusercontent.com/assets/6123260/14611126/b74830b6-055e-11e6-8043-23c78a0e1457.png)

**Comment by kprovance** [comment]
We have the Spinner field, which is the same thing, only the arrows are on both ends of the field.

**Comment by dovy** [comment]
You could also use the spacing field: https://docs.reduxframework.com/core/fields/spacing/

Capable of outputting custom CSS, or just use as an input point.  :)

**Comment by NoahjChampion** [comment]
@dovy @kprovance 

Thanks, Appreciate it! 

I can work with these. 

One side question, which I doubt but will ask. 

Is there any trial type options for an extension or one that would work only on localhost? 
-- I just would like to avoid paying for an extension, namely the Metabox extension, when my finished product (a theme) will still be a minimum of 4-5 months out, ultimately losing out on 4-5 months or more of updates that are actually relevant to the end customer. 
-- While I'm not new not Wordpress, I am to coding and releasing a product. I just got tired of purchasing themes that always end up being limited and have set out to create my own, but I'm not entirely sure what I am all getting into and where that will take me. I'm learning as I go and I've already went through 2 frameworks.... so just want to ask before I decide to commit.

**Comment by kprovance** [comment]
Unfortunately, there is not.  It would be WAY too easy for dev to bypass such a check and not pay for our work, which we really need our users to begin doing.  :)

**Comment by NoahjChampion** [comment]
@kprovance 

Gotcha. Sorry, I didn't think of devs as stealing because they are devs, not hackers, but I guess hackers are devs too (or evil twins), but understood completely, lol.

**Comment by dovy** [comment]
We do have a demo site where you can see any extension in action. http://demo.redux.io/wp-admin

**Comment by NoahjChampion** [comment]
@dovy thanks. I went through the demo though... as to why I ended up at this Repo. My concern about the extensions, was because I don't know anything about post meta options and the feature/ideas I have and will come up will need tested and organized, etc. But, it will all come together sooner than later.

**Comment by dovy** [comment]
:)   Best of luck.
