### ISSUE TITLE
Theme options missing since upgrade

### ISSUE THREAD

**Issue by SarahJee** [reduxframework/redux-framework#2938]
Theme options display but are not selectable since upgrade.

**Comment by kprovance** [comment]
Redux would have nothing to do with shortcodes.  Are you the theme author or a user of a theme?

**Comment by SarahJee** [comment]
Hi, 
Sorry it's not the short codes just the theme options. I have restored the framework to an earlier version and can now access the theme options, also the issue is definitely with the upgraded framework plugin. 
Thank you,
Sarah.

**Comment by kprovance** [comment]
That's kind of a stretch without any real pertinent information.  You also didn't answer my question or provide a support URL.  All I can do is wish you best of luck.

**Comment by SarahJee** [comment]
I'm not asking for support. I'm just letting you know as others will likely have the same issue.

**Comment by kprovance** [comment]
It's not come up so far.  Sorry.  it could very well be a theme issue.  Contact the theme author for support.

**Comment by dovy** [comment]
@sarahlee. Would you provide WordPress WP-admin access and ftp access to support@redux.io. I'd like to fix this.

**Comment by GabrieleLab** [comment]
Same as @sarahlee here. Theme options display but are not selectable since upgrade. Can you please help. And its not my theme I already checked.

**Comment by kprovance** [comment]
You have two options:  Either contact the theme author and have him debug it, or allow us admin access to your site, and server access so we can debug.  Let us know!

**Comment by GabrieleLab** [comment]
@kprovance I can give you the access of my website. That will be great. Thanks. What is your email?

**Comment by kprovance** [comment]
Certainly!  info@reduxframework.com

**Comment by kprovance** [comment]
See your email.  I need to know the site login URL as well.  Or even the site name.  :)

**Comment by kprovance** [comment]
Your site is running again.  The problem was a leftover file from an older version of Redux.  WP should have removed it and put the new one is.  For whatever reason, it did not.  I updated it manually.

**Comment by GabrieleLab** [comment]
Great ! Thank you so much!
Have a nice day!

Gabrièle

1 929 394 6535
labordegabriele@gmail.com


2016-04-20 15:25 GMT-04:00 Kevin Provance <notifications@github.com>:

**Comment by kprovance** [comment]
For anyone else experiencing this issue, please update to the version from this repo (yes, it's the same number, but it has the correct file).  We'll get it updated very soon on wp.org
