### ISSUE TITLE
Illegal String Offset 'rgba'

### ISSUE THREAD

**Issue by Oebryn** [reduxframework/redux-framework#2939]
I am using an up to date version of redux and I am getting this waring: Warning: Illegal string offset 'rgba', this is as a result of the header background i set to be in rgba mode. Is there a way to solve this as I cant seem to figure out the solution?

Any help will be profoundly appreciated.

**Comment by kprovance** [comment]
Hi.  If you could please review this text and provide us with the necessary information, that would be very helpful to us.  Thanks.

https://github.com/reduxframework/redux-framework/blob/master/CONTRIBUTING.md

**Comment by kprovance** [comment]
Checking in to see if you're willing to provide us the information we need to continue.  Otherwise this ticket will be closed in two days.  Thanks.

**Comment by kprovance** [comment]
Closing issue due to lack of reply.
