### ISSUE TITLE
"Required" Argument not working on callback fields

### ISSUE THREAD

**Issue by jaschaio** [reduxframework/redux-framework#2941]
I have a few callback fields that have a required Argument. If the argument is false they showup anyway. If I change the field type to text it hides and shows just if the required argument is true.

So it looks like the required argument is not working with callback fields.

I already had back this issue in September 2015 (#2599) and @dovy answered that I have to mirror the field output exactly, or it won't work.

> Either the redux-field and/or redux-container classes with the proper IDs and such.

I haven't found the right solution yet. What exactly do you mean by mirroring the field output exactly? You mean in my callback function? But how if the table and such are created automatically?

Thanks and best regards

Redux: v3.6.0
Wordpress: v4.5
dev_mode: enabled

**Comment by jaschaio** [comment]
Btw. the Callback Field inside the Documentation has been "coming soon" for quite a while now (at least since I can remember start using the callback field back in early 2015). Can I help out with the documentation for the callback field? Do you need any other help in other parts of the documentation?

**Comment by kprovance** [comment]
Please provide a support url so dovy can see your config.

**Comment by jaschaio** [comment]
Not sure if this works from localhost as well
http://support.redux.io/?id=qPpcQNjg%2BM3tLZdccM3KKO6BAuPMwR44e8qREzKFUFKeCGcn%2BPA2vEF5jHBwKZJN%2BFxbJ39mMpIG8y%2FnoCPJzQ%3D%3D

**Comment by dovy** [comment]
So thing you need to add:

Make sure the classes for redux-container and redux-field properly exist and are attached to what they belong to.

Make sure you call redux_change(OBJ) if you're doing some custom JS.

Have you considered converting this into a extension rather than a callback field? It would be easier to have Redux fix everything you may be lacking.  ;)

**Comment by kprovance** [comment]
Checking in to see if this is resolved.  If so, please close the ticket.  Thanks.

**Comment by jaschaio** [comment]
Thanks for your reply @dovy. 

You were right, I had set the ID in single quotes and it was outputting the variable name instead of the variable value so it didn't assigned the right id:

`<fieldset id="option_name-$option" class="redux-field-container redux-field redux-container-switch">;`

Using double quotes for the echo that outputs the fieldset solved it.

Haven't thought about turning it into an extension yet. Mostly because last time I checked I didn't quite understand how it was done. But I still don't get what you mean, what would be the upside of turning it into an extension rather than using callback custom fields?

**Comment by dovy** [comment]
More power, easier to maintain, and can be used over and over. It just brings everything together.

Plus Redux would output those classes automatically for you.

Here's an example of how to easily get started:
https://github.com/reduxframework/extension-boilerplate

:)
