### ISSUE TITLE
Can't see Visual Composer in page editor anymore

### ISSUE THREAD

**Issue by potatofirelord** [reduxframework/redux-framework#2942]
Hi! 

Since the last Wordpress update, I can't see Visual Composer to arrange page anymore. I'm using the envato toolkit to update the theme. 

My theme is RONNEBY and I'm on version:1.1.0.

My wordpress is 4.5–fr_CA. 

This is what I see when editing a page (see attached picture). 

Thank you
![image](https://cloud.githubusercontent.com/assets/18582033/14688453/a0908130-0710-11e6-8ea3-cceee72b52e9.png)

**Comment by kprovance** [comment]
We are not the author of this theme.  You need to contact the theme author for support in these matters.  Thanks.
