### ISSUE TITLE
update-core.php redirect

### ISSUE THREAD

**Issue by somepaulo** [reduxframework/redux-framework#2943]
Hi.
After updating RF to 3.6.0 I am not able to get to the core update page. It always gets redirected to `/tools.php?page=redux-about` even if I deactivate RF.
Tried logging out and back in to WP too. Cleared the cache. No luck.
.htaccess is fine too.
Please advise.

**Comment by kprovance** [comment]
If you deactive Redux, that message should not come up.  What we need is admin access to your site, and access to your server to debug this problem.  It's come up and we cannot reproduce.  The only way to solve it is to debug on a server where it occurs, and so far, no seems interested in letting us do that.  If you're willing, please email that info to info@reduxframework.com.  it will be kept in the strictest of confidence.  Thanks.

**Comment by somepaulo** [comment]
That's alright with me. I'll send you an email in a minute. Just set up a new admin user for you.
Do you need FTP or cPanel server access (it's a shared hosting, so no root access)?

**Comment by kprovance** [comment]
FTP would be awesome.  Thanks!  :)

**Comment by somepaulo** [comment]
Just emailed you all the details.

**Comment by somepaulo** [comment]
It works in Chrome for me, and TOR, but not FF.
Must be a weird FF issue.
Sorry.

**Comment by kprovance** [comment]
Okay, well, it's still something we'll have to solve eventually.

If anyone else is experiencing this and want to help us out, email us.
