### ISSUE TITLE
Errors on Customizing Page

### ISSUE THREAD

**Issue by bluesuiter** [reduxframework/redux-framework#2944]
Notice: Undefined index: id in /var/www/clients/client22/web48/web/dev10/radar/wp-content/plugins/redux-framework/ReduxCore/inc/extensions/customizer/extension_customizer.php on line 470 Notice: Undefined index: id in /var/www/clients/client22/web48/web/dev10/radar/wp-content/plugins/redux-framework/ReduxCore/inc/extensions/customizer/extension_customizer.php on line 471 Notice: Undefined index: type in /var/www/clients/client22/web48/web/dev10/radar/wp-content/plugins/redux-framework/ReduxCore/inc/extensions/customizer/extension_customizer.php on line 485 Notice: Undefined index: id in /var/www/clients/client22/web48/web/dev10/radar/wp-content/plugins/redux-framework/ReduxCore/inc/extensions/customizer/extension_customizer.php on line 490 Notice: Undefined index: id in /var/www/clients/client22/web48/web/dev10/radar/wp-content/plugins/redux-framework/ReduxCore/inc/extensions/customizer/extension_customizer.php on line 505 Notice: Undefined index: type in /var/www/clients/client22/web48/web/dev10/radar/wp-content/plugins/redux-framework/ReduxCore/inc/extensions/customizer/extension_customizer.php on line 507 Notice: Undefined index: type in /var/www/clients/client22/web48/web/dev10/radar/wp-content/plugins/redux-framework/ReduxCore/inc/extensions/customizer/extension_customizer.php on line 507 Notice: Undefined index: type in /var/www/clients/client22/web48/web/dev10/radar/wp-content/plugins/redux-framework/ReduxCore/inc/extensions/customizer/extension_customizer.php on line 543 Notice: Undefined index: id in /var/www/clients/client22/web48/web/dev10/radar/wp-content/plugins/redux-framework/ReduxCore/inc/extensions/customizer/extension_customizer.php on line 470 Notice: Undefined index: id in /var/www/clients/client22/web48/web/dev10/radar/wp-content/plugins/redux-framework/ReduxCore/inc/extensions/customizer/extension_customizer.php on line 471 Notice: Undefined index: type in /var/www/clients/client22/web48/web/dev10/radar/wp-content/plugins/redux-framework/ReduxCore/inc/extensions/customizer/extension_customizer.php on line 485 Notice: Undefined index: id in /var/www/clients/client22/web48/web/dev10/radar/wp-content/plugins/redux-framework/ReduxCore/inc/extensions/customizer/extension_customizer.php on line 490 Notice: Undefined index: id in /var/www/clients/client22/web48/web/dev10/radar/wp-content/plugins/redux-framework/ReduxCore/inc/extensions/customizer/extension_customizer.php on line 505 Notice: Undefined index: type in /var/www/clients/client22/web48/web/dev10/radar/wp-content/plugins/redux-framework/ReduxCore/inc/extensions/customizer/extension_customizer.php on line 507 Notice: Undefined index: type in /var/www/clients/client22/web48/web/dev10/radar/wp-content/plugins/redux-framework/ReduxCore/inc/extensions/customizer/extension_customizer.php on line 507 Notice: Undefined index: type in /var/www/clients/client22/web48/web/dev10/radar/wp-content/plugins/redux-framework/ReduxCore/inc/extensions/customizer/extension_customizer.php on line 543 Notice: Undefined index: id in /var/www/clients/client22/web48/web/dev10/radar/wp-content/plugins/redux-framework/ReduxCore/inc/extensions/customizer/extension_customizer.php on line 470 Notice: Undefined index: id in /var/www/clients/client22/web48/web/dev10/radar/wp-content/plugins/redux-framework/ReduxCore/inc/extensions/customizer/extension_customizer.php on line 471 Notice: Undefined index: type in /var/www/clients/client22/web48/web/dev10/radar/wp-content/plugins/redux-framework/ReduxCore/inc/extensions/customizer/extension_customizer.php on line 485 Notice: Undefined index: id in /var/www/clients/client22/web48/web/dev10/radar/wp-content/plugins/redux-framework/ReduxCore/inc/extensions/customizer/extension_customizer.php on line 490 Notice: Undefined index: id in /var/www/clients/client22/web48/web/dev10/radar/wp-content/plugins/redux-framework/ReduxCore/inc/extensions/customizer/extension_customizer.php on line 505 Notice: Undefined index: type in /var/www/clients/client22/web48/web/dev10/radar/wp-content/plugins/redux-framework/ReduxCore/inc/extensions/customizer/extension_customizer.php on line 507 Notice: Undefined index: type in /var/www/clients/client22/web48/web/dev10/radar/wp-content/plugins/redux-framework/ReduxCore/inc/extensions/customizer/extension_customizer.php on line 507 Notice: Undefined index: type in /var/www/clients/client22/web48/web/dev10/radar/wp-content/plugins/redux-framework/ReduxCore/inc/extensions/customizer/extension_customizer.php on line 543 Notice: Undefined index: id in /var/www/clients/client22/web48/web/dev10/radar/wp-content/plugins/redux-framework/ReduxCore/inc/extensions/customizer/extension_customizer.php on line 470 Notice: Undefined index: id in /var/www/clients/client22/web48/web/dev10/radar/wp-content/plugins/redux-framework/ReduxCore/inc/extensions/customizer/extension_customizer.php on line 471 Notice: Undefined index: type in /var/www/clients/client22/web48/web/dev10/radar/wp-content/plugins/redux-framework/ReduxCore/inc/extensions/customizer/extension_customizer.php on line 485 Notice: Undefined index: id in /var/www/clients/client22/web48/web/dev10/radar/wp-content/plugins/redux-framework/ReduxCore/inc/extensions/customizer/extension_customizer.php on line 490 Notice: Undefined index: id in /var/www/clients/client22/web48/web/dev10/radar/wp-content/plugins/redux-framework/ReduxCore/inc/extensions/customizer/extension_customizer.php on line 505 Notice: Undefined index: type in /var/www/clients/client22/web48/web/dev10/radar/wp-content/plugins/redux-framework/ReduxCore/inc/extensions/customizer/extension_customizer.php on line 507 Notice: Undefined index: type in /var/www/clients/client22/web48/web/dev10/radar/wp-content/plugins/redux-framework/ReduxCore/inc/extensions/customizer/extension_customizer.php on line 507 Notice: Undefined index: type in /var/www/clients/client22/web48/web/dev10/radar/wp-content/plugins/redux-framework/ReduxCore/inc/extensions/customizer/extension_customizer.php on line 543 Notice: Undefined index: id in /var/www/clients/client22/web48/web/dev10/radar/wp-content/plugins/redux-framework/ReduxCore/inc/extensions/customizer/extension_customizer.php on line 470 Notice: Undefined index: id in /var/www/clients/client22/web48/web/dev10/radar/wp-content/plugins/redux-framework/ReduxCore/inc/extensions/customizer/extension_customizer.php on line 471 Notice: Undefined index: type in /var/www/clients/client22/web48/web/dev10/radar/wp-content/plugins/redux-framework/ReduxCore/inc/extensions/customizer/extension_customizer.php on line 485 Notice: Undefined index: id in /var/www/clients/client22/web48/web/dev10/radar/wp-content/plugins/redux-framework/ReduxCore/inc/extensions/customizer/extension_customizer.php on line 490 Notice: Undefined index: id in /var/www/clients/client22/web48/web/dev10/radar/wp-content/plugins/redux-framework/ReduxCore/inc/extensions/customizer/extension_customizer.php on line 505 Notice: Undefined index: type in /var/www/clients/client22/web48/web/dev10/radar/wp-content/plugins/redux-framework/ReduxCore/inc/extensions/customizer/extension_customizer.php on line 507 Notice: Undefined index: type in /var/www/clients/client22/web48/web/dev10/radar/wp-content/plugins/redux-framework/ReduxCore/inc/extensions/customizer/extension_customizer.php on line 507 Notice: Undefined index: type in /var/www/clients/client22/web48/web/dev10/radar/wp-content/plugins/redux-framework/ReduxCore/inc/extensions/customizer/extension_customizer.php on line 543 Notice: Undefined index: id in /var/www/clients/client22/web48/web/dev10/radar/wp-content/plugins/redux-framework/ReduxCore/inc/extensions/customizer/extension_customizer.php on line 470 Notice: Undefined index: id in /var/www/clients/client22/web48/web/dev10/radar/wp-content/plugins/redux-framework/ReduxCore/inc/extensions/customizer/extension_customizer.php on line 471 Notice: Undefined index: type in /var/www/clients/client22/web48/web/dev10/radar/wp-content/plugins/redux-framework/ReduxCore/inc/extensions/customizer/extension_customizer.php on line 485 Notice: Undefined index: id in /var/www/clients/client22/web48/web/dev10/radar/wp-content/plugins/redux-framework/ReduxCore/inc/extensions/customizer/extension_customizer.php on line 490 Notice: Undefined index: id in /var/www/clients/client22/web48/web/dev10/radar/wp-content/plugins/redux-framework/ReduxCore/inc/extensions/customizer/extension_customizer.php on line 505 Notice: Undefined index: type in /var/www/clients/client22/web48/web/dev10/radar/wp-content/plugins/redux-framework/ReduxCore/inc/extensions/customizer/extension_customizer.php on line 507 Notice: Undefined index: type in /var/www/clients/client22/web48/web/dev10/radar/wp-content/plugins/redux-framework/ReduxCore/inc/extensions/customizer/extension_customizer.php on line 507 Notice: Undefined index: type in /var/www/clients/client22/web48/web/dev10/radar/wp-content/plugins/redux-framework/ReduxCore/inc/extensions/customizer/extension_customizer.php on line 543 Notice: Undefined index: id in /var/www/clients/client22/web48/web/dev10/radar/wp-content/plugins/redux-framework/ReduxCore/inc/extensions/customizer/extension_customizer.php on line 470 Notice: Undefined index: id in /var/www/clients/client22/web48/web/dev10/radar/wp-content/plugins/redux-framework/ReduxCore/inc/extensions/customizer/extension_customizer.php on line 471 Notice: Undefined index: type in /var/www/clients/client22/web48/web/dev10/radar/wp-content/plugins/redux-framework/ReduxCore/inc/extensions/customizer/extension_customizer.php on line 485 Notice: Undefined index: id in /var/www/clients/client22/web48/web/dev10/radar/wp-content/plugins/redux-framework/ReduxCore/inc/extensions/customizer/extension_customizer.php on line 490 Notice: Undefined index: id in /var/www/clients/client22/web48/web/dev10/radar/wp-content/plugins/redux-framework/ReduxCore/inc/extensions/customizer/extension_customizer.php on line 505 Notice: Undefined index: type in /var/www/clients/client22/web48/web/dev10/radar/wp-content/plugins/redux-framework/ReduxCore/inc/extensions/customizer/extension_customizer.php on line 507 Notice: Undefined index: type in /var/www/clients/client22/web48/web/dev10/radar/wp-content/plugins/redux-framework/ReduxCore/inc/extensions/customizer/extension_customizer.php on line 507 Notice: Undefined index: type in /var/www/clients/client22/web48/web/dev10/radar/wp-content/plugins/redux-framework/ReduxCore/inc/extensions/customizer/extension_customizer.php on line 543 Notice: Undefined index: id in /var/www/clients/client22/web48/web/dev10/radar/wp-content/plugins/redux-framework/ReduxCore/inc/extensions/customizer/extension_customizer.php on line 470 Notice: Undefined index: id in /var/www/clients/client22/web48/web/dev10/radar/wp-content/plugins/redux-framework/ReduxCore/inc/extensions/customizer/extension_customizer.php on line 471 Notice: Undefined index: type in /var/www/clients/client22/web48/web/dev10/radar/wp-content/plugins/redux-framework/ReduxCore/inc/extensions/customizer/extension_customizer.php on line 485 Notice: Undefined index: id in /var/www/clients/client22/web48/web/dev10/radar/wp-content/plugins/redux-framework/ReduxCore/inc/extensions/customizer/extension_customizer.php on line 490 Notice: Undefined index: id in /var/www/clients/client22/web48/web/dev10/radar/wp-content/plugins/redux-framework/ReduxCore/inc/extensions/customizer/extension_customizer.php on line 505 Notice: Undefined index: type in /var/www/clients/client22/web48/web/dev10/radar/wp-content/plugins/redux-framework/ReduxCore/inc/extensions/customizer/extension_customizer.php on line 507 Notice: Undefined index: type in /var/www/clients/client22/web48/web/dev10/radar/wp-content/plugins/redux-framework/ReduxCore/inc/extensions/customizer/extension_customizer.php on line 507 Notice: Undefined index: type in /var/www/clients/client22/web48/web/dev10/radar/wp-content/plugins/redux-framework/ReduxCore/inc/extensions/customizer/extension_customizer.php on line 543 Notice: Undefined index: id in /var/www/clients/client22/web48/web/dev10/radar/wp-content/plugins/redux-framework/ReduxCore/inc/extensions/customizer/extension_customizer.php on line 470 Notice: Undefined index: id in /var/www/clients/client22/web48/web/dev10/radar/wp-content/plugins/redux-framework/ReduxCore/inc/extensions/customizer/extension_customizer.php on line 471 Notice: Undefined index: type in /var/www/clients/client22/web48/web/dev10/radar/wp-content/plugins/redux-framework/ReduxCore/inc/extensions/customizer/extension_customizer.php on line 485 Notice: Undefined index: id in /var/www/clients/client22/web48/web/dev10/radar/wp-content/plugins/redux-framework/ReduxCore/inc/extensions/customizer/extension_customizer.php on line 490 Notice: Undefined index: id in /var/www/clients/client22/web48/web/dev10/radar/wp-content/plugins/redux-framework/ReduxCore/inc/extensions/customizer/extension_customizer.php on line 505 Notice: Undefined index: type in /var/www/clients/client22/web48/web/dev10/radar/wp-content/plugins/redux-framework/ReduxCore/inc/extensions/customizer/extension_customizer.php on line 507 Notice: Undefined index: type in /var/www/clients/client22/web48/web/dev10/radar/wp-content/plugins/redux-framework/ReduxCore/inc/extensions/customizer/extension_customizer.php on line 507 Notice: Undefined index: type in /var/www/clients/client22/web48/web/dev10/radar/wp-content/plugins/redux-framework/ReduxCore/inc/extensions/customizer/extension_customizer.php on line 543 Notice: Undefined index: id in /var/www/clients/client22/web48/web/dev10/radar/wp-content/plugins/redux-framework/ReduxCore/inc/extensions/customizer/extension_customizer.php on line 470 Notice: Undefined index: id in /var/www/clients/client22/web48/web/dev10/radar/wp-content/plugins/redux-framework/ReduxCore/inc/extensions/customizer/extension_customizer.php on line 471 Notice: Undefined index: type in /var/www/clients/client22/web48/web/dev10/radar/wp-content/plugins/redux-framework/ReduxCore/inc/extensions/customizer/extension_customizer.php on line 485 Notice: Undefined index: id in /var/www/clients/client22/web48/web/dev10/radar/wp-content/plugins/redux-framework/ReduxCore/inc/extensions/customizer/extension_customizer.php on line 490 Notice: Undefined index: id in /var/www/clients/client22/web48/web/dev10/radar/wp-content/plugins/redux-framework/ReduxCore/inc/extensions/customizer/extension_customizer.php on line 505 Notice: Undefined index: type in /var/www/clients/client22/web48/web/dev10/radar/wp-content/plugins/redux-framework/ReduxCore/inc/extensions/customizer/extension_customizer.php on line 507 Notice: Undefined index: type in /var/www/clients/client22/web48/web/dev10/radar/wp-content/plugins/redux-framework/ReduxCore/inc/extensions/customizer/extension_customizer.php on line 507 Notice: Undefined index: type in /var/www/clients/client22/web48/web/dev10/radar/wp-content/plugins/redux-framework/ReduxCore/inc/extensions/customizer/extension_customizer.php on

**Comment by bluesuiter** [comment]
I keep debug true while developing I found some of these Warnings in files. Please fix these ones.

**Comment by dovy** [comment]
You have to set an ID for each field in Redux. What this means is you're not identifying each field with an identifier. Here's the code causing those errors:

```
foreach ( $section['fields'] as $skey => $option ) {

                        if ( isset( $option['customizer'] ) && $option['customizer'] === false ) {
                            continue;
                        }

                        if ( $this->parent->args['customizer'] === false && ( ! isset( $option['customizer'] ) || $option['customizer'] !== true ) ) {
                            continue;
                        }

                        $this->options[ $option['id'] ] = $option;
```

So please add some 'id' args to each field.  :)
