### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by ticketmvp** [reduxframework/redux-framework#2945]
I received an update for my theme, and when I updated, all of my home page edits were messed up. The VG sliders don't work, I cant see pictures. and there is no option for me to edit it on backend., and when I try to edit front end, my page wont load. I've tried I tried to deactivate and reactivate plugins, and to backup and restore the webpage, but that still doesn't work. please help.. My site needs to be running

**Comment by kprovance** [comment]
We are not the author of your theme.  You need to contact whomever that is for support matters.
