### ISSUE TITLE
Dev mode code crashes memory

### ISSUE THREAD

**Issue by iPublicis** [reduxframework/redux-framework#2946]
When WP-DEBUG is true in some heavy sites the following code provokes memory exhaustion.
Also Theme Panel turns unavailable.

`Allowed memory size of 268435456 bytes exhausted (tried to allocate 184819712 bytes)
Type: PHP Fatal error
Line: 106
File: /home/username/public_html/wp-content/themes/mango/inc/admin/ReduxCore/core/panel.php`

See code from line 102 to 111 in https://github.com/reduxframework/redux-framework/blob/master/ReduxCore/core/panel.php

Also error.log is not saved in the normal place so tools like WP Log Viewer catch the PHP memory exhaustion error but not other Redux important messages and that turned the finding of the error very hard to guess.

Commenting that piece of code and the problem vanishes. But that is not a solution hence you have to comment that code every time you upgrade Redux or a Redux-based theme.

Solution would be to set DEV MODE using an option on Redux panel.

**Comment by kprovance** [comment]
A print_r( $wpdb->queries ) is exhausting memory?  Are you sure it's not a server issue?  I have no such problems on any of my sites, not do thousands of other users.

**Comment by dovy** [comment]
We need more details. Please provide a support URL for us to test with. https://github.com/reduxframework/redux-framework/blob/master/CONTRIBUTING.md

**Comment by spartanpixel** [comment]
I had the same issue with 

> Allowed memory

I had to disable the Redux Framework and my site was up and running in no time.
I'm also running the latest version of Wordpress 4.5 and Redux Version 3.6.0.1

**Comment by kprovance** [comment]
This is unfortunate, gentlemen, but, once again:  We need more details. Please provide a support URL for us to test with. https://github.com/reduxframework/redux-framework/blob/master/CONTRIBUTING.md

Just telling us about an issue with no additional information ties our hands.

**Comment by spartanpixel** [comment]
This is my site https://spartanpixel.net/ I even downgraded to Worpress version 4.4.2 and still crashed my server :/

**Comment by kprovance** [comment]
I'm sorry, but this doesn;t help us help you.  Please re-read the link I sent you.

**Comment by kprovance** [comment]
Last call to provide us with the information we need, otherwise I'm going to close this ticket as unresolved.  Thanks.

**Comment by kprovance** [comment]
No reply.  Closing
