### ISSUE TITLE
Shortcode in editor

### ISSUE THREAD

**Issue by safiro** [reduxframework/redux-framework#2947]
Redux Framework v3.5.9.8
WP  Version 4.5

I'm trying to use Shortcodes in ace_editor.
I add this code in my php file:

`<?php echo do_shortcode($redux_demo['mytextfield']); ?>`
and in my panel I added the shortcode in editor:

`[myshortcode cols="7"]`

it works but the shortcode is always displayed before its content:

```
[myshortcode cols="7"]

1- La Liga Rules for Non-European Players
2- Soccer Fixture: Chelsea Versus Manchester United
3- Tips on Finding Best Football Sites
4- Learn Football Skills to Play Like Pele
5- Want to Become an AFL Player? Here Are a Few Things You Should Do
```

**Comment by kprovance** [comment]
I don't believe shortcodes can be done via the ace_editor? (Well, it sorta can, but it's unpredictable.  Not much we can do about that.)  You might have to go with the editor field, which uses wp_editor.  If do_shortcode is failing, it becomes a wordpress issue.  Check the output of that Redux variable and make sure there isn;t some kind of bad formatting in there causing that.

**Comment by dovy** [comment]
I think they mean php short code as php tag?

**Comment by safiro** [comment]
So Sorry for mistyping, I did that in editor not ace_editor.

```
array(
			'title'            => 'Block One',
			'id'               => 'mytextfield',
			'type' => 'editor',
			'args'    => array(
						'teeny'         => false,
					),
		),
```

**Comment by dovy** [comment]
Then what you need is to pass the value through here:
https://developer.wordpress.org/reference/functions/do_shortcode/

:)
