### ISSUE TITLE
Visual Composer

### ISSUE THREAD

**Issue by fotoon** [reduxframework/redux-framework#2948]
Hello, I have a template Ronneby and suddenly stopped working Visual Composer, that remained an icon but there is no option to change settings. Also, there's nothing I can add to the list of things to add.
(The following link from screenashot)
http://screenshooter.net/102561346/rsagrrg

**Comment by kprovance** [comment]
I'm not sure how you got here, but we here at Redux did not author your theme.  The author used our option panel framework.  That's it.  We do not support themes, at all.  Please, contact the theme author for any all all support matters.  Thanks!  :)

**Comment by fotoon** [comment]
OK, I understand, I have chosen to support the template and replied to me here, thanks, greetings.
