### ISSUE TITLE
Error While Deleting Widget Areas Using Redux Widget Areas Extension 

### ISSUE THREAD

**Issue by manikbajaj** [reduxframework/redux-framework#2949]
Due to WordPress upgrade in the following script we have to change 

From:
title= widget.find('.sidebar-name h3'),

To: 
title= widget.find('.sidebar-name h2'),

This is because of WordPress update and WordPress using h2 now instead of h3. We have for now changed this to h2 manually but we need to understand and be sure that there would be no impact elsewhere. 

=========
Your Script
=========
delete_widget_area: function(e) {
        var widget      = $(e.currentTarget).parents('.widgets-holder-wrap:eq(0)'),
            title       = widget.find('.sidebar-name h3'),
            spinner     = title.find('.spinner'),
            widget_name = $.trim(title.text()),
            obj         = this;
        widget.addClass('closed');
        spinner.css('display', 'inline-block');
        $.ajax({
          type: "POST",
          url: window.ajaxurl,
          data: {
             action: 'redux_delete_widget_area',
             name: widget_name,
             _wpnonce: obj.nonce
          },

Let me know. 

Best Regards 
Manik

**Comment by kprovance** [comment]
Please post all extension issues here:  https://github.com/reduxframework/redux-extensions/issues.  This tracker is for the Redux core.  Thanks.
