### ISSUE TITLE
Options not saving from Redux Option Panel

### ISSUE THREAD

**Issue by mrgurdeep** [reduxframework/redux-framework#2950]
Installed the newest update available on Wordpress.org

The Issue is the options are not saving and I am getting an error message - Invalid security credential. Please reload the page and try again

I think this is due to Wordpress 4.5  is there any fix as the server is upgraded to wordpress 4.5 automatically.  

No Option to downgrade. 

One other thing i have noticed it is picking up defaults only. Please suggest.

**Comment by kprovance** [comment]
This usually means the nonce has expired and the page needs to be refreshed.  Please mind the information require for support by reading this page:  https://github.com/reduxframework/redux-framework/blob/master/CONTRIBUTING.md

**Comment by kprovance** [comment]
Last call to provide us with the information asked for.  I will be closing this ticket soon without a reply.  Thanks.

**Comment by kprovance** [comment]
No reply.  Closing
