### ISSUE TITLE
Theme Options Have More Than A 1000 Variables 

### ISSUE THREAD

**Issue by manikbajaj** [reduxframework/redux-framework#2951]
We are facing an issue over here with the theme options. We have more than 1000 theme options and by default when PHP is installed on a server it has a maximum variable execution limit of 1000. For out theme to run the user would have to increase this limit and we don't want that. Is there something offered by Redux framework to take care of this issue?

Regards 
Manik

**Comment by kprovance** [comment]
The latest version of Redux, when ajax_save set to true, will handle this issue.
