### ISSUE TITLE
Indent issue in section field if info field used

### ISSUE THREAD

**Issue by danfisher85** [reduxframework/redux-framework#2952]
Hi,

If you issue info field inside section and indent is true this info field will break indent. Take a look

![screen shot 2016-04-25 at 14 38 34](https://cloud.githubusercontent.com/assets/7786257/14784054/e9c71170-0af3-11e6-8814-d0c4f028803a.png)

Kind Regards!

**Comment by kprovance** [comment]
Please provide us with the information from this article:   https://github.com/reduxframework/redux-framework/blob/master/CONTRIBUTING.md

**Comment by kprovance** [comment]
No reply.  Closing
