### ISSUE TITLE
Sorter and Slides don't load into WP Customizer

### ISSUE THREAD

**Issue by gordo019** [reduxframework/redux-framework#2955]
All of my theme options load into the WP Customizer correctly except sorter and slides do not appear in Customizer. They appear correctly in the Redux Theme Options panel. I have seen slides work in the Redux demo example with the WP Customizer.
Install: Redux 3.6.0.1, WordPress v_4.5.

**Comment by kprovance** [comment]
Hi.  Please post all customized related issues here:  https://github.com/reduxframework/customizer-integration

Thanks!

**Comment by kprovance** [comment]
Also, when posting there, please include the required Support URL, as discussed here:  https://github.com/reduxframework/redux-framework/blob/master/CONTRIBUTING.md
