### ISSUE TITLE
Refund (Wordpress layout does not work)

### ISSUE THREAD

**Issue by JessicaSilber** [reduxframework/redux-framework#2957]
To Whom it May Concern-

My name is Jessica Silber and I recently purchased a wordpress layout to build my production company website. Unfortunately, I am very unhappy with my purchase as this layout is almost impossible to navigate. Please get back to me asap so I can refund this purchase and find a more fitting layout for my use. Thank you!

Please feel free to email me at heyitsmeproductions@gmail.com

**Comment by kprovance** [comment]
We didn't sell you anything.  Whatever you are using, we didn't author.  The author might be using our framework to generate an option panel, but that's it.  You need to contact the actual author for support and/or refunds.

**Comment by JessicaSilber** [comment]
Sorry Kevin! I am trying to get in touch with wordpress regarding my
website but it brought me to your site when I pressed support. My
apologies.

*Best,*
*Jessica Silber*
*Writer/Producer*
*Hey It's Me Productions*
*c 201-575-9400 <201-575-9400>*
*https://www.linkedin.com/in/jessica-silber-4582b243
<https://www.linkedin.com/in/jessica-silber-4582b243>*
