### ISSUE TITLE
Visual Composer not working

### ISSUE THREAD

**Issue by ptuku** [reduxframework/redux-framework#2959]
Hello,

after last theme update, the visual composer stopped working.
Actually I can't see anything on the visual composer slot inside pages, and when I try to edit a single page, the visual composer seems to load something (displays the circular wheel rounding) but nothing happens.
I bought a theme with the visual composer packed inside from CodeCanyon, so it shouldn't be anything related to the license I suppose (and I really hope).

I also tried to go to the settings panel of visual composer and check all the options on each single tab (administrator, editor ecc..) but nothing happened yet.

Could you please help me?

thank you in advance
Paolo

**Comment by kprovance** [comment]
https://github.com/reduxframework/redux-framework/issues/2953
