### ISSUE TITLE
Missing Folder / File 

### ISSUE THREAD

**Issue by mattie02** [reduxframework/redux-framework#296]
I got this after including this in my theme, Any Suggestions

Warning: require_once(/home/round/public_html/wp-content/themes/iputtyFrame-master/core/ReduxFramework/ReduxCore/inc/fields/callback/field_callback.php): failed to open stream: No such file or directory in /home/round/public_html/wp-content/themes/iputtyFrame-master/core/ReduxFramework/ReduxCore/framework.php on line 944 Fatal error: require_once(): Failed opening required '/home/round/public_html/wp-content/themes/iputtyFrame-master/core/ReduxFramework/ReduxCore/inc/fields/callback/field_callback.php' (include_path='.:/usr/share/php:/usr/share/pear') in /home/round/public_html/wp-content/themes/iputtyFrame-master/core/ReduxFramework/ReduxCore/framework.php on line 944

**Comment by riteshpanchal1** [comment]
i also have same problem. i have upload file 2-3 times but after some time its missing.
