### ISSUE TITLE
WordPress multi-site. save options for each site doesn't work

### ISSUE THREAD

**Issue by danielwebguy** [reduxframework/redux-framework#2960]
Hi,
We discussed it on Slack but I can make it work.
What I need, and understood exists now:
To have the options only influence a specific site. So, each site has its own redux options values.

My settings are like so:
....
```
        'database' => 'network',
        'transient_time' => '3600',
        'network_admin' => TRUE,
        'network_sites' => TRUE,
```
....
and when I save options, it influences all the sites on the network. and I don't want it to influence all sites on the network, we want it to influence just one.
Thanks,
Daniel

**Comment by dovy** [comment]
Try setting network_admin to false.

**Comment by kprovance** [comment]
Was this resolved?  If so, please close the ticket.

**Comment by kprovance** [comment]
Closing.

**Comment by dodacvan** [comment]
any solution to fix that

**Comment by kprovance** [comment]
No.  Code has not yet been added to accomplish this.  No ETA if or when it will be.  Sorry.
