### ISSUE TITLE
Typography Preview

### ISSUE THREAD

**Issue by Bluxart** [reduxframework/redux-framework#2961]
Hi, it is possible disable the preview for typography field? I set preview => false, but if I click on input available into array ( font-size, line-height or letter-spacing ) the preview appear.

Redux Framework: 3.6.0.2
Wordpress: 4.5.1

```php
array(
    'id'             => 'az_hero_header_sm_title_text',
    'type'           => 'typography', 
    'title'          => __( 'Heading - Small', 'az-valkyrie' ),
    'subtitle'       => __( 'Define the font-size for hero header title for small text size.', 'az-valkyrie' ),
    'desc'           => __( 'Enter only number value. Value in rem.<br>
                             10px = 1rem', 'az-valkyrie' ),
    'google'         => false, 
    'font-backup'    => false,
    'font-style'     => false,
    'font-family'    => false,
    'font-weight'    => false,
    'subsets'        => false,
    'word-spacing'   => false,
    'text-align'     => false,
    'color'          => false,
    'preview'        => false,
    'font-size'      => true,
    'letter-spacing' => true,
    'line-height'    => true,
    'units'          => 'rem',
    'default'  => array( 
        'font-size'      => '7', 
        'line-height'    => '9',
        'letter-spacing' => '-0.02',
    ),
    'preview'  => array(
        'always_display' => false
    ),
),
```

**Comment by kprovance** [comment]
At his time, it is not.  The argument you set disabled the preview upon page load.  ANy change to the fields will display it.

**Comment by dovy** [comment]
If you want to submit a pull-release we're fine with that. It wouldn't be too hard to do, we've just never implemented it.

**Comment by kprovance** [comment]
Well, hold on. Let's be up front about this, because it *is* the typography field and not for the novice.  it would require a new argument from 'preview' as not to break backward compatibility, and a more than passing knowledge of javascript and jQuery is needed to implement it.

Or, a generous donation to our cause might motivate me to do it.  :)

**Comment by Bluxart** [comment]
It's ok for a donation for your work, It would also be nice the section type can be included/excluded by required parameter.

**Comment by kprovance** [comment]
Well, for required to do that, it's going to take a serious rewrite.  That's thousands of dollars worth of hours of work, to be honest.

**Comment by dovy** [comment]
For section...  not typography.

**Comment by Bluxart** [comment]
The required argument for section, the disable preview for typography. Let me know guys.
