### ISSUE TITLE
Tutorial Videos Inside Redux Options Panel

### ISSUE THREAD

**Issue by StefsterNYC** [reduxframework/redux-framework#2962]
Anyone ever add videos to Redux Panel? We're thinking of adding videos from Vimeo on certain aspects of teaching the customer how to deal with certain things like Visual Composer and other things with our themes. It would be nice if we could add video components inside the option panel for them to view.

Anyone ever do this? I've seen others do it with other like Panels.

**Comment by dovy** [comment]
You could do it very easily with the raw field. Just put in the html you want and there you go. :)

**Comment by dovy** [comment]
You can even reference a flat html file to do this too.

**Comment by StefsterNYC** [comment]
Hey Dovy, I actually ended up figuring it out. Worked beautifully. Sorry for the delay in replying back. I'm never around. 

Now I'm trying to figure a way to do a sorted list.
