### ISSUE TITLE
Build out of sync again 

### ISSUE THREAD

**Issue by TuxReports** [reduxframework/redux-framework#2963]
Hi,

Just a little nudge that the build website is still using the 3.5 version and not the 3.6. 

Keep up the great work. Good to see Avada and Enfold themes now uses Redux Framework.

**Comment by kprovance** [comment]
I can update it manually next week (not in town).  I can't get our builder to work locally, and thus cannot figure out why the builder won't update.  Gotta get @dovy to see why.  :)

**Comment by kprovance** [comment]
Updated manually, again.  Hopefully I can get Dovy to fix it, or tell me how to fix it soon.  ;-)
