### ISSUE TITLE
Dependency parameter

### ISSUE THREAD

**Issue by kiarashi** [reduxframework/redux-framework#2965]
Not so much an issue but more a enhancement.

Is it possible to have a dependency parameter? 

For example, I created an extra checkbox field with the text "enable a border".
If "yes" is selected, an extra border field will become visible. If "no" is selected, the border field stays hidden.

Edit: Is a opacity parameter inside the Background field also possible? Same as seen with the Color RGBA field.

**Comment by peterkaer** [comment]
Hi
I think you are looking for https://docs.reduxframework.com/core/the-basics/required/ :-)

**Comment by kprovance** [comment]
Yup.  The required argument is what you want. See the docs site via the link above.  :)

**Comment by kiarashi** [comment]
Can't believe I missed that one. Thank you. :)
