### ISSUE TITLE
Slider

### ISSUE THREAD

**Issue by trisghosh** [reduxframework/redux-framework#2967]
Hi,

Found that the Field Slider is not working on Wordpress 4.5.

Please come out with the solutions.

Thanks and Regards

**Comment by dovy** [comment]
Please give more details and provide a support URL.  ;)

**Comment by kprovance** [comment]
If you look at our demo site  demo.redux.io, you'll see the Slider is functioning as expected.  As Dovy said, we need a support URL.  Please review:  https://github.com/reduxframework/redux-framework/blob/master/CONTRIBUTING.md

**Comment by trisghosh** [comment]
Hi Kevin,

I figure out the issue and solve it.



On Fri, May 6, 2016 at 12:17 AM, Kevin Provance <notifications@github.com>
wrote:

> If you look at our demo site demo.redux.io, you'll see the Slider is
> functioning as expected. As Dovy said, we need a support URL. Please
> review:
> https://github.com/reduxframework/redux-framework/blob/master/CONTRIBUTING.md
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/reduxframework/redux-framework/issues/2967#issuecomment-217240498>
>



-- 
Thanks and Regards
Tristup Ghosh

**Comment by kprovance** [comment]
Okay.  Closing.  (although if you'd like to share what you did, or whatever it was, it might be helpful to others.)  :)
