### ISSUE TITLE
Error Message Resolution: Fatal error: Call to undefined method Redux_Helpers::isTheme() in /home/kvmkvm73/public_html/wp-content/themes/porto/inc/admin/porto/settings.php on line 23

### ISSUE THREAD

**Issue by marketingpromogurs** [reduxframework/redux-framework#2969]
I recently uploaded a new wordpress theme and got this error message when I tried to preview the theme: 

Fat**al error: Call to undefined method Redux_Helpers::isTheme() in /home/kvmkvm73/public_html/wp-content/themes/porto/inc/admin/porto/settings.php on line 23**

How do I resolve this error message so I can use my new wordpress theme?

**Comment by dovy** [comment]
Run Redux as a plugin if your not the theme developer. Seems that Redux hasn't been loaded yet so it gets that error.  ;)

If you are the developer, you haven't loaded Redux yet properly. Look for hook order and make sure it's not being called before it's included.

**Comment by marketingpromogurs** [comment]
Dovy....I don't believe that plugin is loaded.  I will look and see if and if not add it now. Will let you know if this works.

**Comment by marketingpromogurs** [comment]
The plugin worked thanks dovy!!!!

**Comment by dovy** [comment]
Np.  ;)

Tell your developer to fix their code.  :P
