### ISSUE TITLE
Uploading theme

### ISSUE THREAD

**Issue by Wordpressjunior** [reduxframework/redux-framework#2970]
Hi
I am new to uploading themes but have followed details and having problems.

I have uploaded the GATHER theme (Wordpress zip. file only) The theme appears but is missing some of the features I bought the theme for. I have tried deleting and reinstalling the theme file and also tried to import demo data which says it failed to import  lots of files (see image)

![image](https://cloud.githubusercontent.com/assets/19177475/15001135/f2116732-118c-11e6-9b2d-74382e60837b.png)

Really appreciate help in getting this site live

**Comment by kprovance** [comment]
We are not the author of this theme, or ANY theme.  They are merely using our framework for the option panel and neglected to update the support links with their own.  You will need to contact the actual theme author for support.
