### ISSUE TITLE
Redux slows down admin panel performance

### ISSUE THREAD

**Issue by msleonar** [reduxframework/redux-framework#2971]
Hi, 

I noticed that when I install a theme using redux on sites with a lot of content the backend becomes extremely slow.  

Any idea what could be causing this issue. 

When redux is not activated the site is normal speed in both the front and backend.

Thanks!

**Comment by kprovance** [comment]
Please review our support guidelines and submit a support URL.  Thanks.

**Comment by kprovance** [comment]
Last call to provide the information we need, or I will have to close this ticket as unresolved.  Thanks!

**Comment by kprovance** [comment]
Closing from lack of reply.
