### ISSUE TITLE
How to extend a list of the select field

### ISSUE THREAD

**Issue by dkanicki** [reduxframework/redux-framework#2972]
I try to create a select field with a list of all pages, which I want to extend with an additional option like "same page". I need this field in an admin area to specify redirection after the login.
Using 'data' => 'pages' gives me all pages, but how to add my own option "same page" to this list?
The list of pages I am getting is just a flat list. Is there any possibility to get a hierarchical kind of list (children intended with blanks etc.)?

**Comment by kprovance** [comment]
Using the data argument?  I don't think so?  (Dovy would know better than I, I think).  What you'll end up having to do, for something like this, it to code up a function to list said pages, add whatever pages you would like to that array, and feed it into the select fields options argument.
