### ISSUE TITLE
Global variable issue

### ISSUE THREAD

**Issue by yderindere** [reduxframework/redux-framework#2973]
Hi,

I used Redux framework on my theme and I got reject “All global variables should be within a function or class.” 
I moved the global $themename_var; to functions.php but variable returns null. Btw Redux not embeded, it works as a plugin.

```
function themename_global_variable(){
	global $themename_var;
}
```
Also I tried #2306  but it doesn’t work. Any suggestions?

Thanks in advance

**Comment by kprovance** [comment]
That's not how PHP works, I'm sorry to say.

Something like

```
function themename_global_variable($option_id){
    global $themename_var;

    return $themename_var[$option_id];
}

It's very basic and does not account for error checking.  We are not really PHP tutors, so if you want something more comprehensive, you'll need to purchase some premium support from us.
