### ISSUE TITLE
Redux buldier

### ISSUE THREAD

**Issue by szakee** [reduxframework/redux-framework#2974]
Hi!

As I see something wrong with the buldier. Doesn't generate proper zip file. (the zip only 1 Kbyte) Can u check it guys? Sorry, I know this is not a framework issue.

**Comment by yojance** [comment]
@szakee,

I'm experiencing the same thing you are. Also, the SSL certificate seems to have expired and is throwing warning messages.

**Comment by kprovance** [comment]
We know.  No ETA when everything will be running again

**Comment by kprovance** [comment]
Fixed.  :)
