### ISSUE TITLE
Border field

### ISSUE THREAD

**Issue by kiarashi** [reduxframework/redux-framework#2975]
This is the code I'm using:

```
array( 
					'id'       	=> 'styling-pp-row-one-border',
					'type'     	=> 'border',
					'title'   	 => __('Border', 'redux-framework-demo'),					
					'all'     	=> 'false',
					'output'  	 => array('.dm-edd-product-page.row-one'),					
					'default'  	=> array(
						'border-color'  => '#E5E5E5', 
						'border-style'  => 'dashed', 
						'border-top'    => '1px', 
						'border-right'  => '0px', 
						'border-bottom' => '1px', 
						'border-left'   => '0px'
					), 
				),
```
This is how it looks inside the redux panel:
![img-border](https://cloud.githubusercontent.com/assets/7079137/15092045/e2f04844-145d-11e6-8d83-b5ed129d22d1.png)

The problem that I'm having is that the left and right border aren't 0. I'm not completely sure, but maybe it's because of the "all" argument? I even disabled it, but it's still there.

I'm using the latest redux wp version (3.6.0.2)

**Comment by kprovance** [comment]
Please review and provide a support URL:  https://github.com/reduxframework/redux-framework/blob/master/CONTRIBUTING.md

**Comment by kiarashi** [comment]
Oddly, not possible at this moment. 
I'm on localhost and when I try to click on Generate a Support URL, I get the following message: 

> There was an error. Please try again later. 

Btw, dev_mode is on. 
After receiving the error, I clicked on the Status tab, but then  I got this error:

> 4.5.2
> Fatal error: Call to a member function get_error_message() on array in C:\xampp\...\wp-content\plugins\redux-framework\ReduxCore\inc\class.redux_helpers.php on line 489

After refreshing the page, it's gone though.

**Comment by kprovance** [comment]
You're setting the 'all' argument to a string value of false.  You MUST use the boolean value.
```
'all' => false,
```
