### ISSUE TITLE
Hub Category is not WPML friendly

### ISSUE THREAD

**Issue by wlteng** [reduxframework/redux-framework#2976]
https://www.dropbox.com/s/ko5dzjz7d12jtv5/category.png?dl=0
Hello, Hub Category is not WPML friendly since i have found out half year ago, whenever i save those categories in other language, the primary language category will be not showing. Hope this could be fix soon. Thanks :)

**Comment by kprovance** [comment]
This looks like an actual theme issue.  We did not author the theme.  Please contact the theme author for support.
