### ISSUE TITLE
Not working on multisite

### ISSUE THREAD

**Issue by hitesh123456** [reduxframework/redux-framework#2978]
Hey i trying to use a plugin woothumbs (build on redux framework) on a multisite network, i have network activated redux framework and woothumbs but woothubs is showing me a message in the frontend "You need to install and enable the Redux Framework plugin before your images are shown."
Any help for that?

**Comment by kprovance** [comment]
You need to contact the author of the plugin for support.  We did not write the actual plugin that uses Redux.
