### ISSUE TITLE
Paypal subscriptioin

### ISSUE THREAD

**Issue by jmc1978** [reduxframework/redux-framework#2979]
Not sure this is best place to post this, however..

Any chance I can get a refund on the subscription I have paid last month for the custom fonts plugin that is not supported or available. Seems a little unfair to have taken a payment when the product is not available and has not been for some time. 

Many thanks in advance.

J

**Comment by kprovance** [comment]
We generally don't do refunds.  However, the extension, while not available publicly, is available for those who have registered.  You'll have to send an email to info@reduxframework.com with your purchase number, and I'll send it to you.
