### ISSUE TITLE
Issues with WP customize display menu generated from redux framework

### ISSUE THREAD

**Issue by HirenKa** [reduxframework/redux-framework#2980]
Hello,

I installed Redux framework plugin in wordpress 2016 theme and  activated developer mode .
After installation; in dashboard ( sample options) i could see the options for "Design Fields" and "Typography" however when checked in WP customize Option panel, I could not see the same options. Images attached with this post explain the problem faced at my end.

Redux Framework version used : 3.6.0.2   
Word Press Version : 4.5.2

I am not sure if this is a bug in the frame work or a mistake done at my end. Appreciate a response on this issue.

![customize-options](https://cloud.githubusercontent.com/assets/17078552/15149975/373a7284-16e9-11e6-9c9c-2bc3aff52899.jpg)
![redux-sample-options](https://cloud.githubusercontent.com/assets/17078552/15149976/373d7cae-16e9-11e6-8281-fdfbe9ebbd01.jpg)

**Comment by kprovance** [comment]
Those fields are not available in the core version of Redux.  Eventually we'll have a premium extension to handle those fields.
