### ISSUE TITLE
Parse CSS media query

### ISSUE THREAD

**Issue by edpittol** [reduxframework/redux-framework#2982]
I'm using the output argument and I didn't find a manner to add a media query to the argument. Is this in some milestone? 

I can help in the development of this feature. What I need to do it is define how must be the syntax to define media queries and the backward compatibility with the actual output argument.

**Comment by kprovance** [comment]
We have a compiler function that does the same thing, which allows you to control the return value.  The problem with tamptering with the actual output function is that each output is handled at the field level, and each field is specific to what it outputs, and why we have the compiler function.  https://docs.reduxframework.com/core/advanced/integrating-a-compiler/  There is also an exampleon using it in the sample-conofig.php, in the sample folder of the Redux package.
