### ISSUE TITLE
Deactivated redux plugin

### ISSUE THREAD

**Issue by ccahill1** [reduxframework/redux-framework#2983]
I recently found a deactivated redux plugin on a wordpress install I'm working on. I'm the only one doing development work on the site but I didn't install this plugin - at least not knowingly. I am using a SiteOrigin theme and some other plugins, and it's possible this plugin was installed as part of some collection of plugins. It is deactivated, so, is this plugin actually doing anything, or can I delete it?

**Comment by kprovance** [comment]
If Redux is deactivated and the theme and all plugins are functioning properly, you should be fine.  You'd have noticed by now if the theme needed Redux for it's option panel.
