### ISSUE TITLE
RTL Problem

### ISSUE THREAD

**Issue by MSalehi** [reduxframework/redux-framework#2985]
Hi Redux masters!

i'm using redux v3.6.0.2 and wordpress v4.5.2
There is a problem with redux
as you can see in the picture the icons and text of items overlapped!!

have anybody a solution for it ?

Thanks All.
![capture](https://cloud.githubusercontent.com/assets/5165298/15206615/def1e1fe-1835-11e6-8858-32940d81a6d4.PNG)

**Comment by MSalehi** [comment]
well,
i just do some search and i realized that should open ReduxFramework/ReduxCore/assets/css/redux-admin.css where this codes written :
.admin-color-midnight .redux-sidebar .redux-group-menu li.hasSubSections a .extraIconSubsections
there, the Float that was set to right, should change to left.

This method fixed my problem.

**Comment by dovy** [comment]
@MSalehi please download from this repo and test the newly compiled CSS to address the issue please.
