### ISSUE TITLE
multidimensional array from input field option pages

### ISSUE THREAD

**Issue by controvi** [reduxframework/redux-framework#2986]
Hello,

I just started using this framework for a project and all is going well.
Thanks for the great framework.

The only thing I am missing (or i just couldn't find it) is to get forms fields into a multidimensional array.

it would be nice if I could create a field like this:

`array(
                'id'            => 'social_sample',
                'array'      => 'sample_array'
                'type'          => 'text',
                'title'         => __( 'Sample URL', 'sample' ),
                'subtitle'      => __( 'please enter the company sample address', 'sample' ),
                'desc'          => __( '' ),
                'text_hint'     => array(
                    'title'         => 'Url info',
                    'content'       => 'https://www.sample.com/[pagename]'
                ),
                'placeholder'   => 'https://www.sample.com/[page name]'
            ),`

with the output being an array:
`<input type="text" name="sample[sample_array][social_sample]" />`

hope  you can help me out or point me in the right direction.

Cheers,

**Comment by kprovance** [comment]
Redux will not do this, no.  We have a repeater field that might be what you're looking for:  https://reduxframework.com/extension/repeater/.  Make sure you visit the docs page from that link as well, to be certain.
