### ISSUE TITLE
Problems after upgrade Theme and VC

### ISSUE THREAD

**Issue by onedesigner** [reduxframework/redux-framework#2987]
Im using Ronneby theme 

My purchase code is :
404c8229-a31e-403d-b006-ca34908ed8e0

My website is under objectstudio.us

With the but of doing an upgrade of the theme without problems I did this steps:

1. Backup site and BD
2. I cloned the site and I did my theme upgrade ( I temporally put this under sanrafaeldoors.us - I didn’t want to misconfigurate my actual site  )
3. In my new Ronneby theme upgraded website, Visual Composer wasn’t working , so i bought a licence and changed the plugin manually  -  sanrafaeldoors.us
4. In my new site  The VC editor works but the front-end doesn’t.(see image)
5. I contacted VC support showing them the problem. and they answer:

The issue is because there is a Visual Composer related code present in your theme added by the theme author. You will have to get rid of it. I would advise you to do so with the help of theme author, otherwise you might loose the extra elements added by him. Once this is done, you can install the standalone plugin and it will work fine. Kindly check.
Thank you,

Can you please help me to config the the theme and solve this problem?

To access to WP admin:

sanrafaeldoors.us/wp-admin
user: support
password: ----

![screen shot 2016-05-10 at 4 16 54 pm](https://cloud.githubusercontent.com/assets/14911460/15217776/13a3e574-182b-11e6-96d3-b8863227913c.png)

**Comment by dovy** [comment]
Hello there. We are actually not the developers of that theme. You'll want to contact them.

Best of luck!
