### ISSUE TITLE
is it possible to add Redux fields inside custom taxonmy ?

### ISSUE THREAD

**Issue by jeni1616** [reduxframework/redux-framework#2988]
Hello ,

i need google maps field (extension is available for redux )  inside custom taxonomy like this http://sabramedia.com/blog/how-to-add-custom-fields-to-custom-taxonomies  , not inside page/post or theme option , can that extension do that  or can it be done for other redux fields too ?

i don't think  'post-type' argument for field is useful for custom taxonomy and not found any other option anywhere .

Thanks .

**Comment by dovy** [comment]
Redux does metaboxes on post_types, but not taxonomy pages (yet). It's just a matter of effort and the demand has not been high enough to work on it.

That being said, it wouldn't be insanely difficult to do...

**Comment by jeni1616** [comment]
okay , Thanks for reply and redux off-course :)
