### ISSUE TITLE
How to enable arabic language ?

### ISSUE THREAD

**Issue by safiro** [reduxframework/redux-framework#2989]
Redux Version: Redux Framework v3.6.0.3
Wordpress: 4.5.2

I installed wordpress arabic version but redux buttons and saving notices are still in english.
The previous versions of redux the language was switched automatically.
How can I resolve this issue.

**Comment by kprovance** [comment]
I ran a quick test on my site, and could not recreate the issue.  We're going to need much more info.  Please review: https://github.com/reduxframework/redux-framework/blob/master/CONTRIBUTING.md noting specifically the support URL we need.

**Comment by kprovance** [comment]
Last call for the information we need, or I'll have to close the ticket unresolved.

**Comment by kprovance** [comment]
Closing.
