### ISSUE TITLE
Issue with 'default value' from spinner field?

### ISSUE THREAD

**Issue by maheshwaghmare** [reduxframework/redux-framework#2990]
Hi,

Is default option required for field `spinner`??.

I `don't` want to set `default width` for the `logo`.  When I leave `default` as a `empty` then it gets the value `0` initially. 

**Screenshot:**
<img src="http://i.imgur.com/aym1MJW.png">

-----

Also, When I set the `max` then it set this as a `default` width.

Code snippet is below:
```
array(
	'id'            => 'logo-width',
	'title'         => __( 'Logo Width', 'next' ),
	'type'          => 'spinner',
	'subtitle'      => __( 'Width of custom logo.', 'next' ),
	'default'       => '',
	'min'           => '',
	'step'          => 1,
	'max'           => 500,
),
```

**Screenshot:**
<img src="http://i.imgur.com/rzkpqsm.png">

When, I leave `max` empty then I'm not able to add the value from `keypad`.

-----

In `doc` there is no `required / optional` fields info.
- `https://docs.reduxframework.com/core/fields/spinner/`

-----

If developer need to manage all these then its fine. :)

**Comment by kprovance** [comment]
Yes, a default is required.  If not, the field defaults to zero to prevent errors.

**Comment by kprovance** [comment]
The dimension field might be a better way to go, also.
