### ISSUE TITLE
Problem with Redux

### ISSUE THREAD

**Issue by aacers** [reduxframework/redux-framework#2991]
Hello,

I have a problem with Redux it seems. When ckecking out a product the short description and description layout dissapears and becomes plain text. Besides that the stock management does strange things. For example stock is 15 and after selling 1 product the stock level changes (after a couple of minutes) to -6 or something. The product can not be sold anymore. 

When disabeling the redux plugin this problem does not occur.

Appriciate any help I can get,

Thanks,
Tim

**Comment by dovy** [comment]
Umm, Redux is a framework people use. It sounds like your theme or plugin author has some bugs in their code. It's best to contact them.  :)
