### ISSUE TITLE
Conditional Validation 

### ISSUE THREAD

**Issue by viraj-nimble** [reduxframework/redux-framework#2994]
Hi,
First of all i want to say Thank You for this wonderful library. i am a developer working on a custom plugin. I am facing a problem though, it's not library issue.

Problem is i have created a radio button with 3 option to upload file.
1) Default (When selected uploading files to site)
2) Google Drive( When selected uploading files to Google drive) 
3) DropBox (When selected uploading files to Dropbox)

My code is as bellow.

     array(         
              'id' => 'store-option',
               'type' => 'radio',
               'title' => __('Upload File', 'save-data'),
                'options' => array(
                'site' => 'Default',
                'google' => 'Google Drive',
                'dropbox' => 'Drop Box'
           ),
            'default' => 'site'
             ),

      array(
            'id' => 'google_clientid',
            'type' => 'text',
            'title' => __('Client ID', 'save-data'),
            'required' => array(
                array('store-option', 'equals', 'google'),
            ),
            'validate' => 'not_empty',
            'desc' => __('Provide Google ClientID', 'save-data'),
        ),

     array(
            'id' => 'dropbox_appkey',
            'type' => 'text',
            'title' => __('App Key', 'save-data'),
            'required' => array(
                array('store-option', 'equals', 'dropbox'),
            ), 
            'validate' => 'not_empty',
             'desc' => __('Provide dropbox appkey', 'save-data'),
    ),

In which i want to put validation like when i select Google drive option only that time Google option should be visible and validate for empty, and when i select Dropbox at that time only Dropbox App key Field should be visible and validate for empty. and when i select Default option  no option should be visible and validate. But currently when i am selecting default option from radio button  no option is visible that's working perfect, but It's validating both hidden fields for google and dropbox.
Since, i have not found this in document  so, asking it here.
Looking forward to your response.

Thanks,
Viraj Sonagara

**Comment by kprovance** [comment]
This is by design, unfortunately.  Any field marked 'not_empty', hidden or not,, will prevent save, because it's empty.  Redux does not offer conditional validation.  If fields are to potentially be left empty, then they cannot use the not_empty validation.

**Comment by viraj-nimble** [comment]
Thank You so much for your quick replay.

**Comment by dovy** [comment]
You could easily implement your own validator class and do the conditional logic. ;)

**Comment by viraj-nimble** [comment]
Thank You Mr. Dovy, As i am new to Wordpress plugin development, i will try my best. Thank You once again.

**Comment by viraj-nimble** [comment]
Sir if possible can you please suggest me any link which can be helpful for me.
