### ISSUE TITLE
Add bbPress forum icon to a Redux based wp theme

### ISSUE THREAD

**Issue by Luke1987** [reduxframework/redux-framework#2995]
Hi!
I need to add forum icon to my bbPress forum. I added this code to theme functions file, but icons doesn't show.

`add_post_type_support('forum', array('thumbnail'));

function ks_forum_icons() {
	if ( 'forum' == get_post_type() ) {
		global $post;
	    if ( has_post_thumbnail($post->ID) )
	    	echo get_the_post_thumbnail($post->ID,'thumbnail',array('class' => 'alignleft forum-icon'));
	 }
}
add_action('bbp_theme_before_forum_title','ks_forum_icons');`

This is the article i followed: [http://kristarella.com/2013/04/bbpress-forum-icons/](url)

Any suggestions?

**Comment by kprovance** [comment]
You'll have to contact the author of the theme, as we are not they.  Redux is a framework the author used to create their options panel.  We had nothing to do with the theme itself.  Sorry.
