### ISSUE TITLE
Does Redux Framework Only Work With the Customizer Now?

### ISSUE THREAD

**Issue by moshemo** [reduxframework/redux-framework#2997]
I am trying to check out the demo and I get sent to a page using the wordpress theme customizer.  I am looking to develop a plugin, not a theme and want a settings/options page for the plugin.  Can Redux help with that?

**Comment by kprovance** [comment]
It can, since plugins do not use the customizer.  I'm not sure exactly where you got sent, but no, we are most assuredly NOT customizer only.  :)
