### ISSUE TITLE
Ronneby

### ISSUE THREAD

**Issue by inteconlinekft** [reduxframework/redux-framework#3001]
Hi

Im trying to setup Ronneby template, whatever i do i can not change in theme options>> Layouts> Settings Single pages layout>>always jump back to no sidebar. Im having trouble also change header in single post or for blog, if i choose header 1 or 2 nothing happen not possible to change it.

Pls advise.
Sam

**Comment by kprovance** [comment]
We are the author of your theme, or any theme, and do not support it.  Please contact the author for support.  Thanks.
