### ISSUE TITLE
Redux Framework & Rev Slider CSS Issue

### ISSUE THREAD

**Issue by Bluxart** [reduxframework/redux-framework#3002]
Hi, when the revolution slider plugin is enabled in backend the redux-framework miss some css style for example from button_sets field.

The problem appear only when revolution slider is active.

This when the rev slider is active: http://cl.ly/321R123B3u2y
Here rev slider is disabled: http://cl.ly/0I0D3G3e161W

**Comment by kprovance** [comment]
Since Rev SLider is the issue (which is it, I've seen it), you need to mentionit to the Theme PUnch folks (I have also).  I can't make up for RevSlider's shortcomings.  Thanks.  :)

**Comment by dovy** [comment]
This is because they're applying their CSS to every page. You may suggest to them to only include the CSS to pages that apply to them, as we are doing.  :)

**Comment by Bluxart** [comment]
I figured that the problem was revolution slider, try to contact them to see if they solve the problem.

**Comment by dovy** [comment]
You could also find a hook to remove their CSS. ;)

**Comment by Bluxart** [comment]
Ok thanks, otherwise with WPML active and Rev Slider deactivate the problem appear.

**Comment by Bluxart** [comment]
PS: This little visual bug appear only inside page and post with metabox and not in redux admin panel.
