### ISSUE TITLE
Error When Including Panels

### ISSUE THREAD

**Issue by moshemo** [reduxframework/redux-framework#3003]
I am trying to follow the instructions on this page:  [https://docs.reduxframework.com/core/templates/](url)

I have taken the following steps:

1. Copied the panels files in ReduxFramework/ReduxCore/templates/panel to a new folder inside my plugin lib folder

2. Used the following code to include those panel files:

`if ( !isset( $redux_demo ) && file_exists( plugin_dir_path( __FILE__ ) . 'lib/options/templates/container.tpl.php' ) ) {
    require_once plugin_dir_path(__FILE__) . 'lib/options/templates/container.tpl.php';
}`

When I try to reload the wp-admin, though, I get the following message:

> Fatal error: Using $this when not in object context in C:\wamp64\www\morethinking2\wp-content\plugins\admin-plus\lib\options\templates\container.tpl.php on line 12

Here is the code that appears on line 12:

`    $expanded = ( $this->parent->args['open_expanded'] ) ? ' fully-expanded' : '' . ( ! empty( $this->parent->args['class'] ) ? ' ' . esc_attr( $this->parent->args['class'] ) : '' );
    $nonce    = wp_create_nonce( "redux_ajax_nonce" . $this->parent->args['opt_name'] );`

Any suggestions on how to fix this?

Thanks.

**Comment by kprovance** [comment]
That's now how panels are loaded.  https://docs.reduxframework.com/core/templates/

You choose a location in your project and copy the panels files there, then specify that path in the `templates_path` argument.  Instructions are on that page.

**Comment by moshemo** [comment]
Is the argument for templates_path supposed to look like this:

`'templates_path'        => plugin_dir_path(__FILE__) . 'lib/options/templates/',`

Here is the full code if you need it: 

    $args = array(
        // TYPICAL -> Change these values as you need/desire
        'opt_name'             => $opt_name,
        // This is where your data is stored in the database and also becomes your global variable name.
        'templates_path'        => plugin_dir_path(__FILE__) . 'lib/options/templates/',
        'display_name'         => $theme->get( 'Name' ),
        // Name that appears at the top of your panel
        'display_version'      => $theme->get( 'Version' ),
        // Version that appears at the top of your panel
        'menu_type'            => 'menu',
        //Specify if the admin menu should appear or not. Options: menu or submenu (Under appearance only)
        'allow_sub_menu'       => true,
        // Show the sections below the admin menu item or not
        'menu_title'           => __( 'Sample Options', 'redux-framework-demo' ),
        'page_title'           => __( 'Sample Options', 'redux-framework-demo' ),
        // You will need to generate a Google API key to use this feature.
        // Please visit: https://developers.google.com/fonts/docs/developer_api#Auth
        'google_api_key'       => '',
        // Set it you want google fonts to update weekly. A google_api_key value is required.
        'google_update_weekly' => false,
        // Must be defined to add google fonts to the typography module
        'async_typography'     => true,
        // Use a asynchronous font on the front end or font string
        //'disable_google_fonts_link' => true,                    // Disable this in case you want to create your own google fonts loader
        'admin_bar'            => true,
        // Show the panel pages on the admin bar
        'admin_bar_icon'       => 'dashicons-portfolio',
        // Choose an icon for the admin bar menu
        'admin_bar_priority'   => 50,
        // Choose an priority for the admin bar menu
        'global_variable'      => '',
        // Set a different name for your global variable other than the opt_name
        'dev_mode'             => true,
        // Show the time the page took to load, etc
        'update_notice'        => true,
        // If dev_mode is enabled, will notify developer of updated versions available in the GitHub Repo
        'customizer'           => true,
        // Enable basic customizer support
        //'open_expanded'     => true,                    // Allow you to start the panel in an expanded way initially.
        //'disable_save_warn' => true,                    // Disable the save warning when a user changes a field

        // OPTIONAL -> Give you extra features
        'page_priority'        => null,
        // Order where the menu appears in the admin area. If there is any conflict, something will not show. Warning.
        'page_parent'          => 'themes.php',
        // For a full list of options, visit: http://codex.wordpress.org/Function_Reference/add_submenu_page#Parameters
        'page_permissions'     => 'manage_options',
        // Permissions needed to access the options panel.
        'menu_icon'            => '',
        // Specify a custom URL to an icon
        'last_tab'             => '',
        // Force your panel to always open to a specific tab (by id)
        'page_icon'            => 'icon-themes',
        // Icon displayed in the admin panel next to your menu_title
        'page_slug'            => '',
        // Page slug used to denote the panel, will be based off page title then menu title then opt_name if not provided
        'save_defaults'        => true,
        // On load save the defaults to DB before user clicks save or not
        'default_show'         => false,
        // If true, shows the default value next to each field that is not the default value.
        'default_mark'         => '',
        // What to print by the field's title if the value shown is default. Suggested: *
        'show_import_export'   => true,
        // Shows the Import/Export panel when not used as a field.

        // CAREFUL -> These options are for advanced use only
        'transient_time'       => 60 * MINUTE_IN_SECONDS,
        'output'               => true,
        // Global shut-off for dynamic CSS output by the framework. Will also disable google fonts output
        'output_tag'           => true,
        // Allows dynamic CSS to be generated for customizer and google fonts, but stops the dynamic CSS from going to the head
        // 'footer_credit'     => '',                   // Disable the footer credit of Redux. Please leave if you can help it.

        // FUTURE -> Not in use yet, but reserved or partially implemented. Use at your own risk.
        'database'             => '',
        // possible: options, theme_mods, theme_mods_expanded, transient. Not fully functional, warning!
        'use_cdn'              => true,
        // If you prefer not to use the CDN for Select2, Ace Editor, and others, you may download the Redux Vendor Support plugin yourself and run locally or embed it in your code.

        // HINTS
        'hints'                => array(
            'icon'          => 'el el-question-sign',
            'icon_position' => 'right',
            'icon_color'    => 'lightgray',
            'icon_size'     => 'normal',
            'tip_style'     => array(
                'color'   => 'red',
                'shadow'  => true,
                'rounded' => false,
                'style'   => '',
            ),
            'tip_position'  => array(
                'my' => 'top left',
                'at' => 'bottom right',
            ),
            'tip_effect'    => array(
                'show' => array(
                    'effect'   => 'slide',
                    'duration' => '500',
                    'event'    => 'mouseover',
                ),
                'hide' => array(
                    'effect'   => 'slide',
                    'duration' => '500',
                    'event'    => 'click mouseleave',
                ),
            ),
        )
    );


If so, it doesn't seem to be working for me.  I made a slight modification to the container.tpl.php file to test it out and nothing changed on the options-page in wp-admin.

**Comment by kprovance** [comment]
I'm not entirely sure.  It's not something I can debug from here as I am not on your server or have the same setup.  You need to run some path checks on the path you are providing.  The feature is working, as it's being used in live themes.  Understand, we're are not PHP tutors.  This git is more for bug tracking and issue reporting.  If you would like us to examine your code to tell you what you're doing wrong, that's going to fall under premium service.   :)

**Comment by moshemo** [comment]
The following code:  

`$t_dir = plugin_dir_path(__FILE__) . 'lib/options/templates/';
echo $t_dir;`

Shows the following path:

`C:\wamp64\www\morethinking2\wp-content\plugins\admin-plus/lib/options/templates/`

Is there anything wrong with that path?

**Comment by kprovance** [comment]
There is no way for me to know if it's correct or not.  I don't have access to your computer.  It looks okay?
