### ISSUE TITLE
How to load config from theme ?

### ISSUE THREAD

**Issue by shrimp2t** [reduxframework/redux-framework#3004]
I trying to load config from theme with Redux framework plugin https://wordpress.org/plugins/redux-framework/ and remove same config option from plugin.
But i can't find any ways to remove same config from plugin 
How to do that ?

Maybe we need add a hook to filter config file ( line 156 file wp-content/plugins/redux-framework/class.redux-plugin.php )
```php
// Include demo config, if demo mode is active
 if ( $this->options['demo'] && file_exists( dirname( __FILE__ ) . '/sample/sample-config.php' ) ) {
 require_once dirname( __FILE__ ) . '/sample/sample-config.php';
}
```

Change to 

```php
// Include demo config, if demo mode is active
$config_file = apply_filters( 'filter_name',  dirname( __FILE__ ) . '/sample/sample-config.php' ); 
if (  $config_file ) {
require_once $config_file;
}
```
That better !.

**Comment by kprovance** [comment]
There si already a hook to remove the demo.  It's in the sample-config.php file

```
add_action( 'redux/loaded', 'remove_demo' );

    if ( ! function_exists( 'remove_demo' ) ) {
        function remove_demo() {
            // Used to hide the demo mode link from the plugin page. Only used when Redux is a plugin.
            if ( class_exists( 'ReduxFrameworkPlugin' ) ) {
                remove_filter( 'plugin_row_meta', array(
                    ReduxFrameworkPlugin::instance(),
                    'plugin_metalinks'
                ), null, 2 );

                // Used to hide the activation notice informing users of the demo panel. Only used when Redux is a plugin.
                remove_action( 'admin_notices', array( ReduxFrameworkPlugin::instance(), 'admin_notices' ) );
            }
        }
    }
```

**Comment by shrimp2t** [comment]
Hi @kprovance,
Thanks for reply, but it not work if you active theme first then active this plugin or whatever option `ReduxFrameworkPlugin` is set and `demo` key is true.

####Problems
We can remove the toggle demo config link in plugins listing page but can't remove admin notices.

if the option name `ReduxFrameworkPlugin` is set, there is no ways to change it, even hook apply_filters( 'option_'.$option_name ):
```php
get_option('ReduxFrameworkPlugin');
``
####Why ?
I found method `ReduxFrameworkPlugin::hooks` but i can't hook any functions there because class `ReduxFrameworkPlugin` run immediately when the plugin file loaded.

There only way to do that is delete option `ReduxFrameworkPlugin`:

```php
function wpcoupon_options_init () {
        //force remove sample redux demo option
        delete_option( 'ReduxFrameworkPlugin' );
    }
    add_action( 'init', 'wpcoupon_options_init' );
```

Please check it again.

**Comment by kprovance** [comment]
Not sure what you want me to check, or what exactly you are doing.  The provided method to disable to demo works.  I do it in my theme.  If you found a kind of hack that works for you, then use it?
