### ISSUE TITLE
When we open the link for a documentation page it expands all categories in documentation

### ISSUE THREAD

**Issue by abhinavchitre** [reduxframework/redux-framework#3005]
When i open a link to a documentation page it expands all categories on navigation tab

**Comment by kprovance** [comment]
You're going to need to be a little more specific.

**Comment by abhinavchitre** [comment]
Hello ,

Please find below link to our website. We are using the manual theme.

citruspay.info/devguide

when we click on an item on the home page, it navigates to a page in
documentation but then it expands all the topics in the left navigation tab
instead of only expanding the topic corresponding to the URL.

for eg click on Wallet or SplitPay and it will expand all topics in
navigation resulting in bad UI

Is there a way to solve this problem?

**Comment by kprovance** [comment]
That's not our site, and if this is about support for a theme, we are not the authors.  You will need to contact whomever that is for support.
