### ISSUE TITLE
Customizer JS Error

### ISSUE THREAD

**Issue by Bluxart** [reduxframework/redux-framework#3006]
Hi, I try to use the customizer with Redux Framework.

But don't work, the console return me a js error:

extension_customizer.js?ver=2.0.0:99 Uncaught TypeError: Cannot read property 'parseAll' of undefined

This is the string:

```javascript
// Helper to get the default value for this option if none is specified by the user
optWithDefault = function( key ) {
    return (options[key] !== false) && (options[key] !== '') && (options[key] || defaultOptions[key]);
};
```

Redux Framework: 3.6.0.4

**Comment by kprovance** [comment]
C"mon dude, you've posted often enough now, you should know better.  https://github.com/reduxframework/redux-framework/blob/master/CONTRIBUTING.md  SUPPORT URL, SUPPORT URL, SUPPORT URL!!!  I am requiring it of everyone now, or I close tickets.

**Comment by dovy** [comment]
Helps us debug a TON if you can provide that.  ;)

**Comment by Bluxart** [comment]
I need to transfer my site in live server, for now I work in localhost. I send the suppor URL as soon as possible.

**Comment by Bluxart** [comment]
Not possible create the support URL, send me an error alert.

**Comment by kprovance** [comment]
Yoou're going to have to be way more specific that "I got an error".  Once again, please review:   https://github.com/reduxframework/redux-framework/blob/master/CONTRIBUTING.md.  I'd like you to actually read it this time, please.  Thanks.

**Comment by Bluxart** [comment]
Hi have this in console.log http://cl.ly/2p3Z420u1w3s

**Comment by kprovance** [comment]
Please update to version 3.6.0.5 from this git repo and try again.

**Comment by Bluxart** [comment]
Now the support URL work, thanks this is the link.

SUPPORT URL: http://support.redux.io/?id=615iF3mRacmEnSzP86dPFGuj7wp5AjSay9PLHlhwe4%2BJQg%2FC6aiT0ZQi05StCUMMhg93mjH7DJVyaC2dYrT5ew%3D%3D

**Comment by Ryu-k** [comment]
Hello,

I have the same problem using the version 3.6.0.5, this is the support URL : http://support.redux.io/?id=e43%2FVpXMSwVgAiNBt8Q%2BxW3n%2B%2BTHksERfTLTMeJMWsETSSG8tcxBHTWmMIlwPOSk0XsHYw%2FO%2BSbtRQp5SuFzCg%3D%3D

Thanks in advance.

Regards

**Comment by contempoinc** [comment]
Same problem here along with all my buyers sites about 1700 of them.

**Comment by kprovance** [comment]
Right now, I just don't have the time to devote to it, and I have no idea where Dovy is.  This is a community project.  If one of you chaps wants to tinker with it, by all mean, please do.  If you find out what's up, let us know and we'll apply the fix.

**Comment by contempoinc** [comment]
I have no clue where to even start with this but I'd be more than willing to pay a little bit for your time to get this resolved.

**Comment by contempoinc** [comment]
I mean if the plugin version of the framework works properly why don't you just migrate the codebase? Also why would there be a difference like this between the two, shouldn't they basically share the same codebase, with slight modifications of course as its a plugin?

**Comment by kprovance** [comment]
I don't know.  Dovy does the customizer stuff.  There is only a plugin version of Redux.  If people use it to embed, it's the same code base, unless they tamper with it.

**Comment by contempoinc** [comment]
See then it doesn't make any sense that it would throw an error, I haven't tampered with any core framework code and I'm running the latest version.

**Comment by contempoinc** [comment]
Looks like Dovy is offline on Skype…

**Comment by kprovance** [comment]
He hasn;t contacted me for a few days now.  I don't know where he is.

**Comment by kprovance** [comment]
Well, I can't find him either.  I guess I need to be the materialistic weasel here and as what 'a little bit' is.  if you don't want to say here, email me kevin@reduxframework.com.  We're talking at least an hour of my time, minimum, because I'm going to have to go over Dovy's code and see what exactly he's doing and then figure out why it's not working.

**Comment by contempoinc** [comment]
What's your hourly rate?

**Comment by kprovance** [comment]
I'll do it for 100, regardless how long it takes.  Won't be able to get in front of my local until 7ish EST though.

**Comment by contempoinc** [comment]
Sounds good.

@Bluxart @Ryu-k You guys want to kick in a few bucks to get this resolved?

**Comment by Ryu-k** [comment]
I wouldn't mind give a few bucks, also I know it's a different problem but if anyone has information about this extension : "https://ideas.reduxframework.com/campaigns/complete-customizer-integration/" is there anywhere we can get this extension or if it's still working with the newest version of WordPress?

**Comment by kprovance** [comment]
I've pretty much got it fixed.  My PayPal is kevin.provance@gmail.com.  If it goes right to Redux, well, I don't know if I'll see it at this point since I don't have access to that account.

I can't seem to get a hold of Dovy.  He won't return my messages (I'm kinda hoping he's okay, and that nothing is wrong at this point).  He's the one who will have to give you an answer about the advanced customize thing, since it's his project.

**Comment by dovy** [comment]
I'm not dead, just going crazy. I've got some great news coming about the advanced customizer, so stay tuned. If you want early access you can email dovy@redux.io

**Comment by Ryu-k** [comment]
Sorry Kevin, had a busy day yesterday, I just sent you money, if you have found the problem or succeed to update the script please tell me :)

Dovy, glad to see you are alive, I just sent you a mail, reply when you have time.

Regards

**Comment by kprovance** [comment]
@Ryu-k - email me - kevin@reduxframework.com

@contempoinc - You still in on this?

**Comment by kprovance** [comment]
Well, it's fixed.  Gotta say, @contempoinc , I'm a little disappointed to see you let someone else pick up the tab on this.  It was my time after all.

**Comment by Bluxart** [comment]
@kprovance what is your paypal e-mail?

**Comment by dovy** [comment]
@bluxart it's kevin.provance@gmail.com
