### ISSUE TITLE
Redux and Themeforest

### ISSUE THREAD

**Issue by mlyczko** [reduxframework/redux-framework#3008]
Hi

I've recently seen your message in documentation :
"Embedding the Redux repo will not pass approval
Be warned that if you attempt to embed the entire Redux repo inside a theme or plugin it will not pass approval for many marketplaces including WordPress.org and ThemeForest."

So, I can use Redux framework only as a plugin ? 
But how this is comparable to Themefores requirement - that, theme should be  fully working without 3rd party plugins ?

I know that I can set Redux plugin as required in TGM, but it will be passable for Themeforest ?

Best Regards
ML

**Comment by kprovance** [comment]
What they mean is your theme needs to load up without any plugins.  If you add

```
if ( !class_exists ( 'Redux' ) ) {
    return;
}
```

to your config, there won't be any php errors on load minus the plugin being loaded.  It's stupid, I know, but that's what they want.
