### ISSUE TITLE
Getting "Parse error…" only on some buyers servers

### ISSUE THREAD

**Issue by contempoinc** [reduxframework/redux-framework#3009]
Only come across 3-5 buyers with this issue out of over 1600 that use my RE7 theme, it won't allow any of the panels to load in the admin options.

![screenshot](https://cloud.githubusercontent.com/assets/686530/15723218/5499e062-27f6-11e6-8ae0-7c87ce6cae3d.png)

This function is the culprit once its removed everything loads up correctly. I'm assuming this a PHP version of possible module issue that needs to be on the server — any idea what's required for the function to run properly?

```php
    #
    # Static Methods
    #

    static function instance($name = 'default')
    {
        if (isset(self::$instances[$name]))
        {
            return self::$instances[$name];
        }

        $instance = new static();

        self::$instances[$name] = $instance;

        return $instance;
    }
```

**Comment by kprovance** [comment]
Version information, please?  Support URL?  I need these things to try it on my end.  :)

**Comment by kprovance** [comment]
Oh.  Parsedown.  Vendor code.  Figures.  There was a PHP7 issue with that some moonths back.  I updated the vendor code to version 1.6.0, which should have solved that.  Is your version of Redux up to date, to at least the version on wp.org?

**Comment by contempoinc** [comment]
My theme is running 3.6.0.4

**Comment by contempoinc** [comment]
Did you release a fix in 3.6.0.5? Don't see anything mentioned in the changelog about it?

**Comment by kprovance** [comment]
It was updated in 3.5.8.12.  I checked thier site.  We have the latest installed in Redux.  Are you actually using the parsedown argument to parse MD code?  If not, remove that argument.  In the interim, I don;t know what the answer would be.  You may need to get the PHP version from the people who are having issues.  PHP 5.2 is no longer supported, apparently.

**Comment by contempoinc** [comment]
Ok, that's what I was thinking. Would there be any issues removing it? Really don't like hacking core files and like I said it was only 3-5 of my buyers out of over 1600 report the problem, which I'm assuming now that those few people are running an old PHP version.

**Comment by kprovance** [comment]
Removing what, specifically?  the actual file from the core?  It's cause errors as long as you have markdown set in your raw field code (why I asked for a support URL).  If you are not parsing any raw MD code in your fields, you can turn the markdown off.  Do a search in your config for `'markdown' => true`.  If you see it, delete it, or set it to false.

**Comment by contempoinc** [comment]
I'm not parsing any raw MD code, I'll just set it to false. Thanks!

**Comment by kprovance** [comment]
That should do it.  Closing.  :)
