### ISSUE TITLE
Redux in plugin and theme is breaking google font

### ISSUE THREAD

**Issue by montourst** [reduxframework/redux-framework#3011]
Hey,

I have a plugin im working on. I am using Redux for a few options for the plugin.
When my plugin is installed into the theme(also using redux) it seems Google font strings are being returned differently and broken. My plugin does not use anything for fonts, the theme however does.

I understand this could be a theme issue. I wanted to check here first to make sure im using Redux in my plugin correctly. I have searched the closed topics and have found a few things close but nothing to my exact issue.

With my plugin installed:
`<link rel='stylesheet' id='redux-google-fonts-salient_redux-css'  href='http://fonts.googleapis.com/css?family=Droid+Sans%7COpen+Sans%3A600&#038;subset=latin%2Csubset&#038;ver=1464990754' type='text/css' media='all' />`

Without my plugin installed:
`<link rel='stylesheet' id='redux-google-fonts-salient_redux-css'  href='http://fonts.googleapis.com/css?family=Droid+Sans%7COpen+Sans%3A600&#038;subset=latin&#038;ver=1464990754' type='text/css' media='all' />`

It seems the culprit when my plugin is installed is this little guy %2Csubset being added to the link for the font, towards the end right after subset=latin. If I remove it in firebug everything renders fine.

Im new to using Redux so I a)apologize if this is a juvenile issue, and I should have read doco better. And b) whatever code you need me to post I most certainly will.

If I delete my call for the framework from my plugin the fonts seem to render just fine, as they would if I kept it and deactivated my plugin.
```
if ( !class_exists( 'ReduxFramework' ) && file_exists( dirname( __FILE__ ) . '/admin/redux-framework/ReduxCore/framework.php' ) ) {
    require_once( dirname( __FILE__ ) . '/admin/redux-framework/ReduxCore/framework.php' );
}
```
Im building in Wordpress 4.5.2.

Thanks in advance.

Cheers

**Comment by kprovance** [comment]
You may need to get with whomever authored the Salient theme.  I do not have it and cannot test.  They'll need to be the ones to determine why this is happening.  If they determine it's a Redux issue, then we'll need to get with them on it, since the output is coming from the theme itself.

**Comment by montourst** [comment]
That is excellent. Thank You.
