### ISSUE TITLE
How to remove SPEAKER from Schedule?

### ISSUE THREAD

**Issue by shanygrimard** [reduxframework/redux-framework#3012]
![image](https://cloud.githubusercontent.com/assets/3783161/15825548/33dc1248-2bd2-11e6-9ae1-6257b369d813.png)

How can I remove the wording Speakers? As my event as no speakers.

**Comment by kprovance** [comment]
We are not the author of these theme and are unable to offer support or answer questions about it.  You will need to contact the theme author directly for all support matters.  Sorry.  Thanks.
