### ISSUE TITLE
Redux Framework Broke Site

### ISSUE THREAD

**Issue by mechamsamuel** [reduxframework/redux-framework#3015]
When  the Redux Framework is active, the front end of my WP site gives me a 500 error. When I disable this plugin, the front end works, but missing many parts as I am using a theme that requires Redux.

**Comment by kprovance** [comment]
You need to contact the theme author for support, since you paid them for the theme, and not us.  500 is a server error which will probably require them going onto your site to determine why.

Please see: https://github.com/reduxframework/redux-framework/blob/master/CONTRIBUTING.md
