### ISSUE TITLE
Can't add Woocommerce Product Categories to Main Menu using customise under Appearance

### ISSUE THREAD

**Issue by adigroverezy** [reduxframework/redux-framework#3017]
Appearance -> Customise -> Menus -> Main Navigation -> Add Items

Upon adding any category the save & Publish button does not do anything (It does not Save). Any help on this will much appreciated.

Thanks
Adi

**Comment by kprovance** [comment]
We are not the author of your theme, and therefore are unable to support it.  Please contact the theme author for all support matters.  Thanks.
