### ISSUE TITLE
Compatible with customizer?

### ISSUE THREAD

**Issue by PulsarMedia** [reduxframework/redux-framework#3018]
Hey guys, this isn't an issue but a question.

Is Redux fully compatible now with the theme customizer? I am submitting a theme to the wordpress theme repository and was wondering if Redux is accepted now? I would like to use Redux instead of Kirki...Kirki is a slow son of a bit** and riddled with issues.

Thanks.

**Comment by kprovance** [comment]
The basic fields are, the more advanced ones will be available in the advanced customize extension, which I don't know when will be available.

**Comment by PulsarMedia** [comment]
Will WordPress.org approve my theme if i submit it using the Redux framework?

**Comment by kprovance** [comment]
Dovy says if you use TGM to install the Redux plugin, for use with the customizer only, then yes.  If you embed, you'll have to make changes to the core, and then keep making those changes for each update.
