### ISSUE TITLE
Sections description glitch

### ISSUE THREAD

**Issue by Surgeonito** [reduxframework/redux-framework#3019]
Hi!
In case where ` $opt_name ` has a digit used in the name
the [function](https://github.com/reduxframework/redux-framework/blob/master/ReduxCore/framework.php#L3265):
```
public function _section_desc( $section ) {
                $id = trim( rtrim( $section['id'], '_section' ), $this->args['opt_name'] );

                if ( isset ( $this->sections[ $id ]['desc'] ) && ! empty ( $this->sections[ $id ]['desc'] ) ) {
                    echo '<div class="redux-section-desc">' . $this->sections[ $id ]['desc'] . '</div>';
                }
            }
```
spits out a wrong description because the `$id` is guessed incorrectly.

Example:
`$opt_name = "theme123_options";`
let's take 15-th section
`$section['id'] = "theme123_options15_section";`
`$id` take a value "5" not "15" - `trim` function remove this extra "1".
As a result the 15-th section has a description taken from 5-th section.

**Comment by kprovance** [comment]
Could you provide a support URL via these guidelines, please?  https://github.com/reduxframework/redux-framework/blob/master/CONTRIBUTING.md  I need to see some version info and PHP settings.

**Comment by Surgeonito** [comment]
Hi, 
here it is: http://support.redux.io/?id=OY%2FZg5i9EaUhYWTAtPbEQAkc%2FScIPGllyrLeTrqVJL3ObEmZFZFA54PEG2aysNglwEOvrqhfAqbAHIAZDIscvg%3D%3D

**Comment by kprovance** [comment]
Which panel specifically in yourt setup are you seeing incorrect information?  I loaded up your config, but cannot find the issue you are describing.  You may need to walk me through this.

**Comment by kprovance** [comment]
Oh, never mind.  I see what's going on here.  Easy fix,

**Comment by kprovance** [comment]
Also, just as a point of reference here, you might want to change your 'page_slug' argument to something other than the default '_options'.  We have code to catch it, but it's generally a good idea to use something unique.  :)

**Comment by kprovance** [comment]
Corrected in v.3.6.0.6

**Comment by Surgeonito** [comment]
Thank You very much indeed :smile:
