### ISSUE TITLE
Fatal Error on plugin activation

### ISSUE THREAD

**Issue by arifamirtt** [reduxframework/redux-framework#3020]
Hi guys,

When i try to activate plugin, it throws the following error.

Fatal error: Call to undefined function wp_generate_password() in /home/arif/projects/pc.local/wp-admin/includes/file.php on line 179

I tried to install it on separate installations but error is same.

Regards,
Arif

**Comment by dovy** [comment]
You're trying to load it too early. Delay until plugins_loaded.  ;)
