### ISSUE TITLE
Text field for every post type, but get_post_types not working.

### ISSUE THREAD

**Issue by frafra85** [reduxframework/redux-framework#3021]
I need to have a text field for every post type ( also custom post type ) to set a label different for post type.
So, i wanna create an array of post types and then , with a foreach, create fields of text.
How can i get post types ?
If i try in my config file, before Redux::setSection, i retrieve only default post types.
Could you help me please ?
Thanks.

PS: i have integrated redux in my theme and custom post type are created by an external plugin. ( i have necessity to mantain cpt function in this plugin ).

**Comment by dovy** [comment]
Use the data argument for this.  ;)

**Comment by frafra85** [comment]
I don't need a select, i need a text field for every post type.
Is it possible use data argument to do this ? How ?
Thanks.

**Comment by dovy** [comment]
@kprovance Can you think of an easy way to do this?

**Comment by kprovance** [comment]
Text field doesn't support the data argument.  So...create the section, then write a function to get all those post type information, then in  a foreach, use setField to add those text fields in there, would be my guess.
