### ISSUE TITLE
Issue with "add to cart" button

### ISSUE THREAD

**Issue by inactionsuperman** [reduxframework/redux-framework#3022]
Hello. I've website http://bestdealsweek.com/?product=lancer-tactical-airsoft-m240-automatic-general-purpose-machine-gun  As you can see the problem is in "add to cart " button. There is not this button....  When i turn off plugin the button is show up. What do i need to do in this case? Thanks

**Comment by dovy** [comment]
Sorry, we did not author this theme. We are simply the framework your developer used. Best to contact them.  :)
