### ISSUE TITLE
Field 'select' data args for Revolution Slider

### ISSUE THREAD

**Issue by pepsinclar** [reduxframework/redux-framework#3023]
Hi,
is it possibile to populate "select"-Field with sliders available in Revolution Slider?
I have made some tests using the "date" and "args" but I did not succeed.

**Comment by kprovance** [comment]
The args argument won't work with things like RevSlider.  You'd have to write a function to pull down the installed slider names, put them into an array, and feed them into the `options` arg of the select field.  :)

**Comment by pepsinclar** [comment]
Ops....it's true I had not thought about it! :)

Ps. thanks for your quick reply
