### ISSUE TITLE
Google font select error

### ISSUE THREAD

**Issue by pepsinclar** [reduxframework/redux-framework#3026]
Unexpectedly I can no longer to select fonts and I get an error "select2" on the console. See Attachment.

![2016-06-21 alle 16 47](https://cloud.githubusercontent.com/assets/16845432/16234021/7610adb8-37d0-11e6-8837-23e0f60e2a51.png)

**Comment by dovy** [comment]
File permissions. You probably uploaded via FTP. Try uploading via the WP admin panel.  ;)

**Comment by pepsinclar** [comment]
Sorry... I did not understand what you mean .... what should I upload?

**Comment by dovy** [comment]
If the google fonts do not show up suddenly, then there's a file permission issue with one of the PHP files that makes up Redux. You need to fix that permission. The easiest way is to install it via the WP plugin/theme uploader and let WordPress set the proper permissions instead of using FTP.  ;)

**Comment by pepsinclar** [comment]
I have tried to eliminate the issue, and reload by Wp installer but keeps giving me the same error.

What permissions do I need to check?

Redux in the configuration files these values Google fonts:

`
...
'google_api_key' => '[MY_API_KEY]',
'google_update_weekly' => true,
...
`

...and these are the font field value...

`
array(
            array(
                'id' => 'colors-font-body-font',
                'type' => 'typography',
                'title' => __('Body Font', 'redux-framework-demo'),
                'subtitle' => __('Specify the body font properties.', 'redux-framework-demo'),
                'google' => true,
                'font-backup' => false,
                'line-height' => false,
				'text-align'	=> false,
				'font-size'	=> false,
				'subsets'	=> false,
				'output' => array('body'), // An array of CSS selectors to apply this font style to dynamically
				'default'     => array(
					'color'       => '#000', 
					'font-style'  => '400', 
					'font-family' => 'Ubuntu Condensed', 
					'google'      => true
				),
            ),
`

**Comment by pepsinclar** [comment]
I have verified that the file "themes/.../redux-framework/ReduxCore/inc/fields/typography/**googlefonts.php**" is not generated ... write permissions on the folders are ok. 
What else can I check?

**Comment by kprovance** [comment]
I would download the redux master file from this repo, grab the googlefonts.php and upload it into the typography field folder, especially if it's not there.

**Comment by pepsinclar** [comment]
Perfect now it works... I've done as you suggested.
I downloaded the master and replaced only the folder "themes/.../framework/redux-framework/inc/fields/**typography**"

Do you suggest that I have to turn "false" the "google_update_weekly" option?

**Comment by kprovance** [comment]
Since there seems to be a lingering permissions error, I would suggest doing so.  I try to keep that file updated with the latest fonts on each release.
