### ISSUE TITLE
crashing the website

### ISSUE THREAD

**Issue by cbmwebdesign** [reduxframework/redux-framework#3027]
Hi,

I accidently pushed the demo link, and now I can not activate this plugin. When I do, I see this error

_Fatal error: Call to undefined function wp_generate_password() in /home/eurydice/domains/cbhri-virology.com/public_html/wp-admin/includes/file.php on line 179_

I have uploaded a new file, but the error remains.

What can I do to solve this error so I can activate the plugin?

**Comment by kprovance** [comment]
Is this a theme issue?  If the plugin isn't activated, then how is it a Redux issue?  I'm lost.  Also, no version information has been provided:  https://github.com/reduxframework/redux-framework/blob/master/CONTRIBUTING.md

**Comment by cbmwebdesign** [comment]
Hi Kevin, I am using Avada, latest version, and WP latest version. Thanks for your reply.
The plugin worked just fine, but I accidently pushed on a demo link, of this plugin. And now I can not activate it, without getting this error. I deleted the plugin and then reinstalled it, but the error is not gone. So when I do activate the plugin, this error comes.

**Comment by dovy** [comment]
That's interesting. So change themes, activate redux, turn off the demo mode, and switch back the theme. Then contact the Avada boys and let them know some of their hooks are running redux too early. ;)

**Comment by cbmwebdesign** [comment]
Changed it to theme twentyfifteen, activated the plugin, and I got the error again. I wish I could turn off the demo mode, but there is no option to do so.

**Comment by dovy** [comment]
Deactivate the avada framework plugin too. ;)

They ran a filter to hide the deactivate the demo link.

**Comment by kprovance** [comment]
Which is called Fusion Core.  If that doesn't do it, you'll have to do some digging, specifically in your PHP error logs.  The last time I saw something like this is because session_start was failing, because the server was 'full' (at capacity) and PHP was shutting down left and right.  The only way to make that determination, regardless the cause, is to examine the error logs and see what's going on before the error you are reporting.

**Comment by kprovance** [comment]
But, yeah, if it's a Fusion Core thing, you'll have to report this to the Avada folks.  :)
