### ISSUE TITLE
At what point can I initialize Redux

### ISSUE THREAD

**Issue by nevetssoftware** [reduxframework/redux-framework#3029]
If I include the config file directly in the plugin I am writing, the menu item and option settings are added as expected.  But this runs before another plugin that I need initialized first.

So I tried using the 'admin_init' action to load the config file.  It is included and there are no obvious errors but the menu item does not appear.  (I have also tried 'admin_menu').

Do you know if this should work or not?

Thanks
Steve

PS.   The plugin would not generate a support URL

**Comment by kprovance** [comment]
plugins_loaded would be my guess.  Somewhere on the WP codex is a list of them.  You'll have to play around with them till you find one that works.  Good luck!  :)
