### ISSUE TITLE
Redux extension metaboxes and redux framework issues.

### ISSUE THREAD

**Issue by saltict** [reduxframework/redux-framework#3031]
Hi author!

I bought redux extension metaboxes, and use in our theme. Its very usefull with me but I have 2 issues when work with them, because redux framework.

1. Output problem:
Output in metaboxes can not replace theme option or generate unwanted css in some field when use same output:
-  background: when I define background color only in metaboxes, It should be replace both background-image that defined in theme option but it doesn't.
- border: when border width of left, right, top or bottom is not defined its output still appear like "border-top: px solid #ddd;".
- dimension and spacing: be same like border it generate values px only.
- rgba field: when I set opacity is 0 it generate value 1, so I can not use transparent in this field
Can be still problem like them in other field, please check again generate rule in all field.

2. Check field is empty: Redux should get option should return empty values or have function to check empty of field like image, spacing, image ... to use them in same way like this:
//Check image field is empty
if(is_redux_empty('logo')){
    //Some code go here
}
//Check spacing is empty
if(is_redux_empty('header-spacing'){
   // Some code go here
}
....

Many thanks.

**Comment by kprovance** [comment]
Extension issues go here:  https://github.com/reduxframework/redux-extensions  Thanks!
