### ISSUE TITLE
Switch Option output in IF else condition

### ISSUE THREAD

**Issue by itworldbd** [reduxframework/redux-framework#3033]
Hello, First of all, thanks for great support.

i made a switch option in redux framework & code is > 

            array(
                'id'       => 'cpv-hm-cat-swi-12',
                'type'     => 'switch',
                'title'    => __( 'Switch On', 'citypost' ),
                'default'  => true,
            ),

Now i want to show in my wordpress, if switch is on, then my section will display >>

     <div class="video-icon-btn">
          <i class="fa fa-play"></i>
          <h1> Switch is On </h1>
      </div>

when my switch if off, then nothing will show there. How can i write that condition properly in wordpress beacuse i was tried that code which given below and its not working.

      <?php if (true == $cpv('cpv-hm-cat-swi-12')): ?>
          <div class="video-icon-btn">
               <i class="fa fa-play"></i>
              <h1> Switch is On </h1>
         </div>
    <?php endif; ?>

Kindly help me & apologies for poor English. Thanks a lot.

**Comment by dovy** [comment]
Figured it out?  ;)
