### ISSUE TITLE
CSS Output on field_typography

### ISSUE THREAD

**Issue by ksere** [reduxframework/redux-framework#3036]
Hi there, 

Regarding some css styles you are [outputting on when using async fonts](https://github.com/reduxframework/redux-framework/blob/master/ReduxCore/inc/fields/typography/field_typography.php#L742)

There are cases where this conflicts and overrides default styles from a theme, for example i had the 'body' as a selector in a fonts field output, which caused redux output to reset it's css transitions. 

One option would be to completely remove those styles, along with the following styles prepended with .wf-loading, and let the theme take care of all that?

Or perhaps add a filter or an option in redux args to disable the specific output on demand?

Let me know and i can give it a try and send a PR.

Regards,
Kostas

**Comment by kprovance** [comment]
If that breaks backward compatibility, then we can't do that.  A filter isn't out of the question

**Comment by ksere** [comment]
You are right, anyone who has it setup with async fonts would probably see
a visual difference when the fonts are loading. I 'll see what i can do.

**Comment by kprovance** [comment]
Cool.  I'm going to close this ticket, since it's just sitting here, but please feel free to submit a pull request if you come up with something workable.  I'm going to start going through them here soon to figure out what works and what doesn't.

Cheers!
