### ISSUE TITLE
if text field has value then show value condition

### ISSUE THREAD

**Issue by itworldbd** [reduxframework/redux-framework#3037]
Hello,

Actually i need a conditional loop for text field. i want to >> if my text field has value then show value or if text field empty then no output show in theme. 

i use this loop, its worked with buttons but its not working for text field.

      <?php if($cpv['cpv-logo-footer-3'] == 1) : ?>
          <li><a href="<?php echo $cpv['cpv-logo-footer-3'];?>"><i class="fa fa-facebook-square social-icon facebook-color"></i></a></li>
      <?php  endif?>

how can i do that?

Regards.

**Comment by kprovance** [comment]
I'm sorry, but were really not PHP tutors here.  You would need a basic PHP foreach loop.  www.php.net
