### ISSUE TITLE
How to replace the Redux options/args in config file

### ISSUE THREAD

**Issue by codelessteam** [reduxframework/redux-framework#3038]
I have added this code at function initSettings at Redux config file, in previous versions of Redux:

`add_filter('redux/options/cl_redata/options/simple', 'simple_styleswitch_opt_online_demo' );
            $this->ReduxFramework = new ReduxFramework($this->sections, $this->args); 
            add_action('wp_ajax_nopriv_simple_online_export_options', array($this, 'ajax_simple_export_options')); `

It worked fine, but I have updated Redux and don't know how to add it in the config file of the new redux version.
Please can you help?

**Comment by dovy** [comment]
We no longer use filters for setting options. Please look at the sample confit file and use the new redux API. It will make things a lot easier for you. ;)
