### ISSUE TITLE
Can't Save Setting.

### ISSUE THREAD

**Issue by sonnnaht** [reduxframework/redux-framework#3039]
Hello everybody,
When a save setting of redux framework it is has isses, and can't save, 

Please help me check it.
Look at image below:

![redux](https://cloud.githubusercontent.com/assets/14999196/16573292/7511cdb2-429c-11e6-9023-36f152f0fe06.png)

Thanks so much!

**Comment by kprovance** [comment]
See support guidelines here:  https://github.com/reduxframework/redux-framework/blob/master/CONTRIBUTING.md

**Comment by kprovance** [comment]
No reply.  Closing.
