### ISSUE TITLE
how remove  edux-framework 3.6

### ISSUE THREAD

**Issue by duboit** [reduxframework/redux-framework#3040]
Hello,

I installed redux framework with a couper theme
My wordpress is a multisite installation
i can't install an another theme because the admin page is welcome Redux Framework 3.6...
I desactivate the plugin and the theme but the problem continued
i tried redux framework disable plugin it doesn't work
Can you help me please?

**Comment by kprovance** [comment]
If Redux came with the theme, the theme author needs to provide you support.  We do not support users of themes that use Redux.  It;s the authors responsibility.  Sorry.  He needs to upgrade Redux, because we fixed that issue a long time ago.
