### ISSUE TITLE
Base Template Color Change not working

### ISSUE THREAD

**Issue by Dynamitefx** [reduxframework/redux-framework#3043]
Hi Team,
I have a little problem . I use currently WordPress version 4.5.3 with the Theme Beeanca . I have all installed and now wanted to adjust the color of the theme. If I set the color in the backend will not appear in the Theme .

The logo will not be displayed even if I uploaded it . Now I have read that the file must be rights changed . I did that and a new folder in wordpress / wp-content / uploads / created named / redux / this folder has the file permissions of 777 but still it does not work .

Somehow, the settings are not saved to the CSS .

Who can help me?

**Here is another answer from a forum .**

> I had the same issue after moving to a new hosting, finally the issue was the route to the uploads folder wasn't updated, check under Settings -> Media, by default it should be wp-content/uploads
> 
> Hope it helps!

https://wordpress.org/support/topic/problem-permission-denied-plugin-redux-framework

What exactly does he mean?

Thanks for your support

**Comment by kprovance** [comment]
I'm not sure how you ended up here, we we are not the author of your theme, and therefore are not able to offer support for it.  Please contact the theme author directly.  Thanks.
