### ISSUE TITLE
Problems with image_select field

### ISSUE THREAD

**Issue by swirltheme** [reduxframework/redux-framework#3044]
If you use multiple image_select fields in a section OR in different subsection under some specific section then it don't save and loses their values, Even previously saved one too.
For example,
Here is first **image_select field**
array(
			    'id'       => 'header_version',
			    'type'     => 'image_select', 
			    'presets'  => true,
			    'title'    => __('Header Layout Variations', 'swirl'),
			    'subtitle' => __('Select the layout you want to use.', 'swirl'),
				'required'  => array('header_hide', '=', '0'),
			    'options'  => array(
                                                       ....Further options for this one goes here
**And this is 2nd image_select field**
array(
			    'id'       => 'header_nav_variations',
			    'type'     => 'image_select', 
			    'presets'  => true,
			    'title'    => __('Header Layout Variations', 'swirl'),
			    'subtitle' => __('Select the layout you want to use.', 'swirl'),
				'required'  => array(array('header_hide', '=', '0'), array('header_version', '!=', '7'), array('header_version', '!=', '14')),
			    'options'  => array(
                                                          .....Further options here
They lose their values. One might be saved other loses its value. And front end starts producing errors like this 
Notice: Undefined index: header_version in ...redux-framework\ReduxCore\framework.php on line 3604

**Comment by kprovance** [comment]
#2914 - Yeah, it's a thing, but I really don't have the time to rip it all apart to figure out why, and no one seems to want to pay us or donate to us to do so (or say they will then don't follow through).  It's a community project.  If you want to dig into the code and find a solution, we'll happily review any pull request for it.  :)

**Comment by swirltheme** [comment]
That is weird. A lot of themes are using it. We are working on a theme and would love to donate some if our project worked well.
Anyway, We will post if got some solution.
If anyone else has got solution to it then post a reply please.
Thanks

**Comment by kprovance** [comment]
Well, the sad fact is that until someone says it and actually means it, it then becomes about my availability and giving up my free time.  The last person I stopped everything I was doing to help out, who said he would support us took my fix and ran, not paying us a thing.  I've tagged this into an open ticket, so I'm closing it for now.

**Comment by swirltheme** [comment]
I tested few more things and came to conclusion that it is not issue of two image_select fields. This issue arises when using preset.
Image select field with presets loses its value when you refresh page and press save button refresh and save again.
Similar issue also reported earlier:
https://github.com/ReduxFramework/redux-framework/issues/1725

**Comment by swirltheme** [comment]
Looks like finally i have figured it out.
I was using a preset option that was defined no where in config file.
Example:
'presets' => array(
                            
							//'top_bar_border_btm_color' => 'transparent',
							'top_bar_bg_color' => '#eb2629',
							'top_bar_text_color' => '#ffffff',
							'top_bar_link_color' => '#ffffff',
							'top_bar_link_hover_color' => '#363535',
							'header_bg_color' => '#ffffff',
							'header_text_color' => '#333333',
							'header_link_color' => '#4a454b',
							'header_link_hover_color' => '#f23f5f'
                        )
**top_bar_border_btm_color** was not defined anywhere in my configuration. So i referencing a preset for non-existing field. That was causing the issue.

**Comment by kprovance** [comment]
That would do it.  I'll have to add something in the documentation that an existing preset is required for preset to work properly.

**Comment by swirltheme** [comment]
Problem re-occured. Actual issue is bit different.
Issue is when you have used preset value for some fields and you try to change the field value and select field again then it loses the value.
For example. Here is example from your example codes.
array(
                'id'         => 'opt-presets',
                'type'       => 'image_select',
                'presets'    => true,
                'full_width' => true,
                'title'      => __( 'Preset', 'swirl' ),
                'subtitle'   => __( 'This allows you to set a json string or array to override multiple preferences in your theme.', 'swirl' ),
                'default'    => 0,
                'desc'       => __( 'This allows you to set a json string or array to override multiple preferences in your theme.', 'swirl' ),
                'options'    => array(
                    '1' => array(
                        'alt'     => 'Preset 1',
                        'img'     => ReduxFramework::$_url . '../sample/presets/preset1.png',
                        'presets' => array(
                            'switch-on'     => 1,
                            'switch-off'    => 1,
                            'switch-parent' => 1
                        )
                    ),
                    '2' => array(
                        'alt'     => 'Preset 2',
                        'img'     => ReduxFramework::$_url . '../sample/presets/preset2.png',
                        'presets' => '{"opt-slider-label":"1", "opt-slider-text":"10"}'
                    ),
                ),
            )

And field named switch-on has following code.
 array(
                'id'       => 'switch-on',
                'type'     => 'switch',
                'title'    => __( 'Switch On', 'swirl' ),
                'subtitle' => __( 'Look, it\'s on!', 'swirl' ),
                'default'  => true,
            )
Now select '**Preset 1**' from from image_select options And then goto '**switch and button set**' and change value of '**switch-on**' Come back to image_select section and click '**Preset 1**' again (OR any other field which could contain '**switch-on**' in its preset) and that is it. It is gone now. It is not selected anymore and it has lost its value.

**Comment by shinedesigners** [comment]
Hi swirltheme,

I am facing the same issue once the preset is set if we change any value it will loose header value and settings.

Did you get any solution on this, if so please let us know.

Thanks in advance.
