### ISSUE TITLE
Uncaught TypeError: a.redux.hideFields is not a function

### ISSUE THREAD

**Issue by adims** [reduxframework/redux-framework#3046]
Reopening- https://github.com/reduxframework/redux-framework/issues/3045

> I believe this was fixed in the latest version of Redux available from this repo. Please update to that version. 

The issue is still there. As mentioned in previous issue, WordPress, ReduX Framework are all on updated version. You probably missed the image to check the versions on console.

Once more the versions used are :
Redux version is 3.6.0.7
Jquery is jQuery v1.12.4 
Wordpress version 4.5.3

**Comment by kprovance** [comment]
No, I didn't.  But you must have missed the part where I asked for a support URL.  Required now.  Please provide one.

**Comment by kprovance** [comment]
ALso, when reporting JS errors (also poined out in the contributing link I sent), dev_mode MUST, MUST, MUST be set to true, otherwise the JS is minimized and I have no way to debug it.

**Comment by adims** [comment]
My Bad,I skipped the instructions.
I followed it now and have the following details (If it is still incomplete let me know)
http://support.redux.io/?id=Ze0vExuWLmw%2F8UYh0Q8meLs%2BWlUT3FrpmcA1xqhULmS3XcSjH2m3JSPf9yO8mx9HOCyJsTmeqbF7bxAQHgrpyQ%3D%3D

Copy Paste from Console (google chrome):

JQMIGRATE: Migrate is installed, version 1.4.1
redux.min.js?ver=3.6.0.7:1 Uncaught TypeError: a.redux.hideFields is not a function(anonymous function) @ redux.min.js?ver=3.6.0.7:1i @ load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,utils,plupload&ver=4.5.3:2add @ load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,utils,plupload&ver=4.5.3:2n.fn.ready @ load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,utils,plupload&ver=4.5.3:2(anonymous function) @ redux.min.js?ver=3.6.0.7:1(anonymous function) @ redux.min.js?ver=3.6.0.7:2

**Comment by kprovance** [comment]
Seriously?  Did you skip the post right above yours?

<blockquote>
ALso, when reporting JS errors (also pointed out in the contributing link I sent), dev_mode MUST, MUST, MUST be set to true, otherwise the JS is minimized and I have no way to debug it.
</blockquote>

I cannot debug a javascript file with one line of minimized code.  Can't do it.  I looked in the redux.min.js file.  That function exists.  Please turn dev_mode on by setting it to true and resend the error message.  Thanks.

**Comment by adims** [comment]
I turned the dev_mode to true and now receiving HTTP ERROR 500, working on it and will update the issue.

**Comment by adims** [comment]
Dev_mode= true

redux.js?ver=3.6.0.7.1468320753:31 Uncaught TypeError: $.redux.hideFields is not a function(anonymous function) @ redux.js?ver=3.6.0.7.1468320753:31i @ load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,utils,plupload&ver=4.5.3:2add @ load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,utils,plupload&ver=4.5.3:2n.fn.ready @ load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,utils,plupload&ver=4.5.3:2(anonymous function) @ redux.js?ver=3.6.0.7.1468320753:8(anonymous function) @ redux.js?ver=3.6.0.7.1468320753:1510

**Comment by kprovance** [comment]
Never mind, I didn't see it posted earlier.  My bad.

**Comment by adims** [comment]
Damn, you google.
I just uncommented async for javascript codes and it starts working. 
Its my theme and was not not working on local even.

Thanks.

**Comment by kprovance** [comment]
Yup, there it is.  Went through that a few months ago.  The short version is this; if you load your JS in the footer, async isn't ready needed.  It's more for header loaded script tags.
