### ISSUE TITLE
Do You Have Full Packages?

### ISSUE THREAD

**Issue by zakmustapha** [reduxframework/redux-framework#3047]
Don't you have a membership that I can pay? Or do I have to purchase extentions on their own?

I recently purchased a theme thinking that these extensions came with it. But, that's okay. I didn't mind paying more for extensions. However, I didn't find an option where I could purchase all the extensions in bulk. Buying them seperate is crazy expensive and also time consuming. 

Please let me know where I can order all the extensions in bulk.

Thank you.

**Comment by kprovance** [comment]
I'm sure something can be worked out, although I don't understand why you would buy  a theme thinking extensions came with it?  Even if that were the case, for you to use them legally in your own work would require your own license, not someone elses.  Now, if you're a theme users, buying extensions won't do a thing for you, they're tools for theme developers, and I can;t quite figure out which you are.  ;-)

**Comment by zakmustapha** [comment]
Sorry, it was a misunderstanding on my behalf. It's solved now. Thanks.
