### ISSUE TITLE
Subsection css class not used

### ISSUE THREAD

**Issue by vlapo** [reduxframework/redux-framework#3048]
Hi, 

I am creating redux extension and want change css classes of sections. I have problem with subsections and property css that not used.

I think problem is here
https://github.com/reduxframework/redux-framework/blob/master/ReduxCore/framework.php#L3232

There is ```$section[ $nextK ]['class']```. I think it is not exist and right formulation is ```$sections[ $nextK ]['class']```. Same issue in next line where is used ```$section[ $nextK ]['class']```.

**Comment by kprovance** [comment]
All extension issues go here:  https://github.com/reduxframework/redux-extensions

**Comment by vlapo** [comment]
Did you read my description? It is issue in redux core. I just find it during developing extension.

Same issue by using ```Redux::setSection``` and setup ```'subsection' => true```, and ```'class'``` property.

**Comment by kprovance** [comment]
I did, but your developing an extension, and extensions go there.  And on the subject of not reading:  https://github.com/reduxframework/redux-framework/blob/master/CONTRIBUTING.md.  You provided absolutely no information about versions, configs, anything.  For all I know you could be using an outdated version of Redux.  I have to be able to recreate what you are claiming, and I can;t do that based on you telling me something isn't working and code you believe it as fault.  It could be, but I have to make that determination, and I need the information asked for in our support guidelines.

**Comment by vlapo** [comment]
Sure because I paste bin link to code I use outdated redux, really good deduction ;) 

So here is code from redux setup without extension. 
 ```php
Redux::setSection($opt_name, array(
    'id' => 'vvv-general-main-tab',
    'title' => __('General', 'vvv'),
    'class' => 'i-want-this-class-in-menu',
    'icon' => 't4p-icon-appbartools',
        )
);

Redux::setSection($opt_name, array(
    'id' => 'vvv-general-subsec-general-tab',
    'title' => __('General', 'vvv'),
    'subsection' => true,
    'class' => 'i-want-this-class-in-menu',
    'fields' => array(
        array(
            'desc' => __('assdasdasd', 'vvv'),
            'id' => 'demo_data',
        ),
    ),
  )
);
```

And here is result. As you see ```i-want-this-class-in-menu``` css class is only in ```li#1_section_group_li``` and not in ```li#2_section_group_li```. Is this correct??

```html
<li id="1_section_group_li" class="redux-group-tab-link-li i-want-this-class-in-menu hasSubSections empty_section activeChild">
    <a href="javascript:void(0);" id="1_section_group_li_a" class="redux-group-tab-link-a" data-key="1" data-rel="1"><span class="extraIconSubsections"><i class="el el-chevron-down">&nbsp;</i></span><i class="t4p-icon-appbartools"></i> <span class="group_title">General</span></a>
            <ul id="1_section_group_li_subsections" class="subsection" style="display: block;">
                    <li id="2_section_group_li" class="redux-group-tab-link-li active">
                            <a href="javascript:void(0);" id="2_section_group_li_a" class="redux-group-tab-link-a" data-key="2" data-rel="2"><span class="group_title">General</span></a>
                    </li>
            </ul>
</li>
```

Feel free ask any question. I want help not fight. And of course I use the newest version of redux.

**Comment by kprovance** [comment]
You're looking in the tab li for the class.  It's actually ini the div panel that appears for the selected tab, and where it's intended to go.  I see the classname also goes in the tab li, but not for subsections, apparently.  I don;t know if this is by design or not.  Either way, it'll take me a bunch of time I don't really have (unless I'm getting properly paid) to dig into it at present.  If you come up with a fix, please feel free to post it.  :)

**Comment by vlapo** [comment]
I will do RP if you reopen this issue.
