### ISSUE TITLE
Cannot submit to WordPress repository after updating to v3.6.0.1

### ISSUE THREAD

**Issue by champsupertramp** [reduxframework/redux-framework#3052]
Hi,

I'm using ReduxFramework in one of our plugins. After we've updated the framework to the latest version 3.6.0.1, WordPress repository via SVN doesn't accept the committed file `class.redux_sass.php`.

Here's the SVN error log:

```
Commit failed (details follow):
Commit blocked by pre-commit hook (exit code 1) with output:

***********************************
PHP error in:
plugin/tags/1.3.65/admin/core/lib/ReduxFramework/ReduxCore/inc/class.redux_sass.php:

Errors parsing
 plugin/tags/1.3.65/admin/core/lib/ReduxFramework/ReduxCore/inc/class.redux_sass.php

***********************************
If you want to break the lock, use the 'Check For Modifications' dialog or the repository browser.
```

And here's a note from WordPress developers:
```
“Please be careful if you are using 5.3 or 5.4-specific language features, like namespaces, closures, short array or ternary syntaxes, etc. These will break sites running PHP 5.2 (which is a majority of sites).”
```
More details: https://wptavern.com/wordpress-plugin-repository-now-rejects-commits-with-php-errors

Is this a compatibility issue?

Thank you,

**Comment by kprovance** [comment]
That file is no longer in our package.  Not sure why it would be now.  You can safely delete it.  :)
