### ISSUE TITLE
Assets urls wrong when using redux-framework in Avada theme, in a default wordpress installation in openshift

### ISSUE THREAD

**Issue by lalber** [reduxframework/redux-framework#3054]
Didn't know if this was the correct place for opening this issue, but since the Theme Options assets that breaks are *only* the ones from redux-framework, I opened it here.

This happens in a default Wordpress installation in openshift, using their official Wordpress cartridge and uploading Avada Theme 4.0.3. Since I don't know if this is a problem with my installation, a [problem with redux-framework](https://codex.wordpress.org/Determining_Plugin_and_Content_Directories) or *both*...

Don't know if there's something to do with the way openshift's [`wp-config.php`](https://github.com/openshift/wordpress-example/blob/fc26e0e6dff6cc53d52ffb26b1435690120df30a/.openshift/config/wp-config.php) is handled:

```php
// absolute path to the WordPress directory
if ( !defined('ABSPATH') )
  define('ABSPATH', dirname(__FILE__) . '/');

// tell WordPress where the plugins directory really is
if ( !defined('WP_PLUGIN_DIR') && is_link(ABSPATH . '/wp-content/plugins') )
  define('WP_PLUGIN_DIR', realpath(ABSPATH . '/wp-content/plugins'));

// sets up WordPress vars and included files
require_once(ABSPATH . 'wp-settings.php');
```

...fact is this is a correct asset url that it's working from Avada theme:

> https://wordpress-mywebsite.rhcloud.com/wp-content/themes/Avada/assets/admin/js/avada-theme-update.js

and an incorrect:

> https://wordpress-mywebsite.rhcloud.com/wp-content/var/lib/openshift/578d94660c1e66330d000202/app-root/data/themes/Avada/includes/avadaredux/avadaredux-framework/AvadaReduxCore/    inc/fields/button_set/field_button_set.min.js

See how it decided to use the full path of the server, `/var/lib/openshift/578d94660c1e66330d000202/app-root/data/themes` instead of just `themes`. Is it a misconfiguration from openshift or really an issue with redux?

**Comment by kprovance** [comment]
You'll have to take it up with the Avada people, since they butchered our code and turned it into their own.  It's up to them to support it now.  Sorry.

**Comment by lalber** [comment]
No problem. I didn't know they created a fork. At least now I know it's their responsibility and if someone search for this issue on google they know where they need to ask for support.

**Comment by lalber** [comment]
After getting contact with Avada support team, they gave us a solution for our specific problem in openshift, since it uses symbolic links. Basically, you need to add this snippet of code (of course, changing `https://wordpress-mywebsite.rhcloud.com/` to your url):

```php
function theme_enqueue_styles() {
    wp_enqueue_style( 'parent-style', get_template_directory_uri() . '/style.css' );
    wp_enqueue_style( 'child-style', get_stylesheet_directory_uri() . '/style.css', array('parent-style') );
}
add_action( 'wp_enqueue_scripts', 'theme_enqueue_styles' );

function avada_lang_setup() {
        $lang = get_stylesheet_directory() . '/languages';
        load_child_theme_textdomain( 'Avada', $lang );
}

add_filter( 'avadaredux/_url', 'ReduxSymLinkURL', 10 );
function ReduxSymLinkURL(){
    $url = "https://wordpress-mywebsite.rhcloud.com/wp-content/themes/Avada/includes/avadaredux/avadaredux-framework/AvadaReduxCore/";
    return $url;
}
```
To:

- A functions.php file, in a new Avada Child Theme;
- A simple [functionality plugin](http://wpcandy.com/teaches/how-to-create-a-functionality-plugin) with only `functions.php`;
- or just add it to to the functions.php of your in-house plugin if you already have one.

I know this is not related to reduxframework *per se*, but I'm writing it down here since it may be useful for someone. If you came here after googling for this problem and if this snippet doesn't solve it, you should get in touch with Avada support :)

**Comment by kprovance** [comment]
I have to add the caveat here for *anyone* who reads this - since it's become such a problem for us - we do not, repeat *not* support themes that use our framework.  Theme users must *always* contact the theme developer.  If the dev determines there is an issue with our code, they come to us and we get it sorted out.  The reason being is because often time theme devs modify our framework, which Avada has done, and it's completely out of our hands.  Plus, theme devs got the money, we didn't.  ;-)

**Comment by lalber** [comment]
@kprovance I think github has a feature of forbidding additional replies in an issue besides closing it, I think it would be a nice idea to do it here.

**Comment by kprovance** [comment]
Removed all reference to the theme name.  I'm not in the way of giving them free advertising, especially since they not contributed to Redux, or paid for our extensions they are using.
