### ISSUE TITLE
How to remove a section in child theme for specific user roles?

### ISSUE THREAD

**Issue by sepano** [reduxframework/redux-framework#3057]
Hi
I bought a theme that uses Redux
I need to hide some sections for shopmanager through child theme's functions.php
But it seems that there is not any method to remove/alter a section. I tried to add new sections in child theme but cant hide sections.

is there any way to hide a specific section in child theme for specific user roles?

**Comment by kprovance** [comment]
You'd need to use removeSection via the Redux API:  https://docs.reduxframework.com/core/redux-api/

For user roles, set up conditional statements using current_user_can().

Understand, modifications for child themes are typically the theme author's responsibility.  I have NO idea how the theme or the author implements Redux.  For us to write that code for you would fall under premium services, a few hours worth at least.
