### ISSUE TITLE
Customizer Issue

### ISSUE THREAD

**Issue by kajdzo** [reduxframework/redux-framework#3058]
Hello guys, I've been trying to resolve issue with current answers you guys already posted but can't find any solution. 
I'm using 

WP Version 4.5.3,
ReduxFramework version 3.6.0.5 
dev_mode => true,
Redux is embedded

I'm building new theme and I have enabled composer in config file but can't make it work. It shows all fields from theme options but can't make any changes with customizer, it doesn't detect any change I make within options in customizer. 

Any suggestions ?
Thanks in advance.

**Comment by kprovance** [comment]
Customizer issues got here, please:  https://github.com/reduxframework/customizer-integration

Thanks.
