### ISSUE TITLE
Google Font Not Loading In Front End

### ISSUE THREAD

**Issue by ethan97** [reduxframework/redux-framework#3060]
Hi,

I'm using Redux version : 3.6.0.2 with WP version : 4.5.3

I have set google_api_key field with my google api key. ( Checked that key is working fine )
I have set async_typography field to false.
I have set disable_google_fonts_link to false.
Dev_mode is enabled.
There's no javascript error.
Using Redux as a plugin.

This is how my field array look like : 

array(
                'id'                     => 'w-body-text-typograpy',
                'type'                 => 'typography',
                'title'                  => __( 'Body Text Typography', 'w-studio' ),
                'compiler'           => array( 'body p, .count, body a, body small' ),
                'desc'                 => __( '', 'w-studio' ),
                'subtitle'            => __( 'Set body typography', 'w-studio' ),
                'google'             => true,
                'all_styles'          => true,
                'font-backup'    => true,
                'letter-spacing'  => true,
                'word-spacing'  => true,
                'text-transform' => true,
                'units'       =>'px',
                'default'   => array(
                    'google'                => true,
                    'color'       		=> '#666',
                    'font-size'   		=> '13px',
                    'font-family' 		=> "'Raleway',sans-serif",
                    'font-weight' 	=> 'Normal',
                    'line-height' 		=> '20px',
                    'letter-spacing'     => '0',
                    'word-spacing'	=> '0',
                ),
            ),

I checked this https://github.com/ReduxFramework/redux-framework/issues/1609 issue as well. Still nothing good for me. 

Google Font not loading in front end yet.

Is there any fault in my process??

**Comment by kprovance** [comment]
Probably?  My theme uses typography and I don;t experience anything like this.  But, you didn't read our support guidelines as there is no support URL included.  And I'm not sure what 'not loading on the front end' means?  What's not loading, specifically?  What does your front end code look like?

https://github.com/reduxframework/redux-framework/blob/master/CONTRIBUTING.md

**Comment by ethan97** [comment]
Sorry.
I've upgraded redux to latest version 3.6.0.11

This is my support url : http://support.redux.io/?id=xmnhdIeekdT6fSRJzeUu11lWbgIIn2XcmBSxcP9SmbDy%2ByRTNL6lZzkYgUXd9LUbOrZ34q88KMV4l%2FuaJ8ik2w%3D%3D

I am a developer.

As per redux, google font css was to be included like below.

<link rel='stylesheet' id='redux-google-fonts-css'  href='http://fonts.googleapis.com/css?family=Abel%3A400&#038;ver=3.9.2' type='text/css' media='all' />

But this is not happening in my theme. I mean there is no <link> element for the selected font in my theme.

Thanks

**Comment by kprovance** [comment]
Okay, unfortunately, I still don;t understand what you mean.  'included like below'.  Below what?

**Comment by ethan97** [comment]
Updated my comment. Sorry for the inconvenience.

**Comment by kprovance** [comment]
I ran your config, and this is what appeared on the front end:

```css
<link rel="stylesheet" id="redux-google-fonts-w_studio-css" href="http://fonts.googleapis.com/css?family=%27Raleway%27%2Csans-serif%3ANormal&amp;ver=1469695063" type="text/css" media="all">
```
The Redux code is functioning as expected.  I can only guess it's a local issue.

**Comment by ethan97** [comment]
solved. Thanks for the support.
