### ISSUE TITLE
Dynamic section and fields

### ISSUE THREAD

**Issue by santoshnextgeni** [reduxframework/redux-framework#3061]
Hi,

Is there any way to create dynamic section Redux::setSection() and section fields from wordpress admin panel. when I want to create new section then should go in coding and write the code like that,

Redux::setSection( $opt_name, array(
        'title'  => __( 'Header Settings', '' ),
        'id'     => 'header',
        'icon'   => 'el el-home',
        'fields' => array(
            array(
                'id'       => 'site-title',
                'type'     => 'text',
                'title'    => __( 'Website Title', '' )
            ),
     )
        )
    ) );

any way to create this type of things from wordpress admin.

**Comment by kprovance** [comment]
I'm sorry, but I don;t understand the question.  Yes, sections can be added dynamically, but 'from the wordpress admin' is vague.  That's a page, not a place where code may be entered.

**Comment by kprovance** [comment]
Closing due to lack of reply.
