### ISSUE TITLE
Can you make field dependent using multiple properties?

### ISSUE THREAD

**Issue by swirltheme** [reduxframework/redux-framework#3062]
How can we use dependency field in such a way that a it is dependent on multiple options.
For example,
array(
				'type' => 'checkbox',
				"class" => "",
				"heading" => __("Custom Styling",'lang'),
				"param_name" => "custom_styling",
				'value' => array(  'Yes'  => true ),
				"description" => __("Use custom styling.",'lang')
			),
array(
				'type' => 'checkbox',
				"class" => "",
				"heading" => __("3D Button",'lang'),
				"param_name" => "btn_3d",
				'value' => array(  'Yes'  => true ),
				"description" => __("Display 3D button.",'lang')
			),
array(
				"type" => "colorpicker",
				"class" => "",
				"heading" => __("Link button border color",'lang'),
				"param_name" => "link_btn_border_color",
				"value" => '',
				"description" => __("Select Link button border color. Leave Blank to use default.",'lang'),
				'dependency' =>  array( 'element' => 'custom_styling', 'value' => array('1'))
			),

In this code "link_btn_border_color" is dependent  on "custom_styling" only BUT i want to add one more dependency to it such that is is dependent on multiple things i.e., "btn_3d" AND "custom_styling"

**Comment by kprovance** [comment]
See out docs for the 'required' argument:  https://docs.reduxframework.com/core/the-basics/required/

**Comment by swirltheme** [comment]
LOL. I have gone mad.
Posted visual composer problem in redux.
Sorry, My mistake.

**Comment by kprovance** [comment]
Whoops!  Okay, I see it now, the in the array code.  I missed it too.
