### ISSUE TITLE
Required doesn't work anymore with latest update

### ISSUE THREAD

**Issue by udarts** [reduxframework/redux-framework#3064]
I am using the latest version of redux framework (love it btw).
Not using the plugin, but integrated it into the custom theme I am building.
I noticed that since the last update: v3.6.0.11, the required parameter is not working anymore, it did before.

Did something change?

**Comment by kprovance** [comment]
Nope.  It works fine.  I use it in my theme.

**Comment by udarts** [comment]
Yeah, now I see why, I red somewhere to use equal instead of =, after changing back to = works again.
Have set it to:

'required'      => array('show-homepage-profiles','=','1'),

**Comment by udarts** [comment]
One questions though, does it work with accordion, it doesn't seem to.

**Comment by kprovance** [comment]
The Accordion does not have a required argument.

**Comment by udarts** [comment]
Why is that? Would be a good idea to have.

**Comment by kprovance** [comment]
I never included it when I wrote it originally?  I'm sure it would  but it seems maybe one copy every six months.  But it's a lot of work, and it's a time/cost issue now.
