### ISSUE TITLE
Redux Update on Wordpress.org

### ISSUE THREAD

**Issue by yerooleopard** [reduxframework/redux-framework#3065]
Hello ReduxTeam,

Can we expect any updates of Redux Framework on [wordpress.org](https://wordpress.org/plugins/redux-framework/) or should we do upgrade manually? Last update is from 3 months ago - version 3.6.0.2 , here we got 3.6.0.11.

Thanks for awesome job with framework,
Adrian

**Comment by kprovance** [comment]
I've been asking Dovy to do it for a while now.  I'll ask again.

**Comment by dovy** [comment]
I'll push it this week. Want to check 4.6 before I do to make sure nothing is broken.  ;)

**Comment by yerooleopard** [comment]
Ok, great to hear. Looking forward to it.
Thanks.

**Comment by jilani53** [comment]
how to stop showing this notice
http://envato.d.pr/11sMy/3Ynsj56E

**Comment by kprovance** [comment]
Only @dovy can say.

**Comment by jilani53** [comment]
dovy please help me. My theme rejected some redux reason

**Comment by kprovance** [comment]
You'll have to either install Redxu as a plugin via TGM, or purchase our ad remover extension:  https://reduxframework.com/extension/ad-remover/
