### ISSUE TITLE
Redux is not giving out the saved option.

### ISSUE THREAD

**Issue by hamzadhamiya** [reduxframework/redux-framework#3067]
I do not know what the problem is. I downloaded redux from wordpress.org then added in my theme files. Added following code in my functions.php
```
<?php
if(is_admin()){
	require_once(get_template_directory().'/core/admin/redux-framework/ReduxCore/framework.php');
	require_once(get_template_directory().'/core/admin/redux-framework/sample/config.php');
}
?>
```
I created a copy of sample-config and renamed into config.php and it is working fine till now. Options and all the display is good. I changed the $opt_name ='redux_demo' to $opt_name ='hamza'. Then in my header.php I added the following code:
```
	<?php global $hamza; ?>
<h2><?php echo $hamza['boom']; ?></h2>
```
boom is already present in my config.php as:
  ```
  Redux::setSection( $opt_name,array(
    'title' =>'Head',
    'fields' => array(
        array(
            'id' => 'boom',
            'type' => 'text',
            'title' => 'For test'
        )
    )
));
```
I know it should work fine but header.php do not show the saved text.

Edit: Also installed redux plugin and activated it but not working.

**Comment by kprovance** [comment]
It's in your config somewhere.  But, you didn;t read our posting guidelins and submit the correct information.  Please read (and I do mean READ it) and post back the information we require:  https://github.com/reduxframework/redux-framework/blob/master/CONTRIBUTING.md
