### ISSUE TITLE
PHP 7 Support

### ISSUE THREAD

**Issue by rhbkweb** [reduxframework/redux-framework#3070]
Hi,

It's the first time using redux-framework and it's great! But my server is using PHP 7 (v7.0.9) and when running the WP Engine PHP Compatibility Checker, it shows 1 Warning + 5 Errors on Redux Framework as i leave bellow.

So is PHP 7 support planned for a near future? Thanks

---------------------------------------------------------------------------------------------
FILE: /var/www/domain.com/htdocs/wp-content/plugins/redux-framework/ReduxCore/inc/browser.php
---------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
---------------------------------------------------------------------------------------------
 1210 | ERROR | Deprecated PHP4 style constructor are not supported since PHP7
---------------------------------------------------------------------------------------------
FILE: /var/www/domain.com/htdocs/wp-content/plugins/redux-framework/ReduxCore/inc/scssphp/scss.inc.php
---------------------------------------------------------------------------------------------------------------
FOUND 4 ERRORS AFFECTING 4 LINES
---------------------------------------------------------------------------------------------------------------
 3386 | ERROR | 'string' is a reserved keyword introduced in PHP version 7.0 and cannot be invoked as a function (T_STRING)
 3584 | ERROR | Function name, class name, namespace name or constant name can not be reserved keyword 'string' (since version 7.0)
 3697 | ERROR | 'string' is a reserved keyword introduced in PHP version 7.0 and cannot be invoked as a function (T_STRING)
 3941 | ERROR | 'string' is a reserved keyword introduced in PHP version 7.0 and cannot be invoked as a function (T_STRING)
----------------------------------------------------------------------------------------------------------------

**Comment by kprovance** [comment]
This has been addressed in the version from our repo here.  And the scss stuff was removed a LONG time ago.  Don't know why it's still in the wp.org version.  You can safely delete the folder.

**Comment by rhbkweb** [comment]
Hi @kprovance 

Thanks for the information. Im a "newbie" so may i please ask you what folder should i delete?

Thanks for your help.

**Comment by rhbkweb** [comment]
Can someone please help me on this? What do i need to do in order to have on my website the latest Redux-Framework that resolved the PHP 7 compatibility?

Also why is in wp.org still the old version?

**Comment by kprovance** [comment]
Update to the version from this repository.  I don;t know why the wp.org version contains all the old legacy stuff.  @Dovy is supposed to update it at some point.  No ETA when.

**Comment by rhbkweb** [comment]
@kprovance 

I just checked and my website is using the v.3.6.0.2. 

So just to ensure i properly understand, i just have to download the new version 3.6.0.11 available at: https://github.com/reduxframework/redux-framework/tree/master/ReduxCore and replace my current files?

Or should i download a different folder / version?

Once again thanks for the help!

**Comment by kprovance** [comment]
Yes.  Delete the old version and replace it with this one.

**Comment by rhbkweb** [comment]
@kprovance 

I will replace current "old" v3.6.0.2 with the new v3.6.11.

Once again thanks for all your help!
