### ISSUE TITLE
Problem with the Docs.

### ISSUE THREAD

**Issue by davidp98** [reduxframework/redux-framework#3071]
Hi Redux team, I don't know if this is the correct place for this but in the Documentation, exactly in the Slides section a comma is missing, this can cause an php error if the example is used as source (an unnecessary problem for less experienced users). 

Please see the Section 'Example Declaration':

`$fields = array(
    'id'          => 'opt-slides',
    'type'        => 'slides',
    'title'       => __('Slides Options', 'redux-framework-demo'),
    'subtitle'    => __('Unlimited slides with drag and drop sortings.', 'redux-framework-demo'),
    'desc'        => __('This field will store all slides values into a multidimensional array to use into a foreach loop.', 'redux-framework-demo') /*missing comma*/
    'placeholder' => array(
        'title'           => __('This is a title', 'redux-framework-demo'),
        'description'     => __('Description Here', 'redux-framework-demo'),
        'url'             => __('Give us a link!', 'redux-framework-demo'),
    ),
),`

Thanks for your creation,

Best, 

David

**Comment by kprovance** [comment]
ill get on it.  Thanks.
