### ISSUE TITLE
Wordpress Redux Framework & Azure WebApps

### ISSUE THREAD

**Issue by selycha** [reduxframework/redux-framework#3072]
Hi all,

we are using the simplemag theme on our wordpress site : www.interez.sk, which uses the Redux Framework. The site was recently migrated from an Apache server, where it worked without issues to a Microsoft Azure WebApp, which is a asp.net IIS solution. 
Unfortunately even on the best performance servers the site is slow and when we checked the plugins for performance and speed, we discovered that Redux is causing the problems - slow page load, slow publishing / editing of post, internal server errors when updating posts, losing database connection...

Is there any solution to this / have you come around a similar issue? Since the whole website is based on Redux, we need it.

Thanks I appreciate any advice and help.

Bests

**Comment by kprovance** [comment]
Sorry, but we do not support users of themes that use Redux.  I just went thropugh this with someone else.  You MUST contact the theme author for support.  THEY must debug your site to determine if there is an issue.  You paid them, not us.  If THEY determine the issue.  Sorry.

**Comment by dovy** [comment]
As @kprovance said. There are so many things developers can do with our framework that makes it seem like it's our problem. You need to bring it up with them. We're not trying to give you the run around, we're just trying to help you resolve the issue quicker.

**Comment by selycha** [comment]
Okay, thanks anyway
