### ISSUE TITLE
Plugin is causing a fatal error on my system

### ISSUE THREAD

**Issue by GabrielHenry** [reduxframework/redux-framework#3074]
I checked the case thoroughly and noticed that the processes running on the server are taking up all of the available memory:

Code:
root@c20643 [~]# free -m
total used free shared buffers cached
Mem: 2048 2048 0 0 0 667
-/+ buffers/cache: 1380 667
Swap: 0 0 0

I used the Linux top tool to determine which process is taking most of the memory and you may find it below:

Code:
PID USER PR NI VIRT RES SHR S %CPU %MEM TIME+ COMMAND
12991 mysql 20 0 2396m 573m 0 S 1.5 28.0 21:54.19 mysqld

Afterwards I went ahead and checked the process list of the MySQL service and it appears that it has numerous sleeping and slow queries:

Code:
+--------+----------------+-----------+----------------+---------+------+-------+------------------+-----------+---------------+
| Id | User | Host | db | Command | Time | State | Info | Rows_sent | Rows_examined |
+--------+----------------+-----------+----------------+---------+------+-------+------------------+-----------+---------------+
| 118918 | lojacari_wp587 | localhost | lojacari_wp587 | Sleep | 50 | | | 0 | 0 |
| 118919 | lojacari_wp587 | localhost | lojacari_wp587 | Sleep | 50 | | | 0 | 0 |
| 118920 | lojacari_wp587 | localhost | lojacari_wp587 | Sleep | 50 | | | 0 | 0 |
| 118926 | lojacari_wp587 | localhost | lojacari_wp587 | Sleep | 50 | | | 0 | 0 |
| 118928 | lojacari_wp587 | localhost | lojacari_wp587 | Sleep | 50 | | | 0 | 0 |
| 118929 | lojacari_wp587 | localhost | lojacari_wp587 | Sleep | 49 | | | 0 | 0 |
| 118930 | lojacari_wp587 | localhost | lojacari_wp587 | Sleep | 49 | | | 0 | 0 |
| 118931 | lojacari_wp587 | localhost | lojacari_wp587 | Sleep | 49 | | | 0 | 0 |
| 118932 | lojacari_wp587 | localhost | lojacari_wp587 | Sleep | 49 | | | 0 | 0 |
| 118933 | lojacari_wp587 | localhost | lojacari_wp587 | Sleep | 49 | | | 0 | 0 |
| 118934 | lojacari_wp587 | localhost | lojacari_wp587 | Sleep | 49 | | | 0 | 0 |
| 118937 | lojacari_wp587 | localhost | lojacari_wp587 | Sleep | 48 | | | 0 | 0 |
| 118938 | lojacari_wp587 | localhost | lojacari_wp587 | Sleep | 48 | | | 0 | 0 |
| 118939 | lojacari_wp587 | localhost | lojacari_wp587 | Sleep | 48 | | | 0 | 0 |
| 118940 | lojacari_wp587 | localhost | lojacari_wp587 | Sleep | 48 | | | 0 | 0 |
| 118941 | lojacari_wp587 | localhost | lojacari_wp587 | Sleep | 48 | | | 0 | 0 |
| 118942 | lojacari_wp587 | localhost | lojacari_wp587 | Sleep | 48 | | | 0 | 0 |
| 118943 | lojacari_wp587 | localhost | lojacari_wp587 | Sleep | 47 | | | 0 | 0 |
| 118944 | lojacari_wp587 | localhost | lojacari_wp587 | Sleep | 47 | | | 0 | 0 |
| 118945 | lojacari_wp587 | localhost | lojacari_wp587 | Sleep | 47 | | | 0 | 0 |
| 118946 | lojacari_wp587 | localhost | lojacari_wp587 | Sleep | 47 | | | 0 | 0 |
| 118947 | lojacari_wp587 | localhost | lojacari_wp587 | Sleep | 47 | | | 0 | 0 |
| 118948 | lojacari_wp587 | localhost | lojacari_wp587 | Sleep | 2 | | | 0 | 0 |
| 118950 | root | localhost | | Query | 2 | init | show processlist | 0 | 0 |
+--------+----------------+-----------+----------------+---------+------+-------+------------------+-----------+---------------+

I thoroughly reviewed the case and it seems that the MySQL processes triggered by the website are consuming all of the server's memory. Usually a query that runs for more than one second is considered as a slow one and on your database there are queries running for 10 seconds:

Code:
=== TOP 10 of 99 (total) Slow Queries for the past 24 hours ==========
1. Executed 6h 40m 52s ago for 309.9712 sec on Database --> Unknown (NOT FOUND / DELETED)
Date: 2016-08-01 23:22:56 Query_time: 309.971200 Rows_examined: 711: Rows_sent 328 Lock_time: 4.899811
# Schema: lojacari_wp587 Last_errno: 0 Killed: 0 SELECT option_name, option_value FROM wp_options WHERE autoload = 'yes';
------------------------------------------------------------------------------------------------------
2. Executed 6h 40m 52s ago for 307.976646 sec on Database --> Unknown (NOT FOUND / DELETED)
Date: 2016-08-01 23:22:56 Query_time: 307.976646 Rows_examined: 18: Rows_sent 0 Lock_time: 4.199871
# Schema: lojacari_wp587 Last_errno: 0 Killed: 0 SELECT * FROM wp_posts LEFT JOIN wp_postmeta ON ( wp_posts.ID = wp_postmeta.post_id ) WHERE (post_type = 'page' AND post_status = 'publish') AND wp_postmeta.meta_key = '_wp_page_template' AND wp_postmeta.meta_value = 'et-registration.php' ORDER BY wp_posts.post_title ASC;
---------------------------------------------------------------------------------------------------
3. Executed 6h 40m 52s ago for 307.976244 sec on Database --> Unknown (NOT FOUND / DELETED)
Date: 2016-08-01 23:22:56 Query_time: 307.976244 Rows_examined: 18: Rows_sent 0 Lock_time: 4.199885
# Schema: lojacari_wp587 Last_errno: 0 Killed: 0 SELECT * FROM wp_posts LEFT JOIN wp_postmeta ON ( wp_posts.ID = wp_postmeta.post_id ) WHERE (post_type = 'page' AND post_status = 'publish') AND wp_postmeta.meta_key = '_wp_page_template' AND wp_postmeta.meta_value = 'et-registration.php' ORDER BY wp_posts.post_title ASC;
---------------------------------------------------------------------------------------------------
4. Executed 6h 40m 52s ago for 307.970417 sec on Database --> Unknown (NOT FOUND / DELETED)
Date: 2016-08-01 23:22:56 Query_time: 307.970417 Rows_examined: 18: Rows_sent 0 Lock_time: 4.199890
# Schema: lojacari_wp587 Last_errno: 0 Killed: 0 SELECT * FROM wp_posts LEFT JOIN wp_postmeta ON ( wp_posts.ID = wp_postmeta.post_id ) WHERE (post_type = 'page' AND post_status = 'publish') AND wp_postmeta.meta_key = '_wp_page_template' AND wp_postmeta.meta_value = 'et-registration.php' ORDER BY wp_posts.post_title ASC;
---------------------------------------------------------------------------------------------------
5. Executed 6h 40m 52s ago for 301.977238 sec on Database --> Unknown (NOT FOUND / DELETED)
Date: 2016-08-01 23:22:56 Query_time: 301.977238 Rows_examined: 4: Rows_sent 4 Lock_time: 36.600695
# Schema: lojacari_wp587 Last_errno: 0 Killed: 0 SHOW FULL COLUMNS FROM `wp_options`;
---------------------------------------------------------------------------------------------------
6. Executed 6h 40m 52s ago for 256.475898 sec on Database --> Unknown (NOT FOUND / DELETED)
Date: 2016-08-01 23:22:56 Query_time: 256.475898 Rows_examined: 0: Rows_sent 0 Lock_time: 60.699606
# Schema: lojacari_wp587 Last_errno: 0 Killed: 0 SELECT option_value FROM wp_options WHERE option_name = 'revSliderAsTheme' LIMIT 1;
---------------------------------------------------------------------------------------------------
7. Executed 6h 40m 52s ago for 256.475892 sec on Database --> Unknown (NOT FOUND / DELETED)
Date: 2016-08-01 23:22:56 Query_time: 256.475892 Rows_examined: 0: Rows_sent 0 Lock_time: 60.699617
# Schema: lojacari_wp587 Last_errno: 0 Killed: 0 SELECT option_value FROM wp_options WHERE option_name = 'revSliderAsTheme' LIMIT 1;
---------------------------------------------------------------------------------------------------
8. Executed 3h 38m 29s ago for 168.94717 sec on Database --> Unknown (NOT FOUND / DELETED)
Date: 2016-08-02 02:25:19 Query_time: 168.947170 Rows_examined: 1: Rows_sent 1 Lock_time: 101.129655
# Schema: lojacari_wp587 Last_errno: 0 Killed: 0 SELECT option_value FROM wp_options WHERE option_name = '_transient_timeout__redux_activation_redirect' LIMIT 1;
----------------------------------------------------------------------------------------------------
9. Executed 3h 38m 29s ago for 168.947101 sec on Database --> Unknown (NOT FOUND / DELETED)
Date: 2016-08-02 02:25:19 Query_time: 168.947101 Rows_examined: 1: Rows_sent 1 Lock_time: 101.129820
# Schema: lojacari_wp587 Last_errno: 0 Killed: 0 SELECT option_value FROM wp_options WHERE option_name = '_transient_timeout__redux_activation_redirect' LIMIT 1;
----------------------------------------------------------------------------------------------------
10. Executed 3h 13s ago for 167.099265 sec on Database --> lojacari_wp587
Date: 2016-08-02 03:03:35 Query_time: 167.099265 Rows_examined: 5: Rows_sent 5 Lock_time: 20.999604
# Schema: lojacari_wp587 Last_errno: 0 Killed: 0 SELECT tr.object_id FROM wp_term_relationships AS tr INNER JOIN wp_term_taxonomy AS tt ON tr.term_taxonomy_id = tt.term_taxonomy_id WHERE tt.taxonomy IN ('nav_menu') AND tt.term_id IN ('32') ORDER BY tr.object_id ASC;
---------------------------------------------------------------------------------------------------

I would strongly recommend that you make sure to eliminate all of the MySQL slow queries to resolve the issue. If you are not certain how to do that I would suggest contacting a professional developer to assist you. For your convenience I copied the whole slow log in the file below:

Code:
root@c20643 [/home/lojacari/public_html]# ll mysql-slow.log.txt
-rw-r--r-- 1 lojacari lojacari 1195819 Aug 2 06:14 mysql-slow.log.tx

**Comment by kprovance** [comment]
https://github.com/reduxframework/redux-framework/blob/master/CONTRIBUTING.md

**Comment by GabrielHenry** [comment]
theme/plugin that uses Redux

**Comment by kprovance** [comment]
Okay, that is not what I asked for via those guidelines.  If you won't provide the necessary information, then Ill take your suggestion under advisement and close the ticket.  Thanks for writing.
