### ISSUE TITLE
Visual Composer - NO LICENSES FOUND

### ISSUE THREAD

**Issue by emjheneghan** [reduxframework/redux-framework#3076]
I tried to install the Visual Composer Plug in and I got redirected to the following page: It seems that you do not have any valid license for Visual Composer. What does it mean? It may be so that you got Visual Composer by purchasing WordPress theme which does not grant you with direct license for Visual Composer. Why do I need direct license? Direct product license unlocks several benefits:

Can someone please assit?

**Comment by kprovance** [comment]
Wrong forum.  We are Redux Framework, NOT WPBakery.
