### ISSUE TITLE
Ace editor not working?

### ISSUE THREAD

**Issue by oknoorap** [reduxframework/redux-framework#3078]
![https://i.gyazo.com/6cc23c5d4656ad55a5e22f6904314003.png](https://i.gyazo.com/6cc23c5d4656ad55a5e22f6904314003.png)

**Comment by kprovance** [comment]
Um.  This is just a screenshot?  Please go back and review our support guidelines.  I can't help with just a screenshot.

**Comment by oknoorap** [comment]
sorry just found it, my bad, I set 'use_cdn'  to false. So ace editor can't render it self.
But if I set value as true, theme-check will throw an error? any solution?
