### ISSUE TITLE
Redux Framework with saas variables: How to setup dynamic color scheme?

### ISSUE THREAD

**Issue by Ascii1point0** [reduxframework/redux-framework#3079]
I am using redux framework and sass to create my theme. I have defined few color variables in sass which are used on the front end to design(or give ) color scheme to my theme. Lets say i have defined 3 variables as below: what i want to do is that i want to give a user the option to choose whatever three colors at back end as primary secondary and so on and apply them at front end. To achieve that obviously i have to change the values inside the sass variables. i have tried to use php code inside the sass file but it does not allows it. please guide me how can i achieve the objective.

```
$primary-color:#000000;
$secondary-color:#333333
#post-second-color:#f1f1f1;
```

**Comment by kprovance** [comment]
This falls under premium support as it is not an issue with Redux itself, or a Redux bug.  More info:  https://github.com/reduxframework/redux-framework/blob/master/CONTRIBUTING.md
