### ISSUE TITLE
integration with template MediaCenter

### ISSUE THREAD

**Issue by EvGeniu5** [reduxframework/redux-framework#3080]
Hello, the problem with your plugin Redux Framework. On the website Sotit.ru incorrectly loaded product images, they expand and then taper to the standard, too bad it looks on the mobile version of the site (attachments 1.1 and 1.2), goods which were created before this problem work fine (attached two images: 2.1 - product code which is loaded correctly, the 2.2 - code of the goods with which the goods are loaded with bugs). If you turn off your plugin everything works correctly. Can you please tell me what to do.
![1 1](https://cloud.githubusercontent.com/assets/20924190/17512149/5006a94e-5e48-11e6-841b-7d48db456e47.png)
![1 2](https://cloud.githubusercontent.com/assets/20924190/17512182/7ab27cc2-5e48-11e6-9d45-dd4778cef7d8.jpg)
![2 1](https://cloud.githubusercontent.com/assets/20924190/17512188/80ca1f3e-5e48-11e6-8a3c-17c0bf0622bb.png)
![2 2](https://cloud.githubusercontent.com/assets/20924190/17512193/8601c740-5e48-11e6-957f-9de521e4bc41.png)

**Comment by EvGeniu5** [comment]
1 and 2, the image shown is simply incorrect display of 
3 - image shows code with wrong display 
4 - image code with which the load properly

**Comment by kprovance** [comment]
You need to take this up with the author of the theme.  We do not support themes that use our framework.  It is the theme authors responsibility.   Thanks.
