### ISSUE TITLE
Redux and WpDemo.io issue

### ISSUE THREAD

**Issue by pseudonymus** [reduxframework/redux-framework#3081]
Hey guys,

I'm trying to set up a theme with the latest ReduxFramework official version on a multisite network but it seems that when the Wp Demo plugin(v1.1 which I got last year) is active, I can`t access the options panel of the theme. 

Is WpDemo.io still a viable product? It seems that the website is actually down at http://wpdemo.io/ 
Is there any newer version than 1.1. for WpDemo which might actually fix my issue? 

FYI, the Wp Demo plugin works well with themes packed with ReduxFramework older than 3.5.

Thank you!
Madalin

**Comment by dovy** [comment]
Answered on the other repo.
