### ISSUE TITLE
Limit or Max Selection costruct from select2 not work

### ISSUE THREAD

**Issue by wichaksono** [reduxframework/redux-framework#3082]
i'm developing a theme and using redux framework (from github repo) for theme option,
im using Redux version 3.6.0.11. and wordpress 4.5.3

i'm using field "select" in multi select mode. it work very well. but when I try to limit the number of options with :
`'select2'  => array(
                    'maximumSelectionLength' => 2
                )`
but no change whatsoever .

thanks
Wichaksono

**Comment by kprovance** [comment]
Please review:  https://github.com/reduxframework/redux-framework/blob/master/CONTRIBUTING.md

**Comment by kprovance** [comment]
No reply.  Closing ticket.
