### ISSUE TITLE
Customizer required/dependent fields do not work

### ISSUE THREAD

**Issue by seventhqueen** [reduxframework/redux-framework#3087]
Hi, the required field settings do not work in the customizer. Do you have it in plan?

Is there an extension that allows dependent fields to work in the customizer?

Thanks

**Comment by kprovance** [comment]
Yes, as indicated on the kickstart page, required does not yet work.  As Dovy said, it's a very complicated piece work that will take time.  Please see his reasons listed for why he cannot get to it at present.  There is no other extension available to accomplish this right now.

**Comment by britner** [comment]
I took a look at how Kirki handled this and it seems with customizer active callback you can do this without much trouble, add a line right after this: https://github.com/reduxframework/redux-framework/blob/master/ReduxCore/inc/extensions/customizer/extension_customizer.php#L557

That has this: 
`'active_callback' => ( isset( $option['required'] ) ) ? array( 'Redux_Active_Callback', 'evaluate' ) : '__return_true',`

Then you can add this class to a functions file or extension: https://gist.github.com/britner/1a00af5d31208ef9e9cd1e1fe5561fd6

That will make the required fields work.
Good Luck
Ben

**Comment by seventhqueen** [comment]
Thank you very much Ben, I will definitely run some tests today and see how it goes.

**Comment by dovy** [comment]
Merging in. Great work Ben!

**Comment by partharkl** [comment]
Hi Britner,

I have tried the the above one.
First added the line in inc/extensions/customizer/extension_customizer.php#L557
Second included the code to the main functions.php file.

But still required filed not working in live customizer.
Will you please let me know what I am doing wrong.

Thanks

**Comment by britner** [comment]
Hey partharkl, 
Can you give me more information about what your trying to require? An example of your options maybe I'll see the issue then.

Ben

**Comment by partharkl** [comment]
Hi Ben,

Notes - Issue is appearing only in live customize not in backend theme options.

The required field is working only when one required condition fulfilled, 
like - 
`array (
				'title' => esc_html__( 'Slider Position','zplus' ),
				'subtitle' => esc_html__( 'Controls if the slider displays below or above the header.','zplus' ),
				'id' => 'slider_position',
				'type' => 'select',
				'options' => array (
					'below' => 'Below',
					'above' => 'Above',
					'from_top' => 'From Top',
				),
				'default' => 'below',
				'required' => array( 
					array('header_position', '=', 'Top'),
				)
			),`

But this is not working with multiple “parent” required values.
