### ISSUE TITLE
dirname (_FILE_)

### ISSUE THREAD

**Issue by ljubomir1301** [reduxframework/redux-framework#3088]
Is there any way if i can replace **$dir = Redux_Helpers::cleanFilePath( dirname( __FILE__ ) );** with **get_template_directory()** at framework.php file? I wanna keep it integrated into the theme, i don't want to use it as plugin. The reviewer for my theme request that to be changed :)
Thankss

**Comment by kprovance** [comment]
There is not.  You'd have to modify that file directly, and keep changing it back on every update.  Or, use TGM to install Redux as a plugin.  OR, you could explain in your submission notes that Redux is designed this way to support themes and plugins, and that get_template_directory is not a one size fit's all solution.  TF is making is more difficult to embed Redux in themes these days.
