### ISSUE TITLE
symlink issue

### ISSUE THREAD

**Issue by cmfwebsolutions** [reduxframework/redux-framework#3090]
I have an issue similar to this
https://wordpress.org/support/topic/redux-framework-and-symbolic-link
I have a plugin that is using redux.
The issue though i have is that i am running a multitenancy setup so there is no single URL that can be set as the multitenancy runs many sites
How can i reference the framework?

**Comment by kprovance** [comment]
What's wrong with https://codex.wordpress.org/Function_Reference/plugins_url

There is also #3054

**Comment by kprovance** [comment]
Closing,  No reply.
