### ISSUE TITLE
Increasing the Memory Limit

### ISSUE THREAD

**Issue by limitlesssoftware** [reduxframework/redux-framework#3091]
Hello, 
I have to increase the memory limit 
it gives an error which is Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 130968 bytes) in /home/letsp234/public_html/limitlesssoftware.ca/wp-content/themes/ronneby/inc/lessc.inc.php on line 1389

Need help! Thank you

**Comment by kprovance** [comment]
Google:  How to increase PHP memory limit in WordPress.

Thanks.
