### ISSUE TITLE
Child Theme

### ISSUE THREAD

**Issue by sakarya** [reduxframework/redux-framework#3092]
Hi. 

I'm triyng to build a child with Redux.

Admin panel finished, and I want to display web pages based on selected options. But I can't get any value. I saw values at db.

options.php;
```
if ( !class_exists( 'ReduxFramework' ) && file_exists( dirname( __FILE__ ) . '/ReduxCore/framework.php' ) ) {
    require_once( dirname( __FILE__ ) . '/ReduxCore/framework.php' );
}
$opt_name = "my_custom";
$theme = wp_get_theme();

$args = 
	array(
		'opt_name'             => $opt_name,
		'display_name'         => $theme->get( 'Name' ),
		'display_version'      => $theme->get( 'Version' ),
		'allow_sub_menu'       => true,
        'menu_title'           => __( 'My Theme', text' ),
        'page_title'           => __( 'My Theme Options', 'text' ),	
		'menu_icon'            => '',
		'admin_bar'            => false,
		'dev_mode'             => false,
	);

Redux::setArgs( $opt_name, $args );

Redux::setSection( $opt_name, array(
	'title'            => __( 'Genel Ayarlar', 'text' ),
	'id'               => 'my_genel',
	'desc'             => __( 'Tema ve sistem ile ilgili genel ayarlar.', 'text' ),
	'customizer_width' => '400px',
	'icon'             => 'el el-adjust-alt'
) );
Redux::setSection( $opt_name, array(
	'title'      => __( 'Firma Bilgileri', 'text' ),
	'id'         => 'my_genel-company',
	'desc'       => __( 'Firma Bilgileri', 'text' ),
	'subsection' => true,
	'fields'     => array(
		array(
			'id'       => 'company-name',
			'type'     => 'text',
			'title'    => __( 'Firma Adı', 'text' ),
			'subtitle' => __( 'Firma adı', 'text' ),
		),
...
	)	
) );

```

functions.php

```
global $my_custom;
require 'inc/options.php';
echo $my_custom['company-name'];

```

**Comment by kprovance** [comment]
You have to load your options config in the function.php.  It's being loaded too late in your scenario.

**Comment by sakarya** [comment]
Moved all codes functions.php, but nothing changed.

var_dump($my_custom) output is functions.php:1208:null

**Comment by kprovance** [comment]
Is this your theme, or someone elses you are modifying?

**Comment by sakarya** [comment]
building storefront (woocommerce default theme) child theme.

**Comment by kprovance** [comment]
Okay, well, this issue tracker is for Redux bug and issues with our core.  What you want from us falls under premium support, but I'll have to download the theme you are using and try and figure out what's not being done properly, which means it's not a core issue.  I'd contact the author of the theme, since they would know it better than us, as we typically do not support theme users, but theme developers.

**Comment by sakarya** [comment]
Thank you.

**Comment by sakarya** [comment]
No, I've created a simple empty theme. But still not get any value.

mytheme
 - index.php
 - style.css
 - functions.php
 - ReduxFramework (folder)

this is in index.php

`<?php //empty`

this is in style.css
```
/*
Theme Name:   	empty
Version:      	1.0.0
License:      	GNU General Public License v2 or later
License URI:  	http://www.gnu.org/licenses/gpl-2.0.html
Text Domain:  	empty
Tags:         	black, white, light, two-columns, left-sidebar, right-sidebar, responsive-layout, custom-background, custom-colors, custom-header, custom-menu, featured-images, full-width-template, threaded-comments, accessibility-ready
*/
```

this is in functions.php
```
/**
 * Empty Theme
 *
 * @author   empty
 * @since    1.0.0
 * @package  empty
 */
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * ReduxFramework
 *
 * @since  1.0.0
 * @return void
 */
if ( !class_exists( 'ReduxFramework' ) && file_exists( dirname( __FILE__ ) . '/ReduxCore/framework.php' ) ) {
    require_once( dirname( __FILE__ ) . '/ReduxCore/framework.php' );
}

$opt_name = "mytheme_options";
$theme = wp_get_theme();

$args = 
	array(
		'opt_name'             => $opt_name,
		'display_name'         => $theme->get( 'Name' ),
		'display_version'      => $theme->get( 'Version' ),
		'allow_sub_menu'       => true,
        'menu_title'           => __( 'Options', 'empty' ),
        'page_title'           => __( 'Custom Options', 'empty' ),	
		'menu_icon'            => '',
		'settings_api'		   => 'true',
		'admin_bar'            => false,
		'dev_mode'             => true,
		'output'			   => true,
	);

Redux::setArgs( $opt_name, $args );

Redux::setSection( $opt_name, array(
	'title'            => __( 'Theme Options', 'empty' ),
	'id'               => 'theme_options',
	'customizer_width' => '400px',
	'icon'             => 'el el-adjust-alt'
) );
Redux::setSection( $opt_name, array(
	'title'      => __( 'Title', 'empty' ),
	'id'         => 'content-title',
	'subsection' => true,
	'fields'     => array(
		array(
			'id'       => 'main-title',
			'type'     => 'text',
			'title'    => __( 'Main Title', 'empty' ),
			'subtitle' => __( 'Main Title', 'empty' ),
		),
	)	
) );

global $mytheme_options;

echo $mytheme_options['main-title'];
print_r($mytheme_options);
```
Admin screenshot: [http://i.hizliresim.com/VEA9kB.png](url)
Redux Version: 3.6.1
Wordpress Version: 4.6

Still, don't see anything.

**Comment by chandani293** [comment]
Hey, i have facing same issue. i have too much try. for all solutions in stackoverflow.
if you get any solutions please give me as soon as possible.

i have use crysta theme. plugin directory use redux framework. but i need child theme to create new section .

**Comment by dovy** [comment]
Easiest method is to use the Redux API. https://docs.redux.io/configuration/api.html

**Comment by dovy** [comment]
And use set_section if you’re using redux 3x. ;)

**Comment by chandani293** [comment]
function add_another_section_bl($sections){
$sections = array(); // Delete this if you want to keep original sections!
$sections[] = array(
'title' => __('A Section added by hook123', 'crysta'),
'desc' => __('<p class="description">This is a section created by adding a
filter to the sections array. Can be used by child themes to add/remove
sections from the options.</p>', 'swift-framework-admin'),
'fields' => array('test1','test2')
);

return $sections;
}
// In this example OPT_NAME is the returned opt_name.
add_filter("redux/options/redux_demo/sections", 'add_another_section_bl');


Hello

  Requirement is : i need to add custom field like favicon icon field for
particular section in child theme. my parent theme is crysta theme for
purchase in themeforest. redux framework is in plugin folder. i have added
above code in function.php file
i have use redux framework version 3.1.7
if i am wrong in code side Please correct me.

Give me reply as soon as possible.

Thanks & Regards
Chandani
