### ISSUE TITLE
About Team-member in Cookie theme

### ISSUE THREAD

**Issue by aslikayma92** [reduxframework/redux-framework#3093]
Hi, i'am using Cookie theme, and my website is www.koridorproduksiyon.com, i have a problem about team-member section. When i am click on a person who is in team, i can see the all social media about them. But when i am click on social media link (facebook, instagram, website icon ), the page is not open in new tab. And i want to open in new tab. Is someone help me about it ?

**Comment by dovy** [comment]
We didn't build that theme. You'll want to contact the theme author.  :)
