### ISSUE TITLE
Slowness

### ISSUE THREAD

**Issue by websydaisy** [reduxframework/redux-framework#3094]
I recently switched a site to the Solstice theme from Seaboard Themes, and the site immediately slowed to a crawl. I contacted WPEngine, the host, to see if they could help me pinpoint the issue, and they sent me the attached screenshots showing issues with processes in Redux Framework. Sure enough, if I disable the Redux Framework plugin, the site speeds right back up. 

I have sent a message to the theme developer but wanted to try here as well - any idea wht the slowdown and what if anything I can do to overcome it?

![2016-08-20_1718](https://cloud.githubusercontent.com/assets/4122190/17834656/6a86b9be-6710-11e6-9013-50a39f57d2ec.png)
![2016-08-20_1717](https://cloud.githubusercontent.com/assets/4122190/17834657/6cd8877e-6710-11e6-8d1f-85cd27b17d6d.png)

**Comment by dovy** [comment]
I regret to inform you we didn't build that theme. Also developers hook into our hooks to run extra functions so it appears like redux is causing slowness. Unfortunately it not our framework, but how they're utilizing it. 

You'll need to contact the theme author yourself.

**Comment by websydaisy** [comment]
Ok, I already sent a message to the theme author. Waiting to hear back.

**Comment by dovy** [comment]
Best of luck!
