### ISSUE TITLE
Show debug mode

### ISSUE THREAD

**Issue by oknoorap** [reduxframework/redux-framework#3095]
How to displaying debug mode like this

[https://github.com/ReduxFramework/redux-framework/issues/1109](https://github.com/ReduxFramework/redux-framework/issues/1109)

![https://cloud.githubusercontent.com/assets/2384410/2775389/f6c92eec-cac4-11e3-9f14-7fc5ac0e9a29.png](https://cloud.githubusercontent.com/assets/2384410/2775389/f6c92eec-cac4-11e3-9f14-7fc5ac0e9a29.png)

**Comment by kprovance** [comment]
Looks like a print_r statement.

**Comment by oknoorap** [comment]
@kprovance thats not what I means,  dev_mode was set as ``true`` but when saving changes, print_r is not showing up in my wordpress admin. I've set ajax_save to false, but debug seems not displaying.

**Comment by kprovance** [comment]
I'm not sure.  Look in the javascript debug console?

**Comment by oknoorap** [comment]
JS console only prints js object.

I think my settings are fine:
* WP_DEBUG is ``true``
* ``dev_mode`` is ``true`` 
* ``ajax_save`` is ``false``
* PHP Settings ``display_errors`` = ``On``

But nothing displayed when I debug a compiler hooks
here is my codes:

```php
<?php
       // This is on class
       add_filter( 'redux/options/' . $opt_name . '/compiler', array(&$this, 'redux_compiler'), 10, 3);

        /**
	 * Theme css compiler, hooks for redux compiler action
	 */
	public function redux_compiler ($options, $css, $changed_values)
	{
		global $wp_filesystem;
		if (empty($wp_filesystem))
		{
			require_once( ABSPATH .'/wp-admin/includes/file.php' );
			WP_Filesystem();
		}

		print_r($wp_filesystem);

		if ($wp_filesystem)
		{
			$filename = UXID_BASE_PATH . '/theme.css';
			$res = $wp_filesystem->put_contents($filename, $css, FS_CHMOD_FILE);
			echo 'file write: ' . $res;
		}
	}
```

**Comment by kprovance** [comment]
Here's the thing; it's not a Redux bug, which is what this issue tracker is for.  If I had to guess, it's because you have to change the option of a field that has the compiler argument set, which is the only way the compiler hook fires.

Oh, and I'm telling you now...that method to write css to a file?  Not going to work, and if it does, it will fail on more than one server.  That's why we got rid of it.

**Comment by oknoorap** [comment]
> Oh, and I'm telling you now...that method to write css to a file? Not going to work, and if it does, it will fail on more than one server. That's why we got rid of it.

Okay thank you.
