### ISSUE TITLE
How to output a button_set

### ISSUE THREAD

**Issue by oknoorap** [reduxframework/redux-framework#3096]
![https://i.gyazo.com/3470174a95c4bbea309f94dfa894a1a4.png](https://i.gyazo.com/3470174a95c4bbea309f94dfa894a1a4.png)

I want to generate output from button_set. This code doesn't generate output on frontend.
Is my code is true? or there is an alternative method to generate css code from button_set.

```php
<?php
array(
        'id'       => 'link-decoration',
        'type'     => 'button_set',
        'title'    => __( 'Text Decoration', 'primax' ),
        'multi'    => false,
        'output'    => array('text-decoration' => array('a')),
        'options'  => array(
            'none'      => 'None',
            'underline' => 'Underline',
            'overline' => 'Overline',
            'line-through' => 'Line Through'
        ),
        'default'  => 'none'
    )
``

**Comment by kprovance** [comment]
Button set does not support any type of output.  Sorry.
