### ISSUE TITLE
Theme Options not saving 

### ISSUE THREAD

**Issue by waqasriaz** [reduxframework/redux-framework#3101]
Hi,
When i save theme options, i get this error in console 
**Uncaught TypeError: Cannot read property 'action' of null**

**Comment by waqasriaz** [comment]
Hi,
When i save theme options, i get this error in console 
**Uncaught TypeError: Cannot read property 'action' of null**

**Comment by kprovance** [comment]
Not enough information.  Please review: https://github.com/reduxframework/redux-framework/blob/master/CONTRIBUTING.md

**Comment by kprovance** [comment]
No reply.  Closing.  If further assistance is needed in the future, please review out support guidelines and post the required information.  Thanks!
