### ISSUE TITLE
Error with color_rgba

### ISSUE THREAD

**Issue by listedegarde** [reduxframework/redux-framework#3102]
I'm able to create a redux element with the type color_rgb like this:

```
array(
  'id'          => 'color-menu_border_bottom',
  'type'        => 'color_rgba',
  'title'       => __('Border bottom colour', 'my-framework'),
  'default'     => array(
    'color'     => '#ffffff',
    'alpha'     => 0,
  ),
  'validate'    => 'color_rgba',
  'compiler'  => true
);

```

After saving and refreshing the page, I get the following error:

Warning: strlen() expects parameter 1 to be string, array given in /home/user/public_html/wp-content/plugins/redux-framework/ReduxCore/inc/class.redux_helpers.php on line 344

I did a dump of the $hex variable, and it is indeed an array.  I'm expecting this is a bug, but haven't yet taken the time to look into it further.

The trace from XDebug:

| Function | Location |
|----------------------|------|
| {main}( ) | 	../admin.php:0 |
| do_action( ) | 	../admin.php:236 |
| call_user_func_array ( ) | 	../plugin.php:525 |
| ReduxFramework->generate_panel( ) | 	../plugin.php:525 |
| reduxCorePanel->init( ) | 	../framework.php:3260 |
| reduxCorePanel->panel_template( ) | 	../panel.php:41 |
| reduxCorePanel->get_template( ) | 	../panel.php:84 |
| require( '/var/www/dev.standish.ca/wario/master/wp-content/plugins/redux-framework/ReduxCore/templates/panel/container.tpl.php' ) | 	../panel.php:254 |
| reduxCorePanel->get_template( ) | 	../container.tpl.php:51 |
| require( '/var/www/dev.standish.ca/wario/master/wp-content/plugins/redux-framework/ReduxCore/templates/panel/content.tpl.php' ) | 	../panel.php:254 |
| reduxCorePanel->output_section( ) | 	../content.tpl.php:70 |
| do_settings_sections( ) | 	../panel.php:328 |
| do_settings_fields( ) | 	../template.php:1292 |
| call_user_func ( ) | 	../template.php:1333 |
| ReduxFramework->_field_input( ) | 	../template.php:1333 |
| ReduxFramework_color_rgba->render( ) | 	../framework.php:3450 |
| Redux_Helpers::hex2rgba( ) | 	../field_color_rgba.php:124 |
| strlen ( ) | 	../class.redux_helpers.php:344 |

**Comment by kprovance** [comment]
Take out the color_rgba validation.  It;s not needed, and it doesn;t work anyway.  The field does validation internally.
