### ISSUE TITLE
Date Issue in WP 4.6?

### ISSUE THREAD

**Issue by mediagin** [reduxframework/redux-framework#3103]
I am using Redux 3.6.1.1 as my personal theme options panel.  I'm seeing a "date" field issue after upgrading to WP 4.6.  The date format is typically "08/30/2016" but after upgrading and selecting a date, the format defaults to "August 30, 2016" and throws an improper date format error within the options panel.  I have disabled all plugins, switched to default theme, etc to test this.  Can you verify?  Thanks.  Jim

**Comment by kprovance** [comment]
Not enough information to look into this.  Please review our support guidelines:  https://github.com/reduxframework/redux-framework/blob/master/CONTRIBUTING.md

**Comment by mediagin** [comment]
I read it thoroughly.  How is there not enough information? I have a regular "date" field in an options panel using version 3.6.0.1 of Redux.  Instead of displaying the chosen date of "08/30/2016" it displays "August 30, 2016" within the options panel right after selecting the date.  There's no other information I can provide that can make this issue any clearer.  I visited http://demo.redux.io to see if the date field produced the same results but you are running WP 4.5.3 instead of WP 4.6.  Of course, it works fine there.  When I downgrade back to a lower version of WP, it's works fine.

**Comment by kprovance** [comment]
support url.  It's required now.

**Comment by mediagin** [comment]
Got it.  I'll create a site copy for you using clean empty site, TwentySixteen theme and Redux 3.6.0.1.  Back in a sec.

**Comment by mediagin** [comment]
I'm not worried about this admin.  We'll delete everything after you check. http://www.mediagin.com/redux/wp-admin.  Use redux/redux.  There's a "Site Options" in the main menu.   

Here's the array...
`		array(
			'id'          => 'takeoverbg-startdate',
			'type'        => 'date',
			'title'       => 'Start Date',
			'subtitle' => 'Required for the background takeover to appear.',
			'placeholder' => 'Click to enter a date.'
		),`

**Comment by kprovance** [comment]
Okay, I need to be plain here.  This does me no good.  I can;t see your config, I can;t see your PHP settings.  I NEED the support URL as explained in the support guidelines, please.

**Comment by mediagin** [comment]
http://support.redux.io/?id=egdHNXuPAoRXVlEhsVlD3%2FO3GHh8LVm3dWij1WB15QCQELQDorqupImCebTktAXb%2BAtc4oV7XEsnbarAnNRWmA%3D%3D

**Comment by kprovance** [comment]
Fixed in v.3.6.1.2
