### ISSUE TITLE
sample data

### ISSUE THREAD

**Issue by mohhsn1977** [reduxframework/redux-framework#3104]
Dear Sir,

How to get sample data for the template?

Regards

**Comment by kprovance** [comment]
Look at the files in the ReduxCore/templates folder.  Those are the ones you would modify.

**Comment by mohhsn1977** [comment]
can  you provide me with more details and instruction on how to use it?

**Comment by mohhsn1977** [comment]
can you provide me with more details and instructions on how to use it?
