### ISSUE TITLE
Issue with output and link_color

### ISSUE THREAD

**Issue by listedegarde** [reduxframework/redux-framework#3105]
I have declared by link_color as following:

```php
$typography_fields[] = array(
  'id'       => 'scss-button-text-colour',
  'type'     => 'link_color',
  'title'    => __('Primary button text colour', 'my-framework'),
  'visited'  => false,
  'output'   => array(
    'color' => '.btn.btn-primary',
  ),
  'default'  => array(
  'regular'  => '#1e73be', // blue
  'hover'    => '#dd3333', // red
  'active'   => '#8224e3',  // purple
  )
);
```

The output only functions on the main color, not the :hover or :active.  Example:
```css
.btn.btn-primary{color:#1e73be;}:hover{color:#ba2dc4;}:active{color:#8224e3;}
```

Which means that my whole body has a :hover colour of #ba2dc4.  I have also tried with 'output' => array('.btn.btn-primary');

Have I missed something, or is this a bug?

**Comment by kprovance** [comment]
https://github.com/reduxframework/redux-framework/blob/master/CONTRIBUTING.md.  Please post a support URL.

**Comment by listedegarde** [comment]
http://support.redux.io/?id=t1ExNc%2Bzv3T1mG3MnCzVTIS%2Fja%2ByWGY2eayOQpj9tyEryXfJDS%2BSKEkGH%2FmmTuQIENul8xxYfmwDIaHuCOvx1w%3D%3D

**Comment by kprovance** [comment]
Pull v3.6.1.3 from this repo.  Should fix that.
