### ISSUE TITLE
Default Date Validation Issue

### ISSUE THREAD

**Issue by pmbaldha** [reduxframework/redux-framework#3106]
When we set wordpress date format to F j, Y, redux date field is not working. Redux default date field validation return false and displays error message something like
"This field must be a valid date."

Please refer below screenshot links:
![general settings epress final wordpress](https://cloud.githubusercontent.com/assets/15802539/18194971/a13ec83e-7106-11e6-9253-d435a55992d6.png)
![sample options epress final wordpress](https://cloud.githubusercontent.com/assets/15802539/18194972/a2aff814-7106-11e6-9fd2-e13e0b8d1fcb.png)

Thank You.

**Comment by kprovance** [comment]
Please update to the latest version of Redux from this repo.

**Comment by pmbaldha** [comment]
After updating latest version of redux from github still this issue coming.

**Comment by pmbaldha** [comment]
Please open this issue again.

**Comment by kprovance** [comment]
With v3.6.1.3, the date defaults to mm/dd/yy/  it cannot be changed via WP settings.

**Comment by kprovance** [comment]
Why>  I forced the javascript to foce the decalut to dd/mm/yy.  That's how it it is.

**Comment by pmbaldha** [comment]
You are right with v3.6.1.3, this issue has been resolved. 
May i know when will you release  v3.6.1.3 from wordpress.org?

Thank You Very Much...
