### ISSUE TITLE
Sorter problems

### ISSUE THREAD

**Issue by atashinbar** [reduxframework/redux-framework#3110]
Hi

 I am looking for 2 things:

 1- Why "Sorter" elements don't appear in customizer? I checked your demo site and saw it in customizer but I cannot find how to put it in customizer.

 2- I have 3 sections for sorter (disable, right, left). I want requirements for this, it means when element is in "right" or "left" the element’s options displays after sorter section.

 See below image:

![capture](https://cloud.githubusercontent.com/assets/19619864/18273787/530ba8ac-7454-11e6-8d62-07909a50bc9d.PNG)

**Comment by kprovance** [comment]
That field is part of the advanced customizer extension which is - sorry to say - still in development hell.  No ETA.  You'd have to ask @DOvy who has too much on his personal plate as it is.

As for using required with the sorter field, it's not set up to do aat present.  That bit of code would be intricate, to make it all work together, and I honestly do not have the entire day to devote to it pro bono.  I can put it on my to-go list, but honestly, until Redux makes Dovy and I some serious money, big projects like that get put on hold indefinitely.
