### ISSUE TITLE
How to disable the default color value output?

### ISSUE THREAD

**Issue by themevan** [reduxframework/redux-framework#3111]
Hi

I use the latest version of redux framework which was downloaded from github. One of my option like below:

```
array(
                'id'       => 'nav_color',
                'type'     => 'color',
                'title'    => __( 'Navigation Background Color', 'dgwork' ),
                'validate' => 'color',
                'default'  => '#fff',
                'output'   => array('background-color'=>'#dgw-topbar,#dgw-topbar.fixed-nav-bg')
            ),
```

I set the default color for the navigation bar, and used output argument, now the default color will be output as the inline CSS in the header, is there any way to make it do not output the default color value? I want to output the inline CSS only when the changed color is not the default color, Now the only way is leave the default value empty, but I hope keep the default value.

Thanks

**Comment by kprovance** [comment]
There is not, short of removing the default value.
