### ISSUE TITLE
Multiple font weights with Google Fonts

### ISSUE THREAD

**Issue by cocodedesigns** [reduxframework/redux-framework#3112]
I am trying to input two font styles (one for headings, one for normal paragraphs).  However, there are multiple weights on the headings, as controlled by my main CSS.  After searching through some posts on here, I have set the `all_styles` variable to `true`, set both `font-style` and `font-weight` to `false` and even commented them out (as seen on your sample-config), however all through the outputted page, the font style is set to `normal` in the inspector for the page, which would naturally override any styles in my CSS.  Is there a way where Redux will load all of the font weights and styles into my site and allow for my CSS to take over assigning weights to the fonts?

If it makes any difference, I have the Wordpress version of Redux installed and I am using Wordpress 4.6.

**Comment by kprovance** [comment]
Honestly, I don't understand all what you are attempting to do here or what's going on.  Our typography field does not allow for multiple weights and styles, do I'm guessing not.

**Comment by cocodedesigns** [comment]
I am trying to set a font in Redux without setting a weight in there.  When I go into the Redux panel, I can see Font Family and Backup Font Family.  I can't see the Font Style and Weight field there.  So far, so good.  However, when I set a font in there, it is displayed in my page with `font-weight: normal;` and `font-style: normal;`  This overrides the styles that I have already declared in my external stylesheet.  What I am hoping is that there is a way that I could pull in all of the styles (as I assume the `all_styles` array variable does) and weights for any font that I declare, but where I, in my stylesheets, can manually declare the weights that I want.  So, for example, Redux will pull in Source Sans Pro as my font.  It will pull in all of the weights (100, 300, 400, 700, etc.) and all of the italic fonts too.  I then have a class in my stylesheet which uses Source Sans Pro.  I then say "This class should use `font-weight: 300` and this other class should use `font-weight: 700`."  So Redux doesn't have to find the right styles and where they go, it just has to pull in all of the styles for the font I have declared, regardless.  From what I have seen, others have had the same problem and have been advised to use the `'all_styles' =. true` setting, but this does not work for me.

**Comment by kprovance** [comment]
All all_styles does is display all the available styling boxes on the option panel.  It does not output all styles into the inline CSS.  Again, Redux doesn't support multiple front weights/styles/etc via one option display.  We toyed with it last year and couldn;t get it working properly, but shelved it since we have no financial backing, and it's a *lot* of work.

**Comment by cocodedesigns** [comment]
..................... Well that sucks.  I gathered that I couldn't cherry-pick the styles but I thought there was a way to just output them all.  Never mind.  Thanks for your help.

**Comment by kprovance** [comment]
It is what it is.  Had even 1% of the tens of thousands of devs who use Redux gave back 5 bucks a piece, we'd be able to do this full time and give everyone what they want.

**Comment by hungitms** [comment]
you add option 'multi' => array( 'subset' => false, 'weight' => true) with multi font weight
