### ISSUE TITLE
Typography, user fonts

### ISSUE THREAD

**Issue by Ryu-k** [reduxframework/redux-framework#3114]
Hi, this is a simple question, maybe and idea for the typography field.

I am currently changing the "Standard Fonts" using the fonts arguments.

It works fine but the font weight is set only showing the default "normal, bold, normal italic, bold italic"

I see that the javascript build this array if the font selected is not a google fonts.

I was wondering if the only way to add a light font weight is to edit the javascript file directly.

Let the user add the font weight propriety to fonts array could be a nice option for the future update.

**Comment by kprovance** [comment]
Right now, probably.  Just remember, any changes you make to the core are unsupported and will be lost on consequent updates.  I'll put it on my to-do list.  :)
