### ISSUE TITLE
Cannot create an account

### ISSUE THREAD

**Issue by AshboDev** [reduxframework/redux-framework#3116]
Hi there.

I tried creating an account on your site and it appears it didn't work. I tried using the same username as on here (Ashbodev) and my work email, however it doesn't recognise it when I try to log into the site, or the builder.

Also, I have received no emails saying that my registration is done or anything.

So yeah! Can you look into this please? :(

Cheers
Ash

**Comment by kprovance** [comment]
I don't see that user name as created or registered. Try again?  I'm not sure what else to do about this.
