### ISSUE TITLE
Rydon Theme

### ISSUE THREAD

**Issue by davefarq** [reduxframework/redux-framework#3119]
Hi there,
I'm making a website using this theme, I'm trying to insert a map into the website, I've inserted my long & latitude, however the map isn't showing, just a blank space. Any suggestions?

Thanks in advance.

**Comment by kprovance** [comment]
We don't sell themes.  You will have to contact the theme author for support, which is not us.  Sorry.

**Comment by davefarq** [comment]
Apologies, I realised that. I've done that now, thanks for getting back to me.
