### ISSUE TITLE
Media Field URL

### ISSUE THREAD

**Issue by Bluxart** [reduxframework/redux-framework#3120]
Redux Framework: 3.6.1.3
Redux Metabox: 1.3.0
Redux Repeater: 1.0.4

Hi, I dont' know if this a bug or not but I explain it.

When use the media field, I can upload the image via wp native upload or insert my custom url.

Now for my test I used the native wp uploader. All works.

Now if export the XML ( Wordpress - Tools - Export ) and re-import the dummy data into a new installation, the URL don't change based on the new wordpress installation but display the old value.

**First Wordpress Installation:**

- URL: _**http://www.domain.com**_
- URL Image into a media field ( Redux Framework, Redux Metabox and Redux Repeater ): _**http://www.domain.com/wp-content/uploads/2016/07/media_gal_08.jpg**_
- Export the XML from Wordpress

**Second Wordpress Installation:**

- URL: _**http://www.sub-domain.com**_
- Import the XML from domain.com wordpress installation
- The URL into media field instead to have this URL _**http://www.sub-domain.com/wp-content/uploads/2016/07/media_gal_08.jpg**_ have the old URL _**http://www.domain.com/wp-content/uploads/2016/07/media_gal_08.jpg**_

Now I don't know if it is a normal, let me know about this.
Thanks

**Comment by kprovance** [comment]
I think that's just how the WP Importer works as that data is stored in the posts meta section.  It's not a Redux bug.  it would happen whether it was running or not.

My only guess is to check the WP Importer code for filter hooks and see if there is one that'll let you manipulate the URLs when they are saved during import.
