### ISSUE TITLE
ERROR: wp-admin/tools.php?page=redux-changelog

### ISSUE THREAD

**Issue by webguy262** [reduxframework/redux-framework#3122]
Parse error: syntax error, unexpected T_STATIC, expecting T_STRING or T_VARIABLE or '$' in /home/content/20/6514320/html/prototypes/lawnside/wp-content/plugins/redux-framework/ReduxCore/inc/fields/raw/parsedown.php on line 1493

**Comment by kprovance** [comment]
Meed WAY more information from you please.  Please review:  https://github.com/reduxframework/redux-framework/blob/master/CONTRIBUTING.md

**Comment by kprovance** [comment]
No reply.  Closing.
