### ISSUE TITLE
Can´t save anything in options

### ISSUE THREAD

**Issue by alexandroff** [reduxframework/redux-framework#3125]
In the Oshin Theme, the redux seems to be broken. 

Can´t save anything from clean install. 

Shows, the following error code in browser console:
load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,utils,jquery-ui-core,jquery-ui-widget,jquery…:4 POST http://ilustraria3d.com.br/v2/wp-admin/admin-ajax.php 500 (Internal Server Error)send @ load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,utils,jquery-ui-core,jquery-ui-widget,jquery…:4ajax @ load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,utils,jquery-ui-core,jquery-ui-widget,jquery…:4a.redux.ajax_save @ redux.min.js?ver=3.6.0.2:1(anonymous function) @ redux.min.js?ver=3.6.0.2:1dispatch @ load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,utils,jquery-ui-core,jquery-ui-widget,jquery…:3r.handle @ load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,utils,jquery-ui-core,jquery-ui-widget,jquery…:3
redux.min.js?ver=3.6.0.2:1 There was an error saving. Here is the result of your action:
redux.min.js?ver=3.6.0.2:1

**Comment by dovy** [comment]
Set your ajax_save to false in your args, see what error is being produced. More than likely one of your functions or hooks is causing an error and thereby saving is not functioning.  ;)
