### ISSUE TITLE
Updated googlefonts.php file with missing fonts.

### ISSUE THREAD

**Issue by prafgon** [reduxframework/redux-framework#3126]
Hey guys,

I had troubles with the automatic update of Google Fonts using the config parameters (weekly update & API key) so I just grabbed your piece of code, lunched it manually in other location with some modifications and came up with a new file, including all of the currently available Google Fonts, including the very latest ones.

I'm attaching the file here to anyone interested and for you to include it in the next ReduxCore update. :)

The path: /ReduxCore/inc/fields/typography/googlefonts.php

[googlefonts.php.zip](https://github.com/reduxframework/redux-framework/files/480568/googlefonts.php.zip)

**Comment by kprovance** [comment]
Thanks!  I'll include with with the next update.  Alternative, you could do a pull request and accomplish the same, without the ZIP files.  :)
