### ISSUE TITLE
Redux v3.6.1 - PHP7 Problems

### ISSUE THREAD

**Issue by rhbkweb** [reduxframework/redux-framework#3130]
Hi,

Im using Wordpress v4.6.1 + Redux Framework 3.6.1 with PHP 7 and when making a PHP 7 compatibility test using the "PHP Compatibility Checker" v1.2.0 plugin it says Redux Framework is not fully compatible with PHP 7.

I thought all PHP 7 problems had already been resolved. 

Can anyone confirm this? And the timeframe to make Redux fully compatible with PHP 7?

`Redux Framework
Not PHP 7.0 compatible.

FILE: /var/www/mydomain.com/htdocs/wp-content/plugins/redux-framework/ReduxCore/inc/scssphp/scss.inc.php
------------------------------------------------------------------------------------------------------------------------------------
FOUND 4 ERRORS AFFECTING 4 LINES
------------------------------------------------------------------------------------------------------------------------------------
 3386 | ERROR | 'string' is a reserved keyword introduced in PHP version 7.0 and cannot be invoked as a function (T_STRING)
 3584 | ERROR | Function name, class name, namespace name or constant name can not be reserved keyword 'string' (since version 7.0)
 3697 | ERROR | 'string' is a reserved keyword introduced in PHP version 7.0 and cannot be invoked as a function (T_STRING)
 3941 | ERROR | 'string' is a reserved keyword introduced in PHP version 7.0 and cannot be invoked as a function (T_STRING)
------------------------------------------------------------------------------------------------------------------------------------`

Thanks

**Comment by kprovance** [comment]
It is.  Those libraries were removed a LONG time ago.  Delete them.

**Comment by rhbkweb** [comment]
@kprovance 

Thanks for the sugestion. Redux team should really update more often the WP repository...

**Comment by kprovance** [comment]
Um...we do.

**Comment by dovy** [comment]
Pushing a new version that's free of those old directories. I really hate SVN, but I have to use it for the WP.org repo. That was the problem here. Even though we told it to delete things, it wasn't.  :(
