### ISSUE TITLE
ThemeForest Themes should avoid opendir / readdir

### ISSUE THREAD

**Issue by cristianstan** [reduxframework/redux-framework#3131]
Hi there Redux community!

Today I got soft rejected for one of my submitted themes. One of the reason was this one, which is caused by the redux framework sample config.

The point from reviewer's message was:
Themes should avoid opendir / readdir: http://envato.d.pr/19l3G/2zT9wfAr

To get accepted I've removed that part from the config but I think that the sample config needs to updated to avoid future rejections for other people. 

Regards

**Comment by kprovance** [comment]
TF won't be happy until they've banned every file op API and replaced with with some escaping thing.  Ugh.  Anyways, it *is* only a sample file, and not a Redux bug per se.  I supposed if it's a problem, I'll just remove that part from the sample and folks can write their own.  Thanks.  :)

**Comment by cristianstan** [comment]
Thanks for the reply @kprovance :)
