### ISSUE TITLE
Contact form 7 shortcode

### ISSUE THREAD

**Issue by MaxLeven** [reduxframework/redux-framework#3134]
Hi. How I can add "Contact form 7" shortcode in the editor? It is not convert in to form.

**Comment by kprovance** [comment]
This is Redux Framework, not Contact Form 7, or the author of your theme.  Please contact one of those two for support in this matter.

**Comment by MaxLeven** [comment]
Short code work is well. But not in Redux Framework editor. It's leve code. Wat shortcodes i can use in editor?

**Comment by kprovance** [comment]
Again, you need to contact the theme author.

**Comment by MaxLeven** [comment]
I am is a theme author.

**Comment by MaxLeven** [comment]
Could you please help me to solve this issue properly? Thank you !
I just cant figure out it by myself..

**Comment by kprovance** [comment]
Okay, well, you never mentioned that, along with anything else from out posted support guidelines.  I should make clear we do not assist author with their actual themes for free.  That's a premium service.  The Redux editor only saves the information put into it, into the database, it's up to you - as the author - to so something with it, including the parsing of shortcodes.  Google do_shortcode.  Best I can offer unless you're hiring one of us.

**Comment by MaxLeven** [comment]
Thank you so much. Thanks to you I understood, and correct the problem.
