### ISSUE TITLE
Customizer Extension to allow for all fields?

### ISSUE THREAD

**Issue by contempoinc** [reduxframework/redux-framework#3135]
I know in the past there was a premium extension to allow for all fields to be used in the customizer, however I don't see it anymore? Is it still available?

Mainly looking for these: Sorter, Background, Spacing, Border & Typography?

**Comment by kprovance** [comment]
It was never officially released.  it was given to those who supported our go fund my type campaign.  Unfortunately, it's stuck in development hell and I have no idea if/when it'll ever get finished,

**Comment by contempoinc** [comment]
Gotcha, is it operable? Am I able to purchase it separately?

**Comment by kprovance** [comment]
As I recall, section fields were not working, WP Editor was not working.  Required and validation are not working, Dynamic (AJAX) CSS output and Dynamic (AJAX) Typography updates are also not working.

You'll have to ask dovy@reduxframework.com.  It's his project.

**Comment by contempoinc** [comment]
Sounds like a lotta issues, LOL

cc @dovy

**Comment by kprovance** [comment]
Oh wait, it's you, @contempoinc .  Gee, didn't I fix some stuff for you after you agreed to pay me for my time, and then stiff me on it?  Yeah, I wouldn't expect too much help from us at this point.  We don;t like being stiffed.  That was so NOT cool.

**Comment by dovy** [comment]
Boys, boys.  :(
