### ISSUE TITLE
Issue with paths when using Docker

### ISSUE THREAD

**Issue by swiderski** [reduxframework/redux-framework#3136]
Hello:-)

I don't have any experience with Docker however I know that it uses some rewrites of paths in its configuration that Redux is vulnerable to.

You use such construction in few places:
`$this->_extension_dir = trailingslashit( str_replace( '\\', '/', dirname( __FILE__ ) ) );
$this->_extension_url = site_url( str_replace( trailingslashit( str_replace( '\\', '/', ABSPATH ) ), '', $this->_extension_dir ) );`

And a problem is with second line, where you try to produce URL based on directory location, as this produce links in docker like this:
`http://staging.rocks/wp/srv/www/rocks/releases/20160911200745/web/app/plugins/redux-framework/ReduxCore/inc/extensions/customizer/extension_customizer.css?ver=1473684612`
and it isn't proper path.

Anyway, if I change second line to:
`$this->_extension_url = ReduxFramework::$_url.'inc/extensions/customizer/';`

then everything works fine, cause this `ReduxFramework::$_url` is prepared in correct(safe) way.

With kind regards.

**Comment by dovy** [comment]
If you can provide a better solution we're open to it. Just removing those lines will break so many things. We can't do that.  :(

**Comment by swiderski** [comment]
Well I don't advise to remove any lines, just to change second line to something more reliable. To be honest I didn't notice any issues with this changes on, but you might know places where I don't ever look :-)

Could you explain what is wrong with my solution? I only used code that you use in other places for this variable `$this->_extension_url`. The way you did it in mentioned place feels very hackish, and like it was done by different person then in other files, with similar construction.

**Comment by dovy** [comment]
@swiderski This issue has been resolved in Redux 4.
