### ISSUE TITLE
Theme Checker Errors

### ISSUE THREAD

**Issue by iMojtaba** [reduxframework/redux-framework#3138]
Hi,
I have some error while testing my theme with [Theme Check](https://wordpress.org/plugins/theme-check/) plugin.

`
Warning: More than one text-domain is being used in this theme. This means the theme will not be compatible with WordPress.org language packs.
The domains found are terme, redux-framework, themecheck, framework
WARNING: Found wp_deregister_script in inc/theme_option/ReduxFramework/ReduxCore/framework.php. Themes must not deregister core scripts.
Line 565: wp_deregister_script( 'wpb_ace' );
WARNING: Found wp_deregister_script in inc/theme_option/ReduxFramework/ReduxCore/core/enqueue.php. Themes must not deregister core scripts.
Line 215: wp_deregister_script( 'jquerySelect2' );
REQUIRED: This theme text domain does not match the theme's slug. The text domain used: terme, redux-framework, themecheck, frameworkThis theme's correct slug and text-domain is termetheme.
REQUIRED: The theme uses the register_post_type() function, which is plugin-territory functionality.
REQUIRED: inc/theme_option/ReduxFramework/ReduxCore/inc/welcome/welcome.php. Themes should use add_theme_page() for adding admin pages.
Line 201: $page = 'add_management_page';
REQUIRED: inc/theme_option/ReduxFramework/ReduxCore/framework.php. Themes should use add_theme_page() for adding admin pages.
Line 1424: $this->page = call_user_func( 'add_menu_page', $this->args['page_title'], $this->args['menu_title'], $this
REQUIRED: inc/theme_option/ReduxFramework/ReduxCore/framework.php. Themes should use add_theme_page() for adding admin pages.
Line 1347: // wrappers and need to be appened to using add_submenu_page.
Line 1398: $this->page = call_user_func( 'add_submenu_page', $page_parent, $page_title, $menu_title, $page_permission
Line 1456: call_user_func( 'add_submenu_page', $this->args['page_slug'], $section['title'], $section['t
RECOMMENDED: No reference to add_theme_support( "custom-header", $args ) was found in the theme. It is recommended that the theme implement this functionality if using an image for the header.
RECOMMENDED: No reference to add_theme_support( "custom-background", $args ) was found in the theme. If the theme uses background images or solid colors for the background, then it is recommended that the theme implement this functionality.
RECOMMENDED: No reference to add_editor_style() was found in the theme. It is recommended that the theme implement editor styling, so as to make the editor content match the resulting post output in the theme, for a better user experience.
INFO: Possible hard-coded links were found in the file inc/theme_option/ReduxFramework/ReduxCore/inc/welcome/welcome.php.
Line 482: <a href='http://docs.reduxframework.com/' class='docs button button-primary'>Docs</a
Line 485: <a href='https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=MMFMHW
INFO: At least one hard coded date was found in the file inc/terme_funcs.php. Consider get_option( 'date_format' ) instead.
INFO: inc/theme_option/redux-extensions-loader/loader.php The theme appears to use include or require. If these are being used to include separate sections of a template from independent files, then get_template_part() should be used instead.
Line 20: require_once( $class_file );
INFO: inc/theme_option/index.php The theme appears to use include or require. If these are being used to include separate sections of a template from independent files, then get_template_part() should be used instead.
Line 4: require_once( dirname( __FILE__ ) . '/ReduxFramework/ReduxCore/framework.ph
Line 7: require_once( dirname( __FILE__ ) . '/terme_options_config.php' );
INFO: inc/theme_option/ReduxFramework/ReduxCore/inc/welcome/welcome.php The theme appears to use include or require. If these are being used to include separate sections of a template from independent files, then get_template_part() should be used instead.
Line 378: require_once 'views/about.php';
Line 393: require_once 'views/changelog.php';
Line 408: require_once 'views/extensions.php';
Line 424: require_once 'views/support.php';
Line 439: require_once 'views/credits.php';
Line 454: require_once 'views/status_report.php';
INFO: inc/theme_option/ReduxFramework/ReduxCore/inc/fields/raw/field_raw.php The theme appears to use include or require. If these are being used to include separate sections of a template from independent files, then get_template_part() should be used instead.
Line 31: if ( ! empty( $this->field['include'] ) && file_exists( $this->field['include'] ) ) {
Line 32: require_once $this->field['include'];
INFO: inc/theme_option/ReduxFramework/ReduxCore/inc/extensions/customizer/extension_customizer.php The theme appears to use include or require. If these are being used to include separate sections of a template from independent files, then get_template_part() should be used instead.
Line 749: require_once( $class_file );
INFO: inc/theme_option/ReduxFramework/ReduxCore/framework.php The theme appears to use include or require. If these are being used to include separate sections of a template from independent files, then get_template_part() should be used instead.
Line 410: require_once 'core/dashboard.php';
Line 414: require_once 'core/newsflash.php';
Line 1705: require_once 'core/enqueue.php';
Line 2852: require_once 'core/enqueue.php';
Line 2910: require_once 'core/panel.php';
Line 3258: require_once 'core/panel.php';`

as you can see, most of the error is related to reduxframework. 
Here is my theme repo. https://github.com/TermeTheme/TermeTheme/tree/nima

Thanks You.

**Comment by kprovance** [comment]
A lot of these are false flags, and others have been explain on other threads.  Have you actually submitted yet and been told these things?

**Comment by nimamamany007** [comment]
"I have this problem too".

![Uploading Screenshot_20161005_093556.png…]()
![screenshot_20161005_093606](https://cloud.githubusercontent.com/assets/17119726/19102847/142b264c-8ae0-11e6-8a03-0fb8adf57b4e.png)

How can i resolve this issue?!

**Comment by nimamamany007** [comment]
"I have this problem too".

![screenshot_20161005_093556](https://cloud.githubusercontent.com/assets/17119726/19102908/78bdc15a-8ae0-11e6-9474-75cc7615456e.png)
![screenshot_20161005_093606](https://cloud.githubusercontent.com/assets/17119726/19102909/78f533d8-8ae0-11e6-81f4-62f1ee1448f7.png)

How can i resolve this issue?!

**Comment by kprovance** [comment]
We have addressed this issue so many times.  I don;t really feel like typing it all our when it's searchable.  Redux is vendor code, not theme code.  We can't use required paths that use get_template_uri because Redux is also used as a plugin.  Explain to the reviewer that it's vendor code and not subject to the same rules theme code is.  Or, install Redux as a plugin via TGM and TF will never look at it.

**Comment by rahul64bit** [comment]
Pls inform me how to solve this Theme Checker Errors

**Comment by kprovance** [comment]
https://reduxframework.com/2015/07/theme-check-compliant/ with a complete support  URL/hash and a more specific issue than 'solve this for me'.
