### ISSUE TITLE
Type "color" field transparent => true not saving by default

### ISSUE THREAD

**Issue by cristianstan** [reduxframework/redux-framework#3141]
I've added a section color type:

```
array(
    'id'       => 'nav_background',
    'type'     => 'color',
    'title'    => 'Nav Menu Background Color', 
    'default'  => '#ffffff',
    'validate' => 'color',
    'transparent' => true
)
```

Note that I am using the config in one of my WordPress themes. So when I install the theme all default values are ok, but the **transparent value is false**.

I guess that the plugin has an issue, this is why I reported this as an issue.

Please let me know if this can be fixable or you need to release a new update.

- Cristian

**Comment by kprovance** [comment]
Did you review the docs for this field?

https://docs.reduxframework.com/core/fields/color/

Setting that arg hides or shows the actual checkbox, not the value.  The note on the docs page says:  NOTE:  To set the transparency checkbox by default, use the string ‘transparent’ in place of a string hex value  in the default argument.

No update to the code needed.
