### ISSUE TITLE
Redux Frame work isn't work  with WordPress 4.6.1

### ISSUE THREAD

**Issue by jackbui2014** [reduxframework/redux-framework#3142]
I can't use image uploader, editor when update WordPress to 4.6.1
How can I fix it?

**Comment by kprovance** [comment]
In fact, it works fine.  "Can't use it' isn't very telling.  Please review our support guidelines for the information we require:   https://github.com/reduxframework/redux-framework/blob/master/CONTRIBUTING.md

**Comment by kprovance** [comment]
No reply.  Closing.
