### ISSUE TITLE
Error on saving theme options : There was a problem with your action. Please try again or reload the page

### ISSUE THREAD

**Issue by kwayyinfotech** [reduxframework/redux-framework#3143]
Hello,

We are developer of DigialLaw theme. We are using Redux Framework for Theme Options section. Also the Redux Framework is working perfectly with all our clients.

Recently one of our theme user is getting this error:
**There was a problem with your action. Please try again or reload the page**

He also contacted hosting service provider and increased all PHP.INI related things but still the error appears. I am not sure what the problem is so I am contacting you. Here is the URL of the data of the user's WordPress site:
http://support.redux.io/?id=HNtrUmhBkEqDQbJXuPMQV4RoURxK37VT%2FyQGx3%2BRZ%2FDHQAI2ouZU6kcIExt8vpPtv%2BWIPMPWk%2BkrXMST4oJmYg%3D%3D

Some basic information about Digital Law theme:
- The theme is using Redux Framework as plugin and not bundled within theme.
- Theme Options are Ajax based.
- The JS message box appear with message "There was a problem with your action. Please try again or reload the page" when saving Theme Options. Also the Theme options are saved.

Hope this helps to find the problem.

**Comment by dovy** [comment]
In your arguments set ajax_save to false and then you'll see the error. ;)

**Comment by kprovance** [comment]
No reply.  Closing.

**Comment by kwayyinfotech** [comment]
I found the bug. Thanks for your reply.
I disabled ajax save and then found a server error.

Thanks,
Bob

**Comment by kprovance** [comment]
If you are the developer, in your options panel array, global arguments.  If you are a theme user, you will have to ask whomever authored your theme.

**Comment by kprovance** [comment]
Let me clarify one thing about this message; There are very common reasons it occurs.  The first is nonces.  Those are security hashes assigned to WordPress functions for security.  They only last between 12 and 24 hours before they expire.  In any situation where the admin window with the options panel is open that long, that message could be displayed on save.  The solution is to refresh the window.  The second is erroneous screen output, specifically PHP or servers errors that are printed either to the window (which are sometimes obscured) or in the HTML itself, again, not always visible.  Theme  uses should contact the theme author about those so the author can do some simple debugging to determine why there are errors.  For theme developers, you'd want to review your PHP error logs and see if said errors are being output, even if obscured.  That's my advice on that.  Good luck!

**Comment by olanrewajujohn** [comment]
hi!

It can be the problem due to version of php.

Try this solution to see if it works.

/wp-content/plugins/redux-framework/ReduxCore/framework.php

go to line 4069

there you find such option
$args = array_merge( array( $current_user ), func_get_args() );

change it to
$name_arr=func_get_args();
$args = array_merge( array( $current_user ),$name_arr );

test if it works. Cheers.
Answer from https://github.com/reduxframework/redux-framework/issues/3124 User:: sourabgupta88

**Comment by kprovance** [comment]
This was fixed some time ago.  If your theme is using an embedded version of Redux, you need to ask your theme author to update to the latest version.
