### ISSUE TITLE
Redux framework not showing the options menu in wp-4.6.1 version

### ISSUE THREAD

**Issue by sahidhossen** [reduxframework/redux-framework#3144]
Here is the code that I have use in function.php file. 
 
`if (file_exists(dirname( __FILE__ ) . '/inc/framework/sample/sample-config.php')) {
    require_once( dirname( __FILE__ ) . '/inc/framework/sample/sample-config.php' );
}else {
    exit();
}`
 

Please late me know what is the problem. 

Thanks
Sahid

**Comment by kprovance** [comment]
Could be an incorrect path, could be the framework isn't loaded.  Hard to say without information required by our support guidelines.  https://github.com/reduxframework/redux-framework/blob/master/CONTRIBUTING.md

**Comment by sahidhossen** [comment]
There are no javascript error and I have use exit() method. So if the path is not valid then it should be blank. I have check the sample-config.php file and its in the right path.

**Comment by kprovance** [comment]
Once again.   https://github.com/reduxframework/redux-framework/blob/master/CONTRIBUTING.md

**Comment by kprovance** [comment]
Maybe this too:  https://docs.reduxframework.com/core/advanced/embedding-redux-into-your-theme-or-plugin/

**Comment by kprovance** [comment]
Closing.  No reply.
