### ISSUE TITLE
How do you hide breadcrumbs?

### ISSUE THREAD

**Issue by kosterstrudel** [reduxframework/redux-framework#3145]
Hey, how do you hide breadcrumbs on posts? Really wonky setup. 
![screen shot 2016-10-06 at 1 38 40 pm](https://cloud.githubusercontent.com/assets/6146583/19169655/439a89aa-8bca-11e6-8a60-b720ce093b5c.png)

**Comment by dovy** [comment]
Hey there. We didn't develop that theme. You'll need to contact the authors. They just used our framework to make your theme better.  ;)

**Comment by kosterstrudel** [comment]
Oh ok. Thanks homie.

**Comment by dovy** [comment]
Best of luck!
