### ISSUE TITLE
support

### ISSUE THREAD

**Issue by waleedelsefy** [reduxframework/redux-framework#3146]
http://support.redux.io/?id=vTg5VLAJUjwaGT0O3CtB7ucJH4hTnt9KS95nV6pM2d%2BHzhrev9A%2BfxNp02Lxpq%2F6SF0ZS3xHMQ1gs47qXcFQMQ%3D%3D

**Comment by kprovance** [comment]
Of course it would be extremely helpful if you could say exactly what the actual issue is?

**Comment by Chatzzz** [comment]
Hello any help i can get would be great.. I bought a wordpress theme "OCULUS" it says it comes with 10+ different layouts.. i am actually new working WP so i need to ask how to apply the different layouts..

thanks!

**Comment by kprovance** [comment]
You need to contact theme theme author for support.  We did not author your theme.
