### ISSUE TITLE
display results

### ISSUE THREAD

**Issue by brody182** [reduxframework/redux-framework#3147]
does not work

```
global $theme_onion;	

register_sidebar( array(
		'name'          => esc_html__( 'Footer 1', 'onion' ),
		'id'            => 'sidebar-2',
		'description'   => esc_html__( 'Add widgets here.', 'onion' ),
		'before_widget' => '<section id="%1$s" class="widget %2$s">',
		'after_widget'  => '</section>',
		'before_title'  => '<h2 class="widget-title" style="background: ' .  $theme_onion['opt-color-copyright'] .'; " >',
		'after_title'   => '</h2>',
	) );
```

**Comment by kprovance** [comment]
Are you running your code under widget_init?  If so, chances are its running before Redux is loaded, and therefore the option is not yet available.  My only guess based on this information.

**Comment by brody182** [comment]
I have this at the top of the functions.php 
`require get_template_directory() . '/admin/admin-init.php';`

**Comment by kprovance** [comment]
That's fine, but I have no idea how you are loading the rest of your theme, specifically the widget register.  If you would like me to debug your actual theme, that's a premium service.  We do not do that for free as it technically not a Redux issue.  Whatever hook you are registering your widgets has to come after the loading of the option panel.  Then it will work fine.

**Comment by brody182** [comment]
i am using unserscore.me

**Comment by brody182** [comment]
ok got it,  I am calling admin-init.php after the widget
