### ISSUE TITLE
Blank site when activating Redux

### ISSUE THREAD

**Issue by bonsaiko** [reduxframework/redux-framework#3150]
Hello,

I installed a theme that I bought which uses redux framework. 
I was working on the theme and everything was fine but after some changes i noticed a blank page for the site. My site was not appearing anymore, only blank pages.
I renamed redux folder (to deactivate it) and then the site appeared again...
Any idea of what could be the problem ?

Thanks

**Comment by kprovance** [comment]
Either server PHP settings or some hook the developer uses.  Sine you purchased the theme from someone else, you need to ask them for support, as the etxt that appeared when you opened the new ticket should have suggested.  Thanks.
