### ISSUE TITLE
Reset section reset to default values rather than presets

### ISSUE THREAD

**Issue by swirltheme** [reduxframework/redux-framework#3151]
Reset section reset to default values rather than presets.
We can understand it by an example,
```php
array(
'id' => 'header_version',
'type' => 'image_select',
'presets' => true,
'title' => __('Header Layout Variations', 'swirl'),
'subtitle' => __('Select the layout you want to use.', 'swirl'),
'required' => array('header_hide', '=', '0'),
'options' => array(
// Array of Header Layout Variations
'1' => array(
'alt' => __('Version 1', 'swirl'),
'img' => ReduxFramework::$url.'assets/img/header_01.png',
'presets' => array(
'top_bar_menu_font_size' => '13',
'top_bar_menu_link_color' => '#000000',
)
),
'2' => array(
'alt' => _('Version 2', 'swirl'),
'img' => ReduxFramework::$url.'assets/img/header_02.png',
'presets' => array(
'top_bar_menu_font_size' => '14',
'top_bar_menu_link_color' => '#123456',
)
)
```
... And more presets continues.
Lets look at two fields and there presets values given above. Two fields lets say 'top_bar_menu_font_size' AND 'top_bar_menu_link_color'

They are defined like this.
```php
array(
'id' => 'top_bar_menu_font_size',
'type' => 'slider',
'title' => _( 'Top bar menu font size', 'swirl' ),
'subtitle' => __( 'Controls the top bar menu font size', 'swirl' ),
'desc' => __( 'In pixels, default is 12', 'swirl' ),
'required' => array('top_bar_display','=', '1'),
'default' => 12,
'min' => 10,
'step' => 1,
'max' => 22,
'resolution' => 1,
'display_value' => 'text'
),
array(
'id' => 'top_bar_menu_link_color',
'type' => 'color',
'required' => array(array('top_bar_display','=', '1')),
'title' => __('Top bar Menu Links color', 'swirl'),
'subtitle' => __('Pick a color for Menu Links in the Top bar (default: #ffffff).', 'swirl'),
'default' => '#ffffff',
'validate' => 'color'
),
```
Ok. Now when we use reset section button it resets values of these fields to their default values rather than values given in preset.
Lets say we choose header Version 1. Then...
Expected Behaviour (On reset section):
top_bar_menu_font_size should reset to 13
top_bar_menu_link_color should reset to #000000
Actual Results (On reset section):
top_bar_menu_font_size should reset to 12
top_bar_menu_link_color should reset to #ffffff

Is there some special setting or option to get this type of behavior.
OR
Redux don't handle it like that
OR
There is some work around to achieve this behavior?

**Comment by kprovance** [comment]
Well, the whole idea of a preset is that the values are preset, in that they cannot be changed.  But if I am reading this correctly, you assigned those IDs to actual fields where they can be changed.  They are going to override the preset, even on reset.  That's how Redux works.  Unless @Dovy threw is some filter hook that I am unaware of, then the field default will always take priority over the preset.
