### ISSUE TITLE
OSS License issues

### ISSUE THREAD

**Issue by veronicaarama** [reduxframework/redux-framework#3153]
Hello,

I'm using version 3.6.0.1 of Redux Framework and i found an inconsistency related to your license references and the declared license on your website and in the license.txt. 

On your official website you say that Redux is under : GPL v2.0
in the license.txt: you have the possibility to go to GPL v3 which is also listed, the entire text of the GPL v3 license appears in the license.txt

In the files containing source code you have: GPL v2 or later reference, but not in all of them as in the below mentioned files the reference is GPL v3 or later.
redux-framework-3.6.0.1\ReduxCore\framework.php
redux-framework-3.6.0.1\redux-framework.php

Please let me know under which version of GPL your code is released, as GPL v2 is incompatible with GPL v3.0, therefore the above mentioned files are actually in conflict with your other files under GPL v2.

I also observed that your first release 3.0.0-beta contains in the license.txt file the entire text of the GPL v2, still in the next release 3.0.4 you upgraded the license to GPL v3 full text, but still no mentions about the changes in the changelog files.

I would kindly encourage you to allign all your references and licenses as from a user perspective it is very difficult to know under which license i'm using your code.

Thank you in advance,

Kind regards,

Veronica

**Comment by kprovance** [comment]
@Dovy?  This is your area.

**Comment by dovy** [comment]
We're using GPL2 here.  ;)   @kprovance care to take out v3 everywhere and replace with v2? Thanks.

**Comment by kprovance** [comment]
updated
