### ISSUE TITLE
fixed dynamically updating css file

### ISSUE THREAD

**Issue by udarts** [reduxframework/redux-framework#3154]
Hi guys,

I was struggling with the dynamic updating of the css file, which on the wiki page didn't work anymore: 
https://docs.reduxframework.com/core/advanced/updating-a-css-file-dynamically/

So I started to dig a bit in the code and found 2 lines in the framework.php file on lines 2394 and 2892:

Change this line:
`do_action( "redux/options/{$this->args['opt_name']}/compiler", $this->options, $this->compilerCSS, $this->transients['changed_values'] );`

To this:
`do_action( "redux/options/{$this->args['opt_name']}/compiler", $this->compilerCSS );`

And then change the code from the doc page (mentioned above), to the following:

`add_filter('redux/options/' . $opt_name . '/compiler', 'compilerCSS', 10, 3);`

`if ( ! function_exists( 'compilerCSS' ) ) {
        function compilerCSS( $css ) {
            global $wp_filesystem;
            require_once( ABSPATH . 'wp-admin/includes/file.php' ); // We will probably need to load this file
            global $wp_filesystem;
            $upload_dir = wp_upload_dir(); // Grab uploads folder array
            $dir = trailingslashit( $upload_dir['basedir'] ) . '/redux/'; // Give it a name
            WP_Filesystem(); // Initial WP file system
            $wp_filesystem->mkdir( $dir ); // Make a new folder for storing our file
            $wp_filesystem->put_contents( $dir . 'dynamic-style.css', $css, 0644 ); // Name your css file
        }
    }`

This seems to work with me.

Let me know if this works for anyone else. If so, maybe the developers of redux can add/change this code to the main code and doc page.

Cheers,

**Comment by kprovance** [comment]
That will completely break backward compatibility, changing that filter.  I'm sorry, but we won't do that.

**Comment by udarts** [comment]
Why is that actually? I have looked at the code and it seems that the compiler action (of lines 2394 and 2892) wasn't doing anything, basically useless. The only thing working is the output to display the inline styling in the head.
So a bit more explaining would be nice as to why it would break the backward compatibility.

Thanks

**Comment by kprovance** [comment]
You want to change

```php
do_action( "redux/options/{$this->args['opt_name']}/compiler", $this->options, $this->compilerCSS, $this->transients['changed_values'] );
```

To this:
```php
do_action( "redux/options/{$this->args['opt_name']}/compiler", $this->compilerCSS );
```

Well, in my theme, I use all three parameters of the compiler hook.  Take two away and my theme breaks, not to mention the hundreds of others out there that also will if they use the other parameters.  Why would I willingly break our code?  Sorry, but I am not doing that.  @Dovy won't either.  We have a very, very strict policy about backward compatibility.

**Comment by udarts** [comment]
Ah, wait, I have changed the filter back and used the following code (modified from the docs page) and it seems to work:

`add_filter('redux/options/' . $opt_name . '/compiler', 'compiler_action', 10, 3);

   if ( ! function_exists( 'compiler_action' ) ) {
        function compiler_action( $options, $css, $changed_values ) {
            global $wp_filesystem;

            require_once( ABSPATH . 'wp-admin/includes/file.php' ); // We will probably need to load this file
            global $wp_filesystem;
            $upload_dir = wp_upload_dir(); // Grab uploads folder array
            $dir = trailingslashit( $upload_dir['basedir'] ) . '/redux/'; // Set storage directory path

            WP_Filesystem(); // Initial WP file system
            $wp_filesystem->mkdir( $dir ); // Make a new folder for storing our file
            $wp_filesystem->put_contents( $dir . 'dynamic-style.css', $css, 0644 );  // Naming of file
        }
    }`

Now I am not changing the the filter.

**Comment by udarts** [comment]
Were you able to look at my last code?

**Comment by kprovance** [comment]
What part are we talking about?  If it's about changing the compiler hook, I already said that cannot happen.

**Comment by udarts** [comment]
No, no not the compiler hook.
I checked the code (function) which is on the page: https://docs.reduxframework.com/core/advanced/updating-a-css-file-dynamically/

And updated that code, which works, without changing the compiler hook.

if ( ! function_exists( 'compiler_action' ) ) {
function compiler_action( $options, $css, $changed_values ) {
        require_once( ABSPATH . 'wp-admin/includes/file.php' ); // We will probably need to load this file
        global $wp_filesystem;
        $upload_dir = wp_upload_dir(); // Grab uploads folder array
        $dir = trailingslashit( $upload_dir['basedir'] ) . '/redux/'; // Set storage directory path
        WP_Filesystem(); // Initial WP file system
        $wp_filesystem->mkdir( $dir ); // Make a new folder for storing our file
        $wp_filesystem->put_contents( $dir . 'dynamic-style.css', $css, 0644 );  // Naming of file
    }
}

**Comment by kprovance** [comment]
Ill update it when I get the chance, but to anyone reading, this is not supported by us any longer, due to permission issues some servers have,  It's 'as is'.

**Comment by udarts** [comment]
I think that's why it is in the upload directory, which usually is accessible (in most cases). If I tried the code to upload it in the theme directory it would fail (agreed with the permissions issue), so that's why I located the file in the upload folder, then no issue there.
