### ISSUE TITLE
Website down

### ISSUE THREAD

**Issue by ismaelyws** [reduxframework/redux-framework#3155]
Hi Guys,

Trying to access your documentation and getting a 502 error.

https://docs.reduxframework.com/core/advanced/wpml-integration/

**Comment by dovy** [comment]
Wow, Linode is having issues even on their name site. Must be under attack.

Soon I'll be moving to Google Cloud Platform and these things will be something of the past. 

Rebooting the box. All should be good in a few mins.

**Comment by ismaelyws** [comment]
thanks :)
