### ISSUE TITLE
SVG images in gallery

### ISSUE THREAD

**Issue by nr1q** [reduxframework/redux-framework#3159]
Hello, first of all thanks for such a useful plugin!

I'm developing a theme that uses svg files inserted in a 'gallery' type, and I found a javascript error that breaks the image insertion after saving the gallery. I found a way to solve this by adding a check which you can see in the diff output below. I hope you can add this change because is not svg-specific and will help me to not edit the file on every update. :) Thanks!

    --- field_gallery.js    2016-10-28 16:56:44.000000000 -0500
    +++ field_gallery_.js   2016-10-28 16:56:57.000000000 -0500
    @@ -92,7 +92,7 @@
                                         var ids = selection.models.map(
                                             function( e ) {
                                                 element = e.toJSON();
    -                                            preview_img = typeof element.sizes.thumbnail !== 'undefined' ? element.sizes.thumbnail.url : element.url;
    +                                            preview_img = (typeof element.sizes !== "undefined" && typeof element.sizes.thumbnail !== 'undefined') ? element.sizes.thumbnail.url : element.url;
                                                 preview_html = "<a class='of-uploaded-image' href='" + preview_img + "'><img class='redux-option-image' src='" + preview_img + "' alt='' /></a>";
                                                 current_gallery.find( ".screenshot" ).append( preview_html );

**Comment by kprovance** [comment]
Added in v.3.6.2.1

**Comment by hugocorenzan** [comment]
I'm using 3.6.5 and still have this problem. http://g.recordit.co/pv4EnZJqAu.gif

**Comment by kprovance** [comment]
The gallery field and the media field are not the same thing.  Also, please upgrade Redux, and please do not piggyback old tickets.
