### ISSUE TITLE
Issue Deleting Repeater Items

### ISSUE THREAD

**Issue by Ryuske** [reduxframework/redux-framework#3162]
I have a few post types that use your metaboxes. When using the repeater, the "delete thing" doesn't work for the last 2. It will remove them visually, but when you update the page, the 2nd to last one get deleted, but not the very last one.

To reproduce: Go to anywhere with a repeater metabox. Add 3 items. Delete all 3 at once & click Update. Check & make sure there are no repeater items (there shouldn't be, but there are).

* Note: If you remove all the content from the repeater items (images, text, etc) then it will delete the items without any issues.

**Comment by kprovance** [comment]
Hi.

Please post all Redux extension issues to the extension issue tracker.  When posting, PLEASE including your purchase code and a support URL.  Thanks.

https://github.com/reduxframework/redux-extensions
