### ISSUE TITLE
Redux WordPress Customizer Update

### ISSUE THREAD

**Issue by gordo019** [reduxframework/redux-framework#3163]
I was hoping to see the issues with Redux theme options and the WordPress Customizer worked out. Did the developers ever get to this? It would be great to hear an update. I would support this effort if there was any hope but maybe the project has already died? The Redux website doesn’t seem to have any updates.

**Comment by kprovance** [comment]
It's @dovy's project.  He'll have to be the one to update you on if it's ever going to happen or not.

**Comment by Moutaz-homsi** [comment]
I would support this effort too if there is any willing to release the Advanced Customizer Extension .

**Comment by gordo019** [comment]
@dovy? What’s the word?

**Comment by Kieran-Calvert** [comment]
Are there any plans to release the Advanced Customiser Extension?

**Comment by kprovance** [comment]
This extension seemed to have been shelved for the time being.  Closing the issue.

**Comment by dovy** [comment]
I'm planning to release it sooner than you might think. I'm just trying to make it perfect. Had some 4.7 updates that needed to be added in.  ;)
