### ISSUE TITLE
Themeforest want me to remove api key

### ISSUE THREAD

**Issue by kowsar89** [reduxframework/redux-framework#3165]
One of the reason our theme got soft rejected because of using api key in config file. Details:

> #. Please remove personal API key: http://envato.d.pr/O2Oy

I got another issue too by reviewer:

> #. Please remove: http://envato.d.pr/uzEA

Any suggestion?

**Comment by kprovance** [comment]
Well, you can either remove it, or explain to them it's necessary to keep Google fonts updated, even thought we do that ourselves.  Those are the only two options.  We have no control of TF and their ever drastic and draconian criteria.

**Comment by kowsar89** [comment]
@kprovance What problems i might face if i remove API key?

**Comment by kprovance** [comment]
Google fonts won't update weekly.
