### ISSUE TITLE
PHP 7 compliance issue

### ISSUE THREAD

**Issue by khaledMohammed000** [reduxframework/redux-framework#3167]
## Any Error Details (PHP/JavaScript)
https://github.com/ahmedkaludi/Accelerated-Mobile-Pages/issues/194

**Comment by kprovance** [comment]
Without any version information, specifically Redux, it's impossible to say.  As far as I know, all these things have been resolved.  So have them ensure they are using the latest version.

**Comment by khaledMohammed000** [comment]
Version : 3.5.7.8

**Comment by kprovance** [comment]
We're up to 3.6.2.1 now.
