### ISSUE TITLE
Possible Unhandled Promise Rejection (id:0): undefined is not an object

### ISSUE THREAD

**Issue by dijimon** [reduxframework/redux-framework#3168]
I have a strange error in Redux framework
Here is description:
http://stackoverflow.com/questions/40606126/possible-unhandled-promise-rejection-id0-undefined-is-not-an-object

**Comment by kprovance** [comment]
We are Redux Framework for WordPress.  We are NOT in ANY way affiliated with that whole react.js project.  That guy who is calling himself Redux ganked our name, and now there is all this confusion.  Sorry.
