### ISSUE TITLE
Trouble with browser in development mode

### ISSUE THREAD

**Issue by stodorovic** [reduxframework/redux-framework#3169]
## Support Hash
I had big trouble because this plugin dump all queries together with all objects and browser is always crashing (because there are a lot of data). This line:

https://github.com/reduxframework/redux-framework/blob/master/ReduxCore/core/panel.php#L106

All developers can use very good plugin:

https://github.com/johnbillion/query-monitor
https://wptavern.com/query-monitor-a-remarkably-comprehensive-debugging-plugin-for-wordpress

So, I don't see any reason for print_r, because I can't enable debug mode for development. Please remove this code.
## Steps to reproduce
Enable WP_DEBUG (need for developers) and open theme options.
## Expected Behavior
Open page
## Actual Behavior
dump a lot of data and browser is crashing (125MB texts before Firefox is crashed)

**Comment by stodorovic** [comment]
#2946 I can confirm it. If PHP buffering is enabled, it's possible. Anyway, it blocks browser. We just tested various browsers.
It seems that's issue related to combination of plugins (included Query Monitor which is one of the best plugin for debugging) - some plugins store objects into $wpdb->queries.

Possible workaround:
```php
foreach ( $wpdb->queries as $query ) {
	echo trim( $query[0] ) . "\n";
}
```

**Comment by kprovance** [comment]
Removed.  Not sure why it was still in there.  

Also, please feel free to donate to this project.  Support from developers helps keep us going.

Thanks.
