### ISSUE TITLE
Theme Check Warnings: wp_deregister_script

### ISSUE THREAD

**Issue by ashffaq** [reduxframework/redux-framework#3170]
Sorry if this is not a right place to ask question.

I have been seeing the following Theme Check Warnings with Redux Framework.

WARNING: Found wp_deregister_script in inc/framework/redux-framework/framework.php. Themes must not deregister core scripts.
Line 565: wp_deregister_script( 'wpb_ace' );

WARNING: Found wp_deregister_script in inc/framework/redux-framework/core/enqueue.php. Themes must not deregister core scripts.
Line 215: wp_deregister_script( 'jquerySelect2' );

Can you please help on that?

**Comment by kprovance** [comment]
Answered via Slack, and multiple times on this issue tracker.

**Comment by ashffaq** [comment]
Thanks.
