### ISSUE TITLE
My web is very slow using redux framework plugin

### ISSUE THREAD

**Issue by rsvidal** [reduxframework/redux-framework#3174]
Hi, My web uses the Redux Framework Plugin, integrated in 'VG Optima' theme.
When I active Redux Framework Plugin, the web is very slow.
If I desactive the Redux Framework Plugin, the web is very fast.
Note: I have created the directory redux into uploads directory.
How can i know the cause?
Can I optimize this plugin?
Regards.
Rafael.

**Comment by kprovance** [comment]
Redux is a tool for developers to include an options panel in their project. Consequently, we do not offer support for folks who have purchased a theme or plugin that uses Redux. The responsibility of support for themes and plugins falls upon it's author. We realize that some authors have included support links for Redux in their projects, when they should not have. We do apologize for that confusion and are taking steps to remedy this confusion.

**Comment by rsvidal** [comment]
Hi,
Ok, thanks.
I have written to the theme's author.
Regards.
Rafael.
