### ISSUE TITLE
Multiple instances of Redux Google Fonts

### ISSUE THREAD

**Issue by Nyota** [reduxframework/redux-framework#3176]
While working with a theme and a plugin that both use the Redux framework, I came across something curious while getting Google Fonts to update using the google_fonts_api feature. The plugin and theme both have unique opt_name and page_slug to avoid interference. Is there anything else that needs to be considered when setting up the framework, to make sure it can run smoothly? The Google Font typography field is only active within the theme, the plugin is not using the field at all. 

I noticed that while Redux within the theme loads an updated version of the googlefonts.php file, it still taps into the outdated googlefonts.php file found within the plugin folder. I then tried to echo out some random text from field_typography.php just to test it, but it would only show if the plugin had been deactivated. As soon as the plugin was active again, my edit would disappear. I tried a couple of other fields and had the same result, which has lead me to believe that there is some kind of interference happening. Under any other circumstance, this probably wouldn't be an issue, but since I would love to have access to the update feature of Google Fonts, I can't have it loading an older file from a different folder.

**Comment by kprovance** [comment]
I cant answer any of this without the information we asked you to provide when you opened a new issue.   The alternative is to pay for premium support, and we can spend an hour with me asking you questions to get the information we need.  Please, open a new issue, read ALL of the text carefully and provide the necessary information.  Thanks!

**Comment by Nyota** [comment]
Hey there, sorry about that. I'll re-write it, no problem.

## Support Hash
Created a support hash: http://support.redux.io/?id=Y562a46PYDpJy8iRxTNEVzW06O1HGYWXLFYcFZGz69yIFg4tbgDOTA%2Fy0Ru1%2B84L9GIZdnHBsvoXBVzvStZCOg%3D%3D

## Steps to reproduce
Activate two instances of Redux (in a theme and a plugin in my case) and update googlefonts.php in only one copy of Redux.
 
## Expected Behavior
Redux running within the theme should load fonts from it's own, updated version of googlefonts.php

## Actual Behavior
Instead it's loading older version of googlefonts.php from the plugin. Same for other fields.

## Any Error Details (PHP/JavaScript)
No errors, checked WordPress dubug log, Firebug console, sever logs, couldn't find anything.

**Comment by kprovance** [comment]
What you want isn't possible.  It sounds like you are embedding Redux into the plugin and the theme.  While multiple instances of Redux are possible, only ONE Redux core will load.  The priority is this:  Redux plugin, Redux embedded in a plugin, Redux embedded in a theme.  The embedded version of Redux in your plugin takes priority.  I can't be changed as this priority is by design.  The only other option available is to run Redux as a plugin, which case the two projects will share that core.

**Comment by Nyota** [comment]
Got it, thanks for the reply.
