### ISSUE TITLE
Cannot import theme options file

### ISSUE THREAD

**Issue by ghostpool** [reduxframework/redux-framework#3178]
http://support.redux.io/?id=K3oM06Q5hZ8f41cNs%2BRfoiY7CMtM8o8UIe4Sp5LIvtazLyf8NKtqaQa6uxtkScpaSCW5Q%2FRstihjtR6wsjBRlg%3D%3D

Go to the Theme Options Redux page, click the Import / Export tab, click Import File.

I expect to see an upload section to upload the export file.

Instead a text box appears.

No errors reported.

**Comment by kprovance** [comment]
There has never been an upload button for import.  It's always been a text field to enter the export data into.
