### ISSUE TITLE
Download Not Found on Update

### ISSUE THREAD

**Issue by Fencer04** [reduxframework/redux-framework#3179]
When I try to update it using Wordpress updater I get a message saying download not found. I'm able to manually download it from the plugin page though. Any idea what could cause this? I'm trying to go from version 3.6.2 to 3.6.3.

**Comment by dovy** [comment]
@Fencer04 Are you trying to run it from WordPress.org?

**Comment by Fencer04** [comment]
I'm running it in my admin. I'm guessing that is where it is trying to access it.

**Comment by theghall** [comment]
Click on Dashboard in the Admin Panel (just to make the explanation easier as you will see what I am talking about just about anywhere). You will see the box near the top of the screen where it says: There is an update available for: Redux Options Framework. Begin updating plugin. Click on 'Begin updating plugin' and it should work.

**Comment by Fencer04** [comment]
It ended up working last night. I imagine it was just an issue with the repository. Thanks for the solid support though. Top notch.
