### ISSUE TITLE
Whitepage happens in WP Admin after activating this plug-in in the past 7 days

### ISSUE THREAD

**Issue by coderighter** [reduxframework/redux-framework#3181]
## Steps to reproduce
I am using the Care Plugin that I purchased from ThemeForest.  The theme requires use of this plug-in.  For the past 3 days or so when I have the Redux Plugin activated my wordpress admin access breaks - i just get white page when visiting any admin area.  I am using version 3.6.3 of the plug-in (which I just updated to today).  The same issue was happening with the prior version as well.

## Expected Behavior
I expect to be able to activate this plugin without seeing a white page as soon as its active.

## Any Error Details (PHP/JavaScript)
I see this error in the error log:

PHP Fatal error:  require_once(): Failed opening required '/home2/petiteg1/public_html/test/wp-content/themes/care/lib/redux/redux-settings.php' (include_path='.:/usr/php/56/usr/lib64:/usr/php/56/usr/share/pear') in /home2/petiteg1/public_html/test/wp-content/themes/care/lib/init.php on line 23

**Comment by kprovance** [comment]
This is an issue with the theme, and you'll have to contact the theme author for support.  We did not author the theme.
