### ISSUE TITLE
Required update file not found

### ISSUE THREAD

**Issue by jobromedia** [reduxframework/redux-framework#3182]
So I'm installing the required update, and I get this:

Installing Plugin: Redux Framework
Downloading update from https://downloads.wordpress.org/plugin/redux-framework.3.6.3.zip…
Download failed. Not Found

**Comment by kprovance** [comment]
https://downloads.wordpress.org/plugin/redux-framework.3.6.3.zip

**Comment by theghall** [comment]
Click on Dashboard in the Admin Panel (just to make the explanation easier as you will see what I am talking about just about anywhere).  You will see the box near the top of the screen where it says: There is an update available for: Redux Options Framework.  Begin updating plugin.   Click on 'Begin updating plugin' and it should work.

**Comment by iamkingsleyf** [comment]
File not found, from dashboard to wp.org

**Comment by theghall** [comment]
> File not found, from dashboard to wp.org

Not sure why it worked for me and not you.  In another thread I think someone said they tried updating from within the Plugin menu and it worked.

**Comment by kprovance** [comment]
The WP dashboard encompasses quite a large area. Could you be more specific where you are attempting to install the update from? A screenshot would be helpful.

**Comment by theghall** [comment]
Clicking update here is what worked for me:
![dashboad_shot](https://cloud.githubusercontent.com/assets/24413773/21077472/6c476f02-bf1a-11e6-9ca8-09e5dbaf6acf.png)

Clicking update here did not work for me:
![plugin_entry](https://cloud.githubusercontent.com/assets/24413773/21077475/7be1fe6e-bf1a-11e6-96a8-0c0cbf5ca03e.png)

But it seems for iamkingsleyf the top example did not work for him.

**Comment by kprovance** [comment]
Okay, thanks.  I was able to reproduce the issue.  It looks like there is something funky going on, on the wp.org side.  I brought it to Dovy's attention.  We're going to do a new upload here soon, which hopefully will fix whatever went wrong over there.

**Comment by Rahisaiful** [comment]
When I install redux by tgm activation it's show an error.
![redux-problem](https://cloud.githubusercontent.com/assets/13090193/21130969/111abe9a-c136-11e6-8b33-2829a1c11d2f.png)

any solution ?

**Comment by iamkingsleyf** [comment]
download from  github and install

**Comment by Rahisaiful** [comment]
I got a solution. I have used the code below in tgmpa and now it's working fine.

        array(
            'name'      => __('Redux Framework', 'ecohosting'),
            'slug'      => 'redux-framework',
            'source'   => 'https://github.com/reduxframework/redux-framework/archive/master.zip',
            'version'   => '',
            'required'  => true,
        ),

**Comment by kprovance** [comment]
The issue at wp.org seems to have resolved itself.
