### ISSUE TITLE
404 File not found

### ISSUE THREAD

**Issue by iamkingsleyf** [reduxframework/redux-framework#3183]
Hello;

I am trying to install the plugin i keep getting **404 File not found** error, from wordpress dashboard to wp.org plugin page.

I use WP4.7

**Comment by caygri** [comment]
I have the same error!

**Comment by kprovance** [comment]
The WP dashboard encompasses quite a large area.  Could you be more specific where you are attempting to install the update from?  A screenshot would be helpful.

**Comment by iamkingsleyf** [comment]
@kprovance somehow i mistakenly deleted it, so i was looking for the theme option when i noticed its missing. so i went to Appearance >> install plugins {no luck}

went to wp-admin/plugins and search for it, it appeared from the search results but when i click install i got 404 error.

same error in wp.org plugins page. so i downloaded from Github

**Comment by kprovance** [comment]
Yeah, sorry, I meant to post back after doing some research.  There is something funky going on with the upload to wp.org.  I notified Dovy about it (he's the one who manages that).  He's going to do a new upload here soon to rectify the issue, hopefully.

**Comment by iamkingsleyf** [comment]
alright

**Comment by mko-x** [comment]
Didn't work for me either - with opened dev tools for analysis it worked.

**Comment by kprovance** [comment]
The issue at wp.org seems to have resolved itself.
