### ISSUE TITLE
Required argument in the callback function does not work in Redux Framework

### ISSUE THREAD

**Issue by ayanize** [reduxframework/redux-framework#3184]
Hello Dev,

I am using Redux Framework in our theme and I am really loving this. Thanks for this awesome software. 

I have an issue with the Required argument and Callback function. Here is a sample file in my config file

Pastebin: http://pastebin.com/shtV3FQq

`
<?php
Redux::setSection( $opt_name, array(
        'title'      => __( 'Title', 'redux-framework-demo' ),
        'id'         => 'switch_buttonset-set',
        'desc'       => __('Select the Site Title'),
        'subsection' => true,
        'fields'     => array(
            array(
                'id'       => 'opt-button-set',
                'type'     => 'button_set',
                'title'    => __( 'My Title', 'redux-framework-demo' ),
                'subtitle' => __( 'My Sub Title', 'redux-framework-demo' ),
                'desc'     => __( 'Some description', 'redux-framework-demo' ),
                'options'  => array(
                    '1' => 'Default Title',
                    '2' => 'Custom Title',
                ),
                'default'  => '1'
            ),
            array(
                'id'       => 'my_id',
                'type'     => 'callback',
                'required' => array('opt-button-set','equals','2'),
                'title'    => __( 'Test Field', 'redux-framework-demo' ),
                'desc'     => __('Some Description'),
                'callback' => 'my_callback'
),
?>
`

And this is my callback function 

<?php`
function my_callback(){

    echo 'Some callback functions here'
}
?>
`

But the problem is the **Required** argument does not seem to work. The **Test field** continues to be displayed regardless of the options selected in the buttons set.

Thanks in advance.

Deep

**Comment by kprovance** [comment]
You didn't include the support URL, that is required information.

**Comment by kprovance** [comment]
Also, I'm not entire certain required works on the callback field, as there is no HTML used to render such a field where the Redux core actually add classes used in required.d  @Dovy?

**Comment by ayanize** [comment]
Sorry I missed the URL here it is http://support.redux.io/?id=VM%2F%2FE%2BLFRuiNLMJmfIPhFE7Jl9YZsAC62jDVPg5q%2F4routz8uyb%2BFFCLMBdYdLe%2FljtpssQz0Cz5WnZ06N1J8Q%3D%3D

**Comment by ayanize** [comment]
I figured it out. I needed to mirror the exact output in the callback function. Thanks. But I would still love to have some clear documentation about this. 

You can close this ticket now.
