### ISSUE TITLE
Multi_text field cannot be saved as empty if it has a default value set

### ISSUE THREAD

**Issue by antoniomangiacapra** [reduxframework/redux-framework#3186]
Hello there,

I am not sure if this is a bug or if I have not very clear the expected behavior, in this case I apologize in advance.

http://support.redux.io/?id=6zivwWjrPNRqe1Q%2FzTxrmah24tzmhW7M8LxePE929%2BU8bKrNIFISI0VqNQp6BU6rhVb5Je%2BI%2Fp9j%2FD3IKIPpTg%3D%3D

I created a new section containing a multit_ext
```
Redux::setSection( $opt_name, array(
	'title'  => esc_html__( 'Header', 'textdomain' ),

	'fields' => array(
		array(
			'id'=>'staticblock-right-logo',
			'type' => 'multi_text',
			'title' => __('Primary navigation: near logo', 'textdomain'),
			'validate' => 'html',
			'subtitle' => __('Static blocks in the primary navigation, on the right of the logo', 'textdomain'),
			'desc' => __('You can use html tags and shortcodes here', 'textdomain'),
			'default' => array(
				'<i class="fa fa-phone"></i> +1 (555) 333 22 11'
			)
		),
	)
));
```

STEPS:

1. Active the theme and the plugin
2. You will see the field filled with the default value
3. Leave the field empty or delete the text box and save
4. All is fine, the field is saved as an empty field
5. Reload the page, save again the settings and the field will contains again the default value

Please explain me what is the expected behavior, because I think that here there is bug anyway.

Thank you in advance.

P.S.: I wanted to ask this on slack before there. I requested the invite but slack says me that I have already received it, but I can't find it in the email :/

**Comment by kprovance** [comment]
I loaded your config and am not seeing this behaviour at all.  I took all the steps you described.  I saved the empty box and reloaded the page.  No box appears at all, which is normal.  Empty text boxes are not supposed to be displayed and are ignored when saving.

**Comment by kprovance** [comment]
Fixed in v.3.6.3.1.  Please note however that when the show_empty argument is not set to false, a default text box will be displayed when nothing is saved.  Also, because of the way this fix was addressed, it is recommended you check any option using this field with empty() or is_array() for any foreach() call.

**Comment by antoniomangiacapra** [comment]
Hi kprovance, thank you for your reply and sorry for the delay. I was going to publish a screen record, but I think it's useless now. If you still want have a look to be sure let me know ;)

**Comment by dovy** [comment]
@antoniomangiacapra please do verify the fix works as you would hope. We like to make sure we finish the job.  ;)

**Comment by antoniomangiacapra** [comment]
Sure @dovy, I'll do it on tomorrow o on monday morning and I'll keep you posted.

Thank you so much again :)

**Comment by antoniomangiacapra** [comment]
I confirm that after the update it works like a charm :)
