### ISSUE TITLE
PHP7 Compatibility Checker error

### ISSUE THREAD

**Issue by svaravindam** [reduxframework/redux-framework#3189]
Currently we are using 'PHP 5.5.9-1ubuntu4.20', and we would like to update it to php7. We have tested the compatibility of the plugin "redux-framework" In 'PHP Compatibility Checker' plugin and it shows 1 error as follows:

([https://wpengine.com/blog/php-7-compatibility-checker-plugin/](https://wpengine.com/blog/php-7-compatibility-checker-plugin/))

 
FILE: /nas/content/live/ishopsev/wp-content/plugins/redux-framework/ReduxCore/inc/validation/preg_replace/validation_preg_replace.php 

------------------------------------------------------------------------------------------------------------------------------------- 

FOUND 1 ERROR AFFECTING 1 LINE 

------------------------------------------------------------------------------------------------------------------------------------- 

 30 | ERROR | preg_replace() - /e modifier is deprecated since PHP 5.5 and removed since PHP 7.0 

FILE: /nas/content/live/ishopsev/wp-content/plugins/redux-framework/ReduxCore/inc/validation/preg_replace/validation_preg_replace.php 

------------------------------------------------------------------------------------------------------------------------------------- 

FOUND 1 ERROR AFFECTING 1 LINE 

------------------------------------------------------------------------------------------------------------------------------------- 

 30 | ERROR | preg_replace() - /e modifier is deprecated since PHP 5.5 and removed since PHP 7.0 

-------------------------------------------------------------------------------------------------------------------------------------

 

 

Kindly fix the problem for PHP7.

 

Thanks 

Ramakrishna Math 

Chennai

**Comment by kprovance** [comment]
Don't use the preg_replace valifation, and you'll be fine.

**Comment by dovy** [comment]
And if you have a suggestion on how we can provide both, we'll gladly implement!  :)

**Comment by kprovance** [comment]
updated preg_replace to preg_replace_callback in v3.6.3.2
