### ISSUE TITLE
Is there a way to show a field only in Theme Options and not in Customizer?

### ISSUE THREAD

**Issue by phoenix23590** [reduxframework/redux-framework#3191]
Hello,

I've just started with the Customizer functionality of Redux. Is to be able to have fields that only show up in the Theme options and not in the Customizer? Right now, I'm able to make a field appear in Customizer and not in Theme options by using the 'panel' => false. 

And is to be able to move all sections to custom new panel only in Cutomizer? 

Please let me know about this and thank you very much for all the previous support and for this wonderful framework.

**Comment by kprovance** [comment]
See the customizer_only argument for sections and fields:

https://docs.reduxframework.com/core/sections/getting-started-with-sections/

In the future, please review the text in the new issue window and provide the required information.  None was included.
