### ISSUE TITLE
switch (On/Off) field with function call when set to on

### ISSUE THREAD

**Issue by juavenel** [reduxframework/redux-framework#3192]
I have wrote a plugin and i need to call a function in this plugin when a switch (On/Off) field is set to On.

How to achieve this ? please

**Comment by ayanize** [comment]
See how the output was call in this example https://docs.reduxframework.com/core/fields/switch/

**Comment by juavenel** [comment]
Yes, but I have to catch the changement of value. Not simply get the value

**Comment by kprovance** [comment]
https://docs.reduxframework.com/core/advanced/integrating-a-compiler/

Example included in the sample-config.php
