### ISSUE TITLE
Saving data programmatically

### ISSUE THREAD

**Issue by kajdzo** [reduxframework/redux-framework#3194]
Hi guys,
I'm developing a theme, and I use Redux Framework for theme options. Works great. I have a question and I couldn't find the answer on it so I wanted to check with you guys is there a some action for saving theme options programmatically. 
Thanks.

**Comment by kprovance** [comment]
Individually, using the ReduxAPI

Redux::setOption ($opt_name, $key, $option );

Replace opt_name with your panels opt_name argument.  Key and option should be self explanatory.

**Comment by kajdzo** [comment]
Thanks for your help :)
