### ISSUE TITLE
Repeater Extension & PHP 7.1

### ISSUE THREAD

**Issue by Bluxart** [reduxframework/redux-framework#3195]
WordPress 4.7
Redux Framework: 3.6.3 Plugin ( Latest WP.org Release )
Repeater Extension: 1.0.4

Hi, I used the repeater extension and with PHP 7.1 not work and break the wordpress functionality.

I can navigate in wordpress admin area, but when edit a page, post or custom post type appear this ( some fields about repeater ): https://cl.ly/272C2m0d2i10

This error appear if present the repeater field in a metabox or theme options panel.

If I use for example a version of PHP < of 7.1 all works perfectly without any problem.

## Support Hash
I cannot generate the support URL, generate an error: https://cl.ly/1L1p2O283u0R

## Steps to reproduce
Create a repeater field in a metabox ( redux metabox ) or inside a theme options create this error.

## Any Error Details (PHP/JavaScript)
Any error in console log or error_log

**Comment by kprovance** [comment]
Extension issues go on the extensions issue tracker, please

**Comment by Bluxart** [comment]
I have made some test and now with PHP 7.1.
If used the Repeater Field and the RGBA field I have this error: https://cl.ly/250p273S0l09

Now I have opened an issue here but without response: https://github.com/reduxframework/redux-extensions/issues/312

**Comment by kprovance** [comment]
It's @Dovy's extension.  It's up to him to sort this out.  Sorry.

**Comment by dovy** [comment]
@Bluxart Send me an email: dovy@reduxframework.com and I have something for you to try.  ;)

**Comment by Bluxart** [comment]
@dovy Thanks. I sent the email.

**Comment by Bluxart** [comment]
@dovy I tested your solution but I have the same errors and WordPress break, take a look: https://cl.ly/3O1Y1Z2m0625

This error appear only if inside the repeater is present the color_rgba field. In fact if I changed the rgba field into the simple color field, all works correctly.

**Comment by dovy** [comment]
Then this is an issue with the color_rgba field.  ;)

I'll give it a go on my end.

**Comment by dovy** [comment]
Do a pull from the redux-framework repo, I think I know the issue. Pushed a JS fix today.

It should be working now as expected.

**Comment by kprovance** [comment]
What is 'serialized_repeater'?  Is that a custom modification?

**Comment by dovy** [comment]
The new repeater.  ;)
