### ISSUE TITLE
Notes concerning the compatibility with PHP 7.0.13

### ISSUE THREAD

**Issue by kenshiwara** [reduxframework/redux-framework#3196]
**Topic:** Compatibility with PHP 7.0.13
**Tested on:** XAMPP -> PHP 7.0.13
**WordPress Version:** 4.7
**Redux Framework Plugin Version:** 3.6.3

**[Note 1]**
FILE: redux-framework/ReduxCore/inc/validation/preg_replace/validation_preg_replace.php
LINE: 30 | preg_replace() - /e modifier is deprecated since PHP 5.5 and removed since PHP 7.0

**[Note 2]**
FILE: redux-framework/ReduxCore/inc/browser.php
LINE: 113 | Use of deprecated PHP 4 style class constructor is not supported since PHP 7.0

**Comment by kprovance** [comment]
Already been addressed and updated via another ticket.

**Comment by kenshiwara** [comment]
The issue has indeed been fixed in version 3.6.3.2.
Thank you very much for pointing that out.
