### ISSUE TITLE
FEATURE REQUEST: Validation Inside Field Class on Save

### ISSUE THREAD

**Issue by dovy** [reduxframework/redux-framework#3197]
Requested by @Enchiridion

Add a method within a field class that validates the data on save. This would be extremely useful for our needs as well with extensions. Make this static.

On load of fields, check each method. Make a hidden input field that outputs the fields that have these methods. Then submit them on post, include only those field names, and run those callbacks before anything else.

Also add a variable inside the class that sets forced save stop to true (or something like that). Basically if validation fails, stop ALL saving regardless (no other options) and return the error.

Feel free to chime in for any other features.

**Comment by kprovance** [comment]
But...isn't that already how it works now?  When validations don't pass, saving stops...at least with Ajax save enabled.

**Comment by rpto** [comment]
Hello
I can't edit my alika theme anymore after provider change. the body font can't be changed anymore.  related to wordpress 4.9.6? or what can I do?

**Comment by kprovance** [comment]
We are not the developer of your theme.  You must contact the author for support, which is not us.
