### ISSUE TITLE
Redux Builder

### ISSUE THREAD

**Issue by mtaddia** [reduxframework/redux-framework#3199]

**Comment by mtaddia** [comment]
hi, i used the redux builder and when i download and install it i have two fileds a text filed and a text area which i turned off the text area. Is there not suppoed to be all of the fields added for me? Where is the documenation to use this tool and should there not be a json file to import the modules i defined? no json file not sure what to do or how this builder helps

**Comment by kprovance** [comment]
The buildr does not build actual fields for you, it does not create your option panel for you.  That may be a prmium offering at a later date.  All the builder does is allow you to set your global arguments and install the fields you wish to include with your custom build of Redux.

**Comment by mtaddia** [comment]
yah i found the sample config file it helped alot.

Im on my way great plugin! 

I have one problem though- there is a base64 backgorund image being generated to go in the top grey menu/breadcrumb panel area above the actual main content in the window for redux- this image is missing and broken the base64 image isnt owrking and there is a broken image icon i need to fix this?


On Dec 28, 2016, at 6:34 PM, Kevin Provance <notifications@github.com> wrote:

> Closed #3199.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Michael Taddia
780.222.4244
www.daylightmedia.ca
