### ISSUE TITLE
Problems with Redux with a local installation

### ISSUE THREAD

**Issue by dralnegar** [reduxframework/redux-framework#3203]
Recently the developer who created our companies website has left. We needed to make a change to the site. In order to do this I created a local installation using MAMP, and pulled down the live site using my preferred IDE, Dreamweaver. Initially I was getting the PHP Fatal error: Class 'ReduxFramework_Extension__notes' not found in... error. I deleted the _notes directory, as per a internet source that this should to fix this error. Howver I was still getting a PHP Fatal error: Class 'ReduxFramework_Extension_' error.

The live wordpress installation did show an update available for Redux, which I updated, and pulled down to the local installation, which seemed to fix this issue. However with that done none of the permalinks setup for pages was working.

Any ideas what could be the issue?

**Comment by dralnegar** [comment]
Ouch, sorry about this but it proved an issue with my MAMP installation not running correctly to the permalinks :( needed to setup the options associated with AllowOverride All etc, and it worked

**Comment by dovy** [comment]
Awesome. Glad you got it.

**Comment by dralnegar** [comment]
No, that was an error caused by me pulling our site down using Dreamweaver, which creates the _notes directory. Creating this directory caused the ReduxFramework_Extension__notes class to try and be loaded but it obviously didn't exist, and the whole site wouldn't start.

**Comment by dovy** [comment]
Aha. Now I understand.
