### ISSUE TITLE
wordpress redux php 7

### ISSUE THREAD

**Issue by Fcases** [reduxframework/redux-framework#3204]
seems redux core is trying to get full uri instead of from current path resulting in trying to load js/css from 

/home/blah/

see issue https://github.com/reduxframework/redux-framework/issues/3054

but for anything basically, 

is there a location i can override the url path ?

**Comment by kprovance** [comment]
Could you open a new issue window, please?  This time, read the text provided, and reply with the information we requested.  Thanks.

**Comment by Fcases** [comment]
you can close it, im in the wrong area for this. ill contact theme provider.. but since you will get people coming here, for sakes of letting them get a fix, here is how to fix 

in custom child theme.. in functions.php override avada theme redux url
```

function theme_enqueue_styles() {
    wp_enqueue_style( 'avada-parent-stylesheet', get_template_directory_uri() . '/style.css' );

    wp_enqueue_style( 'parent-style', get_template_directory_uri() . '/style.css' );
    wp_enqueue_style( 'child-style', get_stylesheet_directory_uri() . '/style.css', array('parent-style') );

}

add_action( 'wp_enqueue_scripts', 'theme_enqueue_styles' );


add_filter( 'avadaredux/_url', 'ReduxSymLinkURL', 10 );


function ReduxSymLinkURL(){
    $url = "http://realurl/wp-content/themes/Avada/includes/avadaredux/avadaredux-framework/AvadaReduxCore/";
    return $url;


}

```

**Comment by kprovance** [comment]
Unfortunately, it's not our job to support all the custom modifications Avada has done to Redux, unless of course they want to pay us for our time.  Theme clients must go to the theme author for help.
