### ISSUE TITLE
Memory leak crashing issue with Safari browser

### ISSUE THREAD

**Issue by reboot-digital** [reduxframework/redux-framework#3206]
When using a theme that uses Redux Framework specifically the wordpress theme Flatsome.  Loading the theme options will work just fine.  But after some time of use when trying to load the theme options page in the Safari browser it will bog down and take forever to load, my cpu on my iMac will go high like there is something major going on like some type of memory leak.  If I access the theme options via Firefox or Chrome I don't get this problem at all.

I have had this issue with several websites now using flat some and the redux framework.  It seems to be something to do with the backup code possibly.  I have been dealing with this issue for well over a year and surprised it's not been mentioned or fixed by now.

**Comment by kprovance** [comment]
We did not author this theme and cannot offer support for it.  YOu must go directly to the theme author, which is NOT us.
