### ISSUE TITLE
Multiple css_layout border radius not working correct

### ISSUE THREAD

**Issue by udarts** [reduxframework/redux-framework#3207]
I am using the latest css_layout version (1.0.1) and notice a issue.
When I use 2 border radius elements on a same tab page, 1 I only use % as unit and the other rem as unit. When I try to change the one with the %, the field value changes to 40undefined, instead of 40%.

When I do some research and the console.log, I notice that it uses the second element with the rem as mainID (very weird), and it doesn't return the % as that mainID data-unit doesn't have the %, but the rem instead.

For the css_layouts I only have the border-radius set to true, the rest set to false.

So something is wrong in the code, but I can't put my finger on it.

Is someone able to reproduce it?

Cheers,
Stephan

**Comment by kprovance** [comment]
Hi.  Could you please post all extension issue here:  https://github.com/reduxframework/redux-extensions  Keeps things orderly.  I have some four other things on my plate.  Ill try to get to this next week.  Also, please post your purchase code also.  Thanks!
