### ISSUE TITLE
Mobile Friendly Google

### ISSUE THREAD

**Issue by leokolt** [reduxframework/redux-framework#3209]
Hello! I found that the Mobile Friendly Google does not pass my site when the plugin is active Redux. When I unplug it, everything is fine. How to be?

**Comment by dovy** [comment]
Because your theme author may be using Redux in a non-standard way. Perhaps you could be more specific on what is failing? The only thing we output to the front-end is custom CSS.

**Comment by leokolt** [comment]
You can see the result of the test on this page? https://search.google.com/search-console/mobile-friendly?id=Ypo9lu7YGIT3T0l88ab4BA

**Comment by dovy** [comment]
Yup, that's 100% your theme developer's choices. We don't control that at all. May want to contact them. Those items are all design concerns, and we don't offer any design standards. Only the tools to implement them.  ;)
