### ISSUE TITLE
Google Font ext-latin connection bug at IE11

### ISSUE THREAD

**Issue by seopromo** [reduxframework/redux-framework#3211]
Chrome & FF looks ok, but IE looks wrong.
The page with H1 with font Sriracha looks wrong http://test3.secretlab.pw/ 
The same font at HTML-page  http://test2.secretlab.pw/font.htm it is looks ok
Typography settings http://prntscr.com/du3xr6 
Also I made screenshot if you couldn’t see difference http://prntscr.com/du3zrd
Best regards

**Comment by kprovance** [comment]
Could you PLEASE go back, open a new ticket and read the text we automatically provided?  You gave us non of the information we asked for.

**Comment by seopromo** [comment]
Sorry, i thought i gave clear and understandable information.

## Support Hash
Dont know what is it.
## Steps to reproduce
Set Sriracha goole font at typography. Opent page with text at IE11. Text example "Tańczące Nutki"
## Expected Behavior
Broken letters http://prntscr.com/du3zrd
## Actual Behavior
Not broken letters
## Any Error Details (PHP/JavaScript)
No.

**Comment by kprovance** [comment]
Sorry, I can't help without that support URL.  It's just how we do things now.  Even so, you understand Redux only puts the Google URL in the HTML.  If IE has render issues, I'm not sure what we could possibly do about it.

**Comment by seopromo** [comment]
What is that support url?
The same font look different with different types of connection to the page. So off cource i thing the issue is with the connection type. Looks like at IE11 redux doesnt connect latin-ext. Isnt it?
