### ISSUE TITLE
Google Font ext-latin bug at IE11

### ISSUE THREAD

**Issue by seopromo** [reduxframework/redux-framework#3212]
## Support Hash
http://support.redux.io/?id=2o8sEwavGfH9Dq9KsFzSZpj5YlzvWFDSpZedn2viks7Yj%2B79DHjzIVFupABmW5DITSmKtDkdfJKgMiIZFBgLqg%3D%3D
## Steps to reproduce
Set Sriracha google font at typography. Opent page with text at IE11. Text example "Tańczące Nutki"
## Expected Behavior
Broken letters http://prntscr.com/du3zrd
## Actual Behavior
Not broken letters
## Any Error Details (PHP/JavaScript)
No.

Chrome & FF looks ok, but IE looks wrong.
The page with H1 with font Sriracha looks wrong http://test3.secretlab.pw/
The same font at HTML-page http://test2.secretlab.pw/font.htm it is looks ok
Typography settings http://prntscr.com/du3xr6
Also I made screenshot if you couldn’t see difference http://prntscr.com/du3zrd

**Comment by kprovance** [comment]
Try turning async_typography off?  I dunno.  I don't have any version of IE installed.  Redux doesn't care what browser is running, it outs the same google font string, regardless.  If it's a render issue on IE, then I don't know what can be done.  IE doesn't follow standards, they never have.

**Comment by seopromo** [comment]
false of async_typography is solve the issue.
