### ISSUE TITLE
compilet_action() doesn't fire up for Typography

### ISSUE THREAD

**Issue by exquisitehost** [reduxframework/redux-framework#3214]
## Support Hash
http://support.redux.io/?id=PNYVWd4meP%2FJqL3QU%2FfUEKYkuvI4dEc3EWH9oPoxS1laolaApn%2BWkZV0zTYV9LGHP9dMCnOundfyjDnCsg77RQ%3D%3D
## Steps to reproduce
Add a complex typography field and enable compiler, e.g.
        array(
            'id'       => 'typography-h2',
            'type'     => 'typography',
            'title'    => __( 'H2 Font', 'redux-framework-demo' ),
            'subtitle' => __( 'Specify the H2 font properties.', 'redux-framework-demo' ),
            'google'   => true,
            'compiler'  => true,
            'all_styles'  => true,
            'line-height' => false,
            'color' => false,
            'text-align' => false,
            'default'  => array(
                'google'      => true,
                'font-family' => 'Roboto',
                'font-weight' => 'Normal',
                'font-size' => '40px',
            ),
        ),

## Expected Behavior
compiler_action() should fire up if any of the parameters (color, size, weight etc.) are updated.
## Actual Behavior
compiler_action() will only fire up if the font parameters like family, weight and size are changed - it won't fire up if the color is changed - unless you've previously edited and saved some other value, like weight - only THEN it will fire up for color. 
## Any Error Details (PHP/JavaScript)
None

**Comment by kprovance** [comment]
Fixed in v.3.6.3.4.  Since I did spend half a day on this, a donation to the project would be greatly appreciated.  Thanks!

**Comment by kprovance** [comment]
Yeah, you're welcome
