### ISSUE TITLE
Question regarding WPML

### ISSUE THREAD

**Issue by ismaelyws** [reduxframework/redux-framework#3215]
I've looked thru the docs and here as well, but I haven't found an answer to my specific section.

I am using Redux for a One-Page theme, where I am using the sorter to display sections on the home page.

However, when I enable and configure WPML and switch language, no sections are displayed.

Does it work with the sorter? Or is there a setting I am missing.

Thank you for your time.

I am more than happy to pay for premium support.

**Comment by kprovance** [comment]
https://github.com/reduxframework/redux-framework/blob/master/ISSUE_TEMPLATE

Also, WPML is a premium plugin that I do not own or have access to.

**Comment by kprovance** [comment]
No reply.  Closing.
