### ISSUE TITLE
JavaScript Validation is wrongly coded

### ISSUE THREAD

**Issue by shahthepro** [reduxframework/redux-framework#3217]
As I was browsing through the code of Redux Framework, I saw that the the `Redux_Validation_js` class uses the function `esc_js()` as a means to sanitize the input. 

But this function isn't meant to sanitize JavaScript code. It actually escapes all the single quotes, double quotes and a few other characters so that it can be included in the attribute of HTML elements.
```
<!-- How it was meant to be used -->
<a ... onclick="<?php echo esc_js('THE_JS_CODE_HERE'); ?>">...</a>
```
```
<?php
$var = "alert('hello');";
echo esc_js($var);
```
The above snippet will print `alert(\'hello\');` which isn't a valid JavaScript.

AFAIK, there are no functions, within WordPress Core, to properly validate and sanitize JavaScript code. Only way to do so is to include a JavaScript parser to parse and validate the code. 

I can create a pull request with a JavaScript parser so as to validate JavaScript code with it. Just wandering if I should go ahead.

**Comment by kprovance** [comment]
Don't worry about it, I'll just remove the esc_js.  I don't have time to vet a JS parser under all possible conditions right now.
