### ISSUE TITLE
how to get url from select fields instead of id redux framework

### ISSUE THREAD

**Issue by Abul4u** [reduxframework/redux-framework#3218]
I want to get url and text from select fields instead of id,
Please help.

array(
        'id'       => 'read_more_btn',
        'type'     => 'select',
        'data'     => 'post',
        'args'     => array( 'post_type' =>  array( 'products' ), 'numberposts' => -1 ),
        'title'    => __( 'Choose button URL.', 'redux-framework-demo' ),
        'desc'     => __( 'Change button URL here.', 'redux-framework-demo' ),
        // 'subtitle' => __( 'Example subtitle.', 'redux-framework-demo' ),
    );

**Comment by kprovance** [comment]
Did you read about any of the info we said was required and required?  Please go back, open a new issue window and review it.  There is no help without it.  Sorry.

**Comment by kprovance** [comment]
From the post data type, and ID is all we return.  You can use WordPress APIS to get what you want.

**Comment by Abul4u** [comment]
Thanks its done.
