### ISSUE TITLE
Google Font issue

### ISSUE THREAD

**Issue by OliverXie2016** [reduxframework/redux-framework#3219]
### Hi Kevin,

Sorry I'm back again... 

Now i met a google font problem, below is the sample,

if i choose Raleway and choose font weight 200, the preview and the front end display like this

![image](https://cloud.githubusercontent.com/assets/20784244/22236925/a1a7e478-e243-11e6-9a62-5a785bba262f.png)

however, if i go to Google font official site and check this font, it should be displayed like this:

![image](https://cloud.githubusercontent.com/assets/20784244/22236959/c11ea9cc-e243-11e6-92af-fd81b0e1f065.png)

What is the problem then?

Thanks
Oliver

**Comment by kprovance** [comment]
I need you togo back and read the posting requirements.  Open a new issue window, it's all there.  I have to be able to duplicaate this on my end, and I suspect you might be using some custom code or a plugin I do not have access to.  That second screenshot doesnt even look like Redux at all.

**Comment by antoniomangiacapra** [comment]
Indeed it's a screenshot from Google Font page. Oliver has compared the previews of Redux and Google Font ;)

**Comment by kprovance** [comment]
And?  What is it you want me to do?

**Comment by antoniomangiacapra** [comment]
I don't want nothing, I know that you need more information to start to work on a ticket. I just tried to help to clarify the request, I am sorry if I did something wrong :)

**Comment by kprovance** [comment]
People keep telling us stuff.  But don't give us the info we ask for.  What
am I to do,
