### ISSUE TITLE
Problem with woocommerce

### ISSUE THREAD

**Issue by vNabi** [reduxframework/redux-framework#3223]
## Support Hash
http://support.redux.io/?id=fpeo1KAA9sk7FUKyH9DPlJ9ATeqxY%2F25NPwsVddV7zVPK5pW9nwHeN7SpziToD5vijk7wCKCI0wfvB3werdqaQ%3D%3D
## Steps to reproduce
I have a little online shopping website, using wordpress 4.7.2, woocommerce 2.6.13 and Redux Framework.
When I updated the Redux Framework to the latest version (3.6.3) , the images of the products are gone in the wooommerce products dashboard (see the below screenshots). 
Every thing in the website is okay and normal. Just in the admin area it is happened.
when I deactivate the Redux, it is okay again. 
I think it is something between redux and woocommerce...

Any idea? 
## Expected Behavior
![capture2](https://cloud.githubusercontent.com/assets/25394540/22388671/e1fcb430-e4f6-11e6-8ff5-341da4e5b555.PNG)

## Actual Behavior
![capture1](https://cloud.githubusercontent.com/assets/25394540/22388670/e1f1c80e-e4f6-11e6-82fb-1ecc744866e5.PNG)

## Any Error Details (PHP/JavaScript)
I see nothing.

**Comment by kprovance** [comment]
Where is all the information we requested?  It's...no here.

**Comment by vNabi** [comment]
Sorry, but what else do you need?

**Comment by kprovance** [comment]
Open a new issue window and read all the text that is there.  it explains everything.

**Comment by kprovance** [comment]
I would also upgrade to Redux v3.6.3.5 from this git repo.  I think Dovy fiddled with some CSS, which would be the only logical explanation.  If that doesn;t work, I needs that support hash.  I've written my own theme, which is WooCommerce ready, using WC 2.6.13 and Redux 3.6.3.5.  I do not experience this issue.  Please see if updating Redux works.

**Comment by vNabi** [comment]
I edited the issue,

**Comment by kprovance** [comment]
Did you upgrade Redux yet?

**Comment by kprovance** [comment]
No follow up reply.  Closing.
