### ISSUE TITLE
Redux Framework

### ISSUE THREAD

**Issue by JaDesignz** [reduxframework/redux-framework#3225]

**Comment by JaDesignz** [comment]
I having a problem with the Redux Framework, whenever I activate the plugin the “add to cart” button disappears from the product page, how this problem can be solve? 
If you need me to send you the username and password so that you can take a look at the website I can do so…….PLEASE I REALLY DO NEED YOUR HELP…ASAP. THANKS  

http://casketetcetera.com/

**Comment by kprovance** [comment]
You already have an open tick et for this.  Please review my reply to it.
