### ISSUE TITLE
php 7 preg_replace()

### ISSUE THREAD

**Issue by oblaum** [reduxframework/redux-framework#3227]
hello i have uses a php 7 scanner (WP Engine PHP Compatibility Checker) and i do not know if it's valid or not, the plugin found issues. might be interessting? 

FILE: ...../wp-content/plugins/redux-framework/ReduxCore/inc/validation/preg_replace/validation_preg_replace.php
----------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------------------------------------------------------------------------------------
 30 | ERROR | preg_replace() - /e modifier is deprecated since PHP 5.5 and removed since PHP 7.0
----------------------------------------------------------------------------------------------------------------------------------------------------

**Comment by kprovance** [comment]
Fixed in the version available from this repo.  Next time, please read all that text in the new issue window.  Thanks.
