### ISSUE TITLE
Dimension field unit (px) for simple text-field which will be used for font-size

### ISSUE THREAD

**Issue by thelegendarynikhil** [reduxframework/redux-framework#3229]
how do i use dimension field unit i.e. px for any text field( font-size) (i mean how to validate it and use )??  also how to use  slider field for giving padding-right  in px ?? (how to validate it)??

**Comment by kprovance** [comment]
https://docs.reduxframework.com/core/the-basics/validation/

**Comment by dovy** [comment]
The dimension and slider fields already have number validation within them. However, dimensions is the only one that you can assign the css output of padding to. You'll have to manually do it with the slider field.

**Comment by thelegendarynikhil** [comment]
thanks.... and one more thing is this the  correct way of getting / and using theme option values in my theme..
Created a file called dynamic-css.php with the following code: and included this file in header.php. I have just stopped fetching the values due to this confusion...which i wanted to clear and wanted to to know i am going right..... if not then what will be the following procedure to use the values of theme. other than compiler output..

<style type="text/css">

.main-navigation  {
	<?php global $theme_optt; ?>
	height: <?php  echo $theme_optt['main-menu-height']['height']; ?>;
	padding-right: <?php echo $theme_optt['main-menu-item-padding']['padding-right'] ; ?>;
 }
  
.main-navigation ul ul  {
	<?php global $theme_optt; ?>
	 width: <?php echo $theme_optt['main-menu-dropdown-width']['width'] ; ?>;	
  }
.main-navigation ul ul  li {
	
		<?php global $theme_optt; ?>
	  padding-top: <?php echo $theme_optt['main-menu-dropdown-item-padding']['padding-top'] ; ?>;	
	  padding-bottom: <?php echo $theme_optt['main-menu-dropdown-item-padding']['padding-bottom'] ; ?>;	
	}

.main-navigation   {
	<?php global $theme_optt; ?>
	  font-family: <?php echo $theme_optt['menus-typography']['font-family'] ; ?>;	 
	  font-weight: <?php echo $theme_optt['menus-typography']['font-weight'] ; ?>;	 
	 font-style : <?php echo $theme_optt['menus-typography']['font-style'] ; ?>;
	 text-align : <?php echo $theme_optt['menus-typography']['text-align'] ; ?>;
	 font-size: <?php echo $theme_optt['menus-typography'] ['font-size'] ; ?>;
	 line-height: <?php echo $theme_optt['menus-typography']['line-height'] ; ?>;
	
	} 
	
.main-navigation a {
	<?php global $theme_optt; ?>
	 color: <?php echo $theme_optt['menus-typography']['color'] ; ?> !important;
	}
	
	body {
	  <?php global $theme_optt; ?>
	  background: <?php echo $theme_optt['body-background-color']; ?> !important;
	}
