### ISSUE TITLE
why select fields return text & some time id

### ISSUE THREAD

**Issue by Abul4u** [reduxframework/redux-framework#3231]
**below return me text**
array(
            'id'       => 'tm-wc-joinURL',
            'type'     => 'select',
            'data'     => 'post_type',
            'title'    => __( 'Button URL.', 'redux-framework-demo' ),
        ),

**This below code return me id**
array(
        'id'       => "read-more",
        'type'     => 'select',
        'data'     => 'post',
        'args'     => array( 'post_type' =>  array( 'products' ), 'numberposts' => -1 ),
        'title'    => __( 'Choose button URL.', 'redux-framework-demo' ) . $i,
        'desc'     => __( 'Change button URL here.', 'redux-framework-demo' ),
        // 'subtitle' => __( 'Example subtitle.', 'redux-framework-demo' ),
    );

I want full url and not the text

**Comment by dovy** [comment]
You have to query the actual post with the ID. ;)
