### ISSUE TITLE
Problem with multiple ReduxFramework Plugin

### ISSUE THREAD

**Issue by altinoktaonalti** [reduxframework/redux-framework#3232]
Hello !

1- I have created new theme using ReduxFramework .
I can use option panel to change everything on my theme .

2- I have created new plugin using ReduxFramework .
I can use option panel to change everything on my plugin .

The problem is :

If I activate the plugin on my website .
Option panel of my theme Disappear and Option Panel Of plugin Show

If I disable The plugin

Option panel of my theme Show again

how can i fix it ?

**Comment by kprovance** [comment]
You can begin by opening a new issue window and reading the information there.  We require several things for support, and not were given,  Please provide that information.

**Comment by altinoktaonalti** [comment]
https://github.com/ReduxFramework/redux-framework/issues/1175

There is the same problem. He was said "fixed" but don't fix. 

Pls help me about my problem, What do you want for support, money ?

**Comment by kprovance** [comment]
I need you to supply the information I asked for.

**Comment by altinoktaonalti** [comment]
What do you need to supply the information ?

**Comment by kprovance** [comment]
<blockquote>
You can begin by opening a new issue window and reading the information there. We require several things for support, and not were given, Please provide that information.
</blockquote>

**Comment by kprovance** [comment]
If you are unable to provide the required information we need, there won't be much else I can do.

**Comment by altinoktaonalti** [comment]
The information you want is unnecessary. I see my own business myself :)

**Comment by kprovance** [comment]
It's actually very necessary, otherwise I'd be spending DAYS guessing at this.  We can go that route, but I'd ask you pay us premium support for my time.  Good luck.
