### ISSUE TITLE
Redux Framwork (Theme Options are not loading)

### ISSUE THREAD

**Issue by isarco** [reduxframework/redux-framework#3234]
Hello

since yesterday, the Theme Options are not loading. I have done nothing.
Wordpress and Plugins are up to date.

![settings](https://cloud.githubusercontent.com/assets/25606674/22684191/9a20fdc4-ed1b-11e6-8f10-e80d6b675d6e.JPG)

**Comment by kprovance** [comment]
Please open a new issue window, read ALL the text there, and supply us with the required information.  Thanks.
