### ISSUE TITLE
Redux Framework issue Theme Options not loading

### ISSUE THREAD

**Issue by isarco** [reduxframework/redux-framework#3235]
![redux-bug-settings](https://cloud.githubusercontent.com/assets/25606674/22685358/4e591c3c-ed20-11e6-807b-be32baa11584.jpg)

**Comment by kprovance** [comment]
Okay, well, you still didn't supply us with a support hash.  Is this your theme?  Did you author it?

**Comment by isarco** [comment]
Iam sorry, the Theme is apicona

https://themeforest.net/item/apicona-health-medical-wordpress-theme/9150966

**Comment by kprovance** [comment]
As the text in the new issue window said:  "If you have purchased a theme or plugin that utilizes Redux, please contact the author for support."

We do not support themes that use our framework.  it is the theme author's job to support their work.  If they discover an issue with our framework, then they bring it to us, as we are unable to actually fix the theme itself.  You can tell him it looks as if the ACE library is not properly loaded, but again, it's his job to go onto your server, debug it and figure out what's wrong; that's what you paid him for.  :)

Sorry.  Good luck.
