### ISSUE TITLE
Visual composer / No licenses found

### ISSUE THREAD

**Issue by JayMarcano** [reduxframework/redux-framework#3237]
Hi, 

I'm not sure If this is the right place. but I am installing Gather Theme and I can't activate Visual Composer as its saying "NO LICENSES FOUND"

Can you please point me in the right direction?

Thanks in advance

Jay

**Comment by kprovance** [comment]
Nope, not the right place, sorry.  You need to contact the author of your theme, which is not us.  Good luck.
