### ISSUE TITLE
Redux Typography Weight Field with custom fonts

### ISSUE THREAD

**Issue by zesseb** [reduxframework/redux-framework#3243]
Hi there!

I put a custom font on my website, and I'm trying to set up this font in the admin panel.

I created a css called «myfont.css» with this code:

`@font-face {
  font-family: 'FontSwiss';
  src: url('../fonts/SuisseIntl-Ultralight-WebS.eot');
  src: url('../fonts/SuisseIntl-Ultralight-WebS.eot') format('embedded-opentype'), url('../fonts/SuisseIntl-Ultralight-WebS.woff2') format('woff2'), url('../fonts/SuisseIntl-Ultralight-WebS.woff') format('woff'), url('../fonts/SuisseIntl-Ultralight-WebS.ttf') format('truetype'), url('../fonts/SuisseIntl-Ultralight-WebS.svg') format('svg');
  font-weight: 100;
  font-style: normal;
}
@font-face {
  font-family: 'FontSwiss';
  src: url('../fonts/SuisseIntl-UltralightItalic-WebS.eot');
  src: url('../fonts/SuisseIntl-UltralightItalic-WebS.eot') format('embedded-opentype'), url('../fonts/SuisseIntl-UltralightItalic-WebS.woff2') format('woff2'), url('../fonts/SuisseIntl-UltralightItalic-WebS.woff') format('woff'), url('../fonts/SuisseIntl-UltralightItalic-WebS.ttf') format('truetype'), url('../fonts/SuisseIntl-UltralightItalic-WebS.svg') format('svg');
  font-weight: 100;
  font-style: italic;
}

@font-face {
  font-family: 'FontSwiss';
  src: url('../fonts/SuisseIntl-Thin-WebS.eot');
  src: url('../fonts/SuisseIntl-Thin-WebS.eot') format('embedded-opentype'), url('../fonts/SuisseIntl-Thin-WebS.woff2') format('woff2'), url('../fonts/SuisseIntl-Thin-WebS.woff') format('woff'), url('../fonts/SuisseIntl-Thin-WebS.ttf') format('truetype'), url('../fonts/SuisseIntl-Thin-WebS.svg') format('svg');
  font-weight: 200;
  font-style: normal;
}
@font-face {
  font-family: 'FontSwiss';
  src: url('../fonts/SuisseIntl-ThinItalic-WebS.eot');
  src: url('../fonts/SuisseIntl-ThinItalic-WebS.eot') format('embedded-opentype'), url('../fonts/SuisseIntl-ThinItalic-WebS.woff2') format('woff2'), url('../fonts/SuisseIntl-ThinItalic-WebS.woff') format('woff'), url('../fonts/SuisseIntl-ThinItalic-WebS.ttf') format('truetype'), url('../fonts/SuisseIntl-ThinItalic-WebS.svg') format('svg');
  font-weight: 200;
  font-style: italic;
}`

Then in my theme option I have this :

`$fonts = array ( 'FontSwiss' => 'FontSwiss', 
		'Arial, Helvetica, sans-serif' => 'Arial', 
		'\'Arial Black\', Gadget, sans-serif' => 'Arial Black', 
		'\'Bookman Old Style\', serif' => 'Bookman', 
		'Courier, monospace' => 'Courier', 
		'Verdana, sans-serif' => 'Verdana' );

Redux::setSection($opt_name, array(
    'title' => __('Typography', 'integral') ,
    'id' => 'general-typography',
    'desc' => __('Change the font properties for the body, titles and top menu', 'integral') ,
    'icon' => 'el el-font',
    'subsection' => true,
    'fields' => array(
           array(
            'id' => 'gen-typography-topmenu',
            'type' => 'typography',
            'title' => __('Top Menu Font', 'integral') ,
            'subtitle' => __('Change the top menu font styles. If you upload a logo larger then 30px in height, the top bar height will adjust accordingly. However this will result in the vertical alignment of the menu to be off. You can fix this by playing with the line height properties.', 'integral') ,
            'subsets' => false,
            'ext-font-css' => '/wp-content/themes/integral-pro/css/font-swiss.css',
            'fonts' => $fonts,
            'text-align' => false,
            'line-height' => true,
            'color' => true,
            'text-transform' => true,
            'all_styles' => true,
            'output' => array(
                '.navbar-default .navbar-nav > li > a, .navbar-default .navbar-nav > .active > a'
            ) ,
        ) ,
    )
));`

And when I'm loading my admin panel, I can select my custom font, the preview is OK but the weight select field does not show all my styles, only the redux default styles.

What can I do?

**Comment by kprovance** [comment]
Unfortunately, right now, not a lot. Redux was not designed to import these kinds of CSS font files (and programatically speaking, it would be an unreliable parsing nightmare to do so.)  When adding user fonts, the standard none google fonts weights will display.  The work that would have to go into the field to make something like this work would be considerable.  For me to do it for free means I would have to devote free time to it, which I have little of at present.  If we could get a crowdfunder campaign together that would get full support, it'd make time to do it.  Those are about our only options.
