### ISSUE TITLE
Can't get in touch on email

### ISSUE THREAD

**Issue by PayteR** [reduxframework/redux-framework#3246]
hi, i cant get in touch with anyone on email for longer than month. I need to have invoice from last year, issue is even on redux-extension repository https://github.com/reduxframework/redux-extensions/issues/320

**Comment by dovy** [comment]
@PayteR Are you speaking about a reoccurring charge? If so, can't you utilize the receipt from Paypal?

**Comment by PayteR** [comment]
no i need invoice

**Comment by dovy** [comment]
The issue is Easy Digital Downloads doesn't seem to support that. I don't know what to tell you. Why won't the paypal payment with our company on it do?

**Comment by dovy** [comment]
Replying via email.
