### ISSUE TITLE
I can't Translate Theme Options using Redux Framework

### ISSUE THREAD

**Issue by MrShabir** [reduxframework/redux-framework#3247]
Hello I used Redux Framework in my theme. 
I have include redux as a plugin and include options file from theme folder.
themename/ReduxFramework/theme-options.php

Then i required plugin.
At the top i have include language file in after_setup_theme action.
```
load_theme_textdomain( 'themename', get_template_directory() . '/languages' );
```
Then i include options file.
All translations are working fine, other then Options. Any help please?

**Comment by kprovance** [comment]
Support URL/hash, please?

**Comment by MrShabir** [comment]
What you mean by support URL @kprovance

**Comment by kprovance** [comment]
Open a new issue window, and read all the text you skipped over when making this post.  Instructions were provided for you about what info we need.

**Comment by MrShabir** [comment]
Ok Thanks .
http://support.redux.io/?id=PIWeBeRlYmeYTszGi%2Beo8fIkn8RLVjatUtBmi%2BeiViTSNaZXScjyJvh8uAWEgptxo9nFBBXLNNOVDoqgy3GRcw%3D%3D
is there anything more @kprovance

**Comment by kprovance** [comment]
What language are you attempting to use?  You're support URL says English.  I loaded German and everything translated just fine, at least everything related to Redux did.  Translation in your own option panel must be done by you.

**Comment by kprovance** [comment]
Closing due to lack of reply.
