### ISSUE TITLE
Customizer Priority Issue

### ISSUE THREAD

**Issue by db-dzine** [reduxframework/redux-framework#3249]
## Steps to reproduce
Initialize the Redux Framework 2 times. In my example I have 2 plugins using the Redux Framework. Then go into customizer.
## Expected Behavior
See 2 Sections:
1. Plugin 1
2. Plugin 2
## Actual Behavior
Both plugin options get merged together into one. The latest initialized one in this example. 
## Any Error Details (PHP/JavaScript)
Problem is in Class "ReduxFramework_extension_customizer". The priority of a section gets increased by the sections from Redux. That is okay.

But the priority of the top level could not be set. That is why it always starts with 0 for each plugin. 

Better: Create an option $args object with the name "customizer_priority".

**Comment by dovy** [comment]
Yes, that is an issue with Redux that we need to fix. There is only one redux object, and thus things get merged. It's quite a task that we need to resolve, but I fear it's a limitation that exists.

The only way you can get around it is to use the same opt_name in all plugins.

**Comment by db-dzine** [comment]
Ok do you have any deadline when this will be fixed? I mean a simple option could work, couldn'it it?

**Comment by dovy** [comment]
It requires every field that uses javascript and required be updated, the core mech for how required and warnings and alerts, get changed. So it's actually a core issue that requires a major rewrite of a lot of modules. So no ETA, it's a big project to undertake.

**Comment by kprovance** [comment]
Move to extension issue tracker.
