### ISSUE TITLE
How to show Conditional Statement In Redux Framework for Logo?

### ISSUE THREAD

**Issue by nriddhi** [reduxframework/redux-framework#3252]
I want to show logo with if else statement. If logo is uploaded it will show logo otherwise it will show insert your logo from theme option. the code is
```
`<?php if(!empty($redux_demo['logo_upload']['url'])) { ?>

                <h1 class="site-title">

                <a href="<?php bloginfo('home'); ?>">
                <img src="<?php global $redux_demo;  echo $redux_demo['logo_upload']['url']; ?>" alt="casanova"></a>
                </h1>
    <?php }

else  echo __("<p> insert your logo from theme option </p>", "casanova")  ?>`
```

I tried it, but not working only showing the text. thanks for help.

**Comment by kprovance** [comment]
This is a PHP issue, not a Redux issue.  We don't have the time or resources to fix folk's PHP errors.

At first glace, your else statement has no brackets.  Plus, don't use empty to check against a blank string.

**Comment by dovy** [comment]
Correction, empty checking can be fine provided you have an `isset() &&` before it to avoid PHP warnings.

Best of luck!
