### ISSUE TITLE
Can't import in multi-site

### ISSUE THREAD

**Issue by ilprincipino89** [reduxframework/redux-framework#3253]
Hi,

I've a WP MU site with 5 sites and a theme (GAUGE THEME on Themeforest) that use Redux Framework to manage style and other options. There a tab to import/export options via URL or File. I've tried both, with the attempt to copy all data from first site to all the others. All seems to go well, the page reload after click on import and appears the "settings save!" message. But, the options remains the same, the default one. How can I copy and paste the options in all 5 sites to avoid copying everything manually.

Thanks!

**Comment by kprovance** [comment]
I had that problem last year.  I could never figure out why.  I mentioned it to @Dovy, but he's off someplace else for the interim.  If I ever get time, I'll try to figure it out again.

**Comment by db-dzine** [comment]
Had the same problem some while ago. Indeed the problem is not part of the Redux Framework, but WordPress itself. WP stores & gets options different, when it is a multisite. There are some special data transformation. 

For details you need to check the wp-includes/option.php

**Comment by rpto** [comment]
Hello,
I can not change the styling options after Datentransfair, in Themeforest's ALIKA theme. What can I do?

**Comment by rpto** [comment]
Hello,
I can not change the styling options after data/file transfair, in Themeforest's ALIKA theme. What can I do?

**Comment by kprovance** [comment]
1) Please do not piggy back older tickets.
2) We are not the author of your theme.  You will need to contact the theme author for support.
