### ISSUE TITLE
Prevent images by cropping

### ISSUE THREAD

**Issue by ingozoell** [reduxframework/redux-framework#3254]
Hi,

how can I show up the preview in original file size or another custom image file size without cropping?

**Cropped image** (WP `thumbnail-size`)

![bildschirmfoto 2017-03-14 um 13 41 39](https://cloud.githubusercontent.com/assets/2229940/23901079/0057e876-08bc-11e7-81ac-f563489598fa.png)

To set a fix height and width doesn't work for me:

```
...
'type'     => 'media',
'width'    => '200px,
'height'  => '120px',
...
```
--
Source: https://docs.reduxframework.com/core/fields/media/

**Comment by kprovance** [comment]
That's just how Redux shows thumbnails for the preview.  The argument you make refence for is not for the preview, but for the field output to be used in your project.  That original image in the preview is set by javascript, using thumbnails.  After refreshing, the media field displays the image at 150x150.  It's hard coded that way.
