### ISSUE TITLE
Relative protocol not respected

### ISSUE THREAD

**Issue by craigtommola** [reduxframework/redux-framework#3255]
I am using the MESH theme provided by Stylish Themes, seen here: https://themeforest.net/item/mesh-music-band-musician-event-club-theme/15113981

I asked our intern to add some custom CSS to the Custom CSS / JS section of the MESH Options but the boxes to add the code were missing. I opened the inspector to find that there were a few errors related to JS and CSS files not loading, due to mixed content warnings.

//cdn.jsdelivr.net/ace/1.1.9/min/ace.js
//cdn.jsdelivr.net/select2/3.5.2/select2.css
//cdn.jsdelivr.net/select2/3.5.2/select2

While these are referenced relative in your files, as shown above, and our server uses https, they are being loaded via http. When I modified the plugin files to use https directly, they loaded as expected.

I modified:
/redux-framework/ReduxCore/inc/fields/ace_editor/field_ace_editor.php
/redux-framework/ReduxCore/core/enqueue.php

**Comment by kprovance** [comment]
Support URL/hash please.

**Comment by dovy** [comment]
Is the site domain set properly?

**Comment by kprovance** [comment]
It's probably that relative url plugin floating around, the one that causes this problem because the author won't update it, but I need the REQUIRED support URL to determine this.

**Comment by kprovance** [comment]
Closing.  No reply.

**Comment by craigtommola** [comment]
Apologies. I didn't see notifications for your replies. The site domain is indeed set properly in Wordpress. The site is: https://wths2.hope.edu/
