### ISSUE TITLE
links target _blank not working for ios devices

### ISSUE THREAD

**Issue by nodarik** [reduxframework/redux-framework#3257]
Hi guys

If the redux framework is activated and i use button in slider revolution with link target _blank it's not opening in ios devices, plugin is deactivated and links are working normally, 
what might be the issue?

here it the link to the site:
http://bulls-eye.se/project/riddarhoppborg/
pdf files will not open in the new tab

**Comment by kprovance** [comment]
This is something you'd have to take with with Theme Punch.  Redux and SLider Revolution do not interact with one another.
