### ISSUE TITLE
Sorter translation

### ISSUE THREAD

**Issue by ingozoell** [reduxframework/redux-framework#3259]
Hi,

how can I translate the options array names:

**"Enabled"
"Disabled"**

![ae3b5c72-5157-11e3-8512-000c3bad0778](https://cloud.githubusercontent.com/assets/2229940/24071963/30756144-0bde-11e7-9c8f-b7f77093d18d.png)

Thanks

**Comment by kprovance** [comment]
Use the __() function on the keys in your option array, for the sorter field.
