### ISSUE TITLE
Google fonts 403 forbidden status

### ISSUE THREAD

**Issue by gabetu** [reduxframework/redux-framework#3260]
Hi guys,

Everything is working as expected except the annoying google fonts stylesheet not displaying the fonts in frontend due to the 403 forbidden status.

Fresh install on various live servers and different domains with or without SSL = same result

Live example: https://www.sabai.directory/

http://support.redux.io/?id=gBQiGxO9D8VeSvOK2Tkjm3RHp76XEBkJfRfKSPDsKkCfYgAPgv7M1dWibHzRKQ3eq%2Fppt5Vi71M1dBG7dBmh5A%3D%3D

Wordpress v. 4.7.3
Redux Framework v. 3.6.3 (installed as required plugin through TGM-Plugin-Activation)
No other plugins active

PHP v. 5.4.45
MySQL v. 5.6.35
Cpanel v. 62.0.16
Custom theme with theme options by Redux

Working as expected on localhost xampp environment.

First thing that I noticed is that after installing Redux Framework plugin the folders and content of uploads/redux/google-fonts/ have not been created on the live server so I moved the content from localhost here.

Some args:
`
'google_api_key'     => '',
// Set it you want google fonts to update weekly. A google_api_key value is required.
 'google_update_weekly' => true,
// Must be defined to add google fonts to the typography module
 'async_typography'     => false,
// Use a asynchronous font on the front end or font string
//'disable_google_fonts_link' => true, 
// Disable this in case you want to create your own google fonts loader
...
'output' => true,     
'output_tag' => true,       
'settings_api' => true,    
'cdn_check_time' => true,
`

And the typography field:

`array(
'id'        	=> 'site-title-typography',
'required'  	=> array ('branding_type', 'equals', 'site-title'),
'type'      	=> 'typography',
'title'     	=> __('Site title font &amp; size', 'myplaces'),
'desc'      	=> __('In case that you do not use any logo set here the font-family &amp; size of the site title. Please adjust the font-size to match the header of the theme.', 'myplaces'),
'google'      	=> true,
'font-backup' 	=> true,
'units'       	=>'px',
'font-size' 	=> true,
'line-height' 	=> true,
'word-spacing'	=> true,
'letter-spacing'=> true,
'text-align'    => false,
'subsets'	=> false,
'color'         => false,
'output' 	=> array('.site-title'),
'default'     	=> array(
'font-family' 	=> 'Lobster',
'font-size'   	=> '38px',
),
),
`

The output in head seems ok excepting that the dynamic-css generated by redux should be before all theme styles ?

![redux](https://cloud.githubusercontent.com/assets/26364320/24080097/8429c448-0ca0-11e7-9515-d96e3b3ffff5.jpg)

And debugging is getting the 403 forbidden google fonts stylesheet:

![403](https://cloud.githubusercontent.com/assets/26364320/24080120/057698c8-0ca1-11e7-97a4-f1da2ef08be0.jpg)

Has anyone ideas why this happens how to fix it ?

Thanks,
Gabetu

**Comment by kprovance** [comment]
Honestly, I have no idea.  Look at the generated google API string:  https://fonts.googleapis.com/css?family=Lobster%3A400%7CNoto+Sans%7CHelvetica

See how the CSS loads properly in the window?  I hard coded that string into my theme (locally) and I got no 403.  I see where Yoast is doing prefetching.  Have you tried turning Yoast off and see if that makes a difference? I'm not sure where the conflict is here.

**Comment by kprovance** [comment]
No follow up reply given.  Closing.
