### ISSUE TITLE
Issue With Live Customizer 

### ISSUE THREAD

**Issue by manikbajaj** [reduxframework/redux-framework#3261]
## Support Hash
x4y3uAMmRO7og22kZX5KGeoIvohLI8z%2FfxYCE3Q3EEhmJnPYisu3Q%2BpOzOrDmCnaKXvCGbDsgdnDGx9wM%2BGQtw%3D%3D

## Steps to reproduce
If you go to live customizer, you would be able to see that you the changes are visible only when you click on save and preview whereas this should not be the case. The changes made to the theme options should reflect there and then. 

Here Are The Problems:
1. This is working in case of a few options but in the case of a few others just does not work. 
2. Even in case of the options it works for the moment you change another option it stops working altogether. 

## Expected Behavior
Should work for all the theme options and without actually saving the theme options.

**Comment by kprovance** [comment]
Could you post this to our customizer issue tracker?  Thanks.

https://github.com/reduxframework/customizer-integration/issues

**Comment by manikbajaj** [comment]
Posted !! Cheers !!
