### ISSUE TITLE
Color RGBA field alpha undefined

### ISSUE THREAD

**Issue by Ryu-k** [reduxframework/redux-framework#3263]
Since I updated Redux framework to 3.6.3.5 the color rgba field doesn't seems to be taking the alpha value anymore.

## Steps to reproduce

Create a color rgba field, try to change the value and try to output it : 
$opt_name['rgba_color']['rgba'];

## Expected Behavior

rgba(255,255,255,0.25);

## Actual Behavior

rgba(242,0,0,undefined);

## Any Error Details (PHP/JavaScript)

PHP Version 5.6.30-1

**Comment by kprovance** [comment]
Support url/hash?  You left that out.  It's required.

**Comment by Ryu-k** [comment]
My bad 

http://support.redux.io/?id=q0qUSjMxg%2BsfdRMPI7Yc3%2BV3R48oNkWfiDHedmf0uBJ3Hk%2B9OydEseSSCdS%2BWOu%2B1tfK2c1BdxfglAdkvP7sgQ%3D%3D

**Comment by Ryu-k** [comment]
Ok, so you can close this, it appears that an additional plugin was included "spectrum.js", this was the source of the problem.

Sorry for the unneeded ticket.

Have a nice day

Regards
