### ISSUE TITLE
Change redux option panel location from tools.php submenu to admin menu

### ISSUE THREAD

**Issue by franksteelcastle** [reduxframework/redux-framework#3264]
Dear Colleagues,

I tried to figure out, how can I change redux option panel location from tools.php submenu to a simple admin menu (e.g.: Redux Option), because I want (if it's possible) to show this option panel (about, credits, supports etc.) for the users. Unfortunately, the option panel under tools is a little bit hidden and no one can find it.

Thank you!

Frank

**Comment by kprovance** [comment]
Those options under tools cannot be changed without modifying the core, which is NOT recommended.  Any changes made to the core will be lost when the core is updated.  If you insist on doing so, then 1) We will not be able to support any changes, or side effects from them.  2) The location is ReduxCore/inc/welcome/welcome.php
