### ISSUE TITLE
PHP 7.0 Compatibility Checker reports Error with Redux Framework Version 3.6.3

### ISSUE THREAD

**Issue by shgaque** [reduxframework/redux-framework#3266]
Hi 
just wanted to let you know that the "PHP 7.0 Compatibility Checker" reports the following error here below for PHP7. Is this something you can fix? 
Many thanks. 
 
FILE: /nas/content/staging/wp-content/plugins/redux-framework/ReduxCore/inc/validation/preg_replace/validation_preg_replace.php
--------------------------------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
--------------------------------------------------------------------------------------------------------------------------------------
 30 | ERROR | preg_replace() - /e modifier is deprecated since PHP 5.5 and removed since PHP 7.0
--------------------------------------------------------------------------------------------------------------------------------------

**Comment by dovy** [comment]
That has been fixed for quite some time. Doing a WP.org push later today.

**Comment by dovy** [comment]
New version pushed. This should go away.
