### ISSUE TITLE
Color RGBA field requires color or color_gradient field in order to work in Customizer.

### ISSUE THREAD

**Issue by burnmaniac** [reduxframework/redux-framework#3271]
## Support Hash
I think this is not needed for this kind of issue as it is easy to reproduce and I do not need the support.
## Steps to reproduce
 * Make a section.
 * Add just one `color_rgba` field. 
## Expected Behavior
It is expected to work as a single field without any other fields.
## Actual Behavior
When you add just one `color_rgba` field in one section, the field is being rendered as input field with type text. When you add `color` field in that or any other section, the field is being rendered properly. The `color_rgba` field is working in Redux Options, not working in Customizer.

## Any Error Details (PHP/JavaScript)
```
Uncaught ReferenceError: redux is not defined
    at field_color_rgba.js?ver=1490834438:4
    at field_color_rgba.js?ver=1490834438:217
Uncaught ReferenceError: redux is not defined
    at field_options_object.js?ver=4.0:6
    at field_options_object.js?ver=4.0:44
Uncaught ReferenceError: redux is not defined
    at field_import_export.js?ver=4.0:6
    at field_import_export.js?ver=4.0:198
```

**Comment by kprovance** [comment]
The support URL IS required.  Feel free to open a new issue when you are ready to provide us with the info needed.

Also, customizer issues go here:  https://github.com/reduxframework/customizer-integration/issues

Thanks.
