### ISSUE TITLE
How to get All sidebars in select fields?

### ISSUE THREAD

**Issue by kingRayhan** [reduxframework/redux-framework#3272]
How can I do this in redux framework?

I tried like this.

I put this in very top of themeoption config file
```php
 $sidebars = array();
 foreach ($GLOBALS['wp_registered_sidebars'] as $key => $value) {
     $sidebars[$key] = $value['name'];
 }
```

And then use `$sidebars` variable in the select field.
```php
            array(
                'id'       => 'select_page_left_sidebar',
                'type'     => 'select',
                'title'    => __( 'Select Left Sidebar', 'drubo' ),
                'options'  => $sidebars
            ),
```

**Comment by kprovance** [comment]
https://docs.reduxframework.com/core/fields/select/

Note the 'data' argument.  Specify 'sidebars' and you won't have to do all that foreach business.

**Comment by kingRayhan** [comment]
Thanks you so much.

**Comment by kingRayhan** [comment]
I should check the documentation first , forgive me
