### ISSUE TITLE
General Option Error

### ISSUE THREAD

**Issue by Box2211** [reduxframework/redux-framework#3273]
Hi,
after updating to Redux 3.6.4 General Theme Options can not be changed.
New entries in Footer section can NOT be SAVED.
"There was a problem with your action. Please try again or reload page."
I tried again several times - logout, login etc. - nothing can be changed.

Is there a workaraound / fix?

Thx.

**Comment by kprovance** [comment]
Could you please open a new ticket, READ the entire text we provide for you, and supply each item of information we asked for?  It is required now.  Thanks.
