### ISSUE TITLE
Unable to get all custom post type?

### ISSUE THREAD

**Issue by Govind13100** [reduxframework/redux-framework#3274]
This is my code in admin-config.php
$post_types =  get_post_types( array( 'public' => true), 'objects' ) );
			
				foreach ( $post_types as $pt ) {
					$post_typeeee[] = $pt->name;
						
				}
						

  Redux::setSection( $opt_name, array(
      'title'      => __( 'SEO', 'redux-framework-demo' ),
      'desc'       => __( '', 'redux-framework-demo'),
      'id'         => 'amp-seo',
      'desc'       => '<strong>Note : <br/> This section only works if  Yoast SEO Plugin is Activated (Exception : Additional Meta Tags Section) </strong>',
      'subsection' => true,
       'fields'     => array(

           array(
               'id'       => 'ampforwp-seo-yoast-meta',
               'type'     => 'switch',
               'subtitle'     => __('Adds Social and Open Graph Meta Tags from Yoast', 'redux-framework-demo'),
               'title'    => __( 'Add Meta Tags from Yoast', 'redux-framework-demo' ),
               'default'  => '1'
           ),
           array(
               'id'       => 'ampforwp-post-typesss',
               'type'     => 'select',
               'subtitle'     => __('POST TYPES', 'redux-framework-demo'),
               'title'    => __( 'POST TYPES', 'redux-framework-demo' ),
               'options'  => $post_typeeee,
              
           ),
I am only getting the built in post types, i want to fetch all custom post too, is that possible ? I am stuck in this
Thanks in advance,

**Comment by kprovance** [comment]
Code that has nothing to do with Redux itself does not fall under the scope of our support, unless you want to pay for premium.

Even so, you're doing it the hard way.

https://docs.reduxframework.com/core/fields/select/

Note the 'data' argument.

**Comment by Govind13100** [comment]
Thank you so very much for instant reply, it worked
