### ISSUE TITLE
select2.js and ace.js fail to load

### ISSUE THREAD

**Issue by lajos** [reduxframework/redux-framework#3278]
The select2.js and ace.js libraries don't exist on the cdn at the hard coded paths.

```
core/enqueue.php:
  '//cdn.jsdelivr.net/select2/3.5.2/select2' . $this->min . '.js'
  '//cdn.jsdelivr.net/select2/3.5.2/select2.css'

inc/fields/ace_editor/field_ace_editor.php:
  '//cdn.jsdelivr.net/ace/1.1.9/min/ace.js'
```

**Comment by kprovance** [comment]
Please open a new issue window, read the entire body of text we have provided, and submit the information that is required.

Thanks.

**Comment by kprovance** [comment]
No reply or required information provided.  Closing.
