### ISSUE TITLE
Redux Color Field Issue

### ISSUE THREAD

**Issue by kuropurogurama** [reduxframework/redux-framework#3279]
Hello, 
I have found a problem in using redux color field. The code is below : 
array(
            'id'        => 'footer_copyright_bg',
            'type'      => 'color',
            'output'    => array('.cs-copyright-area'),
            'title'     => esc_html__('Set Footer Copyright Section Background Color', 'learncare'),
            'subtitle'  => esc_html__('Specify the background color', 'learncare'),    
            'default'  => '#FFFFFF'
            ),
So,  this throws a warning : Notice: Array to string conversion in C:\xampp\apps\wordpress\htdocs\wp-content\plugins\redux-framework\ReduxCore\inc\fields\color\field_color.php on line 62
But if I change the id to something else it works perfectly ! Why is it happening ?

**Comment by kprovance** [comment]
Please open a new issue window.  Please read all the text we provided.  Please reply with ALL the required information.  The little provided here is not enough to help with.  If the required information is not provided in two days, this ticket will be closed.

Thanks.

**Comment by kprovance** [comment]
Closed due to no reply or required information not provided.
