### ISSUE TITLE
About Multi Text Options and Validate

### ISSUE THREAD

**Issue by ozgurkalyoncu** [reduxframework/redux-framework#328]
Everthing great but i have one more suggest,

Multi Text Option - have lots of verified system and repetable option
but i think u can add there

Multi text Option with Multiple input and repatable

For better seo sometime we need it

**Comment by maheraldous** [comment]
Are you done with creating this feature Add  Two Fields at once in Multi Text @dovy  It also will be better if you do it like that the first field will have a validation and the second field will have another validation. So when you click add more you add two fields and each one of them have thier own validation. For example check it out. I have seen those fields in Options Tree Plugin https://prnt.sc/n2bftc
