### ISSUE TITLE
Problem with Redux FrameWork on my Archi Theme

### ISSUE THREAD

**Issue by iknaromer** [reduxframework/redux-framework#3280]
Hi there!

I'm just a regular user... and my skill level in development code its just below basic..

I got a problem.. just after i update my Archi Theme to its las version, this three errors show in the Archi Option

"Redux Framework Warning select2-css CDN unavailable. Some controls may not render properly. Please wait a few minutes, then try refreshing the page. Unable to load some remotely hosted scripts..

Redux Framework Warning select2-js CDN unavailable. Some controls may not render properly. Please wait a few minutes, then try refreshing the page. Unable to load some remotely hosted scripts..

Redux Framework Warning ace-editor-js CDN unavailable. Some controls may not render properly. Please wait a few minutes, then try refreshing the page. Unable to load some remotely hosted scripts.."

And now i can't edit, copy an paste in the CSS code Section

I allready try to edit in the Customize seccion in the Appearance Menu... and dont work.

Please Help Me

**Comment by kprovance** [comment]
A regular user of the theme?  Then you need to contact the theme author for support, as we do not support theme users that use our framework.  This was made clear in the text inside the window you just filled out.  :)

Good luck.

**Comment by DavidRe9** [comment]
Can add this line on wp-config:

/**
*  The constant WP_ACCESSIBLE_HOSTS will allow additional hosts to go through for requests
*/
define('WP_ACCESSIBLE_HOSTS', 'cdn.jsdelivr.net,look.redux.io,');
