### ISSUE TITLE
do i need to buy the redux framework for js_button functionality??? I have tried to add js button manually but the buttons are not visible.

### ISSUE THREAD

**Issue by Govind13100** [reduxframework/redux-framework#3281]
Redux::setSection( $opt_name,    array(
                'title' => __('Discovery'),
                // 'icon' => 'el el-th-large',
                    'desc'  => __('<br /><div class="outer-design-sectionss"><div class="design-sectionss">Discovery Section</div></div>'),
                'subsection' => true,
                'fields' =>
                    array(
                        array(
                                'id'       => 'ampforwp-discovery-on-off-support',
                                'type'     => 'switch',
                                'title'    => __('Discovery', 'redux-framework-demo'),
                                'subtitle' => __('Enable/Disable Discovery using this switch.', 'redux-framework-demo'),
                                'default'  => '1',
                                
                        ),
                        array (
                                'id'            => 'opt-js-button',
                                'type'          => 'js_button',
                                'title'         => 'JS Button',
                                'subtitle'      => 'Run javascript manually from the options panel.',
                                'script'        => array(
                                    'url'       => get_template_directory_uri() .  '/sample.js',
                                    'dep'       => array('jquery'),
                                    'ver'       => time(),
                                    'in_footer' => true
                                ),
                                'buttons'       => array(
                                    array(
                                        'text'      => 'Add Date',

                                        // This class causes the button to appear colored in the options panel
                                        'class'     => 'button-primary',

                                        // The name of the function to execute in the sample.js file
                                        'function'  => 'redux_add_date'
                                    ),
                                    array(
                                        'text'      => 'Alert',
                                        'class'     => 'button-secondary',

                                        // The name of the function to execute in the sample.js file
                                        'function'  => 'redux_show_alert'
                                    ),
                                ),
                            ),
                               // This empty text field will be used for the redux_add_date function to fill out 
                        // with the current date, when the button is clicked.
                        array(
                            'id'        => 'opt-blank-text',
                            'type'      => 'text',
                            'title'     => 'Date',
                        ),
                    )
                )
   );
I am new to redux framework , any help will be very delightful.

Thanks in advance.

**Comment by kprovance** [comment]
The JS button is a premium extention that requires purchase.  It is not included with the redux core.

Http://www.reduxframework.com/extensions/js-button

**Comment by Govind13100** [comment]
Okay thank you
