### ISSUE TITLE
Can we make the support system like our own?

### ISSUE THREAD

**Issue by ayanize** [reduxframework/redux-framework#3282]
Hi Redux Team,

This is a question more than an issue. I have embedded Redux in a theme.

Like you ask us (developers) to provide you with the Support Hash and System Status whenever we create an issue at the Github and you usually review this at your end. Is there a way we can make this our own? Like we ask our theme users to provide us with a Support hash and give us system status and we debug this at our end.

Is it actually possible? If, how we can comprehend the hash?

Thanks once again and thank you for making Redux Framework.

**Comment by kprovance** [comment]
Ancient Chinese secret.  :)

Actually, this is a service we plan on offering 8n the next phase of redux, so I'm not certain how anxious don't will be to give up those algorithms.   However, I'll give him the chance to chime in to make that call, since he designed that feature.  @dovy?

**Comment by kprovance** [comment]
Ps - don't be surprised when.99 percent of your users ignore such requests, and half of that refusing to comply.  It's a great idea on paper.  In practice, not so much.

**Comment by ayanize** [comment]
Thanks for the attention @kprovance . Yes, I understand how frustrating it is when a user/developer ask for support and do not provide any information regarding their system and configuration. We face this all the time. But if you ever plan to incorporate this in Redux, I guess you can then route all those theme/plugin specific (_not actually Redux core package related_) issues to authors and they should bother about this and not you guys. 

Moreover, this will be an excellent feature and developers then guide the users knowing their configuration and system status.

Many thank once again looking into this.

**Comment by kprovance** [comment]
Turns out we are offering this as a premium service in the future.  Sorry.  Thanks.

**Comment by ayanize** [comment]
That will be awesome too. Nothing to be sorry about. However, try to make this so that we can user this on our end products (like themes that we build and users can use) without any limit or so. You can of course keep the best price for this.

Thanks once again.

**Comment by dovy** [comment]
There will be no limits for devs who use the service. There wouldn't be a need to. ;)

**Comment by ayanize** [comment]
That's really awesome. Looking forward to having this service in action soon. Thanks once again.
