### ISSUE TITLE
how can i get the value on change of select box. I need to get the value of 1st select box through which i will fetch value and display into another text box?

### ISSUE THREAD

**Issue by Govind13100** [reduxframework/redux-framework#3283]
Is there any functionality to achieve this kind of result???

Look at my code
`array(
                            'id'       => 'opt-redirection-data',
                            'type'     => 'select',
                            'title'    => __('Source URL', 'redux-framework-demo'),
                            //'subtitle' => __('No validation can be done on this field type', 'redux-framework-demo'),
                            'desc'     => __('You can select source url to perform delete or update operations', 'redux-framework-demo'),
                            //Must provide key => value pairs for options
                            'options' => $source_url,
                            'class'     => 'tr-border-none',
                            
                        ),
                         array(
                            'id'        => 'opt-source-operation-url',
                            'type'      => 'text',
                            'title'     => 'Source URL',
                            'desc'      => __('Source URL', 'redux-framework-demo'),
                            'class'     => 'tr-border-none',
                            'default'   => $source_url[1],
                            'required'  => array(array('opt-redirection-data',)),
                            
                        ),` 

The `$source_url` this is the select box from which i want to get the value on change event.

I tried using JQuery 

`$(document).ready(function(){alert( $('#opt-redirection-data-select').val());
    $("#opt-redirection-data-select").change(function(){
        alert("The text has been changed.");
    });
});`

I have passed the correct id of the select box, when i alert the value of this id the result is positive, but it doesn't work in change event ?? why so?? 

Any help would be appreciated.

Thanks in advance.

**Comment by kprovance** [comment]
Inherently with redux, no.  Custom javascript will be necessary.  Since it's outside the scope of what we offer for support. It becomes a premium support situation.  Email me, kevin@reduxframework.com if you need that service.
