### ISSUE TITLE
Plugin

### ISSUE THREAD

**Issue by dhananjaymayane** [reduxframework/redux-framework#3286]
Hi,

I am looking for the plugin which are currently using Redux Framework for their dashboard settings.

**Comment by kprovance** [comment]
This IS the Redux Framework plugin.  If you are looking for plugin examples that use Redux for their panel, you'll have to search the Internet.  Or reads our docs site and build your own:  https://docs.reduxframework.com

**Comment by dhananjaymayane** [comment]
Hi,

Is there any option for getting this work.
![screenshot from 2017-04-20 13-06-25](https://cloud.githubusercontent.com/assets/21101779/25218950/496d5566-25ca-11e7-9926-abc3530bf9d2.png)

**Comment by kprovance** [comment]
That's not anything Redux offers.  If it's out there, then it's a custom extension that we do not have access to.
