### ISSUE TITLE
Redux generator not working. (https://build.reduxframework.com)

### ISSUE THREAD

**Issue by kulwinder1150** [reduxframework/redux-framework#3287]
Hi. I try to integrate redux framework in my theme. After I used the redux generate to build files according to my theme. When I click on the (Generate admin folder) button, generated zip file is broken.

![one](https://cloud.githubusercontent.com/assets/27079528/25305515/57750f92-279a-11e7-938a-c34340ae59c8.png)

![two](https://cloud.githubusercontent.com/assets/27079528/25305514/57750600-279a-11e7-91a0-c812d6cb9ac6.png)

What should I do?

**Comment by andywarren** [comment]
I'm also experiencing issues with it, although I can't even get it to generate a zip. It just sits there and spins for as long as you let it once you click "Generate admin folder". Any help would be much appreciated!

**Comment by dovy** [comment]
Helped Andy directly. We need to fix the builder. It's on our todo list.  ;)

**Comment by dfrey382** [comment]
i am also experiencing this problem, i have created the theme but cant get any generated zip, just keeps rotating. Any help would be much appreciated!

**Comment by kprovance** [comment]
It's down.  We know.  Says so in half a dozen other posts.  Sorry.  Hopefully it will be fixed soon.

**Comment by dfrey382** [comment]
@kprovance I will appreciate that so much thanks,let me know when the build.redux is up
