### ISSUE TITLE
How Translate Theme Option with Poedit?

### ISSUE THREAD

**Issue by vucumbra** [reduxframework/redux-framework#3288]
Hi
i have problem to translate into backend the theme option field
Of course i use my textdomain
`'title'    => __( 'Registration Message', 'my-textdomain' ),`
and i can see all string into "Loco Translate Plugin"

but if i translate the string i can't see the update into my backend, just with theme option redux not working
with other all theme's string working good

What i wrong? Thx

**Comment by kprovance** [comment]
This is not something we support.  Sorry.  Good luck.

**Comment by kprovance** [comment]
Well, lemme rectify.  Using PorEdit, you are on your own.  Our translations don't need to be changed.  If your backend - meaning your option panel - is not translation with YOUR text domain properly etnered, then that also is not a Redux issue, because it is not Redux doing ANY of the translating of your option panel.

**Comment by vucumbra** [comment]
yes ok i have understand but
how translate "title and desc  fields"? just manually in php file?
and if my customer want translate the theme option in his language?
```
array(
                'id'       => 'email_sender',
                'type'     => 'text',
                'title'    => __( 'Email Sender', 'adsclassi' ),
                'desc'     => __( 'Input here the sender\'s email', 'my-text_domain' ),
            ),
```
i repeat with poedit i can find this 2 string, but translation not have any effect
Regards

**Comment by kprovance** [comment]
Again, I apologize for having to tell you this goes beyond the scope of our support.  We have premium support for $100.00 an hour if you like, but translation issues are not a Redux issue.

**Comment by ayanize** [comment]
Load your text-domain ahead of Redux config. Do the following

`/*...LOADIGN TEXT DOMAI..*/
add_action( 'after_setup_theme', 'load_my_text_domain', 10);
function load_my_text_domain(){
	// for child themes
   // load_child_theme_textdomain( 'text-domain', get_stylesheet_directory() . '/languages' );
   
   // for parent themes
   load_theme_textdomain( 'text-domain', get_template_directory() . '/languages' );
}

/*....CALLING REDUX OPTIONS...*/

function my_opt_redux_config(){
if ( !isset( $my_opt_name ) ) {
    require_once get_template_directory(). '/sample-config.php' ;
	
	// child themes
	
	require_once get_stylesheet_directory(). '/sample-config.php' ;
	
}
}
add_action('after_setup_theme', 'my_opt_redux_config', 20);`

**Comment by HivaEzami** [comment]
to solve this issue: 
i have the same problem, it was why that my text-domain  was after redux and to solve this broblem i move the text-domain  to first lines of functions.php file and it solved.

**Comment by Jimmi08** [comment]
> to solve this issue:
> i have the same problem, it was why that my text-domain was after redux and to solve this broblem i move the text-domain to first lines of functions.php file and it solved.

Thank you so much.  Moving to the first line was the only thing that helped. In the child theme was enough. I spent on this the hours! Thanks.

**Comment by HivaEzami** [comment]
> > to solve this issue:
> > i have the same problem, it was why that my text-domain was after redux and to solve this broblem i move the text-domain to first lines of functions.php file and it solved.
> 
> Thank you so much. Moving to the first line was the only thing that helped. In the child theme was enough. I spent on this the hours! Thanks.
in recent versions there is different ways to solve this issue , but it still works
wishes best for you, bro
