### ISSUE TITLE
Using Redux to control Bootstrap 3 media query

### ISSUE THREAD

**Issue by franksteelcastle** [reduxframework/redux-framework#3290]
Dear Developer,

I want to control some css selectors within a Bootstrap 3 media query.
For example:
@media {min-width:  700px;){
.css-selector: black;
}}

Can I control with Redux the .css-selector element?
Is there a solution in this case the dynamic CSS and compiler function of Redux?
Thank you!

**Comment by kprovance** [comment]
I honestly have NO idea what you are asking or talking about.  Did you ready ANY of the text in the new issue window?  We need more information thn this.

**Comment by kprovance** [comment]
If you want to do media queries, you have to write them yourself via the compiler function.  It's not something Redux will do inherently.  I don;t even think that possible without a major rewrite of the entire core, which we won't do.  Sorry.
