### ISSUE TITLE
Children fields not showing up even if the parent switch fields is on

### ISSUE THREAD

**Issue by bilal-pp** [reduxframework/redux-framework#3293]
Hi,

I have a parent switch field and there are dependent color rgba fields. Toggling the switch works fine, but when I save the settings with the switch field on and selecting the color in the children field, the switch remains on which is fine but the children color rgba fields won't show up. Below is the code for the same:

               array(
	            'id'       => 'test_switch_field',
	            'type'     => 'switch',
	            'title'    => 'Test Switch Field',
	            'subtitle' => '',
	            'desc'     => '',
	            'default'  => false,
	        ),

	    	array(
			    'id'       => 'test_child_1',
			    'type'     => 'color_rgba',
			    'title'    => '', 
			    'subtitle' => '',
			    'desc'     => 'Child 1',
			    'default'  => '#FFFFFF',
			    'validate' => 'color',
			    'transparent' => false,
			    'required' => array('test_switch_field','equals',true)
			),

			array(
			    'id'       => 'test_child_2',
			    'type'     => 'color_rgba',
			    'title'    => '', 
			    'subtitle' => '',
			    'desc'     => 'Child 2',
			    'default'  => '#f2f2f2',
			    'validate' => 'color',
			    'transparent' => false,
			    'required' => array('test_switch_field','equals',true)
			),

Thanks,
Bilal

**Comment by kprovance** [comment]
Please provide the requested support url.  It is not optional.

**Comment by kprovance** [comment]
PLease update to v.3.6.4.4
