### ISSUE TITLE
Redux-Framework does not see the content files in the template-parts folder

### ISSUE THREAD

**Issue by serqanay** [reduxframework/redux-framework#3294]
hi,

In my theme index.php file

get_template_part( 'template-parts/content', get_post_format() );

I call the file in the form.

Why do not I see the content files in the template-parts folder?

**Comment by kprovance** [comment]
I'm sorry, but this is not a Redux issue.  This is a theme issue, and we are not the theme authors.  You will have to contact the actual theme author for support.  Sorry. Good luck!
