### ISSUE TITLE
Little Problem with the field "Select and Multi"

### ISSUE THREAD

**Issue by EMembrillas** [reduxframework/redux-framework#3295]
When a field  "Select and Multi" is created, and that field is an empty array, to save any options within the redux panel, the fields do not appear in the global variable.

```
array(
                'id'       => 'roles-sorter-postsgestor',
                'type'     => 'select',
                'multi'    => true,
                'title'    => 'Desactivar Tipos de posts para el usuario Gestor',
                'subtitle' => 'Arrastra para desactivar los posts que no debe ver el Gestor',
                'desc'     => 'This is the description field, again good for additional info.',
                'data'     => 'post_type',
            ),
```
I have tried putting as default value: a string, an empty array and removing the default value as in the above code. If this fiel is empty the result is the same.

Notice: Undefined index: roles-sorter-postsgeneral in /var/www/vhosts/.../roles.php on line 168

I think it has to be a code error since it only happens with this type of field

**Comment by kprovance** [comment]
When you opened the new issue window, did you read all the text we provided?

**Comment by EMembrillas** [comment]
Yes! I guess I did not write this here. I just write it because I thought it was a mistake. Sorry

**Comment by kprovance** [comment]
Well, if we can't get the support URL, I will just assume that toles.php is part of your project, and that when there is no data, there is no default array.  Do an isset check on the variable and catch it that way.
