### ISSUE TITLE
field type textarea for custom js/css code ?

### ISSUE THREAD

**Issue by vucumbra** [reduxframework/redux-framework#3296]
Hi
exists a field for js code and css code like textarea but with colors formatting code?
Thx for your work

**Comment by vucumbra** [comment]
oh sorry i have find in sample example
thx

**Comment by kprovance** [comment]
Not to mention we did not author your theme and could not support it anyway.  In the future, please direct your questions to the theme author, which is NOT us.  Thanks.

**Comment by vucumbra** [comment]
i try to make a new theme and i have implemented your plugin, i can't ask to author's thema becouse i'm author and this is first time i have used redux
sorry for question
