### ISSUE TITLE
 Hello, how can I change the output_type from the theme options

### ISSUE THREAD

**Issue by ernest35** [reduxframework/redux-framework#3299]
Hello, how can I change the output_type from the theme options
This is my first issue I apologize for if I incorrectly designed it
```php
function is_dymanic_css_active(){
	global $theme_options;
	return $theme_options["activate_dynamic_css"];
}

$output_type = "output";

if( is_dymanic_css_active() ) $output_type = "compiler";

array(
    "id"       => "top-bar-bg",
    "type"     => "background",
    "title"    => __("Top bar background", "theme"),
    $output_type   => array(".topbar-wrapp"),
    "default"  => array(
        "background-color" => "#83b735"
    )
),

array(
    "id"       => "activate_dynamic_css",
    "type"     => "switch",
    "title"    => __("Activate Dynamic Css", "theme"),
    "default"  => false,
),

**Comment by kprovance** [comment]
The best way toi pull option on the fly, from within the option panel is to use the Redux API getSetting

```php
Redux::getSetting ($opt_name, $id)
```

Replace $opt_name with your projects opt_name, and ID should be self explanatory.

**Comment by ernest35** [comment]
Fatal error: Uncaught Error: Call to undefined method Redux::getSetting() 

What could be wrong?

**Comment by kprovance** [comment]
Let's do this:  Open an new issue window.  In it, hopefully this time you will see we provided specific instructions on the data we require.  Please read it in its entirety and post back everything we need.  Thanks.

**Comment by ernest35** [comment]
okay,thank you
