### ISSUE TITLE
FEATURE REQUEST: Remove unnecessary title="dynamic-css" class="options-output" on Compiler Output

### ISSUE THREAD

**Issue by davemoore24** [reduxframework/redux-framework#3302]
What is the purpose of giving a class to the style tag in the header? There is zero need for both the title and class on this output. 
<style type="text/css" title="dynamic-css" class="options-output"></style>

**Comment by kprovance** [comment]
Backward compatibility with old version of Redux and SMOF.  We don't break things unless we don;t have to.  We aren't WooCommerce, after all.
