### ISSUE TITLE
FEATURE REQUEST: Allow max/min height/width for dimensions field

### ISSUE THREAD

**Issue by davemoore24** [reduxframework/redux-framework#3303]
As most websites are responsive, giving the option to use max/min height/width would be a nice feature.

**Comment by kprovance** [comment]
If we did something like this, it would be for the next major upgrade and not the current 3.x version.  I will add the suggestion to our trello board and open it for discussion among our devs.  Thanks.

**Comment by davemoore24** [comment]
Thanks!
