### ISSUE TITLE
Redux Plugin

### ISSUE THREAD

**Issue by SaharBass** [reduxframework/redux-framework#3304]
HI, I have a problem with your plugin.

When the plugin are Active I can't get inside to edit page or post.

I make this check a few times and with the all plugins, and only Redux plugin do that.

how we can solve this issue?

(if I can to get an email when you respondents, it's very useful)

 thank you,
Sahar

**Comment by kprovance** [comment]
One, none of the information we asked for was provided.  Are you the theme author or the user of a theme that uses Redux?

**Comment by kprovance** [comment]
But also, please provide the information we asked for.

**Comment by SaharBass** [comment]
I'm user of a theme that user redux,

What you asked?

**Comment by kprovance** [comment]
Okay, if you read the ext we provided when you opened the new issue window, we stated very clearly, we do NOT support users of themes that use Redux.  You must go to the theme author for support.  He is the one who must diagnose your issue, and if he determines there is an issue with Redux, he must come to us with the necessary information.  So, as sorry as I am to have to tell you this, you need to contact your theme author so he can figure out what's going on.  Thanks.  Good luck.
