### ISSUE TITLE
‘Required’ Argument on Media Field not working

### ISSUE THREAD

**Issue by davemoore24** [reduxframework/redux-framework#3305]
I am trying to show/hide another field if a user has uploaded an image to the media field. Since there is no option to require, how would i do this? Custom Validation?

**Comment by kprovance** [comment]
Not sure.  Redux validations won't work, since they are mostly for input fields.  I imagine you'd have to come up with some custom javascript to hide/show another field based on the change in the media URL field, or the value of one of the hidden media fields.  That's what I would do.  Good luck.
