### ISSUE TITLE
builder never downloads

### ISSUE THREAD

**Issue by hozyali** [reduxframework/redux-framework#3308]
Hi, I am trying to generate the admin folder from the builder page, but it keeps on loading and never downloads the actual admin folder of redux framework. I tried various browsers, it seems there is an issue in returning the data when I saw in the console. can you check and advise. thanks

**Comment by kprovance** [comment]
We're aware of it.  @Dovy has to fix it.  I'll poke him with a big stick again.  ;-)

**Comment by hozyali** [comment]
Thanks for the quick reply. Wanted to get started with a theme dev project :) Will wait. hope it gets fixed asap!

**Comment by clinedgegit** [comment]
Also having this issue. Any fix yet?

**Comment by hozyali** [comment]
I couldn't wait so I downloaded the core and started with the sample config file.

**Comment by clinedgegit** [comment]
Thanks for the response @hozyali! Good idea. Guess I'll have to start there. @kprovance @dovy If you get the Builder back up and running could you add a comment here?
