### ISSUE TITLE
Some options not saving

### ISSUE THREAD

**Issue by ACODA-LTD** [reduxframework/redux-framework#3309]
Hey guys, 

It was all going so well. For some reason, some of the options aren't saving. I've changed the ID's, values, types etc and no new option I add, will save. 

I then noticed that some options I've already added, do not save either. 

I've removed the extensions, installed on a fresh server, disabled ajax... no issues appear to be reported. 

Any ideas, I've ran out? 

Thank you!

**Comment by kprovance** [comment]
Please go back, open a new issue window, read the entire passage of text, and reply with the REQUIRED information.  Thank you.

**Comment by ACODA-LTD** [comment]
My apologies. 

## Support Hash
http://support.redux.io/?id=Eu74h%2B7N7XCENgKvTTskQ6PBSe3eih%2FREJcP2HYg61o%2FdyktX%2BGEuWLKO2a6awqUKUvKkPqG2EUzeKY3PrUtxA%3D%3D

## Steps to reproduce
Goto Theme Options > Layout > Option Not Working ( there is a button and select to demonstrate )
Theme Options > Advanced > These options do not save either. 

## Expected Behavior
They should save as with any other option like "Site Layout". 

## Actual Behavior
Not saving and there doesn't appear to be any errors.

**Comment by ACODA-LTD** [comment]
I've noticed that if I change the $opt_name from "dynamix" to "dynamix_theme" or to anything else it seems, it all works? 

Any idea why that would be? Is it because the option name is the same as the text domain?

**Comment by kprovance** [comment]
I have no idea.  I have never heard of this happening.  But if it's fixed and working, then I am closing the ticket.
