### ISSUE TITLE
There was a problem with your action. wordpress theme option

### ISSUE THREAD

**Issue by dimimall35** [reduxframework/redux-framework#3310]
Hello i have a problem with my website wordpress when I press save change in theme options it appears this popup error "There was a problem with your action. wordpress theme option" I have redux framework and I have read in forum that redux may cause this problem. I dont know for sure. I have lake resort. 

Thanks in advance

**Comment by kprovance** [comment]
If you are the user of a theme that uses Redux, you must go to the theme author for support.  We do not support theme users.  Support must come from the theme author.  Sorry.  Good luck.
