### ISSUE TITLE
Unable to Save Typography settings in Theme Using Redux Framework

### ISSUE THREAD

**Issue by arclement** [reduxframework/redux-framework#3311]
I am using a theme called Candidate 16 that uses the Redux Framework. Repeated efforts to change typography settings in this theme either via options import from another theme or via manual entry have failed. Below is a description of the problem forwarded to the theme developer, who used Redux Framework to build the Candidate 16 theme.

Can you help resolve this issue?
******************************
5/6/17
Unable to import most of my Candidate typography settings into Candidate 16, I attempted to edit the settings manually. As you can see, although the settings are recorded, they are not actually displayed on my staging website located here:

http://91c.180.myftpupload.com

How can I get my Candidate 16 typography settings to "stick"?

5/7/17
This problem is not the cache. My ISP, Godaddy, has a cache clearing feature that I have used repeatedly to clear my cache when testing changes to Candidate 16 options. See attached Print Screen that shows that even when the cache is cleared, my webpage displays the same default typography.

I believe the problem is in the Redux Framework plugin that you used to build the Candidate 16 theme. If you can't identify the bug, can you ask Redux Framework developers to identify and fix the problem?

I currently have Redux Framework v3.6.4 Version 4.7.4 | Unyson 2.6.16 installed on my WP site.

**Comment by kprovance** [comment]
You need to obtain support from the theme author.  We do not support users of themes that use redux as we have no way of knowing how they implimented it.  Sorry.
