### ISSUE TITLE
Demo Broken

### ISSUE THREAD

**Issue by awakekat** [reduxframework/redux-framework#3312]
## Support Hash
Don't have hash but it was documented on May 7, 2017 at 5:22pm EST

## Steps to reproduce
Keep going to the demo address: http://demo.redux.io/
## Expected Behavior
Seeing the demo
## Actual Behavior
![demo-broken](https://cloud.githubusercontent.com/assets/5148843/25785243/b36df9ca-3349-11e7-82f8-d8ea51a5bb6b.png)

## Any Error Details (PHP/JavaScript)
See above screen capture

**Comment by kprovance** [comment]
We are aware of this.  Thank you.
