### ISSUE TITLE
Title image

### ISSUE THREAD

**Issue by marinos123** [reduxframework/redux-framework#3313]
Hello
Im trying replace title image but cant find it anywhere. please let me know hoe to replace it. Check the attachment
![h2move](https://cloud.githubusercontent.com/assets/12137467/25799564/1cfcde0c-33ee-11e7-87da-41e03b730168.PNG)

regards,
Marinos Ioannou

**Comment by ayanize** [comment]
Sorry to chip in but I think it has nothing to do with Redux Framework. You should better ask your theme author. Redux is just a Theme Options framework. It does not output anything by default. You should check with your developer how that title image has been called on the front-end and accordingly make your necessary changes

**Comment by kprovance** [comment]
Indeed.  @marinos123, you need to contact the theme author for theme support.
