### ISSUE TITLE
Typography Font Size Media Query

### ISSUE THREAD

**Issue by ACODA-LTD** [reduxframework/redux-framework#3316]
Hey Guys, 

Is it possible to control the "Font Size" output of the Typography field for mobile devices. I want to set a default font size for Mobile and then the "Font Size" is only applied to larger devices via a media query. 

Thanks in advance.

**Comment by kprovance** [comment]
With output?  No.  With the compiler arg which has a filter hook for a callback, you can manipulate the data anyway you like.  See our docs page for more info and the sample-config file for an example.
