### ISSUE TITLE
Submission on WordPress.org

### ISSUE THREAD

**Issue by bilal-pp** [reduxframework/redux-framework#3317]
Hi, My name is Bilal and I am a web developer working for Paperplane Design Solutions in India. Currently we are building a theme that uses Redux Framework to customize the font, link colors, typography etc. While googling theme submission requirements on WordPress.org, I came across an article: 

https://reduxframework.com/2015/04/updated-wordpress-org-theme-requirements/

The above article says that we can use certain field types:

text
checkbox
radio
select
textarea
color
media

Now the question is, Apart from the fields listed above, we have used switch fields, typography fields, colorPicker fields in our theme, will our theme will get rejected by WordPress.org. If yes, then could you please suggest an alternative solution.

Thanks,
Bilal Ahmed

**Comment by kprovance** [comment]
I'm pretty sure switch is supported in the Redux coire.  Typography is not. That will be supported in an upcoming extension titled Advanced Customizer.  No ETA when that's happening.

As far as alternatives, I'm sorry but I can think of none.  Redux is pretty much the best thing out there these days...and massive improvements are still forthcoming.
