### ISSUE TITLE
There was a problem with your action. Please try again or reload the page.

### ISSUE THREAD

**Issue by suhan7773** [reduxframework/redux-framework#3319]
## Support Hash
http://support.redux.io/?id=CPOGPkr39b2A4ivmmssatM20hKG2Y5M1KHdwrtHbY4y8%2Bb8ZLzZHpNXqMh96NJ5v27ZpzME%2B0nCg4%2B1576JD8w%3D%3D

## Steps to reproduce
go the theme option (Tasty Option)-> made changes on any setting->save->Error (There was a problem with your action. Please try again or reload the page.)
## Expected Behavior
Changes should be saved and reflect in the site.

## Actual Behavior
changes will not be save and will get error message : There was a problem with your action. Please try again or reload the page.

**Comment by kprovance** [comment]
I can't go to theme options, as I and Redux are NOT the author of this theme.  You need to go to the theme author, specifically.  It said as much in the instructions you just read.  Sorry.  Good luck.
