### ISSUE TITLE
GoogleWebFont subset does not work in IE

### ISSUE THREAD

**Issue by KostaStolbunsky** [reduxframework/redux-framework#3321]
## Steps to reproduce
Choose Arimo Google web font and set Hebrew subset
https://www.screencast.com/t/GmYl5JL5CP

## Actual Behavior
In browser source code it looks as follows
`<link href="http://fonts.googleapis.com/css?family=Arimo:400,700&amp;subset=hebrew" rel="stylesheet">`

## Expected Behavior
While Chrome, Safari and Firefox interpret `&amp;` sign as expected, Internet Explorer (including Edge and below) does not recognise it and as a result a subset does not loaded.

## Any Error Details (PHP/JavaScript)
In file ReduxCore/inc/fields/typography/field_typography.php
Lines 612, 654
`$link .= "&amp;subset=" . implode( ',', $subsets );`

Changed `&amp;` to & as a dirty workaround and now subset is loaded in IE as well

**Comment by kprovance** [comment]
Ill add this in
