### ISSUE TITLE
Update redux-framework on Packagist for Composer

### ISSUE THREAD

**Issue by Log1x** [reduxframework/redux-framework#3322]
Hi.

It seems redux-framework on Packagist has stopped updating with the repository back in March.

Could one of you login and click the manual update button in Packagist so it will update [dev-master](https://packagist.org/packages/redux-framework/redux-framework#dev-master)?

Optionally, you can easily setup Packagist's API to auto-update every time a change is pushed to the repo.

Thanks in advance.

**Comment by kprovance** [comment]
@Dovy?  I don't have login data for this.

**Comment by dovy** [comment]
@Log1x I signed in again. If you could provide direction to update the packagist API i'd integrate that tomorrow. ;)
