### ISSUE TITLE
Extend output functionality. 

### ISSUE THREAD

**Issue by ACODA-LTD** [reduxframework/redux-framework#3324]
Is there a way to extend the "output" functionality? 

I was going to use the "Background" field, but then realised it doesn't work with Customizer. So my questions are. 

1. Is there a way to make the "Background" field work with customizer. 

2. Is there a way to extend the "output" functionality to include "background-image" and if so, do you have an example of how to achieve this. I don't mind paying for it. 

Thank you.

**Comment by kprovance** [comment]
You customizer func functionality you would need the advanced customizer extension, which dovy has not yet finished.  As for output, specify your class name in the output arg.

But once again I must tell you that all tickets require a support hash /url.  One will be required in any follow-up replies so please be sure to include

**Comment by kprovance** [comment]
Also for the background field to produce the background - image selector you must select an actual image in the background field and save it

**Comment by ACODA-LTD** [comment]
Thanks for the reply. However, because the "background" field can't be used in the Customizer, I need to use an alternative. Ideally I'd want this to work:

			array(
				'id'       => 'header_image',
				'type'     => 'media', 
				'url'      => true,
				'title'    => __('Background Image', 'dynamix'),
				'output'    => array('background-image' => '.header-wrap-inner'),
				'subtitle' => __('Set a Background Image.', 'dynamix'),
			),	

But the output doesn't support that. Is there a way to extend the 'output' to support that? If so, how can that be achieved? 

Thanks


Here's the support hash
http://support.redux.io/?id=sYV1j668ecFqejncZ6a%2FL5gLz%2BVE3E4GzPYl4kGy2QDI%2FrXAFt4D2pV5g4Jfj%2BuhXK9T2vi5vzmK51m4tmcK1g%3D%3D

**Comment by ACODA-LTD** [comment]
@dovy, how far along is the customizer extension? The two fields I'd love to have working in the Customizer is the "Background" and "Typography". Thank you.

**Comment by kprovance** [comment]
You are setting your output incorrectly:  Outputs set output as such based on field type.  ALl you need to do is pass an array of selectors (or single selector).  The field does the rest.

https://docs.reduxframework.com/core/the-basics/output-2/
