### ISSUE TITLE
google fonts are no working 

### ISSUE THREAD

**Issue by MartynaC** [reduxframework/redux-framework#3326]
Hi 

I am developing a wordpress website using Redux Framework. 

The Google fonts are blocked because of the framework. If it is disabld you can see them working, but once on they change to Arial. 

I have set the Google Api key and the fonts are uploaded to theme itself to. 

Attached the screenshot from sample-config.php and from the developer window, where the font can be actually seen as set, but not working. 

Can I get sme help here?

<img width="1278" alt="zrzut ekranu 2017-05-16 o 19 58 45" src="https://cloud.githubusercontent.com/assets/11480941/26121053/43775cac-3a73-11e7-872c-a0c2b6285b60.png">
<img width="1280" alt="zrzut ekranu 2017-05-16 o 20 06 52" src="https://cloud.githubusercontent.com/assets/11480941/26121060/49512c0c-3a73-11e7-943c-4f5b6a8d55d3.png">

**Comment by kprovance** [comment]
I don't want screen shots.  I want the support/URL has that we specifically asked for when you opened this ticket.  If you cannot provide that critical piece of information, then please close this ticket.  Thanks!
