### ISSUE TITLE
Maximum Upload Size Dropped

### ISSUE THREAD

**Issue by chrisdfellowes** [reduxframework/redux-framework#3327]
Hi guys,

Just logged in as normal to do my monthly podcast upload and the maximum upload size has dropped from around 64mb to 8mb. Any ideas???

Thanks.

**Comment by kprovance** [comment]
Sorry to hear this.  However, it's not a Redux issue.  It's a WordPress config issue, and not under the scope of our support.  Sorry.  Good luck.
