### ISSUE TITLE
Shortcode not working in the editor

### ISSUE THREAD

**Issue by adrian200065** [reduxframework/redux-framework#3328]
Hello, I have a very simple contact form that I am using a shortcode to display the form. The shortcode works in the regular WordPress editor without any issue.  I want to display the contact form on my homepage. So I create a module with Redux (version 3.6.5) with the type of editor but it won't display the form.  It is displaying the shortcode code itself. Although I switch to text mode instead of visual just can't get it to work. I welcome any suggestion on how to resolve this issue. Here is my code I setup in Redux.
                     array(
                            'title'     => __( 'Contact Title', 'mkcj' ),
                            'subtitle'  => __( 'Title text for the contact module.', 'mkcj' ),
                            'id'        => 'contact-title',
                            'default'   => 'Add your contact title here',
                            'type'      => 'text',
                        ),

                         array(
                            'title'     => __( 'Contact Form', 'mkcj' ),
                            'subtitle'  => __( 'Add contact form short code for the contact module.', 'mkcj' ),
                            'id'        => 'contact-form',
                            'default'   => 'Add your contact form short code here',
                            'type'      => 'editor',
                        ),
Thanks.

**Comment by ayanize** [comment]
Try this instead. This is a basic one though

```
function redux_editor_demo(){
global $my_opt;
$editor = isset($my_opt['my_editor_id']) ? $my_opt['my_editor_id'] : ''; 
$output = do_shortcode($editor);
echo $output;
}
add_action('wp_head_or_your_own_hook', 'redux_editor_demo');
```

**Comment by adrian200065** [comment]
Hi Ayanize, thanks for your suggestion. I tried it but it did not work. I decided to put the form code in the contact page module and not use a shortcode. I need to finish this project.  I am somewhat new to WordPress development so it takes to longer to figure out correct PHP syntax. Once I get it to work I will post my answer.  Thanks again.

**Comment by kprovance** [comment]
do_shortcode is the correct WP API to output to that contains shortcode tags.  The problem may be in the hook, and when it runs.  I don't know.  Most editor output is done at the page level.  Not sure why a wp_head hook it necessary.

**Comment by tanmoybiswas87** [comment]
Hi adrian200065, 
sorry for late. Here your solutions .Shortcode  working in the editor.  
  $output = do_shortcode($redux_demo['testimonial-editor-text']);
  echo $output; 
Thanks
