### ISSUE TITLE
Is it possible to reload a field from a section by clicking on its tab?

### ISSUE THREAD

**Issue by ghustavosm** [reduxframework/redux-framework#3329]
For example, when modifying a field in a section, it will modify the options of a select in another section. But, the select field needs to be reloaded to display the new options.

**Comment by kprovance** [comment]
Inherently, no.  You'd have to code up some custom javascript to accomplish such a thing.

**Comment by ghustavosm** [comment]
I think the best solution is to reload the page by clicking the tab. Is there a native solution for this to happen?

Alternatively, I thought of this solution:
```php
add_action('admin_footer', function() {
    if(get_current_screen()->id == 'toplevel_page_{PAGE-SLUG}') :
        ?>
        <script>
            jQuery(document).ready(function() {
                jQuery('.redux-group-tab-link-a[data-key={TAB-INDEX}]').mouseup(function() {
                    window.location.href = '/wp-admin/admin.php?page={PAGE-SLUG}&tab={TAB-INDEX}';
                });
            });
        </script>
        <?
    endif;
});
```

**Comment by kprovance** [comment]
Honestly, I don't know.  This goes beyond the scope of basic support.  This is a premium support issue that would require me devoting my time to it.  It's basically $100 an hour will a two to three hour minimum to setup my local with our config and then working it all out.  Sorry.  I wish I could be of more help, I just don;t have the time to give away anymore.

**Comment by ghustavosm** [comment]
I'm just asking if there is a native solution in your Framework for the page to be regenerated by clicking on a tab. Something like an argument in Redux::setSection. If it does not, the hint is for a future implementation, because this is important for situations like this. With it the framework would be even more robust. My solution works, so you do not have to waste time testing. My intention is just to share the idea with someone who has the same problem. And I'm not charging for it.

**Comment by kprovance** [comment]
Oh, I'm absolutely certain if I spent days upon days of adding all this robust stuff, it woul dbe great for maybe three people.  Who's paying for that?  How much have you donated to Redux (don't answer, it's rhetorical, I already know).  People have been cheap with us for years, always wanting more, but never seeming to want to donate back to us, especially those are are pulling in massive bucks.  I might be inclined to spend that time on such features, but people will pay for it in the form of a Pro version of our software, as the days of giving away our hard, and very valuable work, are over.  Cheers!

**Comment by dovy** [comment]
@ghustavosm That's an interesting idea. In the past we were much more willing to implement feature ideas. Nowadays, we're careful to incorporate further bloat. I do, however, believe that could be a smashing extension. It just would depend on the use case.

There are often features some would want, but without a mass support of the request it becomes difficult to justify the effort. IE, as Kevin described, it becomes difficult to sustain a project on features that have small impact to our developers.

However, if you could describe more fully a use case, perhaps we could see what you are saying.

We are currently hard at work on a few new smashing versions of Redux. Our focus is to reduce complexity, increase security, and make it much more extensible for the future.

Please don't stop making suggestions. In fact, I'd like to hear more.

**Comment by ghustavosm** [comment]
@dovy, sorry for any inconvenience.

In a software with tabs it is often necessary to change the value of a field in a tab according to the value that was recorded in a field in another tab.

Let's assume I want to create a custom select in a section, where the listed options were chosen in a multiselect in another section.

You can not currently do this without deactivating ajax_save globally. Disabling would be a problem because it makes it very difficult to navigate in other sections. The simplest idea would be to reload the page or fields only when you click on the tab with the custom select field or reload certain fields when you click the save button.

An example application would be as follows:
I have a multitext in a section where I register colors. In another section, I have a select that needs to retrieve the name of the colors to be selected.

Also imagine a section where I have a repeater. In another section I need to generate a select with the repeated fields titles.

There are several applications. At first, I asked if the framework would be able to reload the value of a field because when searching here, I found users with the same doubt. In fact, it seems that you have implemented a solution that does not work in the current version of the Framework.

Similar Cases:
Https://github.com/reduxframework/redux-framework/issues/2389
Https://github.com/reduxframework/redux-framework/issues/2523

I solved my problem with a custom javascript. My idea was to share this need so you could think about maybe implementing a native solution that could make the framework even better.

If that was not a good idea, it was just a suggestion.

Thanks @dovy, for your excellent service.
