### ISSUE TITLE
White screen issue with Redux framework

### ISSUE THREAD

**Issue by marinaaisa** [reduxframework/redux-framework#3331]
Hello!

I'm using Redux framework and I'm getting a white screen in the admin pages of the plugin.
I have tried to desactive plugins to get which one is the one causing the white screen of death issue and it's Redux.
I tried this plugin with different themes and it's not working in any of them.

What can I do to fix it?

Thank you very much.

**Comment by dovy** [comment]
@marinaaisa What host are you using? Have you tried turning wp_debug on?

**Comment by marinaaisa** [comment]
Yes, I turned wp_debug in the wp_config.php and it's not returning any log or error in the screen.

All the Wordpress admin works but Redux settings. :(

I'm using a normal host from https://www.arsys.es/ Should I contact with them?

**Comment by dovy** [comment]
Seems like these's something off. My guess is file permissions. Try removing Redux completely and installing it via the WordPress plugins "add new" interface. If it installs there, and still has errors, you need to find out why. Tell your host to point you to your error.log file.

Wish I could help more. This seems permissions or host specific.

**Comment by dovy** [comment]
And make sure you're not running a plugin/theme that may use Redux. Developers "hook" into our functions and can have errors in their code.  ;)

**Comment by marinaaisa** [comment]
Redux was a mandatory plugin for the theme that I bought. Should I contact with the creator of the theme?

**Comment by dovy** [comment]
That helps, but without the "resource" it's trying to load, I have no idea what it could be.  :(

Can you give me more of the error instead of that blurb?

**Comment by dovy** [comment]
Here's what I'd do.

Do as I suggest above. Install Redux via the plugin install. Disable your new theme (switch to something else). Then go to the plugins screen, find redux, and activate demo mode. IF you can access the "Sample" panel then yes it's 100% you're author's issue.

**Comment by marinaaisa** [comment]
I just tried what you suggested. The demo mode is not working either and it's giving me notices as "Redux Framework Notice: There are references to the Redux Framework support site in your config's admin_bar_links argument. This is sample data. Please change or remove this data before shipping your product."

**Comment by dovy** [comment]
If it's not working, did you do as I suggested? Uninstalled your redux of version and installed via the WP interface?

**Comment by marinaaisa** [comment]
Yes, I did the uninstalled and install again with a different theme and using the active demo mode.

**Comment by marinaaisa** [comment]
After doing all what you suggested, it's still the same problem: white screen in the Redux framework plugin admin pages.

**Comment by dovy** [comment]
Honestly, I am sorry to say, seems like a host issue. Contact your host and see if they can get you the PHP error logs.  :(

**Comment by marinaaisa** [comment]
Hello Dovy!
PHP has been updated to version 7 and it seems to work now! :)
Let's hope I don't have more problems in the future!

**Comment by marinaaisa** [comment]
Thank you very much :)

**Comment by dovy** [comment]
So odd, what was it before? We work to PHP 5.2 and up. Either way, glad it's working. Best of luck!
