### ISSUE TITLE
Woocommerce Select2 js conflict

### ISSUE THREAD

**Issue by GTO-1** [reduxframework/redux-framework#3332]
With WC 3.07 and Redux 3.6.5. we get the following js error when trying to save product attributes. Disabling Redux Framework solves the issue (but i built a plugin relying on Redux and therefore users are in trouble at the moment).

If you need more error logs, let me know i'm happy to help as good as i can.

Daniel

```
Uncaught Error: Option 'ajax' is not allowed for Select2 when attached to a <select> element.
    at String.<anonymous> (select2.js:930)
    at Function.each (load-scripts.php:2)
    at constructor.prepareOpts (select2.js:928)
    at constructor.prepareOpts (select2.js:2601)
    at constructor.init (select2.js:690)
    at HTMLSelectElement.<anonymous> (select2.js:3391)
    at Function.each (load-scripts.php:2)
    at a.fn.init.each (load-scripts.php:2)
    at a.fn.init.$.fn.select2 (select2.js:3378)
    at HTMLSelectElement.<anonymous> (wc-enhanced-select.min.js:1)
```

**Comment by GTO-1** [comment]
@kprovance - To narrow it down a bit. I have a select2 dropdown added to product pages in the backend to select a custom posttype. Hope that helps a bit and let me know if i should send more details. Would be awesome if we could solve this as i guess other Redux users will run into the same problems since the last WC update.

Thank you Kevin and have a great day.

Daniel

![select2](https://cloud.githubusercontent.com/assets/16824831/26356532/a2cd8132-3fcc-11e7-8be4-f47dbe73bb3f.jpg)

**Comment by dovy** [comment]
We're going to try and get a fix in soon. Trying to figure out how to do it correctly.

**Comment by GTO-1** [comment]
@dovy Thank you, good to hear! Let me know if i could help in any way (besides of buying extensions which i did). 

Have a good evening Dovy

**Comment by GTO-1** [comment]
I'm temporary using the fix mentioned here : https://github.com/reduxframework/redux-extensions/issues/327

Open core/enqueue.php and find:

```
wp_register_script(
    'redux-select2-sortable-js',
    ReduxFramework::$_url . 'assets/js/vendor/redux.select2.sortable' . $this->min . '.js',
    array( 'jquery' ),
    $this->timestamp,
    true
);
```
Replace with:

```
if ( get_post_type() != 'product'  ) {
    wp_register_script(
        'redux-select2-sortable-js',
        ReduxFramework::$_url . 'assets/js/vendor/redux.select2.sortable' . $this->min . '.js',
        array( 'jquery' ),
        $this->timestamp,
        true
    );
}
```
Otherwise my users have a broken WC backend.

**Comment by nonotei** [comment]
Hello ! I'm not a developper but theese are problems I have with this extension. 
Let me explain to you : 
As my plugin doesn't work I deleted metaboxes file from my FTP. The problem to add product attributes was solve.
But, it delete many features I need to custom my different pages in my WP website. 
Hope your update will be available soon. 
Good luck !

**Comment by kprovance** [comment]
Deleting core files will fix nothing.  Sorry.  I'm not sure how removing the enqueue reference forma file that supports only sortable multi-select support fixed a conflict issue, but, ok.

**Comment by GTO-1** [comment]
@kprovance : I have "only" a select2 dropdown on that pages which still does work if the sortable-js has not been loaded and even more important, the WC product edit fields (ajax) do work again after that.

BTW. any ETA of the pro version for Redux? I'm happy to buy it whenever it's available!

**Comment by GTO-1** [comment]
Dear @kprovance @dovy 

Any news on this? Not to sound unthankful just to let you know the issue still exist after the last WC and WP updates.

Thanks guys i know you are working hard and i'd love to help you out with this, but i think unless WC changes this or Redux updates to a newer version of select2 there's not much we can do.

Cheers  Daniel

**Comment by kprovance** [comment]
Is your temporary fix no longer working?  We still have no ETA,  The 4.x update for Redux which has the updated select2 is still a way off.  I had hoped by end of summer.  Now it's looking beyond that.  The alternative is to fix 3.x with the update, but the code changes are considerable due to the way the select2 handled events and parameters now.  Several hours at least, to do it, and as I told someone else who asked about it, I'd prefer to somehow be paid for that time, since it pulls me away from things I have to do now.  I suggested starting a crowdfunder of some type.  I'm thinking that didn't happen.  :)   Sorry.
