### ISSUE TITLE
Google font, nouisider and color picker not working

### ISSUE THREAD

**Issue by Vikram-ksingh** [reduxframework/redux-framework#3333]
I have integrate redux framework on wordpress theme and its working properly on most of the system except one server. On this server theme options are not showing properly like google font field is missing, noui-slider is not showing. they are working properly on other servers.

I checked for the files permission and they are 777 so its not a permission issue. I am using latest redux framework and wordpress.

following are screenshots for issues.
http://tinyurl.com/me77jce
http://tinyurl.com/madpurx

Please guide me to resolve the issue

**Comment by kprovance** [comment]
Need you to open this window again, read all the prepared text and supply us with the information no included.  It;s required

https://github.com/reduxframework/redux-framework/issues/new

This is not enough information.

**Comment by kprovance** [comment]
No reply.  Closing issue.
