### ISSUE TITLE
Issue with generating Theme from https://build.reduxframework.com/

### ISSUE THREAD

**Issue by iamharidasan** [reduxframework/redux-framework#3334]
Not able to generate the theme

**Comment by dovy** [comment]
We're hard at work on fixing that. We may have to shut down the builder for a bit.  :(

**Comment by Jim-E** [comment]
Yep not working, subscribing for updates on this issue.

**Comment by kprovance** [comment]
https://reduxframework.com/2015/07/theme-check-compliant/ or a more specific issue complete with support URL/hash.
