### ISSUE TITLE
Redux Data Directory Writable

### ISSUE THREAD

**Issue by MrHunter** [reduxframework/redux-framework#3335]
## Support Hash
http://support.redux.io/?id=kYyTjlThGGvAQuOk7gY2TSqCnnXdcx%2FP2VHeF3DyUB3U48Myeb0IoHEVtICNkxtdfP%2BPeMZ06Smb9YX0Uv12%2Fw%3D%3D

## Issue
I am currently working with a customer and they are having some issues when saving the options. I checked under Tools >> Redux Framework >> Status and the "Redux Data Directory Writable" is currently failing:
![screen shot 2017-05-24 at 4 49 03 pm](https://cloud.githubusercontent.com/assets/5040696/26424954/152a15fe-40a1-11e7-9f92-29453e6a02ff.png)

However upon inspecting the redux data directory the user is verifying that the directory is in fact writable:
![permissions](https://cloud.githubusercontent.com/assets/5040696/26425030/716afef0-40a1-11e7-972f-f4ec70e29594.png)

Would there be any other reason that this check would fail or perhaps something configured on the server that is causing Redux to fail this check?

**Comment by dovy** [comment]
It's a permissions issue. Try chmod 775 the uploads directory recursively (or just the redux directory). If that doesn't work you can try deleting the redux directory and try opening a page with Redux on it to recreate.

**Comment by MrHunter** [comment]
Just a follow up for you @dovy, the customer deleted the directory and let Redux create it which solved the saving issues they were having with the color scheme extension however the directory writable check is still failing (even though now Redux functions correctly).

Anyways it's still solved, just thought I'd let you know about the data directory.

**Comment by Flatshift** [comment]
I'm not seeing anything failing to save, but the redux status check defiantly does incorrectly show the wp-content/uploads/redux/ as non-writable.

**Comment by MrHunter** [comment]
There was an incorrect classname causing the failure which was fixed in version 3.6.5.3 (https://github.com/reduxframework/redux-framework/commit/5c57f1bbede6551d5c1cd8ee60ea1d40dcb0db29), if you are using the latest version of Redux you shouldn't get this issue anymore.
