### ISSUE TITLE
Causing 500 error

### ISSUE THREAD

**Issue by Frod279** [reduxframework/redux-framework#3336]
It is causing 500 server errors on the site, the webhost says "it's due to something on your website trying to connect to cloudflare over IPv6 which is causing the site to hang for long periods of time waiting for the connection. See the following strace example:

connect(9, {sa_family=AF_INET6, sin6_port=htons(443), inet_pton(AF_INET6, "2400:cb00:2048:1::6810:180a", &sin6_addr), sin6_flowinfo=0, sin6_scope_id=0}, 28) = -1 ENETUNREACH (Network is unreachable)
close(9) = 0
socket(PF_INET6, SOCK_STREAM, IPPROTO_TCP) = 9
fcntl(9, F_GETFL) = 0x2 (flags O_RDWR)
fcntl(9, F_SETFL, O_RDWR|O_NONBLOCK) = 0
clock_gettime(CLOCK_MONOTONIC, {3512165, 413249357}) = 0
clock_gettime(CLOCK_MONOTONIC, {3512165, 413277775}) = 0
connect(9, {sa_family=AF_INET6, sin6_port=htons(443), inet_pton(AF_INET6, "2400:cb00:2048:1::6810:190a", &sin6_addr), sin6_flowinfo=0, sin6_scope_id=0}, 28) = -1 ENETUNREACH (Network is unreachable)
close(9)

You can see that it's giving "Network is unreachable" meaning it's failing but it does this for large periods of time and won't load the site until it basically gives up trying the connection. This means if you remove whatever part of your site that makes this connection whether it's a plugin or theme related query then it should fix the loading issues on your website."

Through a process of elimination I traced this back to the redux framework, with plugin activated tie to load site (if it actually loads and does not give a 500 error) 55or more seconds, with plugin disabled 5.8 seconds

**Comment by kprovance** [comment]
One of our networks is down  NO idea when it will be back up.  Sorry.
