### ISSUE TITLE
ATTN DEVS:  REDUX BUILDER SITE IS DOWN, PLEASE READ....

### ISSUE THREAD

**Issue by kprovance** [reduxframework/redux-framework#3340]
Attention developers.  Currently, the Redux builder site is down, in as far as attempting to generate an admin folder or theme will not work, or download improperly (zero byte) file.

We are aware of the issue.  There is no ETA when it will be resolved.

It is not necessary to post about this issue.

If you would like to be notified when the builder is back up, subscribe to this post.  When the builder is back up, I will post a reply here and you will receive a notice.

Thank you.

**Comment by dovy** [comment]
The builder is back and working! Sorry for the delay. We had to make some changes to our new box.  ;)

We've moved to a new server and things should be a bit more zippy than they were before. Also, look forward to a new builder in the works with more *cough* options. That is all.  :)

@arelidev @niservers @Jim-E @iamharidasan @hozyali @clinedgegit @kulwinder1150 @andywarren @dfrey382
