### ISSUE TITLE
Redux causing 5xx error on large wordpress site

### ISSUE THREAD

**Issue by mrpriolo** [reduxframework/redux-framework#3341]
I'm running listingpro v 1.0.5 directory theme and when I import my listings the website stops working and returns a 500 internal server error. I have 1.3 million listings in my directory ("wordpress posts")

After looking through the code I found that inside file  /wp-content/plugins/redux-framework/ReduxCore/framework.php

lines 973 to 982 contains the following:

else if ( $type == "posts" || $type == "post" ) {
                            $posts = get_posts( $args );
                            if ( ! empty ( $posts ) ) {
                                foreach ( $posts as $post ) {
                                    $data[ $post->ID ] = $post->post_title;
                                }
                                //foreach
                            }
                            //if
                        }

If i comment out this "else if" for posts than my admin dashboard is able to load. I understand that these lines of code are grabbing the wordpress data from all the posts(listings for my directory) and putting them into an array.

What I don't understand is why it's trying to load all that data into an array. My directory has 1.3 million listings(posts) so I see why it's unable to process successfully. Shouldn't redux only call the post data when i'm viewing or editing a single listing (post).

I'm running on nginx with php 5.6 and mysql 5.5.5(mariadb) with fastcgi and running the wordpress w3 total cache plugin on the latest version of wordpress 4.7.5

My server specs are an AWS EC2 m4.large with 8GB of RAM

Obviously I cannot properly run the site if I comment out those lines of code because then the metabox data is not recorded thus taking away a lot of the themes directory features.

Is there anyway I can have redux only pull the wordpress data when necessary and to only limit it to the current listing ID being edited(vs putting all of them into an array).

Look forward to your responses.

**Comment by kprovance** [comment]
Are you a theme author or a theme user?

**Comment by mrpriolo** [comment]
theme user

**Comment by kprovance** [comment]
Well, typically we do not support theme users, as it's the theme author's responsibility to support their work.  Also, no support URL/hash was provided as specifically asked for in the body of text that was provided in the new issue window.  Right now, that's just how the feature works.  We are working on 'ajaxifying' the select control to only list so many items to be displayed at a time, but that is some ways off.  You could ask the theme author to modify his code to only display x number of items per select box, which is possible using the select2 args for the select field (If you don't know what that means, it's okay, you can pass that onto the author).  However, as we did not author the theme and do not support themes that use our framework, it not a modification we can make.  Also, it could be possible to increase the php and WordPress memory limits, which may also help.  Good luck.
