### ISSUE TITLE
Spacing units_extended issue

### ISSUE THREAD

**Issue by ACODA-LTD** [reduxframework/redux-framework#3342]
When using the units_extended option with padding, setting the individual values with units works the first time, but upon re-loading the options, the units have been stripped from the fields. 

## Support Hash
http://support.redux.io/?id=%2B%2BOO7YsmYMQTsiOlLB25Y5GTwsBNLeXcaTMhBmoHsfJUZZhRojox7PoFEYECmOoRhlA8GPPKD68C%2Fk03Ugnp5Q%3D%3D

## Steps to reproduce
Set the units_extended to true, add the values in e.g. 1.875rem | 15% | 1.875rem | 15%

## Expected Behavior
Saves and displays the units when re-loading the options. 

## Actual Behavior
Strips the units, making them invalid i.e. 1.875 | 15 | 1.875 | 15

**Comment by kprovance** [comment]
This is by design.  The fields were never intended for the unit values to be entered, and why the units select is an option, otherwise the field uses the default option set, or if one is not set, defaults to px.  Any value entered in the fields will be stripped out.
