### ISSUE TITLE
update_option with redux value

### ISSUE THREAD

**Issue by ayanize** [reduxframework/redux-framework#3343]
Hello Redux team,

I want to update an option outside redux global variable using update_option() but it's not saving. Example

```
function get_my_theme_val(){
global $opt_name;
$val = isset($opt_name['my_opt_name']) ? $opt_name['my_opt_name'] : '';
return $val;
// echo $val ... this also does not work
}

```
```
update_option('my_theme_val_opt', get_my_theme_val());
```
It's returning empty value in the option_value in the DB

## Reason for such settings

I want to let users to change/rename the menu title set in the $opt_name arguments

```
     $args    = array(
    'opt_name' => $opt_name,
    'display_name' => $theme->get('Name'),
    'display_version' => $theme->get('Version'),
    'menu_type' => 'menu',
    'allow_sub_menu' => false,
    'menu_title' => get_option('my_theme_val_opt'),
    'page_title' => get_option('my_theme_val_opt'),
    ................
    ..............
    .......
```

**Even I tried with** `apply_filters` **like** 

```
 'menu_type' => 'menu',
    'allow_sub_menu' => false,
    'menu_title' => apply_filters('my_theme_name', 'My Theme'),
    'page_title' => apply_filters('my_theme_name', 'My Theme'),

```

Still it does not work with add_filter like

```
function get_my_theme_val(){
global $opt_name;
$val = isset($opt_name['my_opt_name']) ? $opt_name['my_opt_name'] : '';
return $val;
}
add_filter('my_theme_name', 'get_my_theme_val');

```

Is there any workaround for this?

Thanks for your time in advance.

**Comment by kprovance** [comment]
You're using update_option incorrect where it applies to Redux settings.

I am going to assume $opt_name is a valid global variable you have already set.  It would then be this:

```
update_option ($opt_name['my_theme_val_opt'], get_my_theme_val());
```

FYI, This is untested by me, but how it should be setup.

Or use the Redux API
```
Redux::setOption ($opt_name, opt_id, $opt_value) (please note the opt_name parameter needs to be the string value of your opt_name and NOT the global variable.  That won't work.
```

**Comment by ayanize** [comment]
Hello @kprovance 

Thanks for your direction. I had to make some adjustments but eventually your idea works. The resolution is 

`Redux::getOption ($opt_name, $opt_id, $opt_value);`

Now the `config arguments` will be (_since I want to keep a admin menu title by default until the user changes this_)

```
	$args = array(
    'opt_name' => $opt_name,
    'display_name' => $theme->get('Name'),
    'display_version' => $theme->get('Version'),
	'menu_type' => 'menu',
    'allow_sub_menu' => false,
    'menu_title' => (!empty(Redux::getOption ('opt_name', 'my_menu_title_text', ''))) ? Redux::getOption ('opt_name', 'my_menu_title_text', '') : 'My Theme',
    'page_title' => __('My Theme', 'text-domain'),
```

As you can notice, the 'menu_title' arguments check if there is any input from the user and if so, it retrieves the value. If not, it will put the default one which is 'My Theme' in this case. The screenshots may explain this better below

**The config**

<img src="http://i.imgur.com/eVPRThF.png">

**The default admin menu title**

<img src="http://i.imgur.com/mKilILW.png">

**The changed menu title after user input**

<img src="http://i.imgur.com/2j49FuA.png">

Once again many thanks for this wonderful piece of software named Redux.
