### ISSUE TITLE
Problem activating plugin

### ISSUE THREAD

**Issue by macedo77** [reduxframework/redux-framework#3344]
Fatal error: Allowed memory size of 67108864 bytes exhausted (tried to allocate 72 bytes) in /home/storage/4/9f/4e/canela3/public_html/wp-content/plugins/redux-framework/ReduxCore/inc/fields/typography/googlefonts.php on line 1

**Comment by kprovance** [comment]
You will need to increase php.ini memory limit on your server (if you do not know how to do this, please contact whomever host your site for assistance) and probably also the WordPress memory limit (see the WordPress Codex for instuctions on how to do this.  It will require access to your server and a change of the wep-config.php.)
