### ISSUE TITLE
Admin Bar Priority not working

### ISSUE THREAD

**Issue by robruiz** [reduxframework/redux-framework#3345]
## Support Hash
NA

## Steps to reproduce
Download Latest Redux from Github (currently: 3.6.5). Upload ReduxCore and settings folder contents to plugin "framework" folder. Create copy of sample-config.php file. Include settings and core files in plugin code like so: 
if(!class_exists('ReduxFramework')){
	require_once (dirname(__FILE__) . '/plugin_folder/framework/framework.php');
}
if(!isset($redux_demo)){
	require_once (dirname(__FILE__) . '/plugin_folder/settings/settings-custom.php');
	require_once (dirname(__FILE__) . '/plugin_folder/settings/settings-config.php');
}
Go into settings-config.php (or whatever you name the file). Around line 69, there is an $args array that ends up getting passed into Redux::setArgs( $opt_name, $args ); **In that array, there is a parameter keyed as 'admin_bar_priority' with a comment of /*Choose a priority for the admin bar menu*/.** 

Changing the value of this number makes no difference where the menu shows up in the menu list in the admin menu. It always just shows up at the bottom of the menu.  I would like it to show up higher where some other custom pages of my plugin reside. 

## Expected Behavior
The lower the number, the higher up on the admin menu the menu item should display. 

## Actual Behavior
Everything works fine. I have been changing the options layout, successfully saving data through the UI, literally everything else works. However...
The admin menu link doesn't move no matter what number you enter as a value in these args. 

## Any Error Details (PHP/JavaScript)
No errors are present in PHP or JS.

**Comment by adhamqodirov** [comment]
Hi robruiz!

In your config arguments, try:

'menu_type'         => 'menu'
'page_priority'     => 8
https://prnt.sc/ugecob   https://prnt.sc/ugecgv 

regards
