### ISSUE TITLE
Section option icon not show in customizer page

### ISSUE THREAD

**Issue by pjdemo** [reduxframework/redux-framework#3346]
Check below screenshot
Just active wordpress default theme, add redux plugin
check enable default option
Sample option page show Icons but not in customizer
http://screencast-o-matic.com/watch/cb1QQaXLyO

how this possible?
Don't provide me this link, in this nothing : https://docs.reduxframework.com/core/sections/getting-started-with-sections/

Thank you

**Comment by kprovance** [comment]
Closing this ticket since none of the requested information was provided.
