### ISSUE TITLE
How to add default image URL for media upload

### ISSUE THREAD

**Issue by hansolboy** [reduxframework/redux-framework#3348]
Hi, in the media upload section i need to set a default image for the background and if user upload a new one then it'll replace it.

I have 2 questions that i need help with:
1- How to set a path (**in OPTIONS PHP FILE**) for an image from the "Template Folder" Ex. 
`get_template_directory_uri(). '/romisa-assets/img/sample/img-404.png';`

2- How to create "if" condition in HTML if an option value is empty then to this. Ex:

`<?php if(roms_option('error-404-logo') == 1 ) { ?> <img src="<?php echo roms_option("error-404-logo")["url"]; ?>" alt=""> <?php } else{ ?> <img src="<?php echo get_template_directory_uri(). '/romisa-assets/img/sample/img-404.png'; ?>" alt=""> <?php } ?>`

Regards

**Comment by kprovance** [comment]
1. This answer is provisws in thew sample-config.php
```php
                'default'  => array( 
                    'url' => 'http://s.wordpress.org/style/images/codeispoetry.png',
                    )
                ),
```

2. We're unable to help with frontend or template HTML.  That is a premium service.  Howewver, if you view out documentation on the media field(https://docs.reduxframework.com/core/fields/media/) you will see it returns an array and not true/false, which you seem to be checking for.

**Comment by hansolboy** [comment]
What i understood from your answer that there is no way to create a `get_template_directory_uri()` or equivalent in the config file. 

For the second point i'll post the solution a reference if someone needed it.

`<?php if(roms_option('error-404-logo')['url'] == true ) { ?>`
/* Positive content */
`?php } else{ ?>`
/* default content */
`<?php } ?>`
