### ISSUE TITLE
External fonts not working

### ISSUE THREAD

**Issue by mlenders** [reduxframework/redux-framework#3351]
I'm trying to add an external font (called 'Simplifica') to my project. I'm following this tutorial: http://www.themesdojo.com/2016/06/how-to-add-custom-fonts-to-redux-framework/

It seems that font is loaded (i can see it in chrome console, in the css), but doesn't works, in the screen is loaded a 'default' font.

I'm using Hood Theme based on Redux Framework.

**Comment by kprovance** [comment]
We didn't write that article, which discusses modification of the Redux core.  We do not support any of that.  You'll need to contact the theme author for support on his article.  Sorry.  Good luck.

**Comment by mlenders** [comment]
Thank you for the answer @kprovance .

I know the articles isn't yours, but i need to search a solution for my problem, so i found this (but didn't works to me).

I contacted with the theme author and told me that now is not a solution :(

It's imposible to add an external font?

**Comment by kprovance** [comment]
Nothing's impossible.  However, since this isn't covered under the scope of our support, for me to do this would require premium support, and using a child theme since modifying the core of any theme is not wise.  Changed would be lost on theme update.

**Comment by mlenders** [comment]
Can u give me more information about this premium support? @kprovance

**Comment by kprovance** [comment]
It's $100.00 an hour.  You can email me at kevin@reduxframework.com if interested, to discuss the details in private, and so I am able to get a clearer idea of what you'd like done. :)

**Comment by mlenders** [comment]
Thanks for the info @kprovance . I will study all my options for solve my problem.

**Comment by kprovance** [comment]
Good luck to you then.
