### ISSUE TITLE
'undefined' returned when saving options

### ISSUE THREAD

**Issue by MrHunter** [reduxframework/redux-framework#3352]
## Support Hash
http://support.redux.io/?id=ySAp6ZtfpC%2F5PQliUM78lusMOn15RjxUTCUGWsK%2FbkAwddp6PyFTFYdJIhfJfEanTHI%2F264aGbOahkkpjeK6pQ%3D%3D

## Steps to reproduce
Saving the theme options 

## Expected Behavior
We expect the "Settings Saved!" message after clicking "Save Options".

## Actual Behavior
We get an "undefined" response:
![screen shot 2017-06-16 at 10 16 49 am](https://user-images.githubusercontent.com/5040696/27230419-21b2ba72-527d-11e7-813c-86f60e117944.png)

## Any Error Details (PHP/JavaScript)
When I enabled WP_DEBUG with error logging there was nothing being generated when we saved the options.

**Comment by kprovance** [comment]
Looks as if you are still using Redux 3.6.4.4.  We're up to stable release 3.6.5.  Please try that first.  Also, FYI, always make sure you have the latest version of Redux, as we will ask you to upgrade when older versions are reported.  Thanks!

**Comment by MrHunter** [comment]
Sorry Kevin! I should have realized it wasn't on the latest version. 

I went ahead and updated to 3.6.5, cleared caches, but still received the same "undefined" issue. I generated a new support hash to show the latest version: http://support.redux.io/?id=ySAp6ZtfpC%2F5PQliUM78lusMOn15RjxUTCUGWsK%2FbkAwddp6PyFTFYdJIhfJfEanTHI%2F264aGbOahkkpjeK6pQ%3D%3D

**Comment by kprovance** [comment]
Is there anything in the javascript console?

**Comment by kprovance** [comment]
Problem is, I can;t duplicate this on your options array alone.  I ran it few a few of those 201* theme WP offers.  It could be something in the theme?  Any special hooks used in some of those extensions we didn't author?  Were any core modifications done?

Also,that last support hash still shows the old Redux.

**Comment by MrHunter** [comment]
Apparently the user had their host revert PHP back to 5.5 from 7.0 and it began working for them. I find that strange though since our test servers are all on 7.0 and I couldn't replicate this bug for the life of me?

**Comment by kprovance** [comment]
I have no idea, except that last support hash still showed an old version of redux.  I think dovy fixed some 7.0 issues in the most recent.  Otherwise, this would be a major debug job on someone else's server, which isn't a free thing we do anymore.  Anyways, I'll mark this closed for now.  Cheers.

**Comment by MrHunter** [comment]
Yeah no worries just thought I would let you know about it just in case it rang any bells as to why that would work. 

As always, thanks for your help!
