### ISSUE TITLE
Customizer option reset after short time

### ISSUE THREAD

**Issue by Ryu-k** [reduxframework/redux-framework#3354]
http://support.redux.io/?id=psYziL2XCuXENA3bS0qnxmxRH1xYYJQ0JNjLALdxF%2FW%2F2JVbkWXsP0vQ1cMilDn6gqVHsWqWa4TsGN8LNjvKCw%3D%3D

When editing the theme options with the customizer, I see the change live, for example background color change, but after a short time if I change an other option, the options I changed before are back to the default value.

For example, I change the background color from white to black.
After a short time, I change the text color from dark to white, doing this the background color turn back to white.

Regards

**Comment by kprovance** [comment]
Please post all customizer issues on our customizer issue tracker.  Thanks.

**Comment by relstudiosnx** [comment]
@Ryu-k @kprovance i am also facing same issue, is there any solution for this ?

Thanks

**Comment by kprovance** [comment]
Please post all customize issues here:  https://github.com/reduxframework/customizer-integration/issues

It's be addressed...whenever it's addressed.
