### ISSUE TITLE
On reset i get ( Illegal string offset 'url'  )

### ISSUE THREAD

**Issue by hansolboy** [reduxframework/redux-framework#3355]
Hi, i use redux in a new theme i'm developing.
I'm using "**if**" condition to check if logo option [URL] doesn't exist then add a default image logo

`<?php if(roms_option('error-404-logo')['url'] == true ) { ?> <img src="<?php echo roms_option("error-404-logo")["url"]; ?>" alt=""> `
`<?php } else{ ?> <img src="<?php echo get_template_directory_uri(). '/romisa-assets/img/sample/img-404.png'; ?>" alt="">`
`<?php } ?>`

However i get this error when the theme is freshly installed or i click "Reset All" button.
" Warning: Illegal string offset 'url' "

![image](https://user-images.githubusercontent.com/15946998/27274914-2f54bc32-54e6-11e7-933d-01c713c39ec3.png)

Same effect for all options as well which doesn't apply by default unless i click save

Please advise

**Comment by hansolboy** [comment]
Why are you closing this without providing any help?

**Comment by kprovance** [comment]
You didn't read the text provided in the new issue window.  Ignored it I suspect.  It said provide us with all the required information or your ticket gets closed.

**Comment by kprovance** [comment]
AND, we do not help with front end issues without a premium support subscription, as previously indicated.

**Comment by hansolboy** [comment]
That's all. i finished a theme and tested in a fresh WP install and if i never click save no option will work.
It's up to you if you don't want to help and i understand.

Regards

**Comment by kprovance** [comment]
https://github.com/reduxframework/redux-framework/issues/new: READ IT!!
