### ISSUE TITLE
Default image_select not selected

### ISSUE THREAD

**Issue by hieudo1802** [reduxframework/redux-framework#3356]
I had 2 panels as below :

<pre>
// -> START TOPBAR
Redux::setSection( $opt_name, array(
    'title'            => __( 'Topbar' ),
    'icon'             => 'el el-bookmark',
    'fields'           => array(
        array(
            'id'       => 'opt_topbar_color',
            'type'     => 'color',
            'title'    => __('Topbar Text Color'), 
            'subtitle' => __('Choose Topbar text color'),
            'default'  => '#fff',
            'validate' => 'color',
            'transparent' => false
        ),
        array(
            'id'       => 'opt_topbar_bg_color',
            'type'     => 'color',
            'title'    => __('Topbar Background Color'), 
            'subtitle' => __('Choose Topbar background color'),
            'default'  => '#000',
            'validate' => 'color',
            'transparent' => false
        ),
    ),
) );
Redux::setSection( $opt_name, array(
    'title'            => __( 'Header' ),
    'icon'             => 'el el-arrow-up',
    'fields'           => array(
        array(
            'id'        => 'opt_home_header_style',
            'type'      => 'image_select',
            'presets'   => true,
            'title'     => __('Homepage Header Style'),
            'subtitle'  => __('Select your preferred header style'),
            'options'  => array(
                'header-1' => array(
                    'alt'       => 'Header 1', 
                    'img'       => get_template_directory_uri() . '/header-1.jpg', 
                    'presets'   => array(
                        'opt_topbar_home_color'     => '#333',
                        'opt_topbar_home_bg_color'  => '#f9f9f9',
                    )
                ),
                'header-2' => array(
                    'alt'       => 'Header 2', 
                    'img'       => get_template_directory_uri() . '/header-2.jpg', 
                    'presets'   => array(
                        'opt_topbar_home_color'      => '#fff',
                        'opt_topbar_home_bg_color'   => '#000',
                    )
                ),
                'header-3' => array(
                    'alt'       => 'Header 3', 
                    'img'       => get_template_directory_uri() . '/header-3.jpg', 
                    'presets'   => array(
                        'opt_topbar_home_color'      => '#eee',
                        'opt_topbar_home_bg_color'   => '#ccc',
                    )
                ),
            ),
            'default'  => 'header-1',
        ),
    ),
) );
</pre>

As you can see, the goal is to navigate to tab Header, select any from 3 images there and it will automatically change the color of Topbar. When I set default value in tab Header to "**header-1**", it works but change to "**header-2**" or "**header-3**" won't.

After take a look around, I ended up at this section
<pre>
// Only highlight the preset if it's the same
if ( $selected ) {
    if ( empty( $v['presets'] ) ) {
        $selected = false;
    } else {
        foreach ( $v['presets'] as $pk => $pv ) {
            if ( isset( $v['merge'] ) && $v['merge'] !== false ) {
                if( ( $v['merge'] === true || in_array( $pk, $v['merge'] ) ) && is_array( $this->parent->options[ $pk ] ) ) {
                    $pv = array_merge( $this->parent->options[ $pk ], $pv );
                }
            }

            if ( empty( $pv ) && isset( $this->parent->options[ $pk ] ) && ! empty( $this->parent->options[ $pk ] ) ) {
                $selected = false;
            } else if ( ! empty( $pv ) && ! isset( $this->parent->options[ $pk ] ) ) {
                $selected = false;
            } else if ( isset( $this->parent->options[ $pk ] ) && $this->parent->options[ $pk ] != $pv ) {
                $selected = false;
            }

            if ( ! $selected ) { // We're still not using the same preset. Let's unset that shall we?
                $this->value = "";
                break;
            }
        }
    }
}
</pre>
in file **redux-framework\ReduxCore\inc\fields\image_select\field_image_select.php** and comment out the line 
<pre>
} else if ( isset( $this->parent->options[ $pk ] ) && $this->parent->options[ $pk ] != $pv ) {
            $selected = false;
}
</pre>
fixed the problem, could you please have a look ?

Thanks,
Adam

**Comment by hieudo1802** [comment]
@kprovance :

Sorry, just updated my message with more info.

**Comment by kprovance** [comment]
I added this solution.  it was never supposed to be default behaviour, since the preset option was about available choices, and not what the last selected one was.  But, the masses have spoken!  ;-)
