### ISSUE TITLE
[folder not writable]

### ISSUE THREAD

**Issue by mariuszo73** [reduxframework/redux-framework#3357]
Redux Framework – System status shows error: “Redux Data Directory Writable”: To allow data saving, make…../wp-content/uploads/redux/ writable.

Changing folder permissions to 755, 775, 777 does not removing error
Deleting and creating new folder makes no difference too

**Comment by kprovance** [comment]
Know issue

**Comment by dovy** [comment]
@mariuszo73 the issue is the owner. Change the owner to the same owner that you web server runs. `chown -R USER:GROUP ../wp-content/uploads/`

**Comment by kprovance** [comment]
Right now, there is an issue with redux that causes everyone to see the false flag.  It's fixed in the version from this git.

**Comment by dovy** [comment]
Ahh. We need to push then.  ;)
