### ISSUE TITLE
Redux bug on iPhone

### ISSUE THREAD

**Issue by LB79** [reduxframework/redux-framework#3359]
## Steps to reproduce
Open the redux demo

## Expected Behaviour
Grey space should reduce in width when using portrait mode, allowing options to be used

## Actual Behaviour
Grey space in side panel is too wide which makes the options squash up and become unusable. 
This happens on Redux demo and also other themes using Redux.

**Comment by kprovance** [comment]
Confirmed.  I will fix this in the next release.

**Comment by kprovance** [comment]
Fixed in v.3.6.5.3
