### ISSUE TITLE
It's possible to add external fonts? I'm trying and I CAN'T

### ISSUE THREAD

**Issue by mlenders** [reduxframework/redux-framework#3361]
I tried to add an external font (NOT from google fonts). I did all correctly, and when I see the Chrome console the font appears loaded in the CSS, but in the screen only can see a default regular font. Not my font.

It's possible to add an external font to my project?

Thanks a lot.

Im using this in the css:
`@font-face {
  font-family: 'Simplifica';
  src: url('wp-content/themes/hood-theme/custom-fonts/simplifica.eot'); 
  src: url('wp-content/themes/hood-theme/custom-fonts/simplifica.eot?#iefix') format('embedded-opentype'), 
       url('wp-content/themes/hood-theme/custom-fonts/simplifica.woff2') format('woff2'), 
       url('wp-content/themes/hood-theme/custom-fonts/simplifica.woff') format('woff'),
       url('wp-content/themes/hood-theme/custom-fonts/simplifica.ttf')  format('truetype'), 

.font-simplifica{font-family: Simplifica;}
}
`

**Comment by kprovance** [comment]
It is possible, but since this is not a Redux issue, it becomes a premium support issue.
