### ISSUE TITLE
8Theme Internal Error 500

### ISSUE THREAD

**Issue by tannerhuynh** [reduxframework/redux-framework#3363]
I am having the same issue as a previously opened ticket on here. Just bought my 8theme and installed it today with all the required plugins. I have not edited anything at all and this is a fresh install. I reinstalled the redux framework and it did not do anything to fix the issue. Is it possible that 3.6.5.2 resurfaced this issue? Please tell me how this was fixed?

I downgraded to 3.6.2 and the problem still exists.... 

There is a line in the code that is also causing internal 500 errors for theme customization and deleting plugins. When I deactivate the theme, I am able to delete the plugins. I was also unable to enter in support ticket on www.8theme.com website because the fields were not working in my browser that is why I am here.

![screen shot 2017-06-30 at 2 04 47 pm](https://user-images.githubusercontent.com/13091354/27748444-809ee742-5d9d-11e7-84bf-fd5decf6b556.png)

**Comment by kprovance** [comment]
This is an issue for your theme author to handle, as we do not support theme usets.  This was stayed as such when you filled out the ticket anyway.  Good luck.
