### ISSUE TITLE
Montserrat font has only two weight 400 and 700

### ISSUE THREAD

**Issue by badr0333** [reduxframework/redux-framework#3364]
In typography field the font "Montserrat" has only two font weights instead of having 5 6 i guess excluding italic variations. This font should have all the other font weights as the framework fetch them form google. If you go to google fonts and look at Montserrat font you will find many other font weights like light, semi bold etc. I want to use this font in my project and it requires light and semi bold font weight which this framework don't have. Please fix this issue as this font is used widely in premium themes.

**Comment by kprovance** [comment]
Please update to the latest version.
