### ISSUE TITLE
How to uninstall it?

### ISSUE THREAD

**Issue by jinqifeng** [reduxframework/redux-framework#3366]

**Comment by jinqifeng** [comment]
i have install it on my test site which is hosting on 000webhostapp.
Now i am going to change this theme with my custom theme.
But in the admin panel I can not access install theme page.
how to do

**Comment by kprovance** [comment]
Uninstall what?  redux Framework?  Deactivate it in the plugins section, and delete it from there.  or go in your FTP and inside wp-content/plugins, deleted the redux-framework directory.

**Comment by jinqifeng** [comment]
kprovance, thank you for your reply.
I have done deactivate it and delete it. but when i am going to appearance menu , there appears such message and can not access theme menu. 
"Sorry, you are not allowed to access this page."  

this is  url :  https://sim-uh.000webhostapp.com/wp-admin/tools.php?page=redux-about

**Comment by kprovance** [comment]
Is this your project, or someone elses theme/plugin?

**Comment by jinqifeng** [comment]
this is my personal  site.

**Comment by jinqifeng** [comment]
now i am building first site

**Comment by kprovance** [comment]
I didnt ask about your site, I asked about the theme and or plugin that uses Redux?  Did you write those or did someone else?  It sounds like Redux may be embedded in a project, and if it's not yours, then you will need to contact the author of the theme or plugin that is still using Redux.

**Comment by jinqifeng** [comment]
I am going to build personal prtfolio.
I have search theme for long time and found best theme - xpersonlite.
and I install it , then this theme needs redux plugin, so i install that

**Comment by kprovance** [comment]
Okay, and as we have stated, we do not support theme users of themes that use Redux.  You need to contact the theme author for support.
