### ISSUE TITLE
Separate Options Import Option for each section

### ISSUE THREAD

**Issue by ninzio** [reduxframework/redux-framework#3367]
Hello, we are theme development company that work on Themeforest. We want to add import option for each section, so that a user can import/export options for each section separately. Is there any way to achieve this?

**Comment by kprovance** [comment]
At this time, there is not.  It has been suggested before.  If we do it, it would go in the premium version of redux still in development.  No etc on what a beta run will be ready.  We will announce via our blog.  Cheers.

**Comment by ninzio** [comment]
Ok, thanks a lot!
