### ISSUE TITLE
Options not saving.

### ISSUE THREAD

**Issue by MrHunter** [reduxframework/redux-framework#3370]
## Support Hash
http://support.redux.io/?id=tEsFNd7vuCPrEHCj12tPLTrbmkyz%2F%2BnF02v2Ccc2fhqpRQHNahtxa%2BY%2BzLMxttywPos6yEYRHiUjpZwTEnIT%2BQ%3D%3D

## Steps to reproduce
Change any option under Listing Options (at the moment we are trying to change Listing Options >> Single Listing Page >> Content Tabs >> Second Tab text back to "Features & Options") then save the options, it returns a success message however if you refresh the page it will revert back to the original value.

## Expected Behavior
The expected behaviour is that the option should update and remain after the options are saved.

## Actual Behavior
The changed options revert back after the page has been refreshed.

## Any Error Details (PHP/JavaScript)
No console errors but I did notice one thing happening while I was doing a little debugging. When I would go under Tools >> Redux Framework >> Status and the page wouldn't load. I tracked it down to the file ReduxCore/inc/class.redux_helpers.php in the compileSystemStatus method, when I changed "ReduxCore" to "ReduxFramework" on line 395 it began to show the page.

**Comment by kprovance** [comment]
Sorry to say, I loaded up your config, even changed the WP language to match, and could not reproduce this issue.  Have you tested it across more than one environment with the same issue?

**Comment by MrHunter** [comment]
Yeah we tested it across 3 separate hosting environments and received the same result. 

I did narrow it down to the plugin "WPML String Translation" causing this effect though, I am going to open a thread with WPML and let them know as well and try to get this conflict resolved.

**Comment by MrHunter** [comment]
So apparently the solution was to change, then re-set the default language of the site in WPML (Under WPML >> Languages >> Site Languages) and afterwards the options would save as they should.
