### ISSUE TITLE
Improper way of detemining URL

### ISSUE THREAD

**Issue by szepeviktor** [reduxframework/redux-framework#3374]
Hello!

As you must know `wp-content` location could be outside `ABSPATH`.
Please replace `WP_CONTENT_DIR` in `_extension_dir` 
or get `_extension_url` from WP core functions.
As in https://github.com/reduxframework/redux-framework/blob/c80f828385bd3891d0456b5d8a7e6a4c278f3211/ReduxCore/inc/class.redux_helpers.php#L716-L718

```php
                if ( empty( $this->_extension_dir ) ) {
                    $this->_extension_dir = trailingslashit( str_replace( '\\', '/', dirname( __FILE__ ) ) );
                    $this->_extension_url = site_url( str_replace( trailingslashit( str_replace( '\\', '/', ABSPATH ) ), '', $this->_extension_dir ) );
                }
```

from https://github.com/reduxframework/redux-framework/blob/797af02a75c6692a1cc15edafee508e66351ad8e/ReduxCore/inc/extensions/customizer/extension_customizer.php#L85

**Comment by kprovance** [comment]
We;re going to add filters for this in an upcoming version of Redux since there does not appear to be a 'one solution fits all' answer here.  This is because Redux can be used both as a plugin and embedded in a theme.

**Comment by szepeviktor** [comment]
Excuse me.
You have a helper function that works everywhere:
https://github.com/reduxframework/redux-framework/blob/c80f828385bd3891d0456b5d8a7e6a4c278f3211/ReduxCore/inc/class.redux_helpers.php#L716-L718

**Comment by kprovance** [comment]
ok

**Comment by szepeviktor** [comment]
@kpodemski Could you use your helper function instead of introducing a filter?

**Comment by kprovance** [comment]
When I have the time to sit down and test it with every single way Redux can be used and not break backward compatibility, then yes.  Can't do it right at the moment, sorry.

**Comment by szepeviktor** [comment]
The symptom is 404 in the Customizer.

And I think a slash is missing in front of the JS and CSS files.

**Comment by kprovance** [comment]
Okay, well, customizer issues go here:  https://github.com/reduxframework/customizer-integration/issues
