### ISSUE TITLE
Redux version 3.6.6 giving me error

### ISSUE THREAD

**Issue by kavasey** [reduxframework/redux-framework#3375]
Hi, I just updated redux from 3.5...to 3.6... and got the following (using the embedded way)

Parse error: syntax error, unexpected 'http' (T_STRING), expecting ',' or ';' in ...\inc\ReduxCore\framework.php on line 87

I had to change line below
public static $_version = '3.6.6;
to
public static $_version = '3.6.6';

kindly fix it.
Thanks

**Comment by kavasey** [comment]
Hi, I just updated redux from 3.5...to 3.6... and got the following

Parse error: syntax error, unexpected 'http' (T_STRING), expecting ',' or ';' in ...\inc\ReduxCore\framework.php on line 87

I had to change line below
public static $_version = '3.6.6;
to 
public static $_version = '3.6.6';

kindly fix it. 
Thanks

**Comment by kprovance** [comment]
fixed
