### ISSUE TITLE
Fatal Error - Allowed memory size exhausted

### ISSUE THREAD

**Issue by krskelton** [reduxframework/redux-framework#3378]
## Support Hash
http://support.redux.io/?id=SGhg10U%2BEhCvjJlD%2FdTCIfcJFFm%2BnRow7ueak9RytoSob%2F%2BwXZTS3twgd9rXuQC9GiahRnA4y%2BoriXcFolZSfw%3D%3D

## Steps to reproduce
Viewed a page on the site.

## Expected Behavior
Expected the page to come up. 

## Actual Behavior
This error shows up instead. Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 75 bytes) in /home/dramaticfanatic/public_html/wp-content/plugins/redux-framework/ReduxCore/inc/fields/typography/googlefonts.php on line 1 

## Any Error Details (PHP/JavaScript)
None that I see.

I took over a project from another developer so I'm not entirely sure how this plugin ended up on the site, whether it was from a theme or whether she just downloaded it. The site was working fine and now if I view any page or product, the error above comes up. Can you help me figure out what I should change to fix this error?

Thank you for your help! 

Kristin

**Comment by kprovance** [comment]
It's a WordPress memory issue.  It's something you will have to fix by adjusting memory settings.  See this article:  http://www.wpbeginner.com/wp-tutorials/fix-wordpress-memory-exhausted-error-increase-php-memory/

**Comment by krskelton** [comment]
Thank you so much!!! :D
