### ISSUE TITLE
Default value for select_image field is not working

### ISSUE THREAD

**Issue by ZoranJambor** [reduxframework/redux-framework#3379]
## Support Hash
http://support.redux.io/?id=rDWyQbLbn0lTEZM9v%2BFgw1M5udgry3eZ42LXwLgwjxzM8E2UUDSCcujPSs2Yj%2FOriMY2frkQSxgBzp9mNoz27w%3D%3D

## Steps to reproduce
I'm using the code provided in your docs (https://docs.reduxframework.com/core/fields/select-image/):

```
Redux::setSection($opt_name, Array(
    'title'     => __('Header', 'redux-framework-demo'),
    'id'        => 'header',
    'icon'      => 'el-icon-arrow-up',
    'fields'    => Array(
        Array(
            'id'       => 'opt-select-image',
            'type'     => 'select_image',
            'title'    => __('Select Image', 'redux-framework-demo'),
            'options'  => Array(
                Array (
                    'alt' => 'Basic',
                    'img' => get_template_directory_uri() . '/images/header-basic.png'
                ),
                Array (
                    'alt' => 'Advanced',
                    'img' => get_template_directory_uri() . '/images/header-advanced.png'
                )
            ),
            'default'  => 'Basic',
        )
    )
));
```

## Expected Behavior
Image `header-basic.png` should be selected by default.

## Actual Behavior
No image is selected by default: https://www.dropbox.com/s/vc9abzclb0xkl9k/Screenshot%202017-07-31%2014.44.30.png?dl=0

## Any Error Details (PHP/JavaScript)
There are no PHP or JavaScript errors.
The image path is correct.

**Comment by kprovance** [comment]
That page is slightly outdated.  I will update it as soon as I can.  This is what your array should look like:

```php
        Array(
            'id'       => 'opt-select-image',
            'type'     => 'select_image',
            'title'    => __('Select Image', 'redux-framework-demo'),
            'options'  => Array(
                'basic' => Array (
                    'alt' => 'Basic',
                    'img' => get_template_directory_uri() . '/images/header-basic.png'
                ),
                'advanced' => Array (
                    'alt' => 'Advanced',
                    'img' => get_template_directory_uri() . '/images/header-advanced.png'
                )
            ),
            'default'  => 'basic',
        )
```

**Comment by ZoranJambor** [comment]
Thank you for the reply. But this isn't working either.

```
Redux::setSection($opt_name, Array(
        'title'     => __('Header', 'redux-framework-demo'),
        'id'        => 'header',
        'icon'      => 'el-icon-arrow-up',
        'fields'    => Array(
            Array(
                'id'       => 'opt-select-image',
                'type'     => 'select_image',
                'title'    => __('Select Image', 'redux-framework-demo'),
                'options'  => Array(
                    'basic' => Array (
                        'alt' => 'Basic',
                        'img' => get_template_directory_uri() . '/images/header-basic.png'
                    ),
                    'advanced' => Array (
                        'alt' => 'Advanced',
                        'img' => get_template_directory_uri() . '/images/header-advanced.png'
                    )
                ),
                'default'  => 'basic',
            )
        )
    ));
```

Result is exactly the same. No image is selected by default.

Should I open a new ticket for this?

**Comment by kprovance** [comment]
Not necessary.  However, I am super busy at the moment.  I will try to get to it this week.  You are free to look at the field code too for a solution.  If you do, and find one, post it back, please.  Well credit you for it.

**Comment by ZoranJambor** [comment]
Will do, if I find the time for it. 

Thank you Kevin.

**Comment by kprovance** [comment]
Okay, I was confused.  this is for SELECT_IMAGE.  I had just woken up when I read this...I thoughthis was for IMAGE_SELECT.  So, whoops, technically yout initial field was correct.  The default is supposed to be the name of the file.  Even so, it still not working, and I gotta see why.  I'll post back the proper field after I get this updated.

**Comment by kprovance** [comment]
The select_image field stopped working on the 'alt' argument some time back, but apparently was never finished to use the 'url' argument.  It's not an oft used field, apparently.

Here is how you'll want to do it.

```php
Redux::setSection($opt_name, Array(
        'title'     => __('Header', 'redux-framework-demo'),
        'id'        => 'header',
        'icon'      => 'el-icon-arrow-up',
        'fields'    => Array(
            Array(
                'id'       => 'opt-select-image',
                'type'     => 'select_image',
                'title'    => __('Select Image', 'redux-framework-demo'),
                'options'  => Array(
                    'basic' => Array (
                        'alt' => 'Basic',
                        'img' => get_template_directory_uri() . '/images/header-basic.png'
                    ),
                    'advanced' => Array (
                        'alt' => 'Advanced',
                        'img' => get_template_directory_uri() . '/images/header-advanced.png'
                    )
                ),
                'default'  => get_template_directory_uri() . '/images/header-basic.png',
            )
        )
    ));
```
The 'default' arg must be a full url to the default image.  This is the only way for the default to work and be loaded into the options variabler without breaking backward compatibility, which we try to avoid.

If it's not too much trouble, please consider a donation to the Redux project.
https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=MMFMHWUPKHKPW

**Comment by ZoranJambor** [comment]
Thank you, Kevin. I've donated, I really appreciate your effort with the framework.

This is now working correctly when you _Reset Section_ in admin area, but when the theme is first time activated the field is still empty. 

I've tested this on version 3.6.6.1.
