### ISSUE TITLE
Notice: Undefined offset: 2 in version 3.6.5

### ISSUE THREAD

**Issue by devmybest** [reduxframework/redux-framework#3380]
Getting PHP error notice on version 3.6.5 after update

`Notice: Undefined offset: 2 in /Applications/MAMP/htdocs/bookshop/wp-content/plugins/redux-framework/ReduxCore/framework.php on line 3696
`
after switching on wp_debug. I know it will disappear by turning wp_debug off but themeforest reviewers won't :)

**Comment by devmybest** [comment]
May I know the reason for closing this issue?

**Comment by kprovance** [comment]
When you opened the new issue window, inside was a body of text we ask all those posting issues to read.  Clearly, you did not, or you would know why.  You are free to try again, but if the required information is not posted, it'll be closed again.  Good luck.

**Comment by devmybest** [comment]
Not all issues opened here have that format that you asked. I did read that format but not sure about support hash (I thought that may be generated for your premium extensions). So I reviewed other issues format and you've answered for the issues with out formats. Too rude.
