### ISSUE TITLE
Can't get this done: Update an Option Outside the Options Panel

### ISSUE THREAD

**Issue by ninzio** [reduxframework/redux-framework#3384]
Hello, i am a theme developer and i am using ReduxFramework as my theme option panel, and i need to be able to update an option outside the option panel. Tried to use this post, but no success: https://docs.reduxframework.com/core/advanced/update-an-option-outside-the-options-panel/

This is my code:

`<?php

if (!class_exists('Redux_Framework_config')) {
    class Redux_Framework_config {

        public $args        = array();
        public $sections    = array();
        public $theme;
        public $ReduxFramework;

        public function __construct() {

            if (!class_exists('ReduxFramework')) {
                return;
            }

            // This is needed. Bah WordPress bugs.  ;)
            if (  true == Redux_Helpers::isTheme(__FILE__) ) {
                $this->initSettings();
            } else {
                add_action('plugins_loaded', array($this, 'initSettings'), 10);
            }

        }

        public function initSettings() {

            $this->theme = wp_get_theme();
            $this->setArguments();
            $this->setSections();

            if (!isset($this->args['opt_name'])) { // No errors please
                return;
            }

            $this->ReduxFramework = new ReduxFramework($this->sections, $this->args);
        }

        public function setSections() {
            ob_start();

            $ct             = wp_get_theme();
            $this->theme    = $ct;
            $item_name      = $this->theme->get('Name');
            $tags           = $this->theme->Tags;
            $screenshot     = $this->theme->get_screenshot();
            $class          = $screenshot ? 'has-screenshot' : '';

            $customize_title = sprintf(esc_html__('Customize &#8220;%s&#8221;', 'ninzio-addons'), $this->theme->display('Name'));

            ?>
            <div id="current-theme" class="<?php echo esc_attr($class); ?>">
            <?php if ($screenshot) : ?>
                <?php if (current_user_can('edit_theme_options')) : ?>
                        <a href="<?php echo wp_customize_url(); ?>" class="load-customize hide-if-no-customize" title="<?php echo esc_attr($customize_title); ?>">
                            <img src="<?php echo esc_url($screenshot); ?>" alt="<?php esc_attr_e('Current theme preview', 'ninzio-addons'); ?>" />
                        </a>
                <?php endif; ?>
                    <img class="hide-if-customize" src="<?php echo esc_url($screenshot); ?>" alt="<?php esc_attr_e('Current theme preview', 'ninzio-addons'); ?>" />
                <?php endif; ?>

                <h4><?php echo $this->theme->display('Name'); ?></h4>

                <div>
                    <ul class="theme-info">
                        <li><?php printf( esc_html__('By %s','ninzio-addons'), $ct->display('Author') ); ?></li>
                        <li><?php printf( esc_html__('Version %s','ninzio-addons'), $ct->display('Version') ); ?></li>
                        <li><?php echo '<strong>'.esc_html__('Tags', 'ninzio-addons').':</strong> '; ?><?php printf( $ct->display('Tags') ); ?></li>
                    </ul>
                    <p class="theme-description"><?php echo $ct->display('Description'); ?></p>
                    <?php if ( $ct->parent() ) {
                        printf( ' <p class="howto">' . esc_html__( 'This <a href="%1$s">child theme</a> requires its parent theme, %2$s.', 'ninzio_addons' ) . '</p>',
                            esc_html__( 'http://codex.wordpress.org/Child_Themes', 'ninzio_addons' ),
                            $ct->parent()->display( 'Name' ) );
                    } ?>
                    
                </div>
            </div>

            <?php
            $item_info = ob_get_contents();

            ob_end_clean();

            /* General
            ---------------*/

                $this->sections[] = array(
                    'title'      => esc_html__('General', 'ninzio-addons'),
                    'icon_class' => 'icon-small',
                    'icon'       => 'el-icon-wrench',
                    'fields' => array(
                        array(
                            'id'        =>'layout',
                            'type'      => 'radio',
                            'title'     => esc_html__('Layout', 'ninzio-addons'), 
                            'subtitle'  => esc_html__('Boxed layout allows you to display the whole website in the box. (works on screens larger than 1200px wide). Make sure "Sidebar menu" option is inactive (from Theme Settings >> Header & menu >> Sidebar menu)', 'ninzio-addons'), 
                            'options'   => array(
                                'wide'  => esc_html__('Wide', 'ninzio-addons'), 
                                'boxed' => esc_html__('Boxed', 'ninzio-addons'),
                                'frame' => esc_html__('Frame', 'ninzio-addons')
                            ),
                            'default' => 'wide',
                        ),
                        array(
                            'id'       =>'frame-width-mob',
                            'type'     => 'slider',
                            'title'    => esc_html__('Frame width on mobile', 'ninzio-addons'),
                            'subtitle' => esc_html__('Starts on devices smaller than 1023px wide', 'ninzio-addons'),
                            'min'      =>'5', 
                            'max'      =>'50', 
                            'step'     =>'1',
                            'default'  => '20',
                            'required' => array('layout','equals','frame')
                        ),
                        array(
                            'id'       =>'frame-width',
                            'type'     => 'slider',
                            'title'    => esc_html__('Frame width', 'ninzio-addons'),
                            'min'      =>'5', 
                            'max'      =>'50', 
                            'step'     =>'1',
                            'default'  => '20',
                            'required' => array('layout','equals','frame')
                        ),
                        array(
                            'id'       =>'frame-color',
                            'type'     => 'color',
                            'title'    => esc_html__('Frame color', 'ninzio-addons'), 
                            'default'  => '#ffffff',
                            'required' => array('layout','equals','frame')
                        ),
                        array(
                            'id'   => 'info_normal',
                            'type' => 'info',
                            'desc' => esc_html__('Footer settings', 'ninzio-addons')
                        ),
                        array(
                            'id'   => 'warning-info',
                            'type' => 'info',
                            'style' => 'warning',
                            'desc' => esc_html__('Important! First you must', 'ninzio-addons').' <a href="'.esc_url(home_url('/')).'wp-admin/post-new.php?post_type=footer">'.esc_html__("create a footer", "ninzio-addons").'</a>'
                        ),
                        array(
                            'id'       =>'footer-sticky',
                            'type'     => 'switch',
                            'title'    => esc_html__('Sticky footer', 'ninzio-addons'),
                            "default"  => 0
                        ),
                        array(
                            'id'   => 'info_normal',
                            'type' => 'info',
                            'desc' => esc_html__('One page navigation settings', 'ninzio-addons')
                        ),
                        array(
                            'id'        =>'one-page-navigation',
                            'type'      => 'select',
                            'title'     => esc_html__('One page navigation', 'ninzio-addons'),
                            'subtitle'  => 'Use "Side Bullets" navigation to separate header menu and one page navigation (more about one page navigation find <a target="_blank" href="http://ninzio.com/knowledgebase/build-one-page-layout/">here</a>).', 
                            'options'   => array(
                                "top"   => "Header menu",
                                "side"  => "Side Bullets"
                            ),
                            'default' => "top"
                        ),
                        array(
                            'id'       =>'one-page-speed',
                            'type'     => 'slider',
                            'title'    => esc_html__('One page scroll speed in ms', 'ninzio-addons'),
                            'min'      =>'500', 
                            'max'      =>'1500', 
                            'step'     =>'100',
                            'default'  => '800'
                        ),
                        array(
                            'id'      =>'one-page-hash',
                            'type'    => 'switch', 
                            'title'   => esc_html__('One page layout hash', 'ninzio-addons'),
                            'subtitle'=> esc_html__("Toggle one page layout hash. In browsers that support the history object, update the url's hash when clicking on the links ", 'ninzio-addons'),
                            "default" => 0,
                        ),
                        array(
                            'id'       =>'one-page-filter',
                            'type'     => 'text',
                            'title'    => esc_html__('One page menu filter (if one page navigation is top menu)', 'ninzio-addons'),
                            'subtitle'=> esc_html__("Exclude links from one page menu by entering comma-separated menu items' ids", 'ninzio-addons'),
                        ),
                        array(
                            'id'   => 'info_normal',
                            'type' => 'info',
                            'desc' => esc_html__('Google API settings', 'ninzio-addons')
                        ),
                        array(
                            'id'       =>'google-map-api',
                            'type'     => 'text',
                            'title'    => esc_html__("Google map API Key", 'ninzio-addons'),
                            'subtitle' => 'More about google map api settings find <a target="_blank" href="http://ninzio.com/knowledgebase/google-map-options/">here</a>'
                        ),
                        array(
                            'id'   => 'info_normal',
                            'type' => 'info',
                            'desc' => esc_html__('Site background settings', 'ninzio-addons')
                        ),
                        array(
                            'id'   => 'warning-info',
                            'type' => 'info',
                            'style' => 'warning',
                            'desc' => esc_html__('Important! If you want to add background image/color select the "Boxed" site layout option from Theme Settings', 'ninzio-addons')
                        ),
                        array(
                            'id'       =>'site-background',
                            'type'     => 'background',
                            'title'    => esc_html__('Site background options', 'ninzio-addons'), 
                        ),
                        array(
                            'id'   => 'info_normal',
                            'type' => 'info',
                            'desc' => esc_html__('Under construction page settins', 'ninzio-addons')
                        ),
                        array(
                            'id'       =>'under-construction',
                            'type'     => 'switch',
                            'title'    => esc_html__('Under construction', 'ninzio-addons'),
                            'subtitle' => esc_html__('Toggle this option if you want to have "Under construction" page', 'ninzio-addons'),
                            "default"  => 0
                        ),
                        array(
                            'id'       =>'under-construction-back',
                            'type'     => 'background',
                            'title'    => esc_html__('Under construction page background', 'ninzio-addons'),
                            'required' => array('under-construction','equals',1) 
                        ),
                        array(
                            'id'       =>'under-construction-color',
                            'type'     => 'color',
                            'title'    => esc_html__('Under construction page text color', 'ninzio-addons'),
                            'default'  => '#777777',
                            'required' => array('under-construction','equals',1)
                        ),
                        array(
                            'id'       =>'under-construction-logo',
                            'type'     => 'media', 
                            'url'      => false,
                            'title'    => esc_html__('Under construction page logo upload', 'ninzio-addons'),
                            'required' => array('under-construction','equals',1)
                        ),
                        array(
                            'id'       =>'under-construction-logo-retina',
                            'type'     => 'media', 
                            'url'      => false,
                            'title'    => esc_html__('Under construction page retina logo upload', 'ninzio-addons'),
                            'required' => array('under-construction','equals',1)
                        ),
                        array(
                            'id'       =>'under-construction-slogan',
                            'type'     => 'textarea',
                            'title'    => esc_html__('Under construction page message', 'ninzio-addons'), 
                            'subtitle' => esc_html__('Add simple/html text to "Under construction" page', 'ninzio-addons'), 
                            'default'  => 'Site is under construction',
                            'required' => array('under-construction','equals',1)
                        ),
                    )
                );

            $theme_info  = '<div class="redux-framework-section-desc">';
            $theme_info .= '<p class="redux-framework-theme-data description theme-uri">' . esc_html__('<strong>Theme URL:</strong> ', 'ninzio-addons') . '<a href="' . $this->theme->get('ThemeURI') . '" target="_blank">' . $this->theme->get('ThemeURI') . '</a></p>';
            $theme_info .= '<p class="redux-framework-theme-data description theme-author">' . esc_html__('<strong>Author:</strong> ', 'ninzio-addons') . $this->theme->get('Author') . '</p>';
            $theme_info .= '<p class="redux-framework-theme-data description theme-version">' . esc_html__('<strong>Version:</strong> ', 'ninzio-addons') . $this->theme->get('Version') . '</p>';
            $theme_info .= '<p class="redux-framework-theme-data description theme-description">' . $this->theme->get('Description') . '</p>';
            $tabs = $this->theme->get('Tags');
            if (!empty($tabs)) {
                $theme_info .= '<p class="redux-framework-theme-data description theme-tags">' . esc_html__('<strong>Tags:</strong> ', 'ninzio-addons') . implode(', ', $tabs) . '</p>';
            }
            $theme_info .= '</div>';
            
        }

        public function setArguments() {

            $theme = wp_get_theme();

            $this->args = array(
                'opt_name'          => 'infinitum_ninzio',
                'display_name'      => $theme->get('Name'),
                'display_version'   => $theme->get('Version'),
                'menu_type'         => 'submenu',
                'allow_sub_menu'    => true,
                'menu_title'        => esc_html__('- Theme Settings', 'ninzio-addons'),
                'page_title'        => esc_html__('Theme Settings', 'ninzio-addons'),
                'google_api_key'    => '',
                'async_typography'  => true,
                'admin_bar'         => true,
                'global_variable'   => 'infinitum_ninzio',
                'dev_mode'          => false,
                'disable_tracking'  => true,
                'update_notice'     => false,
                'customizer'        => false,
                'page_priority'     => null,
                'page_parent'       => 'themes.php',
                'page_permissions'  => 'manage_options',
                'page_slug'         => 'ninzio',
                'save_defaults'     => true,
                'default_show'      => false,
                'default_mark'      => '',
                'system_info'       => false,
            );
        }
        
    }

    global $ReduxFrameworkConfig;
    $ReduxFrameworkConfig = new Redux_Framework_config(); 
}`

End the $ReduxFrameworkConfig returns only this:

`Redux_Framework_config Object ( [args] => Array ( ) [sections] => Array ( ) [theme] => [ReduxFramework] => )`

Can you help me to find out what is wrong with my code

**Comment by kprovance** [comment]
Look up the redux api on the same docs site and use that.  All that is legacy code we no longer support.
