### ISSUE TITLE
Tolerance for .svn folders

### ISSUE THREAD

**Issue by forummedia** [reduxframework/redux-framework#3385]
## Steps to reproduce
Call  Redux::setExtensions with .svn folders inside extension directory structure

## Expected Behavior
No error

## Actual Behavior
Error: File(.. /wp-content/plugins/uneebox_core/redux-extensions/extensions/.svn/all-wcprops/extension_all-wcprops.php) is not within the allowed path(s): ...

## Any Error Details (PHP/JavaScript)
Solution: Don't try to load extensions inside hidden folders (beginning with a dot).
Change class.redux_api.php line 540 from
if ( $folder === '.' or $folder === '..' ) {
to
if ( $folder === '.' or $folder === '..'  or strpos($folder, '.') === (int) 0 ) {

Edit, more simple:
if ( strpos($folder, '.') === (int) 0 ) 
if ( $folder[0] == '.' )
does all what is needed...

Thank you!

**Comment by kprovance** [comment]
Why would you want to put extensions in a .svn folder anyway?

**Comment by forummedia** [comment]
Hello Kevin,

we host all our web sites (around 200) in SVN based repositories.
So we see when files are changed - maybe by hacking attempts - and can do quick rollbacks if updates fail.
Normally folders starting with a dot are hidden system files and should not be accessed by PHP.

With best regards , Norbert

Von: Kevin Provance [mailto:notifications@github.com]
Gesendet: Freitag, 18. August 2017 08:27
An: reduxframework/redux-framework <redux-framework@noreply.github.com>
Cc: DE-FMG-DIS-Webadmin <webadmin@forum-media.com>; Author <author@noreply.github.com>
Betreff: Re: [reduxframework/redux-framework] Tolerance for .svn folders (#3385)


Why would you want to put extensions in a .svn folder anyway?

**Comment by dovy** [comment]
Resolved. Thank you!
