### ISSUE TITLE
error on generating from https://build.reduxframework.com

### ISSUE THREAD

**Issue by gulonline** [reduxframework/redux-framework#3386]
i am not able to generating theme with admin panel from https://build.reduxframework.com.
what to do ?

**Comment by kprovance** [comment]
We're going to need you to be a LOT more specific, please.

**Comment by gulonline** [comment]
ok when i m going to build them i am getting 1 bytes zip file to downlaod. 
if you i dont know what is the problem. i tried Firefox and   chrome browser but getting same problem. also i tried 2 different ISP broadband connection but getting same 1 bytes zip file downlaod. if you want i can provide my login user id and password to you for better error understand.

thanks

**Comment by xron89** [comment]
I get the same issue, trying to compile & download the admin folder from the Redux builder and get "Failed network error"

**Comment by gulonline** [comment]
any solution please ?

**Comment by kprovance** [comment]
@Dovy has to fix it since I do not have server access.  Potentially, this could take weeks.  You may just want to download the plugin from this git repo.

**Comment by kprovance** [comment]
#3387
