### ISSUE TITLE
Create transient for WP Queries (slow admin panel)

### ISSUE THREAD

**Issue by db-dzine** [reduxframework/redux-framework#3390]
## Support Hash
"Support hash could not be generated. Please try again later." Server issue?
## Steps to reproduce
Create many taxonomies like WooCommerce Product categories. Then set the following options:

```
            array(
                'id'     =>'excludeProductCategories',
                'type' => 'select',
                'data' => 'categories',
                'args' => array('taxonomy' => array('product_cat')),
                'multi' => true,
                'title' => __('Exclude Product Categories', 'woocommerce-pdf-catalog'), 
                'subtitle' => __('Which product categories should be excluded in the PDF catalog.', 'woocommerce-pdf-catalog'),
            ),
```

## Expected Behavior
Redux sets a transient for taxonomy queries. 

## Actual Behavior
Redux does not set a transient for any queries (see framework.php lines 923 > 1095).

## Any Error Details (PHP/JavaScript)
Redux Framework slows down site. 

Is there any way we can set a transient for all WP_Queries to reduce load time?

**Comment by kprovance** [comment]
I don't believe Redux has ever done what you are asking.  That section of code has remain unchanged for years.

**Comment by db-dzine** [comment]
@kprovance I have created a request to change this: https://github.com/reduxframework/redux-framework/pull/3391

**Comment by kprovance** [comment]
We'll have to carefully vet it first under several conditions, some of which you may not be aware of.  This may take several weeks as Redux is not a full time job for neither Dovy or I.  Please be patient.

**Comment by db-dzine** [comment]
@kprovance No problem :) We really like your framework!

**Comment by kprovance** [comment]
Pull submit received.  Will go into next major version of Redux.

**Comment by db-dzine** [comment]
Great thanks!
