### ISSUE TITLE
Sorter option field not display in theme customize

### ISSUE THREAD

**Issue by savanipriyank** [reduxframework/redux-framework#3394]
Hi,

We have checked your [redux demo ](https://demo.redux.io/) options after that go to demo customizer and check **Sorter**  option, it's work fine. http://prntscr.com/gec9kn.

After that, We create one demo site activate [Twenty Seventeen](https://wordpress.org/themes/twentyseventeen/) theme and install [Redux framework](https://wordpress.org/plugins/redux-framework/) and Activate Demo Mode after that go to demo customizer and check **Sorter**  option, it's not displayed in the customizer and many options fields not display in the customizer. http://prntscr.com/gecc4c

What causes this problem?

Thank you

**Comment by kprovance** [comment]
Please post your customize issue in the appropriate issue tracker:  https://github.com/reduxframework/customizer-integration/issues
