### ISSUE TITLE
Poppins font variants missing after plugin install

### ISSUE THREAD

**Issue by AleksandarPredic** [reduxframework/redux-framework#3395]
## Please update googlefonts.php

When you install plugin, you get 6 months old google fonts for typography field. Poppins have only few variants available, but after the file is updated (after one week), all new variants are available. 

The problem is that you need to wait a week to get new fonts after plugin install.  At the moment the file is updated 6 months ago.

Please update file redux-framework/ReduxCore/inc/fields/typography/googlefonts.php

**Comment by kprovance** [comment]
Google fonts is updated with each release.  In the very near future, the plugin will become self updating.  I'm sorry we don;t update as often as you like.  We do the best we can with what we have.
