### ISSUE TITLE
How to removing Import/Export from redux framework ???

### ISSUE THREAD

**Issue by abhikm1991** [reduxframework/redux-framework#3397]

**Comment by abhikm1991** [comment]
Solution..?

**Comment by abhikm1991** [comment]
![capture](https://user-images.githubusercontent.com/31885327/30321705-963f6f92-97d4-11e7-8339-5ff9975d52c4.JPG)

**Comment by kprovance** [comment]
Incomplete information.  Sorry.

**Comment by abhikm1991** [comment]
how to remove Import/export option ?

**Comment by abhikm1991** [comment]
???

**Comment by abhikm1991** [comment]
![capture](https://user-images.githubusercontent.com/31885327/30322505-52e6974a-97d7-11e7-97e5-895be6e99664.JPG)

**Comment by kprovance** [comment]
Read the docs site.  Arguments section.

**Comment by abhikm1991** [comment]
I am not got.. please help me..

**Comment by abhikm1991** [comment]
Just removing import/export..

**Comment by abhikm1991** [comment]
please yar.....

**Comment by kprovance** [comment]
https://docs.reduxframework.com/core/arguments/#show_import_export I am not writing your code for you, you have to try on your own...or pay for premium support.  I do expect a donation to Redux after this.  Thanks.  Locking thread.
