### ISSUE TITLE
Full list of custom post types not appearing when using 'data' => 'post_types'

### ISSUE THREAD

**Issue by brianmcculloh** [reduxframework/redux-framework#3398]
Redux is not displaying my full list of registered CPTs. If I run the following code in my theme:

`print_r(get_post_types());`

Here is the output:

`Array ( [post] => post [page] => page [attachment] => attachment [revision] => revision [nav_menu_item] => nav_menu_item [custom_css] => custom_css [customize_changeset] => customize_changeset [forum] => forum [topic] => topic [reply] => reply [acf-field-group] => acf-field-group [acf-field] => acf-field [custom_type] => custom_type )`

You can see 12 post types displaying, notably the bbpress CPTs "forum" and "topic". However, when I attempt to list all post types in the Redux options panel like so:

```
array(
    'id'       => 'progress-cpts',
    'type'     => 'button_set',
    'multi'    => true,
    'title'    => __( 'Custom Post Types', 'wtr' ),
    'data'     => 'post_types'
),

```
I only see four CPTs displayed ("Media", "Custom Types", "Pages", and "Posts). I have tried passing lots of various combinations of args into this as well, but nothing I do returns more than these four CPTs. I've even tried specifying by name, but nothing. I'm assuming the CPTs just aren't registered yet when Redux loads, and if that's the case, how do I rectify this? bbpress is obviously a widely-used plugin and I'd be surprised if it wasn't compatible with Redux's post_types data attribute...

Thanks!

**Comment by kprovance** [comment]
Requested info not provided.  Please post back the requested info.

**Comment by brianmcculloh** [comment]
Here is my support hash: http://support.redux.io/?id=UN060Lm3IVxF1VNaS5uzcYAgYY8G%2BvkwXVFgsUtbK4I2iBhQhKYllF26%2FIShT5aVcbiep%2B3psixLc0WKp7YbQg%3D%3D

I am a developer running the latest version of Redux (3.6.8) and still having the exact issue noted above. CPTs are not displaying in the Redux panel. Thank you.

**Comment by kprovance** [comment]
CPT registered by bbPress set the `exclude_from_search` arge to true.  So, add `'exclude_from_search' => true` to your args.

**Comment by brianmcculloh** [comment]
Thanks, that did it!
