### ISSUE TITLE
if text field has value then show value condition redux framework

### ISSUE THREAD

**Issue by soou2** [reduxframework/redux-framework#3399]
Hello,

Actually i need a conditional loop for text field. i want to >> if my text field has value then show value or if text field empty then no output show in theme.

i use this loop, its worked with buttons but its not working for text field.

` <?php if($cpv['cpv-logo-footer-3'] == 1) : ?>`
`           <li><a href="<?php echo $cpv['cpv-logo-footer-3'];?>"><i class="fa fa-facebook-square social-icon facebook-color"></i></a></li>`
` <?php  endif?>`

how can i do that?

**Comment by kprovance** [comment]
This issue tracker is for bug and issues with Redux itself.  We do not teach or help with PHP issues as we do not have the time. (What you have is not even a loop, it's an if/else statement.  Big difference)  I'd also be using true/false not 0/1

You might try posting this to something like https://wordpress.stackexchange.com/
