### ISSUE TITLE
Full list of custom post types not appearing when using 'data' => 'post_types'

### ISSUE THREAD

**Issue by brianmcculloh** [reduxframework/redux-framework#3401]
## Support Hash

http://support.redux.io/?id=0ZC5vBo8q9GGzQjB95%2BeQD0ijDI20Geja5Gm5MCs3uaTKnVD%2FrmNmcpxIhV3m9WWOhB5w7wig4F1n3BA86zZig%3D%3D

## Steps to reproduce

Go to the Redux options panel being used by the Worth The Read plugin: Worth The Read >> Reading Progress >> Functionality

## Expected Behavior

Locate the Custom Post Types option which should be the second one listed. This option should be populated by custom post types. Notably, since bbPress is active, there should be "Forums" and "Topics" listed as custom post types here.

## Actual Behavior

No custom post types are being listed. This option field is using the post_types data type to find all non built-in post types.

## Any Error Details (PHP/JavaScript)

There are no errors present, either PHP or in the console.

**Comment by kprovance** [comment]
Try adding the arg `'exclude_from_search' => true`
