### ISSUE TITLE
Website homepage redirectes to website/wp-admin/tools.php?page=redux-about

### ISSUE THREAD

**Issue by gurpreets4422** [reduxframework/redux-framework#3403]
-->

## Support Hash
http://support.redux.io/?id=7KwIqX6dKnuPsG%2FTQTPJfyP%2FORQCFp04z2IBer7gYU0qFJmLxzukB5WOrDE1xAsH0X28H116ERJbDbwOIjzb6g%3D%3D

## Steps to reproduce

No Idea

## Expected Behavior

Homepage should come @ website url

## Actual Behavior

homepage redirects to  website/wp-admin/tools.php?page=redux-about

## Any Error Details (PHP/JavaScript)

No

**Comment by kprovance** [comment]
That's what happens on first run of Redux.  When you go to a different section, it goes away.

**Comment by gurpreets4422** [comment]
Its not the first run.

**Comment by kprovance** [comment]
Then please provide me with some temporary back-end access where I can see the behavior first hand, for myself.  kevin@reduxframework.com

**Comment by kprovance** [comment]
admin access.

**Comment by gurpreets4422** [comment]
check for it.
