### ISSUE TITLE
Error: There was a problem with your action. Please try again or reload the page

### ISSUE THREAD

**Issue by Dannci** [reduxframework/redux-framework#3405]
Hello there:
one of my customers is getting following error when user is saving admin panel options:  'There was a problem with your action. Please try again or reload the page.' 
Here is the support url:
http://support.redux.io/?id=s%2FpOD%2FKv2Oz5QEhuh%2BGXbvV%2BkarGPL%2Fi6aj06zWQOfnABIWGMa6tJxriXb4ZoAl1gChag9cYTuc1sK5xHy9hhw%3D%3D

- Redux is used as a plugin, there are no changes to the plugin. 
- Other plugins are disabled
- console shows error in redux.min.js file 

Thank you

**Comment by kprovance** [comment]
For now, you need to turn dev_mode, so the js file is NOT minimized.  We need to know what the output is in the console.

**Comment by Dannci** [comment]
Hello and thank you, 
console shows '500 internal server error' now.

**Comment by kprovance** [comment]
Well, then you have a server issue, son.  We don;t service those, not without premium support.  PS - Upgrade to something other than PHP 5.2.  Contact your server admin about doing so, or upgrad eto Redux from this repo.  One or the other.

**Comment by Dannci** [comment]
Hello again,

my customer with the hosting support found this fix:

.../wp-content/plugins/redux-framework/ReduxCore/framework.php

go to line 4069
there you find such option
_$args = array_merge( array( $current_user ), func_get_args() );_

change it to

_$name_arr=func_get_args();
$args = array_merge( array( $current_user ),$name_arr );_

support says:
`The array_merge function requires input two arrays, as previously stated, but the second parameter was a function that returned an array and caused the error."`

Any thoughts? How to add this fix safely (due future plugin update)?

**Comment by kprovance** [comment]
He needs to upgrade to something higher than php 5.2, or you need to upgrade to the version of redux from this repo, where that issue has been resolved, as indicated in the changelog.
