### ISSUE TITLE
Improper use of jQuery.hasClass method

### ISSUE THREAD

**Issue by kostasx** [reduxframework/redux-framework#3406]
Improper parameters passed to the jQuery.hasClass method on lines:

https://github.com/reduxframework/redux-framework/blob/master/ReduxCore/assets/js/redux.js#L860
https://github.com/reduxframework/redux-framework/blob/master/ReduxCore/assets/js/redux.js#L863
https://github.com/reduxframework/redux-framework/blob/master/ReduxCore/assets/js/redux.js#L976

The `.hasClass( '.hide' )` should be `.hasClass( 'hide' )`.

The . dot must be removed according to the docs: [https://api.jquery.com/hasclass/](https://api.jquery.com/hasclass/)

**Comment by kprovance** [comment]
Fixed in v3.6.7
