### ISSUE TITLE
 Warning: Illegal string offset 'width'

### ISSUE THREAD

**Issue by NorthwoodsCreative** [reduxframework/redux-framework#3409]
## Any Error Details (PHP/JavaScript)
Warning: Illegal string offset 'height' in /public_html/wp-content/plugins/redux-framework/ReduxCore/inc/fields/dimensions/field_dimensions.php on line 274

Warning: Illegal string offset 'height' in /public_html/wp-content/plugins/redux-framework/ReduxCore/inc/fields/dimensions/field_dimensions.php on line 274

Warning: Illegal string offset 'width' in /public_html/wp-content/plugins/redux-framework/ReduxCore/inc/fields/dimensions/field_dimensions.php on line 275

Warning: Illegal string offset 'width' in /public_html/wp-content/plugins/redux-framework/ReduxCore/inc/fields/dimensions/field_dimensions.php on line 275

Warning: Illegal string offset 'height' in /public_html/wp-content/plugins/redux-framework/ReduxCore/inc/fields/dimensions/field_dimensions.php on line 274

Warning: Illegal string offset 'height' in /public_html/wp-content/plugins/redux-framework/ReduxCore/inc/fields/dimensions/field_dimensions.php on line 274

Warning: Illegal string offset 'width' in /public_html/wp-content/plugins/redux-framework/ReduxCore/inc/fields/dimensions/field_dimensions.php on line 275

Warning: Illegal string offset 'width' in /public_html/wp-content/plugins/redux-framework/ReduxCore/inc/fields/dimensions/field_dimensions.php on line 275

**Comment by kprovance** [comment]
Please upgrade to v.3.6.7.1 from this repo.  Also, in the future, it would be very, very helpful to use if you would supply the required information instead of slipping over it.  Thanks.

**Comment by NorthwoodsCreative** [comment]
OK, Sorry about that.

Just wanted to let ya know the error still there just new line.

```
Warning: Illegal string offset 'width' in /public_html/wp-content/plugins/redux-framework-master/ReduxCore/inc/fields/dimensions/field_dimensions.php on line 269

Warning: Illegal string offset 'width' in /public_html/wp-content/plugins/redux-framework-master/ReduxCore/inc/fields/dimensions/field_dimensions.php on line 268
```

**Comment by kprovance** [comment]
Can't help you based on no information.  Open a new issue window, READ IT, and supply the required information.  If that's not possible, then you can purchase premium support and we can spend that hour playing Q and A.  Your choice.

**Comment by NorthwoodsCreative** [comment]
Hey it's your product not mine and the only reason I came here was because the Wordpress respo said we needed to.

I'm not the only one with the same issue, but hey keep being a dick and give your product a bad name. Your choice.
