### ISSUE TITLE
Problem with update 'Warning: Illegal string'

### ISSUE THREAD

**Issue by pjkwanten** [reduxframework/redux-framework#3410]
I updated the 'redux framework'-plugin this morning, and now I get this warning on my webpage:

Warning: Illegal string offset 'height' in /home/smiks/public_html/wp-content/plugins/redux-framework/ReduxCore/inc/fields/dimensions/field_dimensions.php on line 274

Warning: Illegal string offset 'width' in /home/smiks/public_html/wp-content/plugins/redux-framework/ReduxCore/inc/fields/dimensions/field_dimensions.php on line 275

(...)

How can I solve this?

**Comment by danfisher85** [comment]
@pjkwanten just declare 'mode' parameter for your 'dimensions' field, e.g.

```
'mode' => array(
  'width'  => true,
  'height' => false,
),
```

**Comment by pjkwanten** [comment]
Thanks for the quick response.
But it did not solve the problem for me. Is there another solution?

**Comment by kprovance** [comment]
Please upgrade to v.3.6.7.1 from this repo.  Also, in the future, it would be very, very helpful to use if you would supply the required information instead of slipping over it.  Thanks.

**Comment by Myth123** [comment]
i don't have an option to update to 3.6.7.1 i have online 3.6.7...
