### ISSUE TITLE
Poppins font variants missing (again) after googlefonts.php file update

### ISSUE THREAD

**Issue by AleksandarPredic** [reduxframework/redux-framework#3411]
i already opened issue about this: https://github.com/reduxframework/redux-framework/issues/3395

Now, the new Redux plugin version have the same problem with Poppins google font. File is updated, but not properly. Please update file with all font variants, or add filter hook. I can send Pull request for filter hook if it's a problem for you to update googlefonts.php with all Poppins variants.

I'm working on the site where I need this from the start. And I love Redux but this is a very small issue and it's easy to fix :)

Thank you

**Comment by kprovance** [comment]
This will ultimately be fixed in version 4.x of Redux. Watch for the announcement on our blog.  Until then , there isn't much we can do.  I updated the google fonts for the last update.  If it isn't enough, then you can wait till v4.0.  Sorry.

**Comment by AleksandarPredic** [comment]
Why not implement filter hook to add missing font variants when someone need them? Should I send pull request for this? Will you consider it?

**Comment by kprovance** [comment]
No, because we are working on v4.0, which will put an end to these complaints.  Complaints for free software in which no one donates.  Remember that.

**Comment by kprovance** [comment]
Interesting portfolio:  https://themeforest.net/user/shindiristudio  How much time and effort did Redux save you?  How much did you donate back?  How much have you made?  Just sayin'.  How are you justifying about a font variant with a straight face?
