### ISSUE TITLE
Field "Dimensions" Illegal string offset for width and height

### ISSUE THREAD

**Issue by vladanost** [reduxframework/redux-framework#3413]
Your previous code allowed that "mode" can be used as "max-width" for example which was very handy when using Dimensions field. After latest plugin update Illegal string offset warning is present.

## Support Hash
http://support.redux.io/?id=jbqmgy6k7X4ytUwFcPhBr0QpvM1zcP2252mdR9ZV18XBM%2Fbjo9CHff%2F5JU5p%2FofGHgYJRE3uLajmYgdWzsRs8g%3D%3D
## Steps to reproduce
Create a dimesions field by setting mode to max-width
and height to false
## Expected Behavior
End css uses max-width

## Actual Behavior
Illegal string offset warning plugins/redux-framework/ReduxCore/inc/fields/dimensions/field_dimensions.php on line 268 and 269

## Any Error Details (PHP/JavaScript)
No

**Comment by vladanost** [comment]
This is the change that causes the issue https://github.com/reduxframework/redux-framework/commit/124c7a1e0f9fb149c204b31dccab5f2b9c83f5c6

**Comment by kprovance** [comment]
Well, that was actually a bug fix.  If you read the doc page (https://docs.reduxframework.com/core/fields/dimensions/) the mode is supposed to only accept an array containing height and width.  You're using it in a way in which it was never intended, that is a mode with a single not array value.  That broke when I fixed the original issue.   Unfortunately, adding 'max-width' or 'max-height' to the array won't work either.  So, basically I have to restore broken code to maintain backward compatibility, and fix it without removing it.  Should be fun.  I'll post back when I have something

**Comment by vladanost** [comment]
Thanks.

**Comment by kprovance** [comment]
Try version 3.6.7.2 from this repo.  If it works out, we'll commit to wp.org

**Comment by vladanost** [comment]
Great!
This is working.

**Comment by kprovance** [comment]
Okay, closing.
