### ISSUE TITLE
Fatal error: Uncaught Error: Class 'ReduxCore' not found

### ISSUE THREAD

**Issue by neko** [reduxframework/redux-framework#3414]
## Support Hash
http://support.redux.io/?id=kJWMUn7yFLRN42t5d9SGUljeQ8JHqncay0m%2Bfcfcc9zVeQevcazC1j%2B8CiYI3hohc061Tw2JyiRltkkRpOohMw%3D%3D

## Steps to reproduce

1. Install the plugin.
2. Activate the demo.
3. Navigate to the demo settings page.

## Expected Behavior
For it to work without breaking.

## Actual Behavior
Fatal error, causing half the page to load, or in some cases not at all.

## Any Error Details (PHP/JavaScript)
`Fatal error: Uncaught Error: Class 'ReduxCore' not found in /wp-content/plugins/redux-framework/ReduxCore/inc/class.redux_filesystem.php on line 123`

## More info
I have tested this with PHP 5.6 & PHP 7, on both linux & windows environments. With both the WordPress repo version of this, and the master branch of this repo.

**Comment by dovy** [comment]
My bad! We've identified the issue, pushed to this repo, and we'll be deploying to WP.org very shortly.

**Comment by dovy** [comment]
Issue resolved. Please update to 3.6.7.6.
