### ISSUE TITLE
Fatal error: mkdir() 

### ISSUE THREAD

**Issue by kiarashi** [reduxframework/redux-framework#3415]
Inside the latest version, a customer of ours received the following error when Redux was enabled:

Fatal error: Call to a member function mkdir() plugins/redux-framework/ReduxCore/inc/class.redux_filesystem.php on line 176

**Comment by seriusokhatsky** [comment]
Hi,

The same issue here.

**Comment by Marius25** [comment]
Yes, I am also having exact same problem

**Comment by otavioalban** [comment]
Same problem here.

**Comment by wayheming** [comment]
Same problem

**Comment by contempoinc** [comment]
All my new buyers are having the same issue, guessing its something simple? Looks like you guys made a commit 3 minutes ago to the ReduxCore folder, any idea when this will be pushed to the WordPress.org repo?

**Comment by mybeautycravings** [comment]
Hi there, i just upgraded the redux and it broke my site at www.mybeautycravings.com. Please kindly advise how I can restore my website. This is urgent, pls.

**Comment by ilichzuniga** [comment]
Restore the old version of the plugin if you have a backup.

**Comment by kprovance** [comment]
A pretty serious bug somehow made it through our testing process.  The fixed version has been pushed to wp.org.  To get this version you may have to go into your server via FTP and delete the redux-framework plugin from your wp-content/plugins folder.  This will allow WordPress to function.  Afterward, the updated plugin can be reinstalled from wp.org, the the plugins section in the WordPress admin.

**Comment by dovy** [comment]
We truly are sorry this happened. It was completely my fault.  :(

**Comment by mybeautycravings** [comment]
Thank you, all. Followed the instruction and website is back up.

**Comment by ilichzuniga** [comment]
I did as instructed and deleted the exisiting plugin folder, went to install the new version 3.6.7.4, and I still get the same mkdir error, restored to version 3.6.7.3 and I'm working again. Please advise.

**Comment by contempoinc** [comment]
@Dovy You're the man!


Cheers,

Chris Robinson
www.contempoinc.com
twitter.com/contempoinc

**Comment by dovy** [comment]
@ilichzuniga please provide the full error here. Or hop on slack http://slack.redux.io and I'll help you in real-time.

**Comment by tjdownes** [comment]
Same issue as @ilichzuniga (paths with "..." edited for security)

```
Fatal error: Uncaught Error: Call to a member function mkdir() on null in /.../wp-content/plugins/redux-framework/ReduxCore/inc/class.redux_filesystem.php:187 Stack trace: #0 /.../wp-content/plugins/redux-framework/ReduxCore/inc/class.redux_filesystem.php(126): Redux_Filesystem->do_action('mkdir', '/.../...') #1 /.../wp-content/plugins/bushcraft-toolkit/includes/redux/extensions/wbc_importer/extension_wbc_importer.php(106): Redux_Filesystem->execute('object') #2 /.../wp-content/plugins/bushcraft-toolkit/includes/redux/extensions/wbc_importer/extension_wbc_importer.php(149): ReduxFramework_extension_wbc_importer->demoFiles() #3 /.../wp-content/plugins/bushcraft-toolkit/includes/redux/extensions/wbc_importer/extension_wbc_importer.php(71): ReduxFramework_extension_wbc_importer->getImports() #4 /.../wp-content/plugins/bushcraft-tool in /.../wp-content/plugins/redux-framework/ReduxCore/inc/class.redux_filesystem.php on line 187
```

**Comment by dovy** [comment]
@tjdownes 3.6.7.5 is transmitting to WP.org and that fixes that last issue.

**Comment by tjdownes** [comment]
@dovy thank you. Can you comment when it's published? My site is down, so there's like 2 people who can't see it right now ;)

**Comment by tjdownes** [comment]
3.6.7.5 does not resolve the issue

```
Fatal error: Uncaught Error: Call to a member function put_contents() on null in /.../wp-content/plugins/redux-framework/ReduxCore/inc/class.redux_filesystem.php:238 Stack trace: #0 /.../wp-content/plugins/redux-framework/ReduxCore/inc/class.redux_filesystem.php(136): Redux_Filesystem->do_action('put_contents', '/.../...', Array) #1 /.../wp-content/plugins/bushcraft-toolkit/includes/redux/extensions/wbc_importer/extension_wbc_importer.php(106): Redux_Filesystem->execute('object') #2 /.../wp-content/plugins/bushcraft-toolkit/includes/redux/extensions/wbc_importer/extension_wbc_importer.php(149): ReduxFramework_extension_wbc_importer->demoFiles() #3 /.../wp-content/plugins/bushcraft-toolkit/includes/redux/extensions/wbc_importer/extension_wbc_importer.php(71): ReduxFramework_extension_wbc_importer->getImports() #4 /.../wp-content/p in /.../wp-content/plugins/redux-framework/ReduxCore/inc/class.redux_filesystem.php on line 238
```

**Comment by tjdownes** [comment]
Actually this is a new error. Can I make the recommendation that you folks roll back to 3.6.7.3 and sort out the issues with the current releases before moving forward again?

**Comment by ilichzuniga** [comment]
Same error here after updating to 3.6.7.5 on my staging site `Fatal error: Call to a member function put_contents() on null in /nfs/c10/h06/mnt/148970/domains/wordpress.lynwood.ca.us/html/wp-content/plugins/redux-framework/ReduxCore/inc/class.redux_filesystem.php on line 238`

**Comment by 9mmparabellum** [comment]
same issue here , after upgrading i get this error

Fatal error: Call to a member function mkdir() on null in plugins/redux-framework/ReduxCore/inc/class.redux_filesystem.php on line 187

**Comment by WowFactorMedia** [comment]
yes, still getting the error with the version fresh from wp.org

**Comment by lucianocn** [comment]
same error with version 3.6.7.5

**Comment by ilichzuniga** [comment]
Do not update to 3.6.7.5, redux devs are working on trying to fix whats wrong, if you updated delete the redux plugin folder and replace it with the old version from the redux github page, this will make your website functional again.

**Comment by 9mmparabellum** [comment]
where can i get version 3.6.6 again? can you upload it ?

thanks

**Comment by ilichzuniga** [comment]
Fore those that don't know how to pull old versions from github, here is version 3.6.2 which I know works, 
https://drive.google.com/open?id=0B7Rqy-5TM76bd3pnVjkzWTFYNWc

**Comment by ilichzuniga** [comment]
Just got word on the slack channel that they are rolling back the repo.

**Comment by tjdownes** [comment]
f your host supports backups, you can restore directly from backup. Just restore the wp-content/plugins/redux-framework folder. I restored mine from Sunday and all is well.

It doesn't appear they've been consistent about tagging releases on the repo, so the latest branch, which should work, is 3.6.5. You can [download the zip from GitHub directly](https://github.com/reduxframework/redux-framework/archive/3.6.5.zip) and upload it manually.

**Comment by contempoinc** [comment]
Hope they're rolling back the repo and WordPress.org, got buyers blowing me up about this.

@Dovy work your magic!

**Comment by 9mmparabellum** [comment]
thanks , installed version 3.6.5 and worked again

**Comment by ilichzuniga** [comment]
looks like dovy may have found the issue

**Comment by dovy** [comment]
Gah, finally fixed. 3.6.7.6. Please download now. Sorry everyone!

**Comment by dovy** [comment]
On a side note this was entirely my fault. I was trying to fix an issue we've had where the redux directory is listable. See https://www.google.com/search?q=Index+of+%2Fsite%2Fwp-content%2Fuploads%2Fredux

To fix this issue, we're now writing an index.php file inside any directory our filesystem class uses. I also wanted to clean up some code, so I added the creation of that directory via our api, not a standard WordPress function as we've had before.

The problem was I was attempting to use the $wp_filesystem before it had been instantiated. Thanks to the help of @ilichzuniga others I was able to resolve the issue.

Thank you for your patience all. I am sorry for the issue in the name of greater security!

**Comment by tjdownes** [comment]
I can confirm that 3.6.7.7 is working fine for me. Thanks @dovy

**Comment by dovy** [comment]
You're most welcome. Sorry all once more!

**Comment by SanjibBarma** [comment]
I'm just new in wordpress and I got this problem what should i do?

object from empty value in ....\Avada\includes\lib\inc\redux\framework\FusionReduxCore\inc\class.fusionredux_filesystem.php on line 29

**Comment by dovy** [comment]
@SanjibBarma that’s a bug in Avada’s code of redux. I’ll ping one of their devs about this. Best to just send them a support ticket and link this thread.
