### ISSUE TITLE
Fatal error: Call to a member function mkdir() on null 

### ISSUE THREAD

**Issue by KAJOJEK** [reduxframework/redux-framework#3417]
After update plugin to version 3.6.7.4 I have this error:
Fatal error: Call to a member function mkdir() on null in .../wp-content/plugins/redux-framework/ReduxCore/inc/class.redux_filesystem.php on line 187

Please repair.

**Comment by dovy** [comment]
I just pushed a fix. Please pull from this repo or wait 10 mins for the wp.org release to be deployed. Thank you for your patience.
