### ISSUE TITLE
Fatal Error After Updating

### ISSUE THREAD

**Issue by giuliomarziani** [reduxframework/redux-framework#3418]
Fatal error: Uncaught Error: Call to a member function mkdir() on null in xxxxxxxxxx/wp-content/plugins/redux-framework/ReduxCore/inc/class.redux_filesystem.php:187 Stack trace: #0 xxxxxxxxxx/wp-content/plugins/redux-framework/ReduxCore/inc/class.redux_filesystem.php(126): Redux_Filesystem->do_action('mkdir', '/home/svaposel/...') #1 xxxxxxxxxx/wp-content/plugins/tdl-extensions/framework/extensions/wbc_importer/extension_wbc_importer.php(106): Redux_Filesystem->execute('object') #2 xxxxxxxxxx/wp-content/plugins/tdl-extensions/framework/extensions/wbc_importer/extension_wbc_importer.php(149): ReduxFramework_extension_wbc_importer->demoFiles() #3 xxxxxxxxxx/wp-content/plugins/tdl-extensions/framework/extensions/wbc_importer/extension_wbc_importer.php(71): ReduxFramework_extension_wbc_importer->getImports() #4 xxxxxxxxxx.c in xxxxxxxxxx/wp-content/plugins/redux-framework/ReduxCore/inc/class.redux_filesystem.php on line 187

**Comment by dovy** [comment]
Thank you for that. The fix has been pushed to this repo and is currently being deployed to WP.org. Please give it a try.

**Comment by dovy** [comment]
Issue resolved. Please update to 3.6.7.6.
