### ISSUE TITLE
Metabox not inheriting parent option. 

### ISSUE THREAD

**Issue by ACODA-LTD** [reduxframework/redux-framework#3419]
## Support Hash
http://support.redux.io/?id=7%2FCO6TTfpjbrvsaFbVKlchmq8GJVGMBXVbepTnv3rS9%2Bh%2B22gK4DmQkIgoMnnDIRNivkgvlIjnFj%2BAG7KhVqmg%3D%3D

## Steps to reproduce

Set a background image via Theme Options > Header > Header Styling > Background Image. The Page or Post will not inherit this option. Instead, it's blank. Suggesting it's taking the blank field value within the Page or Post.

I'm dumping the header_image variable for reference. 

## Expected Behavior

When saving the Background Image theme option, it should update the Pages and Posts. Like with other options, such as the Header Background Color. 

However, even with this, I seem to have to double save the Theme Options in order for it to take affect. 

## Actual Behavior

It appears the Post / Page Metabox option overrides the Theme Option, even though it's blank. 

## Any Error Details (PHP/JavaScript)
None

**Comment by kprovance** [comment]
Are you the theme author or a theme user?  If you are a user, you need to contact the theme author.  If you are a user, this belong in the extensions issue tracker, since it involves Metaboxes.  Thanks.

https://github.com/reduxframework/redux-extensions/issues

Please be sure to include all this information as well.

**Comment by kprovance** [comment]
PS - you have to include a default argument in your option panel.  If you have not, it will be blank.  That's by default.

**Comment by ACODA-LTD** [comment]
I'm the the Theme Author.

I've set the default argument to blank, but it makes no difference: 

`			array(
				'id'       => 'header_image',
				'type'     => 'media', 
				'url'      => true,
				'title'    => __('Background Image', 'dynamix'),
				'subtitle' => __('Set a Background Image.', 'dynamix'),
				'default'   =>  '',
			),`

**Comment by kprovance** [comment]
Please post to where I have indicated.  This issue tracker is for the Redux core, not extensions.
