### ISSUE TITLE
Redux Framework - Crashes Website

### ISSUE THREAD

**Issue by Wilberto1** [reduxframework/redux-framework#3422]

**Comment by Wilberto1** [comment]
Your new Redux Framework updates have crash 3 of our website. So, we know is not a problem with our sites but with Redux Framework itself. 

We understand that you are not responsible for the support, but we feel that important to let you know that your new updated on the Redux Framework are crashing websites. This is something that we strongly feel you need to address. As of now, we have 3 websites that we can't update because of your Redux Framework. 

Thank you.

**Comment by dimitrilongo** [comment]
why you do not update on a test site or pre-prod  to see if everything is ok then you push to your live site. With that kind of workflow you avoid issues

**Comment by Wilberto1** [comment]
Every website we've updated when down and we had to use backups to restore our sites.


Our top developers have said the new update on the Redux Framework is the issue.


Godaddy developers also confirm the problem was Redux Framework.


So, at this point, we will wait for your company to address the problem.


Wilberto Barahona

Founder & CEO

818.601.5984

wilberto@emprezo.com


http://emprezo.com/

[1497495385332_Emprezo-Site.jpg]<http://emprezo.com/>

The information contained in this e-mail message is intended only for the personal and confidential use of the recipient(s) named above. This message may be an attorney-client communication and/or work product and as such is privileged and confidential. If the reader of this message is not the intended recipient or an agent responsible for delivering it to the intended recipient, you are hereby notified that you have received this document in error and that any review, dissemination, distribution, or copying of this message is strictly prohibited. If you have received this communication in error, please notify us immediately by e-mail, and delete the original message.


________________________________

**Comment by dovy** [comment]
@Wilberto1 can you get on http://slack.redux.io and I'll try to help you today.

**Comment by dovy** [comment]
Also can you post the actual error you're getting and the version of Redux you installed please.

**Comment by dovy** [comment]
This has been resolved by updating to the newest version of Redux.  :)

**Comment by neko** [comment]
Is there any sort of testing process before updates are made available to your 500k+ consumers?
