### ISSUE TITLE
Redux Framework conflict with Visual Composer

### ISSUE THREAD

**Issue by ceas88** [reduxframework/redux-framework#3423]
In the backend visual composer loads fine, but when the homepage loads everything shows for a split second then displays white. I have the latest version, although I have tried various other versions with other versions of Redux Framework.

**Comment by kprovance** [comment]
Could you please go back and open a new issue window, read the entire block of text there, and post back the required information that we need in order to help you. I am not able to offer any help based on this one statement alone. Thank

**Comment by dovy** [comment]
Also I fear we're going to need to probably log into your system. First, are you the developer or the user? Have you tried contacting the author of your theme/plugin that Redux is using?

**Comment by kprovance** [comment]
No reply.  Closing.
