### ISSUE TITLE
Latest Version of Redux does not display Home Page on Theme unless I disable

### ISSUE THREAD

**Issue by hawks50** [reduxframework/redux-framework#3424]
Hi,

does any one know why REDUX does not work 100% correctly on all website hosting providers? For example, on one of my websites, it won't show the Home Page but it will show all the other pages correctly. I have the latest version of Reddux installed. And the only way I can see the whole website is if I turn off Reddux. But yet the same website on another server works perfectly fine.

I've mentioned this to one of the hosting providers and they say it's not their issue? Even though it works on another hosting provider. What specific questions can I say for them to fix this conflict?

**Comment by dovy** [comment]
Haha. I just responded on slack bud.

We had an issue with a version of Redux we pushed. Be sure you have the newest version. That will fix the issue.  :)
