### ISSUE TITLE
How to add Yelp in the sticky social icon

### ISSUE THREAD

**Issue by S1lv1to** [reduxframework/redux-framework#3425]
Hello,

On my site i have the sticky social icon where user can get access to my social media accounts and i was wondering how to add yelp on there as I see it's not an option. Can you please advise me on this.

Thanks,
Siilvio

**Comment by kprovance** [comment]
Not sure how this is a Redux issue.  It sound like something you may need to take up with the theme author, which is not us.  Sorry.  Thanks.
