### ISSUE TITLE
Previus Redux version

### ISSUE THREAD

**Issue by niko80** [reduxframework/redux-framework#3426]
Hi,
where i can download the previous version of redux plugin for wordpress?

**Comment by niko80** [comment]
I found it, thank you

**Comment by kprovance** [comment]
Previous versions are not supported by us, please do not submit issues about them.  Perhaps instead you could tell us about whatever issue you are having with the current stable version?

**Comment by dovy** [comment]
@niko80 as @kprovance said. If you need help, let us know.
