### ISSUE TITLE
google analytics parameter

### ISSUE THREAD

**Issue by behrokh1985** [reduxframework/redux-framework#3428]
## Any Error Details (PHP/JavaScript)
![image](https://user-images.githubusercontent.com/33035794/31902866-9c1a403c-b826-11e7-8bd8-90d41b4ba97f.png)
![screen shot 2017-10-23 at 19 09 20](https://user-images.githubusercontent.com/33035794/31902889-b1fadef2-b826-11e7-87e1-fafd6c6d8aeb.png)

**Comment by kprovance** [comment]
We did not author this theme, and therefore are unable to help with this.  Please contact the theme author directly for all support matters.  Thanks.  Good luck.
