### ISSUE TITLE
Redux embedded and sortable field problem

### ISSUE THREAD

**Issue by fakeartist** [reduxframework/redux-framework#3429]
Hi. I have embeded the redux in a site of mine. All work good except for one problem.

If I use a sortable field, then the console returns this error:

`Uncaught TypeError: c.sortable is not a function`

and the sortable field does not work (you cannot drag and drop).

I have the latest WordPress and Redux versions.

If I install the plugin the usual way (and not embed it), the sortable field works as expected.

Any idea what might be wrong?

Thank you

## Support Hash
http://support.redux.io/?id=mu6HrV3vDm35GuOlm4xS5NW23Sltudhne2YcZFC9ll4QFN3HRutsjbb73NdqEZ%2F4KOVaqRpL8eDdaAkZH8SRPQ%3D%3D

## Steps to reproduce
Initialize the redux config through a plugin (and not through a theme).

## Expected Behavior
Drag and drop the items in a sortable field.

## Actual Behavior
Cannot drag and drop the items in a sortable field.

## Any Error Details (PHP/JavaScript)
`Uncaught TypeError: c.sortable is not a function`

**Comment by dovy** [comment]
Are you sure you're not doing something funky with the embed? Make sure you're including framework.php much earlier, not hooks.

**Comment by fakeartist** [comment]
Thanks for your reply. I also installed the plugin the usual way (not embed) and the problem still persists.

The problem is that I try to initialize the redux config file through a plugin (and not a theme).

I initialize the redux by using this line:

add_action('init', array($this, 'initSettings'));

All works good, except for the sortable field. Only the sortable field has the problem.

**Comment by dovy** [comment]
https://docs.reduxframework.com/core/generating-a-support-hash/

**Comment by kprovance** [comment]
No reply.  Closing.

**Comment by fakeartist** [comment]
I have entered all the info you require at my original question on the top (and the hash). Here is the hash itself

http://support.redux.io/?id=mu6HrV3vDm35GuOlm4xS5NW23Sltudhne2YcZFC9ll4QFN3HRutsjbb73NdqEZ%2F4KOVaqRpL8eDdaAkZH8SRPQ%3D%3D

Could you reopen the ticket?

Thank you

**Comment by kprovance** [comment]
I see this:

```php
                array(
                    'id' => 'social_icons',
                    'type' => 'text_sortable',
                    'title' => 'Social Icons',
                    'subtitle' => 'Define and reorder your social links.<br /><b>Note:</b> These will be displayed in the "Bucket Social Links" widget so you can put them anywhere on your site. Only those filled will appear.<br /><br /><strong> You need to imput the entire URL (ie. http://twitter.com/username)</strong>',
                    'desc' => 'Icons provided by <strong>FontAwesome</strong> and <strong>Entypo</strong>.',
                    'checkboxes' => array(
                        'widget' => 'Widget',
                        'header' => 'Header',
                    ),
                    'options' => array(
                        'flickr' => 'Flickr',
                        'tumblr' => 'Tumblr',
                        'pinterest' => 'Pinterest',
                        'instagram' => 'Instagram',
                        'behance' => 'Behance',
                        'fivehundredpx' => '500px',
                        'deviantart' => 'DeviantART',
                        'dribbble' => 'Dribbble',
                        'twitter' => 'Twitter',
                        'facebook' => 'Facebook',
                        'gplus' => 'Google+',
                        'youtube' => 'Youtube',
                        'vimeo' => 'Vimeo',
                        'linkedin' => 'LinkedIn',
                        'skype' => 'Skype',
                        'soundcloud' => 'SoundCloud',
                        'digg' => 'Digg',
                        'lastfm' => 'Last.FM',
                        'appnet' => 'App.net',
                        'rss' => 'RSS Feed',
                    ),
                    'class' => '',
                ),
```

We do not have a 'text_sortable' field as part of our core package.  If that is a modification you made to the core, then it is unsupported as we do not support mods made to the core we offe, especially in a situation where you have embedded the core..  The only alternative is premium support, which is $100.00 an hour.

**Comment by fakeartist** [comment]
That's strange... My field is this one:

`array(
                        'id' => 'social_share_btns',
                        'type' => 'select',
                        'multi' => true,
                        'sortable' => true,
                        'title' => __('Social share buttons activation and order', 'redux-framework-demo'),
                        'options' => array(
                            '1' => 'Facebook',
                            '2' => 'Twitter',
                            '3' => 'Google+',
                            '4' => 'Pinterest'
                        ),
                        'required' => array('woo_single_socialshare', '=', array('1'))
                    ),`

Which is a part of you core package, right?

**Comment by kprovance** [comment]
Please upgrade to v.3.6.7.9 from this repo.

**Comment by fakeartist** [comment]
Great! That fixed the error and it now works like a charm! Thank you so much!
