### ISSUE TITLE
Multiple "parent" required values issue

### ISSUE THREAD

**Issue by anthonyryanrusso** [reduxframework/redux-framework#3431]
Any items that have multiple required checks like the following will have a slight delay in the options panel when toggling.

            'required' => array(
                array('header_middle_icons_menu', 'equals', '1'),
                array('header_middle_cart', 'equals', '1')
            )

Prior to v3.6.7.7 this wasn't an issue.

**Comment by kprovance** [comment]
Nothing was changed in that regard.  Not sure what to tell you, not having any of the required information.  Sorry.

**Comment by dovy** [comment]
Please provide a support URL if you want us to check on our end.  ;)

**Comment by anthonyryanrusso** [comment]
I've made a video of the newest version of Redux vs the prior version, you
can see the difference.  Whether you touched these files in your update or
not they have an issue.

https://drive.google.com/open?id=0B3Iwpa55He9FZ2c4a1E2UVBmbE0

**Comment by anthonyryanrusso** [comment]
I've made a video of the newest version of Redux vs the prior version, you
can see the difference.  Whether you touched these files in your update or
not they have an issue.

https://drive.google.com/open?id=0B3Iwpa55He9FZ2c4a1E2UVBmbE0

**Comment by dovy** [comment]
@anthonyryanrusso We won't look at this further UNTIL you provide a support URL.
https://docs.reduxframework.com/core/generating-a-support-hash/

It's too difficult for us to duplicate on our end unless you provide this.

**Comment by dovy** [comment]
And by "previous version" please tell me what version you're talking about. I need a number here.

**Comment by anthonyryanrusso** [comment]
The prior version I tested in the video was 3.6.5

**Comment by kprovance** [comment]
Okay.  Seriously.  For the third time, PLEASE provide the support URL that has been requested.  See the link Dovy provided.  Otherwise this issue can go no further and will be closed.  Since Redux is free and basic support is free, we need to do this our way.  Thanks.

**Comment by anthonyryanrusso** [comment]
First of all, I am really tired of you being a jerk to everyone on these issues, it has to stop.  We all understand that you're supporting this project for free, no need to repeat yourself to every user that comes on here.

Second of all, if you want to close out an issue because I didn't paste some support url that you need, that's your choice.  I have provided plenty of information (even videos) that show exactly what's going on.

Third of all, I was only responding again because Dovy asked what the previous version was.

**Comment by kprovance** [comment]
I have deleted your message because name calling is just inappropriate and we don't tolerate it, from anyone.  If such posts continue, they will be deleted and you could face a ban.  Unfortunately, I am no longer interested in assisting with this issue and am done with it.  I am sure Dovy will look past your behavior and help at some point, provided you give him the support URL he asked for.  If you had read the text in the new issue window which spelled out the information we needed, this would never have been an issue.

**Comment by anthonyryanrusso** [comment]
There was definitely no harsh name calling in my previous comment, a judge of character from the many comments I've read through on here.  Lets be honest the reason you deleted it is because 90% of users on here would agree with me. If you choose to ban me because you aren't able to treat others how you want to be treated, then you're just a hypocrite.  I hope @dovy can read that previous comment because I guarantee nothing bad was said in it.  Like I said before, the only reason I responded was because Dovy asked for a previous version.

**Comment by dovy** [comment]
Ok everyone. Let’s not be upset. In the defense of @krprovance we have asked 3 times for a support url. It gives us your config so we can test locally and not “guess” what’s going on. 

Let’s all get along. We’re on the same team. ;)

**Comment by kprovance** [comment]
Strike 2

**Comment by kprovance** [comment]
If you have something you want to say to me, get on Slack and say it to me in private.
