### ISSUE TITLE
i need the origonal .pot lang file

### ISSUE THREAD

**Issue by hattaabdo** [reduxframework/redux-framework#3433]
hy
 i hope this is the perfect place to get that i need the pot file please
for the multistore woocommerce theme
thanks

**Comment by kprovance** [comment]
He are not your theme's author and therefore cannot offer support.  You will need to contact the author of your theme...which is not us.  Sorry.  Good luck.

**Comment by hattaabdo** [comment]
when i click on support in my theme redirect to this page..

**Comment by kprovance** [comment]
Because the author of your theme took our sample config and didn't bother to change the support links.  Unfortunately, it happens all the time.  You might mention it to him as well his support links are wrong.

**Comment by hattaabdo** [comment]
okay thanks
