### ISSUE TITLE
http://support.redux.io/?id=tqhugHlLq951X2Qv6HXZKeTqCG2JLC8XX6JRKYp%2BwdlLEk6bjhmIrOgcnnU8HrKozyVrHmGPciF5LSQTxm9Tzw%3D%3D

### ISSUE THREAD

**Issue by intuitive1** [reduxframework/redux-framework#3435]
## Support Hash
http://support.redux.io/?id=tqhugHlLq951X2Qv6HXZKeTqCG2JLC8XX6JRKYp%2BwdlLEk6bjhmIrOgcnnU8HrKozyVrHmGPciF5LSQTxm9Tzw%3D%3D

**Comment by kprovance** [comment]
What exactly is the issue?  That information was left out.

**Comment by intuitive1** [comment]
Our site went down www.illinoisshade.com and the following error is on
screen:
*Parse error*: syntax error, unexpected ''{"ABeeZee":{"variants":[{"id"'
(T_ENCAPSED_AND_WHITESPACE), expecting ')' in
*/home/illinois/public_html/wp-content/plugins/redux-framework/ReduxCore/inc/fields/typography/googlefonts.php*
on
line *1*

If I deactivate the Redux plugin the site comes back up but we are missing
header/footer objects. Not sure how to fix the Redux issue. Any help would
be appreciated - I have never worked with Redux before.

Thank you.

Gina Lorenz
760-828-3048
www.IntuitiveWebsites.com

**Comment by kprovance** [comment]
Okay, let me say up front we are not the author of this theme.  First, have you tried contacting them to see if this has been an issue with anyone else.  I cannot replicate it, but I also don't have the theme, and I have no way of knowing if this author did something using Redux hook to modify output.

All I can suggest is deactivating the Redux plugin and deleting it from the plugin interface.  After it's gone, download and active a fresh copy from the plugin interface.  If that does not correct the problem, you will need to contact the author of theme to see if he can reproduce it with his theme.

**Comment by intuitive1** [comment]
Thank you for your help. I appreciate your response and suggestion.



Gina Lorenz
760-828-3048
www.IntuitiveWebsites.com
