### ISSUE TITLE
Editor field text color not work

### ISSUE THREAD

**Issue by Rahisaiful** [reduxframework/redux-framework#3437]
I'm trying to use TinyMCE text color option in toolbar2 like http://prntscr.com/h83lez But it's not work. 
I used this code.
			array(
				'id'    => 'editor-text',
				'type'  => 'editor',
				'title' => __ ( 'Editor Text', 'demo' ),
				'default'   => '',
				'args'  => array(
					'textarea_rows' => 8,
					'tinymce' => array('toolbar2' => 'formatselect,underline,alignjustify,fontsizeselect,forecolor,forecolorpicker,backcolorpicker,styleselect,pastetext,removeformat,charmap,outdent,indent,undo,redo,wp_help'),

				),
			),

**Comment by babarbabar336** [comment]
where is the solution? topic closed without any solution/comment?
