### ISSUE TITLE
Plugins link redirect to Redux About Page.

### ISSUE THREAD

**Issue by Xervenine** [reduxframework/redux-framework#3438]
I am running version 3.6.7.7 of Redux.  Just installed it with a theme. When I click on plugins, it redirects to the Redux about page.  Any help would be appreciated to resolve this.

**Comment by kprovance** [comment]
That's what it does on first load.  Select something else in the admin menu and it will go away.

**Comment by Xervenine** [comment]
Mine just keeps doing the same thing.

**Comment by Xervenine** [comment]
Ahh. Cleared my cache.  Resolved!

**Comment by dovy** [comment]
Whew. Glad you fixed it.
