### ISSUE TITLE
Wordpress 4.9 Issue

### ISSUE THREAD

**Issue by krishna19** [reduxframework/redux-framework#3439]
Hi,
I'm using Redux Version 3.6.7.9. It works fine before I update the wordpress 4.9. After Update the wordpress the color picker not works.
Thanks

**Comment by dovy** [comment]
Did this get resolved @kprovance

**Comment by kprovance** [comment]
Could never reproduce it and no required information was provided to us.  So.  I don't know.  There were CSS issues which I fixed.

**Comment by dovy** [comment]
K. @krishna19 you need to respond with more details if you want us to assist. Otherwise this is closed.  ;)

**Comment by krishna19** [comment]
@dovy @kprovance thanks it was fixed now and sorry for not responding.

**Comment by dovy** [comment]
Thanks for letting us know. Just didn't want something left undone.  ;)
