### ISSUE TITLE
dev version breaks WBC-Importer-extension

### ISSUE THREAD

**Issue by andrejarh** [reduxframework/redux-framework#3440]
Hi,
Somewhere between your latest WordPress version and latest github version, 
https://github.com/Webcreations907/WBC-Importer-extension stopped working.

I went through latest Redux commits and laughed a bit about the @dovy naming of commit logs ( like OOps, One more thing, AAHHH) but sadly couldn't pinpoint the issue. 

I also reported the issue here: https://github.com/Webcreations907/WBC-Importer-extension/issues/85 - However the extension seems unsupported. Their latest commit was 10 month ago (but it worked fine last week, before redux update).

I know you have a lot of more important stuff to do then solving compatibility issues of third party redux plugins.  But anyway, I thought I'd at least let you know about it ....

## Support Hash
'#'
## Steps to reproduce
1. Load the extension https://github.com/Webcreations907/WBC-Importer-extension/ into latest redux version
2. Open redux
## Expected Behavior
No fatal error. :) 
## Actual Behavior
fatal error

## Any Error Details (PHP/JavaScript)
Fatal error: Uncaught Error: Call to a member function dirlist() on null in .../redux-extensions/extensions/wbc_importer/extension_wbc_importer.php:107 Stack trace: #0 .../redux-extensions/extensions/wbc_importer/extension_wbc_importer.php(149): ReduxFramework_extension_wbc_importer->demoFiles() #1 .../redux-extensions/extensions/wbc_importer/extension_wbc_importer.php(71): ReduxFramework_extension_wbc_importer->getImports() #2 .../redux-framework/inc/class.redux_api.php(71): ReduxFramework_extension_wbc_importer->__construct(Object(ReduxFramework)) #3 .../wordpress/wp-includes/class-wp-hook.php(286): Redux::loadExtensions(Object(ReduxFramework)) #4 /Use in .../redux-extensions/extensions/wbc_importer/extension_wbc_importer.php on line 107

**Comment by kprovance** [comment]
Could you post this in the dev version Git?  The beta is still private.  Thanks!

**Comment by andrejarh** [comment]
Sorry, @kprovance 
Where is the dev version Git?

**Comment by kprovance** [comment]
We are talking about Redux 4, right?  There is an issue tracker where you downloaded it.  Did you officially get an invite from us for this beta?  It is not public yet.

**Comment by kprovance** [comment]
Oh, the dev version of the open git.  Never mind, I thought you mean the v4.  We'll be offering a general beta soon.

As far as that extension goes, you're going to have to submit a ticket to them.  I just don;t have the time right now to debug other dev's code, at least not for free.  It would be a premium support situation since it's not our code.  Even if I could fix it, and the project is dead, there would be no one do a pull request.

**Comment by kprovance** [comment]
You sir, just got lucky.  I was looking into something else at noticed the parent object of the Redux filesystem was loading improperly.  Fixed it, which solves your issue.  Download v.3.6.7.11 from this repo and give it a try.

**Comment by andrejarh** [comment]
Will do that. Many thanks.
