### ISSUE TITLE
Typography field, Source Sans Pro missing languages

### ISSUE THREAD

**Issue by fakeartist** [reduxframework/redux-framework#3441]
## Support Hash

http://support.redux.io/?id=Wo21Hr8Ee%2FEAV6OZtf1CrEit3%2BipaFk1Au3QUxcy1aItT0EUYl5j3I%2FVExAJeCPDTPYeLKTu1RdeRLxZTbKFww%3D%3D

## Steps to reproduce

Choose Source Sans Pro as a font in a typography field

## Expected Behavior

In a typography field, the Source Sans Pro font should have also Greek (as seen [here](https://fonts.google.com/specimen/Source+Sans+Pro?selection.family=Source+Sans+Pro:200,300,400,600,700&selection.subset=greek-ext))

## Actual Behavior
In a typography field, the Source Sans Pro font only has Latin, Latin Extended and Vietnamese

## Any Error Details (PHP/JavaScript)

No errors

**Comment by kprovance** [comment]
The google font array needed to be updated, which I did for v.3.6.7.12.  You will have to download it from this repo, however.

It's difficult to keep up with all their updates.  However, the v4 of Redux we are working on will have an auto update feature without the need for an API key, and will solve this issue.  No ETA when at this point.

**Comment by fakeartist** [comment]
Works like a charm! Thanks a lot!
