### ISSUE TITLE
Fatal error: require_once(): Failed opening required 'core/panel.php'

### ISSUE THREAD

**Issue by presslayouts** [reduxframework/redux-framework#3442]
Hello Redux Team,

First of all your framework really appreciate with lots of features and option and easy customizability.

But when i  activated your plugin then display below fatal error and warring message.

```
Warning: require_once(core/panel.php): failed to open stream: No such file or directory in /home/namjestajkupi/public_html/wp-content/plugins/redux-framework/ReduxCore/framework.php on line 3278

Fatal error: require_once(): Failed opening required 'core/panel.php' (include_path='.:/opt/alt/php70/usr/share/pear') in /home/namjestajkupi/public_html/wp-content/plugins/redux-framework/ReduxCore/framework.php on line 3278
```

How can resolve it, Please you can help me.

Thank you.

**Comment by kprovance** [comment]
Looks like the either the core folder is missing, or the files in that folder are missing.  Best to delete that copt of Redux and reinstall from wp.org, or this repo.  If you are attempting to modify the core in order to remove those panels, please. do not.  They are there for a reason.
