### ISSUE TITLE
Hide / Show options

### ISSUE THREAD

**Issue by basestarter** [reduxframework/redux-framework#3445]
Hi,
I'm a new theme developper and I mostly learn by my own, but I just installed the redux framework and I was wondering if there was a way to create a hide/show (toggle) function for the options panel ? Example: I have a menu called "General Settings" and submenus "Styling, Functionnality, Css, etc." but I want to know how to only have "General Settings" and in this menu there will be for instance a "Styling" button that when clicked will show or hide the styling customization options ?

If you don't completly understand my request I would be more than happy to answer your questions.

Thanks

**Comment by kprovance** [comment]
The 'required' argument will accomplish this:  https://docs.reduxframework.com/core/the-basics/required/.  Examples are included in the sample-config.php
