### ISSUE TITLE
Possibility to define separate HEADERS and FOOTERS for different Pages

### ISSUE THREAD

**Issue by roderich74** [reduxframework/redux-framework#3449]
I was wondering if it would be possible to use redux framework to create and manage multiple HEADERS and FOOTERS for different Pages.

Some pages would use HEADERS and FOOTERS A and other pages would use HEADERS and FOOTERS B. Each with its own logo and details.

**Comment by kprovance** [comment]
Metaboxes extension.  This will allow you to do per page settings.
