### ISSUE TITLE
Adding a data option to slides

### ISSUE THREAD

**Issue by ilicmarko** [reduxframework/redux-framework#3452]
I really like the **Slides** field, it really saves you from making another custom post type, but I think it is missing one really essential thing. Having an option to add a post as a slider.

If you guys are planing on implementing it would be good to add a `data` option or even have like a switch with option one *Post* and *Custom*.

If this is not planned can someone give me at least a hint how I would go about implementing this. Would I have to create a whole new field type?

Thanks in advance.

**Comment by kprovance** [comment]
The field would have to undergo some modifications, which we do not plan on doing for v3.  Maybe in the upcoming v4.  But it's not a priority, I'm sorry to say.   However, you can use either our field overrides instructions, or create your own extension to modify the field into something else (you'd also have to call it something other than 'slides'

See this issue for a more in depth answer:  https://github.com/reduxframework/redux-framework/issues/3376
