### ISSUE TITLE
rest default values automatically

### ISSUE THREAD

**Issue by firaszwara** [reduxframework/redux-framework#3453]
i have two sections
section 1
section 2
i want  rest default values automatically in section 2  when i press save button in section 1..

**Comment by kprovance** [comment]
Redux does not have a section saving option.  Our save button saves everything at once.  Also, you did not include the required information for support.  That is required.

**Comment by firaszwara** [comment]
i have "select field" [color-name] => [blue,darkblue,red etc]  in section 1
and in section 2  "color fields" [background,border-color,text-color etc..]
the default values in section 2 is:
'default' => $get_color('background_color');
i want rest defualt values  when i change select field [color-name]  in section 1 ...
