### ISSUE TITLE
rest section automatically after the select field value changed in another section

### ISSUE THREAD

**Issue by firaszwara** [reduxframework/redux-framework#3454]
how to rest section automatically after the select field value changed in another section 
 i have select field for color name in section 1  
and in section 2 i have color fields (background,border color,text color etc..)  
the default values in color fields is 
` <?php 'default' => get_color('background_color'); ?> `
 i want to rest the default values after the select field value (color name) changed in section 1

i'm sorry if there any mistake because my english is not good

**Comment by kprovance** [comment]
That code doesn't even look like it will work.  I will say this only one more time; you need to provide the information we ask for, or we cannot assist.  Please open a new issue ticket and read the entire block of text there, specifically the support URL/hash.
