### ISSUE TITLE
rest section automatically after the select field value changed in another section

### ISSUE THREAD

**Issue by firaszwara** [reduxframework/redux-framework#3455]
## Support Hash
http://support.redux.io/?id=GvXtF0rdEf03qCieotJY8n%2F5cW3oHMD8lFRFwJccl111ndFWZAGkPLVozrooZfxOv4i%2FbdPP8FVPfu8LCLHlWA%3D%3D
## Any Error Details (PHP/JavaScript)

how to rest section automatically after the select field value changed in another section
i have select field for color name in section 1
and in section 2 i have color fields (background,border color,text color etc..)
the default values in color fields is dynamic depends on color name in select field

`<?php
Redux::setField($opt_name, 
   array(
    'id'       => 'body-text-color',
    'section_id' => 'custom-skin',
    'type'     => 'color',
    'title'    => 'Body Text Color',
    'default'  => $color->get('body')['text_color'],
    'validate' => 'color',

  )

    );
?>`

i want to rest the default values after the select field value (color name) changed in section 1

**Comment by kprovance** [comment]
Okay, now I need to know what 'rest' means.  Do you mean 'reset'?  Are you attempting to change the values of the select field based on another fields new value?

**Comment by firaszwara** [comment]
i want do what the 'reset section' button do..but when the user change the select field value(color-name)in anathor section..
the function:
 $color->get('body')['text_color'],
will return new value after the select field changed (color name).. i want set/update it..

**Comment by kprovance** [comment]
No, this is not something Redux does.  You will have to write some goodly amount of javascript, in which you'll need more than a moderate skill level in, and perhaps AJAX, depending on which route you go.  It's not something we can help with pro bono as this forum is for issue reporting oly.
