### ISSUE TITLE
Cant edit footer text and fields

### ISSUE THREAD

**Issue by filipexavierti** [reduxframework/redux-framework#3457]
Hello, i can't edit some fields like footer site...
can someone explain me why?

**Comment by kprovance** [comment]
You need to contact the author of your theme, which is not us.  Sorry.  Good luck.

**Comment by filipexavierti** [comment]
are u sure about that? i'm using Trips - WP

**Comment by kprovance** [comment]
Yeah, I am.  This is Redux Framework.  We have authored no theme, at all.  Your theme author used as as a vendor for their option panel and didn't fix their support links.  Now you are here, but here is not where you need to be.  Sorry.  We did not author that theme, we do not support it, and cannot help you.

**Comment by filipexavierti** [comment]
Omg, i'm realy sorry =/

**Comment by kprovance** [comment]
No need to be sorry.  It's just...not our theme, and we do not support it.

**Comment by filipexavierti** [comment]
ok, i get that thanks for the information have a nice week =D
