### ISSUE TITLE
W3C Validation error in h1 typography field

### ISSUE THREAD

**Issue by pareshsojitra** [reduxframework/redux-framework#3458]
Hi,

There is w3c error when i save h1 tags field value, can some one looks at the following.

**I have added the following code in Option Config File for H1 Tag Styling :**
----------------------------------------------------
array(
	'id' => 'h1-font',
	'type' => 'typography',
	'title' => esc_html__('H1', 'theme-toolkit'),
	'subtitle' => esc_html__('Specify the Heading font properties.', 'theme-toolkit'),
	'google' => true,
	'text-align' =>false,
	'output' => array('h1'),
),

**When I save options for h1 styling & see page viewsource, it gives W3C Validation error :**
----------------------------------------------------
Error: CSS: Parse Error: Encountered {. Was expecting one of: ...

**When i save code it compiles following code :**
------------------------------------------------
h1{font-family:'Bookman Old Style', serif;font-weight:normal;font-style:normal;opacity: 1;visibility: visible;-webkit-transition: opacity 0.24s ease-in-out;-moz-transition: opacity 0.24s ease-in-out;transition: opacity 0.24s ease-in-out;}.wf-loading h1,{opacity: 0;}.ie.wf-loading h1,{visibility: hidden;}

**The error in following Code, its adding comma after css value, that is why there is code error :**
------------------------------------------------
foreach ( $this->field['output'] as $value ) {
	$key_string .= ".wf-loading " . $value . ',';
	$key_string_ie .= ".ie.wf-loading " . $value . ',';
}

The above code is in "wp-content\plugins\redux-framework\ReduxCore\inc\fields\typography\field_typography.php".

**Comment by kprovance** [comment]
Nothing we can do about it for version 3.  Ill see if ti can be corrected in a future version.

**Comment by pareshsojitra** [comment]
Hi,

Is it really issue in code or error in my code ?

Can i bypass this issue some other way, any suggestion ?

**Comment by kprovance** [comment]
You'd have to edit the source, I guess to encode the comma (which didn't work as I recall).  ANy changes you make will be undone with the next update.  So basically...no.  Sorry.

**Comment by pareshsojitra** [comment]
OK, Thank you.

**Comment by jilly11** [comment]
I have this same issue and encoding the comma did not work. 
Can you share how to fix this code by editing the source? Thanks....

**Comment by pareshsojitra** [comment]
Hello,

I have fixed issue by overriding the typography extension & fixed the issue for many of the projects, works well..

You can contact me via email to get the code.
pareshsojitracom@gmail.com

Thank you.
