### ISSUE TITLE
How to on/off woocommerce filter with redux framework

### ISSUE THREAD

**Issue by kashifkiduniya** [reduxframework/redux-framework#3459]
I am using this woocommerce filter in my function file
add_filter ('add_to_cart_redirect', 'redirect_to_checkout');

function redirect_to_checkout() {
    global $woocommerce;
    $checkout_url = $woocommerce->cart->get_checkout_url();
    return $checkout_url;
}
How can i get on/off system to this filter with redux framework. I already created Option in redux.

**Comment by kprovance** [comment]
This is our issue tracker for bugs and other related things.  What you want is premium support.
