### ISSUE TITLE
Redux Framework Codex page not accessible (SSL error)

### ISSUE THREAD

**Issue by velichkod** [reduxframework/redux-framework#3460]
## Support Hash
N/A 
## Steps to reproduce
1. Open web browser.
2. Try to open "https://codex.reduxframework.com/"

## Expected Behavior
Get the Redux Framework Codex page content.

## Actual Behavior
Getting "Insecure Connection" browser error page.
## Any Error Details (PHP/JavaScript)
Mozilla Firefox version 58.0b11 was used.
As I get from details, the SSL certificate used on codex.reduxframework.com is signed for the github.com and subdomains, and browser is blocking such unsafe request.
Adding exception not available because  site uses HTTP Strict Transport Security (HSTS).

**Comment by kprovance** [comment]
We are aware.   No etc for a resolution.  Sorry.

**Comment by dovy** [comment]
It's hosted on GitHub and they don't have custom SSL certs for people. That's the issue.  ;)
