### ISSUE TITLE
Invalid security credential. Please reload the page and try again.

### ISSUE THREAD

**Issue by FelipeFAzevedo** [reduxframework/redux-framework#3463]
Everytime I try to change something using Appearence > Theme Options I cant save it, it keeps showing me the following message: Invalid security credential. Please reload the page and try again.

![invalid_security](https://user-images.githubusercontent.com/34921966/34420034-539c04b6-ebee-11e7-9c5c-4fafb52e2cad.PNG)

Im also trying to contact Dubro theme to help me, but without succes.  I already tried to reload the page, clear cache and Incognito mode, didnt work. Does anybody knows how to solve ir?

Thank you

**Comment by kprovance** [comment]
As we are unable to support users of themes that has redux installed, you will need to continue to contact the author of the theme.
