### ISSUE TITLE
PHP Warning:  unlink googlefonts.php Permission denied in field_typography.php on line 945

### ISSUE THREAD

**Issue by utsavs** [reduxframework/redux-framework#3464]
I upgraded my wordpress site from PHP 5.6 to PHP 7 and I am getting this error message from the logs:

PHP Warning:  unlink(/var/www/html/somanyerrands.com/wp-content/plugins/redux-framework/ReduxCore/inc/fields/typography/googlefonts.php): Permission denied in /var/www/html/somanyerrands.com/wp-content/plugins/redux-framework/ReduxCore/inc/fields/typography/field_typography.php on line 945

Site is down. Please help!

**Comment by kprovance** [comment]
It's a permission issue on that folder, and why we stopped supporting Google font updates.  Either change that folders permission to allow for writing, or set the update_google_font global argument to false.  If you are a theme user, please ask your theme author for assistance with this.  Good luck.

**Comment by utsavs** [comment]
no I am not a theme user. I updated the folder permissions of redux_framework to 777 and still having this issue

The update_weekly argument is set to false. I cant find update_google_font

**Comment by kprovance** [comment]
Sorry, the global argument should be `google_update_weekly` and it should be set to to false.  You didn;t say what version of Redux you are using.  You might also try updating to the version from this repo, since I have no idea how many fixes will be applicable.

**Comment by utsavs** [comment]
I am using 3.6.7.7 found on wordpress site:
https://en-ca.wordpress.org/plugins/redux-framework/

I opened the field_typography.php file and added the line 'google_update_weekly' => false to the function __construct class

Still no luck :( What am I doing wrong?

**Comment by utsavs** [comment]
I updated it to the repo version and still getting the same error. The site keeps going up and down

**Comment by kprovance** [comment]
No, that's not going to help.

This is the code tripping you up:
```php
            if ( isset( $this->parent->args['google_update_weekly'] ) && $this->parent->args['google_update_weekly'] && ! empty( $this->parent->args['google_api_key'] ) ) {
                if ( file_exists( $gFile ) ) {
                    // Keep the fonts updated weekly
                    $weekback     = strtotime( date( 'jS F Y', time() + ( 60 * 60 * 24 * - 7 ) ) );
                    $last_updated = filemtime( $gFile );
                    if ( $last_updated < $weekback ) {
                        unlink( $gFile );
                    }
                }
            }
```
It only runs when the `'google_update_weekly` argument is found AND set to true AND if the `google_api_key` argument is not empty.

When I said set your global argument, I meant in whatever file you are setting your option arrays  That file would be in your project/theme/plugin/ (whichever it is).  That is where the global args are set.  You may as well go in and remove `google_api_key` and `google_api_key` completely.  If after all that, it's still an issue, then my only other guess would be there is another plugin using Redux who is still using that google font update feature.  You'd then have to find it and disable it.

**Comment by kprovance** [comment]
I tried to look at your site.  I am assuming: www.somanyerrands.com.  On Chrome is gives me this:

This site can’t provide a secure connection

www.somanyerrands.com uses an unsupported protocol.
ERR_SSL_VERSION_OR_CIPHER_MISMATCH

On FireFox I get a Cloudflare window telling me a 502 Gateway error occurred.  These are not things associated with Redux.

**Comment by utsavs** [comment]
Ah Okay so the problem was actually in W3 Total Cache plugin. Once I deleted that  plugin, the site started working.

Anyways thanks for your help! I appreciate it!
