### ISSUE TITLE
Revolition Slider

### ISSUE THREAD

**Issue by Damarsito** [reduxframework/redux-framework#3467]
Hello,

I can´t install the Revolution Slider... This message appears:

Fatal error: Uncaught Error: [] operator not supported for strings in /var/www/vhosts/41/216979/webspace/siteapps/WordPress-234601/htdocs/wp-content/plugins/revslider/includes/framework/base-admin.class.php:71 Stack trace: #0 /var/www/vhosts/41/216979/webspace/siteapps/WordPress-234601/htdocs/wp-content/plugins/revslider/admin/revslider-admin.class.php(442): RevSliderBaseAdmin::addMetaBox('Revolution Slid...', '', Array, NULL) #1 /var/www/vhosts/41/216979/webspace/siteapps/WordPress-234601/htdocs/wp-content/plugins/revslider/admin/revslider-admin.class.php(72): RevSliderAdmin->addSliderMetaBox() #2 /var/www/vhosts/41/216979/webspace/siteapps/WordPress-234601/htdocs/wp-content/plugins/revslider/admin/revslider-admin.class.php(44): RevSliderAdmin->init() #3 /var/www/vhosts/41/216979/webspace/siteapps/WordPress-234601/htdocs/wp-content/plugins/revslider/revslider.php(156): RevSliderAdmin->__construct('/var/www/vhosts...') #4 /var/www/vhosts/41/216979/webspace/siteapps/WordPress-234601/htdocs/wp-admin/includes/plugin.php(1897 in /var/www/vhosts/41/216979/webspace/siteapps/WordPress-234601/htdocs/wp-content/plugins/revslider/includes/framework/base-admin.class.php on line 71

Can you help me??

I have not too much experience...

Thank you,

**Comment by dovy** [comment]
Contact Rev Slider support or your theme authors. Unfortunately we are neither so we can't support a product we didn't build. Have a great day!
