### ISSUE TITLE
Visual Composer won't activate 

### ISSUE THREAD

**Issue by Rasmus-VangRasmussen** [reduxframework/redux-framework#3471]
Hello,

I've just started using the "Artday" theme and when i bought the theme i got the idea that "Visual Composer" was included in the theme with updates - but I can't activate the plugin. I get an error message telling me that i do not own a licence. 

Looking forward to your reply

Best regards
Rasmus

**Comment by kprovance** [comment]
We are not the theme author.  Please contact whomever that is for support.
