### ISSUE TITLE
hi where can i buy the page builder for redux please

### ISSUE THREAD

**Issue by harrydad123** [reduxframework/redux-framework#3472]

**Comment by kprovance** [comment]
We don't currently offer any type of page builder.  The closest thing we have is a service that build a customized version of Redux based on the only the fields you want or need:  https://build.reduxframework.com

**Comment by harrydad123** [comment]
Just had a website build but I want to build pages? The developer wont help me, do I add a redux framework plugin on my wordpress site to help build a page?

**Comment by kprovance** [comment]
Redux Framework is an option panel that developers use to build their themes.  it is NOT a page builder.  I am sorry, but we I cannot help you with page building.
