### ISSUE TITLE
Sorter not working

### ISSUE THREAD

**Issue by ilicmarko** [reduxframework/redux-framework#3473]
There a really big problem with sorter filed.

First of all the value that is sent `post_name` is not really a post name generated by WP it is generated by your own function which is not correct.

```
private function replace_id_with_slug( $arr ) {
    $new_arr = array();
    if ( ! empty( $arr ) ) {
        foreach ( $arr as $id => $name ) {

            if ( is_numeric( $id ) ) {
                $slug = strtolower( $name );
                $slug = str_replace( ' ', '-', $slug );

                $new_arr[ $slug ] = $name;
            } else {
                $new_arr[ $id ] = $name;
            }
        }
    }

    return $new_arr;
}
```

As you see from here the `$slug` is generated in an inappropriate way, why?

Because if you have two posts with the same title they will have the same slug and this will happen (for sure) because you can query posts and custom post types. What is more if you have a utf-8 character inside your title (maybe a latin or cyrilic) this won't work, because your slug is not correct.

The only correct way to generate a slug is `wp_unique_post_slug`.

**I don't know why you would use the post_name as a key and not the ID?** All fields work with ID why doesn't this one?

**Comment by kprovance** [comment]
Do you have a proposed solution without breaking backward compatibility?

**Comment by kprovance** [comment]
This was why:  https://github.com/reduxframework/redux-framework/issues/1834

**Comment by ilicmarko** [comment]
Unfortunately no, that is a big problem I saw before add a pull request. Because if I change it to ID's it will break all the queries that use `post_name__in` because it would need to be replace with `post__in`. I have a temporary fix that will fix a part of a problem, using `sanitize_title`. I will add a pull request now. It will fix the cyrilic, latin and other UTF-8 chars

**Comment by kprovance** [comment]
I will go ahead and vet your pull request, and apply it if there are no problems.  Otherwise, something of this magnitude would require a complete rewrite of the field.  Considering it's low percentage of use and lack of support from our users, it's just not something I am able to do at present.

**Comment by ilicmarko** [comment]
Thank you for the reply!
I can write a custom field that would do the same but work with the ID's, so it would be added to the core of the redux, should I submit it as a pull request? If so what should I name it?

**Comment by kprovance** [comment]
Chances are modifying the field to do what you want would break compatibility for us, so it's probably not something we could accept, as backward compatibility is very important to this project.  However, you are free to modify the field however you wish.  I would turn it into an extension however, as modifying the core directly is not recommended.  Anything you change will be lost with the next update.

**Comment by ilicmarko** [comment]
I think you didn't understand what I wanted to say. I would like to create a **NEW** field type that would become a part of the redux core, so it ships with new field example: `sorter-id`.
