### ISSUE TITLE
color_rgba field doesn't accept full transparency (eg. 0, 0 ,0 ,0 )

### ISSUE THREAD

**Issue by zabestof** [reduxframework/redux-framework#3476]
http://support.redux.io/?id=KSii9IuNxyLtS1ydAeZyvl%2BDCHGGG8NQPJB%2FNvGpfQmASqSOOZ7zW4llWJ4S0lNIVmUy9K1DBvm4XciDpZwN1w%3D%3D

Hi there,

When I select a fully transparent color in the color_rgba field it reverts back to the fully opaque color. Is this the intended mode of working?

Cheers!

**Comment by kprovance** [comment]
Looks like it's a limitation of the vendor.  The altenative is to click the 'transparent' button, assuming you have it set in your args, or just leave the field blank, or set default in your args to blank.
