### ISSUE TITLE
Redux Clash

### ISSUE THREAD

**Issue by kewalsunberg** [reduxframework/redux-framework#3477]
Hello there,

We're still facing the problem with loading the website as Redux Framework still clashes with windows. The website wouldn't load when the plugin is activated.

It loads back (with some elements missing) when the plugin is deactivated. Our URL is truetribe.uk

Could this be due to SSL permissions or something else?

Looking forward to your help .

Thanks,
Kewal Ram

![true tribe paris wild by nature designer swim shorts backpacks](https://user-images.githubusercontent.com/35330321/34818802-b900b352-f6dd-11e7-96c9-7ce62026521b.png)
![true tribe paris without redux](https://user-images.githubusercontent.com/35330321/34818804-b9495b02-f6dd-11e7-9517-6b05a5e2d142.png)

**Comment by kprovance** [comment]
You need to contact the theme author for support in this matter, as we do not support users of themes that use our framework.  The author needs to determine the cause of the issue and report it to us properly in the event it's a Redux problem.
