### ISSUE TITLE
after update the last version of Wordpress under name of "Sample Options" comes on my adminpanel page but i don't need this.How can i remove this section?

### ISSUE THREAD

**Issue by eyupdmg** [reduxframework/redux-framework#3479]

**Comment by kprovance** [comment]
Disable it in the plug in meta

**Comment by Uranbold** [comment]
Hello,

PHP version 7.0.28

dev_mode false and show_options_object false.

But Sample Options Tab displaying twice and Theme Options not working.

@eyupdmg Did you resolved this?

**Comment by Uranbold** [comment]
Only Redux Activated and WordPress version 4.9.4.

**Comment by kprovance** [comment]
Sounds like you might have more than one Redux plugin running.  I don't know.  You provided NONE of the required information.  Go into the plguin page, find Redux Framework and click Deactive Demo Mode.
