### ISSUE TITLE
What would YOU like to see in Redux?

### ISSUE THREAD

**Issue by ghost1227** [reduxframework/redux-framework#348]
We (especially @dovy) have been working hard to bring you the best, most powerful, and most flexible options panel available today, and I think we're off to an awesome start! That said... there's ALWAYS room for improvement! So, I'd like to pose a simple question to our awesome community...

__What would you like to see in the future?__

**Comment by Momizat** [comment]
Make it more faster and i would like to see "add sidebars" field in this awesome framework 
Thanks dovy, kprovance
Regards

**Comment by Jim-E** [comment]
A field to Import/Export Section giving the ability to import/export just that section.

Thanks

**Comment by dovy** [comment]
@Jim-E That wouldn't be insanely difficult to add a section export... Care to contribute?

**Comment by Jim-E** [comment]
I'll dig around but my skills are nowhere near yours. I'll no doubt have questions if that's ok.

**Comment by dovy** [comment]
Always.  ;)

**Comment by Jim-E** [comment]
@dovy As I suspected, I don't have the expertise to pull this one off. Might be willing to hire it done though.

**Comment by kprovance** [comment]
At $100 bucks an hour, probably a *minimum' of one work day?  That could get pricey, quickly.  ;-)

**Comment by Jim-E** [comment]
Ouch!

**Comment by dingo-d** [comment]
So about that group field, any eta of that option? :)

**Comment by dovy** [comment]
It's now called the repeater extension and it was just released!  ;)

**Comment by dingo-d** [comment]
Oh, that's it! I was wondering what that was :D :+1:  Awesome!

**Comment by CaerCam** [comment]
Did you plan to provide a way to filter the post_types available in select? For instance if you want the user to be able to select post_types but not media. For now I'll just add a filter myself, but it could be usefull to have a way to exclude some post_types.

**Comment by dovy** [comment]
Using the data argument you can filter out extra posts types using the args argument for a select field. Search out issues. We've answered this many times before.

**Comment by nicolas92** [comment]
I do not know if it's possible to create a premium extension "One Click Demo Data" to import the entire contents of a site, sliders, widgets, theme options, etc., as Redux is used by many theme premium, including my own :), I think it would be a good extension.

**Comment by kprovance** [comment]
@nicolas92 , I began work on one, but our theme has been my focus.  Soon, hopefully.  :)

**Comment by nicolas92** [comment]
it would be great :)
You have created a theme?

**Comment by dingo-d** [comment]
Can the 'ajax_save' option be enabled globally? Or does it need to be specified on every field separately? Thanks.

**Comment by kprovance** [comment]
It's always been a global argument, never a field one. (right, Dovy?)

**Comment by dingo-d** [comment]
I understood it needed to be put in every field array :S

**Comment by kprovance** [comment]
O_o  Oh wow.  No.  That must have been a massive miscommunication.  `save_ajax` goes in the `setArgument` function.  :)

**Comment by dingo-d** [comment]
Yeah, I changed it now, and it works :) Thanks for clarification :)

**Comment by vol4ikman** [comment]
How can I create  a simple text field repeater?

**Comment by dovy** [comment]
@vol4ikman - http://reduxframework.com/extensions/repeater   :)

**Comment by vol4ikman** [comment]
@dovy
I mean without paying 200$ ;)

**Comment by dovy** [comment]
Sorry @vol4ikman, but we need support to keep the project alive. Let me tell you though, the repeater field took MONTHS to complete.

**Comment by ThemeSurgeon** [comment]
Build it yourself. Or, find someone who is qualified and willing to write
complex custom functions for free.

**Comment by dovy** [comment]
Hehe. Thanks @ThemeSurgeon.

**Comment by Emetrop** [comment]
I don't know if I do something wrong but I cannot find out how to get image uploaded via media type field in some other sizes then the origin size through the url attribute or thumbnail size through the thumbnail attribute of the returning redux array. I would like to have access to all of the predefined image sizes by wordpress like - medium, small etc. + my custom sizes defined by add_image_size WP function. Or do I do just something wrong?

**Comment by paulthecoder** [comment]
Add an option to media field to choose the image size of the preview. Instead of loading 150x150 thumbnail you could load the full image. For ex. uploading a logo usually gets cut off with a thumbnail size 150x150.

**Comment by dovy** [comment]
@paulthecoder That's why we include the attachment ID, so you can easily query that information.  :)

**Comment by invot** [comment]
The ability to import or export your options and their values. This would be great for backups or migrations.

**Comment by kprovance** [comment]
@invot: http://docs.reduxframework.com/core/fields/importexport/

**Comment by justnorris** [comment]
### Moar [naming conventions](https://make.wordpress.org/core/handbook/coding-standards/php/#naming-conventions).

I'm moving a part of my code to the "new redux" today, and I encountered a rather ugly `Redux::setArgs()`. 

I get it - you guys prefer camels over snakes. It's ok. But when you're developing to a community that's used to snakes ( I am at least ) it's a bit different... I think at least the exposed API should comply.

**Comment by kprovance** [comment]
The API required a static class solution.  I wouldn't necessarily call it preference.

**Comment by justnorris** [comment]
Static class solution is perfectly fine for the API.

setArgs is the part that doesn't look like Wordpress, it should be set_args() according to naming conventions.

**Comment by ThemeSurgeon** [comment]
With all due respect, WP naming conventions suck.

**Comment by kprovance** [comment]
LOL!  Why is this such an issue?  Damn!  if it bothers you that much, fork the project, change it to how you like it and be done with it.  Sheesh!  I hate to break it to you, but the WP way, their 'standards' doesn't equate to 'the best' or even proper.  They are not the be all, end all guidelines to how code should be written.  That's like telling Orwell he needs to write more like Steinbeck.  It's all relative.

**Comment by kprovance** [comment]
@ThemeSurgeon THANK YOU!  I'm looking for the 'Like' button here!

**Comment by justnorris** [comment]
I'm on the "What would you like to see in Redux" topic right ? 

Meh - as always - expressing an opinion isn't an option with you @kprovance. Either I agree with you, or keep my mouth shut. Duly noted.

**Comment by kprovance** [comment]
Hey, you can express all the opinions you want.  it doesn't make them or you right.

**Comment by justnorris** [comment]
That's the thing - an opinion is usually subjective. You're defining mine as being "wrong" because it doesn't match yours. And that's what I said earlier - either I agree with you, or keep my mouth shut, because opinions that don't match yours are wrong. 

It's okay, I'll just keep being a spectator and shut up now. Thank you for continuously making Redux, no matter whether I like the API or not. It's a great project with awesome results. 

Cheers!

**Comment by ThemeSurgeon** [comment]
@jusnorris I think you should agree there are horrible naming conventions in WP. 

Example, does is_admin make a bit of sense given that it only checks if the page view is in admin? 

I wouldn't sweat that stuff. In fact, I'd buck their bad habits altogether. 

setArgs is better anyway.

**Comment by justnorris** [comment]
@ThemeSurgeon 
1. I'm not going to argue about that in Redux github issues. Not the place.
2. Not going to argue about is_admin() at all. It was introduced in 1.5.1, that's a very, very long time ago.

Yes. setArgs is the best.

**Comment by dovy** [comment]
Boys, boys. Not the place and not the post. BTW, this thread is retired. We're moving it to http://ideas.reduxframework.com.

Please take personal disagreements elsewhere.  :)

**Comment by liquida** [comment]
1) I think it would be amazing the possibility to create sections dynamically via ajax, based on required fields

2) Sections identifier data-rel="$ Section-> ID", so we can create links with http://{options_url}&tab=SECTION_ID

Regards

**Comment by SnakeO** [comment]
Is this thread alive?

**Comment by kprovance** [comment]
Not particularly.   See:  http://ideas.reduxframework.com.
