### ISSUE TITLE
Global variable in get_wordpress_data return empty

### ISSUE THREAD

**Issue by gomonkey** [reduxframework/redux-framework#3481]
Hello,
I have the problem when I am use get_wordpress_data() method for get sidebars list.
The array is empty.

I make my own function before find this method in class and have the same problem.

If i call my own function by `add_action( 'widgets_init', 'get_all_sidebar_array' );` it's work and that means the sidebars are registered

I don't know if is redux issue or I wrong something.

The redux file is called in the last row in function theme file.

What can be?
Thank you

**Comment by kprovance** [comment]
This issue tracker is for bug reporting and issues with the Redux core.  Unfortunately, core modification and anything else falls under premium support, and would require a subscription for that service for us to help with any issue outside the Redux core.

Alternatively, there is https://wordpress.stackexchange.com, or you may get lucky on our Slack channel.  Sometimes people help out there.

Good luck.
