### ISSUE TITLE
Code to Fix W3C Validation error in h1 typography field?

### ISSUE THREAD

**Issue by jilly11** [reduxframework/redux-framework#3482]
Hi, 

I was reading this post https://github.com/reduxframework/redux-framework/issues/3458#issuecomment-352409170

and see that I have the same problem which is creating w3c errors throughout my site.

I tried to encode the comma suggested in this file  "wp-content\plugins\redux-framework\ReduxCore\inc\fields\typography\field_typography.php"

foreach ( $this->field['output'] as $value ) {
$key_string .= ".wf-loading " . $value . ',';
$key_string_ie .= ".ie.wf-loading " . $value . ',';
}

But it did not work. (If I remove the  ,  the error is gone, but the fonts do not appear).

Is there a way to fix this code by editing the source? 

Thanks....

**Comment by kprovance** [comment]
At this time, no.  It will be addressed in Redux 4.  No ETA on that.  In the meantime, disable the async_typography argument, and this goes away.

**Comment by jilly11** [comment]
Can you tell me which line this is? Thanks....

**Comment by jilly11** [comment]
It worked...thanks!

**Comment by pareshsojitra** [comment]
Hello,

We can not fix the code by updating the code in redux plugin.

So we need to fix issue by overriding the code.

I have fixed issue by overriding the typography extension & fixed the issue for many of the projects, works well..

You can contact me via email to get the code.
pareshsojitracom@gmail.com

Thank you.
