### ISSUE TITLE
Website is down! reduxframework.com

### ISSUE THREAD

**Issue by toddbarnett** [reduxframework/redux-framework#3491]
I am unable to access the documentation. It was down yesterday as well. Is there a mirror site? I also noticed this isn't the first time the documentation has been inaccessible.

**Comment by kprovance** [comment]
We'e aware of it.  No ETA when it will be fixed.  Sorry.

**Comment by mukundthanki** [comment]
Website is not working yet. docs (http://docs.reduxframework.com/) builder (http://build.reduxframework.com/) are not accessible.

**Comment by dovy** [comment]
It's back.  ;)
