### ISSUE TITLE
options save doesnt work . on page refresh options gets reverted

### ISSUE THREAD

**Issue by ronakganatra9** [reduxframework/redux-framework#3493]
Hello Team,

I have an issue with saving option when. whenever I save option and then on the front end when I page refresh within one or two minutes options gets reverted.  please help me to solve the issue.

Thanks

**Comment by ronakganatra9** [comment]
@ kprovance is there any solution for it ?

**Comment by kprovance** [comment]
No idea.  You provided none of the required information we requests.  Tickets they do not supply it are closed.

**Comment by dovy** [comment]
Please create a ticket with more details than "it's not working." It takes far too much time to manage tickets where we have no data to go off of. Hint, we need a support URL.  ;)

**Comment by kprovance** [comment]
Each new ticket window has a very specific set of instructions we provide in an effort to prevent these kinds of 'it doesn't work' tickets.  Please review it carefully and in its entirety.  Thanks.
