### ISSUE TITLE
Status Page

### ISSUE THREAD

**Issue by DNACode-ca** [reduxframework/redux-framework#3494]
## Support Hash
http://support.redux.io/?id=kGG2AApoxAM9HJDSJxNOtBAl8rtP7A55PNQ4LoAb5o7W0aeeZ9qucd6XygG%2B0tdrCWZ5nAzeGszE6DcyaMckCFLwX3r2%2FLgdkCgvtvuShsiJloIxufTLEuFd09cP2m0u

## Steps to reproduce
Go under Tools >> Redux Framework >> Status

## Expected Behavior
Expected to see the debug page that includes information about the current websites WordPress Install.

## Actual Behavior
Receiving a PHP error (below)

## Any Error Details (PHP/JavaScript)
[21-Feb-2018 12:05:51 UTC] PHP Fatal error:  Uncaught Error: Call to a member function get_error_message() on array in \wp-content\plugins\automotive\ReduxFramework\ReduxCore\inc\class.redux_helpers.php:507
Stack trace:
#0 \wp-content\plugins\automotive\ReduxFramework\ReduxCore\inc\welcome\views\status_report.php(21): Redux_Helpers::compileSystemStatus(false, true)
#1 \wp-content\plugins\automotive\ReduxFramework\ReduxCore\inc\welcome\welcome.php(452): require_once('Z:\\MAMP\\htdocs\\...')
#2 \wp-includes\class-wp-hook.php(286): Redux_Welcome->status_screen('')
#3 \wp-includes\class-wp-hook.php(310): WP_Hook->apply_filters('', Array)
#4 \wp-includes\plugin.php(453): WP_Hook->do_action(Array)
#5 \wp-admin\admin.php(22 in \wp-content\plugins\automotive\ReduxFramework\ReduxCore\inc\class.redux_helpers.php on line 507

**Comment by DNACode-ca** [comment]
Looks like it's being caused by a '400 Bad Request' response from the URL: http://reduxframework.com/wp-admin/admin-ajax.php?action=get_redux_extensions but the response isn't an wp_error object so it can't get_error_message(). 

I submitted a pull request that fixes this issue: #3495

**Comment by kprovance** [comment]
It's a server side issue we are looking into.  Also, I will apply your code fix, which is also needed.  WIll post back when it's resolved.

**Comment by kprovance** [comment]
Problem resolved on our end.  And error trap code added.  We're good.  Thank you for the assist!  ;-)

**Comment by DNACode-ca** [comment]
Awesome sounds good, glad I could help!
