### ISSUE TITLE
Redux framework conflict with jetpack after connecting with WordPress.com account using jetpack plugin

### ISSUE THREAD

**Issue by ronakganatra9** [reduxframework/redux-framework#3496]
## Support Hash

themeoptions are resetting automatically. conflict with jetpack after connecting with jetpack

## Steps to reproduce
I am using beamstore WooCommerce theme which uses redux framework for theme options setting.

1. Activate beamstore theme, Redux framework.

2. go to theme options page (ie. beamstore settings)

3. change any setting like color or logo etc.

4. go to your website it will working fine.

5. install and activate jetpack plugin. till activation of jetpack plugin it is working fine.

6. go to jetpack settings connect your wordpress.com account with jetpack and your website.

7. move anywhere into WordPress admin panel after go to settings page your options are resetted automatically. check from frontend and it will changed into default settings.

## Expected Behavior
Everything will working fine

## Actual Behavior
theme options resetting automatically after 5-10 minutes

## Any Error Details (PHP/JavaScript)
No errors getting but not working as expected

Please provide me solution as early as possible.

Regards,
Thanks

**Comment by kprovance** [comment]
Support url?

**Comment by ronakganatra9** [comment]
Which support url are you talking about can you please explain me ?

Do you need my live website URL?

**Comment by kprovance** [comment]
Wait, you are not the author of the theme?  I am sorry, we do not offer support for users of themes that use our framework.  It is the responsibility of the theme author to support their work.  Please contact them with your issue.  They need to determine the cause.  If the developer determine it's a Redux issue, they need to come to us with their findings.  That is simply how we operate.  So, please contact the author of this theme.  Good luck.
