### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by kipou96** [reduxframework/redux-framework#3498]
Hello,

I installed the Intima template and I am very happy with it: http://guillaume-boivin.com/

Thing is: all my website is in french, except the "hire me" and "download resume" button, do you know where I can translate this part ?

Best Regards

**Comment by kprovance** [comment]
Redux is a tool for developers to include an options panel in their project. Consequently, we do not offer support for folks who have purchased a theme or plugin that uses Redux. The responsibility of support for themes and plugins falls upon it's author.
