### ISSUE TITLE
Customizer API partial /selective refresh

### ISSUE THREAD

**Issue by MihaiCraciun** [reduxframework/redux-framework#3500]
Hi,

I'm trying to get an existing Redux field to work with selective refresh in customizer but can't find any documentation or examples on the web.

I've managed to figure out that the 'id' used by `$wp_customize->selective_refresh->add_partial()` is `$opt_name['field-id']` and got the Edit button to appear and link to the correct section in the Customizer, but that's as far as I got.

I'm trying to get a sortable field type to work but I have no clue what to do to stop it from refreshing the page and to reflect the value of the checkbox.

```
function my_customizer_options(WP_Customize_Manager $wp_customize) {
  $wp_customize->add_setting( 'my_opt[my-sortable-field]' , array(
    'transport' => 'postMessage'
  ) );
  $wp_customize->selective_refresh->add_partial('my_opt[my-sortable-field]', [
    'selector' => '.sortable_container',
    'render_callback'     => 'callback_fn',
  ]);
}

add_action('customize_register', 'my_customizer_options');
```
and the callback

```
function callback_fn(){
  $my_opt = get_option('my_opt');
  $items = $my_opt['my-sortable-field'];
  foreach ($items as $key => $value){
    echo 'item: '. $key .' ; value : '.$value .'<br>';
  }
}
```
and outputting with

```
<div class='sortable-container'>
   <?php callback_fn(); ?>
</div>
```

**Comment by kprovance** [comment]
Hi!

Please keep customizer specific issues to the customizer integration tracker.  Thanks!

https://github.com/reduxframework/customizer-integration/issues

**Comment by ramseva** [comment]
Hi!

Please keep customizer specific issues to the customizer integration tracker. Thanks! 
http://support.redux.io/?id=GdgEdI1GFyBTTsWxzVPY4JIIM13Ul78QJJfAt65yq068HTpK4uguI1vgRk83xujT9LbpLsdpWqahODgxFLNMpQ%3D%3D

**Comment by MihaiCraciun** [comment]
Where issues go to die you mean?
It would be cool if you’d focus on closing some of them. That tracker is stale af...

**Comment by kprovance** [comment]
Well, unfortunately, that is the reality.  I don;t know if you are under the assumption that Redux is a profitable venture in which this is all Dovy and I do all day? It isn't.  We make literally nothing.  My time here, is all volunteer.  We get ZERO support for our community.  They take and take and give nothing back...except complaints that we are not doing a good enough job, which really motivates me to give more of my time to people who have really done nothing to earn it.  And right now, I am basically in this project by myself and I have many other things on my plate that will hopefully revitalize this project.  Dovy has many more important things going on in his life that take priority over pro bono work for people who - again- take and give nothing back, and still expect us to ail every issue they have, immediately.  I wish I had the support from the community and the income from this project to devote my time to everyone's issues 24/7, but I do not.  That's reality.  It would be very cool if things were different, but they aren't.
