### ISSUE TITLE
Font Weight

### ISSUE THREAD

**Issue by stormit** [reduxframework/redux-framework#3501]
Hello,

Thank you for the awesome plugin!

I'm having a problem. I add a font option in Theme Options. But I want to load some bolder fonts from that font. For example, if I add the Poppins font, font weight is 500. I want also to load 600,700 from this font. I know you have the all_styles option. But I don't want to load all. So, could you please add a filter which allows us to load more font weights from a font option?

Thank you!

**Comment by kprovance** [comment]
We have no plans for such a thing at this time.  We do not have the funding or support of our community to spend the needed number of hours to research, implement and debug this.  Sorry. Hopefully someday this will change.  You are free to add this functionality and submit a pull request, but we vet those very carefully for backward compatibility issues.
