### ISSUE TITLE
errors from redux

### ISSUE THREAD

**Issue by atv2016** [reduxframework/redux-framework#3509]
Not sure if i should have removed that block of text, but here goes:

Yes i'm a user of a template that utilises redux. I'm also a developer.
I realize not to expect any support, but i'm still going to give it a try. I would appreciate a pointer in the right direction.

I am getting many redux errors in my /var/log/httpd/error_log. This is slowing my site down, and ultimately runs out of memory. I already tried to install the latest redux so it would overwrite the theme that also has redux, but i still get the errors.

[Wed Mar 28 18:51:26.768589 2018] [:error] [pid 15679] [client 82.45.65.95:62059] PHP Notice:  Undefined index: database in /var/www/html/wp-content/plugins/redux-framework/ReduxCore/framework.php on line 799, referer: http://localhost/wp-admin/tools.php?page=redux-status
[Wed Mar 28 18:51:26.768733 2018] [:error] [pid 15679] [client 82.45.65.95:62059] PHP Notice:  Undefined index: database in /var/www/html/wp-content/plugins/redux-framework/ReduxCore/framework.php on line 801, referer: http://localhost/wp-admin/tools.php?page=redux-status
[Wed Mar 28 18:51:26.768794 2018] [:error] [pid 15679] [client 82.45.65.95:62059] PHP Notice:  Undefined index: database in /var/www/html/wp-content/plugins/redux-framework/ReduxCore/framework.php on line 803, referer: http://localhost/wp-admin/tools.php?page=redux-status
[Wed Mar 28 18:51:26.768847 2018] [:error] [pid 15679] [client 82.45.65.95:62059] PHP Notice:  Undefined index: database in /var/www/html/wp-content/plugins/redux-framework/ReduxCore/framework.php on line 807, referer: http://localhost/wp-admin/tools.php?page=redux-status
[Wed Mar 28 18:51:26.768903 2018] [:error] [pid 15679] [client 82.45.65.95:62059] PHP Notice:  Undefined index: opt_name in /var/www/html/wp-content/plugins/redux-framework/ReduxCore/framework.php on line 812, referer: http://localhost/wp-admin/tools.php?page=redux-status
[Wed Mar 28 18:51:26.768959 2018] [:error] [pid 15679] [client 82.45.65.95:62059] PHP Notice:  Undefined index: global_variable in /var/www/html/wp-content/plugins/redux-framework/ReduxCore/framework.php on line 756, referer: http://localhost/wp-admin/tools.php?page=redux-status
[Wed Mar 28 18:51:26.769438 2018] [:error] [pid 15679] [client 82.45.65.95:62059] PHP Notice:  Undefined index: opt_name in /var/www/html/wp-content/plugins/redux-framework/ReduxCore/framework.php on line 2517, referer: http://localhost/wp-admin/tools.php?page=redux-status
[Wed Mar 28 18:51:26.771818 2018] [:error] [pid 15679] [client 82.45.65.95:62059] PHP Notice:  Undefined index: database in /var/www/html/wp-content/plugins/redux-framework/ReduxCore/framework.php on line 799, referer: http://localhost/wp-admin/tools.php?page=redux-status
[Wed Mar 28 18:51:26.771833 2018] [:error] [pid 15679] [client 82.45.65.95:62059] PHP Notice:  Undefined index: database in /var/www/html/wp-content/plugins/redux-framework/ReduxCore/framework.php on line 801, referer: http://localhost/wp-admin/tools.php?page=redux-status
[Wed Mar 28 18:51:26.771838 2018] [:error] [pid 15679] [client 82.45.65.95:62059] PHP Notice:  Undefined index: database in /var/www/html/wp-content/plugins/redux-framework/ReduxCore/framework.php on line 803, referer: http://localhost/wp-admin/tools.php?page=redux-status
[Wed Mar 28 18:51:26.771841 2018] [:error] [pid 15679] [client 82.45.65.95:62059] PHP Notice:  Undefined index: database in /var/www/html/wp-content/plugins/redux-framework/ReduxCore/framework.php on line 807, referer: http://localhost/wp-admin/tools.php?page=redux-status
[Wed Mar 28 18:51:26.771851 2018] [:error] [pid 15679] [client 82.45.65.95:62059] PHP Notice:  Undefined index: opt_name in /var/www/html/wp-content/plugins/redux-framework/ReduxCore/framework.php on line 812, referer: http://localhost/wp-admin/tools.php?page=redux-status
[Wed Mar 28 18:51:26.771856 2018] [:error] [pid 15679] [client 82.45.65.95:62059] PHP Notice:  Undefined index: global_variable in /var/www/html/wp-content/plugins/redux-framework/ReduxCore/framework.php on line 756, referer: http://localhost/wp-admin/tools.php?page=redux-status

Many thanks in advance.

**Comment by kprovance** [comment]
Honestly, I have no idea what that theme user is doing with Redux.  You'd have to take it up with them.  I do not see any of these errors ina ny of my Redux installs, so it's likely something they are doing incorrectly.  For me to download his work and review it is a premium support issue.  We no longer do that kind of work for free.  Sorry.
