### ISSUE TITLE
Redux Option compatible with pl domain?

### ISSUE THREAD

**Issue by anggaerlsa** [reduxframework/redux-framework#3511]
Hi there,

Is anyone know why my redux option not show on WordPress sidebar menu. Actually it works until the domain change to domain-name.pl

Is polish domain doesn't work with this plugin? Or I need to config something in the server?

Cheers :)

**Comment by kprovance** [comment]
I need you to go back and read the New Issue window you just complete skipped over.  None of the we require is provided.  Also, if you are a theme user, you must go to the theme author for support, as we did not author any theme.

**Comment by anggaerlsa** [comment]
Sorry my bad.

## Support Hash
I cannot get any support hash code since I cannot access my Redux Framework option panel in WordPress admin backend.

## Steps to reproduce
Install Redux Plugin to the site.

## Expected Behavior
The options should be in WordPress admin menu, but it's not it's disappear

## Actual Behavior
There is no 'Option' menu in admin sidebar. Plugin is active. No JS error no php error. The issue come when my client change the URL to "site-name.com.pl"

Cheers :)

**Comment by dovy** [comment]
What he means is we need a support URL to even begin helping you.  :)

**Comment by kprovance** [comment]
No reply.  Closing.
