### ISSUE TITLE
redux-image-select-selected class is not added for Default

### ISSUE THREAD

**Issue by niraj547** [reduxframework/redux-framework#3512]
## Support Hash
http://support.redux.io/?id=W5l4thlfKfLTTVulxsw%2BBDotxO0tZfkQgw%2BwW%2BW3MYMC6PnClEB5JcFBNsUrP9ivqOrVtD2ekD1xz8pOBOMYMA%3D%3D
## Steps to reproduce
Added Current Version in Theme Folder i.e inbuilt Version 3.6.8
## Expected Behavior
It must add 'redux-image-select-selected' class in default option values so that our custom css work
## Actual Behavior
Hi I was trying to create a theme option for my theme, Everything is working fine and great but thr was 1 pblm 

`array(
                'id'       => 'layout_type',
                'type'     => 'image_select',
                'tiles'    => true,
                'title'    => __('Header Layout', 'redux'), 
                'options'  => array(
                                'boxed-layout' => array('title' => 'Boxed', 'img' => REDUX_ADMIN_ASSETS.'img/layout/layout-width.png'),
                                'full-width' => array('title' => 'Full width', 'img' => REDUX_ADMIN_ASSETS.'img/layout/layout-width.png'),
                            ),
                'default'  => 'full-width',
                ),
            )`

That's for image_select everything was working fine like Image were showing etc. But, My pblm is default value is not working, suppose in above code `'default' => 'full-width'` in theme option doesn't have redux-image-select-selected class in full-width option, its added when u click on that. I don't know how to debug

**Comment by kprovance** [comment]
Where is the rest of the requested information?

**Comment by niraj547** [comment]
Srry Updated :)

**Comment by niraj547** [comment]
anything?

**Comment by kprovance** [comment]
Addressed in v.3.6.9, available in this repo.  Bo ETA when we'll push to wp.org.  Soon, I would suspect.
