### ISSUE TITLE
Dashboard error WP_Feed_Cache::create() should not be called statically on PHP 7

### ISSUE THREAD

**Issue by Graphicfort** [reduxframework/redux-framework#3514]
## Support Hash
http://support.redux.io/?id=p7gjVFvy53RGXlNdq1GydJJ%2BAiscsM2%2BQm7v2bJxr3wmvvLc0gB%2FZjuGpxHxD8sW4NNdRM3sLCm1xMH58Ug7bw%3D%3D

I'm using WP 4.9.5, PHP 7 and i got a dashboard error
DEPRECATED Error: [8192]Non-static method WP_Feed_Cache::create() should not be called statically	/Applications/MAMP/htdocs/LTR/wp-includes/SimplePie/Registry.php on line 215

- integrate the frame work with my own theme i got the previous error
- using new installation of WP same error.
- using new installation of WP with twentyfifteen  same error.
- using new installation of WP and activate the plugin demo with twentyseventeen without doning anything with it still have the same error

when i switch the PHP to 5, no errors appear

**Comment by kprovance** [comment]
That's a WordPress file.  Not much we can do about their own depreciated code.
