### ISSUE TITLE
adminbar link missing in all sub sites admin

### ISSUE THREAD

**Issue by Kieran-Calvert** [reduxframework/redux-framework#3515]
Hi Guys

I just switched to using the plugin version from an older version I had included in my Theme. The multisite adminbar link is missing in all sub sites on the admin side. 
The admin_bar  is visible on the admin bar on the front end however.

II have 'admin_bar' => true, in config.

Is there a way to get it to display in admin again in all subsites?

Thanks

Kieran

**Comment by kprovance** [comment]
I use Redux in my theme on multi site.  I am seeing nothing like this,  However, you left out required information as aske for in the new issue window.  Without it, there isn't much else I can do.
