### ISSUE TITLE
getting virus alert on your http://docs.reduxframework.com 

### ISSUE THREAD

**Issue by gulonline** [reduxframework/redux-framework#3519]
dear team,

i am getting avast virus alert on your http://docs.reduxframework.com link. please check from your end.
i am also attaching screenshot for your better understand.
![image](https://user-images.githubusercontent.com/31122804/39614411-4a571366-4f8d-11e8-85a0-5930c8612a4d.png)

thanks

**Comment by kprovance** [comment]
That was something we tried several months back to try and get people to donate to our site (it wasn't considered a virus then).  I removed that code a long time ago after the complaints began.  I don;t see it on the site anymore.  Clear cache?
