### ISSUE TITLE
Non-static method WP_Feed_Cache::create() should not be called statically	

### ISSUE THREAD

**Issue by db-dzine** [reduxframework/redux-framework#3526]
## Steps to reproduce
Load Dashboard in WP-Admin
## Expected Behavior
No error
## Actual Behavior

Non-static method WP_Feed_Cache::create() should not be called statically

## Any Error Details (PHP/JavaScript)
<img width="2246" alt="bildschirmfoto 2018-05-18 um 16 26 13" src="https://user-images.githubusercontent.com/3169388/40240190-4fa93dc2-5ab8-11e8-819f-dd0e1c32e27c.png">

**Comment by kprovance** [comment]
It looks as if WordPress depreciated one of their own apis and forgot to update their own software? Redux is only calling the API, the actual error has nothing to do with Redux

**Comment by dovy** [comment]
We could update our call though @kprovance. Thanks for the note. We'll look into it.  :)
