### ISSUE TITLE
Reduxframework Download Link is broken

### ISSUE THREAD

**Issue by Santukon2** [reduxframework/redux-framework#3528]
Hello There, I been trying to download latest version, but its not posible, as link is not existing.
![captura_2](https://user-images.githubusercontent.com/32211954/40561252-d933fda8-605c-11e8-8577-0a9b1cce4d07.PNG)
![captura](https://user-images.githubusercontent.com/32211954/40561253-d955f228-605c-11e8-9ce9-9f14e0c74c29.PNG)

**Comment by kprovance** [comment]
What page is this, exactly?  You didn't say.  A URL would be helpful.

**Comment by Santukon2** [comment]
Hello, Sorry for the late response url is: https://reduxframework.com/download-2/
