### ISSUE TITLE
Dealing with the compiler

### ISSUE THREAD

**Issue by Santukon2** [reduxframework/redux-framework#3529]
Hello There,
    After making several test with the compiler, I noticed 2 things:

1. If I add for example color to the class .test_class, and then I add another field for example, height to the same class, the compiler returns: .test_class{color:red}.test_class{height:10px}, instead of .test_class{color:red;height:10px}. So question is: Is there an option to optimize the css output combining calsses? 
In case no, I would like to be able to make my own compiler, but for that I would need to also get the classes, so question here would be: is there a way to get the classes inputed for the compiler on then theme global options?

2. Just starting I found that I can not set a background color, as there´s no way to indicate this right? As I can just set the class for the compiler, and not if I want to add a color or a background-color. I am missing something here?

Thanks a lot framework is amazing

**Comment by kprovance** [comment]
Hi.

1) No.  Each field handles it's own CSS output, and thus they are separated as such. (You can see what I man if you understand PHP well by looking at the individual field php files and look out the output function.  Each field kicks back it's css into the core where it is accumulated.)   The only alternative I can think of off the top of my head is strong manipulation, in which you take the output string and use something like substr and regex to reorganize the entire thing.  Might be more work that it's worth, and I have no idea what the speed benefit would be like.  I can tell you - as I've seen it asked many, many times -  if this is an effort to write a css file that will load on each page, it's not an easy thing to ull off in terms of reliability and individual server settings (what might work on yours will assuredly not work on everyones).  It's why we dropped support for such a concept, and why we have the output feature.  But, it won't organize the css the way in which you are asking.

2. If you are talking about the color field, the mode may be set (see: https://docs.reduxframework.com/core/the-basics/output-2/).  I understand the page is for output, but it also applies to compiler.  Or it should.

**Comment by Santukon2** [comment]
Hello kprovance,
   Thanks a lot for your fast response. OKay point 1 is clear. But for point 2, link looks broken.
Thank you.

**Comment by kprovance** [comment]
https://github.com/reduxframework/redux-framework/issues/3530

**Comment by Santukon2** [comment]
oK clear thanks
