### ISSUE TITLE
ATTENTION DEVS:  Our website is currently down.  We know.

### ISSUE THREAD

**Issue by kprovance** [reduxframework/redux-framework#3530]
So, there is no need to post about it.  If you would like notification when the site is back, please tag yourself in this issue.  I will post back here when everything is as it should be.

Thank youf or the understanding, and we apologize for the inconvenience.  Remember, you can download the latest version of Redux from this repo, or from wp.org.

**Comment by CodeBrauer** [comment]
Where can I get any docs?

**Comment by kprovance** [comment]
Right now, no where.  Sorry.  It sucks this happened on an American holiday.  I have no idea when Dovy will get to this.

**Comment by kprovance** [comment]
It's because the site is down.

**Comment by dovy** [comment]
Fixed!  :)

In the future (version 4) we'll be removing all dependency on our website FYI.

**Comment by kprovance** [comment]
Site is up people!  Thank you, Dovy!!  We all appreciate it!

**Comment by db-dzine** [comment]
You are awesome :)
