### ISSUE TITLE
How to display slides?

### ISSUE THREAD

**Issue by kentneo** [reduxframework/redux-framework#3532]
Hello, I'm new to the Redux Framework and do not know how to display slides out the Font End. Can you help me how to make it to Front End? I need a sample code.

Thank You!

**Comment by kprovance** [comment]
Redux does not, nor do we here offer actual design interfaces.  It is an option panel that inputs the desired options, which may use the output for, for whatever you wish.  It does not output actual slide interfaces.  You will need to design those yourself, or hire a professional designer to do so.  Good luck.
