### ISSUE TITLE
Required dependant on slider field's value

### ISSUE THREAD

**Issue by codeminelab** [reduxframework/redux-framework#3533]
Let's say that I have a slider field like this one:

```
array(
                'id' => 'slider_id',
                'title' => 'Slider title',
                'default' => 0,
                'min' => 0,
                'step' => 10,
                'max' => 1000,
                'type' => 'slider'
            ),
```

And I want to hide other fields, if the slider's value is greater than 0 (zero).

Can I do so by using the required argument on the desired fields?

**Comment by codeminelab** [comment]
Solved. 

    'required' => array('form_submit_max_width', '!=', array('0')),

**Comment by dovy** [comment]
Rockin'.  ;)
