### ISSUE TITLE
 Fatal error: Call to undefined function redux_theme_categorized_blog() in /web/htdocs/www.vesuvionatura.it/home/sito/wp-content/themes/gocargo/404.php on line 27

### ISSUE THREAD

**Issue by 82Angelo** [reduxframework/redux-framework#3537]
Hi everyone,

i've this problem...when i go to the link for wordpress control panel login and click go after insert user and password, i receive this error: 

Fatal error: Call to undefined function redux_theme_categorized_blog() in /web/htdocs/www.vesuvionatura.it/home/sito/wp-content/themes/gocargo/404.php on line 27

Please help me because i can't entry in control panel

Thanks

**Comment by 82Angelo** [comment]
ah...i've a Multilingual website

**Comment by kprovance** [comment]
That's an error with the theme.  We did not author the theme.  You will have to go to the theme author for support.  Good luck.
