### ISSUE TITLE
How do I Display Redux framework option to individual page edit

### ISSUE THREAD

**Issue by tarifhossain** [reduxframework/redux-framework#3540]
I am trying to develop a theme where I am using Redux framework. So far its good and right now my concern is with a slider. I have create a slider option where slider image, title, subtitle and button text/link can be added for each slider. I also have the output running fine. Now I am wondering if this slider option is possible to put on individual page edit option. Meaning I would like to use separate sliders for each page or disable it if not required.

My question is, if it is possible to display these slider option (also other options if required) to the individual page edit page or its only possible to show at admin options only? its not a bug but just want to know if Redux has this option? 

Thank you

**Comment by kprovance** [comment]
You would need to purchase the premium metabox extension, and keep that subscription active for as long as your work is for sale.  There is no free solution for what you wish to do.  Good luck.
