### ISSUE TITLE
array of font weights #performance

### ISSUE THREAD

**Issue by andrejarh** [reduxframework/redux-framework#3541]
Hi 
This is a feature request, not a bug, but I decided to post the issue, because I believe a proposed solution could benefit many Redux Framework users.

Redux Typography field currently supports single font weight or all font weights ('all_styles' => true), but as far as I know it doesn't support an array of font sizes. 

This results in two possible ways of handling the fonts in Redux:
1. Make the user select the same font family with appropriate font weight for each possible use case (all headings, lead text, bold text, italic text,...) 
This can result in dozen fields for the same font-family - which is a very bad UX for the users
2. Give them one field only and load all variations, which is good for UX, but bad for the performance 

**A possibility to pass an array of font weights would thus result in better UX and better performance.**

Currently I am using the 'all_styles' => true, in the typography field to load all font sizes for the selected font. The font I use is 'Open Sans', which supports the array of font sizes {300, 400, 600, 700, 800}.  Also the user might not need the greek, greek-ext, vietnamese, cyrillic, cyrillic-ext and latin-ext variations, which I think come automatically with the 'all_styles' => true flag.

However the only font sizes I would really need are just {400, 800} along with their italics versions. 
If an array with font sizes could be passed as an option, the load of the google fonts could be about 30% or less of the current one, which would mean a substantial performance improvement for ReduxFramework users.

**Comment by kprovance** [comment]
We'll put it under considering for Redux 4.  It's a lot of work, and we are getting zero support from our community.  Maybe we'll start a gofundme.  I dunno.  We'll see.  Thanks!
