### ISSUE TITLE
Redux Typography

### ISSUE THREAD

**Issue by Demarroach** [reduxframework/redux-framework#3546]
Greetings!

Having abit of a snorkel with seeing the fonts on my Redux. I'd be grateful for some support  & advise.

![screen shot 2018-07-10 at 13 03 52](https://user-images.githubusercontent.com/41077803/42525748-f2c1aef6-8441-11e8-9ec6-ea54aebfa53c.png)

**Comment by kprovance** [comment]
Per our insructions, if you are a theme user, you must contact the theme author for support. If you are the author of the theme, then please review our posting guidelines and Supply us with the required information. Thank you
