### ISSUE TITLE
Artim Theme Copyright bunching up

### ISSUE THREAD

**Issue by CharlesSandor** [reduxframework/redux-framework#3548]
## Any Error Details (PHP/JavaScript)
OK, this is a really weird way to support a theme. I purchased the Artim theme and have an issue and the link sent me here. In the footer the copyright texts bunches up in the left. I need it to flow in one line ideally centered.

 https://hi-woodmeadowsco-op.ca/

**Comment by kprovance** [comment]
Hi.  We do not support themes that use our framework.  You will need to contact the theme author for support.  I'm not certain why they would have a link to send you to us.  Good luck.
