### ISSUE TITLE
Couldn't get_options “global $redux_option” on a Class Method

### ISSUE THREAD

**Issue by litonarefin** [reduxframework/redux-framework#3550]
I'm working on a WordPress Plugin. Plugin Options used "Redux Framework". I'm declaring my method like this-

public function my_function(){
    global $redux_option;
    echo $redux_option['my_var'];
}
I'm struggling to get Option values like this last 6 hours, but I couldn't do this anyway. Please help me to solve this problem.

Thanks

**Comment by kprovance** [comment]
There was a list of required information that we need from you in order to offer free support. Please open the new issue window and review all the texts that you deleted out before writing your issue. Within that texts the information we require. Please post all of it back
