### ISSUE TITLE
Multisite/Network-Synchronization

### ISSUE THREAD

**Issue by Gitbrainnoah** [reduxframework/redux-framework#3552]
we build a Network in Wordpress. In the Network we have two others Networks (for others languanges) in which we have multiple Pages where we display Blogs.

Now we want to Display a Theme Demo on all Network-Pages. Is there any possibility to set the Demo for the whole Networks?

Also is it Possible or does exist a Plugin that make it possible that you can duplicate Network and Page Settings for other Pages or Networks?

**Comment by davidteissier** [comment]
Hi,
What is your issue with Redux ?
Sorry i don't understand clearly.

**Comment by Tofandel** [comment]
Don't use Networks/Multisite for different languages... You should use WPML or polylang
But yeah this is not a redux framework issue..

**Comment by kprovance** [comment]
@Tofandel is correct.  This is not any way in which Redux should be used.  WPML is a better alternative.
