### ISSUE TITLE
Installing the plugin shows error messages in dashboard

### ISSUE THREAD

**Issue by ephourita** [reduxframework/redux-framework#3553]
Hello,

a theme I bought uses redux-framework. But when I install the plugin (NOT activated, just installed), the following code appears 18 times in my wordpress dashboard. I just censored the username with "mywebsite" in this case.

`Warning: file_exists(): open_basedir restriction in effect. File(/www/htdocs/mywebsite/blog/wp-content/plugins/newsgamer-addons/extensions/minify/data/js/operators_after.txt/extension_operators_after.txt.php) is not within the allowed path(s): (/www/htdocs/mywebsite/:/tmp:/usr/bin:/www/htdocs/mywebsite:/bin:/usr/local/bin:/usr/share/php:/dev/urandom) in /www/htdocs/mywebsite/blog/wp-content/plugins/redux-framework/ReduxCore/inc/class.redux_api.php on line 556`

The line says:

` if ( file_exists( $path . $folder . '/extension_' . $folder . '.php' ) ) {
                                self::checkExtensionClassFile( $opt_name, $folder, $path . $folder . '/extension_' . $folder . '.php' );
                            } else if ( is_dir( $path . $folder ) ) {
                                self::setExtensions( $opt_name, $path . $folder );
                                continue;
                            }`

When I delete the plugin from my plugin directory via FTP, it's gone.

I'm using Wordpress version 4.9.7. It would be great if you have a hint for me.

Best regards,
Sam

**Comment by kprovance** [comment]
That is not one of our extensions. We did not offer that particular extension. The author of the work probably didn't. Please contact that individual for support. Thank you
