### ISSUE TITLE
Redux conflict with WP

### ISSUE THREAD

**Issue by davindersangha** [reduxframework/redux-framework#3554]
First post on GitHub, so be kind :)

Installed Redux on my site to work with Variations Table and also Print Products. However, it's causing a conflict where the Storefront theme options don't save and also menus wouldn't save, as well as other issues such as uploading plug ins, saving WooCommerce products. 

When disabling, it all works. Any suggestions?

I'm not a developer, but writing on here as the instructions for support on the WordPress Redux section advise to post here.

**Comment by kprovance** [comment]
We do not support themes that use Redux. Please contact the theme author for support. Good luck.
