### ISSUE TITLE
Missing Dependencies js file

### ISSUE THREAD

**Issue by tinhbeng** [reduxframework/redux-framework#3558]
Hello,
I have used the Redux Framework for my theme. After I install this plugin, some fields not show. I installed the plugin jQuery Monitor and get some error.
![missing_dependencies](https://user-images.githubusercontent.com/11867289/43506073-272cdcd0-9593-11e8-80a8-a03531fb35b3.jpg)

Can someone tell me the cause of this problem?
Thanks.

**Comment by kprovance** [comment]
Looks like some files are missing?  Or the select2 CDN isn't being loaded?

What I need you to do is go back, open a new ticket window, read the text you skipped over and deleted out, and supply us with the REQUIRED information.  

Or, don;t embed Redux and just use the plugin.

**Comment by tinhbeng** [comment]
Thanks for your feedback.
I have another question: 
The Redux Framework is compatible with PHP 7.2.x version?

**Comment by kprovance** [comment]
Yes.
