### ISSUE TITLE
Update bug

### ISSUE THREAD

**Issue by easyweband** [reduxframework/redux-framework#3561]
Hi !

I need help, I made a update for this plugin and now the menu is invisible...
Where can I find a older version of the plugin ?

Thank's

**Comment by mikeanywhere1** [comment]
I am in the boat!!

I just updated the plugin and most of the site information has vanished. Can I have a copy of the earlier version of the plugin until this bug is resolved?

**Comment by easyweband** [comment]
I finded a solution, try this plugin "WP Rollback". With that, I put the older version of the plugin :)

**Comment by mikeanywhere1** [comment]
I used the rollback plugin as you metioned and it worked. everything is back to how it was before - phew!!

Thanks for that  :-)

**Comment by easyweband** [comment]
With plaisure ! It saved my site too !! :)

**Comment by Dannci** [comment]
Hey devs,

it will be something in _field_typography.php_: https://plugins.trac.wordpress.org/changeset?sfp_email=&sfph_mail=&reponame=&old=1921964%40redux-framework&new=1868478%40redux-framework&sfp_email=&sfph_mail=#file15

when I remove _opacity: 0;_ and _visibility: hidden;_  headings/texts are visible again.

Bests
Dannci

**Comment by kprovance** [comment]
Guys, instead of just saying 'ot doesn't work', could you go back, read the information provided inthe 'new issue' window and reply back with at last the support hash?  I can't even begin to try to replicate this based on this vague information.

Thanks.

**Comment by kprovance** [comment]
I see the problem.  I will need an hour or so to fix it.  Afterward I will push to wp.org and all will be well again.

**Comment by kprovance** [comment]
Version 3.6.11 has been pushed to this repo and to wp.org.  Sorry again, folks.
