### ISSUE TITLE
Suggestion: Work with Elementor

### ISSUE THREAD

**Issue by juliusgabrielalba** [reduxframework/redux-framework#3563]
Hello, I am asking if it's possible for this plugin to work with Elementor builder? We bought a theme with this plugin included and our developer struggled in keeping things up. We have to deactivate this and edit on elementor and activate again.

Hope you can help us! 

Best regards,
Juls

**Comment by kprovance** [comment]
Sounds like that is more of an issue for elementor.  I would contact the author of that plugins for theme issues.

**Comment by kprovance** [comment]
Again, this is an issue for the developer of the theme. Redux does not author themes and we are unable to support themes that use Redux.  The developer needs to work all that out as it's their theme.  If he wants to pay us to do that, we are welcome to hear a proposal.

**Comment by juliusgabrielalba** [comment]
Okay, thank you. Cheers!
