### ISSUE TITLE
Arabic signs not valid URL in text field

### ISSUE THREAD

**Issue by db-dzine** [reduxframework/redux-framework#3565]
Hi there,

created a text field with validate => URL like this:

                'id'       => 'country',
                'type'     => 'text',
                'title'    => 'Title',
                'validate' => 'url',
                'default'  => '',

When I want to enter an arabic URL like this: https://www.facebook.com/नेपाल-राएलियन-अभियान-Nepal-Raelian-Movement-780666772054671

I get a validation error: 

![bildschirmfoto 2018-08-16 um 09 23 20](https://user-images.githubusercontent.com/3169388/44194207-929e8100-a135-11e8-8342-eea708652224.png)

Maybe the validation should be UTF8 compatible?

**Comment by db-dzine** [comment]
@kprovance yes sorry:

Are you a user reporting a bug with a theme or plugin?
======================================================
- Standalone Plugin

Have a development usage question?
==================================
- No

Questions about a Redux extension?
==================================
- No



## Support Hash
- none

## Steps to reproduce
- create a text field with validate 'url'
- enter arabic URL: https://www.facebook.com/नेपाल-राएलियन-अभियान-Nepal-Raelian-Movement-780666772054671
- click on save

## Expected Behavior
- arabic url gets saved

## Actual Behavior
- error occurs, that URL is not validate

## Any Error Details (PHP/JavaScript)
See above

**Comment by kprovance** [comment]
Redux uses filter_var with the FILTER_VALIDATE_URL flag.  Obviously, PHP itself does not allow for this, which seem sodd, but, it is what it is.  I googled for an alternative.  I did not find one.  Again, if you have a proposal, submit a pull request and we'll review it.
