### ISSUE TITLE
Hi,  we are creating the free theme now for my clients, and we want to disable(not remove) some options or field for free version, that user can not change or save. does it make sense? Is it possible?  Thank you

### ISSUE THREAD

**Issue by erdanishweb** [reduxframework/redux-framework#3566]

**Comment by kprovance** [comment]
With Redux alone?  No.

**Comment by erdanishweb** [comment]
Hi there,

I mean is there any array parameter with the field which can disable the specific option?

Thank you

**Comment by kprovance** [comment]
No.  There is a 'hidden' argument that would hide a field, but that's about it.  Alternatively, you could use CSS.

**Comment by erdanishweb** [comment]
can you please share the sample code with the hidden argument for any filed? that would be great

**Comment by kprovance** [comment]
```php
'hidden' => true
```

**Comment by erdanishweb** [comment]
Thank you very much @kprovance
