### ISSUE TITLE
Plugin installation failed.

### ISSUE THREAD

**Issue by KirillSolomein** [reduxframework/redux-framework#3568]
Good afternoon, my name is Kirill Solomein, I use the Bario template for the WordPress (4.9.8) site. I have a problem that I can not solve by myself. I received a message stating that my site is required to install the Redux Option Framework, I tried to install a new plugin, but the plugin failed. Here is what I got instead:

Downloading installation package from https://downloads.wordpress.org/plugin/redux-framework.3.6.11.zip…

Unpacking the package…

Installing the plugin…

Destination folder already exists. /home/content/p3pnexwpnas13_data02/25/41909325/html/wp-content/plugins/redux-framework/

Plugin installation failed.

TGMPA v2.6.1
Return to Required Plugins Installer

Me: Can you help me find the reason why I can not install the new plugin? Do I need to contact WordPress support? Or maybe problem is that I have already using WPBakery Page Builder Version 5.5.2? Thank you for the support. Kirill at solomeinkirill@gmail.com

**Comment by dovy** [comment]
This means it's already installed. You don't need to do anything and can dismiss the installed version. OR you can delete the plugin and use TGM to install.

Good luck.
