### ISSUE TITLE
fatal error when calling wp_create_nonce in options-init.php

### ISSUE THREAD

**Issue by ARAGATO** [reduxframework/redux-framework#3570]
When calling wp_create_nonce in options-init.php I get a Fatal error: Uncaught Error: Call to undefined function wp_create_nonce()

Why is it and how to solve it?

**Comment by kprovance** [comment]
Could you supply the required information we requested, please?  If you are not the theme author, please contact the theme author for support.

**Comment by ARAGATO** [comment]
It is a plugin and not a theme. I am the plugin author.

**Comment by kprovance** [comment]
Then please return to the new issue window, read all the texts you deleted out of there, and supplies with the required information that we need to continue

**Comment by kprovance** [comment]
That particular API is inherent to Wordpress. You're attempting to call it before WordPress has completely initiated. This is not a Redux issue. Therefore we are not able to help unless you were willing to purchase premium support. Good luck.

**Comment by ARAGATO** [comment]
Ok, please close this issue and I will ask somewhere else. Thanks
