### ISSUE TITLE
Please Update Elusive Icons - it's not actually up to date...search for pinterest icon for proof

### ISSUE THREAD

**Issue by spragucm** [reduxframework/redux-framework#3574]
Are you a user reporting a bug with a theme or plugin?
======================================================
NO
	
Have a development usage question?
==================================
NO

Questions about a Redux extension?
==================================
NO

Think you found a bug?
======================
YES

Before you post, check the JavaScript!
======================================
DONE

## Steps to reproduce
1. Use the el el-pinterest icon in any menu
2. It will not show up

## Expected Behavior
The pinterest icon is in the elusive icons v2.0 pack yet not the Redux Elusive icons that also indicate they are v2.0. Consequently, I can't use the pinterest icon even though it should be possible.

## Actual Behavior
Look at expected behavior.

## Recommendation
Pull the elusive icon version 2.0 again because your 2.0 doesn't match their 2.0

**Comment by kprovance** [comment]
This should be posted to the Elusive git tracker.  Truth is, that project is about dead.
