### ISSUE TITLE
Set Defaults on theme activation 

### ISSUE THREAD

**Issue by crerem** [reduxframework/redux-framework#3576]
I'm using reduxframework in a WordPress theme (embed in theme) and i'm looking for a way to have the default values set on theme activation.

I already have the
'save_defaults'        => true,

in redux config file and defaults are set after i hit save or reset button . Is there a way to have the defaults set on theme activation ?

I know this is a not a bug , so i'm sorry if i'm posting in the wrong place.
Thank you

**Comment by kprovance** [comment]
Redux should automatically pull the default value set in the actual field array if it does not find any info in the database.  Be sure to set defaults for fields you require default information from.  Or write a centralized function to pull options.  With that you can pass a default value to the function to always return one.  Good luck.
