### ISSUE TITLE
PHP Notice: Undefined index: REMOTE_ADDR cronjob

### ISSUE THREAD

**Issue by No3x** [reduxframework/redux-framework#3577]
When a cronjob is executed via php cli the REMOTE_ADDRis not set. The redux code does not check if it is set. 
## Support Hash
irrelevant
## Steps to reproduce
Execute a cronjob with php cli
## Expected Behavior
Produces no notice
## Actual Behavior
Produces a notice 
## Any Error Details (PHP/JavaScript)
```
PHP Notice: Undefined index: REMOTE_ADDR
```
## Version
Redux 3.6.5 but also present in current master
## Issue
https://github.com/reduxframework/redux-framework/blob/0b6bc366ca3f487b5235920e9006e439995fe0be/ReduxCore/inc/class.redux_helpers.php#L69
This results in a PHP notice. 

Please see the issue of a plugin using redux https://github.com/No3x/wp-mail-logging/issues/72 for further details.

**Comment by kprovance** [comment]
Aren't those PHP constants?  I would surmise then PHP is not fully loaded?  I can add an isset to that line.  That's about it.
