### ISSUE TITLE
Where can i found the previous version of wordpress plugin ?

### ISSUE THREAD

**Issue by thomascz001** [reduxframework/redux-framework#3579]
Hi The team !

Where can i found the previous version of the redux framework plugin for Wordpress ?

I need the .zip that i can upload to my wordpress website.

I would like to roll back to the 3.6.2 version.

Indeed my theme is old and i think i have a compatibility problem. I now have a white screen for few seconds before the page loads. With the 3.6.2 version of the plugin (last installed version), i didn't have the problem.

I am developping a new version of my website that is why i can use a previous version of the plugin in the meantime.

**Comment by kprovance** [comment]
We do not archive older version of the plugin here.  You could try the Redux Framework wp.org repository.  The SVN should still have old versions.  We won;t be able to support older versions.  Good luck.

https://wordpress.org/plugins/redux-framework/
