### ISSUE TITLE
tax_query is not working in WordPress args 

### ISSUE THREAD

**Issue by afaqmca** [reduxframework/redux-framework#3580]
This is not working....
array(
                'id'       => 'abc-1',
                'type'     => 'select',
                'data'     => 'post',
                'width'   => '100%',
                'args' => array('post_type' => array('card'), 'posts_per_page'=>-1,'orderby'=> 'post_title','order'=> 'ASC', 'tax_query' => array(array('taxonomy' => 'feature','field' => 'slug','terms' => 'no-annual'))), 
                'title'    => __( 'Select Balance Transfer 1', 'cc-redux-framework' ),
                'subtitle' => __( 'No validation can be done on this field type', 'cc-redux-framework' ),
                'desc'     => __( 'This is the description field, again good for additional info.', 'cc-redux-framework' ),
            ),

and getting error below
Notice: Array to string conversion

**Comment by kprovance** [comment]
Could you please go back and open the NEW ISSUE window, read, not skip over and delete, but READ about the information we REQUIRE and post ALL OF IT, please? 

Thank you.

**Comment by kprovance** [comment]
Fixed in v.3.6.12.1, available from this repo only, at present.

**Comment by afaqmca** [comment]
Thanks , It is working 3.6.12.1 version.
but when I use "posts_per_page=>-1", It is showing all posts.

**Comment by kprovance** [comment]
That's what -1 does.  Look, all redux does is feed those arts directly into rhen WordPress api.  We don't alter that functionality at all.  For posts, we use get_posts, I believe.  Look that up in the codex to properly form your queries.
