### ISSUE TITLE
Broke website - Fatal Error - Warning Label

### ISSUE THREAD

**Issue by kendrickteamhomes** [reduxframework/redux-framework#3581]
Ive tried searching but most of the resolutions require an update of the redux framework.  any suggestions?

Fatal error: Uncaught Error: Call to private Browser::__construct() from context 'Redux_Helpers' in /home3/wah2ck0aemhq/public_html/wp-content/plugins/redux-framework/ReduxCore/inc/class.redux_helpers.php:430 Stack trace: #0 /home3/wah2ck0aemhq/public_html/wp-content/plugins/redux-framework/ReduxCore/inc/welcome/views/status_report.php(21): Redux_Helpers::compileSystemStatus(false, true) #1 /home3/wah2ck0aemhq/public_html/wp-content/plugins/redux-framework/ReduxCore/inc/welcome/welcome.php(452): require_once('/home3/wah2ck0a...') #2 /home3/wah2ck0aemhq/public_html/wp-includes/class-wp-hook.php(286): Redux_Welcome->status_screen('') #3 /home3/wah2ck0aemhq/public_html/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array) #4 /home3/wah2ck0aemhq/public_html/wp-includes/plugin.php(453): WP_Hook->do_action(Array) #5 /home3/wah2ck0aemhq/public_html/wp-admin/admin.php(224): do_action('tools_page_redu...') #6 /home3/wah2ck0aemhq/public_html/wp-admin/tools.php(10): require_once('/home3/wah2ck0a...') #7 {main} thro in /home3/wah2ck0aemhq/public_html/wp-content/plugins/redux-framework/ReduxCore/inc/class.redux_helpers.php on line 430

**Comment by kprovance** [comment]
The only one I have to to go back, reread the text provided in the new issue window and provide the required information to look into this.  An error message isn't enough.
