### ISSUE TITLE
Users that are non- administrator cannot see the fields

### ISSUE THREAD

**Issue by crerem** [reduxframework/redux-framework#3582]
Hi,
My goal is to let authors change the theme settings, and I  made the following setup

1. Redux embed in theme, all things working fine for administrator 

2. set the following permission in functions.php 
$role = get_role( 'author' );
$role->add_cap( 'manage_options' );
$role->add_cap( 'manage_categories' );
$role->add_cap( 'publish_pages' );
$role->add_cap( 'publish_posts' );
$role->add_cap( 'edit_pages' );
$role->add_cap( 'edit_posts' );
$role->add_cap( 'edit_published_posts' );
$role->add_cap( 'edit_published_pages' );

3. in admin-config.php i have 

 'page_permissions'     => 'manage_options',

and also      'permissions' => 'manage_options' for certain section (i want to give access to all sections )

The problem is that the theme options page ,is visible, is loading but the actual fields are not visible. Please see this screen capture http://prntscr.com/ky2c1x 

Thank you

**Comment by kprovance** [comment]
Please provide all info data we requested.  You can open a new issue window to refresh your memory.  These things are required.

**Comment by kprovance** [comment]
Without the required info, the only answer I can give you involves our existing documentation.

https://docs.reduxframework.com/core/fields/using-permissions/

You can set sections and/or fields with permissions different than set in the global args.

Good luck.
