### ISSUE TITLE
Redux import not working

### ISSUE THREAD

**Issue by zacholas** [reduxframework/redux-framework#3583]
Running into a strange bug -- can't seem to import redux options data, either through the url style or the file style (which is presumably just pasting the JSON string, not actually uploading a file through the media library, right)

I've tried about 10 times or so, and each time it reports as if it were a success, but nothing actually changes. However, it did work once, and I have no idea why.

I have a somewhat large compiler setup for this, I think. Wondering if that might have something to do with it. Is the import feature currently working for other sites in general?

## Support Hash
http://support.redux.io/?id=K2oTHdrArrkyLTXEB293%2B%2FGOVC42I4EsnyHXoRacTZL%2F8OyXxD477EOSzJgFV7YqMiL425XodmBUVv5q%2FOdXpQ%3D%3D

## Steps to reproduce
Go to the import/export tab (or use the setting) and try to import some data.

## Expected Behavior
All options will be updated with the imported data

## Actual Behavior
All options stay at whatever they already were

## Any Error Details (PHP/JavaScript)
No js console errors or php errors.

**Comment by zacholas** [comment]
Update: I believe the thing that makes the difference of whether or not it actually works is the location of the import/export option.

If I have the option on a tab that contains other options that are being affected by the import, it works.

But if that import option is on some other tab that's not being affected by the import, it does not work.

**Comment by zacholas** [comment]
I am the theme author, yes. The media library thing was just me making sure that's not the intended functionality, as the way the button is worded ("upload") makes it sound like it might be.

So for you, the import is working just fine?

**Comment by kprovance** [comment]
Yes, I took your config and bounced it between two different installs.  I also see you are using this plugin (https://www.wpbeaverbuilder.com/wordpress-customizer-export-import-plugin/#038;utm_medium=customizer-export&#038;utm_campaign=plugins-page).  I have to ask, are you using that?

**Comment by zacholas** [comment]
I'm not really using it, no. I just tried disabling all the plugins and running the import again and still no dice.

But if it's working for you, that's good. Maybe it's just me. I can certainly work around it for now, so no worries.

**Comment by zacholas** [comment]
Lemme know if you want me to close or if you want to still try to nut it out.

**Comment by Tofandel** [comment]
> Update: I believe the thing that makes the difference of whether or not it actually works is the location of the import/export option.
> 
> If I have the option on a tab that contains other options that are being affected by the import, it works.
> 
> But if that import option is on some other tab that's not being affected by the import, it does not work.

That would be the expected behaviour wouldn't it ?
The tab is opt_name dependant so as long as you're importing from the same opt_name it should work, else of course it won't or did I misunderstood ?

**Comment by zacholas** [comment]
I had figured the purpose of this field was to be able to import/export *all* of your redux options. (?)

**Comment by Tofandel** [comment]
Well what you need to understand is that different themes and plugins use redux and they are differencied by an opt name so the import export will only export/import the data under that opt name else you would get information you may not have wanted getting overidden

**Comment by zacholas** [comment]
Oh sorry, I think we had a miscommunication. In this instance, yes everything is within the same option name. When I said "different tabs" I was referring to difference redux sections, but still under the same opt name.

**Comment by kprovance** [comment]
It's not an opt_name issue.  I ruled that out straight away (I can see all this data via the support hash).  All I did was take the options array from this theme, plugin it into my generic install(s) and bounced it back and forth.  I fear something else is in play.  I noticed the theme was based on Genesis, which is it's own framework, and not one I have ever used.  Sometimes theme authors change things around (I could not even tell you if Genesis uses Redux).  If I get some time, I'll try using my theme (which relies heavily on Redux) and see if there is any failure there, on a real server and not my local.  It's why I've left the ticket open.

**Comment by zacholas** [comment]
Sounds good, no problem.

And as an aside, I am 99% sure Genesis does not use Redux, but can send a zip of the as well for you to check if you like; just lemme know. 

But I recognize that there are some potentially-janky things I unknowingly did with my various scripts that I'm including in my theme and such, so it very well could be just some bug in my code, or some conflict with something that I'm using.

**Comment by zacholas** [comment]
@kprovance Could you direct me to your function(s) that process the actual importing of the data and I can see if I can resolve this bug? It's not immediately clear to me where this is handled; I don't see anything in the `/redux-framework/inc/extensions/import_export/import_export` directory that sticks out to me as handling it. (But maybe I'm just not looking closely enough)

Thanks,
Zach

**Comment by kprovance** [comment]
FIrst, make sure you pull the version from this repo.  Some modifications were made.  IN the framework.php files, go to line 2548.  It's mostly there.

**Comment by zacholas** [comment]
Alright, @kprovance, I have spent a few hours banging my head against this and have finally tracked down the pesky bug. It's coming up due to the php.ini max_input_vars value. If the import field itself is further along in the redux options array than the max_input_vars key (in this case, 1000), it is ignored. And being that my "developer settings" tab with the import field is at the end of my options panel, this is bound to happen.

I found this bug by going panel-by-panel, option-by-option, to try to find where exactly the breakage was happening, and then learned that if it was after/before some field on one of my panels halfway down the list, it would either work or not.

The two workarounds I've found are to either place the import field earlier on in my options settings or require people to change their php.ini. The former's not ideal, but not a big deal, as it's obviously far better than the latter.

It's worth noting that as long as the import field _is_ earlier than that max_input_vars index, I *can confirm* that it imports *all* values, even beyond the max_input_vars limit. This is presumably because once the import is executed, it's combing through one single posted json array, rather than a bunch of different $_POST fields.

I don't have a lot of experience working with posting large arrays, but my only thought for a "real fix" to this, rather than me just moving this field earlier in my code as a workaround, would be to post all these values as one json_encode'd array, rather than as individual $_POST array keys. Then at that point, the only concern would be the upload max file size limit. However, I believe this would be preferable, since php sites explode and throw an error when that happens, so you at least know it's happening, whereas this just sort of silently truncates the array in the background. So up to you whether or not you want to fix it, but at least I know a workaround that I'll be implementing into my own project.

Let me know if you want any more detail.

**Comment by kprovance** [comment]
It may be something I can work on for Redux 4.  Don;t know how much of a rewrite it will take until I study it.  As time and funding are an issue, I can offer no ETA.

Have you tried something like:  ```php @ini_set('max_input_vars', '3000'); ``` in your functions.php?

**Comment by kprovance** [comment]
Okay, I had this crazy idea that since input_vars are an issue, and our ajax save fixes that, that maybe I could move the import functionality to that same function.  I do believe I have it working.  Well, it work in my demo and whatnot, but those do not exceed max_input_vars.

Please try the following:

Download version 3.6.12.3 from this repo and install it however you have Redux installed.  Using the same conditions in which the import failed, run it again with this version and see if they take this time.  It only uses a handful of input_vars and a json string for the import values.

Please let me know ASAP.  Thanks!

**Comment by kprovance** [comment]
Did you get a chance to try this?  I'm waitin' on you at this point before I push this to wp.org

**Comment by zacholas** [comment]
Hey @kprovance, nice job, it worked! You can cross-check it by adding this to your .htaccess: `php_value max_input_vars 100`

But I'm guessing you already did that since it looks like this is on master now.

So what did you change? You're posting the json array with ajax now?

Thanks for resolving this Kevin. When are you guys looking at for Redux 4 release?

**Comment by kprovance** [comment]
Okay, so Redux, by default, uses an ajax save on the actual option panel, instead of the page sending any input data via POST.  A few years back people began reporting they were unable to save all their settings because they blew the max_input_var limit.  The typography field chews those up pretty quickly.  Dovy came up with the axjas save, which basically posts all the option data in a json string and then decodes it via callback, and saves to the database there.  It uses a whopping 4 vars via post.  Ajax action, the nonce for security, the opt_name for the panel and the data string with all the options.

As you know, the import function took the entire array of input variables from the option panel, plus added yet another var for the import string, which was just a json string of the same data.  Redundant, right?  I think - based on how the code was written - import was excluded from ajax save either because it wasn;t finished, or it was a todo.  I'm not sure.  I just finished it.  Didn't take nearly as long as I thought it would.

Anyways, I am thrilled it worked out.  I will bundle this build up and push it to wp.org later on tonight.

As for version 4...<sigh> I keep saying soon, but it never seems to happen due to time and not enough people donating to us.  I was working on a GoFundMe page and got sidetracked.  I should finish that.  We have a private beta going on, as @Tofandel can attest to.  If you want in, send Dovy as email at dovy@reduxframework.com, tell him I sent you.  He'll ass you as soon as he can (I'd do it, but it's his private repo).   If you decide to play with it, please, please, please do not use it in production yet.  ;-)

Cheers!

**Comment by zacholas** [comment]
@kprovance ahhh, gotcha. Awesome. In my theme, I've incorporated some "variable typography" fields where people can choose between typekit, google, or inheriting from another component, and a similar thing with variable backgrounds -- doesn't take too many of those to suck up 1000 post vars, ha. That's fantastic that you were able to implement so quickly. So far it's been working great for me but I'll let you guys know if I manage to find a way to break it again.

@dovy thanks so much for the invite.

I think I am on your mailing list to hear about updates to v4, but in case I'm not, what's the best place for me to opt in to get notified if you end up launching a gofundme so that I can contribute?

**Comment by kprovance** [comment]
Meh.  The signup form on the site is down.  Something else to fix.  If you want, I can add your name email manually.  When I get the GoFundMe thing finished, I'll make an announcement.  Both mail list and blog post  :)

**Comment by zacholas** [comment]
Sure, I sent you an email with my email.
