### ISSUE TITLE
EmallShop theme setting. question

### ISSUE THREAD

**Issue by innokims** [reduxframework/redux-framework#3591]
EmallShop theme setting. question

1. When I am using EmallShop v2.0.12, I can not see the input box for color code in the color change option of the theme options suddenly. How can I use the input box again? How can I solve it? Thank you for your reply, in advance.
2. Category Products With Tab-->Name/Title With Products How to change the tab title name in Tap

Please refer to attached file and we will wait for answer.
Thank you.
[Reference file.zip](https://github.com/reduxframework/redux-framework/files/2509150/Reference.file.zip)

**Comment by kprovance** [comment]
We are not the author of this product.  Please contact them directly  for support.
