### ISSUE TITLE
redux-group-tab not hiding

### ISSUE THREAD

**Issue by crerem** [reduxframework/redux-framework#3592]
Hi,
I have installed redux framework on a theme and everything works well on all installations except one. What's happening is that sections div in admin are not hiding when you click on submenu. 
Unfortunately this is on a client website so i cannot provide more details. This is a screen capture of in Dev Tools : http://prntscr.com/laooa7  - you can see several sections keeping the style display block.

Can you give me a hint for debug ? Again this is happening only on a single client website (works fine on 100+). All plugins are disabled and there are no errors in php or js console.

Thank you

**Comment by kprovance** [comment]
Are you the theme author or did you purchase a theme that uses redux?

**Comment by crerem** [comment]
I'm the theme author.

**Comment by kprovance** [comment]
Then you should have read the block of text we provided in the the new issue window that explained the information we need.  Please review that again and post back that information.  Thanks.

**Comment by crerem** [comment]
In the end it seems that the client had a bad WordPress install . Thank you for your help.
