### ISSUE TITLE
Error Blank Page

### ISSUE THREAD

**Issue by MarcosHC90** [reduxframework/redux-framework#3596]
Hi, first, congratulations for ur plugin, its nice! I buy many themes with your plugin integrate but I detected error in all, when I desactivate your plugin its all ok. In server Linux when active option "LESS COMPILER" its fix, but in server Windows always fail. The problem is when you click or load any page, its show a flash blank page for many seconds. 
The autor theme say me contact with you. I read in your terms then I need pay you for support. Can you help me and say me the cost? Thank you very much

## Support Hash
I cant get the support hash. 

## Steps to reproduce
when you click or load any page, its show a flash blank page for many seconds

## Expected Behavior
No show flash blank page

## Actual Behavior
Show flash blank page

## Any Error Details (PHP/JavaScript)
The JavaScript console show: "Active resource loading counts reached to a per-frame limit while the tab is in background. Network requests will be delayed until a previous loading finishes, or the tab is foregrounded. See <URL> for more details "

## Other
I have the last version plugin.
Im using too WP-Rocket for optimization speed with minification Javascript, but when desactivate this plugin its same (i think it no affect)

**Comment by kprovance** [comment]
Redux does not use a less compiler.  That would be part of the theme?  It really is the responsibility of the theme author to support Thier work and not push support off onto vendors.  May I have Thier name and where I may find where they sell Thier theme?

**Comment by MarcosHC90** [comment]
Thanks for your fast response. The error may not be produced by less compiler. Could you check it? The name of theme is Ogani, author roadthemes, you can buy in envato/themeforest. Thanks

**Comment by kprovance** [comment]
I don't believe I've made myself clear here. We do not support themes that use Redux. It is responsibility of the theme offer to support their own product. If they discover a problem with Redux they come to us and we work with them. I will not download somebody else's steam to check for an error in their theme. That is not what we do here. If the theme author will not support you as he is supposed to do, I will contact him directly at envato or leave a comment on his page and ask him why he is not supporting his own product. It is his job to debug any issues that you may have. For me to do it would cost you several hundred dollars in minimum
