### ISSUE TITLE
Manual "compile" button

### ISSUE THREAD

**Issue by zacholas** [reduxframework/redux-framework#3597]
I am pretty sure this falls outside the scope of what I'm allowed to ask here, so I'll keep it short.

I was curious if anyone has any ideas on how I might add a "compile" button to a redux panel that I can click to fire the compiler? Right now I just change some arbitrary option value to do it, but it's a bit tedious. Is this maybe doable with the "js button" extension?

@kprovance / @dovy if you see this as clutter / unsupported, feel free to just close it and I'll continue as I have been.

**Comment by kprovance** [comment]
Unfortunately, no.  The compiler was designed to run on save, and only when values were changed.  Even if a save click could be simulated, there would have to be a change in the fields where the compiler arg when specified.

Is this about CSS output or something more in depth?

**Comment by zacholas** [comment]
Ok no worries. It's about SCSS compilation specifically. The way I'm using my redux compiler implementation is to trigger the leafo scssphp compiler, and set vars based on redux options. But what this means is that if I change one of my local scss files and upload it, I have to go change some value in my redux panel to trigger the compiler again, and I just thought it'd be nifty to have a manual compiler button. But it sounds like it may be more trouble than it's worth, so no worries. :)
