### ISSUE TITLE
Redux Framework Custom Rest Api / Export

### ISSUE THREAD

**Issue by onuravci** [reduxframework/redux-framework#3598]
I want to learn how I can change this export link to custom?

`wp-admin/admin-ajax.php?action=redux_download_options-custom&secret=c232a146b76ca2976c6a7a345f3c7432
`
Like :

`wp-admin/admin-ajax.php?action=redux_download_options-custom&secret=custom_export
`
I need to see what they change something for mobile apps.

Thanks for helping me ;)

**Comment by kprovance** [comment]
You'd have to clone the import_export folder in ReduxCore/inc/extensions, install it someplace outside the plugin (or the changes get lost on update).  You then edit the php however you like.  Be careful not to change any of the original class names or ids, otherwise the javascript will break, and then you'd have to update that too.

Good luck.

**Comment by onuravci** [comment]
Thank for answer @kprovance it works now ;)

extentions_import_export.php
change md5 checks to "custom_export_uri"

`
            function link_options() {
                if ( ! isset( $_GET['secret'] ) || $_GET['secret'] != 'custom_export_uri' ) {
                    wp_die( 'Invalid Secret for options use' );
                    exit;
                }

                $var                 = $this->parent->options;
                $var['redux-backup'] = '1';
                if ( isset( $var['REDUX_imported'] ) ) {
                    unset( $var['REDUX_imported'] );
                }

                echo json_encode( $var );

                die();
            }

            public function download_options() {
                if ( ! isset( $_GET['secret'] ) || $_GET['secret'] != 'custom_export_uri' ) {
                    wp_die( 'Invalid Secret for options use' );
                    exit;
                }`

Then "field_import_export.php" line 74
`
            public function render() {

                $secret = 'custom_export_uri';`

> admin-ajax.php?action=redux_download_options-wport&secret=custom_export_uri

Thanks for help ;)

**Comment by kprovance** [comment]
Not sure removing security is a good idea.  You are on your own as far as the core goes now.  We do not support modified cores.  Good luck.
