### ISSUE TITLE
Redux Version:3.6.14   Ajax Saving

### ISSUE THREAD

**Issue by GoSheng** [reduxframework/redux-framework#3599]
How is Ajax Saving introduced in version 3.6.14? Is it the option to save the settings? Or save settings via ajax?

**Comment by kprovance** [comment]
It's built into the core.  Redux is a developers tool.  It's not a user tool.  If you are designing a theme or the like and wish to use Redux to create your option panel, I suggest reviewing the sample-config.php included with the package, or review our docs site:  http://docs.reduxframework.com.  A more than novice knowledge of PHP is required.

**Comment by dovy** [comment]
We also have this doc that may help.  ;)

https://docs.reduxframework.com/core/advanced/adding-another-icon-web-font-to-the-panel/

**Comment by GoSheng** [comment]
> It's built into the core. Redux is a developers tool. It's not a user tool. If you are designing a theme or the like and wish to use Redux to create your option panel, I suggest reviewing the sample-config.php included with the package, or review our docs site: http://docs.reduxframework.com. A more than novice knowledge of PHP is required.

I am a theme developer, I have used reduxframework for a while, the save option is always through the button, and the button will be used to determine the save option, right?

**Comment by kprovance** [comment]
Yes, one must click the save button to save changes options.

**Comment by GoSheng** [comment]
> We also have this doc that may help. ;)
> 
> https://docs.reduxframework.com/core/advanced/adding-another-icon-web-font-to-the-panel/

Why do I use Font Awesome 5.5 and don't show the correct icon? It’s weird, can you only use the 4.x series?

**Comment by kprovance** [comment]
I don't know.  I don't use FA 5.x.  I'm sure there is a way, but it's wading into premium support territory as it's not inherently a Redux core issue and more of a vendor issue.
