### ISSUE TITLE
Showing an image inside a hint tooltip

### ISSUE THREAD

**Issue by codeminelab** [reduxframework/redux-framework#3600]
Hi. Is it possible to show an image inside a hint tooltip?

**Comment by kprovance** [comment]
We use the qtip library for the hint feature.  I believe they do allow for HTML markup.  You would have to write your own HTML and CSS for proper positioning in the hint content argument

**Comment by codeminelab** [comment]
Thank you. Got it working. Like this:

    'hint' => array(
                     'content' => "<img src=".IMG_PATH."assets/admin/img/TEST.jpeg'>",
                ),

**Comment by kprovance** [comment]
Exactly!  Cheers!  Good luck.
