### ISSUE TITLE
Wordpress plugin blocks menu sections

### ISSUE THREAD

**Issue by faitdumal** [reduxframework/redux-framework#3603]
After installing the latest plugin, I am no longer able to access "installed plugins". Clicking on the respective menu link leads me to the tools/redux framework instead.

**Comment by faitdumal** [comment]
Yes, it's a new install. So, you are saying I'll have to delete it manually and won't be able to use it until some future version fixes the issue?

**Comment by kprovance** [comment]
No, that's not what I am saying.  Please read my last replay and answer those questions, please.

**Comment by faitdumal** [comment]
Apologies, I am not clear on which questions you are referring to. As mentioned, it only happens when I click on "Installed Plugins" and it's a new install. I am not sure what other questions you are referring to. You indicated the link would only pertain to redirects from any link... Can you clarify, please?

**Comment by kprovance** [comment]
As indicated, the About window will appear once on a new install.  Now, when you click on other links in the admin menu...pages, post, anything, does that window still appear?  Have you seen it since?

**Comment by faitdumal** [comment]
I am no longer to enter the "Installed Plugins" section at all. It will redirect every time I click on that link. However, it will not happen when I click on other menu items.

**Comment by kprovance** [comment]
Then please click the hyperlink I supplied earlier, read all the ext carefully, and provide the information I require.  Thanks.

**Comment by faitdumal** [comment]
Will do. thanks

**Comment by faitdumal** [comment]
## Support Hash
http://support.redux.io/?id=ojlquMfL%2BmY9ZIp3ybf5tm7a4D8Xxx0QgWfXoOhkZRQyoQpi2P1X%2BK2A3Rg8ps386CpC%2BgrnRQ%2FhRWhpo%2FbDkQ%3D%3D


## Steps to reproduce
Install & Activate Redux, click on Plugins/Installed Plugin, arrive on Tools/Redux instead of on Installed Plugins

## Expected Behavior
I expect to arrive on Installed Plugins when clicking said menu link

## Actual Behavior
Page redirects to tools/redux when clicking on Installed Plugins menu item

## Any Error Details (PHP/JavaScript)
None. It's a redirect.

**Comment by kprovance** [comment]
Are you the author of this this theme?

**Comment by faitdumal** [comment]
No, I am a just user

**Comment by kprovance** [comment]
Ah, ok.  I need to refer back to this in the text I asked you to review:

> Redux is a tool for developers to include an options panel in their project. Consequently, we do not offer support for folks who have purchased a theme or plugin that uses Redux. The responsibility of support for themes and plugins falls upon it's author. We realize that some authors have included support links for Redux in their projects, when they should not have. We do apologize for that confusion and are taking steps to remedy this confusion. 

> If you have purchased a theme or plugin that utilizes Redux, please contact the author for support. If the author is unavailable for support or has discontinued support, please refer to this before posting to our issue tracker: https://docs.reduxframework.com/core/support-defined/

The reason we have to do this is because there are a multitude of different way in which a theme author could use Redux, or hook into it, and that's not something I am able to investigate.  If the author determines it's an actual Redux issue, then they would come to use with all the pertinent information and we'd go from there.  Good luck.
