### ISSUE TITLE
I bought a premium support tickets, but don't know ask support.

### ISSUE THREAD

**Issue by k-kikuchi-idea-hack** [reduxframework/redux-framework#3604]
Dear Redux team.

My name is kazuki, and I bought a premium support ticket for getting support of my plugin development using redux builder.
I bought a ticket and clicked "shortcodes-1.0.2" button, but it showed an error page, which "You must have an active subscription to Shortcodes in order to download this file." was written in.

I also need a help about how to get a support now.

King Regards

KAZUKI KIKUCHI

**Comment by kprovance** [comment]
You may ask me, via email if you prefer kevin@reduxframework.com.  Please remember, it's for an uninterrupted hour of time.  It's not cart blanch.

**Comment by kprovance** [comment]
Resolved via email.  Thanks!
