### ISSUE TITLE
Add custom extention to WP customizer

### ISSUE THREAD

**Issue by MohamAladham** [reduxframework/redux-framework#3606]
Hi

Thank you for this GREAT work.

I need your help, I have created a custom extension, it's simply a copy of the TEXT field but added some js, css and html.

Now, I'm trying to add it to WordPress Customizer.

Please let me know if something is missed or what should I do in order to have it added to the customizer.

Thank you

**Comment by kprovance** [comment]
Please post customizer issues here:  https://github.com/reduxframework/customizer-integration/issues

FYI, Redux's basic core customizer does not load extensions of any sort.  You'd pretty much have to come up with your own integration for the time being.  Eventually we'll have an extension to handle all customizer fields, but there is no ETA on that.
