### ISSUE TITLE
Continued development

### ISSUE THREAD

**Issue by Alex77ru** [reduxframework/redux-framework#3607]
Hello!

I purchased a theme template built with your product.

It turned out that the developer has invested a minimum of functions for settings.

When contacting the developer, I received the answer that it is impossible to make additional fields in the settings.

I need to add fields to the settings and finish this project.

I am ready to purchase premium modules for self-completion of work, which the developer did not share.

Tell me, is it possible?

Thank!

**Comment by kprovance** [comment]
Anything is possible, it all depends on how much money you have and are willing to devote.  We are $100.00 an hour.  While the adding of fields to your option array could probably be done in that span (depending on how many there are and how specific you are in your proposal), if you are also looking for code to be written to use those options on the front end, then yes, it can get expensive as that ventures into theme development.  It's up to you.  Feel free to contact me via email for a more accurate quote, but I will need you to be very specific about the work you want done.  kevin@reduxframework.com

Thanks!
