### ISSUE TITLE
Post Category Bug

### ISSUE THREAD

**Issue by James-Odinson** [reduxframework/redux-framework#3609]
## Support Hash
http://support.redux.io/?id=K30ch6MM49KaDY41xT9FJXlURYJYq2s2csUrayyumN82eACrsmZ%2FIf67IbHcQ8EyNG9HTVrVge1K9BOU2wpY%2BA%3D%3D
## Steps to reproduce
When the Redux framework is activated with the consultix theme, all posts appear in EVERY category, no matter which category they are assigned to. The problem disappears when the Redux framework plugin is deactivated.
## Expected Behavior
Posts only appear in their own category
## Actual Behavior
Posts appear in every category
## Any Error Details (PHP/JavaScript)
No errors

**Comment by kprovance** [comment]
You need to contact the theme author for support.  We do not support users of themes that use our framework.  This was stated very clearly in the new issue screen.  Good luck.
