### ISSUE TITLE
Which Redux fields aren't supported inside WP Customizer

### ISSUE THREAD

**Issue by kiarashi** [reduxframework/redux-framework#3610]
Not so much an issue but more a question;

Could it be some redux fields aren't supported inside WP Customizer? Such as background, dimensions, or spacing?
Any news on Redux Pro (4.0)? ;)

Kind regards, 
Kiarashi

**Comment by kprovance** [comment]
Here are the supported fields:  checkbox, color, color_rgba, media, spinner, palette, button_set, image_Select, radio, select, gallery, slider, sortable, switch, text and textarea.  Everything else comes later on in whatever form our premium product is going to take.

News on Redux v4 is coming before the week is out.  I'm launching a GoFundMe to get this thing finished. Announcement via blog, mailing list and social media to come.
