### ISSUE TITLE
conflict with redux plugin

### ISSUE THREAD

**Issue by vollmerag** [reduxframework/redux-framework#3611]
After updating Redux Framework, warnings started to appear on my site. Are you aware of this problem and can it be resolved. 

Warning: Invalid argument supplied for foreach() in /home/vollmera/public_html/wp-content/plugins/redux-framework/ReduxCore/inc/fields/typography/field_typography.php on line 930

Warning: array_change_key_case() expects parameter 1 to be array, string given in /home/vollmera/public_html/wp-content/plugins/redux-framework/ReduxCore/inc/fields/typography/field_typography.php on line 824

Warning: Invalid argument supplied for foreach() in /home/vollmera/public_html/wp-content/plugins/redux-framework/ReduxCore/inc/fields/typography/field_typography.php on line 825

**Comment by kprovance** [comment]
As I said in the other thread you posted, you need to contact the author of your theme for support.  We do not support users of themes that use our software.  Out of 700, 000+ active insalls, this has not been a reported issue.   The author of the theme must determine why this is happening and file a properly written report with us.
