### ISSUE TITLE
Forcing https to avoid https security issues on static generated sites

### ISSUE THREAD

**Issue by fpworks** [reduxframework/redux-framework#3612]
_Originally posted by @dovy in https://github.com/reduxframework/redux-framework/issues/2051#issuecomment-74570145_

How to force https:// on redux generated /head link for google fonts in case site is exported to static html?

**Comment by kprovance** [comment]
It can't.  Redux detects if SSL is in use and modifies the protocol based on that.   Honestly, I'm not sure why were still doing that.  Seems antiquated.  I'll look into seeing if there are any side effects of doing https regardless.
