### ISSUE TITLE
Dynamic Alerts and Messages

### ISSUE THREAD

**Issue by lhoucinecherif** [reduxframework/redux-framework#3613]
Hi,
Thank you for this amazing great framework.
Am wondering how to add some alerts or message'boxes after or before a concerned field!
Its like the validation process, but it doesn't validate anything,  just shows  a response from the server !! I've spent hours searching for a solution, ( without using session or a get param ) !  there is not clear documentation about this behavior! using errors/notices hooks needs validation

In clear how can I show message box or alert or even a raw text above or aside  of a "switch field" , after saving !!! (one time , like flash messages in Laravel)  

Thank you!

===============
Wordpress: v4.9.8
Redux framework: v3.6.15
PHP: 7.1

**Comment by kprovance** [comment]
Without the required information as request in the 'new issues' window, there isn't much I can offer besides the following:

IN as far as our validation schemes go, no, there is no way to display any type of alert popup.  Depending on the validation (which was not specified), an error message can be displayed beneath the field in question by adding a ```msg'`` argument to the field in question.  Without more information, I cannot offer any other suggestion.  Good luck.
