### ISSUE TITLE
Redux Error for Woocommerce Variations Atribuites

### ISSUE THREAD

**Issue by catistudio** [reduxframework/redux-framework#3617]
My website is takunyalar.com i disabled redux to problem solved but theme dont functional work.

Please test https://takunyalar.com/urunlerimiz/abel-haki-hakiki-deri-bot/ select shoe number. Select to reload page, normally select to javascript work. Whats problem redux?

Please help me.

**Comment by kprovance** [comment]
Sir, I have addressed this with you twice now.  It is a conflict of the select2 library with WooCommerce who updated theirs, which began this issue some time back.  It is not as simple as just upgrading our version as there are appreciable code rewrites involved.  As I have also said before, this issue will be solved in Redux 4.  Hopefully there will be a public beta in the beginning of the new year for folks to try.  That's all I can tell you at this time.  It's also worth noting that your theme author will have to make those upgrades if they are using an embedded version.  So even when our beta become available, it will be the theme authors responsibility to make those changes as do do not and are not able to support theme users directly.
