### ISSUE TITLE
Typography doesn't set default values for options that are false by default, but set to true

### ISSUE THREAD

**Issue by FlippFlopps** [reduxframework/redux-framework#3619]
## Steps to reproduce
Define any typography field, 
set 'text-transform' Argument to TRUE (or any other argument that is FALSE by default)
set 'text-transform' default option to 'uppercase'
set 'output' to array( 'h1, h2' ),
in the admin panel, DO NOT touch the 'Text Transform' field.
Check the outputted CSS in the front end, the 'text-transform' property isn't there.

## Expected Behavior
In the admin panel, the 'Text Transform' field should be set to 'Uppercase' BY DEFAULT
Outputted CSS should be
h1, h2 {text-transform: uppercase;}

## Actual Behavior
In the admin panel, the 'Text Transform' field remains unset.
Outputted CSS
h1, h2 {}

## Any Error Details (PHP/JavaScript)
No errors

**Comment by FlippFlopps** [comment]
http://support.redux.io/?id=CJH6YCcNBgVIsRka0g9QW5bD62K74lM29b0QTirSxddUnkGk2B7rd57uXb9smXq4OG19I88dOSXKRG4NXjGIhQ%3D%3D

**Comment by FlippFlopps** [comment]
UPDATE:
To reproduce the issue:

1. Create a typography field (as described above) but WITHOUT 'text-transform' Argument even defined. 
2. Open Admin
3. Go back to creating the field and then add 'text-transform' => true, and 'text-transform' => 'uppercase',

The bug was a bit more complex to reproduce because, if defined straight away perfectly, it WILL output the default values. But, if you were to create a typography field and, later on, set any argument which was false by default to true (and set its option to something), that option in the admin will stay grayed out and will not be outputted.

**Comment by kprovance** [comment]
Honestly, I'm not sure this is something than can be dealt with at the code level.  Once defaults are set, changing them will require a reset of the option panel.  Users will not change their defaults, as most don't code.  The product you ship should be the product intended.  I'll take a look at it, but I can't guarantee this is something than can be compensated for.  Changing options after a product launch is a very small use case scenario.  Since this is free software we basically update for free, the amount of time to rewrite such a thing for a few cases out of thousands may not be cost effective.  

After you make panel changes, reset your panel.

**Comment by kprovance** [comment]
I looked it over.  I would try setting this argument to false:  https://docs.reduxframework.com/core/arguments/#save_defaults.  You'll have to reset your panel again to clear the database.

**Comment by FlippFlopps** [comment]
I'm yet to try your suggestion with save_defaults and reset. Meanwhile:

[SOLUTION] 
I "patched" it by changing the IDs of fields that were impacted by this issue, and then setting up every field to its final state from the start (which messed up my neat field ID naming convention but that's not a burning issue since I only had a couple of hundred of fields).

Solution example:

If setting a field argument, that was false by default, to true:

e.g. 'text-transform' => 'true'

Immediately assign a default value to it:

e.g. 'text-transform' => 'uppercase' (otherwise, defining it later on will not output the value)

In case you didn't specify the default value right away:

1. Change the field's ID
2. Specify the default value before saving your file (or before refreshing the admin panel in WP)
3. Update the ID in other files as well (if you used this option manually, e.g. not only through 'output'), "replace in all documents" is the quickest way unless it was a generic ID name like h2, then you're stuck with manual updating.

I guess no developer sets all the fields to exactly what they want when building the theme options with redux (especially if using redux for the first time). We build it and try things out before we decide what's best. Many other guys might run into this issue while developing and I hope this will help.

Thanks again for replying so fast.
