### ISSUE TITLE
Update an option outside the options panel? 

### ISSUE THREAD

**Issue by thimfy** [reduxframework/redux-framework#3620]
Not found this code in current redux config to update option from URL
Replace this line:
new Redux_Framework_sample_config();

with these lines:
global $sampleReduxFramework;
$sampleReduxFramework = new Redux_Framework_sample_config();

**Comment by kprovance** [comment]
This is from a very outdated and no longer supported version of Redux.  Please use the sample-config.php from the lastest version's 'sample' folder.  Thanks.

**Comment by thimfy** [comment]
I thinks you should updated documents for non frindly redux users.

**Comment by kprovance** [comment]
Thanks for the advice.  I will see what I can do for you.

As explained above, the way you are attempting to use is antiquated.  it was replaced with the Redux API (https://docs.reduxframework.com/core/redux-api).  I have no examples of how it was done years ago.  Sorry.

**Comment by thimfy** [comment]
Ok, thanks, do you think that your documentation should be update as they are 4 year old?

**Comment by kprovance** [comment]
I understand.  One one pays us to do any of this.  It's spare time we give.  I think there was a plan for move the docs to git, but I don;t know what's going on with that anymore.  I have the v4 beta to complete.    If you'd like to donate, I can give you a link.  :)

**Comment by thimfy** [comment]
We have link and my partner already donate, what is possible from our side.
