### ISSUE TITLE
CSS Error 

### ISSUE THREAD

**Issue by Bkauffman25** [reduxframework/redux-framework#3621]
Warning: A non-numeric value encountered in /home/noexcu09/public_html/MSTV/wp-content/themes/dazimaxx/inc/inline-css.php on line 106

That is the error I am getting when I activate the framework on my wordpress theme.

**Comment by kprovance** [comment]
You need to contact your theme author with this.  It's not part of Redux.  We did not author your theme and we have no way of knowing how the author integrated Redux.  Good luck.
