### ISSUE TITLE
Status Error / Not Writable

### ISSUE THREAD

**Issue by Bkauffman25** [reduxframework/redux-framework#3622]
Is this something that I can get some help with?

Redux Data Directory Writable:

 | [?] | ✕ To allow data saving, make /home/noexcu09/public_html/MSTV/wp-content/uploads/redux/writable.

It isn't allowing the file to be writable for some reason.

**Comment by kprovance** [comment]
As I explained in a different ticket, we do not support users of themes that use Redux.  That is the responsibility of the theme author.   Any issues with the theme and your server configuration is their area to support.  If your theme author discovers the issue to be within Redux, then they need to file a ticket with us.  Good luck.
