### ISSUE TITLE
validate_callback triggers even though field is not visible

### ISSUE THREAD

**Issue by hnkumar** [reduxframework/redux-framework#3623]
## Support Hash
http://support.redux.io/?id=%2BKSH1WYMmFmvXJnmAUlLgNEmVZzuzpN8W95YqtZhlPmBxSM7%2FG%2F7f9iPMqv7StDVJyRsCkrQaK4TZmb9vwYEdA%3D%3D

## Steps to reproduce
/* For Mail function */
Redux::setSection("essentials", array(
    'id' => 'essentials_mail',
    'title' => 'Mail Configuration',
    'icon'  => 'el el-envelope',
    'fields' => array(
        array(
            'id' => 'mail-enable',
            'type' => 'switch',
            'title' => 'Disable all WP Mail activities?',
            'default' => true,
        ),
        array(
            'id' => 'mail-custom',
            'type' => 'switch',
            'title' => 'Enable custom SMTP Server option',
            'default' => false,
        ),
        array(
            'id' => 'mail-customip',
            'type' => 'text',
            'title' => 'Enter SMTP Server IP or Address',
            'default' => '',
            'validate_callback' => 'validation',
            'required' => array('mail-custom', 'equals', '1'),
            'rules' =>'required|iporaddress',
            'optname' => 'essentials',
            'dependid' => 'mail-custom',
        ),
        array(
            'id' => 'mail-customport',
            'type' => 'text',
            'title' => 'Enter SMTP Server Port Number',
            'default' => '25',
            'required' => array('mail-custom', 'equals', '1'),
            'validate_callback' => 'validation',
            'optname' => 'essentials',
            'dependid' => 'mail-custom',
            'rules' =>'required|numeric|min_numeric,20|max_numeric,49000',
        ),
        array(
            'id' => 'mail-customsrvtype',
            'type' => 'select',
            'title' => 'Select server security type',
            'options' => array('' => 'None', 'ssl' => 'SSL', 'tls' => 'TLS'),
            'default' => 'None',
            'required' => array('mail-custom', 'equals', '1')
        ),
        array(
            'id' => 'mail-authentication',
            'type' => 'switch',
            'title' => 'SMTP required authenticatoin?',
            'default' => 'false',
            'required' => array('mail-custom', 'equals', '1')
        ),
        array(
            'id' => 'mail-creduser',
            'type' => 'text',
            'title' => 'SMTP Account User Name',
            'default' => '',
            'optname' => 'essentials',
            'dependid' => 'mail-authentication',
            'placeholder' => 'enter username',
            'validate_callback' => 'validation',
            'rules' =>'required|min_len,3|max_len,40',
            'required' => array('mail-authentication', 'equals', '1')
        ),
        array(
            'id' => 'mail-credpwd',
            'type' => 'password',
            'username' => false,
            'optname' => 'essentials',
            'dependid' => 'mail-authentication',
            'title' => 'SMTP Account Password',
            'validate_callback' => 'validation',
            'rules' =>'required|min_len,3|max_len,30',
            'required' => array('mail-authentication', 'equals', '1')
        ),

    )
));

## Expected Behavior
Callback should happen only when field is visible and required conditions met.

## Actual Behavior
Callback for specific field is triggered even though field is not visible.

## Any Error Details (PHP/JavaScript)
No

**Comment by kprovance** [comment]
I don't believe there is a way to detect when a field is visible or not to filter out that call, even in core PHP code.  Technically, it could be done with Javascript, detecting hidden fields, but then the validate call becomes an AJAX issue.  That would be a custom code project and not something we would be able to put into the core.  Sorry.
