### ISSUE TITLE
Sorry, you are not allowed to access this page.

### ISSUE THREAD

**Issue by dhmusman** [reduxframework/redux-framework#3624]
Hi i am not able to visit the given below link, I think redux framework plugin is deactivate in build site. 

https://build.reduxframework.com/wp-admin/admin.php?page=_options

**Comment by kprovance** [comment]
The builder is not working correctly right now.  I can't give you an ETA when that will be fixed.  Sorry.

**Comment by kprovance** [comment]
Okay.  I think I got it.  Give it a try now.
