### ISSUE TITLE
Is their a way to expose options to a REST API endpoint?

### ISSUE THREAD

**Issue by joshbedo** [reduxframework/redux-framework#3626]
Wondering if there is a way to expose redux theme options through an API endpoint? I'm using VueJS on the frontend so i'm pulling data through endpoints.

Thanks in advance!

**Comment by kprovance** [comment]
I'm not familiar with VueJS, so I'm not sure if this helps:  We have the Redux API.  It's a static class.  It exposes these:  https://docs.reduxframework.com/core/redux-api/

Two are not listed for some reason, and are the ones you probably want:

`Redux::getOption( $opt_name = "", $key = "" );'

and

'Redux::setOption( $opt_name = "", $key = "", $option = "" );'

Good luck!
