### ISSUE TITLE
Javascript is not loaded in the correct order

### ISSUE THREAD

**Issue by hitech95** [reduxframework/redux-framework#3631]
Hi,
I'm not sure if the problem have been discovered by someone else but i'm having a strange behaviour with redux. 

The Javascript import order on the HTML page is:
```
<script type='text/javascript' src='http://one.wordpress.test/wp-content/plugins/redux-framework/ReduxCore/inc/extensions/options_object/options_object/field_options_object.js'></script>
<script type='text/javascript' src='http://one.wordpress.test/wp-content/plugins/redux-framework/ReduxCore/inc/extensions/import_export/import_export/field_import_export.js'></script>
<script type='text/javascript'>
	/* <![CDATA[ */
var redux =......
/* ]]> */
</script>
<script type='text/javascript' src='http://one.wordpress.test/wp-content/plugins/redux-framework/ReduxCore/assets/js/redux.js'></script>
```
As you can imagine this causes javascript errors.

## Support Hash
http://support.redux.io/?id=g%2Fo3JwA1dfT%2F5en1s8BS5UZVIvmblnuoEKvfK9%2BsJ6cx4TZbPLkt2TgZSfCBmP6cFe2piYqjRYAFwll6Ah%2BFZA%3D%3D

## Steps to reproduce
This problem is not always present, I can (sometimes) reproduce it by removing a field type 'sortable' from a section.
If I add that field the Javascript order is correct. I'm using a simple config file with just a section and a raw type field to print out a message.

This is my Field section, the `$args` are the same of your example but I changed the `$opt_name`.

I have installed Redux as a plugin, so it is not included in my codebase. The builder does not accept registration so I cannot generate a template and I have created the enviroment by myself.
(its just a single PHP file)

I don't have custom extensions.

```
Redux::setSection($opt_name, array(
    'title' => ''Hello',
    'id' => 'sidebar',
    'icon' => 'dashicons dashicons-feedback',
    'fields' => array(
        /*array(
            'id' => 'prevent-bug',
            'type' => 'sortable',
            'options' => array()
        ),*/
        array(
            "title" => 'About',
            "id" => "welcome-text",
            "type" => 'raw',
            "content" => 'Thanks for choosing this plugin'
        ),
    )
));
```

## Expected Behavior

No Javascriopt error and correct raw content positioning.

## Actual Behavior
Javascritp errors, Options Object not working to debug.
Filed content is not correctly aligned due to some column on the table in the DOM that are removed by javascript when not needed.

## Any Error Details (PHP/JavaScript)
Javascript error are a bunch of:
`ReferenceError: redux is not defined`

On PHP side I have nothing.

**Comment by kprovance** [comment]
Hi,

Thanks for the report.

This is an issue we identified before and have fixed in Redux v4.  The public beta test for that will begin very soon.  We are no longer actively working on or updating v3 so that we may focus out efforts on the future.

If you would like to be notified when that beta is ready, you may join our mailing list here:  https://reduxframework.com/subscribe-to-redux-framework/

- Kev
