### ISSUE TITLE
White blank screen while adding or editing pages in wordpress

### ISSUE THREAD

**Issue by ashishhbh** [reduxframework/redux-framework#3633]
I am not able to add or edit pages in wordpresss . When i go to the page edit option in wordpress a complete white blank screen is showing with the error message –

**(Warning: call_user_func_array() expects parameter 1 to be a valid callback, function ‘wp_cache_set_posts_last_changed’ not found or invalid function name in /home/accounts/public_html/wp-includes/class-wp-hook.php on line 288)**

All the things was working fine some days back . I have also tried to deactivate all the plugin to make sure it will not be due to any plugins but even after deactivating the plugins error is still showing.

I have already done lots of R & D to solve this issue but nothing works..

**Comment by dovy** [comment]
You're welcome to search our source code, but we do not even use that hook. Your problem is in the theme or another plugin. Good luck!
