### ISSUE TITLE
 redux-framework using a lot of resources / high cpu usage 

### ISSUE THREAD

**Issue by kyleluna** [reduxframework/redux-framework#3634]
What can cause redux-framework to use a lot of resources? My website's cpu usage is very high and this plugin is one of the reasons why. My website was fine for over a year then this issue started to occur last month. No changes were made. Even after updating everything I still have the same issue. What can I do to troubleshoot/resolve this?

**Comment by kprovance** [comment]
You will need to contact the author of your theme for support on this matter as we have no way of knowing how they implemented it.  We made this very clear in the text provided for you before you posted this. 

To prove this point, disable all plugins, load a default theme like Twenty-Nineteen and then active Redux Framework.  You will see no speed issues as Redux is very fast.

 Good luck.
