### ISSUE TITLE
Invalid argument supplied for foreach() 

### ISSUE THREAD

**Issue by kiarashi** [reduxframework/redux-framework#3635]
I've created a custom posttype and when I'm on the archive page of this specific posttype, I get the following warning message (query monitor):
Warning: Invalid argument supplied for foreach() 
wp-content/plugins/redux-framework/ReduxCore/framework.php:1486

I noticed that inside the admin bar, normally, I see "Theme Options", but on the page where the error appears, it's gone. Perhaps it's related?

**Comment by kprovance** [comment]
Theme users need to contact the author of the theme for support as we have no way of knowing ow they are implementing Redux.

**Comment by kiarashi** [comment]
I'm a developer myself and know how I'm using redux in my theme. :)

**Comment by kprovance** [comment]
There was a whole page of information we require for free support.  None of it was included.   Required for free support.  If you open a New Issue, select Theme Developer you can read it there.
