### ISSUE TITLE
Redux Framework requests pluggable.php

### ISSUE THREAD

**Issue by Ihor-B** [reduxframework/redux-framework#3636]
Hello there,

I'm a developer, and use the Redux Framework as a part of my plugin about 3 years.
After some of an updating of plugins/theme/wordpress appears the error message:

> Postman: wp_mail has been declared by another plugin or theme, so you won't be able to use Postman until the conflict is resolved.
> More info that may help - /home4/ristici0/public_html/emarketinginstitute-project/wp-includes/pluggable.php:175

Below more details for this issue...

**## Support Hash**

http://support.redux.io/?id=yxCg%2FiLLT55ugZfcQDfKWGvebw1IqYLFe%2BmxdQBAjuPfZ3qRUPTdeyxVs4aUmSCzdjh1t46gDaeunsTOguoQxSIaKanxre0i3ZLHJxGx9b4neKPNtoGOfFGAK8jQn3dc

## Steps to reproduce

We use the plugin "[Post SMTP](https://postmansmtp.com/)" with Redux Framework.

I have tried to find a source of the problem and the error disappeared only when I have comented the string "require_once( dirname(__FILE__).'/redux-framework/ReduxCore/framework.php' );" in the file admin-init.php

## Expected Behavior

I've expected to use the Redux Framework and Post SMTP together without errors.

## Actual Behavior

Currently I have this conflict between "Redux Framework" and "Post SMTP" and we can't send and emails from our site.

## Any Error Details (PHP/JavaScript)

[25-Mar-2019 10:18:49 UTC] ERROR PostmanManageConfigurationAjaxHandler: Gmail API
[25-Mar-2019 10:18:49 UTC] ERROR PostmanManageConfigurationAjaxHandler: SMTP - gmail.com:587
[25-Mar-2019 10:18:49 UTC] ERROR PostmanManageConfigurationAjaxHandler: Mailgun API
[25-Mar-2019 10:18:49 UTC] ERROR PostmanManageConfigurationAjaxHandler: SendGrid API
[25-Mar-2019 10:18:49 UTC] ERROR PostmanManageConfigurationAjaxHandler: Mandrill API
[25-Mar-2019 10:18:49 UTC] ERROR PostmanManageConfigurationAjaxHandler: 
[25-Mar-2019 10:18:49 UTC] ERROR PostmanManageConfigurationAjaxHandler: 
[25-Mar-2019 10:19:02 UTC] FATAL Postman: Postman: wp_mail has been declared by another plugin or theme, so you won't be able to use Postman until the conflict is resolved.

I have commented the string: "require_once ABSPATH . "wp-includes/pluggable.php";" in the file /ReduxCore/framework.php but without success. 
Perhaps this request exist in other file?

Please can you help me to fix it?
Thank you.

**Comment by dovy** [comment]
Hey there. You’re welcome to search our code, but we don’t use wp_mail anywhere. So... I really can’t see how Redux is causing this. Best of luck!

**Comment by Ihor-B** [comment]
The problem appears not by calling wp_mail... Actually this error appears by hard request of pluggable.php in the Redux Framework.

**Comment by dovy** [comment]
Umm. I am confident that if you install the redux plugin and disable all other plugins and change your theme there won’t be an issue. ;)

**Comment by dovy** [comment]
Oh and then on Demo mode for redux. Care to give that a try?

**Comment by Ihor-B** [comment]
I have integrated Redux Framework into my plugin, not as a another plugin.
The same problem appears in other combinations of plugins and/or other themes.
I mean - I have tried to localise the problem before ask you for help. :) And I have checlked all possible options to define a source of the problem.
As result only the combination - Redux Framework + Post SMTP make this "pluggable.php ERROR" happened.

**Comment by dovy** [comment]
@Ihor-B I wish you would try my outlined steps a little more.

1. Only have the Redux plugin active
2. Use a generic theme, not yours.
3. Activate Redux demo mode
4. Activate Post SMTP 

You will see there's no issue.

If you are running Redux in your plugin, then you probably have to delay your plugin from loading until the `plugins_loaded` hook. More than likely, you are running Redux too early which is causing the pluggable issue.

**Comment by Ihor-B** [comment]
Thank you for your suggestion. I think you are right - "...running Redux too early...".
I will try to fix it.
Thank you for your hard work.

Have a nice day. :)

**Comment by dovy** [comment]
It's super easy to delay your plugin. In your plugin's main file:

```
function run_ihor_b_code() {
// Run your code here, all includes, inits, etc
}
add_action('plugins_loaded', 'run_ihor_b_code')
```

Best of luck!

**Comment by dovy** [comment]
And it would really help if you mention the conflicting plugin as you open the support issue in the future. I could have isolated the suggestions quicker.  ;)

Let me know how it turns out.

**Comment by Ihor-B** [comment]
Sure, I will fix my requests in future. :)
And yes, delaying of calling Redux fixed the problem.
Thank you. :)

**Comment by dovy** [comment]
Awesome! Glad to hear it.

Side note, have you tried Redux 4 yet?

---
If you feel up to it, we'd appreciate your review of Redux. https://wordpress.org/support/plugin/redux-framework/reviews/#new-post

**Comment by Ihor-B** [comment]
Not yet, may be later. :)
Thank you.
