### ISSUE TITLE
Login and Registration Issue

### ISSUE THREAD

**Issue by ngarawakimani** [reduxframework/redux-framework#3639]
There is an issue with registration and sign up, it seems redux.io and https://build.reduxframework.com/wp-login.php are using different databases cant login to reduxframework but can login to redux.io. please check it

**Comment by gak92** [comment]
I am still having same issue. Can't login on https://build.reduxframework.com/wp-login.php
I reset the password but does not work. 

It said:
ERROR: Invalid email address. Lost your password?
while using same email address when login on main site.

**Comment by rikdenb** [comment]
Issue still there.
