### ISSUE TITLE
exploore accomodation edit room type

### ISSUE THREAD

**Issue by tess9125** [reduxframework/redux-framework#3642]
<!--
exploore accomodation edit room type. 

Unable to list separate price for adults and children. I see infant price but I have rooms that will charge more for adults than children. I wish you could allow children rates and not only infant rates. Won't show up correctly on the calculation. Anything I am missing or you can do?

**Comment by tess9125** [comment]
exploore accomodation edit room type. 

Unable to list separate price for adults and children. I see infant price but I have rooms that will charge more for adults than children. I wish you could allow children rates and not only infant rates. Won't show up correctly on the calculation. Anything I am missing or you can do?

**Comment by dovy** [comment]
Hey there. I think you need to contact your theme author. We don't have anything like child rates in our framework. Best of luck!

**Comment by tess9125** [comment]
The last one I have Version 5.5 ( 04 January 2019 ), I have been trying to find out to get the latest updates. Your system says register your product, well we did though your site but we don’t get updates. Should automatically update like all my other themes have done in the past.. It's like you sell these templates but no one works here.
