### ISSUE TITLE
Font-display

### ISSUE THREAD

**Issue by Productdb** [reduxframework/redux-framework#3643]
Hello,

When is font-display enabled in the redux framework?

**Comment by dovy** [comment]
@Productdb What do you mean? You'll have to give me more details.

**Comment by Productdb** [comment]
All info => https://developers.google.com/web/updates/2016/02/font-display?utm_source=lighthouse&utm_medium=unknown

**Comment by gobanana66** [comment]
Any update on this? I'd like to use font-display:swap with my theme

**Comment by mithunmohandas** [comment]
I'd like to see this as well. As of Lighthouse v5, pagespeed scores have been tanking because font-display: swap isn't present in the Redux framework CSS files

**Comment by dovy** [comment]
Hey, can anyone take the CSS redux is outputting for them, and then show me a before and after case? If it's easy I can just throw it in.  ;)

**Comment by kprovance** [comment]
Will look into adding this for Redux 4.  Thanks!
