### ISSUE TITLE
Redux Builder Login Problem

### ISSUE THREAD

**Issue by fabiancuza** [reduxframework/redux-framework#3644]
Hello!
For some reason, i cannot login to Redux Builder. It simply says that the password is incorrect, even though I have an account and reseted the password.

**Comment by fabiancuza** [comment]
Update: On https://build.reduxframework.com/ says "Invalid email address" but if I click on the link after that it redirects me to redux.io/account where i already have an account with the email address i have been trying to use.

**Comment by MagdiElmowafy** [comment]
Me too!

**Comment by MagdiElmowafy** [comment]
Same problem!

**Comment by dovy** [comment]
I’m working on it all! My apologies. Doing a complete rebuild.
