### ISSUE TITLE
WpBackery issue since 2 month

### ISSUE THREAD

**Issue by benoitvincens** [reduxframework/redux-framework#3647]
Hi,

I have a problem since WP upadtes 👍 
I can't use page builder any more. Look at the screen below.
I bought my waxom theme with this wpbakery pagebuilder, and wpbackery says to ask to waxom...

Thanks

![Capture d’écran 2019-05-14 à 15 42 52](https://user-images.githubusercontent.com/45176246/57927098-6d4dc780-78ad-11e9-94ab-9316ee7f67f8.png)

**Comment by dovy** [comment]
We didn’t write your theme or wpbakery. Best to contact your theme author or that plugin author. Best of luck!
