### ISSUE TITLE
Scroll does not work

### ISSUE THREAD

**Issue by User221061** [reduxframework/redux-framework#3648]
The scroll does not work when Rudux framework plugin is active. Once deactivated the scrolling works but the header & Title pages changes. Wordpress  support recommended to access github support. Regards

**Comment by dovy** [comment]
Hello @User221061. I fear that's a question for the developer of the theme or plugin that is using Redux Framework. They probably have some CSS settings that are misfiring. Best to reach out to them.

Best of luck!

**Comment by zhangys** [comment]
Customizing-"Additional CSS"  add 

.product_list_widget.cart_list
{
	 max-height: 500px;
	overflow: auto
}
