### ISSUE TITLE
Issues with Redux plugin

### ISSUE THREAD

**Issue by rococodecor** [reduxframework/redux-framework#3649]
Hi, 

I updated my theme a few days ago. 
However, the plugin Redux Framework is impacting on my website. When it is active, the website seems to be broken. And when that plugin is not active, the website appears to be working but it not showing all the features of the theme options and it is partially broken.

Not sure what steps to take... Please help!
<img width="1550" alt="Screen Shot 2019-05-29 at 7 39 38 pm" src="https://user-images.githubusercontent.com/51158049/58549501-02a66f80-824f-11e9-9713-3e10b76d037a.png">
<img width="1533" alt="Screen Shot 2019-05-29 at 7 43 35 pm" src="https://user-images.githubusercontent.com/51158049/58549503-02a66f80-824f-11e9-8e1d-5e158bdb8f1a.png">
<img width="1536" alt="Screen Shot 2019-05-29 at 7 43 21 pm" src="https://user-images.githubusercontent.com/51158049/58549504-02a66f80-824f-11e9-92e3-2607adbfd096.png">
<img width="1531" alt="Screen Shot 2019-05-29 at 7 40 35 pm" src="https://user-images.githubusercontent.com/51158049/58549505-033f0600-824f-11e9-9861-5cedd7e5f558.png">
<img width="1151" alt="Screen Shot 2019-05-29 at 7 43 08 pm" src="https://user-images.githubusercontent.com/51158049/58549507-033f0600-824f-11e9-9229-b3176558118f.png">

## Any Error Details (PHP/JavaScript)

**Comment by dovy** [comment]
Best to contact the theme author here. Sounds like their update broke something.
