### ISSUE TITLE
Remove Google's webfont.js

### ISSUE THREAD

**Issue by mariusbolik** [reduxframework/redux-framework#3653]
I read your statement, but the Theme Author couldn't help me.
I simply want to remove the following part in the source code of my website:

```
<script type="text/javascript">
/* You can add more configuration options to webfontloader by previously defining the WebFontConfig with your options */
if (typeof WebFontConfig === "undefined") {
    WebFontConfig = new Object();
}
WebFontConfig['google'] = { families: ['Open+Sans:300,400,600,700,800,300italic,400italic,600italic,700italic,800italic', 'Open+Sans+Condensed:300,700,300italic'] };

(function () {
    var wf = document.createElement('script');
    wf.src = 'https://ajax.googleapis.com/ajax/libs/webfont/1.5.3/webfont.js';
    wf.type = 'text/javascript';
    wf.async = 'true';
    var s = document.getElementsByTagName('script')[0];
    s.parentNode.insertBefore(wf, s);
})();
</script>
```
What is the best way to do that? Is there any action hook I can use? I don't want connections to google servers on my website.

Best Regards
Marius

**Comment by dovy** [comment]
The simplest approach is to remove all Google Fonts from your typography fields (use default fields) and it should be gone.  ;)

Alternatively, you can find the author's typography fields and set a new arg as google => false.

Best of luck!

**Comment by martin-braun** [comment]
@dovy I don't really like this solution, because it will cause the stylesheets to be removed, too. It's better to do

```php
/**
 * Disable Google Fonts in Redux.
 */
add_action( 'redux/loaded', function( $redux ) {
	$redux->args['disable_google_fonts_link'] = true;
}
```

Now the stylesheets are not removed and I simply have to store the font's and the CSS file from gstatic.com by myself and style definitions will be preserved.

**Comment by josip-matic** [comment]
@martin-braun Where tu put this code, functions.php? I broke whole site. 
@mariusbolik It is not the greates solution but it is working. I contact author to add option to disable font.

**Comment by martin-braun** [comment]
@josip-matic Put it in the functions.php of your child theme.

**Comment by jmslbam** [comment]
> @martin-braun Where to put this code? I broke whole site. @mariusbolik It is not the greates solution but it is working. I contact author to add option to disable font.

It broke because the code was not complete. It forgot the `);` at the end.

```
add_action( 'redux/loaded', function( $redux ) {
	$redux->args['disable_google_fonts_link'] = true;
});
```

**Comment by martin-braun** [comment]
@jmslbam Thanks, yes, copy paste failure. Edited and fixed my comment for reference.
