### ISSUE TITLE
Spacing field units

### ISSUE THREAD

**Issue by Stas0238** [reduxframework/redux-framework#3654]
Hello, i would like to add vh and vw dimensions in spacing field. It works till I won't refresh the options page which contains an error with text like 'Undefined index on .../redux-framework/ReduxCore/inc/fields/spacing/field_spacing.php on line 161' so that when I looked closer I saw you have an array of acceptable values for units
array(
'',
'%',
'in',
'cm',
'mm',
'em',
'rem',
'ex',
'pt',
'pc',
'px'
)
Can you please add vh, vw also in this array of units to make them working good ?:)

**Comment by kprovance** [comment]
Hi!

Redux 3.x has reached its end of life.  We will no longer be maintaining it.  Please update to Redux v4, which will be moved to this repository shortly.  Should you should discover the same issue with Redux v4, please rereport the issue, making sure to supply the required information request via the New Issue form.

Thank you for choosing Redux.

- Kev
