### ISSUE TITLE
Upcoming New Updates? There is no update for some time

### ISSUE THREAD

**Issue by btayvre** [reduxframework/redux-framework#3657]
It is incompatible with the latest WPBakery Page Builder version.

**Comment by kprovance** [comment]
Hi!

Redux 3.x has reached its end of life.  We will no longer be maintaining it.  Please update to Redux v4, which will be moved to this repository shortly.  Should you should discover the same issue with Redux v4, please rereport the issue, making sure to supply the required information request via the New Issue form.

Thank you for choosing Redux.

- Kev
