### ISSUE TITLE
OUTDATED THEME TEMPLATES

### ISSUE THREAD

**Issue by PennyMarketing** [reduxframework/redux-framework#3660]
I am receiving this notification in my wordpress dashboard:
Your theme (Turbo) contains outdated copies of some WooCommerce template files. 
These files may need updating to ensure they are compatible with the current version of WooCommerce. 
Suggestions to fix this:

Update your theme to the latest version. 
If no update is available contact your theme author asking about compatibility with the current WooCommerce version.
If you copied over a template file to change something, then you will need to copy the new version of the template and apply your changes again.

Where can I find the latest theme?  and if that does not work.... what woocmmerce version should I use to make all the features work right.

**Comment by IgorCode** [comment]
Why are you writing here? You need to contact your theme's author.

**Comment by dovy** [comment]
Thank you @IgorCode.

@PennyMarketing please contact your theme author as we did not build it.  ;)
