### ISSUE TITLE
Default Text doesnt change

### ISSUE THREAD

**Issue by helvetica123** [reduxframework/redux-framework#3662]
Are you a user reporting a bug with a theme or plugin?
======================================================
i want to learn how to integrate the plugin to a theme
	
Have a development usage question?
==================================
i copied redux core to my theme then i called redux with sample config ( i changed its name to only config ) from functions.php.then to learn how to use textarea i changed default text but it didnt change although the other texts like desc or subtitle changed.

the part which was edited of config:

```
    Redux::setSection( $opt_name, array(
        'title'      => __( 'Textarea', 'redux-framework-demo' ),
        'id'         => 'basic-Textarea',
        'desc'       => __( 'For full documentation on this field, visit: ', 'redux-framework-demo' ) . '<a href="//docs.reduxframework.com/core/fields/textarea/" target="_blank">docs.reduxframework.com/core/fields/textarea/</a>',
        'subsection' => true,
        'fields'     => array(
            array(
                'id'       => 'opt-textarea',
                'type'     => 'textarea',
                'title'    => __( 'Textarea Option - HTML Validated Custom', 'redux-framework-demo' ),
                'subtitle' => __( 'Subtitle', 'redux-framework-demo' ),
                'desc'     => __( 'This is the description field, again good for additional info.', 'redux-framework-demo' ),
                'default'  => 'Default Text',
            )
        )
    ) );

    // -> START Editors
```

Before you post, check the JavaScript!
======================================
there are errors on chrome console.you can look  at screenshot here:

https://ibb.co/dMHQFWP

or the copy past:

JQMIGRATE: Migrate is installed, version 1.4.1
VM1931 admin.php:1 [DOM] Found 2 elements with non-unique id #opt-multi-text: (More info: https://goo.gl/9p2vKq) <input type=​"text" id=​"opt-multi-text" name=​"redux_demo[opt-multi-text]​[]​" value class=​"regular-text ">​ <input type=​"text" id=​"opt-multi-text" name value class=​"regular-text">​
VM1931 admin.php:1 [DOM] Found 2 elements with non-unique id #opt-multitext: (More info: https://goo.gl/9p2vKq) <input type=​"text" id=​"opt-multitext" name=​"redux_demo[opt-multitext]​[]​" value class=​"regular-text ">​ <input type=​"text" id=​"opt-multitext" name value class=​"regular-text">​
look.redux.io/api/index.php?in&g&i=1&c=1&w=1349&h=redux.deniz-tasarim.site&rf=redux.deniz-tasarim.site&callback=jQuery112406601784639307617_1564188866521&_=1564188866522:1 Failed to load resource: the server responded with a status of 404 ()

-->

**Comment by dovy** [comment]
Reset your panel. It probably has the old defaults stored. ;)
