### ISSUE TITLE
htmlspecialchars(): charset `none' not supported

### ISSUE THREAD

**Issue by sordespilosus** [reduxframework/redux-framework#3663]
Hi, a have warning related with redux framework:

"Warning:  htmlspecialchars(): charset `none' not supported, assuming utf-8 in /home/netsh109628/html/wp-content/plugins/redux-framework/ReduxCore/inc/fields/ace_editor/field_ace_editor.php on line 84"

or you can see the picture:

[https://yadi.sk/i/XklXXjPY4ZimwA](url)

line 84 on this file look like that:

`<pre id="<?php echo esc_attr($this->field['id']); ?>-editor" class="ace-editor-area"><?php echo htmlspecialchars($this->value); ?></pre>`

how i can fix it?

**Comment by dovy** [comment]
Oh, interesting, this must be a new PHP7 thing. Are you a user or a developer?

**Comment by sordespilosus** [comment]
user, but i have ftp and hosting panel access

**Comment by sordespilosus** [comment]
give me instructions, i ready for cooperation )

**Comment by dovy** [comment]
Change it to `htmlspecialchars( $this->value, ENT_QUOTES, 'UTF-8' )`. I'll put a ticket in to make the fix.

**Comment by dovy** [comment]
Actually, I was wrong. Change it to this:

```<pre id="<?php echo esc_attr($this->field['id']); ?>-editor" class="ace-editor-area"><?php echo esc_html($this->value); ?></pre>
```
We already made the change in Redux 4.0.  ;)
