### ISSUE TITLE
Premium Support defunct, no way to cancel subscription

### ISSUE THREAD

**Issue by jessor** [reduxframework/redux-framework#3665]
I tried to work this out via email for 5 weeks but unfortunately couldn't get a result so I'd like to advise others about my experience with this project.

I can't download a premium extension purchased in June 2015 and renewed yearly since then ($39.99, ID 10143). I also can't cancel the subscription on the website because the site just reloads the dashboard. I can't even download a purchase or transactional receipt.

The email address `support@stg.redux.io` as stated on https://redux.io/extension/premium-support/ does not exist and bounces. The Terms and Conditions page (https://redux.io/extension/terms-and-conditions/) does not exist and returns a 404.

So on 2019-06-23 I tried emailing `support@redux.io` and asked to cancel the yearly subscription and possibly refund the latest transaction. After another email on 2019-07-04 I got an answer from Dovy on 2019-07-05 asking for confirmation that the extension was not on sale anymore. I answered on the same day and then again on 2019-07-23 but sadly haven't gotten an answer since.

**Comment by dovy** [comment]
@jessor my apologies, we're a little light on the team lately. I'll reply to the email.
