### ISSUE TITLE
Generate your own Underscores + Redux Framework based WordPress theme Error

### ISSUE THREAD

**Issue by Kan1221** [reduxframework/redux-framework#3666]
Hello Team,

I am new to develop with Redux framework. So I going to generate the theme with below line link. It shows an error. Can you please have a look.

[[Generate your own Underscores + Redux Framework based WordPress theme](http://build.reduxframework.com/) ]
https://prnt.sc/on00bd

Thank You
Kan

**Comment by enox-media** [comment]
Do you have an ETA on when the builder will be released?

**Comment by dovy** [comment]
This week! I’m between projects and I want to get Redux 4 ready for release and the builder functioning again. ;)

**Comment by Kan1221** [comment]
Thanks, @dovy.  waiting for the new release!

**Comment by Kan1221** [comment]
@dovy  still can't access the url.
