### ISSUE TITLE
Issue with search engine

### ISSUE THREAD

**Issue by tibethills** [reduxframework/redux-framework#3668]
Hi there! Some time ago I installed the Electro template on my website. We have recently installed a web browser called "Doofinder" that works correctly when the "Redux Framework" plugin is disabled. We need this search engine since having a large volume of products makes the search immediate. You can check an example on the web https://pccomponentes.com. My question is this: Can you find the incompatibility that these plugins have?

**Comment by dovy** [comment]
You'll need to contact your theme author. We didn't build that product.
