### ISSUE TITLE
Admin Panel Running Slowly

### ISSUE THREAD

**Issue by rupbrown** [reduxframework/redux-framework#3669]
Hi there

I have recently installed Redux Framework to use with a Product Catalogue Plug In (by welaunch) and the admin section of wordpress is now incredibly slow and is timing out on occasion. I am using the Flatsome Theme (if that makes a difference).

I am a bit of a novice with all of this so any help would be much appreciated!

Many thanks!

**Comment by dovy** [comment]
Hey there! I'm sorry you're having this issue. I fear that this is probably not a Redux issue. We can't control how all developers use our framework and some do so poorly. :(

Here's how you can test if it's Redux:
- Install the Redux Framework Plugin
- Switch to a generic WordPress theme
- Activate Redux Demo Mode

More than likely the theme is doing too much processing against SCSS or something. Best of luck to you!
