### ISSUE TITLE
Repeater extension doesn't work combined with metaboxes extension

### ISSUE THREAD

**Issue by rafaelfndev** [reduxframework/redux-framework#3683]
I'm using custom post type (register_post_type), and I'm using metaboxes extension on this custom post type.

I try to use repeater field combined with metaboxes and doesn't work, the fields of metaboxes appears, but when I press the button "Add" or "Delete" of repeater, nothing happens.

![metaboxes-repeater](https://user-images.githubusercontent.com/7171869/67626138-a8213780-f81d-11e9-9303-3c55e85a4edf.jpg)

**Comment by dovy** [comment]
Hmm. I'll have to take a look. Sorry for the delay, Google buried the notification for this!

**Comment by kprovance** [comment]
Hi!

Redux 3.x has reached its end of life.  We will no longer be maintaining it.  Please update to Redux v4, which will be moved to this repository shortly.  Should you should discover the same issue with Redux v4, please rereport the issue, making sure to supply the required information request via the New Issue form.

Thank you for choosing Redux.

- Kev
