### ISSUE TITLE
Repeater doesn't work on WordPress v. 5.3

### ISSUE THREAD

**Issue by rafaelfndev** [reduxframework/redux-framework#3685]
I upgraded of version 5.2.4 to version 5.3 and repeater stopped works. The button add or delete dont anything and all sections are expanded by default.

![repeater-error-5-3](https://user-images.githubusercontent.com/7171869/68766255-55a59080-05fd-11ea-9230-72d0530e5800.png)

**Comment by dovy** [comment]
Let me take a look.  :)

**Comment by rafaelfndev** [comment]
Hey @dovy thanks, you have any news? Customers are charging me, I need to update some sites...

**Comment by dovy** [comment]
@rafaelfndev Been looking into this. I can't reproduce it. Can you give me the version of Repeater you are using as well as the Redux version you are using?

**Comment by dovy** [comment]
Better yet, do this. I'll be able to debug it all that way: https://docs.redux.io/guides/basics/generating-a-support-hash.html

**Comment by rafaelfndev** [comment]
http://support.redux.io/?id=GjyhALiv1pil8GdJROrDk3ErQ16vctM620m7dbugXGebdq7H5JyphjVa4yTdog%2FwrLqQ2k%2B8RGxvs51bzieYFQ%3D%3D

Redux: 3.6.15
Repeater: 1.0.6
WordPress: 5.2.4 (5.3 stop working)

**Comment by rafaelfndev** [comment]
I make a clean installation, include redux framework, metaboxes extension and repeater extension, on WordPress version 5.2.4 are ok, but if I update to version 5.3 stops working.

**Comment by dovy** [comment]
@rafaelfndev can you pass your code to me? Honestly, I am able to get it to work without an issue. dovy@redux.io

**Comment by rafaelfndev** [comment]
@dovy sent! Thanks.

**Comment by dovy** [comment]
Released repeater-1.0.7 to resolve this issue.  :)
