### ISSUE TITLE
HELP: Feed not showing on Child Lineza

### ISSUE THREAD

**Issue by pdl2k** [reduxframework/redux-framework#3686]
Hello, today I notice that the widgets in the Home Content Area of Lineza are not showing, the only thing visible is the "recent news".
I check all and it's OK, I not make any change.
The widgets in the Sidebar are just fine, but the ones I already have in the Homepage Content Area are not.

The site is http://www.motriz.info/

What can be the problem?

**Comment by dovy** [comment]
We didn't build Lineza. It's best to contact the author of that product. Have a great day!
