### ISSUE TITLE
I can not edit Listings after updating to newer version of WP

### ISSUE THREAD

**Issue by demetrioucy** [reduxframework/redux-framework#3687]

**Comment by demetrioucy** [comment]
http://support.redux.io/?id=QiQ8PiMz9w%2BpMHse2FVlD3CeTNOZ%2F9Yo8HexB9Dfk4tu6BS5cCX7lLvKG7iVRbkWnbZwURolbb2S%2FrCAalWjDQ%3D%3D

**Comment by dovy** [comment]
Sorry, we didn't build that theme or plugin, but rather the user interfaces that run it. You'll need to contact your theme/plugin author for help with "listings." Best of luck!
