### ISSUE TITLE
Redux Marked as Expired After Payment

### ISSUE THREAD

**Issue by michelbayard** [reduxframework/redux-framework#3688]
Hi, our team has tried to contact support multiple times via email since October 29th to try and resolve a payment/license issue, but have yet to hear back from them.  We were billed on May 4th, 2019, but we aren't able to access any Redux downloads or even view the invoice on the Redux site.  Included below are some screenshots of the Redux account backend as well as the invoice we received from Paypal confirming that the money was sent to the Redux.

If there is a better place for us to post or get support in a timely manner, just let me know, and I'll use that channel in the future.

Thank you in advance!
Matthew Clark
ArcticLune

![image](https://user-images.githubusercontent.com/14185663/69473653-82d00c80-0d7c-11ea-9460-6862ac76c8b4.png)

![image](https://user-images.githubusercontent.com/14185663/69473646-6af88880-0d7c-11ea-9aa1-d3f632244b6e.png)

![image](https://user-images.githubusercontent.com/14185663/69473713-025ddb80-0d7d-11ea-8638-baa12d72e9ff.png)

**Comment by dovy** [comment]
@michelbayard I'm on it.

**Comment by michelbayard** [comment]
Hi @dovy,

Thank you very much for taking a look into our situation!  We currently see most of the extensions in the downloads section, but are still missing the "Accordion", "JS Button" and "Ad Remover" ones plus the "Advanced Customizer", "Taxonomy Metaboxes", and "User Metaboxes" that are still marked as coming out soon.

Additionally, We noticed that the [Ultimate Bundle](https://redux.io/extension/ultimate-bundle/) has been renamed to "All Access Pass", which is $250 cheaper now.  Would it be possible for us to purchase the All Access pass and refund the difference from the $750 Ultimate Bundle that we weren't able to use previously?

Thank you in advance!

![image](https://user-images.githubusercontent.com/14185663/70104703-79f4fb80-1604-11ea-8c7e-85faa44327ff.png)

**Comment by dovy** [comment]
We resolved the issue offline.
