### ISSUE TITLE
Mobile menu sign instead of text?

### ISSUE THREAD

**Issue by slavicport** [reduxframework/redux-framework#3689]

**Comment by slavicport** [comment]
Hi! Is the anyway to set mobile menu instead of having text, to put 3 lines as usually other developers do? 'cause my site looks ugly without this option: 

![IMG_2252](https://user-images.githubusercontent.com/29007806/70380184-085ecb00-18ec-11ea-8c27-2e6a966f5495.PNG)

**Comment by dovy** [comment]
We didn't build that theme. You will need to contact the theme author. Thank you.
