### ISSUE TITLE
Big problem with Redux Framework in y wordpress website

### ISSUE THREAD

**Issue by king2028** [reduxframework/redux-framework#3690]
http://support.redux.io/?id=mAM2Zkcs%2FttsBTPrAmrCQfekpSVZdL9Yt1v92LIOyEzELXAqIStU7WJPQynPKEBC0bVkIp14GijTyAEDuxLUZQ%3D%3D

I have a big problem in the admin dashboard of my website, i'm using homey theme which use redux framework to create the panel administration but when i clic to save after doing same modifications, all the item of the panel are not showin and i will have a white block and when i see the console i will get this message Uncaught SyntaxError: Unexpected token '<' ...... admin.php?page=homey_options&tab=1:4161 Uncaught SyntaxError: Unexpected token '<.'
I need help to resolve this problem please.

**Comment by dovy** [comment]
You will need to contact the creators of the homey theme. It seems they have a bug in their code. We did not build that theme. Best of luck to you.
