### ISSUE TITLE
Failed to load resource: the server responded with a status of 404 ()

### ISSUE THREAD

**Issue by helvetica123** [reduxframework/redux-framework#3691]
======================================================
admin panel console:

```
﻿load-scripts.php?c=0&load[chunk_0]=jquery-core,jquery-migrate,utils,moxiejs,plupload&ver=5.3.2:8 JQMIGRATE: Migrate is installed, version 1.4.1
look.redux.io/api/index.php?in&g&i=1&c=1&w=1271&h=www.themeforest-deneme2.deniz-tasarim.site&rf=www.themeforest-deneme2.deniz-tasarim.site&callback=jQuery11240697217489976472_1577903577897&_=1577903577898:1 Failed to load resource: the server responded with a status of 404 ()
```

	
Have a development usage question?
==================================
how can I solve this?

**Comment by dovy** [comment]
This issue is resolved. You don't need to change a thing.  ;)

**Comment by helvetica123** [comment]
> This issue is resolved. You don't need to change a thing. ;)

Sorry for my english, did you update redux version to solve it?

**Comment by dovy** [comment]
It was a configuration issue on our end. It is resolved. No updates needed.
