### ISSUE TITLE
Redux Framework disable issue

### ISSUE THREAD

**Issue by utsavtilava** [reduxframework/redux-framework#3692]
Hiii,

I am using redux framework plugin.I am add a setting using its default theme settings.setting is completely running.

But when I deactivate a plugin, my content will not be visible.

What should be done to prevent this from happening?

and, content is not to show in front side. why ?

I am using Simple Code see here attached screenshot( reduxissue.png ).

**Note : When I do plugin disable, front-end side does not show me my tittle.**

![reduxissue](https://user-images.githubusercontent.com/45058029/71892260-8b36a800-316e-11ea-9a07-67080e2bdb0a.png)

**Comment by dovy** [comment]
The variable $redux_demo is created by Redux. That name, redux_demo, is the opt_name that you set in Redux when you build a panel. If you changed that opt_name it won't work. If Redux isn't active, that variable does not get set, so it won't work then either.

Does that help?

**Comment by dovy** [comment]
Closed for inactivity.
