### ISSUE TITLE
Switch display doesnt seem

### ISSUE THREAD

**Issue by helvetica123** [reduxframework/redux-framework#3693]
Are you a user reporting a bug with a theme or plugin?
======================================================
I want to display social icons such as twitter,facebook etc. on the header.To this, I want to use switch option and text area.Switch option will control that display or not and the text areas are for link.
	
Think you found a bug?
======================
However, my code doesnt work.There is no output on header.

I use sample config.Here is the snippet:

```
Redux::setSection( $opt_name, array(
        'title'      => __( 'Switch', 'redux-framework-demo' ),
        'id'         => 'switch_buttonset-switch',
        'desc'       => __( 'For full documentation on this field, visit: ', 'redux-framework-demo' ) . '<a href="//docs.reduxframework.com/core/fields/switch/" target="_blank">docs.reduxframework.com/core/fields/switch/</a>',
        'subsection' => true,
        'fields'     => array(

            array(
                'id'       => 'switch-on',
                'type'     => 'switch',
                'title'    => __( 'Switch On', 'redux-framework-demo' ),
                'subtitle' => __( 'Look, it\'s on!', 'redux-framework-demo' ),
                'default'  => true,
            ),
            array(
                'id'       => 'switch-off',
                'type'     => 'switch',
```
Here is my code in function.php: 
```
function header_social_icons() {
    global $redux_demo;
    $hsicons =& $redux_demo['switch-on']  ? $redux_demo['switch-on'] : "true";
    switch ( $hsicons ) {
        case 'true':
            echo "açık";
            break;
        case 'false':
            echo "kapalı" ;
            break;
    }
}
```

Here is calling the function in header:

`<?php header_social_icons() ?>`

Before you post, check the JavaScript!
======================================
Uncaught TypeError: Cannot read property 'fn' of undefined
    at util.js:68
    at util.js:10
    at bootstrap.min.js:6
    at bootstrap.min.js:6
jquery-migrate.min.js?ver=1.4.1:2 JQMIGRATE: Migrate is installed, version 1.4.1
slick.min.js?ver=2.1.7:17 Uncaught TypeError: Cannot read property 'add' of null
    at e.initADA (slick.min.js?ver=2.1.7:17)
    at e.init (slick.min.js?ver=2.1.7:17)
    at new e (slick.min.js?ver=2.1.7:17)
    at a.fn.init.i.fn.slick (slick.min.js?ver=2.1.7:18)
    at HTMLDivElement.<anonymous> (wp-carousel-free-pub….min.js?ver=2.1.7:1)
    at Function.each (jquery.js?ver=1.12.4-wp:2)
    at a.fn.init.each (jquery.js?ver=1.12.4-wp:2)
    at wp-carousel-free-pub….min.js?ver=2.1.7:1
    at wp-carousel-free-pub….min.js?ver=2.1.7:1
﻿
​

**Comment by dovy** [comment]
You will need to contact the theme author. We didn't design your header.  ;)

**Comment by helvetica123** [comment]
> You will need to contact the theme author. We didn't design your header. ;)

@dovy The theme author is me.I dont want help about design, it is only setting question

**Comment by dovy** [comment]
If you look at the options-object tab, you can see the values of the data:

```
switch-on: "1"
switch-off: ""
```

So if you test like so:
```
function header_social_icons() {
    global $redux_demo;
    if ( isset( $redux_demo['switch-on'] ) && $redux_demo['switch-on'] ) {
        echo "açık";
    } else {
        echo "kapalı" ;
    }
}
```

I believe if/else are faster than switches anyways.  ;)

**Comment by helvetica123** [comment]
ok, thanks!

**Comment by dovy** [comment]
Glad it worked out. Good luck!

--- 
If you like Redux, or the support we render, please do one or all of the following:
- Donate to keep us going: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=MMFMHWUPKHKPW
- Review us: http://wordpress.org/support/view/plugin-reviews/redux-framework
- Like us: http://facebook.com/ReduxFramework
- Follow us: http://twitter.com/ReduxFramework
