### ISSUE TITLE
Redux Framework 3.6.17 update crashed my website

### ISSUE THREAD

**Issue by awnings** [reduxframework/redux-framework#3694]
I updated Redux Framework to the most recent version 3.6.17 and it crashed my entire website. The website is no longer visible and when I click on any and all items in the Wordpress dashboard I get this message: 
"There has been a critical error on your website. Learn more about debugging in WordPress".

Why did the update crash the website?

What do I do to fix the issue and how long will it take to fix the issue?

**Comment by dovy** [comment]
That is so odd. What was the version you had before?

**Comment by awnings** [comment]
3.6.15

**Comment by dovy** [comment]
send me an email at dovy@redux.io. I'll invite you to slack and we can work on this together in real-time. My apologies for the issue.

**Comment by dovy** [comment]
This issue was not with Redux. Resolved.

**Comment by awnings** [comment]
Dovy provided amazing service by logging in to my Wordpress account and determining that the issue was with Autoptimize and not Redux. Thanks so much Dovy :)
