### ISSUE TITLE
How can I use custom css file for option framework?

### ISSUE THREAD

**Issue by risingrun** [reduxframework/redux-framework#3700]
Hi, Anyone can help me please? 

I am using the redux framework to develop my theme. 

While I created dynamic-css.php file in developing time it worked, but after resetting the wordpress the dynamic-css.php doesn't work
in header.php it working, So how can I make CSS file which property value will change by options panel?

**Comment by dovy** [comment]
Did you figure this out?

**Comment by zebulondev** [comment]
Hello !
For use $globals Redux on css.php file :-)

On start your php css wrote this line :

define('WP_USE_THEMES', false);
require('../../../../wp-load.php');  /* change path in your level :-) */

header("Content-type: text/css; charset: UTF-8");
$variableFooterColor = $GLOBALS['redux_demo']['opt-color-footer']; /* access to globals variables */

/* write css and use php variables */

Enjoy ;-)

**Comment by zebulondev** [comment]
In redux, the dynamic-css is inline. The setting is created by 'output' value.

In your generated head of website you find it :
<style type="text/css" title="dynamic-css" class="options-output">
</style>

Sample in your config file :
Redux::setSection( $opt_name, array(
        'title'  => __( 'Typography', 'redux-framework-demo' ),
        'id'     => 'typography',
        'desc'   => '',
        'icon'   => 'el el-font',
        'fields' => array(
            array(
                'id'       => 'opt-typography-body',
                'type'     => 'typography',
                'title'    => __( 'Body Font', 'redux-framework-demo' ),
                'subtitle' => __( 'Specify the body font properties.', 'redux-framework-demo' ),
                'google'   => true,
                **'output' => array('h1, h2, h3, h4'),**
                'default'  => array(
                    'color'       => '#dd9933',
                    'font-size'   => '30px',
                    'font-family' => 'Arial,Helvetica,sans-serif',
                    'font-weight' => 'Normal',
.....
