### ISSUE TITLE
missing update section functionality with setSection?

### ISSUE THREAD

**Issue by rtpHarry** [reduxframework/redux-framework#3701]
## Support Hash

http://support.redux.io/?id=EggTdxE9e129gQ%2BRbLoSv1PrnYJoKFTrpHG6Do2JcTnugBaHJGqTImREbSZCJTe5A1vz7DZjD7PnM2nPed1tbA%3D%3D

## Steps to reproduce

I'm using 3.6.17.

According to the [docs](https://docs.redux.io/configuration/objects/section.html#updating-an-existing-section) it seems that I should be able to pass a third parameter, `true`, to the `setSection()`.

I'm trying to update a setting in a child theme to cleanly adjust it for the client, but it doesn't work.

I've wrapped the redux include inside an action to ensure that it happens after the theme registers its initial settings:

```php
add_action('redux/options/hotmagazine_options/register', 'update_redux_options', 50);
function update_redux_options() {
    require_once get_stylesheet_directory() . '/lib/redux.php';
}
```

And then override with:

```php
<?php 

    /**
     * ReduxFramework Barebones Sample Config File
     * For full documentation, please visit: http://docs.reduxframework.com/
     */
    if ( ! class_exists( 'Redux' ) ) {
        return;
    }

    // This is your option name where all the Redux data is stored.
    $opt_name = "hotmagazine_options";

    // update the blog selection options
    // Link: https://docs.redux.io/configuration/objects/section.html
    Redux::setSection( $opt_name, array(
        'id'         => 'blog_settings',
        'fields'     => array(
            array(
                'id'        => 'category_layout',
                'type'      => 'select',
                'title'     => esc_html__('Default Category Layout', 'hotmagazine'),
                'subtitle'  => esc_html__('Select default category blog layout.', 'hotmagazine'),
                'options'   => array(
                                        'default' => '2 Column Thumbnails With Caption (Default)', 
                                        '2colsidebar' => '[TO REMOVE] 2 Columns Sidebar', 
                                        '3columns' => '[TO REMOVE] 3 Columns', 
                                        'largeimage' => '[TO REMOVE] Large Image', 
                                        'bothsidebar' => '[TO REMOVE] Both Sidebar', 
                                        'thumbleft' => '[TO REMOVE] Thumbnail left sidebar', 
                                        'video' => '[TO REMOVE] Video',
                                    ),
                'default'   => 'default',
            ),
        )
    ), true );
```

But it doesn't work.

Then I investigated the source code and can find no mention of [the third parameter](https://github.com/reduxframework/redux-framework/blob/751e05229e89a66ce6be590deb6c37981721bf97/ReduxCore/inc/class.redux_api.php#L255):

```php
public static function setSection( $opt_name = '', $section = array() ) {
```

## Expected Behavior

Expected the setting to be replaced with my own values.

## Actual Behavior

Values remained the same.

**Comment by kprovance** [comment]
Hi!

Redux 3.x has reached its end of life.  We will no longer be maintaining it.  Please update to Redux v4, which will be moved to this repository shortly.  Should you should discover the same issue with Redux v4, please rereport the issue, making sure to supply the required information request via the New Issue form.

Thank you for choosing Redux.

- Kev
