### ISSUE TITLE
Deprecated error -> Non-static method Redux::remove_demo() 

### ISSUE THREAD

**Issue by Monsiter** [reduxframework/redux-framework#3702]
## Support Hash
http://support.redux.io/?id=TgZiGS8ZC5h68dmAXM2LEBeem5Jf6aVhfE1fMy5tr7na%2BqoIYHgalNFVNkkWndvb83BqG4BSskGhH1OMoHJthw%3D%3D

## Steps to reproduce
1. Activate plugin
2. Add the `Redux::disable_demo();` code for removing the demo
2. See the deprecated notice on the screen

## Expected Behavior
No notices

## Actual Behavior
Deprecated: Non-static method Redux::remove_demo() should not be called statically in /var/www/html/wp-includes/class-wp-hook.php on line 288

## Any Error Details (PHP/JavaScript)
The problem is as in notice the method added to action is as static but in real it's not static. It can be found in the file `/redux-framework/ReduxCore/inc/class.redux_api.php`
```
public static function disable_demo() {
    add_action('ReduxFrameworkPlugin_admin_notice', 'Redux::remove_demo', 0);
    add_action('redux_framework_plugin_admin_notice', 'Redux::remove_demo', 0);
}

/**
 * Callback used by Redux::disable_demo() to remove the demo mode notice from Redux.
*/
function remove_demo() {
    update_option('ReduxFrameworkPlugin_ACTIVATED_NOTICES', '');
}
```

If we will change `function remove_demo` to `public static function remove_demo` everything would be fine.

Thanks

**Comment by dovy** [comment]
We actually have this fixed in Redux 4. As soon as we release that version, this message will go away.  :)
