### ISSUE TITLE
WordPress caught an error with one of your plugins, Redux Framework.

### ISSUE THREAD

**Issue by MVCreativeServices** [reduxframework/redux-framework#3706]
My developer said he could not address this issue. I'm using Chris Robinson's WP Pro Real Estate 7 Theme. He recommended that I get with hosting support, which I did. Their reply, along with all the error notices are in this posting:

WordPress caught an error with one of your plugins, Redux Framework.

Redux would not let me generate a Support URL. I kept getting an error notice.

https://outdoorpropertiesinternational.com/

Fatal error: Uncaught Error: Call to private Browser::__construct() from context 'Redux_Helpers' in /home/customer/www/outdoorpropertiesinternational.com/public_html/wp-content/plugins/redux-framework/ReduxCore/inc/class.redux_helpers.php:430 Stack trace: #0 /home/customer/www/outdoorpropertiesinternational.com/public_html/wp-content/plugins/redux-framework/ReduxCore/inc/welcome/views/status_report.php(21): Redux_Helpers::compileSystemStatus(false, true) #1 /home/customer/www/outdoorpropertiesinternational.com/public_html/wp-content/plugins/redux-framework/ReduxCore/inc/welcome/welcome.php(452): require_once('/home/customer/...') #2 /home/customer/www/outdoorpropertiesinternational.com/public_html/wp-includes/class-wp-hook.php(288): Redux_Welcome->status_screen('') #3 /home/customer/www/outdoorpropertiesinternational.com/public_html/wp-includes/class-wp-hook.php(312): WP_Hook->apply_filters('', Array) #4 /home/customer/www/outdoorpropertiesinternational.com/public_html/wp-includes/plugin.php(478): WP_Hook->do_action(Array in /home/customer/www/outdoorpropertiesinternational.com/public_html/wp-content/plugins/redux-framework/ReduxCore/inc/class.redux_helpers.php on line 430

There has been a critical error on your website. Please check your site admin email inbox for instructions.

Ticket Subject: SiteGround Hosting Services follow-up

Posted on: 2020-03-11 16:31:59

From: SiteGround Sales

We tested out all available aspects of the hosting environment.

PhP versions, .Htaccess files, API restrictions, PhP variables etc..

There is nothing linked to the environment that could cause an error like that.

We strongly suggest that you double-check that with your developer one more time and make sure that plugin simply works with the latest version of Wordpress.

I can be reached at Mark@mvcreativeservices.design
Thanks.

**Comment by MVCreativeServices** [comment]
Hi Dovy. The problem has been solved with Chris's help. You can close this ticket out.
Cheers.

**Comment by emilevanasbeck** [comment]
Hi, I also have an issue with the redux framework plugin. When I enable it I get a white screen of death. The plugin is currently disabled. What are my best moves from here? Thanks is advance.

**Comment by dovy** [comment]
@emilevanasbeck please don't piggyback other tickets. I'd suggest going to a generic WordPress theme, then activating Redux. More than likely it is an issue with the theme using Redux. Best of luck!
