### ISSUE TITLE
Issue: fieldset:empty,td applied to all global td elements

### ISSUE THREAD

**Issue by accessally** [reduxframework/redux-framework#3707]
Hi there,

Our development team spotted an issue in redux.js (and redux.min.js) with this line:

`.redux-container td > fieldset:empty,td > div:empty`

This is applying display:none to all td table cell fields rather than only ones in the redux container and should be adjusted.

Hope this helps!

**Comment by dovy** [comment]
Any suggestion on what changes to make?  Care to do some extra testing for us? Community project and all.  ;)

**Comment by kprovance** [comment]
Hi!

Redux 3.x has reached its end of life.  We will no longer be maintaining it.  Please update to Redux v4, which will be moved to this repository shortly.  Should you should discover the same issue with Redux v4, please rereport the issue, making sure to supply the required information request via the New Issue form.

Thank you for choosing Redux.

- Kev
