### ISSUE TITLE
413 error on import

### ISSUE THREAD

**Issue by dciphered** [reduxframework/redux-framework#3709]
## Steps to reproduce
Attempting to import a previously exported options config results in a 413 (URL too long) error when doing so behind a CDN such as AWS CloudFront. CloudFront has a hard set URL length limit of 8,192 bytes and the import in 99% of cases is larger than this, resulting in a 413 error when attempting to import settings.

The issue would be overcome if redux supported the ability to upload the .json file, instead of requiring a copy/paste of the json syntax into the import window.

This is an issue for all sites that sit behind a reverse proxy or full CDN deployment.

**Comment by kprovance** [comment]
Hi!

Redux 3.x has reached its end of life.  We will no longer be maintaining it.  Please update to Redux v4, which will be moved to this repository shortly.  Should you should discover the same issue with Redux v4, please rereport the issue, making sure to supply the required information request via the New Issue form.

Thank you for choosing Redux.

- Kev
