### ISSUE TITLE
Problem when deactivating dev mode.

### ISSUE THREAD

**Issue by zabestof** [reduxframework/redux-framework#3710]
Hi there,

I'm using the Redux framework in my plugin but with the latest version every time I disable the dev mode I get this error in the console: 

redux.min.js?ver=3.6.18:1 Uncaught TypeError: Cannot use 'in' operator to search for 'text' in undefined

If I turn on dev mode it works without a problem.

You can see a video here: https://d.pr/v/8NnMxc

http://support.redux.io/?id=rsHFLuAZmyOy2Q4wXhntzW8SIZ%2BuJfWHCOnuIvKzDs44lQdNuUzojuiNlujngWt%2BVGUefiUijBdVvi%2F6dSN2bg%3D%3D

**Comment by dovy** [comment]
Hmm. Can you do some tests? Can you disable any CSS/JS/Speedup plugins you have? Sometimes I've seen caching plugins cause issues. My guess is that's the issue here.

**Comment by zabestof** [comment]
Sure, I've disabled everything except my plugin (which doesn't add any js or css). If I use an older version of Redux the problem is gone but with the latest I always get those errors.

**Comment by dovy** [comment]
Can you try the newest version of Redux coming out in an hour? 4.1.15. It should resolve this issue.

**Comment by kprovance** [comment]
Hi!

Redux 3.x has reached its end of life.  We will no longer be maintaining it.  Please update to Redux v4, which will be moved to this repository shortly.  Should you should discover the same issue with Redux v4, please rereport the issue, making sure to supply the required information request via the New Issue form.

Thank you for choosing Redux.

- Kev
