### ISSUE TITLE
PROPERTIES PAGE LYOUT 

### ISSUE THREAD

**Issue by mdfarishrahman** [reduxframework/redux-framework#3714]
HOW TO CHANGE Contract OPRTION DEFULT IN PAGE 
![Screenshot 2020-04-17 at 4 19 26 AM](https://user-images.githubusercontent.com/63822502/79513922-a57ffc00-8062-11ea-924a-49bed8c4f4ab.png)

HELP ME OUT HOW TO CHANGE OR CREAT NEW OPTION

**Comment by dovy** [comment]
We didn't build that theme. Contact your theme author.  ;)
