### ISSUE TITLE
redux plugin get error get_template_part() should be used instead

### ISSUE THREAD

**Issue by bobbykumar1** [reduxframework/redux-framework#3715]
when upload my theme wordpress.org and show error. many error are show same as like bellow how to fix this 

INFO: admin/ReduxFramework/ReduxCore/framework.php The theme appears to use include or require. If these are being used to include separate sections of a template from independent files, then get_template_part() should be used instead.
Line 424: require_once 'core/dashboard.php';
Line 428: require_once 'core/newsflash.php';
Line 1700: require_once 'core/enqueue.php';
Line 2849: require_once 'core/enqueue.php';
Line 2907: require_once 'core/panel.php';
Line 3259: require_once 'core/panel.php';

INFO: admin/ReduxFramework/ReduxCore/inc/class.redux_api.php The theme appears to use include or require. If these are being used to include separate sections of a template from independent files, then get_template_part() should be used instead.
Line 541: include_once( $api_check );

when i replace require_once to get_template_part() with show error

Parse error: syntax error, unexpected '$panel' (T_VARIABLE) in C:\xampp\htdocs\test\wp-content\themes\seerathemes\admin\ReduxFramework\ReduxCore\framework.php on line 3261

**Comment by dovy** [comment]
Use TGM to install Redux Framework instead. WP.org has some strict guidelines that we can't always abide by.  ;)

**Comment by bobbykumar1** [comment]
i already use but zip file are not allow in theme wordpress requrment
and i also use TGM function 'source' 

here is link
https://github.com/bobbykumar1/redux-framework/blob/master/redux-framework.zip

**Comment by dovy** [comment]
TGM will default to the WP.org repo.  ;)

```
<?php
 
$plugins = array(
    array(
        'name'      => 'Redux Framework',
        'slug'      => 'redux-framework',
        'required'  => true, // this plugin is recommended
    )
);
```

**Comment by dovy** [comment]
https://code.tutsplus.com/tutorials/using-the-tgm-plugin-activation-library-in-your-themes--cms-20901

See: Requiring a Plugin From WordPress.org
