### ISSUE TITLE
PHP 7.4 LOGS FULL OF WARNINGS BY REDUX

### ISSUE THREAD

**Issue by fasttrackhost** [reduxframework/redux-framework#3716]
Hi,
would be great to get rid of the warnings in the php 7.4 log

PHP Warning:  Creating default object from empty value in ....\wp-content\plugins\foodmood-core\includes\framework\ReduxCore\inc\class.redux_filesystem.php on line 31

It happens in several diferent themes, so we gues is a Redux issue (no need to copy-paste all the diferrent lines since all are for the same file, same line). We got in touch with the theme developer as well.

**Comment by deepak-rajpal** [comment]
In quick analysis, I can see that warning is generated in Redux file: **ReduxCore/inc/class.redux_filesystem.php**

**Fix:** Add empty constructor in class Redux_Filesystem:
```
public function __construct() {
}
```

I would be delighted to know if there is a better approach. Also, waiting to patch in core file with updated version.

**Comment by dovy** [comment]
I apologize for the delay here. This will be resolved in Redux 4 shortly.

**Comment by lvwuwei** [comment]
add **@**    like @$this > pratent

**Comment by dovy** [comment]
This issue should be resolved in Redux 4.4.14. Can anyone please confirm?

**Comment by dovy** [comment]
This is for Redux 3.x code. Version 4 does not have this issue. Closing.  :)
