### ISSUE TITLE
get_magic_quotes_gpc()  (@deprecated 7.4) - is being used in latest redux

### ISSUE THREAD

**Issue by deepak-rajpal** [reduxframework/redux-framework#3717]
## Expected Behavior
No deprecated function should be used.

## Actual Behavior
There is get_magic_quotes_gpc() being used in latest redux plugin code which is deprecated in PHP 7.4 version.
**../redux-framework/ReduxCore/framework.php**

## Any Error Details (PHP/JavaScript)
When we enable Query Monitor plugin in WordPress, we get following warning.

```
component: "Theme"
file: "wp-content/themes/abc-theme/admin/redux-framework/framework.php"
line: 2817
message: "Function get_magic_quotes_gpc() is deprecated"
stack: (2) ["ReduxFramework->ajax_save()", "do_action('wp_ajax_gar_ajax_save')"]
type: "deprecated"
```

**Comment by udhaya0000** [comment]
yes, in php 7.4 we are getting the deprecated message

![image](https://user-images.githubusercontent.com/18388014/84760219-549a6e80-afe5-11ea-8d0f-85b135d59694.png)

**Comment by dovy** [comment]
Have you tried Redux 4? https://github.com/reduxframework/redux-framework-4

**Comment by dovy** [comment]
Confirmed, this is not in Redux 4. Please do try the new version. The release is imminent.  ;)
