### ISSUE TITLE
Redux Framework plugin is giving error for second user to log in to wordpress as an editor.

### ISSUE THREAD

**Issue by adnanamer2** [reduxframework/redux-framework#3719]
Hi, 
I have bought a theme template online for my wordpress website and after assigning a second user as an editor to the website the login is giving error. "You don't have permission to access this page."
Kindly if I can be assisted asap as our editors need to upload products.

**Comment by dovy** [comment]
Hey there! That probably means the user doesn't have the proper permissions to access the panel. This is a security feature, not a bug.  ;)

Change their user type OR grab this plugin: https://wordpress.org/plugins/user-role-editor/ and make sure that your editors have the edit options feature. 

If that doesn't work, you can try upgrading to Redux 4, but installing this plugin: https://github.com/reduxframework/redux-framework-4/archive/master.zip. It's coming out later this month.

Best of luck!

**Comment by adnanamer2** [comment]
Hi, 
Thank you for your response, but I have just setup everything new. And user have permission to edit content. I have tried one thing on it , when I deactivate redux the user can log in but when I activate again it gives this error.
![Annotation 2020-05-26 191202](https://user-images.githubusercontent.com/66002129/83016919-69f62b80-a02b-11ea-8826-8f0fd8e88771.png)

**Comment by PYPLCode** [comment]
+ I have a same problem
