### ISSUE TITLE
Redux Framework plugin clashes with WooCommerce Add To Cart function. WP v5.4.1, Redux v3.6.18, WooCommerce v4.1.1.

### ISSUE THREAD

**Issue by websalacarte** [reduxframework/redux-framework#3721]
## Support Hash

http://support.redux.io/?id=i%2BJ1zddMU%2BsrRWfgrra2aoMHvONo00H0Al01zTmJjK%2BT8qr9uY33eQraZAbUQe9QiW0wY9UISLcaVJDOYiuOLA%3D%3D

## Steps to reproduce

To reproduce the issue, there just needs to be activated both the Redux Framework plugin (v3.6.18), with WooCommerce (v.4.1.1), in Wordpress (v5.4.1).

## Expected Behavior

With the Redux Framework plugin activated, the Add To Cart button and functionality should appear.

## Actual Behavior

When I activate the Redux Framework plugin, the Add To Cart button disappears, everywhere it should appear.

## Any Error Details (PHP/JavaScript)

There are no detected errors. Nor in console, nor in logs.

**Comment by websalacarte** [comment]
Hi, 
I help admin a site (supernautica.com) that uses WooCommerce extensively, and we use the Redux Framework plugin to place important info that enables sales.

We have WordPress v5.4.1, WooCommerce v4.1.1, and the latest Redux Framework plugin v3.6.18.
The Add To Cart button was not showing (all over), and after deactivating one by one each of the plugins we have, the Add To Cart button shows up again when deactivating just the Redux Framework plugin, and it disappears again when reactivating it.

There are no messages in the console, other than non-unique id's warnings.

We need the Redux Framework plugin activated, in order to run the business. Otherwise, we cannot sell. But if we activate it, there's no Add To Cart button for customers to buy from us.

Are you aware of this issue? In that case, do you have any idea how long can it take to dev a fix?
Do you need any info from us to investigate this issue?

Thank you,
Josep

**Comment by websalacarte** [comment]
In the eror_log I see this message: 
"[Thu May 28 14:06:32.494307 2020] [fcgid:warn] [pid 1134740:tid 139644536575744] (32)Broken pipe: [client XX.XXX.XXX.XXX:XXXXX] mod_fcgid: ap_pass_brigade failed in handle_request_ipc function"

**Comment by nanyali** [comment]
I have the same issue when i try to open  my wocoomerce cart appears as white area i try to edit some css code to appears correct but in mobile view there is overlaping window
i used Redux Framework plugin (v3.6.18), with WooCommerce (v.4.1.1),
http://support.redux.io/?
id=tbo7S6u81iznGB9DIOf54lus9A0Y%2BNEm9NGjVIZal6jEuTEjtvxj7QoeG%2FD3JNktq%2F4O674TxqdlhgJyiWL9UA%3D%3D

**Comment by dovy** [comment]
We don’t have any of those functions in our code. Are you sure it’s not a wooconmerce issue?

Also try installing redux 4 and see if that revolves it. https://github.com/reduxframework/redux-framework-4

**Comment by dovy** [comment]
Confirmed, this isn't Redux.  ;) 

https://stackoverflow.com/questions/33811543/php-and-mod-fcgid-ap-pass-brigade-failed-in-handle-request-ipc-function

Contact WooCommerce for further support. Best of luck!
