### ISSUE TITLE
Create a new field

### ISSUE THREAD

**Issue by DoNgocPhuc** [reduxframework/redux-framework#3723]
Hi, I want create a new BUTTON field that the default field in Redux not have. Can you tell me how I make it.Thanks

**Comment by dovy** [comment]
Here you go.  :)   It's pretty easy to make your own custom field in Redux.

https://docs.redux.io/guides/basics/using-extensions.html#creating-a-custom-extension

**Comment by dovy** [comment]
One side note, this will change a little with the release of Redux 4. I'd strongly suggest you build/test using that new approach. I'll be updating the boilerplate repo soon.
