### ISSUE TITLE
Update option value depending on URL parameter

### ISSUE THREAD

**Issue by thimfy** [reduxframework/redux-framework#3730]
Is it possible to change option value from URL so that we can use it for showing multiple option in demos.
No success with it...
https://github.com/reduxframework/redux-framework/wiki/Update-an-option-outside-the-options-panel

**Comment by thimfy** [comment]
Its been year i am looking to try this but no success is there anything i can do or not?

**Comment by dovy** [comment]
A year? You posted this 4 days ago.

It's very possible to update values outside of Redux. You could use the Redux API: https://docs.redux.io/configuration/api.html#available-methods

See Redux::set_option (Redux::setOption)
