### ISSUE TITLE
PHP 7.4 Deprecation Warning

### ISSUE THREAD

**Issue by vzani** [reduxframework/redux-framework#3732]
There´s a deprecation warning when running redux-framework on PHP 7.4

Deprecated: Function get_magic_quotes_gpc() is deprecated in wp-content/plugins/redux-framework/ReduxCore/framework.php on line 2821

**Comment by dovy** [comment]
This is resolved in Redux 4. The release is imminent. https://github.com/reduxframework/redux-framework-4
