### ISSUE TITLE
Deprecated: get_row_css_class is deprecated since version 4.2 (will be removed in 6.0) with no alternative available.

### ISSUE THREAD

**Issue by iz-sathish** [reduxframework/redux-framework#3733]
Hi, i have your theme and Visual Composer latest version plugin only. but, i am facing Deprecated: get_row_css_class is deprecated since version 4.2 (will be removed in 6.0) with no alternative available. in \wp-includes\functions.php on line 4724

Please do the needful.

Thanks.

**Comment by dovy** [comment]
Hey there! I fear we didn't build your theme. If you do a search in our repo (https://github.com/reduxframework/redux-framework/search?q=get_row_css_class&unscoped_q=get_row_css_class) you'll see we don't use that function at all.

You will need to contact your theme author. Best of luck to you!
