### ISSUE TITLE
Class 'Redux_Typography' not found

### ISSUE THREAD

**Issue by mikeshiftone** [reduxframework/redux-framework#3737]
Receiving the following error suddenly, and can't find the reason or to resolve it:
Error thrown
Class 'Redux_Typography' not found

https://support.redux.io/?id=49HH6UmHyVjs6pNbnyHWYabeAFM8FgrQcktZteem7cxY1achR1WOenumwcWyCYaU4KwtKIxZ7SF9SlDNu6pXOA%3D%3D

**Comment by dovy** [comment]
Try this version or the newest code from this repo. https://downloads.wordpress.org/plugin/redux-framework.4.0.4.1.zip

**Comment by mikeshiftone** [comment]
Thanks for the quick response. I seem to get the same error with this version.

**Comment by dovy** [comment]
Gah, I wonder if I pushed the wrong code. I’ll have to get back to you later today. Away from the computer.

**Comment by mikeshiftone** [comment]
Thanks, really appreciated!

**Comment by dovy** [comment]
Are you still around? I have a new version you can test with. Try this code out. I tested it with your theme. https://downloads.wordpress.org/plugin/redux-framework.4.0.4.2.zip

Make sure to delete any other versions of Redux from your instance before you install this.

**Comment by mikeshiftone** [comment]
Yippee!! Thank you very very much! This is a new client's website that we literally just started looking at to give the site an overhaul of improvements, and the day we started they got this error, so it looked really bad on our side (as if we broke it), so you really saved us! What was the issue - just updates?

**Comment by dovy** [comment]
We did a soft release of Redux 4, a complete overhaul of Redux that is 2+ years in the making. I fixed the last bit bug it would seem. Glad I was able to help. 

If you want to see something cool go to Gutenberg (the new block editor) and click on library. ;)
