### ISSUE TITLE
Encountered fatal error after updating the plugin

### ISSUE THREAD

**Issue by aljonderrickofficial** [reduxframework/redux-framework#3738]

**Comment by aljonderrickofficial** [comment]
Hi, I encountered an error on my site after updated the Redux Framework to its latest version which released 57 mins ago. Can you please check?

**Comment by dovy** [comment]
Can you please give me some details? Such as what version of the Redux plugin you were installing and what theme you are using? Please email support@redux.io. We're here for you!

**Comment by dovy** [comment]
Also your website please.

**Comment by aljonderrickofficial** [comment]
**Here's the error.**

Fatal error: Uncaught Error: Class 'Redux_Typography' not found in /home/twcorangeandberg/public_html/wp-content/plugins/redux-framework/redux-core/inc/classes/class-redux-output.php:181 Stack trace: #0 /home/twcorangeandberg/public_html/wp-includes/class-wp-hook.php(287): Redux_Output->enqueue('') #1 /home/twcorangeandberg/public_html/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array) #2 /home/twcorangeandberg/public_html/wp-includes/plugin.php(478): WP_Hook->do_action(Array) #3 /home/twcorangeandberg/public_html/wp-includes/script-loader.php(2294): do_action('wp_enqueue_scri...') #4 /home/twcorangeandberg/public_html/wp-includes/class-wp-hook.php(287): wp_enqueue_scripts('') #5 /home/twcorangeandberg/public_html/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array) #6 /home/twcorangeandberg/public_html/wp-includes/plugin.php(478): WP_Hook->do_action(Array) #7 /home/twcorangeandberg/public_html/wp-includes/general-template.php(2884): do_action('wp_head') #8 /home/twcorangeandberg/pu in /home/twcorangeandberg/public_html/wp-content/plugins/redux-framework/redux-core/inc/classes/class-redux-output.php on line 181
There has been a critical error on your website.


Plugin version is: Redux Framework 4.0.5

Website is: thewaxingco.com

**Comment by dovy** [comment]
Watch this video to roll back to a previous version of Redux: https://www.youtube.com/watch?v=oaiAzmpgbYU

3.6.18 is the last stable and I have rolled back on WP.org to that version so no one else suffers as you do. I must admit, I am a little perplexed. Would you be willing to work with me to try to get to the root of this issue?

**Comment by aljonderrickofficial** [comment]
Sorry, I can't as I am not capable of doing this kind of issue. I am just working with the maintenance of our site. Thank you for this. I'll try it.

**Comment by aljonderrickofficial** [comment]
Its working properly now. Thanks for your help Dovy. 👍

**Comment by dovy** [comment]
I'll do my best to resolve your issues locally so you can upgrade next time with confidence.

**Comment by aljonderrickofficial** [comment]
Really appreciate it. Thank you so much!

**Comment by dovy** [comment]
We've resolved the concern. You should be good to upgrade to 4.0.6. Apologies for the issues.
