### ISSUE TITLE
Redux Lite issue

### ISSUE THREAD

**Issue by xplotech** [reduxframework/redux-framework#3740]
Support,

We got this issue with your plugin:

Howdy!

Since WordPress 5.2 there is a built-in feature that detects when a plugin or theme causes a fatal error on your site, and notifies you with this automated email.

In this case, WordPress caught an error with one of your plugins, Redux Lite.

First, visit your website (https://www.djsproduction.xyz/) and check for any visible issues. Next, visit the page where the error was caught (https://www.djsproduction.xyz/wp-admin/post.php) and check for any visible issues.

Please contact your host for assistance with investigating this issue further.

If your site appears broken and you can't access your dashboard normally, WordPress now has a special "recovery mode". This lets you safely login to your dashboard and investigate further.

https://www.djsproduction.xyz/wp-login.php?action=enter_recovery_mode&rm_token=Sm0MgZZhfwRKKCivnvY9sT&rm_key=BSmiT5qvKsHTu6EiQAcmZ9

To keep your site safe, this link will expire in 1 day. Don't worry about that, though: a new link will be emailed to you if the error occurs again after it expires.

When seeking help with this issue, you may be asked for some of the following information:
WordPress version 5.4.2
Current theme: SoundRise Child (GroovyMenu) (version 1.0)
Current plugin: Redux Lite (version 4.0.7)
PHP version 7.4.8

Error Details
=============
An error of type E_ERROR was caused in line 128 of the file /home/djspryfxat/public_html/wp-content/plugins/redux-framework/redux-core/inc/classes/class-redux-options.php. Error message: Uncaught Error: Call to a member function get() on null in /home/djspryfxat/public_html/wp-content/plugins/redux-framework/redux-core/inc/classes/class-redux-options.php:128
Stack trace:
#0 /home/djspryfxat/public_html/wp-content/plugins/soundrise-music/admin/options.php(1785): Redux_Options->get('widget_title_up...', NULL)
#1 /home/djspryfxat/public_html/wp-content/plugins/soundrise-music/includes/class/widget.class.php(41): soundrise_music_get_option('widget_title_up...')
#2 /home/djspryfxat/public_html/wp-content/plugins/soundrise-music/includes/shortcodes.php(117): Iron_Music_Widget::is_widget_title_uppercase()
#3 /home/djspryfxat/public_html/wp-includes/shortcodes.php(343): iron_shortcode_events(Array, '', 'iron_events')
#4 [internal function]: do_shortcode_tag(Array)
#5 /home/djspryfxat/public_html/wp-includes/shortcodes.php(218): preg_replace_callback('/\\[(\\[?)(iron_e...', 'do_shortcode_ta...', '[vc_row iron...')
#6 /home/djspryfxat/public_html/wp-includes/class-wp-hook.php(287): do_shortcode('

___________________________________

**Comment by dovy** [comment]
What version of Redux are you running? Also what theme do you have and what is the url to the website? Thank you.

**Comment by dovy** [comment]
Ha, sorry I didn’t read the full message. Please upgrade to Redux 4.1.5.

**Comment by xplotech** [comment]
We are using Redux: Version 4.1.5
Url: https://www.djsproduction.xyz
Theme: SoundRise

**Comment by dovy** [comment]
Thanks for that. We haven’t had a chance to test that theme. Would you be willing to send a copy of that theme via wetransfer.com to dovy@redux.io if that’s ok. Then watch this video to downgrade to 3.6.18 until I resolve this. :). https://www.youtube.com/watch?v=oaiAzmpgbYU

**Comment by xplotech** [comment]
We have also rollback to 3.6.18

**Comment by dovy** [comment]
Great. I’ll get this resolved and then ask you to test. Thank you.

**Comment by xplotech** [comment]
thanks so much

**Comment by dovy** [comment]
Ok, so your theme uses Redux 2.0, a SUPER old version (nearly 6-8 years old?). First I tried to convert it dynamically, but your theme developers have modified it a ton. I just pushed to Redux a different class name for our Redux_Options class as not to conflict. You should now be able to use the Redux 4.1.6 without any issues.  :)

Let me know if you have any problems!
