### ISSUE TITLE
V4.1.3 Break WP-Bootstrap-Blocks Guttenberg Blocks

### ISSUE THREAD

**Issue by drewskix86** [reduxframework/redux-framework#3741]
After updating to Redux 4.1.7 Gutenberg Editor no longer loaded wp-bootstrap-blocks block types with the error 'Your site doesn't include support for the "wp-bootstrap-blocks/container" block'.

Incrementally rolled back versions to 4.1.2 where the issue was resolved and confirmed 4.1.3 reintroduces issue.

WP-Bootstrap-Blocks v2.4.0.

**Comment by dovy** [comment]
Have you tried 4.1.7?

**Comment by dovy** [comment]
Can you provide your theme please?

**Comment by dovy** [comment]
I just tested locally and I can't experience this issue with that plugin.

Would you be willing to share your actual theme via wetransfer.com to dovy@redux.io. Or if you wanted to save time you could setup access to your admin panel and I can debug quickly.

Most bugs I can fix pretty quick, but it's really hard to resolve things I can't see. Thank you for your patience!

**Comment by drewskix86** [comment]
Issue appears to be resolved with v4.1.8
