### ISSUE TITLE
First argument is expected to be a valid callback 

### ISSUE THREAD

**Issue by alfredofaccipieri** [reduxframework/redux-framework#3746]
After installing new version:

First argument is expected to be a valid callback in /customers/1/9/6/faccipieri.com/httpd.www/wp-content/plugins/redux-framework/redux-core/class-redux-core.php on line 273 Warning: Cannot modify header information - headers already sent by (output started at /customers/1/9/6/faccipieri.com/httpd.www/wp-content/plugins/redux-framework/redux-core/class-redux-core.php:273) in /customers/1/9/6/faccipieri.com/httpd.www/wp-includes/functions.php on line 6221 Warning: Cannot modify header information - headers already sent by (output started at /customers/1/9/6/faccipieri.com/httpd.www/wp-content/plugins/redux-framework/redux-core/class-redux-core.php:273) in /customers/1/9/6/faccipieri.com/httpd.www/wp-admin/includes/misc.php on line 1282 Warning: Cannot modify header information - headers already sent by (output started at /customers/1/9/6/faccipieri.com/httpd.www/wp-content/plugins/redux-framework/redux-core/class-redux-core.php:273) in /customers/1/9/6/faccipieri.com/httpd.www/wp-admin/admin-header.php on line 9

**Comment by dovy** [comment]
What theme are you using? I will help you resolve this. I am sorry you're having any issues at all!

**Comment by alfredofaccipieri** [comment]
Hello! I use CraftFactory Versione: 1.0 Di: Dannci & Themnific



Il 6 agosto 2020 20:32:21 +02:00, Dovy Paukstys <notifications@github.com> ha scritto:

**Comment by dovy** [comment]
This should be resolved in the version just released, Redux 4.1.14. Please let me know if it works for you. So sorry for the delay. This was a tough edge case.

If that doesn't work please let me know.
