### ISSUE TITLE
Compiler not working with > character for first child

### ISSUE THREAD

**Issue by neiltipo** [reduxframework/redux-framework#3747]
After updating to Version 4.1.13 the redux compiler seems to not work when I use the '>' character. e.g. `'compiler'   => array( '.site-navigation ul > li a' ),`. When I remove the > character is seems to work. Is this a know issue?

**Comment by dovy** [comment]
Oh how interesting. This is probably due to an escape attribute. Does it break, or is the CSS sent just excluding that >?

**Comment by neiltipo** [comment]
Hi,
It does not break it just does not write the css to my dynamic-css file, as soon as I delete the ‘>' it it works but I need to target first li’s. ?

Great plugin bye the way!!

Kind Regards,
Neil Tipping

**Comment by neiltipo** [comment]
Although it works on another part of my options 

.entry-meta li > i

? Very strange

Kind Regards,
Neil Tipping

**Comment by dovy** [comment]
Well that is odd. Then I'll need your exact code to test.

Can you dig in a little and see why? Do you have a required set? If the field is not visible the output is filtered out.

**Comment by dovy** [comment]
And thanks for the kind works!

**Comment by dovy** [comment]
I THINK I've fixed it. Please try the newest version of Redux 4.

**Comment by dovy** [comment]
Closing for lack of response. Please let me know if this issue still persists.
