### ISSUE TITLE
 URGENT: New version hide “Add to Cart” button on my ecommerce site

### ISSUE THREAD

**Issue by Mosesodoz** [reduxframework/redux-framework#3748]
I recently create a new eccommerce website. Of a sudden, I discovered that the "Add to Cart" button was not visible. Instead, it wrote "View Product". I deactivate most of my plugins and reactivate one after the other to discovered which one is causing the problem, of which I later found out that it's the Redux plugin. I've updated and also back-dated the Redux plugin, but it's still not working. I use Electro theme. My website is https://pcplaceng.com

**Comment by STV11C** [comment]
Hi @Mosesodoz, I'm a user of Redux and thought to try and help you out. Looking at the website link you provided it is only a Notice page. Can you please provide the link to the site you are having issues with?

**Comment by dovy** [comment]
Can you use WP Rollback and install Redux 3.6.18 and see if that fixes your concern?

**Comment by Mosesodoz** [comment]
> Hi @Mosesodoz, I'm a user of Redux and thought to try and help you out. Looking at the website link you provided it is only a Notice page. Can you please provide the link to the site you are having issues with?

Hi @STV11C, thanks for your response. I actually put the website on "Maintenance mode" before now. But I've removed it now

**Comment by Mosesodoz** [comment]
> Can you use WP Rollback and install Redux 3.6.18 and see if that fixes your concern?

@dovy I just rolled it back to Redux 3.6.18, but it's still the same thing. It doesn't work

**Comment by Mosesodoz** [comment]
@dovy The website link is https://pcplaceng.com

**Comment by dovy** [comment]
If it's not working with 3.6.18 the error is in the theme then. You'll need to contact the theme author.

I wish you the best!

**Comment by Mosesodoz** [comment]
> If it's not working with 3.6.18 the error is in the theme then. You'll need to contact the theme author.
> 
> I wish you the best!

@dovy That's not true, because, I used it for another website......Check this website out and compare it to the one above: www.kkbod.com

**Comment by Mosesodoz** [comment]
@dovy That's not true because I used it on another website with the same theme........but another version

**Comment by dovy** [comment]
So perhaps the saving went awry... Try re-saving your panel if you have 3.6.18?
