### ISSUE TITLE
Disabling Templates (Blocks) in Redux Lite

### ISSUE THREAD

**Issue by Nyota** [reduxframework/redux-framework#3751]
What would be the best way to disable the templates link that appears when creating a new post/page? I haven't found any information on this in the documentation or other support tickets and issues. The new blocks aren't currently needed so it would be great to disable them. Thanks for a great plugin and great work!

**Comment by dovy** [comment]
Hey there! I fear we haven't built a way to disable templates at all. If you want to truly disable then you must embed the redux-core directly in your product.

Blocks are the wave of the future, and we are doing our best to adapt.

Let me know if I can help with anything else.
