### ISSUE TITLE
Uncaught Error: Call to a member set on null in

### ISSUE THREAD

**Issue by jomiarts** [reduxframework/redux-framework#3752]
![download](https://user-images.githubusercontent.com/50069764/89985796-2a47f300-dcae-11ea-9d37-1d7886538076.png)
Can you help us with this error that keeps sending to our email? 
Thanks.

**Comment by dovy** [comment]
I just put a small fix for this inside the core. The fix is in 4.1.15 that I am pushing here shortly. Thanks for reporting this!

**Comment by dovy** [comment]
P.S. You may want to show this to wp-jobsearch. They were sending a null value to be set in the database.  ;)
