### ISSUE TITLE
Error load static file (js, css) when Embedding Redux into Theme

### ISSUE THREAD

**Issue by ndstyle** [reduxframework/redux-framework#3753]
### Support Hash
Unable to generate Support Hash

### Setup
Ubuntu 20.04
PHP Version 7.4.3
10.3.22-MariaDB
Wordpress 5.5

### Installation

- I installed and configured wordpress 5.5 with the theme twentynineteen.
- I downloaded Redux Framework version 4.1.14 and put it inside the twentynineteen theme folder.

In the file function I tried to insert the code to do the Embedding of the plugin following the instructions found at this url: [https://docs.redux.io/guides/advanced/embedding-redux.html](https://docs.redux.io/guides/advanced/embedding-redux.html)

I tried to insert this code inside the file function:

```
if ( !class_exists( 'ReduxFramework' ) && file_exists( dirname( __FILE__ ) . '/redux-framework/redux-core/framework.php' ) ) {
    require(dirname( __FILE__ ) . '/redux-framework/redux-core/framework.php');
}
```

OR

```
if ( !class_exists( 'ReduxFramework' ) && file_exists( dirname( __FILE__ ) . '/redux-framework/redux-framework.php' ) ) {
    require(dirname( __FILE__ ) . '/redux-framework/redux-framework.php');
}

```
### Error
In both cases, when you enter the wordpress administration area panel, there are many 404 errors in the browser console because you don't load several files:

- /redux-framework/redux-core/assets/img/redux-powering-up.svg
- /redux-framework/redux-core/assets/img/logo--color.svg
- /redux-framework/redux-core/inc/welcome/js/redux-banner-admin.js
- /redux-framework/redux-core/inc/welcome/css/redux-banner.css
- /redux-framework/redux-core/inc/welcome/js/redux-banner-admin.js
- /redux-framework/redux-core/assets/img/redux-powering-up.svg
- /redux-framework/redux-core/assets/img/logo--color.svg

If I install the plugin normally everything works.

If you need more details, ask away. 

Can you help me?
Danilo

**Comment by dovy** [comment]
Try the newest code on .org or the redux-framework-4 repo. Let me know if that fixes it. If not, can you send me a copy of your code to dovy@redux.io via wetransfer.com and I'll get it fixed pretty quick. I know exactly where the problem is.

**Comment by ndstyle** [comment]
Hi @dovy.

Thank you so much for your answer. I tried the new code but I always find the same mistake. I'll send you the code as requested.

Kind Regards
Danilo

**Comment by kprovance** [comment]
Hi!

Redux 3.x has reached its end of life.  We will no longer be maintaining it.  Please update to Redux v4, which will be moved to this repository shortly.  Should you should discover the same issue with Redux v4, please rereport the issue, making sure to supply the required information request via the New Issue form.

Thank you for choosing Redux.

- Kev
