### ISSUE TITLE
Composer install problem

### ISSUE THREAD

**Issue by angelorocha** [reduxframework/redux-framework#3755]
I'm trying to install redux on my theme via composer. When I add the dependency in my composer.json the installation of the package is outside my "vendor" folder.

My composer.json
```
  "config": {
    "vendor-dir": "lib"
  },
  "require": {
    "php": ">=7.2.0",
    "monolog/monolog": "1.12.0",
    "cmb2/cmb2": "dev-master",
    "dompdf/dompdf": "^0.8.3",
    "phpoffice/phpspreadsheet": "^1.9",
    "php-ffmpeg/php-ffmpeg": "^0.14.0",
    "php-ffmpeg/extras": "^0.3.1",
    "redux-framework/redux-framework": "*"
  },
```

After executing the command, a directory tree is created at the root of my theme: wp-content/plugins/redux

How do I fix this?

**Comment by prosenjit-manna** [comment]
"config": {
      "vendor-dir": "vendor"
   },

**Comment by dovy** [comment]
Good call @prosenjit-manna
