### ISSUE TITLE
Latest version broke the site settings

### ISSUE THREAD

**Issue by skullwritter** [reduxframework/redux-framework#3757]
## Support Hash
cannot generate since it's a fatal error

## Steps to reproduce
update to latest version available on WordPress repo

## Expected Behavior
everything working fine until update

## Actual Behavior
updated from 4.1.14 to 4.1.15

## Any Error Details (PHP/JavaScript)
```
Fatal error: Uncaught Error: Call to undefined method Redux::instance() in 
/home/{hidden}/web/{hidden}/public_html/app/plugins/redux-framework/redux-core/inc/classes/class-redux-class.php:60 Stack trace: 
#0 /home/{hidden}/web/{hidden}/public_html/app/plugins/redux-framework/redux-core/inc/classes/class-redux-enqueue.php(89): Redux_Class->core() 
#1 /home/{hidden}/web/{hidden}/public_html/app/plugins/{hidden}/third_party/ReduxCore/framework.php(1702): Redux_Enqueue->init() 
#2 /home/{hidden}/web/{hidden}/public_html/wp/wp-includes/class-wp-hook.php(287): ReduxFramework->_enqueue('toplevel_page_d...') 
#3 /home/{hidden}/web/{hidden}/public_html/wp/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array) 
#4 /home/{hidden}/web/{hidden}/public_html/wp/wp-includes/plugin.php(478): WP_Hook->do_action(Array) 
#5 /home/{hidden}/web/{hidden}/public_html/wp/wp-admin/admin-header.php(102): do_action('admin_enqueue_s...', 'toplevel_page_d...') 
#6 /home/{hidden}/web/{hidden} in /home/{hidden}/web/{hidden}/public_html/app/plugins/redux-framework/redux-core/inc/classes/class-redux-class.php on line 60
```

**Comment by dovy** [comment]
Wow, that is odd. You had 4.1.14 without any issues? Is this on a server or local? I'd love to debug, but I need to mirror your setup.

I didn't change anything related this the last item. Is there another Redux class being loaded? Perhaps Redux 3 is being included?

**Comment by skullwritter** [comment]
@dovy was on a server, a reimport of the latest reduxCore folder, broke the settings, trying to figure it out.
I can tell you the redux version that I've imported the redux folder (reduxCore): 3.6.18 (replaced by now, but I have a git of the plugin that isn't changed until I figure this out.).
Maybe, will be important to have a warning then updating the plugin that if the redux folder (reduxCore) is from 3.6.18, it might break the settings.

**Comment by skullwritter** [comment]
@dovy about the reimport part 2:
Wrong folder, should have imported the `redux-core` folder, not the `reduxCore`

**Comment by dovy** [comment]
So error in our code or yours? Just trying to see if I need to fix something. ;)

**Comment by skullwritter** [comment]
@dovy as the first comment said, probably it's some kind of conflict with the both versions 
- 3.6.18 (the integrated with the plugin)
- 4.1.15 (plugin redux-framework - theme)

**Comment by skullwritter** [comment]
> @dovy as the first comment said, probably it's some kind of conflict with the both versions
> 
> * 3.6.18 (the integrated with the plugin)
> * 4.1.15 (plugin redux-framework - theme)

When I've fixed the incompatibility, the only thing that worked was putting the new version of the `redux-core` folder.
What I've to recommend to other developers is to update it as soon as possible since they can come with the same problem

**Comment by dovy** [comment]
I will try and find a way to fix it as well. I just have to find out why, haha. I probably will import the api immediately in framework.php instead of waiting.

**Comment by skullwritter** [comment]
@dovy for now, that can be ok, but, and i don't believe that i'm posting this, the better way is to warn administrators that they have to update their redux embed version and block the update until they do.

**Comment by dovy** [comment]
My goal is to have redux 4 override any embedded versions. ;)

**Comment by skullwritter** [comment]
Yes, it's a good goal, but until you cannot make it in that form, consider asking developers to update the embed.

In my case I've made it compatible with it... but i'll have to check the things again to be certain that the bug does not come again...
```

/**
 * Optional - Redux Framework Core Class and the options, 
 * It's optional. if we have the plugin, ignore the embed
 */
if (!class_exists('ReduxFramework') && file_exists(plugin_dir_path( dirname( __FILE__ ) ) . 'third_party/redux-core/framework.php')){
    require_once plugin_dir_path( dirname( __FILE__ ) ) . 'third_party/redux-core/framework.php'; 
}
require_once plugin_dir_path( dirname( __FILE__ ) ) . 'configs/redux_configuration.php';
```

With that said, I also make things in a "plug-in plug-out way, so it's kinda the same...

#relatable 🤣🤣

**Comment by skullwritter** [comment]
@dovy i'll close this for now, but if needed open it again and i'll be glad to help

**Comment by dovy** [comment]
Can you try the newest code in the repo? I think my load_first hook was not firing properly. ;)
