### ISSUE TITLE
Callback on Select not working

### ISSUE THREAD

**Issue by mneitz** [reduxframework/redux-framework#3758]
## Support Hash
http://support.redux.io/?id=wsAgPwbI4uOmwesxh%2Bfa5Un2vBzJ%2BiYQz3J7y3HBPbwpXpxM%2Bab2MQsDvqGT2Lq1jHGg%2FzKewEmWlbcU8yHBPA%3D%3D

## Steps to reproduce
I included the callback request in an select field and defined an function according to the examples in the documentation

## Expected Behavior
I am using the following definition and expected that the function will be called to return the valid values:
                'data'     => 'callback',
                'args'     => 'mesu_redux_callback_product_and_pages',

## Actual Behavior
The function is not be called because of the following error:
call_user_func() expects parameter 1 to be a valid callback, no array or string given.

## Any Error Details (PHP/JavaScript)
PHP Warning:  call_user_func() expects parameter 1 to be a valid callback, no array or string given in /var/www/vhosts/vivo.academy/httpdocs/wp-content/plugins/kongress-warehouse/options/ReduxCore/framework.php on line 1083.

If I debug the given argument ( $args ) in #1083 the name of the callback will be transfered but in the following form:

array(1) { ["mesu_redux_callback_product_and_pages"]=> string(0) "" }

so the code:
#1080  $data = call_user_func( $args[0] );
will deliver NULL

**Comment by dovy** [comment]
We're on it.

**Comment by dovy** [comment]
This has been fixed. Please try the most recent code here in this repo.

**Comment by mneitz** [comment]
I tested the last version in this repository... but it is 7 Month old and still produce the same error.

**Comment by dovy** [comment]
Yea, wrong repo. https://github.com/reduxframework/redux-framework-4

I really just need to merge the repos...

**Comment by mneitz** [comment]
So the fix will not be available in version 3x -I am not ready to move to 4x

**Comment by dovy** [comment]
Correct. Redux 3 has reached end of life especially with WordPress 5.5 removing jQuery Migrate. We have worked to make the shift to Redux 4 inconsequential. Maybe give it a try?

**Comment by mneitz** [comment]
I am not able to switch, as I do have so many plugins wich are depending on each other... can i fix it with 

#1080 $data = call_user_func( $args[0] );  => #1080 $data = call_user_func( $args );

**Comment by dovy** [comment]
It should probably work... I just can't update the Redux 3 code further. You would have to do it.

I did make most everything work fine between 3 and 4. You should try the newest version of 4. I added some compatibility fixes.

**Comment by mneitz** [comment]
Hi Dovy
I did it and the transition was very smooth  THX.
