### ISSUE TITLE
Flash White my site double open i mean white flash

### ISSUE THREAD

**Issue by sercans** [reduxframework/redux-framework#3759]

**Comment by sercans** [comment]
i have problem on my web site -> yollando.com 

double open with white screen if i deactive redux-framework plugins everyting is okay but i need it :D 

can u help me

**Comment by dovy** [comment]
So I wish I could. The issue is your theme author has coded a lot of the design in JavaScript, which will cause a flash on load. You'll need to reach out to them. The reason you see it with Redux is that Redux seems to drive your theme.

Haha, seems like you solved it?

**Comment by sercans** [comment]
ye thanks for help i added css
body {
	-webkit-transition: none !important;
    -moz-transition: none  !important;
    transition: none !important;
    opacity: 1 !important;
}

**Comment by dovy** [comment]
Awesome. Glad you found a solution.
