### ISSUE TITLE
el.find(...).live is not a function

### ISSUE THREAD

**Issue by Alamin407** [reduxframework/redux-framework#3762]
Hi,
I am a WordPress developer. I found a error in your core file. When I use the slides fields in the functions the slides fields are not working because of there are a error .live is not a function now in jquery 1.9. .live is not available in the jquery latest version. Please change the function .live and replace there .on function.

Thanks

**Comment by dovy** [comment]
So Redux 3 has reached its end of life. Please use Redux 4. I will merge it into this repo soon. https://github.com/reduxframework/redux-framework-4
