### ISSUE TITLE
Custom redux options in multisite network using SUBDIRECTORY instead subdomain

### ISSUE THREAD

**Issue by masterbip** [reduxframework/redux-framework#3764]
Hello.
I have a multisite network configured as subdomains and redux works perfectly.
Now I am seting up another multisite network but this time using subdirectories.
The same template with redux custom config file works fine in subdomain multisite network
But I cant make it work in subdirectory multisite network. I cant see menu with redux options ...
What Am I missing here?

**Comment by kprovance** [comment]
Hi!

Redux 3.x has reached its end of life.  We will no longer be maintaining it.  Please update to Redux v4, which will be moved to this repository shortly.  Should you should discover the same issue with Redux v4, please rereport the issue, making sure to supply the required information request via the New Issue form.

Thank you for choosing Redux.

- Kev
