### ISSUE TITLE
WP 5.6  warnings

### ISSUE THREAD

**Issue by risto987** [reduxframework/redux-framework#3766]
## WP 5.6 warnings coming from Redux Framework

Please check this problem occurred in the new WordPress veriosn.
I test this by disabling one by one plugin.

`<b>Warning</b>:  array_intersect_key(): Expected parameter 1 to be an array, string given in <b>C:\xampp\htdocs\meks\herald\wp-includes\rest-api\class-wp-rest-server.php</b> on line <b>1402</b><br />`

**Comment by risto987** [comment]
It's happening on adding/editing posts or pages.

**Comment by dovy** [comment]
This has been resolved in 4.1.24. Please update your copy of Redux.

**Comment by risto987** [comment]
Cool
Thank you
