### ISSUE TITLE
WordPress version 5.6 issue with Redux Plugin

### ISSUE THREAD

**Issue by etwordpress01** [reduxframework/redux-framework#3767]
Hello, We are using your plugin into our themes. When we updated latest version of WordPress 5.6 then bellow issues appear while editing pages and posts. 

Warning: array_intersect_key(): Expected parameter 1 to be an array, string given in G:\xampp\htdocs\www\doctreat\wp-includes\rest-api\class-wp-rest-server.php on line 1402

![2](https://user-images.githubusercontent.com/31212934/101921852-42456a00-3bef-11eb-9a59-8b0d580014b6.png)

When we disable Redux plugin then issues gone.

Please help us

Thanks

**Comment by ctiger** [comment]
Same problem on WP 5.6 & Redux 4.1.23

**Comment by dovy** [comment]
Update to 4.1.24. That's the version which fixes it.  ;)

**Comment by ctiger** [comment]
Thx. 4.1.24 - is work!

**Comment by dovy** [comment]
Fantastic! Have a great day.
