### ISSUE TITLE
PHP Notice

### ISSUE THREAD

**Issue by Stas0238** [reduxframework/redux-framework#3768]
Recently one of my clients updated Redux Framework plugin on his WP to  v.4.1.24 of plugin and reported my about issues he had. I found that he uses 7.1 version of PHP and with debug enabled on admin dashboard is shown a few notices.

PHP Notice:  Only variables should be passed by reference in /public_html/wp-content/plugins/redux-framework/redux-core/inc/classes/class-redux-functions-ex.php on line 311
[14-Dec-2020 09:13:45 UTC] PHP Notice:  Only variables should be passed by reference in /public_html/wp-content/plugins/redux-framework/redux-core/inc/classes/class-redux-functions-ex.php on line 312

I found out the reason of notices and you can use my fix for next version of plugin

Before you have these lines of code -> http://prntscr.com/w2b65e and why you have 2 times the same code ?

You have to change that code to -> http://prntscr.com/w2b5pk

Notices dissapeared and that's ok now.

Regards, Stas

**Comment by dovy** [comment]
Yes, that's a new warning in PHP, not wanting multiple functions to be run. Thanks for bringing this to my attention.

https://github.com/reduxframework/redux-framework-4/commit/9c57115765b70927e230f25fb9d06efbfbc297cb

It will go out in the next release.  :)
