### ISSUE TITLE
Redux overrides the theme style for P tags

### ISSUE THREAD

**Issue by mohammedeisa** [reduxframework/redux-framework#3769]
## Support Hash
Redux overrides the theme font  style
It adds the following style automatically:
`p {
font-family: Arial, Helvetica, sans-serif;
font-weight: Normal;
font-style: normal;
color: #dd9933;
font-size: 30px;
font-display: swap;
}`

## Steps to reproduce
Activate Redux with TwentyTwentyone
Create a page/post and insert a <P> that includes some text
Check the page/post in the frontend
The text color will be orange

## Expected Behavior
The <p> tag should have the default theme styles

## Actual Behavior
Redux overrides the theme <p> tag style

## Any Error Details (PHP/JavaScript)
No

**Comment by kprovance** [comment]
Hi!

Redux 3.x has reached its end of life.  We will no longer be maintaining it.  Please update to Redux v4, which will be moved to this repository shortly.  Should you should discover the same issue with Redux v4, please rereport the issue, making sure to supply the required information request via the New Issue form.

Thank you for choosing Redux.

- Kev
