### ISSUE TITLE
Redux prints empty style tag

### ISSUE THREAD

**Issue by mohammedeisa** [reduxframework/redux-framework#3770]
## Support Hash
Redux prints empty style tag

## Steps to reproduce

- Activate Redux with a default WordPress theme
- Visit any page in the frontend and check the page source code
- You will find an empty style tag like the following:
- <style type="text/css"></style>

## Expected Behavior
This tag shouldn't be printed to get a clean page

## Actual Behavior
Redux prints empty style tag

## Any Error Details (PHP/JavaScript)
No

**Comment by kprovance** [comment]
Hi!

Redux 3.x has reached its end of life.  We will no longer be maintaining it.  Please update to Redux v4, which will be moved to this repository shortly.  Should you should discover the same issue with Redux v4, please rereport the issue, making sure to supply the required information request via the New Issue form.

Thank you for choosing Redux.

- Kev
