### ISSUE TITLE
Styling issue in the Button Set, an icon appears above the button text

### ISSUE THREAD

**Issue by mohammedeisa** [reduxframework/redux-framework#3771]
## Support Hash
Icons appear above the button text in the button set field.
As per the button set documentation https://devs.redux.io/core-fields/button-set.html#default-argument
There shouldn't be an icon above the button in the button set field.

## Steps to reproduce
Activate Redux
Check the appearance of the button set field

## Expected Behavior
There shouldn't be an icon above the button in the button set field.

## Actual Behavior
Icons appear above the button text in the button set field.

## Any Error Details (PHP/JavaScript)
No

**Comment by kprovance** [comment]
This is resolved in Redux v4.
