### ISSUE TITLE
Redux produces errors that prevent editing pages/posts when Elementor is active

### ISSUE THREAD

**Issue by mohammedeisa** [reduxframework/redux-framework#3772]
## Support Hash
A user complaints that he is not able to edit his pages when Redux and Elementor are active and he gets this message:
The preview could not be loaded
We’re sorry, but something went wrong. Click on ‘Learn more’ and follow each of the steps to quickly solve it.
Click here for preview debug

Another user shared these findings:
The error is caused by this:
PHP Warning: Use of undefined constant REDUX_PLUGIN_FILE – assumed ‘REDUX_PLUGIN_FILE’ (this will throw an Error in a future version of PHP) in …./wp-content/plugins/redux/redux-framework/redux-templates/classes/class-api.php on line 875
which causes the “Headers already sent” error and therefore Elementor does not work.

So I manually replaced REDUX_PLUGIN_FILE in the “class-api.php” file with ‘REDUX_PLUGIN_FILE’ and it worked.

## Steps to reproduce
Not available

## Expected Behavior
The user should be able to edit the pages

## Actual Behavior
The users can't edit the pages

## Any Error Details (PHP/JavaScript)
The preview could not be loaded
We’re sorry, but something went wrong. Click on ‘Learn more’ and follow each of the steps to quickly solve it.
Click here for preview debug

PHP Warning: Use of undefined constant REDUX_PLUGIN_FILE – assumed ‘REDUX_PLUGIN_FILE’ (this will throw an Error in a future version of PHP) in …./wp-content/plugins/redux/redux-framework/redux-templates/classes/class-api.php on line 875

**Comment by dovy** [comment]
Thank you. This has been fixed in the most recent code in this repo and will be included in the 4.1.25 release.
