### ISSUE TITLE
The default button value is set to hidden when you set the default value of the color selection field to empty

### ISSUE THREAD

**Issue by mohammedeisa** [reduxframework/redux-framework#3774]
## Support Hash
The default button value is set to hidden when you set the default value of the color selection field to empty

## Steps to reproduce
Create a color selection field with an empty default value like the following:
`array(
				'id'          => 'opt-color-title',
				'type'        => 'color',
				'output'      => array(
					'background-color' => '.site-background',
					'color'            => '.site-title',
				),
				'title'       => esc_html__( 'Site Title Color', 'your-textdomain-here' ),
				'subtitle'    => esc_html__( 'Pick a title color for the theme (default: #000).', 'your-textdomain-here' ),
				'default'     => '',
				'color_alpha' => true,
			),`
In your admin dashboard, click to select a color
Click clear
You will see that the clear button value is empty and no text inside it.

## Expected Behavior
The button text shouldn't be cleared

## Actual Behavior
The button text is being cleared after you click it

## Any Error Details (PHP/JavaScript)
No errors

## Debug
Line 281 in \wp-admin\js\color-picker.js removes the button value.
self.options.clear.call( this, event );
I'm not sure if we can overcome this behavior or we should report tit to WordPress.

**Comment by kprovance** [comment]
Hi!

Redux 3.x has reached its end of life.  We will no longer be maintaining it.  Please update to Redux v4, which will be moved to this repository shortly.  Should you should discover the same issue with Redux v4, please rereport the issue, making sure to supply the required information request via the New Issue form.

Thank you for choosing Redux.

- Kev
