### ISSUE TITLE
Redux Metabox not load stored value

### ISSUE THREAD

**Issue by lucnham** [reduxframework/redux-framework#3775]
My develop environment:
- PHP version: 7.3
- Wordpress: 5.6
- Redux: 4.1.24
- Redux Pro: 1.0.2

Hello, I have made instructions from the documentation to configure Metabox. The input fields are visible, the value is updated to the database after I publish or update the post. However, the displayed value (admin view) of the fields is incorrect, it loads the default value from the Global option (if any), or leaves it blank if there is no default, although the value in the database is different. This issue affects on all fields.

**Comment by kprovance** [comment]
Hi!

Redux 3.x has reached its end of life.  We will no longer be maintaining it.  Please update to Redux v4, which will be moved to this repository shortly.  Should you should discover the same issue with Redux v4, please rereport the issue, making sure to supply the required information request via the New Issue form.

Thank you for choosing Redux.

- Kev
