### ISSUE TITLE
Pro version fields show some erros!

### ISSUE THREAD

**Issue by ZoOmArts** [reduxframework/redux-framework#3777]
Hi there,

I purchased the pro version. But there some errors after load some fields like "Color Schemes", "Custom Fonts".
Also the "CSS Layout" didn't work! I got this msg: "Field opt-css-layout could not be displayed. Field type css_layout was not found."
Also the metaboxes showing alot of errors here:
<img width="1533" alt="Screen Shot 2021-01-11 at 2 22 42 PM" src="https://user-images.githubusercontent.com/11763471/104182086-93c45d00-5418-11eb-8a5f-b4cdb1997969.png">

Thanks.

**Comment by kprovance** [comment]
Hi!

Redux 3.x has reached its end of life.  We will no longer be maintaining it.  Please update to Redux v4, which will be moved to this repository shortly.  Should you should discover the same issue with Redux v4, please rereport the issue, making sure to supply the required information request via the New Issue form.

Thank you for choosing Redux.

- Kev
