### ISSUE TITLE
Mobile Friendly Issues

### ISSUE THREAD

**Issue by ashvin991** [reduxframework/redux-framework#3778]
Hi all,

I have the redux framework however with the framework my website is not mobile friendly as the page is zoomed in for some reason.

I have checked the website without redux and it works well.

May I please have some assistance if this is a redux issue or the theme.

My website is:  https://www.newlabelsonly.com/2017/03/10/stubble-co-the-stylish-durable-and-perfect-mens-bag/

Thank you!

**Comment by dovy** [comment]
Hey there. This is actually an issue in your theme CSS! If you put this in the customizer to override some CSS, the problems will all go away:

.no-sidebar .row .post-list {
	max-width: 100%;
}

The offending code is found in this file, part of eaglewood. https://www.newlabelsonly.com/wp-content/themes/eaglewood/style.css?ver=1.0.0

Have a great day!
