### ISSUE TITLE
Doc website unavailable:  docs.reduxframework.com

### ISSUE THREAD

**Issue by kakokvantaliani** [reduxframework/redux-framework#3779]
Unable to access website:
[ docs.reduxframework.com]( docs.reduxframework.com)

## Steps to reproduce
Open web browser
Enter  docs.reduxframework.com in address bar

## Actual Behavior
It shows Apache2 Debian Default Page

**Comment by mohammedeisa** [comment]
This will be fixed in the next Redux version.
Please use http://devs.redux.io/ instead
