### ISSUE TITLE
Redux is undefined! field_options_object.js is enqueing before redux.js

### ISSUE THREAD

**Issue by prionkor** [reduxframework/redux-framework#3780]
## Steps to reproduce
Add redux framework to a plugin and option the option page

## Expected Behavior
no js error

## Actual Behavior
redux is not defined throwing from field_options.object.js file

## Fix

The js file is clearly using redux object but dependency is only set for `jquery` and not `redux`. Adding `redux` in the dependency array fixes the issue. 

https://github.com/reduxframework/redux-framework/blob/master/ReduxCore/inc/extensions/options_object/options_object/field_options_object.php#L135

**Comment by mohammedeisa** [comment]
This has been fixed in the master branch. Can you check that?

**Comment by mohammedeisa** [comment]
This has been moved to Redux Pro: https://github.com/reduxframework/redux-pro/issues/12
Closing here.
