### ISSUE TITLE
JS error, type of redux.field_objects undefined?

### ISSUE THREAD

**Issue by prionkor** [reduxframework/redux-framework#3781]
Error: Uncaught TypeError: right-hand side of 'in' should be an object, got undefined

## Steps to reproduce
Add a redux in a plugin with a section and few fields.

## Expected Behavior

No js error

## Actual Behavior

JS error Uncaught TypeError: right-hand side of 'in' should be an object, got undefined

## Possible fix

In redux.js#L640 it might help to check for `undefined` (which is commented out).

**Comment by kprovance** [comment]
Hi!

Redux 3.x has reached its end of life.  We will no longer be maintaining it.  Please update to Redux v4, which will be moved to this repository shortly.  Should you should discover the same issue with Redux v4, please rereport the issue, making sure to supply the required information request via the New Issue form.

Thank you for choosing Redux.

- Kev
