### ISSUE TITLE
Getting an error 'Sanitized value and saved as #FFFFFF instead of #002269.'

### ISSUE THREAD

**Issue by ZCweb** [reduxframework/redux-framework#3783]
Getting an error 'Sanitized value and saved as #FFFFFF instead of #002269.' If I update a color always says that it is sanitized and saved as white even when I change it to white? why is this?

## Support Hash

Goes to 404 not found or with SSL it goes to SSL issue so this link is bad.

## Steps to reproduce

I update a color and I get this: 'Sanitized value and saved as #FFFFFF instead of #002269.' I am using 'Version 4.1.24'

## Expected Behavior

I could use the color

## Actual Behavior

Saw: 'Sanitized value and saved as #FFFFFF instead of #002269.' error and refreshed an it was white. Even if I put in white it makes it white?
## Any Error Details (PHP/JavaScript)

No errors that I see

**Comment by kprovance** [comment]
Hi!

Redux 3.x has reached its end of life.  We will no longer be maintaining it.  Please update to Redux v4, which will be moved to this repository shortly.  Should you should discover the same issue with Redux v4, please rereport the issue, making sure to supply the required information request via the New Issue form.

Thank you for choosing Redux.

- Kev
