### ISSUE TITLE
reduxframework.com/feed/ 404

### ISSUE THREAD

**Issue by jamieburchell** [reduxframework/redux-framework#3784]
## Support Hash

Can't generate - privacy error at https://docs.reduxframework.com/core/generating-a-support-hash

## Steps to reproduce
Check PHP error logs or RSS feed widget on WP dashboard

## Expected Behavior
RSS feed

## Actual Behavior

```
Redux Framework News
RSS Error: A feed could not be found at `http://reduxframework.com/feed/`; the status code is `404` and content-type is `text/html`
```
## Any Error Details (PHP/JavaScript)

```
PHP Notice: A feed could not be found at `http://reduxframework.com/feed/`; the status code is `404` and content-type is `text/html` in wp/wp-includes/class-simplepie.php on line 1728
```

**Comment by kprovance** [comment]
Hi!

Redux 3.x has reached its end of life.  We will no longer be maintaining it.  Please update to Redux v4, which will be moved to this repository shortly.  Should you should discover the same issue with Redux v4, please rereport the issue, making sure to supply the required information request via the New Issue form.

Thank you for choosing Redux.

- Kev
