### ISSUE TITLE
Service Page Style

### ISSUE THREAD

**Issue by zaherhourani** [reduxframework/redux-framework#3785]
Hello There!
I'm using Industrio theme for my WordPress website
I'm using home 4 as my HomePage and trying to use the same page template to show the services "same header and footer"
but the "services" page keeps showing the default header and footer
How to use the Homepage style for my whole website?

**Comment by kprovance** [comment]
Hi!

Redux 3.x has reached its end of life.  We will no longer be maintaining it.  Please update to Redux v4, which will be moved to this repository shortly.  Should you should discover the same issue with Redux v4, please rereport the issue, making sure to supply the required information request via the New Issue form.

Thank you for choosing Redux.

- Kev
