### ISSUE TITLE
Problem Font 

### ISSUE THREAD

**Issue by atiiiiiii** [reduxframework/redux-framework#3786]
Hello,

I cannot change some of the font sizes:
~/monolit/includes/redux-sections/fonts.php

for example in the footer that contains this html code:
<div class="row">
<div class="col-md-6">
     
    <div class="footer-item footer-logo">
        <a href="http://carletto2.winx.bz/" class="ajax"><img src="http://carletto2.winx.bz/wp-content/uploads/2021/02/LOGO-NEW-COMPLETO_NEU.png" alt="footer logo"></a>
    </div>
     
</div>
 
<div class="col-md-2">
    <div class="footer-item">
        <h4 class="text-link">TELEFON</h4>
        <ul>
            <li><a href="#">Carletto: +39 335 600 8785</a></li>
            <li><a href="#">Moritz: +39 331 422 6018</a></li>
        </ul>
    </div>
</div>
 
 
<div class="col-md-2">
    <div class="footer-item">
        <h4 class="text-link">EMAIL</h4>
        <ul>
            <li><a href="#">info@carletto.it</a></li>
        </ul>
    </div>
</div>

 
<div class="col-md-2">
    <div class="footer-item">
        <h4 class="text-link">ADRESSE</h4>
        <ul>
            <li><span>DANTERCEPIES 76, 39048 WOLKENSTEIN</span></li>
            <li> <a href="#" target="_blank">GOOGLE MAPS</a></li>
        </ul>
    </div>
</div>
 
</div>

<div class="row">
<div class="col-md-6"></div>
<div class="col-md-6">
    <div class="footer-wrap">
        <span class="copyright">  produced by WINX. All rights reserved.  
        </span>
        <span class="to-top">To Top</span>
    </div>
</div>
</div>

**Comment by kprovance** [comment]
Hi!

Redux 3.x has reached its end of life.  We will no longer be maintaining it.  Please update to Redux v4, which will be moved to this repository shortly.  Should you should discover the same issue with Redux v4, please rereport the issue, making sure to supply the required information request via the New Issue form.

Thank you for choosing Redux.

- Kev
