### ISSUE TITLE
Undefined index: real_path , 404 Error for CSS and JS

### ISSUE THREAD

**Issue by mehditayebi** [reduxframework/redux-framework#3787]
hi . It gives me an error when I put the framework in my template.
**Error** : 
`Notice: Undefined index: real_path in D:\xampp\htdocs\wordpress\wp-content\themes\my-theme\includes\redux-framework\redux-core\inc\classes\class-redux-field.php on line 175`

**Installation**
I installed and configured wordpress 5.6 with the custom theme . 
I downloaded Redux Framework version 4.1.24 and put it inside the custom-theme theme folder.

the path redux-framework in my theme is :
  +my-theme 
   |++includes
   |+++redux-framework

my code for import redux-framework in theme : 
` include_once get_stylesheet_directory() . '/includes/redux-framework/redux-core/framework.php';
include_once get_stylesheet_directory() . '/includes/theme-config.php'; `

or 

` require(dirname( __FILE__ ) . '/includes/theme-panel/redux-core/framework.php');
require(dirname( __FILE__ ) . '/includes/theme-config.php'); `

Console Error Log : 
localhost/my-themeassets/css/redux-admin.min.css?ver=4.1.24 net::ERR_ABORTED 404 (Not Found)
localhost/my-themeassets/css/colors/fresh/colors.min.css?ver=4.1.24 net::ERR_ABORTED 404 (Not Found)
localhost/my-themeassets/css/vendor/select2.min.css?ver=4.0.5 net::ERR_ABORTED 404 (Not Found)
localhost/my-themeassets/css/redux-fields.min.css?ver=4.1.24 net::ERR_ABORTED 404 (Not Found)
localhost/my-themeassets/css/vendor/elusive-icons.min.css?ver=4.1.24 net::ERR_ABORTED 404 (Not Found)
localhost/my-themeassets/css/vendor/qtip.min.css?ver=2.2.0 net::ERR_ABORTED 404 (Not Found)
localhost/my-themeassets/css/vendor/jquery-ui-1.10.0.custom.css?ver=4.1.24 net::ERR_ABORTED 404 (Not Found)
localhost/my-themeassets/css/rtl.css?ver=4.1.24 net::ERR_ABORTED 404 (Not Found)
localhost/my-themeassets/css/colors/fresh/colors.min.css?ver=4.1.24 net::ERR_ABORTED 404 (Not Found)
localhost/my-themeassets/css/redux-admin.min.css?ver=4.1.24 404 (Not Found)
localhost/my-themeassets/js/vendor/select2-sortable/redux.select2.sortable.min.js?ver=4.1.24 net::ERR_ABORTED 404 (Not Found)
localhost/my-themeassets/js/vendor/select2/select2.min.js?ver=4.0.5 net::ERR_ABORTED 404 (Not Found)
localhost/my-themeassets/js/vendor/qtip/qtip.min.js?ver=2.2.0 net::ERR_ABORTED 404 (Not Found)
localhost/my-themeassets/js/redux-vendors.min.js?ver=4.1.24 net::ERR_ABORTED 404 (Not Found)
localhost/my-themeassets/css/redux-fields.min.css?ver=4.1.24 net::ERR_ABORTED 404 (Not Found)

If I install the plugin normally everything works.
If you need more details, ask away.

thanks .

**Comment by kprovance** [comment]
Hi!

Redux 3.x has reached its end of life.  We will no longer be maintaining it.  Please update to Redux v4, which will be moved to this repository shortly.  Should you should discover the same issue with Redux v4, please rereport the issue, making sure to supply the required information request via the New Issue form.

Thank you for choosing Redux.

- Kev
