### ISSUE TITLE
New Project

### ISSUE THREAD

**Issue by Deltanet-solutions** [reduxframework/redux-framework#3789]
I have to do a new project and when i have to Select Background White Or Black only appear select an item, i can not choose any value. 

Idem in Select Project 1 Or Project 2

Thank you

**Comment by kprovance** [comment]
Hi!

Redux 3.x has reached its end of life.  We will no longer be maintaining it.  Please update to Redux v4, which will be moved to this repository shortly.  Should you should discover the same issue with Redux v4, please rereport the issue, making sure to supply the required information request via the New Issue form.

Thank you for choosing Redux.

- Kev
