### ISSUE TITLE
PHP 8 deprecation warnings

### ISSUE THREAD

**Issue by maicol07** [reduxframework/redux-framework#3793]
I get the following deprecation warnings with PHP 8:

```
Deprecated: Required parameter $handle follows optional parameter $register in /home/maicol07.it/blog.maicol07.it/wp-content/plugins/redux-framework/redux-core/inc/classes/class-redux-cdn.php on line 96

Deprecated: Required parameter $src_cdn follows optional parameter $register in /home/maicol07.it/blog.maicol07.it/wp-content/plugins/redux-framework/redux-core/inc/classes/class-redux-cdn.php on line 96

Deprecated: Required parameter $deps follows optional parameter $register in /home/maicol07.it/blog.maicol07.it/wp-content/plugins/redux-framework/redux-core/inc/classes/class-redux-cdn.php on line 96

Deprecated: Required parameter $ver follows optional parameter $register in /home/maicol07.it/blog.maicol07.it/wp-content/plugins/redux-framework/redux-core/inc/classes/class-redux-cdn.php on line 96

Deprecated: Required parameter $footer_or_media follows optional parameter $register in /home/maicol07.it/blog.maicol07.it/wp-content/plugins/redux-framework/redux-core/inc/classes/class-redux-cdn.php on line 96

Deprecated: Required parameter $handle follows optional parameter $register in /home/maicol07.it/blog.maicol07.it/wp-content/plugins/redux-framework/redux-core/inc/classes/class-redux-cdn.php on line 170

Deprecated: Required parameter $src_cdn follows optional parameter $register in /home/maicol07.it/blog.maicol07.it/wp-content/plugins/redux-framework/redux-core/inc/classes/class-redux-cdn.php on line 170

Deprecated: Required parameter $deps follows optional parameter $register in /home/maicol07.it/blog.maicol07.it/wp-content/plugins/redux-framework/redux-core/inc/classes/class-redux-cdn.php on line 170

Deprecated: Required parameter $ver follows optional parameter $register in /home/maicol07.it/blog.maicol07.it/wp-content/plugins/redux-framework/redux-core/inc/classes/class-redux-cdn.php on line 170

Deprecated: Required parameter $footer_or_media follows optional parameter $register in /home/maicol07.it/blog.maicol07.it/wp-content/plugins/redux-framework/redux-core/inc/classes/class-redux-cdn.php on line 170
```

**Comment by kprovance** [comment]
Hi!

Redux 3.x has reached its end of life.  We will no longer be maintaining it.  Please update to Redux v4, which will be moved to this repository shortly.  Should you should discover the same issue with Redux v4, please rereport the issue, making sure to supply the required information request via the New Issue form.

Thank you for choosing Redux.

- Kev

**Comment by nihalanichu** [comment]
Hello iam getting following error on my wordpress theme after i changed my hosting to another registrar.

Deprecated: Optional parameter $list declared before required parameter $is_script is implicitly treated as a required parameter in /home/petromax/public_html/wp-content/themes/petromax-theme/redux_framework/ReduxCore/inc/class.redux_cdn.php on line 21

Deprecated: Optional parameter $register declared before required parameter $footer_or_media is implicitly treated as a required parameter in /home/petromax/public_html/wp-content/themes/petromax-theme/redux_framework/ReduxCore/inc/class.redux_cdn.php on line 45

Deprecated: Optional parameter $register declared before required parameter $footer_or_media is implicitly treated as a required parameter in /home/petromax/public_html/wp-content/themes/petromax-theme/redux_framework/ReduxCore/inc/class.redux_cdn.php on line 100

Deprecated: Optional parameter $expire declared before required parameter $path is implicitly treated as a required parameter in /home/petromax/public_html/wp-content/themes/petromax-theme/redux_framework/ReduxCore/inc/class.redux_functions.php on line 54

Fatal error: Uncaught Error: Attempt to modify property "admin_notices" on null in /home/petromax/public_html/wp-content/themes/petromax-theme/redux_framework/ReduxCore/inc/class.redux_filesystem.php:29 Stack trace: #0 /home/petromax/public_html/wp-content/themes/petromax-theme/redux_framework/ReduxCore/inc/class.redux_filesystem.php(47): Redux_Filesystem->__construct() #1 /home/petromax/public_html/wp-content/themes/petromax-theme/redux_framework/ReduxCore/inc/class.redux_filesystem.php(285): Redux_Filesystem::get_instance() #2 /home/petromax/public_html/wp-content/themes/petromax-theme/redux_framework/ReduxCore/framework.php(51): require_once('/home/petromax/...') #3 /home/petromax/public_html/wp-content/themes/petromax-theme/inc/includes.php(9): require_once('/home/petromax/...') #4 /home/petromax/public_html/wp-content/themes/petromax-theme/functions.php(12): require_once('/home/petromax/...') #5 /home/petromax/public_html/wp-settings.php(600): include('/home/petromax/...') #6 /home/petromax/public_html/wp-config.php(77): require_once('/home/petromax/...') #7 /home/petromax/public_html/wp-load.php(50): require_once('/home/petromax/...') #8 /home/petromax/public_html/wp-blog-header.php(13): require_once('/home/petromax/...') #9 /home/petromax/public_html/index.php(17): require('/home/petromax/...') #10 {main} thrown in /home/petromax/public_html/wp-content/themes/petromax-theme/redux_framework/ReduxCore/inc/class.redux_filesystem.php on line 29

How can i fix this?
