### ISSUE TITLE
Redux Console Errors

### ISSUE THREAD

**Issue by trisghosh** [reduxframework/redux-framework#3794]
Hi Team,

I am using **Redux** as Theme Option panel from 2014 through the https://build.redux.io/, but recently I came to know that is no more available. So I downloaded it from the **Github** and starter integrating it. But unfortunetly I am getting the following console error.  I need your help to get rid of this, please help.

**Refused to execute script from 'http://localhost/wporgtesting/mytheme/wp-admin/admin-ajax.php?action=redux_p&nonce=683e73913e&url=http%3A%2F%2Flook.redux.io%2Fapi%2Findex.php%3Fjs%26g%261%26v%3D2&proxy=http%3A%2F%2Flocalhost%2Fwporgtesting%2Fmytheme%2Fwp-admin%2Fadmin-ajax.php%3Faction%3Dredux_p%26nonce%3D683e73913e%26url%3D' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.**

Thanks in advance

**Comment by kprovance** [comment]
Hi!

Redux 3.x has reached its end of life.  We will no longer be maintaining it.  Please update to Redux v4, which will be moved to this repository shortly.  Should you should discover the same issue with Redux v4, please rereport the issue, making sure to supply the required information request via the New Issue form.

Thank you for choosing Redux.

- Kev
