### ISSUE TITLE
Home page is loading and loading

### ISSUE THREAD

**Issue by RKD1180** [reduxframework/redux-framework#3795]
## Expected Behavior

open very fast 

## Actual Behavior

it loading and loading

## Any Error Details (PHP/JavaScript)

javascript problem may be home page not open properly 
![tt](https://user-images.githubusercontent.com/70838828/117251156-18bf0080-ae66-11eb-8126-df8343f4de31.PNG)

**Comment by kprovance** [comment]
Hi!

Redux 3.x has reached its end of life.  We will no longer be maintaining it.  Please update to Redux v4, which will be moved to this repository shortly.  Should you should discover the same issue with Redux v4, please rereport the issue, making sure to supply the required information request via the New Issue form.

Thank you for choosing Redux.

- Kev
