### ISSUE TITLE
Issue_PHP Time Limit: -1

### ISSUE THREAD

**Issue by jintsai12** [reduxframework/redux-framework#3800]
Hi, 

We use Redux - Health Report to check on our site. The issue is that we found out that the setting PHP Time Limit: -1. We have confirmed our Cpanel max_execution_time is 30.  Why does Redux show PHP Time Limit: -1 instead of 30? Can you kindly help us to see how do we sync this number? Thanks!

**Comment by kprovance** [comment]
Hi!

Redux 3.x has reached its end of life.  We will no longer be maintaining it.  Please update to Redux v4, which will be moved to this repository shortly.  Should you should discover the same issue with Redux v4, please rereport the issue, making sure to supply the required information request via the New Issue form.

Thank you for choosing Redux.

- Kev
