### ISSUE TITLE
Warning: Undefined array key "type"

### ISSUE THREAD

**Issue by istvan-bujdoso** [reduxframework/redux-framework#3801]
If 'type' is not defined in the $option array, the code keeps creating the following record in the log.

```
Warning: Undefined array key "type"

/wp-content/plugins/bp-restrict/includes/options/inc/extensions/customizer/extension_customizer.php in ReduxFramework_extension_customizer::_register_customizer_controls at line 507
```

**Comment by kprovance** [comment]
Redux 3 has been sunset, which means it's reached its end of life.  Please upgrade to Redux 4.  If the problem persits, please post to that issue tracker.  Thanks!
