### ISSUE TITLE
generating css  gives error font-display: Property font-display doesn't exist.

### ISSUE THREAD

**Issue by giannisgiat** [reduxframework/redux-framework#3803]
how can i change my generated css code so as not to generate this kind of error. 

`.man_page h1, .man_page h1 a{font-family:Roboto;line-height:70px;font-weight:700;font-style:normal;color:#260601;font-size:56px;font-display:swap;}`

how to disable font-display:swap which causes the error

**Comment by kprovance** [comment]
Redux 3.x has reached its end of life.  Please update to Redux 4.  Thanks!

**Comment by giannisgiat** [comment]
Redux Framework 4.1 is installed on my wordpress and not Redux 3.x

**Comment by giannisgiat** [comment]
could we know how the  font-display:swap is generated so as to disable or somehow include it in @font-face so as to avoid getting errors in validator

**Comment by kprovance** [comment]
Add the following to your global arguments:

`font_display' => 'auto', // the default.
