### ISSUE TITLE
.setHSpace is not a function conflict with WordPress core 

### ISSUE THREAD

**Issue by Rahisaiful** [reduxframework/redux-framework#3806]
I have found the issue after the update WordPres 5.7.2 and redux  4.1.29. When I have navigated the redux option it's shown console error. and I think the redux conflicts with WordPress Core. Please checkout the screenshot.

http://prntscr.com/18oq5ho

Thanks

**Comment by kprovance** [comment]
None of the files indicated in your screenshot are installed with Redux.  If you provide a support URL (as was asked when you posted this), I can take a closer look, although I suspect the issue lies elsewhere.
