### ISSUE TITLE
Warning: Creating default object from empty value - class.redux_filesystem.php

### ISSUE THREAD

**Issue by JJITPro** [reduxframework/redux-framework#3807]
I just realized that my client's site is experiencing an issue with the class.redux_filesystem.php file.  I have read some articles that say to define the FTP credentials in the wp-config file, which I have also tried.

The front-end and back-end of the site show the below error...

"Warning: Creating default object from empty value in /home/customer/www/DOMAINNAME/public_html/wp-content/plugins/moto_core/admin/inc/class.redux_filesystem.php on line 29"

Below is line 29...

"            public function __construct() {
                $this->parent->admin_notices[] = array(
                    'type'    => 'error',
                    'msg'     => '<strong>' . __( 'File Permission Issues', 'redux-framework' ) . '</strong><br/>' . sprintf( __( 'We were unable to modify required files. Please check your permissions, or modify your wp-config.php file to contain your FTP login credentials as <a href="%s" target="_blank">outlined here</a>.', 'redux-framework' ), 'https://codex.wordpress.org/Editing_wp-config.php#WordPress_Upgrade_Constants' ),
                    'id'      => 'redux-wp-login',
                    'dismiss' => false,"

Below is the Support URL...

"http://support.redux.io/?id=3C7jcaU8XwuHqhrAA%2Bg2R3RPPJ4SpchRl33mGajxUAqgYaM96k86QHbbTaONtIhcTBgUF3g8Ztpd1%2Bffr10MTQ%3D%3D"

Any ideas, suggestions, or help would be greatly appreciated.

**Comment by kprovance** [comment]
Unfortunately, we no longer support Redux v3.  It has reached its end of life and is no longer maintained by us.  Redux v4 is the currently supported version. 

Unofficially, I can tell you this is a permissions issue on the server.  The upload and subdirs are probably not writable and/or the owner of the recursive directories is not set to the same owner the web server runs.
