### ISSUE TITLE
Parse error: syntax error, unexpected ':', expecting '

### ISSUE THREAD

**Issue by tonyjohnsamuel** [reduxframework/redux-framework#3808]
Hello 

I am new to using this plugin. After installing the plugin, I am getting Parse error. Need your guidance to fix this.

Parse error: syntax error, unexpected ':', expecting ';' or '{' in /home/yhw5ll5kfd9s/public_html/indiacafe.crunkminds.com/wp-content/plugins/redux-framework/redux-core/class-redux-core.php on line 460

Look forward to your support. Thanks!

**Comment by kprovance** [comment]
Please provide the requested and required support hash, please.

**Comment by kprovance** [comment]
If we're using the same version, that line is the first line of a function, and the ':' sets the return value.  If this is giving you an error, you are using an outdated and unsupported version of PHP.  Redux requires PHP version 7.1 or later.  Please upgrade to the minimum required version.  Thanks!
