### ISSUE TITLE
Outdated packagist package and wrong name at composer.json

### ISSUE THREAD

**Issue by yangm97** [reduxframework/redux-framework#3809]
https://github.com/reduxframework/redux-framework/blob/455d17684c0b6147b2a7d93938fe297a482e1e8c/composer.json#L2

https://packagist.org/packages/redux-framework/redux-framework

**Comment by kprovance** [comment]
How exactly is the name incorrect?  It is the name of this repository.

![image](https://user-images.githubusercontent.com/3412363/125201979-84936000-e23f-11eb-95a1-ba104f57769d.png)

The package used to auto-update, so I will endeavor to have that fixed.

Thanks!

**Comment by yangm97** [comment]
@kprovance I think it's supposed to match the composer path (which has a dash in it's namespace).

**Comment by kprovance** [comment]
The composer docs are vague, at best.  This is all I could find:  https://getcomposer.org/doc/04-schema.md#name

**Comment by kprovance** [comment]
It's all syncing up again with packagist.
