### ISSUE TITLE
FATAL ERROR:  #3810

### ISSUE THREAD

**Issue by slyfoxregen** [reduxframework/redux-framework#3810]
.

**Comment by kprovance** [comment]
You've posted nothing but the template.

**Comment by slyfoxregen** [comment]
Fatal error: Uncaught TypeError: method_exists(): Argument #1 ($object_or_class) must be of type object|string, bool given in /Applications/MAMP/htdocs/minimalshop/wp-content/plugins/redux-framework/redux-core/inc/classes/class-redux-enqueue.php:420 Stack trace: #0 /Applications/MAMP/htdocs/minimalshop/wp-content/plugins/redux-framework/redux-core/inc/classes/class-redux-enqueue.php(420): method_exists(false, 'enqueue') #1 /Applications/MAMP/htdocs/minimalshop/wp-content/plugins/redux-framework/redux-core/inc/classes/class-redux-enqueue.php(503): Redux_Enqueue->enqueue_field(Object(ReduxFramework), Array) #2 /Applications/MAMP/htdocs/minimalshop/wp-content/plugins/redux-framework/redux-core/inc/classes/class-redux-enqueue.php(106): Redux_Enqueue->enqueue_fields(Object(ReduxFramework)) #3 /Applications/MAMP/htdocs/minimalshop/wp-includes/class-wp-hook.php(292): Redux_Enqueue->init('toplevel_page_r...') #4 /Applications/MAMP/htdocs/minimalshop/wp-includes/class-wp-hook.php(316): WP_Hook->apply_filters('', Array) #5 /Applications/MAMP/htdocs/minimalshop/wp-includes/plugin.php(484): WP_Hook->do_action(Array) #6 /Applications/MAMP/htdocs/minimalshop/wp-admin/admin-header.php(102): do_action('admin_enqueue_s...', 'toplevel_page_r...') #7 /Applications/MAMP/htdocs/minimalshop/wp-admin/admin.php(239): require_once('/Applications/M...') #8 {main} thrown in /Applications/MAMP/htdocs/minimalshop/wp-content/plugins/redux-framework/redux-core/inc/classes/class-redux-enqueue.php on line 420

**Comment by kprovance** [comment]
Version information?

**Comment by kprovance** [comment]
Are you the developer of the theme?  Are you a user of the theme?  PHP version?  Redux version?

**Comment by slyfoxregen** [comment]
Redux v4.0
PHP 8.0.3
MySQL 5.7.32
WordPress 5.7.2

**Comment by slyfoxregen** [comment]
Redux 4.1 sorry

**Comment by kprovance** [comment]
Theme developer or theme user?  What *Specific version* of Redux?  4.1.x <--this number also.

Is there any reason you cannot submit a support URL as noted in the instructions?

**Comment by slyfoxregen** [comment]
4.1.30 RC

**Comment by slyfoxregen** [comment]
I did include the support URL, when i opened it, it took me to this page
![Uploading Screenshot 2021-07-18 at 19.01.07.png…]()

**Comment by kprovance** [comment]
That URL takes me no where.  I really need to see your support URL

**Comment by slyfoxregen** [comment]
[https://support.redux.io/?id=EmyyNVnS65z7%2BniaynCbCmrOTc%2Bz4A5v6V%2FSnfI2M7OKF3YiD4lJ23I7OPE%2FPog9tgABh7W1TPxuGjaDERcz9Q%3D%3D](url)

**Comment by slyfoxregen** [comment]
[https://docsv3.redux.io/core/generating-a-support-hash/index.html](url)

that's all I got after following these steps
Pardon me, I'm new to PHP and GitHub

**Comment by slyfoxregen** [comment]
I just check Redux Health, under settings in WordPress, it says there my version is : 4.1.29
as downloaded with WordPress

![Screenshot 2021-07-18 at 19 14 14](https://user-images.githubusercontent.com/87527031/126076224-9b92ae53-622f-49ea-a832-881c092e1c1f.png)

**Comment by kprovance** [comment]
According to your config, you are in fact use `"redux_ver": "4.1.29",` which is not the RC from this repo.  

Your config show the only Redux instance you are running is the sample-config file (the demo included).  I am running it with PHP 8.0.6 and am unable to recreate this issue.  There have also been no other reports of this kind.  Please try upgrading to the 4.1.30 RC version and see if that resolves it.

**Comment by slyfoxregen** [comment]
I will thank you, I will also follow the configuration steps per your documentation and see if I can resolve it.
You may close this ticket for now and I will contact you again if I really need to.

Thanks again.
