### ISSUE TITLE
Issues With WordPress 5.8

### ISSUE THREAD

**Issue by umertoday** [reduxframework/redux-framework#3811]
Hi,
Your framework is awesome. Keep up good works.
There are some issue with WordPress 5.8

Number 1:

WordPress now showing below message in widget admin area.
Notice: wp_enqueue_script() was called incorrectly. "wp-editor" script should not be enqueued together with the new widgets editor (wp-edit-widgets or wp-customize-widgets). Please see Debugging in WordPress for more information. (This message was added in version 5.8.0.) 

This error occur in file due to use of wp-editor 
wp-content/plugins/redux-framework/redux-templates/classes/class-init.php line 107
![Screenshot_1](https://user-images.githubusercontent.com/9529251/126461743-3f0470ce-a62f-458d-b5c4-3fd55cd497b2.png)

Number 2:

There are some react issues shared screenshot

**Comment by kprovance** [comment]
This is a known issue that we will have a fix for, hopefully by the end of the week. Hopefully.

In the interim, you have two options.

1) Upgrade to Redux 4.2 via our GitHub repository (the version that will be released after some more internal testing) here: https://github.com/reduxframework/redux-framework

2) Install and activate a plugin from the wp.org repository called “Classic Widgets,” which will revert the widgets screen to the old version. That is a stop-gap suggestion until we can get this new release finished up and the issue solved.

If you go with the first option and discover something wrong, please use the GitHub issue tracker to report it until the final release.

Thanks!

– Kev
