### ISSUE TITLE
WordPress 5.8 compatibility issue with widgets area

### ISSUE THREAD

**Issue by etwordpress01** [reduxframework/redux-framework#3813]
Hello, Thank you for creating an awesome framework for the Theme Options

We are facing an issue with the latest version of WordPress 5.8, in WordPress 5.8, they introduce a block editor for widgets. Unfortunately, the redux plugin creating an issue with the latest version 5.8

When we visit Appearance > Widgets then it throws an error and doesn't show anything on the widget page. We even tested with fresh installations. 

You can check the below video link

https://www.loom.com/share/b806f827b00040e09f12d9f5a466102f

Hopefully, this will be fixed on the priority basis

Thanks again

**Comment by kprovance** [comment]
This is a known issue that we will have a fix for, hopefully by the end of the week. Hopefully.

In the interim, you have two options.

    Upgrade to Redux 4.2 via our GitHub repository (the version that will be released after some more internal testing) here: https://github.com/reduxframework/redux-framework

    Install and activate a plugin from the wp.org repository called “Classic Widgets,” which will revert the widgets screen to the old version. That is a stop-gap suggestion until we can get this new release finished up and the issue solved.

If you go with the first option and discover something wrong, please use the GitHub issue tracker to report it until the final release.

Thanks!

– Kev
