### ISSUE TITLE
Test result from using both Twenty-Twenty One and Seele theme

### ISSUE THREAD

**Issue by arreanelevelup** [reduxframework/redux-framework#3814]
I wasn't able to generate a support harsh. I've got an alert error when I try to generate a support url

**The link provided on the Pre-Text is also broken**
https://docsv3.redux.io/core/generating-a-support-hash/index.html%20for%20more%20details.

Below are the following issues I found when testing both Twenty-Twenty One and Seele theme. The results from PHP v7.3 and 8.0 are similar. I also added a short recording on each test cases.

**PHP 7.3.29 | PHP 8.0.8 | WordPress 5.8 | Twenty-Twenty One**

- WP admin page: 
  - Error: Redux_Helpers::isFieldInUse is deprecated since version Redux 4.0! Use Redux_Helpers::is_field_in_use( $parent, $field ) instead.	
- Redux Sample page:
  - Notice: WP_Scripts::localize was called incorrectly. The $l10n parameter must be an array. To pass arbitrary data to scripts, use the wp_add_inline_script() function instead. Please see Debugging in WordPress for more information. (This message was added in version 5.7.0.)
- repeater field delete button doesn't work most of the time - https://share.getcloudapp.com/2NuqGJop
- social profiles not displaying all icons - https://share.getcloudapp.com/xQu7B48P
- social profiles reset button doesn't work - https://share.getcloudapp.com/GGuWmPYR
- error when adding redux social widget "there was an error. Cannot read property 'hasOwnProperty' of undefined" - https://share.getcloudapp.com/2NuqGJGK
- documentations tab throws error "Field failed to render: Class 'Redux_Parsedown' not found" - https://share.getcloudapp.com/04u2l9mX
- customizer > editors > wordpress editor > editor. visual tab not working - https://share.getcloudapp.com/Kou4gzzX
- customizer > editors > wordpress editor > w/o media button has white text and is not visible - https://share.getcloudapp.com/L1uB0Kx4
-customizer > accordion fields to be continued - https://share.getcloudapp.com/jkuP9rQx
-customizer > documentation error > Field failed to render: syntax error, unexpected token "class" - https://share.getcloudapp.com/NQuoyE6O

**PHP 7.3.29 | PHP 8.0.8 | WordPress 5.8 | Seele**
-No Issues
-No redux widget to test
-No Customizer option to test

**Comment by kprovance** [comment]
> Notice: WP_Scripts::localize was called incorrectly. The $l10n parameter must be an array. To pass arbitrary data to scripts, use the wp_add_inline_script() function instead. Please see Debugging in WordPress for more information. (This message was added in version 5.7.0.)

@arreanelevelup, Was there any information about which PHP file this was triggered, or could you tell me the specific steps you took that triggered this?

**Comment by kprovance** [comment]
@arreanelevelup , never mind.  I found it.  It's pro.  I left myself an issue on the Pro tracker to fix it later.

**Comment by kprovance** [comment]
@arreanelevelup, @arturgrabo, @clubkert 

That was a really well done report.  Thank you!  Very comprehensive!  Here are my notes.

1. _Redux_Helpers::isFieldInUse:_ I turned that deprecation message back on to find instances in Pro.  Turned it back off.
2.  _WP_Scripts::localize was called incorrectly_. - Pro issue.  Moved it to the pro issue tracker.
3. _Repeater and Social Profile issues_ - Pro issues.  I moved them to the Pro issue tracker.  I *think* I fixed the social profiles stuff in my theme extension.  I'll double check, and if so, move the fixes to Pro.  If not, it's on the to-do list.
4. _Field failed to render: Class 'Redux_Parsedown' not found_ - Fixed. 
5. _Editor visual tab in customizer_ - That has never worked.  It was on the 'known issues' list for years.  Next time I talk to Dovy, I'll ask him if he ever knew why and see if it's fixable.
6. _Editor text in customizer_ - Fixed.  Weird CSS going on there.
7. _Accordion in customizer_ - Was never supported.  As it was one of the lowest selling extensions, I never bothered to figure out why.  No one ever asked.  ;-)
8. _Docs tab in customizer_ - Fixed from item 4.

If there isn't anything more, I can tag this in the repo, which will automatically push it to wp.org.  Let me know!

- Kev

**Comment by arreanelevelup** [comment]
@arturgrabo Please check the comment above. @kprovance already explained each issues. I'll just list here based on my testing what's working and what's not as a summary.

1.  (CONFIRMED FIXED) WP admin page:
	Error: Redux_Helpers::isFieldInUse is deprecated since version Redux 4.0! Use Redux_Helpers::is_field_in_use( $parent, $field ) instead.

2. [(issue moved to redux-pro repo - not yet fix)](https://github.com/reduxframework/redux-pro/issues/19) Redux Sample page
	Notice: WP_Scripts::localize was called incorrectly. The $l10n parameter must be an array. To pass arbitrary data to scripts, use the wp_add_inline_script() function instead. Please see Debugging in WordPress for more information. (This message was added in version 5.7.0.)

3. [(issue moved to redux-pro repo - not yet fix)](https://github.com/reduxframework/redux-pro/issues/20)
repeater field delete button doesn't work most of the time - https://share.getcloudapp.com/2NuqGJop

4. [(issue moved to redux-pro repo - not yet fix)](https://github.com/reduxframework/redux-pro/issues/21) 
 social profiles not displaying all icons - https://share.getcloudapp.com/xQu7B48P - moved to redux-pro repo - not yet fixed

5. [(issue moved to redux-pro repo - not yet fix)](https://github.com/reduxframework/redux-pro/issues/21) 
social profiles reset button doesn't work - https://share.getcloudapp.com/GGuWmPYR

6. [(issue moved to redux-pro repo - not yet fix)](https://github.com/reduxframework/redux-pro/issues/21) 
 error when adding redux social widget "there was an error. Cannot read property 'hasOwnProperty' of undefined" - https://share.getcloudapp.com/2NuqGJGK

7. (CONFIRMED FIXED) 
documentations tab throws error "Field failed to render: Class 'Redux_Parsedown' not found" - https://share.getcloudapp.com/04u2l9mX

8. (after testing, still doesn't work on my end) 
customizer > editors > wordpress editor > editor. visual tab not working - https://share.getcloudapp.com/Kou4gzzX

9. (known issue - not yet fix) 
customizer > editors > wordpress editor > w/o media button has white text and is not visible - https://share.getcloudapp.com/L1uB0Kx4

10. (was never supported, not yet fix) 
customizer > accordion fields to be continued - https://share.getcloudapp.com/jkuP9rQx

11. (CONFIRMED FIXED) customizer > documentation error > Field failed to render: syntax error, unexpected token "class" - https://share.getcloudapp.com/NQuoyE6O

**Comment by kprovance** [comment]
Releasing.  Smoke 'em if ya got 'em.
