### ISSUE TITLE
WP 5.8 version admin widget blank issue created by redux plugin

### ISSUE THREAD

**Issue by sdsrony** [reduxframework/redux-framework#3815]
Please fix script loading in widget area https://prnt.sc/1ghhi7y
When activating redux plugin then wp admin widget show blank otherwise wp admin widget area is fine.

**Comment by kprovance** [comment]
This is a known issue that we will have a fix for, hopefully in the next hour or so.  I'm waiting for final approval.  :)
In the interim, you have two options.

1. Upgrade to Redux 4.2 via our GitHub repository (the version that will be released after some more internal testing) here: https://github.com/reduxframework/redux-framework

2. Install and activate a plugin from the wp.org repository called “Classic Widgets,” which will revert the widgets screen to the old version. That is a stop-gap suggestion until we can get this new release finished up and the issue solved.

If you go with the first option and discover something wrong, please use the GitHub issue tracker to report it until the final release.

Thanks!

– Kev
