### ISSUE TITLE
Wordpress site errors

### ISSUE THREAD

**Issue by rhaleluk** [reduxframework/redux-framework#3818]
We're getting errors from the Redux plugin...

There are showing up on the homepage...

Warning: Declaration of Redux_Color_Rgba::output($style = '') should be compatible with Redux_Field::output(string $style = '') in /var/www/vhosts/smartparts.com/httpdocs/wp-content/plugins/redux-framework/redux-core/inc/fields/color_rgba/class-redux-color-rgba.php on line 20

Warning: Declaration of Redux_Typography::output($style = '') should be compatible with Redux_Field::output(string $style = '') in /var/www/vhosts/smartparts.com/httpdocs/wp-content/plugins/redux-framework/redux-core/inc/fields/typography/class-redux-typography.php on line 18

Warning: Declaration of Redux_Color::output($style = '') should be compatible with Redux_Field::output(string $style = '') in /var/www/vhosts/smartparts.com/httpdocs/wp-content/plugins/redux-framework/redux-core/inc/fields/color/class-redux-color.php on line 20

And these are showing up on the widgets page....

<img width="1346" alt="Screen_Shot 2021-07-29 at 11 06 41 AM" src="https://user-images.githubusercontent.com/544234/127516837-d3daa1a1-0554-413a-b653-ba0f67b4ce33.png">

We need some help to fix these errors.

**Comment by kprovance** [comment]
Redux Framework requires, at the minimum, PHP 7.1.  WordPress recommends a minimum PHP 7.4 because of security concerns in older versions.  Please update your PHP version to something 7.1 or higher.  These errors will stop then.

**Comment by rhaleluk** [comment]
We have PHP version 7.1 installed - I checked that. We can't upgrade to 7.4 on our server because we'd have to switch the operating system and we have a bunch of other domains active that would be taken down. We need a quick fix for a simple landing page. Not only are we running 7.1 - but we were told the latest version of the plugin resolved these issues and it did not. Is there a way to downgrade the plugin?

**Comment by kprovance** [comment]
Could you PLEASE provide the request support URL?  The instructions for posting said this:

>Also, unless you provide a Support Hash, your request will also be rejected.  NO exceptions.  If you do not including this information and we close your ticket, please do not ask why. See See https://docsv3.redux.io/core/generating-a-support-hash/index.html for more details.

It's required and would help me figure out what's going on.  I test Redux with PHP 7.1 up to 8.1 and I don't get these warnings.  You;re free to downgrade via the Tag section of this repo, but it will not help fix the issue, and that's the point of the issue tracker.  It'll mean future versions will not correct this.

**Comment by rhaleluk** [comment]
It says error when trying to do that - I tried that.

**Comment by rhaleluk** [comment]
When I do a health check, it says everything checks out. It seems to be an issue with the plugin. 

When I deactivate the plugin, everything works fine but the theme doesn't work and we've already put a bunch of time into using this theme.

**Comment by kprovance** [comment]
I'll just undo the typesafe dec and that'll be that.  Should be out later tonight.
