### ISSUE TITLE
Function file_in_theme is missing normalization

### ISSUE THREAD

**Issue by Santukon** [reduxframework/redux-framework#3820]
Hello Team,
  Just to note that function file_in_theme at file https://github.com/reduxframework/redux-framework/blob/master/redux-core/inc/classes/class-redux-functions-ex.php on ilne 238 is missing normalization.
  In my case it was not detecting the embedded core.

This is how I left it to work properly.

```
public static function file_in_theme( string $file ): bool {		
	// Normalization
	$filePath = self::wp_normalize_path( dirname( $file ) );
	
	if ( strpos( $filePath, self::wp_normalize_path( get_template_directory() ) ) !== false ) {
		return true;
	} elseif ( strpos( $filePath, self::wp_normalize_path( get_stylesheet_directory() ) ) !== false ) {
		return true;
	}

	return false;
}
```

**Comment by kprovance** [comment]
Added to repo code.

**Comment by Santukon** [comment]
Awesome! thank you.
