### ISSUE TITLE
editor field output have a problem

### ISSUE THREAD

**Issue by webbudesign** [reduxframework/redux-framework#3821]
Hello,

Today I discover a problem with the new version.  v4.2.11 - I tested the same issue with the v4.1.29 and it is not happening on the old version.

Let me explain the problem: I am calling redux global variable on the init section and I get all options except editor field values. Something making delay on editor fields global variable output. I couldn't find the problem and I need help with this. 

My customers started to send bug reports and I need to fix this problem asap.

Thanks
Webbu

**Comment by kprovance** [comment]
I need reproducible data, and perhaps a support hash from an affected client.  I can;t fix what I can't break, so I need to be able to reproduce it here.   I tested this with our sample config and couldn't reproduce it.

**Comment by webbudesign** [comment]
Correction: 
1-) The issue happening on the old version too.
2-) Only happening on the corn job events.

## Support Hash
https://support.redux.io/?id=TdrEp5ZvZQMkARiqPjGWbMIgwIlBVhA%2F6d4BfoL23zLgPQztkziepZEck2CJRDaEPd7ygADpoSh9uF4mhr1lgg%3D%3D

Configuration file for test: https://snippets.cacher.io/snippet/1d504c8cae7d878ec37f
The output of global printout: https://snippets.cacher.io/snippet/8000d2c8ce7f9b9290ab

## Steps to reproduce
1-) Create a corn event on your system. (Daily or hourly)
Info:  I am using https://tr.wordpress.org/plugins/wp-crontrol/ plugin to run cronjob without waiting.

2-) Use a code like the below;
`ob_start();
global $pointfindermail_option;
if (empty($pointfindermail_option)) {
$pointfindermail_option = get_option('pointfindermail_options');
}
var_export($pointfindermail_option);
$content = ob_get_clean();
error_log($content);`

3-) Check your debug log and you will see there is no editor field output exists. I don't know about other fields but button_set and text are print out correctly.

**Comment by kprovance** [comment]
Where exactly would I put the code to output the results?

**Comment by webbudesign** [comment]
Anywhere in your cronjob function.

**Comment by kprovance** [comment]
functions.php?  Do I have to create an action hook?  I've never worked with cron, so I'm unsure what it goes.

**Comment by kprovance** [comment]
If it's happening with the old version, it may be an existing issue and not something broken in the 4.2 update.  I'll check anyone once I know how to trigger this output

**Comment by webbudesign** [comment]
Yes, I discover it today. My listing expiration check system using daily cronjob and sending empty emails because there is no content exist on the global option variable. 
You can check this article for more information about cronjob: https://www.cloudways.com/blog/wordpress-cron-job/

**Comment by kprovance** [comment]
The problem here is firing order.  Redux settings aren't loaded until after `init`.  When the cron jobs are firing, the data pulled from the global variable is, in fact, default values and not what's in the database.  I'm not certain there's a fix for that without rewriting parts of Redux.  I'm not even certain at the time `init` is even firing, and if it is, when it's happening in relation to crons, if at all.  It would take some time to research and experiment with.

The work around is:

```php
ob_start(); 
$pointfindermail_option = get_option('pointfindermail_options');
var_export($pointfindermail_option); 
$content = ob_get_clean(); 
error_log($content);
```

**Comment by webbudesign** [comment]
Ok, but it was working when I write this theme by using Redux Framework. I need to use a global variable, I can not use get_options  on every field request.  Hope you find a solution for this.

**Comment by webbudesign** [comment]
Is closing the issue means, you will not provide a solution?

**Comment by kprovance** [comment]
get_options pulls the entire database, all the fields.   To get a specific field, you'd just do something like:

```php
$value1 = $pointfindermail_option ['some_value_1'];
$value2 = $pointfindermail_option ['some_value_2'];
$value3 = $pointfindermail_option ['some_value_3'];
// etc...
```

I couldn't say why it worked once.  I don't know how long ago that was or what version was involved.  You did say 4.1.29 wasn't  working either.   All I can tell you is why it's not working now.  There is some hook someplace in the Redux core that is not firing during cron.  To determine which one it is and why would take more time that I am allotted right now.  There is no solution right now, no quick one, except pull the database array and reading the field values off it like one would do with the global variable.

The other option if you want to pursue it it to look at the release tags in the repo and test backward with older version of 4.0 until you find one that works, if one works.  From there I could do a diff on the code and see what's different.  If it goes back into the 3.x versions, it may be an out-of-luck situation as that code has been retired and very different from the 4.0 code.

**Comment by webbudesign** [comment]
I tried v4.1.16 which is the oldest version available on your GitHub. It is working.
v4.1.16 - global variable output: https://snippets.cacher.io/snippet/cbb7484b1bd6fe0b6f05

v4.2.11 - global output: https://snippets.cacher.io/snippet/8000d2c8ce7f9b9290ab

The problem is not about init it is a problem on the editor field. Maybe some other fields have the same problem. 
If you check the second output, I can see the button set and text fields. I should see nothing if it is not working into the cronjob.

Please take time and solve this issue. I can not release theme update on every Redux Framework update.

**Comment by webbudesign** [comment]
This is the code I am using 
`ob_start();
global $pointfindermail_option;
/*if (empty($pointfindermail_option)) {
$pointfindermail_option = get_option('pointfindermail_options');
}*/
var_export($pointfindermail_option);
$content = ob_get_clean();
error_log($content);`

**Comment by kprovance** [comment]
I'm doing the best I can with the time I am allotted.  Please be respectful of that.  Thanks.

I need you to trust me.  I used the sample config and the cron code.  I could not use your config as it depended upon a page created by another Redux instance and I didn't have time to edit it all to work.  The rest is the same.  The sample config has wp-editor fields.  The results using the global variable are the default values.  I changed a bunch for every field and they were always the default values.  Using get_option gave me the database values.  I'm not sure why that's a huge deal or a major inconvenience.  It is a solution that imitates the global variable.

I will try the older version and see what happens.  I cannot promise a resolution in the time you;d prefer and I'm sorry.  I'm one guy doing the best I can with MANY people who want the same demands of me for open-source, free software,

**Comment by webbudesign** [comment]
I am always respectful of your work and efforts.  I can not use get_options on every get_field function (custom function). I will look at all releases and try to find the problem with you.

**Comment by webbudesign** [comment]
The problem starts on v4.1.28 
4.1.27 is working well and all the below versions.

**Comment by webbudesign** [comment]
I found the problem: https://github.com/reduxframework/redux-framework-4/commit/5a44d6d9af677bf47d255724b0075c9351e1e991

I sent a pull request https://github.com/reduxframework/redux-framework/pull/3823

**Comment by kprovance** [comment]
```php
if ( 'wp-cron.php' === $pagenow || empty( $args ) || ! isset( $args['opt_name'] ) || ( isset( $args['opt_name'] ) && empty(   $args['opt_name'] ) ) ) {
    return;
}
```

If I remove wp-cron, I'm breaking someone else's fix.

**Comment by webbudesign** [comment]
Ok but you are disabling construct on the cron. This feature was working since today from the first version.

**Comment by webbudesign** [comment]
I can recommend something to solve this.  You can add a global variable for those who want to disable cron and it can be an optional request.

**Comment by kprovance** [comment]
If I eliminate `'wp-cron.php' === $pagenow` per your pull request, another user is going to come back and complain I broke his plugin. 

> I can recommend something to solve this. You can add a global variable for those who want to disable cron and it can be an optional request.

A global arg?  `load_on_cron => true`

That's a good a solutionn as any.   You okay  with that?

**Comment by webbudesign** [comment]
Yes, but please leave the original code cron on and if someone wants to disable it ok they can do that.

**Comment by kprovance** [comment]
Okay.  Gimme a few minutes to add this and test it, then I'll push to the repo.

**Comment by webbudesign** [comment]
Thank you very much :)

**Comment by kprovance** [comment]
Give that a try and see if it works.  I've not run with multiple Redux instances yet.

**Comment by kprovance** [comment]
Use `'load_on_cron' => true,` in your args.

**Comment by webbudesign** [comment]
@kprovance thanks for your changes but wp-cron is a part of wp and can't it be default true?  
Since the first version of redux it was true and now changed.

**Comment by webbudesign** [comment]
> Use `'load_on_cron' => true,` in your args.

It is working. But please consider to change default value to true.

**Comment by kprovance** [comment]
If I do that, the other user who doesn't want cron to run will ultimately come back and complain and then I have to tell him to add stuff for a fix I basically will undo by making run_on_cron true, and honestly, I don't want to deal with that guy.  Redux exiting on wp-cron.php has to be the default.  It;s one line to add to the arguments array,

**Comment by webbudesign** [comment]
Ok. This is your decision respect. 

But this feature was an existing feature, I develop my theme over 5 years ago and now one person requesting a code change and I need to update my plugin and my theme because of that guy's request. 

Should I check every commit in the future to have no problem? Please consider looking at it from a theme developer's eyes.

**Comment by kprovance** [comment]
Okay, I don't want to get in the middle of this.  Someone is going to be unhappy.  You can ask them, if you want.

@pablodiloreto, @thomasplevy

**Comment by webbudesign** [comment]
Done. https://github.com/reduxframework/redux-framework-4/issues/215#issuecomment-892268599

**Comment by thomasplevy** [comment]
@kprovance the relevant portion of https://github.com/reduxframework/redux-framework-4/commit/5a44d6d9af677bf47d255724b0075c9351e1e991 which resolved #215 for our shared users is replacing `exit` with `return` on line 414:

https://github.com/reduxframework/redux-framework-4/commit/5a44d6d9af677bf47d255724b0075c9351e1e991#diff-4d2b23fdf00a73e808993a16daee81079a5c5cd40a157da7db3256d475c971f2R414

The WP heartbeat (which LifterLMS relies on for autosaving in our course builder) was being effectively killed because of this line. Switching to a `return` stopped killing PHP and allowed us to play nice with one another and (I think) have everything everyone wants.

Although I'm not going to pretend to be an expert on Redux or exactly what all the implications of this meant.

Therefore I don't believe that @webbudesign's pr https://github.com/reduxframework/redux-framework/pull/3823/files will have affect #215  because the change in this PR wouldn't actually get executed during a LifterLMS autosave because of the condition causing the return on 414

I think at least

**Comment by webbudesign** [comment]
@thomasplevy the problem is about 417 not 414 ( 'wp-cron.php' === $pagenow ||)

**Comment by kprovance** [comment]
I spoke with management last night regarding this.  This new code stays.  Adding one line to your args array isn't a big deal.  We have other things to take care of and my time is needed there.  They want me to move on from this.  That's the decision from the top.  End of story.  Thanks. Locking thread.
