### ISSUE TITLE
Fatal error: Uncaught TypeError: Redux_Options_Defaults::default_values(): Return value must be of type array

### ISSUE THREAD

**Issue by humayun-sarfraz** [reduxframework/redux-framework#3822]
Hi,

I am using the following theme option:

array(
        'id'    => 'opt-button-set-term',
        'type'  => 'select',
        'title' => __( 'Select Term', 'redux-framework-demo' ), 
        'data'  => 'terms',
        'multi'            => true,
        'ajax'             => true,
        'sortable'         => true,
        'args'  => array(
            'taxonomies' => array( 'taxonomy_name' ),
            'hide_empty' => false,
        )
    );

It throws following error:
Fatal error: Uncaught TypeError: Redux_Options_Defaults::default_values(): Return value must be of type array, string returned in F:\wamp\www\XXXXXX.com\wp-content\plugins\redux-framework\redux-core\inc\classes\class-redux-options-defaults.php:51

In the following file 
wp-content\plugins\redux-framework\redux-core\inc\classes\class-redux-options-defaults.php
Line Number: 51 It should return array() instead of empty string.

Thanks,

**Comment by kprovance** [comment]
Fixed in repo.

**Comment by humayun-sarfraz** [comment]
Facing same issue in 4.3.1 and it returning empty instead of array.

In the following file
wp-content\plugins\redux-framework\redux-core\inc\classes\class-redux-options-defaults.php
Line Number: 51 It should return array() instead of empty string.
