### ISSUE TITLE
I didn't find global variable values. It's showing null value.

### ISSUE THREAD

**Issue by mddalwar** [reduxframework/redux-framework#3827]
Hello,
I have used the redux framework to create theme options in my Theme. But when I check the global variable using PHP var_dump function in the functions.php file it's showing null value. But when I checked the same variable in the header.php file it's showing all values.

**Comment by kprovance** [comment]
PLease try upgrading to the version in this repo.

**Comment by mddalwar** [comment]
Thanks, I have got a solution.
