### ISSUE TITLE
Multi-text Color Field validation

### ISSUE THREAD

**Issue by kprovance** [reduxframework/redux-framework#3828]
Advance Features > Field validation

Under "Multi Text Option - Color Validated" - when adding invalid value an error message will appear, but when changed to the correct value, the error message still stays - https://share.getcloudapp.com/YEuOKAA6

**Comment by cyberwani** [comment]
I have noticed similar behavior in the text field with the URL validation.

**Comment by Drayyblacc** [comment]
this is a nice theme but unfortunately i cannot seem to win on changing theme color

**Comment by kprovance** [comment]
@Drayyblacc , We do not author or sell themes.  You will need to contact your theme author support on that issue.

**Comment by Drayyblacc** [comment]
I am not sure if envato can help me with this ?

**Comment by kprovance** [comment]
Not Envato; the specific author of your theme.  Their name would be listed on the page from which you downloaded it.  We can't help you wither as we did not author or sell the theme, or any theme.  Sorry.

**Comment by Drayyblacc** [comment]
okay no worries i understand now thanks a lot for your help

**Comment by ahahsan99** [comment]
There is a problem with my site using this theme. When I install elementor plugin then my site is not working on any device except my admin dashboard.

**Comment by ahahsan99** [comment]
There is a problem with my site using this theme. When I install elementor plugin then my site is not working on any device except my admin dashboard.

**Comment by kprovance** [comment]
@ahahsan99 - We do not author or sell themes. You will need to contact your theme author for support on that issue.

**Comment by Drayyblacc** [comment]
just crosscheck the theme builder if its the one that comes with the theme
