### ISSUE TITLE
widget area notice WordPress 5.8

### ISSUE THREAD

**Issue by DesignInvento** [reduxframework/redux-framework#3829]
Embedded version 4.2.14 but still notice not fixed
 
Notice: wp_enqueue_script() was called incorrectly. "wp-editor" script should not be enqueued together with the new widgets editor (wp-edit-widgets or wp-customize-widgets). Please see Debugging in WordPress for more information. (This message was added in version 5.8.0.)

**Comment by kprovance** [comment]
Gonna need more info.  Please refer to the posting guidelines

**Comment by DesignInvento** [comment]
ignore it another plugin was culprit,
