### ISSUE TITLE
You don't have permission to access this page

### ISSUE THREAD

**Issue by PYPLCode** [reduxframework/redux-framework#3831]
after assigning a second user as an editor to the website the login is giving an error:

"You don't have permission to access this page."

when I deactivate redux the user can log in but when I activate again it gives this error

**Comment by kprovance** [comment]
If you are a theme user, you need to contact the theme author.  Per ou support guidelines, which I assume you read, we are unable to support individual themes and theme users.

It sounds like a user with fewer permissions is attempting to access a page created by Redux.  Redux can be set to only display pages to users with certin permissions.  Based on this very limited information, that's my guess.

**Comment by PYPLCode** [comment]
Ok thanks, that was a block in theme configurations.

**Comment by Hosni-Aboshanab** [comment]
How are you, I hope you are fine, I have the same problem, how did you solve it? @PYPLCode

**Comment by smailtech1** [comment]
How did you solve the problem
