### ISSUE TITLE
Lost customizer data after some interval

### ISSUE THREAD

**Issue by testhome132** [reduxframework/redux-framework#3839]
Hey Guys,

I have added redux framework with twenty-twenty theme and No one plugin activated. ( Redux framework version is - 4.3.1 )
Issue is like - When I add/change value in customizer and wait for call other action ( Like - wait for call customize_save action second time ). Once customize_save action call second time and after that I add/change other fields value then my previously change lost from redux global variable. 

For more info you can check this video in which I have recorded all things.
https://screencast-o-matic.com/watch/crQt6QV6pQH

Thanks.

**Comment by kprovance** [comment]
Are you still interested in having me investigate this?  If so, I need to see your theme.  If not, please close this ticket.  Thanks!

**Comment by kprovance** [comment]
Closing over inactivity.
