### ISSUE TITLE
Preloader hide

### ISSUE THREAD

**Issue by Ads-1986** [reduxframework/redux-framework#3840]
Hello, 
I'm trying to hide the preloader on Piohost template used with wordpress at https://www.biolifemetrics.com/ 
I use CSS code and try to directly edit the main.css, but the preloader continues to be shown.
Please can you help me to remove it?
TY
AdS

**Comment by kprovance** [comment]
Hi,

We did not author this theme, or any theme.  You will need to contact the theme's author for all support related matters.  Good luck.
