### ISSUE TITLE
Rest API link to use in custom blocks

### ISSUE THREAD

**Issue by HamdanMahran** [reduxframework/redux-framework#3843]
Hello Awesome team,
i need the Rest Api link that contains all options 👍

<code>
wp.apiFetch({
    url: '/wp-json/wp/v2/redux'
})
</code>

Thank you.

**Comment by kprovance** [comment]
We do not have a REST endpoint to grab Redux options.  At this point, you'll need to code in your own.  It may be something we'll look at in a future release.  You could easily convert the global option variable into a JSON string and pass that to your JS.
