### ISSUE TITLE
CSS and JS files not loaded when embedded in a theme

### ISSUE THREAD

**Issue by milanhirapra** [reduxframework/redux-framework#3850]
## Site Health Report

We have implemented redux framework in the theme. But, If we use version 4.3.1 then the CSS and JS files are not loaded in the theme option page and customise page and it's working in previous version.
**It's happen on linux systems/server.**
Here is the screenshot: https://nimb.ws/ZXn4qQ

## Steps to reproduce

1. Download Redux framework plugin from wordpress directory.
2. Copy entire directory and paste in the theme folder
3. Include redux framework core class and config file.
4. Go to theme option and see the error in console: https://nimb.ws/ZXn4qQ

**Here is the file structure inside the theme folder: https://nimb.ws/2pbLKQ**

## Expected Behavior

The all CSS and JS files should include proper.

## Actual Behavior

The assets file URL path return wrong. The URL is return parent directory instead of child.

For example: 
Actual URL:  https://domain.com/wp-content/themes/sample-theme/inc/admin/framework/assets/css/redux-fields.min.css?ver=4.3.1
Expected URL:  https://domain.com/wp-content/themes/sample-theme/inc/admin/framework/redux-core/assets/css/redux-fields.min.css?ver=4.3.1

## Any Error Details (PHP/JavaScript)

Getting error in browser console for both theme option page and customise page: https://nimb.ws/ZXn4qQ

**Comment by kprovance** [comment]
Finally, someone with some actual data!

Would you please send me a copy of the theme?  If you;d prefer not to post it here, you can email it to kevin.provance@gmail.com.  This way I can rule out any potential config issues.  If I am able to, I may need access to your server and an admin login so I can finally figure out what causes this.  If it comes to that, we can handle it privately.  Let's begin with the theme first and go from there.

- Kev

**Comment by milanhirapra** [comment]
Hi @kprovance,

I sent you an email. Please check and let me know.

**Comment by kprovance** [comment]
Received.  I'll begin looking into it this afternoon.

**Comment by kprovance** [comment]
Well, I'm not sure if locking unregistered users out of the options panel is the best idea.  Regardless, I can't do much because of it.

**Comment by kprovance** [comment]
@milanhirapra - Install v4.3.3.1 from this repo and see if that resolves the issue for you.

**Comment by milanhirapra** [comment]
Thanks @kprovance!

I will update Redux framework and let you know,

**Comment by milanhirapra** [comment]
This patch is working. Now, I am closing this issue.
Thanks @kprovance!

**Comment by kprovance** [comment]
That's excellent to hear!  This has been a lingering issue for a while.  I appreciate your help and patience with this issue.  Good luck!
