### ISSUE TITLE
Style issue

### ISSUE THREAD

**Issue by f-rahim** [reduxframework/redux-framework#3860]
I have downloaded and tried to use this framework.
But it has a styling issue.

**Comment by kprovance** [comment]
Hi,

I don't know what that means.  Please review the posting guidelines versus skipping over them and post back the *required* information.  Thanks.

https://github.com/reduxframework/redux-framework/issues/new?assignees=&labels=&template=dev.md

**Comment by f-rahim** [comment]
I mean, When I use the redux updated version on my new theme,
Then go to "Sample Options", I saw its style is broken, 
Hope you test that issue.

**Comment by kprovance** [comment]
Add this global arg: https://devs.redux.io/configuration/global_arguments.html#admin-theme  Set it to 'classic.'

If you are not the theme author, you will need to contact them to make that adjustment as we do not support themes.
