### ISSUE TITLE
Global variable returning null after the v4.3.6 update.

### ISSUE THREAD

**Issue by webbudesign** [reduxframework/redux-framework#3861]
## Site Health Report
`
### wp-core ###

version: 5.8.3
site_language: en_US
user_language: en_US
timezone: +03:00
permalink: /%postname%/
https_status: true
multisite: false
user_registration: 0
blog_public: 0
default_comment_status: open
environment_type: production
user_count: 4
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /var/www/vhosts/pointfindertheme.com/tr.pointfindertheme.com
wordpress_size: 64.61 MB (67747413 bytes)
uploads_path: /var/www/vhosts/pointfindertheme.com/tr.pointfindertheme.com/wp-content/uploads
uploads_size: 55.98 MB (58699350 bytes)
themes_path: /var/www/vhosts/pointfindertheme.com/tr.pointfindertheme.com/wp-content/themes
themes_size: 8.60 MB (9016065 bytes)
plugins_path: /var/www/vhosts/pointfindertheme.com/tr.pointfindertheme.com/wp-content/plugins
plugins_size: 226.18 MB (237169968 bytes)
database_size: 21.89 MB (22953984 bytes)
total_size: 377.26 MB (395586780 bytes)

### wp-dropins (3) ###

advanced-cache.php: true
db.php: true
maintenance.php: true

### wp-active-theme ###

name: Pointfinder (pointfinder)
version: 2.1.1
author: Webbu (@webbudesign)
author_website: http://themeforest.net/user/Webbu
parent_theme: none
theme_features: core-block-patterns, automatic-feed-links, post-formats, post-thumbnails, bbpress, woocommerce, html5, title-tag, align-wide, wp-block-styles, responsive-embeds, editor-styles, menus, widgets
theme_path: /var/www/vhosts/pointfindertheme.com/tr.pointfindertheme.com/wp-content/themes/pointfinder
auto_update: Enabled

### wp-themes-inactive (1) ###

Point Finder Child Theme: version: 1.9, author: Your name here, Auto-updates enabled

### wp-plugins-active (8) ###

Advanced Custom Fields: version: 5.11.4, author: Delicious Brains, Auto-updates disabled
Advanced Custom Fields PRO: version: 5.11.4, author: Delicious Brains, Auto-updates enabled
PointFinder Core Elements: version: 1.2.6, author: Webbu, Auto-updates enabled
Query Monitor: version: 3.8.2, author: John Blackbourn, Auto-updates disabled
Redux: version: 4.3.6, author: Extendify, Auto-updates disabled
Ultimate Addons for WPBakery Page Builder: version: 3.19.11, author: Brainstorm Force, Auto-updates enabled
WPBakery Page Builder: version: 6.8.0, author: Michael M - WPBakery.com, Auto-updates enabled
WP Mail SMTP: version: 3.2.1, author: WPForms, Auto-updates disabled

### wp-plugins-inactive (31) ###

bbPress: version: 2.6.9, author: The bbPress Contributors, Auto-updates disabled
Classic Editor: version: 1.6.2, author: WordPress Contributors, Auto-updates disabled
Coming Soon Page, Maintenance Mode & Landing Pages by SeedProd: version: 6.6.0, author: SeedProd, Auto-updates disabled
Custom Fonts: version: 1.3.3, author: Brainstorm Force, Auto-updates disabled
Debug Bar: version: 1.1.2, author: wordpressdotorg, Auto-updates disabled
Elementor: version: 3.5.3, author: Elementor.com, Auto-updates disabled
Elementor Beta (Developer Edition): version: 1.1.1, author: Elementor.com, Auto-updates disabled
Envato Market: version: 2.0.6, author: Envato, Auto-updates enabled
Envato Theme Check: version: 20180222, author: Scott Parry, Auto-updates enabled
Front End PM: version: 11.3.3, author: Shamim Hasan, Auto-updates disabled
One Click Demo Import: version: 3.0.2, author: OCDI, Auto-updates disabled
PointFinder Additional Functions: version: 1.1.1, author: Webbu, Auto-updates enabled
PointFinder Additional Location Functions: version: 1.0.0, author: Webbu, Auto-updates enabled
PointFinder Image Actions: version: 1.0.0, author: Webbu, Auto-updates enabled
PointFinder Special Addon for Links: version: 1.0.0, author: Webbu, Auto-updates enabled
PointFinder User Subscriptions: version: 1.6.4, author: Webbu, Auto-updates enabled
PointFinder User Subscriptions (Beermaps): version: 1.7.3, author: Webbu, Auto-updates enabled
Post Duplicator: version: 2.26, author: Metaphor Creations, Auto-updates disabled
RTL Tester: version: 1.2, author: <a href="http://blog.yoavfarhi.com">Yoav Farhi</a>, <a href="http://automattic.com">Automattic</a>, Auto-updates enabled
Slider Revolution: version: 6.5.14, author: ThemePunch, Auto-updates enabled
Templatera: version: 2.0.5, author: WPBakery, Auto-updates enabled
WordPress Beta Tester: version: 3.1.4, author: Peter Westwood, Andy Fragen, Auto-updates disabled
WordPress Importer: version: 0.7, author: wordpressdotorg, Auto-updates disabled
WP-Optimize - Clean, Compress, Cache: version: 3.2.1, author: David Anderson, Ruhani Rabin, Team Updraft, Auto-updates disabled
WP All Export: version: 1.3.3, author: Soflyy, Auto-updates disabled
WP Crontrol: version: 1.12.0, author: John Blackbourn & crontributors, Auto-updates disabled
WPML Media: version: 2.6.2, author: OnTheGoSystems, Auto-updates enabled
WPML Multilingual CMS: version: 4.4.8, author: OnTheGoSystems, Auto-updates enabled
WPML String Translation: version: 3.1.6, author: OnTheGoSystems, Auto-updates enabled
WPML Translation Management: version: 2.10.4, author: OnTheGoSystems, Auto-updates enabled
WP Rocket: version: 3.9.1.1, author: WP Media, Auto-updates enabled

### wp-media ###

image_editor: WP_Image_Editor_Imagick
imagick_module_version: 1690
imagemagick_version: ImageMagick 6.9.10-68 Q16 x86_64 2021-10-14 https://imagemagick.org
imagick_version: 3.6.0
file_uploads: File uploads is turned off
post_max_size: 32M
upload_max_filesize: 32M
max_effective_size: 32 MB
max_file_uploads: 20
imagick_limits: 
	imagick::RESOURCETYPE_AREA: 62 GB
	imagick::RESOURCETYPE_DISK: 9.2233720368548E+18
	imagick::RESOURCETYPE_FILE: 6144
	imagick::RESOURCETYPE_MAP: 62 GB
	imagick::RESOURCETYPE_MEMORY: 31 GB
	imagick::RESOURCETYPE_THREAD: 1
imagemagick_file_formats: 3FR, 3G2, 3GP, AAI, AI, ART, ARW, AVI, AVS, BGR, BGRA, BGRO, BMP, BMP2, BMP3, BRF, CAL, CALS, CANVAS, CAPTION, CIN, CIP, CLIP, CMYK, CMYKA, CR2, CRW, CUR, CUT, DATA, DCM, DCR, DCX, DDS, DFONT, DNG, DOT, DPX, DXT1, DXT5, EPDF, EPI, EPS, EPS2, EPS3, EPSF, EPSI, EPT, EPT2, EPT3, ERF, EXR, FAX, FILE, FITS, FRACTAL, FTP, FTS, G3, G4, GIF, GIF87, GRADIENT, GRAY, GRAYA, GROUP4, GV, H, HALD, HDR, HISTOGRAM, HRZ, HTM, HTML, HTTP, HTTPS, ICB, ICO, ICON, IIQ, INFO, INLINE, IPL, ISOBRL, ISOBRL6, J2C, J2K, JNG, JNX, JP2, JPC, JPE, JPEG, JPG, JPM, JPS, JPT, JSON, K25, KDC, LABEL, M2V, M4V, MAC, MAGICK, MAP, MASK, MAT, MATTE, MEF, MIFF, MKV, MNG, MONO, MOV, MP4, MPC, MPEG, MPG, MRW, MSL, MSVG, MTV, MVG, NEF, NRW, NULL, ORF, OTB, OTF, PAL, PALM, PAM, PANGO, PATTERN, PBM, PCD, PCDS, PCL, PCT, PCX, PDB, PDF, PDFA, PEF, PES, PFA, PFB, PFM, PGM, PGX, PICON, PICT, PIX, PJPEG, PLASMA, PNG, PNG00, PNG24, PNG32, PNG48, PNG64, PNG8, PNM, PPM, PREVIEW, PS, PS2, PS3, PSB, PSD, PTIF, PWP, RADIAL-GRADIENT, RAF, RAS, RAW, RGB, RGBA, RGBO, RGF, RLA, RLE, RMF, RW2, SCR, SCT, SFW, SGI, SHTML, SIX, SIXEL, SPARSE-COLOR, SR2, SRF, STEGANO, SUN, SVG, SVGZ, TEXT, TGA, THUMBNAIL, TIFF, TIFF64, TILE, TIM, TTC, TTF, TXT, UBRL, UBRL6, UIL, UYVY, VDA, VICAR, VID, VIFF, VIPS, VST, WBMP, WMF, WMV, WMZ, WPG, X, X3F, XBM, XC, XCF, XPM, XPS, XV, XWD, YCbCr, YCbCrA, YUV
gd_version: bundled (2.1.0 compatible)
gd_formats: GIF, JPEG, PNG, WebP, BMP, XPM
ghostscript_version: not available

### wp-server ###

server_architecture: Linux 3.10.0-1160.25.1.el7.x86_64 x86_64
httpd_software: Apache
php_version: 8.0.14 64bit
php_sapi: fpm-fcgi
max_input_variables: 20000
time_limit: 300
memory_limit: 256M
max_input_time: 60
upload_max_filesize: 32M
php_post_max_size: 32M
curl_version: 7.81.0 NSS/3.67
suhosin: false
imagick_availability: true
pretty_permalinks: true
htaccess_extra_rules: true

### wp-database ###

extension: mysqli
server_version: 10.5.13-MariaDB
client_version: mysqlnd 8.0.14

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /var/www/vhosts/pointfindertheme.com/tr.pointfindertheme.com/wp-content
WP_PLUGIN_DIR: /var/www/vhosts/pointfindertheme.com/tr.pointfindertheme.com/wp-content/plugins
WP_MEMORY_LIMIT: 40M
WP_MAX_MEMORY_LIMIT: 256M
WP_DEBUG: true
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: true
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: false
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_LOCAL_DEV: undefined
DB_CHARSET: utf8
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable
mu-plugins: writable
0: Writable

### redux-framework ###

version: 4.3.6
installation: plugin
data directory: /var/www/vhosts/pointfindertheme.com/tr.pointfindertheme.com/wp-content/plugins/redux-framework/redux-core/
browser: 
	Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36
	Browser: Chrome
	Version: 97.0.4692.71
	Platform: Windows

### redux-instance-pointfindertheme_options ###

opt_name: pointfindertheme_options
global_variable: pointfindertheme_options
dev_mode: false
ajax_save: true
page_slug: _pointfinderoptions
page_permissions: manage_options
menu_type: submenu
page_parent: pointfinder_tools
compiler: true
output: true
output_tag: true
templates_path: undefined
extensions: 
	Accordion: 1.0.0
	Ad Remove: 1.0.0
	Custom Icon: 1.0.0
	Custom Link Color: 1.0.0
	Custom Slides: 1.0.0
	Custom Sorter: 1.0.0
	Customizer: 4.0.0
	Import Export: 4.0.0
	Itempage: 1.0.0
	Metaboxes: 4.0.0
	Options Object: 4.0.0
	Search: 3.4.5
	Shortcodes: 4.3.5
	Sidebar Slides: 1.0.0
	Streetview: 1.0.0
	Vendor Support: 3.0.0

### redux-instance-pointfinderthemefmb_options ###

opt_name: pointfinderthemefmb_options
global_variable: pointfinderthemefmb_options
dev_mode: false
ajax_save: true
page_slug: _optsdsdsions
page_permissions: manage_options
menu_type: hidden
page_parent: pointfinder_tools
compiler: true
output: true
output_tag: true
templates_path: undefined
extensions: 
	Accordion: 1.0.0
	Ad Remove: 1.0.0
	Custom Icon: 1.0.0
	Custom Link Color: 1.0.0
	Custom Slides: 1.0.0
	Custom Sorter: 1.0.0
	Customizer: 4.0.0
	Import Export: 4.0.0
	Itempage: 1.0.0
	Metaboxes: 4.0.0
	Options Object: 4.0.0
	Search: 3.4.5
	Shortcodes: 4.3.5
	Sidebar Slides: 1.0.0
	Streetview: 1.0.0
	Vendor Support: 3.0.0

### redux-instance-pfascontrol_options ###

opt_name: pfascontrol_options
global_variable: pfascontrol_options
dev_mode: false
ajax_save: true
page_slug: _pfasconf
page_permissions: manage_options
menu_type: submenu
page_parent: pointfinder_tools
compiler: true
output: true
output_tag: true
templates_path: undefined
extensions: 
	Accordion: 1.0.0
	Ad Remove: 1.0.0
	Custom Icon: 1.0.0
	Custom Link Color: 1.0.0
	Custom Slides: 1.0.0
	Custom Sorter: 1.0.0
	Customizer: 4.0.0
	Import Export: 4.0.0
	Itempage: 1.0.0
	Metaboxes: 4.0.0
	Options Object: 4.0.0
	Search: 3.4.5
	Shortcodes: 4.3.5
	Sidebar Slides: 1.0.0
	Streetview: 1.0.0
	Vendor Support: 3.0.0

### redux-instance-pfcustomfields_options ###

opt_name: pfcustomfields_options
global_variable: pfcustomfields_options
dev_mode: false
ajax_save: true
page_slug: _pfcifoptions
page_permissions: manage_options
menu_type: submenu
page_parent: pointfinder_tools
compiler: true
output: true
output_tag: true
templates_path: undefined
extensions: 
	Accordion: 1.0.0
	Ad Remove: 1.0.0
	Custom Icon: 1.0.0
	Custom Link Color: 1.0.0
	Custom Slides: 1.0.0
	Custom Sorter: 1.0.0
	Customizer: 4.0.0
	Import Export: 4.0.0
	Itempage: 1.0.0
	Metaboxes: 4.0.0
	Options Object: 4.0.0
	Search: 3.4.5
	Shortcodes: 4.3.5
	Sidebar Slides: 1.0.0
	Streetview: 1.0.0
	Vendor Support: 3.0.0

### redux-instance-pfsearchfields_options ###

opt_name: pfsearchfields_options
global_variable: pfsearchfields_options
dev_mode: false
ajax_save: true
page_slug: _pfsifoptions
page_permissions: manage_options
menu_type: submenu
page_parent: pointfinder_tools
compiler: true
output: true
output_tag: true
templates_path: undefined
extensions: 
	Accordion: 1.0.0
	Ad Remove: 1.0.0
	Custom Icon: 1.0.0
	Custom Link Color: 1.0.0
	Custom Slides: 1.0.0
	Custom Sorter: 1.0.0
	Customizer: 4.0.0
	Import Export: 4.0.0
	Itempage: 1.0.0
	Metaboxes: 4.0.0
	Options Object: 4.0.0
	Search: 3.4.5
	Shortcodes: 4.3.5
	Sidebar Slides: 1.0.0
	Streetview: 1.0.0
	Vendor Support: 3.0.0

### redux-instance-pointfindermail_options ###

opt_name: pointfindermail_options
global_variable: pointfindermail_options
dev_mode: false
ajax_save: true
page_slug: _pfmailoptions
page_permissions: manage_options
menu_type: submenu
page_parent: pointfinder_tools
compiler: true
output: true
output_tag: true
templates_path: undefined
extensions: 
	Accordion: 1.0.0
	Ad Remove: 1.0.0
	Custom Icon: 1.0.0
	Custom Link Color: 1.0.0
	Custom Slides: 1.0.0
	Custom Sorter: 1.0.0
	Customizer: 4.0.0
	Import Export: 4.0.0
	Itempage: 1.0.0
	Metaboxes: 4.0.0
	Options Object: 4.0.0
	Search: 3.4.5
	Shortcodes: 4.3.5
	Sidebar Slides: 1.0.0
	Streetview: 1.0.0
	Vendor Support: 3.0.0

### redux-instance-pfsidebargenerator_options ###

opt_name: pfsidebargenerator_options
global_variable: pfsidebargenerator_options
dev_mode: false
ajax_save: true
page_slug: _pfsidebaroptions
page_permissions: manage_options
menu_type: submenu
page_parent: pointfinder_tools
compiler: true
output: true
output_tag: true
templates_path: undefined
extensions: 
	Accordion: 1.0.0
	Ad Remove: 1.0.0
	Custom Icon: 1.0.0
	Custom Link Color: 1.0.0
	Custom Slides: 1.0.0
	Custom Sorter: 1.0.0
	Customizer: 4.0.0
	Import Export: 4.0.0
	Itempage: 1.0.0
	Metaboxes: 4.0.0
	Options Object: 4.0.0
	Search: 3.4.5
	Shortcodes: 4.3.5
	Sidebar Slides: 1.0.0
	Streetview: 1.0.0
	Vendor Support: 3.0.0

### redux-instance-pfitemreviewsystem_options ###

opt_name: pfitemreviewsystem_options
global_variable: pfitemreviewsystem_options
dev_mode: false
ajax_save: true
page_slug: _pfrevsystemconf
page_permissions: manage_options
menu_type: submenu
page_parent: pointfinder_tools
compiler: true
output: true
output_tag: true
templates_path: undefined
extensions: 
	Accordion: 1.0.0
	Ad Remove: 1.0.0
	Custom Icon: 1.0.0
	Custom Link Color: 1.0.0
	Custom Slides: 1.0.0
	Custom Sorter: 1.0.0
	Customizer: 4.0.0
	Import Export: 4.0.0
	Itempage: 1.0.0
	Metaboxes: 4.0.0
	Options Object: 4.0.0
	Search: 3.4.5
	Shortcodes: 4.3.5
	Sidebar Slides: 1.0.0
	Streetview: 1.0.0
	Vendor Support: 3.0.0

### redux-instance-pfsizecontrol_options ###

opt_name: pfsizecontrol_options
global_variable: pfsizecontrol_options
dev_mode: false
ajax_save: true
page_slug: _pfsizelimitconf
page_permissions: manage_options
menu_type: submenu
page_parent: pointfinder_tools
compiler: true
output: true
output_tag: true
templates_path: undefined
extensions: 
	Accordion: 1.0.0
	Ad Remove: 1.0.0
	Custom Icon: 1.0.0
	Custom Link Color: 1.0.0
	Custom Slides: 1.0.0
	Custom Sorter: 1.0.0
	Customizer: 4.0.0
	Import Export: 4.0.0
	Itempage: 1.0.0
	Metaboxes: 4.0.0
	Options Object: 4.0.0
	Search: 3.4.5
	Shortcodes: 4.3.5
	Sidebar Slides: 1.0.0
	Streetview: 1.0.0
	Vendor Support: 3.0.0

### redux-instance-pfpgcontrol_options ###

opt_name: pfpgcontrol_options
global_variable: pfpgcontrol_options
dev_mode: false
ajax_save: true
page_slug: _pfpgconf
page_permissions: manage_options
menu_type: submenu
page_parent: pointfinder_tools
compiler: true
output: true
output_tag: true
templates_path: undefined
extensions: 
	Accordion: 1.0.0
	Ad Remove: 1.0.0
	Custom Icon: 1.0.0
	Custom Link Color: 1.0.0
	Custom Slides: 1.0.0
	Custom Sorter: 1.0.0
	Customizer: 4.0.0
	Import Export: 4.0.0
	Itempage: 1.0.0
	Metaboxes: 4.0.0
	Options Object: 4.0.0
	Search: 3.4.5
	Shortcodes: 4.3.5
	Sidebar Slides: 1.0.0
	Streetview: 1.0.0
	Vendor Support: 3.0.0

### wp_mail_smtp ###

version: 3.2.1
license_key_type: lite
debug: No debug notices found.
db_tables: 4QRqn3m37_wpmailsmtp_tasks_meta, 4QRqn3m37_wpmailsmtp_debug_events
lite_install_date: Nov 18, 2020 @ 12:42am

`
## Steps to reproduce
I just update the latest version v4.3.6

## Expected Behavior
global variable returning null after the update.

## Actual Behavior
It should return the options panel.

## Any Error Details (PHP/JavaScript)
I see tons of errors because of no global variable.

**Comment by webbudesign** [comment]
I found an issue on the site health report. 
redux-instance-pointfindertheme_options - my global_variable is " pointfindertheme_option " and opt_name is " pointfindertheme_options " but both looks like same on the report.

**Comment by kprovance** [comment]
You may have to send me your theme on this one, as I cannot readily reproduce it.  Use wetransfer.com  my email is kevin.provance@gmail.com

**Comment by webbudesign** [comment]
Done

**Comment by kprovance** [comment]
Got it.  Gimme a few minutes to see what's going on.  This is probably series enough to do a new deployment today.  I'll let you know here when I figure it out.  Thanks for the heads up.

**Comment by kprovance** [comment]
@webbudesign - I just pushed 4.3.7 to the repo.  Give that a test and see if it fixes your issue.  It did here, but I'd like to be sure.  If it does, I'll deploy straight away!  Thanks!

**Comment by webbudesign** [comment]
Problem solved.

**Comment by kprovance** [comment]
Cool.  I'll deploy now to wp.org.
