### ISSUE TITLE
Demo content error

### ISSUE THREAD

**Issue by Alluwark** [reduxframework/redux-framework#3866]
when changing the logo of the demo it does not respect it, the options do not appear in the theme settings.

**Comment by Alluwark** [comment]
when changing the logo of the demo it does not respect it, the options do not appear in the theme settings.

**Comment by kprovance** [comment]
Please go back, read the posting guidelines, and provide the required information.  Thanks.

**Comment by kprovance** [comment]
Closed for inactivity.
