### ISSUE TITLE
I want to report two deprecation notice in core files.

### ISSUE THREAD

**Issue by webbudesign** [reduxframework/redux-framework#3871]
1) _enqueue is deprecated since version 4.0.0! Use enqueue_class->init() instead.
[redux-core/inc/extensions/metaboxes/class-redux-extension-metaboxes.php:560](https://github.com/reduxframework/redux-framework/blob/3788dc664da2bdf632d4c8f07f01aa318d2de5f9/redux-core/inc/extensions/metaboxes/class-redux-extension-metaboxes.php#L560)

2) get_header_html is deprecated since version 4.0.0! Use render_class->get_header_html( $field ) instead.
[redux-core/inc/extensions/metaboxes/class-redux-extension-metaboxes.php:1284](https://github.com/reduxframework/redux-framework/blob/3788dc664da2bdf632d4c8f07f01aa318d2de5f9/redux-core/inc/extensions/metaboxes/class-redux-extension-metaboxes.php#L1284)

These notices come on the meta box page on v4.3.11 of Redux Framework.

**Comment by kprovance** [comment]
Fixed.  You can get the update from this repo.  Thanks for the catch!

- Kev
