### ISSUE TITLE
PHP errors on class-redux-helpers.php after update PHP version

### ISSUE THREAD

**Issue by yderindere** [reduxframework/redux-framework#3875]
## Site Health Report
`
### wp-core ###

version: 5.9.2
site_language: en_US
user_language: en_US
timezone: +00:00
permalink: /%postname%/
https_status: false
multisite: false
user_registration: 0
blog_public: 1
default_comment_status: open
environment_type: local
user_count: 1
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /Users/themecube/Local Sites/escape/app/public
wordpress_size: 46.81 MB (49086232 bytes)
uploads_path: /Users/themecube/Local Sites/escape/app/public/wp-content/uploads
uploads_size: 38.70 MB (40580393 bytes)
themes_path: /Users/themecube/Local Sites/escape/app/public/wp-content/themes
themes_size: 31.55 MB (33085647 bytes)
plugins_path: /Users/themecube/Local Sites/escape/app/public/wp-content/plugins
plugins_size: 95.99 MB (100657953 bytes)
database_size: 7.08 MB (7421952 bytes)
total_size: 220.14 MB (230832177 bytes)

### wp-active-theme ###

name: Escape (escape)
version: 2.4
author: themecube
author_website: https://themeforest.net/user/themecube
parent_theme: none
theme_features: core-block-patterns, widgets-block-editor, post-thumbnails, automatic-feed-links, title-tag, menus, html5, custom-background, customize-selective-refresh-widgets, custom-logo, custom-header, woocommerce, wc-product-gallery-zoom, wc-product-gallery-lightbox, wc-product-gallery-slider, widgets
theme_path: /Users/themecube/Local Sites/escape/app/public/wp-content/themes/escape
auto_update: Disabled

### wp-themes-inactive (3) ###

Twenty Twenty: version: 1.9, author: the WordPress team, Auto-updates disabled
Twenty Twenty-One: version: 1.5, author: the WordPress team, Auto-updates disabled
Twenty Twenty-Two: version: 1.1, author: the WordPress team, Auto-updates disabled

### wp-plugins-active (9) ###

Booked: version: 2.3.5, author: Boxy Studio, Auto-updates disabled
CMB2: version: 2.10.1, author: CMB2 team, Auto-updates disabled
Contact Form 7: version: 5.5.6, author: Takayuki Miyoshi, Auto-updates disabled
Envato Theme Check: version: 1.0.0, author: Scott Parry, Auto-updates disabled
Slider Revolution: version: 6.5.19, author: ThemePunch, Auto-updates disabled
Template Library and Redux Framework: version: 4.3.12, author: Extendify, Auto-updates disabled
ThemeCube Core: version: 2.4, author: themecube, Auto-updates disabled
WooCommerce: version: 6.3.1, author: Automattic, Auto-updates disabled
WPBakery Page Builder: version: 6.8.0, author: Michael M - WPBakery.com, Auto-updates disabled

### wp-media ###

image_editor: WP_Image_Editor_GD
imagick_module_version: Not available
imagemagick_version: Not available
imagick_version: Not available
file_uploads: File uploads is turned off
post_max_size: 1000M
upload_max_filesize: 300M
max_effective_size: 300 MB
max_file_uploads: 20
gd_version: bundled (2.1.0 compatible)
gd_formats: GIF, JPEG, PNG, BMP
ghostscript_version: not available

### wp-server ###

server_architecture: Darwin 21.3.0 x86_64
httpd_software: Apache/2.4.43 (Unix)
php_version: 8.0.0 64bit
php_sapi: fpm-fcgi
max_input_variables: 4000
time_limit: 1200
memory_limit: 256M
max_input_time: 600
upload_max_filesize: 300M
php_post_max_size: 1000M
curl_version: 7.54.0 LibreSSL/2.6.5
suhosin: false
imagick_availability: false
pretty_permalinks: true
htaccess_extra_rules: false

### wp-database ###

extension: mysqli
server_version: 5.7.28
client_version: mysqlnd 8.0.0
max_allowed_packet: 16777216
max_connections: 151

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /Users/themecube/Local Sites/escape/app/public/wp-content
WP_PLUGIN_DIR: /Users/themecube/Local Sites/escape/app/public/wp-content/plugins
WP_MEMORY_LIMIT: 40M
WP_MAX_MEMORY_LIMIT: 256M
WP_DEBUG: true
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_ENVIRONMENT_TYPE: local
DB_CHARSET: utf8
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable
0: Writable

### redux-framework ###

version: 4.3.12
installation: plugin
data directory: /Users/themecube/Local Sites/escape/app/public/wp-content/plugins/redux-framework/redux-core/
browser: 
	Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.83 Safari/537.36
	Browser: Chrome
	Version: 99.0.4844.83
	Platform: Apple

### redux-instance-themecube ###

opt_name: themecube
global_variable: themecube
dev_mode: false
ajax_save: true
page_slug: _options
page_permissions: manage_options
menu_type: menu
page_parent: themes.php
compiler: true
output: true
output_tag: true
templates_path: /Users/themecube/Local Sites/escape/app/public/wp-content/themes/escape/inc/panel/
extensions: 
	Customizer: 4.0.0
	Import Export: 4.0.0
	Metaboxes: 4.0.0
	Options Object: 4.0.0
	Repeater: 4.3.7
	Search: 3.4.5
	Shortcodes: 4.3.5
	Wbc Importer: 1.0.3

`

## Steps to reproduce
I updated the PHP ver. 8.

## Any Error Details (PHP/JavaScript)

![Ekran Resmi 2022-03-26 15 03 13](https://user-images.githubusercontent.com/6400048/160238525-d1faa7a4-efb9-4cc4-bbe5-95dd2243a344.png)

**Comment by kprovance** [comment]
Are you the author of this theme or a user of the theme?  I ask because so far I have been unable to duplicate this,  which means I need a copy of the theme (or at the least know what setting you are entering into the RGBA field.

**Comment by kprovance** [comment]
Please download and install v4.3.12.4 from this repo and see if it resolves your issue.  I'm still guessing at this point since I cannot reproduce this.  If it does not, the question I posted earlier still applies.  Thanks!

**Comment by kprovance** [comment]
After some digging, it appears the author of this theme is using `transparent` as the default color for the `color_rgba` option.  That is an invalid value.  It needs to be a blank string.  Please contact the author and submit this as a bug report.  You're free to repeat what I've told you here.

I'll add some extra code to filter out bad default values so this doesn't happen in the future.

**Comment by yderindere** [comment]
> After some digging, it appears the author of this theme is using `transparent` as the default color for the `color_rgba` option. That is an invalid value. It needs to be a blank string. Please contact the author and submit this as a bug report. You're free to repeat what I've told you here.

Kevin,
Thank you for your quickly solution. I'll do it.
