### ISSUE TITLE
How to import settings from json programming?

### ISSUE THREAD

**Issue by steve231293** [reduxframework/redux-framework#3876]
Hello Redux author,

First of all thank you for great plugin.

Could you help me how to import settings with json file programming?

I spent 2 days without successfully.

Thanks in advanced.

**Comment by kprovance** [comment]
Redux already has an import/export field.  To do it manually would require some time and work.  Unfortunately, writing custom code doesn't fall under the scope of support we offer.

You might take a look at this project:  https://github.com/Webcreations907/WBC-Importer-extension  It's several years old and no longer maintained, but the author did write a way to import Redux settings outside the plugin.  Disclaimer: We did not write this code and I'm not sure how well it works anymore.  

Good luck.
