### ISSUE TITLE
I-spirit Slider

### ISSUE THREAD

**Issue by karo1984** [reduxframework/redux-framework#3880]
We have a problem with I-Spirit Slider, I Can Not Change The Image, What can i do
![Captura de pantalla 2022-05-02 a las 9 28 46 p m](https://user-images.githubusercontent.com/104809686/166398631-c41a1fc5-5bd0-4fd3-8cca-8871d8d8ddc9.png)
?

**Comment by kprovance** [comment]
You'll need to contact the theme's author for support as we did not code the theme itself.  Good luck.

**Comment by hardikJoshi123** [comment]
@karo1984 I am facing same issue, would you please help how you fixed this? Thanks!
