### ISSUE TITLE
Typography Field - Unitless Line Height

### ISSUE THREAD

**Issue by DJMIMi** [reduxframework/redux-framework#3881]
Hi 

Can you add 'number-only' option for line-height part of the Typography field https://developer.mozilla.org/en-US/docs/Web/CSS/line-height

Regards.

**Comment by kprovance** [comment]
I can look into it.  FYI, `em` and no value are the same thing.

**Comment by DJMIMi** [comment]
Thanks for quick response. Unfortunately, It is not the same. Let's say parent has line-height 1.2 and child has different font size. Child's line height would be it's font-size * line height while if parent had 1.2em child's line-height would be equal to parent's line height.

**Comment by kprovance** [comment]
Added a new field argument, `line-height-unit` that you can set to blank. This will eliminate any unit from the output.  See: https://devs.redux.io/core-fields/typography.html

Caveat: If you change your code, any existing user who has saved typography values will need to resave their typography field to update to the new value with no unit.
