### ISSUE TITLE
use only framefowk delete and disable page builder

### ISSUE THREAD

**Issue by Masihgh** [reduxframework/redux-framework#3884]
hello
i have question
how use only framefowk delete and disable page builder? |:

**Comment by Masihgh** [comment]
how disable Gutenberg Template Library? in v4

**Comment by kprovance** [comment]
On the admin screen, click "Settings" and select "Redux." On the Redux welcome screen, click the "Templates" tab. On that screen, you can activate/deactivate any of the template libraries.
