### ISSUE TITLE
Redux::setSection is deprecated!

### ISSUE THREAD

**Issue by carboxyalic** [reduxframework/redux-framework#3889]
Hi my wordpress website is throwing this error and i guess this has more to do with version. The error is as follows:

PHP Deprecated: Redux::setSection is <strong>deprecated</strong> since version Redux 4.3! Use Redux::set_section( $opt_name, $section ) instead. in /nas/content/live/website-name/wp-includes/functions.php on line 5323

Let me know if there's anything i can do to resolve this.

**Comment by kprovance** [comment]
That's a deprecation notice, not an error. It means the author of your theme has not updated the Redux API in their project as we asked devs to do four years ago. We're now enforcing this. I would contact them and advise them of this: https://devs.redux.io/guides/other/migration-guide.html

Alternatively, you could disable WP_DEBUG in the wp-config to not display errors, or adjust the settings of the php.ini not to show deprecation notices.

Good luck.
