### ISSUE TITLE
Framework is loading Custom Post Option for Select Field on Admin-Side Page Load

### ISSUE THREAD

**Issue by ak-singla** [reduxframework/redux-framework#3890]
Hello, 

I am not sure if this is how it is supposed to work, but I see that the select option with the following configuration is being loaded on every page load, even on the plugins section of the admin panel. 
![image](https://user-images.githubusercontent.com/6893693/179204310-96535f74-e02d-4c87-a872-a576862fec79.png)

I could confirm this by using the query monitor plugin, please see the following screenshot: 
![Screenshot of Plugins ‹ IJARIIT — WordPress](https://user-images.githubusercontent.com/6893693/179204501-1de770b9-0442-41cb-ab81-d55a31a93dd4.jpg)

1. Is there a way to load it only when the options panel is loaded? 
2. I have two select fields with the same options (the same custom post), is there a way to provide the same options set to the second field as well?

**Comment by kprovance** [comment]
1) The short answer is no. Redux has to load to show its admin menu items (among other things) even when the options panel isn't loaded. All plugins do.

2) I'm not sure I understand the question. Why not copy and paste the field? As long as the `id` argument of the field is unique, you can duplicate as many fields as you need.
