### ISSUE TITLE
Changing the appearance of the admin panel

### ISSUE THREAD

**Issue by harbievan** [reduxframework/redux-framework#3891]
Hello
What should we do if we want to change the appearance of the admin section of this plugin?

All appearance changes can be called from the style section of the template itself and not changed at all from the plugin? I tried but it didn't work
thank you.

**Comment by kprovance** [comment]
Here are instructions for changing templates: https://devs.redux.io/guides/advanced/panel-templates.html

 Instructions to override the Redux CSS so you can write your own, to style the plane however you wish: https://devs.redux.io/guides/advanced/overriding-default-css.html

Good luck.
