### ISSUE TITLE
remove menu welcome page

### ISSUE THREAD

**Issue by Stargate-project** [reduxframework/redux-framework#3907]
Hello,  I am using the latest version 4.3 and wp 6.0.2
after creating my own custom page with a few basic fields I still see the Redux menu link to "Welcome to Redux Framework 4.3"
under the Settings  tab, is there a way to hide this menu link?

I have tried `Redux::disable_demo();` and `'dev_mode'                  => false,`

but it's still there

**Comment by kprovance** [comment]
There is no way to turn off the Redux menu item, as that's where Redux-specific options are, and the Pro registration interface.

**Comment by Stargate-project** [comment]
ok but I'm using an embeded version of redux, I dont need any other redux menu items

```
Copyright © author
Link: https://devs.redux.io/guides/advanced/embedding-redux.html

if ( !class_exists( 'ReduxFramework' ) && file_exists( dirname( __FILE__ ) . '/ReduxFramework/redux-core/framework.php' ) ) {
    require_once( dirname( __FILE__ ) . '/ReduxFramework/redux-core/framework.php' );
}
if ( !isset( $redux_demo ) && file_exists( dirname( __FILE__ ) . '/ReduxFramework/sample/sample-config.php' ) ) {
    require_once( dirname( __FILE__ ) . '/ReduxFramework/sample/sample-config.php' );
}

```
