### ISSUE TITLE
Repeater not Working in Custom Post Type

### ISSUE THREAD

**Issue by imadeelnazar** [reduxframework/redux-framework#3910]
Hi There,

I am Theme Developer, I am using Repeater in Custom Post type and Page some reason repeater just showing static fields on custom post type but on theme options repeater working perfectly fine.

Any help would be great.

Thank You

**Comment by kprovance** [comment]
Problem one. All of the request information left blank? You'll need to go back, read the instructions provided, and post that information. "It doesn't work, why?" tells me nothing.  https://raw.githubusercontent.com/reduxframework/redux-framework/master/.github/ISSUE_TEMPLATE/dev.md

**Comment by kprovance** [comment]
Did you check the console log or error logs for errors? I am unable to recreate this issue. Please post your theme so I can download it and take a look without all the guesswork. Thanks.

**Comment by imadeelnazar** [comment]
Hi Kevin,

I have created a small video i hope it will explain what actually i am facing.

https://share.vidyard.com/watch/JzQd1zuca6vrcswi1qVaaa?
You need to install the plugin after installing the Redux Framework Plugin and activate any WordPress default theme.

Here is the Redux Plugin i am developing for the Theme Options and Custom FIelds.
https://drive.google.com/file/d/1OKlXjaK5XelCZDBYgXtZr5YbTe2pfrAJ/view?usp=sharing

Thank You

**Comment by kprovance** [comment]
Your metabox config was incorrect. Here is how it should look.

```php
<?php

defined( 'ABSPATH' ) || exit;

if ( ! class_exists( 'Redux_Metaboxes' ) ) {
	return;
}
Redux_Metaboxes::set_box(
	$redux_testing_opt,
	array(
		'id'         => 'opt-event-simple-layout-one-section',
		'title'      => esc_html__( 'Simple Repeater With One Field', 'your-textdomain-here' ),
		'post_types' => array( 'post' ),
		'position'   => 'normal', // normal, advanced, side.
		'priority'   => 'high', // high, core, default, low.
		'sections'   => array(
			array(
				'fields' => array(
					array(
						'id'       => 'opt-event-simple-layout-one-field',
						'type'     => 'repeater',
						'title'    => esc_html__( 'Repeater', 'your-textdomain-here' ),
						'subtitle' => esc_html__( 'Repeater', 'your-textdomain-here' ),
						'fields'   => array(
							array(
								'id'          => 'title_field',
								'type'        => 'text',
								'placeholder' => esc_html__( 'Title', 'your-textdomain-here' ),
							),

						),
					),
				),
			),
		),
	)
);
```
For additional information how on to use metaboxes and configs, see here: https://devs.redux.io/core-extensions/metaboxes.html#example-config

Good luck.

**Comment by galaxyboy1988** [comment]
Hi 
we have the same problem and repeater not working in custom post type

here is the code

`Redux_Metaboxes::set_box(
	$sc_opt_name,
	array(
		'id'         => 'opt-event-simple-layout-one-section',
		'title'      => esc_html__( 'Simple Repeater With One Field', 'your-textdomain-here' ),
		'post_types' => array( 'sc_story' ),
		'position'   => 'normal', // normal, advanced, side.
		'priority'   => 'high', // high, core, default, low.
		'sections'   => array(
			array(
				'fields' => array(
					array(
						'id'       => 'opt-event-simple-layout-one-field',
						'type'     => 'repeater',
						'title'    => esc_html__( 'Repeater', 'your-textdomain-here' ),
						'subtitle' => esc_html__( 'Repeater', 'your-textdomain-here' ),
						'fields'   => array(
							array(
								'id'          => 'title_field',
								'type'        => 'text',
								'placeholder' => esc_html__( 'Title', 'your-textdomain-here' ),
							),

						),
					),
				),
			),
		),
	)
);`


we look into the console and this is the error data:

redux-repeater.js?ver=4.3.13:65 Uncaught TypeError: Cannot read properties of undefined (reading 'repeater')
    at HTMLFieldSetElement.<anonymous> (redux-repeater.js?ver=4.3.13:65:17)
