### ISSUE TITLE
How to change css variable using image select field in redux?

### ISSUE THREAD

**Issue by daghash** [reduxframework/redux-framework#3918]
I want to change the website container width by changing the CSS --site-width variable by using image select field in redux that has 2 options (boxed and fullwidth)

**Comment by kprovance** [comment]
Use the class name of the box and assign a value to it. 

```css
.redux-container-image_select .redux-image-select {
   <!-- whatever you want here. -->
}
```

**Comment by daghash** [comment]
> Use the class name of the box and assign a value to it.
> 
> ```css
> .redux-container-image_select .redux-image-select {
>    
> }
> ```

Thanks for your reply, but i want to change the current css variable that i used for website width

**Comment by kprovance** [comment]
I think this is what you want: https://devs.redux.io/configuration/fields/output-variables.html#example-generated-css-variables

Unfortunately, image_select is not a supported field.
