### ISSUE TITLE
Core using depreciated method

### ISSUE THREAD

**Issue by shazzad** [reduxframework/redux-framework#3926]
When WP_DEBUG is enabled, i see following error in my WordPress site:

> ( ! ) Deprecated: Function Redux::setSections is <strong>deprecated</strong> since version Redux 4.3! Use Redux::get_sections( $opt_name, $sections ) instead. in 

Following are my findings:

#### 1. Follow depreciation method reference is wrong.
https://github.com/reduxframework/redux-framework/blob/a9048c66e9866d0e87edbd7fbe98ac4c45eefd64/redux-core/inc/classes/class-redux-api.php#L566

It should be - `Redux::set_sections( $opt_name, $sections )`

#### 2. Core using the depreciated method here.
https://github.com/reduxframework/redux-framework/blob/a9048c66e9866d0e87edbd7fbe98ac4c45eefd64/redux-core/inc/extensions/metaboxes/class-redux-metaboxes-api.php#L114

Correct method should be `Redux::set_sections(`

Thanks.

**Comment by kprovance** [comment]
Fixes applied. Thanks!
