### ISSUE TITLE
efpose Custom Functions plugin is messing up with elementor

### ISSUE THREAD

**Issue by umerkhanwp** [reduxframework/redux-framework#3937]
I have widget from elementor on this page: (https://freelancecapsule.com/resources/)
But efpose Custom Functions plugin is not allowing to elementor widget to show, when I disable efpose Custom Functions plugin the elementor widget shows up but the elements by efpose Custom Functions plugin gets messed up because it deactived.

Let me know if there is any solution

-Umer

**Comment by kprovance** [comment]
Hi,

I'm not sure why you're posting this issue here. We aren't the authors of whatever theme you are using. It'd be best to contact whomever that is for support.  Good luck.
