### ISSUE TITLE
multi_media: HTML error in files list causes remove file to fail

### ISSUE THREAD

**Issue by alantygel** [reduxframework/redux-framework#3939]
## Site Health Report
`
### wp-core ###

version: 6.2
site_language: pt_BR
user_language: pt_BR
timezone: America/Sao_Paulo
permalink: /%year%/%monthnum%/%day%/%postname%/
https_status: false
multisite: false
user_registration: 0
blog_public: 1
default_comment_status: open
environment_type: production
user_count: 1
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /var/www/html/wordpress
wordpress_size: 8,83 GB (9481787692 bytes)
uploads_path: /var/www/html/wordpress/wp-content/uploads
uploads_size: 3,27 GB (3512532628 bytes)
themes_path: /var/www/html/wordpress/wp-content/themes
themes_size: 28,61 MB (29995585 bytes)
plugins_path: /var/www/html/wordpress/wp-content/plugins
plugins_size: 327,89 MB (343819712 bytes)
database_size: 4,59 MB (4816896 bytes)
total_size: 12,45 GB (13372952513 bytes)

### wp-active-theme ###

name: Twenty Twenty-Three (twentytwentythree)
version: 1.0 (latest version: 1.1)
author: a equipe do WordPress
author_website: https://br.wordpress.org
parent_theme: none
theme_features: core-block-patterns, wc-product-gallery-zoom, wc-product-gallery-lightbox, wc-product-gallery-slider, woocommerce, post-thumbnails, responsive-embeds, editor-styles, html5, automatic-feed-links, block-templates, widgets-block-editor
theme_path: /var/www/html/wordpress/wp-content/themes/twentytwentythree
auto_update: Desativado

### wp-themes-inactive (8) ###

Blocksy: version: 1.8.76, author: CreativeThemes (latest version: 1.8.81), Atualizações automáticas desativadas
Cetra: version: 1.0.0, author: Cooperativa Eita, Atualizações automáticas desativadas
Universidade Livre Feminista: version: 1.0.0, author: Cooperativa Eita, Atualizações automáticas desativadas
B Universidade Livre Feminista: version: 1.0.0, author: Cooperativa Eita, Atualizações automáticas desativadas
Twenty Nineteen: version: 2.3, author: a equipe do WordPress (latest version: 2.5), Atualizações automáticas desativadas
Twenty Twenty: version: 2.0, author: a equipe do WordPress (latest version: 2.2), Atualizações automáticas desativadas
Twenty Twenty-One: version: 1.6, author: a equipe do WordPress (latest version: 1.8), Atualizações automáticas desativadas
Twenty Twenty-Two: version: 1.2, author: the WordPress team (latest version: 1.4), Atualizações automáticas desativadas

### wp-plugins-active (3) ###

EEP Config: version: 1.0.0, author: Alan Tygel, Atualizações automáticas desativadas
Redux Framework: version: 4.4.0, author: Team Redux, Atualizações automáticas desativadas
WooCommerce: version: 7.5.1, author: Automattic, Atualizações automáticas desativadas

### wp-plugins-inactive (23) ###

Advanced Custom Fields: version: 6.0.7, author: WP Engine (latest version: 6.1.2), Atualizações automáticas desativadas
Advanced Custom Fields: Extended: version: 0.8.9.2, author: ACF Extended (latest version: 0.8.9.3), Atualizações automáticas desativadas
Akismet Anti-Spam: version: 5.0.2, author: Automattic (latest version: 5.1), Atualizações automáticas desativadas
Blocksy Companion (Premium): version: 1.8.42, author: CreativeThemes, Atualizações automáticas desativadas
Cool Timeline: version: 2.5, author: Cool Plugins (latest version: 2.6.1), Atualizações automáticas desativadas
Custom Post Type UI: version: 1.13.4, author: WebDevStudios (latest version: 1.13.5), Atualizações automáticas desativadas
Download Manager: version: 3.2.67, author: W3 Eden, Inc. (latest version: 3.2.70), Atualizações automáticas desativadas
FG Joomla to WordPress: version: 4.8.0, author: Frédéric GILLES, Atualizações automáticas desativadas
FooBox Image Lightbox: version: 2.7.17, author: FooPlugins (latest version: 2.7.25), Atualizações automáticas desativadas
FooGallery: version: 2.2.26, author: FooPlugins (latest version: 2.2.35), Atualizações automáticas desativadas
Getwid: version: 1.8.3, author: MotoPress, Atualizações automáticas desativadas
MainWP Child: version: 4.2.4, author: MainWP (latest version: 4.4.0.4), Atualizações automáticas desativadas
Nginx Cache: version: 1.0.5, author: Till Krüss, Atualizações automáticas desativadas
Query Monitor: version: 3.11.2, author: John Blackbourn (latest version: 3.12.1), Atualizações automáticas desativadas
Sementes - Sistema de Cestas Agroecológicas e de Grupos de Consumo Responsável: version: 1.2.11, author: Cooperativa EITA, Atualizações automáticas desativadas
UiPress Lite: version: 3.0.99, author: Admin 2020 (latest version: 3.1.12), Atualizações automáticas desativadas
WordPress Importer: version: 0.8, author: wordpressdotorg, Atualizações automáticas desativadas
WP Activity Log: version: 4.4.3.2, author: WP White Security, Atualizações automáticas desativadas
WP All Export: version: 1.3.9, author: Soflyy, Atualizações automáticas desativadas
WP Data Access: version: 5.3.4, author: Passionate Programmers B.V. (latest version: 5.3.7), Atualizações automáticas desativadas
wpDataTables - Tables & Table Charts: version: 2.1.53, author: TMS-Plugins (latest version: 2.1.55), Atualizações automáticas desativadas
WP fail2ban: version: 4.4.0.6, author: Charles Lecklider (latest version: 5.0.1), Atualizações automáticas desativadas
WP Mail SMTP: version: 3.5.1, author: WPForms (latest version: 3.7.0), Atualizações automáticas desativadas

### wp-media ###

image_editor: WP_Image_Editor_Imagick
imagick_module_version: 1687
imagemagick_version: ImageMagick 6.9.7-4 Q16 x86_64 20170114 http://www.imagemagick.org
imagick_version: 3.7.0
file_uploads: File uploads is turned off
post_max_size: 3000M
upload_max_filesize: 3000M
max_effective_size: 3 GB
max_file_uploads: 20
imagick_limits: 
	imagick::RESOURCETYPE_AREA: 122 MB
	imagick::RESOURCETYPE_DISK: 1073741824
	imagick::RESOURCETYPE_FILE: 6144
	imagick::RESOURCETYPE_MAP: 512 MB
	imagick::RESOURCETYPE_MEMORY: 256 MB
	imagick::RESOURCETYPE_THREAD: 1
	imagick::RESOURCETYPE_TIME: 1.844674407371E+19
imagemagick_file_formats: 3FR, AAI, AI, ART, ARW, AVI, AVS, BGR, BGRA, BGRO, BIE, BMP, BMP2, BMP3, BRF, CAL, CALS, CANVAS, CAPTION, CIN, CIP, CLIP, CMYK, CMYKA, CR2, CRW, CUR, CUT, DATA, DCM, DCR, DCX, DDS, DFONT, DJVU, DNG, DOT, DPX, DXT1, DXT5, EPDF, EPI, EPS, EPS2, EPS3, EPSF, EPSI, EPT, EPT2, EPT3, ERF, EXR, FAX, FILE, FITS, FRACTAL, FTP, FTS, G3, G4, GIF, GIF87, GRADIENT, GRAY, GROUP4, GV, H, HALD, HDR, HISTOGRAM, HRZ, HTM, HTML, HTTP, HTTPS, ICB, ICO, ICON, IIQ, INFO, INLINE, IPL, ISOBRL, ISOBRL6, JBG, JBIG, JNG, JNX, JPE, JPEG, JPG, JPS, JSON, K25, KDC, LABEL, M2V, M4V, MAC, MAGICK, MAP, MASK, MAT, MATTE, MEF, MIFF, MKV, MNG, MONO, MOV, MP4, MPC, MPEG, MPG, MRW, MSL, MSVG, MTV, MVG, NEF, NRW, NULL, ORF, OTB, OTF, PAL, PALM, PAM, PANGO, PATTERN, PBM, PCD, PCDS, PCL, PCT, PCX, PDB, PDF, PDFA, PEF, PES, PFA, PFB, PFM, PGM, PICON, PICT, PIX, PJPEG, PLASMA, PNG, PNG00, PNG24, PNG32, PNG48, PNG64, PNG8, PNM, PPM, PREVIEW, PS, PS2, PS3, PSB, PSD, PTIF, PWP, RADIAL-GRADIENT, RAF, RAS, RAW, RGB, RGBA, RGBO, RGF, RLA, RLE, RMF, RW2, SCR, SCT, SFW, SGI, SHTML, SIX, SIXEL, SPARSE-COLOR, SR2, SRF, STEGANO, SUN, SVG, SVGZ, TEXT, TGA, THUMBNAIL, TIFF, TIFF64, TILE, TIM, TTC, TTF, TXT, UBRL, UBRL6, UIL, UYVY, VDA, VICAR, VID, VIFF, VIPS, VST, WBMP, WMF, WMV, WMZ, WPG, X, X3F, XBM, XC, XCF, XPM, XPS, XV, XWD, YCbCr, YCbCrA, YUV
gd_version: 2.3.3
gd_formats: GIF, JPEG, PNG, WebP, BMP, XPM
ghostscript_version: 9.50

### wp-server ###

server_architecture: Linux 5.4.0-146-generic x86_64
httpd_software: Apache/2.4.41 (Ubuntu)
php_version: 7.4.33 64bit
php_sapi: apache2handler
max_input_variables: 1000
time_limit: 30
memory_limit: 128M
admin_memory_limit: 256M
max_input_time: 60
upload_max_filesize: 3000M
php_post_max_size: 3000M
curl_version: 7.68.0 OpenSSL/1.1.1j
suhosin: false
imagick_availability: true
pretty_permalinks: true
htaccess_extra_rules: false

### wp-database ###

extension: mysqli
server_version: 8.0.32-0ubuntu0.20.04.2
client_version: mysqlnd 7.4.33
max_allowed_packet: 67108864
max_connections: 151

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /var/www/html/wordpress/wp-content
WP_PLUGIN_DIR: /var/www/html/wordpress/wp-content/plugins
WP_MEMORY_LIMIT: 40M
WP_MAX_MEMORY_LIMIT: 256M
WP_DEBUG: true
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: true
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_ENVIRONMENT_TYPE: Indefinido
DB_CHARSET: utf8mb4
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable
0: Writable

### redux-framework ###

version: 4.4.0
installation: plugin
data directory: /var/www/html/wordpress/wp-content/plugins/redux-framework/redux-core/
browser: 
	Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/111.0
	Browser: Firefox
	Version: 111.0
	Platform: Linux

### redux-instance-eep_config ###

opt_name: eep_config
global_variable: eep_config
dev_mode: true
ajax_save: true
page_slug: eep_config_options
page_permissions: manage_options
menu_type: menu
page_parent: themes.php
compiler: true
output: true
output_tag: true
templates_path: undefined
extensions: 
	Accordion: 1.0.1
	Custom Fonts: 2.0.0
	Customizer: 4.0.0
	Datetime: 2.0.0
	Google Maps: 2.0.0
	Import Export: 4.0.0
	Js Button: 2.0.0
	Metaboxes: 4.0.0
	Multi Media: 4.3.15
	Options Object: 4.0.0
	Repeater: 4.3.7
	Search: 3.4.5
	Shortcodes: 4.3.5
	Social Profiles: 4.3.17
	Widget Areas: 1.0.0

`

## Steps to reproduce

1. Add a field of type multi_media according to the documentation sample
2. Add a file
3. Save
4. Reload

## Expected Behavior

A list of selected files should be rendered.

## Actual Behavior

The list is rendered with an html error, which causes a wrong formatting. Furthermore, javascript for removing files doesnt work.

## Any Error Details (PHP/JavaScript)

Apparently there is an extra `</li>` here : https://github.com/reduxframework/redux-framework/blob/b6aba73123f3bc96d1d77576c5bde61026aa3494/redux-core/inc/extensions/multi_media/multi_media/class-redux-multi-media.php#L146

**Comment by kprovance** [comment]
The fix is in the v4.0.0.1 version in this repo. I wasn't able to reproduce the JavaScript claim.

**Comment by alantygel** [comment]
Great, thanks. Hope the fix comes soon to the Wordpress plugin!
