### ISSUE TITLE
Prelorder Hide from Theme

### ISSUE THREAD

**Issue by SSDigimarkTechnology** [reduxframework/redux-framework#3940]
how i can Remove Website Preloader From Edumart Child/Parent Theme 1.0

**Comment by kprovance** [comment]
Hi,

As you should have read here, when opening a ticket, we do not support themes that use Redux. It is the responsibility of theme author to support their work: https://raw.githubusercontent.com/reduxframework/redux-framework/master/.github/ISSUE_TEMPLATE/user.md
