### ISSUE TITLE
Multimedia field: max upload limit fails when there are two fields in the same section 

### ISSUE THREAD

**Issue by alantygel** [reduxframework/redux-framework#3946]
## Site Health Report
`
### wp-core ###

version: 6.2
site_language: pt_BR
user_language: pt_BR
timezone: America/Sao_Paulo
permalink: /%year%/%monthnum%/%day%/%postname%/
https_status: false
multisite: false
user_registration: 0
blog_public: 1
default_comment_status: undefined
environment_type: production
user_count: 29648
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /var/www/html/wordpress
wordpress_size: 8,84 GB (9495332541 bytes)
uploads_path: /var/www/html/wordpress/wp-content/uploads
uploads_size: 3,28 GB (3520317020 bytes)
themes_path: /var/www/html/wordpress/wp-content/themes
themes_size: 29,82 MB (31272894 bytes)
plugins_path: /var/www/html/wordpress/wp-content/plugins
plugins_size: 332,29 MB (348435913 bytes)
database_size: 1,08 GB (1154790204 bytes)
total_size: 13,55 GB (14550148572 bytes)

### wp-dropins (1) ###

db.php: true

### wp-active-theme ###

name: Hello Elementor (hello-elementor)
version: 2.7.1
author: Equipe Elementor
author_website: https://elementor.com/?utm_source=wp-themes&utm_campaign=author-uri&utm_medium=wp-dash
parent_theme: none
theme_features: core-block-patterns, widgets-block-editor, post-thumbnails, menus, automatic-feed-links, title-tag, html5, custom-logo, editor-style, align-wide, woocommerce, wc-product-gallery-zoom, wc-product-gallery-lightbox, wc-product-gallery-slider, widgets
theme_path: /var/www/html/wordpress/wp-content/themes/hello-elementor
auto_update: Desativado

### wp-themes-inactive (10) ###

Blocksy: version: 1.8.76, author: CreativeThemes (latest version: 1.8.84), Atualizações automáticas desativadas
Cetra: version: 1.0.0, author: Cooperativa Eita, Atualizações automáticas desativadas
Expressão Popular: version: 1.0.1, author: Cooperativa EITA, Atualizações automáticas desativadas
Universidade Livre Feminista: version: 1.0.0, author: Cooperativa Eita, Atualizações automáticas desativadas
B Universidade Livre Feminista: version: 1.0.0, author: Cooperativa Eita, Atualizações automáticas desativadas
Twenty Nineteen: version: 2.3, author: a equipe do WordPress (latest version: 2.5), Atualizações automáticas desativadas
Twenty Twenty: version: 2.0, author: a equipe do WordPress (latest version: 2.2), Atualizações automáticas desativadas
Twenty Twenty-One: version: 1.6, author: a equipe do WordPress (latest version: 1.8), Atualizações automáticas desativadas
Twenty Twenty-Three: version: 1.0, author: a equipe do WordPress (latest version: 1.1), Atualizações automáticas desativadas
Twenty Twenty-Two: version: 1.2, author: the WordPress team (latest version: 1.4), Atualizações automáticas desativadas

### wp-plugins-active (47) ###

Additional Order Filters for WooCommerce: version: 1.10, author: Anton Bond, Atualizações automáticas desativadas
Admin Menu Editor: version: 1.11, author: Janis Elsts, Atualizações automáticas desativadas
Advanced Custom Fields: version: 6.1.4, author: WP Engine, Atualizações automáticas desativadas
Booster for WooCommerce: version: 6.0.5, author: Pluggabl LLC, Atualizações automáticas desativadas
Brazilian Market on WooCommerce: version: 3.7.2, author: Claudio Sanches, Atualizações automáticas desativadas
Claudio Sanches - Correios for WooCommerce: version: 3.8.0, author: Claudio Sanches, Atualizações automáticas desativadas
Contact Form 7: version: 5.7.5.1, author: Takayuki Miyoshi (latest version: 5.7.6), Atualizações automáticas desativadas
Contact Form 7 - Post Fields: version: 2.5.7, author: Markus Wiesenhofer, Atualizações automáticas desativadas
Contact Form CFDB7: version: 1.2.6.5, author: Arshid, Atualizações automáticas desativadas
Custom Order Numbers for WooCommerce: version: 1.4.0, author: Tyche Softwares (latest version: 1.4.1), Atualizações automáticas desativadas
Custom Post Type UI: version: 1.13.5, author: WebDevStudios, Atualizações automáticas desativadas
Disable Emails: version: 1.8.1, author: WebAware, Atualizações automáticas desativadas
EEP Config: version: 1.0.0, author: Alan Tygel, Atualizações automáticas desativadas
Elementor: version: 3.12.1, author: Elementor.com (latest version: 3.12.2), Atualizações automáticas desativadas
Elementor Pro: version: 3.12.2, author: Elementor.com (latest version: 3.12.3), Atualizações automáticas desativadas
FiboSearch - AJAX Search for WooCommerce: version: 1.23.0, author: FiboSearch Team, Atualizações automáticas desativadas
hCaptcha for WordPress: version: 2.7.0, author: hCaptcha, Atualizações automáticas desativadas
Import Export Suite for WooCommerce: version: 1.1.5, author: WebToffee, Atualizações automáticas desativadas
Import Export WordPress Users and WooCommerce Customers: version: 2.3.9, author: WebToffee, Atualizações automáticas desativadas
iThemes Security: version: 8.1.5, author: iThemes (latest version: 8.1.6), Atualizações automáticas desativadas
Kadence WooCommerce Email Designer: version: 1.5.10, author: Kadence WP, Atualizações automáticas desativadas
LiteSpeed Cache: version: 5.3.3, author: LiteSpeed Technologies (latest version: 5.4), Atualizações automáticas desativadas
Loco Translate: version: 2.6.4, author: Tim Whitlock, Atualizações automáticas desativadas
Min Max Quantity & Step Control for WooCommerce: version: 4.1, author: CodeAstrology Team, Atualizações automáticas desativadas
Modern Events Calendar Lite: version: 6.5.5, author: Webnus, Atualizações automáticas desativadas
Order Export & Order Import for WooCommerce: version: 2.3.3, author: WebToffee, Atualizações automáticas desativadas
Password Strength Settings for WooCommerce: version: 3.0.0, author: Daniel Santoro, Atualizações automáticas desativadas
Product Import Export for WooCommerce: version: 2.2.9, author: WebToffee, Atualizações automáticas desativadas
Redux Framework: version: 4.4.0, author: Team Redux, Atualizações automáticas desativadas
Regenerate Thumbnails: version: 3.1.5, author: Alex Mills (Viper007Bond), Atualizações automáticas desativadas
Relevanssi: version: 4.18.4, author: Mikko Saari (latest version: 4.19.0), Atualizações automáticas desativadas
Restrict User Access: version: 2.4.2, author: Joachim Jensen - DEV Institute, Atualizações automáticas desativadas
Sequential Order Numbers for WooCommerce: version: 1.5.0, author: WebToffee (latest version: 1.5.1), Atualizações automáticas desativadas
Set Custom Order Number: version: 1.0.7, author: SunArc, Atualizações automáticas desativadas
Smart Coupons For WooCommerce Coupons: version: 1.4.6, author: WebToffee, Atualizações automáticas desativadas
Sucuri Security - Auditing, Malware Scanner and Hardening: version: 1.8.39, author: Sucuri Inc., Atualizações automáticas desativadas
UpdraftPlus - Backup/Restore: version: 1.23.3, author: UpdraftPlus.Com, DavidAnderson, Atualizações automáticas desativadas
WooCommerce: version: 7.6.0, author: Automattic, Atualizações automáticas desativadas
WooCommerce Correios - Cálculo de Frete na Página do Produto (CFPP): version: 3.2, author: Lucas Bustamante, Atualizações automáticas desativadas
WooCommerce Product Bundles: version: 6.18.4, author: WooCommerce, Atualizações automáticas desativadas
Wordfence Security: version: 7.9.2, author: Wordfence, Atualizações automáticas desativadas
WordPress Importer: version: 0.8, author: wordpressdotorg, Atualizações automáticas desativadas
WP Activity Log: version: 4.5.0, author: WP White Security, Atualizações automáticas desativadas
WP Activity Log for WooCommerce: version: 1.5.1, author: WP White Security, Atualizações automáticas desativadas
WP Maps: version: 4.4.4, author: flippercode, Atualizações automáticas desativadas
YITH WooCommerce Wishlist: version: 3.19.0, author: YITH (latest version: 3.20.0), Atualizações automáticas desativadas
Yoast SEO: version: 20.5, author: Team Yoast, Atualizações automáticas desativadas

### wp-plugins-inactive (10) ###

Manage Notification E-mails: version: 1.8.4, author: Virgial Berveling, Atualizações automáticas desativadas
Order Splitter for WooCommerce: version: 4.8.4, author: Fahad Mahmood, Atualizações automáticas desativadas
Pre-Orders for WooCommerce: version: 1.2.11, author: Bright Plugins, Atualizações automáticas desativadas
Query Monitor: version: 3.12.1, author: John Blackbourn, Atualizações automáticas desativadas
Really Simple SSL: version: 6.2.4, author: Really Simple Plugins, Atualizações automáticas desativadas
Vindi WooCommerce 2: version: 1.1.13, author: Vindi (latest version: 1.2.1), Atualizações automáticas desativadas
WooCommerce All Products For Subscriptions: version: 4.0.5, author: WooCommerce, Atualizações automáticas desativadas
WooCommerce Subscriptions: version: 5.0.1, author: WooCommerce, Atualizações automáticas desativadas
WooCommerce Yapay: version: 0.6.4, author: Integração Yapay Intermediador, Atualizações automáticas desativadas
WP Mail SMTP Pro: version: 3.4.0, author: WPForms, Atualizações automáticas desativadas

### wp-media ###

image_editor: WP_Image_Editor_Imagick
imagick_module_version: 1687
imagemagick_version: ImageMagick 6.9.7-4 Q16 x86_64 20170114 http://www.imagemagick.org
imagick_version: 3.7.0
file_uploads: File uploads is turned off
post_max_size: 3000M
upload_max_filesize: 3000M
max_effective_size: 3 GB
max_file_uploads: 20
imagick_limits: 
	imagick::RESOURCETYPE_AREA: 122 MB
	imagick::RESOURCETYPE_DISK: 1073741824
	imagick::RESOURCETYPE_FILE: 6144
	imagick::RESOURCETYPE_MAP: 512 MB
	imagick::RESOURCETYPE_MEMORY: 256 MB
	imagick::RESOURCETYPE_THREAD: 1
	imagick::RESOURCETYPE_TIME: 1.844674407371E+19
imagemagick_file_formats: 3FR, AAI, AI, ART, ARW, AVI, AVS, BGR, BGRA, BGRO, BIE, BMP, BMP2, BMP3, BRF, CAL, CALS, CANVAS, CAPTION, CIN, CIP, CLIP, CMYK, CMYKA, CR2, CRW, CUR, CUT, DATA, DCM, DCR, DCX, DDS, DFONT, DJVU, DNG, DOT, DPX, DXT1, DXT5, EPDF, EPI, EPS, EPS2, EPS3, EPSF, EPSI, EPT, EPT2, EPT3, ERF, EXR, FAX, FILE, FITS, FRACTAL, FTP, FTS, G3, G4, GIF, GIF87, GRADIENT, GRAY, GROUP4, GV, H, HALD, HDR, HISTOGRAM, HRZ, HTM, HTML, HTTP, HTTPS, ICB, ICO, ICON, IIQ, INFO, INLINE, IPL, ISOBRL, ISOBRL6, JBG, JBIG, JNG, JNX, JPE, JPEG, JPG, JPS, JSON, K25, KDC, LABEL, M2V, M4V, MAC, MAGICK, MAP, MASK, MAT, MATTE, MEF, MIFF, MKV, MNG, MONO, MOV, MP4, MPC, MPEG, MPG, MRW, MSL, MSVG, MTV, MVG, NEF, NRW, NULL, ORF, OTB, OTF, PAL, PALM, PAM, PANGO, PATTERN, PBM, PCD, PCDS, PCL, PCT, PCX, PDB, PDF, PDFA, PEF, PES, PFA, PFB, PFM, PGM, PICON, PICT, PIX, PJPEG, PLASMA, PNG, PNG00, PNG24, PNG32, PNG48, PNG64, PNG8, PNM, PPM, PREVIEW, PS, PS2, PS3, PSB, PSD, PTIF, PWP, RADIAL-GRADIENT, RAF, RAS, RAW, RGB, RGBA, RGBO, RGF, RLA, RLE, RMF, RW2, SCR, SCT, SFW, SGI, SHTML, SIX, SIXEL, SPARSE-COLOR, SR2, SRF, STEGANO, SUN, SVG, SVGZ, TEXT, TGA, THUMBNAIL, TIFF, TIFF64, TILE, TIM, TTC, TTF, TXT, UBRL, UBRL6, UIL, UYVY, VDA, VICAR, VID, VIFF, VIPS, VST, WBMP, WMF, WMV, WMZ, WPG, X, X3F, XBM, XC, XCF, XPM, XPS, XV, XWD, YCbCr, YCbCrA, YUV
gd_version: 2.3.3
gd_formats: GIF, JPEG, PNG, WebP, BMP, XPM
ghostscript_version: 9.50

### wp-server ###

server_architecture: Linux 5.4.0-147-generic x86_64
httpd_software: Apache/2.4.41 (Ubuntu)
php_version: 7.4.33 64bit
php_sapi: apache2handler
max_input_variables: 1000
time_limit: 3600
memory_limit: 256M
max_input_time: 60
upload_max_filesize: 3000M
php_post_max_size: 3000M
curl_version: 7.68.0 OpenSSL/1.1.1j
suhosin: false
imagick_availability: true
pretty_permalinks: true
htaccess_extra_rules: true

### wp-database ###

extension: mysqli
server_version: 8.0.32-0ubuntu0.20.04.2
client_version: mysqlnd 7.4.33
max_allowed_packet: 67108864
max_connections: 151

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /var/www/html/wordpress/wp-content
WP_PLUGIN_DIR: /var/www/html/wordpress/wp-content/plugins
WP_MEMORY_LIMIT: 40M
WP_MAX_MEMORY_LIMIT: 256M
WP_DEBUG: true
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: true
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_ENVIRONMENT_TYPE: Indefinido
DB_CHARSET: utf8mb4
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable
0: Writable

### redux-framework ###

version: 4.4.0
installation: plugin
data directory: /var/www/html/wordpress/wp-content/plugins/redux-framework/redux-core/
browser: 
	Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/112.0
	Browser: Firefox
	Version: 112.0
	Platform: Linux

### redux-instance-eep-config ###

opt_name: eep-config
global_variable: eep_config
dev_mode: false
ajax_save: true
page_slug: eepconfig_panel
page_permissions: manage_woocommerce
menu_type: menu
page_parent: themes.php
compiler: true
output: true
output_tag: true
templates_path: undefined
extensions: 
	Accordion: 1.0.1
	Custom Fonts: 2.0.0
	Customizer: 4.0.0
	Datetime: 2.0.0
	Google Maps: 2.0.0
	Import Export: 4.0.0
	Js Button: 2.0.0
	Metaboxes: 4.0.0
	Multi Media: 4.3.15
	Options Object: 4.0.0
	Repeater: 4.3.7
	Search: 3.4.5
	Shortcodes: 4.3.5
	Social Profiles: 4.3.17
	Widget Areas: 1.0.0

`

## Steps to reproduce
1. Add two multi-media fields in the same section. 
2. Set both field with max upload files to value 1
3. Select a file on the second field
4. Try to select a file to the first field

## Expected Behavior
File should be normally selected.

## Actual Behavior
Error: Maximum upload limit of 1 reached/exceeded.

## Any Error Details (PHP/JavaScript)
If there are two multi-media fields, `redux.field_objects.multi_media.mainID` is always returning the id of the second field. This is why the error happens.

**Comment by kprovance** [comment]
Resolved in v4.4.0.4 beta, available in this repo. Thanks,
