### ISSUE TITLE
Error to change the image

### ISSUE THREAD

**Issue by platinumclinic** [reduxframework/redux-framework#3955]
Hello,

I purchased 'Thecappa' and making our homepage.
But there are some errors which are not able to know the reason.

1. HOME -> background images
2. COMMUNITY -> EVENTS -> images
3. COMMUNITY -> NEWS -> images
4. ABOUT -> 의료진 소개(first) -> image

1-3. sections have error to change the image. It just doesn't work even I selected the image from media library.
4. section had same error before but it worked at some moment. I don't know the reason how it worked.
I cleaned up plugin to fix this error and still same situation.

Please let me know how to fix this error or fix it.
Look forward hearing from you asap.
Thank you.

**Comment by kprovance** [comment]
Hi,

We don't support themes that use Redux. That is the responsibility of the theme author. You will have to contact them for theme support. If they determine there is an issue with Redux, they'll need to be the ones to file a report.

Good luck.

**Comment by platinumclinic** [comment]
aha. thank you for replying.
I'll try to contact them.
