### ISSUE TITLE
Header Question

### ISSUE THREAD

**Issue by BoldtMarcus** [reduxframework/redux-framework#3959]
Dear Team,

i have looked to get die pointed Overlay in the Header and Slider as shown in the Demo from the new LMS Template, but i have no Idea how to edit or set it up...

Please kan you help me in this case.

Friendly Regards

Marcus

**Comment by BoldtMarcus** [comment]
thanks for nothing

**Comment by kprovance** [comment]
The text that wasn't included when I closed the issue said that this is a theme issue. We do not support themes that use Redux. You'll need to contact the theme author for support. We also added text in the ticket window that stated as such. You should've read it before posting.

Good luck.
