### ISSUE TITLE
HOME THEME

### ISSUE THREAD

**Issue by YvetteTampa** [reduxframework/redux-framework#3964]
PLEASE HELP ME TO REMOVE THE "0 VIEWS" or edit the total of views
![Screenshot (152)](https://github.com/reduxframework/redux-framework/assets/141751988/7905096c-4143-4075-8a3c-433bda91de8c)

**Comment by kprovance** [comment]
As I explained in your last submission, we are Redux Framework, a tool theme developers use to create options for their themes. We do not support themes that use Redux. This is an issue you will have to take up with the theme's author. Please do not post theme issues here again. Thank you.
