### ISSUE TITLE
CSS/JS URL path is wrong

### ISSUE THREAD

**Issue by MorenoDD** [reduxframework/redux-framework#3966]
## Site Health Report
WordPress Version: 6.3.1
Server: nginx/1.16.0
PHP Version: 7.4.1

## Steps to reproduce

1. Download Redux framework
2. Follow this guide https://devs.redux.io/guides/advanced/embedding-redux.html to embed ReduxFramework 
3. Go to "Sample Options" 
4. Get the errors

## Expected Behavior
No Errors

## Actual Behavior
The assets file URL path is wrong.
<img width="1064" alt="Screenshot 2023-09-13 alle 10 17 41" src="https://github.com/reduxframework/redux-framework/assets/501663/3428ed31-8d4c-42f5-9822-048eeb8b3bf1">

**Comment by kprovance** [comment]
Well, chances are you're not embedded Redux correctly. You didn't provide any code, so I can't say. Again, PLEASE do not embed Redux. We generally will not support Redux issues (such as this one) if you do.
