### ISSUE TITLE
Repeater return array

### ISSUE THREAD

**Issue by MorenoDD** [reduxframework/redux-framework#3967]
## Site Health Report
WordPress Version: 6.3.1
Server: nginx/1.16.0
PHP Version: 7.4.1
ReduxFramework Installed as Plugin

## Steps to reproduce
Initialize a field like this:
<img width="528" alt="Screenshot 2023-09-13 alle 12 58 08" src="https://github.com/reduxframework/redux-framework/assets/501663/38ab70b4-ebd3-44c3-a400-2d9cb90be564">

and try to print the value with:

`
print_r($opt_name['color_palette']);
`

## Expected Behavior
Return an array well formatted like this:
`
Array
(
  Array(
    name => 'blue',
    color => '#1e73be'
  ),
  Array(
    name => 'red',
    color => '#dd3333'
  )
)
`

## Actual Behavior
Return a non-well formatted array
<img width="283" alt="Screenshot 2023-09-13 alle 12 57 25" src="https://github.com/reduxframework/redux-framework/assets/501663/2a3118a6-9282-4212-ae14-d0732c43dea6">

**Comment by kprovance** [comment]
That's expected behavior when `grouped_values` is set to true.
