### ISSUE TITLE
How to update ROOM HEADER SLIDER images? 

### ISSUE THREAD

**Issue by hardikJoshi123** [reduxframework/redux-framework#3971]
Hello. I am trying to update ROOM Slider images but we can't able to update from Elementor. Would you please let me know how can we update? 
Best,
Hardik

**Comment by hardikJoshi123** [comment]
My issue closed?

**Comment by kprovance** [comment]
We didn't author your theme. You're posting in the incorrect place. 

https://raw.githubusercontent.com/reduxframework/redux-framework/master/.github/ISSUE_TEMPLATE/user.md
