### ISSUE TITLE
File Permission Issues We were unable to modify required files. Please ensure that /home/fitmaple/moccotheme.com/www/wp-content//uploads/ has the proper read-write permissions, or modify your wp-config.php file to contain your FTP login credentials as outlined here..

### ISSUE THREAD

**Issue by David-Lyashuk** [reduxframework/redux-framework#3975]
Dear Redux Framework,
I've built a WP theme using your plugin and glad with the result.
Unfortunately, when I load the Theme on the real domain I got next issue.

File Permission Issues
We were unable to modify required files. Please ensure that /home/fitmaple/moccotheme.com/www/wp-content//uploads/ has the proper read-write permissions, or modify your wp-config.php file to contain your FTP login credentials as [outlined here](https://codex.wordpress.org/Editing_wp-config.php#WordPress_Upgrade_Constants)..

All Files permissions are set to needed values, but the issue still persist. 
How to fix this issue ?

Looking forward for reply

**Comment by kprovance** [comment]
update to the beta version of Redux from this repo.

**Comment by David-Lyashuk** [comment]
Thanks a lot
