### ISSUE TITLE
Multilingual social media profiles

### ISSUE THREAD

**Issue by gmt-it** [reduxframework/redux-framework#3977]
Hi. Since I don't know who to write to:

Is it possible to translate the social profile URLs via WPML? Many multilingual sites also have multilingual social media presences.

Best regards

Michael

**Comment by kprovance** [comment]
None that I am aware of. But I've never used WPML. If it's possible through a config file, that info would be here: https://wpml.org/documentation/support/language-configuration-files

Good luck.
