### ISSUE TITLE
Can't change the home screen logo and colours of the theme

### ISSUE THREAD

**Issue by Scaan7** [reduxframework/redux-framework#3981]
I am using a demo import and updated the Logo within customisation, however this has not changed on the home page. I am using Home 04. I also want to change the colour scheme, from the white background and black text to Black background, Purple Text. But can't find the option within customisation to make this happen.

Can you help?

**Comment by kprovance** [comment]
Please reread the posting guidelines. We do not support themes that use Redux., Contact the theme author.
