### ISSUE TITLE
4.4.10 Redux Upgrade - Fatal  error

### ISSUE THREAD

**Issue by kdesysadmin** [reduxframework/redux-framework#3985]
Following the update to 4.4.10 we received the following fatal error which rendered our Wordpress instance inaccessible.
Downgrading back was the only path forward to correct this.

An error of type E_ERROR was caused in line 868 of the file [docroot]/wp-content/plugins/redux-framework/redux-core/inc/classes/class-redux-filesystem.php. 

Error message: Uncaught TypeError: Return value of Redux_Filesystem::mkdir() must be of the type bool, null returned in [docroot]/wp-content/plugins/redux-framework/redux-core/inc/classes/class-redux-filesystem.php:868

Stack trace:
#0 [docroot]/wp-content/plugins/redux-framework/redux-core/inc/classes/class-redux-filesystem.php(367): Redux_Filesystem->mkdir()
#1 [docroot]/wp-content/plugins/redux-framework/redux-core/inc/classes/class-redux-filesystem.php(281): Redux_Filesystem->do_action()
#2 [docroot]/wp-content/plugins/redux-framework/redux-core/inc/extensions/custom_fonts/class-redux-extension-custom-fonts.php(89): Redux_Filesystem->execute()
#3 [docroot]/wp-content/plugins/redux-framework/redux-core/inc/classes/class-redux-api.php(253): Redux_Extension_Custom_Fonts->__construct()
#4 [docroot]/wp-content/plugins/redux-framework/redux-core/inc/classes/class-redux-api.php(16)

When seeking help with this issue, you may be asked for some of the following information:
WordPress version 6.4.2
Active theme: Jevelin (version 5.8)
Current plugin: Redux Framework (version 4.4.10)
PHP version 7.4.33

**Comment by kprovance** [comment]
Please try the beta posted in the repo. Also, please, in the future, follow the request information when submitting a support request. The information was posted for a reason, and it wasn't to be ignored. Thanks.
