### ISSUE TITLE
Warning count display Nan on left side for color menu

### ISSUE THREAD

**Issue by jitendrabanjara1991** [reduxframework/redux-framework#3988]
If we have two or more warnings related to color picker and we change color picker/click on default to anyone of them then count for menu is display NaN.

Here is the video - https://screenpal.com/watch/cZVZiaVJB1z

Are you a user reporting a bug with a theme or plugin?
======================================================
I am using Redux Framework WordPress plugin. Just activate plugin and checked color picker with diff type of hex code. You can check more details with this video - https://screenpal.com/watch/cZVZiaVJB1z

## Site Health Report
`
### wp-core ###

version: 6.4.2
site_language: en_US
user_language: en_US
timezone: +00:00
permalink: /%postname%/
https_status: false
multisite: false
user_registration: 1
blog_public: 1
default_comment_status: open
environment_type: production
user_count: 5
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: D:\wamp64\www\projects\redux-testing
wordpress_size: loading...
uploads_path: D:\wamp64\www\projects\redux-testing/wp-content/uploads
uploads_size: loading...
themes_path: D:\wamp64\www\projects\redux-testing/wp-content/themes
themes_size: loading...
plugins_path: D:\wamp64\www\projects\redux-testing/wp-content/plugins
plugins_size: loading...
database_size: loading...
total_size: loading...

### wp-active-theme ###

name: Twenty Twenty-Four (twentytwentyfour)
version: 1.0
author: the WordPress team
author_website: https://wordpress.org
parent_theme: none
theme_features: core-block-patterns, post-thumbnails, responsive-embeds, editor-styles, html5, automatic-feed-links, widgets-block-editor, block-templates
theme_path: D:\wamp64\www\projects\redux-testing/wp-content/themes/twentytwentyfour
auto_update: Disabled

### wp-themes-inactive (3) ###

BuddyBoss Theme: version: 2.5.10, author: BuddyBoss, Auto-updates disabled
Twenty Twenty-Three: version: 1.3, author: the WordPress team, Auto-updates disabled
Twenty Twenty-Two: version: 1.6, author: the WordPress team, Auto-updates disabled

### wp-mu-plugins (2) ###

BuddyBoss API Caching: version: 1.0.1, author: BuddyBoss
BuddyBoss Performance API: version: 1.0.0, author: BuddyBoss

### wp-plugins-active (1) ###

Redux Framework: version: 4.4.11, author: Team Redux, Auto-updates disabled

### wp-plugins-inactive (9) ###

Akismet Anti-spam: Spam Protection: version: 5.3, author: Automattic - Anti-spam Team (latest version: 5.3.1), Auto-updates disabled
BuddyBoss App: version: 1.8.52, author: BuddyBoss, Auto-updates disabled
BuddyBoss Platform: version: 2.5.20, author: BuddyBoss, Auto-updates disabled
BuddyBoss Platform Pro: version: 2.3.91, author: BuddyBoss (latest version: 2.4.50), Auto-updates disabled
Defender: version: 4.4.2, author: WPMU DEV, Auto-updates disabled
Defender Pro: version: 4.4.2, author: WPMU DEV, Auto-updates disabled
Hello Dolly: version: 1.7.2, author: Matt Mullenweg, Auto-updates disabled
Query Monitor: version: 3.15.0, author: John Blackbourn, Auto-updates disabled
WPMU DEV Dashboard: version: 4.11.23, author: WPMU DEV, Auto-updates disabled

### wp-media ###

image_editor: WP_Image_Editor_Imagick
imagick_module_version: 1808
imagemagick_version: ImageMagick 7.1.0-18 Q16 x64 2021-12-14 https://imagemagick.org
imagick_version: 3.7.0
file_uploads: 1
post_max_size: 12800000000000000M
upload_max_filesize: 12800000000000000M
max_effective_size: 8 EB
max_file_uploads: 20
imagick_limits: 
	imagick::RESOURCETYPE_AREA: 12 GB
	imagick::RESOURCETYPE_DISK: 9.2233720368548E+18
	imagick::RESOURCETYPE_FILE: 1536
	imagick::RESOURCETYPE_MAP: 12 GB
	imagick::RESOURCETYPE_MEMORY: 6 GB
	imagick::RESOURCETYPE_THREAD: 1
	imagick::RESOURCETYPE_TIME: 9.2233720368548E+18
imagemagick_file_formats: 3FR, 3G2, 3GP, AAI, AI, APNG, ART, ARW, ASHLAR, AVI, AVIF, AVS, BGR, BGRA, BGRO, BIE, BMP, BMP2, BMP3, BRF, CAL, CALS, CANVAS, CAPTION, CIN, CIP, CLIP, CLIPBOARD, CMYK, CMYKA, CR2, CR3, CRW, CUBE, CUR, CUT, DATA, DCM, DCR, DCRAW, DCX, DDS, DFONT, DJVU, DNG, DOT, DPS, DPX, DXT1, DXT5, EMF, EPDF, EPI, EPS, EPS2, EPS3, EPSF, EPSI, EPT, EPT2, EPT3, ERF, EXR, FARBFELD, FAX, FF, FILE, FITS, FL32, FLIF, FLV, FPX, FRACTAL, FTP, FTS, G3, G4, GIF, GIF87, GRADIENT, GRAY, GRAYA, GROUP4, GV, HALD, HDR, HEIC, HEIF, HISTOGRAM, HRZ, HTM, HTML, HTTP, HTTPS, ICB, ICO, ICON, IIQ, INFO, INLINE, IPL, ISOBRL, ISOBRL6, J2C, J2K, JBG, JBIG, JNG, JNX, JP2, JPC, JPE, JPEG, JPG, JPM, JPS, JPT, JSON, JXL, K25, KDC, KERNEL, LABEL, M2V, M4V, MAC, MAP, MASK, MAT, MATTE, MEF, MIFF, MKV, MNG, MONO, MOV, MP4, MPC, MPEG, MPG, MRW, MSL, MSVG, MTV, MVG, NEF, NRW, NULL, ORA, ORF, OTB, OTF, PAL, PALM, PAM, PANGO, PATTERN, PBM, PCD, PCDS, PCL, PCT, PCX, PDB, PDF, PDFA, PEF, PES, PFA, PFB, PFM, PGM, PGX, PHM, PICON, PICT, PIX, PJPEG, PLASMA, PNG, PNG00, PNG24, PNG32, PNG48, PNG64, PNG8, PNM, POCKETMOD, PPM, PS, PS2, PS3, PSB, PSD, PTIF, PWP, RADIAL-GRADIENT, RAF, RAS, RAW, RGB, RGB565, RGBA, RGBO, RGF, RLA, RLE, RMF, RSVG, RW2, SCR, SCREENSHOT, SCT, SFW, SGI, SHTML, SIX, SIXEL, SPARSE-COLOR, SR2, SRF, STEGANO, SUN, SVG, SVGZ, TEXT, TGA, THUMBNAIL, TIFF, TIFF64, TILE, TIM, TM2, TTC, TTF, TXT, UBRL, UBRL6, UIL, UYVY, VDA, VICAR, VID, VIFF, VIPS, VST, WBMP, WEBM, WEBP, WMF, WMV, WPG, X3F, XBM, XC, XCF, XPM, XPS, XV, YAML, YCbCr, YCbCrA, YUV
gd_version: bundled (2.1.0 compatible)
gd_formats: GIF, JPEG, PNG, WebP, BMP, XPM
ghostscript_version: not available

### wp-server ###

server_architecture: Windows NT 10.0 AMD64
httpd_software: Apache/2.4.46 (Win64) PHP/8.0.26 mod_fcgid/2.3.10-dev
php_version: 8.0.26 64bit
php_sapi: apache2handler
max_input_variables: 2500
time_limit: 1200000000000000000
memory_limit: 12800000000000000M
max_input_time: 600000000
upload_max_filesize: 12800000000000000M
php_post_max_size: 12800000000000000M
curl_version: 7.76.1 OpenSSL/1.1.1g
suhosin: false
imagick_availability: true
pretty_permalinks: true
htaccess_extra_rules: false
current: 2024-01-24T07:39:05+00:00
utc-time: Wednesday, 24-Jan-24 07:39:05 UTC
server-time: 2024-01-24T07:39:02+00:00

### wp-database ###

extension: mysqli
server_version: 5.7.31-log
client_version: mysqlnd 8.0.26
max_allowed_packet: 104857600
max_connections: 151

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: D:\wamp64\www\projects\redux-testing/wp-content
WP_PLUGIN_DIR: D:\wamp64\www\projects\redux-testing/wp-content/plugins
WP_MEMORY_LIMIT: 40M
WP_MAX_MEMORY_LIMIT: 12800000000000000M
WP_DEBUG: true
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: true
SCRIPT_DEBUG: true
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_ENVIRONMENT_TYPE: Undefined
WP_DEVELOPMENT_MODE: undefined
DB_CHARSET: utf8mb4
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable
mu-plugins: writable
0: Writable

### redux-framework ###

version: 4.4.11
installation: plugin
data directory: D:/wamp64/www/projects/redux-testing/wp-content/plugins/redux-framework/redux-core/
browser: 
	Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
	Browser: Chrome
	Version: 120.0.0.0
	Platform: Windows

### redux-instance-redux_demo ###

opt_name: redux_demo
global_variable: redux_demo
dev_mode: true
ajax_save: true
page_slug: redux_demo
page_permissions: manage_options
menu_type: menu
page_parent: themes.php
compiler: true
output: true
output_tag: true
templates_path: undefined
extensions: 
	Accordion: 4.3.16
	Custom Fonts: 4.4.2
	Customizer: 4.4.11
	Datetime: 4.3.15
	Google Maps: 4.4.0
	Icon Select: 4.4.2
	Import Export: 4.0.0
	Js Button: 4.3.16
	Metaboxes: 4.2.0
	Multi Media: 4.4.1
	Options Object: 4.0.0
	Repeater: 4.3.13
	Search: 3.4.5
	Shortcodes: 4.3.6
	Social Profiles: 4.3.17
	Tabbed: 4.4.8
	Taxonomy: 4.4.6
	Users: 4.4.1
	Widget Areas: 4.3.20

`

## Steps to reproduce
- Install Redux Framework from WP
- Sample Options - Color Selection - Color - Change color to like - #c1c1c1g ( Wrong hex code to generate warnings ). Make sure we required two or more warnings
- Click on save changes - You can see 2 count is display on left side Color menu.
- Now click on any one of color picker and click on default or change color using color picker
- See error - Color menu count is NaN

## Expected Behavior
- Color menu count should be updated properly

## Actual Behavior
- Color menu count display NaN instead of number

## Any Error Details (PHP/JavaScript)
Nothing

**Comment by kprovance** [comment]
This issue is fixed in the current beta and will be available in the next wp.org release. Thanks!
