### ISSUE TITLE
Attribute not working with text field

### ISSUE THREAD

**Issue by j7-dev** [reduxframework/redux-framework#3989]
## Issue

`attribute` not working with `text` field.

<br /><br /><br />

## Reproduce the issue

I followed the document [here](https://devs.redux.io/configuration/fields/attributes.html)

```php
Redux::set_field( 'redux_demo', 'SECTION_ID', array(
    'id'   => 'field_id',
    'type' => 'text',
    'attributes'       => array(
        'type'         => 'password',
        'readonly'     => 'readonly',
        'autocomplete' => 'off',
        'data-json' => array(
            'example' => 'json'
        )
    )
) );
```

But It seems not working 🔽

![image](https://github.com/reduxframework/redux-framework/assets/9213776/a2fd70eb-9b23-4443-8acf-f713378f018c)

<br /><br /><br />

## Expected result

 - override the attributes of the input field

<br /><br /><br />

## Trace the source code

I trace code here [`redux-framework/redux-core/inc/fields/text/class-redux-text.php`](https://github.com/reduxframework/redux-framework/blob/master/redux-core/inc/fields/text/class-redux-text.php)

I can't find any keyword with `attributes` in `class-redux-text.php`, it seems `attributes` key do NOTHING in `class-redux-text.php`

**Comment by kprovance** [comment]
The `attributes` feature was removed last year as it was designed for something we never used. You'll have to use the field arguments instead. I'll update the docs to get rid of all that old data.

**Comment by kprovance** [comment]
Basically. Redux has a `password` field, but it doesn't have `min` or `max.` You could easily take that field and use it to make a custom extension. Be sure to change the class name so it doesn't conflict.

**Comment by kprovance** [comment]
Alternatively, if you're proficent in in it, you could use some custom JavaScript to add attributes to existing Redix fields. I've seen it done many times.
