### ISSUE TITLE
Backend is buggy- No Field ID is set

### ISSUE THREAD

**Issue by gchristo94** [reduxframework/redux-framework#3993]
Plugins update but an error is returned in the dashboard. 
Update failed: No field ID is set.{"success":true,"data":{"update":"plugin","slug":"disable-gutenberg","oldVersion":"Version 3.1","newVersion":"Version 3.1.1","plugin":"disable-gutenberg\/disable-gutenberg.php","pluginName":"Disable Gutenberg"}}

Each page in the dashboard has a blank space at the top of the page. 
![scrnli_3_4_2024_3-28-16 PM](https://github.com/reduxframework/redux-framework/assets/162213835/eeed4a54-bdae-47ce-81dc-c10e575622ac)

Site health report:

[BPBsitehealthinfo.txt](https://github.com/reduxframework/redux-framework/files/14487588/BPBsitehealthinfo.txt)

I cannot upload images. I cannot use the plugin search.

**Comment by kprovance** [comment]
I need admin and FTP access to this site so I can see the issue for myself. Please email this information to kevin.provance@gmail.com and I'll look into it this evening.

**Comment by gchristo94** [comment]
Just sent credentials. Thank you!

**Comment by kprovance** [comment]
I tried to login and got this    From: gchristo94Sent: Monday, March 4, 2024 5:04 PMTo: reduxframework/redux-frameworkCc: Kevin Provance; CommentSubject: Re: [reduxframework/redux-framework] Backend is buggy- No Field ID is set (Issue #3993) Just sent credentials. Thank you!—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

**Comment by gchristo94** [comment]
What??
Logged in where?

**Comment by gchristo94** [comment]
That was FTP access that you asked for.

**Comment by kprovance** [comment]
And admin access to the WordPress site, so I can actually see the issues in real time. The FTP is so I can add debug code to Redux to see where it's failing.

**Comment by gchristo94** [comment]
I tested and sent a screenshot of the FTP setup. It worked for me.

**Comment by kprovance** [comment]
Issue resolved. The copy of Redux on your site is good to go. You won't need to update to the beta version for the fix. Thanks for the assist!

**Comment by gchristo94** [comment]
Thank you. I appreciate you getting to this quickly.

**Comment by offspring42** [comment]
> Issue resolved. The copy of Redux on your site is good to go. You won't need to update to the beta version for the fix. Thanks for the assist!

Hello, I just wanted to let you know that Redux 4.4.13 produced similar problems on my WP-Installation (login was not possible anymore and I had to remove the Wordfence plugin, free space in the upper admin window etc.) . Rolling back to Version 4.4.11 fixed the problems.

The support from my hoster sent me the following error.log (anonymized):

sample.com [Mon Mar 04 06:11:53 2024] [error]: Got error 'PHP message: PHP Warning: Trying to access array offset on value of type null in /clients/client123456_789s/pages/wordpress/wp-content/plugins/redux-framework/redux-core/inc/classes/class-redux-options-constructor.php on line 381; PHP message: PHP Warning: Trying to access array offset on value of type null in /clients/client123456_789s/pages/wordpress/wp-content/plugins/redux-framework/redux-core/inc/classes/class-redux-options-constructor.php on line 381; PHP message: PHP Warning: Trying to access array offset on value of type null in /clients/client123456_789s/pages/wordpress/wp-content/plugins/redux-framework/redux-core/inc/classes/class-redux-options-constructor.php on line 383; PHP message: PHP Warning: Trying to access array offset on value of type null in /clients/client123456_789s/pages/wordpress/wp-content/plugins/redux-framework/redux-core/inc/classes/class-redux-options-constructor.php on line 383', referer https://sample.com/wp-admin/update-core.php

Hope that info helps.
