### ISSUE TITLE
Theme options resets and show default values after avg (1min) of editing in wp customizer 

### ISSUE THREAD

**Issue by melsaka** [reduxframework/redux-framework#3999]
## Site Health Report
`
### wp-core ###

version: 6.5.2
site_language: en_US
user_language: en_US
timezone: +00:00
permalink: /%postname%/
https_status: false
multisite: false
user_registration: 0
blog_public: 1
default_comment_status: open
environment_type: local
user_count: 1
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: C:\Users\kerbe\Local Sites\blog\app\public
wordpress_size: 54.67 MB (57328749 bytes)
uploads_path: C:\Users\kerbe\Local Sites\blog\app\public/wp-content/uploads
uploads_size: 170.69 KB (174787 bytes)
themes_path: C:\Users\kerbe\Local Sites\blog\app\public/wp-content/themes
themes_size: 30.05 MB (31507272 bytes)
plugins_path: C:\Users\kerbe\Local Sites\blog\app\public/wp-content/plugins
plugins_size: 9.74 MB (10210816 bytes)
database_size: 2.84 MB (2981888 bytes)
total_size: 97.47 MB (102203512 bytes)

### wp-active-theme ###

name: Shams (shams)
version: 1.0.0
author: moelsaka
author_website: https://themeforest.net/user/moelsaka
parent_theme: none
theme_features: widgets-block-editor, title-tag, post-thumbnails, automatic-feed-links, html5, wp-block-styles, align-wide, editor-styles, menus
theme_path: C:\Users\kerbe\Local Sites\blog\app\public/wp-content/themes/shams
auto_update: Disabled

### wp-themes-inactive (1) ###

Twenty Twenty-Four: version: 1.1, author: the WordPress team, Auto-updates disabled

### wp-plugins-active (1) ###

Redux Framework: version: 4.4.15.2, author: Team Redux, Auto-updates disabled

### wp-media ###

image_editor: WP_Image_Editor_Imagick
imagick_module_version: 1808
imagemagick_version: ImageMagick 7.1.0-18 Q16 x64 2021-12-14 https://imagemagick.org
imagick_version: 3.7.0
file_uploads: 1
post_max_size: 1000M
upload_max_filesize: 300M
max_effective_size: 300 MB
max_file_uploads: 20
imagick_limits: 
	imagick::RESOURCETYPE_AREA: 14 GB
	imagick::RESOURCETYPE_DISK: 9.2233720368548E+18
	imagick::RESOURCETYPE_FILE: 1536
	imagick::RESOURCETYPE_MAP: 14 GB
	imagick::RESOURCETYPE_MEMORY: 7 GB
	imagick::RESOURCETYPE_THREAD: 1
	imagick::RESOURCETYPE_TIME: 9.2233720368548E+18
imagemagick_file_formats: 3FR, 3G2, 3GP, AAI, AI, APNG, ART, ARW, ASHLAR, AVI, AVIF, AVS, BGR, BGRA, BGRO, BIE, BMP, BMP2, BMP3, BRF, CAL, CALS, CANVAS, CAPTION, CIN, CIP, CLIP, CLIPBOARD, CMYK, CMYKA, CR2, CR3, CRW, CUBE, CUR, CUT, DATA, DCM, DCR, DCRAW, DCX, DDS, DFONT, DJVU, DNG, DOT, DPS, DPX, DXT1, DXT5, EMF, EPDF, EPI, EPS, EPS2, EPS3, EPSF, EPSI, EPT, EPT2, EPT3, ERF, EXR, FARBFELD, FAX, FF, FILE, FITS, FL32, FLIF, FLV, FPX, FRACTAL, FTP, FTS, G3, G4, GIF, GIF87, GRADIENT, GRAY, GRAYA, GROUP4, GV, HALD, HDR, HEIC, HEIF, HISTOGRAM, HRZ, HTM, HTML, HTTP, HTTPS, ICB, ICO, ICON, IIQ, INFO, INLINE, IPL, ISOBRL, ISOBRL6, J2C, J2K, JBG, JBIG, JNG, JNX, JP2, JPC, JPE, JPEG, JPG, JPM, JPS, JPT, JSON, JXL, K25, KDC, KERNEL, LABEL, M2V, M4V, MAC, MAP, MASK, MAT, MATTE, MEF, MIFF, MKV, MNG, MONO, MOV, MP4, MPC, MPEG, MPG, MRW, MSL, MSVG, MTV, MVG, NEF, NRW, NULL, ORA, ORF, OTB, OTF, PAL, PALM, PAM, PANGO, PATTERN, PBM, PCD, PCDS, PCL, PCT, PCX, PDB, PDF, PDFA, PEF, PES, PFA, PFB, PFM, PGM, PGX, PHM, PICON, PICT, PIX, PJPEG, PLASMA, PNG, PNG00, PNG24, PNG32, PNG48, PNG64, PNG8, PNM, POCKETMOD, PPM, PS, PS2, PS3, PSB, PSD, PTIF, PWP, RADIAL-GRADIENT, RAF, RAS, RAW, RGB, RGB565, RGBA, RGBO, RGF, RLA, RLE, RMF, RSVG, RW2, SCR, SCREENSHOT, SCT, SFW, SGI, SHTML, SIX, SIXEL, SPARSE-COLOR, SR2, SRF, STEGANO, SUN, SVG, SVGZ, TEXT, TGA, THUMBNAIL, TIFF, TIFF64, TILE, TIM, TM2, TTC, TTF, TXT, UBRL, UBRL6, UIL, UYVY, VDA, VICAR, VID, VIFF, VIPS, VST, WBMP, WEBM, WEBP, WMF, WMV, WPG, X3F, XBM, XC, XCF, XPM, XPS, XV, YAML, YCbCr, YCbCrA, YUV
gd_version: bundled (2.1.0 compatible)
gd_formats: GIF, JPEG, PNG, WebP, BMP, AVIF, XPM
ghostscript_version: not available

### wp-server ###

server_architecture: Windows NT 10.0 AMD64
httpd_software: nginx/1.16.0
php_version: 8.1.23 64bit
php_sapi: cgi-fcgi
max_input_variables: 4000
time_limit: 1200
memory_limit: 256M
max_input_time: 600
upload_max_filesize: 300M
php_post_max_size: 1000M
curl_version: 7.77.0 OpenSSL/1.1.1t
suhosin: false
imagick_availability: true
pretty_permalinks: true
htaccess_extra_rules: false
current: 2024-04-23T04:45:29+00:00
utc-time: Tuesday, 23-Apr-24 04:45:29 UTC
server-time: 2024-04-23T04:45:28+00:00

### wp-database ###

extension: mysqli
server_version: 8.0.16
client_version: mysqlnd 8.1.23
max_allowed_packet: 16777216
max_connections: 151

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: C:\Users\kerbe\Local Sites\blog\app\public/wp-content
WP_PLUGIN_DIR: C:\Users\kerbe\Local Sites\blog\app\public/wp-content/plugins
WP_MEMORY_LIMIT: 256M
WP_MAX_MEMORY_LIMIT: 256M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_ENVIRONMENT_TYPE: local
WP_DEVELOPMENT_MODE: undefined
DB_CHARSET: utf8
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable
0: Writable

### redux-framework ###

version: 4.4.15.2
installation: plugin
data directory: C:/Users/kerbe/Local Sites/blog/app/public/wp-content/plugins/redux-framework/redux-core/
browser: 
	Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36
	Browser: Chrome
	Version: 123.0.0.0
	Platform: Windows

### redux-instance-shams_opt ###

opt_name: shams_opt
global_variable: shams_opt
dev_mode: true
ajax_save: true
page_slug: shams-settings
page_permissions: manage_options
menu_type: menu
page_parent: themes.php
compiler: true
output: true
output_tag: true
templates_path: undefined
extensions: 
	Accordion: 4.3.16
	Color Scheme: 4.4.10
	Custom Fonts: 4.4.2
	Customizer: 4.4.11
	Datetime: 4.3.15
	Google Maps: 4.4.0
	Icon Select: 4.4.2
	Import Export: 4.0.0
	Js Button: 4.3.16
	Metaboxes: 4.2.0
	Multi Media: 4.4.1
	Options Object: 4.0.0
	Repeater: 4.3.13
	Search: 3.4.5
	Shortcodes: 4.3.6
	Social Profiles: 4.3.17
	Tabbed: 4.4.8
	Taxonomy: 4.4.6
	Users: 4.4.1
	Widget Areas: 4.3.20

`

## Steps to reproduce
Changing colors and settings in customizer without publishing for about (1 min) in average.

## Expected Behavior
The customizer resets all values to default values but if you publish it will update the theme options to the changed values.  

## Actual Behavior
I guess that the problem is related to the global variable which in my case $shams_opt because this problem is not happening when i use get_theme_mod('shams_opt') but this work around causes to me other problems that i need to think about.

## Any Error Details (PHP/JavaScript)
I also Noticed that php log this error whenever this happens:
[23-Apr-2024 03:44:35 UTC] PHP Warning:  Attempt to read property "title" on null in C:\Users\kerbe\Local Sites\blog\app\public\wp-includes\class-wp-customize-widgets.php on line 905

https://github.com/reduxframework/redux-framework/assets/16939366/7aab6258-edaf-4008-b29f-1687c2f694d0

**Comment by kprovance** [comment]
I'm not understanding the problem (I have to mention the actual and expected behavior fields are not properly filled out, making my job a little tougher here). I watched the video of you changing options. And? Does it have to do with the preview? Are you saving the the settings reverting to default?

I tried this with the default Twenty-Twenty-One theme in demo mode and can't reproduce it. But again, I don't understand the problem.

Please disable your theme and all plugins but Redux. Activate the Twenty-Twenty-One theme (later themes don't use the customizer) and then activate the demo mode. Does this problem still exist?

**Comment by kprovance** [comment]
Also, those PHP errors are WordPress issues based on the PHP file. Is there stack trace data available to see the error's origin?

**Comment by melsaka** [comment]
> I'm not understanding the problem (I have to mention the actual and expected behavior fields are not properly filled out, making my job a little tougher here). I watched the video of you changing options. And? Does it have to do with the preview? Are you saving the the settings reverting to default?
> 
> I tried this with the default Twenty-Twenty-One theme in demo mode and can't reproduce it. But again, I don't understand the problem.
> 
> Please disable your theme and all plugins but Redux. Activate the Twenty-Twenty-One theme (later themes don't use the customizer) and then activate the demo mode. Does this problem still exist?

I installed Twenty-Twenty-One, then activated Redux plugin only, then added the code blew to the end of the function.php file, then opened up the customizer and changed colors and buttons values for about 1min and a half then checked the dynamic added style tag added by redux with id="shams_opt-dynamic-css" i noticed that css variables added by redux has the default values for example --link-effect-color: #ffe66b; and the value in the customizer is #000000.

------- Here is the code ------- 

$args = [
	// This is where your data is stored in the database and also becomes your global variable name.
	'opt_name'             => 'shams_opt',
	// Name that appears at the top of your panel
	'display_name'         => '<img src="/wp-content/themes/shams/assets//images/shams-white.svg" style="margin-right: 5px; height: 30px;">',
	// Version that appears at the top of your panel
	'display_version'      => '1.0',
	//Specify if the admin menu should appear or not. Options: menu or submenu (Under appearance only)
	'menu_type'            => 'menu',
	// Show the sections below the admin menu item or not
	'allow_sub_menu'       => true,
	// Menu Title
	'menu_title'           => esc_html__( 'Shams Settings', 'shams' ),
	// Page Title
	'page_title'           => esc_html__( 'Shams Theme Settings', 'shams' ),
	// Choose an priority for the admin bar menu
	'admin_bar_priority'   => 42,
	// If dev_mode is enabled, will notify developer of updated versions available in the GitHub Repo
	'customizer'           => true,
	// Show the panel pages on the admin bar
	'admin_bar'            => true,
	// Choose an icon for the admin bar menu
	'admin_bar_icon'       => 'dashicons-admin-generic',
	// What to print by the field's title if the value shown is default. Suggested: *
	'default_mark'         => '',
	// If true, shows the default value next to each field that is not the default value.
	'default_show'         => false,
	// Show the time the page took to load, etc
	'dev_mode'             => true,
	// Force your panel to always open to a specific tab (by id)
	'last_tab'             => '',
	// Specify a custom URL to an icon
	'menu_icon'            => '',
	// Order where the menu appears in the admin area. If there is any conflict, something will not show. Warning.
	'page_priority'        => 2,
	// For a full list of options, visit: http://codex.wordpress.org/Function_Reference/add_submenu_page#Parameters
	'page_parent'          => 'themes.php',
	// Permissions needed to access the options panel.
	'page_permissions'     => 'manage_options',
	// Icon displayed in the admin panel next to your menu_title
	'page_icon'            => 'icon-themes',
	// Page slug used to denote the panel
	'page_slug'            => 'shams-settings',
	// On load save the defaults to DB before user clicks save or not
	'save_defaults'        => true,
	// Shows the Import/Export panel when not used as a field.
	'show_import_export'   => true,
	// The time transients will expire when the 'database' arg is set.
	'transient_time'            => 60 * MINUTE_IN_SECONDS,
	// Global shut-off for dynamic CSS output by the framework. Will also disable google fonts output.
	'output'                    => true,

	// Allows dynamic CSS to be generated for customizer and google fonts,
	// but stops the dynamic CSS from going to the page head.
	'output_tag'                => true,
	// Disable the footer credit of Redux. Please leave if you can help it.
	'footer_credit'             => '',
];

Redux::set_args('shams_opt', $args);

Redux::set_section( 'shams_opt', [
	'title' => esc_html__( 'Theme Colors', 'shams' ),
	'id'    => 'main_color',
	'icon'  => 'el el-adjust ',
	'fields' 	=> [
		[
			'id'		=> 'link_hover_effect_color',
			'type' 		=> 'color',
			'transparent' => false,
			'title' 	=> esc_html__('Link Hover Effect', 'shams'),
			'default' 	=> '#ffe66b',
			'validate' 	=> 'color',
			'output'    => ['--link-effect-color' => ':root'],
		],
		[
			'id'		=> 'social_icons_hover_color',
			'type' 		=> 'color',
			'transparent' => false,
			'title' 	=> esc_html__('Social Icons On Hover', 'shams'),
			'default' 	=> '#ffffff',
			'validate' 	=> 'color',
			'output'    => ['--social-icons-color' => ':root'],
		],
		[
			'id'		=> 'social_icons_hover_bg_color',
			'type' 		=> 'color',
			'transparent' => false,
			'title' 	=> esc_html__('Social Icons Background On Hover', 'shams'),
			'default' 	=> '#000000',
			'validate' 	=> 'color',
			'output'    => ['--social-icons-bg-color' => ':root'],
		],

		[
			'id' 		=> 'header_section_start',
			'type' 		=> 'section',
			'title' 	=> esc_html__('Header', 'shams'),
			'indent' 	=> true,
		],
		[
			'id'		=> 'header_bg_color',
			'type' 		=> 'color',
			'transparent' => true,
			'title' 	=> esc_html__('Background', 'shams'),
			'default' 	=> 'transparent',
			'validate' 	=> 'color',
			'output'    => ['--header-bg-color' => ':root'],
		],
		[
			'id'		=> 'header_text_color',
			'type' 		=> 'color',
			'transparent' => false,
			'title' 	=> esc_html__('Text', 'shams'),
			'default' 	=> '#000000',
			'validate' 	=> 'color',
			'output'    => ['--header-text-color' => ':root'],
		],
		[
			'id'		=> 'header_subtext_color',
			'type' 		=> 'color',
			'transparent' => false,
			'title' 	=> esc_html__('Subtext', 'shams'),
			'default' 	=> '#575757',
			'validate' 	=> 'color',
			'output'    => ['--header-subtext-color' => ':root'],
		],
		[
			'id'		=> 'header_dropwdown_hover_bg_color',
			'type' 		=> 'color',
			'transparent' => false,
			'title' 	=> esc_html__('Dropdown Background On Hover', 'shams'),
			'default' 	=> '#ffe66b',
			'validate' 	=> 'color',
			'output'    => ['--header-dropwdown-hover-bg-color' => ':root'],
		],
		[
			'id'		=> 'header_dropwdown_hover_text_color',
			'type' 		=> 'color',
			'transparent' => false,
			'title' 	=> esc_html__('Dropdown Text On Hover', 'shams'),
			'default' 	=> '#000000',
			'validate' 	=> 'color',
			'output'    => ['--header-dropwdown-hover-text-color' => ':root'],
		],
		[
			'id' 		=> 'header_section_end',
			'type' 		=> 'section',
			'indent' 	=> false,
		],[
			'id' 		=> 'header_nav_section_start',
			'type' 		=> 'section',
			'title' 	=> esc_html__('Header Navigation', 'shams'),
			'indent' 	=> true,
		],
		[
			'id'		=> 'header_nav_bg_color',
			'type' 		=> 'color',
			'transparent' => false,
			'title' 	=> esc_html__('Background', 'shams'),
			'default' 	=> '#ffffff',
			'validate' 	=> 'color',
			'output'    => ['--header-nav-bg-color' => ':root'],
		],
		[
			'id'		=> 'header_nav_text_color',
			'type' 		=> 'color',
			'transparent' => false,
			'title' 	=> esc_html__('Text', 'shams'),
			'default' 	=> '#000000',
			'validate' 	=> 'color',
			'output'    => ['--header-nav-text-color' => ':root'],
		],

		[
			'id' 		=> 'header_nav_section_end',
			'type' 		=> 'section',
			'indent' 	=> false,
		],
		[
			'id' 		=> 'body_section_start',
			'type' 		=> 'section',
			'title' 	=> esc_html__('Page Body', 'shams'),
			'indent' 	=> true,
		],
		[
			'id'		=> 'body_text_color',
			'type' 		=> 'color',
			'transparent' => false,
			'title' 	=> esc_html__('Text', 'shams'),
			'default' 	=> '#000000',
			'validate' 	=> 'color',
			'output'    => ['--body-text-color' => ':root'],
		],
		[
			'id'		=> 'body_subtext_color',
			'type' 		=> 'color',
			'transparent' => false,
			'title' 	=> esc_html__('Subtext', 'shams'),
			'default' 	=> '#575757',
			'validate' 	=> 'color',
			'output'    => ['--body-subtext-color' => ':root'],
		],
		[
			'id' 		=> 'body_bg_color_extend',
			'type' 		=> 'button_set',
			'title' 	=> __('Extend Background Gradient Colors', 'shams'),
			'options' 	=> [
				'enable' 		=> esc_html__( 'Enable', 'shams' ),
				'disable' 		=> esc_html__( 'Disable', 'shams' ),
			], 
			'default' 	=> 'disable',
		],
		[
			'id' 		=> 'body_bg_color_direction',
			'type'     => 'select',
			'title' 	=> __('Gradient Direction', 'shams'),
			'options' 	=> [
				'to right top' 			=> esc_html__( 'To Right Top', 'shams' ),
				'to right' 				=> esc_html__( 'To Right', 'shams' ),
				'to right bottom' 		=> esc_html__( 'To Right Bottom', 'shams' ),
				'to bottom' 			=> esc_html__( 'To Bottom', 'shams' ),
				'to left bottom' 		=> esc_html__( 'To Left Bottom', 'shams' ),
				'to left' 				=> esc_html__( 'To Left', 'shams' ),
				'to left top' 			=> esc_html__( 'To Left Top', 'shams' ),
				'to top' 				=> esc_html__( 'To Top', 'shams' ),
			], 
			'default'  => 'to bottom',
		],
		[
			'id'		=> 'body_bg_color_1',
			'type' 		=> 'color',
			'transparent' => false,
			'title' 	=> esc_html__('Gradient Color 1', 'shams'),
			'default' 	=> '#f9f9f9',
			'validate' 	=> 'color',
			'output'    => ['--body-bg-color-1' => ':root'],
		],
		[
			'id'		=> 'body_bg_color_2',
			'type' 		=> 'color',
			'transparent' => false,
			'title' 	=> esc_html__('Gradient Color 2', 'shams'),
			'default' 	=> '#f9f9f9',
			'validate' 	=> 'color',
			'output'    => ['--body-bg-color-2' => ':root'],
		],
		[
			'id'		=> 'body_bg_color_3',
			'type' 		=> 'color',
			'transparent' => false,
			'title' 	=> esc_html__('Gradient Color 3', 'shams'),
			'default' 	=> '#f9f9f9',
			'validate' 	=> 'color',
			'output'    => ['--body-bg-color-3' => ':root'],
			'required' 	=> [
				['body_bg_color_extend','=','enable'],
			],
		],
		[
			'id'		=> 'body_bg_color_4',
			'type' 		=> 'color',
			'transparent' => false,
			'title' 	=> esc_html__('Gradient Color 4', 'shams'),
			'default' 	=> '#f9f9f9',
			'validate' 	=> 'color',
			'output'    => ['--body-bg-color-4' => ':root'],
			'required' 	=> [
				['body_bg_color_extend','=','enable'],
			],
		],
		[
			'id'		=> 'body_bg_color_5',
			'type' 		=> 'color',
			'transparent' => false,
			'title' 	=> esc_html__('Gradient Color 5', 'shams'),
			'default' 	=> '#f9f9f9',
			'validate' 	=> 'color',
			'output'    => ['--body-bg-color-5' => ':root'],
			'required' 	=> [
				['body_bg_color_extend','=','enable'],
			],
		],
		[
			'id' 		=> 'body_section_end',
			'type' 		=> 'section',
			'indent' 	=> false,
		],

		[
			'id' 		=> 'footer_section_start',
			'type' 		=> 'section',
			'title' 	=> esc_html__('Footer', 'shams'),
			'indent' 	=> true,
		],
		[
			'id'		=> 'footer_bg_color',
			'type' 		=> 'color',
			'transparent' => true,
			'title' 	=> esc_html__('Background', 'shams'),
			'default' 	=> 'transparent',
			'validate' 	=> 'color',
			'output'    => ['--footer-bg-color' => ':root'],
		],
		[
			'id'		=> 'footer_text_color',
			'type' 		=> 'color',
			'transparent' => false,
			'title' 	=> esc_html__('Text', 'shams'),
			'default' 	=> '#000000',
			'validate' 	=> 'color',
			'output'    => ['--footer-text-color' => ':root'],
		],
		[
			'id'		=> 'footer_subtext_color',
			'type' 		=> 'color',
			'transparent' => false,
			'title' 	=> esc_html__('Subtext', 'shams'),
			'default' 	=> '#575757',
			'validate' 	=> 'color',
			'output'    => ['--footer-subtext-color' => ':root'],
		],
		[
			'id' 		=> 'footer_section_end',
			'type' 		=> 'section',
			'indent' 	=> false,
		],

		[
			'id' 		=> 'button_section_start',
			'type' 		=> 'section',
			'title' 	=> esc_html__('Buttons', 'shams'),
			'indent' 	=> true,
		],
		[
			'id'		=> 'button_bg_color',
			'type' 		=> 'color',
			'transparent' => false,
			'title' 	=> esc_html__('Background', 'shams'),
			'default' 	=> '#ffe66b',
			'validate' 	=> 'color',
			'output'    => ['--button-bg-color' => ':root'],
		],
		[
			'id'		=> 'button_text_color',
			'type' 		=> 'color',
			'transparent' => false,
			'title' 	=> esc_html__('Text', 'shams'),
			'default' 	=> '#000000',
			'validate' 	=> 'color',
			'output'    => ['--button-text-color' => ':root'],
		],
		[
			'id'		=> 'button_hover_bg_color',
			'type' 		=> 'color',
			'transparent' => false,
			'title' 	=> esc_html__('Background On Hover', 'shams'),
			'default' 	=> '#000000',
			'validate' 	=> 'color',
			'output'    => ['--button-hover-bg-color' => ':root'],
		],
		[
			'id'		=> 'button_hover_text_color',
			'type' 		=> 'color',
			'transparent' => false,
			'title' 	=> esc_html__('Text On Hover', 'shams'),
			'default' 	=> '#ffffff',
			'validate' 	=> 'color',
			'output'    => ['--button-hover-text-color' => ':root'],
		],
		[
			'id' 		=> 'button_section_end',
			'type' 		=> 'section',
			'indent' 	=> false,
		],

		[
			'id' 		=> 'search_drawer_section_start',
			'type' 		=> 'section',
			'title' 	=> esc_html__('Search Drawer', 'shams'),
			'indent' 	=> true,
		],
		[
			'id'		=> 'search_drawer_bg_color',
			'type' 		=> 'color',
			'transparent' => false,
			'title' 	=> esc_html__('Background', 'shams'),
			'default' 	=> '#ffe66b',
			'validate' 	=> 'color',
			'output'    => ['--search-drawer-bg-color' => ':root'],
		],
		[
			'id'		=> 'search_drawer_text_color',
			'type' 		=> 'color',
			'transparent' => false,
			'title' 	=> esc_html__('Text', 'shams'),
			'default' 	=> '#000000',
			'validate' 	=> 'color',
			'output'    => ['--search-drawer-text-color' => ':root'],
		],
		[
			'id' 		=> 'search_drawer_section_end',
			'type' 		=> 'section',
			'indent' 	=> false,
		],

		[
			'id' 		=> 'menu_drawer_section_start',
			'type' 		=> 'section',
			'title' 	=> esc_html__('Menu Drawer', 'shams'),
			'indent' 	=> true,
		],
		[
			'id'		=> 'menu_drawer_bg_color',
			'type' 		=> 'color',
			'transparent' => false,
			'title' 	=> esc_html__('Background', 'shams'),
			'default' 	=> '#ffe66b',
			'validate' 	=> 'color',
			'output'    => ['--menu-drawer-bg-color' => ':root'],
		],
		[
			'id'		=> 'menu_drawer_text_color',
			'type' 		=> 'color',
			'transparent' => false,
			'title' 	=> esc_html__('Text', 'shams'),
			'default' 	=> '#000000',
			'validate' 	=> 'color',
			'output'    => ['--menu-drawer-text-color' => ':root'],
		],
		[
			'id'		=> 'menu_drawer_subtext_color',
			'type' 		=> 'color',
			'transparent' => false,
			'title' 	=> esc_html__('Subtext', 'shams'),
			'default' 	=> '#575757',
			'validate' 	=> 'color',
			'output'    => ['--menu-drawer-subtext-color' => ':root'],
		],
		[
			'id'		=> 'menu_drawer_social_icons_color',
			'type' 		=> 'color',
			'transparent' => false,
			'title' 	=> esc_html__('Social Icons', 'shams'),
			'default' 	=> '#000000',
			'validate' 	=> 'color',
			'output'    => ['--menu-drawer-social-icons-color' => ':root'],
		],
		[
			'id'		=> 'menu_drawer_list_item_color',
			'type' 		=> 'color',
			'transparent' => false,
			'title' 	=> esc_html__('List Item Text', 'shams'),
			'default' 	=> '#000000',
			'validate' 	=> 'color',
			'output'    => ['--menu-drawer-list-item-color' => ':root'],
		],
		[
			'id'		=> 'menu_drawer_list_item_active_bg_color',
			'type' 		=> 'color',
			'transparent' => false,
			'title' 	=> esc_html__('List Item Active Background', 'shams'),
			'default' 	=> '#ffe66b',
			'validate' 	=> 'color',
			'output'    => ['--menu-drawer-list-item-active-bg-color' => ':root'],
		],
		[
			'id'		=> 'menu_drawer_list_item_active_text_color',
			'type' 		=> 'color',
			'transparent' => false,
			'title' 	=> esc_html__('List Item Active Text', 'shams'),
			'default' 	=> '#000000',
			'validate' 	=> 'color',
			'output'    => ['--menu-drawer-list-item-active-text-color' => ':root'],
		],
		[
			'id'		=> 'menu_drawer_list_item_hover_bg_color',
			'type' 		=> 'color',
			'transparent' => false,
			'title' 	=> esc_html__('List Item Background On Hover', 'shams'),
			'default' 	=> '#ffe66b',
			'validate' 	=> 'color',
			'output'    => ['--menu-drawer-list-item-hover-bg-color' => ':root'],
		],
		[
			'id'		=> 'menu_drawer_list_item_hover_text_color',
			'type' 		=> 'color',
			'transparent' => false,
			'title' 	=> esc_html__('List Item Text On Hover', 'shams'),
			'default' 	=> '#000000',
			'validate' 	=> 'color',
			'output'    => ['--menu-drawer-list-item-hover-text-color' => ':root'],
		],
		[
			'id' 		=> 'menu_drawer_section_end',
			'type' 		=> 'section',
			'indent' 	=> false,
		],

	]
]);

**Comment by melsaka** [comment]
The problem is that the customizer preview for some reason after taking your time changing colors and settings without pressing the publish button resets the global variable which in my case $shams_opt to the values before customization only in the iframe embeded preview but all values in the customizer menu itself remains the same. now i tried premium theme from themeforest built by another dev using the same version of redux and i noticed it has the same problem.

**Comment by melsaka** [comment]
in the video the default color values are all bright ones, this is why i'm changing colors to black and darker values and while i'm doing so the problem occurs the customizer embedded preview soddenly ignored all new black values and printed out the default bright values.

**Comment by kprovance** [comment]
I didn't ask you to add your own code; I asked you to use the demo mode. Currently, I cannot reproduce the issue. I can't fix what I can't break.

**Comment by melsaka** [comment]
> I didn't ask you to add your own code; I asked you to use the demo mode. Currently, I cannot reproduce the issue. I can't fix what I can't break.

nvm i will build my own framework, feel free to close this issue.

**Comment by melsaka** [comment]
For the people facing the same annoying problem, here is my workaround solution:

1. You MUST NOT USE THE `output` argument. Do it manually and enqueue your custom css code instead.

2. Write a custom function to get the theme options and use the get_theme_mod in customizer preview to avoid the error caused by global variable. here's an example.

`
// Note: $opt_name is the value you provided to the redux opt_name key of the $args array.

function example_options($option = null, $default = ''){
    global $opt_name;

    $options = is_customize_preview() ? get_theme_mod('opt_name') : $opt_name;

    if ($option) {
        return isset($options[$option]) ? $options[$option] : $default;
    }

    return $options;
}`

3. Enqueue your custom css code manually, for example:

let's imagine we have this field in redux:

`[
	'id'		=> 'bg_color',
	'type' 	=> 'color',
	'title' 	=> esc_html__('Background Color', 'example'),
	'default' 	=> '#ffe66b',
	'validate' 	=> 'color',
]`

Instead of using `output` argument you do this:

`
add_action( 'wp_enqueue_scripts', 'example_theme_assets');

function example_theme_assets()
{
    wp_enqueue_style('shams-custom', false);
}

add_action( 'wp_enqueue_scripts', 'example_custom_inline_css' );

function example_custom_inline_css()
{
    $options = example_options();
    $colors = [
        '--bg-color' => 'bg_color',
        // add more ..
    ];

    $customCss = ':root{';

    foreach ($colors as $var => $option) {
        $color = isset($options[$option]) ? $options[$option] : null;

        if ($color) {
            $customCss .= $var . ':' . $options[$option] . ';';
        }
    }

    $customCss .= '}';

    wp_add_inline_style( 'example-custom', $customCss );
}
`

Now you can use the css variable --bg-color in your css files and you won't face any problem.

4. When user click on Reset Section Or Reset All buttons the global variable values will be reseted to the default values but the get_theme_mod('opt_name') values are still the same and not reseted. so we will have to write this additional code:

`
add_filter('redux/validate/shams_opt/defaults', 'reset_customizer_values');

add_filter('redux/validate/shams_opt/defaults_section', 'reset_customizer_values');


function reset_customizer_values($defaults) 
{
  global $opt_name;

  $current_options = $opt_name;

  $current_options = array_merge($current_options, $defaults);

  set_theme_mod('opt_name', $current_options);

  update_option('opt_name', $current_options);
}
`

And that's it.
