### ISSUE TITLE
How to Combine plugin menu and submenu into one parent menu?

### ISSUE THREAD

**Issue by shyambaseapp** [reduxframework/redux-framework#4001]
I have developed two different plugins using the Redux framework, so the title and slug of the menu in both plugins are the same. When I activate both plugins at the same time, they will appear under a single menu with the same title and slug, including all submenus inside that menu.

**Comment by kprovance** [comment]
Redux cannot inherently do something like this. Each instance should have a unique slug and opt_name; otherwise, unpredictable behavior can occur.  I'm not even sure WordPress itself can have a submenu with its own submenu. Either way, Redux cannot do something such as this. Sorry.
