### ISSUE TITLE
It is recommended about Metaboxes

### ISSUE THREAD

**Issue by junyaopk** [reduxframework/redux-framework#4027]
It is recommended that the Metaboxes function stores data in 1 key-value pair (array) and only occupies one key value in the postmeta table to reduce space waste.
In addition, I used the redux_post_meta( "OPT_NAME", "POST_ID", "META_KEY" ) function but failed to obtain the data. I used get_post_meta to obtain it successfully.
The version in Metabox code is 4.2.0

**Comment by kprovance** [comment]
Thanks. We'll take it under advisement.
