### ISSUE TITLE
Bug Report : Repeater Add button not working

### ISSUE THREAD

**Issue by mafiayemakhfi** [reduxframework/redux-framework#4041]
## Site Health Report
Wordpress

Version | 6.7
-- | --
Site Language | en_US
User Language | en_US
Home URL | http://localhost
Is this site using HTTPS? | No
Is this a multisite? | No
Environment type | production
Communication with WordPress.org | Word

Redux
Version | 4.5.0
-- | --
Installation | plugin
Data directory | C:/xampp/htdocs/wp-content/plugins/redux-framework/redux-core/
Browser | Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:109.0) Gecko/20100101 Firefox/115.0Browser: FirefoxVersion: 115.0Platform: Windows

## Steps to reproduce
1. Install and activate the Redux Framework in a WordPress site.
2. Create a repeater field in the Redux framework options page.
3. Attempt to add a new item to the repeater field.

```php
$opt_name = 'test';

        // Define the args for Redux framework.
        $args = array(
			'opt_name' => $opt_name,
            'dev_mode' => true,
        );

        // Initialize Redux framework with the args.
        Redux::set_args( $opt_name, $args );

        // Define the fields for your settings page.
        Redux::set_section( $args['opt_name'], array(
            'title' => __( 'Repeater Example', 'redux-framework-demo' ),
            'desc'  => __( 'This is an example of a repeater field.', 'redux-framework-demo' ),
            'icon'  => 'el el-list-alt',
            'fields' => array(
                // Repeater field
                array(
                    'id'        => 'my_repeater_field', 
                    'type'      => 'repeater',
                    'title'     => __( 'My Repeater', 'redux-framework-demo' ),
                    'subtitle'  => __( 'Add, edit, or remove items from the list.', 'redux-framework-demo' ),
                    'fields'    => array(
                        // Individual fields inside each repeater item
                        array(
                            'id'        => 'repeater_text',
                            'type'      => 'text',
                            'title'     => __( 'Text Field', 'redux-framework-demo' ),
                            'subtitle'  => __( 'Add a simple text value', 'redux-framework-demo' ),
                            'default'   => '',
                        ),
                    )
                ),
            ),
        ) );
```

## Expected Behavior
The "Add" button should work and add a new row in the repeater field, allowing the user to input data in the fields.

## Actual Behavior
The "Add" button does not function, and no new rows are added to the repeater field. Upon checking the browser's developer console, the following error is shown:

## Any Error Details (PHP/JavaScript)

Here is the relevant JavaScript error from the browser console:
```javascript
Uncaught TypeError: window.tinyMCEPreInit is undefined
```

**Comment by kprovance** [comment]
This issue is already active and being worked on. Please follow it here: https://github.com/reduxframework/redux-framework/issues/4037
