### ISSUE TITLE
$version must be string problem with 4.5.4

### ISSUE THREAD

**Issue by Hoiss** [reduxframework/redux-framework#4048]
Just wanted to give you a short feedback about the latest version 4.5.4, because I get the error with it:
E_COMPILE_ERROR, line 18 of /redux-framework/redux-core/inc/extensions/search/class-redux-extension-search.php
`Type of Redux_Extension_Search::$version must be string (as in class Redux_Extension_Abstract)`

I downgraded to 4.5.2 and everything works again.

Kind regards

**Comment by kprovance** [comment]
It's fixed in the current beta. Check the repo. If not, stay with the old version. It'll be replaced eventually. However, please do NOT report bugs on the older version.
