### ISSUE TITLE
Still A little fuzzy how to integrate into theme.  

### ISSUE THREAD

**Issue by ghost** [reduxframework/redux-framework#412]
Hey all i know this is a simple issue so i feel a little stupid for asking but this is my first  wordpress options panel I have used. I have opted to include the framework in my theme my using the provided code. 

```
         <?php
if ( !class_exists( 'ReduxFramework' ) && file_exists( dirname( __FILE__ ) . '/ReduxFramework/ReduxCore/framework.php' ) ) {
    require_once( dirname( __FILE__ ) . '/ReduxFramework/ReduxCore/framework.php' );
}
if ( !isset( $redux_demo ) && file_exists( dirname( __FILE__ ) . '/ReduxFramework/sample/sample-config.php' ) ) {
    require_once( dirname( __FILE__ ) . '/ReduxFramework/sample/sample-config.php' );
}
// 
```

And it is showing up with the demo content.  How would I make use of a media selection option included in Redux say if I wanted to customize my header code to display a logo that I picked in redux? Normal logo code from my theme

```
                <a href="<?php echo home_url(); ?>" rel="nofollow"><img src="logo.png" alt="logo" /></a> 
```

Thanks for your input on so simple an issue.

**Comment by anilshah694** [comment]
Thanks you all for you're help. I now have everything working.
