### ISSUE TITLE
Translating config?

### ISSUE THREAD

**Issue by wpexplorer** [reduxframework/redux-framework#485]
I'm having issues getting translations to work for titles, descriptions, subtitles.

Example:

<pre>
array(
 'id'=>'custom_logo',
 'url'=> true,
 'type' => 'media', 
 'title' => __('Logo', 'wpex'),
 'default' => '',
 'subtitle' => __('Upload your custom site logo.', 'wpex'),
),
</pre>

So...both strings from the title and subtitle show up perfectly fine in my default.po file and I can translate them. However, it has no effect.

I've tried with the sample data as well and the only string translated is the ones that are in the core (such as the Import Export).

Anyone successfully gotten their custom config file settings translated?

Thanks!

**Comment by simopetrelli** [comment]
I have the same problem. Thanks for your help.

**Comment by simopetrelli** [comment]
I have the same problem. Thanks for your help.

**Comment by simopetrelli** [comment]
I have the same problem. Thanks for your help.

**Comment by simopetrelli** [comment]
I have the same problem. Thanks for your help.
