### ISSUE TITLE
How could I add a dependency field in options?

### ISSUE THREAD

**Issue by ponvendhan** [reduxframework/redux-framework#497]
How could I add a dependency field in options? like if I chose 'yes' in field, then another option would show under it.

**Comment by webselfsrl** [comment]
Hello,
'required' is great, but I would like to know if I can populate a select field using data from another field..

Ex. Select 1 has 3 IDs.. when I select the first ID the Select2 is populated using the Select1's ID...
(without save the page.. )

I see a similar feature for the Typography field, indeed when you select the Font, the weight dropdown is istantly updated (maybe ajax)..

I can also buy an extension if it exists..

Let me know,
Betsr Regards

**Comment by kprovance** [comment]
I replied to your email, and got this:

Questa è la Ricevuta di ritorno del messaggio inviato a assistenza@webself.it.

Nota: questa Ricevuta di ritorno attesta solamente che il messaggio è stato visualizzato nel computer del destinatario. Non c'è pertanto alcuna garanzia che il destinatario abbia letto o compreso il suo contenuto.

I don't know what that says.  Did you get my reply?
