### ISSUE TITLE
Editor field shortcodes

### ISSUE THREAD

**Issue by SirDarcanos** [reduxframework/redux-framework#525]
Am i supposed to create the shortcodes mentioned in the sample config?

I'm referring to [wp-url] [site-url] [theme-url] [login-url] [logout-url] [site-title] [site-tagline] [current-year].

I tested them in an editor field but they show like plain text.
Thank you!

**Comment by tanmoybiswas87** [comment]
Editor field shortcodes solutions 
<?php 
  $output = do_shortcode($redux_demo['opt-editor-text']);
  echo $output; 
 ?>
