### ISSUE TITLE
New Video Tutorials! Make Requests Now!

### ISSUE THREAD

**Issue by dovy** [reduxframework/redux-framework#574]
So I just posted our first video tutorial and I am more than willing to record various segments. Take a look here and give me your thoughts: http://reduxframework.com/video-tutorials/

Make requests for small video segments here!

**Comment by zealmurapa** [comment]
I am trying to export my menus with locations,
help with:

Primary (menu) Primary Menu (menu location)

anyone?

**Comment by kprovance** [comment]
@zealmurapa , see #2067.  Posting the same issue to other irrelevant threads won;t get you a different answer.

**Comment by kenshiwara** [comment]
Hello!

It would really be nice if you can prepare a video for the absolute beginners that teaches them how to use the online builder of Redux and how to initiate the admin folder properly inside their themes.

Thank you for creating such a great framework! The plugin of Redux is pretty amazing as well!

**Comment by kprovance** [comment]
You mean, basic PHP?  We keep saying, a working knowledge of PHP is required to use Redux.  A video isn't a bad idea, but every project is different, and one solution (say the one used in a video) might not work for all projects...then who has to deal with the 'it don't work' support requests?  I know it sounds critical, but folks who don't know or understand PHP have no business writing WP themes.

**Comment by winwinwebdesign** [comment]
How about instead of tutorials, you make videos of some of your advanced extensions in action?

**Comment by dovy** [comment]
Good call. We do have the extensions on the demo. You can try them out yourself. ;)

Http://demo.redux.io
