### ISSUE TITLE
get_wordpress_data and terms

### ISSUE THREAD

**Issue by pressoholics** [reduxframework/redux-framework#613]
Line refs are for framework.php

Found a small bug when adding a multi select field using terms. On line 567 when processing terms an extra dimension called 'args' is added to the methods $args array. This is for all get_terms() args.

The issues arises in lines 531 & 663 where an array to string conversion error occurs due to the array within an array of $args['args'] =  array(). 

If you remove the following from the terms section (line 573):

Remove:
if (empty($args['args'])) {
   $args['args'] = array();
}

Change:
$terms = get_terms($taxonomies, $args['args']);
TO
$terms = get_terms($taxonomies, $args);

And just make sure that all term args are added into the top level of the $args array (along with the 'taxonomies' arg string) all is well as the taxonomies element of the array is unset.

Hope this helps.

**Comment by slamorte** [comment]
The solution is to leave the `['args']` out of the framework.php, and use a different approach to defining your terms selector. Don't next the get_terms arguments in a second array; instead put them in the same array as the taxomomies argument: 

```
array(
          'title'  => ’Select Terms',
          'id' => ‘opt-terms-select,
          'type' => 'select',
          'data' => 'tags',
          'args' => array(
            'taxonomies' => 'post_tag',  // no second args! 
            'hide_empty' => 1,
            'orderby' => 'count',
            'order' => 'DESC',
          ),
          'multi' => true,
          'sortable' => true,
        ),
      )
    );
```
