### ISSUE TITLE
Problem with background field

### ISSUE THREAD

**Issue by prison47** [reduxframework/redux-framework#628]
Hello, thank you very much for this framework. I have a problem with background field. I try to set background color for footer, but default value not working.

'fields' => array(
                        array(
                            'id'=>'the-footer-background',
                            'type' => 'background',
                            'output' => array('#footer'),
                            'title' => __('Footer Background Color', 'redux-framework-demo'), 
                            'subtitle' => __('Pick a background color for the theme .', 'redux-framework-demo'),
                            'default' => '#323231',
                            'validate' => 'color'
                        )

and in the panel a have a warning: 
Warning: Invalid argument supplied for foreach() in Z:\home\localhost\www\wordpress\wp-content\themes\imp\admin\framework\ReduxCore\inc\fields\background\field_background.php on line 370

What I doing wrong?

**Comment by rozen-001** [comment]
How I use this code this code 

I already use this 
background-image: url("<?php global $options; echo $options['header-background']['background-image']; ?>");

on my funtions.php but it not working
