### ISSUE TITLE
Adding custom fonts to typography

### ISSUE THREAD

**Issue by isarmstrong** [reduxframework/redux-framework#642]
I'm so sorry if this has been answered before, I did a pretty specific search to check first.
(site:https://github.com/ReduxFramework/ReduxFramework/issues font -google)

I've got a project that uses a mix of custom and Google fonts. For the header font, I need to default to "American Captain" but also include other options. I can't seem to figure out how I add a custom font list to the existing ones! I'm sure it's as simple as calling an array, however, I have been unable to find the solution in a timely manner by reading the typography php class files.

Thanks as always for taking a moment to help out.

**Comment by b00rek** [comment]
@kprovance I apologize for asking this here, but after many, many hours of googling, I just couldn't find a solution. I have a theme that ships with Redux Framework inside. I'm using a child theme, where I customized some stuff. Now is it possible to make the above solution work from a child theme?

Overall I'm trying to disable any loading of Google Fonts and include just my own. Is this even the way proper way to do it? BTW, I would purcashe the Custom Fonts extension if that would help, but it has been discontinued apparently....

**Comment by jordan26** [comment]
@dovy - I've added my custom font as an option in the Redux Panel with:

`
'fonts'       => array(
  'Market Deco' => 'Market Deco'
)
`

However, this **replaces** all the standard fonts. How could I **add** my Market Deco font to the existing standard fonts?

**Comment by kprovance** [comment]
You are replacing the array, not appending to it, and why anything in it is now gone.  Basic PHP.
