### ISSUE TITLE
Hide/disable demo mode

### ISSUE THREAD

**Issue by Ninos** [reduxframework/redux-framework#681]
Following action hook doesn't work in themes:
`do_action( 'redux/plugin/hooks', $this );`

So I can't disable or hide the demo mode.

Also I think it would be better to add a hook in this way?

```
function redux_remove_demo_options($class) {
    if ( class_exists('ReduxFrameworkPlugin') )
        remove_filter( 'plugin_row_meta', array($class, 'plugin_meta_demo_mode_link'), null, 2 );

    if ( class_exists('ReduxFrameworkPlugin') )
        remove_action('admin_notices', array($class, 'admin_notices') );
}
add_action( 'redux/plugin/hooks', 'redux_remove_demo_options' );
```

**Comment by TukuTuru** [comment]
I can't remove the on page load changing advertisement to (on each reload) different REDUX stuff.
I use the embedded version.

Removing the Widget (top screen) works good, but in the black header on top of the Admin Panel, right side, a advertisement is still present.
any way to remove that?

**Comment by kprovance** [comment]
#2238
