### ISSUE TITLE
Custom tinymce button in wpeditor field

### ISSUE THREAD

**Issue by alvisir** [reduxframework/redux-framework#722]
Hi, I've created my own shortcodes plugin that it adds a tinymce button with which it shows a modal box. I notice that this button doesn't appear in the wpeditor field...Is it normal? 
It's extremely important that I can put my shortcodes in this field.

**Comment by alijange** [comment]
Hi @dovy : 'args' => array('teeny' => false)  is not working for me. It is not showing my shortcode button but if i reverse it like 'args' => array('teeny' => true) and also update core editor field code on line number 73 to  'teeny'  => false, then its working fine.  what's wrong with it ? thanks

**Comment by emorling** [comment]
@dovy @alvisir @alijange was this every fixed? I also updated from an earlier version of Redux and experience the custom tinymce button gone.

**Comment by emorling** [comment]
It sees that the filters 
mce_external_plugins
mce_buttons

are never being called and therefore the tinymce never being loaded. Works exactly like expected for posts and pages, so it's something to do with how tiny is loaded in Redux

**Comment by emorling** [comment]
There appears to be a bug in the field_editor.php function render()
The args passed are empty. So the teeny=>false never makes it there.

**Comment by emorling** [comment]
Re-open or new issue?

**Comment by kprovance** [comment]
This is (or was) supposed to be a community project.  My suggestion would be to dig into the code for yourself, then offer a pull request so the community might benefit.  If you plan on just waiting for one of us to donate yet more free time, the wait will amount to weeks, or months.

**Comment by alijange** [comment]
@emorling continue with your custom code 'args' => array('teeny' => true). I had pull request already for this change but unfortunately ignored by author.

**Comment by emorling** [comment]
Okay thanks @alijange
