### ISSUE TITLE
Question: Update Redux option from outside of Redux options page?

### ISSUE THREAD

**Issue by zth** [reduxframework/redux-framework#772]
Hey! Thanks for an amazing framework. Talk about cutting time it takes to do stuff!

Like the headline says, how do I update a Redux option from outside of Redux? Any way to do that? I'm looking to just make a basic option toggleable outside of the page. I'm not necessarily looking to output a Redux switch or similarily (although that would be cool), but rather just change an option somehow in my PHP.

Thanks again!

**Comment by ahmadmll** [comment]
Hi dear , in my wordpress theme have installed Redux Framework 3.6 and I located for  "new Redux_Framework_sample_config();" but there is not in whole of redux frame work. 
please help me....
