### ISSUE TITLE
Theme Check Plugin Issues Caused by Redux Framework

### ISSUE THREAD

**Issue by NickMcBurney** [reduxframework/redux-framework#797]
Hi,

Ive been using Theme-Check plugin along with the ThemeForest-Check to test my theme.

http://wordpress.org/plugins/theme-check/
http://wordpress.org/plugins/themeforest-check/

I have noticed that the errors I have left are caused by the Redux Framework.

Here is errors when checking with ThemeForest-Check enabled:
WARNING: Found ini_set in the file pot-ext-meta.php. Themes should not change server PHP settings.

Line 74: ini_set('display_errors', 1);

WARNING: Found ini_set in the file po.php. Themes should not change server PHP settings.

Line 14: ini_set('auto_detect_line_endings', 1);

WARNING: Found eval in the file not-gettexted.php. eval() is not allowed..

Line 111: eval('$current_string='.$text.';');

WARNING: Found eval in the file extract.php. eval() is not allowed..

Line 202: // we can use eval safely, because we are sure $text is just a string literal

Line 203: eval('$current_argument = '.$text.';' );

WARNING: .tx Hidden Files or Folders found.
RECOMMENDED: TEMPLATEPATH was found in the file sample-config.php. Use get_template_directory() instead.

Line 18: if ( defined('TEMPLATEPATH') && strpos( Redux_Helpers::cleanFilePath( **FILE** ), Redux_H

RECOMMENDED: TEMPLATEPATH was found in the file config.php. Use get_template_directory() instead.

Line 18: if ( defined('TEMPLATEPATH') && strpos( Redux_Helpers::cleanFilePath( **FILE** ), Redux_H

I also get loads more errors, many of which look like they are caused by Redux when I check just using the Theme-Check plugin.

has anyone come across this before? 
p.s Im using the latest master download from GitHub.

**Comment by huykon** [comment]
how to resolve the problem with add_theme_page() in theme? I have same problem

**Comment by Eiad** [comment]
> how to resolve the problem with add_theme_page() in theme? I have same problem

Apparently the authors can't resolve this silly issue for us.
