### ISSUE TITLE
Prevent WebFontConfig

### ISSUE THREAD

**Issue by wpexplorer** [reduxframework/redux-framework#838]
Testing out the latest update...awesome!

One thing I noticed though is now there is a WebFontConfig js function loading on the front-end:

<pre>
WebFontConfig = {
  google: {
    families: [<?php echo $typography->makeGoogleWebfontString( $this->typography )?>]
  }
};
(function() {
  var wf = document.createElement('script');
  wf.src = 'https://ajax.googleapis.com/ajax/libs/webfont/1.5.0/webfont.js';
  wf.type = 'text/javascript';
  wf.async = 'true';
  var s = document.getElementsByTagName('script')[0];
  s.parentNode.insertBefore(wf, s);
})();
</pre>

(located in framework.php)

I personally loop through fonts to call the appropriate stylesheets for Google Fonts because it seems to render much faster. I noticed also the js code causes a weird "flash" in chrome so when the site first loads the text looks really thin then it bolds up.

Anyway...whats the best way to prevent this code from loading on the front end?

Thanks!
AJ

**Comment by kprovance** [comment]
In the future, please do not piggy back old tickets.  Create your own with the required information.

Set the global argument `async_typography` to false.
