### ISSUE TITLE
Select field post_type ?

### ISSUE THREAD

**Issue by djevrek** [reduxframework/redux-framework#87]
How can i show custom post type in select field ?

```
array(
            'id'=>'select-posts',
            'type' => 'select',
            'data' => 'televizor',
            'title' => __('Prvi post u sidebaru', 'redux-framework'), 
            'desc' => __('Post koji ce se prikazivati na svim stranicama sa strane', 'redux-framework'),
        ),
```

this is not working, but my custom post type is "televizor".

If i put in "data" post or posts i got standard wordpress posts.

**Comment by aneesv** [comment]
@dovy I have large number of posts and when i give -1  the script exit at the select widget as it can't handle it , it works when i give a limit . is there any solution available like select2 ajax search  ?

**Comment by dovy** [comment]
Not yet. We're welcome to users contributing for that.  ;)   It would take some... effort.

**Comment by santoshmajhi** [comment]
Hi,
Can we get the custom post type list dynamically in Redux and how ?

**Comment by dovy** [comment]
Data argument as outlined in the docs. O

**Comment by santoshmajhi** [comment]
I don't get ur point, Can u please mention it in details.

**Comment by dovy** [comment]
Read our docs on the data argument. Please do not post here. It's an old thread. Open a new one of you need. 

Our sample config and docs all show how to get what you're asking for. Look around before you post again please.
