### ISSUE TITLE
Get options

### ISSUE THREAD

**Issue by ghost** [reduxframework/redux-framework#923]
I tried to get the redux framework options and to echo them, but after 2 hours of seach I really don't understand how to output them...

For example I set this fields in my options file : 

`array(
                        'id' => 'favicon',
                        'type' => 'media',
                        'url' => true,
                        'title' => __('Favicon', 'redux-framework-demo'),
                        'compiler' => 'true',
                        'desc' => __('Upload a 16x16px jpge, png or gif image.', 'redux-framework-demo'),
                        'subtitle' => __('Add a favicon logo to your website. <br> The favicon is displayed on the browser tab of your website.', 'redux-framework-demo'),
                        'default' => '',
                    ),`

And I want to ouptut this option.

What is the way to output it?

I know that I need to do something like this:

`<?php echo $options['favicon']?>`

But I didn't find in the document where and how I defined my $options name and where and how I output my option name id in my template page?

I didn't understand the global declaration, where to to it, why and how...

I know that I'm not really great in php, that the reason I choose to use this framework, but near every wiki links of redux framework are missing... (and my english are also not enough good to clearly understand the instructions...)

I hope that someone can help me...

By the way, to set the options in the admin panel, it's very very simple and it's saving time.

**Comment by hopper124** [comment]
Thanks very nice
