### ISSUE TITLE
I need to know how to add multi text field with multiple inputs fields

### ISSUE THREAD

**Issue by rabinassar** [reduxframework/redux-framework#925]
Hello,
at first i want to thank you for the great hassle free framework, keep up in you perfect work.

if it possible can you please explain how i can use the argument of multi text field to add more inputs in each field of the repeater for example:
 when i press on add more two input fields will appear on for the name and other one for the price etc.

waiting your kind reply,
have a nice weekend
best regards

**Comment by mdtaslimkhan** [comment]
Hello,
Thanks for nice framework, 
It is really nessery thing that can help us a lot for our development work. I really appreciate for this.
But there is a problem with "add more" fields. I think also It's need multiple fields.  If we use multiple text filed instead this "add more" feature. it is not looking good and very unproffessional work for a developer. I hope Redux develpore team will attention on this issue.
Best Regards,
Taslim

**Comment by kprovance** [comment]
Repeater field?  http://reduxframework.com/extension/repeater/

**Comment by dovy** [comment]
Yea, our group field has now been renamed to the repeater field. You can grab it immediately.
