### ISSUE TITLE
hints not working

### ISSUE THREAD

**Issue by CodeSymbol** [reduxframework/redux-framework#930]
Redux ver 3.1.8.21

hints are not working on sample-config.php. I didn't edit any code to make sure the problem isn't from side. Thanks

**Comment by TukuTuru** [comment]
above hint setup will never show a hint on the screen 

at least on my localhost I need to do:
Hints setup in setArguments function:

<code>
$args[hints] => array(
                    'icon'          => 'icon-question-sign',
                    'icon_position' => 'right',
                    'icon_color'    => 'lightgray',
                    'icon_size'     => 'normal',
                    'tip_style'     => array(
                        'color'         => 'light',
                        'shadow'        => true,
                        'rounded'       => false,
                        'style'         => '',
                    ),
                    'tip_position'  => array(
                        'my' => 'top left',
                        'at' => 'bottom right',
                    ),
                    'tip_effect'    => array(
                        'show'          => array(
                            'effect'        => 'slide',
                            'duration'      => '300',
                            'event'         => 'mouseover',
                        ),
                        'hide'      => array(
                            'effect'    => 'slide',
                            'duration'  => '300',
                            'event'     => 'click mouseleave',
                        ),
                    ),
                ),
</code>

BTW none of above settings, if changed, have any effect.

**Comment by kprovance** [comment]
Thank you for posting on the Redux Issue tracker. In order for us to begin debugging your issue, we need you to first generate a support URL. You can learn about how you generate that here: http://docs.reduxframework.com/core/generating-a-support-hash/

Please update this ticket with the support URL when you have it. Thank you.

**Comment by kprovance** [comment]
No, wait.  Please do not piggy back old ticket.  Please open a new one using the support URL  

http://docs.reduxframework.com/core/generating-a-support-hash/
