### ISSUE TITLE
Dynamically add options section with AJAX

### ISSUE THREAD

**Issue by rubenkuipers** [reduxframework/redux-framework#958]
Hello!

Is it possible to dynamically add a options section with AJAX? I have a Ajax callback function in my functions.php, and I'd like to use that function to add a section to the options panel with the following hook:
`add_filter('redux/options/'.OPTION NAME.'/sections', array($this, 'dynamic_section'));`

**Comment by liquida** [comment]
hello kuiperr, have you found a way to do it?

regards

**Comment by kuiperr005** [comment]
Hi Liquida,

I have not found a way to do it yet. I have not been working much on the redux related project.

regards

**Comment by liquida** [comment]
ok thanks for time!
