### ISSUE TITLE
Multiple Conditionals for "required" field.

### ISSUE THREAD

**Issue by wpexplorer** [reduxframework/redux-framework#961]
Would it be possible?

Ex:

<pre>
'required'  => array(
  'sample_id' => array ( 'equals', '1' ).
  'sample_id_2' => array ( 'equals', '1' ).
),
</pre>

or..

<pre>
'required'  => array(
  'relation' => 'AND',
  array( 'sample_ID', 'equals', array('1') ),
  array( 'sample_ID2', 'equals', array('1') )
),
</pre>

Or too much?

**Comment by SenikaIndo** [comment]
This perfect Thanks wpexplorer
