### ISSUE TITLE
Themes should use add_theme_page() for adding admin pages.

### ISSUE THREAD

**Issue by talentedaamer** [reduxframework/redux-framework#970]
theme check plugin requires the use of add_theme_page() for adding admin pages in three files import_export.php, framework.php & debug.php

**Comment by futr3** [comment]
Is there any update on using Redux for wordpress.org, is it accepted now?  For the time being I have commented out those lines as I saw one of your dev's mention on another thread.  Theme check runs fine without them and all theme options seem to be working fine on the current install. Any news on this?

**Comment by azexo** [comment]
as i know last months ThemeForest reviewers start to rejecting redux REQUIRED alerts.
here screenshot from ThemeForest reviewer with rejection reason:
http://envato.d.pr/B4pT/JKLdv4ny
