### ISSUE TITLE
Background Color Hover

### ISSUE THREAD

**Issue by cybentizen** [reduxframework/redux-framework#983]
Hi!

Is there any option that I could use background color hover? Like this framework has link_color but this is only used for css color filed but we can't use it for background-color or background css property.

Regards

**Comment by futr3** [comment]
yes, i love you guys.  You make this so easy

**Comment by dovy** [comment]
If you're happy with Redux, please doing some or all of the following.
* Like us on Facebook https://www.facebook.com/ReduxFramework/
* Follow us on Twitter https://twitter.com/reduxframework
* Review us on WordPress.org https://wordpress.org/support/view/plugin-reviews/redux-framework?filter=5
* Grab an extension (or two) to keep the project running. https://reduxframework.com/extensions/
